### ISSUE TITLE
NPC: Theramore Guard

### ISSUE THREAD

**Issue by Scrazle** [dalaranwow/dalaran-wow#100]
- There is a problem with the guards at Theramore Isle. They don't stop chasing me and they don't hit me. They just follow forever. Maybe the issue is only with me, but I doubt it.

http://wotlk.openwow.com/npc=4979

**Comment by Rushor** [comment]
updateai is missing (but i think it was already replaced by sai)

**Comment by Rushor** [comment]
https://github.com/TrinityCore/TrinityCore/blob/a56a402190c885e51038df55654875cc9e875c03/sql/old/4.3.4/TDB5_to_TDB6_updates/world/138_2014_06_23_10_world_misc.sql

script was already converted to sai, fixed two years ago
