### ISSUE TITLE
Quest: Take Down Tethyr!

### ISSUE THREAD

**Issue by highness** [dalaranwow/dalaran-wow#1007]
Currently it's on autocomplete.

Now, let's look at how the script should work, step-by-step.

Upon accepting the quest, the sky should darken, the lighthouse turns on and it starts to rain. Three mortars on the dock become 'sparkly'.

Major Mills (http://www.wowhead.com/npc=23905) should yell: 

"Marksmen, form up and take your positions!"

12 Theramore Marksmen (http://www.wowhead.com/npc=23900) spawn and run to their positions around the dock, spreading evenly (1 marksman for ~15 yards or so). They have 3,810 health, 1,283 mana and Shoot ability (http://www.wowhead.com/spell=42580) which hits for 24 to 29. Marksmen count (12\12) appears at the top of the screen, and if every Marksman dies, the quest is failed.

After 10 seconds or so, Tethyr (http://www.wowhead.com/npc=23899) swims in. He has 152k health and Water Bolt ability (http://www.wowhead.com/spell=42574) which hits for 350 to 450 frost damage. Also, there is some cone-like water-based ability which did knockback and currently isn't listed on wowhead. If player is knocked away from harbor while the quest is on, it fails.

Tethyr takes a round around the harbor, then Major Mills yells:

"Prepare to fire upon my command! Ready, aim..."
"FIRE AT WILL!"

Then Marksmen start shooting at Tethyr, so he aggroes at them.

Player character then can use any mortar (they become 'active'), which will automatically target and hit Tethyr for ~15k with each hit. Not sure what the exact spell it uses though.

When Tethyr dies, player should get a quest credit, and Theramore Marksman yells: 

"We did it! We defeated Tethyr!"

or\and

"We defeated the sea monster!"

Some fireworks then blow up around the harbor for a minute or so. Lighthouse goes off, weather turns to whatever it was before the event started.

Here's the video that has it all: http://www.youtube.com/watch?v=vSd2RgWqPBg

Good luck scripting it :o

**Comment by meowmewo** [comment]
Still the same.STILL

**Comment by n-ghost** [comment]
Scripted flawlessly atm <3

**Comment by Rushor** [comment]
closing pls :)

**Comment by BlazeRavenHeart** [comment]
I can comfirm that this quest is bugged again. With Tethyr getting stuck at the far end of the Harbor and you can only get one cannon to work on him to kill him and your not near major mills for completetion.

This is how to suppose to work.
Upon accepting the quest, the sky should darken, the lighthouse turns on and it starts to rain. Three mortars on the dock become 'sparkly'.

Major Mills (http://www.wowhead.com/npc=23905) should yell:

"Marksmen, form up and take your positions!"

12 Theramore Marksmen (http://www.wowhead.com/npc=23900) spawn and run to their positions around the dock, spreading evenly (1 marksman for ~15 yards or so). They have 3,810 health, 1,283 mana and Shoot ability (http://www.wowhead.com/spell=42580) which hits for 24 to 29. Marksmen count (12\12) appears at the top of the screen, and if every Marksman dies, the quest is failed.

After 10 seconds or so, Tethyr (http://www.wowhead.com/npc=23899) swims in. He has 152k health and Water Bolt ability (http://www.wowhead.com/spell=42574) which hits for 350 to 450 frost damage. Also, there is some cone-like water-based ability which did knockback and currently isn't listed on wowhead. If player is knocked away from harbor while the quest is on, it fails.

Tethyr takes a round around the harbor, then Major Mills yells:

"Prepare to fire upon my command! Ready, aim..."
"FIRE AT WILL!"

Then Marksmen start shooting at Tethyr, so he aggroes at them.

Player character then can use any mortar (they become 'active'), which will automatically target and hit Tethyr for ~15k with each hit. Not sure what the exact spell it uses though.

When Tethyr dies, player should get a quest credit, and Theramore Marksman yells:

"We did it! We defeated Tethyr!"

or\and

"We defeated the sea monster!"

Some fireworks then blow up around the harbor for a minute or so. Lighthouse goes off, weather turns to whatever it was before the event started.

Here's the video that has it all: http://www.youtube.com/watch?v=vSd2RgWqPBg

**Comment by Rushor** [comment]
inactive gridcell causes this issue

**Comment by Rushor** [comment]
https://github.com/TrinityCore/TrinityCore/commit/aebf5a172a9e11ddae24282154f32fdc189a50c0

already merged
