### ISSUE TITLE
Talent: Decimation

### ISSUE THREAD

**Issue by Jazex** [dalaranwow/dalaran-wow#1011]
Decimation
Rank 2/2
'When you Shadowbolt, Incinerate or Soul Fire a target that is at or below 35% health, the cast time of your Soul Fire spell is reduced by 40% for 10 sec. Soul Fires cast under the effect of Decimation cost no shard.'

If you have the 'Decimation' proc (it's a buff), but it is at low duration (for instance, the last second) and you start casting the Soul Fire it will be a fast cast (as it is supposed to be) but if the decimation proc has faded when your casting of Soul Fire is finished (when you actually release the bolt of fire) a Soul Shard is still deducted.

How it should work: If you cast a soul fire under the effect of decimation, it should never cost a Soul Shard, even when the decimation buff has faded upon release of the Soul Fire bolt.

**Comment by Rathyan** [comment]
Taken from the 3.3 Compendium on Elitist Jerks:
"Something to keep an eye on is that if decimation expires while you're casting Soul Fire, the soulfire *will* consume a Soul Shard. It's okay if this happens once, but if it happens a lot its going to cost you a lot of soulshards in a talent spec that requires 1 soulshard for every wipe already anyway."

So its not bugged.

**Comment by npmusicftw** [comment]
"Soul Fires cast under the effect of Decimation cost no shard."

Still under the effect of Decimation, even if the completion of the cast was after the fading of Decimation.

I don't remember if it's supposed to be like that though.
