### ISSUE TITLE
[NPC] Scarlet Magician - Missing spellcasts

### ISSUE THREAD

**Issue by highness** [dalaranwow/dalaran-wow#1016]
http://www.wowhead.com/npc=4282

Mob should have an ability, Fireball (http://www.wowhead.com/spell=9053), which he must use against player character.

Currently mob just melees.

**Comment by Rushor** [comment]
DB/Creature: Add SAI for several creatures in tirisfal

* source wowhead and openwow
* commit: a9203cd600f52899b79067da96f7c678aab12c4d

**Comment by TeridanDW** [comment]
Feedback for this creature, since it's casting means this commit is on ptr.
This npc sometimes behaive strange in combat as it continues it's random movement (while it's in combat).

**Comment by Rushor** [comment]
SAI added/modified for those creatures:

-- Scarlet Disciple
-- Scarlet Sentry
-- Scarlet Magician
-- Hungering Dead SAI
-- Scarlet Scout
-- Scarlet Preserver
-- Sri'skulk
-- Fellicent's Shade
-- Wandering Spirit
-- Bleeding Horror
-- Scarlet Bodyguard
-- Captain Melrache
-- Captain Vachon
-- Captain Perrine
-- Scarlet Neophyte
-- Scarlet Vanguard
-- Scarlet Friar
-- Scarlet Zealot
-- Scarlet Missionary
-- Muad
-- Vile Fin Minor Oracle
-- Vile Fin Muckdweller
-- Vile Fin Puddlejumper
-- Bayne
-- Cracked Skull Soldier
-- Darkeye Bonecaster
-- Rotting Ancestor
-- Wailing Ancestor
-- Maggot Eye
-- Rot Hide Graverobber
-- Rot Hide Mongrel
-- Rot Hide Gnoll
-- Lost Soul
-- Ravaged Corpse
-- Tormented Spirit SAI
-- Rotting Dead
-- Ressan the Needler
-- Vampiric Duskbat
-- Greater Duskbat
-- Farmer Solliden
-- Tirisfal Farmhand
-- Shambling Horror SAI
-- Tirisfal Farmer
-- Scarlet Warrior
-- Night Web Matriarch
-- Young Scavenger

The creatures should also no longer walk random while casting/attacking.
