### ISSUE TITLE
Misplaced text: Harthal Truesight

### ISSUE THREAD

**Issue by highness** [dalaranwow/dalaran-wow#1019]
There's a set of plaques in SM: Armory, each dedicated to some of the Crusade's heroes. 

A plaque under Harthal Truesight's statue should say this:

"Harthal Truesight
Lord Paladin of the Scarlet Crusade
Citizen of Azeroth - Knight of the Silver Hand
Last seen entering the cursed city of Stratholme"

Currently the text is misplaced and says this instead:

![wowscrnshot_121113_111309](https://f.cloud.github.com/assets/5235996/1722522/abdc9da8-6244-11e3-9677-9f6c93156db0.jpg)

Object id: http://www.wowhead.com/object=210489

The plaque of Fellari Swiftarrow, which has it's text duplicated here, is fine.

**Comment by Rushor** [comment]
i fixed it already in https://github.com/dalaranwow/dalaran-wow/issues/898 /closing
