### ISSUE TITLE
Quest: Battle of Hillsbrad (Part 7)

### ISSUE THREAD

**Issue by Crispybuilt** [dalaranwow/dalaran-wow#102]
Quest Battle of Hillsbrad - 14351

Issue: The NPC will simply not offer you the last part of this chain quest after you complete the previous quest which is: http://wotlk.openwow.com/quest=541

Entire chain quest can be found here: http://wotlk.openwow.com/quest=14351

NPC who has to give you the chain quest is: High Executor Darthalia - 2215

**Comment by n-ghost** [comment]
Still an issue.

**Comment by Winstrol** [comment]
tried doing the quest line, still does not offer the quest.
