### ISSUE TITLE
Shaman-Stoneclaw-Glyph

### ISSUE THREAD

**Issue by dammtoni** [dalaranwow/dalaran-wow#1020]
Some of the glyph doesnt have the % increasing effect or neither absorbing. Theres is some who shoud not abble to dispell but they are dispellable. i need to ask especially to check Stoneclaw totem doesnt absorb as much as is shoud , cause effect breaks up after 3000-4500 damage as i know the the minimum benefit from resilience is 7800 and near 9800 on 1000 resillience

**Comment by Golganeth** [comment]
As mentioned above this works fine, so closing up.
