### ISSUE TITLE
Dungeons: Uldaman, Archaedas gauntlet event problems.

### ISSUE THREAD

**Issue by highness** [dalaranwow/dalaran-wow#1036]
Encounter works better than on the other servers overall, but there are still some problems to deal with yet. 

1) adds along the sides of the room which he 'awakes' during the encounter just stand there and do nothing unless aggroed.

You can see some here on both sides:

![wowscrnshot_121413_130848](https://f.cloud.github.com/assets/5235996/1748334/12ac6632-64b4-11e3-8929-1d3465915aed.jpg)

Here's the video from retail, http://www.youtube.com/watch?v=ZBFm5MTPSmk at 0:55 you can clearly see that adds are supposed to run to the center of the room and aggro players.

Add ID: http://www.wowhead.com/npc=7309

2) At the second phase ('Awake ye servants, defend the disks') nothing happens (you can see how it should happen at 2:35 in video), i.e. he won't revive http://www.wowhead.com/npc=7076, statues that are closer to the middle of the room.

3) Phase 3 transfer (which is indicated by 'Arise brothers, for the Makers') won't happen as well, he should revive 2 golems, Vault Warders (http://www.wowhead.com/npc=10120) at this point.

http://www.wowwiki.com/Archaedas has a detailed description of the encounter.

Other than that, it works fine.

Cheers.

**Comment by Demlock** [comment]
Confirmed

**Comment by n-ghost** [comment]
Currently the event works flawlessly (and I mean it), but afterwards, probably due to the recent pathing overhaul, you will find Lore Keeper's of Norgannon legs being devoured by it's pedestal :'(

![wowscrnshot_072515_012633](https://cloud.githubusercontent.com/assets/8515510/8885974/381bb1d8-326d-11e5-87bd-38d0fce1675f.jpg)

**Comment by Rushor** [comment]
all issues here are already solved on live?

**Comment by Rushor** [comment]
works everything fine on PTR.

On every phase transition different adds will be revivived and they attack the player. also the keeper stands on his gameobject

![GitHub Logo](http://i.imgur.com/yKxImsj.jpg)
![GitHub Logo](http://i.imgur.com/efQEpBk.jpg)
![GitHub Logo](http://i.imgur.com/ae8FAL5.jpg)
![GitHub Logo](http://i.imgur.com/1u85rbg.jpg)

related issues from TC:

Scripts/Uldaman: Instance update

- Fixup Boss Ironaya
- Add the freeze animation for minions and archaedas
- Fix attack target for minions who wake up

* commit: 9cb4cb52d842d3611e3053c9bd46e1925283d14e

Scripts/Uldaman: Fix build & fix some movement suggested by josch

* commit: cf286ea9cdba3e9019eb6bc4816034070f6480be
