### ISSUE TITLE
Ahn'Kahet: The Old Kingdom

### ISSUE THREAD

**Issue by loresome** [dalaranwow/dalaran-wow#1037]
1st boss, Elder Nadox, he doesn't become immune to dmg but instead him and his adds become immune to taunts and the whole thing goes haywire.

2nd boss, Prince Taldaram. He should spawn 3 flame spheres which go into different directions, yet it seems that they go the same way and they basicly do insane amount of damage. Furthermore embrace of the vampyr becomes active while the flame spheres are as well making the fight neigh impossible. Not to mention that damage

We didn't manage to check the rest of the bosses out and this is on normal mode in rdf

**Comment by Rushor** [comment]
As @Lothloryen already announced there should be a new script for this encounter since 2014.

Please list the remaining issues in a new seperated issue (https://github.com/dalaranwow/dalaran-wow/issues/new) with details on "how it is" and "how it should be" to keep the overvriwe. Thank you!
