### ISSUE TITLE
Item: Anti-venom

### ISSUE THREAD

**Issue by rotterz** [dalaranwow/dalaran-wow#104]
i have been leveling first aid and noticed when using anti venom on myself its not removing poison

**Comment by Uthil** [comment]
Confirmed again, [Anti-Venom](http://wotlk.openwow.com/item=6452) isn't removing venom, heres a screen shot from ingame that shows anti-venom on CD and still poison on. 

<div style="width:480px;text-align:right;"><embed width="480" height="360" src="http://pic2.pbsrc.com/flash/rss_slideshow.swf" flashvars="rssFeed=http%3A%2F%2Ffeed42.photobucket.com%2Falbums%2Fe328%2FAloucard79%2FWoW%2520General%2Ffeed.rss" type="application/x-shockwave-flash" wmode="transparent" /><a href="javascript:void(0);" target="_blank"><img src="http://pic.photobucket.com/share/icons/embed/btn_geturs.gif" style="border:none;" /></a><a href="http://s42.photobucket.com/user/Aloucard79/library/WoW%20General" target="_blank"><img src="http://pic.photobucket.com/share/icons/embed/btn_viewall.gif" style="border:none;" alt="Aloucard79&#039;s WoW General album on Photobucket" /></a></div>

**Comment by belegija** [comment]
confirmed. strong anti-venom not working

**Comment by Alavarin** [comment]
Confirmed, anti-venom doesn't work.

**Comment by Rushor** [comment]
http://de.wowhead.com/item=6452#comments:id=801580

> Von devilez (385 – 4·21) am 2009.08.06 (Patch 3.2.0)    
>These seem to be bugged in 3.2, so far I've used about 10 of them and not a single one could >remove any poisons

>EwokAssassin am 2009.08.08 (Patch 3.2.0)
>Yeah, I'm having the same problem, trying to get rid of Touch of Zanzil, which originally could of been >removed using this, but now its not working..

>makisk am 2009.09.11 (Patch 3.2.0)
>Definitely bugged after 3.2 //www.wowhead.com/?item=6452 is a must when fighting hunters at the >10-19 pvp bracket as a twink and the problem is that it has stopped working... It no longer removes >//www.wowhead.com/?spell=13550 as it used to, thus making 1 vs. 1 against hunters even more >difficult than it was before Hope it will be fixed soon

Blizzlike issue during wotlk - if you find a proof, that this item was working during 3.3.5, we will fix it and reopen the issue
