### ISSUE TITLE
Quest: One Shot. One Kill. [5713]

### ISSUE THREAD

**Issue by Golganeth** [dalaranwow/dalaran-wow#1049]
- **Issue:** Once you pick up the quest, absolutely nothing happens.

- **How it should work:** Once you pick up the quest, you are supposed to protect Aynasha till she applies the antidote.
Once the quest has been picked up, a pair of waves with Blackwood trackers will approach (Firstly one of 2 mobs, followed by one of 3). These waves are followed by Marosh the Devious, the final boss.
As soon as the boss dies (and if the NPC is still alive) credit shall be given.

- *~ Sentinel Aynasha* - 11711
*~ Blackwood Tracker* - 11713
*~ Marosh the Devious* - 11714

- **Video of how it should work:** http://www.youtube.com/watch?v=VCr5MZaODZo

-------------------------

- *A scripted event starts upon accepting the quest:*

**Sentinel Aynasha says:** Wait... did you hear that? Something approaches from the west!
*Furbolgs approach, Aynasha starts shooting.*
**Sentinel Aynasha says:** I've run out of arrows! I'm afraid if any more come you will need to take them on by yourself my friend.
*When all the furbolgs are dead (and assuming Aynasha lives):*
**Sentinel Aynasha says:** My leg feels much better now, the remedy must be working. If you will excuse me, I must go report to my superiors about what has transpired here.
**Sentinel Aynasha says:** Please speak with sentinel Onaeya at Maestra's Post in Ashenvale, she will see to it that you are properly rewarded for your bravery this day.

----------------------
http://wotlk.openwow.com/quest=5713
http://wotlk.openwow.com/npc=11711
http://wotlk.openwow.com/npc=11713
http://wotlk.openwow.com/npc=11714

**Comment by glitterlance** [comment]
Quest still appears to be bugged.

**Comment by Stihii** [comment]
I can confirm that the bug still reproduces (05 June 2016).
Any news of a fix, please?

**Comment by Rushor** [comment]
yes fixed soon

**Comment by Stihii** [comment]
Thanks a lot, looking forward to completing the quest :)

**Comment by Rushor** [comment]
e17b2172655fb393ae1db344147bb2492709ff00
- event and texts added. only available on ptr

**Comment by Stihii** [comment]
Any idea when the fix will be propagated to Algalon so I can test it as well?

**Comment by Lothloryen** [comment]
Hello there,

In 2 days as much if everything goes fine on the PTR, it needs to be tested first, the next maintenance will not contain this quest.

**Comment by Stihii** [comment]
Hi, thanks for the answer. I will come back with a final confirmation once I see the fix in place.

**Comment by Golganeth** [comment]
Quest credit message is shown twice at the end, rest works great.

**Comment by Rushor** [comment]
not related to this script - fix for this was applied 5 days ago on tc https://github.com/TrinityCore/TrinityCore/commit/9480a210f24a1ebe006b065d7972512882cf3c5a

**Comment by Stihii** [comment]
I can confirm the fix on Algalon. Works perfectly, thanks!
