### ISSUE TITLE
[Storm Peaks] Quest: Expression of Gratitude

### ISSUE THREAD

**Issue by Rathyan** [dalaranwow/dalaran-wow#1056]
Quest's name: Expression of Gratitude

Wowhead's link: http://www.wowhead.com/quest=12836

Wowhead's Quest giver link: http://www.wowhead.com/npc=29428

What's broken: The quest is not present to pick up from the NPC

How it should work: The quest should be present without any pre-quests to unlock it

**Comment by moljac89** [comment]
did all quests in K3 and this one didnt show up, bumperino, cant do others in chain.

**Comment by Golganeth** [comment]
#3048

**Comment by Lothloryen** [comment]
Corrected already.
