### ISSUE TITLE
[Warrior] Bladestorm/Whirlwind

### ISSUE THREAD

**Issue by Rathyan** [dalaranwow/dalaran-wow#1063]
Talent link: http://wotlk.openwow.com/spell=46924

What's wrong: Bladestorm's damage is weird. First off, it hits twice with just one weapon equipped: the first hit for 100% weapon damage and the second for 20% weapon damage

How it should work: Bladestorm should deal 150% of weapon's damage every second for 6 seconds.

The same bug is for Whirlwind too, only whilrwind does more damage. Whirlwind is supposed to do 100% (+20% with the Improved Whirlwind talent and +10% with Unending Fury) weapon damage with each of the weapons. On DalaranWoW with one weapon equipped does 100% (130% with the talents) weapon damage plus another 20%

Source: (http://wowpedia.org/Bladestorm)  If you check the patch notes, in the 401, Bladestorm was dealing 100% damage due to a bug instead of 150% as it always was so it was changed back. Can't find any wotlk reference to the damage value though

**Comment by Vaxsysl** [comment]
Atm, when you do whirlwind, you deal damage with your weapon you have in your main hand (be it two hander or not), and if the offhand is free, you will punch (well, slap) the target with your fist.

**Comment by Vaxsysl** [comment]
There is a new bug with Bladestorm and fear that I just got in arena this instant. I activated Bladestorm just as enemy priest used fear, and the result was me being able to move, but not use any abilities for the full duration; and my bladestorm didn't do any damage either. 

I'll try to replicate it on some other date via skirmish.

**Comment by Rushor** [comment]
This was fixed with 

https://github.com/TrinityCore/TrinityCore/commit/a77c94eb3752c37f9c4ac3a641288cfe5898454d
https://github.com/TrinityCore/TrinityCore/commit/85143f305dd6b82e35639fe026f5f8613a1b96c4

The fix for it will be applied on the live realm with further merges. Thanks

**Comment by Aridam** [comment]
I'm confirming this bug as still-present: Striking twice with Whirlwind at the moment -- once with the Two-Handed Weapon, but _also_ a second time alongside that, with my fist (which can Crit as well); supposed to attack only once if using one Weapon, twice if using one in each hand, rather than have a free second attack with your other empty hand for about a fifth of the Main Hand's Damage.

**Comment by Aridam** [comment]
Any progress on this? WW and BS _both_ are _still_ hitting with the empty OH, which inherits the current SS charges bug and stucking Recklessness in its current state as well -- not a good combo as a whole.

**Comment by Aridam** [comment]
Reconfirming this as still bugged -- Whirlwind/Bladestorm still land with the Off-Hand when there's no actual Off-Hand equipped in the Item Slot there.

Furthermore it's expending as many Sweeping Strikes charges as the amount of hits it lands -- it's supposed to be one Sweeping Strikes charge expended per Whirlwind _use_.

**Comment by Aridam** [comment]
WW and BS both still hitting with the Off-Hand even if there isn't an Off-Hand Weapon equipped -- SS charges expended by WW are also still per hit and not per usage (1 with 1 Weapon, 2 with 2 Weapons).

**Comment by Aridam** [comment]
WW and BS still hitting with empty OH.

**Comment by Aridam** [comment]
Both still hitting with empty Off-Hand -- I am not a fan of fisting while fidgetspinning.

**Comment by Aridam** [comment]
Bump.

https://www.youtube.com/watch?v=hTwEItDr_qY

No updates to this report for a long time.
