### ISSUE TITLE
[Warrior] Charge, Intercept and Intervene

### ISSUE THREAD

**Issue by Rathyan** [dalaranwow/dalaran-wow#1064]
Ability link: http://wotlk.openwow.com/spell=100 ; http://wotlk.openwow.com/spell=30151 ; http://wotlk.openwow.com/spell=3411

What's wrong: Charge, Intervene and Intercept are all usable at the same moment

How it should work: While charging/intercepting/intervening a mob or a player, you shouldn't be able to use the other two

How to reproduce: Spec into "Warbringer" in the protection tree, get a friend into a party near you, use this macro on a mob

/cast charge
/cast intercept
/cast [@party1] intervene

You'll charge, intercept and intervene at the same time

**Comment by robinsch** [comment]
On PTR.
