### ISSUE TITLE
[Warrior] Talent: Titan's Grip

### ISSUE THREAD

**Issue by Rathyan** [dalaranwow/dalaran-wow#1065]
Talent's link: http://wotlk.openwow.com/spell=49152

What's wrong: Titan's grip is not applying the 10% damage reduction

How it should work: When equipping a two handed sword, axe or a mace, no matter if a single or dual wielding, there should be a 10% damage reduction

How to reproduce: Talent up until Titan's, learning all the talents but not Titan's grip, equip a two handed sword, mace or an axe, check your damage, learn Titan's Grip, check the weapon's damage again, won't change no matter if you remove and re-equip the weapon again.

**Comment by Prljoman** [comment]
Is this still an issue? Was it repaired with the patch?

**Comment by Vaxsysl** [comment]
People have opened new topic at #2639  so it is still a problem.

**Comment by PolarCookie** [comment]
still bugged

**Comment by Crispybuilt** [comment]
Can confirm as well

**Comment by robinsch** [comment]
On PTR

**Comment by plznoz** [comment]
This should be reopened. Look at strobe-light's comment on #4365 
Bop breaks the 10% penalty.

**Comment by VeilaMidn** [comment]
Still bugged when bopping warriors

**Comment by Rushor** [comment]
It was fixed with https://github.com/dalaranwow/dalaran-wow/issues/4365#issuecomment-280107800 and the fix will be apllied from PTR to the Live Realm in the future.

**Comment by robinsch** [comment]
> in the future.

**Comment by hrtyv** [comment]
add this the the upcomming fixes please, alot of people are taking advantage of it.
