### ISSUE TITLE
[Icecrown] Quest: Honor Above All Else

### ISSUE THREAD

**Issue by Rathyan** [dalaranwow/dalaran-wow#1071]
Quest link: http://www.wowhead.com/quest=13036

Quest giver: http://www.wowhead.com/npc=28179

What's wrong: The quest is available to take before completing the previous one in the chain (Judgement Day Comes! http://www.wowhead.com/quest=13226). If the player continues with the chain without completing the first one, at one point he/she'll get phased out and can't complete the first one at all 

How it should work: The quest shouldn't be available to take before completing http://www.wowhead.com/quest=13226

Chain tree here: http://www.wowhead.com/quest=13036#comments:id=657339

**Comment by Lothloryen** [comment]
Conditions working already.
