### ISSUE TITLE
Zone: Jintha'kalar

### ISSUE THREAD

**Issue by Golganeth** [dalaranwow/dalaran-wow#1074]
**Issue:** Jintha'kalar doesn't have any mobs on the following area:

![asdasdads](https://f.cloud.github.com/assets/5057942/1815378/f1c1ee02-6f16-11e3-9923-e7c8790eb2f3.png) - (*Only* **Overseer Deathgaze** *can be found*)

- **Related quest**: *The Cleansing Of Jintha'kalar (ID: 12545).* Even though a player can successfully complete it, because the southern area (at the other side of the stairs) has few creatures.

---------------------

The marked area needs:
- **Decrepit Necromancer** - *26942*
- **Battered Drakkari Berserker** - *26943*
- **Reanimated Drakkari Tribesman** - *26946*
- **Hulking Atrocity** - *26948*

----------------------

http://wotlk.openwow.com/quest=12545
http://wotlk.openwow.com/npc=26942
http://wotlk.openwow.com/npc=26943
http://wotlk.openwow.com/npc=26946
http://wotlk.openwow.com/npc=26948

**Comment by NovaHiros** [comment]
Overseer Deathgaze doesn't spawn actually (at least, not in in hour or so...)

**Comment by alphaest** [comment]
Can confirm, Deathgaze is not there, checked 5 times in 3 hours.

**Comment by Golganeth** [comment]
Confirmed. **[Overseer Deathgaze](http://wotlk.openwow.com/npc=27122)** seems to be missing in-game currently.

**Comment by rinleezwins** [comment]
Seems like Overseer Deathgaze is now in the game and killable, but still can't see any of the undead monsters needed for the other quest.

**Comment by Sagrath** [comment]
They are ingame now
