### ISSUE TITLE
[Warrior] Ability: Enraged Regeneration

### ISSUE THREAD

**Issue by Rathyan** [dalaranwow/dalaran-wow#1075]
Ability's link: http://wotlk.openwow.com/spell=55694

What's wrong: Death Wish (12292), Bloodrage (29131) and Berserker Rage (18499) are usable during Enraged Regeneration even though the effect doesn't trigger

How it should work: Any enrage effect should not be castable at all during Enraged Regeneration. Whenever you try to cast one of those abilities there should be an error saying "You can't use that yet"

**Comment by vison2** [comment]
Neither Berserker Rage nor the "Improved Devensife Stance" - Rage proc activate it.

**Comment by Vaxsysl** [comment]
There's a work-around to it from player side. Make macros for all Enrage abilities with a line "/cancelaura Enraged Regeneration" before the ability itself, and it will be fine.

Also, what poster failed to clarity is that we can still "use" abilities with enraged regeneration working, trigger their cooldown, but the abilities themselves WILL NOT ACTIVATE, only use up the cooldown.

**Comment by robinsch** [comment]
On PTR.

**Comment by Golganeth** [comment]
Works but message "You can't do that while you are immune" message displays. Not sure if that should be the case, probably intended.
