### ISSUE TITLE
Quest: Ancient Spirit [4261]

### ISSUE THREAD

**Issue by Golganeth** [dalaranwow/dalaran-wow#1077]
**Issue:** When you pick up the quest from *Arei - (ID:9598)* the escort event doesn't start and, in most cases, the quest gets completed right away.

http://wotlk.openwow.com/quest=4261
http://wotlk.openwow.com/npc=9598

**Comment by beregas** [comment]
confirmed, quest gets auto completed when accepted.

**Comment by Rushor** [comment]
45df048f60e52601904f77d16a27c22d344a43af
- event added

**Comment by Golganeth** [comment]
> An infinite amount of Arei (9598) can be summoned from the item Flute of the Ancients (11445). Also a minor issue with Arei's pathing when entering and exiting combat, besides that works like a charm.

**Comment by Rushor** [comment]
d0f9d95ebe12b2bf46d1694a506836e084c4e59f

> Also a minor issue with Arei's pathing when entering and exiting combat, besides that works like a charm.

gereric issues, not related to the quest itself

> An infinite amount of Arei (9598) can be summoned from the item Flute of the Ancients (11445). 

fixed
