### ISSUE TITLE
Quest: Where in the World is Hemet Nesingwary? [12521]

### ISSUE THREAD

**Issue by Golganeth** [dalaranwow/dalaran-wow#1080]
- **Issue:** The gossip option from the NPC doesn't work as it should and causes a mess in Krasus Landing. Once you click it, the machine spawns but you don't get automatically mounted and it despawns after a short while. Venture Co. Pilot also spawns (this is completely wrong), and he triggers a fight between Enraged Wyverns and Enraged Gryphons from the flight master. Any nearby player can get attacked by them as well.

- **How it should work**: Once you pick up the quest and click the Gossip option *"I'm ready to fly to Sholazar Basin"*, you should be automatically flown to the location of the quest objective. In mid-flight, after few seconds, the flying machine flies through a portal to Sholazar Basin. Additional information can be found down below.

------------------

*Player clicks the gossip.*
**Archmage Pentarus says:** I'll send you on my flying machine. Keep your eyes peeled for clues about what might've happened to Hemet!
*Player enter Pentarus' flying machine, which then flies through a portal to Sholazar Basin.*
**Venture Co. Pilot yells:** More intruders? You'll soon learn, no one messes with the Venture Company!
*Player gets shot out of the sky just to the northwest of Monte Muzzleshot.*
**Monte Muzzleshot yells:** Over here, to the southeast. I see they got you too...

--------------

http://wotlk.openwow.com/quest=12521
http://wotlk.openwow.com/npc=28160

**Comment by taralej90** [comment]
Just tried doing the quest and it's still happening as described. At least gryphons and wyverns aren't attacking anymore.

**Comment by Lothloryen** [comment]
Working already.
