### ISSUE TITLE
[Shaman] Totem trouble over all from every type Disarm effect

### ISSUE THREAD

**Issue by dammtoni** [dalaranwow/dalaran-wow#1082]
[this is how shoud work] Usually disarm effect interupts shaman class from casting any time of totem for 9 sec which is the maximum time in case if weapon is enchanted or used talent to reduce disarm effect ( http://thottbot.com/item=41976 [Titanium Weapon Chain
] / http://www.wowhead.com/spell=7224 [Steel Weapon Chain] /  Anticipation [enhancement tree]) shoud stay maximun 4.5 sec

[how actually works] After any type of Disarm effect used on Shaman class  is interupted for 15 sec from casting any time of totem(earth/fire/water/air)
Even when if he has a reduce Dissarm effect enchant/talent is still 15 sec 
Sometimes  even Sillence effect from priest only  still interupt shaman class from using totems for duration of 15 sec

**Comment by Rushor** [comment]
works fine on ptr
