### ISSUE TITLE
Quest: Send Them Packing [11224]

### ISSUE THREAD

**Issue by Golganeth** [dalaranwow/dalaran-wow#1083]
**Issue:** You can spam *"/raise"* on the same Mule till the quest is completed. 

**How it should work**: Each Mule should only count once towards the quest and, as soon as you do the emote, the NPC should run away.

http://www.youtube.com/watch?v=j40N4aLWPS0#t=1m12s

- *Abandoned Pack Mule - 23977*

http://wotlk.openwow.com/quest=11224
http://wotlk.openwow.com/npc=23977

**Comment by Lothloryen** [comment]
Should be fine already.
