### ISSUE TITLE
[Quest] The Pledge of Secrecy (Ironforge)

### ISSUE THREAD

**Issue by Renemis** [dalaranwow/dalaran-wow#1091]
"The Pledge of Secrecy (Ironforge)" this quest supposed to give "Gnome Engineer Membership Card" 
plus it should be renewable "This remains valid for 14 days of 'played time' (336 hours in-game), not 14 real days."

**Comment by Rushor** [comment]
http://wotlk.openwow.com/item=10790

**Comment by Rushor** [comment]
Well the item is a "played-time" item. the Item duration will not tick even if player is offline.

This alreayd works on PTR.
