### ISSUE TITLE
Quest: Test Flight: Raven's Wood <needs reward>

### ISSUE THREAD

**Issue by Daveonx** [dalaranwow/dalaran-wow#110]
Rally Zapnabber offers the gossip to use the Zephyrium Capacitorium but nothing happens.

http://www.wowhead.com/quest=10716/test-flight-ravens-wood-needs-reward

Side  note: quest was left from Blizzard during the beta and is marked as obsolete, that is why the quest name is a bit weird. I would recommend removing it from npc.

**Comment by Rushor** [comment]
394a4db4eabff9afc4e9a16dba377840dd1e368f

- thats true, the quest was no longer available during wotlk
fix:
- moved the quest to disables, so as player (without gm mode) you are no longer able to accept that quest
