### ISSUE TITLE
[Death Knight] Blood Tap and fake rune availability

### ISSUE THREAD

**Issue by Rathyan** [dalaranwow/dalaran-wow#1104]
Spell: http://wotlk.openwow.com/spell=45529

What's wrong: When using Blood Tap and both of the Blood Runes are on cooldown, the spell will reset the cooldown of the first one, turn it into a death rune and lower the cooldown of the second one by a couple of seconds. The problem is that when you try to use the second rune that got the cooldown reduction, it's not actually ready even though the UI says so. I've tested it with tons of rune tracking addons, and the blizzard UI of course, and all of them show the rune as ready

How it should work: Blood Tap should not reduce the cooldown of the second rune

**Comment by taralej90** [comment]
Tested this today. The result was the same: first rune gets converted OK, and then the second B rune's cooldown either moves up or down a random amount of seconds. It can get back to 10 seconds or even look like it is completely refreshed. Of course, this is only visual and the rune's actual cooldown is as normal, but it can get very annoying sometimes. A guildie of mine says he has no such issues through addons, which means the fault is in the Blizz UI.

**Comment by robinsch** [comment]
On PTR
