### ISSUE TITLE
Calendar raids disappearing

### ISSUE THREAD

**Issue by ChistaMisuto** [dalaranwow/dalaran-wow#1106]
What happened: Raid on the calendar disappeared from the raid leader's calendar./Raid leader was removed from their own raid.

What did I do: I invited all L80 people from FOE and a few people from another guild. I gave two people from the other guild the ability to help managing this raid. After this, I checked the raid a few times until eventually the raid disappeared from my calendar. Removal appears random. 

Workaround <not optimal>: Made a new raid, but as the people that had already signed up were missing from this new raid; drama occured.

**Comment by Golganeth** [comment]
#1293
