### ISSUE TITLE
Buff: Alchemist's Stone

### ISSUE THREAD

**Issue by Gordin508** [dalaranwow/dalaran-wow#1107]
Buff description see: http://www.wowhead.com/spell=17619/alchemist-stone
ID: 17619

**Issue:** The Buff should cause health and mana potions to have an additional 40% effect, but this doesn't apply to all potions.

I got the buff from **Mercurial Alchemist Stone** [ID:44322] (http://www.wowhead.com/item=44322/mercurial-alchemist-stone) and tested it with following potions:
**Endless Mana Potion** ID 43570: *Doesn't work*
http://www.wowhead.com/item=43570
**Endless Healing Potion** ID 43569: *Works*
http://www.wowhead.com/item=43569
**Runic Mana Potion** ID 33448: *Doesn't work*
http://www.wowhead.com/item=33448
**Runic Healing Potion** ID 33447: *Doesn't work*
http://www.wowhead.com/item=33447/runic-healing-potion

The fact that it worked with one potion shows that the buff is somehow implented, but not applied to most potions.

Example for how the combat text for a working one looks like:

![image](https://f.cloud.github.com/assets/5062634/1900474/c5fffd6a-7c52-11e3-9fd3-ec60c02f59e2.png)

**Comment by Bacontotem** [comment]
Bump.
Just saw this week's bugfix report (nice job btw) and it reminded me of a bug. 
It was allrdy repoeted tho, most pots dont get the 40% incresed effect fom the Mercurial Alchemist Stone. Is this a bug that is posible to fix?

**Comment by Rushor** [comment]
f043cf726f2a1858abd196d18a73ab39b5aa79e9
- it should proc on mana now

**Comment by Bacontotem** [comment]
It dosent proc fomr Endless Mana Potion.

**Comment by Rushor** [comment]
it's only on ptr bro

**Comment by Rushor** [comment]
this was just fixed, and is only available on the ptr. it will be abpplied on the live realm with the next changelog

**Comment by Bacontotem** [comment]
Ok, very nice! Thanks and great work you all are doing :)
