### ISSUE TITLE
Pushed Too Far

### ISSUE THREAD

**Issue by Vaxsysl** [dalaranwow/dalaran-wow#1110]
Quest Pushed too far ( http://wotlk.openwow.com/quest=12869 ) isn't working as it should, but it is still completable.

The player should be able to mount Stormcrest Eagle ( http://wotlk.openwow.com/npc=29854 ), but mounting doesn't have "mount" icon but "trigger" icon, and the player cannot do anything with the eagle.

But as said, the quest is still completable, the player can still manually kill Stormpeak Wyrms ( http://wotlk.openwow.com/npc=29753 ), but only few are at the land, most of those in air cannot be reached even by Hunters or Fire Mages (40-42y attack range), and flying up to one and using some abilities will agrro them, but they won't follow the player down to land, instead remain up. I could kill three drakes on land and one in air with thrown attack spamming (warrior class). Takes a while.

**Comment by belegija** [comment]
mounting the eagle works fine, but the warms are reseting therefore very hard to kill

**Comment by Sagrath** [comment]
spell 56411 summon the eagles with wrong faction, either 35(friendly) or with the players race faction id

**Comment by jonanone** [comment]
Stormpeak Wyrms now cast Frost Spit when in combat, so they won't stay bugged and continuously regenerating.
 
This update will be applied to the live realm soon.
