### ISSUE TITLE
Daily: The Relic's Emanation

### ISSUE THREAD

**Issue by Jazex** [dalaranwow/dalaran-wow#1111]
After completing this quest (which works perfectly by the way) you get a buff called 'Apexis Emanations' which gives you 15% movement speed increase for 2 hours while in the Blade's Edge Plateaus. However currently this buff also increases your movement speed in other areas than just the Blade's Edge Plateaus, making it viable for abuse.

Edit. Even after removing the buff by right-clicking it I retained the movement speed increase, even relog didn't fix it.

**Comment by Crispybuilt** [comment]
This can be closed because it no longer provides speed bonus if you are outside the Blade's Edge.

**Comment by Rushor** [comment]
alright then
