### ISSUE TITLE
NPC: Vyragosa

### ISSUE THREAD

**Issue by Gordin508** [dalaranwow/dalaran-wow#1112]
**NPC ID:** 32630
Link: http://de.wowhead.com/npc=32630/vyragosa
Location: Storm Peaks / Northrend

**Issue Present:** This "rare" mob spawns every 5 minutes at the same location (approx. at 54/67 in Storm Peaks). It then stays there until attacked/killed.

**How it should be:** This mob should rarely spawn (i don't know the exact time) and patrol all over the Storm Peaks (see link for possible paths).

**Comment by Golganeth** [comment]
Closing up since this is no longer an issue.
