### ISSUE TITLE
NPC: Thistleshrub Rootshaper

### ISSUE THREAD

**Issue by Comgu** [dalaranwow/dalaran-wow#1114]
**Link:** http://wotlk.openwow.com/npc=5485
**Location:** Tanaris

**Issue present:** Thistleshrub Rootshaper's spell "Earthgrab Totem" is not working properly.

**How does it currently work:** The summoned totem from the spell can move and attack the player. It does not do anything else. In addition, its health is incorrect.

**How it should be:** Totem should immobilize the player, without moving or attacking the player at all. The correct amount of health is  15 health.

**Spell link:** http://wotlk.openwow.com/spell=8376

**Comment by n-ghost** [comment]
Still an issue.

**Comment by Demlock** [comment]
Confirmed

**Comment by Golganeth** [comment]
#2924
