### ISSUE TITLE
Breath (On Top of Water)

### ISSUE THREAD

**Issue by Comgu** [dalaranwow/dalaran-wow#1116]
**Issue present:** Breath meter is *sometimes* depleting even though player is swimming on the surface.

**How does it currently work:** Breath meter depletes occasionally even though player is swimming on the surface. This can be fixed by aiming your movement upwards by holding right-click, after this player can swim normally without breath depleting. 

A player with mount has his breath depleting at all times in this situation. In addition the previous fix does not work while mounted.

This has been tested on a Draenei male, mount being a Draenei-race Elekk.

**How it should be:** Player should always be able to breath, if swimming on the surface of water.

**Pictures:** Images with "Breath" showing are ones where breath is depleting.

![wowscrnshot_011814_090020](https://f.cloud.github.com/assets/6435159/1946546/543d7ff8-800e-11e3-9146-bc1cb22450db.jpg)
![wowscrnshot_011814_090024](https://f.cloud.github.com/assets/6435159/1946547/543eae1e-800e-11e3-8539-f2c35d5fa574.jpg)
![wowscrnshot_011814_090242](https://f.cloud.github.com/assets/6435159/1946552/8f5f3cde-800e-11e3-984d-340ef9d1b7d2.jpg)

**Comment by robinsch** [comment]
https://github.com/dalaranwow/dalaran-wow/issues/3109
