### ISSUE TITLE
Quest: Still at It / NPC: "Tipsy" McManus

### ISSUE THREAD

**Issue by Crispybuilt** [dalaranwow/dalaran-wow#1118]
Quest: **Still at It** *(ID:12644)*
NPC: **"Tipsy" McManus** *(ID: 28566)*

- **Issue present:** After the entire quest procedure is over, NPC **"Tipsy" McManus** won't become interactable by players again. His gossip option won't become available for anyone else, thus making the quest being uncompleteable by anyone on the server.
*Quest can be done only once per server crash or restart.*

- **How it should work:** After the entire process is over, and player gets the quest credit, NPC **"Tipsy" McManus** should completely reset making his gossip option available for any player that attempts to do the quest.

- **In-game temporary fix:** It looks that killing and respawning the NPC fixes the issue with the gossip option which then becomes available.

- **Another source of Info**: After 30-45 minutes NPC will manually reset (soft-reset) making the quest doable again apperantly.

__________

http://www.wowhead.com/quest=12644/still-at-it
http://wotlk.openwow.com/quest=12644

**Comment by Lothloryen** [comment]
This was corrected already, thank you.
