### ISSUE TITLE
[NPC] Skinning Bug in Dustwallow Marsh

### ISSUE THREAD

**Issue by InvisibleJon** [dalaranwow/dalaran-wow#1120]
Hello there.

So I have been playing on Dalaran WoW for a while and skinning seems to be working just fine, except for this one thing I experienced in Dustwallow Marsh.
The Dragonkin around there, especially around Onyxia's Lair, seem to have something bugged when you skin them. Often, around 50%, theres absolutely No Loot whatsoever in the ''skinning loot part'', this has nothing to do with skill level or Skinning nor player / mob level differences. Usually it just says, Skinning Failed and you reskin it, but here theres just no loot.
Hope this can get fixed, I lost quite a lot of Leather cause of this :/

How it should work:
Either it would stop and say Skinning Failed, and you'd have to reskin, or simply the Skinning Level is too low.
- Foxa

**Comment by Rushor** [comment]
DB/Item: Increase leather droppchance for some creatures in 'Dustwallow Marsh'

* closes https://github.com/dalaranwow/dalaran-wow/issues/1120

affected creatures:

wotlk.openwow.com/npc=4323 
wotlk.openwow.com/npc=4323 
wotlk.openwow.com/npc=4329 
wotlk.openwow.com/npc=4329 
wotlk.openwow.com/npc=4331 
wotlk.openwow.com/npc=4331 
wotlk.openwow.com/npc=14123
wotlk.openwow.com/npc=14123
wotlk.openwow.com/npc=14123
