### ISSUE TITLE
Quest: Mending Fences

### ISSUE THREAD

**Issue by Evyll** [dalaranwow/dalaran-wow#1122]
This quest doesn't give the ammount of reputation as it should give.
Completing this quest should give 28600 rep (Sons of Hodir) not 22000

http://www.wowwiki.com/Sons_of_Hodir

**Comment by mantacore** [comment]
The problem I am having with this quest is the charm doesn't work on Fjorn but works OK on the other elites, even though the dwarves dont hold agro I can just about manage to down them but have problems with Fjorn.

I've completed this on two other toons and don't recall having this problem

**Comment by Lothloryen** [comment]
Hello there,

You will be able to use the quest item on Fjorn also, after the next realm restart.

Thank you.
