### ISSUE TITLE
Rage generation and absorbs

### ISSUE THREAD

**Issue by Rathyan** [dalaranwow/dalaran-wow#1126]
When the auto attack gets fully absorbed, the player generates no rage as if the auto attack missed.

From http://wowpedia.org/Rage : Patch 3.1.0 (2009-04-14): Attacks that are absorbed (such as by [Power Word: Shield]) will now generate rage.

**Comment by robinsch** [comment]
Can't confirm. Working.

**Comment by Golganeth** [comment]
http://wowwiki.wikia.com/wiki/Rage
>Rage can be generated with several different methods. The primary cause of rage generation is by being attacked, which varies based on damage taken. **Attacks that are blocked, parried, dodged or absorbed (as with Power Word: Shield) also generate rage.** The druid feral talent Natural Reaction allows druids to generate a fixed amount of rage when they dodge.

http://wow.gamepedia.com/Rage
>Patch 3.1.0 (2009-04-14): Attacks that are absorbed (such as by  [Power Word: Shield]) will now generate rage.

Attacks that are absorbed or partially absorbed do not generate Rage currently.

**Comment by Golganeth** [comment]
Disregard. Works now
