### ISSUE TITLE
Quest: Feathers for Nafien [8467]

### ISSUE THREAD

**Issue by bobmanone** [dalaranwow/dalaran-wow#1129]
The quest currently gives 75 reputation instead of 300 reputation.

http://www.wowhead.com/quest=8467

The following also suffer from the same bug,

Feathers for Grazle
http://www.wowhead.com/quest=8466
Beads for Salfa
http://www.wowhead.com/quest=8469

**Comment by Demlock** [comment]
Still an issue...

**Comment by Daveonx** [comment]
Reputations gains for all 3 quests have already been corrected.
