### ISSUE TITLE
Daily Quest: Netherdust Pollen

### ISSUE THREAD

**Issue by Jazex** [dalaranwow/dalaran-wow#1130]
http://www.wowhead.com/quest=11017#comments

There are hardly any netherdust bushes around the Netherwing Ledge. I've been able to find about 2 or 3 but there should be many more since you have to collect 40 of the netherdust pollen (you get around 1-3 from each bush, like a normal herbalism node)

**Comment by jonanone** [comment]
There are around 40 bushes spawned on the area. Just wait the respawn.
