### ISSUE TITLE
NPC: Knight-Captain Drosche

### ISSUE THREAD

**Issue by Crispybuilt** [dalaranwow/dalaran-wow#1146]
**NPC**: Knight-Captain Drosche *(ID:32302)*

- **Issue present:** The following NPC is not spawned in-game on the patroling Skybreaker in the Icecrown Zone. Therefore, players can not obtain nor turn the quests at him.

- **How it should work:** The NPC should be spawned on the Skybreaker and should offer quests to player.

________

http://www.wowhead.com/npc=32302/knight-captain-drosche
http://wotlk.openwow.com/npc=32302

**Comment by jonanone** [comment]
Right now it is already spawned on the Skybreaker, so I'm closing the issue.
