### ISSUE TITLE
The Left Piece of Lord Valthalak's Amulet (Dire Maul)

### ISSUE THREAD

**Issue by medan** [dalaranwow/dalaran-wow#1152]
http://www.wowwiki.com/Quest:The_Left_Piece_of_Lord_Valthalak%27s_Amulet_%28Dire_Maul%29

As wowwiki says: "Use the Brazier of Beckoning to summon forth the spirit of Isalien and slay her." Then you have to loot quest item from her.

When you use Brazier, nothing happen. But Isalien is spawned there permanently (which is wrong, but can temporary help). The problem is that she is marked as friendly (green) so you can't attack her and therefore you can't loot quest item to complete the quest.

http://www.wowwiki.com/Isalien

http://wotlk.openwow.com/quest=8967

**Comment by Rushor** [comment]
moved to https://github.com/dalaranwow/dalaran-wow/issues/2503
