### ISSUE TITLE
NPC: Terrorclaw [20477]

### ISSUE THREAD

**Issue by Golganeth** [dalaranwow/dalaran-wow#1153]
**issue:** The respawn timer of this NPC is roughly 25 minutes, should be lowered to 5-6 minutes at most.

http://wotlk.openwow.com/npc=20477

**Comment by Golganeth** [comment]
Fixed.

**Comment by shilofax** [comment]
Issue seems to have been re-introduced. I've been waiting for about 10 minutes and it hasn't respawned.

**Comment by thestranger064** [comment]
Not respawning for about 25m or more. Still is not seeing the npc
