### ISSUE TITLE
[Quest][Classic] The Right Piece of Lord Valthalak's Amulet (Scholomance)

### ISSUE THREAD

**Issue by medan** [dalaranwow/dalaran-wow#1154]
http://www.wowwiki.com/Quest:The_Right_Piece_of_Lord_Valthalak%27s_Amulet_%28Scholomance%29

"Use the Brazier of Beckoning to summon forth the spirit of Kormok and slay him."

When I use Brazier of Beckoning at correct place (the Laboratory in Scholomance) nothing happen. It should summon boss Kromok who drops quest item.

http://www.wowwiki.com/Kormok

Similar problem as #1152 and probably all other variants of Lord Valthalak's Amulet quests.

http://wotlk.openwow.com/quest=8992

**Comment by Rushor** [comment]
This was fixed by:

https://github.com/TrinityCore/TrinityCore/blob/a249d86b00eb0854cb925f8bea76ddbb364208df/sql/old/3.3.5a/TDB53_to_TDB54_updates/world/2014_07_01_00_world_misc.sql

already working on PTR.

![GitHub Logo](http://i.imgur.com/MJqbMBl.jpg)
