### ISSUE TITLE
 Achievment/ Instance - Cullling of Stratholme HC - Zombiefest

### ISSUE THREAD

**Issue by Dupsi** [dalaranwow/dalaran-wow#1155]
After trying it 2 times now in the last streets of Stratholme in the HC Dungeon, i am pretty sure that no credits are given for Zombiekills in the appropriate time. We cleared the Way to the Market row first then neglecting Arthas, waited a bit and went back, single target killing the respawned elites and having the Zombies on a healer or second tank without a weapon, we counted more then 90 both times before starting to rush for the last few. From this description on our attempt, you already see that Zombie spawns also differ from retail.

[url]http://www.wowhead.com/achievement=1872/zombiefest%E2%80%8E[/url]

**Comment by kikomir** [comment]
1 year and 9 months later, this still doesn't work, achievement "Zombiefest" can't be done. No credits are given for killing zombies. This achievement is needed for meta achievement "Glory of the Hero".

**Comment by Golganeth** [comment]
This has been working for a while, report shouldn't be opened.

Closed
