### ISSUE TITLE
Mea Culpa, Lord Valthalak

### ISSUE THREAD

**Issue by medan** [dalaranwow/dalaran-wow#1157]
http://www.wowwiki.com/Quest:Mea_Culpa,_Lord_Valthalak

"Use the Brazier of Beckoning to summon Lord Valthalak. Dispatch him, and use Lord Valthalak's Amulet on the corpse." Have to be used in The Beast's chamber in UBRS.

Brazier of Beckoning doesn't summon any boss (as I already reported in other issues), so I couldn't summon Lord Valthalak and kill him. I have no idea if amulet works on his corpse.
#1152 #1154

**Comment by Rushor** [comment]
works fine since https://github.com/TrinityCore/TrinityCore/commit/4a05a082fd671099463049552170ddbeaff6a257

http://i.imgur.com/APkSEeD.jpg
http://i.imgur.com/FYWIe4U.jpg
