### ISSUE TITLE
Return to Bodley

### ISSUE THREAD

**Issue by medan** [dalaranwow/dalaran-wow#1158]
http://www.wowwiki.com/Quest:Return_to_Bodley

This quest is a follow up after #1157 so it cannot be obtained in game at this moment, because of previous quest bug. You can't kill Lord Valthalak and use item on him to summon his spirit, who offer you this quest. GM had to help me (thanks :o), so I can finish the quest chain now.

**Comment by Rushor** [comment]
well the script iteself works. we just need to fix this quest https://github.com/dalaranwow/dalaran-wow/issues/1157
