### ISSUE TITLE
[Hellfire Peninsula] Quest 10764: Hotter than Hell

### ISSUE THREAD

**Issue by Rathyan** [dalaranwow/dalaran-wow#1167]
Quest: http://www.wowhead.com/quest=10764
Quest Item: http://www.wowhead.com/item=31251
Quest mob: http://www.wowhead.com/npc=18733

The quest item is usable anywhere without having to slay a Fel Reaver

**Comment by n-ghost** [comment]
Still an issue.

**Comment by jonanone** [comment]
Quest item is now only usable near Fel Reaver. Still not implemented the requirement to have it killed.

**Comment by Rushor** [comment]
0f57e2984f8dcecaa2cf0eefef574ab1c7b8fa63
- now also requires to be dead
