### ISSUE TITLE
Pet Ability: Pet Bite/claw/smack don't properly scale with attack power

### ISSUE THREAD

**Issue by wonopon** [dalaranwow/dalaran-wow#1175]
Bite (http://wotlk.openwow.com/spell=17253) does not scale with attack power; my pet only hits between 16 and 22, never more than 22 (this is for the Rank 4 version). 

According to http://www.wowwiki.com/Bite it does scale with attack power. No idea what the coefficient is though

EDIT: This might help. http://www.trinitycore.org/f/topic/5161-hunters-and-pet-scaling/

**Comment by Rushor** [comment]
this issue will be handled in https://github.com/dalaranwow/dalaran-wow/issues/3774
