### ISSUE TITLE
[NPC] Gorgannon - calls for help but no mobs come

### ISSUE THREAD

**Issue by wonopon** [dalaranwow/dalaran-wow#1176]
Gorgannon (http://wotlk.openwow.com/npc=17300) calls for help when he gets low on HP, but no mobs come to help him.

**Comment by Rushor** [comment]
before he calls for help http://i.imgur.com/5NX5W8V.jpg
after he called for help http://i.imgur.com/qwPNSC5.jpg > nearby creature will help him

Issue was already fixed
