### ISSUE TITLE
[Achievement] Flirt With Disaster (horde) 1280

### ISSUE THREAD

**Issue by bobmanone** [dalaranwow/dalaran-wow#1177]
http://www.wowhead.com/achievement=1280

This achievement is currently not working, I got my character completely smashed, used the rose petals on him, then /kissed him and I did not receive the achievement.

**Comment by Rushor** [comment]
DB/Misc: Fix achievement Flirt With Disaster.

* commit: 1e8bf1aad18088c0e5cde8918d653bc00b0187a4

Already fixed ON PTR.

http://www.wowhead.com/achievement=1280/flirt-with-disaster#comments:id=1621772

Tips to get this achievement.

1) buy all the drinks from Sylannia ( Drink Vendor ) at the Darkmoon Fair.

2) Exchange Love Token for 'Handful of Rose Petals' and any Perfume from Lovely Merchant.

3) Go to UnderCity and look for Jeremiah Payson who is the c.ockroach vendor.

4) Consume and repeat consuming all the drinks which you bought from Darkmoon Fair untill u get SMASHED.( Screen very Blur )

5) use the perfume on yourself

6) use the handful of Rose Petals on Jeremiah Payson

7) Kiss Jeremiah Payson

Achievement completed.
