### ISSUE TITLE
[Quest] A Friendly Chat... [Seasonal love is in the air] 24576

### ISSUE THREAD

**Issue by bobmanone** [dalaranwow/dalaran-wow#1178]
http://www.wowhead.com/quest=24576

When you approach Snivel Rustrocket nothing happens and you cannot receive his ledger. there should be some dialog then he gives you the quest item, this quest is required for the achievement Dangerous Love.

**Comment by Rushor** [comment]
already fixed on PTR:

DB/Quest: A Friendly Chat
* commit: 0c9e39f1510c838cb3c84fc7502db9dd00bd4771
