### ISSUE TITLE
Quest: Into Hostile Territory [12325]

### ISSUE THREAD

**Issue by Golganeth** [dalaranwow/dalaran-wow#1179]
**Issue:** You can't get a secure ride to Thorson's Post. Once you mount one of the gryphons clicking the green arrow, you get stuck on a stationary vehicle.

**How it should work:** As soon as you click one of the gryphons, you should be brought to Thorson's Post.

-------------------

- **Wintergarde Gryphon** ~> *ID: 27661*

/

Gryphon spawned via script once mounted, one of these: (Pending confirmation)
- **Wintergarde Gryphon (NPC Mount)** ~> *ID: 27841*
- **Wintergarde Gryphon (Taxi)** ~> *ID: 27764*

![image](https://f.cloud.github.com/assets/5057942/2126077/a8381d6a-925c-11e3-8494-5ffb1c4c3580.png)

http://wotlk.openwow.com/npc=27661
http://wotlk.openwow.com/npc=27764
http://wotlk.openwow.com/npc=27841
http://wotlk.openwow.com/quest=12325

**Comment by Thillo** [comment]
confirmed

**Comment by jonanone** [comment]
Clicking on the Gryphon will fly you to Thorson's Post. Also the texts and the parachute have been added. The fix will be applied to the live realm soon.
