### ISSUE TITLE
Quest: Not On Our Watch

### ISSUE THREAD

**Issue by Golganeth** [dalaranwow/dalaran-wow#1181]
**Issue:** The amount of game objects in-game is too low, even when the respawn is completely full, you will not be able to complete the quest as you will barely get 8-9 out of the overall 12 you need.

Also the thugs in the area should pick up the boxes off the ground and they should disappear. Consequently, they should drop shipments as loot.

- **Shipment of Animal Parts** ~> *IDs: 188015 / 188016 / 188017 / 188018*

http://wotlk.openwow.com/search=shipment+of+animal#objects

**Comment by jonanone** [comment]
Northsea Thugs carrying a bag will drop quest items and use the Crazy ability.

This update will be applied to the live realm soon.
