### ISSUE TITLE
Quest: If Valgarde Falls... [11243]

### ISSUE THREAD

**Issue by Golganeth** [dalaranwow/dalaran-wow#1183]
**Issue:** The amount of NPC's to kill in-game is too low, even when the respawn is completely full, you will not be able to complete the quest as you will barely get 7-8 kills (if you are lucky) out of the overall 12 you need.

Apparently, they should spawn without limit while the Elite Guards fight them non-stop.
WH comment (Patch 3.2.2):
> *"These guys will spawn without limit so it can be a very efficient way to gain xp without the hassle of running around .... The guards will help you kill but you will noticeably get reduced xp if you can tag it before the guard finishes it off."*

--------------

- **Dragonflayer Invader** ~> *ID: 24051*
- **Dragonflayer Worg** ~> *ID: 24063*

http://wotlk.openwow.com/quest=11243
http://wotlk.openwow.com/npc=24051
http://wotlk.openwow.com/npc=24063

**Comment by Thillo** [comment]
can confirm this, takes very long this way to finish the quest

**Comment by jonanone** [comment]
Some more npcs have been added, and their respawn time has been adjusted. These changes will be applied to the live realm soon.
