### ISSUE TITLE
Quest: Meet Lieutenant Icehammer... [11427]

### ISSUE THREAD

**Issue by Golganeth** [dalaranwow/dalaran-wow#1186]
**Issue:** Upon accepting the quest, you are not brought anywhere.

**How it should work:** Accepting the quest should bring you to Lieutenant Icehammer.

**Wowwiki notes regarding the quest:**
> "*Accepting the quest puts players on the back of a two-seater gryphon, on a path that is designed to show players the route back to Valgarde from Nifflevar, via the dam interior.*"

**Video:** http://www.youtube.com/watch?v=8ddCYM5l--s

------------

- **Quest Giver** - Guard Captain Zorek ~> *ID: 23728*
- **Ends the quest**-  Lieutenant Icehammer ~> *ID: 24634*

http://wotlk.openwow.com/npc=23728
http://wotlk.openwow.com/npc=24634
http://wotlk.openwow.com/quest=11427

**Comment by jonanone** [comment]
Accepting the quest will put the player on a gryphon that will bring him/her to the Lieutenant Icehammer.


This update will be applied to the live realm soon.
