### ISSUE TITLE
Quest: Lightning Infused Relics [11494]

### ISSUE THREAD

**Issue by Golganeth** [dalaranwow/dalaran-wow#1187]
**Issue:** You can't get into the Iron Rune Construct so you can't achieve the objectives of the quest.
You get this quest once you complete the chain quest "Iron Rune Constructs and You" (related to #470).

This quest is directly related to the training you did during the following quest:
*"Iron Rune Constructs and You: Collecting Data" (ID: 11489)*

**Video of how it should work:** http://www.youtube.com/watch?v=cerT_kHn2xw

http://wotlk.openwow.com/quest=11494

**Comment by Lothloryen** [comment]
Working since long time ago.
