### ISSUE TITLE
Quest: The Delicate Sound of Thunder [11495]

### ISSUE THREAD

**Issue by Golganeth** [dalaranwow/dalaran-wow#1188]
**Issue:** You can't get into the Iron Rune Construct so you can't achieve the objectives of the quest.
You get this quest once you complete the chain quest "Iron Rune Constructs and You" (related to #470).

**How it should work:** WH comment (Patch 2.4.3)
> "71.6, 69.8 inside the cave at the Baelguns Excavation Camp.
After passing by on an army of Dark Iron Dwarves an holograph titan appears talking to the crowd. After listening to the following lines, you get the quest completed."

/

**Video of how it should work:** http://www.youtube.com/watch?v=_wmU9qV8CWA

---------------------------

**Dialog:**
> - **Kronus yells:** [Titan] Come, minions! Your master calls!
- **Kronus yells:** [Titan] The work of your brothers in the Storm Peaks has reached a frenzied pace. Soon, Father will be freed.
- **Iron Rune Worker says:** [Titan] Stop! Stop! Scrap metal moves itself now?
- **Iron Rune Construct says:** [Titan] To interfere with construct's function results in termination. Move along.
- **Iron Rune Worker says:** [Titan] Forgive my insolence!
- **Kronus yells:** [Titan] Your brothers to the north have subjugated the stone behemoths and set them on the path to Ulduar. Soon, the remaining defenses of the Pantheon will be neutralized.
- **Kronus yells:** [Titan] The three fissures opened by the mortals of this region must be silenced. The earth hears and sees what we do and will continue to interfere with our efforts if the way is not closed.
- **Kronus yells:** [Titan] Bury this place! Your master demands it!

-----------------

http://wotlk.openwow.com/quest=11495

**Comment by catta000** [comment]
Whole questchain works well, you are able to fully use the construct, enter the cave and finish the quests.

**Comment by Lothloryen** [comment]
Hello there,

Yes, the whole chain quest works now well, forgot to close this issue.
