### ISSUE TITLE
Quest: March of the Giants [A: 11355 / H: 11365]

### ISSUE THREAD

**Issue by Golganeth** [dalaranwow/dalaran-wow#1189]
**Issue:** The quest works but the Runed Stone Giant corpse doesn't despawn right after using the quest item.

http://wotlk.openwow.com/npc=24329
http://wotlk.openwow.com/quest=11355 (Alliance)
http://wotlk.openwow.com/quest=11365 (Horde)

**Comment by Sagrath** [comment]
Working, they despawn after 2 sec
