### ISSUE TITLE
Spell / Aura: Northsea Force Reaction [44017]

### ISSUE THREAD

**Issue by Golganeth** [dalaranwow/dalaran-wow#1191]
**Issue:** Once in Scalawag Point (Howling Fjord) you receive the buff called "Northsea Force Reaction" _(ID:44017)_ but you are able to attack the NPCs in the area.
However, you can pick up their quests flawlessly, but if you happen to attack them or cast a harmful spell on them, all the nearby NPC's will attack you.

**How it should work:** The buff should force your reputation with Northsea Pirates to neutral, and therefore they should NOT be attackable at all.

http://wotlk.openwow.com/spell=44017

**Comment by jonanone** [comment]
It seems that is something wrong with the reputation itself, since the buff is putting the player in Neutral rep but allowing the player to attack the NPCs. I have changed it to put the player on Friendly reputation instead of Neutral (I have seen several videos about the quests in that area showing the npcs as friendly). This way the quests are still doable and you won't kill npcs or be attacked when you shouldn't.

I will let the issue open since this should be reviewed to make Neutral npcs for this faction not attackable.

**Comment by Edzero** [comment]
Working on PTR according to the temporary fix that Jonanone has made.

**Comment by Zibathy** [comment]
I am unable to turn in quests as a result of this. I was able to accept their quests and they were friendly but when I came back after completing these quests they were hostile again, and won't go back to friendly no matter how many times I reload the area.

![wowscrnshot_112116_212048](https://cloud.githubusercontent.com/assets/7729864/20509733/6b669516-b030-11e6-8440-698841ecc228.jpg)

**Comment by Edzero** [comment]
Unable to replicate this on the PTR, was able to complete all of the quests for this faction just fine.

"To be clear, if you are a Bloodsail Admiral and the Steamwheedle Cartel are angry with you, the NPCs of this subzone will be angry with you unless you are carrying the Street "Cred" quest. While that quest is in your log, the NPCs will be friendly permitting you to proceed. If you drop the quest and leave the subzone, the NPCs will return to being angry with you. That is to say, the co-operation of these NPCs are sensitive to this quest in your log. Handy to know if you wish to drop a quest for space and think about picking it up again and are all 'Oh noes they hate me oh well won't bother picking up that chain'."

Taken from WowWiki. Is this relevant to your character? If you meet the criteria then things are working as intended. If you aren't a Bloodsail Admiral then this will require additional investigation.

Thank you.

**Comment by ImprezaWoW** [comment]
@edzero also the player is from Kirin Tor, and I'm not sure that live updates are being applied there, it might be only Algalon.

**Comment by Edzero** [comment]
Well spotted.

**Comment by Zibathy** [comment]
I'm from Kirin Tor, that is correct. Also Honored with the Steamwheedle Cartel.
