### ISSUE TITLE
Druid's Ability: Nature's Grasp

### ISSUE THREAD

**Issue by Jiokko** [dalaranwow/dalaran-wow#1192]
http://wotlk.openwow.com/spell=16689
Nature's Grasp trigger internal cooldown (1,5 second)  is not enabled.

How it works: if you got hit by a melee too fast or by multiple attackers, all the hits will trigger that nature's grasp's charges even if the have 0,00001 second difference or even if they hit at the exact same time, which means all the 3 charges go wasted pretty fast and become useless.

How it should work: When a charge of Nature's Grasp is triggered by an attack then the spell gets the 1,5 second internal cooldown in which no attack can trigger the next charge of the spell, when that 1,5 second passes, then the next attack will trigger the 2nd charge and goes on.

a maybe helpfull link or maybe not (http://code.google.com/p/trinitycore/issues/detail?id=3917)

**Comment by robinsch** [comment]
Since time(nullptr) is only seconds precise the internal cooldown is 2 seconds.

**Comment by Rushor** [comment]
robinsch going wotlk, nice :>
