### ISSUE TITLE
[Hunter] Pet talent: Wild hunt

### ISSUE THREAD

**Issue by moliskrc** [dalaranwow/dalaran-wow#1203]
http://www.wowwiki.com/Wild_Hunt
Increases the contribution your pets get from your Stamina by X%(20/40) and attack power by X%(15/30).

The problem is when you mount your pet disappears and when you dismount your pet appears without the same amount of hitpoints he gained from this talent. So you must heal the pet to full health everytime you mount/dismount (very annoying in bg's).

http://s27.postimg.org/8c7xb51qr/Wo_WScrn_Shot_021514_163415.jpg
http://s15.postimg.org/clczfn2ff/Wo_WScrn_Shot_021514_163424.jpg

Pets hp should stay the same despite mounting/dismounting.

**Comment by Lothloryen** [comment]
#2910

**Comment by MrAndersonX** [comment]
Alot of pet talents are still bugged, waiting for the changelog to be applied to the live realm. Can we get a timed release on it ? We've been waiting for it to be applied for a while now...
