### ISSUE TITLE
Algalon: Mob Stacking

### ISSUE THREAD

**Issue by sayamen** [dalaranwow/dalaran-wow#1204]
Hello there. So the problem is:

When attacked by 2+ mobs, they stack on each other in one spot. They should be spread around the character.

Thank you.

**Comment by Rushor** [comment]
how it should look like: https://www.youtube.com/watch?v=GDAldody2YY

**Comment by Rushor** [comment]
https://github.com/dalaranwow/dalaran-wow/issues/4711 < This issue is more detailed and we will state this issue as duplicate for now. Thanks
