### ISSUE TITLE
Quest: The Bones of Nozronn (Sholozar Basin)

### ISSUE THREAD

**Issue by Jiokko** [dalaranwow/dalaran-wow#1210]
After the last update this quest broke, when you use the quest item at the offering bowl nothing happens.

How it should work: once you use the Soo-rahm's Incense at the offering bow near the bones of Nozronn a small event in which a text should appear at the chatlog saying somethings i dont remember and after this text finishes, then the quest is completed.

**Comment by ashido96** [comment]
Will say i got it to work as gonklol said. Stood still for about 15 second after activating the item until questhelper showed credit. (no credit shown via main client unless looking in quest log).

**Comment by Comgu** [comment]
Working on Algalon at the moment.

**Comment by Lothloryen** [comment]
Working since long time ago.
