### ISSUE TITLE
[Misc/Items] Eternium Ore Mining Chance Zero

### ISSUE THREAD

**Issue by Gordin508** [dalaranwow/dalaran-wow#1211]
**Item ID**: 23427
**Link 1**: http://www.wowhead.com/item=23427/eternium-ore
**Link 2**: http://www.wowwiki.com/Eternium_Ore

**Pre-Info**: This problem didn't exist a few weeks ago.

**Issue Present**: The Chance to get Eternium Ore when mining Outlands nodes is either **very low or not given at all.**

**How it should work**: When mining any Outland mining node, there should be  chance (unfortunately the community pages have different numbers for the chances) to get one or multiple Eternium Ore, dependent on the type of node.

**How i tested it**: Since the farming success for this item is based on NRG, it cannot proof it 100%, but here is my data:
While leveling mining from 1-450 a few weeks ago, i got 22 Eternium Ore during my Outland-Phase. Unfortunately i haven't got data about how much i mined back then.

When i tried farming Eternium on 15.02.2014 and 16.02.2014 i mined the following:
_>270 Adamantite Ore (from both rich and normal Adamantite Deposits)_
_208 Fel Iron_
_47 Khorium Ore_
**0 Eternium Ore**

Both leveling mining and attempting to farm eternium happened in Nagrand.

**Deposit IDs**:
Rich Adamantite Deposit: 181569, 181570, 181558, 181568 
(see http://www.wowhead.com/search?q=Adamantite+Deposit)
Adamantite Deposit: 181556
Fel Iron Deposit: 181555
Khorium Vein: 181557

**Comment by Rushor** [comment]
The item can be found in:  

```sql
('Fel Iron Deposit');
('Adamantite Deposit');
('Khorium Vein');
('Rich Adamantite Deposit');
('Rich Adamantite Deposit');
('Heavy Fel Iron Chest');
('Adamantite Bound Chest');
```

Droppchances can be found here: http://wotlk.openwow.com/item=23427#mined-from-object

This works correctly for me on PTR.
