### ISSUE TITLE
[Spell] Shadowform form + infinite cooldowns

### ISSUE THREAD

**Issue by chereyo** [dalaranwow/dalaran-wow#1214]
Bug: Sometimes when trying to enter shadowform, the spell will become "grey" and will give the message "This spell is not ready" when trying to use it. It is seen on multiple servers

Cause: It happen if you use a spell and immediately try to use shadowform, probably before the global cooldown clears. There may be other causes as well.

Solution right now: To relog.

**Comment by cover25** [comment]
Still bugged. When you try to enter before GCD is finished it gets bugged

**Comment by Lothloryen** [comment]
Hello there,

I am performing a realm maintenance in 10 minutes, this issue should be corrected with it, as well as several other class related ones.

Thank you very much.
