### ISSUE TITLE
Blessed Recovery

### ISSUE THREAD

**Issue by lindsethlol** [dalaranwow/dalaran-wow#1225]
Blessed Recovery : After being struck by a melee or ranged critical hit, Blessed Recovery heals you for 5% of the damage taken over 6 sec.Additional critical hits taken during the effect increase the healing recieved.

It consinstantly ONLY heals me for 1, whetever mob or crit i only get the ticks of 1 and 1 heal.

**Comment by robinsch** [comment]
Can't confirm.
