### ISSUE TITLE
[Quest] [Love in the air] Dailies are not giving EXP

### ISSUE THREAD

**Issue by wonopon** [dalaranwow/dalaran-wow#1230]
None of the Love Is In the Air event dailies are giving EXP to players. Upon picking up the quest, there is an experience reward which scales based on your level. When completing the quest, however, you do not get that experience reward.

EDIT: it appears this bug is only on Kirin Tor; on Algalon the dailies do give exp.

**Comment by Golganeth** [comment]
#2964
