### ISSUE TITLE
[NPC] Zanzil NPCs unscripted

### ISSUE THREAD

**Issue by wonopon** [dalaranwow/dalaran-wow#1236]
Zanzil Witch Doctor (http://wotlk.openwow.com/npc=1490), 
Zanzil Zombie (http://wotlk.openwow.com/npc=1488), 
Zanzil Naga (http://wotlk.openwow.com/npc=1491),
Zanzil Hunter (http://wotlk.openwow.com/npc=1489), and
Zanzil the Outcast (http://wotlk.openwow.com/npc=2534) are not casting any of their abilities.

**Comment by Rushor** [comment]
i already added thos abilities some time ago. the issue was fixed
