### ISSUE TITLE
Paladin \ Shield of Righteousness unable to trigger on-hit effects (i.e. Seals)

### ISSUE THREAD

**Issue by PinkClassBugs** [dalaranwow/dalaran-wow#1237]
__Current situation__

* When you hit a target with Shield of Righteousness, the Seal effects of Seal of Vengeance, Command, Wisdom and Justice as well as the Judgement effects of Judgement of Light and Wisdom are not being triggered / have no chance of being triggered.

__Desired situation__

* When you hit a target with Shield of Righteousness, it should be capable of triggering any Seal and Judgement effects.

__Spell IDs__

|ID|Name|
|--:|:--| 
|53600|Shield of Righteousness Rank 1|
|61411|Shield of Righteousness Rank 2|
|31801|Seal of Vengeance|
|20375|Seal of Command|
|20166|Seal of Wisdom|
|20164|Seal of Justice|
|20271|Judgement of Light (Spell)|
|20185|Judgement of Light (Debuff)|
|53408|Judgement of Wisdom (Spell)|
|20186|Judgement of Wisdom (Debuff)|
|9452|Vindication Talent Rank 1|
|26016|Vindication Talent Rank 2|

__Additional information__
Other on-hit effects than Seals would be the Vindication talent (listed in the spell IDs, although it's proc rate is bugged, see #1315) or  weapon procs, such as [Last Word (http://wotlk.openwow.com/item=50179)](http://wotlk.openwow.com/item=50179) to name one example (cannot test or verify that it procs on Dalaran-Wow, this is a retail example).

**Comment by robinsch** [comment]
Tested, working fine.

https://i.gyazo.com/39f0e19a9554907205e0a17b1cfdc9a5.png

**Comment by PinkClassBugs** [comment]
Not working fine; the following issues persist:
* Shield of Righteousness does not trigger Judgement of Light.
* Shield of Righteousness does not trigger Judgement of Wisdom.
* Shield of Righteousness does not apply a Seal of Vengeance debuff.
* Shield of Righteousness does not trigger Seal of Command.

**Comment by robinsch** [comment]
Shield of Righteousness does not trigger Judgement of Wisdom.
![](https://i.gyazo.com/94d26c2f030fef1838208ac81b23636d.png)
(Not applied to live realm yet.)

Shield of Righteousness does not trigger Judgement of Wisdom.
![](https://i.gyazo.com/a04d6e16a8f141e6826177ada6922bac.png)
(Not applied to live realm yet.)

Shield of Righteousness does not apply a Seal of Vengeance debuff.
![](https://i.gyazo.com/96884f7d1d2e5e65880b9ab2a88e71a9.png)
(Not applied to live realm yet.)
Shield of Righteousness does not trigger Seal of Command.
![](https://i.gyazo.com/bcb1b26d985344cb44576350660e9336.png)
(Not applied to live realm yet.)

**Comment by Golganeth** [comment]
- [x] Shield of Righteousness does not trigger Judgement of Light. 
- [x] Shield of Righteousness does not trigger Judgement of Wisdom. 
- [ ] Shield of Righteousness does not apply a Seal of Vengeance debuff. (buggy on PTR)
- [x] Shield of Righteousness does not trigger Seal of Command. 

While doing melee swings and spamming shield ability, only melee swings would apply a stack of  Seal of Vengeance. The rest worked fine.

**Comment by Golganeth** [comment]
Seal of Vengeance (Alliance) works. Seal of Corruption (Horde) doesn't.

**Comment by Golganeth** [comment]
Works perfect now.

**Comment by robinsch** [comment]
Removed Shield of Righteousness does not apply a Seal of Vengeance debuff.

http://wowwiki.wikia.com/wiki/Seal_of_Vengeance

Patch 3.2.0 (04-Aug-2009):
Only auto-attacks and Hammer of the Righteous can place the debuff on the paladin's current target(s).
