### ISSUE TITLE
NPC: Kruban Darkblade <Darkmoon Faire Barker>

### ISSUE THREAD

**Issue by AlgaFrosty** [dalaranwow/dalaran-wow#1241]
Issue present: Kruban Darkblade (ID: 14843) is a Darkmoon Faire Barker, he should wander around Orgrimmar with quest "The Darkmoon Faire". Instead of doing it, he just stands near Auction House, doesn't move.
How it should work: Kruban Darkblade (ID: 14843) should wander around Orgrimmar.
WoWWiki: http://www.wowwiki.com/Kruban_Darkblade
Regards, Frosty.

**Comment by Demlock** [comment]
Confirmed.

**Comment by Rushor** [comment]
95ce06fa1e433d94597ca9d334000c2954c8dcde
- added some waypoints for him

**Comment by Rushor** [comment]
we will move this issue to https://github.com/dalaranwow/dalaran-wow/issues/3406
