### ISSUE TITLE
Summon Water Elemental

### ISSUE THREAD

**Issue by Stoney21** [dalaranwow/dalaran-wow#1256]
First of all, any time you summon your Elemental his pet abilities switch into default bars, not the ones you previously set them to. 

Another thing is that everytime he launches a Waterbolt on an enemy he gets closer to him few yards and it shouldn't be like that. 

I noticed that he sometimes hits with his arm and that's another problem. Water Elemental is RANGE pet and it shouldn't be possible for him to use his melee attacks similar to Warlock's Imp or DK's Gorgoyle. When you disable his auto cast on Waterbolt he should just look at the enemy withouth attacking it anyhow and NOT getting closer to him. 

It's obvious fact but there's a simple proof:
http://us.battle.net/wow/en/forum/topic/1670091290

"Water elementals, like warlock's imps, have no melee attack.. if they can't cast their spell [in cases such as if the auto-cast is disabled], they will just sit there."

Another proof: http://eu.battle.net/wow/en/forum/topic/9413781701

"If you have accidently right-clicked this and turned it off auto cast, you are basically telling your pet "You are only allowed cast this spell when I manually tell you to". So when they are in a fight, they aren't automatically casting it, and don't have a melee attack, so there is nothing for them to do!"

WOWWIKI: http://www.wowwiki.com/Summon_Water_Elemental

"Waterbolt is the elemental's primary spell, and it will automatically use this spell when attacking an enemy."

EDIT. Another thing I've noticed is a strange delay with damage appliement after Waterbolt hits the target.

**Comment by Archcry** [comment]
@Toman408, Possible workarount is to make a macro that dismisses the pet and then summons it again?

**Comment by Rushor** [comment]
Summary:
- enable resummon if pet is dead (cold snap)
- de/remount problem
- spell power scaling
- range attack
