### ISSUE TITLE
[NPC] Skadi the Ruthless

### ISSUE THREAD

**Issue by AlbanLHC** [dalaranwow/dalaran-wow#1276]
On Algalon, it is currently possible to kill Skadi with the harpoons.

IMG: http://i.imgur.com/20Xy3cg.jpg

**Comment by bucovsky** [comment]
It is not working properly at the moment. When you shoot those harpoons, Skadi dies in the air and cannot be looted.

**Comment by urdarchina** [comment]
Confirmed, he is killed by the harpoons and is unlootable. Harpoons should only kill his mount and he should land on the ground for the fight.

**Comment by Lothloryen** [comment]
Issue corrected, it shall be alive after the next maintenance, which will happen in about 15-20 minutes.

Thank you.
