### ISSUE TITLE
Quest: By Fire Be Purged

### ISSUE THREAD

**Issue by Crispybuilt** [dalaranwow/dalaran-wow#1277]
**Quest: By Fire Be Purged** - *13211*

- **Issue present:** Quest currently doesn't work due the credit failing to register. Once you burn the corpses you do not get credit for burning them.

- **How it should work:** Once you burn the corpse with the quest item, player should get the credit.

- **Additional Info:** Quest is crucial and it's breaking the chain which leads to the: *"The Flesh Giant Champion"*

___________________

**Items & NPCs:**

*43524 - [Olakin's Torch]*
*Festering Corpse: Entry: 31130*

____________________

http://wotlk.openwow.com/quest=13211
http://www.wowhead.com/quest=13211/by-fire-be-purged

**Comment by Lothloryen** [comment]
Working since long time ago.
