### ISSUE TITLE
Quest: Death's Gaze

### ISSUE THREAD

**Issue by Crispybuilt** [dalaranwow/dalaran-wow#1278]
**Quest: Death's Gaze** - 

- **Issue present:** After completing the quest and getting all 3 objects done, you are unable to turn the quest to the following NPC which gave you the quest: **Darkrider Arly** - Reason unkown.

- **How it should work:** After completing the quest and getting all 3 objects done, you should be able to turn in the quest to the NPC.

- **Additional info:** Restarting the game doesn't help, clearing cache doesn't help, re-taking and re-doing the quest doesn't help.

______________

**NPCs**
Darkrider Arly - 30631

__________
http://wotlk.openwow.com/quest=13120
http://www.wowhead.com/quest=13120

**Comment by Lothloryen** [comment]
Working fine
