### ISSUE TITLE
Daily Dungeon Quest rotation & Daily Heroic Quest

### ISSUE THREAD

**Issue by AlbanLHC** [dalaranwow/dalaran-wow#1279]
Archmage Timear in Dalaran is currently only offering the quest "Timaet" (tested for 3 days straight). He should however offer different quests each new day, (see http://www.wowwiki.com/Wrath_of_the_Lich_King_daily_quests).

Archmage Lan'dalock in Dalaran should offer 1 daily heroic quest for each day. Right now he isn't doing anything (see http://www.wowwiki.com/Wrath_of_the_Lich_King_daily_quests).

**Comment by Lothloryen** [comment]
Everything was scripted long time ago, including the images and so.

Thank you.
