### ISSUE TITLE
[Encounter] Thaddius

### ISSUE THREAD

**Issue by AlbanLHC** [dalaranwow/dalaran-wow#1283]
1. Magnetic Pull (Cast by Stalagg and Feugen) sometimes doesn't throw the tank all the way, resulting in the tank being thrown down in the ooze.

2. Stalagg and Feugen do not respawn after a wipe on Thaddius, resulting in the encounter being impossible to start again.

3. It is possible that negative polarity deals damage to negative polarity, and that positive polarity deals damage to positive polarity. (not tested thoroughly)

source: http://www.wowwiki.com/Thaddius

**Comment by Golganeth** [comment]
#1415

**Comment by TeridanDW** [comment]
Hello,
I would like to point out that the 2 charges (positive and negative) are working properly now, but are not removed from players when thaddius dies, which leads to deaths if someone moves after boss is killed.
Workaround is waiting the duration of the debuffs to end.
