### ISSUE TITLE
[Object][Classic] Less Bloodstone Deposit

### ISSUE THREAD

**Issue by Crispybuilt** [dalaranwow/dalaran-wow#1286]
**Object: Less Bloodstone Deposit** - 2653
- **Issue present:** Object is currently unavailable to players since they cannot see it, even Game Masters can not see the objects for some reason. They exist in the game and are spawned, but simply not visible for some reason.

There are currently 29 spawned Nodes across that cave.
- **How it should work:** Players should be able to see the nods and mine them.

---

http://wow.zamimg.com/uploads/screenshots/normal/2574.jpg
http://www.wowhead.com/object=2653/lesser-bloodstone-deposit
http://wotlk.openwow.com/object=2653

**Comment by Golganeth** [comment]
http://wotlk.openwow.com/quest=627

**Comment by TheRealestMcCoy** [comment]
I am trying to do the quest for these now. I saw 1 node and iron respawned in that place.

**Comment by Rushor** [comment]
DB/Gameobject: Reduce respawntime of Lesser Bloodstone Deposit Respawntime to 5 minutes

* closes https://github.com/dalaranwow/dalaran-wow/issues/1286
* 2223fa2a9d32128ca00a0cceeb12de2ae5a4ae12

note: the gameobjects are pooled, this means you will not find the same object after 5 min respawned on the same place. keep watching and walk through the cave to find another one

**Comment by TheRealestMcCoy** [comment]
So did you fix it or are you saying it was working as intended cause i sat in that cave for 1hr last nite to only find 2 nodes total in 1 hour.
