### ISSUE TITLE
[Algalon] Rogue: Shadowstep

### ISSUE THREAD

**Issue by Hatebugs** [dalaranwow/dalaran-wow#1287]
Shadowstep teleports rogue to the ground (nearest solid point below the target), which is incorrect - it must telepot rogue just behind the target (to the target's altitude).
How to reproduce: use shadowstep on flying assistant during duel.
This issue seems relative to core pathfinding\positioning system.

**Comment by Golganeth** [comment]
#1213

**Comment by Hatebugs** [comment]
I see issue got closed and referenced to "[Effect][Fear] Passing through the texture while feared" #1213 - I think its incorrect, because that one has completely different nature.
That way one day #1213 will get fixed, while #1287 stay closed and still not done.

In  #1287 i reported NOT the "pass-through-texture" problem, but issue is about wrong initial caster Z-coordinate calculation for shadowstep or it's later correction by the unit positioning system: current logic assumes that player as non-flyable unit should be position to the ground - which is incorrect, because player can also swim or just be in the air (starting to fall after shadowstep is done)).

**Comment by Golganeth** [comment]
You're absolutely right, my bad. Thank you for pointing that out.

**Comment by robinsch** [comment]
@Lothloryen Working on PTR.

**Comment by Rushor** [comment]
Already working on PTR. After further merges the fix will be applied on he live realm.
