### ISSUE TITLE
[Hunter] Spell - Bestial Wrath

### ISSUE THREAD

**Issue by moliskrc** [dalaranwow/dalaran-wow#1289]
http://www.wowwiki.com/Bestial_Wrath
Send your pet into a rage, causing 50% additional damage for 10 sec and breaking all effects which cause loss of control of your pet.

How it works:
When you use Bestial Wrath when your pet is not in your line of sight, it uses skill's cooldown, but you don't get the buff and your pet doesnt get the buff too.
http://s27.postimg.org/6b7yv5x03/Wo_WScrn_Shot_022714_214855.jpg

How it should work:
If your pet is not in your line of sight, then you shouldnt be able to use this skill at all, and if you press it - a message should appear - "you cannot use this skill now(yet)" and it should not consume the skill and begin the cooldown.
You should be able to use this skill only when your pet is in your line of sight.

I guess its another los issue.

**Comment by Demlock** [comment]
I have noticed it working as intended as of late. I can't use the spell while my pet is out of sight so you might want to check up on that, test it and close the thread .

**Comment by robinsch** [comment]
On PTR.
