### ISSUE TITLE
Quest: King of the Foulweald

### ISSUE THREAD

**Issue by Crispybuilt** [dalaranwow/dalaran-wow#129]
Quest King of the Foulweald - 6621

Issue: The quest item which is provided with the quest doesn't work when you use it on the correct location, it will not count as a completed quest.

The even doesn't start to protect the banner also from the wave of the mobs (including a mini boss on the end)

Temporary solution: I spawned the NPC on top of the hill (near where you have to place banner) and also reduced his re-spawn time from 5 minutes to 3 minutes. (Players can now kill the Chief and loot the quest item and therefore complete the quest)

This is how the event has to work: http://www.youtube.com/watch?v=qjpqeP9vo5U

**Comment by meowmewo** [comment]
Confirmerd

**Comment by Rushor** [comment]
need merge of https://github.com/TrinityCore/TrinityCore/pull/16493

**Comment by Rushor** [comment]
179bc4531f1c9fcb280feb0df194bb9db29af408
- the waves will now attack the banner and try to destroy it
