### ISSUE TITLE
Calendar event management totally bugged on Algalon (and possibly on Kirin Tor)

### ISSUE THREAD

**Issue by dsafer** [dalaranwow/dalaran-wow#1293]
Therer are numerous bugs regarding calendar event creation & management on the Algalon server (and probably on Kirin Tor too):
- When I update or create the event, the event's time is reduced by 1 hour. Eg.: I want to create an event at 19:00, it will create it 18:00.
- Participants appaer multiple times on the list (including me, who creates the event). Removing one of the multiplicates removes all, but changing invitation status only changes one of them. Also, the icons where you can see how many players you have from each class counts the multiplicates too.
- The events randomly disappear on logout, or when I create a new event. Sometimes all events disappear, sometimes only a few.
- When I can actually create multiple events, it usually mixes invitations between the events. Also, updating one event often changes the others to look exactly like the one I wanted to update. On logout, only one of these events stays in the calendar, the rest disappears.
- Once a single participant disappeared from the list. No, it was not removed by the player.
- Today a new event appaered in my calendar, created by the leader of another guild. Only me and my guildmates, who have applied to our guild's event - which disappeared- were on that list. Their status was set to "Confirmed", just like on our disappeared event. Because our event disappeared from the calendar, it seems that we have been moved to the event of the other guild, possibly kicking them from their event. Also, the time "I've responded on" was set to January 1, 2000, 01:00 on this event.

**Comment by Rushor** [comment]
fixed with https://github.com/TrinityCore/TrinityCore/pull/14924
