### ISSUE TITLE
Death knight: Raise Dead

### ISSUE THREAD

**Issue by allegiance** [dalaranwow/dalaran-wow#1295]
After summoning your ghoul, the icon becomes greyed out and doesnt start the cooldown, it only seems to be resetting when logging out or dying.

**Comment by epaulito** [comment]
Bug is active as of now, here are screenshots. I haven't been able to resummon my ghoul until after I have left the instance. The skill has been grayed-out the entire time when my ghoul died.
![wowscrnshot_050716_195111](https://cloud.githubusercontent.com/assets/18262684/15092033/abd7026c-148f-11e6-81fe-1d38e62f5834.jpg)
![wowscrnshot_050716_195112](https://cloud.githubusercontent.com/assets/18262684/15092035/b5d2ba9a-148f-11e6-8190-b5a82de01c96.jpg)

**Comment by Golganeth** [comment]
Tested and confirmed. Reopening

**Comment by Golganeth** [comment]
Bug should be fixed since last maintenance, feedback is welcome.

Closed
