### ISSUE TITLE
Quest: The Battle of Darrowshire - Roleplay Past Event

### ISSUE THREAD

**Issue by Crispybuilt** [dalaranwow/dalaran-wow#130]
Quest The Battle of Darrowshire - 5721

Issue: The quest item, "Relic Bundle", cannot be placed on the location where its supposed to start the epic event full of roleplay.

This is how the event has to work:
http://www.youtube.com/watch?v=mRAC-SpS7Po

**Comment by n-ghost** [comment]
Still an issue.

**Comment by muffybg** [comment]
Still not working, just says "Darrowshire Square required"

**Comment by Lothloryen** [comment]
Hello there,

This quest shall be working with the next update.

Thank you very much.

**Comment by n-ghost** [comment]
#lothforpresident

**Comment by Rushor** [comment]
na the script is from trinity ^^
