### ISSUE TITLE
[Hunter] Talent rapid recuperation grants no mana from killing mobs (with talent rapid killing)

### ISSUE THREAD

**Issue by Hedonistus** [dalaranwow/dalaran-wow#1310]
As stated in the title you get zero mana when you kill mobs (that give exp or honor) when you have both those talents. It simply says "You gain Rapid Recuperation" but no mana gained. It should grant you 2% every 2 seconds for 6 seconds.

It's quite a big deal for MM hunters I'd say =)

**Comment by Vaxsysl** [comment]
The issue is still present, poof.

**Comment by robinsch** [comment]
On PTR.
