### ISSUE TITLE
Brann Spankin' New

### ISSUE THREAD

**Issue by Alastia** [dalaranwow/dalaran-wow#1319]
The Achievement works but there is an invisible and unassailable mob in the middle of the room, the only way to kill it is with retribution aura ( you have to do it or brann will take damage)

![wowscrnshot_030714_104813](https://f.cloud.github.com/assets/6248803/2355816/3a5754c6-a5e1-11e3-95c1-da301f244026.jpg)

**Comment by roots84** [comment]
Invisible mob is still there and attack Brann sometimes (2 times out of 6 visits)

**Comment by Golganeth** [comment]
Again an issue, reopening

**Comment by Golganeth** [comment]
Fixed.
