### ISSUE TITLE
Spell: Sacred Shield

### ISSUE THREAD

**Issue by Vekt** [dalaranwow/dalaran-wow#1320]
Sacred Shield doesn't proc on DoTs !

http://wotlk.openwow.com/spell=53601

**Comment by zozefin** [comment]
indeed and not only dots even from aoe damages and turrent/vecicle damage,please fix that.. Spriests and locks are having major advantage vs palas.Its so frustrating when you are about to heal yourself but dying from dots which if sacred shield would proc correctly you could actually survive:(

**Comment by Zibathy** [comment]
here's a fix: remove paladin from the game because it's the worst class ever made

no need to thank me

**Comment by robinsch** [comment]
Tested, working fine.
