### ISSUE TITLE
Quest: Convocation at Zol'Heb

### ISSUE THREAD

**Issue by Artannis** [dalaranwow/dalaran-wow#1322]
After the Prophet of Akali reaches 75% hp and becomes immune,Har'koa should spawn and join in on the fight as seen here http://www.youtube.com/watch?v=EBTPnGj1Etg

On Algalon she doesn't spawn which makes the fight impossible to finish because of the Prophet's immunity.

http://www.wowhead.com/quest=12730
http://wotlk.openwow.com/quest=12730

**Comment by Cone182** [comment]
Tried today, unattackable under 75%.

**Comment by mephorash** [comment]
I tried it today, it didn't work when i tried it the first time. When i tried it for the second time i made him stay inside the summoning circle zone and everything worked(it might be related). Also made my pet go to passive when he went immune the second time(my pet was not effected by the aoe stun).

**Comment by daxpedda** [comment]
I can confirm that, if let him stay inside the summoning circle everything works just fine.

**Comment by Acillius** [comment]
Just did this quest today and you get stuck in a perma stun lock and Har'Koa does not come to help.

**Comment by Acillius** [comment]
Just so people are aware you need to stand in the circle to complete this otherwise it will bug out.

**Comment by ImprezaWoW** [comment]
Only a minor issue, but if you die on Prophet of Akali before the 75% mark, he will be untargettable and if you summon a new one, the untargetable duplicate will stand around there. Meaning if you wipe there a lot, you will see many Prophets of Akali spawned in the spot.

**Comment by Thimoteus** [comment]
I've killed him twice (with Har'koa showing up) but the quest still doesn't complete.

**Comment by jonanone** [comment]
Now Prophet of Alkali can be killed outside the summoning circle and everything will work as intended.

This update will be applied to the live realm soon.
