### ISSUE TITLE
[Quest] Are we there, yeti? Part 3 works, but the npcs dont say their texts

### ISSUE THREAD

**Issue by wonopon** [dalaranwow/dalaran-wow#1329]
The quest Are we there, Yeti? (http://wotlk.openwow.com/quest=5163) works but the npcs involved do not say the text they are supposed to, depriving the quest of its humorous aspect!

All the texts can be found here http://www.wowwiki.com/Quest:Are_We_There,_Yeti%3F_(3).

**Comment by Demlock** [comment]
Confirmed

**Comment by Rushor** [comment]
https://github.com/TrinityCore/TrinityCore/commit/2f6754f8d2c15954beeeb0547ee984cb9f2720e0

**Comment by n-ghost** [comment]
Works like a charm now.
