### ISSUE TITLE
Lots of basic rune mechanic issues

### ISSUE THREAD

**Issue by yeknom366** [dalaranwow/dalaran-wow#1337]
Problem: Talents Blood of the North (tested), Death Rune Mastery (tested), and Reaping (not tested) will generate death runes on use, but if a death rune was used, it will revert to it's original rune.  

Example, I have 2 death runes from Blood of the North that were originally blood runes.  If I use blood strike or pestilence, the death rune becomes a blood again.  it is supposed to remain as a death rune.  Same thing was seen for Death Rune Mastery, and I would assume Reaping, though I have not tested it.

Problem: Death runes not being smart on use.  

Example:  If I obtained 4 death runes (2 from frost, 2 from unholy) via Death Rune Mastery, and I use death strike it will automatically use the unholy ones first.  It should use the death runes in a manner that it uses the ones connected to the original rune cost first.  Rather than using both unholy, it should use 1 unholy and 1 frost.  As of now, the precedence for original rune use for death runes is blood, then unholy, the frost.

Problem:  Rune cooldown grace period not working.  All runes have a 10 second cooldown, but there is supposed to be a grace window coming off of cooldown up to 2 seconds.

Example:  If a rune came off cooldown, and I immediately use it, it will incur the usual 10 second cooldown.  However, if I am delayed in using it for 2 seconds, the cooldown should be reduced to 8 seconds.  Similar if delayed for 1 second, cooldown should be 9.  The cooldown should be 10-x, where x is the delay time, capped at 2 seconds.  Without this, frost loses a lot of damage due to the inability to use Glyph of Disease, and all specs will lose damage and/or threat.

Problem:  Death runes reverting to their original runes while in combat.

Example:  I use a blood strike to generate a death rune, and it will become a blood rune again after 30 seconds of not being used.  This should only happen while out of combat, but still does occur in combat.

**Comment by taralej90** [comment]
I came looking EXACTLY for this report. Here is the ALL the information you need to fix the rune grace issue:

http://forums.elitistjerks.com/topic/93308-dk-mechanics-discussion/page-2

https://gitlab.com/trinitycore/trinitycore/commit/ec59c3ab0377f4077a2d63e7b242f2a3693dd2d4

https://gist.github.com/Morgoporc/8536210

https://gist.github.com/Morgoporc/8558019

Warmane took and applied these fixes just yesterday and have deemed the bug fixed now. I will personally test it there tonight and come back with feedback. YES, I know I'm not supposed to take fixes from other servers, but these are official TrinityCore fixes and EJ knowledge base so it doesn't count, plus they're not the authors of the fix.

Golganeth, Lothloryen - it's up to you now, guys.

**Comment by taralej90** [comment]
Fix the issues in this perfectly written report ( @yeknom366 really gj, mate) and DKs will be one VERY big step towards being blizzlike.

**Comment by taralej90** [comment]
Got my hands on a PC with 3.3.5 on it and I can say the rune grace period WORKS. Good job :)

**Comment by robinsch** [comment]
> Problem: Talents Blood of the North (tested), Death Rune Mastery (tested), and Reaping (not tested) will generate death runes on use, but if a death rune was used, it will revert to it's original rune. 
On PTR.

> Problem: Death runes not being smart on use
Can't confirm

> Problem: Rune cooldown grace period not working. All runes have a 10 second cooldown, but there is supposed to be a grace window coming off of cooldown up to 2 seconds.
On PTR.

> Problem: Death runes reverting to their original runes while in combat.
Proof please.
