### ISSUE TITLE
NPC: Mai'Zoth

### ISSUE THREAD

**Issue by Crispybuilt** [dalaranwow/dalaran-wow#134]
NPC Mai'Zoth - 818

Issue: NPC Spawn time was wrong (he had 30 minutes while the respawn max time is 5 minutes)

Issue has been resoloved by setting up his timer to 5 minutes according to WoWhead and OpenWoW.

**Comment by SadhuArch** [comment]
Not sure what happened to his spawn timer but a rogue killed him right before me (I watched it) and I've been waiting for at least 15 minutes now. So something is up with the respawn timer again.

**Comment by catta000** [comment]
Confirmed - NPCs in the cave including Mai'Zoth still respawn after 30 minutes, not 5.

**Comment by shilofax** [comment]
This is still bugged as of 12/14/2017

**Comment by TeridanDW** [comment]
Hello,
The respawn timer is reduced to 5 mins.
