### ISSUE TITLE
NPC: Shadowstalker Getry [25729]

### ISSUE THREAD

**Issue by Golganeth** [dalaranwow/dalaran-wow#1341]
**Issue:** Players can't interact wth him for the quest "Get to Getry" if someone has done recently "Foolish Endeavors". The NPC will just stand outside the building doing nothing.
The NPC should get force-killed or reseted back to the top of the building once the event is over.

The NPCs/event get stuck if:
- A player dies while fighting Varidus the Flenser.
- A player talks to Getry and starts the event while Varidus is dead.

http://wotlk.openwow.com/npc=25729
http://wotlk.openwow.com/npc=25618

**Comment by sspecterr** [comment]
It is not fixed. It is still bugged...

**Comment by Omuno** [comment]
as of today July 23rd its still bugged like Golganeth's Post

**Comment by nyrpha** [comment]
as of 20-09-2015 this bug still happens. i saw a player who was doing the quest die, and now getry just stands around doing nothing exactly like in the screenshot above. i checked again every hour or so, and it has been this way since yesterday.

**Comment by Oelacs** [comment]
Still bugged. The Npc just stands at the edge of the field and you cant interact with him.

**Comment by DrFuler** [comment]
[04/03/2016] - Still bugged.

**Comment by NovaHiros** [comment]
This quest is bugged since forever - why don't you add a "manual" reset button for Getry - by speaking to him with a bouble or something like that

**Comment by akirus67** [comment]
Still bugged.

**Comment by Lothloryen** [comment]
Hello there,

I have added a correction which will be deployed after the next realm restart. Any feedback will be welcome.
