### ISSUE TITLE
[Quest] Root Samples

### ISSUE THREAD

**Issue by Lanrutcon** [dalaranwow/dalaran-wow#1349]
Currently...the quest is impossible to complete...

Reason:
Herbs from The Barrens don't drop the quest-item...and it should be 100% drop...

More info:
http://wowpedia.org/Quest:Root_Samples
http://www.wowhead.com/item=5056#comments

**Comment by Zantu** [comment]
At level 80 and taking every flower I have seen in Barrens, I still only have 6 of these. It is broken.

**Comment by Rushor** [comment]
already fixed with https://github.com/TrinityCore/TrinityCore/commit/f060b8f6b82f74f21a7e7d1812bc94336ebadb52
