### ISSUE TITLE
NPC: Gahz'rilla

### ISSUE THREAD

**Issue by Crispybuilt** [dalaranwow/dalaran-wow#135]
NPC Gahz'rilla - 7273

Issue: If you wipe on the boss, he will despawn and you can't resummon him with the gong.

You should be able to re-summon him again.

**Comment by Rushor** [comment]
https://github.com/TrinityCore/TrinityCore/commit/cec05ff07d1751649b6eecff07f23f52ca5443cd

fixed long time ago
