### ISSUE TITLE
Malygos - Official Developer Report 

### ISSUE THREAD

**Issue by Crispybuilt** [dalaranwow/dalaran-wow#1366]
**This is a detailed overlook and report for the full Malygos encounter which goes into pure details.**
- _What is different,_
- _What has to be corrected,_
- _How it should work properly and simillar._

**Content is taken directly from the game testing, multiple reports from players, VPN internal testing and so on.**
- _Please use this thread to report all the issues about Malygos, anything that I have missed, please add it here in the comment section below._

---

**Pre-phase Intro Issues**

> - After a wipe, **Malygos** will respawn and will start flying around as usual, saying his quotes and start opening portals. But this time, when he flies around to interact with spark portals, he will stutter in the air slowly, which breaks his animation of flying around. It should be reseted properly and reapplied at Z coordinate. _(This works fine the first time before you attempt him, it only happens after a wipe and Malygos is respawned.)_

**Phase 1 Issues**

> - Vortex which should pick up the entire raid only picks up one person at the moment. He is getting damaged as he should and the player can cast instant spells as intended.
>   - Vortex is missing one big major animation at the moment. There are small visual sparks flying around him when he picks up a player. They are more like lighting storm sparks which can be seen around Malygos.**That is at the moment completely missing.**
> - How it should work: http://youtu.be/J81w3FFcojs?t=3m31s
> - How does it work at the moment: http://youtu.be/3-u5v2RwC5U?t=50s
>   - Vortex should drop a player down when it's over and roughly do 10 000 damage, **that currently works as intended.**
> - After the Vortex is and animation is over, all the players will lose combat and re-enter the next second for some reason, making this slightly easier, since things such as potions can be used again. **That should currently not be the case and should not happen.**
>   - Vortex should be delayed a bit (starts 3 seconds after Malygos flies to center, not instant like here on Dalaran WoW) before starting to being active: This is due the quote he says before picking up players (check quote report down below). **This is not working as intended.**
> - Spark moving animation: When the Spark spawns, it doesn't have a smooth animation flying to Malygos's platform, but it keeps stuttering in the air slowly, simillar when Malygos respawns after a wipe. This is a minor glitch with movement at the moment. Which in conclusion makes me thinking: most of the spawned NPCs which fly and have Z coordinate and waypoints will act like this and stutter in the air. **This is currently not working as intended**
>   - Spark is currently eaten by Malygos slighty faster than retail, small visual issue most likely. Statement above would fix this for sure.

.**Phase 2 Issues**

> - If the Nexus Lord's are Death Gripped by Death Knight when they are still flying and landing down, they will glitch out and it will be impossible to kill them. It should be the best to put immunity masks on them to prevent that. **Minor glitch that should be fixed**
> - Scions of Eternity move slightly too fast than retail at the moment, I'd say 5% to 10% faster than they should. Their speed should be reduced significally.
>   - Scions of Eternity DO NOT drop their Hover Disks at the moment which allows more players to fly around. Only Nexus Lords do that at the moment. **This doesn't work as intended since they should make them available and usable for players, correct me if I'm wrong.**
> - **WoWWiki Quote:** _When one dies, it will drop its disc to the ground, allowing melee classes to fly up and engage them._
> - Deep Breath animation: Currently the animation happens, but it is not on the ground but for some reason in the air at his mouth directly, like there is invisible barrier up there for some reason. Most likely invisible world barrier at coordinate Z is glitching this out, 99% sure. **This doesn't work as intended, the breath should hit the ground. This was working on Kirin Tor just fine.**
> - How it should work: http://youtu.be/J81w3FFcojs?t=7m24s
> - How does it currently work at the moment: http://youtu.be/3-u5v2RwC5U?t=4m2s
>   ![image](https://f.cloud.github.com/assets/5054924/2457015/722180fa-af2a-11e3-8d42-722a5d15c536.png)
> - Hover Disk: Currently after a person picks up the disk he can leave it and jump on it again infinite time. But only one person for the end of the fight, because it doesn't let other players to use it if someone already used it before at least once. **This should be corrected as well.**
>   - After leaving Hover Disk: it should always drop down at the ground from any Z coordinate, which currently doesn't happen. You can leave it in the mid air and then you won't be able to get on it again because it's too high.

**Phase 3 Issues**

> - Dragon abilites: 
>   - Flame Spike - **Works as intended**
>   - Engulf in Flames - **Works as intended**
>   - Revivify - **Works as intended**
>   - Life Burst - **Works as intended**
>   - Flame Shield - **Doesn't work at all, I've tried using Shield having energy, not having energy, targeting my drake, targeting Malygos, targeting another friendly drake, targeting my character, targeting pets, it didn't work. If I target Malygos the button is visible and available, but when I try to use it, it says: "No target"** However, if you target drake, the button is grayed out and you can't use it.
>   - Blazing Speed - **Works as intended**
- How the shield should work: http://youtu.be/LBZOqpvgpgw?t=4m17s - look at the drake in the upper left surrounded by red shield .
- Finishing move to protect your drake. Shield surrounds you reducing all damage taken by 80% and lasting up to 6 seconds for max combo points. Costs 25 energy with a 30-second cooldown. You must be targeting someone and have combo points on them to use this ability!
  This can be used on yourself or a friendly drake as well.

**Outro Issues - Malygos's Death**

> - When Malygos dies, he doesn't have animation of falling down into Z coordinate slowly and then despawning, but instead he dies and does animation of normal death as he would die normally standing on the ground. **That should not happen**
> - How it should work: http://youtu.be/J81w3FFcojs?t=11m28s
> - How does it currently work at the moment: http://youtu.be/3-u5v2RwC5U?t=7m20s
> - If a player on a dragon dies, he will fall down into abyss until he dies, his release button will however be grayed out, so he has to do /reload to release.
> - The method that would fix loot issue with those not in range: Make an invisible platform just below Malygos where players fall down and die, but still be in range to recieve achievement and be eligible for the loot. But, if they attempt to reincarnate or use soulstone, they would still die in the air.

**Issue with loot:**

> To avoid issue with loot, make sure that you are very near the looting object, heart and the Gift, or you will glitch it out.
> - **Quote from WoWWiki:** If you died during the fight, do not release until Alexstrasza finishes summoning the loot. If you do, you will not be allowed to loot.
> - Portal spawning / despawning: Currently the portal spawns which allows players to exit or enter the instance after Malygos's death. The issue is that is usable only ONCE by someone, and after that first usage, it will despawn. **That doesn't work as intended, the portal should stay spawned forever after Malygos's death.**.
> - When a player will try to return to the instance, and moves into the instance (after Malygos is dead on that ID), he should be automatically switched on the flying drake so he doens't fall into oblivion.
> - **Quote from WoWWiki:** The exit portal respawns, and you can fly over to it. The floor of the instance does not respawn.

**Quotes missings from Malygos and small issues:**

> - **Malygos is missing the following quotes:**
> - **Phase 1:**
> - When picking up people into Vortex:
>   - _Watch helplessly as your hopes are swept away..._
> - **Phase 2:**
> - When shooting bubbles at players:
>   - _I will teach you IGNORANT children just how little you know of magic..._
> - **Phase 3:**
> - When killing a drake or a player:
>   - _SUBMIT!_

---

Links and source:
http://www.wowwiki.com/Malygos_(tactics)
http://wotlk.openwow.com/npc=28859#abilities
http://www.wowhead.com/npc=28859/malygos

**Comment by npmusicftw** [comment]
It has been over 2 years now. One of your dominant claims about this server is the impeccable scripting of the raids. 

**This needs to be assigned and fixed immediately. This should be labeled as _critical priority!!**_

**Comment by MrAndersonX** [comment]
+ 1 bump. Experienced the Nexus Lord bug last night (http://www.wowhead.com/npc=30245/nexus-lord) where they cannot be attacked/killed if they are Death Griped. This prevented us from being able to complete the Eye of Eternity raid. A second time however, when a Nexus Lord was griped, he could only be attacked/killed by ranged players (donno how or why, but that's just how it went).
P.S. : We even waited for Malygos to kill us, and even with the Berserk buff active he dealt insane low amounts of dmg.

Ps of the Nexus Lord bug :

https://postimg.org/gallery/1p8w09au2/

**Comment by Rushor** [comment]
@MrAndersonX could you please summarise all mentioned issue in one post? this would help me to get a fresh update on the issues!

**Comment by MrAndersonX** [comment]
Sure, if I have some spare time tonight I will.

**Comment by Rushor** [comment]
we will continue the work on this in the new and fresh and detailed bugreport from https://github.com/dalaranwow/dalaran-wow/issues/3858. ty @MrAndersonX

**Comment by MrAndersonX** [comment]
You're very welcome. Glad to pull my weight to help you guys and give back what the server has given me for years. 
 Good luck and keep up the good work out there !
