### ISSUE TITLE
Sartharion - Official Developer Report

### ISSUE THREAD

**Issue by Crispybuilt** [dalaranwow/dalaran-wow#1367]
**This is a detailed overlook and report for the full Sartharion, Vesperon, Shadron and Tenebron encounter which goes into pure details.**
- _What is different,_
- _What has to be corrected,_
- _How it should work properly and simillar._

**Content is taken directly from the game testing, multiple reports from players, VPN internal testing and so on.**
- _Please use this thread to report all the issues about Sartharion, Vesperon, Shadron and Tenebron, anything that I have missed, please add it here in the comment section below._

---

**Vesperon:**

> - The only issue with Vesperon is that he won't despawn a portal sometimes after killing disciple inside and exiting out of the phase.
> 
> **Missing two unique rng quotes when opening portal:**
> _Aren't you tricky... I have a few tricks of my own..._
> _Unlike you, I have many talents._

**Shadron:**

> - The only issue with Shadron is that he won't despawn a portal sometimes after killing disciple inside and exiting out of the phase.
> 
> **Missing two unique rng quotes when opening portal:**
> _Father taught me well!_
> _On your knees!._
> 
> Also, his original aggro quote should be disabled if he is left alive and Sartharion is engaged. That is not the case at the moment. But it is with Tenebron and Vesperon which work flawlessly.
> **This quote should be disabled if engaged in 3D:** 
> _I fear nothing, least of all you!_
> He successfuly answers Sarth when he calls to him:
> _I will take pity on you, Sartharion, just this once._
> But 2 seconds after it will overlap his quote with his original quote which is a small mess, that's why original aggro quote must be disabled.

**Tenebron:**

> - The only issue with Shadron is that he won't despawn a portal sometimes after killing all 6 egg hatchlings inside and exiting out of the phase. Even if hatchlings come out, portal still won't despawn at that time.
> - **Hatchlings do not despawn if you wipe on Sartharion 1,2,3D or Tenebron individually. They should.**
> 
> **Missing two unique quote when opening portal:**
> _Arrogant little creatures! To challenge powers you do not yet understand..._
> _I am no mere dragon! You will find I am much, much, more...._

**Sartharion**

> **Flame Wall Issues:**
> - Flame works around 95% as intended, more or less but this is how it should work:
> 1. \- Spawn Flame Wall at point A
> 2. \- Wait for 2 seconds delay until Flame Wall Enlarges
> 3. \- Enlarge in size Flame Wall from 0.1 to 1 on a scale
> 4. \- Send Flame Wall to travel from point A to B
> 5. \- Stop Flame Wall
> 6. \- Wait for 2 seconds delay until Flame Wall Decreases
> 7. \- Decrease Flame Wall
> 8. \- Despawn Flame Wall at point B
> 
> How it should work: http://youtu.be/k6ZAuJIgHJc?t=55s
> How does it work at the moment: http://youtu.be/187iLZ9cxl8?t=4m45s
> 
> **Fire elemental Adds HP Issues:**
> - Health: 65165 (25), ~26,000 (10) 
> - Curently adds have around 68k hp on 10 normal, they should have 26k.
> - Not getting despawned on wipe when engaged in any mode which forces you to kill them after fight.
> - Lava elemental add's do not cross over into void zones when you go into them, but whelps do. **This has to be corrected, Lava Blazes should go around Void Zones.**
> 
> **Hitbox:**
> - Hitbox of Sartharion is way too small at the moment. It should be enlarged drastically so he can be attacked from a larger distance, but also his breath and tail wipe will hit in a larger cone.
> 
> **Soft Enrage:**
> - His Soft Enrage starts at 10% but it's delayed for 10 seconds at least. It should start right away when he hits 10%. He should also start spawning much more adds until the point you get completely overwhelmmed. Here it spawns barely few.
> 
> How it should work: http://youtu.be/k6ZAuJIgHJc?t=8m57s
> How does it work at the moment: http://youtu.be/187iLZ9cxl8?t=6m4s
> **You can see significant difference between the amount spawned on retail and here.**

**Loot Issues:**

> _Satchel of Spoils_ - Currently missing from table - Should contain 5 EoH and around 30 to 50g
> _Large Satchel of Spoils_ - Currently missing from table - Should contain 5 EoV and around 30 to 50g
> 
> **When engaging Sartharion in 3D or less, Vesperon, Shadron or Tenebron shouldn't drop any emblem if killed during the fight or the encounter will turn into emblem farmfest.**

**Invisible World Trigger Issue:**

> Tenebron Egg Controler. It's an invisible trigger damaging players and keeping them in combat, all the time. It has to remodified.
> 31138 - Tenebron Egg Controller - 10 MAN
> 31550 - Tenebron Egg Controller - 25 MAN
> https://f.cloud.github.com/assets/5054924/939976/8099fa2a-0121-11e3-8138-f392b50de2c4.png
> https://f.cloud.github.com/assets/5054924/939978/8979404c-0121-11e3-823a-7f5d6aa4c284.png

We have to make it non interactable with players.

**Spamming messages**

> - The general announce messages are currently broken for Sartharion and mini drakes, they will repeat and spam the same general message each time special ability is done by any of the drakes. It is coorespondant to the players in the raid, so if there are 5 players: 5 spamming message instead of 1, if there are 10, 10 messages. **That should be corrected as well**
> 
> For example: 
> Shadron Begins to Open a Twilight Portal! x10
> The Lava Surronding Sartharion churns! x10
> ---

Source: 
http://www.wowwiki.com/Sartharion
http://www.wowwiki.com/Vesperon
http://www.wowwiki.com/Shadron
http://www.wowwiki.com/Tenebron
http://www.wowhead.com/zone=4493/the-obsidian-sanctum
http://www.wowhead.com/item=43347#comments
http://www.wowhead.com/item=43346#comments

**Comment by Edzero** [comment]
25man Sartharion drops Emblem of Heroism instead of the Emblem of Valor that he should.

The 3 drakes drop Emblem of Valor as they should.

**Comment by Rushor** [comment]
DB/Creature: Satharion 25 man mode should drop Emblem of Valor

* closes: https://github.com/dalaranwow/dalaran-wow/issues/1367
* commit: 8e797c4cb1f56b08b3468f5685d0e7fbca6f4540

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
