### ISSUE TITLE
[Outland][Hellfire Peninsula][Alliance][Quest] The Finest Down

### ISSUE THREAD

**Issue by Akkalevil** [dalaranwow/dalaran-wow#1370]
The Kaliri Nests should spawn mob if interacted. They don't.

http://www.wowhead.com/quest=9420/the-finest-down

**Comment by Rushor** [comment]
This was already fixed on TC and it works on PTR.

https://github.com/TrinityCore/TrinityCore/blob/a249d86b00eb0854cb925f8bea76ddbb364208df/sql/old/4.3.4/TDB8_to_TDB9_updates/world/040_2014_09_22_00_world.sql

[![https://gyazo.com/45ee502c8c6fd55725fb9a77e77de9ce](https://i.gyazo.com/45ee502c8c6fd55725fb9a77e77de9ce.gif)](https://gyazo.com/45ee502c8c6fd55725fb9a77e77de9ce)
