### ISSUE TITLE
[Outland][Hellfire Peninsula][Alliance][Quest] Cruel Taskmasters

### ISSUE THREAD

**Issue by Akkalevil** [dalaranwow/dalaran-wow#1371]
The Dreghood brokens should not be hostile (yellow) until a taskmaster is aggroed nearby, and should stop the fight and flee once he's dead.

http://www.wowhead.com/quest=9399

**Comment by Rushor** [comment]
confirmed https://youtu.be/3HMC8tPoz8U?t=79
