### ISSUE TITLE
[Borean Tundra][Quest] Abduction

### ISSUE THREAD

**Issue by Akkalevil** [dalaranwow/dalaran-wow#1377]
The captured Beryl Mages in the quest don't despawn (or do so VERY slowly), ending up with no un-captured mage available.

Edit : after being able to finish it (probably some GM reset), I can detail more precisely the problems.

How it should work :
- You hurt a mage, then use the chain on him. It captures him, makes him friendly and makes him follows you. You then bring him back to the quest giver, which complete the quest.

How it does work :
- You hurt a mage, then use the chain on him. It captures him and make him friendly. BUT it immediately complete the quest, and doesn't necessarily makes him follow you (I had to re-use the chain to have him starting to follow).
Bringing him back to the quest giver does makes him despawn, but as the quest is already completed at capture and the fact that the mage doesn't always follow, it means that not all players will do so, creating a permanently friendly captured Beryl Sorcerer who will stay around and never despawn.

What needs fixing :
- The quest shouldn't be marked as completed until the mage is brang back to the quest giver. The mage should always start to follow the player at capture, and if he can't, he should despawn.

**Comment by Lothloryen** [comment]
Hello there,

This issue has been fixed and it will work in a Blizzlike way after the next scheduled maintenance (not restart).

Thank you very much.

**Comment by Chmielok** [comment]
Doesn't work again.

**Comment by Focused12** [comment]
If you can get one of the REGULAR mages.. NOT the ones provided.. the REGULAR ones that you can attack, to 25% HP and then use the quest item this will complete!!!! Have done this on 2 different toons now!  Thank me later
