### ISSUE TITLE
 [Borean Tundra][Quest] Abduction 

### ISSUE THREAD

**Issue by bho72285** [dalaranwow/dalaran-wow#1381]
I understand this was answered at  [Borean Tundra][Quest] Abduction #1377, but please, take another look at this.  A glance in game can clearly show things are not working properly.

The quest IS completable, but once all of the Sorcerers have been captured, no one else is able to do this.  I've stuck around for over an hour today to ensure that these mobs never despawn and respawn as uncaptured sorcerers.  

You can witness this in a broken state right this moment.

**Comment by Lothloryen** [comment]
Hello there,

This issue has been fixed and it will work in a Blizzlike way after the next scheduled maintenance (not restart).

Thank you very much.
