### ISSUE TITLE
[Mechanic] Dot snapshotting

### ISSUE THREAD

**Issue by NaturelSin** [dalaranwow/dalaran-wow#1382]
What is dot snapshotting?

> Once a DoT is applied it will "snapshot" your current Attackpower/Spellpower and for the entire duration of the DoT the damage will remain the same ( It will remain static )
> 
> > The only exception to this are "on target debuffs." What i mean by that is Mangle ( 30% bleed damage ), (Any increased/decreased spell resistance (Chromagus BWL)), ( percentage damage reduction, amplify ( Barkskin / Evocation (Kurator Karazhan)) to name some examples.

How does it currently work?

> Once you apply the DoT, it will recalculate the damage value for every tick. First tick with 200 AP will do 450 damage, second tick ( you procced a trinket ) with 400 ap it will do 600 damage. Trinket falls of, your dot is back to 450 damage with 200 ap. ( It is currently dynamic )

How it should work?

> If you apply a DoT with 400ap, it will always tick for 600 damage. Even if you lose/gain some AP/SP during its duration. If you reapply it while its still running, the DoT will "snapshot" your AP/SP again  and it will continue to tick for its (possibly modified, if increased AP/SP compared to the snapshot from before) damage values.
> 
> > The only exception to this are "on target debuffs." What i mean by that is Mangle ( 30% bleed damage ), (Any increased/decreased spell resistance (Chromagus BWL)), ( percentage damage reduction, amplify ( Barkskin / Evocation (Kurator Karazhan)) to name name some examples.

Exceptions on reapply values

> Serpent sting retains the % damage bonuses (as well as crit for those using 2pc T9) from whenever it is first applied and does not automatically update these to current values when refreshed with Chimera Shot. This means that if you have significant temporary damage bonuses applied it may be worthwhile to lock them into your serpent sting by manually refreshing it while those bonuses are up. However keep in mind that whenever you do this you're sacrificing a GCD for this purpose that could be spent on another shot, so you should only do it if you expect the sting to last a significant period of time (at least 2 minutes). If you have the 2pc T9 bonus you may want to also use a Potion of Wild Magic before refreshing the sting to further increase the crit applied to your sting.
> 
> > This is taken from an EJ guide for 3.3 MM hunter. Its special in this case cause chimera doesnt take a new snapshot from your AP/SP, instead just resets ur serpent sting duration.
> > 
> > > This is also the only exception I know of. There might be others out there.

Affected spells the Author currently knows of and has tested it.

> Shadow priest DoT effects (Shadowword: Pain, Vampiric Touch, Devouring Plague ) tested by Infame
> Feral druid DoT effects ( Rake, Rip, Pounce, Lacarate ) tested by Naturel
> Balance druid DoT effects (Insect swarm, Moonfire )
> Fire mage DoT effects ( Living bomb, Fireball, Frostfireball ) tested by Elevay
> Hunter DoT ( Serpent sting, Black arrow, Explosive Shot ) tested by Queezie
> 
> > The list probably goes on for every dot, including pets and traps.

Sources

> http://forums.elitistjerks.com/topic/97220-the-mm-hunter-in-33/
> http://us.battle.net/wow/en/forum/topic/10497380331 (WoD removes snapshotting as a mechanic, basicly "nerfing" it to what it is on Dalaran WoW)
> http://eu.battle.net/wow/en/forum/topic/9388548781 (WoD removes snapshotting as a mechanic, basicly "nerfing" it to what it is on Dalaran WoW)
> http://www.youtube.com/watch?v=R33bupRzWYQ ( This is a guide on how to snapshot in mop )

What is a dot?

> http://www.wowwiki.com/Damage_over_Time

**Comment by Lothloryen** [comment]
Hello there,

This mechanic has been implemented. Any feedback will be welcome, thank you.

**Comment by Dolmio1** [comment]
Reopen please

**Comment by Winstrol** [comment]
hunter serpent sting snapshotting doesnt work.

**Comment by v2b87** [comment]
In my experience I've found that snapshotting does work for the full duration of the spell (e.g. corruption) with both your haste and spell power taken into account. What I've found doesn't work is that when you refresh the corruption with shadowbolt/haunt e.t.c. it also refreshes the snapshot, so you cant maintain that big beefy corruption you cast with spellpower procs + eradication + BL/Hero e.t.c.
I'm pretty sure in retail it was supposed to retain the original snapshot if you refreshed it with another spell, and if you wanted to refresh the snapshot you had to manually recast corruption. Maybe i'm wrong though.

**Comment by tyler200100** [comment]
I don't have screenshots at the moment but I can confirm that Rupture does snapshot properly.

**Comment by WellGeez** [comment]
Serpent Sting should retain the AP buffs even when when you refresh with Chimera Shot and it does not
short video showing it does not; https://youtu.be/e70JEVnznmk

**Comment by Coztume** [comment]
@WellGeez No it should not. Refreshing Serpent Sting with Chimera Shot should update it to your current AP value. Proof: http://www.warcrafthuntersunion.com/2009/12/chimera-shot-secrets-for-mm-hunters/
