### ISSUE TITLE
[Warrior] Item: Heroes' Dreadnaught Battlegear's 4 piece bonus

### ISSUE THREAD

**Issue by Rathyan** [dalaranwow/dalaran-wow#1387]
Set bonus spell: http://wowhead.com/spell=60176
Buff's name: http://wowhead.com/spell=61571

Sometimes when using an ability and having this buff up, the buff doesn't go away even though the rage reduction is gone. The UI will still show you that your abilities cost 5 rage less but when you cast them, they'll cost the original points of rage.

At first I thought it was Victory Rush causing this since it doesn't cost rage but then I found out that even offensive abilities that cost no rage make the buff disappear!

Also the spell seems to proc very very few times. It's supposed to be 10% proc chance with no internal cooldown (http://wowhead.com/spell=60176) and with deep wounds rolling the whole time, should be up at least every 3-4 seconds where I see it pop only once every 10 -ish seconds

**Comment by robinsch** [comment]
Is this still a thing?
