### ISSUE TITLE
[Borean Tundra][NPC] Kara Thricestar

### ISSUE THREAD

**Issue by Akkalevil** [dalaranwow/dalaran-wow#1395]
Kara Thricestar is the flightmaster in Fizzcrank Airstrip, but she doesn't provide gryphon transport.

![karathricestarbug](https://f.cloud.github.com/assets/6848735/2513877/d10509bc-b433-11e3-8b9b-7857bff9a128.jpg)

**Comment by Golganeth** [comment]
Works fine.
