### ISSUE TITLE
Quest: Redemption (Draenei Paladin Ressurection)

### ISSUE THREAD

**Issue by Kannibrawne** [dalaranwow/dalaran-wow#1396]
**Quest** - Redemption - *ID: 9600*
**Quest Giver** - Jol - *ID: 17509*
**Quest Item** - Symbol of Life - *ID: 6866*
**Quest Item Target** - Young Furbolg Shaman - *ID:  17542*

* Issue: Resurrecting the Young Furbolg Shaman with the Symbol of Life does not give credit for completion.

**Comment by Woider001** [comment]
Late reply, but I can confirm the quest works as of the latest patch, and you're able to learn your resurrection spell.
