### ISSUE TITLE
[Northrend][Borean Tundra][Mob] En'kilah mobs

### ISSUE THREAD

**Issue by Akkalevil** [dalaranwow/dalaran-wow#1397]
The blood globe are NPC in the sense that you could strike them, but they should neither:
- Move.
- Attack you.
- Give XP.

For now they do all three of these things.
http://www.wowhead.com/npc=25534/enkilah-blood-globe#comments

- The abominations don't use (have ?) their abilities. Especially noticeable for the hook, which they should use to bring you closer when you're out of range.
http://www.wowhead.com/npc=25383#abilities

**Comment by Golganeth** [comment]
Fixed.
