### ISSUE TITLE
Quest: Ghost-o-plasm Round Up

### ISSUE THREAD

**Issue by Crispybuilt** [dalaranwow/dalaran-wow#140]
Quest Ghost-o-plasm Round Up - 6134

Issue: When you place the item on the spot it doesn't summon any Magrami Spectres which are needed to complete the quest.

Magrami Spectre - 11560

Temporary solution: I spawned 10 Magrami Specters around the area so players can  atleast kill them and pick up the quest items. (Respawn time is 5 minutes)

**Comment by n-ghost** [comment]
The quest is very glitchy atm: you can't use a Crate of Ghost Magnets anywhere, there is no targetable ghosts available and sometimes you get killed by INVISIBLE AND UNTARGETABLE ghosts that you can see/target only when they reset. Also, you can't loot them even if you manage to kill them with AoE.

**Comment by Rushor** [comment]
https://github.com/TrinityCore/TrinityCore/commit/977c517392198043b42c7a6426272400e80264c4

**Comment by Rushor** [comment]
14 Mar 2015

so added long time ago
