### ISSUE TITLE
Quest: Hell Hath a Fury

### ISSUE THREAD

**Issue by mupske** [dalaranwow/dalaran-wow#1401]
This quest is broken (Zul'Drak). You are supposed to use the quest item on the High Priestess. When you use the questitem on High Priestess Tua-tua, it says: 'Invalid Target'.

**Comment by Mantigora** [comment]
Quest works fine. Make sure mob have Quetz'lun's Hex debuff after using item on him.

**Comment by blackeaglebr** [comment]
About Hell hath a fury quest.

High priestess hawinni is inside the terrain, I could target, hit, used the item, but dosent worked to me.
High priestess Tua-tua is here, on 73,60 casting something and when I use the item a invalid target appears.
High priestess Mu'funu was with 1 health and I used the item sucefully

**Comment by Kaporalhart** [comment]
Hawinni worked as intended for me (he's underground, but whatever) Mu'funu had 1 health so i just had to use the item and i got the credit. But Tua-Tua does not have a health bar above her head. Like Mu'funu she has only one health and seems to be casting something, but you can't use the item on her, it says "invalid target".

**Comment by Arrowzinger** [comment]
![wowscrnshot_082515_065243](https://cloud.githubusercontent.com/assets/13681885/9464960/5cdafa0a-4af6-11e5-86d5-f341a6e153dd.jpg)

Still broken, sure it works on server restart.

**Comment by Taffa2** [comment]
Not 100% fixed.  Was able to do Mu'funu and Hawinni.  But Tua-Tua is stuck on 1 life and is doing a casting action.  If you attempt to use the hex stick on her it says 'invalid target'.

**Comment by Linandir** [comment]
Does not work. Might be that everybody on the server have to race to complete this quest in order to get all 3 after a restart since that will respawn the questmobs. I tried this again yesterday and all mobs in the area were stuck on 1 hp and could not be killed.

**Comment by marsalandrei** [comment]
yes, the quest needs a restart, and Hawinni was patrolling under the map, used /target to find him, and use Killing Spree to teleport to him and kill.

**Comment by DrFuler** [comment]
[18/03/2016] - Still bugged. Can't cast it at High Priestess Tua-Tua.

**Comment by Lothloryen** [comment]
Hello there,

This quest has been corrected and it is already on the live server.

Thank you.
