### ISSUE TITLE
Achievement: Hadronox Denied

### ISSUE THREAD

**Issue by Pia7** [dalaranwow/dalaran-wow#1407]
### Achievement: Hadronox Denied (*ID: 1297*)

**Issue present**: **Hadronox** (*ID: 28921*) is currently not spawning the gauntlet due to the *doors* which spawn the mobs being closed as the instance begins.

**How it works currently**: Credit for the achievement is not received when **Hadronox** (*ID: 28921*) is killed due to the doors being closed when the instance is begun.

**How it should work**: **Hadronox** (*ID: 28921*) should spawn adds which come down towards him and will fight him [(1)](http://www.youtube.com/watch?v=t-BWkkvcMLk#t=40). The doors atop the stairs should be open and the adds should spawn here and move towards Hadronox. 
- Adds should apply [Infected wound (*ID: 59348*)](http://www.wowhead.com/spell=59348)

Furthermore, the doors should close once Hadronox reaches the stairs and the achievement become unobtainable from that Heroic ID .

##### References:
[http://www.youtube.com/watch?v=t-BWkkvcMLk](http://www.youtube.com/watch?v=t-BWkkvcMLk)
[http://www.wowhead.com/achievement=1297#comments](http://www.wowhead.com/achievement=1297#comments)

**Comment by Crispybuilt** [comment]
Bump, this could be easily fixed if somehow sunwell scripts could be applied for this particular event in Azjol Nerub

**Comment by Crispybuilt** [comment]
Fixed! Thank you for this! Now only "My Girl Loves To Skadi all the Time" #1787 and Red Proto Drake will be obtainable!
