### ISSUE TITLE
Blessed Recovery

### ISSUE THREAD

**Issue by cycka625** [dalaranwow/dalaran-wow#1409]
Priest talent "Blessed Recovery" isn't working properly.
http://wotlk.openwow.com/spell=27811
I was leveling a priest and sometimes I was getting critical hits from mobs and there were no buff from this talent, for example when you get critical hit from higher level mob it jsut not triggering this talent.
How it works: sometimes when you get a critical hit you get this buff and it heals you a little.
How it should work: You should be able to get this buff after EVERY critical hit you received by enemy, doesn't matter if its higher level than yours or not

**Comment by ImprezaWoW** [comment]
Can be merged with [#1225](https://github.com/dalaranwow/dalaran-wow/issues/1225).
