### ISSUE TITLE
[Hunter] [Pet Ability] Wolverine Bite

### ISSUE THREAD

**Issue by wonopon** [dalaranwow/dalaran-wow#1411]
Wolverine Bite (http://wotlk.openwow.com/spell=53508) can be used by the pet regardless of whether or not it crits. It is supposed to be available only after your pet crits.

http://www.wowwiki.com/Wolverine_Bite : 
"Patch 3.3.0 (08-Dec-2009): This talent is now enabled when the pet lands a critical strike rather than from the target dodging the pet's attacks. In addition, this talent no longer has a prerequisite."

**Comment by robinsch** [comment]
On PTR. Note: There seems to be a visual issue that the react state doesn't get updated. Sadly I have no idea how to fix this currently.
