### ISSUE TITLE
[Northrend][Dragonblight][Quest] Something that doesn't melt.

### ISSUE THREAD

**Issue by Akkalevil** [dalaranwow/dalaran-wow#1412]
The amount of splintered bone chunks findable to complete the quest is extremely low, and their respawn very long.

The issue was referenced here : #510 and was marked fixed, but either the bug has come up once more, or the fix didn't work, because it's again exactly as described there.

**Comment by Golganeth** [comment]
Amount of gobjects fixed. Respawn timer is 5 minutes
