### ISSUE TITLE
Becoming a Shadoweave Tailor - bugged

### ISSUE THREAD

**Issue by ReaverB** [dalaranwow/dalaran-wow#1418]
Andrion Darkspinner in the Lower City of Shattrath gives you this quest at 350 Tailoring.

Quest: 
Use the Crystal of Deep Shadows near the Altar of Shadows to deepen your attunement to the altar, then return to Andrion Darkspinner in Shattrath's Lower City.
 
Provided item:
Crystal of Deep Shadows

The crystal gets consumed but the quest isn't completed.

**Comment by jonanone** [comment]
Improved the usage of the Crystal of Deep Shadows to get credit for quest completion. It already worked on some spots. The fix will be applied to live realm soon.
