### ISSUE TITLE
Northrend HC dungeons NPC's loot tables

### ISSUE THREAD

**Issue by Warlockboss** [dalaranwow/dalaran-wow#1421]
What's wrong: non boss NPC's loot in Heroic dungeons feels really poor and lower than average NPC's outside instances.
Loot tables for most NPCs should be checked and updated.
Edit: Tried to kill ~20 same NPCs in both normal and heroic difficulty. Results were: nothing lootable on heroic. However on normal half were lootable(frostweave, gray, green items, even boe rare).

**Comment by Rushor** [comment]
apply a detailed list of the creature with the missing items from http://wotlk.openwow.com

closed for now due to missing informations
