### ISSUE TITLE
Supreme Defender

### ISSUE THREAD

**Issue by Jazex** [dalaranwow/dalaran-wow#1431]
http://www.wowhead.com/achievement=206

'Kill 100 flag carriers in Warsong Gulch'

It's not counting the credit for killing a flag carrier.

**Comment by Cieply-Dalaran-WoW** [comment]
Fixed after last update. Killing flag carrier now give credit for achievement.

**Comment by Golganeth** [comment]
Fixed by Loth, this has been working for a while.

Closed
