### ISSUE TITLE
Rake

### ISSUE THREAD

**Issue by Isuel** [dalaranwow/dalaran-wow#1433]
it's initial damage is considered bleed damage, meaning that it doesn't ignore armor. Mangle still increases rake's initial damage, so that part is working.

**Comment by taralej90** [comment]
Confirmed. Rake's initial damage does not ignore armor and it should. It is clearly stated in the ability tooltip that the initial damage is BLEED damage.

Check here: http://www.wowhead.com/spell=1822/rake#comments:id=657611

**Comment by Isuel** [comment]
i guess they only fix bugs which are open for at least a year ))

**Comment by taralej90** [comment]
I know this is not the place but I feel it's kind of sad: I came to this server with great expectations and the server showed great promise at first. However, I started finding bugs one after the other and what was worse - when I came here they were already reported very long time ago and are still not fixed. I would totally understand if a server so young would have many bugs - I have no problem with researching, testing and reporting bugs. I did this all the time on the previous server where I played.

But I do have a problem when I see reports which are 1-2 years old. This seriously shakes my faith in the devs and without devs a server is bound to fall in time.

When I ask people about this, they say "priority fixes". Well, what are their priorities then? I've encountered class bugs, quest bugs, achievement-related bugs, pathfinding bugs, LoS bugs, general core bugs - bugs in almost every matter of the game... What are they focusing on then?

**Comment by Isuel** [comment]
obviously pve is more important than broken dps because of class mechanics. Better tune the boss dmg and hp, not the classes' damage abilities!

**Comment by Isuel** [comment]
happy birthday! the bug report is officially more than 1 year old now! ))

**Comment by Lothloryen** [comment]
Hello there,

I already had this issue fixed and prepared for the next update. It shall be working as it should as the new patch goes live.

Thank you very much.

**Comment by Isuel** [comment]
well, thank you, but i stopped playing here a year ago xd
