### ISSUE TITLE
Missing recipe(s): Henry Stern doesn't teach Goldthorn Tea (and maybe not Major Troll's Blood Elixir)

### ISSUE THREAD

**Issue by Shanghi** [dalaranwow/dalaran-wow#1434]
**Desired situation:**
Talking to Henry Stern in Razorfen Downs gives you two dialog options. One will teach you Goldthorn Tea if your cooking skill is at least 175 and the other will teach Major Troll's Blood Elixir if your alchemy skill is at least 180.

**Current situation:**
Going through the dialogs work as shown below, but picking to learn Goldthorn Tea doesn't actually teach the recipe (my cooking skill is at 411). I'm not an alchemist so I don't know if learning Major Troll's Blood Elixir works.

**Henry Stern:** http://www.wowhead.com/npc=8696
**Goldthorn Tea:** http://www.wowhead.com/spell=13028
**Major Troll's Blood Elixir:** http://www.wowhead.com/spell=3451

![henry1](https://cloud.githubusercontent.com/assets/2672633/2601968/c6c4ea44-bb18-11e3-9a5a-73375289950e.jpg)
![henry2](https://cloud.githubusercontent.com/assets/2672633/2601969/ca946cb2-bb18-11e3-8a4f-604e23308222.jpg)

**Comment by n-ghost** [comment]
Still an issue.

**Comment by Augur89** [comment]
I wish I checked this before wasting my time. At least I got the dungeon achievement...

Please consider fixing this for completionists like us (and for the cooking achievement that requires 160 recipes...).

**Comment by koubx** [comment]
I could learn the recipe last week with my troll hunt (lvl 53 and cooking lvl around 260 at the time I think). No particular issue.
![wowscrnshot_072115_181956](https://cloud.githubusercontent.com/assets/13437869/8806108/4ef6df8a-2fd5-11e5-85df-b80eedcd2f76.jpg)

**Comment by n-ghost** [comment]
Confirmed, works as intended now.

**Comment by Rushor** [comment]
cooking skill must be 180 and alchemy 175. the script for this guy was reworked in https://github.com/dalaranwow/dalaran-wow/issues/3863
