### ISSUE TITLE
shadowmeld

### ISSUE THREAD

**Issue by Veqzow** [dalaranwow/dalaran-wow#1435]
does not work correctly shadowmeld.
when the character exits the use of all forms.
This ability resets Target - Works 
Conclusion of the battalion in use - does not work. Char is still in combat when used. 
Not "catch" is already flying spells (must catch, including instant) - broken, should work in a similar Stealth and Vanish.

 comments with wowhead:
This is insanely good for druids. I use it like vanish. 

1. Shadow Meld (puts you out of combat and in caster form)
2. Switch to cat form (a brief moment without stealth)
3. Enter stealth.
4. Use opener again, sneak away, etc.

Reminds me the most of a more powerful fade. Good for healers in the arena against pets to begin drinking.
It could also be useful in a macro as an additional vanish for rogues.
http://www.wowhead.com/spell=58984

**Comment by Golganeth** [comment]
#2175
