### ISSUE TITLE
Priest Bubble on Rogue issue

### ISSUE THREAD

**Issue by Mom-** [dalaranwow/dalaran-wow#1438]
My friends and I have tested and have noticed that when a priest shields a rogue that it prevents them from breaking stealth on "everything" On retail of course when you shielded a rogue they could go throw death and decay and flamestrike, consencration etc you get the idea. Any spell that has a lasting ground aoe effect. Whereas on Algalon, if you put a shield on them they can go through blizzards arcane blast, etc etc any aoe that does immediate damage and still not break them out of stealth.

**Comment by robinsch** [comment]
Working as you described currently. Tested with Shadowflame, Hellfire, Rain of Fire (breaking Stealth with Shield) and Consecration (doesn't break Stealth with Shield).
