### ISSUE TITLE
[Paladin] Spells: Blessing of Kings and Blessing of Sanctuary

### ISSUE THREAD

**Issue by Rathyan** [dalaranwow/dalaran-wow#1443]
Kings: http://wotlk.openwow.com/spell=20217 and http://wotlk.openwow.com/spell=25898

Sanctuary: http://wotlk.openwow.com/spell=67480 and http://wotlk.openwow.com/spell=25899

When the player has already Kings and another paladin buffs with Sanctuary, the Kings buff is removed even though it's not supposed to. The stacking of the stats; 10% strength and 10% stamina (strength and stamina get the 10% boost just once from either one of the two) and 10% to the rest of the stats works retail like but this minor bug makes it very annoying when buffing the whole raid having to wait for the Sanctuary paladin to do it first and then for the Kings assigned one to start buffing.

Proof that both can be on the same target: Retail's Paragon world first LK 25 heroic 

http://www.youtube.com/watch?v=RSeVCw3hVgQ 

Quote from the patchnotes: "This blessing now also increases stamina by 10%. This effect is not cumulative with [Blessing of Kings] "(Implying that both can be on the same target and you don't get the boost of double stamina but the rest of the stats from Kings remain). 
"This blessing now grants 10% strength in addition to its current effects. Also, the strength and stamina bonuses from this blessing will no longer be lost when Blessing of Kings is removed." (Another proof of both being on the same target and that the shared stats boost aka strength and stamina are not summable while the rest are)

http://www.wowwiki.com/Blessing_of_Sanctuary

**Comment by DwowSupport** [comment]
Greetings!
As of 5.09.2015 this has been tested and it works as intended. (Fixed) 
Report can be closed.
