### ISSUE TITLE
Shield slam cap

### ISSUE THREAD

**Issue by ntt1** [dalaranwow/dalaran-wow#1446]
So we know that at about patch 3.2 on retail, there was a cap put on shield slam benefitting from block value (its 2760). Its implemented here as well. What is not implemented here is, that when using shield block/glyph of blocking, they get you above the cap for the time of the duration (increasing by 110%, up to around 5800 during the duration) and this does not work here. A huge huge downfall for prot warrior pvp and it really needs to be fixed as soon as possible, as this is the season where prot warriors get most benefit from Shield Slam spec.

Here's a short source I found (not detailed, I am sure you can research and find better one): http://www.tankspot.com/showthread.php?64797-block-value-cap-post-3.3

**Comment by robinsch** [comment]
On PTR
