### ISSUE TITLE
NPC Spammer: Har'koan Subduer [28403]

### ISSUE THREAD

**Issue by Golganeth** [dalaranwow/dalaran-wow#1453]
**(Minor problem)**

The following issue has been encountered once these NPCs reach 15-20% of their HP

![asd](https://cloud.githubusercontent.com/assets/5057942/2628796/a4d83108-be2d-11e3-8b93-f1d2f78a4325.png)

http://wotlk.openwow.com/npc=28403

**Comment by Sagrath** [comment]
Its fixed on Algalon
