### ISSUE TITLE
Tricks of the Trade [Algalon]

### ISSUE THREAD

**Issue by pascagabriel** [dalaranwow/dalaran-wow#1461]
Casting Tricks of the Trade on a target which is in combat will grant the rogue combat.

**Comment by Zarjofgt** [comment]
Not a bug.
"Actions that will get you into combat:
Casting a Buff or Healing spell on a unit that is in combat"
(http://wowwiki.wikia.com/wiki/Combat)

Unless you think this was changed post wotlk?
