### ISSUE TITLE
[Spell] Replenishment  - Aggrobehaviour

### ISSUE THREAD

**Issue by pascagabriel** [dalaranwow/dalaran-wow#1463]
Grating Replenishment to friendly players while in combat will also put your allies in combat.

**Comment by Zarjofgt** [comment]
Not a bug.
"Actions that will get you into combat:
Casting a Buff or Healing spell on a unit that is in combat"
(http://wowwiki.wikia.com/wiki/Combat)

Unless you think this was changed post wotlk?

**Comment by pascagabriel** [comment]
Not sure if the bug is still around since I've stopped playing here a long time ago and not sure if this is a joke from Loth but the bug report clearly states that triggering replenishment with one of your spells, granting the buff to friendly players who are out of combat and ARE NOT DOING ANYTHING puts THEM in combat. 
"Actions that will get you into combat:
Casting a Buff or Healing spell on a unit that is in combat"
Since when is standing still and being buffed placing you in combat? This was not changed post wotlk because it never placed you in combat. I hope common sense is enough proof :). Good luck finding bugs
