### ISSUE TITLE
Leader of the Pack procs Greatness Trinket

### ISSUE THREAD

**Issue by Jiokko** [dalaranwow/dalaran-wow#1464]
i noticed that when you are in feral form in a group and another  player rather than you is criting and procing your leader of the pack (mana and hp gain) then there is a chance your greatness trinket will pop.

**Comment by Rushor** [comment]
Cannot confirm this on PTR.

Event if i spamm spell http://wotlk.openwow.com/spell=68285 on myspell while wearing item http://wotlk.openwow.com/item=44253, i don't got a single proc after 1000 casts of http://wotlk.openwow.com/spell=68285
