### ISSUE TITLE
Priest: Prayer of Fortitude

### ISSUE THREAD

**Issue by Joana123** [dalaranwow/dalaran-wow#1470]
So basically I was on "http://www.wowwiki.com/Patch_3.3.3" and saw "Several raid buffs have had their ranges increased to 100 yards, up from 45 yards, to prevent select buffs from repeatedly getting applied and removed during highly mobile encounters. Some buffs, such as paladin auras, totems, shouts and [Blood Pact] are intentionally meant to have shorter ranges and remain unchanged." which got me thinking.... some buffs might be bugged. So i checked. 

In my search, I came across "http://www.wowhead.com/spell=21562/power-word-fortitude#comments" which said the aura was 100 yds but the buff was 30 yds... i was confused honestly, but I looked for an "aura" or 100 yd buff of some sort and came across "With some exceptions†, all characters in the target's party, including pets, that are within 100 yards of him also gain the buff. This effect is not limited by line of sight. As a result, the caster can buff people at triple the spell range."

I found it on "http://web.archive.org/web/20130311070623/http://www.wowwiki.com/Prayer_of_Fortitude" (I used web archive version because that's where the comments posted about 100 yards so i wanted to see if it was wotlk related or supposed to be that way in general, turns out it was that way in general).

I tested it. A priest named "Sniffeh" buffed a DK named "Aaron" with "prayer of fortitude" while i was out of LoS and I didn't get the buff. So I'm assuming buffs like that should work regardless of LoS. Dunno if this is posted already or not. Thanks for reading.

**Comment by robinsch** [comment]
On PTR.
