### ISSUE TITLE
The Old Kindgom -- Ahn'Kahar Guardian Spawn Location

### ISSUE THREAD

**Issue by Joana123** [dalaranwow/dalaran-wow#1473]
On Algalon (and kirin tor), to my knowledge, The Ahn'Kahar Guardians spawn right from under the boss outta nowhere. I know because I did some achievements and would always see the guardian spawn right under. I watched 2 retail videos (i was reading 3.3.2 patch notes, saw the date and watched a youtube from before AND after the patch to be 100% sure of location) and on both occurences, the guardians spawned from some eggs nearby.

What sparked my curiosity was "Elder Nadox now only gets one Ahn'Kahar Guardian during the encounter." from "http://www.wowwiki.com/Patch_3.3.2." The 1 guardian spawning is fine but the location wasn't (Btw, patch 3.3.2 came out February 2nd, 2010)

Video #1 (December 23rd, 2009): http://www.youtube.com/watch?v=Y19UOAnbYuc
Video #2 (January 28th, 2010): http://www.youtube.com/watch?v=Ih3lyCJ3JA0

**Comment by Golganeth** [comment]
#494
