### ISSUE TITLE
Quests: Howling Fjord, involving Winterhoof Brave.

### ISSUE THREAD

**Issue by wimvm** [dalaranwow/dalaran-wow#1479]
The three quests involving the Winterhoof Brave NPC in Howling Fjord, near the town of Skorn (Burn, Skorn, Burn!; Gruesome, But Necessary; Towers of Certain Doom) can be started by using the Winterhoof Emblem and summoning the Winterhoof Brave. However, I summoned him, got the quests, went and finished some other quests first, and then went to Skorn and completed the 3 quests. The brave is now nowhere to be found, the emblem is gone from my inventory, and I cannot get it back from Chieftian Ashtotem or anyone else.

This means the 3 quests are unable to be completed, for me at least.

(item) Winterhoof Emblem: http://wotlk.openwow.com/item=33340
(npc) Winterhoof Brave: http://wotlk.openwow.com/npc=24130
(quest) Gruesome, But Necessary: http://wotlk.openwow.com/quest=11257
(quest) Burn, Skorn, Burn!: http://wotlk.openwow.com/quest=11258
(quest) Towers of Certain Doom: http://wotlk.openwow.com/quest=11259

**Comment by jonanone** [comment]
Chieftain Ashtotem and Captain Adams will give you a new Emblem/Insignia if you lost it.

This update will be applied to the live realm soon.
