### ISSUE TITLE
A Distraction for Akama

### ISSUE THREAD

**Issue by tree0flifee** [dalaranwow/dalaran-wow#1480]
The quest "A Distraction for Akama" seems to be bugged.The whole script is gone.You have to talk to Xi'ri and start fighting your way with Akama and Maev to Black Temple.While in Dalaran-wow theres is not chat dialogue with Xi'ri.
Quest http://www.wowhead.com/quest=13429
Quest giver http://www.wowhead.com/npc=18528
How it should work https://www.youtube.com/watch?v=w4aoSd41vzQ 
So basicly the whole script of the event is missing.

**Comment by medan** [comment]
I just did this quest and the script works fine. Quest is completed and I can turn it to Xi'ri. Also it is quest number 10985 http://www.wowhead.com/quest=10985 which is the correct one for Hand of A'dal title.
You just need to wait a moment, when you get back to Xi'ri, until the question mark appear.

**Comment by jonanone** [comment]
Xi'ri has the option to start the event and everything is working as intended.
