### ISSUE TITLE
[Northrend][Zul'Drak][Quest] Cocooned!

### ISSUE THREAD

**Issue by Akkalevil** [dalaranwow/dalaran-wow#1481]
Several bugs :
- The cocoons fight back and give XP (that's common to a lots, maybe all, of quests with cocoons).
- Cocoons often contains a big bunch of mob instead of just one.
- The validations are completely random : often there is an Argent footman inside and the counter doesn't goes up, and sometimes the cocoon is empty and the counter suddendly goes up.
![cocooned](https://cloud.githubusercontent.com/assets/6848735/2674023/7a83811c-c0fa-11e3-939d-bf15bfa6d928.jpg)

**Comment by DrFuler** [comment]
[17/03/2016] - Doable, but still bugged.

**Comment by Sagrath** [comment]
Cant reproduce the issue, probably fixed
