### ISSUE TITLE
[NPC] Tauren starting zone druid not offering training

### ISSUE THREAD

**Issue by ivan6285** [dalaranwow/dalaran-wow#1492]
What the title says - the tauren druid in the starting zone does offer the quest and general dialogue, but does not offer druid training, as he should.

Server - Algalon

**Comment by Demlock** [comment]
This issue has still not been fixed. Not a game-breaking issue but it would be nice if it worked, at least for the sake of players new to WoW

**Comment by patrickebates** [comment]
Just ran into this myself.  Annoying to say the least.

**Comment by Rushor** [comment]
already fixed http://i.imgur.com/m75FT3U.jpg

**Comment by ivan6285** [comment]
This is absolutely shameful, you closing or even looking at this issue now.
This issue was reported nearly 3 years ago.
