### ISSUE TITLE
Drake hunt (algalon) 

### ISSUE THREAD

**Issue by arizonalighting** [dalaranwow/dalaran-wow#1494]
There seems to be a lack of these spawning. I recall retail the skies were full of these things. I've been sitting for 10 minutes and only saw one fly by.

**Comment by Golganeth** [comment]
#877

**Comment by Taffa2** [comment]
Why was this closed?  It was not fixed.  Still seems to be only one drake that gets spawned.  The correct number of drakes for the area need to be spawned.
