### ISSUE TITLE
Fishing / Fountain in Dalaran

### ISSUE THREAD

**Issue by beute** [dalaranwow/dalaran-wow#1498]
I can not fish in the fountain in Dalaran. The fishing line is not in the water, but directly under my character. I have tested different positions with my character, but it does not work.

Greets Beute

**Comment by Rushor** [comment]
Works fine for me on PTR.

The fishing line is always in the water. Else if the bait will get played behind the wall or sth. i get correctly the errormessage "Water too shallow." or " you cannot use here."
