### ISSUE TITLE
NPC: Defias Looter Backstab

### ISSUE THREAD

**Issue by Daveonx** [dalaranwow/dalaran-wow#15]
Defias Looter Backstab can hit players from the front, when it should only be possible from the back. http://wotlk.openwow.com/spell=7159

**Comment by taralej90** [comment]
Nice to see there's progress on this issue. Hoping for a fix soon. The situation with the Anub'ar Skirmishers is a bit problematic for any tank who doesn't outgear the dungeon severely.

**Comment by Rushor** [comment]
fix for this (and related spell) can be found here https://github.com/raczman/TrinityCore/commit/7057e3a36042548766eca2c85e8525589c97a6b2

**Comment by Rushor** [comment]
INSERT INTO `spell_custom_attr` (`entry`, `attributes`) VALUES (7159, 131072);


attribute was already applied
