### ISSUE TITLE
Vehicles and Pets.

### ISSUE THREAD

**Issue by ghost** [dalaranwow/dalaran-wow#1504]
Hello, it seems like all vehicles considered as pets, this causes duplicated frames (player+pet-vehicle) in addons like Grid. Tested it with default grid without any plugins, with deleted cache and WTF folders, still getting duplicated frames on Malygos p3 and Oculus drakes.

**Comment by Rushor** [comment]
We don't support addonfixes. You may need to adjust the code of the addon itself to fit to the servercode. Thank you.
