### ISSUE TITLE
[Item] Drums of Speed

### ISSUE THREAD

**Issue by Itchybus** [dalaranwow/dalaran-wow#1509]
Made a drums of speed (Kurenai Outland pattern). Tooltip says: 

Use: Increases movement speed of nearby party members by 15%.  Lasts 30 sec. (2 Min Cooldown)

Using the item gives the correct buff tooltip but there is no movement speed increase.

**Comment by Rushor** [comment]
Effect 0: Id 6 (SPELL_EFFECT_APPLY_AURA)
BasePoints = 15
Targets (22, 33) (TARGET_SRC_CASTER, TARGET_UNIT_SRC_AREA_PARTY)
Aura Id 129 (SPELL_AURA_MOD_SPEED_ALWAYS), value = 15, misc = 0 (0), miscB = 0, periodic = 0
Radius (Id 23) 40.00

working fine for me
