### ISSUE TITLE
Quest: Stunning defeat at the ring

### ISSUE THREAD

**Issue by Daveonx** [dalaranwow/dalaran-wow#151]
After the whole event is done player can't loot the item from Ancient Cipher (Id:186649), it is always empty. Need some priority since it opens a lot of quests in the chain.

http://www.wowhead.com/quest=11300/stunning-defeat-at-the-ring
http://www.wowhead.com/object=186640

**Comment by Golganeth** [comment]
Works but needs polishments. The Ancient Cipher still drops from Oluf, it should fall to the ground and be lootable from a game object, as "The ancient cipher falls to the ground." message states.
