### ISSUE TITLE
Stacking Auras/Buffs/Debuffs

### ISSUE THREAD

**Issue by ntt1** [dalaranwow/dalaran-wow#1510]
So we have tested most of the buff/debuffs/auras/totems that are not supposed to stack and these are the ones that seem to be stacking and need to be corrected.

<b>Damage % increase</b>
BM hunter’s Ferocious Inspiration, retribution paladin’s Sanctified Retribution and arcane mage’s Arcane Empowerment are incorrectly adding up. They are not necessarily supposed to overlap eachother, but when all of them are present the damage % should not be adding up (because paladin’s aura also gives 3% haste if talented, in addition to 3% damage, which shouldn’t be diminished if another damage % aura is up).

<b>Physical Critical Chance</b>
Feral druid’s Leader of the Pack is incorrectly stacking with warrior’s Rampage. They are not supposed to overlap eachother, as improved leader of the pack should still be gained even if both auras are up, just the crit should not be adding up.

<b>Spell damage increase</b>
Shaman’s Totem of Wrath/Flametongue totem are incorrectly adding up to warlock’s Demonic pact. Demonic pact should have priority when both are present, but the spell power should not be adding up.

<b>Haste increase</b>
Retribution paladin’s Swift Retribution is incorrectly stacking with balance druid’s Improved Moonkin Form.

<b>Armor reduction</b>
Rogue’s Expose armor is incorrectly stacking with warrior’s Sunder Armor.

<b>3% crit on target</b>
Totem of Wrath, Heart of the Crusader and Master Poisoner debuffs are stacking on the target but its hard to say if the crit is adding up. According to the logs we have from 25 mans, they are not adding up, but still its not certain as the logs are only from 2 raids and data might not be enough and that’s why I am posting it anyway. For reference, combat rogue’s and warrior’s 4% physical are stacking on the target as well but they are not adding up, so the case could be the same.

<b>5% spell crit on target</b>
Mage’s Improved Scorch and warlock’s Improved Shadow bolt debuffs are stacking on the target and according to the logs from the last few raids they also seem to be adding up the crit (for 10% in total) but again it cannot be 100% certain and it needs to be checked by a dev.

**Comment by Aizenscar** [comment]
5% spell crit on target:
Improved Scorch - http://wotlk.openwow.com/spell=22959
Improved Shadow Bolt - http://wotlk.openwow.com/spell=17803

Have tested both and I can say while the one of the debuff is not overwritten by the other, the 10% crit does not apply. Even with both on the target its 5% spell crit on the target.

**Comment by Vaxsysl** [comment]
Naturel Sin: Afaik, replenishment and revitalize should stack, they're different effects.

**Comment by Golganeth** [comment]
Improved FF and Misery (3% hit rating buffs) are still stacking. - #2718 #3134

**Comment by robinsch** [comment]
On PTR

**Comment by plznoz** [comment]
Misery and faerie fire still stacks (3% hit). @robinsch ?

**Comment by Edzero** [comment]
It's on the PTR but not yet fully tested. The update for it affects a lot of other abilities too so it requires very thorough testing.

**Comment by plznoz** [comment]
@Rushor Does the sunwell stacking fixes also include these?
1. Gordok Green Grog: http://www.wowhead.com/item=18269/gordok-green-grog#comments:id=948254
2. Halaani Whiskey: http://www.wowhead.com/item=30615/halaani-whiskey#comments:id=230402
3. Dried Fruit Rations: http://www.wowhead.com/item=24009/dried-fruit-rations#comments:id=233702

**Comment by Rushor** [comment]
@plznoz yes indeed they do except Dried Fruit Rations

**Comment by Rushor** [comment]
DB/Spell: Add 'Dried Fruit Rations' to spellgroup stacking rule 

* updates: https://github.com/dalaranwow/dalaran-wow/issues/1510
* commit: 2b59284c81bd917376e1e25877e4e7ce13596c91

added it

**Comment by datbunneh** [comment]
@Lothloryen So Shadow Mastery/Improved Scorch & Misery/Improved Faerie Fire no longer stack on LIVE servers indeed?

**Comment by Tziva** [comment]
The community would appreciate an update regarding the stacking hit debuffs (misery/faerie fire), or atleast a change on the label of this post.

**Comment by maciejpk** [comment]
As of 03.08.2020, the issue with Improved FF/Misery is still present on LIVE server
