### ISSUE TITLE
[Northrend][Storm Peaks][Quest] The Earthen Oath

### ISSUE THREAD

**Issue by Akkalevil** [dalaranwow/dalaran-wow#1512]
Player doesn't get credit if he's not the one giving the killing blow (even if he did the overwhelming majority of damage to the mob).

Also, Iron Sentinels hurt themselves (and their allies) when using the "Throw Boulder" attack (which can lead to the aforementioned problem when they kill themselves).

**Comment by Zeilze** [comment]
Confirmed that this is still an issue as of today.

**Comment by Khronos-** [comment]
Confirmed that this is still an issue.

**Comment by Lothloryen** [comment]
This should be solved already, thank you.
