### ISSUE TITLE
[Northrend][Icecrown][Quest] Raise the Barricades

### ISSUE THREAD

**Issue by Akkalevil** [dalaranwow/dalaran-wow#1513]
The quest item is correctly only usable close to Ebon Blade markers, but sometimes it works, sometimes it doesn't.

It may be due to a marker used being not usable again ?

**Comment by Mantigora** [comment]
Looks like players are unable to see any of Ebon Blade marker.
50.67, 39.34
51.58, 38.97
51.17, 40.83
50.39, 40.91
49.70, 39.82

**Comment by Daveonx** [comment]
Tested and currently working, markers are visible. If players still experience issues with this quest, comment bellow.
