### ISSUE TITLE
[Rogue] Hexed Rogues

### ISSUE THREAD

**Issue by Esunnaxqt** [dalaranwow/dalaran-wow#1514]
Hexed rogues can stealth if they manage to get out of combat.
While hexed, a rogue shouldnt be able to use any ability.

How to test: As a rogue, ask a shaman to hex you in a duel. Wait to leave combat and try to stealth during hex.

**Comment by Rushor** [comment]
https://threadmeters.com/wow/rYhZmJ/Hex_is_so_lame_that/

Azium of Mal'Ganis
Rogues and druids can stealth/prowl when hexed.

Wrong. you should be able to go in stealth while hexed

www.wowhead.com/spell=51514/#comments

Rogues can use cloak of shadows to remove hex, and can also vanish while a frog. They remain a frog while stealthed.
