### ISSUE TITLE
A Mammoth Undertaking

### ISSUE THREAD

**Issue by Oliverthehardestofthemall** [dalaranwow/dalaran-wow#1515]
You are not able to apply the harness to the mammoth and mount it for hand in 
http://www.wowhead.com/quest=12607

**Comment by Lothloryen** [comment]
Hello there,

Thank you for your report. Now the quest will be doable as it should but there is a chance for it to get glitched. However I have also implemented a method for this special cases, where just by using the quest item over the propper Mammoths (Shattertusk Mammoth) the player shall get the quest credit.

Thank you very much.
