### ISSUE TITLE
Quest: Building a Perimeter

### ISSUE THREAD

**Issue by Jazex** [dalaranwow/dalaran-wow#1517]
http://www.wowhead.com/quest=10240

Using the Rune Activation Device near the runes does not grant credit.

**Comment by Demlock** [comment]
I require the last rune. So far, I've got a credit for all the runes.

**Comment by Demlock** [comment]
So, the last rune doesn't give you the credit for quest. That's the rune on that hill overlooking the whole southern part of Kirin'var Village.

**Comment by catta000** [comment]
None of the runes gives credit for the quest.

**Comment by Mantigora** [comment]
Confirmed. None of them gives credit after using Activation Device.

**Comment by jonanone** [comment]
Using Rune Activation Device now gives quest credit. The beam that appears once the device is used now despawns after 3 mins and the runes are usable again. The fix will be applied to the live realm soon.

**Comment by Golganeth** [comment]
Works great but the quest item can be used while the rune is despawned and the beam is active. You can spam the quest item and create infinite beams.

Edit: the quest item is usable everywhere. It should only be usable infront of runes and ONLY if the rune has respawned and beam isn't active anymore.

https://i.gyazo.com/10488103196b5d2fc3cda8ca0d469ac9.png
