### ISSUE TITLE
[Northrend][Borean Tundra][Mob] Raging Boiler ID:25417

### ISSUE THREAD

**Issue by omonoia91** [dalaranwow/dalaran-wow#1522]
Raging Boilers should be spawned here
![wowscrnshot_041814_124924](https://cloud.githubusercontent.com/assets/7306252/2740958/1b1345b0-c6df-11e3-81f0-5cad6e61f2ee.jpg)

but there is none. This place is just outside of Bor'gorok Outpost.

**Comment by Randomi** [comment]
Hello, no raging boilers spawning yet.
