### ISSUE TITLE
Druid: Cyclone + Immunity Mechanics

### ISSUE THREAD

**Issue by Golganeth** [dalaranwow/dalaran-wow#1525]
**Issue:** Cyclone goes through some immunity mechanics, such as:

- ***Anti-Magic shell:*** #1524
- ***Spiritual Immunity [58729]:*** The player having this aura is immune to any source of incoming damage, but he is vulnerable to cyclone.
Once cyclone is over, even though the immunity buff remains, the player becomes completely vulnerable.
http://wotlk.openwow.com/spell=58729

More auras may be added to the report, if required.

**Comment by Johanes022** [comment]
This has become highly abusable almost by every druid in Wintergrasp.Druids waiting at graveyard and cycloning everyone who gets ressurected removing immunity and getting honorable kills/honor.
