### ISSUE TITLE
Algalon Druid Talent:Primal Fury

### ISSUE THREAD

**Issue by Landslid3** [dalaranwow/dalaran-wow#1526]
Hi there,

I`ve noticed while playing as a  feral druid that the talent "Primal Fury" isn`t working properly.I have 2/2 points in it so i should get an additional combo point whenever i crit with claw/rake or any other ability that adds combo points.But i have noticed that most of the time the talent doesn`t work even if it has 100% chance.
Sure there are some crits that add 2 combo points instead of 1 but they are few and far between.Can any one else confirm this?

Best regards!

**Comment by robinsch** [comment]
Tested - working as intended. Please reopen if this still accours and how to reproduce it.

**Comment by Rushor** [comment]
mostly happens after you changed your spec and then relogged and the changed your spec again - no way to reproduce this for 100 % sadly :/

**Comment by Daveonx** [comment]
Still a common issue for feral druids on Algalon, happens after a few minutes or hours of gameplay, changing specs fixes the problems, but breaks again after some time regardless. Gimps feral dps quite a bit without them noticing sometimes.

**Comment by robinsch** [comment]
Please try to get a way how to reproduce it, otherwise I can't do much.

**Comment by Rushor** [comment]
the hackfix for the problem

```c++
diff --git a/src/server/game/Entities/Player/Player.cpp b/src/server/game/Entities/Player/Player.cpp
index 8888a21..4ec142b 100644
--- a/src/server/game/Entities/Player/Player.cpp
+++ b/src/server/game/Entities/Player/Player.cpp
@@ -3836,6 +3836,12 @@ bool Player::AddSpell(uint32 spellId, bool active, bool learning, bool dependent
                 }
             }
         }
+        // primal fury(feral) Don't learn low ranks and remove low rank spell if present
+        else if (spellId == 16954 || spellId == 16961)
+        {
+            if (uint32 prev_spell = sSpellMgr->GetPrevSpellInChain(spellId))
+                RemoveSpell(prev_spell, false, false);
+        }
         // non talent spell: learn low ranks (recursive call)
         else if (uint32 prev_spell = sSpellMgr->GetPrevSpellInChain(spellId))
         {
```

but well.. no idea how to reproduce. the posted crap above solves the issue

**Comment by robinsch** [comment]
On PTR
