### ISSUE TITLE
[Priest] Shadowfiend runs too slow

### ISSUE THREAD

**Issue by chereyo** [dalaranwow/dalaran-wow#1529]
If the shadowfiend is chasing someone in movement, it isn't able to attack and return mana. It's intended that the shadowfiend should be able to attack as regularly while chasing a target, as if they were standing still. This does not include any slow or impairment effects, of course.

**Comment by robinsch** [comment]
Can't confirm, it would always attack the target while it's chasing it. Please proive a video from retail (Maybe Lightdoom?) where we can see the speed of the Shadowfiend.
