### ISSUE TITLE
Profession Links

### ISSUE THREAD

**Issue by Golganeth** [dalaranwow/dalaran-wow#1532]
**Issue:** If you link your profession in-game, players will be able to re-link it.

Even though it's not game-breaking, this could lead to awkward situations such as when you're in a raid / group rolling for a profession item.

**Comment by Rushor** [comment]
![GitHub Logo](http://i.imgur.com/cKmw2TY.jpg)

(Rushor posted it, Testlow rposted it. Works fine on PTR.
