### ISSUE TITLE
Felguard DPS

### ISSUE THREAD

**Issue by Cephyric** [dalaranwow/dalaran-wow#1533]
Having recently gotten back into using Rawr to optimize my warlock, I've been tracking my felguards damage compared to what I should be expecting of it.

Currently, the scaling of felguards damage is way down compared to what is to be expected of it. an untalanted imp currently outperforms felguard by 200-300 dps unbuffed.

Having ran it at a (nonbugged) dummy for 30 minutes, my felguard sat on an unbuffed average of 570 dps, just about 800 less dps than Rawr says it should be doing in my gear.

**Comment by elorix** [comment]
So abit more detailed and with numbers:

Expected Felguard base stats: 
str 314
agil 90
sta 328
int 150
power 608
spell 0
damage 329 - 495, with 0 power
armor 14033

ref. http://www.wowwiki.com/Felguard_%28warlock_minion%29

Expected stats trough scaling

ref. http://www.wowwiki.com/Minion

my stats unbuffed http://i.imgur.com/BaOurRv.jpg

expected stats of my felguard
str 314
agil 90
sta 1171,25
int 448,5
spell 395,55
power 1974,29
damage 392,89 - 591,12
armor 14776,4

actual stats of my felguard http://i.imgur.com/p1uTmto.jpg

so both the base stats and scaling are wrong for it

another thing is pet's hit/expertise cap as these stats should be capped if the master is spell hit capped
ref. http://www.wowwiki.com/Minion

results http://i.imgur.com/1LmLhAp.jpg with 390 hit rating
-------
something that could help as ure not the first having this problem
https://github.com/TrinityCore/TrinityCore/issues/5136

**Comment by Lothloryen** [comment]
Hello there,

Thank you for your reports, after the next scheduled maintenance Felguard will benefit properly from the Attack Power granted by its owner's spell power, as well as the rest as stats (such hit rating, expertise...etc).

In addition, his Glyph will also provide the extra 20% of his total Attack Power.

If there is something you wish to add after the update, I am sure it will be helpful.

**Comment by Lothloryen** [comment]
It will be live in 15 minutes. Any feedback will be welcome.

**Comment by elorix** [comment]
armor and damage are still too low
http://i.imgur.com/BFsacIf.jpg

the hit/exp conversion and glyph are working tho

**Comment by elorix** [comment]
still not a viable pet; bump
