### ISSUE TITLE
Druid Ability: Survival Instincts

### ISSUE THREAD

**Issue by Jiokko** [dalaranwow/dalaran-wow#1536]
The ability Survival Instincts which is activated via Feral Talent tree and increases a player's maximum health by 30% when he is in Bear/Dire Bear/Cat should work ONLY in these forms.

The bug in our server is that Survival Instincts can be used in any form and in no-form, you can use it anytime in anyform while you ONLY should be able to use it while in Bear/Dire Bear/Cat form.

**Comment by Golganeth** [comment]
Works fine.

**Comment by Winstrol** [comment]
nope not fixed
