### ISSUE TITLE
Quest: Fields of Grief

### ISSUE THREAD

**Issue by Frostriver** [dalaranwow/dalaran-wow#1540]
Hello there.
Quest: Fields of Grief
ID: 365
Issue: At the moment all the pumpkins are invisible, which makes quest undoable.

**Comment by Golganeth** [comment]
This is no longer an issue. Pumpkins are visible and have a 2 min. respawn timer.

**Comment by MrAndersonX** [comment]
Confirmed - still bugged. No pumpkins, they either don't spawn or are invisible.
