### ISSUE TITLE
Wintergrasp tenacity still broken after this long time.

### ISSUE THREAD

**Issue by Lyricaldot** [dalaranwow/dalaran-wow#1541]
Like loth said before , theres no way to know the ratio of tenacity stacks and the missing players. Im not asking to have 10 stacks of tenacity , but having 3-4 would help a lot when you are fighting a 9 vs 20 fight.
This is something that must be fixed and have priority since the server has been claiming it has a fully working wintergrasp since kirin tor got released( I must admit that no server has better wintergrasp than this one but still.)

Both pics were taken at the same time. 
Alliance side: http://imgur.com/ARp4NZL
Horde side: http://imgur.com/J0gTKHR

**Comment by Golganeth** [comment]
#561
