### ISSUE TITLE
[Quest][Northrend][Storm Peaks] Just Around the Corner

### ISSUE THREAD

**Issue by BenBezac** [dalaranwow/dalaran-wow#1544]
Hi,

This quest (http://www.wowhead.com/quest=12819/ works

But you shouldn't be able to fly above the minefield, like on this video : http://www.youtube.com/watch?v=bkEZAqH-FoI

**Comment by jonanone** [comment]
Players now will be shoot down from their mounts when flying above the mine field.

This update will be applied to the live realm soon.
