### ISSUE TITLE
Time-Lost Proto Drake Spawning

### ISSUE THREAD

**Issue by machinegun1988** [dalaranwow/dalaran-wow#1545]
He spawning now every 10 minutes at same position. You can literaly farming gold on him. That don't have sense. 

How working now: he spawning every 10 min in same location 50,64 map coords. 

How shoud be: He should spawn once a week becouse this is x1 server. Fix this please ty.

**Comment by Golganeth** [comment]
No longer an issue so closing up.

**Comment by Torrigan** [comment]
This is an issue again
