### ISSUE TITLE
Divine Sacrifice and Hand of Sacrifice

### ISSUE THREAD

**Issue by dfortner** [dalaranwow/dalaran-wow#1546]
Hello, paladin's divine shield does not absorb damage from this spells.
DS - http://i.imgur.com/1xWpVcx.jpg - http://wotlk.openwow.com/spell=64205
HoC - http://i.imgur.com/432PYCm.jpg - http://wotlk.openwow.com/spell=6940

For DS it was always possible to absorb damage from release of this spell at 3.1, source - http://www.wowwiki.com/Divine_Sacrifice
As for HoC only after 3.3, source - http://www.wowwiki.com/Hand_of_Sacrifice

And both of this spells stack with each other, up to 80% damage reduction - http://i.imgur.com/iGdc6EI.jpg
The rest is correct, DS works only for party.

**Comment by robinsch** [comment]
Tested and working correctly.
