### ISSUE TITLE
Quest: Hot and Cold

### ISSUE THREAD

**Issue by ReaverB** [dalaranwow/dalaran-wow#1548]
The drop rate for Essence of Ice (ID:42246) from Brittle Revenant (ID:30160) is extremely low. I had to kill over 50 Brittle Revenants on Kirin Tor to get 6 required for the quest. That was waiting for 7 mobs to respawn 8 times.

Most when killed aren't dropping anything. Wowhead has the drop rate listed as 69%
http://www.wowhead.com/npc=30160/brittle-revenant

**Comment by Golganeth** [comment]
#944
