### ISSUE TITLE
[Northrend][Wintergrasp] Quest: Fueling the Demolishers

### ISSUE THREAD

**Issue by deniya** [dalaranwow/dalaran-wow#1550]
Issue: Alliance players can take and complete 2 such quests in a week, unlike Horde.
Quest link: http://www.wowhead.com/quest=13197/fueling-the-demolishers

This means they have better honor points boost from doing weekly quests in Wintergrasp. Kind of unfair.
P.S. I'm playing both horde and alliance so I'm sure of it.

**Comment by NovaHiros** [comment]
I can't turn the quest in to stonehoof.
![wowscrnshot_032116_040009](https://cloud.githubusercontent.com/assets/17796298/13909801/a17c87ec-ef19-11e5-9283-19dc7e2b7461.jpg)

**Comment by jonanone** [comment]
- Fixed issues with duplicate quests for the alliance.
- Now the alliance should see the correct quest when defending or attacking.
- Fixed some texts.
- Fixed questenders and queststarters for the quest.

These updates will be applied to the live realm soon.
