### ISSUE TITLE
[Quest][Outland][Shadowmoon Valley]Blast the Infernals!

### ISSUE THREAD

**Issue by tavna** [dalaranwow/dalaran-wow#1555]
I used the bomb while standing in the green circle, but nothing happens

**Comment by AgeAgainst** [comment]
Updating for the newer people coming along.  It does work inside the circle.  22.6, 40.0 are the coordinates I used to complete the quest.

**Comment by Demlock** [comment]
I killed all the channelers around the circle and it worked as intended.

**Comment by jonanone** [comment]
Working as intended.
