### ISSUE TITLE
[Quest] Unexpected Results

### ISSUE THREAD

**Issue by Reziark** [dalaranwow/dalaran-wow#1564]
**Issue Present:** You accept the quest from an NPC named "Apprentice Mirveda" in East Sanctum, Eversong Woods. You are asked by Mirveda to protect her from the incoming scourge ambush.

**How it works:** Once you accept the quest, you are not required to defend Mirveda. All you have to do is right click her and turn the quest in.

**How it should work:** You should have to fight off the scourge ambush, preventing the death of Mirveda. 

**Quest Link:** http://www.wowhead.com/quest=8488/unexpected-results
**NPC ID:** Unknown

**Comment by Golganeth** [comment]
#1485
