### ISSUE TITLE
Event Quest: Pilgrim's Bounty

### ISSUE THREAD

**Issue by Spruitje** [dalaranwow/dalaran-wow#1566]
The event Quest Pilgrim's Bounty (http://www.wowhead.com/quest=14036) cannot be completed since at the right spot in the Courtyard above Undercity there is no NPC/Items spawned to turn in this quest
Maybe this is the wrong timeframe (its an event quest) but in that case the questgivers should not be giving out this quest

**Comment by Golganeth** [comment]
Works fine. Abandon the quest if the event is over.
