### ISSUE TITLE
Quest: A Spirit Guide

### ISSUE THREAD

**Issue by Sagrath** [dalaranwow/dalaran-wow#157]
http://www.wowhead.com/quest=9410
The summoned Ancestral Spirit Wolf missing the aura Guided by the Spirits, which allows the player to complete the quest, as player is Unfriendly with Mag'har at the time of making this quest, and the aura allows the player to complete it, showing the Mag'har NPC s as Friednly.
Ancestral Spirit Wolf - http://www.wowhead.com/npc=17077
Guided by the Spirits - http://www.wowhead.com/spell=29938

**Comment by Lothloryen** [comment]
Hello there,

This quest was working since long time ago.

Thank you.
