### ISSUE TITLE
Hunter Spell: Deterrence

### ISSUE THREAD

**Issue by JebsterWrath** [dalaranwow/dalaran-wow#1572]
When activated, deterrence gives you 100% parry chance, 100% spell deflection, and 100% reduction chance to be hit by ranged attacks.

Well I have found time and time again that this spell does not work properly, I have been killed through deterrence countless times by melees (from the front, mind you) and I was not stunned or CC'd in anyway. I check the combat logs and it would say that I gained deterrence, then suffered a melee hit (usually by a paladin).

Also, the warlock spell "Chaos Bolt" goes through deterrence, while it should not. The spell tooltip says that the spell cannot be resisted and pierces through all absorption effects. Well deterrence does neither of those, and still it goes through. If that does not convince you enough, then why can a warrior spell reflect chaos bolt, but a hunter cannot spell deflect a chaos bolt?

**Comment by Esunnaxqt** [comment]
It is also deflecting the feral talent Primal Fury.

**Comment by keki88** [comment]
Parry is an avoidance effect.
But there is some information:
Patch 3.2.0 (04-Aug-2009): This ability now allows the hunter to parry spells and attacks from BEHIND as well as in front. Now has a new visual spell effect.
By Shiroikage (235 – 3) on 2011/01/12 (Patch 4.0.3)		
Note that attacks made to you while your targets are stealthed will still hit you.(cheapshot pounce ambush garrote etc.) via wowhead (its like patch 3.3.5a)

**Comment by Winstrol** [comment]
Seems like deterrence no longer works on boss abilities like it used to. eg. cosmic smash on algalon

**Comment by Blagodarocka** [comment]
Deterrence now does not deflect many aoe spell and spells like Avenger's Shield by protection paladins.

**Comment by robinsch** [comment]
@Lothloryen Can you import changes you've made to the PTR source?

**Comment by robinsch** [comment]
I will close this because all those bugs do not exist on PTR. I've fixed that you can no longer deflect spells while stunned according to https://github.com/dalaranwow/dalaran-wow/issues/1572#issuecomment-66904431.
