### ISSUE TITLE
[Quest][Outland][Blade's Edge mountains] Getting the Bladespire Tanked 10512

### ISSUE THREAD

**Issue by nagyiwarri** [dalaranwow/dalaran-wow#1575]
http://wowhead.com/quest=10512
I found this quest bugged. I think I tried everything, here's what:
A: Found a patrolling Bladespire Brute, put the mug close to him (without starting combat) he ran to the mug, stopped, then ran back to his previous position. Did NOT give quest objective.
B: Started combat with a Bladespire Brute, Cook, Shaman, RAPTOR, the leaders in the building and their guards and then placed the mug, but nothing happened. Doesnt matter if I ran away or killed them.

I hope you can get this to work, it could help the loremasters.

Szipirtyo

**Comment by jonanone** [comment]
At the moment, the ogres are getting drunk are the credit for the quest is being given.
