### ISSUE TITLE
[Spell] [48125] - Shadow Word: Pain

### ISSUE THREAD

**Issue by lanrutcon** [dalaranwow/dalaran-wow#1576]
Shadow Word: Pain is not refreshing correctly...
----
Problem:
When you refresh Shadow Word: Pain with Mind Flay on a Mage that is using Mage Armor...it refreshs to 9sec...
_________________
How should work:
After refreshing Shadow Word: Pain with Mind Flay it should restore the 18sec...
_________________
Proofs:
http://www.arenajunkies.com/topic/133105-mindflay-bug/
_________________
More Info:
Shadow Word: Pain - http://wotlk.openwow.com/spell=48125
Pain and Suffering - http://wotlk.openwow.com/spell=47581
Mage Armor - http://wotlk.openwow.com/spell=43024
_________________
Important Note:
This issue may be "duplicated" on Corruption (Warlock's spell)

**Comment by Golganeth** [comment]
#1348
