### ISSUE TITLE
[Elevator] Dun Argol, Dismounting a Charged War Golem in an elevator breaks it.

### ISSUE THREAD

**Issue by fizzl** [dalaranwow/dalaran-wow#1577]
When completing the quest "Bringing Down The Iron Thane", I stepped into an elevator in the Dun Argol. While in the elevator, I dismounted the Charged War Golem. I dropped throught the elevator and now I am at the bottom of the elevator well. When looking up, I cannot see the elevator anymore.

**Comment by Rushor** [comment]
Elevator was already fixed years ago on live /closes
