### ISSUE TITLE
[Hunter] Pet Talent - Cobra Reflexes

### ISSUE THREAD

**Issue by crumble6000** [dalaranwow/dalaran-wow#1585]
Cobra Reflexes Rank 1 - http://wotlk.openwow.com/spell=61682
Cobra Reflexes Rank 2  - http://wotlk.openwow.com/spell=61683

What it should do - It should increase your pets attack speed by 15% each rank and reduce the pets base damage by 7.5% each rank. 

What it currently does - Currently it does increase the attack speed correctly but it is also reducing the damage by 15% each rank resulting in a dps loss (see screenshot)

No Cobra Reflexes taken 
![no cobra reflexes](https://cloud.githubusercontent.com/assets/7499358/2888684/b637771c-d50f-11e3-98e0-9daa02fda18f.jpg)

Cobra Reflexes Taken
![cobra reflexes taken](https://cloud.githubusercontent.com/assets/7499358/2888685/bbad6472-d50f-11e3-9972-6ab178f21d1b.jpg)

As you can see from the ingame dps the pet loses around 6 dps at my level from just taking the talent. The actual dps of the pet should not go down by taking this talent, the only thing that should change is that each hit will be weaker but the pet hits more to compensate.

**Comment by Winstrol** [comment]
this needs to get labeled and looked at.

**Comment by Winstrol** [comment]
Could the admins lable this post? its still an issue.

**Comment by MrAndersonX** [comment]
Just noticed it on my pet too. This is really kinda silly tbh. Since when and how come hunters are so damned bugged ? Please, any staff member, can u pay a little attention to hunters ?

**Comment by MrAndersonX** [comment]
Still bugged, needs a fix ASAP. One of THE most important talent in a BM hunter pet build and the lowered dps really hurts us.

**Comment by robinsch** [comment]
On PTR.

**Comment by MrAndersonX** [comment]
Well Lothloryen said : "Hello there,

The remaining fixes were applied yesterday night already.

Thank you very much."

But still, Wild Hunt is still bugged (no increase stamina or ap), same as pet stats, hit ,expertise, etc and Cobra Reflexes. So, what gives ?....

**Comment by Lothloryen** [comment]
This is working, test it again. Please there is no need to copy paste the same for all the issues.

**Comment by MrAndersonX** [comment]
Yes, Cobra Reflexes work. But Wild Hunt doesn't, and scaling I think doesn't (pet has same hp/ap as it did before the changelog). Forgot to update the post, sorry.
