### ISSUE TITLE
[NPC] Instance: SM GY Rare Boss Spawn

### ISSUE THREAD

**Issue by Sagrath** [dalaranwow/dalaran-wow#159]
They are spawned all the time. 
How it should work: Ironspine, and the other rare elites associated with SM Graveyard are tricky to get to spawn. While they CAN be there for the initial spawn, it seems very unlikely that they will be.

The three rare elites are:
http://www.wowhead.com/?npc=6490 - Azshir the Sleepless
http://www.wowhead.com/?npc=6488 - Fallen Champion
http://www.wowhead.com/?npc=6489 - Ironspine

**Comment by Rushor** [comment]
3333c568ddd9e06a7d3390f348964006abbae37a
- Azshir the Sleepless (6490) + Ironspine (6489) + Fallen Champion (6488) will now spawn for 37 % if you enter the instance. there is no longer a 100% to spawn them
- also added combatabilities for all 3 creatures
