### ISSUE TITLE
Death Grip

### ISSUE THREAD

**Issue by Eyesblank** [dalaranwow/dalaran-wow#1595]
I've been having a hard time to understand it so that I could reproduce it, more testing is required, but here goes.

What's wrong?

Sometimes, upon casting Death Grip, it will have its animation and become on cooldown but doesn't pull its target to the Death Knight. I've noticed this issue while PvPing but didn't manage to establish a context in which it was used. The issue is rare and I believe happens randomly. However, I made sure the targeted player was not close to any Grounding Totem or was under the influence of a spell which made them immune to other spells such as Cyclone, etc.

How should it work?

It should pull its target to the Death Knight.

Note 1: Check into CCs such as fears if they could affect the use of Death Grip.
Note 2: It's pretty game-breaking for PvPers.

**Comment by Golganeth** [comment]
Merge with #326
