### ISSUE TITLE
[Rogue][Talents] Master Poisoner

### ISSUE THREAD

**Issue by Akkalevil** [dalaranwow/dalaran-wow#1597]
This talent simply doesn't work at all.
Even with 3/3, the Deadly Poison stacks are removed after Envenom.
If you poison an enemy, he doesn't get a debuff (at least not a visible one).
Didn't try the reduction of poisoning duration though, maybe it's the one thing that works...

**Comment by Golganeth** [comment]
#1782

**Comment by Golganeth** [comment]
Merge with #1782
