### ISSUE TITLE
Quest: The Crusaders' Pinnacle (phasing)

### ISSUE THREAD

**Issue by Shanghi** [dalaranwow/dalaran-wow#1598]
After finishing the quest "The Crusaders' Pinnacle" normally, it isn't actually set as being complete even though the phasing continues to make the quest giver disappear. I don't know if it happens every time or if the alliance also have this problem, but so far I've seen it affect 5 horde people including myself. A GM completing it fixes the problem.

This causes confusion for people trying to do the "Icecrown: The Final Goal" quest achievement. It's required for getting the quest "Orgrim's Hammer" from Warlord Hork Strongbrow (or "The Skybreaker" from Marshal Ivalius for the alliance) in the building nearby which then opens up over 20 more quests throughout the area. People, like myself, just assume there's nothing left there and continue on, eventually wondering where the missing quests are.

Players can test if the quest is really completed by pasting these 2 commands separately (wait a few seconds after the first one):
/run QueryQuestsCompleted()
/run local qc = GetQuestsCompleted() print(qc[13157] and "Completed!" or "Not completed!")

The Crusaders' Pinnacle: http://www.wowhead.com/quest=13157/the-crusaders-pinnacle

**Comment by Golganeth** [comment]
Father Gustav disappears (phasing) right after you turn in [The Battle For Crusaders' Pinnacle](http://wotlk.openwow.com/quest=13141) - *ID: 13141*
For that reason, you can't take the follow up [The Crusaders' Pinnacle](http://wotlk.openwow.com/quest=13157) - *ID:13157* which sends you Tirion and opens more quests.

**Comment by mihailovici** [comment]
These kind of issues are very important to fix.If you really understand us as truly wow players than you know that this issue is staying in our way to finish the journey we started.So please fix this.Thank you.

**Comment by Lothloryen** [comment]
This issue has been corrected, it is already active on the live realm.

Thank you.
