### ISSUE TITLE
Cure the Sick (Alliance Druid Poison Quest)

### ISSUE THREAD

**Issue by jerimiahshort** [dalaranwow/dalaran-wow#1600]
The entire chain up to this point works great, however upon usingthe salve to cure the sickly deer; it works (the sickly deer become cured) but credit it not given. Tried multiple times on various sickly deer (some are olive green, others have the poisoned look) to no avail.

**Comment by Demlock** [comment]
Confirmed. This is still bugged :/

**Comment by ffighter29** [comment]
Confirmed.

**Comment by Daveonx** [comment]
Players now get credit when using the item on the Sickly [Deer](http://www.wowhead.com/npc=12298/sickly-deer)/[Gazelle](http://www.wowhead.com/npc=12296/sickly-gazelle), but still get credit after killing them.

**Comment by Rushor** [comment]
works fine http://i.imgur.com/b3xZ5OQ.jpg
