### ISSUE TITLE
Seal of Ascension quest 

### ISSUE THREAD

**Issue by mjpwn** [dalaranwow/dalaran-wow#1603]
This part doesn't work http://www.wowwiki.com/Quest:Seal_of_Ascension_(2)
Emberstrifes flame doesn't forge the seal, it has no effect over it.

**Comment by n-ghost** [comment]
Confirmed, the drake (even freshly spawned) doesn't have an ability (http://www.wowhead.com/spell=16054/flames-of-the-black-flight) that's needed to be used on seal to complete the quest.

**Comment by mjpwn** [comment]
wow..this guaranteees i'll never play there again 

     On Saturday, 14 February 2015, 15:26, n-ghost <notifications@github.com> wrote:
   

 Confirmed, the drake (even freshly spawned) doesn't have an ability (http://www.wowhead.com/spell=16054/flames-of-the-black-flight) that's needed to be used on seal to complete the quest.—

**Comment by Demlock** [comment]
Confirmed, this quest is bugged. Emberstrife can be controlled and has all the abilities but the flame won't forge the new item.

**Comment by koubx** [comment]
Confirmed here also. There is a flame breath to cast, but doesn't affect the seal.

**Comment by Golganeth** [comment]
The game object with the Seal doesn't seem to despawn after a while. The Dominion of Soul has a wrong timer on the player's buff bar so it can't be right clicked in time to automatically dismiss Emberstrife. Gotta right click pet frame and dismiss it from there.
