### ISSUE TITLE
Lost Thunderbrew Recipe

### ISSUE THREAD

**Issue by Spruitje** [dalaranwow/dalaran-wow#1613]
The quest [Lost Thunderbrew Recipe] (http://www.wowhead.com/quest=4134/lost-thunderbrew-recipe)

After destroying the kegs (there are 3) nothing happens

**Comment by n-ghost** [comment]
https://github.com/dalaranwow/dalaran-wow/issues/917

**Comment by Golganeth** [comment]
Duplicate of #917 indeed, closing up. Thanks @n-ghost
