### ISSUE TITLE
Thassarian and NPC's of Skybreaker.

### ISSUE THREAD

**Issue by Jarms** [dalaranwow/dalaran-wow#1614]
The NPC on Skybreaker, have seem to dissapeared. Have waited for around 4 hours for a spawn or it giving some attention, but nothing is happening?

**Comment by Golganeth** [comment]
#907

**Comment by Dragongl11** [comment]
Still dissapear and suddenly appear - i dunno why this happens such way, he have to appear all the time on the board.
