### ISSUE TITLE
Quest: Reclamation

### ISSUE THREAD

**Issue by ArgustheLight** [dalaranwow/dalaran-wow#1615]
This is the last quest given by the Avatar of Freya in Scholazar Basin. It's doable, but buggy. Urgreth is not supposed to stop casting (I forget the name of the spell, it's a channeled ability) when you move away from him.

I remember he was particularly difficult, and in retail the way I completed this quest was to move away when he does his AoE, regen mana, and attack him afterwards. Here, when you move away he just stops casting and keeps attacking you.

There's a LoS bug which allows you to complete the quest, but it's far from perfect.

http://www.wowhead.com/npc=28103#comments

**Comment by Rushor** [comment]
619764f41a91fce60dde5158829e13a6ffcb6431
- respawntime will now be between 60 (or 120 seconds if not 60 seconds)

**Comment by Kaporalhart** [comment]
Well i'm impressed how fast you took care of the issue. Good job, keep up the good work.

**Comment by Golganeth** [comment]
1 min respawn timer for bosses works fine. Small issue here, where Glonn and Cerberon don't have a synced respawn timer with their owner (Bythius the Flesh-Shaper). The dogs have a 7-8 min respawn timer currently, not a big deal.

http://wotlk.openwow.com/npc=28207 Cerberon
http://wotlk.openwow.com/npc=28211 Glonn

**Comment by Rushor** [comment]
kay bumping this to myself

**Comment by Rushor** [comment]
e3f7d9c55e84747575c7efbc96e556f1c2400764
- alright, despawntimer for these two dogs adjusted
