### ISSUE TITLE
NPC: Captain Skarloc - Instance Old Hillsbrad Foothills

### ISSUE THREAD

**Issue by Crispybuilt** [dalaranwow/dalaran-wow#162]
NPC Captain Skarloc 17862 is missing his weapon and shield in his hands. 

http://www.wowhead.com/npc=17862/captain-skarloc#screenshots:id=21639

This is simillar to Grand Marshal Stormwind Sword from a PvP vendor

His weapon is: http://www.wowhead.com/item=12584/grand-marshals-longsword#screenshots:id=12508

But his shield, I cannot recognize

**Comment by Rushor** [comment]
http://i.imgur.com/DivePwM.jpg
http://i.imgur.com/FNlcZNC.jpg

shield and sword are there (i summoned them manually, but that doesn't change anything)
