### ISSUE TITLE
QUEST: Taken by the scourge  (ALGALON)

### ISSUE THREAD

**Issue by darakleon** [dalaranwow/dalaran-wow#1627]
Hi guys. Is about the quest:

Taken by the scourge ( http://www.wowhead.com/quest=11611 ).

In this quest you must brake webs to liberate workers.
In this quest when u brake a web , three things can happen:
1.Nothing
2.A peon inside, count one for quest completion.
3.A NPC allied comes out, buff you with a buff depending of wich NPC comes out and then follow you as a guardian.

PROBLEM:
The main problem is, in this quest, at first, u have more probabilities to get a guardian on every web , but, when u have 3 guardian (one of each type), u must have a huge probabilites to get a peon . Is intendeed to be a normal quest, doing it fast and go other quest.

But here in dalaran-wow the probabilities of get a guardian never changes, so it is always very high and you almost always get a guardian, convergint this quest in a pain in the ass and imagine if there are more people doing it....

Also, a minor problem, the NPC doesnt give you the buffs of each type, but meh, who cares that.

Thanks in advance , keep the good work guys

**Comment by vison2** [comment]
Confirmed

**Comment by Leodimas** [comment]
confirmed, also the guys you rescue that can give you a buff, also used to fight a bit for/with you . As it its now they deal 1 dmg

**Comment by Vaxsysl** [comment]
Not working since new fixes introduced last night.

**Comment by Lothloryen** [comment]
Hello there,

The quest works, however the chance to get a Warsong peon feed is small. I it is corrected already and should be on the live realm after the next scheduled maintenance.

Thank you very much.
