### ISSUE TITLE
[Fear Ward] [Algalon]

### ISSUE THREAD

**Issue by pascagabriel** [dalaranwow/dalaran-wow#1629]
Fear Ward seems to have an lingering effect after being dispelled off the target. I am not sure how long and under what conditions this bug occurs but it has happened to me and the opponent priest I was playing. I dispelled Fear Ward off of him and instantly feared him as soon as my GCD finished, which was around 1.3s, but he was unaffected by it and  the "Immune" message appeared on my screen. In a later game, the same situation occured, myself immuning his fear even though he had just dispelled Fear Ward off of me.

**Comment by robinsch** [comment]
Can't confirm. Dispelled and Feard on next global.
