### ISSUE TITLE
Auction house sales

### ISSUE THREAD

**Issue by Yozzzy** [dalaranwow/dalaran-wow#1632]
Hello i have a rly big problem.My auction house sales are only giving me gold for half of them and for rest i only receve the letter saying Estimated delivery time 00:00 and then after a day or 2 the letter gets deleted and i dont get any gold from that sales.

![wowscrnshot_052614_095206](https://cloud.githubusercontent.com/assets/7700133/3080159/056f596c-e4ab-11e3-8e51-4d69a2f095e4.jpg)
![wowscrnshot_052614_095213](https://cloud.githubusercontent.com/assets/7700133/3080160/0e6d6df6-e4ab-11e3-96a8-a9748429ca19.jpg)
![wowscrnshot_052614_095216](https://cloud.githubusercontent.com/assets/7700133/3080165/25b8df4a-e4ab-11e3-93db-9f2e9a06cefe.jpg)

**Comment by Golganeth** [comment]
#1390
