### ISSUE TITLE
[Burning Crusade][Deadwind Pass/Kharazan][Quest] Arcane Disturbances

### ISSUE THREAD

**Issue by Akkalevil** [dalaranwow/dalaran-wow#1634]
Using the Violet Scrying Crystal doesn't validate the quest objectives, making the completion of the quest (and the subsequent entrance into Kharazan save for the "secret hole") impossible.

**Comment by Vaxsysl** [comment]
Still not working on Algalon realm.

**Comment by Lothloryen** [comment]
Hello there,

Thank you very much for your reports. These quest was prepared already to be working after the next update. So, you should be perfectly able to complete it.
