### ISSUE TITLE
NPC / Quest: Lar'Korwi / The Bait for Lar'korwi

### ISSUE THREAD

**Issue by Crispybuilt** [dalaranwow/dalaran-wow#164]
Quest The Bait for Lar'korwi -  4292
NPC - 11510

Issue: Once you use both the items on the rock to set up the bait, Lar'korwi should be spawned. (for now only mixture is needed to spawn him, but not the meat) - first the meat should be placed on the rock, and then the mixture and then he spawns. Condition has to be corrected (just that)
____________________________________________
Second Issue is that the creature, once summoned, should not respawn for other players on that spot, he has to dissapear and never spawn again until summoned by some other player.
How it should work:

When you accept the quest The Bait for Lar'korwi from Torwa Pathfinder you are given Torwa's Pouch. This will go into your pack. Right click on Torwa's Pouch to open it. It will put items Preserved Pheromone Mixture and Preserved Threshadon Meat into your pack. 

Go to Un'Goro Flat Rock (79.9,49.9). Stand on the Un'Goro Flat Rock and right click on Preserved Threshadon Meat that is in your pack. Then right click on Preserved Pheromone Mixture that is in your pack. 

Lar'korwi will appear just near the Un'Goro Flat Rock at location 79,49.

http://wotlk.openwow.com/quest=4292
http://wotlk.openwow.com/npc=9684

**Comment by Rushor** [comment]
3ac86d95b6f233bcef4857aee2701f0e1eeedc8f
- the gameobject 169216 will now only be summoned if you cast 15118
- the order how to setup the items on the ground should be correct now

**Comment by Golganeth** [comment]
Works fine, although the meat gobject doesn't seem to despawn after 10 minutes. So if another player arrives just gotta place the mixture and the boss will spawn.
