### ISSUE TITLE
Quest: Hatching a Plan

### ISSUE THREAD

**Issue by Shamalalla** [dalaranwow/dalaran-wow#1640]
http://www.wowhead.com/quest=11936/hatching-a-plan

How should it work: you are supposed to kill Coldarra Wyrmkin (http://www.wowhead.com/npc=25728), loot them, take their frozen axes (http://www.wowhead.com/item=35586) and break 5 blue dragon eggs (http://www.wowhead.com/quest=11936/hatching-a-plan#screenshots:id=89502).

Where's the issue: The Wyrmkin correctly drop the item but the eggs doesn't appear to respawn once broken. I ran around for more than 10 minutes but they didn't spawn

.

**Comment by taralej90** [comment]
There are currently 2 issues with the eggs:

1) When broken, they still "sparkle" as if they can be used for the quest, which indicates there is a problem with how the eggs are counted;
2) The respawn timer is around 30 min, which I believe is tied to the above issue. The normal object respawn should be no longer than 5 min, auto-adjusting when more players are interacting with it (another thing that I have yet to see implemented on any private server).

This quest works like this on all other Trinity-core servers I've played. I was disappointed to find out Dalaran-WoW too hasn't fixed this...

**Comment by deltafoxnine** [comment]
Still bugged

**Comment by Cone182** [comment]
confirmed, still bugged.

**Comment by dragondd** [comment]
confirmed, still bugged. please fix this quest

**Comment by nyrpha** [comment]
as of 21-09-2015 the eggs still take very long to respawn. two guys just did the quest before me, and during a 20 minute wait no eggs became available. please adjust the respawn timer to 30 seconds instead of 30 minutes.

**Comment by VonKaufmann** [comment]
Still bugged. Almost two years this bug has existed. Wow...

**Comment by kevinmd88** [comment]
Still bugged. Encountered precisely 10 minutes ago. Eggs showing their "broken" appearance, are sparkling as if possible to interact with them, cannot be interacted with by right-clicking or by using the Frozen Axe on them, and either do not respawn or take an inordinate amount of time to do so.

**Comment by Lothloryen** [comment]
Hello there,

This quest has been corrected and the fix should be active after the next scheduled maintenance.

Thank you.
