### ISSUE TITLE
STV Fishing Extravaganza Does Not Start at 14:00

### ISSUE THREAD

**Issue by cypherrage** [dalaranwow/dalaran-wow#1649]
When does this contest start on Algalon?  It is supposed to be at 14:00, and the calender even says 14:00, but I have been sitting here for 30 minutes now since 14:00 ST and the Contest NPCs are nowhere to be seen.

I tried fishing up the contest fish as well and I could not, so the event definitely has not started.

**Comment by Golganeth** [comment]
Merging with #1134
