### ISSUE TITLE
[Quest] Lab Work

### ISSUE THREAD

**Issue by Skyl3lazer** [dalaranwow/dalaran-wow#1650]
This quest can get stuck, where you can't click on the pot to throw in more ingredients. If this happens, you also can't restart the quest, even if you drop/re accept it, you'll never get the option to begin the ingredient grab again.

**Comment by mankring** [comment]
still...

**Comment by zr00130** [comment]
I came across the same issue. This might be conjecture but Finklestein stopped telling me what to grab once another person started the quest.

Either way, how I completed the quest was I just ran to each shelf and picked up every item that I could. You will finally get credit for one of them. Then I ran back to the cauldron and right clicked on it until all of the items expired. Then I started over again.

After 5 or so pickups I finally got the quest complete. Also remember you can get items out of the sacks, barrels, and boxes so try as well.

**Comment by jonanone** [comment]
We have made some improvements to the quest to avoid problems when multiple players attempt to complete it at the same time.
Also canceling and re-accepting the quest will show you the option to start the quest again.

This fixes will be applied to the live realm soon.
