### ISSUE TITLE
[Quest] Making Peace

### ISSUE THREAD

**Issue by Skyl3lazer** [dalaranwow/dalaran-wow#1654]
This quest becomes available too early: it shouldn't show up until you've also completed Gods Like Shiny Things. The game lets you pick up the quest, but you immediately get a "You dont meet the requirements for this quest" error and the quest disappears. It does indeed come back after finishing the Shiny quest, but it shouldn't be available to be taken in the first place, and it's very confusing.

http://www.wowhead.com/quest=12573/making-peace

**Comment by jonanone** [comment]
This is working properly now.
