### ISSUE TITLE
[NPC] Engineer "Spark" Overgrind

### ISSUE THREAD

**Issue by woodiesvk** [dalaranwow/dalaran-wow#1662]
There is NPC bugged (spawned too many times) on one location because of quest "Tree's Company". NPC should despawn after quest is completed. It only spawns when quest begins, but does not despawn.

Location: Azuremyst Isle - Traitor's Cove (19,44 82,40)
Quest: http://wowhead.com/quest=9531

![wowscrnshot_060414_150913](https://cloud.githubusercontent.com/assets/6662101/3173669/95c875a8-ebe9-11e3-8c9d-76aa2237edff.jpg)

Biggest problems caused: FPS drop and chat spam.

**Comment by Rushor** [comment]
Scripts/Kalimdor: Engineer "Spark" Overgrind and Geezle should always be active

* closes https://github.com/dalaranwow/dalaran-wow/issues/1662
* they should always despawn now
* commit: 7899dcfc1b4e3ae8945b81d6c762b63df0fd19fc

**Comment by TeridanDW** [comment]
Works as intended on ptr.
