### ISSUE TITLE
[NPC] Laughing Sister (Raynewood Retreat, Ashenvale)

### ISSUE THREAD

**Issue by VictorTyne** [dalaranwow/dalaran-wow#1664]
Issue:

The Laughing Sister (http://www.wowwiki.com/Laughing_Sister) dryads of Raynewood Retreat in Ashenvale are all currently armed with wrenches.
![wowscrnshot_060414_143213](https://cloud.githubusercontent.com/assets/7576380/3180379/7297fcf6-ec30-11e3-982d-c4c2f815ff0e.jpg)

How it should be:

The Laughing Sisters should not be holding anything

**Comment by Rushor** [comment]
![GitHub Logo](http://i.imgur.com/kOaxWDv.jpg)
Already fixed on live
