### ISSUE TITLE
Quest / Howling Fjord / The Fallen Sisters

### ISSUE THREAD

**Issue by dalaran-bug-reporter1321** [dalaranwow/dalaran-wow#1665]
The quest "The Fallen Sisters" [id 11314] cannot be completed because the Pendant cannot target the NPCs to update the quest. The message reports invalid target.

The quest item in question is: 
Lurielle's Pendant [id 33606]

The quest NPC that is the pedant is used upon is:
Chill Nymph [id 23678]

**Comment by indigoataxia** [comment]
Not working for me, getting invalid target and cannot attack the nymphs as they are green.

![image](https://cloud.githubusercontent.com/assets/12549223/7960896/d797e8e0-09d1-11e5-9d4f-6a2895cda29d.png)

**Comment by deltafoxnine** [comment]
Confirmed still bugged. The nymphs still don't respawn in hostile state, therefore unable to complete quest until server restart.

**Comment by Blackoutx** [comment]
just got 1 / 7 credit for killing the quest giver. its gunna take a while boys

**Comment by MrAndersonX** [comment]
Confirmed - bugged. Needs a fix.

**Comment by Mantigora** [comment]
Confirmed - does not work as intended.
Possible workaround - kill quest giver Chill Nymph [id 23678]  7 times. You don't need to use quest item on her.b

**Comment by Oelacs** [comment]
Still dont work as of 22/2-16

**Comment by Lothloryen** [comment]
Hello there,

This quest has been corrected and it is already on the live server.

Thank you.

**Comment by Golganeth** [comment]
In WoTLK I think the quest item should only be usable once NPCs are weak (30%~ "Chill Nymph appears weak!" message appears)
Right now you are able to use the quest item when the NPC is at full HP but nothing will happen.
Proof needed.

**Comment by Rushor** [comment]
By aeonix05 (155 – 1) on 2011/10/27 (Patch 4.2.2)		
cant attack the nymph and cant use the pendant. it says invalid target. :(

indirect proof for the errormessage at 100% hp

**Comment by Golganeth** [comment]
That might be the bug where they would get stuck as 'friendly'
