### ISSUE TITLE
Quest: Bladespire Kegger

### ISSUE THREAD

**Issue by Sagrath** [dalaranwow/dalaran-wow#167]
http://www.wowhead.com/quest=10545/bladespire-kegger
When you place a Keg on the ground, it does attrack the ogre, but it does not get you drunk nor you get the credit for it.

**Comment by Zibathy** [comment]
Confirmed x2. What n-ghost said.

**Comment by Klala** [comment]
Actually, it does work on brutes at least.
All you have to do is kill them where you put the brew and not let them go back to their position

**Comment by Penguindrum** [comment]
Yes works on brutes, but they need to be stationary mobs with no movement whatsoever. Only then will they get drunk. Easiest way to find stationary brutes is to check the huts.

**Comment by Rushor** [comment]
getmotionmaster()->Clear(); on spellhit

**Comment by Rushor** [comment]
6ec0e5192481aee422335287df9537b2b9f62f8e
- the item will noe work for the creatures 19991, 19995, 19998, 20334, 21241
- the script will also work if the creature are moving
