### ISSUE TITLE
[Mechanic] Scaling Reducing Effects - Wrong reapply after auras fades

### ISSUE THREAD

**Issue by vareesa** [dalaranwow/dalaran-wow#1674]
Hello there. There is a mandatory bug in Drak'tharon Keep which is being abused by many players. The boss called "King Dred" - http://www.wowhead.com/npc=27483 , has an ability called "Bellowing Roar" - http://www.wowhead.com/spell=22686 , which is bugged. When he fears people they all get +250 Spell Power. What makes it even worse, you keep that Spell power even after you leave the dungeon and even if you die. The only way how you lose this ridiculous buff is when you log off. Here are screenshots to prove this:

http://prntscr.com/3qg0nb 

Check my buffs and especially Spell power which is 2806.

http://prntscr.com/3qg0qr 

Now check my Spell power again. It is 3056 which is 250 higher than before while i have excactly the same gear and buffs. That is because I got feared by the boss and it gave me permament +250 Spell power.

http://prntscr.com/3qg0sx

Here you can see that the buff remains even when you leave the dungeon. I still have 3056 Spell power.

So please fix this crap as soon as possible because there are many people abusing this in PvE.

**Comment by Rushor** [comment]
This happens with all spells which reduce the spellpower for a period of time
