### ISSUE TITLE
Quest: The Stones of Vekh'nir

### ISSUE THREAD

**Issue by Crispybuilt** [dalaranwow/dalaran-wow#168]
Quest The Stones of Vekh'nir - 10565

Issue: Once you complete the quest and you get the quest item, you can't turn it in instantly at the NPC.
How it works for now: Abandon the quest and re-take it and you can turn it back right away.
How it should work: You should be able to turn in the quest without abandoning it 

http://wotlk.openwow.com/quest=10565
Quest Item upon completing it: http://wotlk.openwow.com/item=30567

**Comment by DrFuler** [comment]
15/12/2015: Crispybuilt's solution confirmed!

Thanks a lot! I was very upset with this quest because it leads to others, and this was my second character to have this problem. Your solution (abandoning and retaking it) works perfectly! (Just wished I knew that before haha)

**Comment by Daveonx** [comment]
Confirmed, still and issue.

**Comment by Rushor** [comment]
6c3cbb8075eb91e652645ddb12da5ac486fcb349
- the quest will now always be completed, even without abandoning and retaking it
