### ISSUE TITLE
[Item] Fury of the Five Flights

### ISSUE THREAD

**Issue by Tsunadee** [dalaranwow/dalaran-wow#1680]
This Item should stack up with Seal of Command procs for Paladins.

Current Situation:
Using Divine Storm with 4 mobs and Seal of Command, only 4 stacks are granted.

How it should be:
Using Divine Storm with Seal of Command should give an additional stack for each Seal of Command proc.

Source:
http://www.wowhead.com/item=40431#comments:40

Retribution:
The new Seal of Command in 3.2.2 stacks this trinket in seconds on the PTR.
DS and you get 10+ stacks due to the new cleaving SoC mechaninc, so this is now useful also for AoE/trash situations, no need to swap anymore.

can try to find more if you want.

**Comment by Golganeth** [comment]
Can't confirm. Closed until proof is given
