### ISSUE TITLE
NPC : Blood Elf Bandit

### ISSUE THREAD

**Issue by bravade** [dalaranwow/dalaran-wow#1685]
http://www.wowhead.com/npc=17591/blood-elf-bandit

Some Blood Elf Bandit are not stealth.

In fact, I think that at spawn time they are stealth, but if they are aggro and not killed, they don't use Shadowstalker Stealth (Shadowstalker Stealth) anymore.

**Comment by Rushor** [comment]
![GitHub Logo](http://i.imgur.com/5rmIT3w.jpg)

The issue was fixed 1 year ago
