### ISSUE TITLE
[Quest] Gluttonous Lurkers

### ISSUE THREAD

**Issue by Shaann** [dalaranwow/dalaran-wow#1687]
If you stay mounted while picking up Zul'Drak Rat, the rat will not disappear. You could get enough rats from one rat for the entire quest vs. chasing them around if you pick them up while mounted.

**Comment by Dasher2417** [comment]
Still happening. Picking Basilisk crystals can also be abused same way. After you feed them all 5 rats, they become friendly, and you leave combat, you can mount up right away, and spam looting, while mounted up - the basilisk won't disappear.

**Comment by jonanone** [comment]
Now rats and Basilisks disappear even when the player is mounted.

This fix will be applied to the live realm soon.
