### ISSUE TITLE
[Fishing] Pygmy Suckerfish - non-existent droprate from schools

### ISSUE THREAD

**Issue by GhostAlgalon** [dalaranwow/dalaran-wow#1689]
Server: Algalon

Pygmy Suckerfish are primarily caught from the schools of fish found in Northrend but have a smaller chance to be found in open water. Schools of fish, with the exception of Crystalsong Forest have about a 65% chance to drop suckerfish (Source: Wowwiki)

In addition to this; Patch 3.0.8 (2009-01-20): Now also caught from Northrend pools - rarely from glassfin minnow school, commonly from other pools.

Issue: According to many different sources, the droprate of Pygmy Suckerfish is supposed to have a average of 50%+ droprate chance when fished from schools. I have not to find a single Pygmy Suckerfish from any school fished from Northrend, having tried around 10 school of each kind. 

Solve: Make them drop from fishing schools in Northrend aswell.

**Comment by basteh** [comment]
Noticed as well today. Caught around 120~ Glacial Salmons from schools in Howling Fjord, caught zero suckerfish. Later tried open inland water, again ~100 catches, caught 3 suckerfish.

I also remember the 65% rate stated on Wowwiki to be quite accurate, always had around more than half of the fish I was catching in pools.

**Comment by Naidira** [comment]
Confirmed to still be a problem.  After a few hundred catches, 1 suckerfish.

The Pygmy Suckerfish is a key ingredient in multiple alchemy recipes:  Elixirs, Flasks, and even Alchemist's Stones.  This also provides a speedbump for gaining alchemy skill points, as the suckerfish are traditionally the way to gain points at the 375 mark.

http://wotlk.openwow.com/item=40195#reagent-for

**Comment by npmusicftw** [comment]
This is something you guys really need to fix. Potions for raiding need the oil from these, and because they're so rare, potion prices are absolutely ridiculous and insane right now. This needs to be a priority.

I remember on my server, these things sold for 30s a stack. That's how common it was to find them. 

Please, fix this drop rate ASAP.

**Comment by jonanone** [comment]
Pygmy Suckerfish loot has been added to missing Fishing Pools. It already had a 65% chance to drop in one kind of pool but now it has been added to the rest of the pools where it is supposed to drop. This should increase the overall drop rate over Northrend.

This fix will be applied to the live realm soon.

**Comment by Dolarr** [comment]
Any news? It's been 2 months since the last post and it still doesn't work. I've just been fishing from Musselback Sculpin School for a while, got 40 Musselback Sculpin and NONE of the Pygmy...
