### ISSUE TITLE
Rapture [Algalon]

### ISSUE THREAD

**Issue by pascagabriel** [dalaranwow/dalaran-wow#1691]
The Discipline Priest talent [Rapture] puts the casting priest in combat when returning mana if the person the shield was on had combat when the shield broke.

**Comment by Golganeth** [comment]
#2784 -  
> Rapture does not have an internal cooldown on Algalon server. Both effects proc every time a shield is fully absorbed. There needs to be a 12 second cooldown for both of its effects.

>http://forums.elitistjerks.com/topic/97029-wotlk-healing-compendium-v335-fun-in-the-twilight-with-halion/
"The details are a bit more complex, though. Rapture can proc only once every 12s. However, if multiple shields break at exactly the same time and Rapture is not on cooldown, Rapture will proc for most (usually all) of the shields. "

> -MihkelRoogna

**Comment by robinsch** [comment]
On PTR.
