### ISSUE TITLE
[Hunter] Misdirection buff

### ISSUE THREAD

**Issue by Johanes022** [dalaranwow/dalaran-wow#1692]
Current situation:When hunter uses his MD on a friendly target, that target does not recieve MD buff.
Desired situation:When hunter uses his MD, target should get MD buff and players should be able to remove MD buff( by right clicking on it)

Links: http://www.wowwiki.com/Misdirection
-The target of Misdirection can remove their buff. 

Also : https://github.com/dalaranwow/dalaran-wow/issues/1124 sometimes MD bugs out and cd wont start , theres no buff or anything , and it stays that way untill logout.Usualy happends when you try to use MD during GCD.

**Comment by Lothloryen** [comment]
This should be corrected already, thank you.
