### ISSUE TITLE
[Quest] A Cold Front Approaches

### ISSUE THREAD

**Issue by Shaann** [dalaranwow/dalaran-wow#1693]
![Uploading A Cold Front Approaches.png . . .]()
http://www.wowhead.com/quest=13070/a-cold-front-approaches

Siegemaster Fezzik appears in the hut at the front gate, but am not able to turn in the quest to him to open new quests.
Upon dropping the quest, not able to pick it back up.

**Comment by Watterx** [comment]
Confirmed. Did what Exorcista said to make it work!

**Comment by Lothloryen** [comment]
Some corrections about the phasing issue deployed.
