### ISSUE TITLE
Deflection - Rogue talent trait

### ISSUE THREAD

**Issue by Sultanking** [dalaranwow/dalaran-wow#1695]
I see no evidence of this ever working - When my rogue used this trait nothing was registered. Fix this.

**Comment by Rushor** [comment]
http://wotlk.openwow.com/spell=52420

The talent works fine for me, make shure that this part "Melee attacks which reduce you below 35% health..." is fullfilled

**Comment by Rushor** [comment]
and btw: open a new better report if this is still an issue on live like already said in https://github.com/dalaranwow/dalaran-wow/issues/1695#issuecomment-46288741
