### ISSUE TITLE
Quest: The Thunderspike

### ISSUE THREAD

**Issue by Sagrath** [dalaranwow/dalaran-wow#170]
http://www.wowhead.com/quest=10526
Gor Grimgut is not spawning after clicking on The Thunderspike.
Gor Grimgut - http://www.wowhead.com/npc=21319
The Thunderspike object - http://www.wowhead.com/object=184729

**Comment by Zibathy** [comment]
This makes me a sad panda. Pls fix :'(

**Comment by Zibathy** [comment]
It is critical this gets fixed because it makes 13 following quests incompletable... Which affects achievements.

**Comment by Rushor** [comment]
https://github.com/TrinityCore/TrinityCore/commit/80c3f3071e1a51319897bd9751a0549cbdc22fa8

fixed long time ago
