### ISSUE TITLE
[Quest]Fury of the Frostborn King

### ISSUE THREAD

**Issue by Sylvant** [dalaranwow/dalaran-wow#1703]
http://www.wowhead.com/quest=12879
I am not able to turn in quest to Creteus. Quest is in my quest log and its indicated as complete, quest item is in my bags, but when i speak to Creteus no quest is listed in the dialog box.
Anyone else had similar problem with this or another quest recently? What could be causing it and how to deal with it? I tried retake quest, but that didnt help, also deleting my cache folder.

**Comment by ar1s7717** [comment]
still bugged...

**Comment by ar1s7717** [comment]
Creteus' s corpse is outside  the cave, as it should be. I am, however, unable to interact with it at all. Moreover, the area around the engine of the makers is in "quest land" mode so all the mining nodes and creatures that are normally there, are replaced by iron dwarves. Please take care of the matter.

**Comment by Flagg24** [comment]
This bug still exists. It starts at some point in time while you're doing the Thorim portion of the Sons of Hodir questline.

**Comment by epaulito** [comment]
Still confirmed bugged as of now.

**Comment by Lothloryen** [comment]
It should be fine now, any feedback before closing it would be welcome.

Thank you.

**Comment by Flagg24** [comment]
My alt is still locked in phase from it. Still seeing his dead body and unable to turn in quest.

**Comment by Golganeth** [comment]
Creteus is dead, players can't get the quest rewarded.

**Comment by Lothloryen** [comment]
The issues mentioned here were corrected already, as well as the rest of the chain ones.

Thank you.
