### ISSUE TITLE
NPC: Succubus Minion

### ISSUE THREAD

**Issue by Golganeth** [dalaranwow/dalaran-wow#171]
When you engage a fight against Shadowy Summoner in outlands, or any other NPC having as minion "Succubus Minion" such as Bloodsail Warlock in STV, their pet will basically just follow his owner and won't attack the player at all.

NPCs: http://wotlk.openwow.com/npc=17088
http://wotlk.openwow.com/npc=1564
(perhaps more, however not essential as the issue is with the minion)

Succubus Minion: http://wotlk.openwow.com/npc=10928

**Comment by Rushor** [comment]
Issue is up to date in 2016

**Comment by Golganeth** [comment]
Works now on PTR.
