### ISSUE TITLE
[Achievement] Intense Cold

### ISSUE THREAD

**Issue by Sylvant** [dalaranwow/dalaran-wow#1710]
http://wotlk.openwow.com/achievement=2036
The achievement "Intense Cold" is working in incorrect way. I've tried to do it several times by not letting Keristrasza debuff reach more than 2 stacks, yet couldnt manage to do it. Another 2 members of my party, eager to have it, succeeded in it, but not letting the debuff reach 1 stack, that said one was druid that shape-shifted and another was pally dispelling himself, not allowing to get hold in place by the dragon's freezing spell. 
So currently this achieve only works if you dont let the Intense cold debuff reach even 2nd stack.

**Comment by Golganeth** [comment]
Fixed by Loth, it will be active after the next maintenance.
