### ISSUE TITLE
[raid drops] Boots of the Renewed Flight

### ISSUE THREAD

**Issue by Winstrol** [dalaranwow/dalaran-wow#1717]
http://wotlk.openwow.com/item=40549boots-of-the-renewed-flight#contained-in-object
doesnt seem to drop from eoe25, never seen it drop/never seen anyone using them.
Pretty sure others can confirm.
Should be looked into as its BiS for hunters, and maybe other classes aswell

**Comment by Golganeth** [comment]
#1507
