### ISSUE TITLE
[Item] Living Ice Crystals isn't getting the talent's buff

### ISSUE THREAD

**Issue by Jiokko** [dalaranwow/dalaran-wow#1718]
the item Living Ice Crystals (http://www.wowhead.com/item=40532/living-ice-crystals)
isnt getting buffed from talents. The fact is that this trinket should not scale with spellpower BUT it should getting buffed from talents that increase the healing received (like shaman's Purification that increases the healing by 10%).

**Comment by Rushor** [comment]
> The fact is that this trinket should not scale with spellpower BUT it should getting buffed from talents that increase the healing received (like shaman's Purification that increases the healing by 10%). 

That works already.

Rushôr's Living Ice Crystals heals Rushôr for 0.(2710 Overhealed) -- without talent http://wotlk.openwow.com/spell=16213
Rushôr casts Living Ice Crystals at Rushôr.
Rushôr's Living Ice Crystals heals Rushôr for 0.(2981 Overhealed) - with talent http://wotlk.openwow.com/spell=16213
