### ISSUE TITLE
Utgarde Catacombs: Decomposing Ghoul and Devouring Maggot

### ISSUE THREAD

**Issue by VictorTyne** [dalaranwow/dalaran-wow#1722]
In the Utgarde Catacombs, the halls are filled with Decomposing Ghouls and Devouring Maggots. Those mobs should only spawn in the very lower levels for the quest The Shining Light.

What it should look like: http://www.wowwiki.com/File:Utgarde_Catacombs_Entrance.jpg

What it does look like:
![wowscrnshot_063014_160017](https://cloud.githubusercontent.com/assets/7576380/3437099/6a07dcee-00aa-11e4-85e1-88802adf588a.jpg)

**Comment by belegija** [comment]
confirmed
