### ISSUE TITLE
Sentinel Selarin

### ISSUE THREAD

**Issue by che0522** [dalaranwow/dalaran-wow#1723]
Sentinel Selarin doesnt appear after you get A Lost Master Quest done.

http://www.wowwiki.com/Sentinel_Selarin

**Comment by Rushor** [comment]
3ecf9337184919c302db6fd2741245bc3922ba6a
- now she spawn upon reward of quest 3694 or 3694 for 180000 milliseconds
- also added a little event where she walks around

**Comment by Golganeth** [comment]
> "now she spawn upon reward of quest 3694 or 3694"
Did you mean 994 or 995? (Escape through - escorts) If you did, ignore this.

**Comment by Golganeth** [comment]
> "now she spawn upon reward of quest 3694 or 3694"

Did you mean 994 or 995? (Escape through - escorts) If you did, ignore this.
