### ISSUE TITLE
Frenzyheart/Oracles repeatable quests for reputation

### ISSUE THREAD

**Issue by Prljoman** [dalaranwow/dalaran-wow#1729]
Everything is working fine, the only problem is that those 3 quests you get daily give only 850 reputation points instead of 1700. In other words, rep gained from doing quests is split on half instead full rep (we get from 3 quests 250, 250, 350 and we should get 500, 500, 700). I found sources which confirm this.
The thing is if you see in the comments and guides (patch 3.0.3. etc) in WOTLK you get 1700 rep, while probably later in Cata etc. (which can be seen in list of quests on Wowhead) they cut the reputation in half (my guess...). That's how I understood it and remembered from retail. If I'm anyhow wrong, feel free to notify with sources or anything.

Wowhead comments etc.: http://www.wowhead.com/faction=1104#comments

P.S. When I did those quests I was thinking that with only 850 rep it will take long to get that reputation to exalted and I remembered from retail that it was much faster (going almost in the same rhythm as reputation with Kalu'ak which gives 1500 reputation points). That's how I get into looking on internet for the (probably) right information. Thank you!

**Comment by taralej90** [comment]
Well, they still give 250-350 x)

**Comment by Augur89** [comment]
Just checked and the three Frenzyheart dailies I did today ("Chicken Party", "The Heartblood's Strength" and "Tools of War") gave me full reputation gains: 500+500+700. So I think all the Oracle/Frenzyheart dailies have been fixed to give the right reputation but confirmation is still needed for all the quests and, of course, for other factions.

Anyway, good job Lothloryen and let me say it feels glorious being in a server where bugs get fixed eventually!!

**Comment by Augur89** [comment]
Some days have passed and now I'm working on the Oracles dailies. They give the correct reputation gains too.

I recon this issue is no more and so it can be safely closed. Good job!

**Comment by marsalandrei** [comment]
The reputation is fine, however there is a bug atm. I chose oracles after doing the lich quest, and did a few dailies for them, but I cannot do the quests which require you to kill frenzyheart tribe members, because my reputation with them is not at warr, even thought they are hated with me, and I cannot set it to at war; therefore cannot attack them back. I heard aoe works, will have to try fan of knives

**Comment by wwrpg** [comment]
After the last reset the AOE no longer work. There is no way to do these dailies now

**Comment by Golganeth** [comment]
See #5595
