### ISSUE TITLE
Dr. Boom should not be able to move.

### ISSUE THREAD

**Issue by VictorTyne** [dalaranwow/dalaran-wow#1735]
Dr. Boom is an NPC in Netherstorm who you need to kill for the quest "Dr. Boom!". During the quest, you kill him by throwing the provided quest items at him as he has 654,000HP can't really be killed otherwise.

From the wiki:  (http://www.wowwiki.com/Dr._Boom)
"Dr. Boom is a non-elite quest boss with 654,000 hitpoints; he does not move or use ranged attacks, "

Currently, Dr. Boom is able to move, chase down players, and use attacks including a dynamite throw.

**Comment by Aalhazred** [comment]
Dr boom is currently stucked into the rock behind him and it's unkillable / untautable

**Comment by jonanone** [comment]
Dr. Boom is now unable to move. The fix will be applied to live realm soon.
