### ISSUE TITLE
Quest: Fel Reavers, No Thanks!

### ISSUE THREAD

**Issue by VictorTyne** [dalaranwow/dalaran-wow#1738]
It is currently not possible to turn in the quest Fel Reavers, No Thanks!

After completing the objectives, it shows as complete in the Quest Log. The ? Over Nether-Stalker Nauthis's head is silver, but when interacting with him the ? in front of the quest name is yellow. Clicking that option does not allow you to proceed further.

**Comment by Demlock** [comment]
This is working properly now.

**Comment by jonanone** [comment]
Completing Nether Gas In a Fel Fire Engine (Delivering 5 Condensed Nether Gas to an Inactive Fel Reaver) now gives credit for Fel Reavers, No Thanks! so it is completable now. The fix will be applied to live realm soon.

**Comment by Golganeth** [comment]
Works fine. Although I killed all the [Gan'arg Mekgineer](http://wotlk.openwow.com/item=31653) surrounding the area for [Condensed Nether Gas](http://wotlk.openwow.com/item=31653) and got only 4 (5 are needed). The item could use a drop rate increase to 55-60% (56% according wowhead)

**Comment by Golganeth** [comment]
Drop rate adjusted. Applied to live realm soon

**Comment by Braniacz** [comment]
Condensed Nether Gas drop rate is ok, also i can accept the quest from inactive fel reavers but when i click complete quest on the inactive fel reaver it doesnt complete. I tried re-do the quest 3 times and it didnt work, so i guess its broken again.

**Comment by Golganeth** [comment]
It works as intended.

**Comment by Braniacz** [comment]
I tried it once again after notification it supposed to work, I have watched videos how it should work and i can state that indeed it works as intended but I still dont get "fel reavers, no thanks" complete so i am not saying its something wrong with the quest scripting itself just the quest doesnt complete as it should.

**Comment by Fundalicious** [comment]
I've just tried it aswell. It is the subquest "Nether gas in a fel fire engine" that does not give the objective for the main quest upon completion.
Upon turning in the 5 condensed nether gas, chat says "Nether gas in a fel fire engine completed." followed by "Inactive fel reaver begins to sputter as its engine malfunctions", but then nothing happens, you don't get the acknowledgement for the main quest.

**Comment by Golganeth** [comment]
Weird this works exactly as intended on PTR but not live realm. The quest "Nether Gas In a Fel Fire Engine" ID 10850 shouldn't be able to be picked up, a blue questionmark should appear if "Fel Reavers, No Thanks!" is on player's log.

On live realm the quest can be picked up, once it's rewarded the emote triggers but the Fel Reaver keeps moving around forever and never die.
On PTR, blue question mark appears, get it rewarded, Fel Reaver triggers the emote, wanders around a bit and dies.

**Comment by Lothloryen** [comment]
Working in both already.

Thank you.
