### ISSUE TITLE
NPC Gino and his quests [Storm Peaks]

### ISSUE THREAD

**Issue by Prljoman** [dalaranwow/dalaran-wow#1739]
I've done all the prerequisites needed (read on Wowhead, WoWWiki etc.) for this NPC to show up (so I could take quests from him) near teleport on Garm's Rise, but there isn't any sign of him, nowhere to be seen. As I understand it's phasing stuff. I tried leaving the area, leaving Northrend, reloging, reloading ui but nothing helped. I saw somewhere it was said it's repaired but as I see for now, it isn't or it's maybe broken again? Thank you!

NPC Gino: http://www.wowhead.com/npc=29432#starts

**Comment by Augur89** [comment]
It's fixed now! Gino is where he should be and the two quests he gives work flawlessly.

**Comment by Lothloryen** [comment]
Every quest is working now and properly chained with Ricket's ones.
