### ISSUE TITLE
Log Out Timer

### ISSUE THREAD

**Issue by Nain1** [dalaranwow/dalaran-wow#1749]
This might be a duplicate, but I couldn't find a report on it.

Logging out of the game, even when the client is closed should invoke a 20 second log out timer for a character which can't be bypassed unless if the player is in a city or inn, or any area with the feature of instantly logging out available.

In combat, when closing your client, the player's logout timer shouldn't begin until he's out of combat.  If he's in combat, then the player will remain active in the game until he either dies to leave combat, or leaves combat through some other means.

The way it works currently with how it logs players out instantly is highly abusable in both raids and PvP.

**Comment by robinsch** [comment]
Working fine on PTR @Lothloryen. Check https://github.com/TrinityCore/TrinityCore/pull/12045/files

**Comment by Rushor** [comment]
well no idea what to add here, you cannot dissappear with alt f4 with your character on ptr if you have no gm rights

the commit was:
Core/WorldSession: After sudden disconnects, session should persist for a minute

- With this change, if a player alt-f4, he'll only fade from world after a minute

commit: d12737d9bb8a9f7643c3f03344aef3c2c986522f
