### ISSUE TITLE
Mithril spawns in Badlands

### ISSUE THREAD

**Issue by cloven92** [dalaranwow/dalaran-wow#1758]
The mithril nodes in Badlands are insufficient. The Badlands are known as the sweetspot for Mithril Ore, however on dalaran-wow there're only one or two nodes in the whole zone. 

Regards,
Cloven92

**Comment by Demlock** [comment]
Since I've spent a lot of time farming Mithril on previous servers I've played on, I can confirm that what cloven92 says is true. But also, yeah, we all agree upon that Mining and Herbalism nodes are broken on this server.

**Comment by Rushor** [comment]
moved to gerneral issue https://github.com/dalaranwow/dalaran-wow/issues/1208
