### ISSUE TITLE
Bringing Down Heb'Jin Bug

### ISSUE THREAD

**Issue by kyle84835** [dalaranwow/dalaran-wow#1759]
Banging on the drum does not spawn Heb'Jin or anyone/anything at all.  Issue on Algalon server, don't have a character on Kirin Tor able to test there.

**Comment by Vaxsysl** [comment]
NPC is shy to this date!

**Comment by Cone182** [comment]
Still bugged...

**Comment by Watterx** [comment]
Still bug

**Comment by Kenleed** [comment]
Still doesent work.

**Comment by Zantu** [comment]
Same same.

**Comment by Lothloryen** [comment]
It was fixed already.

Thank you.
