### ISSUE TITLE
[Item] Pendant of Myzrael

### ISSUE THREAD

**Issue by che0522** [dalaranwow/dalaran-wow#1763]
Havent seen this drop after clearing most if not all quests below lvl45. I dont want to miss the quest Crystal in the Mountains so I didnt do the quest chain.

I'm curious if the drop rate is correct or not.

**Comment by Rushor** [comment]
the droprates can be found here : http://wotlk.openwow.com/item=4614#dropped-by

The droppchances are correctly on PTR.
