### ISSUE TITLE
[WotLK][Naxxramas][Boss] Heigan's Dance

### ISSUE THREAD

**Issue by Akkalevil** [dalaranwow/dalaran-wow#1770]
The zones in Heigan's Dance are not adequate, and may deal damage even though the characters are in a location where they shouldn't.

Okay, this bug has been reported several time, but each time blindingly disreguarded as "nah, works perfectly". Though, NO, IT DOESN'T.
At the very least, the second zone in the dance is bogus and may deal damage even when you're far from the borders. Proof in pictures.

1) How it SHOULD work, from http://www.wowwiki.com/Heigan_the_Unclean :
http://www.wowwiki.com/File:Heigandance.jpg
As you can see, not only the four zones are well separated WITHOUT OVERLAP, but they even have space in-between them where people don't take damage from the surrounding zones.
In other words : if you are in a zone, you should NEVER take any damage from another.

2) How it DOES work on the server (each image if from a different raid, and each time I was killed by the eruption, checked with the combat log, it's neither disease or anything else) :

![heigan1](https://cloud.githubusercontent.com/assets/6848735/3713696/351eb640-157e-11e4-84e7-b054584a58d5.jpg)
![heigan2](https://cloud.githubusercontent.com/assets/6848735/3713697/352d4f8e-157e-11e4-827a-c459ae2983a0.jpg)
![heigan3](https://cloud.githubusercontent.com/assets/6848735/3713698/353a464e-157e-11e4-9ba5-46b8d0faab76.jpg)

Not only the damage covers the "safe spots" in-between each of the eruption zones, it also covers HALF OF THE ZONE THAT ISN'T ERUPTING !
Here is how it looks compared to the retail version : 

![heigandancecomparison](https://cloud.githubusercontent.com/assets/6848735/3713701/58cfc4d0-157e-11e4-9045-fea9f5e52228.jpg)

So now can we please stop closing the issues saying it all is perfect ? 'cause it VERY OBVIOUSLY isn't.

**Comment by blackeaglebr** [comment]
nothing about that yet ?

**Comment by phurios** [comment]
Heigan the unclean has some more issues.. i mean! The waves of lava get faster as we go through several phase 1 and 2, and when we wipe we get teleported to heigan sometimes to just die again.

**Comment by Lothloryen** [comment]
It should be corrected after the next scheduled maintenance.

Thank you very much for the reports.
