### ISSUE TITLE
Fiery Payback

### ISSUE THREAD

**Issue by daemonicBookkeeper** [dalaranwow/dalaran-wow#1778]
A deep Mage Fire talent, Fiery Payback, has a 5/10% chance to disarm an attacker when they hit the Mage. When it procs and the attacker has no weapons, a "Target has no weapons equipped" error incorrectly appears. The talent otherwise functions perfectly.

**Comment by Vaxsysl** [comment]
Talent doesn't work properly at all.

Currently, taking 2/2 results in Pyroblast having 3sec CD timer (when in red HP) and cast time is 3.5 seconds. I grew annoyed at this, and I swapped specs when in red HP - suddenly, talent works. Cooldown is 5sec, and cast time is 1.5 as it should be (unmodified by haste). I re-logged with the same results.

However, as I eat up or get healed up - get above 35% HP mark - the talent effect reverses back to bugged state.

To further test it, I changed spec to have only 1/2, and effects are the same, taking 1/2 or 2/2 makes no difference.

The damage reduction seems to work fine, tested with another mage (no SP proc items present) with Arcane Missiles, damage was noticeably lower.

**Comment by Vaxsysl** [comment]
I was playing around a little bit. Not sure what sparked the sudden change, but now, if we respec while in red HP, we keep the bonus until we relog. Haven't tested in arena, but talent works in BGs with this "trick" that seems to fix most problems with talents. Until relog that is.

**Comment by Milton3450** [comment]
I can confirm this. only works as 1/2 points. It is quite annoying you have to do this trick every time you want to play fire mage?

**Comment by Milton3450** [comment]
Can the title get changed, since it is not a minor bug?

**Comment by Milton3450** [comment]
Golganeth, dude I made the other thread to sum up the issue with this talent and you closed that. Then change the discription of this issue at least? Since the devs will think that this is only a minor bug, and it is not.

**Comment by Milton3450** [comment]
Any chance this will get fixed?

**Comment by Vaxsysl** [comment]
If you have your hearthstone set in Dalaran, go to FP, fly high enough so when you hit the ground you end up in red HP. Perform talent re-spec (enter Fire spec with Fiery Payback while in red HP) and the talent will work.

**Comment by Vaxsysl** [comment]
![wowscrnshot_092515_042806](https://cloud.githubusercontent.com/assets/5100071/13723533/d18e3780-e868-11e5-988b-d588840faae7.jpg)
It seems that it can be reflected...

**Comment by Lothloryen** [comment]
Talent fixed after the next maintenance.

Thank you for the reports, I will also take a look into the disarm glitch.
