### ISSUE TITLE
[Reputations] Reputation gains from mobs seems affected by levels.

### ISSUE THREAD

**Issue by Akkalevil** [dalaranwow/dalaran-wow#1780]
I noticed that many mobs didn't give the adequate amount of reputation (for example, killings ogres in Kurenai only gave one of my char 5 rep, instead of the 10 rep it should).
After making comparison with what another character gained, it seems that level is part of how much rep is gained (my lvl 65 char gained 13 rep by killing birdmen in Auchindoun instances, while my lvl 80 one only gained 7-9 rep).

Levels should not affect rep gains (it was the case in Vanilla, but it shouldn't in WotLK).

**Comment by Golganeth** [comment]
Just tested and works fine, the reputation increased doesn't seem to change at all.
