### ISSUE TITLE
[Shaman] Spell: Earthbind totem

### ISSUE THREAD

**Issue by Sunite** [dalaranwow/dalaran-wow#1783]
Talented earthbind totem should unstealth if rooted. It does not, fix please

Link of roots from elemental talent tree
http://wotlk.openwow.com/spell=51486
Link of earthbind totem
http://wotlk.openwow.com/spell=6474

Thanks

**Comment by Rushor** [comment]
already fixed http://i.imgur.com/HPNYdyv.jpg the rooteffect removed the stealtheffect
