### ISSUE TITLE
[Shaman] Spell: Hex

### ISSUE THREAD

**Issue by Sunite** [dalaranwow/dalaran-wow#1784]
Hex should dismount hexed target like a polymorph. It does not.

Link of hex
http://wotlk.openwow.com/spell=51514

Thanks

**Comment by Watterx** [comment]
It didn't dismount people on retail.

**Comment by Rushor** [comment]
http://us.battle.net/forums/en/wow/topic/4015341854

i cant hex people thats in the air on their mount i got a plan to hex someone off their mount to let em fall to their death while using spiritwalker's grace but as i pulled it off it said he was immune... anyone else find that annoying you cant dismount people in the air?

This mechanic is blizzlike. It sould not dismount you.
