### ISSUE TITLE
Pet - combat bug

### ISSUE THREAD

**Issue by vareesa** [dalaranwow/dalaran-wow#1785]
This reffers to: https://github.com/dalaranwow/dalaran-wow/issues/1465

http://www.arenajunkies.com/topic/72876-pet-combat-bug/
http://www.arenajunkies.com/topic/154952-pet-combat-sap-bug/
http://www.arenajunkies.com/topic/118924-combat-bug-with-pet/

If you send your pet on a target rogues can still sap you which shouldn't be possible. You can actually read that in those links the guy here posted (The Arenajunkies ones) and also check many of retail WOTLK arenas such as Draintrain's one: http://www.warcraftmovies.com/movieview.php?id=149469
There are MANY more which shows the same but this should be enough to get you the idea. Warlock couldn't be sapped on retail while he sent pet on someone. It's true that this mechanic is "working" differently on many privates. On some you (caster) just get into combat along with the pet when you send him. On the others you are not in combat but pet is and you can't get sap (that's how it should work).
Please fix this ASAP because it's one of the most mandatory Warlock mechanics how to fight against rogue team (especially double DPS, they get free sap this way and in other words free win).

**Comment by Rushor** [comment]
already fixed on PTR

https://github.com/TrinityCore/TrinityCore/pull/12083
https://github.com/TrinityCore/TrinityCore/pull/12084
