### ISSUE TITLE
Achievement: My Girl Loves to Skadi All the Time

### ISSUE THREAD

**Issue by Golganeth** [dalaranwow/dalaran-wow#1787]
http://wotlk.openwow.com/achievement=2156

The achievement isn't obtainable even if you meet the criteria, which is:
*"Defeat Skadi the Ruthless in Utgarde Pinnacle on Heroic Difficulty after having killed Grauf from 100% to dead in a single pass."*

This issue, together with #515, #1155 and #1407 makes [Glory of the Hero](http://wotlk.openwow.com/achievement=2136) impossible to obtain.

**Comment by urdarchina** [comment]
As of October 2015 this still doesn't work. I would really like to see these achievements fixed for "Glory of the Hero" meta achievement.

**Comment by Crispybuilt** [comment]
If sunwell scripts can be applied just for this particular fight the achievement criteria would work I believe, just tested it on my core.

**Comment by Crispybuilt** [comment]
On the side note: The problem lies in the encounter itself and achievement criteria can not be met because of the following issue:
*When you shoot the arrows from the Harpoons, they also damage Skadi as well and that makes him to die together with Grauf while being in the air.*

**Comment by Lothloryen** [comment]
Issue corrected, it shall be alive after the next maintenance, which will happen in about 15-20 minutes.

Thank you.

**Comment by PolarCookie** [comment]
we finished the achievement, but the next door didn't open, and skadi first landed on the fence behind the harpoons.
He was out of sight, but we managed to move him to the side and then to the floor.

**Comment by Lothloryen** [comment]
Thank you, the issue with the door shall be fixed after the next maintenance, there was a small mistake with it. About he landing behind the harpoons, I do not seem able to reproduce, let's see if more players experience it.

**Comment by Lothloryen** [comment]
Hello again,

Found the issue with Skadi getting stuck within the fence, it has been already corrected and shall be deployed altogether with the door correction.

Thank you for the report.
