### ISSUE TITLE
Dire Maul North, tribte run

### ISSUE THREAD

**Issue by Schnap** [dalaranwow/dalaran-wow#1791]
The tribute run where you do not kill the guards do not work. There is no mob spawning at the Kings' corpse.

http://www.wowwiki.com/Dire_Maul_tribute_run

The tribute run is needed to obtain the item Gordok Green Grog, which is benefical to use for raiders. Few people know about it. 
![image](https://cloud.githubusercontent.com/assets/5253352/3831633/9e645c76-1d95-11e4-99b6-72b233b6610b.png)

Nothing happends when you kil lthe King as you see.

**Comment by Golganeth** [comment]
#2503
