### ISSUE TITLE
Basic campfire does not give the buff

### ISSUE THREAD

**Issue by Schnap** [dalaranwow/dalaran-wow#1792]
http://www.wowwiki.com/Basic_Campfire

The campfire does none of the following:

Anybody in range of the fire gets a +4 spirit Buff.
It is possible to raise your cooking skill when you create a campfire

![image](https://cloud.githubusercontent.com/assets/5253352/3832298/80bb1ce4-1d9c-11e4-861b-009c05c51111.png)

**Comment by TheLichWarrior** [comment]
It will be nice fix thank you

**Comment by ImprezaWoW** [comment]
Got fixed somewhere along the way, works fine now.
