### ISSUE TITLE
[Paladin][cleanse]Can't be resisted on harmful spells

### ISSUE THREAD

**Issue by chereyo** [dalaranwow/dalaran-wow#1797]
Talents such as silent resolve and vile poisons don't work against a paladin's cleanse. It doesn't seem to be the dispel resist mechanic that doesn't work, but rather just cleanse ignoring it. Silent resolves works when trying to dispel the buffs from the priest.

Also, cleansing totem from shamans seem to be unaffected by dispel resist.

**Comment by robinsch** [comment]
Tested, working fine. https://i.gyazo.com/ffededed4351be966679dc45f736071a.png
