### ISSUE TITLE
[Shaman] Earthbind totem - Combat

### ISSUE THREAD

**Issue by jessyo** [dalaranwow/dalaran-wow#1798]
http://mop.wowhead.com/spell=2484

Players affected by the earthbind totem slowing effect (not talking about the talented earthbind totem of elemental spec) get instantly in combat, although they should stay out of it.

It is quite gamebreaking for rogues, as they can't use their sap ability when they're in combat.

**Comment by Rushor** [comment]
/issues/5290

**Comment by Rushor** [comment]
Spell/Shaman: Earthbind Totem - should not generate threat

* closes https://github.com/dalaranwow/dalaran-wow/issues/1798
* the spellcast ( http://wotlk.openwow.com/spell=3600) itself on a target will no longer generate threat
* commit: 72353bc1123a260023fd1725cc009e6d058b16f9

**Comment by TeridanDW** [comment]
Works as intended on PTR.
