### ISSUE TITLE
Gordunni Ogre Mage only casting one spell

### ISSUE THREAD

**Issue by Saisino** [dalaranwow/dalaran-wow#1807]
Gordunni Ogre Mages in Gordunni Outpost in Feralas only cast one lightning strike upon aggroing them and them pop bloodlust. after that they just stands still until killed or aggro is lost.

**Comment by Morens-D** [comment]
NPC Gordunni Ogre Mage (ID: 5237) works as intended now. Cheers!

**Comment by Rushor** [comment]
you added the fix in the repo, or was it already working @Morens-D ?
