### ISSUE TITLE
[Mechanic][Spell] Interrupts on player's pets/mobs/minions - No spellcooldown

### ISSUE THREAD

**Issue by cycka625** [dalaranwow/dalaran-wow#182]
The part of any interrupt spells(like wind shear, kick, shield bash, counterspell, spell lock, mind freeze, feral charge)  aren't  working on player's pets (thats really important in PVP), mobs and their minions. The exactly part that doesn't work is that those pets mobs or minions are "prevents any spell in that school from being cast". E.G. I'm shaman and my interrupting spell is called "wind shear" It should prevent mob from being cast the school that was interrupted for 2 seconds. But whenever I interrupt the mob he just starts to cast the same spell again in the same second he got interrupted.
I don't know what link should i give so ill just drop links with interrupting spells that are not preventing spells from being cast.
Kick http://wotlk.openwow.com/spell=1766
Wind shear http://wotlk.openwow.com/spell=57994
Shield bash http://wotlk.openwow.com/spell=72
Mind freeze http://wotlk.openwow.com/spell=47528
Pummel http://wotlk.openwow.com/spell=6552
Feral charge http://wotlk.openwow.com/spell=16979
Counterspell http://wotlk.openwow.com/spell=2139
Spell lock http://wotlk.openwow.com/spell=67519

**Comment by Uthil** [comment]
I can confirm to with [Shield Bash](http://wotlk.openwow.com/spell=72), mobs isn't interrupted and start to cast again in the same second they got interrupted.

**Comment by TheLichWarrior** [comment]
14 03 2015 same thing happens on my warrior shield bash cant interrupt school of magick for 6 seconds on mob's

**Comment by Lothloryen** [comment]
This was implemented already.
