### ISSUE TITLE
Manabomb's Strange Aura

### ISSUE THREAD

**Issue by n-ghost** [dalaranwow/dalaran-wow#1823]
http://www.wowhead.com/spell=32407

This debuff should affect any player that enters Cenarion Thicket subzone of Terokkar Forest and fade away when player leaves this subzone. Also, all Fallen Druid NPC there (http://www.wowhead.com/npc=18490) have it, as well as Warden Treelos (http://www.wowhead.com/npc=18424).

It has 2 effects: 
- reduces all stats by 5%
- quoting wowhead commentary: 'Arcane damage spells suffer a high resist rate while affected by this aura. Arcane based spells from a level 65 mage had damage reduction of 50% to 100% on almost all casts. I had to switch to fire and ice spells to avoid the resists'.

Currently player recieves no debuff when entering the subzone, nor any druids are affected by it.

Also needs to be tested if similar aura affects Firewing Point after anyone finishes the Final Code quest chain.

**Comment by n-ghost** [comment]
Atm both auras are present, good job.

**Comment by Rushor** [comment]
already fixed
