### ISSUE TITLE
Blood elf death knight - master of ghouls #death knight

### ISSUE THREAD

**Issue by stewazy** [dalaranwow/dalaran-wow#1838]
Hello I have a problem with my dk in unholy spec when i summon my ghoul with the talent master of ghouls it should have a name but it doesn't it just says Risen ghoul it works fine. But when i use death pact on it, the ghoul just disappears and it doesn't trigger the cooldown on raise dead spell, i have to relogg to make it work :S. Am I the only one with this problem or r there other people with similar problems. The summon ghoul and death pact works normally when i'm in blood spec. Can someone help me, what steps should i take to solve this problem ? Thanks in advance

**Comment by Rushor** [comment]
duplicate of https://github.com/dalaranwow/dalaran-wow/issues/1815
