### ISSUE TITLE
Hearthstone (Using on moving objects)

### ISSUE THREAD

**Issue by Crispybuilt** [dalaranwow/dalaran-wow#185]
If you use Hearthstone on any flying objects, moveable objects such as a Boat in Booty Bay, Stormwind Harbor, Zeppelin outside the Orgrimmar and simillar, it will finish the cast but it won't port you anywhere. You got 30 minutes cd on eitherway.

**Comment by Rushor** [comment]
http://i.imgur.com/RzbA0nZ.jpg
http://i.imgur.com/h6StwHf.jpg
http://i.imgur.com/ttuOzOy.jpg

fixed in 2014
