### ISSUE TITLE
[Quest][Classic] Thunderfury, Blessed Blade of the Windseeker

### ISSUE THREAD

**Issue by Ellriond** [dalaranwow/dalaran-wow#1850]
Hello!
There is an issue with Thunderfury questline, when you get 1st binding and start the quest, you collect all other items needed wich are 2nd binding, 10 elementium bars and essence of firelord, and when you return it to quest giver he will spawn a boss for you (Prince Thunderaan) wich when you kill he drops and item wich start the quest so you get thunderfury. Issue appears when you kill the boss, he doesnt drop the item he is suposed to, the item has 100% chance of drop but he doesnt drop it. Its unknown what causes the problem, If you did it in raid group and it didnt drop its not the problem..you can be in wich ever group, or you can solo it, you can have leadership and be master looter and if he doesnt drop it its not any of those problems. Problem is he just wont drop it. I searched many sites and stuff to figure the problem but nothing helped. You cannot resummon him or re-do the quest. I hope this will help to whoever is doing this quest and this happens to him, you didnt do nothing wrong..you collected all materials needed you killed boss and everything no matter how and with who, he is not dropping it for some reason

**Comment by Rushor** [comment]
he contains the item for 100 % http://wotlk.openwow.com/item=19018 from http://wotlk.openwow.com/npc=14435

```sql
INSERT INTO `creature_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) VALUES (14435, 19018, 0, 100, 0, 1, 0, 1, 1, NULL);
```

works fine on PTR.

**Comment by Rushor** [comment]
gossip options were already fixed with https://github.com/TrinityCore/TrinityCore/blob/a249d86b00eb0854cb925f8bea76ddbb364208df/sql/old/3.3.5a/TDB52_to_TDB53_updates/world/2013_12_20_01_world_conditions.sql so you can resummon him
