### ISSUE TITLE
[Shaman] talent: Tidal Waves

### ISSUE THREAD

**Issue by nt32** [dalaranwow/dalaran-wow#1854]
Shaman restoration talent Tidal Waves (http://wotlk.openwow.com/spell=53390) is not working as intended. It has 2 stacks and that stacks should be consumed after using Lesser Healing Wave or Healing Wave. Currently it works fine with the Healing Wave but Lesser Healing Wave only consume 1 stack weather first or second. It is not consumed and has no effect on second Lesser Healing Wave.

**Comment by Watterx** [comment]
Can confirm. Please fix this already, its a major bug and it works properly on every server...

**Comment by Watterx** [comment]
@Golganeth Can we have an update about this? Its a very important talent for shaman, and it works on every server...

**Comment by Rushor** [comment]
already on PTR:

Fix redundant calculation of spell critical chance, fix spellmods being dropped twice.

Closes #7315
https://github.com/TrinityCore/TrinityCore/commit/b39216eed31f587b1bcef88e69a714214304e896
