### ISSUE TITLE
Server experience rate seems to be lower than retail's rate.

### ISSUE THREAD

**Issue by Cynthetik** [dalaranwow/dalaran-wow#1857]
First off, I'd like to say that I have played retail WoW, and I have played from when Wrath first came out, to the end of Wrath, which was 3.3.5. I did not play on Retail after that patch, and when I was playing, I used a leveling guide to breeze through the leveling stages and get to 80 as efficiently as possible. The leveling guide I have used is Jame's leveling addon, and I have followed this guide to a T from 1 to 80.

I have noticed one thing, and I've used this addon as a test to see if it's actually the blizz rate exp I experienced in retail. And what I've noticed is that the experience from the starting zone to my current level is actually lower than what I've experienced with Blizzard. I have done every quest from one to another and found that I'm actually at a lower level than the mobs that these quests are asking me to fight. Retail, by doing those quests, you should have already been at that level or maybe a level higher than the mobs.

Also, when I followed the leveling addon, it instructed me to pick up the Quest Encroachment which requires level 6 to do. 

http://www.wowhead.com/quest=837/encroachment

Here's a screenshot of my progress when I reached that step in the guide.
http://i.imgur.com/5DdMAmQ.jpg

The way the addon works is that it expects you to be at that level at that moment, and at some points expects you to fall behind or ahead, which in that case, it would say "By now you should be level X." I have nearly always reached the level the guide wants me to by then anyway. Private servers with 1x, not so much. This is not the only private server that seems to got the blizz rates incorrect.

Not sure if it's a mistake or not, but the experience rate seems to be lower than that of Retail WoW.

**Comment by Khronos-** [comment]
As far as I can remember, it's working as intended as of WotLK expansion.

Not very uncommon for people that played since vanilla to do 2-3 zones to level up. It actually encourage you to explore the world, unlike Cata xpansion onward.
