### ISSUE TITLE
TBC Heroics get saved for long periods of time.

### ISSUE THREAD

**Issue by Extraweltas** [dalaranwow/dalaran-wow#1866]
I now have been locked for Magister's Terrace heroic for 4 days in a row with the same ID and it doesn't reset. Same goes for Sethekk's Halls... Can you please do something about it. Thank you very much.

**Comment by Rushor** [comment]
cannot reproduce this anymore on ptr.

**Comment by maegrim** [comment]
Mana-Tombs Heroic lock has been extending by itself with 19 hours every day this week, with the mobs up to and in the first room respawning, including the first boss; the rest of the instance remains empty.

**Comment by Rushor** [comment]
it works fine on ptr
