### ISSUE TITLE
Rise, Obsidion!

### ISSUE THREAD

**Issue by Kalyino** [dalaranwow/dalaran-wow#1888]
First I will start off by saying the way to get to this quest chain is bugged (Issue#74 Quest: Suntra Stones). You can not escort the first dwarf which is mentioned in another bugtracker issue.

I got all the way to this quest though and when you touch the alter to summon Lathoric he comes out and attacks you, you can kill him and loot his head, he does not however activate Obsidion or trigger him to be killed. Instead he is laying on the ground and when you go to attack him it just says that target is not attackable. Because of this it can not be completed.

There was another issue about this issue#71 which was closed as it was claimed to be scripted and working now, just making a new one to say it is not working it is still broken.

**Comment by TeridanDW** [comment]
This quest is completeable but should be improved a bit as it can get stucked if the player leaves visual range, issues that can be looked at:
 - object http://wotlk.openwow.com/object=148498 is missing a condition, the gossip menu:
![image](https://cloud.githubusercontent.com/assets/6797611/24697226/0aa25af6-19f5-11e7-9ff5-acd8b7c6d24c.png)
should only be avaliable to player with quest take (http://wotlk.openwow.com/quest=3566), however currently it's avaliable to everyone
 - the event for quest http://wotlk.openwow.com/quest=3566 should NOT start on quest taken, but when the player clicks on the gossip menu on the stone
 - object http://wotlk.openwow.com/object=148498 should lose flag has gossip on event start so a player (or 2) can't start the event more than once
 - creature http://wotlk.openwow.com/npc=8400 should be "force" respawned on event start (if he is dead)
 - creature http://wotlk.openwow.com/npc=8421 spawned 2 times during the event (once at the start > when combat starts he despawn > when combat ends he spawn again > after few secs despawn again)
 - npc http://www.wowhead.com/npc=8391/lathoric-the-black#abilities is missing his only combat spell:
http://www.wowhead.com/spell=9613/shadow-bolt with flag 64
 - npc http://wotlk.openwow.com/npc=8400 is casting his combat spell under wrong event (it's set to range, but should be under update_ic)
