### ISSUE TITLE
[Mechanic] Combat: Ending combat problem

### ISSUE THREAD

**Issue by aracnaphobia** [dalaranwow/dalaran-wow#1906]
There is a lingering combat state after combat has ended. It may stem from 1 of 2 things. 
When I aggro an enemy and do not attack or kill it, I will remain in combat after the enemy has been reset.
When I kill an enemy, the combat state doesn't recognize that the enemy has been killed and the state of combat never ends.
This results in health that does not regenerate and is dangerous when you have no food or bandages in your inventory. 
It also makes it impossible to logout without force closing the game

**Comment by Rushor** [comment]
Already fixed on PTR.

https://github.com/TrinityCore/TrinityCore/pull/15538
https://github.com/TrinityCore/TrinityCore/commit/a40d855337bd29f55d898fb5213af92abd5b43a1
