### ISSUE TITLE
NPC: Mo'arg Engineer

### ISSUE THREAD

**Issue by n-ghost** [dalaranwow/dalaran-wow#1911]
http://www.wowhead.com/npc=16945

This mob should have and use 3 following abilities:
- Thorium drill: inflicts weapon damage + N scaled to level, similar to Heroic Strike. http://www.wowhead.com/spell=32005
- Puncture: bleed scaled to level every 2 seconds for 10 sec.
  http://www.wowhead.com/spell=15976
- Magnetic Pull: pulls target towards caster, similar to Death Grip.
  http://www.wowhead.com/spell=31705

Currently Mo'arg Engineers just melee instead.

**Comment by Rushor** [comment]
DB/Creature: Implement Murkblood Putrifier SAI

* closes https://github.com/dalaranwow/dalaran-wow/issues/1911
* commit: 11be7793b90e55d5ee2972e3b361a13b8158b9d8
