### ISSUE TITLE
NPC: Mo'arg Master Planner

### ISSUE THREAD

**Issue by n-ghost** [dalaranwow/dalaran-wow#1912]
http://www.wowhead.com/npc=18567

This guy should have and use one ability: 
- Magnetic Pull: pulls target towards caster, similarly to Death Grip. 
  http://www.wowhead.com/spell=31705

Currently Mo'arg Master Planners just melee instead.

**Comment by Rushor** [comment]
DB/Creature: Implement Mo'arg Master Planner SAI

* closes https://github.com/dalaranwow/dalaran-wow/issues/1912
* added ability Magnetic Pull, Puncture and Thorium Drill
* commit: 36403f015da176b48ba9aa13f9e13e22e5a095c5
