### ISSUE TITLE
NPC: Sal'Salabim.

### ISSUE THREAD

**Issue by n-ghost** [dalaranwow/dalaran-wow#1914]
http://www.wowhead.com/npc=18584

This guy should have and use 1 following ability:
- Magnetic Pull: similar to Death Grip, same as these forgefiends: https://github.com/dalaranwow/dalaran-wow/issues/1912

http://www.wowhead.com/spell=31705

Currently Sal'Salabim just melees instead.

**Comment by Rushor** [comment]
```c++
void UpdateAI(uint32 diff) override
        {
            if (!UpdateVictim())
                return;

            if (MagneticPull_Timer <= diff)
            {
                DoCastVictim(SPELL_MAGNETIC_PULL);
                MagneticPull_Timer = 15000;
            } else MagneticPull_Timer -= diff;

            DoMeleeAttackIfReady();
        }
```

he uses this ability every 15 seconds.
