### ISSUE TITLE
Quest:  Rescue From Jaedenar

### ISSUE THREAD

**Issue by Golganeth** [dalaranwow/dalaran-wow#192]
Quest: http://wotlk.openwow.com/quest=5203

Issue: Upon picking up the quest to start the escort, the NPC doesn't move and the quest gets auto-completed.

NPCs:
Arko'narin - http://wotlk.openwow.com/npc=11018
Captured Arko'narin  - http://wotlk.openwow.com/npc=11016

**Comment by n-ghost** [comment]
Currently the quest is on auto-complete, but not scripted.

**Comment by beregas** [comment]
As 2016, confirmed. Quest auto completes

**Comment by Rushor** [comment]
e293354262571b1f1a40d3a3c1cb0fce75b0ec8e
- implemented the whole escortevent

**Comment by Golganeth** [comment]
Works so much better, needs some cosmetic details and corrections.
- I think Captured Arko'narin should turn into Arko'narin once the escort starts.

- The speed of the NPC and the whole escort process could be increased a little bit.

- >[18:10:32]Captured Arko'narin says: The corruption of the fel has not left any of the creatures of Felwood untouched. Please, be on your guard.
[18:10:36]Captured Arko'narin says: The corruption of the fel has not left any of the creatures of Felwood untouched. Please, be on your guard.
[18:10:49]Captured Arko'narin says: This creature suffers from the effect of the fel... We must end its misery.
[18:12:36]Captured Arko'narin says: The corruption of the fel has not left any of the creatures of Felwood untouched. Please, be on your guard.
[18:12:42]Captured Arko'narin says: The corruption of the fel has not left any of the creatures of Felwood untouched. Please, be on your guard.
**Says that quote a lot of times**

- > [18:13:21]Captured Arko'narin says: I sense the taint of corruption upon this. Help me detroy it.
**destroy it*** typo

- > [18:18:16]Captured Arko'narin says: I can sens it now. Ashenvale lies down this path.
**sense*** typo

- > [18:18:37]Captured Arko'narin says: My form has now changed! The true strength of my spirit is returing to me now... The cursed grasp of the forest is leaving me.
**returning*** typo

**Comment by Rushor** [comment]
bfc1db8063cc6f8094c148499a86b254bd98a046
- not shure about the morph and speed part
- i fixed the typos for now

**Comment by Golganeth** [comment]
Typos are fixed, but the escort itself needs a few polishments. Nothing that requires high priority.
