### ISSUE TITLE
[Quest] Shadowmoon Valley (Netherwing Ledge) - Quest: The Booterang: A Cure For The Common Worthless Peon

### ISSUE THREAD

**Issue by Prljoman** [dalaranwow/dalaran-wow#1922]
It is a daily quest given when friendly with Netherwing after doing "Overseeing and You: Making the Right Choices". When using quest item Booterang on Disobedient Dragonmaw Peon, it can be thrown but credit is not given, therefore quest cannot be completed.

Quest: http://www.wowwiki.com/Quest:The_Booterang:_A_Cure_For_The_Common_Worthless_Peon
Quest: http://www.wowhead.com/quest=11055
Disobedient Dragonmaw Peon: http://www.wowhead.com/npc=23311

**Comment by Rushor** [comment]
this is fixed on PTR.

https://github.com/TrinityCore/TrinityCore/commit/3a4ba127d17373f521c79eac2a1bcaaebe44d9a3

**Comment by TeridanDW** [comment]
Quest is completeable but its made in a really poor way.
Issues that i found:
 - when player hits npc http://wotlk.openwow.com/npc=23311 with spell http://wotlk.openwow.com/spell=40742 it starts the mini event however in the event is interrupted by aggro the creature will reset at it's home location and player can start the event again - heavyly abuseable
 - npc http://wotlk.openwow.com/npc=23311 does not lose emote state work (or mine not sure which one it is used)
 - event should have some cd and not be interrupteable by aggro (creature should continue from where the event was interrupted on reset)
 - on spell hit http://wotlk.openwow.com/spell=40742 npc http://wotlk.openwow.com/npc=23311 moves towards npc http://wotlk.openwow.com/npc=23308 and immediately returns to it's home location (it should stay and work for X seconds before it returns)
