### ISSUE TITLE
Quest: There Is No Hope

### ISSUE THREAD

**Issue by n-ghost** [dalaranwow/dalaran-wow#1924]
http://www.wowhead.com/quest=10172

Same issue as with https://github.com/dalaranwow/dalaran-wow/issues/1902 (and with same NPC, as well): instead of saying correct lines in response to player clicking gossips, NPC always says "Hello, young %race%."

Correct dialogue, quoted from wowwiki:

```
What did Garrosh tell you, <name>? 
```

Gossip: Garrosh is beyond redemption, Greatmother. I fear that in helping the Mag'har, I have convinced Garrosh that he is unfit to lead.

```
<Greatmother Geyah nods, accepting your answer.> 

I can no longer fight the spirits, <name>. My time has long since passed. Once again, I must thank you for all that you have done. While Garrosh may be unmoveable, many of my people have been lifted by your accomplishments. They are now willing to fight for our rights as a unified clan. 
```

Gossip: I have done all that I could, Greatmother. I thank you for your kind words.

```
<Greatmother Geyah smiles at you.> 

You remind me of my son, <name>. 

He was an immovable mountain. A pillar of strength and honor. 

<Geyah's eyes well up with tears.> 

He sacrificed himself so that we could survive. So that generations of orcs after him could be born into a world without the blood curse... Without Gul'dan and his Dark Horde... 

<Geyah stares into the distance, lost in thought.> 

Oh Durotan, how I wish you could be here. Your people so desperately need you... 
```

Gossip: Greatmother, you are the mother of Durotan?

```
<Greatmother Geyah nods.> 

Did you know my son? 
```

Gossip: Greatmother, I never had the honor. Durotan died long before my time, but his heroics are known to all on my world. The orcs of Azeroth reside in a place known as Durotar, named after your son. And... (You take a moment to breathe and think through what you are about to tell the Greatmother.)

```
<Greatmother Geyah's violet eyes lock onto yours.> 

Yes... 
```

Gossip: It is my Warchief, Greatmother. The leader of my people from my world. He... He is the son of Durotan. He is your grandchild.

```
<Tears stream down Greatmother Geyah's face.> 

I... I... Durotan survived to have a child? The child Draka told me of before they left... It was their greatest fear... To raise a child in this world. On the other side of that gate was their only hope. I dared not tell Durotan, but secretly, I begged the spirits to watch over them- to protect their child and to give them strength. 

I... I must see my grandchild. I must see him. Please, I am too weak. You must tell him. Before I leave this world... 
```

Gossip: I will return to Azeroth at once, Greatmother.

**Comment by Rushor** [comment]
http://i.imgur.com/ERQZWf3.jpg http://i.imgur.com/xwZdZzb.jpg

already fixed
