### ISSUE TITLE
NPC speech: Melizza Brimbuzzle

### ISSUE THREAD

**Issue by Zindai** [dalaranwow/dalaran-wow#1934]
NPC: <b>Melizza Brimbuzzle</b> - <a href="http://www.wowhead.com/npc=12277/melizza-brimbuzzle">Wowhead</a>
Quest: <b>Get Me Out of Here!</b> - <a href="http://www.wowhead.com/quest=6132">Wowhead</a> / <a href="http://www.wowwiki.com/Quest:Get_Me_Out_of_Here!">WoWWiki</a>

<b>The quest</b> (working as intended):
You free Melizza Brimbuzzle from her centaur cage and escort her to her brother, Hornizz Brimbuzzle. When you both reach his camp, Melizza Brimbuzzle runs off again after saying something in chat.

<b>What she currently says</b> (including the hard line breaks):
<code>Melizza Brimbuzzle says: We</code>
<code>e going to have to scratch the Maraudines off our list. Too hard to work with...</code>
<code>Melizza Brimbuzzle says: Well, Im off to the Gelkis. They</code>
<code>e not as dump as the Maraudines, but they</code>
<code>e more reasonable.</code>

<b>What she should say</b>:
<code>Melizza Brimbuzzle says: We're going to have to scratch the Maraudines off our list. Too hard to work with...</code>
<code>Melizza Brimbuzzle says: Well, I'm off to the Gelkis. They're not as dumb as the Maraudines, but they're more reasonable.</code>

<b>Other</b>:
I'm not aware if her initial line "<i>Hey Hornizz! I'm back! And there are some people behind me who helped me out of a jam.</i>" is flawed too, as I was out of her speech range at the time.

**Comment by Rushor** [comment]
```sql
(12277, 0, 0, 'Thanks $n.  Now let\'s get out of here!', 12, 0, 100, 0, 0, 0, 7540, 0, 'Melizza Brimbuzzle');
(12277, 1, 0, 'We made it!  Thanks again!  I\'m going to run ahead!', 12, 0, 100, 0, 0, 0, 7544, 0, 'Melizza Brimbuzzle');
(12277, 2, 0, 'Hey Hornizz!  I\'m back!  And there are some people behind me who helped me out of a jam.', 12, 0, 100, 0, 0, 0, 7550, 0, 'Melizza Brimbuzzle');
(12277, 3, 0, 'We\'re going to have to scratch the Maraudines off our list.  Too hard to work with...', 12, 0, 100, 0, 0, 0, 7551, 0, 'Melizza Brimbuzzle');
(12277, 4, 0, 'Well, I\'m off to the Gelkis.  They\'re not as dumb as the Maraudines, but they\'re more reasonable.', 12, 0, 100, 0, 0, 0, 7552, 0, 'Melizza Brimbuzzle');
```

already fixed
