### ISSUE TITLE
Summon Friend not working under certain circumstances

### ISSUE THREAD

**Issue by Fleischi** [dalaranwow/dalaran-wow#1935]
#1. Once the summon did not show up in the friend page at all. We were in a group, one in Tanaris, one in Hinterlands. We were logged out for at least an hour before that so we could not possibly have had cooldown on it. If there are more conditions attached to this spell, then it would be cool if they went into the refer a friend FAQ.
2. We were in a group. I started the summon my friend. One time with an NPC in target and one time with nothing in target. Nothing happened, no summon, no cooldown.
3. Immediately after those failed summons I started another one with the friend in target. I got the cooldown but the friend did not get the summon. IIRC the friend was on a flight in one case and on zeppelin in the other case. This might just be a result of the failed attempts right before it though.

PS: This is kind of hard/frustrating to debug as user so somebody with the ability to reset cooldowns might have better chances to get at it.

**Comment by Rushor** [comment]
maybe adding the flag: can target not in los will help here?

**Comment by robinsch** [comment]
On PTR.

Commit:

**Comment by Rushor** [comment]
Core/RAF: Use FriendStatus as a flag

* commit: 8a0947d395a5cb0ea12575ac5566c43e2b0ac9e9
Ref: https://github.com/TrinityCore/TrinityCore/pull/19317

* by @robinsch
