### ISSUE TITLE
Enchant Weapon : Black Magic / Visual Issue

### ISSUE THREAD

**Issue by asbraich** [dalaranwow/dalaran-wow#1940]
The black magic enchant is not showing on all one-handed weapons.  I believe it shows correctly if the weapon is labeled as "Main Hand" but "One-Hand" and perhaps "Offhand" weapons do not show the twirling skulls animation.  

Picture: http://i.imgur.com/tXUILJ2.jpg

**Comment by Rushor** [comment]
works fine on PTR.

![GitHub Logo](http://i.imgur.com/fyI5TxS.jpg)

**Comment by asbraich** [comment]
Uh, that's a mainhand weapon.  I already acknowledged it was working on Mainhands.

Does it work on Off-Hand and One-Hand weapons on the PTR?
