### ISSUE TITLE
S6 gear

### ISSUE THREAD

**Issue by pascagabriel** [dalaranwow/dalaran-wow#1941]
The rating requirement on the Furious cloak is wrong, it should be 1.9k (http://wow.joystiq.com/2009/02/06/arena-season-6-rise-of-the-furious-gladiator/) (http://wow.zuggaming.com/2009/02/06/season-6-arena-gear-and-rating-requirements/). Also you forgot to add the new resilience PvP trinket and also removed the old one, which makes newcomers unable to get a trinket except form WG. Also forgot to update WG vendor.

**Comment by Golganeth** [comment]
#2398
