### ISSUE TITLE
Gathering: Failed attempt

### ISSUE THREAD

**Issue by Zindai** [dalaranwow/dalaran-wow#1943]
<a href="https://www.youtube.com/watch?v=aoYTaTa7xMs">Video proof</a> (22 sec) recorded on the realm Algalon.
The video shows 3 herb gathering attempts interrupted on purpose, followed by 2 <b>Failed attempts</b> and then a succesful gathering.

<b>The issue</b>:
Gatherings attempts can fail.
Gathering attempts shouldn't be able to fail as of <a href="http://www.wowwiki.com/Patch_3.1.0#Gathering_Skills">patch 3.1.0.</a>
"<i>You can no longer fail when Mining, Herbing, and Skinning.</i>"

<b>Other</b>:
This may affect Mining and Skinning as well.
Update: Mining and Skinning confirmed.

**Comment by Rushor** [comment]
1f2d9b4c625a7c46a33f827149201d0a2a61e896
- gathering will no longer fail
