### ISSUE TITLE
Gnome Engineering

### ISSUE THREAD

**Issue by n-ghost** [dalaranwow/dalaran-wow#1953]
http://www.wowwiki.com/Gnome_Engineering

To become a proud engineer of gnomish wonderworks player must:
- get a 200 skill in Engineering;
- complete the quest: http://www.wowwiki.com/Quest:Gnome_Engineering ;
- complete the following quest: either http://www.wowwiki.com/Quest:The_Pledge_of_Secrecy_%28Ironforge%29 (for IF trainer, obviously) or http://www.wowwiki.com/Quest:The_Pledge_of_Secrecy_%28Stranglethorn_Vale%29 (for STV trainer);
- complete http://www.wowwiki.com/Quest:Show_Your_Work_%28Gnome%29 afterwards and get a specialization as a reward;

Only after that player should get the access to all the schematics that his specialization offers.

Currently any alliance player can get Gnome Engineering recipes from Tinkmaster Overspark regardless of any requirements (save for skill level), which severely compromises security of Gnomeregan as whole.

Need to be tested with Horde\Goblin engineering trainers as well.

**Comment by Demlock** [comment]
I can confirm that the Horde side has access to Gnome Schemata regardless of their affiliation.

**Comment by n-ghost** [comment]
Apparently same thing going on with Armorsmithing/Weaponsmithing.

**Comment by Rushor** [comment]
moved to https://github.com/dalaranwow/dalaran-wow/issues/1483
