### ISSUE TITLE
Pets falling through world

### ISSUE THREAD

**Issue by Jaxtal** [dalaranwow/dalaran-wow#1955]
I am noticing on both my locks and my hunters that when above a cavern and attacking a mob, my pet will fall through to the cavern.  For example, when fighting above the tunnels to deadmines, to get the pathstalkers bandits and such, my pet will charge at a guy i say above world, but will fall through to the defias caverns.  Hope this helps in fixing this issue.  Thanks!

**Comment by n-ghost** [comment]
Really really good place to test this thing out is Scholomance.

Managing the pet there is harder than doing the instance per se.

**Comment by Golganeth** [comment]
#3073
