### ISSUE TITLE
Glyph of Charge

### ISSUE THREAD

**Issue by ConradSilverwind** [dalaranwow/dalaran-wow#1967]
How it should work: "Increases maximum range for charge by 5 yards which makes charge usable from 8 to 30 yards."

Problem: Though the tooltips say that the range has been increased, charge can't be used on targets that are further than 25 yards.

**Comment by ConradSilverwind** [comment]
Tested on Algalon today and it works. Good job :)

**Comment by Vaxsysl** [comment]
This glyph got bugged again. Tooltip updates, spell is not red (target is in range of the spell, but we're still out of range.
Proof: http://i.imgur.com/6rWIRfD.jpg (note: Image will get deleted in one month's time)

**Comment by Rushor** [comment]
has something todo with bugged rayvast

bugged

**Comment by Crispybuilt** [comment]
Can confirm that glyph bugged out again, this can re-opened.

**Comment by Aalhazred** [comment]
it's still bugged
