### ISSUE TITLE
Spell Reflection Bugs

### ISSUE THREAD

**Issue by ConradSilverwind** [dalaranwow/dalaran-wow#1968]
Spell reflection doesn't work on the following spells:

- [x] Priest's Penance
- [x] Death Knight's Death Grip
- [x] If there are more spells casted on the warrior at same time, Spell Reflection will only reflects one spell

How it should work:
-Penance should cause damage to the Priest
-Death Knight should be death-gripped to the warrior
-Spell Reflection should reflect all spells casted on warrior at the moment the spell reflection buff is consumed ( spells must be casted within the global cooldown of the first spell to get multi-reflected ).

**Comment by ConradSilverwind** [comment]
Removed Holy Shock from the list as it turned out it works properly.

**Comment by ConradSilverwind** [comment]
Spell Reflection sometimes works on Death Grip, but chances are low.  Most of the time it just consumes death grip.

**Comment by robinsch** [comment]
@ConradSilverwind: Please post a proof for DK Death Grip (Video from retail)

**Comment by Goatform** [comment]
I have some hack fix for Death Grip but I don't know how to fix Penance to have blizzlike visual instead of casting spell from target (with Spell Reflection).

**Comment by robinsch** [comment]
Issue 1 & 3 on PTR.

**Comment by robinsch** [comment]
2 on PTR.
