### ISSUE TITLE
Librams Vanilla

### ISSUE THREAD

**Issue by altid** [dalaranwow/dalaran-wow#1972]
Hej Dala-WoW i have an issue regarding completing "Libram of Voracity Quest" most of the things work. but the last part of item "Whipper Root Tuber" cant get completed in the right way in Felwood. it just says quest complete. and i dont get the "Whipper Root Tuber" witch is normaly rewarded.

i have done the quest chain and used the Cenarion Plant salve to complete. and it just says Quest complete, and i get nothing!

Just cheked all the Herb Quests in Felwood aint working. just a quest complete yellow tekst

Quest: http://www.wowwiki.com/Libram_of_Voracity
Item: http://www.wowwiki.com/Whipper_Root_Tuber
http://www.wowwiki.com/Cleansed_Whipper_Root
Cords for the plants: http://www.wowwiki.com/Corrupted_Whipper_Root
Plant salve needed to complete herb quests: http://www.wowwiki.com/Cenarion_Plant_Salve

Sure hope you can fix this and that this is enuf info for you. thanks in advance!

**Comment by Demlock** [comment]
That is indeed correct. My experience with this quest is that you should wait for a few moments before the corrupted plant despawns and the "cleansed" plant appears in its place to get either the item or the buff. However, on DalaranWow this is not the case, as you only get credit on the quest and nothing else.

**Comment by Rushor** [comment]
the script for the plants and the spawn of the cleansed version of the flower was fixed in https://github.com/dalaranwow/dalaran-wow/issues/1841
