### ISSUE TITLE
Quest: Light Won't Grant Me Vengeance

### ISSUE THREAD

**Issue by TilmanK** [dalaranwow/dalaran-wow#1975]
Quest: http://www.wowhead.com/quest=12904

Issue: Gerk (http://www.wowhead.com/npc=29455) is at the correct position in Zul'Drak but does not give you the quest.

Expected: Gerk gives you the quest. See video: https://www.youtube.com/watch?v=fmAry8_lB2w

**Comment by Lothloryen** [comment]
Corrected.
