### ISSUE TITLE
Quest: Fhwoor Smash! [9729]

### ISSUE THREAD

**Issue by Golganeth** [dalaranwow/dalaran-wow#1976]
**Issue:** You can't start the escort after taking the quest from [Fhwoor](http://wotlk.openwow.com/npc=17877).

**How it should work:** [Quoting Wowhead](http://www.wowhead.com/quest=9729/fhwoor-smash#comments:id=278409)

> *Fhwoor slowly stomps around the naga camps; he makes a mostly semicircular path through the camp, grabbing the ark on the way. Of course, he has a tendency, like most escorted NPCs, to pull basically everything in the area, so I strongly suggest pulling things ahead of time. The naga are easy to kill and whole groups of them should not be a problem at all, though. Be sure to keep Fwhoor relatively unharmed (if you play a class which can heal, you can cast healing spells on him), because if he dies, the quest is, unsurprisingly, over.*
*Once Fhwoor clears the naga camps, there is a brief delay before an elite naga along with two guards (a melee fighter and a caster) shows up. They all charge Fwhoor, so try to pull the elite and another off of him. I recommend killing the enchantress (the caster) first, as she dies very quickly, and then finishing off the melee naga (or just keeping him crowd-controlled throughout the fight---Fwhoor can take him out on his own, too). Then, simply focus on the elite naga, who will die very swiftly when under attack by a 70th-level character.
If you are lower level than 70, you may need to bring friends for this quest. However, if you are 70th-level and decently-geared, you should not have a big problem with protecting Fwhoor and killing the elite naga at the end.*

http://wotlk.openwow.com/quest=9729
http://wotlk.openwow.com/npc=17877

**Comment by jonanone** [comment]
Fhwoor now starts the escort mission. It summons Ssslith and two adds once going back to Sporeggar. The fix will be applied to the live realm soon.

**Comment by Golganeth** [comment]
Only missing the quote  "Ha ha, squishy naga!"  once the two adds and Ssslith die.
