### ISSUE TITLE
Pet resilience

### ISSUE THREAD

**Issue by akokic** [dalaranwow/dalaran-wow#1979]
Pet's are melting like ice. boom boom down,if they focuse my pet on 2 sec he is dead,you cant heal him (everyone knows that pet healing is slow and can't help in that situations). I thik resilience scaling on them is not right. If someone can check that out.

**Comment by Rushor** [comment]
should work fine already on PTR.

```c++
float Unit::GetCombatRatingReduction(CombatRating cr) const
{
    if (Player const* player = ToPlayer())
        return player->GetRatingBonusValue(cr);
    // Player's pet get resilience from owner
    else if (IsPet() && GetOwner())
        if (Player* owner = GetOwner()->ToPlayer())
            return owner->GetRatingBonusValue(cr);

    return 0.0f;
}
```
