### ISSUE TITLE
Item Issue : Elemental Focus Stone - Ulduar 10

### ISSUE THREAD

**Issue by asbraich** [dalaranwow/dalaran-wow#1981]
The item Elemental Focus Stone, dropped by Auriaya in Ulduar 10 man (Item ID 45866) is not proccing from rogue poisons as it should be.

Evidence that is should be proccing can be found in the comments here: http://www.wowhead.com/item=45866#comments

"YES! I just want to confirm that YES THIS PROCS FROM POISONS on a rogue! I got this on a rogue in ulduar tonight because no one else needed it. I was going to use it to itimize hit a little better.. replace a few hit gems with ArP ones. Anyway, to my surprise, it's procing from my poisons, and rather frequently too! The proc from this was up about 75% of the duration of the Freya encounter. And haste isn't that bad for rogues, i have 5.28% haste from gear already, without gemming or enchanting for it, 10% from lighting reflexes, and the proc from this trinket brings it up to 31.20% haste"

Further evidence is that the weapon enchant, "Black Magic" also procs off poisons which are considered harmful spells.

**Comment by asbraich** [comment]
any update on this?

**Comment by Golganeth** [comment]
#2130
