### ISSUE TITLE
Hallow's End - Wickerman Guardian Ember not spawning after Wickerman Guardian is killed

### ISSUE THREAD

**Issue by bab4m** [dalaranwow/dalaran-wow#1982]
The Wickerman Guardian's (http://wotlk.openwow.com/npc=15195) are not spawning a Ember (http://wotlk.openwow.com/object=180574) after they are killed. Normally players are able to right click this object and have a Buff (http://wotlk.openwow.com/spell=24705) Cast on them that grants +10% XP and +10% rep gains.

See: http://www.wowhead.com/object=180574#comments

This is an Alliance Human, I tried to interact with them without the quest to scout the wicker festival and with the quest and they did not spawn in either case. The quest should not affect them however.

Further update: Horde Characters are able to click on the other object that grants this buff Wickerman Ember (http://wotlk.openwow.com/object=180437 / http://www.wowhead.com/object=180437#comments) and "Smear it on their face like war paint" to receive the buff. At this point it is also an issue of faction imbalance.

**Comment by Lothloryen** [comment]
Hello there, 

This year the Alliance and the Horde will be able to benefit from the Invocation of the Wickerman buff.

Thank you.
