### ISSUE TITLE
Mage Talents, Firestarter + Arcane Concentration

### ISSUE THREAD

**Issue by Vaxsysl** [dalaranwow/dalaran-wow#1985]
This might not be a bug, I haven't found any concrete information anywhere online.

Mage Talent Firestarter: Your damaging Blast Wave and Dragon's Breath spells have a 50% chance to make your next Flamestrike spell instant cast and cost no mana. Lasts 10 sec.
http://wotlk.openwow.com/spell=54741

Mage Talent Arcane Concentration (5/5) : Gives you a 10% chance of entering a Clearcasting state after any damage spell hits a target. The Clearcasting state reduces the mana cost of your next damage spell by 100%.
http://wotlk.openwow.com/spell=18189 (link might be wrong!)

Spell Flamestrike: http://wotlk.openwow.com/spell=42926
What's wrong with these two talents? When using Flamestrike with Firestarter and Clearcasting buffs up, its instant, consumes no mana, but Clearcasting is also consumed. I am not sure if that is right or wrong.

**Comment by Rushor** [comment]
http://wowwiki.wikia.com/wiki/Firestarter_(talent)

Hm a similar effect where Clearcasting is not consumed is http://wowwiki.wikia.com/wiki/Arcane_Missiles:
> "Patch 3.2.2: [Arcane Missiles]: Casting this spell while both Missile Barrage and Clearcasting are active will cause only Missile Barrage to be consumed."

However for http://wowwiki.wikia.com/wiki/Firestarter_(talent) that text is not mentined in the changelog. I will close the issue for now and set it "on hold", until a proof for it was found. Then we will reopen the issue. Thanks.
