### ISSUE TITLE
Hallows end: Unable to interact with Candy Buckets

### ISSUE THREAD

**Issue by charasalgalon** [dalaranwow/dalaran-wow#1987]
I am currently not able to get any quests from the Candy Buckets around Azeroth, interacting with a Candy Bucket should give the following item: http://wotlk.openwow.com/item=37586
Note that this works for near everyone, but i suspect it is not working for me since i also did this event last year(on Kirin Tor).
According to this post http://us.battle.net/wow/en/forum/topic/3418982294 the candy buckets should reset every year (see second post).

**Comment by Lothloryen** [comment]
Hello there, 

This year everyone would be able to interact again with the Candy Buckets, if you are experiencing issues please let us know.

Thank you.
