### ISSUE TITLE
Pet health after dismounting

### ISSUE THREAD

**Issue by Johanes022** [dalaranwow/dalaran-wow#1992]
After dismounting ghoul pet spawns with extremly low HP (~150hp), sometimes he even spawns as dead and his health start regenerating afterawards.This is happening (at least to me) since hallows end event started, and it happends randomly , sometimes pet spawns with full hp, sometimes bearly alive wich makes him easy to kill in pvp.I have tried reseting my talents , deleting Chache folder but nothing helped.

**Comment by AraelWindwings** [comment]
Happens very often during BG too.

**Comment by JinKhanzo** [comment]
happens with every mount its not a mount problem

**Comment by bmbvenom** [comment]
This is still happening for me. Any update on this? Very frustrating when questing because I have to wait to mend pet every single time I dismount.

**Comment by Johanes022** [comment]
DK pet is now useless in pvp, dies pretty much right away after dismounting.

**Comment by robinsch** [comment]
Already fixed on PTR. Should be on Live tomorrow.

**Comment by bmbvenom** [comment]
This is still not resolved.

**Comment by bmbvenom** [comment]
This is still not resolved. Can you please open this again and leave it open until fixed?

**Comment by kalvindeane** [comment]
The changes just haven't been applied to live yet.

**Comment by bmbvenom** [comment]
4 days ago they said it would be live tomorrow, which means 3 days ago. Fix should be applied already.

**Comment by kalvindeane** [comment]
Been some delays. It's definitely working on the PTR.

**Comment by bmbvenom** [comment]
Ok great. I'm not trying to be pushy or anything, I'm just not on PTR so I didn't know. Thanks to all who worked on this!

**Comment by Edzero** [comment]
I believe this is incorrectly labelled as it seems to work fine on both the live realm and the PTR but another related issue still exists on both live and PTR.

There is an issue where pets have low hp when summoned but it is not related to mounting or dismounting. It seems they are given the default hp that they would have without any bonuses taken into account. Such as the stamina from the DK himself, glyphs and talents.

For example the Ghoul from an Unholy DK's Raise Dead spell will spawn with 5.3k hp. Mounting / dismounting will not affect it. If the pet is healed to full hp (or any other value) and then the player mounts and dismounts, the pet will retain the amount of hp it had before the mounting.

**Comment by Rushor** [comment]
it was moved to fixed on "15. Sept. um 03:31 Uhr" /label changed
