### ISSUE TITLE
Ores overspawn, blue items from normal mobs drop rate bug(maybe), please read

### ISSUE THREAD

**Issue by Aalhazred** [dalaranwow/dalaran-wow#1995]
Hello, what actually happens, is that some ores (mainly tin and copper and gold, sometimes iron or so) are overspawning in some areas, like in jangolode mine in westfall, there are like 10-16 veins inside the mine usually, yet after mine one, it takes like 5 minutes or lest for it to re spawn, same with gold at stonetalon mountains, making pretty easy to gather minerals, lowing (from my perspective) the ores value, also, as i said in a forum thread i made some days ago, the drop rates of the gems obtained from minerales, are, maybe, somehow too high, since i'm lvl 37, and from only mining i have nearly 30-40 precious stones (malaquite, tiger eye, jade, etc), maybe i'm wrong, but i had played in some other blizzlike servers(i'll not say any name), and obtain gems through mining, was pretty hard, i mean, malaquite and tiger eye were easy, but jade, aquamarine, moon stone, were pretty hard, also, the spawn from "rare minerals" veins (silver, truesilver, gold), it's high too, i'll just say that while i was gathering iron, i somehow end with 60 gold ores.

p.s: the drop rate of rare(blue) items, from common mobs, i'ts probably bugged too, since i have seen way too many of them while leveling (like 20 items or so), while it was usually pretty rare from a normal mob to drop a blue item, also even sometimes while killing mobs they dropped the same rare blue item twice in the same zone.

The purpose of this is not being annoying, neither criticize the server or so, i'ts purely becouse i really believe the thing that this one is the best scripted wotlk server, so i'm really interested in stay here (maybe donate when i get 80 or so), and i'm just trying to help to found bugs, thanks fore reading  :)

**Comment by Rushor** [comment]
moved to mainissue https://github.com/dalaranwow/dalaran-wow/issues/1208

pooling and spawnpoints must be improved
