### ISSUE TITLE
Enrage and Improved Defensive Stance stacking together

### ISSUE THREAD

**Issue by ConradSilverwind** [dalaranwow/dalaran-wow#1998]
Enrage (fury tree perk) and Improved Defensive Stance (protection tree perk) proc same enrage buff which stacks and gives warriors 20% increased damage.

How should it work: Enrage procs should never stack together, even if they are in different specs.

http://www.wowhead.com/forums&topic=153002/enrage-and-improved-defensive-stance

**Comment by robinsch** [comment]
On PTR
