### ISSUE TITLE
Meteorite Crystal proc bug

### ISSUE THREAD

**Issue by jklsd** [dalaranwow/dalaran-wow#1999]
This trinket had a change after patch 3.2 and the proc "Meteoric Inspiration" isn't working properly because it should be stacking the 75mp5 for 20secs on every cast instead of chance to proc like it is now. Using Beacon of Light doesn't seem to affect the bufff stacking as well.

**Comment by elorix** [comment]
pretty much a useless item atm, you cant even macro it together with a cast, it just says "interrupted" and you dont get the effect of the trinket at all

**Comment by Zephyrino** [comment]
The Meteoritic Inspiration buff only appears to have a ~10% chance to proc or so once the trinket is used (rather than 100%), making the on use aspect of the trinket pretty useless. It's unfortunate considering how powerful this trinket is supposed to be for a holy paladin in this expansion.
