### ISSUE TITLE
 [Npc][Karazhan] Midnight

### ISSUE THREAD

**Issue by Exorcista** [dalaranwow/dalaran-wow#2000]
Hi there, want to report this boss here wich is pretty buggy, for not saying completely insane bugged :S 

<b>::How it works:</b>

<b>\- Midnight (16151)</b> -- http://www.wowhead.com/npc=16151/midnight 

When engaged is all normal, when hes low HP, <b>Attumen the Huntsman (15550)</b> -- http://www.wowhead.com/npc=15550, appears or is it 2 of them? (at a moment where 3 of them but one of them dissapeared), could be beacuse hunter used Feign Death twice, i just dont know.

<b>Screenshots:</b>

--http://i.imgur.com/My9qe6H.jpg
--http://i.imgur.com/ezJvPjj.jpg
--http://i.imgur.com/hxECowT.jpg

Manage to climb there to take them, some mate in raid says it happens all the time and you need a BiS tank and heal to do it since those spawns, or he justs doesnt join Midnight as a mount as it should and just they both stay there hitting you.

<b>::How should it work:</b> closer to this video: https://www.youtube.com/watch?v=nuv4u5e7mdg

I know its just tbc raid, and might be low priority, but this guy is mayor farm resource for the mount, i hope it gets some atention at least.

<b>Edit:</b> We cleared it, just thing was midnight had to die so Huntsman appeared as one riding him, no clones showed up this time.

**Comment by Golganeth** [comment]
#2204 (Confirmed issue) - Excessive damage from boss' [Cleave](http://www.wowhead.com/spell=29832).

**Comment by Rushor** [comment]
todo: 
- no double summons
- cleave dmg

**Comment by Rushor** [comment]
done

**Comment by Golganeth** [comment]
It's pretty much the same or worst, needs improvements.

When Midnight is at 90% Attumen Appears. If you kill Midnight and ignore Attumen the fight will abruptly end, you shouldn't be able to kill Midnight.
When Attumen is around 25% it will mount Midnight. Cleave damage and white hits seem fine.
And now Attumen the Huntsman doesn't seem to drop any loot on PTR.

**Comment by peszmerd** [comment]
I will add my 3 cents about white dmg.

Couple of screenshots from my test run - I have noticed that Attumen is hitting me way too hard, something felt really odd.

[(http://i.imgur.com/a2WSrsQ.png)]

Having 60% dmg reduction from armor and additional:
- 3% from glyphed Divine Plea:
- 3% Blessing of Sanctuary:
- 6% Talented Righteous Fury:
(1-0.6)(1-0.03)(1-0.03)(1-0.06)=0,3538=35.38% dmg taken

From wikia/gamepedia:
[(http://wowwiki.wikia.com/wiki/Attumen_the_Huntsman)]
[http://wow.gamepedia.com/Attumen_the_Huntsman]
Basic Melee: 4,715 - 7,508 damage, mitigated by armor.

Based on my dmg taken (7026 / 6770 / 5969 / 6529) something is definitely not right. 
If wiki data is correct (which sounds about right considering how much hp had tanks during that time), with my mitigation and Attumen's max hit i should be able to receive would be 7508*0,3538=2656dmg - which is clearly not the case.

Those might be crushing blow hits, but this isn't stated in the log, as it should be if they actually have been crushing (as of patch 1.6.0) [http://wow.gamepedia.com/Combat_Log]

**Comment by Rushor** [comment]
fixed with https://github.com/TrinityCore/TrinityCore/commit/4c4d92faa3b9e82fbabffb03eb63761b282f03a2

This fix will be applied after further merges.
