### ISSUE TITLE
[Warrior talent]: Toughness

### ISSUE THREAD

**Issue by ConradSilverwind** [dalaranwow/dalaran-wow#2007]
Toughness is a warrior protection tree talent that gives warriors bonus armor rating from gear and reduces the duration of movement slowing effects.

Problem: Currently it reduces duration of movement slowing effects by 10/20/30/40/50%.

How it should work: Reduces duration of movement slowing effects by 6/12/18/24/30%.

Armor part works.

**Comment by ConradSilverwind** [comment]
Would be great if somebody could check the same thing with death knights and paladins. Thanks.

**Comment by robinsch** [comment]
@ConradSilverwind Tested and working fine. Hamstring gets reduced to 7 (will display 6) seconds.
