### ISSUE TITLE
[Northend] [Quest] The Sum is Greater than the Parts

### ISSUE THREAD

**Issue by Exorcista** [dalaranwow/dalaran-wow#2008]
Quest link: http://www.wowhead.com/quest=13043/the-sum-is-greater-than-the-parts

<b>Description</b>: 
Mount and take control of Nergeld. Defend it from the denizens of the Hall of Horrors until Dr. Terrible shows himself.

Use Nergeld to slay the doctor, and then return to The Bone Witch in Njorndar Village.

<b>How it Works</b>

<b>-Nergeld (30403)</b>: appears to be bug somehow, you can move him arround all the place, use his abilities but the event never start and <b>Dr Terrible (30404)</b> never shows up for the party.

<b>How should it work:</b> close to this video https://www.youtube.com/watch?v=cbsIDef8T4E

Have to add that as seen in wowhead, this quest leads to unlock Valhalas quests, wich are pretty important in the zone. 

Cheers, if anyone has a workarround, dont be shy to post one.

**Comment by marsalandrei** [comment]
Uh how did you get the quest? I did the previous one with beating the info out of that guy in the underhalls, but all I can do at the bone withc now is turn in vykrul bones.

**Comment by DrFuler** [comment]
[07/04/2016] - Seems like it can't be done.

I've killed the apprentice and looted the quest item, but the flesh giant (Nergeld) is right in the beginning of the entrance of the whole place, on the top floor, rather than below, and isn't mountable. Without him, seems to be impossible to complete the quest as it is event based.

**Comment by DrFuler** [comment]
[07/04/2016] - Seems very bugged, but still doable:

- First you have to kill the apprentice, and LOOT the item that starts the quest. Seems a simple task but it is actually a bit bugged, first time I killed it the item dropped but I simply couldn't loot it (bug), and then I killed the apprentice once again and then was able to loot it, and then killed a third time and then could loot the item a second time, while already doing the quest (I think you are not suppose to loot the same quest-starting item twice)

- With that completed, go back to the entrance of the whole place, on the top level (I don't think he should be there). The flesh giant, Nergeld is there, but if you put your mouse over it, it won't display the "mount me" icon. However, he is still mountable and you can ride it down 

- On the lower level, on the corridor that was previously empty, a bunch of monsters should have spawned. However, at first they were all bugged and started floating into the ceiling and I couldn't keep the aggro on any of them. However, I took the giant for a small ride until I noticed that Dr. Terrible was screaming some bullshit, so naturally I came down again to check on it. Dr. Terrible was there and some other mobs as well, both now being normally targetable. Just so you know, my giant got an ass kicking and I had to finish the job by myself (killing the doctor).

And that is how I completed. Hope it helps however is looking for how this can be done.

**Comment by spectralzenith** [comment]
When I had "Deep in the Bowels of The Underhalls" in my quest log, the book dropped the first time but  it wasn't lootable. Then I camped that mob for more than 1 hour and it didn't drop anymore. After I completed "Deep in the Bowels of The Underhalls", I decided to go back and kill Apprentice Osterkilgr again. Then the book dropped and it was lootable this time. I guess you have to complete your previous quest first.

**Comment by Golganeth** [comment]
MalkaviaDW:
> Seems the Punch ability from Nergeld does not inflict damage at all, making the quest nearly impossible to complete. I die on the 3rd wave.

**Comment by Golganeth** [comment]
MalkaviaDW:
> Seems the Punch ability from Nergeld does not inflict damage at all, making the quest nearly impossible to complete. I die on the 3rd wave.

**Comment by jonanone** [comment]
Varguls and Hounds now will attack the giant once summoned.

The Punch ability has a mistake on its description since it can only be used at 1yd range from the creatures, but it works. The quest is now doable, you only have to be closer to the targets in order to use the Punch ability.

The fixes will be applied to the live realm soon.
