### ISSUE TITLE
Quest:  A Sample of Slime...

### ISSUE THREAD

**Issue by Naidira** [dalaranwow/dalaran-wow#201]
The quest in Undercity "A Sample of Slime..." appears to be non-working for the final step.  The orange colored Testing Equipment next to Chemist Fuely does not allow you to purify Felwood Slime Samples, making the quest impossible to complete.  It comes up with a window that simply says "Greetings, [character name]".

In addition, if you accept "A Sample of Slime..." at the same time as its counterpart, "...And a Batch of Ooze" the green Testing Equipment required to purify Un'goro Ooze Samples becomes inaccessable.  "...And a Batch of Ooze" can be completed normally if you drop "A Sample of Slime...".

With "A Sample of Slime..." incompleteable, the quest chain can not be finished.

**Comment by Demlock** [comment]
Indeed, once you complete the ...A Batch of Ooze (which works just fine, btw), the testing equipment (the Red one) won't offer you any quests. These quests are not mutually exclusive to my knowledge so this problem is definitely something to be looked into.

**Comment by Rushor** [comment]
UPDATE `quest_template` SET `NextQuestId`=0, `ExclusiveGroup`=0 WHERE  `Id` IN (4293, 4294);

**Comment by Rushor** [comment]
f4e057e6cb23ae19792fd58c7fc31d5289010c03
- both quests should now be completable
