### ISSUE TITLE
Abilities: Crusader Strike - Dvine Storm not producing seals

### ISSUE THREAD

**Issue by nt32** [dalaranwow/dalaran-wow#2012]
After checking some logs I realized that my seal proc count was lower than my swing count + CS count + DS count. So I have done some testing today on heroic training dummy suing seal of command.

Using only Divine Storm without autoattacking procced seal every time so did my autoattacks. So I decided to use a rotation without CS and I noticed there are still some procs being lost.

Upon furter testing with CS every CS I used in middle of my swing timer produced seals whereas every CS I used right as my swing hit did not produce a second proc.

This is the case with both CS and DS causing dps loss for retri paladin. I would really appreciate it if you could fix this. 

Thank you.

**Comment by Golganeth** [comment]
Can't confirm. Closed until proof is given
