### ISSUE TITLE
Guards in Silvermoon City

### ISSUE THREAD

**Issue by ghostlynx** [dalaranwow/dalaran-wow#2017]
Don't appear to recognize enemy faction characters killing NPCs.  Saw one walk right by a night elf hunter in the process of killing the Worker in the building near the front gate.

**Comment by Demlock** [comment]
I can confirm that. I've fought with numerous enemies, or have been resting and the patrol didn't do anything, even though they've passed right through me.

**Comment by Rushor** [comment]
http://i.imgur.com/5v1PYkB.jpg already fixed
