### ISSUE TITLE
[NPC] Ghaz'an

### ISSUE THREAD

**Issue by Nenki** [dalaranwow/dalaran-wow#2018]
The second boss of The Underbog (The Burning Crusade dungeon located to the right in Coilfang Reservoir) is basically impossible with an appropriately leveled group, as his Cone ability "Acid Spit" which is supposed to be 180 degrees infront of him, hits 360 degrees around him in an absolutely massive radius, melting the entire party in a matter of about 30 seconds.

http://www.wowwiki.com/Ghaz'an

**Comment by belegija** [comment]
confim bump

**Comment by Rushor** [comment]
http://wotlk.openwow.com/spell=34290
http://de.wowhead.com/npc=18105/ghazan#comments:id=385271
Von Activist (142 – 1) am 2008.09.23 (Patch 2.4.3)
Acid Spit hits in all directions not only front, i've tested by standing at max range behind the boss and it was still hitting.

![GitHub Logo (http://i.imgur.com/0XT6jmT.png)


It's not an issue, it's blizzlike behaviour. closing
