### ISSUE TITLE
Minor bug Spirit of kirith / Mayor bug Suntara Stones

### ISSUE THREAD

**Issue by Aalhazred** [dalaranwow/dalaran-wow#2022]
Minor bug NPC over spawn "spirit of kirith" --- (blasted lands)

-What's happening?

After killing "kirith the Damned" (at 68.0, 28.9 according to http://wotlk.openwow.com/npc=7728)
Spirit of kirith spawns correctly, yet, it not dissapear after a time, leading into a "kirith army"

-Proof

http://imgur.com/mi2iX3S

http://imgur.com/AV0sLtP

http://imgur.com/ATAIAWu

-How should it works?

Not completly sure about the dissapear timing, yet after complete the quest (58)Kirith ( http://www.wowwiki.com/Quest:Kirith )
and take (60)The Cover of Darkness ( http://www.wowwiki.com/Quest:The_Cover_of_Darkness ), it should dissapear

P.S: this bug it's purely cosmetic, the spirith of kirith is friendly to Alliance and Horde, not sure if the nearby mobs would kill the
 kirith's army (mobs dead at the moment of the proofs)

Mayor bug "Suntara Stones" quest --- (searing gorge)

-What's happening?

It's not possible to accept the quest (46)Suntara Stones (http://wotlk.openwow.com/quest=3367) from Dorius Stonetender(63.6, 60.8 http://wotlk.openwow.com/npc=8284 ), neither is possible to complete it, even if that's what appear instead of being able to pick up the quest
(more clearly in proofs), and as the first quest is not possible, the quest chain is blocked (can't get to part 2, so it's blocked
the rest of quest of the quest chain).

Also, at the place where the escort event should finish, the note there it's bugged (at 74.5, 19.4 http://www.wowwiki.com/Singed_Letter ), so neither this way it's possible to continue
to the other chain quest

-Proof

  -the npc that starts the quest

  http://imgur.com/6jIRR3k

  http://imgur.com/CRQZPTg

  -the singed letter

  http://imgur.com/N3I6Qp8

  http://imgur.com/HG1QLQK

-How should it works?

After accepting the quest from Dorius Stonetender, the player(s) (don't know if could be a group quest) should defend Dorius until he arrives his patrol end
where he is shooted, and then, the player(s) should be able to "quest interact" with Singed letter, then complete Suntara stones(1) http://www.wowwiki.com/Singed_Letter
and pick up Suntara stones(2) http://www.wowwiki.com/Quest:Suntara_Stones_(2)

hope this can help :)

**Comment by Golganeth** [comment]
First issue seems fixed. Second issue fixed on #74
