### ISSUE TITLE
Unable to change Tailoring specialization

### ISSUE THREAD

**Issue by Bk00l** [dalaranwow/dalaran-wow#2023]
I learned Mooncloth Tailoring Specialization by completing the quest from Nasmara Moonsong in Shatrath. I decided I wanted to switch to another specialization which should be done by going to NPC that granted you the specialization in the first place (in my case - Nasmara Moonsong) and pay a fee to unlearn it. Then you can learn a new Tailoring Specialization from some of the other NPCs.

The issue is that Nasmara Moonsong does not give me the option to unlearn the spec. It only gives me option to buy some patterns.

**Comment by MalkaviaDW** [comment]
Hello, 

This was fixed a long time ago, thank you for the report.

Cheers!
