### ISSUE TITLE
Engineering: Nitro Boosts [54861]

### ISSUE THREAD

**Issue by Golganeth** [dalaranwow/dalaran-wow#2026]
**Issue:** The spell may fail if used inside a dungeon, raid or battleground map.

**How it should work:** The spell effect shouldn't fail inside any of those maps. The perk was changed after WotLK with Cataclysm.

http://wotlk.openwow.com/spell=54861

--------------

While I couldn't find any official patch changes in regards of this matter, I found several different threads about people complaining (from Cataclysm and onwards) about the fact that Blizzard changed this.

http://eu.battle.net/wow/en/forum/topic/1549385535
> In WotLK Nitro Boosts could never fail in raid. 

http://eu.battle.net/wow/en/forum/topic/1751688184
> I'd like to request that line is removed, changed to "they explode violently regularly" or the actual nitro boosts reverted to how they worked back at the end of WotLK - where they NEVER backfired in BGs or PvE.

**Comment by Winstrol** [comment]
please fix this, this bug makes engineering so much worse than it should be.

**Comment by Crispybuilt** [comment]
Did anyone got any fails inside the Raids so far?
I've been using them for several months and it never failed for me inside the instance.
Specifically Ulduar/Trial of the Crusader

Also got confirmation from a guildie who's been using them constantly that they do not fail in raids.
So maybe this got fixed?

**Comment by Golganeth** [comment]
This was already fixed indeed. If you notice any issue regarding this, please leave feedback down below.

Closed
