### ISSUE TITLE
H Gundrak - Instance Completed when not Saved

### ISSUE THREAD

**Issue by DiiNovensiles** [dalaranwow/dalaran-wow#2028]
2 of the 4 times I've entered H Gundrak with a group on Algalon it has acted as if it's completed even when noone is saved. The bridge is in position with altars unclickable and bosses are missing.

Resetting dungeons and/or reforming the group doesn't fix the issue.

**Comment by Rushor** [comment]
cannot reproduce this anymore - add informations if the issue is still present on the live-server
