### ISSUE TITLE
Hakkari items

### ISSUE THREAD

**Issue by natrixas** [dalaranwow/dalaran-wow#2029]
There is a oozes in plaguelands (cave), which killed spams little ones. That little ones drops items that it shouldn't, like hakkari set (it's dungeon q reward). That items (bop) can be equipted on any lvl char (like 1lvl or 19lvl). That would be easy fix which will drag down 19lvl twinks a bit, so bgs would be more easy for non twinks at that lvl.
cave location:
http://s7.postimg.org/8zc1pupaj/World_Map_Western_Plaguelands.jpg

**Comment by Winstrol** [comment]
might aswell lock this since its fixed.

**Comment by Lothloryen** [comment]
Hello there,

Yes, all these items level restriction has been corrected.

Thank you very much.

**Comment by n-ghost** [comment]
Just got some of those items from oozelings.

There is still no level requirements, but those items are soulbound (meaning that low-level characters can get those only with help of higher levels). Still, worth doublechecking.

![wowscrnshot_021915_193913](https://cloud.githubusercontent.com/assets/8515510/6272285/428c6afe-b86f-11e4-99b3-c1ec4958c5a9.jpg)
![wowscrnshot_021915_193909](https://cloud.githubusercontent.com/assets/8515510/6272291/467b556c-b86f-11e4-9ea0-d323534f1297.jpg)
![wowscrnshot_021915_193904](https://cloud.githubusercontent.com/assets/8515510/6272293/4c5099b6-b86f-11e4-86b5-5c2d3e762064.jpg)

**Comment by Golganeth** [comment]
They were already soulbound before the hotfix. Level requirements show fine for me though.

![image](https://cloud.githubusercontent.com/assets/5057942/6289565/52d876e8-b921-11e4-90f5-1e74a776b478.png)
