### ISSUE TITLE
Northrend Transport Music

### ISSUE THREAD

**Issue by Canderous** [dalaranwow/dalaran-wow#2035]
The music that should play when you take a boat or a zeppelin to Northrend does not play.
https://www.youtube.com/watch?v=hcvVu8mCGIM&list=RDhcvVu8mCGIM&index=1
https://www.youtube.com/watch?v=vfhZmlRCXPU&index=2&list=RDhcvVu8mCGIM

This is a very minor and atmospheric issue of course, but the server has so many great details, I thought I should mention this.

**Comment by Lothloryen** [comment]
Fixed in #5018
