### ISSUE TITLE
[Quest][Northrend] Need More Info / No Rest For The Wicked

### ISSUE THREAD

**Issue by Canderous** [dalaranwow/dalaran-wow#2039]
There are 2 minor issues with these quests.

1) The items (Robes, Scepter, Skull, Heart) you loot to summon Alumeth do not have a duration of 2 minutes as they should.
http://www.wowhead.com/item=44479
http://www.wowhead.com/item=44476
http://www.wowhead.com/item=44478
http://www.wowhead.com/item=44477

2) There are too few Cult Researchers spawned, there are none on the right side of the room. Also, they don't use their abilities.
http://www.wowhead.com/npc=32297#abilities

**Comment by Rushor** [comment]
DB/Quest: No Rest For The Wicked - Limit duration for questitems to 120 seconds and add SAI for Cult Researcher

* closes https://github.com/dalaranwow/dalaran-wow/issues/2039
* commit: ef9035bf3898fc751b7da23cab1ab1b369b866f2

**Comment by TeridanDW** [comment]
Works as intended on PTR.
