### ISSUE TITLE
[GO] Scarlet Onslaught Trunk Key

### ISSUE THREAD

**Issue by Canderous** [dalaranwow/dalaran-wow#2040]
The key is not needed to open the trunks (and does not disappear even if you have a key in your inventory when you open a trunk), making the quests associated with the objects easier.

http://www.wowhead.com/item=40652
http://www.wowhead.com/object=191543

**Comment by Rushor** [comment]
![GitHub Logo](http://i.imgur.com/Gwsm9aR.png)

works already on PTR.
