### ISSUE TITLE
[NPC] Venture Co. Ruffian

### ISSUE THREAD

**Issue by Canderous** [dalaranwow/dalaran-wow#2041]
There is a minor issue with them, they use their Backhand ability on themselves instead of their target.
http://www.wowhead.com/npc=28124#abilities

**Comment by Rushor** [comment]
DB/Creature: Venture Co. Ruffian SAI - use propper Backhand spell

* closes https://github.com/dalaranwow/dalaran-wow/issues/2041
* commit: 2da2bb4ed1e1d2d13cc3eb2abfb894c6f1606cd9
