### ISSUE TITLE
[Instance] Utgarde Keep Bugs

### ISSUE THREAD

**Issue by Canderous** [dalaranwow/dalaran-wow#2045]
Reference video from Cataclysm:
http://www.youtube.com/watch?v=clezph_OgrE&list=UUSco-JUaLS8hDLn8aHrveeQ

- [x] 1) Dragonflayer Runecasters can cast their shield abilities on mobs that are not in combat yet. They should only cast it on mobs that are already in combat in order to not waste a cast.
www.wowhead.com/npc=23960

- [x] 2) The Ticking Bombs that the Dragonflayer Strategists place on the ground have no effect at all. The debuff correctly appears on players standing on them, but they do not explode for damage. Also, they are attackable and targetable, when they shouldn't be.
http://www.wowhead.com/npc=23956#abilities

- [x] 3) There are some minor issues with Ingvar's roleplay transition from phase 1 to phase 2. Sometimes (I suspect if there are "multiple killing blows" involved), he will yell his first death yell multiple times, Annhylde appears multiple times and the event happens multiple times.

Also, Annhylde is missing some yells:
"Ingvar! You have been judged and found worthy! Arise and slaughter in the Lich King's name!"
"Ingvar! Your pathetic failure will serve as a warning to all... you are damned! Arise and carry out the master's will! "
She should do the first one if Ingvar managed to kill someone in phase 1, and the second if he didn't.

When Ingvar is resurrected, he should yell: 
"I return! A second chance to carve your skull!"
And when he dies for the last time:
"No! I can do... better! I can..."

Useful links:
http://www.wowwiki.com/Ingvar_the_Plunderer
http://www.wowhead.com/npc=23954

- [x] 4) Ingvar is stunnable in his phase 2, he should not be.

- [x] 5) When Ingvar is resurrected and phase 2 begins, he should cast Dreadful Roar immediately. This was the reason that everyone used to hide behind the pillars at the start of phase 2. It is not needed here right now. http://www.wowhead.com/spell=42729

- [ ] 6) The fire walls at the big circular starting room (from 0:30 on the video) should block line of sight. Right now, it is possible to pull mobs through the wall, skipping a few groups in the process (since the Forgemaster aggroing makes the flame disappear, which is correct).

- [x] 7) There are no patrols at all in the instance currently. The video shows all of them.

- [x] 8) Proto-Drake Handler https://wowgaming.altervista.org/aowow/?npc=24082 - Their Throw ability https://wowgaming.altervista.org/aowow/?spell=54983 looks like a blue cube while it should look like a knife instead.

- [x] 9) The spawnanimation for the https://wowgaming.altervista.org/aowow/?npc=23970 Vrykul Skeletons is missing. They should cast birth and then after 5 seconds walk towards the players. https://www.youtube.com/watch?v=0R7SfCBo0vk 

- [x] 10) The summoned creatures https://wowgaming.altervista.org/aowow/?npc=23970 for price keleseth should despawn together with the boss once prince keleseth died.

- [x] 11) https://www.youtube.com/watch?v=BqR6Kjz0jvo There should be an Introevent with Ingvar and the Proto-Drake Rider every few seconds. He should yell some sentences like 'Raze every structure! Silence every cry! or 'Slay them all! No excuses! No mercy! No rest!' to them - and then they fly away - returning after few seconds.

**Comment by Rushor** [comment]
Okay the patrols were added already 2 years ago.

**Comment by Rushor** [comment]
> Dragonflayer Runecasters can cast their shield abilities on mobs that are not in combat yet. They should only cast it on mobs that are already in combat in order to not waste a cast.

Actually the creatures should have a formation, where all the trash groups of Dragonflyer attack together.

**Comment by Rushor** [comment]
The spawnanimation for the https://wowgaming.altervista.org/aowow/?npc=23970 Vrykul Skeletons is missing. They should cast birth and then after 5 seconds walk towards the players. https://www.youtube.com/watch?v=0R7SfCBo0vk

**Comment by Rushor** [comment]
The summoned creatures https://wowgaming.altervista.org/aowow/?npc=23970 for price keleseth should despawn together with the boss once prince keleseth died.

**Comment by Rushor** [comment]
https://www.youtube.com/watch?v=BqR6Kjz0jvo There should be an Introevent with Ingvar and the Proto-Drake Rider every few seconds. He should yell some sentences like 'Raze every structure! Silence every cry! or 'Slay them all! No excuses! No mercy! No rest!' to them - and then they fly away - returning after few seconds.

**Comment by Rushor** [comment]
> The fire walls at the big circular starting room 

The walls already disable LOS, however the creature groups should be linked together.

**Comment by Rushor** [comment]
All issues from the list were handled now - the missing thing are the emotescripts for the creatures. Will add them once i got a video from the instance. Thanks
