### ISSUE TITLE
Azjol-Nerub Bugs

### ISSUE THREAD

**Issue by Canderous** [dalaranwow/dalaran-wow#2047]
Reference video from the end of WotlK: http://www.youtube.com/watch?v=31OlMogSrkM

1) The first two mobs at the start of the instance do not patrol. Route can be seen in the video.

2) On normal mode, all bosses are stunnable (and probably slowable etc. too). They should not be.
http://wotlk.openwow.com/npc=28684
http://wotlk.openwow.com/npc=28921
http://wotlk.openwow.com/npc=29120

3) The aggro drop that the Anub'ar Skirmishers do does not work here. When they do this, they should be immune to taunts and focus on the random person. After the effect wears off, they should continue to go for the target that had the highest threat on their loot table (usually back to the tank).
http://www.wowhead.com/spell=52537 - the spell they should use
http://wotlk.openwow.com/npc=28734
http://wotlk.openwow.com/npc=31606

4) Anub'ar Skirmishers on normal mode use Backstab even when their target is in front of them, resulting in massive damage output. They should only use Backstab from behind.

5) The trash at the start drop Borean Leather and Nerubian Chitin as normal loot on normal mode. They should only drop these via skinning,
http://wotlk.openwow.com/npc=29335
http://wotlk.openwow.com/npc=28733
http://wotlk.openwow.com/npc=28734
http://wotlk.openwow.com/npc=28732

6) The Krik'thir event is not working as it should. The yells he makes now after each Watcher group is down should be yelled at certain intervals before the Watchers are aggroed, starting from when the group enters the instance.
http://www.wowwiki.com/Krik%27thir_the_Gatewatcher describes his yells in detail.
Functionally, the way this event hould work is that once a Watcher group is aggroed, there should be a timer starting and when that expires, a random other Watcher group should aggro on the party, and so on, until all Watchers are dead. After a few seconds after they are all dead, Krik'thir should aggro himself. If the party wipes, all Watchers and their groups should respawn and the encounter reset. More details can be found on the wowwiki page and the video from 1:48 - 4:46.

7) The Web Wrap ability cast by several mobs in the instance does not do anything. It should stun the target, spawning a web wrap mob on them, dealing damage over time until the web wrap is killed. 1:13 on the video is a good example.
http://wotlk.openwow.com/spell=28622

8) Hadronox is also not scripted, but I guess it's a known issue, very complex to script properly and detailed on his wowwiki page (in the video, he bugged him out).
http://www.wowwiki.com/Hadronox

9) The Skittering Swarmers on normal mode give a lot of XP. They should give none.
http://wotlk.openwow.com/npc=32593

The next ones are going to be about the Anub'arak encounter, which starts at 7:40 in the video.

10) The Carrion Beetles spawned by Anub'arak give a lot of XP on normal (they shouldn't), have a lot of health (they shouldn't) on both normal and heroic, and deal 1 damage (they should deal more) on both normal and heroic.
http://wotlk.openwow.com/npc=29209
http://wotlk.openwow.com/npc=31647

11) Anub'arak's Pound does not work correctly. Here, it always hits the tank (and another person if they are close to the tank), and always deals 0 damage.
Here is a quote from wowwiki on how it should work:
Pound: 18k on plate with a 4 second stun, has a 3 second cast time. This ability hits in a frontal cone from Anub'arak. Note that the direction Anub'arak casts it is towards wherever his aggro target was standing at when he BEGINS casting Pound; he cannot turn during its cast time. The facing of Anub'arak's model may not accurately show the direction he's casting Pound at; if you are unsure of where he's aiming a Pound, it's best to run away from him, as Pound's max range is short (10-15 yards). It can be particularly hard to predict where a Pound is being aimed at if Anub'arak starts casting it immediately after running to an edge of the platform, or immediately after surfacing, since threat is wiped after a resurface and Anub'arak's first aggro target will be whoever happens to attack him first.

12) There are very few Anub'ar Darters spawning after the third burrow, there should be a lot more, and they should use their Dart ability.
http://wotlk.openwow.com/npc=29213
http://wotlk.openwow.com/npc=31598

13) Anub'ar Guardians do not use their abilities on either mode.
http://wotlk.openwow.com/npc=29216
http://wotlk.openwow.com/npc=31599

14) Anub'ar Venomancers do not use their abilities. Also, they should only spawn on heroic mode.
http://wotlk.openwow.com/npc=29217
http://wotlk.openwow.com/npc=31607

**Comment by Golganeth** [comment]
Already fixed with last AN revamp.
