### ISSUE TITLE
[Instance] The Nexus - Main issue

### ISSUE THREAD

**Issue by Canderous** [dalaranwow/dalaran-wow#2048]
Reference video from Cataclysm (instance is same as in WotlK):
http://www.youtube.com/watch?v=Qduq-xNZgKg

- [x] 1) The 3 sets of Mage Slayer + Mage Hunter Ascendant patrol groups are not patrolling. You can see their routes in the video. (Before and after the frozen faction mobs, and after Grand Magus Telestra)

- [x] 2) The frozen faction mobs are too few. The first 3 are placed appropriately, but the rest of them are missing. There should be of them (Cleric + Berserker or horde versions) with the boss that should always come with him. Relevant part in the video is 0:53 - 2:05.

- [x] 3) Grand Magus Telestra should use her Gravity Well more often (in the video, starting from 3:23, you can see her cast it before the first split). It also doesn't do the tossing effect here, just the damage.
http://www.wowhead.com/spell=47756

- [x] 4) The Chaotic Rifts' spell attacks should chain on enemy targets, but I believe they do not chain here (might need more testing). Also, the effect should ignore distance and LoS, this was the reason the Chaos Theory achievement was hard before the "1 rift only on Anomalus" nerf.
http://wotlk.openwow.com/npc=30522
http://wotlk.openwow.com/npc=26918

- [x] 5) The Crazed Mana-Surges throughout the instance are not attackable, but they should be. Just before Anomalus, the dragonkin trash should be dead, and the group should contain the Mana-Surges and the Rift already present there. In the video, the part starts from 6:21.
Also, when the Crazd Mana-Surges die, the mana restorative aura should appear as seen in the video. They should also cast Mana Burn and Arcane Nova.
http://wotlk.openwow.com/npc=30519
http://wotlk.openwow.com/npc=26737

- [x] 6) There are a few groups of Crystalline Tenders and Keepers that are not patrolling. 8:08 - 8:57 on the video.

- [x] 7) The AI of the Crystalline Frayers is not working correctly. Right now, they don't aggro unless concentrated upon hard. When they die and Ormorok is still alive, they should be encapsulated in a pod as seen in the video also from 8:08. After a while, they should become active again and be aggroed again normally.
http://www.wowwiki.com/Crystalline_Frayer

**Comment by belegija** [comment]
just did the first run
3) still no tossing, just pulled to the center
7) they aggro for only under a second they they reset

also [Crazed Mana-Surges](http://www.wowhead.com/npc=26737/crazed-mana-surge#abilities) should spawn area of effect that gives back mana, called [Loose Mana](http://www.wowhead.com/spell=29882).

**Comment by Rushor** [comment]
> The AI of the Crystalline Frayers is not working correctly. Right now, they don't aggro unless concentrated upon hard. When they die and Ormorok is still alive, they should be encapsulated in a pod as seen in the video also from 8:08. After a while, they should become active again and be aggroed again normally.

Thsi works fine already on PTR.

**Comment by Rushor** [comment]
> also Crazed Mana-Surges should spawn area of effect that gives back mana, called Loose Mana.

Works fine already on PTR.

**Comment by Rushor** [comment]
> The frozen faction mobs are too few. The first 3 are placed appropriately, but the rest of them are missing. There should be of them (Cleric + Berserker or horde versions) with the boss that should always come with him. Relevant part in the video is 0:53 - 2:05.

Done. ![GitHub Logo](https://i.imgur.com/caDBC6e.jpg) ![GitHub Logo](https://i.imgur.com/riYJYJv.jpg)

**Comment by Rushor** [comment]
> The Crazed Mana-Surges throughout the instance are not attackable, but they should be. Just before Anomalus, the dragonkin trash should be dead, and the group should contain the Mana-Surges and the Rift already present there. In the video, the part starts from 6:21.
Also, when the Crazd Mana-Surges die, the mana restorative aura should appear as seen in the video. They should also cast Mana Burn and Arcane Nova.

Already works fine on PTR. 

![GitHub Logo](https://i.imgur.com/UUyZaG1.jpg)

**Comment by Rushor** [comment]
> The Chaotic Rifts' spell attacks should chain on enemy targets, but I believe they do not chain here (might need more testing). Also, the effect should ignore distance and LoS, this was the reason the Chaos Theory achievement was hard before the "1 rift only on Anomalus" nerf.

Already works fine on PTR.

**Comment by Rushor** [comment]
There should be a tiny event where Azure Skyrazor casts Arcone Bolt every few seconds on a Crazed Mana-Wyrm. 

![GitHub Logo](https://i.imgur.com/Wywk7AZ.jpg)

**Comment by Rushor** [comment]
There should be some Breath Caster which cast a freeze spell priodically on the ice prison of Keristrasza

![GitHub Logo](https://i.imgur.com/2kEBkst.jpg)

**Comment by Lothloryen** [comment]
Everything from this report and several other improvements will be applied to Algalon during the next maintenance.

Thank you.
