### ISSUE TITLE
Halls of Stone Bugs

### ISSUE THREAD

**Issue by Canderous** [dalaranwow/dalaran-wow#2049]
Reference video from Cataclysm (same instance as in WotlK):
http://www.youtube.com/watch?v=9x5sliYDPXU&list=UUSco-JUaLS8hDLn8aHrveeQ

1) Dark Rune Elementalists don't seem to cast Summon Air Elemental.
http://wotlk.openwow.com/npc=31372
http://wotlk.openwow.com/npc=27962

2) There are lots of patrols missing, you can see it on the video from the start until roughly 1:35 and from 4:06 - 4:10.

3) Krystallus does not always apply Petrifying Grip after a knockback. If this happens, Shatter might end up one shotting the person who did not get Petrifying Grip.

4) Lightning Constructs should have the Electrical Overload buff when they stand near the giant beam just before the Tribunal of Ages room. It should preiodically damage nearby enemies and should be quite deadly.
http://wotlk.openwow.com/npc=31383
http://wotlk.openwow.com/npc=27972

5) If Brann Bronzebeard dies in some way, he will not respawn, making the instance uncompletable.

6) During the Tribunal of Ages encounter, the 3 giant statue heads should activate periodically, each of them using some ability to hinder the party. It is very well explained on wowwiki. The event is shown from 8:12 - 10:30 in the video.
http://www.wowwiki.com/Tribunal_of_Ages

7) The mobs that spawn during the Tribunal of Ages event have no abilities or weapons (visual issue). The mob spawning is also a bit different from retail, you can also see it from 8:12 - 10:30 in the video. Basically, as each of the heads activate, new type of mobs should spawn. It works with the golems, but the other 2 dwarf types come together from the start. Also, they should spawn from 2 directions instead of one.
http://wotlk.openwow.com/npc=31876
http://wotlk.openwow.com/npc=27983
http://wotlk.openwow.com/npc=31877
http://wotlk.openwow.com/npc=27984
http://wotlk.openwow.com/npc=31380
http://wotlk.openwow.com/npc=27985

8) Brann does not move from the Tribunal room to Sjonnir's room, as there is no dialog option to skip the roleplay after the Tribunal. This makes it so the quest is only completable at another run. There is the option after the roleplay has finished, but then Brann just disappears (this is correct), but does not appear at Sjonnir and doesn't participate in the fight. See Brann's participation at the end from 11:40.

9) Sjonnir's adds don't have abilities, sometimes don't attack or not even attackable. They also come very late, they should come at a much faster interval.
http://wotlk.openwow.com/npc=31394 (and normal version)
http://wotlk.openwow.com/npc=31390 (and normal version)
http://wotlk.openwow.com/npc=31388 (and normal version, this one is friendly)
http://wotlk.openwow.com/npc=31389 (and normal version, this should come from combined Malformed Oozes, I never got to see one yet, because he always dies faster, so not sure if it works)
http://www.wowwiki.com/Sjonnir

10) Normaly there should be coming out a fire laser beam out of the statue which is not happening as we're doing the boss 

https://youtu.be/_LO_61yVl1w?t=14m26s
http://wowwiki.wikia.com/wiki/Tribunal_of_Ages
I'm also fairly certain the abilities on the adds are not scripted as well; all found here: (2nd tab for heroic abilities)
http://www.wowhead.com/npc=28234/tribunal-of-the-ages#article

Here are the 3 faces, but I can't find any spell IDs on what they cast or if they are even casting the spells (is it just appearing out of thin-air from some invisible NPC or what not? idk).
http://www.wowhead.com/npc=30898/kaddrak
http://www.wowhead.com/npc=30899/abedneum
http://www.wowhead.com/npc=30897/marnak

<a href="http://nl.tinypic.com?ref=1q0tvk" target="_blank"><img src="http://i67.tinypic.com/1q0tvk.jpg" border="0" alt="Image and video hosting by TinyPic"></a>

**Comment by Akkalevil** [comment]
Krystallus often OS people even though they are far appart.
Also, rather often the petrification isn't removed after the shatter, which ends in people being petrified for more than 20s straight.

**Comment by Lothloryen** [comment]
Hello there,

Thank you for the report, this dugenon has also been reworked (including the Tribunal of Ages) and it will be on the live server after the next scheduled maintenance.

**Comment by Lothloryen** [comment]
Live now.
