### ISSUE TITLE
Archavon the Stone Watcher

### ISSUE THREAD

**Issue by Canderous** [dalaranwow/dalaran-wow#2055]
Reference video: http://www.youtube.com/watch?v=K90b3cMqSMQ

1) Archavon's Rock Shards can target any hostile targets of Archavon (totems, pets etc). It should only target players. Totems for example instantly die and the Rock Shards stop due to it.

2) Archavon's lunging attack (when he grabs the current main tank) does not work to a full extent. Right now, he properly makes the grab after Stomp, making the tank unable to do anything. But he should also go for the second highest threat on his threat table if there are more than 1 targets. Right now, he keeps hitting the grabbed main tank, making the fight require 1 tank instead of 2. Also, the general announcement is missing when he does the grab ("Archavon the Stone Watcher lunges for <target name>"), the camera and visual effect for the grabbed person is not correct (minor issue), and he does not throw away the grabbed target after he's finished.
0:46 - 0:56 in the video.

**Comment by Rushor** [comment]
moved to https://github.com/dalaranwow/dalaran-wow/issues/564
