### ISSUE TITLE
Emalon the Storm Watcher

### ISSUE THREAD

**Issue by Canderous** [dalaranwow/dalaran-wow#2056]
1) The Tempest Warders before Emalon are not scripted. They should have the same Overcharge mechanic as the Tempest Minions. I couldn't find accurate data about how much health they should start Overcharging, it should be around 20-30%, a number which is close to the actual Tempest Minion health, since the Warders were meant as a raid check for the Minions.
http://wotlk.openwow.com/npc=34015

2) The Tempest Minions' Overcharge explosion can be avoided by going out of its line of sight. The explosion should ignore line of sight, meaning it should always hit the raid if they fail to kill the overcharged Minion in time. I believe this issue persists on both 10 and 25 player mode.

3) On 25 player mode, the Tempest Minions do not "respawn" when killed.

4) On 25 player mode, Emalon's Lightning Nova does not deal less damage with more distance, meaning it always deals the full damage to the raid, unless the raid gets out of his line of sight. Lightning Nova should also ignore line of sight, but deal less damage the further the players are away.
http://wotlk.openwow.com/spell=65279

5) On both 10 and 25 player mode, the Tempest Minions start with 2 or 3 stacks of Overcharged buff most of the time when Emalon casts Overcharge. They should always start at 1 stack and gain a stack every 2 seconds.

**Comment by Jonneitapuro** [comment]
Damage from either Overcharge or Lightning Nova can no longer be avoided by line of sight, but Lightning Nova still doesn't deal less damage with distance. This means that the nova will kill everyone who isn't a tank/has a defensive cooldown/shield up, meaning the fight is near impossible.

**Comment by Rushor** [comment]
merge with https://github.com/dalaranwow/dalaran-wow/issues/564
