### ISSUE TITLE
[Rogue][Assassination] Overkill buff countdown timer not displayed after exiting stealth

### ISSUE THREAD

**Issue by yoyosan** [dalaranwow/dalaran-wow#2059]
As an Assassination rogue, when you exist Stealth, the [Overkill](http://www.wowhead.com/spell=58426) buff countdown timer is not displayed at all. 
Instead, you get the Overkill buff icon that wil disappear after 20 seconds.

**Comment by Golganeth** [comment]
Corrected after the next scheduled maintenance.
