### ISSUE TITLE
[Druid][Restoration] Wild Growth doesn't correctly heal party/raid members in a 15 yards range

### ISSUE THREAD

**Issue by yoyosan** [dalaranwow/dalaran-wow#2060]
Hello.

Me and my guildmate just tested [Wild Growth(WG)](http://wotlk.openwow.com/spell=48438). We've used DBM's range check tool to measure 15 yards correctly.

Please take a look at the screenshots and scenarios below:

![Example 1](http://s29.postimg.org/gj2oyq07r/Wo_WScrn_Shot_110914_145833.jpg)

* *Dudus* had cast Wild Growth on *Ginxy*, *Ginxy* receives WG but *Dudus* doesn't receive it even if he's in range.

![Example 2](http://s13.postimg.org/vbwtga7gn/Wo_WScrn_Shot_110914_145819.jpg)

* *Dudus* had cast Wild Growth on himself.  *Ginxy* doesn't receive WG even if she's in range.

We've did some more tests and concluded that:
* it works when we're in a 10 yards range
* it works when we're in a 13-14(we don't have a better tool to measure it other than DBM's range check) yards range.

Thank you.

**Comment by robinsch** [comment]
@Golganeth Could you (or someone else) test this on PTR with .distance command?

**Comment by Golganeth** [comment]
@robinsch 
On a flat ground, this is the distance limit where it stops applying WG to a friendly target if I cast it on myself:
The distance is: (3D) 13.534212 (2D) 13.534212 (Exact 3D) 16.534212 (Exact 2D) 16.534212 yards.

One small step forward makes it apply, distance:
The distance is: (3D) 13.390532 (2D) 13.390532 (Exact 3D) 16.390532 (Exact 2D) 16.390532 yards.

**Comment by robinsch** [comment]
I will close this because we have no proof if it should include bounding radius or not. (And you won't find it)
