### ISSUE TITLE
[NPC] The "Zombie" Snakes :D

### ISSUE THREAD

**Issue by Todoran** [dalaranwow/dalaran-wow#2064]
looks dead, but they can attack u ..... 
Pics here:  http://postimg.org/image/58d4sjet1/ and http://postimg.org/image/wu4ewt1nb/

**Comment by Rushor** [comment]
already fixed on PTR with 

https://github.com/TrinityCore/TrinityCore/commit/c1006c5a53b4d33c9b9163483f42e1162c063ffb
