### ISSUE TITLE
Aaron Hollman <Blacksmithing Supplies>

### ISSUE THREAD

**Issue by Nenki** [dalaranwow/dalaran-wow#2073]
The blacksmithing plans for Adamantite Rod appear to spawn incredibly infrequently from "Aaron Hollman" <blacksmithing supplies> in Shattrath, I've heard that other recipes from him also respawn incredibly infrequently, as I bought the two-handed Adamantite Axe recipe from him, and 3 hours later, others were still waiting on it to respawn, making blacksmithing incredibly difficult to get to 350 without potentially paying somebody who was first to him after a reset an absolutely ludicrous amount on the auction house because he got the only one that spawns for 3 or more hours.

**Comment by Sagrath** [comment]
fixed
