### ISSUE TITLE
[Mechanic] Extend Raid Lockout

### ISSUE THREAD

**Issue by Kalyino** [dalaranwow/dalaran-wow#2075]
The Extend Raid Lockout function does not work at all, it is not even scripted. TrinityCore has seem to of abandoned this as the last attention it has gotten was Sep 14, 2011.

When you click extend raid lockout all it does is give you a message that it did extend, when in reality it did not. This is an issue with the core of the server its self.

What should happen is when you click extend lockout it extends it till the next week, if you click it a second time it removes the extension.

**Comment by saltylopez** [comment]
This is still broken.

Are there any intentions to make this utility functional?  It would be a great help to some of the guilds with more limited raid times that are trying to make it through Ulduar (and later ICC).

**Comment by shadovvs** [comment]
It is implemented in TrinityCore. Difficulty of adding it to dalaran-wow is going to depend on how heavily modified the core is.

Maps/Instances: Implement handling of CMSG_SET_SAVED_INSTANCE_EXTEND:
https://github.com/TrinityCore/TrinityCore/pull/16392

Merge branch '3.3.5-instanceextend':
https://github.com/TrinityCore/TrinityCore/commit/62aff401f687b56d720a320778950e82b65fbd8b

**Comment by Rushor** [comment]
it will be merged with everything else in the future. thanks for the note (and thanks for you addonwork btw)

**Comment by KharchenkoDmitriy** [comment]
This is still broken. So ICC is already provided and it will be realy usefull to expand lock, because we can try it whole week and even more. I believe that this issue is not forgotten and will be merged.

**Comment by Rushor** [comment]
Yep it will be merged in the future with https://github.com/TrinityCore/TrinityCore/commit/62aff401f687b56d720a320778950e82b65fbd8b

I will close it and lable it with the Merger Milestone. Thank you.

**Comment by chris-wyatt-livinglens** [comment]
This is merged in TrinityCore now. Is it going to appear on dalaran-wow at some point?
