### ISSUE TITLE
Quest "Sniffing out the perpetrator" (Alliance) bug

### ISSUE THREAD

**Issue by Aalhazred** [dalaranwow/dalaran-wow#2078]
Well, the problem is that this specific quest can't even be taked from the quest.giver, blocking a huge quest chain, (being this quest the 2/17 of the questchain), and also possibly blocking the acchivement "the summit of storm peaks" (87/100 quest atm, this is the last quest chain i need, maybe it happen to other people too)

Wowwiki source : http://www.wowwiki.com/Quest%3ASniffing_Out_the_Perpetrator_(Alliance)

proofs:http://i.imgur.com/Sk97fj6.jpg

**Comment by ashido96** [comment]
This is also bugged for horde side.

**Comment by Bloodhawk92** [comment]
Still not working (alliance)

**Comment by MalkaviaDW** [comment]
Would you care to specify the issue? No player has reported this quest in around 2 weeks by in-game ticket.

**Comment by Bloodhawk92** [comment]
The mob's nameplate appears outside the cave, but it is untargetable, so you cannot get credit for the quest.

**Comment by MalkaviaDW** [comment]
Check it again, please. I just checked it in-game and the NPC seems to be on its spot. 

Cheers!

**Comment by Bloodhawk92** [comment]
It works now, cheers!

**Comment by Lothloryen** [comment]
This was fixed already. If anyone else experiences any issue, let us know, please.

**Comment by Randomi** [comment]
Hello, I have killed Tracker Thulin multiple times and never looted Brann's communicator. I also read that Moteha Windborn would provide you with a communicator if you don't have one, which is not the case here.
