### ISSUE TITLE
Strand of the Ancients - Demolisher hp regeneration

### ISSUE THREAD

**Issue by Johanes022** [dalaranwow/dalaran-wow#2080]
Current situation:Players who control Demolishers are able to regenerate(abuse) cannon hp.Whenever demolisher is below maximum hp all they need to do is to leave/exit vehicle and demolisher will regenerate back to his maximum health in a second or two,and they can mount and use it over and over again.
Desired situation:Demolishers should not regenerate their health points upon dismounting.
Many players know about this bug and abuse it almost every battle.It is similar to https://github.com/dalaranwow/dalaran-wow/issues/1949

**Comment by Lothloryen** [comment]
It will be corrected after the next server restart.

Thank you.
