### ISSUE TITLE
Death Knight: Death Rune conversions back to basic runes

### ISSUE THREAD

**Issue by Nevahs** [dalaranwow/dalaran-wow#2083]
Whenever all Frost and Unholy Runes are converted into Death Runes, any skill used will start using the Death Runes that were converted from Unholy Runes, even Skills that require Frost Runes.

Example:
Have all runes be normal at first -> B B F F U U
Death Strike twice to convert F and U runes into D runes -> B B D D D D
Use Icy Touch and Plague Strike you'd expect it to be -> B B F D U D
Instead it will be -> B B D D U U

The Runes should be used up depending on their state before the Death Rune conversion, and only if no "Native" converted runes are available, use a converted Unholy Runes for a Frost attack ect.

My UI shows that it will always uses the Death Runes in the Following order: B B 3 4 1 2

**Comment by Icespear1** [comment]
Tested this recently and it seems its working fine for me. Used Death Rune Mastery talent in the blood tree.

Started off with BB DD DD. Used Icy Touch and Plague Strike and ended up with BB FD UD.

Screenshots: http://imgur.com/a/UEu0j

**Comment by Rushor** [comment]
well then if it already works fine on live realm - /closes
