### ISSUE TITLE
Credit while in party / Group quests

### ISSUE THREAD

**Issue by Nevahs** [dalaranwow/dalaran-wow#2089]
This Questchain appears to be bugged. Only a random amount of people in a group get credit for the completion if at all. Relogging brought no change, dismissing hunter pets didn't appear to have an effect. Even soloing the quest didn't give any credit.

If someone got credit before, reforming the group seem to change who got credit for the kill, however that led to less people being credited than before.

**Comment by Golganeth** [comment]
#32 Merge

**Comment by Golganeth** [comment]
Confirmed, credit issue for members when doing a group quest used to happen for a lot of them (can't be reproduced at the moment because of #3337 though).
