### ISSUE TITLE
Death Knight - Ebon Gargoyle cast speed

### ISSUE THREAD

**Issue by Johanes022** [dalaranwow/dalaran-wow#2091]
Current situation:Right now if when death knight summons Ebon Gargoyle his cast time will be 2.0sec no matter how much haste does death knight has.The only things that affect gargoyle cast time is Heroism/Bloodlust(after Gargolye is summoned) and Wrath of Air totem.

Desired situation:Ebon Gargoyle cast time should be affected by death knights current haste rating.

When summoned Ebon Gargoyle takes a "snapshot" of death knights current stats.
I have 337 (13,36%) Haste without buffs/potions
I did some testing :

1.With Blood presence : Gargoyle cast time is 2.0sec
2.With Unholy presence: Gargoyle cast time is 2.0sec
3.With Unholy presence(20%-attack speed) + Haste potion(500haste) + Icy Talons(talent-20% attack speed)+ Heroism then summoned gargoyle(gargoyle doesnt get heroism buff) : Gargoyle cast time is 2.0sec 
4.With Unholy presence(20%-attack speed) + Haste potion(500haste) + Icy Talons(talent-20% attack speed)+ summoned gargoyle then Heroism(gargoyle gets heroism buff) : Gargoyle cast time is 1.5sec 
5.Wrath of Air totem reduces his cast time from 2.0  to 1.9sec

PS:Im not sure if Gargoyle cast time should be affected by death knight current attack speed.But some people said that they were switching to Unholy Presence just before they summoned gargoyle.

**\* If i may add to this that whenever you summon gargoyle he will not attack unless death knights moves(pet moves with him) after that gargoyle will attack the random target he finds around the player.

**Comment by Esunnaxqt** [comment]
I think more extensive tests should be made to gargoyle and another pets like this.
If its not snapshoting the caster haste, its probably not snapshoting its resilience and other stats correctly.

**Comment by Johanes022** [comment]
Cast time on ebon gargoyle is working now, but still he wont attack your target unless you move (and he follows you), then he will start attacking.
