### ISSUE TITLE
[Outland] [Quest] There's No Explanation for Fashion (id: 9769)

### ISSUE THREAD

**Issue by Exorcista** [dalaranwow/dalaran-wow#2096]
<b>Link:</b> http://www.wowhead.com/quest=9769/theres-no-explanation-for-fashion

<b> Description: </b>: 

Bring 8 Diaphanous Wings from any species of Zangarmarsh fireflies to Magasha in Swamprat Post.

:: Diaphanous Wing (8)

<b> Issue present: </b>: The drop on <b>Diaphanous Wing - 24372</b> from <b>Umbraglow Stinger's- 18132</b> is extremely low, 1/9 mobs (this is the farest i got), thats less than the 30% that wowhead says, making this quest not pleasant to do at all, hence most pple droping it.

<b> How should it work: </b>  %of drop increased arround what wowhead/openwow says.

**Comment by Rushor** [comment]
for 18132 the droppchance is 40%. Moreover the more creature you kill, the higher the chance for the drop. Thsi was fixed months ago
