### ISSUE TITLE
Kirin Tor pathing

### ISSUE THREAD

**Issue by martijnhaah** [dalaranwow/dalaran-wow#2099]
Hello there,

At the moment on Kirin Tor the pathing for mobs is on tilt.
It has been so since attacks. I already wrote a lot of messages to staff members --> no response.
E-mail --> no response.

What is the problem?
Mobs are falling through the floors in a lot of occasions (on aggro/movement):
- stormwind city, even the rats drop through the floor
- scarlet monastry, everything falls through
- (quest) mobs with open space beneath them will drop down, and then drop even further through textures when attacked thus making them un-able to loot (and un-able to loot quest items)
- Stormwind Stockades the mobs "run away in fear" will try to get through the ceiling.
- !! spells like death and decay, army of the death etc. etc. will fal through the ground on the spots where mobs would fall through aswell !!
- *
- *
- *
* add countless of other issues here because of this issue with pathing (that happened since attacks)

So, I hope this finally gets some response!
This issue is not present on Algalon realm, tested that.

!!This is NOT the usual "can happen" bug of mobs etc. falling through ground, this issue happens 100% of the time you attack something that has double layers (like the street in stormwind, underneath it you could walk aswell on retail if you bugged it), This bug makes Kirin Tor unplayable at the moment!!

**Comment by vivalagrunt** [comment]
confirm

**Comment by martijnhaah** [comment]
I wonder how much fucks are given this update... if they still did not fix it they lost me for good, not ever recommending this place anymore.

**Comment by Lothloryen** [comment]
I answered you on the forums about this, not sure if you did not read me. Kirin Tor shall also have the update, which will fix this.
