### ISSUE TITLE
[Northend][NPC][Ability] Piercing Blow

### ISSUE THREAD

**Issue by gitghost** [dalaranwow/dalaran-wow#2106]
How it should work?
NPC uses ability on itself making his next melee attack ignore target's armor.

How it works?
NPC uses ability on itself and attack player even when he is out of his melee range.
Melee NPC are now ranged. It looks like NPC is using it as ranged spell.
When they are in melee range, they using both auto attacks and piercing blow 
(it's hard to tell if it's ignoring auto attack timer or not).
Im

Piercing Blow:
http://www.wowhead.com/spell=49749#used-by-npc

Who use this ability?
Venture Co Excavator - Sholazar Bazin: 
http://www.wowhead.com/npc=28123/venture-co-excavator#abilities
Nerub'ar Skitterer - Borean Tundra:
 http://www.wowhead.com/npc=24566#abilities
Iron Rune Worker - Howling Fjord:
http://www.wowhead.com/npc=23672#abilities

During leveling through northend i can tell it's not the only NPC ability, that ignores range.

**Comment by Rushor** [comment]
DB/SAI: Creatures with the ability 'Piercing Blow' will now use the spell in range

* closes https://github.com/dalaranwow/dalaran-wow/issues/2106
* commit: a45c3a5ce14ac7c2cad3e40636356edde9511ef6
