### ISSUE TITLE
[Ulduar] General Vezax Door Remains Locked

### ISSUE THREAD

**Issue by delebota** [dalaranwow/dalaran-wow#2111]
Last week when we killed the Faceless Horror at the start of the General Vezex trash we killed it with one of the demons banished. This seemed to bug out the instance and left the door locked. Pretty easy to work around by not banishing, but it might be something to look at since that's how I remember doing it on live.

**Comment by Lothloryen** [comment]
Hello there,

A hotfix was implemented time ago.

Thank you.
