### ISSUE TITLE
Paladin: Sanctified Retribution

### ISSUE THREAD

**Issue by Silfwer** [dalaranwow/dalaran-wow#2112]
Issue: The talent Sancified Retribution (ID: 31869) doesn't seem to work at all.

Affected spells:
Devotion Aura (ID: 48942)
Retribution Aura (ID: 54043)
Concentration Aura (ID: 19746)
Shadow Resistance Aura (ID: 48943)
Frost Resistance Aura (ID: 48945)
Fire Resistance Aura (ID: 48947)
Crusader Aura (ID: 32223)

How it currently works: Doesn't affect the damage done by Retribution Aura at all. Also doesn't add a 3% damage multiplier either (holding the cursor over "damage" in the character panel doesn't display a "x103%" modifier, tested with all auras).

With 1/1 Sanctified Retribution, my aura still only does 155 damage without other modifiers and 1358 spell power (It should scale with spellpower).

How it Should Work: The talent should give Retribution Aura a 50% damage modifier(from 112 up to 168 base damage at rank 7), this should be visible in the aura's tooltip. The talent should also provide a 3% flat damage multiplier to everyone affected by any of the paladin's auras at all times. This should be visible in the character panel by holding the cursor over "damage".

http://wotlk.openwow.com/spell=31869
http://wotlk.openwow.com/spell=48942
http://wotlk.openwow.com/spell=54043
http://wotlk.openwow.com/spell=19746
http://wotlk.openwow.com/spell=48943
http://wotlk.openwow.com/spell=48945
http://wotlk.openwow.com/spell=48947
http://wotlk.openwow.com/spell=32223
http://www.wowwiki.com/Retribution_Aura?oldid=2184823
http://www.wowwiki.com/Sanctified_Retribution?oldid=2224415

PS: I'm aware that this has been reported and fixed multiple times in the past and maybe no one else sees what I see, but as it stands, it has never worked for me since I came to the server in june 2014.

**Comment by Vaxsysl** [comment]
Not working, just tested with one retri paladin on my mage. Living bomb tick is not increasing if I get any of his auras on me.

**Comment by Lothloryen** [comment]
Hello there,

Thank you for this report, I shall add this task to my list so, it should be corrected soon. I will keep you updated.

**Comment by Lothloryen** [comment]
Hello there,

This issue has been solved, it will be working as it should after the next realm restart.

Thank you very much.
