### ISSUE TITLE
[Paladin] Spell: Hammer of Justice

### ISSUE THREAD

**Issue by Ironfoe** [dalaranwow/dalaran-wow#2116]
Hammer of justice should be able to be used on stun immune mobs to interrupt spell casting, a similar effect of Wind Shear, Shield Bash, Kick, ect.

"Stuns the target for 6 sec and interrupts non-player spell casting for 3 sec."

**Comment by Golganeth** [comment]
Tested with Moorabi (Gun'drak, transformation cast). Sadly the boss was stunnable (it shouldn't) so I triggered diminishing returns by stunning him a couple times. After that, a message "immune" was displayed but cast wasn't interrupted.

Tested with Stormcaller Brundir (Ulduar, chain lightning cast). Message "immune" was displayed but the cast wasn't interrupted.

**Comment by robinsch** [comment]
Are those bosses are immune to interrupt effects?

**Comment by Golganeth** [comment]
No they aren't immune to interrupt effects, tried with kick and mind freeze on same NPCs on the PTR and cast got interrupted.

Tried with world NPCs and it doesn't interrupt either.

**Comment by robinsch** [comment]
Updated!
