### ISSUE TITLE
Quest: Whispers of the Raven God

### ISSUE THREAD

**Issue by Sagrath** [dalaranwow/dalaran-wow#212]
http://www.wowhead.com/quest=10607
While killing Grishna arakkoa players do not gain Understanding Ravenspeech for 2 minutes.
Even while under the effects of the spell, you CANT find and receive the prophecy from the four shrines.
http://www.wowhead.com/spell=37466 - Understanding Ravenspeech

**Comment by Klala** [comment]
The quest works well. You need to kill harbingers\ravens in order to receive the buff as mentioned in wowwiki in the link below.
I'm not sure, but I think you should get the buff from all of the Grishna npcs around the area.
http://wowwiki.wikia.com/Quest:Whispers_of_the_Raven_God?oldid=627322

**Comment by Demlock** [comment]
The quest works well up to the part when you need to get the fourth part of the prophecy. It doesn't give you quest credit at all.

**Comment by Aalhazred** [comment]
Still bugged as demlock said

**Comment by Rushor** [comment]
https://github.com/TrinityCore/TrinityCore/commit/d0d9a5b8e6cb1660e446096a8a22225d676248c7

updated and fixed long time ago
