### ISSUE TITLE
Trinket is not procing on HoTs

### ISSUE THREAD

**Issue by Logik1** [dalaranwow/dalaran-wow#2120]
Hello:)
I observed that this trinket http://www.wowhead.com/item=40685/the-egg-of-mortal-essence is not procing with my druid HoTs :) i hope this problem will be repaired soon :)

**Comment by Exorcista** [comment]
might be related to #2130 from the description

**Comment by M0dinstaller** [comment]
Bump. This needs fixing, it's game breaking to have half the best trinkets for resto druids not work at all. It's also game breaking for shadow priests which have the same problem, but for dot spells.

**Comment by StheNoble** [comment]
since this has been closed yesterday i checked the issue from my report #4687 (closed and linked to this issue) again. unfortunatly nothing has changed, PW:S and its Glyph still dont proc Illustration
