### ISSUE TITLE
Priest: Divine Hymn [64843]

### ISSUE THREAD

**Issue by Golganeth** [dalaranwow/dalaran-wow#2124]
- **Issue:** Each tick of the spell heals all the friendly units within 40 yards even if they aren't party or raid members. For this reason, the spell doesn't have a maximum number of ticks - the more people around the caster, the more it heals.

- **How it should work:** Each tick of the spell should heal 3 party or raid members within 40 yards. The spell is considered a "smart heal" and the mechanics should work as follows (quoting from Wowhead):
>Say it hits persion A, B, and C. After the heal, A has more health than D. 
>The next tic, the spell will heal B, C, and D, as D has less health than A.

http://wotlk.openwow.com/spell=64843
http://www.wowhead.com/spell=64843/divine-hymn#comments

**Comment by robinsch** [comment]
Working on PTR.
