### ISSUE TITLE
[Item] Flare of the Heavens + Elemental Focus Stone + Embrace of the Spider

### ISSUE THREAD

**Issue by healmyballs** [dalaranwow/dalaran-wow#2130]
Hello, trinket Flare of the Heavens (http://www.wowhead.com/item=45518) absolutely broken for shadow priest, as well as Elemental Focus Stone (http://www.wowhead.com/item=45866), but i really care only about first one. So, after getting that item i'm just arrived to Orgrimmar dolls to check proc rate of this item. I've spent about 141 seconds before it proced first time, then, after 45 seconds GCD expire, i've spent about 120 seconds to trigger proc. Then it was two smooth procs about 45s per one, and then there was 0 procs during x2 attempts 3 minutes each. Meanwhile, i traded that item to warlock for test and he got like ~8 procs per 45 seconds (pure procs per GCD), about 4 procs per 35-40 seconds and several procs with 15-30 seconds above GCD (45 seconds) time. I've also tried trigger that proc without using MB or SW:D, but that did not even happen (and i didn't got any proc WITH using it in my last 3 min attempt as well). One mage from Nebulous with this item also told me that procs are a bit strange, but pretty stable for him. I suspect that this item is kinda broken for DoTs and channeling spells (but works pretty nice for direct spells) and beg you guys to fix that issue if possible, because that item is simply bis for every caster class, including shadow priests and its kinda unfair when one item works fine for one class (like warlock or mage) and totally broken for another one :P.
Regards.
Upd 1: Procs from [Holy Nova] damage pretty nice (like 5 procs in ~45-53s each);
Upd 2: Does not procs from [Mind Sear] or [Mind Flay] or improved DP or DoTs applying;
Upd 3: [Shadow Word : Death] and [Mind Blast] are triggering proc.

**Comment by Exorcista** [comment]
A good getaway for the trinkets mentionen avove would be Dying Curse + Curse of the Dragon Soul, or Forge Ember (http://wotlk.openwow.com/item=37660), tested this one today and it procs well as far as i can see, also Sundial of the Exiled working fine. Seems that the "Harmfull spells" are the only really bugged for Shadow Priests. This is <b>gamebreaking</b> the class, sure you can get the trinkets i mentioned here and perform well but every player aims to get the best gear possible ingame to perform the best possible.

**Comment by Exorcista** [comment]
Im bumping this to add that Forge Ember- http://wotlk.openwow.com/item=37660, is again bugged for Shadow Priest, 30 min on test and not a single proc from any source, is this under any review? you literally have to do Naxx and OS 25 every week (for how long gods know) to get Dying Curse + Dragon Soul as only working trinkets for the class, this is gamebreaking and anoying :(

**Comment by Golganeth** [comment]
#1981 - Elemental Focus Stone for rogue poisons / shadow priests.

**Comment by Rushor** [comment]
DB/Item: Flare of the Heavens + Elemental Focus Stone + Embrace of the Spider - Update spellproccflags

* closes https://github.com/dalaranwow/dalaran-wow/issues/2130
* commit: 261dd5a89813f3c4ccfe4fad21f559546cb09c94
* commit: a93fca7e63dd772ac58e4f91e0ab5afdaa922768

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
