### ISSUE TITLE
Shaman: Earthliving weapon talent - Blessing of the Eternals

### ISSUE THREAD

**Issue by Aradash** [dalaranwow/dalaran-wow#2141]
below 35% hp there should be 100% chance to trigger earthliving weapon with ANY spell or HOT - if it's not active already
this does not work at all

" Blessing of the Eternals has been changed to Increases the critical effect chance of your spells by 2/4%, and increases the chance to apply the Earthliving heal over time effect on the target by 40/80% when they are at or under 35% total health."

"Imbue the Shaman's weapon with earthen life. Increases healing done by 110 and each heal has a 20% chance to proc Earthliving on the target [...]"

**Comment by Golganeth** [comment]
Couldn't reproduce any problem despite your "this does not work at all" which isn't really accurate information by the way.

In addition:
>Together with the base 20% proc chance on Earthliving Weapon, Blessing of the Eternals gives a 100% chance for your single target direct healing spells to trigger Earthliving on targets below 35% health. Spells which innately have a lower chance to trigger Earthliving, such as  [Healing Rain] and  [Chain Heal] will have their chance to trigger Earthliving increased, but not up to 100%.

http://wow.gamepedia.com/Blessing_of_the_Eternals
