### ISSUE TITLE
Quest: Assault on The Sanctum

### ISSUE THREAD

**Issue by Esunnaxqt** [dalaranwow/dalaran-wow#2142]
Not really a bug, but this quest was introduced in patch 3.3.5 and is not completeable without access to the Ruby Sanctum.
I think it should be removed until RS is opened.

http://www.wowhead.com/quest=26012
http://www.wowhead.com/quest=26013
http://www.wowhead.com/quest=26034

**Comment by Golganeth** [comment]
The same happens with the ICC, FoS/PoS/HoR, Quel'Delar questlines (the latter can't be started though). That's something minor and not a big deal so we intend to keep them on the DB until the players are able and ready to complete them.
