### ISSUE TITLE
Trap > Feign

### ISSUE THREAD

**Issue by Esunnaxqt** [dalaranwow/dalaran-wow#2144]
Im not a hunter expert and i cant describe exactly how traps should work, hope someone else helps here.
But im sure hunters shouldnt be able to trap you instantly using Freezing Trap Arrow into Feign Death, and theres a lot of hunters already abusing that mechanic.

This bug gives hunters a big advantage in pvp.

**Comment by Uthil** [comment]
Here some info about the class skills, just to refresh skill memory, check also feign death limitations. But also you might need a screenshot or 2 for what is happening.

[url="http://wow.gamepedia.com/Freezing_Arrow"]Freezing Arrow[/url] and [url="http://wow.gamepedia.com/Feign_Death"]Feign Death[/url]

**Comment by Golganeth** [comment]
Invalid report. Please provide specific information as well as valid sources/proofs to backup the issue(s).
