### ISSUE TITLE
Vote page link opens two windows

### ISSUE THREAD

**Issue by Blangas** [dalaranwow/dalaran-wow#2148]
I don't know why, but links in vote page always opens two windows to vote.
I can guess that can make some issues because vote tracks ip (so double open from 1 ip?). In any case i think it can irritate lot of people willing to vote.

**Comment by Golganeth** [comment]
The Bug Tracker lists only in-game issues. In addition, this does not happen at all so it might be an issue with your computer or the browser settings/binds you're using.
