### ISSUE TITLE
NPC - Matis the Cruel

### ISSUE THREAD

**Issue by Uthil** [dalaranwow/dalaran-wow#2150]
I just did the [Matis the Cruel](http://wotlk.openwow.com/quest=9711) and saw that [Flare Gun](http://wotlk.openwow.com/item=24278) isn't working properly.

You summon the NPC to help you kill aka capture Matis but that NPC doesn't do anything. Normally will attack upon range of Matis the cruel and help you kill him since is an 18 level elite and hard to be killed alone.
Also the dialog upon turn in the quest also isn't working too.

WoWhead Link: [Matis the Cruel](http://www.wowhead.com/quest=9711)

WoWWiki info : [Matis the Cruel](http://www.wowwiki.com/Matis_the_Cruel)

**Comment by Golganeth** [comment]
#18
