### ISSUE TITLE
Quest : Razormaw

### ISSUE THREAD

**Issue by Uthil** [dalaranwow/dalaran-wow#2152]
I tried to do that [Razormaw](http://wotlk.openwow.com/quest=9689) quest from the chain and it seems that is broken. When you try to use [Bundle of Dragon Bones](http://wotlk.openwow.com/item=24221) on the fire it doesn't do anything. Also Razormaw isn't flying around that hill as he suppose to be.

I search also for the quest and found that is still bugged since **Feb 2014**. Guys try to fix that quest since it gives very good experience and item rewards at the end of it.

**Comment by Golganeth** [comment]
Re-check the issues before opening new ones, this is already reported. #61
