### ISSUE TITLE
Quest: Patching Up [11894]

### ISSUE THREAD

**Issue by Golganeth** [dalaranwow/dalaran-wow#2154]
You should be able to cure the hides over any of the steam vents in the Geyser Fields. Currently only one of them works (as mentioned in #295)

http://wotlk.openwow.com/quest=11894
http://wotlk.openwow.com/object=300182

**Comment by Sagrath** [comment]
Working

**Comment by Rushor** [comment]
no, not all spots are working, some spellfocusobject are missing

**Comment by Rushor** [comment]
Scripts/The Battle for the Undercity: Add some spellfocusgos for quest 'Patching Up'

* closes https://github.com/dalaranwow/dalaran-wow/issues/2154
* updates https://github.com/dalaranwow/dalaran-wow/issues/2404
* commit: cab896f5278941f321e3fb6b04070ed27de00293

**Comment by TeridanDW** [comment]
Works as intended on PTR.

Note: What does this quest has to do with The Battle for the Undercity?
