### ISSUE TITLE
Quest / NPCs: Eliminate the Competition [12955]

### ISSUE THREAD

**Issue by Golganeth** [dalaranwow/dalaran-wow#2155]
As soon as you reset any of the NPCs (going too far away or dying) their flags get stuck and players can't attack / interact with them.
Their flags should reset completely (gossip option included) when that happens. 

- [Efrem the Faithful](http://wotlk.openwow.com/npc=30081) -> ID: **30081**
- [Sigrid Iceborn](http://wotlk.openwow.com/npc=30086) -> ID: **30086**
- [Tinky Wickwhistle](http://wotlk.openwow.com/npc=30162) -> ID: **30162**
- [Onu'zun](http://wotlk.openwow.com/npc=30180) -> ID: **30180**

------------------
http://wotlk.openwow.com/quest=12955
http://wotlk.openwow.com/npc=30081
http://wotlk.openwow.com/npc=30086
http://wotlk.openwow.com/npc=30162
http://wotlk.openwow.com/npc=30180

**Comment by dragondd** [comment]
been checked at 8/9/15, still bugged

**Comment by deasease** [comment]
ye tinky bugged...

**Comment by Rushor** [comment]
set them active on gossip select

**Comment by MrAndersonX** [comment]
Confirmed - bugged. Needs a fix.

**Comment by Lothloryen** [comment]
Hello there,

This quest has been corrected and the fix should be active after the next scheduled maintenance.

Thank you.
