### ISSUE TITLE
Quest : The Hermit

### ISSUE THREAD

**Issue by Uthil** [dalaranwow/dalaran-wow#2156]
I started to do quest's in the area of Duskwood. I found that [The Hermit](http://wotlk.openwow.com/quest=165) quest was given from [Elaine Carevin](http://wotlk.openwow.com/npc=633) and not from [Commander Althea Ebonlocke](http://wotlk.openwow.com/npc=264) as it used to be.

WoWPedia Info : [Commander Althea Ebonlocke](http://wow.gamepedia.com/Commander_Althea_Ebonlocke) - [Elaine Carevin](http://wow.gamepedia.com/Elaine_Carevin).

WoWWiki Info : [Commander Althea Ebonlocke](http://www.wowwiki.com/Commander_Althea_Ebonlocke) and [Elaine Carevin](http://www.wowwiki.com/Elaine_Carevin)

[The Hermit](http://www.wowwiki.com/Quest%3AThe_Hermit) quest line in WoWWiki.

**Comment by Golganeth** [comment]
If you are going to report anything, at least take a look to the links you post. The first link clearly shows there is no issue.

As for the other links:
> Patch 4.0.3a (2010-11-23):  Added

If you don't know, I'll tell you. Dalaran-WoW is a 3.3.5 (WoTLK) server.

**Comment by Uthil** [comment]
That Quest added in 4.0.3 was about the new hermit that takes place in the tower at the border of Kharazhan, at Beggars Haunt. (http://www.wowhead.com/quest=26627). no more undead occupied the tower.

**Comment by Uthil** [comment]
Yeah you right on this one, i messed a bit, thought that was pre-cata since in cata te quest change place, it is in beggars haunt, so that might confuse me. Sorry for if did wrong, but also i know what expansion i choose to mess with, since TBC until early MoP i was online so yeah i kinda be aware that you folks are last WotLK patch and you try to make a difference from other private crap out there. Point is to make.
