### ISSUE TITLE
Death Grip in PvP

### ISSUE THREAD

**Issue by Esunnaxqt** [dalaranwow/dalaran-wow#2158]
Death Grip should have a minimum range in PvP of 8 yards, wich is not the case on Dalaran-Wow.
It gives DK's an extra interrupt in melee range wich is a significant buff.

How to reproduce: As a DK, duel another player, go to melee range and use Death Grip.

What should happen: Death grip should not go off and the player should get the error message "Target too close."

"Wrath-Logo-Small Patch 3.3.3 (2010-03-23): Minimum range has been changed to 8 yards in PvP."
- Quoted from http://www.wowwiki.com/Death_Grip

**Comment by Golganeth** [comment]
Merge with #326
