### ISSUE TITLE
Quest bug - Vent Horizon

### ISSUE THREAD

**Issue by Portotada** [dalaranwow/dalaran-wow#2161]
Quest links: http://www.wowhead.com/quest=25212/vent-horizon
                    http://www.wowwiki.com/Quest:Vent_Horizon
NPC links: http://www.wowhead.com/npc=39396/thunderflash
                  http://www.wowwiki.com/%27Thunderflash%27 <- better link
Server: Algalon
Class: Druid

Objective: Use Pilot Muzzlesprock's flying machine to toss Radiageigatrons at the vents surrounding Gnomeregan. Deploy Radiageigatron at Gnomeregan Vents (3).

Issue: When clicking on the flying machine (NPC name:Thunderflash) , it gives you the dialog option that you are supposed to click to hop in it. The issue is that clicking this option does nothing.

How it should work: Clicking on the option should embark on the flying machine, in order to continue the quest.

How it currently works: It doesnt, nothing happens when clicking the option.

P.S. I cant figure out how to label this Googled it followed the steps till there is no checkbox or whatever, my head aches now.

P.P.S Contributors only.^

**Comment by Golganeth** [comment]
Already reported. #72
