### ISSUE TITLE
[NPC] Blackrock Summoner

### ISSUE THREAD

**Issue by Uthil** [dalaranwow/dalaran-wow#2163]
The [Blackrock Summoner](http://wotlk.openwow.com/npc=4463) at Redridge Mountain's has a minion Imp. That Imp isn't attacking you if you attack the Blackrock Summoner when normally it does since its part of the npc. You have to attack it also.

The imp will attack you normally if you step near its aggro range, that also will trigger the summoner too.

Also occasionally happens that Imp instead of vanish upon killing it to give loot and the loot is some copper coins when it doesn't have loot.

**Comment by Rushor** [comment]
Game/Unit: Attackstart - Minions should now always attack the enemy

* how it is: if you attack a minion from a creature A, the minion will not attack if you attack the creature A with range attacks

* how it should be: if you attack a minion from a creature A, the minion will attack if you attack the creature A with range attacks

* commit: 1852ddbb58e79dbf6e80c87608d35d452e154f8b
