### ISSUE TITLE
Pyrewood Ambush Quest

### ISSUE THREAD

**Issue by Blangas** [dalaranwow/dalaran-wow#2169]
Pyrewood Ambush (Silverpine Forest, Pyrewood Vilage) quest not working. As i know after accepting quest there should come some npc to kill, but nothing happening. Can I (we) hope this kind of bugs will be fixed?

**Comment by Golganeth** [comment]
Yes, you can expect every single bug fixed. Only the ones that are actual bugs though.

![image](https://cloud.githubusercontent.com/assets/5057942/5686008/bea7e73a-983f-11e4-9e0b-e059f4463eb4.png)

![image](https://cloud.githubusercontent.com/assets/5057942/5685993/a052381c-983f-11e4-858e-86ca95fbdf7c.png)

Thanks!
