### ISSUE TITLE
Quest: Mimicking Nature's Call

### ISSUE THREAD

**Issue by azzco** [dalaranwow/dalaran-wow#2172]
Using the carved horn at the frozen waterfall, no matter how close you stand, gives an error messege: Requires Frozen Waterfall.
I've tried both waterfalls in the area (coords 52 4 Howling Fjord).

http://wotlk.openwow.com/quest=11281
http://wotlk.openwow.com/item=33450

**Comment by Golganeth** [comment]
False report. Works fine as long as you are on the correct spot.
