### ISSUE TITLE
I cant log in Dalaran-WoW server

### ISSUE THREAD

**Issue by Solaris83** [dalaranwow/dalaran-wow#2173]
I'm new on the server Dalaran-WoW and i can't log in cause it stops at the step "connecting". Can u help me pls?

**Comment by Golganeth** [comment]
The bug tracker is for in-game issues. Make sure that you're using the correct realmlist (which is - set realmlist logon.dalaran-server.com) and visit our [Community Support](http://www.dalaran-wow.com/forums/input-and-assistance/community-support) section of the forums, which is there to offer help regarding client downloads, installations and all kind of errors that may arise during the process to connect to our servers.

You may also find this [thread](http://www.dalaran-wow.com/forums/input-and-assistance/community-support/topic/4416/unable-to-connect) useful. Thanks.
