### ISSUE TITLE
Tabetha's assistance

### ISSUE THREAD

**Issue by Tenrazz** [dalaranwow/dalaran-wow#2176]
hey guys 
found this one pls check on in..quest:/ Tabetha's assistance  Quest giver:/Captain darill
location:/dustwallow marsh cords:/46: 24

thx vm guys
ceyas
Vorian

**Comment by Golganeth** [comment]
Please make a small research before opening new reports. The quest is obtainable as long as you have completed the prequests.

**Comment by Tenrazz** [comment]
http://www.wowhead.com/quest=27428/tabethas-assistance 
Sorry to bug m8 but i did my research this is no prequesting

**Comment by Golganeth** [comment]
If you're going to post links, at least take a closer look at them. Cataclysm isn't Wrath of the Lich King.  Thanks!
