### ISSUE TITLE
Help!!!!

### ISSUE THREAD

**Issue by Tenrazz** [dalaranwow/dalaran-wow#2177]
![tmp_22461-screenshot_2015-01-15-00-00-311246180705](https://cloud.githubusercontent.com/assets/10294936/5743225/6592039c-9c4a-11e4-8855-32db287f823a.png)
Hey guys i am a premium
And i made a ticket more than a day ago still no respones and help ..for some reason on your webpage it tells me i have no characters and i try clicking on the green tab but nothing changes i tried making a ingame ticket..cause i cant make webpage ticket 
PLSSSSSS HELP!!!!!

**Comment by Golganeth** [comment]
Invalid report. The bug tracker only lists in-game issues.

You may find #2107 useful so check that out.
