### ISSUE TITLE
NPC ability: Thrash

### ISSUE THREAD

**Issue by n-ghost** [dalaranwow/dalaran-wow#2180]
http://www.wowhead.com/spell=3391/thrash

This issue seems to be relatively new. 

Basically, this ability somehow has no maximum range requirement (and is being cast even when mob isn't in melee range). 

This makes every npc that has this ability use it at range, thus firing some random melee attacks x2 at it's target every so often, even if there is a whole Azeroth between them and the target.

Needs fixing.

**Comment by Rushor** [comment]
DB/SAI: Creatures which use the spell 'Trash' will now only use it if they are in 2 yards range to a victim

* closes https://github.com/dalaranwow/dalaran-wow/issues/2180
* commit: 2360fe0efb11c1415320916818e5cf36a2eef7d2

**Comment by Rushor** [comment]
already refixed in https://github.com/dalaranwow/dalaran-wow/issues/5357
