### ISSUE TITLE
stonetalon trash mobs are not using their skills

### ISSUE THREAD

**Issue by xerfilstyx** [dalaranwow/dalaran-wow#2181]
I can't remember the whole list of them but:

deepmoss creeper should use their poison ability
deepmoss venomous? should use their poison shot ability
but both of them are just melee-attacking only

**Comment by Rushor** [comment]
281bf5b44b962d4adcc030a0df429bcaa53ee10b
- sai added for 
SET @ENTRY := 4005; and SET @ENTRY := 4007;
