### ISSUE TITLE
[Quest] Find the Ancient Hero

### ISSUE THREAD

**Issue by keki88** [dalaranwow/dalaran-wow#2184]
http://www.wowhead.com/quest=13133/find-the-ancient-hero

Iskalder hits HUGE. Quest item doesn't work. Iskalder disappears after few seconds.
This quest needed to the Icecrown arene quest chain.

**Comment by Golganeth** [comment]
Works as intended. Read your quest log

**Comment by keki88** [comment]
Bugged like hell on Algalon, check it before you blame.
I read the quest log.
Check youtube videos.
Thanks.
