### ISSUE TITLE
Quest: Timber Worg Tails

### ISSUE THREAD

**Issue by codyflood** [dalaranwow/dalaran-wow#2185]
Timber Worgs do not drop the quest item, Timber Worg Tail.

**Comment by Golganeth** [comment]
Yes, they do.

**Comment by codyflood** [comment]
I can stream and show that they are not dropping for me. I've dropped and picked up the quest twice. They were dropping for me the first time I started the quest until I was one shy, and since when I picked up the quest a second time they have not been dropping at all (and I've killed MORE than enough to see at least one drop)
