### ISSUE TITLE
[Paladin] Sheath of Light HoT

### ISSUE THREAD

**Issue by Aegletes** [dalaranwow/dalaran-wow#2188]
The paladin talent Sheath of Light (Rank 3) ID: 53503 adds a heal over time to targets of critical heals (ID: 54203).  The issue with this HoT is that successive critical heals are not correctly summing together.

What is happening on the server: You land a critical heal and the HoT is applied to your target, but when you land a second critical heal it ignores any remaining heal amounts from the first HoT and simply overwrites the old HoT with a new one based solely on the heal amount of the most recent critical heal.

How it should work: When you land successive critical heals, it should calculate the total amount of healing left on the current HoT and add that to the amount of healing from the most recent critical heal, then apply this total over 12 seconds.

For example,
First critical lands for 6000 so 60% of that or 3600 healing is applied over 12 seconds, healing 900 every 3 seconds.  After two ticks of this HoT a second critical heal lands on the same target for another 6000.  The 1800 healing remaining from the first critical heal should be added to the 3600 healing from the second critical for 5400 total healing applied over 12 seconds, or ticking for 1350 every 3 seconds.

This is most obvious when a large critical heal like Holy Light is followed by a small flash of light critical heal.  Here you lose a significant amount of healing while on retail you did not lose any healing, it was lumped into the new HoT.

c.f., https://github.com/TrinityCore/TrinityCore/issues/3256

**Comment by zozefin** [comment]
confirmed, i crited with holy light and had a hot of 200+ (lvl50) and then i i crited with a flash of light before sheath of light ended and the hot reduced to 40

**Comment by DwowSupport** [comment]
Greetings!
As of 5.9.2015 this issue has been tested and the problem still persists.
Additional information:
The talent Righteous Vengeance (http://wotlk.openwow.com/spell=53382) uses the same mechanic as Sheath of Light (http://wotlk.openwow.com/spell=53503) ,but the first one is regarding dealing damage while the second one is for healing( both of the applies a dot/hot on the target). The interesting part is that the first one is working as intended( the dot as of 5.9.2015) while the second one is not. Hope that can be of some use to the developer.
Cheers!

**Comment by Golganeth** [comment]
It's not taking into account remaining ticks from last Sheath of Light, it stacks the whole healing for the whole duration

**Comment by Golganeth** [comment]
Nvm fixed
