### ISSUE TITLE
Quest (Outland):  The Warp Rifts

### ISSUE THREAD

**Issue by Naidira** [dalaranwow/dalaran-wow#219]
The quest "The Warp Rifts"  (http://www.wowhead.com/quest=10278) is completable but behaves oddly.  The summoned rift appears as a wraith-type mob rather than a rift and has the nametag "Void Spawner - Quest - Warp Rifts".

It will continue to churn out a new EXP granting mob every 30 seconds or so, which will pile up into a large cluster over a period of time.  Unsure of despawn time, as I found another inactive "Void Spawner" further West from another player.

![thewarprifts](https://f.cloud.github.com/assets/5104690/868516/950b5cdc-f7a9-11e2-9722-d8c378796ece.jpg)

**Comment by Rushor** [comment]
ed4f471802c9523dda72dc5ec091a8dcb40f381f
- only one spawn after use of the item
- the strange name should no longer be displayed
- removed the wrong modelid of the creature

**Comment by Golganeth** [comment]
Only one spawn is kind of a hassle at the moment, considering the quest item has 2 min cooldown. The Unstable Warp that the item creates doesn't seem to despawn after a while.

Despite that works fine, but it takes too long (6 mins) to complete, so needs an improvement

**Comment by Rushor** [comment]
51a8693274e0a156bc3cee9ea4ea51f657942dfe
- ok then, the triggercreature will spawn every 30 seconds a new attackable creature
- the triggercreature will despawn after 120000 milliseconds
