### ISSUE TITLE
[Quest] Timbermaw Hold reputation

### ISSUE THREAD

**Issue by AppleCake** [dalaranwow/dalaran-wow#2190]
Hey, the repeatable quests at Timbermaw Hold gives 75 reputation, when it's supposed to give out 300 after patch 3.0.2. This server is at 3.3.5, right? In any case, I made a ticket about it and GM Eonahr or something like that sent me here. Hope you can fix it, and thanks for your work!

**Comment by Dasher2417** [comment]
Confirmed. Both feather NPCs, and beads one, give only 75 rep for each quest. Even if we were at patch 3.0.1, the reputation should be at least 150 per quest. At the moment, it's on Vanilla standards.

**Comment by Rushor** [comment]
DB/Quest: Timbermaw Hold - Increase reputation for repeatable quest to 300

* also add waypoints for creatureguid: 39359 in Timbermaw Hold 
* closes https://github.com/dalaranwow/dalaran-wow/issues/2190
* commit: 8b003c8f88d3c127070068e8354899143e707332
