### ISSUE TITLE
Death and Decay threat

### ISSUE THREAD

**Issue by LiNK2088** [dalaranwow/dalaran-wow#2195]
Death and Decay should produce a high amount of threat, like the tooltip says.
However it currently does barely any threat, even in frost presence.
This makes it very hard for DKs to properly aoe tank.

**Comment by willardnigma** [comment]
It pulls a high amount of threat initially, but the actual amount of threat it pulls will vary.  DnD's damage scales off spell damage, which is limited in blood/frost specs.  It's designed as an initial pull, and further multi target tanking is meant to be done via various other abilities.   It's only meant to be viably mid pull for unholy spec, so could you provide more info such as the TPS calculation from omen, along with a screenshot of your talents, a list of your gear and any procs and buffs you may have at the time.

**Comment by Golganeth** [comment]
Works fine. You can't expect to hold aggro for a long time by using just one spell. Closing up until valid proof to support the statement is given.
