### ISSUE TITLE
[Item] Parachute Cloak

### ISSUE THREAD

**Issue by Kiwago** [dalaranwow/dalaran-wow#2200]
The engineering profession cloak enchant "Parachute Cloak" currently has a peculiar bug associated with it. Using the cloak right as you hit the ground will trigger the bug, it will cause client side slow fall until the parachute cloak is activated then deactivated. On the server side it, it looks very different, it looks like your falling fast repeatedly. You still take fall damage. This bug was discovered with frequent use of the cloak in combination with disengage.

**Comment by Vaxsysl** [comment]
Confirmed, I got the bug on my warrior when I was jumping down from emblem vendors. I would still be slow falling in visual to everyone, including me, but on landing I still take full fall damage.

**Comment by Kiwago** [comment]
It appears that you fall slow visually for your game client. For the rest of the server, you fall rapidly many times in place until you reach the ground.

**Comment by AraelWindwings** [comment]
Once I was flying with my mount, I was going down to reach the ground, I dismounted just half second before touch the terrain... I had 100% HP Damage from falling...

I was about 5 yards high...

**Comment by Vaxsysl** [comment]
That's different. There's a bug when you log out unexpectedly or zone out while mounted - the height you were when that happened is your "ground" and everything below that is fall damage. Or it's fall damage in any case, I'm not sure, I never tested zoning out somewhere to test the logic behind it.

In any case, you won't die if you land with your mount and dismount while still.

**Comment by Rushor** [comment]
cannot confirm this n PTR anymore.
