### ISSUE TITLE
Amaner Berserker (Eversong Woods) damage while enraged

### ISSUE THREAD

**Issue by ashido96** [dalaranwow/dalaran-wow#2202]
http://www.wowhead.com/npc=15643/amani-berserker

Deals 8-9 damage while un-enraged, when he becomes enraged (buff says 60% bonus damage) he deals 40-45 instead.

**Comment by n-ghost** [comment]
Works as intended, tooltip might be bugged though.

**Comment by Golganeth** [comment]
According to [Wowhead comments](http://www.wowhead.com/npc=15643/amani-berserker#comments), it seems to work as intended. Closing up until strong evidences are given to support the report..
