### ISSUE TITLE
Mail

### ISSUE THREAD

**Issue by daibheid** [dalaranwow/dalaran-wow#2203]
"You have reached the in-game cap of unique mail recipients"

I've sent mail to at most 6 characters.  I never saw this message in retail, and can't imagine that it is working correctly.

**Comment by Rathyan** [comment]
It means that the person you're trying to send a mail has their mailbox full. Not  a bug

**Comment by Golganeth** [comment]
> Rathyan:
It means that the person you're trying to send a mail has their mailbox full. Not a bug

That, or you've reached the cap of X number of letters sent in Y amount of time. Once that resets or as players take the mail you sent out of their mailbox, you should be fine.

Not a bug so closing up.
