### ISSUE TITLE
[TBC] [Karazhan] [Boss] [Attument the Hunstman]

### ISSUE THREAD

**Issue by Warthug** [dalaranwow/dalaran-wow#2204]
What's the issue?
https://www.youtube.com/watch?v=5pYuuq0B2Ig

Excessive damage from his Shadow Cleave, i'm gettin crits for 15k, 17k, and more than 20k sometimes, with blood tank spec and tank gear.

http://www.wowhead.com/spell=29832/shadow-cleave

How should it work?

You should be able to safely solo him on tank gear at least.

This is what i personally experimented with him.

1) When attumen mount up Midnight, the same excesive damage persist

2) I'm was using Sigil of the Unfaltering Knight http://www.wowwiki.com/Sigil_of_the_Unfaltering_Knight that's why my defense rating went from 563 to 574

3) i was using a Indestructible Potion http://www.wowwiki.com/Indestructible_Potion

4) All my tank gear was properly enchanted same as the weapon i used with the Death knight tank enchant (Rune of Stoneskin gargoyle)

5) Before the video i attempted full buffed "priest/paladin/druid" having the same result as you can see in the video.

Videos from Attumen the Huntsman during Wotlk retail

https://www.youtube.com/watch?v=CZYWG01VUMI

https://www.youtube.com/watch?v=3pc2g8b-Zzc

https://www.youtube.com/watch?v=yM9KXxVArgI

Sources 

http://wowpedia.org/Attumen_the_Huntsman

http://www.wowwiki.com/Attumen_the_Huntsman

http://www.wowhead.com/npc=16152/attumen-the-huntsman

P.S Already tried with unholy spec (bone shield) it doesn't help much either

**Comment by Golganeth** [comment]
Confirmed. Going to merge this with #2000

**Comment by bucovsky** [comment]
Any update on this issue? Attumen is still hitting for 16k, even though my prot paladin is quite well geared.
