### ISSUE TITLE
Borean Tundra bugged quests(?)

### ISSUE THREAD

**Issue by Chazeka** [dalaranwow/dalaran-wow#2205]
First quest: Taken by the Scourge - Here you are supposed to free webbed peons. First issue is that the respawn timer for these webs seems to be extremely long. The second issue is that alot of times I'll destroy a web and theres nothing in there at all. No peons nor any other npc/mob. I had to give up on this quest.

Second quest: Get to Getry - Afaik, Getry is supposed to stand up at the watch tower, however, he is standing down by the fields and I am unable to turn in this quest and start the escort quest. I have tried waiting for 15 minutes, but nothing changes.

**Comment by Golganeth** [comment]
Please recheck the current reports before opening new ones. Duplicated; #1627 and #1341
