### ISSUE TITLE
RaF Level Granting

### ISSUE THREAD

**Issue by willardnigma** [dalaranwow/dalaran-wow#2206]
The ability to grant levels is showing gray when attempting to use it.
http://i.imgur.com/sBO2TJ4.jpg

On the site, it is stating the level granting as a benefit of the RaF

Blizzlike implementation of this feature has it working as described below

Level Granting

For every two levels your friend gains while the accounts are linked, they can grant one level to one of your characters. Your friend must log in to the character with grantable levels, right-click on your character's portrait, and select Grant A Level. The Grant A Level menu item will only appear when:

The characters are in a party on the same realm and faction.
The characters are within 100 yards of each other.
The character granting the level is higher level than the character receiving the level.
The character receiving the level is level 84 or lower.  (79 for WOTLK)
The character receiving the level has not disabled experience gain.
Only levels earned through normal gameplay count for grantable levels. Levels earned through Character Boost do not apply.
Note: Unclaimed levels are not moved during a character copy or transfer. Be sure to use them before you transfer.

Source  https://us.battle.net/support/en/article/recruit-a-friend

**Comment by Lothloryen** [comment]
Hello there,

Thank you for your report. However the only person who is allowed to perform the grant a level, is the recruited to the recruiter as states the Blizzlike standards regarding the Recruit a friend feature. If it is not your case, please write an ingame ticket and a Game Master shall check if you are proprely linked.

http://www.dalaran-wow.com/forums/news-and-rules/rules-and-guidelines/topic/2565/how-to-use-the-recruit-a-friend

**Comment by Golganeth** [comment]
Closing up.

**Comment by willardnigma** [comment]
I am the recruiter , and our accounts are linked.  I invited my friend to the server via the RaF feature, and she did sign up via the link.  All of the conditions requiring the use of the feature were met.

**Comment by Lothloryen** [comment]
Hello there, 

Your friend must grant you level, the recruited can grant level the recruiter.
