### ISSUE TITLE
Deterrence and time travel

### ISSUE THREAD

**Issue by Kiwago** [dalaranwow/dalaran-wow#2208]
The hunter spell "Deterrence" will not stop travel time crowd controls, ranged attacks or mid air spells if they are launched before the hunter activates deterrence. Currently they will only stop attacks, or spells if they are cast after the hunter has applied deterrence. This feature makes the spell more obsolete in pvp and arena. I understand that this is a core issue however I have a possible solution to this problem. Perhaps you could have the system detect deterrence. If deterrence is active at the time, then the spell will simply miss, instead apply the spell effect.

**Comment by Esunnaxqt** [comment]
I dont know about deterrence, but cloak of shadows cant block spells if they were already flying and that is blizzlike.

Can you provide some source about deterrence?

**Comment by moliskrc** [comment]
Only spells like Divine Shield and Iceblock work like that. Unfortunately Deterrence doesnt stop missiles that are already flying to hit the hunter. You can also test it in arenatournament - works the same (btw they have flawless class skill scripts and mechanics).

**Comment by Vaxsysl** [comment]
Moliskrc, warriors' shield block works like that too.
Logically it makes no sense, its like raising your shield and not blocking an arrow because it was in air, no matter the shield is up at the time, the arrow passes through the shield? No sense at all.

**Comment by Kiwago** [comment]
Please don't derail this issue

**Comment by Kiwago** [comment]
Spent time sifting through old reports about the spell "Deterrence." I've come to the conclusion that it won't always stop time travel spells and that it is currently working as intended.
