### ISSUE TITLE
Stampede (rhino)

### ISSUE THREAD

**Issue by Kiwago** [dalaranwow/dalaran-wow#2209]
The Rhino's unique ability "Stampede" applies the increased bleed damage debuff in addition to knocking the enemy backwards. It does not currently knock the enemy back on Dalaran.
http://us.battle.net/wow/en/game/patch-notes/3-0-0

**Comment by Rushor** [comment]
duplicate https://github.com/dalaranwow/dalaran-wow/issues/2058
