### ISSUE TITLE
Spiritual Attunement

### ISSUE THREAD

**Issue by daibheid** [dalaranwow/dalaran-wow#2210]
Not sure how you can say that it isn't broken.  Clearly in the two screenshots you can see I am not at full mana or health, and it doesn't proc at all on a large heal, when by talent/glyph I am supposed to be getting 12% back.

I promise it is not working, I played a prot pally from BC release to the end of cata.
![pally1](https://cloud.githubusercontent.com/assets/10663372/5991086/89f03810-a9a3-11e4-8697-323fe13e2b36.png)
![pally2](https://cloud.githubusercontent.com/assets/10663372/5991087/89f07dca-a9a3-11e4-96b4-1a2dc7471452.png)

**Comment by Golganeth** [comment]
- 3282 (2581 Overhealed) -> 701 effective heal points.
- 12% of 701 <-> 0,12 * 701 = **84,12** mana points gained

According to that screenshot you got 124 mana (I assume it's the **84,12** + normal mana regen)

Tested once again at different levels with different spells to no avail. Closing up

**Comment by daibheid** [comment]
It was a critical heal.  First screenshot 4126 health, second 7476.  3282 heal, Further, when spiritual atunement does work, as shown in the first post from last week, it shows up in the combat log.  This heal gave me 0 mana from spiritual attunement.
