### ISSUE TITLE
[Death Knight] Gargoyle - Wrong damage+behavior

### ISSUE THREAD

**Issue by AraelWindwings** [dalaranwow/dalaran-wow#2213]
Spell: http://www.wowhead.com/spell=49206/summon-gargoyle
NPC: http://www.wowhead.com/npc=27829/ebon-gargoyle

Gargoyle Damage should be:
0.333 Death knight AP (with Impurity 0/5) + 120 (Base damage).
0.400 Death knight AP (with Impurity 5/5) + 120 (Base damage).

Detailed formula:
120 + (0.333 \* Attack Power \* Impurity)

Note: the Gargoyle Damage should be affected by Orc Racial Command.

With 2021 AP and Impurity 5/5:
Gargoyle currently deal 709 Damage (Unknown math)
Gargoyle should deal 928 damage = ((2021*0.4) + 120)

With 4527 AP and Impurity 5/5:
Gargoyle currently deal 1433 Damage (Unknown math)
Gargoyle should deal 1930 damage = ((4527 *0.4) + 120)

http://www.wowhead.com/spell=49206/summon-gargoyle#comments:id=760212

I find this a quite important issue that shouldn't take much to fix.

**Comment by AraelWindwings** [comment]
Made several updates.

**Comment by AraelWindwings** [comment]
Added more tests.

Making some researches, I found out it should be needed to change a value inside the DB.

It shouldn't be so hard...

**Comment by Golganeth** [comment]
Confirmed. Also the gargoyle doesn't obey /petattack orders to change target once summoned. Gargoyle should descend from the sky but it just appears on the ground.

**Comment by robinsch** [comment]
On PTR.

**Comment by Rushor** [comment]
Core/Spell: Implement Impurity and Gargoyle Impurity scaling

Issue: https://github.com/dalaranwow/dalaran-wow/issues/2213
commit: c3b119757bc58ed06690736b13b71937b5522dc4

**Comment by TeridanDW** [comment]
Works as intended on ptr.
