### ISSUE TITLE
Some of pvp bugs that i had noticed that far.

### ISSUE THREAD

**Issue by Riddix91** [dalaranwow/dalaran-wow#2216]
1)Hunters are able to do Deterrence while they are disarmed.
2)Not sure about this, but prists still can use Dispersion while Vampiric Touch or Mind Blast is bashed(shadow spells locked).
3)Intimidating Shout gets breaked by dots if dmg is absorbed(not sure about this).
4)Charge or Intercep on Deterrenced Hunter will totally waste cd, because warrior will stand in the same possition and stun will be defflected(as far as i know, it should atleast charge next to Hunter).
5)Noticed only today and i didnt tested it yet properly, but players can dodge attacks from behind.
6)Something is wrong with fear for sure. Not sure if it is with all fear effects, but sometimes fear instantly drops like 40 or more yards away from place where was before feared.

**Comment by Golganeth** [comment]
Most of the issues are already reported, re-check the current reports before opening new ones. The other ones are either false or invalid.

Open separated reports for each of the issues unless they are somewhat related to each other.

Thanks!
