### ISSUE TITLE
AI: no leash reset on non-active damage

### ISSUE THREAD

**Issue by daxpedda** [dalaranwow/dalaran-wow#2217]
<ul>
<li>
<b>Issue Present:</b> Damage with buffs like <a href="http://wowhead.com/spell=8990">Retribution Aura</a>, <a href="http://wowhead.com/spell=66068">Thorns</a> or <a href="http://wowhead.com/spell=36907">Fire Shield</a> reset the leash range of mobs, resulting in them chasing you forever. I uploaded a <a href="https://youtube.com/watch?v=JrEdajZJVLQ">video</a> showing the problem.
</li>
<hr></hr>
<li>
<b>How it should work:</b> Abilites that do not "active" damage on mobs should not reset the leash range, resulting in them dropping aggro and returning to their spawn points.
</li>
<hr></hr>
<li>
<b>Proof:</b> The only hint I could find about this problem is on <a href="http://wowwiki.com/Talk:Thorns">wowwiki</a> and <a href="http://wowhead.com/forums&topic=130050/bug-mobs-do-not-drop-agro#p1574659">wowhead</a>. I could not find any video proving the issue.
</li>
<hr></hr>
<li>
<b>Similar Issues:</b> #1477, #1.
</li>
</ul>

**Comment by Golganeth** [comment]
Merging with #682
