### ISSUE TITLE
[Death Knight] Icy Talons and Improved Icy Talons stacking togheter

### ISSUE THREAD

**Issue by AraelWindwings** [dalaranwow/dalaran-wow#2218]
Those two talents actually stack with each other.

They SHOULD NOT.

Once you take Improved Icy Talons, the effect of Icy talons should not affect the DK anymore.

Basically improved Icy Talons adds only 5% attack speed, now it adds 25% instead.

This issue allow frost builds to have insane attack speed and insane DPS.

**Comment by ntt1** [comment]
This is 3.3.5, they are supposed to stack.  Here's an article at 2.01.2010, stating the following: 
In 3.33 the stacking has changed , so your IIT and your personal melee haste stack, giving 45% haste. More commentary in my 3.33 post.
http://pwnwear.com/2010/01/02/on-improved-icy-talons-melee-haste-buff
Case closed.

**Comment by AraelWindwings** [comment]
Patch 3.3.3 (2010-03-23): The personal haste benefit provided by this talent is no longer exclusive with other sources of melee haste. This will allow death knights to always swing 4/6/12/16/20% faster when Frost Fever is applied. Windfury Totem and the party/raid component of Improved Icy Talons still do not stack.

Making some searches It seems I remembered wrong, the original issue was not the IIT and IT but IIT and WF.
