### ISSUE TITLE
Warrior Charge/Intercept bug

### ISSUE THREAD

**Issue by Riddix91** [dalaranwow/dalaran-wow#2219]
From Wowwiki:

Charge is a core warrior ability learned at level three. It is considered the opening skill. Charge rapidly moves the warrior towards a target, stuns it, and generates rage. It cannot be used during combat and has to be used as an opener. This is useful in duels against casters and ranged classes, as the distance is covered almost instantly.

Now the thing i dont like. When warrior casts Charge/Intercept on Hunter with Deterrence, Hunter will defflect all of Charge/Intercept. Stun and rapidly move. I am sure it shouldnt work like that. I agree about stun effect, but nothing else should be defflected as far as i know.

Last time when i putted threat about bugs, it was closed as explanation: Some issues are already reported, re-check the current reports before opening new ones. The rest are either false or invalid.
I scrolled all pages about this bug and i didnt saw any threat about this and one more for sure. Maybe i missed it - i dont know.
Hopefully this will be fixed. It doesnt give huge, but still gives advantage for Hunters in pvp against Warriors.

Thank you !

**Comment by Golganeth** [comment]
This is already reported. It's not an issue with warriors but with Deterrence itself (see #1572 26th Oct comment). Thanks for the report though!
