### ISSUE TITLE
NPC:  Bleeding Hollow Tormentor

### ISSUE THREAD

**Issue by Naidira** [dalaranwow/dalaran-wow#222]
Bleeding Hollow Tormentor (http://www.wowhead.com/npc=19424) demonstrates minor bugs.

- Barely casts Fear, after ~40 encounters. When it does it casts it sometimes on themselves instead of target.

- When dismounting to attack players, NPC will summon a Riding Worg attack pet (http://www.wowhead.com/npc=19640).  If the NPC is leashed back to passive without killing the Riding Worg, it will re-mount without dismissing the Riding Worg.  The next time it dismounts to attack, it will summon yet another Riding Worg.  This can be repeated indefinitely to produce more Riding Worgs.

**Comment by Rushor** [comment]
```sql
-- 
-- Bleeding Hollow Tormentor SAI
SET @ENTRY := 19424;
UPDATE `creature_template` SET `AIName`="SmartAI" WHERE `entry`=@ENTRY;
DELETE FROM `smart_scripts` WHERE `entryorguid`=@ENTRY AND `source_type`=0;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(@ENTRY,0,0,0,0,0,100,1,5000,5000,10000,10000,11,12542,0,0,0,0,0,2,0,0,0,0,0,0,0,"Bleeding Hollow Tormentor - In Combat - Cast 'Fear' (No Repeat)"),
(@ENTRY,0,1,0,0,0,100,1,0,0,3000,3000,11,34368,0,0,0,0,0,1,0,0,0,0,0,0,0,"Bleeding Hollow Tormentor - In Combat - Cast 'Summon Riding Worg' (No Repeat)"),
(@ENTRY,0,2,0,2,0,100,1,0,15,0,0,11,31553,0,0,0,0,0,2,0,0,0,0,0,0,0,"Bleeding Hollow Tormentor - Between 0-15% Health - Cast 'Hamstring' (No Repeat)"),
(@ENTRY,0,3,0,2,0,100,1,0,15,0,0,25,0,0,0,0,0,0,1,0,0,0,0,0,0,0,"Bleeding Hollow Tormentor - Between 0-15% Health - Flee For Assist (No Repeat)");

DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId`=22 AND `SourceGroup`=19424 AND `SourceEntry`=2;
INSERT INTO `conditions` (`SourceTypeOrReferenceId`,`SourceGroup`,`SourceEntry`,`SourceId`,`ElseGroup`,`ConditionTypeOrReference`,`ConditionTarget`,`ConditionValue1`,`ConditionValue2`,`ConditionValue3`,`ErrorTextId`,`ScriptName`,`Comment`, `NegativeCondition`) VALUES
(22,19424,2,0,0,29,1,19640,10,0,0,"","", 1);
```

**Comment by Rushor** [comment]
342b47d6b841daa5b4da243836b06ce2f0dfd66c
- Bleeding Hollow Tormentor will now cats the fear on enemies (f.ex the player)
- the summoned Riding Worg will instantly despawn once he evades (i think thats the best solution in order to prevent the massive spawn)

**Comment by Golganeth** [comment]
Fear works fine, however most of them aren't mounted in a Worg nor summon one.

**Comment by Aridam** [comment]
Once they use the Ability to summon the Worg as they dismount to engage in Combat, the summoned Worg immediately despawns.

**Comment by Aridam** [comment]
Reconfirming the summoned Worg still disappears when it gets summoned as the Tormentor dismounts.
