### ISSUE TITLE
[Priest] Borrowed Time

### ISSUE THREAD

**Issue by Kumanix** [dalaranwow/dalaran-wow#2222]
"Grants 25% spell haste for your next spell after casting Power Word: Shield".
After getting the buff, using Penance might not consume the proc (the increased spell haste is applied), making it possible to use another spell with 25% extra haste during the 4 second duration.

![](http://puu.sh/fybp9/2dbf0d6ec6.jpg)

**Comment by jardacle** [comment]
As far as I know it was the same on retail.

**Comment by Golganeth** [comment]
This is intended. Closing up
