### ISSUE TITLE
Warrior Poleaxe Spec Error

### ISSUE THREAD

**Issue by SgtButtermilk** [dalaranwow/dalaran-wow#2223]
Warrior's speccing into the Arm's tree can't take advantage of Polearm weapons.  The Poleaxe Specialization talent in the tree doesn't give the extra 5% crit for the polearms, which removes a large portion of weapons that for Arm's, are actually very useful.

**Comment by robinsch** [comment]
Working fine.

EquippedItemClass = 2 (WEAPON)
SubClass mask 0x00000043 (AXE, AXE2, POLEARM)
