### ISSUE TITLE
[Mechanic] Disarm + Death Grip on Bosses

### ISSUE THREAD

**Issue by Nikvet** [dalaranwow/dalaran-wow#2224]
I noticed that disarm can be used on bosses.All dungeon bosses should be immune to Disarm.Same for Death Grip.
I saw disarming on Grand Magus Telestra.Also I saw Prince Taldaram can be Death Gripped and I think other bosses can also be gripped.They should be immune to these effects.

**Comment by Rushor** [comment]
DB/Creature: Apply immunities for several dungeon bosses

* closes https://github.com/dalaranwow/dalaran-wow/issues/2224
* commit 9cfc0cf53788f42f934afabb94737108c940e3a7
