### ISSUE TITLE
Quest: The Fare of Lar'korwi

### ISSUE THREAD

**Issue by Hellfingers** [dalaranwow/dalaran-wow#2228]
You can't loot Piece of Threshadon Carcass from the carcass

Quest: http://www.wowhead.com/quest=4290/the-fare-of-larkorwi
Carcass: http://www.wowhead.com/object=166863/fresh-threshadon-carcass

![wowscrnshot_020715_211156](https://cloud.githubusercontent.com/assets/10686355/6094001/f870199e-af0d-11e4-8ec3-2ff2da6ebbf2.jpg)

**Comment by n-ghost** [comment]
Works, this is a more of a general issue related to looting.

Another example is here: https://github.com/dalaranwow/dalaran-wow/issues/2016

The quest item will be in place after the next server reset and usually respawns as it should.

**Comment by Golganeth** [comment]
Retake the quest and try to stand closer when looting it. I've just tested it and works fine.
