### ISSUE TITLE
Quest: The Summoning

### ISSUE THREAD

**Issue by Vaxsysl** [dalaranwow/dalaran-wow#223]
After doing the quest "Cyclonian" we get "The Summoning" quest. The problem is that Bath'ran is not summoning the Cyclonian. He walks to the summoning location, and doesn't summon, instantly re-tracks back to his original position.

**Comment by Rushor** [comment]
fixed long time ago in https://github.com/TrinityCore/TrinityCore/commit/5c95431df2e68e79b21ec0d74260555a0114b212
