### ISSUE TITLE
[Minor Bug] Quest: King of the Foulweald [6621]

### ISSUE THREAD

**Issue by ashido96** [dalaranwow/dalaran-wow#2234]
All of the monsters spawned by the totem don't run toward you, so you have to run around the area killing everything to get the main quest guy to spawn instead of having to "defend" the totem. Fully completable, just very annoying and had to retry like 3 times because i didn't kill certain monsters in time.

http://www.wowhead.com/quest=6621/king-of-the-foulweald

**Comment by Demlock** [comment]
Confirmed. It is annoying up to a degree but just a minor bug...

**Comment by crborga** [comment]
Quest is still bugged as of July 4th, 2015. Workaround is to kill mobs that spawn around the mound until boss spawns. Attack them all until he spawns then kill him.

**Comment by Daveonx** [comment]
Tested and currently working correctly.
