### ISSUE TITLE
Being in combat after clearly leaving combat.

### ISSUE THREAD

**Issue by Watterx** [dalaranwow/dalaran-wow#2236]
I have seen none reported this yet.

This is a very annoying bug which is pretty common on every server. But in this server it seems to happen almost 80% of the time after you "leave combat", you remain in it, being impossible to mount or drink. I believe it's part of the aggro problem, since it has a very strange behavior most of the times.

It happened even in dungeon, I couldn't drink the entire dung because of that.

The "temporal solution to this" is to kill yourself or use hearthstone.

**Comment by Zibathy** [comment]
This is a real drag. I never really thought of reporting it cause it just... happens so often and idek if a fix is realistic. But yeah I have to quit my game every now and again. It's part of the NPC supposed to evade/reset after like 10 seconds of being unable to attack its target. That's nonexistent on the server currently. In a way this has been reported already cause of the evade issue being reported but yeah, not really for this reason though (last I checked).

**Comment by n-ghost** [comment]
https://github.com/dalaranwow/dalaran-wow/issues/1954

Let's pray and hope, I guess.

**Comment by Golganeth** [comment]
Already reported. More of a general issue rather than an aggro reset problem. It does happen sometimes but not 80% of the time.

It can also be sorted out by using key spells (vanish, invisibility, shadowmeld...) or by force closing your game client.
