### ISSUE TITLE
Quest: Natural Remedies [#10351]

### ISSUE THREAD

**Issue by Zeilze** [dalaranwow/dalaran-wow#2237]
Quest: Natural Remedies [#10351]

Quest giver: Earthbinder Galandria Nightbreeze [#19294]
Quest mob: Goliathon [#19305]

Natural Remedies is a group quest in Hellfire Peninsula where the quest giver provides an item called "Seed of Revitalization" [#29478] to summon and kill Goliathon, a level 63 elite (coordinates are 13,39).

The problem arises that there are DOZENS of Goliathon currently stacked on that exact location - likely a result of of aggregated failed attempts by other players that summoned, but were unable to kill him. Pulling the singular quest mob is impossible, and initiating combat against dozens of these elite mobs resulted in them killing a lv 62 Druid in Dire Bear form in under 1 second of first blow. 

What should happen is that Goliathon should disappear after a certain amount of time, NOT remain on the spawn location indefinitely.

I request this be changed as such, or at the very least a GM go to that co-ordinate and clear out the Goliathon's currently on that location.

Thank you!

**Comment by Zeilze** [comment]
Wowhead link: http://www.wowhead.com/quest=10351/natural-remedies

**Comment by Zeilze** [comment]
The Goliathon have all been removed, making the quest doable now. Thank you

**Comment by Golganeth** [comment]
Yes, already reported on #758 though.
