### ISSUE TITLE
Glowing Blood debuff bug

### ISSUE THREAD

**Issue by Arrenton** [dalaranwow/dalaran-wow#2238]
The Glowing Blood debuff from Umbraglow Stingers in Zangarmarsh is supposed to prevent you from using stealth/invisible. But I was able to use prowl as a druid while I had it. 
I have no idea if the other wasp blood debuffs in Zangarmarsh have the same bug or not.

**Comment by n-ghost** [comment]
They do.

https://github.com/dalaranwow/dalaran-wow/issues/414

Also applies to that disease on rogue quest that's presumably should prevent them from stealth.

**Comment by Golganeth** [comment]
Duplicate of #414
