### ISSUE TITLE
Battle ground finder is gliched

### ISSUE THREAD

**Issue by natrixas** [dalaranwow/dalaran-wow#2239]
We were trying join arathi basin for pity the fool achie, but it seems that specific bg only works if all players joins same one. And it is not mixing with random bg joined players. In other words if u join specific bg u need find more 7 players in both sides in order to enter there. And it should mix like random dungeon does.

**Comment by Golganeth** [comment]
If you are queued for X specific battleground, and then random battleground pops, you will get in if random = X, not the other way around. Read about the workings of the feature before stating it as glitched.

**Comment by natrixas** [comment]
I understand how should it work, may be that was 2 specifics cases, but I
want to report that:
We was qued to specific battleground x =(arathi basin) ;
random battleground poped random = arathi basin (so random = x),
Result = we don't got in.
 after we qued to random battleground,
Result = we got to arathi basin (which started before and we do not poped
in while we was qued to it as specific).
 And same situation was 2 times for us. Thats why I am reporting it as
gliched.
Thank you.

2015-02-12 15:23 GMT+02:00 Golganeth <notifications@github.com>:
