### ISSUE TITLE
Felhunter (warlock minion) autocast bug

### ISSUE THREAD

**Issue by JinKhanzo** [dalaranwow/dalaran-wow#2240]
Anytime i summon my felhunter i go to check my spellbook under demon and there are the felhunters abilities, shadowbite and fel intelligence i want it on autocast but devour magic and spell lock i don't want it on autocast, well i right click those two (spell lock and devour magic) directly in the spellbook so that they do not remain set as autocast, i mount then i dismount check my spellbook and the abilities are on autocast again, i right click them again, remove those on felhunters ability bar and replace them with those not set to autocast, then i mount, dismount again and the same problem happens, i tried to delete cache folder and WTF folder, i tried deactivating all my addons, i tried deleting all my addons, the same problem happens, pls do something about this because it's impossible to play arenas and pvp in general for lock with this problem, i asked around a few lock have this bug too. PLS DO SOMETHING ABOUT IT

**Comment by Golganeth** [comment]
#1021
