### ISSUE TITLE
Shadowfang Keep bug

### ISSUE THREAD

**Issue by ladyriona** [dalaranwow/dalaran-wow#2241]
Just tried to run SFK with level 20 group, and the Apothecary Trio were present in the low level dungeon.  Screenshots are upcoming.

**Comment by ladyriona** [comment]
Here's a screenshot our healer took: http://i.imgur.com/EbOmqQT.jpg

**Comment by Golganeth** [comment]
This will get fixed when event ends (16th). Closing up
