### ISSUE TITLE
[Core/System][NPC] Mob corpses dissapearing too fast !

### ISSUE THREAD

**Issue by Martoff** [dalaranwow/dalaran-wow#2243]
Well, the title says it all.
I have noticed that they disappear in under a minute, usually the looted corpses should last around 2 minutes and  uninspected  for 5 minutes.

**Comment by Zibathy** [comment]
I've lost epics because of this. I have to stop mid combat to loot because of how ridiculous it is. You can't kill more than 5 enemies at once because they start to despawn before you can finish them all off and loot the corpses.

**Comment by Golganeth** [comment]
Duplicate of #971
