### ISSUE TITLE
Core Hound pup not available to all characters

### ISSUE THREAD

**Issue by bobrandon** [dalaranwow/dalaran-wow#2244]
Donated to server and core hound pup not available on Main Realm (Algalon)  because the account doesn't even register a character on that server I had to make a character on the other server just to have a forum account and such please fix.

**Comment by Golganeth** [comment]
Invalid report. The bug tracker is for in-game issues with npc's, quests, gobjects and such. If you donated and you want your Core Hound Pup, make an in-game ticket.

Feel free to check out the forums for more info, the sync of Algalon with the website is underway.
