### ISSUE TITLE
Quest: Mustering the Reds

### ISSUE THREAD

**Issue by taralej90** [dalaranwow/dalaran-wow#2251]
In this quest Keristrasza asks you to take her back to Raelorasz. At this point you stand on a floating platform some 500 yards in the sky. When you accept the quest, a dialog becomes available on Keristrasza which teleports both of you instantly at Raelorasz.

This dialog is missing, so players without fly mounts only have one option - jump. Jump to their deaths and hope not to hit another of the platforms below.

Quest link: http://www.wowhead.com/quest=11967/mustering-the-reds

**Comment by Lothloryen** [comment]
Hello there,

Already working, use the Augmented arcane prison to summon Keristrasza and talk to her right after kill Saragosa, she will teleport you back to the Transitus Shield.

Thank you for the report.
