### ISSUE TITLE
Quest: Return My Remains missing finale script

### ISSUE THREAD

**Issue by taralej90** [dalaranwow/dalaran-wow#2255]
After you free Farseer Grimwalker's spirit, he asks you to take his remains back to Bor'gorok Outpost. Upon quest delivery Spirit Talker Snarlfang says in the Completion dialogue:

"Thank you for freeing his spirit from Kaganishu and returning with his remains. We have little to reward you with, but you may take whatever catches your eye.

And now, I will return him to the living where he belongs."

After this she should resurrect him, but this script is missing so nothing happens and... yeah, he pretty much stays a very dead pile of tauren bones.

Quest link: http://www.wowhead.com/quest=11638/return-my-remains

**Comment by Zibathy** [comment]
"... yeah, he pretty much stays a very dead pile of tauren bones" lmao

**Comment by jonanone** [comment]
Missing event has been added.

This update will be applied to the live realm soon.
