### ISSUE TITLE
Mage Arcane Talent - Magic Absorption

### ISSUE THREAD

**Issue by patrickebates** [dalaranwow/dalaran-wow#2256]
At two points this talent should be providing 1 to all resistances per level, but it seems to be providing slightly less than one.  At Lvl 16 it provided 15 resist all.  At Lvl 22 it provided 19 resist all.

As you can see, the variance is growing as level increases.

Thanks.

**Comment by Golganeth** [comment]
On level 80 it grants you 79 resist since you level-up 79 times, so it seems to work just fine.
