### ISSUE TITLE
[Death Knight] Death and Decay does not produce enough threat.

### ISSUE THREAD

**Issue by LiNK2088** [dalaranwow/dalaran-wow#2257]
Death and Decay currently does not produce high threat, as the tooltip states it should.
The threat modifier should be x1.9 damage, as you can see on this website: http://www.wowwiki.com/Threat
If you fix this it will be much smoother for DKs to aoe tank, cause currently its kind of a struggle.

**Comment by Golganeth** [comment]
Works fine. You can't expect to hold aggro for a long time by using just one spell. Closing up until valid proof to support the statement is given.
