### ISSUE TITLE
[Spell / Paladin] Holy Wrath

### ISSUE THREAD

**Issue by ashido96** [dalaranwow/dalaran-wow#2258]
Holy Wrath
- http://www.wowhead.com/spell=119072/holy-wrath
- http://wotlk.openwow.com/spell=48817

The Paladin spell Holy Wrath does no damage, ever, no affects/stuns, just drains mana.

**Comment by Golganeth** [comment]
Works as intended. You should read the tooltip carefully to know what targets get affected by the spell.
