### ISSUE TITLE
[Quest] The Undermarket - unobtainable

### ISSUE THREAD

**Issue by ashido96** [dalaranwow/dalaran-wow#2260]
The Undermarket ( http://wotlk.openwow.com/quest=3385 ) is the sequel to the quest "Shadowreaver" ( http://wotlk.openwow.com/quest=3379 ) but is unobtainable after "Shadowreaver" is completed.

The quest dialogue pops up for "The Undermarket" after completing "Shadowreaver" but says "You are not eligible for the quest" and then cannot be seen again, even though you should be able to just accept the quest immediately.

Edit: Both quests are obtained from "Nilith Lokrav" (http://wotlk.openwow.com/npc=8439).

**Comment by Golganeth** [comment]
I've just tested it and worked fine. Make sure you're indeed eligible for the quest and it will show up. 

If it doesn't show up, it could be an issue that only your character is having. If that's the case, then make an in-game ticket and we'll verify you are eligible and add the quest to your log.
