### ISSUE TITLE
Powering our Defenses

### ISSUE THREAD

**Issue by DeSis** [dalaranwow/dalaran-wow#2261]
Quest gives auto complete. It should go like this https://www.youtube.com/watch?v=Dctry8qOkIc

**Comment by Demlock** [comment]
Still an issue. However, the object can be placed at the specified spot but doesn't trigger a script...

**Comment by Daveonx** [comment]
Tested and currently working with some minor issues. The [Infused Crystal](http://www.wowhead.com/item=22693/infused-crystal) can be placed and trigger the event, but only one [Enraged Wraith](http://www.wowhead.com/npc=17086/enraged-wraith) spawns at a time, when it should be 3, making the quest slightly more challenging.
