### ISSUE TITLE
[Shaman] Earth Shield not working properly

### ISSUE THREAD

**Issue by Qxcr** [dalaranwow/dalaran-wow#2263]
How it works here: Earth Shield heals the target before the target takes damage. Tested it on full hp resulting in overheals from Earth Shield.

How it is supposed to work: Earth Shield heals the target after the target took damage.

**Comment by Golganeth** [comment]
The spell will overheal if the damage taken is lower than the healed amount, which seems logical.

**Comment by Qxcr** [comment]
Date: Wed, 11 Mar 2015 14:16:29 -0700

**Comment by Marquito01** [comment]
The OP is correct. Healing from Earth Shield occurs right before the damage is taken (instead of right after), which results in almost constant overhealing from ES and renders this spell useless. Is it possible to add a small delay?
