### ISSUE TITLE
Blink Teleports you off flying mount to ground instantly even outside of clip range. Class#mage

### ISSUE THREAD

**Issue by Sedare** [dalaranwow/dalaran-wow#2264]
Pretty self explanitory. But at times casting blink above the ground causes you to blink thru the floor of certain places (Grizzley hills - center area Grizzmaw Hold, and Dragonblight - Area directly above FP NPC At wyrmrest.) Pretty much blink yourself to a free death. You fall thru the ground and die.

Might be a simple fix, although this isnt working as intended, and I have used to to my advantage a few times, the death occasionally makes this very annoying.

**Comment by Golganeth** [comment]
Merge with #2495
