### ISSUE TITLE
[Quest][Classic] Level 10 Mage Quest Stormwind.

### ISSUE THREAD

**Issue by halmal242** [dalaranwow/dalaran-wow#2268]
If you are a non human mage and you take the initial mage quest while in elwyn forest you will be locked out of the following quest.

To reproduce.  Make a non human mage up to level 10 (I have a gnome).  Pick up the starter quest in Elwyn forest at the mage trainer in Goldshire.  Turn it in at the mage trainer within Stormwind.  The follow-on quest will show up so you can read it but will not be able to accept it.  Once you complete this quest you can not take the class quest at your races original trainer (confirmed for gnomes at least).

**Comment by Rushor** [comment]
fixed
