### ISSUE TITLE
[Quest] A Sample of Slime... [Object] Testing Equipment (red)

### ISSUE THREAD

**Issue by ashido96** [dalaranwow/dalaran-wow#2271]
The "Testing Equipment" for the quest "A Sample of Slime..." has no interaction what-so-ever, even after abandoning and retaking the quest. 
It should have a repeatable quest (blue question mark) to trade a "Felwood Slime Sample" for a "Corrupted Tested Sample" which when opened has a chance to give the quest item "Corrupted Felwood Sample".

Note: the Un'goro version of the testing equipment (green) works just fine for it's respective quest.

Testing Equipment: (red one on left) http://www.wowhead.com/object=174848/testing-equipment
A Sample of Slime... : http://www.wowhead.com/quest=4293/a-sample-of-slime
Felwood Slime Sample: http://www.wowhead.com/item=12230/felwood-slime-sample
Corrupted Tested Sample: http://www.wowhead.com/item=15103/corrupt-tested-sample#contains
Corrupted Felwood Sample: http://www.wowhead.com/item=12234/corrupted-felwood-sample

**Comment by Golganeth** [comment]
#201
