### ISSUE TITLE
[NPC] Vi'el <Exotic Reagent Merchant>

### ISSUE THREAD

**Issue by ashido96** [dalaranwow/dalaran-wow#2273]
The NPC "Vi'el" does not spawn at all. (or in the incorrect position).

wotlk coords via twinhead: https://wotlk-twinhead.twinstar.cz/?npc=16015
wowhead: http://www.wowhead.com/npc=16015/viel

**Comment by n-ghost** [comment]
He's in the cave on the ledge to the right of you when you're about to enter the Frostwhisper Gorge.

Not sure if the spawn is correct though, but he's definitely out there. Will make some screenshots if I ever get there in any near future.

**Comment by n-ghost** [comment]
Here he is, in the cave at 59.77.
![wowscrnshot_030615_124544](https://cloud.githubusercontent.com/assets/8515510/6524181/8706ce40-c3ff-11e4-933b-1a2da3665ecd.jpg)

**Comment by ashido96** [comment]
Ty sir
