### ISSUE TITLE
[Quest] - Tomber's Supplies (ID: 9152)

### ISSUE THREAD

**Issue by Klala** [dalaranwow/dalaran-wow#2275]
I heard that the quest works fine from someone but when i tried to loot Rathis Tomber's Supplies (ID: 181133) I get empty loot.

Maybe this quest works once per server restart? I have a little bit of experience with this sort of problem and it looks like it.

UPDATE: I tried it now 4 times in a row and it worked perfectly. I wasn't online to witness a server restart though.
Maybe when someone is looting it too fast or from the max range (sometimes causes the empty loot bug too) it happens.

**Comment by Golganeth** [comment]
This was fixed in-game. It's a rare and general issue with game objects. The quest itself works fine.
