### ISSUE TITLE
"Wyrmrest Defender" usable out of zone and map

### ISSUE THREAD

**Issue by HK8919** [dalaranwow/dalaran-wow#2276]
I've seen a night elf (I think female) fly over Valiance Keep in the Borean Tundra using a Wyrmrest Defender.

Wyrmrest Defender are daily quest drakes that should automatically dismount you when you get out of the daily quest zone. This is the quest I'm referring to: https://www.youtube.com/watch?v=qzvmPD9pV5I

The exact time this happened was
Day: 04, Month: 03, Year: 2015, Hour: 00, Minutes: 44, Seconds: 17
(04/03/2015 00:44:17)

The position of the glitcher was on the surface of the ship between both parts of Valiance Keep. I saw him fly from far, rest on the surface of the ship then fly away.

I wasn't able to discern the name of the character abusing the glitch due to the name not appeared, instead it was replaced by "Wyrmrest Defender". It seemed to be a female night elf rogue though. I'm afraid that's as much information as I could gather.

**Comment by Golganeth** [comment]
Merge with #1413
