### ISSUE TITLE
Quest: Mage Summoner

### ISSUE THREAD

**Issue by ffighter29** [dalaranwow/dalaran-wow#2277]
Slay Sarilus Foulborne and bring his head to Sentinel Velene Starstrike in Silverwind Refuge.

Sarilus Foulborne sits atop Dreadmist Peak in the Barrens

So it took me a while to find this fella but i did it. NPC is stuck in ground. To see him use ctrl+v when on top of Dreadmist Peak just above cave entrance. When u walk near Sarilus u will enter combat then slowly move to the top of cave entrance and Sarlisus will follow u to attack and leave ground and then he becoms attackable. Kill him and loot quest item. Hope i have been helpfull. Enjoy game ^^

It would be great if Sarilus Foulborne cordinates are changed so he is not stuck in ground. Cheers!

**Comment by Golganeth** [comment]
This may happen sometimes with NPCs but It is related to pathfinding. The coordinates are correct.
