### ISSUE TITLE
Meteorite Crystal trinket from Algalon 10 bugged

### ISSUE THREAD

**Issue by Phenomenal101** [dalaranwow/dalaran-wow#2278]
As of patch 3.2 the Meteorite Crystal trinket had a change made to it, changing the relatively low chance on cast to a 100% chance on mana costing spellcast affected by amount of hits the spell does.
e.g. Chain Heal with Glyph gives a stack for all the 4 hits the heal does, Flash of Light healing the maintarget as well as the Beacon of Light target gives 2 stacks, etc, etc.
Next to the buff not having the correct proc chance the trinket also can't be "Used" correctly, giving an "Interrupted" message if you cast something too quickly after it. This counts even for instant abilities which cast time should not interrupt a trinket Use. I assume there's a hidden cast time within the Use of the trinket, much like a Hunter's Multishot has a 0,5 cast time for which no cast bar actually appears.
The tooltip still says 60mp5 but the trinket already gives the correct updated 75mp5. The referance to this buff can be found in the link below but does not have to be changed as it is correct.

http://www.wowhead.com/item=46051/meteorite-crystal#comments can be checked for confirmed information about the trinket. Especially the post by "Theolol (14,309 – 3·27·143) on 2010/01/31 (Patch 3.3.0)" is incredibly useful.

I've found some more information in the form of a video:
https://www.youtube.com/watch?v=_CzsvSxJGz8
https://www.youtube.com/watch?v=fA2IpRMxM_c Gets used at the 0:56 and 4:27 minute mark.

**Comment by Rlolas** [comment]
bump

**Comment by Phenomenal101** [comment]
So as WotLK progresses it looks more and more like a majority of the issues with Paladins are related to the fact that Glyph of Holy Light for some reason isn't classed as a Heal for a lot of trinkets including Meteorite Crystal and some others as well as Val'anyr shields not appearing on targets healed by Glyph of Holy Light.

# https://github.com/dalaranwow/dalaran-wow/issues/2375

**Comment by fsironman** [comment]
Easy DB fix:
https://github.com/TrinityCore/TrinityCore/issues/8669#issuecomment-148266549

UPDATE `spell_proc_event` SET `ppmRate`=0 WHERE `entry`=64999;

**Comment by shitserver** [comment]
Hey Loth Copy Pasta please. :+1:

**Comment by shitserver** [comment]
Why no Easy fix yet.

**Comment by fsironman** [comment]
PLS Loth executing one SQL query to make every Holy Paldins happy is it to much to ask?
