### ISSUE TITLE
[Mechanic] Death at Shattrath's flight

### ISSUE THREAD

**Issue by Kaporalhart** [dalaranwow/dalaran-wow#2280]
For the second time, i died upon arriving at shattrath by flightpath. Unfortunately, both times, i wasn't looking when it happened. I die from fall damage, but i don't think i died on the spot but went through the floor, because i can see i'm about 500 yard below the city, in a glitchy void of doom from which i can  see the city's not-supposed-to-be-seen bottom, and my corpse is nowhere to be found.

**Comment by n-ghost** [comment]
Same goes for Ironforge (which kills you) and Stormwind (which just sends you under it).

Rip Ironman attempts.

**Comment by Demlock** [comment]
This problem is present on many private servers, so it must be tied to the core or sth.

**Comment by Rushor** [comment]
Cannot reproduce this on ptr anymore. Let us now if the sisue still exists on live-server and add a comment and we will reopen the issue, Thank you.
