### ISSUE TITLE
Ulduar / Stormcaller Brundir's Lightning Tendrils

### ISSUE THREAD

**Issue by Nikvet** [dalaranwow/dalaran-wow#2282]
Stormcaller Brundir's Lightning Tendrils is not working correctly.He's supposed to follow a person and switching the target to another random person every 4-5 seconds,total of 4 players.Then he lands.Stormcaller Brundir should not move forward while he's landing.While the Lightning Tendrils Phase he's not high enough in the air.See Picture for the correct height.
http://wow.zuggaming.com/wp-content/uploads/iron-council-strategy-guide.jpg
And there should be more lightning under him while Lightning Tendrils,even if there are no players taking damage from the spell.Stormcaller Brundir is casting Chain Lightning or Lightning Whirl in the air, just before he begins to land. He should not cast anything while in the air and when landing.
Here's a video from retail if you need - https://www.youtube.com/watch?v=JJiGMwKB3JI

Some more bugs I have found:

When Stormcaller Brundir begins to cast Overload,there should be a message in the centre of the screen - Stormcaller Brundir begins to Overload!

When starting the Boss Encounter sometimes Stormcaller Brundir won't engage in the battle.The Iron Council are not linked together,they should be.And only one of them should yell his aggro quote.It's random.

**Comment by Lothloryen** [comment]
Hello there,

Lightning Tendrils and boss linking were corrected already, deploying the text.

Thank you.
