### ISSUE TITLE
Object: Portal to Inner Maraudon

### ISSUE THREAD

**Issue by daxpedda** [dalaranwow/dalaran-wow#2283]
<ul>
<li>
<b>Issue Present:</b> There is no <a href="http://wotlk.openwow.com/object=178404">Portal to Inner Maraudon</a> in the Pre-Dungeon to Maraudon.
</li>
<hr></hr>
<li>
<b>How it should work:</b> The portal should always be spawned.
</li>
<hr></hr>
<li>
<b>Proof:</b> Patch 3.0.8 as seen <a href="http://wow.gamepedia.com/Patch_3.0.8_(undocumented_changes)#Dungeons_and_Raids">here</a>. I guess the <a href="http://www.wowhead.com/item=17191">wowhead comments</a> should also provide enough evidence.
</li>
</ul>

**Comment by Demlock** [comment]
Confirmed, there is supposed to be the portal there but there is none. This portal used to be created with the scepter of Celebras but as of wotlk, this is no longer the case. Now Scepter of Celebras is the rare quest reward while the portal should be at the place through the middle door

**Comment by Rushor** [comment]
INSERT INTO `gameobject` (`guid`, `id`, `map`, `zoneId`, `areaId`, `spawnMask`, `phaseMask`, `position_x`, `position_y`, `position_z`, `orientation`, `rotation0`, `rotation1`, `rotation2`, `rotation3`, `spawntimesecs`, `animprogress`, `state`, `VerifiedBuild`) VALUES (5417, 178404, 1, 0, 0, 1, 1, -1382.07, 2918.79, 73.2073, 2.80997, 0, 0, 0, 1, 120, 255, 1, 0);


it already spawned on ptr

**Comment by Jindra555** [comment]
Portal is there, but can't be clicked.
(Since patch 3.0.8, it was accessible for everyone.)
http://wowwiki.wikia.com/wiki/Patch_3.0.8_(undocumented_changes)#Dungeons_and_Raids
