### ISSUE TITLE
NPC's In Air

### ISSUE THREAD

**Issue by TheLichWarrior** [dalaranwow/dalaran-wow#2287]
Hello Best developer's and programer's of Dalaran Wow Server in the Starting Zone's Monster's in The Mine's are floating from time to time pls check the pathing's of the monster's in all zone's where there are Mine's only there i can see Mob's Flying good Luck.

On Algalon Realm I am Playing.

P.S=Good Server

**Comment by Golganeth** [comment]
Duplicate of #42
