### ISSUE TITLE
Kira Songshine Pathway !

### ISSUE THREAD

**Issue by TheLichWarrior** [dalaranwow/dalaran-wow#2288]
The npc's is not on the right track she is offroad pls fix the path for the npc's Kira Songshine.
Zone : Elweyyn Forest
Location : Goldshire
http://wotlk.openwow.com/npc=3937

**Comment by TheLichWarrior** [comment]
TY

**Comment by TheLichWarrior** [comment]
sometimes she fly

**Comment by Rushor** [comment]
duplicate of https://github.com/dalaranwow/dalaran-wow/issues/2609
