### ISSUE TITLE
Grandmaster's Training Dummy's

### ISSUE THREAD

**Issue by TheLichWarrior** [dalaranwow/dalaran-wow#2290]
They dont work don't give weapon skill training tryied for Alliance in Stormwind pls fix em asap.

**Comment by TheLichWarrior** [comment]
On every hit there is mesage enering combat and leaveing combat

**Comment by TheLichWarrior** [comment]
Place Dummy's for all range of levels we need more 1-10 12-20 20-30 30-40 40-50 +++

**Comment by Golganeth** [comment]
This is Blizzlike. Dummies aren't supposed to give weapon skill. Please inform yourself before stating something as bug.

Thanks!

**Comment by TheLichWarrior** [comment]
ok
