### ISSUE TITLE
Westfall Stew Quest

### ISSUE THREAD

**Issue by TheLichWarrior** [dalaranwow/dalaran-wow#2292]
Hello again the quest in zone Westfall cant be finished have all the correct ingrediants and cant complete pls fix the quest.

**Comment by n-ghost** [comment]
Abandon and retake it, same with any other quest that asks you to collect white reagents.

**Comment by Golganeth** [comment]
Yes. Abandon and retake it, you won't lose any item and you'll be able to get it rewarded. It's a general issue, the quest itself works fine.

**Comment by TheLichWarrior** [comment]
ty
