### ISSUE TITLE
[NPC] Anub'ar Ambusher [26402] - [Ability] Rush [50347]

### ISSUE THREAD

**Issue by ashido96** [dalaranwow/dalaran-wow#2294]
The ability Rush "Increases the damage of the next melee attack by 200%." used by Anub'ar Ambusher lasts for the full duration of 5 seconds and can proc multiple times instead of just one attack.
The buff should be removed after an auto attack successfully does damage (stays active if hitting shields or anything that entirely blocks the damage).

Anub'ar Ambusher: www.wowhead.com/npc=26402/
Rush: www.wowhead.com/spell=50347/

**Comment by Rushor** [comment]
DB/Creature: Anub'ar Ambusher - Remove Aura 'Rush' 3 seconds after combatstart

* closes https://github.com/dalaranwow/dalaran-wow/issues/2294
* commit: 86a96d08a71d356e1bc6de05f22c152a101b41ed

**Comment by Aridam** [comment]
Confirmed that the Anub'ar Ambushers' Rush doesn't get used-up on their first hit upon applying the Buff on themselves -- it stays on and allows them to keep doing the amplified Damage until it runs out on its own.
