### ISSUE TITLE
Cold snap sometimes doesn't reset frost tree cooldowns. 

### ISSUE THREAD

**Issue by Sweglordz** [dalaranwow/dalaran-wow#2295]
This has happened to me multiple times while pvping - I used iceblock 1 or 2 minutes earlier, i press cold snap and it doesnt reset ice block cooldown. Similar thing with Water Elemental. Just doesn't work sometimes.

**Comment by Golganeth** [comment]
Duplicate of #2162. The reasons can be found on that report as well.
