### ISSUE TITLE
Warrior's Shield Bash

### ISSUE THREAD

**Issue by TheLichWarrior** [dalaranwow/dalaran-wow#2296]
Beggining effect interupt spell is working but the second effect interrupt school of magick for some 6 seconds isnt working pls fix the problem need thet ability against casters of magick & spell.

Only tried on Mob's havent traied on Players in PVP

**Comment by TheLichWarrior** [comment]
hm on all Mob's happens this the correct second effect is to disable the caster school of magick for 6 seconds pls fix faster this. game is hard

**Comment by Golganeth** [comment]
Please re-check the current issues before opening new ones. This is a duplicate of #182. Works fine on PvP.
