### ISSUE TITLE
Website Account Need help for Forum's

### ISSUE THREAD

**Issue by TheLichWarrior** [dalaranwow/dalaran-wow#2297]
Hello server is best i have only one problem.Can't write on forum's because under my account there isn't character to select so i can have acces to forum's.My ingame character is Dsword lv18 help me so I can use forum's

**Comment by TheLichWarrior** [comment]
Under real name and surname Vele Taratakov there says no characters have beeen found

**Comment by Golganeth** [comment]
Invalid report. The bug tracker only lists in-game issues.

You may find #2107 useful so check that out.

**Comment by Demlock** [comment]
Please stop opening threads about problems that are not tied to in-game bugs. This problem of yours is solved by creating a character on Kirin Tor realm...
