### ISSUE TITLE
(ROGUE) Klaven's Tower Bugged

### ISSUE THREAD

**Issue by gingerbread2465** [dalaranwow/dalaran-wow#2300]
After pickpocketing the key I still can not open the chest at the top of the tower.
![wowscrnshot_031515_125017](https://cloud.githubusercontent.com/assets/11489723/6656965/dc147b08-cb11-11e4-8dc6-a542d1a85d38.jpg)

**Comment by Golganeth** [comment]
Works as intended. The chest isn't meant to be opened with the key. Read internet sources such as Wowhead comments of the quest if you don't know how proceed.
