### ISSUE TITLE
[QUEST] The Affray

### ISSUE THREAD

**Issue by AvenMoira** [dalaranwow/dalaran-wow#2305]
IGN: Nahu level 34
Quest: The Affray

Details:
I have accepted the quest then as mentioned gone to the pit and nothing happens. I tried abandoning the quest and retaking it but still not working.

**Comment by AvenMoira** [comment]
not really sure with how  closing of issues here works but this is resolved as of today(7 hours ago based on this post). Nice work! much appreciated!

**Comment by Golganeth** [comment]
There isn't any issue with this quest.

**Comment by Chieftain99** [comment]
How was it resolved? I have exact same issue
