### ISSUE TITLE
[Account] Account suspended *without email notification*

### ISSUE THREAD

**Issue by mpatterson957** [dalaranwow/dalaran-wow#2311]
My account mpatterson957 says it is suspended when I try to log in. I did not recieve an email notification. How may I know what I was suspended for and for how much time? thanks

Edit: I found out I'm supposed to post this on the forum so I posted there. However I do think it may be considered a Bug that I didn't get a notification

**Comment by Golganeth** [comment]
Invalid report. The bug tracker only lists in-game issues.
