### ISSUE TITLE
Warrior's Charge 

### ISSUE THREAD

**Issue by TheLichWarrior** [dalaranwow/dalaran-wow#2312]
Hello Good Server Developer's and Programer's.
My problem is little.When i use charge with my warrior he always stuck in middle of enemy model I need to use arrows so to get away little from the enemys so it dont look stupid pls fix this issue with the next patch it will make the server more polished Thank you.

**Comment by Rlolas** [comment]
I think wow's a bit too hard for you man.

**Comment by TheLichWarrior** [comment]
Its normal game i like it

**Comment by Golganeth** [comment]
Invalid report.

**Comment by TheLichWarrior** [comment]
why invalid report ?
