### ISSUE TITLE
Glyph Of Consecration

### ISSUE THREAD

**Issue by dirindon** [dalaranwow/dalaran-wow#2319]
It simply doesn't work nothing more to say about it.

**Comment by Tarpor** [comment]
Consec lasts for 10 seconds, cooldown is 10 seconds, works fine. Can be closed.

**Comment by dirindon** [comment]
Wasn't working at all but  it was my client side. If you ever except glyph thats not working delete wdb and cache folders and if it didn't helped turn off addons and repair wow. Yea can be closed.
