### ISSUE TITLE
The Sons of Hodir questchain - Reputation gains are way off.

### ISSUE THREAD

**Issue by Xehpo** [dalaranwow/dalaran-wow#2320]
Dear Dalaran-WoW development team,

there is a questchain in Storm Peaks, which begins with "They Took Our Men!" (http://www.wowhead.com/quest=12843, Quest-ID: 12843).
This is the questchain that ultimately leads to the Sons of Hodir and boosts your reputation with them from *Hated* to *Honored*.
Please see this overview for the whole questchain and all relevant quests:
http://www.wowwiki.com/Sons_of_Hodir

However, the reputation gains with the Sons of Hodir during this questchain are way off on Algalon.
There are two major quests, which take you instantly to *honored* reputation with the Sons of Hodir:
[Mending Fences] (http://www.wowwiki.com/Quest:Mending_Fences) *Quest-ID: 12915* and
[A Spark of Hope] (http://www.wowwiki.com/Quest:A_Spark_of_Hope) *Quest-ID: 12956*

Please note the patch changes in both wowwiki entries: *Patch 3.3.0 (08-Dec-2009):  reputation gain increased from 22,000 to 28,600 (for non-humans). Where this formerly increased reputation to Neutral with the Sons of Hodir, it now makes one Honored.*

Since this server is on 3.3.5, at least concerning all character abilities, spells, cooldowns, achievements and even faction reputation rewards (Sons of Hodir *Exalted* Shoulder Enchants became Bind on Account only with Patch 3.3.0, when reputation gains were changed as described above), etc. etc. it is a bug when players do not recieve the reputation rewards that should be given for the aforementioned quests. Especially since you have to grind reputation now to just continue with this questchain, as it leaves you at *Neutral*, but a *Friendly* reputation is required to complete the follow-up quest: [Krolmir, Hammer of Storms] (http://www.wowwiki.com/Quest:Krolmir,_Hammer_of_Storms) *Quest-ID: 13010*.

Also other quests in this questchain are currently in the post 3.3.0 state, like [Hot and Cold] (http://www.wowwiki.com/Quest:Hot_and_Cold) *Quest-ID: 12981*, where the required amount of Frozen Scraps (Item=42252) has been changed with patch 3.3.0, too. So there is no reason why the amount of reputation a player recieves upon completing the quests should not be changed accordingly, aswell.

I'd like to point out that this was posted before, but sadly closed by the Thread-Starter: #1121 and #1122. Having the faction at war does not change your reputation gains from quests though, and was not the reason this player didn't get the accurate amount of reputation.

Please consider looking into this. Thank you very much for your help.
Kind regards,
Xehpo

**Comment by Augur89** [comment]
Almost all the factions and their reputation gains are messed up. It's annoying that you have to farm some reputation to be able to continue the introductory chains, but then is just double the grind time until exalted. Hard but doable.

**Comment by Lothloryen** [comment]
Hello there,

This has been corrected already and it shall be active after the next realm restart.

Thank you.
