### ISSUE TITLE
[Druid] Last lifebloom tick behavior

### ISSUE THREAD

**Issue by M0dinstaller** [dalaranwow/dalaran-wow#2321]
The bloom (end tick) should be able to crit but currently isn't.
The bloom should also be counted as a direct heal (like regrowth is) and thus be able to proc certain trinkets like http://wotlk.openwow.com/item=37734 but it isn't right now.

**Comment by Illiyara** [comment]
Lifebloom crits are working fine for me.
I can't comment on trinket procs yet.

**Comment by ImprezaWoW** [comment]
Fixed.
