### ISSUE TITLE
[Death Knight] [Arena] Raise Dead - Cooldown bug preparation

### ISSUE THREAD

**Issue by AraelWindwings** [dalaranwow/dalaran-wow#2324]
During preparation this spell have his cool down refreshed even if the Unholy DK have a Ghoul active.

It should not. This way it allows DK to cast it again even if the spell is (hidden) on cool down.

Casting during this hidden cool down cause Raise Dead spell to be bugged till you are out of arena, not allowing you to summon your ghoul till arena is over.

**Comment by Golganeth** [comment]
Confirmed. It's an issue with all the spells. Gonna make a general report and merge this with #2325.
