### ISSUE TITLE
[Item] Mark of the Dragon Lord

### ISSUE THREAD

**Issue by Tarpor** [dalaranwow/dalaran-wow#2328]
How it works: It is giving a shield that absorbs 500 damage, that is it.

How it should work: It gives a shield that absorbs 500 damage, and every 5 seconds that the shield is still up, it should give you 22 mp5. (There is no mp5 at all right now.)

**Comment by Rushor** [comment]
http://wotlk.openwow.com/spell=17252

**Comment by Rushor** [comment]
this works fine on ptr.

while mana break:

http://i.imgur.com/lhixKQV.jpg -> http://i.imgur.com/xArWKO8.jpg

frist: 24 > the it pops directly to 46

so:
Effect 1: Id 6 (SPELL_EFFECT_APPLY_AURA)
BasePoints = 22
Targets (1, 0) (TARGET_UNIT_CASTER, NO_TARGET)
Aura Id 24 (SPELL_AURA_PERIODIC_ENERGIZE), value = 22, misc = 0 (0), miscB = 0, periodic = 5000

is working fine.

**Comment by TeridanDW** [comment]
Works as intended on ptr.
