### ISSUE TITLE
[Warrior Talent]: Improved Spell Reflection

### ISSUE THREAD

**Issue by ConradSilverwind** [dalaranwow/dalaran-wow#2329]
Description: Reduces the chance you'll be hit by spells by 2/4% and when the ability is used it will reflect the first spell cast against the 2/4 closest party members within 20 yards.

Problem: This talent doesn't work at all. SR is never consumed on party members (except when used with Intervene) and it doesn't reduce the spell hit chance.

**Comment by Rlolas** [comment]
Even though the first part of it might not be working (or at least i have not been missing any spells at all to prot warriors), I have seen other prot warriors reflecting spells for me quite a few times.

**Comment by robinsch** [comment]
@Golganeth: Can you test this? Only the second part

**Comment by Golganeth** [comment]
@robinsch doing it right now

**Comment by Golganeth** [comment]
@robinsch works fine, the spells are correctly reflected and the effect is consumed. What I noticed is the 20 yds distance is a bit off. Currently only affects friendly targets if at 8.4~yds 3D and 11.4~ yds 2D.

https://i.gyazo.com/1e39937ea0c782a84b0e40680e5d3946.gif

**Comment by robinsch** [comment]
On PTR

**Comment by Golganeth** [comment]
It has infinite range as long as the party member is in sight 90-100 yards~(?)

**Comment by robinsch** [comment]
Updated
