### ISSUE TITLE
Random Dungeon Finder queue excluding random people.

### ISSUE THREAD

**Issue by Lebaowski** [dalaranwow/dalaran-wow#2331]
Couldnt find a topic on this issue, which i found weird as everyone i have talked to experience this.

The LFD queue seem to be getting stuck before filling up, even if there are players in the right level range also queued for the right role but wont get into that group and stay in the queue indefinately without getting grouped with anyone.

Example: me and a friend queued as tank and healer for a random dungeon. my friend did one dungeon before this where it worked, but the whole group were the exact same level, this has happened more times than it haven't to my friend, with everyone being the exact same level. 

When the queue we were in didn't pop for 2 hours with only 1 dps missing from the moment we signed up, we started asking around. As it turned out, there were at least 2 people in right level range, signed as the right role in the queue for 1 hour ++ and these were only the ones in my guild, 

when me and my friend invited a dps that had been in the queue for himself for a long time without getting a pop or being grouped with anyone when mousing over the LFD icon, we got an instant pop with 3 people signing up as a group.

So it looks like the LFD tool is excluding people and not putting them in groups, even when there are groups waiting for one person of the exact role that people are already signed as.  I'm not sure if this is an issue with lower level dungeons or in general. 

The example is of my first experience with the LFD tool, the pattern has been the same since.

Hope this can be looked into, as it makes the server seem less populated than it is and that probably turns a few players who prefer leveling by dungeons away. Having issues convincing my friend to stay at this point as we can stay signed for dungeons for as long as we like, and in the end we just have to start whispering people anyway. 

Sorry i couldnt be more clear on this, english is not my first language and i find this hard to explain properly.

To be clear, no one in the group of the example i experienced had anyone on their ignore list, i made sure to ask.

**Comment by Shadesmar** [comment]
i can confirm this. when the queue gets stuck leaving and rejoining the queue often works tho in that case

**Comment by Rushor** [comment]
one reason for this issue is that you are not added to the top of the Queue if any of the player denied the proposal. There are many more reasons for the "stucking" but that fix should improve it a bit.

On PTR.

Core/LFG: Readd to queue if proposal denied
* commit: 5f26f265170b4e201e66674a078fc2e44feb0970

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by Rushor** [comment]
related: https://github.com/dalaranwow/dalaran-wow/issues/2468 https://github.com/dalaranwow/dalaran-wow/issues/2726 https://github.com/dalaranwow/dalaran-wow/issues/3558

**Comment by Aridam** [comment]
Confirming this -- earlier (about 30m ago), I was queued as both Tank and DpS (Warrior), and the RDF Group being formed was missing a DpS. I re-queued a total of three times in a short span (within five minutes), before getting an instant pop-up on the last -- seems not everyone's accounted for and it's as if there just aren't people queuing up for those Roles, when there actually are.

**Comment by Rushor** [comment]
Already on PTR.
