### ISSUE TITLE
[Quest : The Light of Dawn] wont work

### ISSUE THREAD

**Issue by AvenMoira** [dalaranwow/dalaran-wow#2333]
Ign: Harlyquin
Issue: The Light Of Dawn does not work. I have tried abandoning the quest and retaking it but the needed characters wont show up.

**Comment by Golganeth** [comment]
It works as long as you trigger and start the event, just as intended.

**Comment by AvenMoira** [comment]
Hi, thanks for the reply. i tried it again but still now working. I tried to create another character(deleted the old one) and up to this point, the npc now shows up but when i tried to trigger the quest it stopped to a point where-to be exact- the commander summons all the minions and that it, nothing happens after. i tried to logout but sitll not working. i tried retaking the quest but still the same. 

thanks for your prompt response as always.

just to be sure IGN: HarlleyQuin

**Comment by AvenMoira** [comment]
nah, its working, a couple of logouts do fix. thanks again!

**Comment by Leodimas** [comment]
Well, seems like no one really knows HOW it is working, ive spend the last 2 hours trying to figure it out.
This quest should be looked at , and for the time it should be set to autocomplete. 
It is a shameful display of scripting as it is now.
