### ISSUE TITLE
Quest : Bringing Down Heb'Jin

### ISSUE THREAD

**Issue by Xllerator** [dalaranwow/dalaran-wow#2334]
I am supposed to click on a drum and the boss will spawn, but he does not spawn.I have seen other players trying do to the quest, or talk about it on global.I click on the drum and nothing happens.I tried in catform, bearform, nelf form, nothing happens.The boss is nowhere to be found.

http://www.wowhead.com/quest=12662/bringing-down-hebjin
https://www.youtube.com/watch?v=MVhDH_Z3WMk

It should work as this : click the drum, boss spawns, you use the net on his bat and then you kill him.

**Comment by Golganeth** [comment]
#1759
