### ISSUE TITLE
Too low droprate on  Voldrethar, The Dark Blade of Oblivion?

### ISSUE THREAD

**Issue by lmmense** [dalaranwow/dalaran-wow#2338]
Ulduar has been out for over 6 months, yet there's less than 12 drops of the item that all the platies crave for; I suspect that there's something wrong with the loottable. Epiphany received 2 from Lothloryen as a compensation, and Obsidius has received quite a few as well, could it be possible that the drop chance is off?

**Comment by Immenshrekt** [comment]
It sure is off, dear boy. I heard that if you QQ every now and then, the drop chance gets higher and higher )))

**Comment by WhereisthemyVoldrethar** [comment]
You can ask Mysterious how he feels about the drop rate. Heard you felt so happy he got it, top kek ))
