### ISSUE TITLE
Hackers in Game

### ISSUE THREAD

**Issue by jpdraibas** [dalaranwow/dalaran-wow#2339]
Dear reader,

it has accured to me and my guild (undergeared) that there are a few cheaters. They have robbed the guildbank and go by the name "fyropowah" and "destropowah". It is not appreciated in the guild to have them behave this way. Though they have been warned in game, they still continue their abbuse toward us. Please help us regain our fun and motivation for Dalaran-wow.

PS: the guildmaster is informed.

**Comment by Golganeth** [comment]
Invalid report. The bug tracker only lists in-game issues.
