### ISSUE TITLE
Resistance stacking Shadow Protection & Mark of the Wild

### ISSUE THREAD

**Issue by vdambrogi12** [dalaranwow/dalaran-wow#2340]
I know for sure that resistance is not stacking properly with Mark of the Wild and Shadow Protection.  Shadow Protection alone give the 130 shadow resist and the 54 given from MOTW is not accounted for.
![screenshot_040915_192533](https://cloud.githubusercontent.com/assets/11879120/7079789/4abd8d48-deee-11e4-8806-6b15da42fcb2.jpeg)

**Comment by Golganeth** [comment]
> - Auras, Shaman totems, raid buffs (e.g. Gift of the Wild, Prayer of Shadow Protection), and [Magic Resistance Potion] do not stack with themselves - only the highest single effect of these will apply;

> **Example**
In a group where Mark of the Wild, Aspect of the Wild, and Nature Resistance Totem is active, the group will only receive 130 Nature Resistance (either from the aspect or totem).

http://www.wowwiki.com/Resistance

Closing up.
