### ISSUE TITLE
Characters Gone

### ISSUE THREAD

**Issue by Bradleypain** [dalaranwow/dalaran-wow#2342]
Hi, I've quit this server a while back and my friends recently asked me if i had any servers to play on. I said that Dalarn wow a Wotlk server with retail scripts is one i used to play, I told them i had a lvl 70 ish warlock a 15 shaman and a 60ish Death Night. I recently redownloaded the client and started the game up, My deathnight that was 60ish was gone and my Warlock 70ish was gone and the only character left was my Shaman. I was really dissapointted because it took forever to get that character to 70 and a lot of hard work. Is there anywhere you can look at my account and see how it was deleted or give me a lvl 70 warlock, Please it took FOREVER to get to 70.

**Comment by Golganeth** [comment]
Invalid report. The bug tracker only lists in-game issues with quests, NPCs and such.
