### ISSUE TITLE
Pet - Rocket Chicken

### ISSUE THREAD

**Issue by Crispybuilt** [dalaranwow/dalaran-wow#2347]
**Item ID:** - 34492

- **Current Issue:**  The companion-pet doesn't have any visual effects of flying around, spinning or bursting into thin air at all.

- **How it should work:** - The chicken should fly casually around, spin and after some time explode in the air. It is somewhat simillar to Mini-Thor.

- **Helpful links:**
https://www.youtube.com/watch?v=SVThBlc6GU0 - Video of it
https://www.youtube.com/watch?v=jRuaT_9hMIA - 2nd video of it
http://wotlk.openwow.com/item=34492 - Open WoW
http://www.wowhead.com/item=34492/rocket-chicken - WoW Head

**Comment by Lothloryen** [comment]
Hello there,

This pet shall be properly scripted after the next scheduled maintenance.

Thank you very much.
