### ISSUE TITLE
Quest (Outland):  As the Crow Flies

### ISSUE THREAD

**Issue by Naidira** [dalaranwow/dalaran-wow#235]
"As the Crow Flies"  ( http://www.wowhead.com/quest=9718 )

Issue:  Upon using the Stormcrow Amulet ( http://www.wowhead.com/item=25465 ) the player will fly the determined course, but in their normal humanoid form, as if without a mount (seen below).  Player should be shapeshifted into a stormcrow during the journey.

![asthecrowflies](https://f.cloud.github.com/assets/5104690/869456/792af672-f7fd-11e2-84dd-b581bd1a31bf.jpg)

**Comment by Golganeth** [comment]
The dialog is also missing - #2341 

> "Here's the dialog she should have:

>>Ysiel Windsinger whispers: It's just like the structure you described at Umbrafen Lake. Does this mean the naga are pumping water out of all the lakes in Zangarmarsh?
Ysiel Windsinger whispers: The naga are even pumping the water out of their own lake! What purpose could that possibly serve?
Ysiel Windsinger whispers: There! Those pipes all appear to be connected to that structure. It can't possibly fit all the water they've been stealing. Where are they keeping it?
Ysiel Windsinger whispers: What we say explains what happened in the Dead Mire. There was a lake here once. If we don't stop the naga, all of the marsh will soon look like this?"

**Comment by Rushor** [comment]
visual was added https://github.com/TrinityCore/TrinityCore/blob/a56a402190c885e51038df55654875cc9e875c03/sql/old/3.3.5a/TDB55_to_TDB56_updates/world/2014_09_13_00_world_misc.sql

text still missing, will reopen the other issue for this
