### ISSUE TITLE
[Warrior](Spell Charge)

### ISSUE THREAD

**Issue by TheLichWarrior** [dalaranwow/dalaran-wow#2354]
Spell is working fine only problem it goes too far the charge needs to end before the monster but instead it goes into mid of the enemy model and you need to move 2 metters check and correct ending of spell good luck.

**Comment by ConradSilverwind** [comment]
Actually charge worked that way on retail, you can still hit mob when you charge him.

The only problem with charge here (besides the glyph) is that you can't charge uphill like on retail, but that's more pathfinding issue than charge.

**Comment by Golganeth** [comment]
Invalid report, works fine.
