### ISSUE TITLE
Mob LOS and pathfinding

### ISSUE THREAD

**Issue by deadmage** [dalaranwow/dalaran-wow#2355]
Some mobs have LOS issue even when you're facing them and there's nothing between you, even if you move closer to them they don't agro you.
![wowscrnshot_042115_195411](https://cloud.githubusercontent.com/assets/12057043/7262024/f7c06d8c-e87e-11e4-9628-6ec5cf985e95.jpg)

Another issue is with the pathfinding, here's a screen shot of it.
![wowscrnshot_042115_233055](https://cloud.githubusercontent.com/assets/12057043/7262039/0e881bbe-e87f-11e4-9cb1-ba2bdcb3ae75.jpg)
I spammed Hunters Mark and it said the target is LOS.

**Comment by Golganeth** [comment]
#1954
