### ISSUE TITLE
All panthers fly, realy silly :D

### ISSUE THREAD

**Issue by deadmage** [dalaranwow/dalaran-wow#2357]
![wowscrnshot_042415_005244](https://cloud.githubusercontent.com/assets/12057043/7308330/49f67f12-ea1c-11e4-89c9-84d6c7e4ffb9.jpg)

**Comment by Rushor** [comment]
inhabitshit in creature_addon and Creature_template_addon for every guid must be removed - old mangos issue

**Comment by Golganeth** [comment]
#42
