### ISSUE TITLE
gurubashi arena trinket

### ISSUE THREAD

**Issue by siasiekw** [dalaranwow/dalaran-wow#2358]
hi, i am trying to get the arena trinket but the chest doesnt even show up at 3, 6, 9 or 12 o'clock (server time, ofc). can you explain me how it works here? or is it bugged?

**Comment by Rushor** [comment]
wait one hour more or less (so 2 oder 4) because of the switching summer/wintertime

**Comment by Golganeth** [comment]
Invalid report.

**Comment by siasiekw** [comment]
what do you mean by invalid report? on retail servers its always been 3/6/9/12! if its different than there, we should be able to get such information, and its natural thing to come up with an idea that its a bug. am i wrong?!

**Comment by Golganeth** [comment]
This is not a valid report because you don't provide any proof nor valid information about retail WotLK. 

>"can you explain me how it works here? or is it bugged?"

For questions or concerns, feel free to visit the [forums](http://www.dalaran-wow.com/forums/). Thanks!

**Comment by belegija** [comment]
proof of the chest spawning at fixed times every 3 hours in [wowhead comments](http://www.wowhead.com/object=179697/arena-treasure-chest#comments).
