### ISSUE TITLE
Classic/Raid: Nefarian

### ISSUE THREAD

**Issue by Blackoutx** [dalaranwow/dalaran-wow#2360]
I guess this could also go under quest / achievment.

Currently the general consensus of Nefarian is that you start the encounter by going through the rp with him. And then as normal on Retail He goes immune and starts casting shadow bolts on whoever has aggro on him. while various dragonkin adds spawn and swarm you. After a set amount of time he phase transitions to phase two. During phase two he is supposed to disappear and reappear above his platform this time in his Dragon form and land on the platform and cast shadowflame. Currently on dalaran he appears as a dragon in the air. stays there where he spawns in the air. and then after a short amount of time he disappears and resets 10 - 30 minutes later and you have to start the whole encounter over again. He seems out of range for most spells and immune when you try to attack him if you are in range or "LoS". I've tried this many times many different ways and it all ends up the same... with him despawning. 
This is also a problem as far as the raid completion achievement for Blackwing Lair goes as well as the Quest "Nefarius's Corruption" where you are supposed to kill Nefarian within 5 hours of obtaining the quest.

**Comment by Tarpor** [comment]
We pulled him using the Power Word:Shield damage talent 'Reflective Shield'. I'm assuming he can be pulled with any damage-on-return spells. (As he does cast Shadowflame)

**Comment by Blackoutx** [comment]
Yep, Can Confirm now, this did work. He then proceeded to turn everyone in the raid into a feral druid and perma bop us.

**Comment by Rushor** [comment]
Description: Nefarian's call outs have no effect.

Current behaviour: Nefarian's call outs have no effect.

Expected behaviour: His call outs should be aflicting players with a specific debuff.

Steps to reproduce the problem:

    Go to Blackwing Lair
    Go to Nefarian's Lair
    Speak with NPC and wait till Nefarian will fall down

Include proofs for this behaviour

http://www.wowhead.com/npc=11583/nefarian

Nefarian's id: 11583

Include Screenshots from the issue if necessary

**Comment by Hephaetorix** [comment]
Still isn't fixed 3 years later

**Comment by Lothloryen** [comment]
Hello there,

Thank you for the report. This issue with Nefarian will be fixed after the last scheduled maintenance.
