### ISSUE TITLE
Rogue Crit Bug

### ISSUE THREAD

**Issue by anthony9915** [dalaranwow/dalaran-wow#2361]
Why is it when I am combat (Fist/Dagger) if I equip a dagger MH I gain a bonus 9% crit than I would if I had a fist in my MH.

![wowscrnshot_042615_125459](https://cloud.githubusercontent.com/assets/12125337/7338224/790bf176-ec13-11e4-8117-cf2ad93147ea.jpg)
![wowscrnshot_042615_125525](https://cloud.githubusercontent.com/assets/12125337/7338226/820d3dc0-ec13-11e4-974f-64e3c4abc07f.jpg)

**Comment by Golganeth** [comment]
Check your weapon skill before stating something as a bug. Thanks!
