### ISSUE TITLE
[Paladin][Hand of Reckoning]

### ISSUE THREAD

**Issue by Deqths** [dalaranwow/dalaran-wow#2363]
Hello there,
I am a main paladin player, have a large experience on the paladin especially on wotlk and BC, and noticed a bug on Hand of Reckoning.
The taunt is supposed to deal damage as long as the (pve) target is tauntable and not targeting you. Which means, not only when you don't have the aggro but also when for instance the humanoid mob is low on health and starts fleeing. Which means it can be used for a boost on the dps or as a finisher ( may be really useful in dungeons preventing the mob fleeing from aggroing some more by killing him )

**Comment by Augur89** [comment]
I didn't know the use you describe was possible in retail, but you could instead use Judgment of Justice to prevent them from fleeing or Hammer of Wrath to finish them at range... even Exorcism if you're DPS specced and Art of War is up.

I mean, even with bugs we have more than enough tools for this kind of situations ;-)

**Comment by robinsch** [comment]
Closed until proof is provided.
