### ISSUE TITLE
[General] Vmap

### ISSUE THREAD

**Issue by Deqths** [dalaranwow/dalaran-wow#2364]
I noticed that the mobs don't react they way they should when aggroing them from a distance, some don't get out of the water, others take awkward paths to the player. Which means that the vmap is kinda messed. There is also a bunch of wallcasts and out of ligne of sight issues, sometimes there's nothing between the target and yourself, and you still have the los error. Other times there are actually things between you and nothing prevents you or the mob from casting freely.

**Comment by Golganeth** [comment]
#1954
