### ISSUE TITLE
PVP BROKEN THINGS - read [ do not delete]

### ISSUE THREAD

**Issue by insanityTV** [dalaranwow/dalaran-wow#2370]
Pet control - B R O K E N
Pet disappear -  when pet disappear you need to go RELOG ( even in arena )
Traps - mostly dont work at  A L L  or even if they work you need to move your target to trap so it can work
Flare -  sometimes dont see stelth players
Spells  LATE  ( not latency problem )
LoS problem in battlegrounds ( walls , doors , arenas )
Resilience - D O N T  W O R K  -  example : DK kill in 5 sec , Paladin (retri) kill in 5-6 sec and not to mention other classes too. 
Arena leave button dont work sometimes.
Arena and battlegrounds are scripted very bad 
need to fix arena que - Teams with 0 rating cant play with those with 1500 rating and those with 1500 cant play with those with 2k + rating.
here is video that shows resilience at retail and how that works and HOW MANY SECONDS they need to burst someone down.
Also priest pain supression sometimes is broken - i got 8 k hit from mage  (pain supression on ) IT CANT BE DISPELED.
Today in arena  : my hunter partner died from lock and shamy in 4 sec - PAIN SUPRESSION ON - DETERRECE - PRAYERS OF MEDNING - RENEW - AEGIS
here is video : 
https://www.youtube.com/watch?v=mVd2FDqVRW4

**Comment by Lothloryen** [comment]
Hello there,

Thank you for the report, however it does not follow our report guidelines. The mentioned issues shall be looked into.
