### ISSUE TITLE
Warlock Demon BIGBIGBUG

### ISSUE THREAD

**Issue by JinKhanzo** [dalaranwow/dalaran-wow#2372]
here's the deal, whenever i die in bgs or wg or whatever i respawn with my last summoned demon, then i mount, run, dismount and my demon is 0%hp 0% mana and because of soul link he dies instantly when i get hit, so to recap im with my demon, die in pvp combat respawn and my demon is full hp full mana as expected, i mount, run, dismount, my demon is almost dead and withouth mana and because of soul link when i get hit he instantly die, pls fix this cuz it's game breaking

**Comment by Golganeth** [comment]
Might be related to #1992
