### ISSUE TITLE
Warlocks demon bug (not autocasting bug so don't erase this issue)

### ISSUE THREAD

**Issue by JinKhanzo** [dalaranwow/dalaran-wow#2373]
In pvp combat when i take dmg my demon takes dmg with me because of soul link spell, i get killed for example and my demon surely took some dmg with me, so i respawn with my demon and he is full hp full mana, i mount and dismount and my demon is 1% hp and 1% mana, i wrote this issue to you yesterday but you just erase critical issues like this? whats the deal?

**Comment by Golganeth** [comment]
As I said here: #2372, this is already reported. Thanks
