### ISSUE TITLE
Val'anyr, Hammer of Ancient Kings

### ISSUE THREAD

**Issue by jenahaze** [dalaranwow/dalaran-wow#2375]
The highly sought after legendary Ulduar mace does not proc with many heals as it should including:
- Beacon of Light Target DIRECT heal
- Glyph of Holy Light AOE Heal

As a Holy Paladin, the shield should proc off those receiving healing with 'Beacon of Light' but currently does not. This seems to be a similar problem to the trinket 'Meteorite Crystal' as seen in this bug report:
https://github.com/dalaranwow/dalaran-wow/issues/1999

In addition, the shields should also proc off of healing received via 'Glyph of Holy Light' but also currently do not.

**Comment by Crispybuilt** [comment]
Bump, hopefully this gets fixed soon so we can see Val'anyr in full action!

**Comment by Golganeth** [comment]
#2743 - 
> The "Protection of Ancient Kings" shield gained from the "Blessing of Ancient Kings" buff on the wielder of Val'anyr is supposed to stack up to 20,000 damage in overall according to this post on wowhead which quotes a blue [post](http://www.wowhead.com/spell=64411/blessing-of-ancient-kings#comments:id=705808) from the official forums. 

> The shield's damage absorb gets added to and duration gets renewed by heals from other healers who have the "Blessing of Ancient Kings" buff as well. More [clarification by Ghostcrawler](http://www.wowhead.com/item=46017/valanyr-hammer-of-ancient-kings#comments:id=705194) 

> Currently it doesn't stack with shields from other healers who have the procc active, the shield gets overwritten by subsequent shields instead of stacking.

> -Vathdar

**Comment by jenahaze** [comment]
Bump. Hoping for an update on this current issue... would be a shame to see the mace getting replaced in the upcoming release of ToC due to the proc's current broken state.

**Comment by Phenomenal101** [comment]
It looks like Val'anyr, Hammer of Ancient Kings now works 100% correctly for at least Paladins. Correctly shielding heals done by Beacon of Light and Glyph of Holy Light. Before this thread gets closed I want to thank the Dalaran staff for fixing the issue with Val'anyr and I want to give credit where credit is due; Akensai (80 Blood Elf Hunter) has send several fixes to the Support mail which have been implemented over the past 3 days now, including a Val'anyr fix. He has not had a reply on his mail so there's no way telling if it was his fix that was applied but regardless I want to thank him for his effort.

**Comment by Lothloryen** [comment]
Hello there,

Closing this issue since as stated it has been fixed, however, we do not have received any fix in our support mail - we have received a proposal to send fixes in the future though, from this player.

Anyways, thank you.

**Comment by strobe-light** [comment]
Hi, I really appreciate the fix of the interaction between Val'anyr and Beacon/Glyph of Holy Light, but the fix went a little bit too far. Currently the shields are proccing via healing from Judgement of Light, which it should not be. Everything else seems to be fine though.
