### ISSUE TITLE
Quest/NPC: Deciphering the Journal[12054]

### ISSUE THREAD

**Issue by ashido96** [dalaranwow/dalaran-wow#2378]
Quest: Deciphering the Journal [12054]
Mob: Grumbald One-Eye [26681]
Item: Spiritsbreath [36740]

Grumbald does not have a 100% drop rate for Spiritsbreath as he should when the quest Deciphering the Journal in the quest log. Took me killing him 7 times to get the item.

**Comment by Golganeth** [comment]
Already reported #256

**Comment by Golganeth** [comment]
Again an issue, #256

**Comment by Golganeth** [comment]
The drop rate has been increased to 100% and it will be applied to the live realm soon.
