### ISSUE TITLE
Pursuit of justice Talent

### ISSUE THREAD

**Issue by Argonn** [dalaranwow/dalaran-wow#238]
The retribution talent for the paladins doesn't seem to work like they should.
When learned they should increase your speed by 15% (does not stack with other speed blah blah). 

Problem is it doesn't effect your mount speed, which it should. Maybe because mount is a 'other' speed increase. But I'm currently running as fast as any other mounted player that has no speed increase.

Blizz removed the increase of mounted speed in MOP, in Wotlk it should still exists.

http://www.wowhead.com/spell=26023/pursuit-of-justice

**Comment by zozefin** [comment]
confirmed after i had a few test-races with friends

**Comment by Naidira** [comment]
Crusader Aura is working normally.

It provides a *multiplicative* 20% increase, and did on retail as well.  Your mounted speed on an Epic Ground mount is +100%, or 200% of normal walking speed.  As a result, it amounts to 200%*1.2= 240% movement speed, or +140% over normal walking.

PoJ, however, does not apply any form of mounted speed increase on this server, neither additive nor multiplicative.

**Comment by Argonn** [comment]
2 years open and still counting ^_^

**Comment by Spectralus** [comment]
Ridiculous. Really shows how the Dalaran team fixes bugs!

**Comment by Argonn** [comment]
If only 'THEY' had this talent to speed things up

**Comment by NovaHiros** [comment]
This is still bugged, sadly.

**Comment by Ryuseishinay** [comment]
Still bugged almost three years after what a nice talent.

**Comment by lightstylez** [comment]
I thought I wasn't going faster when I was putting talents into PoJ. It was obvious after unlocking crusader aura that pursuit of justice was not increasing mounted movement speed. I downloaded 2 different 3.3.5a add-ons for run speed both of them confirm only 200% mounted speed with 2/2 talent and 240% with crusader aura.. :( 
There Seems to be a lot of small & seemingly easily fixable bugs on the tracker from years ago. Makes me worried for the future after making this server my home.

**Comment by sixele** [comment]
tfw you say "seemingly easy fixable" because you have no clue what are you talking about. Also I'd think there are more important things to work on over speed boosts. Anyways, yes, this is still bugged.
