### ISSUE TITLE
[quest] The Storm King's Vengeance : Prince Navarius stuck in the wall

### ISSUE THREAD

**Issue by Kaporalhart** [dalaranwow/dalaran-wow#2380]
Prince Nevarius is in the wall that are the stairs near where he's supposed to be. he is not affected by any of the 4 abilities of the giant. he also has his bubble ability that grants him -20% damage.
He's supposed to be in the center, near his acolytes of pain.
He is also supposed to make thrym appear after his death, so thrym is nowhere to be found and cannot be killed either for the quest.
I suspect a player has used the shouting ability that kicked him and he got stuck in the wall.

**Comment by Golganeth** [comment]
Confirmed. There are pathfinding issues with this NPC.

**Comment by Kaporalhart** [comment]
i forgot to mention that the giant does not deal automatic attacks, and he is also very slow, he's supposed to be pretty fast.

**Comment by MrAndersonX** [comment]
Found him, killed him, but I can't seem to find Algar the Chosen. Is he bugged ? Does he not spawn ?

**Comment by Lothloryen** [comment]
This issue is no longer on the live server.
