### ISSUE TITLE
Quest in Venomspite bugged.

### ISSUE THREAD

**Issue by unb3l13v3r** [dalaranwow/dalaran-wow#2382]
Apparently, after I picked up the quest in Agmar's Hammer (Imbeciles Abound!) and delivered it to Chief Plaguebringer Middleton, I couldn't continue the quest chain. It displayed: "You don't meet the requirements for this quest" error. I completed all the other quests in the area.

**Comment by Leodimas** [comment]
To take the quest to fly to venomspite you need lvl 71. If you level with wowpro addon and start howling fjord with lvl 68, chances are you will have a few chains you cant Start when the addon says.
Always check wowhead as it says what prequisites or min lvl you need

**Comment by unb3l13v3r** [comment]
I'm lvl 73 fyi, and as far as I know, the only prerequisite is to take quest in Agmar's Hammer. Done most of the quests in Howling Fjord as well.

**Comment by Golganeth** [comment]
The quest is obtainable; #841
