### ISSUE TITLE
Tree of life shapeshifting not removing roots

### ISSUE THREAD

**Issue by Voidpants** [dalaranwow/dalaran-wow#2384]
When you are in tree of life and shift back into tree of life via a powershift macro (/cast !Tree of Life), it does not clear roots as it should from shapeshifting. This is very important to druid PvP as well as fights such as the last boss in nexus.

**Comment by Golganeth** [comment]
I did some testing and shapeshifting works just fine. It seems to remove all the roots/snares, including PvE mechanics such as Freya's roots. Closing up until valid proof to support the bug is given.
