### ISSUE TITLE
[NPC] Rezlak doesn't offer quests for Alliance players

### ISSUE THREAD

**Issue by Augur89** [dalaranwow/dalaran-wow#2385]
I am trying to complete the Loremaster achievement and this NPC named Rezlak (id 3293) is supposed to offer the only 2 quests available for Alliance players in Durotar, "Winds in the Desert" (id 834) and "Securing the Lines" (id 835), but I visited him today and he doesn't offer any. The quests are marked as neutral so any player can complete them, maybe here are marked as Horde. Or maybe they've some hidden prerequisite they didn't have in retail. Anyway, I don't know yet if I'll need those two quests to complete the achievement, but if they're indeed needed this should be fixed.

Here I provide the pertinent links:

-WoWWiki article: http://www.wowwiki.com/Rezlak
-WoWHead page with comments that confirm him offering quests to alliance players: http://www.wowhead.com/npc=3293/rezlak#comments
-WoWHead page for quests: http://www.wowhead.com/quest=834/winds-in-the-desert and http://www.wowhead.com/quest=835/securing-the-lines

Thanks and keep up the great job!

**Comment by Rushor** [comment]
you can accept the quest:

![GitHub Logo](http://i.imgur.com/fFQSAvu.jpg)

maybe your reputation is hateful with the faction of the creature.
