### ISSUE TITLE
Murloc suit no longer lets player mount.

### ISSUE THREAD

**Issue by pyrothraxus** [dalaranwow/dalaran-wow#2386]
After the patch was released, Players in Murloc Suits now get "you are in shapeshift form"

If you have the "deviate fish" buff as well (and look like a pirate) you can mount with both of the transformation buffs.

It is only an error when you only have the murloc suit buff. Please fix for this wonderful DP item!

**Comment by Lothloryen** [comment]
Hello there,

Thank you for yoru report, tomorrow I shall reset the bug tracker to have a proper track of all the issues from this point. However I will add this so I can take a look.

**Comment by Lothloryen** [comment]
Issue solved, thank you.
