### ISSUE TITLE
Felguard Attack power not scaling with gear.

### ISSUE THREAD

**Issue by pyrothraxus** [dalaranwow/dalaran-wow#2387]
Warlock pet buffs work in the following way. 

Char Tab-> Spell -> Mouseover (bonus damage) 
"Your Fire Damage increases your pet's Attack Power by X and Spell Damage by Y"

Pet Tab-> 
Pet gets the Spell Damage Bonus, but not the Attack Power bonus.

This bug is mainly effecting Demonology warlocks since their pet damage is mainly physical. 

This Bug effects ALL warlock pets currently, and thus NO pet is getting attack power bonus's from players gear, which will become a bigger and bigger issue was raiders gear up.

**Comment by Golganeth** [comment]
#1533

**Comment by Lothloryen** [comment]
Correction will be live in 15 minutes.
