### ISSUE TITLE
[Warlock] Fel Armor

### ISSUE THREAD

**Issue by Tprz** [dalaranwow/dalaran-wow#2389]
Problem: Since the patch today Fel Armor is proccing trinkets and lightweave on the heal tick even if you're at full health. I can stand still in dalaran on my mount with it up and watch my trinkets and lightweave proc.

How it should work: Fel armor should only be able to proc certain trinkets IF you are damaged and the healing tick actually heals you

**Comment by npmusicftw** [comment]
I don't recall Fel Armor healing ticks *ever* proccing trinkets.

**Comment by Akkalevil** [comment]
Why is this report closed ? It's still fully in effect in the game.

**Comment by robinsch** [comment]
Commit: 6add64e347af4149f9bde94f9e247ce5c8956304
Core/Spell: Don't proc auras if SPELL_AURA_OBS_MOD_HEALTH overheals

**Comment by TeridanDW** [comment]
Same commit as #3221
