### ISSUE TITLE
Kirin Tor currency vendors

### ISSUE THREAD

**Issue by martijnhaah** [dalaranwow/dalaran-wow#2396]
Vendors have been removed as if this is algalon.
Those that have not been deleted have had their items removed.

Just a small thing I worry about, did you remove the "buffs" on raid bosses? (the thing you do on Algalon to make it a bit harder)

**Comment by kazubla** [comment]
If you want to buy the rings they're still available at the Jewelcrafting vendor in Dalaran

**Comment by ImprezaWoW** [comment]
Vendors in Argent Tournament grounds don't sell anything either. But since it's an inactive realm, I doubt anything will be done about it.
