### ISSUE TITLE
Quest: Teron Gorefiend, I am...

### ISSUE THREAD

**Issue by Crispybuilt** [dalaranwow/dalaran-wow#240]
Quest Teron Gorefiend, I am - 10645/10639

Issue: The quest event won't start or won't work upon picking up the quest. Basically, there is a lot of introduction text events, the NPC will reveal himself as Teron Gorefiend (Ancient Shadowmoon Spirit), a Dranei Paladin will appear and Teron will have to posses you to fight him (with Teron's abilites) meanwhile there is lighting storm coming at you from the nearby "lost ghost red spirits in the air (you can see on the video)". After you defeat the Karsius, an outro roleplay has to start (great event) seeing Teron escaping on his Undead Horse.

How it should work (video): http://www.youtube.com/watch?v=vxcTATUqA5c
Quest is the same for Horde and Alliance, you just have to turn it in to a different NPC.

http://wotlk.openwow.com/quest=10645 - Alliance Version
http://wotlk.openwow.com/quest=10639 - Horde Version

http://www.wowhead.com/quest=10645/teron-gorefiend-i-am - Alliance Version
http://www.wowhead.com/quest=10639/teron-gorefiend-i-am - Horde Version

NPCs: 
Karsius the Ancient Watcher - 21877
Ancient Shadowmoon Spirit - 21797

ADDING NPC MANUALLY (Karsius) IN THE GAME DOESN'T HELP BECAUSE HE IS FRIENDLY TO PLAYERS

Quotes from WoWhead:

Make sure you dismount before accepting the quest, if youre mounted you cannot attack and cant be attacked thus just wasting time and causing you a headache.

Event bugs if you allready have a pet, dismiss it first
and if you have a funky UI that hides pet bar, might want to enable it

When you accept the quest you'll get to control Teron Gorefiend and a pet action bar pops up. He has 4 spells he can cast (Haste, Unholy armor, Touch of Darkness, Death and Decay). Start the fight with turning on Haste and Unholy armor. Cast Death and Decay on Karsius and auto attack him in the Death and Decay cloud. After that just keep auto attacking him and recast every spell once they have cooled down.

If you fail the quest Gorefiend will despawn then respawn in a few seconds. When he respawned for me(and before I even accepted the quest) he used his haste spell for some reason (I could hear him cast it then see the buff on him). When I picked up the quest again the haste ability was already on the 3 minute cooldown, but I didn't have the buff. I had to retry the quest about 3 times (because I hadn't read the tips on here :P ) and each time he respawned he used his haste spell and it was on cd when I started the quest. Finally I just waited a few minutes after he spawned then accepted the quest and it was off cd and worked just fine. Just something to be aware of.

**Comment by Exorcista** [comment]
i tryed this on Horde side and when accepting it (no pet no mounted) i get the debuff but no event happens just the mob to kill is sumoned but cant attack him because says im pacified.

**Comment by ashido96** [comment]
Just completed this quest today without any problems, the only thing I saw that was bugged was the life leech spell from the guy you "mount?" does not activate a gcd, and can thus just be spammed.

**Comment by Blackoutx** [comment]
![teron gorefiend](https://cloud.githubusercontent.com/assets/12115810/10116700/47161b54-640b-11e5-87e6-e84dbe91ac41.png)

Currently what I'm dealing with on the quest, Not mounted, no pet. Get MC'd by Teron, No mob spawns to fight

**Comment by M0dinstaller** [comment]
Had the same problem as Blackoutx

**Comment by jonanone** [comment]
The quest is working as intended. To be able to see Karsius you should be wearing the spectrecles (http://www.wowhead.com/item=30719/spectrecles) that you get from a previous quest on the chain.

**Comment by Rushor** [comment]
yeah there are two spectrecles which handle different quests
