### ISSUE TITLE
Azuremyst-Bloodmyst Flight Path broken

### ISSUE THREAD

**Issue by Woider001** [dalaranwow/dalaran-wow#2400]
The flight path between The Exodar and Blood Watch doesn't work, when trying to use the flight master in either city, a message pops up explaining that you have no connecting flight paths, even if you have visited both the flight master outside The Exodar, and the one in Blood Watch.

**Comment by martijnhaah** [comment]
saw a similar issue at trinitycore a few days ago.... seems to be it is rendering you in another continent.

**Comment by n-ghost** [comment]
Confirmed.

**Comment by n-ghost** [comment]
Seems to be fixed atm.

**Comment by Kelderen** [comment]
Just letting you know it doesn't work at the moment, in Kirin Tor. It shows you as being in Zul'Aman instead of Exodar.

**Comment by Rushor** [comment]
this was fixed with https://github.com/TrinityCore/TrinityCore/commit/a8f447b9eff366129296d6fcad97bca1767d2fd5

**Comment by TeridanDW** [comment]
Works as intended on ptr.
