### ISSUE TITLE
Unable to mount up when shapeshifted

### ISSUE THREAD

**Issue by ConradSilverwind** [dalaranwow/dalaran-wow#2401]
Happens when players ( non-druids in this case, not sure about druids ) use shapeshifting item like Frenzyheart Brew or get transformed in Brunnhildar Village.

**Comment by pyrothraxus** [comment]
Also murloc outfit.

**Comment by Vaxsysl** [comment]
Afaik, it's actually supposed to be that way?

**Comment by AgeAgainst** [comment]
Happened to me about 2 hours ago in Brunnhildar Village You could always remount after you finished any quests in Brunnhildar Village, since being in the area forces the shapeshift.

**Comment by Leodimas** [comment]
Confirmed, also the area where the transformation is forced upon you is way too big, it should stop just as you leave the village towards nyffelheim. At the moment it goes up to far behind nyffelheim.
Also you should be able to mount in disguise.

2 possible fixes

Fix disguise range so we can run out of the village and mount up

or 

Let us mount up in Disguise

**Comment by ConradSilverwind** [comment]
I read somewhere that you shouldn't be able to mount up if your disguise doesn't have a riding animation. Still, we should be able to mount as Brunnhildar Challengers and when using Orb of Sin'dorei.

**Comment by Lothloryen** [comment]
Hello there,

This issue has been corrected already.

Thank you very much.

**Comment by jerj** [comment]
no, this has not been corrected. fix it.

**Comment by deltafoxnine** [comment]
Still Bugged

**Comment by belegija** [comment]
issue still persists

**Comment by Lothloryen** [comment]
Hello again,

It seems the patch to fix this issue got reverted by mistake, my apologies. It will be working again with the next scheduled maintenance.

Thank you.
