### ISSUE TITLE
[Quest] Battle for the Undercity - Mainissue

### ISSUE THREAD

**Issue by Prljoman** [dalaranwow/dalaran-wow#2404]
Mainissue for all missing/nonimplemented Quests.

Commit history for all undercity-quest-related issues:

Old:
bca701a50fe6d13f5954ab9423776e9f0314093c
5403f99fc59d583d923d21ee097fcbf0de369adf
9928d24fe060ce234d238156bd8f935e2985040c
caec4490b3cde084936f346dc188d3a70f762fad
5a88e3d8ca91c70db0795c729b9d3f71116499bf
aca1f3514344660ba27825a7f621abaf50b44458
4a81d41c13266d3182feb65b75619e5dd14aec26
bf12ba099fec7276f60f5e185b79cc2c199f98b0
8bb8be2100f64d628abe6f33b34debc1d36e77ea
6aa6412defac7d912df72722e5879acb31ba6f3f
d3d244c8f8f874317c56ae6293444ab8e69a9f3c

07.11.2016:
```sql
32625bd2b96429fb47b9c0fa05177e36ca556a6f Scripts/The Battle for the Undercity: Move scripts to dev branch
c07f37146deefb7cb4b67617818d1e51e2acc58d Scripts/Spells: Taunka'le Refugee Transform for quest: Blood Oath of the Horde
dc463317f44a1f318576022708ec8f17bd798812 DB/Quest: From the Depths of Azjol-Nerub - now completable again
6ffdc4f83f40838b9325ec93f0cd45339cb19ef9 DB/Creature: Overlord Agmar - Always reset after 5 Minutes
0c291bd18e9e610ff5f30afd6de245372e6c9702 DB/Quest: Spread the Good Word - Despawn vehicle after 10 seconds after ejection 
d5ab2d31d7364b46e2d86a33efe4e949fd509024 DB/Spell: Implement mechanic for spell 'Devour Ghoul'
c4ba84157e133e5cac10bc7ebbe91ba417c280ed DB/Creature: Saurfang the Younger - Add movie after quest 'Return To Angrathar'
616af506d50b6fa11009aa36d917bf5bc6d9514b Scripts/The Battle for the Undercity: Implement quest: Herald of War
4447874d4aa7ff108ada833e63f964959f42895b Scripts/The Battle for the Undercity: Remove disables for all Quests
7d69df31096663c1074f161acfc50a92468d8a8a Scripts/The Battle for the Undercity: Set "Wyrmbait" and Icestorm always active 
cab896f5278941f321e3fb6b04070ed27de00293 Scripts/The Battle for the Undercity: Add some spellfocusgos for quest 'Patching Up'
047257165e7bae9120586a007b6973a21a6bb14c Scripts/The Battle for the Undercity: Improve quests: Herald of War + A Life Without Regret
c1d4cc24627b7d81278aac15d60807d51c61721f Scripts/The Battle for the Undercity: Teleport Hordeplayer back to OG after questreward
f3017a82937e037a285a71d1b533d4dfde71c0c4 Scripts/The Battle for the Undercity: Implement Fate, Up Against Your Will + A Royal Coup + The Killing Time
fbc327a08c57bbcda5c04b7e9bd85125c82d5126 DB/Quest: Herald of War - replace the starting object guid for an unused one.
b02db6efbde4b13383fa6d0663f8ffe3b5eeecbf Db/Quest: Battle for the Undercity - create sql file for all db changes
d90b8fcd5fafc199da82141c0d8170c3ab5ee286 Scripts/Battle for the Undercity: Set Thrall active (enables multiple eventstarts for "Herald of War" quest) + remove one unneeded sylvanas spawn in Orgrimmar
```

**Comment by Lukas45** [comment]
Basicly what goes wrong is, when you accept the quest there is suppost to be open a portal to Orgrimmar, but a phased version with UC refugees and the "correct" Thrall you can talk to
This portal never opens, so you never get to the phased version of Orgrimmar

**Comment by Cone182** [comment]
Conformed, not working.

**Comment by Nikectory** [comment]
Confirmen on https://github.com/TrinityCore/TrinityCore/commit/f4e2fb8f79e5a223506d9e514b7adf18c2198bab

Sarufang doesn't create the portal, same issue for the respective alliance quest

**Comment by DrFuler** [comment]
[13/3/2016] - Still not working.

**Comment by OriLighter** [comment]
[06/05/2016] - Still no portal, no responding Thrall.
[http://wow.gamepedia.com/Quest:Herald_of_War](url)

**Comment by Golganeth** [comment]
@rushor On PTR.

**Comment by MrAndersonX** [comment]
Still bugged. The portal doesn't open.

**Comment by Edzero** [comment]
Please refrain from bumping issues and creating duplicates.

We understand the frustration you feel but bumps will only slow things down as it cuts into our work time. The Battle for the Undercity chain has been on the PTR for some time now but due to a lack of testers it hasn't been pushed to live. It's the second item on my to-do list. 

I shall update this item once I have had a chance to thoroughly test it on the PTR. It may take about a week so please be patient with me.

**Comment by Rushor** [comment]
last fixes to the undercity event will be done today

**Comment by MrAndersonX** [comment]
Nice, ty for the update !

**Comment by Rushor** [comment]
reopening this as a note:
current state of fixing progress:
High Overlord Saurfang will now create the portal, dialoge and everything missing in og

**Comment by Rushor** [comment]
Scripts/The Battle for the Undercity: Implement quest: Herald of War

* updates https://github.com/dalaranwow/dalaran-wow/issues/2404

**Comment by Rushor** [comment]
Commit history for all undercity-quest-related issues:

Old:
bca701a50fe6d13f5954ab9423776e9f0314093c
5403f99fc59d583d923d21ee097fcbf0de369adf
9928d24fe060ce234d238156bd8f935e2985040c
caec4490b3cde084936f346dc188d3a70f762fad
5a88e3d8ca91c70db0795c729b9d3f71116499bf
aca1f3514344660ba27825a7f621abaf50b44458
4a81d41c13266d3182feb65b75619e5dd14aec26
bf12ba099fec7276f60f5e185b79cc2c199f98b0
8bb8be2100f64d628abe6f33b34debc1d36e77ea
6aa6412defac7d912df72722e5879acb31ba6f3f
d3d244c8f8f874317c56ae6293444ab8e69a9f3c

07.11.2016:
32625bd2b96429fb47b9c0fa05177e36ca556a6f
c07f37146deefb7cb4b67617818d1e51e2acc58d
dc463317f44a1f318576022708ec8f17bd798812
6ffdc4f83f40838b9325ec93f0cd45339cb19ef9
0c291bd18e9e610ff5f30afd6de245372e6c9702
d5ab2d31d7364b46e2d86a33efe4e949fd509024
c4ba84157e133e5cac10bc7ebbe91ba417c280ed
616af506d50b6fa11009aa36d917bf5bc6d9514b

**Comment by MrAndersonX** [comment]
Nice. Keep it up ! ^_^ This is a chain I've been dying for (and I think I'm not the only one).

**Comment by Rushor** [comment]
Scripts/The Battle for the Undercity: Remove disables for all Quests

* updates https://github.com/dalaranwow/dalaran-wow/issues/2404
* commit: 4447874d4aa7ff108ada833e63f964959f42895b

**Comment by Rushor** [comment]
Scripts/The Battle for the Undercity: Set "Wyrmbait" and Icestorm always active 

* they will no longer stuck in one place and "Wyrmbait" will always readd his gossip option if you don't follow his path
* closes https://github.com/dalaranwow/dalaran-wow/issues/3787
* updates https://github.com/dalaranwow/dalaran-wow/issues/2404
* commit: 7d69df31096663c1074f161acfc50a92468d8a8a

**Comment by Rushor** [comment]
Scripts/The Battle for the Undercity: Add some spellfocusgos for quest 'Patching Up'

* closes https://github.com/dalaranwow/dalaran-wow/issues/2154
* updates https://github.com/dalaranwow/dalaran-wow/issues/2404
* commit: cab896f5278941f321e3fb6b04070ed27de00293

**Comment by Rushor** [comment]
Scripts/The Battle for the Undercity: Improve quests: Herald of War + A Life Without Regret

* both quests are now completable
* add adjustments to the horde undercity-quest
* updates https://github.com/dalaranwow/dalaran-wow/issues/2404
* commit: 047257165e7bae9120586a007b6973a21a6bb14c

**Comment by Rushor** [comment]
pictures for the hordefight:
http://i.imgur.com/NDMrjtW.jpg
http://i.imgur.com/9Y2OTEW.jpg
http://i.imgur.com/xQhtRWZ.jpg
http://i.imgur.com/IytdE9P.jpg
http://i.imgur.com/aqjxY7c.jpg
http://i.imgur.com/nYhqkG7.jpg
http://i.imgur.com/IqmOCod.jpg
http://i.imgur.com/nsaR1o2.jpg
http://i.imgur.com/8vKpxLD.jpg
http://i.imgur.com/kjz1WLf.jpg
http://i.imgur.com/bqtZR63.jpg
http://i.imgur.com/sZ2mJEZ.jpg
http://i.imgur.com/7Girxof.jpg
http://i.imgur.com/iwfdI4p.jpg
http://i.imgur.com/ySbu0uH.jpg
http://i.imgur.com/faWwW6W.jpg
http://i.imgur.com/0iBis3E.jpg
http://i.imgur.com/dCK2eqh.jpg
http://i.imgur.com/ip2OVNi.jpg
http://i.imgur.com/ehLDGsG.jpg
http://i.imgur.com/lqp1hCK.jpg
http://i.imgur.com/Rhr7dCy.jpg
http://i.imgur.com/XpDfW7W.jpg
http://i.imgur.com/T8paaNX.jpg
http://i.imgur.com/yMe6Pzf.jpg
http://i.imgur.com/1rEOCH6.jpg
http://i.imgur.com/yv2pIQQ.jpg
http://i.imgur.com/3NhtZ8y.jpg
http://i.imgur.com/d6Xpe9C.jpg
http://i.imgur.com/nuAJjib.jpg

some alliance prequests are missing.

**Comment by MrAndersonX** [comment]
When will the fix be applied to the live realm ?

**Comment by Rushor** [comment]
first we need loth in order to apply the fixes to the ptr. then after testing by golgy or any other tester it will be applied on the liverealm with the next changelog

**Comment by MrAndersonX** [comment]
Okay, thank you very much !

**Comment by Rushor** [comment]
Scripts/The Battle for the Undercity: Teleport Hordeplayer back to OG after questreward

* updates https://github.com/dalaranwow/dalaran-wow/issues/2404
* commit: c1d4cc24627b7d81278aac15d60807d51c61721f

**Comment by Rushor** [comment]
Scripts/The Battle for the Undercity: Implement Fate, Up Against Your Will + A Royal Coup + The Killing Time

* updates https://github.com/dalaranwow/dalaran-wow/issues/2404
* commit: f3017a82937e037a285a71d1b533d4dfde71c0c4

**Comment by Rushor** [comment]
![GitHub Logo](http://i.imgur.com/DwxtGPX.jpg[/img])
![GitHub Logo](http://i.imgur.com/B2qY3vb.jpg[/img])
![GitHub Logo](http://i.imgur.com/ideCEwP.jpg[/img])
![GitHub Logo](http://i.imgur.com/AJRj1p5.jpg[/img])
![GitHub Logo](http://i.imgur.com/2zFAkrJ.jpg[/img])
![GitHub Logo](http://i.imgur.com/LwGb8i7.jpg[/img])
![GitHub Logo](http://i.imgur.com/0OwogUe.jpg[/img])
![GitHub Logo](http://i.imgur.com/AlWlRQH.jpg[/img])
![GitHub Logo](http://i.imgur.com/R0cRdLL.jpg[/img])
![GitHub Logo](http://i.imgur.com/3iDOP5Q.jpg[/img])
![GitHub Logo](http://i.imgur.com/fhUe6Ps.jpg[/img])
![GitHub Logo](http://i.imgur.com/hdUOoPB.jpg[/img])
![GitHub Logo](http://i.imgur.com/WPVknm0.jpg[/img])

**Alliance and Hordequest completely fixed now. Once it was tested by the testerteam it will be applied to the liverealm with tzhe next changelog.**

**Comment by Rushor** [comment]
@MrAndersonX: I hope you will have time to test it together with @edhelas :)

**Comment by MrAndersonX** [comment]
@Rushor : I'm not a tester, so, sorry man.

**Comment by edhelas** [comment]
@Rushor I'd really like to test that but I haven't played WoW for a couple of years now !

**Comment by Rushor** [comment]
then we have an other edhelas in our team too haha :D

**Comment by Edzero** [comment]
I'm the original Edhelas but I changed my name to match my in game one so players could contact me easier. :P Edzero is short for Edhelas zero.

**Comment by Rushor** [comment]
Scripts/Battle for the Undercity: Set Thrall active (enables multiple eventstarts for "Herald of War" quest) + remove one unneeded sylvanas spawn in Orgrimmar

* updates https://github.com/dalaranwow/dalaran-wow/issues/2404

**Comment by TeridanDW** [comment]
Few issues that I noticed on the horde version:
 - the initial message " X minutes until The battle for the Undercity will begins" X is always = 0 , it should be counting down until the event starts.
 - Big issue, Sylvanas is suppose to be with the group all the time, however after the courtyard she reset to her original position (where the event starts) and never bother to come. We saw her later in her "throne" room where she had a short conversation with thrall and then she reset again (going though walls to her original position, again).
 - Stormwing soldiers died from a single tunderstorm, howver they should not die and be frozen by jaina's nova and despawn with her and varian
 - Sylvanas's minions are level 1

**Comment by TeridanDW** [comment]
After 1 more run though the horde version of the event the results are the same as what I wrote above (point 1, 3 ,4) with exeption of:

> Big issue, Sylvanas is suppose to be with the group all the time, however after the courtyard she reset to her original position (where the event starts) and never bother to come. We saw her later in her "throne" room where she had a short conversation with thrall and then she reset again (going though walls to her original position, again).

This time she was with Thrall all the time, however due to formation system she almost got stucked here:
![wowscrnshot_101617_165101](https://user-images.githubusercontent.com/6797611/31616372-38392ec0-b295-11e7-9e4a-ef55c8a3080b.jpg)

 - Adding 1 minor issue - the orientation of the portals in the last room (Royal Quarter) seems off:
![wowscrnshot_101617_165902](https://user-images.githubusercontent.com/6797611/31616475-775a7cb2-b295-11e7-9974-3c2db8d2983c.jpg)

Moving on to Alliance's version

**Comment by TeridanDW** [comment]
Issues with the alliance version:
 - this

> the initial message " X minutes until the manhunt will begins" X is always = 0 , it should be counting down until the event starts.

 - sewers - creatures do really  low damage from 50-60 none elites to ~ 400 for the elites.
 - sewers - varian has the habbit of just passing though waves of undeads.
![wowscrnshot_101617_175220](https://user-images.githubusercontent.com/6797611/31619269-b0080276-b29c-11e7-9dea-14e42588e540.jpg)

 - overall varian spams "thunderstorm"(why he uses this spell I don't know) way too often
 - creatures fly in sewers (pathing)
![wowscrnshot_101617_175301](https://user-images.githubusercontent.com/6797611/31619259-a7ae22ae-b29c-11e7-8509-2389ada0e71c.jpg)

 - jaina is bearly casting any spells, she should spam her abilities
 - slimes do really low damage ~100

These are just notes, will come back to this later.

**Comment by Rushor** [comment]
alright concerning pathing and formation, i cannot change much - this would be fixed with https://github.com/dalaranwow/dalaran-wow/issues/4603. Concering the damage i will change it a bit.

**Comment by Rushor** [comment]
I think all mainissues with quest concerning announcements and quest retake (Horde side) are fixed now. Please open up a new issue for the remaining cosmetic issues, that are not related to the formation system. thanks :)
