### ISSUE TITLE
[Hunter][Spells] Lock and Load not proccing on ticks

### ISSUE THREAD

**Issue by kazubla** [dalaranwow/dalaran-wow#2406]
Hello there, I have noticed that during my Obsidium Sanctum and Eye of Eternity run Lock and Load did not proc at all! 

The tooltip suggests that there is a 100% chance to proc on freezing and frost traps and a 6% chance for this effect to activate off every explosive trap/immolation trap/black arrow tick

http://wotlk.openwow.com/spell=56344

The Freezing trap/Frost trap aspect of the ability works fine but the periodic damage does not.

I tested this by planting an explosive trap on a training dummy allowing it to hit for an 18%(6% on 3 targets) chance to proc per tick.

As you can see after 300 recorded ticks of explosive trap and 50 ticks of Black Arrow Lock and Load did not proc even once for me.

http://gyazo.com/93a11ac9cdb8e0baad99d05c1452fe0f

Point. The talent was working fine before the argent tournament patch

This increases Hunter Survival damage by a lot and therefore hinders my performance in raids so would appreciate a fix asap ^^

**Comment by kazubla** [comment]
Don't know whether you've got round to it yet but the bug still persists after the hotfix of 24/05/2015 which occured around 9:30am

**Comment by keggarr** [comment]
Confirmed on my end as well. Huge DPS loss

**Comment by irodeyourmom** [comment]
Any kind of ETA? Still bugged.

**Comment by Savagerqt** [comment]
The spell is still bugged

**Comment by Sigwastaken** [comment]
As of 10/4/2015 Still bugged.

**Comment by chichio15** [comment]
That talent still bugged, making survival build unviable, the amount of dps loss is HUGE, please consider working on that asap

**Comment by Lothloryen** [comment]
Hello there,

Thank you very much for the reports and comments. The periodic damage of the Black Arrow spell will also trigger this proc after the next server restart.

Thank you.

**Comment by Lothloryen** [comment]
It is already on the live server.

Thank you.

**Comment by chichio15** [comment]
Lothloren, i tested already, it's working now, but is working wrong, not it overpower us SV hunters xD
It's procing on everything, except black arrow, that should proc.

The procs i tested so far: 

Serpent Sting (wrong)
Explosive Trap (right)
Mana procs from Aspect of the Viper (REALLY wrong)

i'll be running more tests and keep you informed

**Comment by chichio15** [comment]
Hello again Lothloryen,

Now it seems to be working perfect, thank you again for your fast support and attention.

**Comment by chichio15** [comment]
Hello again Lothloryen

After server shutdown this morning, the bug was back to the start, no procs of lock and load on black arrow and explosive trap

Can you look at this again please?

Tyvm

**Comment by Winstrol** [comment]
Tested survival spec on the 25th on XT, had 3 lock and load procs during a 6min22sec fight, something is still wrong.
