### ISSUE TITLE
[Hunter] Glyph of Mending doesn't work.

### ISSUE THREAD

**Issue by JamesEakk** [dalaranwow/dalaran-wow#2407]
[Glyph of Mending]
http://wotlk.openwow.com/item=42900

It's used to work well until yesterday (20 May 2015, UTC+7 timezone) I noticed when engaged with elite mob and my [Mend Pet] skill seem definitely weakened so I test it with others situation to figure out what's wrong with it.
Finally I found out everything is going well except when I removed [Glyph of Mending] then nothing has changed, healing amount is not changed so I tried to replace it with the new one from AH and it's still the same like the glyph doesn't have any effect at all.

**Comment by robinsch** [comment]
@Golganeth Can you test this?

**Comment by robinsch** [comment]
Working fine.
