### ISSUE TITLE
Paladin: Judgement of wisdom: Does not grant Mana

### ISSUE THREAD

**Issue by kaygolob** [dalaranwow/dalaran-wow#2408]
The paladin Judgement of wisdom does not grant Mana on hit, as it should do.

[spell 20186]
class=Paladin
name=Judgement of Wisdom Rank 1
reqspell=20268

(http://www.wowwiki.com/Judgement_of_Wisdom)

Issue present: I do not know.
How does it work currently: It does Judge the target of an amout of holy damage, depending on the seal you have.
How it should work:  It shoeld Judge the target of an amout of holy damage, depending on the seal you have and have a chanse of granting you 2% of your base mana on hit.

**Comment by Woider001** [comment]
Wrong, I went and tested it out myself, not only does it grant mana, it does it fairly frequently, too.

Screencap for evidence: http://i.imgur.com/1umIgOR.jpg

**Comment by Golganeth** [comment]
Closing up.
