### ISSUE TITLE
Quest: Kroshius' Infernal Core - Part of the Warlock Quest Chain Line

### ISSUE THREAD

**Issue by Crispybuilt** [dalaranwow/dalaran-wow#241]
Quest Kroshius' Infernal Core - 7603

Issue: The quest itself is doable but the quest item which is needed to activate the Kroshius is not needed (it has to be, it's a part of the quest). He is sometimes killable and you can just easily loot the quest item from him. Also, he does have game model objecta and when you aggro him, his object stays the same making it as a visual bug (you see few rocks on the ground attacking you with no emotions) 

How the quest should work:
http://www.youtube.com/watch?v=_hYKJd88nNg

NPCs & Quest Item:
Fel Fire - 18626
Kroshius - 14467 (he also has one ability ( Knock Away )

After I completed this quest Niby summoned something he wanted to be an infernal. What he got was El Pollo Grande, a "Black chicken of death", quoting from it's description. It was a giant chicken that attacked me, only a level 50 so it was nothing serious. That event was actually quite amusing.

The dialogue for that cutscene (this occurs straight after you turn the quest in: [code] <Niby walks up to the hill behind him> Niby the Almighty: Stand back! Stand clear! The infernal will need to be given a wide berth! Niby the Almighty: BOW DOWN TO THE ALMIGHTY! BOW DOWN BEFORE MY INFERNAL DESTRO... chicken? <A fireball falls down from the sky, and a giant black chicken emerges. Hilarity ensues> Impsy rolls on the floor laughing. Impsy: Niby, you're an idiot. Niby the Almighty: Silence, servant! Veng

http://wotlk.openwow.com/quest=7603
http://www.wowhead.com/quest=7603/kroshius-infernal-core

**Comment by Rushor** [comment]
event was added here https://github.com/TrinityCore/TrinityCore/commit/036b4857abbef107fa5b52a406847f1066cf9f59

the rest maybe also works already

**Comment by Rushor** [comment]
bab37e8aa1be67d5bd06391f7fb693ff944efa4c
- added some improvements for that quest (the endevent was already there)

**Comment by Golganeth** [comment]
Needs some improvements like Kroshius' remains not disappearing once quest item is used. Very minor issue, works great.

**Comment by Rushor** [comment]
kay bumb myself
