### ISSUE TITLE
At The Enemy's Gates

### ISSUE THREAD

**Issue by Torrigan** [dalaranwow/dalaran-wow#2410]
The Vehicle horses can attack players. If I recall correctly in retail they weren't able to attack players but just the other faction's vehicles.

**Comment by Torrigan** [comment]
Also if I recall you could run over the Boneguard Footman and it kill them instantly.

**Comment by Vaxsysl** [comment]
Yup, running them over = they die. And it's quest http://www.wowhead.com/quest=13847/at-the-enemys-gates.

Boneguard Footman: http://www.wowhead.com/npc=33438/boneguard-footman
