### ISSUE TITLE
Mana Regeneration

### ISSUE THREAD

**Issue by Shadesmar** [dalaranwow/dalaran-wow#2411]
Whats the issue on Algalon:
Although auto-attacks doesnt spend mana they stop my mana regeneration.

How it should work:
quote from wowwiki(found in the spirit article http://wowwiki.wikia.com/Spirit#Mana_Regeneration ) : 
Five second rule 
Whenever mana is expended for any purpose, mana regeneration is interrupted for five seconds. This is most often caused by casting spells, but diseases that drain mana will also interrupt mana regeneration. During this time, no spirit-based mana regeneration takes place unless the character has certain talents; there is also the fixed regeneration from MP5 items, which is never interrupted for any reason (see the mana regeneration article for details). 

Here are the patch changes to mana regeneration: 
http://wowwiki.wikia.com/Mana_regeneration#Patch_changes
5 second rule was removed in the cata patch 4.0.1

**Comment by kazubla** [comment]
I have actually notice that I am ooming a lot more with my hunter, I thought that it was because of my gear reducing in Int but this seems more likely since you actually acquire more Int with higher level gear

**Comment by Winstrol** [comment]
Also noticed mana is a way bigger issue for hunters here, comparing videos from retail to here it almost feel like we oom at twice the speed with the same buffs.

**Comment by Rushor** [comment]
The issue was set to "On Hold" and will be closed until a proof was provided. Thank you.
