### ISSUE TITLE
[Quest][Northrend] Cold Hearted

### ISSUE THREAD

**Issue by Vaxsysl** [dalaranwow/dalaran-wow#2412]
Cold Hearted quest in The Storm Peaks
Quest: http://www.wowhead.com/quest=12856/cold-hearted
Drake(?): http://www.wowhead.com/npc=29709/freed-proto-drake

Issue: The drakes are extremely slow. We cannot fly them up, fly them down, just go "straight" and go left and right - making us unable to free prisoners. And then once we get the prisoners freed, and fly outside, and auto-pilot starts... it's quite literally walking speed. Takes more than four minutes to fly it back.

Also additionally, not sure if designed so, but we cannot mount up in those subzones related to the "crazy blue women" questline, because we're shapeshifted and therefore cannot mount - which would be no problem, we'd just cancel the buff manually and fly up, but we cannot cancel the aura either.

It takes us 1:30 to get three prisoners, we're flying for for seven minutes and twenty eight seconds, and it takes us another minute and something to get out of the area via tunnel (afaik, closest point we lose shapeshift to mount again).

EDITS: Wordings and timers added.

**Comment by ises** [comment]
Hello,

I also experienced the above issue. After a very long time of waiting for respawns/dragon to travel. I came across a horde (im alliance) that was moving fast on his drake. He saw me moving slow and said something in /say "n n o n n n n g o o g a o a l l a o n". While this doesn't make sense I figured out what he was trying to tell me. I hit the spacebar and it then allowed me to move fast on my drake, as well as up and down.

**Comment by Khronos-** [comment]
Can also confirm this is happening. Have experienced all the symptoms.

**Comment by Taffa2** [comment]
Just wanted to confirm that this is still happening.

**Comment by exiledone** [comment]
can confirm that hitting the space bar makes the drake work properly

**Comment by Golganeth** [comment]
Opening in order to give the issue more relevance, in case a player comes here looking for a workaround. 
For now, hit the Spacebar as mentioned above.

**Comment by Golganeth** [comment]
Opening the report in in case a player comes here searching for a workaround. 
For now, hit the Spacebar to make the drake work correctly, as mentioned above.

**Comment by Golganeth** [comment]
Opening the report to give it more relevance, in case a player comes here looking for a workaround. 
For now, hit the Spacebar to make the drake work correctly, as mentioned above.

**Comment by Rushor** [comment]
> Opening the report to give it more relevance, in case a player comes here looking for a workaround.
For now, hit the Spacebar to make the drake work correctly, as mentioned above.

the issue will be handled in https://github.com/dalaranwow/dalaran-wow/issues/3904
