### ISSUE TITLE
Chillblains

### ISSUE THREAD

**Issue by pascagabriel** [dalaranwow/dalaran-wow#2416]
High priority, please address this as soon as possible!

Patch 3.2.0 (04-Aug-2009): Icy Clutch can no longer miss when Frost Fever hits, however, when Frost Fever is dispelled Icy Clutch will also be dispelled. (http://www.wowwiki.com/Chilblains)

Currently, when you dispel Frost Fever, Icy Clutch is not removed with it. This gives frost DK's a huge advantage as it's one of their main disadvantages of this spec is the lack of an undispelable slow.

**Comment by Lothloryen** [comment]
Hello there,

Thank you very much for your report, this issue shall be corrected after the next server restart.

**Comment by pascagabriel** [comment]
Greatly appreciate the swift response!

Regards,
Freekill
