### ISSUE TITLE
Improved Succubus (warlock talent)

### ISSUE THREAD

**Issue by adytzyca** [dalaranwow/dalaran-wow#2417]
The talent doesnt work at all:having 3/3 talent points=same casting time as if 0-critical pvp talent point for warlocks and really frustrating to see it now work(ontop of all the other bugs that locks have and havent goten fixed yet)

**Comment by Zibathy** [comment]
so it turns out the skill required to play a class is directly proportional to how many bugs it has; maybe you should delete your lock and play a non garbage class? like any other class besides paladin?

**Comment by Lothloryen** [comment]
Hello there,

I will take a look, thank you for your report.

**Comment by Lothloryen** [comment]
Hello again,

It has been corrected, it will be deployed during the next maintenance.

Thank you.

#1332

**Comment by adytzyca** [comment]
Im sorry,i dont understand where your butthurt is coming,but either way,please refrain from making such statements only a down syndrome-terminal phase alzheimer person would make.That being said,you're added to the block list,so by all means,relieve all your real life frustrations on someone else#peace 


     On Saturday, 23 May 2015, 1:45, Zibathy <notifications@github.com> wrote:
   

 so it turns out the skill required to play a class is directly proportional to how many bugs it has; maybe you should delete your lock and play a non garbage class? like any other class besides paladin?—

**Comment by adytzyca** [comment]
The talent has been fixed,but today,02.06.2015 i've noticed it has bugged again
