### ISSUE TITLE
10 big issues with the Argent Tournament mounted duels.

### ISSUE THREAD

**Issue by DameronAlgalon** [dalaranwow/dalaran-wow#2418]
Based on the thread on the forums that the devs deleted with no comment...

1) The dueling NPC's randomly aggro onto other nearby players in the midst of combat.
2) Even though the dueling NPC's are taggable, the marks still go to whomever gets the last hit.
3) The dueling NPC's, Boneyard Lieutenants and Boneyard Commanders can use Charge and Shield-Breaker from a much shorter range than you can, and they can cast both at the same time. I've also had occurences of them using Charge at melee range.
4) A single enemy Charge sometimes randomly removes all three of your Defense stacks, while your own Charges occasionally do not register at all.
5) Charge works on airborne targets, like the Boneyard Scouts.
5) In the Court of Bones, you can attack other players' dueling mounts and even other players themselves while you're on your own dueling mount.
6) Boneyard Footmen do not die when trampled by your dueling mount.
7) Boneyard Scouts' Necrocution does not drain Defense stacks.
8) Almost all of the Boneyard Lieutenants that are supposed to spawn have been replaced with Boneyard Commanders. Double checked on other private servers.
9) At least half of all the dueling packs in the Court of Bones are absent. Also double checked.
10) The phased area in the Court of Bones is too small, making you unable to attack the enemies at the stairs in the back.

**Comment by AgeAgainst** [comment]
Confirming most of this except #2:

2) - You don't always get marks on the last hit, whether someone else tags it or if you tag it.  Someone simply being near the dueling NPCs can remove the ability to get marks.

Also adding
11) Dueling NPCs sometimes instantly reset or reset after a single Shield Break.
12) Dueling NPCs do not always give credit, even if nobody is around.

**Comment by darkwulfv** [comment]
Confirming the above; Charge not registering is also very frustrating as it makes defeating Champion opponents pretty difficult when they get 2-3 melee-range charges and none of yours have hit.

Also, the dueling mounts work differently from the mounts at the Court of Bones:

When riding a Dueling Mount at the Argent Tournament, you can use Shield Breaker even if you aren't facing your target. The Argent horse at Court of Bones does not allow this, making it very difficult to actually use Shield Breaker after Charge.

**Comment by Rushor** [comment]
7.) Boneyard Footmen do not die when trampled by your dueling mount.

This works fine for me on PTR
