### ISSUE TITLE
Quest: Mystery of the Infinite

### ISSUE THREAD

**Issue by AizenD-WoW** [dalaranwow/dalaran-wow#242]
So, this quest does not phase you or do anything correct, just spawns the hourglass and does nothing, when several mobs should spawn and attack the hourglass.

Two waves of 2, One wave of 3, One wave of a 75 elite.

Creatures related to the quest:
27889 Future You
27896 Infinite Assailant - 2 sets of 2 Try to ambush you.
27897 Infinite Destroyer - 2 Try to ambush you after the assailants
27898 Infinite Chrono-Magus - One spawns with 2 Infinite Destroyers. Then 2 spawns with the second wave of Infinite Destroyers.
27900 Infinite Timerender - Final hostile NPC to spawn.
27925 Nozdormu - Completion of quest.

Here's what it's supposed to look like.
http://www.youtube.com/watch?v=ay3TDGRld0U

http://www.wowhead.com/quest=12470

**Comment by Prljoman** [comment]
After the big update I checked Chromie and she offers quests again. This one I did without any problems but the next one "Mystery of the Infinite, Redux" is not working. Hourglass is spawned but nothing is happening.

**Comment by ashido96** [comment]
Can confirm that "Mystery of the Infinite, Redux" [13343] spawns nothing after placing the hourglass, it is not completable.

**Comment by daxpedda** [comment]
Seems that after the update this quest worked flawlessly for me.

**Comment by wwrpg** [comment]
Just tried this quest. The hourglass spawns, your future self shows up, as do all the mobs. But no credit is given after the hourglass disappears.

**Comment by Lothloryen** [comment]
Quest working as well as #806

**Comment by Frostriver** [comment]
It seems to be bugged again, after killing the last wave of mobs the quest doesn't complete.

**Comment by Frostriver** [comment]
After few testings it seems that the quest doesn't work every time, you need to kill the last npc close to Hourglass and you need to be close to him (near malee distance) in order to get a completion, otherwise the quest doesn't complete.

**Comment by Aridam** [comment]
Confirmed that the credit isn't given if completed farther from the Hourglass.
