### ISSUE TITLE
Fishing in Lordamere Lake

### ISSUE THREAD

**Issue by Shadesmar** [dalaranwow/dalaran-wow#2420]
While fishing in the Lordamere Lake after catching fish when clicking the swimmer the loot window doesnt show. The swimmer vanishes normally after few seconds with the message 'your fish got away' as if one hasnt tried to haul up the fish several times by clicking. Looks like some type of fish is bugged. Tried it with very low fishing skill (where non-bugged fishing loot was often junk and higher fishing skill)

**Comment by Shadesmar** [comment]
i got this bug fishing in orgrimmar and in tanaris. Looks like its not a fish but a type of junk thats bugged because tanaris dont share many fish with the other places

**Comment by Demlock** [comment]
No, this is some sort of core bug. This bug is present pretty much everywhere you fish. Sometimes it just happens so that you can't at all fish up from this blubber. I usually just recast it, without waiting for the message.

**Comment by Golganeth** [comment]
Merge #1275
