### ISSUE TITLE
staff of hecular (quest in hillsbrad foothills)

### ISSUE THREAD

**Issue by Shadesmar** [dalaranwow/dalaran-wow#2421]
The quest works until the end. When the player drives the staff of Hecular into the grounds at the graveyard (by clicking the tombstone and end the quest) the staff should appear in vincinity and summon the undead hecular from the ground to drive fear into the hearts and minds of the alliance town nearby (hecular is of course friendly towards any horde player and hostile towards alliance players).

But nothing happens when ending the quest at the tombstones :<

**Comment by Demlock** [comment]
Confirmed. You still complete the quest though.

**Comment by Rushor** [comment]
fixed in this issue https://github.com/dalaranwow/dalaran-wow/issues/3875
