### ISSUE TITLE
[NPC] orokk omosh (blacksmithing quest)

### ISSUE THREAD

**Issue by Shadesmar** [dalaranwow/dalaran-wow#2422]
orokk omosh (orgrimmar, horde) doesnt show the marker for the (first horde) blacksmithing quest, which is available at lvl 32+ 140 skill. Neither on the minimap nor above his head. The quest is available though after clicking him.

**Comment by Vaxsysl** [comment]
Confirmed, I forgot to report that when skilling up my BS.
http://www.wowhead.com/npc=7790/orokk-omosh

**Comment by Rushor** [comment]
with 140 blacksmith skill i can get his quest. fixed on the liverealm

![GitHub Logo](http://i.imgur.com/g5h6TXd.jpg)
