### ISSUE TITLE
Quest: The Black Knight's Fall

### ISSUE THREAD

**Issue by AgeAgainst** [dalaranwow/dalaran-wow#2423]
I have finished Quest: The Black Knight's Orders on both a Paladin and a Death Knight.  Neither character is able to obtain Quest: The Black Knight's Fall.

According to this link:

http://www.wowhead.com/quest=13664/the-black-knights-fall

It states It's a series, after The Black Knight's Orders and that there are no other requirements to doing this quest.  

This series is required for "Threat from Above", which is required for Champion's Seals.

I have seen others with the quest "The Black Knight's Fall", but nobody can share it with me since the quest is Not Shareable.

Anyone else run into this issue?

**Comment by Lothloryen** [comment]
Hello AgeAgainst,

You do need to complete first the quest "A champion Rises" as you can read through te guide which Malkavia posted on our forums:

http://www.dalaran-wow.com/forums/input-and-assistance/guides-and-tutorials/topic/5421/the-argent-tournament-basic-guide

Or:

http://www.wowhead.com/news=80946/argent-tournament-guide

Thank you.
