### ISSUE TITLE
Fiery Payback (Fire Mage talent)

### ISSUE THREAD

**Issue by Scrybid** [dalaranwow/dalaran-wow#2425]
Hi,

The talent Fiery Payback appears to be working incorrectly. While below the 35% health threshold that the talent requires, Fiery Payback 2/2 is supposed to reduce the cast time of pyroblast by 3.5 seconds and increase the cooldown by 5 seconds. However, the talent only seems to recognize that Fiery Payback is at 1/2 talents, and instead reduces the cast time by 1.75 seconds, and increases the cooldown by 2.5 seconds.

Other people have stated that the talent works correctly if you swap talent specs while you are below the 35% health threshold, and remains working until you log-out. 

A permanent fix would be nice however! Thanks in advance!

**Comment by Golganeth** [comment]
#1778
