### ISSUE TITLE
Combat Duration

### ISSUE THREAD

**Issue by pascagabriel** [dalaranwow/dalaran-wow#2426]
Test performed with Stopwatch macroed into the ability. It takes 5 seconds precisely to drop combat on Algalon. It should take 6 seconds.
http://wowwiki.wikia.com/Combat

**Comment by ntt1** [comment]
Can confirm, please fix this asap!

**Comment by ntt1** [comment]
Quoting so you don't spend time searching from that link: "In PvP, a player will leave combat if they have not attacked or been attacked for 6 seconds, or all the enemy characters that have attacked you are killed."

**Comment by Rushor** [comment]
Game/Unit: Increase Combattimer (in pvpv) by 1 second 

* closes https://github.com/dalaranwow/dalaran-wow/issues/2426
* commit: 1601904f11383071fb74b3cfdb15673759a181a6

**Comment by TeridanDW** [comment]
After ~ 50+ tests on PTR it seems it is 6 seconds now (really hard to time it exacly in-game).
