### ISSUE TITLE
steady shot + heirloom bow

### ISSUE THREAD

**Issue by Shadesmar** [dalaranwow/dalaran-wow#2427]
Steady shot damage is bugged when using the heirloom bow.
This issue should have been fixed with patch 3.1.0 .. why is this a problem on this 3.3.5 server?

**Comment by Vaxsysl** [comment]
And what exactly is the problem? Make a full bug report man, complete with IDs.

**Comment by Shadesmar** [comment]
http://wotlk.openwow.com/item=42946 is the heirloom bow...
using any other bows will increase the damage of steady shot (http://wotlk.openwow.com/spell=56641) significantly

ID? what is this? where do i get this?

**Comment by Vaxsysl** [comment]
http://wotlk.openwow.com/item=42946 >> that 42946 stands for ID in WoW's database.
So, what's wrong with the heirloom bow when using Steady Shot? Be specific, take screenshots, etc. What is the damage like when using some blue 200ilevel ranged weapon compared to the heirloom weapon; or any weapon for steady shot's level for the matter? You say the damage is lower, but to what margain? etc. - you have to be specific.

**Comment by Zincicha** [comment]
![wowscrnshot_052915_011432](https://cloud.githubusercontent.com/assets/12650953/7873303/064458c0-05a1-11e5-9169-7e667fabde1f.jpg)
![wowscrnshot_052915_011533](https://cloud.githubusercontent.com/assets/12650953/7873306/127cedd2-05a1-11e5-8e7d-4959fc97786e.jpg)

**Comment by Shadesmar** [comment]
steady shot damage is calculated by weapon damage + ammo + fixed value + 10% of ap
it looks like the weapon damage component of the heirloom weapon is bugged and steady shot calculates its damage from the lvl 1 heirloom and not from heirloom at present lvl

**Comment by MrAndersonX** [comment]
Yeah, happened to me also. Steady Shot using heirloom bow does less dmg than a normal white hit...nice bug tbh... -1 skill out the flusher.

**Comment by MrAndersonX** [comment]
Definitely needs a fix.

**Comment by robinsch** [comment]
On PTR.
