### ISSUE TITLE
Loot bug during raid

### ISSUE THREAD

**Issue by hairybolz** [dalaranwow/dalaran-wow#2428]
Hello,
I play Scythawr a level 80 Nelf warrior. Today (24/5/15) I organized a VoA 25 man pug and we downed both bosses, the second boss Archavon became bugged during loot distribution and it became impossible to hand out the extra loot to the other players.

I have screen shots of the loot that had dropped, if it's possible could you please give the loot to the people who were there?

![wowscrnshot_052415_181428](https://cloud.githubusercontent.com/assets/12585601/7788429/0f05b1f4-0243-11e5-8809-74d28c3b69f7.jpg)
![wowscrnshot_052415_181418](https://cloud.githubusercontent.com/assets/12585601/7788431/17c82844-0243-11e5-8fbb-af77af8b086c.jpg)

Another issue that came up tonight was the loot from Flame Leviathan during our Uld 25 raid, only 1 piece of loot was able to be looted, the others were bugged:

![wowscrnshot_052415_204755](https://cloud.githubusercontent.com/assets/12585601/7789147/3add554a-025f-11e5-9d16-853f8bc3e7ef.jpg)

Please contact me in game for the loot distribution,

Scythawr

**Comment by ImprezaWoW** [comment]
Issues like this should be reported in-game via ticket. Still an issue nonetheless.
