### ISSUE TITLE
Quest bug: A Race Against Time

### ISSUE THREAD

**Issue by paster2529** [dalaranwow/dalaran-wow#2429]
Inquistor Salrand keep standing on the ground. can't use quest item to proceed.

**Comment by Lothloryen** [comment]
Hello there,

Thank you very much for your report, I have been checked and you are right, this quest got glitched lately. I have already fixed it and it shall be working after the next server restart.

Thank you very much.

**Comment by martijnhaah** [comment]
Can you restart kirin tor soon? :) got to this quest and it is indeed bugged as described.
