### ISSUE TITLE
Quest: Protecting Our Own

### ISSUE THREAD

**Issue by Crispybuilt** [dalaranwow/dalaran-wow#243]
Quest - Protecting Our Own - 10488

Issue: Upon using the quest items on the wolves, they should either turn hostile or friendly and it shold count towards the quest. If they become hostile, you are forced to kill them and they will not count towards the quest. 
They have to count if they become friendly. 

http://www.wowhead.com/quest=10488/protecting-our-own - Horde Version
http://wotlk.openwow.com/quest=10488 - Horde Version

**Comment by Daveonx** [comment]
Quest is working correctly accordingly to several comments on WoWhead and retail videos showing that it counts regardless if they become hostile or not.
