### ISSUE TITLE
[Utgarde Pinnacle] King Ymiron's Dark Slash not working properly

### ISSUE THREAD

**Issue by taralej90** [dalaranwow/dalaran-wow#2432]
King Ymiron (http://www.wowhead.com/npc=26861/king-ymiron) is the last boss in Utgarde Pinnacle (http://www.wowhead.com/zone=1196/utgarde-pinnacle).

One of his abilities - Dark Slash (http://www.wowhead.com/spell=48292/dark-slash) - does not work properly. Instead of periodically using it to deal half of the target's HP, it deals straight 25k shadow damage only when there is just one target left alive.

Additionally, the duration of Screams of the Dead (http://www.wowhead.com/spell=51750/screams-of-the-dead) is reduced by DR, which basically allows players to free-hit Ymiron on his 3-4 cast.

**Comment by taralej90** [comment]
Can anyone assign labels to this and work on resolving it? It's been over 2 weeks :(

**Comment by Rushor** [comment]
already fixed ON ptr.

Scripts/UtgardePinnacle: King Ymiron

- Updated to EventMaps
- Replaced manual summons with proper spells
- Fixed glitch where boss would resume fight/run back to his main target before the ancestor summon roleplay was over (it might still need few adjustments i.e fire on boat is currently missing)
- Implemented damage calculation for spell Dark Slash (http://www.wowhead.com/spell=48292) as previously the spell would do no damage and it's BasePoints is 0

Scripts/UtigardePinnacle: Use a generic spell to calculate the damage for Dark Slash instead

Thanks to @Vincent_Michael for the heads up

* commit: 12e405bedde4f97960ff99fb59d20959be9e6851
* commit: e746e8685c65264cd1ba4495ab7f23f535c88404

**Comment by Zarjofgt** [comment]
Just got shit on by Ymiron, +1.

**Comment by Lothloryen** [comment]
Hello there,

Thank you for the reports and the reminder, this issue has been fixed already and will be corrected on Algalon with the next maintenance.
