### ISSUE TITLE
Broken warrior protection tallents !

### ISSUE THREAD

**Issue by Redrig** [dalaranwow/dalaran-wow#2434]
Hello ! wanted to ask about warrior protection tree. By default in defensive stance i have 95% damage, but with [One-Handed Weapon Specialization] i should have +10% so = 105% total.
Unfortunately when i have all that talent 5/5 completed i still have 95% damage, please help !
Look forward hearing from you.

**Comment by ConradSilverwind** [comment]
I tested that talent couple of days ago and it seems that few abilities do not benefit from it:
1) auto-attack
2) shockwave
3) intercept

**Comment by Redrig** [comment]
Hello! So, those main tank abilities xD Is it possible to do something
about it ? Thank you for help. Look forward hearing from you.

2015-06-07 11:11 GMT+03:00 ConradSilverwind <notifications@github.com>:

**Comment by ConradSilverwind** [comment]
Hello. Tested again ( i do it few more times :P ) and it looks that the real problem is defensive stance damage penalty. It says that it should decrese our damage by 5% but in reality it reduces by around 10%!!!!

Shockwave damage in Battle Stance: 1930
Shockwave damage in Defensive Stance: 1768 ( reduced by 8.4% )

Devastate in Battle Stance with 5 stacks: 1700
Defensive Stance with 5 stacks: 1495 ( reduced by 12%)

**Comment by Redrig** [comment]
Thank you for looking for a problem ), but will you be able to fix it ? it
is hard to level and impossible to arena with that kind of problems ! Thank
you for help. Look forward hearing from you.

2015-06-08 18:36 GMT+03:00 ConradSilverwind <notifications@github.com>:

**Comment by Redrig** [comment]
Hello ! how about warrior fixes ? Is there something new about it ? Strange
that such a little problem with numbers you are solving so long, I like
this server, but don't want to play with 12% damage decrease and it is
impossible to pvp an holding agro at lower levels.

2015-06-09 8:08 GMT+03:00 Ernest Nedelko <ernest.nedelko@gmail.com>:

**Comment by ConradSilverwind** [comment]
There's nothing wrong with stance damage, in case you haven't noticed battle stance gives you 10% arp so that's why the damage difference is so big. Take a hint when somebody deletes their post.
