### ISSUE TITLE
Quest: Protecting Our Own

### ISSUE THREAD

**Issue by Crispybuilt** [dalaranwow/dalaran-wow#244]
Quest Protecting Our Own - 10457

Issue: You get the double credit upon using the item on the "Roots" around the zone. It should count only one, per one root released. Also, there are no "NPCs" released during this quest, there should be "Trees - Druid Form",they should spawn be attackable (they are neutral though) once you use the item on the roots. 

http://www.wowhead.com/quest=10457/protecting-our-own#screenshots
These treants are critical to the defense of the grove, especially if you choose not to make Sylvanaar your home for long.

http://www.wowhead.com/quest=10457/protecting-our-own
http://wotlk.openwow.com/quest=10457

**Comment by Rushor** [comment]
b39afe72e9f860d2875381b297607d67a67aa935
- double killcredit removed

**Comment by Golganeth** [comment]
There are no NPCs released during the quest.
