### ISSUE TITLE
The Ape Hunter's Slave [Quest]

### ISSUE THREAD

**Issue by Zantu** [dalaranwow/dalaran-wow#2440]
http://www.ownedcore.com/forums/world-of-warcraft/world-of-warcraft-guides/208548-guide-reputation-oracles-frenzyheart.html

After handing in "Playing Along" you should get "The Ape Hunter's Slave" Quest dosn't pop tho. Not even as a low lvl quest.

**Comment by Golganeth** [comment]
Sholazar Basin quest chains are working as intended. Read guides if you don't know how to proceed.
