### ISSUE TITLE
[Quest][Northrend] The Key of Warlord Zol'Maz

### ISSUE THREAD

**Issue by Kaporalhart** [dalaranwow/dalaran-wow#2443]
Zol'Maz's whole fight is broken. His charge is very bugged, it deals 3 times its around 800 damage instead of simply one, and instead of coming to you he glitches in the wall near the exit where he stays.

He seems to not be able to get out of his building, but we're supposed to fight him outside. The only way to make him fight is to get inside. 
Plus, your tiki is supposed to be your guardian and help you during the fight, but he only uses melee attacks that are around 100 damage. Not helpful.

And finally, once you manage to beat him, the building closes instantly on you and does not let you a chance to get out because i guess you're not supposed to get inside in the first place. My only way out was my hearthstone.

Add in the fact that the NPCs tiki here are also broken, because they remove 45 % of your stats and deal massive damage to me because i'm a fury warrior (https://github.com/dalaranwow/dalaran-wow/issues/1455), this zone is an absolute nightmare for me.

That could have been worse, i could be a rogue. (although i'm afraid if a rogue has gone through this aswell, he has already hired a hitman against the staff)

**Comment by Rushor** [comment]
works fine for me http://i.imgur.com/WFODnv3.jpg he can leave his building. also the tiki does around 150 damage. i could not found any abilities for him. please link me the spellids and i will add it to the tiki. Closing since the other issues are fixed already. Thank you.
