### ISSUE TITLE
Daily Quest: What Do You Feed a Yeti, Anyway?

### ISSUE THREAD

**Issue by Augur89** [dalaranwow/dalaran-wow#2446]
Hi!
Today I got this random daily quest, "What Do You Feed a Yeti, Anyway?" (id 14112) from Savinia Loresong (NPC 34912) at the Argent Tournament. It seems I have to take "Fresh Chum" (item 47036) from the "Buckets of Fresh Chum" (object 195352) and use it on the water to attract sharks and loot meat pieces.

Well, the item works but the shark (or occasional vrykul) that spawns goes immediately to the sea bed and I can't attack it as it says it is out of range (with me being at melee range).

I think the sharks should stay on the surface and be killable for the quest to work.

By the way, I had the same problem with some sharks on Onslaught Harbor while doing "Blood In the Water" (id 12810), but in this case some of the sharks are targettable.

**Comment by AgeAgainst** [comment]
Confirmed the sharks and vrykul do swim down to the sea bed.    I found out that if you head down a bit under water as soon as you use the chum, the shark will aggro you (even had one swim from the sea bed up to me).  

However, I didn't have an issue targeting or killing any of the sharks.

**Comment by Augur89** [comment]
Just followed your advice and completed the quest easily. Thank you very much!!

The targeting problem was for the sharks already at the sea bed. They wouldn't aggro me and any attack or spell would display the out of range message. Anyway, the solution is now available for everyone thanks to AgeAgainst ;-)

**Comment by Rushor** [comment]
merge with https://github.com/dalaranwow/dalaran-wow/issues/3431
