### ISSUE TITLE
Herbalism in Elwynn Forest

### ISSUE THREAD

**Issue by arvizs** [dalaranwow/dalaran-wow#2448]
I don't know if this is a bug or it's intended to like this, but peacebloom and silverleaf herbs spawn very quickly after gathering them. It is like 1-2 mins. Is it a bug or it supposed to be like this?

Here are some pics:
![wowscrnshot_052815_154340](https://cloud.githubusercontent.com/assets/7989495/7860419/6f59393e-0551-11e5-9f8f-9f12ddb01544.jpg)
![wowscrnshot_052815_154350](https://cloud.githubusercontent.com/assets/7989495/7860421/6f5981dc-0551-11e5-839b-a62c961d7052.jpg)
![wowscrnshot_052815_154459](https://cloud.githubusercontent.com/assets/7989495/7860420/6f5956da-0551-11e5-91cb-f5632b3ad928.jpg)

**Comment by waefre1** [comment]
https://github.com/dalaranwow/dalaran-wow/issues/1345
https://github.com/dalaranwow/dalaran-wow/issues/1208

It's a known issue, to put it bluntly.

**Comment by Golganeth** [comment]
Duplicated.
