### ISSUE TITLE
Nat Pagle, Angler Extreme

### ISSUE THREAD

**Issue by Shadesmar** [dalaranwow/dalaran-wow#2450]
Nat Pagle http://wotlk.openwow.com/npc=20344 should give me this quest http://wotlk.openwow.com/quest=13826http://wotlk.openwow.com/quest=13826
Its not obtainable right now (tested @ lvl 53, horde, after going there with the quest You too good! http://wotlk.openwow.com/quest=6608)
as far as i can remember he should have a store too, selling some fishing items. this store isnt accessible even though the mouse shows the typical mouse-over vendor icon.

**Comment by Augur89** [comment]
I don't know about the store but I did this quest some months ago with my Alliance main. Maybe it's a problem only for Horde characters?

**Comment by Shadesmar** [comment]
>.>  now i was reading somewhere that since patch 3.1.0 this quest is not a requirement for artisan fishing and theres a 'new' skill requirement since this patch. A fishing skill of 225 is required now and everyone who takes the You too good quest which is visible way earlier will get misled. blizzard bug, not dalaran-wow bug

**Comment by AgeAgainst** [comment]
Not sure if the quest was broken in some way with the patch that brought in the Argent Tournament dailies as I finished this quest a couple of months ago, but I can confirm that the vendor aspect is still available for at least 1 item, the Mudskunk Lure, which is only needed if you want to be able to spawn Gahz'ranka.

**Comment by Demlock** [comment]
I did the quest recently with my Orc Hunter. Worked like a charm so it may be a problem with this new release. As for Vendor, he sells one thing (as stated above) and only once you provide him with an item from Zul' Gurub.
