### ISSUE TITLE
Broken Quests

### ISSUE THREAD

**Issue by Aidin22** [dalaranwow/dalaran-wow#2451]
On Ruby Wings
and 
The Frost Wyrm and its Master

**Comment by Augur89** [comment]
Before making a report please check the bug tracker to avoid repeating the same issues over and over. And then make a proper report explaining the issues in detail and with all the information: NPC names, zones, id numbers and such.

Otherwise you're wasting everybody's time (and yours).

**Comment by Aidin22** [comment]
Wow
So rude!

Date: Sat, 30 May 2015 07:48:27 -0700

**Comment by Demlock** [comment]
I fail to see how anything is rude here. The man is right though, first of all, you should check if quests you are writing about are already on the thread and if they are not, you are supposed to give more information about them. Just stating they are broken won't get you anywhere.

**Comment by Aidin22** [comment]
:O
So Rude as well!

Date: Mon, 8 Jun 2015 08:36:38 -0700

**Comment by Golganeth** [comment]
Invalid/duplicated report.
