### ISSUE TITLE
Quest bug: the Yeti Next door

### ISSUE THREAD

**Issue by paster2529** [dalaranwow/dalaran-wow#2454]
Hi

can u check quest The Yeti Next door in Howling Fjord, not sure it's bug or not

**Comment by bucovsky** [comment]
You can complete that quest but the meat that is supposed to drop off those rams around the town has really low drop chance. I spent a lot of time getting those meat pieces but eventually completed the quest. Link to the quest below:

http://wowwiki.wikia.com/Quest:The_Yeti_Next_Door

**Comment by paster2529** [comment]
Thank you so much for your advice. So sry to disturb.
