### ISSUE TITLE
[Mage Talent] Chilled to the Bone

### ISSUE THREAD

**Issue by warcraftgeekygamer** [dalaranwow/dalaran-wow#2457]
The Frost talent for Mages called "Chilled to the Bone" does not seem to be slowing creatures down the additional 10% (5/5): http://wotlk.openwow.com/spell=44571

For example, when Frostbolt is cast against a creature, it will be slowed by 40%. The creature should be slown by 50% as indicated by the talent noted above. I can take screen shots, but at this point, it is either a display issue (ie: not displaying correctly) or the talent is flat out broken.

Again, I just can't tell if this is a display issue or the talent not working. I can take a screen shot, but I don't know what that could prove - other than my UI showing creatures being slowed down to 40% instead of 50%.

**Comment by warcraftgeekygamer** [comment]
This talent is still broken. Creatures are supposed to be slowed down to 50% movement speed with the Chilled to the Bone Frost talent.

**Comment by Golganeth** [comment]
Seems to work just fine. The extra percentage isn't supposed to be shown on the enemy's debuff tooltip.
