### ISSUE TITLE
[Quest] If he cannot be turned

### ISSUE THREAD

**Issue by Kaporalhart** [dalaranwow/dalaran-wow#2459]
Previous issue with this quest : https://github.com/dalaranwow/dalaran-wow/issues/1085

Quest Name: If He Cannot Be Turned
Quest Link: http://www.wowwiki.com/Quest:If_He_Cannot_Be_Turned_(Horde)
Location: Icecrown
Quest Objective: Defeat General Lightsbane
Start NPC: Baron Silver
Start NPC Link:: http://www.wowwiki.com/Baron_Sliver

Issue Present : The three npcs that didn't appear last time do appear now, but they're too weak and the baron is incredibly strong. Upon spawning him, he deals massive damage that you can bearly survive from. Then Vile appears to help but he merely has the time to say his quote before the Baron takes him down. the same happens for the others.

How it should work : The general should hit less hard and use his abilities only from time to time.

**Comment by Golganeth** [comment]
#1085
