### ISSUE TITLE
[Core/System] Cannot Loot Mobs

### ISSUE THREAD

**Issue by kazubla** [dalaranwow/dalaran-wow#2460]
Whilst questing in the storm peaks I am only able to loot mobs half the time. I have so far tested this on elementals, giants outside of ulduar, mammoths and jormugars.

I tried to kill them with dots, without dots, noted whether crits were affected but it does not seem like these are the triggers.

I made a party to ensure that the loot belongs to me.

![wowscrnshot_060115_160059](https://cloud.githubusercontent.com/assets/12538122/7915878/4ef028f4-0878-11e5-8955-7dd22d026d2c.jpg)

It still allowed me to skin the mobs back when I was a skinner.

Edit: After some testing I have found the solution to be ensuring that you last hit with auto attacks. I believe any spell regardless of dots aoe etc last hittng the target will result in this bug

**Comment by Nunsnasty** [comment]
Nice Comic Sans, nerd

**Comment by ConradSilverwind** [comment]
Confirmed. Happens to me sometimes when farming mechanicals in the Storm Peaks.

**Comment by Kaporalhart** [comment]
Weird that it says who the loot belongs to when you're alone. Were you just leaving a dungeon ? Sometimes the game thinks you're still in a group after leaving, might be the source of your problem.

**Comment by kazubla** [comment]
I made the group after I noticed the bug to ensure that the loot belongs to me and not someone else as proof.

**Comment by kazubla** [comment]
Been working for a while but as of 18/06/2015 seems to be working, cheers!
