### ISSUE TITLE
[Quest] The Storm King's Vengence - Gymer Stuck at cage

### ISSUE THREAD

**Issue by ises** [dalaranwow/dalaran-wow#2461]
Quest Name: The Storm King's Vengence
Quest Link: http://www.wowhead.com/quest=12919/the-storm-kings-vengeance
Location: Zul'Drak
Quest Objective: Kill 100 Scourge, kill Algar the Chosen, kill Thrym, kill Prince Navarius

Issue Present:
Player talks to Gymer and becomes Gymer (vehicle) and is unable to move away from the cage area. 

How it should work:
https://www.youtube.com/watch?v=Vjy4V6nBo44
Player talks to Gymer and becomes Gymer (vehicle). Player can then move freely away from the cage.

NOTE: This was working fine for me originally. I ended up going back to Gymer's cage and trying to get a new Gymer to ride. Now I am experiencing the above issue.

**Comment by ises** [comment]
I ended up getting this to work by clicking on the Grymer in the cage and not the one that spawns outside the cage.

**Comment by Golganeth** [comment]
#3511
