### ISSUE TITLE
Boneguard X

### ISSUE THREAD

**Issue by Tarpor** [dalaranwow/dalaran-wow#2462]
Boneguard Footman,
Boneguard Lieutenant,
Boneguard Commander,
Boneguard Scout,

They all have a bug where they randomly start evading and keep following you or just stand still in the middle of nowhere, makes the dailies horrible at the moment.

**Comment by Rlolas** [comment]
It's not only them. There are also valiants/champions, wintergrasp cannons, even chillmaw, who got evade bugged so this must be a general issue.

**Comment by Lothloryen** [comment]
Hello there,

Yes, indeed. It was a general issue generated by the last update while doing some server tests. It has been corrected and it should not happen anymore.

Thank you very much for the report.
