### ISSUE TITLE
[Paladin] Art of War

### ISSUE THREAD

**Issue by Tarpor** [dalaranwow/dalaran-wow#2463]
Greetings, 

I was questing and I noticed that the Art of War bug is back. Exorcism and Flash of Light reset swing timer as said in issue #918 . Hope this can be fixed soon again.

**Comment by Tarpor** [comment]
Fixed

**Comment by Lothloryen** [comment]
Hello Tarpor,

Yes, it has been fixed with this last maintenance.

Thank you.
