### ISSUE TITLE
Quest: Search and Rescue / Drak'tharon Keep 

### ISSUE THREAD

**Issue by vison2** [dalaranwow/dalaran-wow#2464]
is it better to open a new Topic or should I jst write in the old one (already closed)?
Well I did both as you see

https://github.com/dalaranwow/dalaran-wow/issues/675
----------------------------------------------------------------------------------------------------------------
Crispybuilt commented on 7 Oct 2013
Temporary fix added, Kurezel is now spawned inside the instance on normal and heroic.
@CrispybuiltCrispybuilt closed this on 7 Oct 2013
@GolganethGolganeth reopened this on 20 Feb 2014
@GolganethGolganeth closed this on 5 Jan

-----------------------------------------------------------------------------------------------------------------------
Did the Instance on Algalon
NPC was nowhere to be found

**Comment by jobolarius** [comment]
still not working

**Comment by jonanone** [comment]
This has been already fixed and Kurzel will now spawn from one of the cocoons inside the instance. The update will be applied to the live realm soon.
