### ISSUE TITLE
BS recipe bug

### ISSUE THREAD

**Issue by Elufson** [dalaranwow/dalaran-wow#2467]
Some BS recipes sold by vendors are missing out. Aaron Hollman from Shatrath and Eriden form Silvermoon should sell blacksmithing recipes which are almost obligatory for leveling bs 335+. I guess they somehow lost their recipes after the latest server restart, cause I highly doubt that they have been sold out all the time. Please look into this!

**Comment by Kaporalhart** [comment]
Sorry, i've been through this before. I asked to level 450 BS, because it seemed dumb to me at the time, they have been through this aswell. your only way to get to 350 is to craft the yellow-greens. It's doable, you just have to farm a lot of fel iron.

**Comment by Sagrath** [comment]
Fixed
