### ISSUE TITLE
RDF stuck in current instance when requeuing after completing the dungeon

### ISSUE THREAD

**Issue by cover25** [dalaranwow/dalaran-wow#2468]
Title. 

HOW TO REPRODUCE: 

Queue for RDF
Complete the dungeon
Attempt to requeue with the same group inside the instance

The RDF should bug out and break, You will not be able to join your new instance, nor will you be able to leave the RDF without getting a debuff.

**Comment by Lothloryen** [comment]
Hello Cover25, 

Thank you for your report, I am currently working on many things but will definitely take a look to this once I am done with them.
