### ISSUE TITLE
[Quest/Mob] The Battle For The Ebon Hold Unable to kill Patchwerk

### ISSUE THREAD

**Issue by Xuthos** [dalaranwow/dalaran-wow#2469]
For the DK quest "The Battle For The Ebon Hold" I am unable to kill Patchwerk as he evades all attacks. I cannot avoid it since I need to complete this quest to leave Acherus.

http://www.wowhead.com/quest=13166/the-battle-for-the-ebon-hold

**Comment by Stygimoloch** [comment]
Lots of creatures are evade bugged right now, including random normal mobs. I think it's only been like this since the last maintenance.

Some are in strange places, too. I just saw an evading level 8 harpy at the entrance to Orgrimmar.

**Comment by Lothloryen** [comment]
Hello there,

Yes, it was a glitch with the last update, already corrected.

Thank you very much.
