### ISSUE TITLE
[Mob] Evading Mobs

### ISSUE THREAD

**Issue by Rumsteak** [dalaranwow/dalaran-wow#2470]
I found many mobs today there were evading my attacks and/or where completely un-attackable.
They didnt react to...

- direct melee attacks
- normal aggro range
- ranged attacks/spells
- aggroing with other agressive mobs around them

Examples:

http://fs2.directupload.net/images/150603/agaym7oe.png
http://fs1.directupload.net/images/150603/pvfudonv.png
http://fs2.directupload.net/images/150603/grbil6yz.png

Mobs i experienced to be un-attackable:

http://www.wowhead.com/npc=3382/southsea-cannoneer (about 2-3 of 10)
http://www.wowhead.com/npc=3383/southsea-cutthroat (about 2-3 of 10)
http://www.wowhead.com/npc=3384/southsea-privateer (about 2-3 of 10)
http://www.wowhead.com/npc=3461/oasis-snapjaw (about 1-2 of 10)
http://www.wowhead.com/npc=4127/hecklefang-hyena (about 1-2 of 10)
http://www.wowhead.com/npc=5799/hannah-bladeleaf
http://www.wowhead.com/npc=5798/thora-feathermoon
http://www.wowhead.com/npc=5800/marcus-bel

**Comment by Lothloryen** [comment]
Hello Rumsteak,

Thank you for your report, it was a glitch with the last update while doing some server tests. It has been corrected already.
