### ISSUE TITLE
[Quest][Warrior] The Affray 

### ISSUE THREAD

**Issue by trollingpig** [dalaranwow/dalaran-wow#2471]
This q is for warrior berserk stance, 
After you stand on top of grate, the challenge should start, but no npc shows up and the given time runs out and then the q is failed.

**Comment by Chieftain99** [comment]
Same thing here.

**Comment by blaichch** [comment]
Same here

**Comment by oberinjo** [comment]
have the same problem, lvl 70 warrior: Demolition (horde)
i just donated for instant 70 and i find this dissapointing.

**Comment by BlazeRavenHeart** [comment]
http://www.wowhead.com/quest=1719/the-affray
Kill Big Will, then speak to Klannoc Macleod on Fray Island.

     

	Big Will slain

 
	Step on the grate to begin the Affray
Description
If you want to learn from me, then you must first pass The Affray. It is a challenge we on Fray Island like to offer rising warriors who think they're tough, and if you can pass this test then I'll know you are.

To begin, walk into the middle of that crowd yonder and step on the grate. That'll tell Twiggy Flathead you're ready, and he'll send challengers against you.

Beat all the challengers and he'll call out Big Will. Kill Big Will, and return to me in the time we allow.

It only seems to complete half of the quest. The NPC Big Will doesn't show up for the time you are given (10 mins).

**Comment by PhlashDrago** [comment]
Can confirm, I'm having the same issue with this quest.

Challengers and Big Will don't show up after you stand on the grate for the whole 10 minutes.
Another warrior was in the area, he was not able to finish the quest either.
Also tried restarting the quest, no changes.

**Comment by bartcore123** [comment]
I am having this problem too

**Comment by blastedlandss** [comment]
Still bugged and no one is interesting...

**Comment by yohohomafaka** [comment]
have the same problem

**Comment by Rushor** [comment]
DB/Quests/Kalimdor: The Affray.

If the warrior goes to far, the event will reset.

* closes https://github.com/dalaranwow/dalaran-wow/issues/2471
* commit: 3c6578c2c84d7fa0cecd72f1cdfeb0186ef88022

**Comment by TeridanDW** [comment]
Works as intended on ptr.

Note to players: If you manage to relog after you have stepped in the arena and log back in after few minutes, the quest will reset (including the part you have already done - stepping on arena) and you will need to retake the quest in order to get credit for stepping in arena again.
