### ISSUE TITLE
[Mob] Barak Kodobane

### ISSUE THREAD

**Issue by Rumsteak** [dalaranwow/dalaran-wow#2475]
Mob-Name: Barak Kodobane
Zone: Northern Barrens
WoWhead: http://www.wowhead.com/npc=3394/barak-kodobane

Needed for the quest: "Kolkar Leaders"
Quest WoWhead: http://www.wowhead.com/quest=850/kolkar-leaders

When you pull his aggro, he will attack you with the bow and will continue his normal walk from the platue upwards to his small tower and back, while still shooting you with the bow.
If you outrange of his bow-reach, he will de-aggro instantly.

If you come into melee-range he will react normally, net you, attack you with a sword.
He also has a very short de-aggro range then.

**Comment by Rushor** [comment]
always attacks me propperly, cannot confirm this anymore http://i.imgur.com/Aw58zOQ.jpg
