### ISSUE TITLE
Class#Hunter [Survival] Talent - Lock and Load

### ISSUE THREAD

**Issue by lewtorz** [dalaranwow/dalaran-wow#2476]
After 55 immolation Trap ticks, 65 Black Arrow Ticks, 90 Explosive Trap Ticks on training dummies and a naxx 25man raid I didn't get 1 lock and load proc. It is only triggering from freezing arrow freezing something.

**Comment by keggarr** [comment]
This is already in the bug tracker

https://github.com/dalaranwow/dalaran-wow/issues/2406

**Comment by Golganeth** [comment]
Duplicate of #2406 indeed.
