### ISSUE TITLE
Quest : Heroic: All Is Well That Ends Well

### ISSUE THREAD

**Issue by Jamezs** [dalaranwow/dalaran-wow#2480]
Your recent updates to the server has broken the quest Heroic: All Is Well That Ends Well www.wowhead.com/quest=13819
After obtaining the item Reply-Code Alpha http://www.wowhead.com/item=46053 when someone try to use it to start the quest it says "You don't meet the requirements for that quest"
This is a major problem because this quest provides a Best in Slot item for many classes.

**Comment by Tirion52** [comment]
I have the quest item in my inventory for like a week now....i logged today and i still can't accept the quest.

**Comment by HelloKitty** [comment]
@MalkaviaDW Did you find an information on the expected behavior of this quest? It had a quest_template_addon listing requiring the a quest from the Algalon chain. This is still an issue on TC as of Nov. 2016. What did you find?
