### ISSUE TITLE
Hunter Pet [Autocast Issue]

### ISSUE THREAD

**Issue by Finnebar** [dalaranwow/dalaran-wow#2481]
Hello,
I recently noticed that my hunter pet (cat) won't use special abilities properly after being summoned unless I command it to attack via the pets "Attack" command. 
It doesn't seem to matter wether it is a summoning after using "call pet", dismounting or changing continents via ship/zeppelin.

For example: Whenever I use a skill to force a dismount, lets say attacking a foe by targeting it and using "Arcane Shot" or "Serpent Sting", my pet will attack said foe automatically due to its defensive stance, however it wont use dash to reach it more quickly and once it attacks it takes in bitween 1-3 white hits before it uses its first special ability, and then most of the time it won't be able to gain enough threat anymore.

**Comment by Golganeth** [comment]
#1021
