### ISSUE TITLE
Deathknight  talent Night of the Dead  rebroken.

### ISSUE THREAD

**Issue by burkey6** [dalaranwow/dalaran-wow#2482]
The talent "Night of the Dead" is once again not working due to the recent patch issues.
Instead of reducing area of effect damage by 90% the ghoul is once again taking 100% area of effect damage.
Currently this is making the spec useless again in Pve due to the Dps loss suffered from the pet dying frequently.

**Comment by LiNK2088** [comment]
Confirmed :(

**Comment by Lothloryen** [comment]
Hello there,

Yes, I am aware of it. These fixes shall be deployed during the next few days again.

Thank you.

**Comment by LiNK2088** [comment]
Also Lothloryen, if you are reading this, Death & Decay is dropping through the floor again

**Comment by Lothloryen** [comment]
Deployed already, thank you very much.
