### ISSUE TITLE
Will of the Forsaken doesn't share a CD with PvP trinket

### ISSUE THREAD

**Issue by pascagabriel** [dalaranwow/dalaran-wow#2485]
I am aware this has been fixed a long time ago, however it seems it's occurring again. Using Will of the Forsaken first does not put your PvP trinket on a .cooldown

**Comment by Lothloryen** [comment]
Thank you for the report, I shall re-apply the patch and it will be corrected after the next update.

**Comment by Lothloryen** [comment]
Deployed already, thank you very much.
