### ISSUE TITLE
Hunter Spell - Deterrence with Big Bang

### ISSUE THREAD

**Issue by Hunspdt** [dalaranwow/dalaran-wow#2486]
On Algalon encounter, hunters can no longer stay outside and block Big Bang with deterrence. Hunters was able to stay outside every time Algalon was casting Big Bang but now it simply does not work.

**Comment by Vidmantasaf** [comment]
it was bug that they were able to detterence that, all skills that remove the damage completely (detterence/bubble) does not count as soaking
