### ISSUE TITLE
[NPC] Nedar, Lord of Rhinos

### ISSUE THREAD

**Issue by Loutmourne** [dalaranwow/dalaran-wow#2487]
NPC Nedar, Lord of Rhinos [ID:25801] is supposed to be spawning in Borean Tundra, riding around on his mount "Lunchbox" around 47, 44. On Kirin Tor server, there are 3 copies of him instead, 2 without a mount. First additional copy is spawned around 44.9, 45.0, second is approximately at 48.1 44.4
His dismounted copies, like an original NPC, use abilities and do same damage, can also be used to complete quest "Nedar, Lord of Rhinos..." [Quest ID:11884] although since player is required to kill his mount as well, they will have to seek "original" Nedar.
![wowscrnshot_060715_011924](https://cloud.githubusercontent.com/assets/12653828/8024572/b2d3b22e-0d40-11e5-9f27-2e8e29fd00c6.jpg)
![wowscrnshot_060715_011944](https://cloud.githubusercontent.com/assets/12653828/8024574/b8e60680-0d40-11e5-948a-4b89e7a9e418.jpg)

**Comment by Golganeth** [comment]
"Lunchbox" doesn't attack players, minor issue.
