### ISSUE TITLE
[Shaman] [Spell] Grounding Totem

### ISSUE THREAD

**Issue by Crix1123** [dalaranwow/dalaran-wow#2489]
First of all, 
I'd like to say I'm more than happy to see it work so well overall but would like to report one brand of spells that bypass it.

Hunter traps, which should be destroyed along with the totem and their effect negated.

The way it is now, you get the full effect of the traps that trigger with no trouble, regardless of the presence of grounding totem. The totem itself stays, but I'd very much love for it to work as intended because brings so much to high-end PvP. 

Cheers and keep up the good work.

**Comment by Rushor** [comment]
https://github.com/TrinityCore/TrinityCore/pull/15119
https://github.com/TrinityCore/TrinityCore/pull/16193

**Comment by Rushor** [comment]
the fix is already on PTR.

Core/GameObjects: Fixed an issue where traps were not redirected to Grounding Totem
commit: 42594c16873328e5e17121597e13f5db95ed12ab

**Comment by Lothloryen** [comment]
@TeridanDW @AttendantTock Could you check the status of this issue on PTR? Fix was already there.

**Comment by TeridanDW** [comment]
Works as intended on PTR.
