### ISSUE TITLE
Wintergrasp Graveyard and Night elf ghost

### ISSUE THREAD

**Issue by tkr2099** [dalaranwow/dalaran-wow#2490]
As of about 1 week ago, the auto-resurrection at the alliance camp graveyard in Wintergrasp does not. The only way to resurrect is to run to your corpse or spirit rez. Additionally, while the other races get a flying mount as a ghost in WG, Night Elves appear as a sprite which is much slower.

**Comment by Golganeth** [comment]
Already fixed.
