### ISSUE TITLE
Quest: Imp Delivery

### ISSUE THREAD

**Issue by Zantu** [dalaranwow/dalaran-wow#2491]
Go to Scholomance, release imp in jar, wait, and you get a complete.
http://www.wowhead.com/quest=7629/imp-delivery

Not working. imp does nothing, and just stands there. no complete, no nothing :(

**Comment by bojan112** [comment]
i had same problem, tryed everything imp just stands there and does nothing

**Comment by Daveonx** [comment]
Tested and currently scripted and working.
