### ISSUE TITLE
[Quest] The Tome of Valor - Daphne Stillwell

### ISSUE THREAD

**Issue by fearnostigma** [dalaranwow/dalaran-wow#2493]
Hey how goes it!

I would first like to thank you a ton for putting this up here, I play on algalon Elivia paladin level 20, and the find daphne part of the quest appears to be bugged...

ty

**Comment by Sagrath** [comment]
https://github.com/dalaranwow/dalaran-wow/issues/2452
Open a Ticket and the Gm s will help you with it
