### ISSUE TITLE
[Northrend][Dragonblight][Quest] Something that doesn't melt. 

### ISSUE THREAD

**Issue by rayzero** [dalaranwow/dalaran-wow#2494]
Last referenced at #1412, was said to have been fixed but still seems to be a problem - spawn rate for the bones is very low.

**Comment by darkwulfv** [comment]
Confirmed, still having this problem; there are only 4 bone spawns and they take a long time to come back. Definitely not fixed.

**Comment by deltafoxnine** [comment]
darkwulfv is right, only 4 spawn locations, and very low spawnrate

**Comment by Raadfar** [comment]
The current [4 spawn locations](http://wotlk.openwow.com/maps=65:623291623300571240575239) with a timer of 5 minutes for each [Splintered Bone Chunk](http://wotlk.openwow.com/item=36730).

**Comment by Golganeth** [comment]
The fix will be applied to live realm soon. It could use some extra chunks here and there, especially on the left side bones.
