### ISSUE TITLE
[Mage] [Spell] Blink

### ISSUE THREAD

**Issue by Alver1** [dalaranwow/dalaran-wow#2495]
http://wotlk.openwow.com/spell=1953

Blink functions differently on Dalaran-WoW as opposed to retail. Sources of this report include my personal experience as a mage on Algalon + tests and comparisons done here and on retail.

Attempting to Blink when there is a higher terrain in front of you is troublesome. It used to be a problem before the patch, but now there are more situations where this problem occurs, most notably in raids. Examples of this are floor slabs in Antechamber of Ulduar or Heigan's platform in Naxxramas. Blinking up the stairs should always be possible it is not here however. Using Blink when facing stairs which are going up either brings you next to them or does not move you at all. When the stairs are going down Blink does move you a few yards if you are on the stairs but a much shorter distance than it should. If you're standing just in front of them it will either not move you at all or bring right next to them. Same goes for hills, Blink somewhat works, but only for a very short distance or not at all depending on how sloping the hill is. Very glitchy in tunnels such as the one leading to the flag room in Warson Gulch. Feels like it is using some wrong formula based on the character's and destination's Y coordinates. 

There is also a problem sometimes when blinking towards obstacles which are closer than 20 yards to where the mage is facing. While it should bring the mage as close as possible to the obstacle, it sometimes does not move you at all. There are also some objects which you sometimes Blink into. Like the orb decorations in Antechamber of Ulduar or an occasional random wooden box. You can exit them by walking however.

The way Blink functions in retail: when Blink is used it checks the path 20 yards ahead of the mage regardless of height and it succeeds if it is possible to walk to the destination of it and teleports you to it. If not - it teleports you as far as it is possible to walk forward up until 20 yards range. For example, if you're attempting to use Blink uphill which you normally wouldn't be able to climb - it fails, but if the hill is climbable, Blink will bring you 20 yards forward the walkable terrain.

Also, gaps like the 'sewer' around Ironforge or the gaps in Deeprun Tram can't be blinked over in retail. They can in here. Probably a bug, but certainly something I appreciate :)

I realize that with all the issues which popped up in Ulduar recently and with the upcoming release of ToC you barely have any time left for fixing class bugs but when by any chance you have some time on hand - I can assure you that the mages of Dalaran-WoW would appreciate some attention to Blink greatly, as it is one of those abilities which 'make' the class. Thank you in advance! :)

**Comment by Kaporalhart** [comment]
I have a lvl 100 mage on Warlords of Draenor, and although some of those don't seem normal, i can tell that blink does not work as often as i want to. Sometimes it will not work because -???- and every now and then your huge powers of 8 years playing will still get stopped by a deadly and unstoppable blade of grass.

**Comment by Alver1** [comment]
Did some more testing in various caves and well, I have to say that it is literally impossible to successfully Blink inside a cave unless terrain is absolutely even 20 yards ahead of you (which in almost all caves is usually not the case). What usually happens is you just appear either in the same spot you blinked from, few yards ahead, or sometimes it is going to Blink you up through textures and you just fall down to your old location afterwards.

**Comment by n-ghost** [comment]
Confirmed, Blink, as glitchy as it is by design, still became much worse since the last update. 

Among other things, more often than not when you try to blink indoors, it will send you through the walls or even through the ceiling if the path leads downwards. Especially annoying inside dungeons.

**Comment by Sedare** [comment]
Blink was always buggy in this patch on live servers. You could never blink across ground textures when it changed. As far as I am concerned, this aspect of blink is live like.

How ever when you are in mid air, your reference point on the x,y axis grid, on this server is directly corelated to the ground location directly under your character. No matter how far. So if you want to get to the ground, using blink instantly takes you to that coordinate at ground elevation, as a coding reference, and puts you 20 yards from that spot. I found this handy when doing world PVP and I bait someone in the air 4 years up, and I just blink down and drink. This is a bug. Blinking in the air should move you 20 yards in the air. No elevation change should take place, and it should also reset your falling elevation. timing the jumps in WSG from the top to the flag, and aiming at the flag and blinking 2 yards from the ground prevented falling damage on live servers. Blink as it functioned on live had a built in elevation detection. Here it does not. Hence the glitchy floor porting at times.

This same coding error could also be related to the issue about leaving your mount in the air and falling to your death 1 yard above the ground. Elevation is not taken into consideration in some of the coding here. :)

**Comment by Rushor** [comment]
already on ptr:

Correction for blink

Add available blink on Transport
* using Position

fix travis

Blink v4
- -[x] blink in abyss
- -[x] blink by path ( rechecking each step )
- -[x] where player can walk - blink will available there
- -[x] implemented check on dynamic objects (locked doors and etc)
- -[x] implemented total path of blink.

video : http://www.youtube.com/watch?v=wpymzrkwNTg

* commit: ee052b2d727a9e724050edf5c4cd6b490f06d605

@Lothloryen this was fixed (27.02.2016 00:12:06) in trinitycore

**Comment by datbunneh** [comment]
Oh boi, so excited to see this live. :]

**Comment by TeridanDW** [comment]
Regarding:

> Add available blink on Transport

What does that exacly means? Because i can now blink on platforms (moving) but always fall under it.
For transporting ships/zeppelins spell will always fail to blink.
![image](https://cloud.githubusercontent.com/assets/6797611/24753776/4ede98d2-1adc-11e7-8f13-45d5659b00dc.png)

Blinking on platform after Lady Deathwhisper (while the platform in between point A and B) will result in interesting "effect"
![image](https://cloud.githubusercontent.com/assets/6797611/24753403/a50d86b6-1ada-11e7-9974-4017bfa8e5c8.png)
![image](https://cloud.githubusercontent.com/assets/6797611/24753488/fca37a16-1ada-11e7-8733-1e7eb10d3370.png)
![image](https://cloud.githubusercontent.com/assets/6797611/24753534/38fabdbc-1adb-11e7-9b0f-a3e293b3e5ef.png)
And so on, you get the idea

 - There is a strange element while binking the spell is trying to push the Z of your destination higher (which results in almost never fall undermap) but it incorrect
You can see this effect clearly when you are blinking in deep waters.

However this is a big improvement to what we have ingame now, so marking as:

**Comment by Skipslegdays** [comment]
I don't think this is fully fixed yet. There are so many places where blink will just make you stay in place.
- Any time there is elevation (Bridges in Arathi Basin, whether blinking up or down will make you stay in place)
- Bumps in the ground, like at the entrance of the Horde Tavern in Dalaran. Can't blink past those
- Ground textures in Ruins of Lordaeron will also stop blink
