### ISSUE TITLE
Kalimdor: Gerenzo's Orders

### ISSUE THREAD

**Issue by Demlock** [dalaranwow/dalaran-wow#2496]
There is a quest in Stonetalon Mountains' Windshear Crag Mines. A NPC under the name Piznik (http://wowwiki.wikia.com/Piznik) offers a quest Gerenzo's Orders (http://wowwiki.wikia.com/Quest:Gerenzo%27s_Orders) which requires you to protect him for around 5 minutes before the quest is completed. The event is desctibed on WoWhead: http://www.wowhead.com/quest=1090/gerenzos-orders

At the moment, no event starts, nor is the quest set to autocomplete.

**Comment by Golganeth** [comment]
#590
