### ISSUE TITLE
Ulduar 25 man

### ISSUE THREAD

**Issue by 1repmax** [dalaranwow/dalaran-wow#2498]
I know you said that we shouldn't report any Ulduar related bugs, but since it has been unraidable for the last 4 ID lockouts I will do it.
XT Hard mode the Life sparks sometimes don't spawn at all. The void zone doesn't do any damage when you stand in it, the pull-in part still works.
On Freya HM she doesn't gain any self healing, tho the stacks are there. Basically you can just pop heroism on start of the encounter and nuke her in around 1 minute. The small adds don't do any damage when they explode. Don't know about other add waves.
On Mimiron HM his first phase has 3x more HP than it was before. On second phase he has less HP and the fires most of the time don't spawn. Don't know about phase 3 and phase 4.
On FL you can't pick up pyrite as a gunner because you get kicked out when you pick it and demolisher gets bugged. To get it you have to drive over it. You can't interrupt his AoE spell with Sieges.
On Auryaia you can polymorph the cats, which isn't blizzlike I suppose. But we did it since they were melee hitting the tanks for around 35k each.
Don't have information about any other bosses since the raid is on Wednesday. Good luck!

**Comment by Lothloryen** [comment]
Hello 1repmax,

I had some reports on the e-mail with this and some more issues generated by the last update so I am already working on all of them.

Thank you very much for your collaboration.

**Comment by 1repmax** [comment]
I will see how tomorrows raid goes and post if I see something terribly awful.

**Comment by 1repmax** [comment]
Malady spawning inside the brain room on YS 25 man HM. No idea about normal mode tho.

**Comment by Lothloryen** [comment]
Hello,

Has this issue been reproduced during the past raid lockout?

Thank you.

**Comment by 1repmax** [comment]
Hey!
Sorry, won't be able to answer because I have stopped playing the game and
deleted the character
Good luck on your work!
