### ISSUE TITLE
[Northrend][Howling Fjord][Quest] Drop it the rock it!

### ISSUE THREAD

**Issue by InvincibleEagle** [dalaranwow/dalaran-wow#2499]
I drop the banner, but nobody appears to defend it from.

**Comment by warcraftgeekygamer** [comment]
I can also confirm this quest is completely broken. When you drop the flag, there are supposed to be npc's who come to attack. The flag that you drop also follows you around as if they were another character. This is not supposed to happen.

Quest: http://www.wowhead.com/quest=11429/drop-it-then-rock-it
Video: https://www.youtube.com/watch?v=0sfbXoBsHsE

The links I have provided shows you how the quest is supposed to work.

**Comment by bucovsky** [comment]
I can also confirm that this quest does not work.

**Comment by Nikvet** [comment]
Confirmed.It's bugged.

**Comment by Sagrath** [comment]
https://github.com/dalaranwow/dalaran-wow/issues/363
