### ISSUE TITLE
NPC: Verog the Dervish spawn buged

### ISSUE THREAD

**Issue by Sagrath** [dalaranwow/dalaran-wow#25]
Verog the Dervish http://wotlk.openwow.com/npc=3395
You have to kill the other Centaurs around the command tent until Verog will spawn, but dosnt spawn.

**Comment by Golganeth** [comment]
Works great. Verog spawns after you kill some moderate amount of centaur.

![image](https://cloud.githubusercontent.com/assets/5057942/5669462/f87afb8c-9777-11e4-91df-38ead15392e3.png)
