### ISSUE TITLE
Spell:  Toxic Saliva

### ISSUE THREAD

**Issue by Sagrath** [dalaranwow/dalaran-wow#250]
http://www.wowhead.com/spell=7125/toxic-saliva

Inflicts 20 [+ 10% of SpellPower] Nature damage to an enemy every 3 sec. Also drains 20 mana every 3 sec. Lasts 30 sec.

It does not leech the players mana

**Comment by Rushor** [comment]
it drains stuff periodically
http://i.imgur.com/qlsxl8n.jpg - while ticking
http://i.imgur.com/kQMuR3R.jpg - while regenaration
