### ISSUE TITLE
Ormorok the Tree-Shaper (The Nexus)

### ISSUE THREAD

**Issue by ldmccartney** [dalaranwow/dalaran-wow#2500]
No matter where you stand you get knocked up by the bosses spikes.

**Comment by warcraftgeekygamer** [comment]
https://github.com/dalaranwow/dalaran-wow/issues/2502



I can also confirm this. As a level 71 Mage, I was with 4 others including a level 77 Death Knight. All of us were being one or two shot by the spikes - no matter where you stand you take extremely high damage.

http://www.wowhead.com/npc=26794/ormorok-the-tree-shaper
http://www.wowhead.com/npc=26794/ormorok-the-tree-shaper#abilities
http://www.wowhead.com/spell=47958/crystal-spikes

Video showing you how the fight is supposed to work: https://www.youtube.com/watch?v=ZnFmRF3ea-k

**Comment by Lothloryen** [comment]
#2502
