### ISSUE TITLE
[NPC] Interaction Between: Tillinghast's Plague Canister & Proto-Drake Egg

### ISSUE THREAD

**Issue by ashido96** [dalaranwow/dalaran-wow#2501]
If the Proto-Drake Egg is damaged before Tillinghast's Plague Canister is used on the egg both a Proto-Whelp and a Plagued Proto-Whelp spawn instead of just a single plagued Plagued Proto-Whelp.

If the Cannister is used before the egg is damage it works as intended and only summons the Plagued Proto-Whelp.

http://www.wowhead.com/item=33418/tillinghasts-plague-canister
www.wowhead.com/npc=23777/proto-drake-egg
http://www.wowhead.com/npc=23688/proto-whelp
http://www.wowhead.com/npc=24160/plagued-proto-whelp

**Comment by belegija** [comment]
Proto-Whelps movement is not right. Proper movement can be seen on this video https://www.youtube.com/watch?v=TqH8t8rqS2g .

**Comment by Rushor** [comment]
DB/Creature: Proto-Drake Egg - Only summon 'Proto-Whelp' on death by damage, only summon 'Plagued Proto-Whelp' on death by 'Tillinghast's Plague Canister'

* closes https://github.com/dalaranwow/dalaran-wow/issues/2501
* commit: 1682fc9b7e283f5aedd6755ed8c96ff0c5a17036
