### ISSUE TITLE
[NPC] Missing Ironforge Quartermaster

### ISSUE THREAD

**Issue by Alver1** [dalaranwow/dalaran-wow#2504]
In Argent Tournament Grounds, inside Silver Covenant Pavillion NPC Derrick Brindlebeard (Ironforge Quartermaster) is not present. Quartermasters of other 4 Alliance cities are there.

Proof: http://postimg.org/image/c40bbrg73/
NPC: http://wotlk.openwow.com/npc=33310

**Comment by Augur89** [comment]
I can confirm this and it has been an issue for several days.

**Comment by Alver1** [comment]
After last maintenance the NPC is now present. Thank you.
