### ISSUE TITLE
Herald of War and following Wrathgate quests cannot be completed

### ISSUE THREAD

**Issue by Vandreth** [dalaranwow/dalaran-wow#2506]
After starting the quest "Herald of War" from Saurfang in Warsong Hold, he is usually to be scripted to open a portal to the phased version of Orgrimmar to speak with a phased version of Thrall to start the remaining quests to eventually "The Battle for Undercity" where we kill Varimathras.

Is this a bug from the latest reset or has this important questline always been this way?

**Comment by Sagrath** [comment]
https://github.com/dalaranwow/dalaran-wow/issues/2404
