### ISSUE TITLE
Pyrewood Ambush the Npc not spam

### ISSUE THREAD

**Issue by zenaeq** [dalaranwow/dalaran-wow#2507]
Ok this is a Quest line, i didn´t finish cuz i need the misión Pyrewood Ambush, the npc is under the building he must spam inside the building when the player talk whit Deathstalker Faerleia, Faerleia dont show me the option for get prepared.

**Comment by Sagrath** [comment]
https://github.com/dalaranwow/dalaran-wow/issues/2169
