### ISSUE TITLE
[Paladin] Seals on absorb effects

### ISSUE THREAD

**Issue by Vekt** [dalaranwow/dalaran-wow#2509]
I re-open this issue because it's back...

The Seal of Righteousness (http://wotlk.openwow.com/spell=25742) doesn't work on absorbs such as the Power Word: Shield, the absorb shield of Stoneclaw totem or the Ice Barrier. Thus it is way harder to break these absorb shields.

#1813

**Comment by Lothloryen** [comment]
Hello Vekt,

Okay, thank you very much, I shall take a look to this issue.

I am currently re-working and fixing Ulduar but I will focus myself on PvP after ToC is released.

**Comment by Vekt** [comment]
Cool, good luck with that then!
Oh and while we're talking about PvP, have you seen this issue : #2398 ? It's a minor thing but shouldn't be long to fix I guess.

**Comment by Lothloryen** [comment]
Hello again,

This issue has been corrected, the patch will be applied with the next scheduled maintenance.

Thank you very much.
