### ISSUE TITLE
[Quest] Cold Hearted

### ISSUE THREAD

**Issue by unb3l13v3r** [dalaranwow/dalaran-wow#2510]
Zone: The Storm Peaks
I'm unable to remove disguise from previous quest, because of that I can't mount up to get to the dragons. I managed to complete this first time (1/3 Freed Proto-Drakes, 3/9 Rescued Brunnhildar Prisoners), but when I tried to do it second time, the disguise wouldn't disappear.

**Comment by 7193224** [comment]
And this quest mounts the flight speed problem~~

**Comment by xxauroraxx** [comment]
If you go to the cave with jormungar, you can mount up just outside of it

**Comment by Golganeth** [comment]
#2412
