### ISSUE TITLE
[Fishing] No fish are hooked

### ISSUE THREAD

**Issue by glitterlance** [dalaranwow/dalaran-wow#2513]
![wowscrnshot_061115_210612](https://cloud.githubusercontent.com/assets/12849501/8114546/151091d8-107e-11e5-8d90-a570fda0f922.jpg)
While fishing occasionally there is a message "no fish are hooked" right after I open the loot window. I spent 12 hours trying to fish old crafty in Orgrimmar as Alliance (yes, that's really painful), when I finally caught him due to that bug I was unable to loot him. I could click the fish, click okay for the "Looting this item will bind it to you" but I received no loot nor achievment.

**Comment by Golganeth** [comment]
Merge #1275
