### ISSUE TITLE
[Classic][Quest] Alien Ecology

### ISSUE THREAD

**Issue by xxauroraxx** [dalaranwow/dalaran-wow#2515]
You are tasked with taking an item (Unused Scraping Vial) to a specific location (hatchery wall) and using it near a game wall. The item reports that no location is valid.

The comments are highly relevant. http://www.wowhead.com/quest=3883/alien-ecology

**Comment by darkwulfv** [comment]
The quest does work; like the comments say, you have to use it in the middle of the room, not against the walls. The misleading quest text is the fault of Blizz, not Dalaran-wow.

**Comment by xxauroraxx** [comment]
I specifically did try it in the middle of the room.

**Comment by darkwulfv** [comment]
I don't want to sound patronizing, so I apologize if I do, but were you in the correct room? There's multiple chambers but only ones with the hanging orange sacs will work.

Aside from that, if there was no where in any of the hatcheries that the vial worked, then it's possible the quest somehow got bugged in the last patch, as I've had it work multiple times before.

**Comment by xxauroraxx** [comment]
Yeap. I've done this quest plenty of times on retail, knowing where to go. When it didn't work, I tried the other rooms.

**Comment by xxauroraxx** [comment]
For whatever reason, this quest worked on the second attempt at it. If you keep getting errors, its possible the zone may be REALLY small in the hatchery room.
