### ISSUE TITLE
[Quest] The Wayward Apprentice - NPC Missing

### ISSUE THREAD

**Issue by PVPieter** [dalaranwow/dalaran-wow#2518]
NPC Apprentice Mirveda is not at the location that the question mark says.
http://wotlk.openwow.com/quest=9254

**Comment by ashido96** [comment]
Please use the search function, this is the 6th post for this quest.

**Comment by kreaper187** [comment]
she's there but she is spawned underground. this command confirms it
/target Apprentice Mirveda
/run SetRaidTarget("target", 8)

**Comment by Ryan295** [comment]
This is still an issue. Specifically with the NPC Apprentice Mirveda. She is still stuck underneath the ground and cannot be interacted with.

**Comment by Sagrath** [comment]
fixed
