### ISSUE TITLE
[Spells/Auras] Lok'lira's Bargain

### ISSUE THREAD

**Issue by unb3l13v3r** [dalaranwow/dalaran-wow#2519]
I got this disguise while doing quests in Brunnhildar Village. Disguise's supposed to disappear when I get out of village, but it doesn't. I tried everything: relogging, dying, right clicking on it but I just can't remove it. It's such pain in the ass because I can't mount up.
![wowscrnshot_061315_174116](https://cloud.githubusercontent.com/assets/9680458/8144926/869e3adc-11f3-11e5-8548-3ecc5a0adbbc.jpg)
As you can see I'm in the middle of Dun Niffelem with a disguise miserably trying to do a quest.

**Comment by ashido96** [comment]
It makes you keep the disguise through the whole area, the quickest way to get rid of is to slowly go down some of the cliffs on the back/south side of the village (can be done losing about 50% of your health) get up on your flying mount and go to your next objective.

Also, unsure if not being able to mount while disguised is intended or not? bug here?

**Comment by unb3l13v3r** [comment]
This worked, thank you! :D

**Comment by Cone182** [comment]
still cant mount there

**Comment by Vission** [comment]
Hi, this shows exactly, that it should be possible to mount up even with this "shapeshift". https://youtu.be/qrp6CsQeTXA?t=48s
Thanks for fixing this, it's a little annoying to walk outside the village everytime...

**Comment by Golganeth** [comment]
#2510
