### ISSUE TITLE
Threat bug

### ISSUE THREAD

**Issue by Alexandre-Simao** [dalaranwow/dalaran-wow#2523]
Wen leveling and agroing mobs, the distance they travel is insane, agro should be determined by total damage, not percentage of health, if you take 20% of a mobs health(wich happens with thorns retri aura etc) the mobs will chase you to infinity and stack until they eventualy kill you.

Hope i helped and thanks for the great server, you guys are amazing.

**Comment by Golganeth** [comment]
#682
