### ISSUE TITLE
Scroll buffs overriding non-scroll buffs

### ISSUE THREAD

**Issue by M0dinstaller** [dalaranwow/dalaran-wow#2524]
A druid's mark of the wild buff (rank 8) is overriden by a stamina or an agility VII scroll when it shouldn't.
Buffing one of these 2 scrolls deletes the previous mark of the wild and prevents a new one from being cast.

I suppose the bug happens on any scroll and any class buff (like a stamina scroll blocking a priest buff, or an intellect scroll blocking a mage buff ... or the other way around if the player buff is stronger than the scroll buff) but I don't have the resources to test.
It worked properly before. I was able to have 1 scroll buff along with any other non-scroll buff.

**Comment by ntt1** [comment]
Not a bug, Its supposed to be that way.

**Comment by M0dinstaller** [comment]
Alright, thought it was. Couldn't find a single raid video with scroll buffs and even though I couldn't find the change documented on the wiki a few friends told me scrolls became obsolete in wotlk. Oh well, more space in my bank.
Closing the issue, forgive me.
