### ISSUE TITLE
[Northrend] [Quests] Steam Tank Surprise

### ISSUE THREAD

**Issue by warcraftgeekygamer** [dalaranwow/dalaran-wow#2527]
As of June 15, 2015 the quest "Steam Tank Surprise" cannot be completed. You are able to get into the tank and you are able to drop off the two soldiers. Using the ability to drop off a Gnome does NOT work - at all. 

Video showing how it is supposed to work: https://www.youtube.com/watch?v=uCKNCfOLDy8
wowhead: http://www.wowhead.com/quest=12326/steamtank-surprise
wowwiki: http://wowwiki.wikia.com/Quest:Steamtank_Surprise
Spell: http://wotlk.openwow.com/spell=49109

Again, part of this quest works fine but the option to drop off the Gnomes do NOT work. This prevents Alliance players from completing the entire Wrath-Gate chain quests.

@Lothloryen
@Golganeth

**Comment by bucovsky** [comment]
I can confirm that. I was able to drop off a soldier, but not the gnome who is supposed to sabotage Plague Wagons.

**Comment by warcraftgeekygamer** [comment]
I do not know what has happened, but when I tried this quest again today....it worked flawlessly. I do not know if a hotfix was applied or if an update was applied....but it worked with no issues today. I'm very surprised...but curious to know what happened to make it working again...

**Comment by bucovsky** [comment]
Thanks for posting that. I was able to finish the quest too.

**Comment by Sagrath** [comment]
https://github.com/dalaranwow/dalaran-wow/issues/351
