### ISSUE TITLE
[Silithus][58]Into the maw of madness

### ISSUE THREAD

**Issue by xxauroraxx** [dalaranwow/dalaran-wow#2529]
You are supposed to go to Hive Regal, enter the tunnels, and kill a night elf. She does not spawn.

**Comment by warcraftgeekygamer** [comment]
Video on how it's supposed to work: https://www.youtube.com/watch?v=yHSZRL9Mtt0
http://www.wowhead.com/quest=8306/into-the-maw-of-madness
http://wowwiki.wikia.com/Quest:Into_The_Maw_of_Madness

**Comment by xxauroraxx** [comment]
That video was taken AFTER the cataclysm, so there might be minor differences.

**Comment by Daveonx** [comment]
Quest can be completed since [Mistress Natalia Mar'alith](http://www.wowhead.com/npc=15215/mistress-natalia-maralith#objective-of) is spawned, but she needs some scripting, since she doesn't use any of here abilites or say any of the flavor texts.

**Comment by Rushor** [comment]
https://youtu.be/kuoKhEUDgZ4?t=81

**Comment by Rushor** [comment]
```sql
-- Mistress Natalia Mar'alith SAI
SET @ENTRY := 15215;
UPDATE `creature_template` SET `AIName`="SmartAI" WHERE `entry`=@ENTRY;
DELETE FROM `smart_scripts` WHERE `entryorguid`=@ENTRY AND `source_type`=0;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(@ENTRY,0,0,0,0,0,100,0,5000,10000,18000,19000,11,11639,0,0,0,0,0,2,0,0,0,0,0,0,0,"Mistress Natalia Mar'alith - In Combat - Cast 'Shadow Word: Pain'"),
(@ENTRY,0,1,0,0,0,100,0,8000,15000,10000,15000,11,13704,0,0,0,0,0,2,0,0,0,0,0,0,0,"Mistress Natalia Mar'alith - In Combat - Cast 'Psychic Scream'"),
(@ENTRY,0,2,0,0,0,100,0,14000,15000,16000,17000,11,16568,0,0,0,0,0,2,0,0,0,0,0,0,0,"Mistress Natalia Mar'alith - In Combat - Cast 'Mind Flay'"),
(@ENTRY,0,3,0,2,0,100,0,0,20,10000,15000,11,27527,0,0,0,0,0,1,0,0,0,0,0,0,0,"Mistress Natalia Mar'alith - Between 0-20% Health - Cast 'Healing Touch'"),
(@ENTRY,0,4,0,4,0,100,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,"Mistress Natalia Mar'alith - On Aggro - Say Line 0");

DELETE FROM `creature_text` WHERE `entry`=15215;
INSERT INTO `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `BroadcastTextId`, `comment`) VALUES 
(15215, 0, 0, 'You will make a fitting sacrifice!', 12, 0, 100, 0, 0, 0, 10742, 'Mistress Natalia Mar\'alith'),
(15215, 0, 1, 'C\'Thun will retake this world!', 12, 0, 100, 0, 0, 0, 10743, 'Mistress Natalia Mar\'alith');

```

DB/Creature:  Mistress Natalia Mar'alith - Add combatscript and texts

* closes https://github.com/dalaranwow/dalaran-wow/issues/2529
* commit: 1ff355509216d995713b777e6cd2dfead424299e

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
