### ISSUE TITLE
Anub'ar Skirmisher's Backstab's facing requirement

### ISSUE THREAD

**Issue by taralej90** [dalaranwow/dalaran-wow#2530]
It has none. Pretty simple.

The Skirmishers can and will face-stab you. Considering their aggro switching, this bug makes them painful...

http://www.wowhead.com/npc=28734/anubar-skirmisher#abilities

**Comment by n-ghost** [comment]
More of a general issue with the mob backstab ability as a whole, I believe.

https://github.com/dalaranwow/dalaran-wow/issues/15
https://github.com/dalaranwow/dalaran-wow/issues/65

Though I admit that eating a backstab in the face from nothing lesser than Anub'ar Skirmisher can make one wish he hadn't left the bed that morning.

**Comment by taralej90** [comment]
Well, it caused several wipes and me being votekicked for "being a bad tank and taking too much damage". Backstabs were hitting me for 3.8k out of my 11k HP at 70lvl in Frost Presence. Add the 1.5k autos from the skirmisher and the shadowcaster, and the 2.5k auto from the watcher, and I was dying in one melee cycle with no possibility of getting any heals.

**Comment by taralej90** [comment]
And yes, it's a general bug with mob Backstab... It's just that here it is also gamebreaking where in other cases it's negligible.

Easily duplicated situation - Skirmisher switches aggro to a clother via Fixate, face-stabs and oneshots him.

**Comment by Golganeth** [comment]
Merge with #15
