### ISSUE TITLE
Combat bug caused by fighting npc

### ISSUE THREAD

**Issue by Shadesmar** [dalaranwow/dalaran-wow#2531]
When hostile npc fight each other (worg and deer for example) and a player comes near they will aggro and get the player stuck in combat. Withdrawing out of aggro range doesnt help. Even when the fight is resolved the player is still stuck in combat.
Mobs shouldnt aggro at all as long as they are still fighting another faction.

**Comment by warcraftgeekygamer** [comment]
As a Mage, the only way I have been able to force myself out of aggro is using Invisibility....but even then...we should never have to be forced to do that. We shouldn't even be drawing aggro when two creatures are fighting each other.

**Comment by Golganeth** [comment]
#1312

**Comment by MrAndersonX** [comment]
Most annoying bug at the moment. Please fix this ASAP.
