### ISSUE TITLE
Blood DK Last skill in skill tree

### ISSUE THREAD

**Issue by earth6000** [dalaranwow/dalaran-wow#2532]
The last skill the blood dk tree is bugged and wont work

**Comment by warcraftgeekygamer** [comment]
Please elaborate...can you give more information other than "wont work"? It's extremely helpful if you can provide additional information.

**Comment by earth6000** [comment]
Like the skill its self you cant use. it just wont go off when you click it or use the button

**Comment by Golganeth** [comment]
#1098
