### ISSUE TITLE
Silence shot travel time

### ISSUE THREAD

**Issue by xumae** [dalaranwow/dalaran-wow#2537]
Silencing shots travel time is bugged and way way too long on dalaran, proof of how silencing shot should work in wolk:
http://www.twitch.tv/drakedog_ca/c/6847692
how it works on dalaranwow:
http://www.twitch.tv/drakedog_ca/c/6847699
In both clips i am at max range, and you can even watch me hit silencing shot on dalaranwow and it takes about a full second to hit the target this needs to be fixed fast.

**Comment by Lothloryen** [comment]
Hello, it has been corrected and deployed with the last maintenance.

Thank you.
