### ISSUE TITLE
[Nagrand/Shattrath]Patience and Understanding

### ISSUE THREAD

**Issue by xxauroraxx** [dalaranwow/dalaran-wow#2541]
You are sent to Shattrath to speak to Sal'Salabim. He is either invisible or not properly instanced in the bar.

**Comment by Furminator** [comment]
The quest is working fine, done it several times, being the last time last week. Probably someone did the quest sometime before you so the npc was not interactable in the proper way.

**Comment by Sagrath** [comment]
Confirmed to be working
