### ISSUE TITLE
Death bug, can not revive

### ISSUE THREAD

**Issue by Gone-deaD** [dalaranwow/dalaran-wow#2542]
when i was doing the quest "Thrusting Hodir's Spear", i died. After set free the soul, it's bugged.
i am in the sky, can not going down to the ground; and On the mount, can not using the stuck function.
now i am waiting. is there any GM here, please revive me?

**Comment by Gone-deaD** [comment]
Hm, by the way, the role i played is a priest, named "Fmaple", if anye GM see this, please help me.

**Comment by cover25** [comment]
Not the place to put this. You should use the ticket feature ingame.

**Comment by Gone-deaD** [comment]
yes i tried, but more than 10 hours passeed, there is no GM reply.

**Comment by Furminator** [comment]
A guy I met had the same problem, delete your cache folder and log back in. In any case this does not work, get someone to kill you if possible and repeat the process, you should be able to play again. Met a guy that had this problem and helped him in the way I explained.

**Comment by Lothloryen** [comment]
Hello there,

I think you were already helped ingame so, I will close this issue.

Thank you.
