### ISSUE TITLE
Master's call usable through los

### ISSUE THREAD

**Issue by xumae** [dalaranwow/dalaran-wow#2544]
Master's call is currently  useable while you are NOT in los of your pet causing the ability to fizzle and go on CD.

**Comment by Lothloryen** [comment]
Thank you Xumae,

I shall take a look, all the feedback is welcome.

**Comment by xumae** [comment]
Cool thanks man, also it seems that just using master's call while rooted has a chance to cause it to fizzle out suddenly, even when your pet is in los right beside you it may just go on cd and not work. TY for the fast reply!

**Comment by Lothloryen** [comment]
Hello again,

It has been fixed, it will be working fine after the next scheduled maintenance.

Thank you.
