### ISSUE TITLE
Solanian's Belongings Quest

### ISSUE THREAD

**Issue by Ryan295** [dalaranwow/dalaran-wow#2545]
In the Blood Elf Starting zone, sometimes we aren't able to pick up the item's for the quest. Currently I am unable to pick up the item called Scroll of Scourge Magic.

The other two items have bugged like this as well but it seems to fix itself after a couple of days only to bug again later on.

**Comment by Golganeth** [comment]
Fixed in-game. This is a rare and general issue with game objects.
