### ISSUE TITLE
Dr. Whitherlimb Rarespawn in Ghostlands has never spawned. Verified by GM was told to make bugfix ticket.

### ISSUE THREAD

**Issue by jbrown7261987** [dalaranwow/dalaran-wow#2550]
Trying to get an item off Dr. Whitherlimb the rarespawn in ghostlands. He has 4 spawn points in the towers one of the towers seems to be bugged completely where no mobs(even regular ones) will spawn in it when there is suppose to be. But i was finally able to talk to GM today and he verified it hasnt seemed to have spawned at all. Please look into this and try to fix when you guys can :) <3 Go dalaranwow!

**Comment by jbrown7261987** [comment]
Still has yet to spawn. I really hope you guys are able to get to this :( something has to be stuck it might have to do with that one tower(1 out of 4 spawn points) that seems to be completely bugged where nothing will spawn inside.

**Comment by jbrown7261987** [comment]
It's been a week after first making this post....Still no spawn. He literally doesnt spawn at all hes bugged......AN ACTUAL BUG PLEASE FIX

**Comment by Torrigan** [comment]
Confirmed that this NPC does not spawn. Please check into this!

**Comment by jbrown7261987** [comment]
Over a Month ago. Still no response. PLEASE LOOK INTO THIS

**Comment by jbrown7261987** [comment]
2 months and not even a glance...

**Comment by Lothloryen** [comment]
Working after the next maintenance.

Thank you.
