### ISSUE TITLE
Conflagrate is currently broken. 19% rather than 69%

### ISSUE THREAD

**Issue by pyrothraxus** [dalaranwow/dalaran-wow#2551]
Conflagrate: "Consumes an immolate or shadowflame effect on the enemy target to instantly deal damage equal to 69% of immolate or Shadowflame, and causes an additional 40% damage over 6 seconds.

Ran numerous tests and found the following.
Immolate with constant non changing stats. 1449 initial damage, 1080 tick damage, 8 times. for 10089 damage total.
69% of 10089 is 6961
Conflagrate is doing 1897 for that immolate.
This equates to roughly 19% of immolates damage. 

This means a MASSIVE dps loss for destro and hybrid locks. please fix immediately!

**Comment by elorix** [comment]
confirm

**Comment by pyrothraxus** [comment]
Please fix this major bug ASAP.
This is effectively a class breaking bug.
Affliction isnt viable till high enough haste.
Demo is uneffected (but you only want 1 per raid)
Destro is broken from this bug.
Hybrid is broken from this bug. please fix asap!

**Comment by moonsado** [comment]
So conflag is broken,glyph of pet seduce is broken,fear is bugged and when you tell your pet to stay than you use a skill of his like pet seduce he can sometimes randomly run away.
Rip Destruction

**Comment by Lothloryen** [comment]
Thank you for the report. I am currently taking a look

**Comment by robinsch** [comment]
https://github.com/TrinityCore/TrinityCore/pull/14987

**Comment by Lothloryen** [comment]
Hello there,

Thank you Robinsch, the issue is solved.
