### ISSUE TITLE
Feral Druid Talent - Heart of the Wild (Not increasing Stamina)

### ISSUE THREAD

**Issue by Nikvet** [dalaranwow/dalaran-wow#2552]
The Feral Druid Talent - Heart of the Wild does not increase the stamina while in Bear of Dire Bear form.I tested it now on a level 40 feral druid.The stamina in the base stats was not increased when I applied 5/5 Heart of the Wild.
(http://wotlk.openwow.com/spell=24894)

**Comment by robinsch** [comment]
Tested and working.

**Comment by Golganeth** [comment]
Seems to work.  but has some small issues here and there:

- If you apply the talent while in Bear / Cat Form, only the intellect will increase. After that if you refresh the form, bonus will be there.
- While you have the bonus and change to a different spec (without the talent), it seems extra stats will be kept, not the intellect though, for as long as you keep that shapeshift.
