### ISSUE TITLE
Stormpeaks has some several bugs

### ISSUE THREAD

**Issue by mariobrose** [dalaranwow/dalaran-wow#2553]
So from my experience at Stormpeaks so far, I can tell that the number of bugged quests is just impressive. Please do something about this. I'll leave the link of the quests down here:

http://www.wowhead.com/quest=12879/fury-of-the-frostborn-king - Fury of the Frostborn King (QUEST CHAIN, fix ASAP)
http://www.wowhead.com/quest=13007/the-iron-colossus - The Iron Colossus
http://www.wowhead.com/quest=12856/cold-hearted - Cold Hearted
http://www.wowhead.com/quest=12869/pushed-too-far - Pushed Too Far

And also, one REALLY big bug: ''The Foot Steppes'' zone next to the ''Engine of the Makers'' bug out when you move from one to each other, how? They make the npcs around dissappear, making a lot of quests impossible to do.

Thanks, and please fix ASAP.

**Comment by Furminator** [comment]
From my own experience I have to agree that Fury of the Frostborn King is bugged (reported also if I'm not mistaken)

*The Iron Colossus: The quest does work, but you cannot mount a Jormungar to fight the Colossus. You get the credit for killing it yourself, thou it can be hard for most classes.

*Cold Hearted: The quest is also working, the disguise can sometimes bug and it won't get removed after leaving Bruhindar Village, but as stated on other reports, going somewhere else, beside the Village and Sons of Hodir base you will get the disguise removed and you can go back to mount on the Proto Drakes.

*Pushed Too Far: Easily doable, there are enough wyrms standing on the peaks all around Storm Peaks, although they do not deal damage nor have an aggro table, making the pulls from the ones flying around hard.

**Comment by Tarpor** [comment]
#511
#1110
#1703
#2510 
Check the bugtracker if the quests are already on there next time

**Comment by Golganeth** [comment]
Duplicates.
