### ISSUE TITLE
Warrior 'infinite' falling while charge

### ISSUE THREAD

**Issue by jbeeahn** [dalaranwow/dalaran-wow#2554]
It's not happening randomly, but at some point, my warrior falls into 'infinite' glitch and cannot even release for 6 mins. It's almost impossible to do leveling at this moment.

Since it's not bound to certain quest or area, it's really hard to describe, but I can say it's a MAJOR issue with this server.

**Comment by Golganeth** [comment]
Not an issue with the Warrior class itself. You can /reload or relog for instant corpse release.

Closing up since this is already reported and it's pathfinding related.
