### ISSUE TITLE
Paladin Two-Handed Weapon Specialization not working.

### ISSUE THREAD

**Issue by Snusnufs** [dalaranwow/dalaran-wow#2558]
Hello. First time reporting a bug here and just want to say that Dalaran is the best server i have played on ever so keep up the good work :) and now for the bug.

Retribution paladins Two-Handed Weapon Specialization (http://wotlk.openwow.com/spell=20111) dont give any effect when i look at my chars damage. It should say 2/4/6% when i hold a 2 hand weapon but it dont.

**Comment by AgeAgainst** [comment]
I just checked, I'm getting it with 2H equipped, but I'm even getting the bonus with a 1H weapon equipped:

![2hspec](https://cloud.githubusercontent.com/assets/10249601/8298373/e44c522e-191c-11e5-9569-5811428aa37e.jpg)

**Comment by Snusnufs** [comment]
I see. It might work for me then aswell later, atm i'm levling and only have 1 point in it.

**Comment by Snusnufs** [comment]
this is how it looks for me now with 3/3 in Two-Handed Weapon Specialization. I think i got the damage increase when i put in the other 2 points but i cant be sure.
![wow](https://cloud.githubusercontent.com/assets/13010665/8321119/4bb21848-1a23-11e5-8d61-9cb880e0d774.png)

**Comment by Golganeth** [comment]
Seems to work so closing up.
