### ISSUE TITLE
[Item] Quest Items with incorrect drop rate. - LIST

### ISSUE THREAD

**Issue by Sagrath** [dalaranwow/dalaran-wow#256]
Making a list of incorrect drop rate of quest items, only confirmed will be posted.
Comment this issue with quest item information and the quest item drop rate will be checked.
WH - Drop rate according to WowHead
OW - Drop rate according to OpenWow
(<)  - drop rate is lower ingame than it should be
(>)  - drop rate is higher ingame than it should be

Good report example:
Brann's Communicator - http://wotlk.openwow.com/item=40971
Drops from: Tracker Thulin - http://wotlk.openwow.com/npc=29695
OW = 100%
WH = 78%
Currently the drop rate is really low, and the item is needed to hand in the quest.
Drop rate should increased to 100% while you are on the quest:
Sniffing Out the Perpetrator - http://wotlk.openwow.com/quest=12910 (Horde)
Sniffing Out the Perpetrator - http://wotlk.openwow.com/quest=12855 (Alliance)

**Comment by ashido96** [comment]
"Master Summoner's Staff" is not fixed, last comment Aug 29, 2013.
Just killed Zarod while on the quest and did not get the staff.

**Comment by Golganeth** [comment]
#2641

**Comment by ImprezaWoW** [comment]
[#2730](https://github.com/dalaranwow/dalaran-wow/issues/2730)

**Comment by ImprezaWoW** [comment]
Won't make a separate issue, but[Burning Legion Gate Key]( http://www.wowhead.com/item=29795/burning-legion-gate-key) for the quest [Invasion Point: Annihilator](http://www.wowhead.com/quest=10397/invasion-point-annihilator) does not have a 100% drop chance for people with the quest, even when it's supposed to have that.

**Comment by Rushor** [comment]
http://math.arizona.edu/~ercolani/pyzdek.pdf can be used as base to implement this

**Comment by Rushor** [comment]
https://github.com/dalaranwow/dalaran-wow/issues/3409

> [QUEST] Lost But Not Forgotten (Item Drop Rate)
> Drop rate of Kron's Amulet is set quite low. I killed every Crocolisk in the river three times (amounting to roughly 35-40 mobs) before it dropped. Not sure if it's just bad luck on my part or if the drop rate is set lower than it should normally be.

**Comment by Rushor** [comment]
implemented the system from http://math.arizona.edu/~ercolani/pyzdek.pdf 

the more open you kill a creature without getting the questitem, the higher the chance to get the questitem for the next killed creature

there are some quests which require 100% droppchance for some item, pls add a new issue for this, that must be fixed in db then
