### ISSUE TITLE
Quest: Herald of War

### ISSUE THREAD

**Issue by Zawi47** [dalaranwow/dalaran-wow#2560]
The portal to Orgrimmar doesn't spawn. Because of that, Horde players can't take part in the battle for Undercity

**Comment by Prljoman** [comment]
Battle for Undercity isn't scripted yet on this server so that's why you can't progress.

**Comment by Sagrath** [comment]
repost
https://github.com/dalaranwow/dalaran-wow/issues/2404

**Comment by MrAndersonX** [comment]
Still bugged. The portal doesn't open.
