### ISSUE TITLE
Heroics dropping emblems of triumph.

### ISSUE THREAD

**Issue by Craptla** [dalaranwow/dalaran-wow#2563]
Me and a friend have been running heroics all day on fresh characters, neither of us have any raid progression and yet we've noticed that we have some bossses have been dropping emblems of triumph, the only boss we've actually noticed dropping the emblems is the bran bronzebeard gauntlet in halls of stone, but there are clearly other bosses as my friend has racked up 8 emblems today.

**Comment by darkwulfv** [comment]
If you're doing Heroics via RDF, then that's why; after your first Heroic RDF you get 2 Emblems of Triumph per dungeon, which is a known bug. The emblems will be wiped when ToC is fully released.

**Comment by Craptla** [comment]
Well this isn't the RDF reward (at least not entirely) we've noticed bosses dropping them, not final bosses either.

**Comment by darkwulfv** [comment]
I wonder if that broke recently then, I don't remember seeing any extra Triumphs beyond the RDF reward.
