### ISSUE TITLE
Dk Pet Explosion

### ISSUE THREAD

**Issue by buffdkplz** [dalaranwow/dalaran-wow#2565]
Pet Explosion used to be one of the best Pvp dmg skills. on this server it is not even worth using is. cause first of all it seems to scale with the pets amount of crit instead the one of the player so it doesnt crit at all on players with resilence and secondly its damage seems to scale to low but im not rlly sure how much because i cant test it anywere else beside AT were i have better gear. Using it does also not work sometimes here and it does just nothing then. and u have to target the pet and cant use a /cast [target=pet] macro for some reason.

**Comment by Golganeth** [comment]
#2201
