### ISSUE TITLE
Orgrimmar Stable Master

### ISSUE THREAD

**Issue by tozzy52** [dalaranwow/dalaran-wow#2566]
Stable master Xon'cha in the Valley of Honor is not working properly, it is giving me the text prompt if I were a non-hunter class. 

"Hey der, mon.
Did ya need help recoverin' a lost companion?"

Checked the TB stable master to see if it was my character that was glitched but it worked properly over there. Happened while in party with a paladin if that changes anything.

Please look into it and thank you in advanced.

**Comment by Lothloryen** [comment]
Hello there,

Thank you, this issue will be corrected after the next maintenance.
