### ISSUE TITLE
[Spell] Engineering: Personal Electromagnetic Pulse Generator

### ISSUE THREAD

**Issue by Rukker** [dalaranwow/dalaran-wow#2570]
Supposed to Stun for 3 seconds, but only Incapacitates; damage revives the target.

http://www.wowhead.com/spell=54736/emp-generator

**Comment by Rushor** [comment]
Effect 0: Id 6 (SPELL_EFFECT_APPLY_AURA)
BasePoints = 0
Targets (22, 15) (TARGET_SRC_CASTER, TARGET_UNIT_SRC_AREA_ENEMY)
Aura Id 12 (SPELL_AURA_MOD_STUN), value = 0, misc = 0 (0), miscB = 0, periodic = 0
Radius (Id 10) 30.00
Effect Mechanic = 12 (MECHANIC_STUN)

works fine for me
