### ISSUE TITLE
[EoE] 25 man

### ISSUE THREAD

**Issue by Althaloss** [dalaranwow/dalaran-wow#2571]
Yesterday, my guild attempted to run EoE 25 on the Algalon server. We found a few bugs.

1. The orb that you click on the begin the encounter is supposed to disappear when the fight starts, it did not, causing line-of-sight issues.

2. All of the safe purple zones in phase 2 all spawned in the middle of the platform, they are supposed to be randomly spread about.

3. We could not make it to phase 3, so I am unsure of potential bugs in that phase.

**Comment by M0dinstaller** [comment]
For 3. there are a fuckload of bugs.

The first of them being if you die, you have to reload to get out, and you'll most likely not get the achievement for the kill and if the raid loots while you're running in you won't be eligible for the loot.

The second and most annoying is that you can't cast the shield on yourself or anyone, making the laser focus thing unavoidable. This is the main cause for wipes and this is why you need more heals / more competent heals that will quickly heal the victims.

The 3rd and mildly annoying bug (and I don't actually know if it's a bug) is that there is a huge delay between the time at which you cast your spells and the one at which they actually hit, making first timers confused. Did my ability generate a combo point there ? Did I cast my finisher move ? I still see the combo points on the boss ...
May not be a bug, so idk.

As for the last one, it's one shared by all vehicles. The energy cost of any vehicle ability is X, but if you try to cast it when you have X to X+9 energy, it won't go off. Or rather it will, the gcd will be used, but nothing will happen. Every vehicle ability needs 10ish more energy to be cast than displayed. The 10 energy will be refunded after the cast. It's like that on wintergrasp siege and other vehicles too. Confusing.

**Comment by Golganeth** [comment]
#1366
