### ISSUE TITLE
glyph of succubus

### ISSUE THREAD

**Issue by adytzyca** [dalaranwow/dalaran-wow#2572]
Glyph of succubus doesnt work at all:it doesnt remove any dots from your target...add that ontop of improved succubus being completely broken aswell and you get a 100% unplayable class in pvp.Would be nice not to be banished from such activities

**Comment by Lothloryen** [comment]
Hello there,

I shall take a look to the Glyph, however the Improved Succubus talent has been already corrected as stated here #2564 , the maintenance has not been done yet. It will be performed tomorrow night.

Thank you very much.

**Comment by moonsado** [comment]
Hello,
Has the maintenance been done yet? Because I haven't notice any difference whatsoever regarding the Improved Succubus talent. same for other people?

**Comment by Lothloryen** [comment]
Hello,

My apologies, I forgot to add the patch for the Seduction cast time. It shall be for the next one.

The glyph has also been corrected and will be applied in such maintenance.

Thank you very much.

**Comment by Lothloryen** [comment]
The last maintenance had those fixes deployed. Thank you.
