### ISSUE TITLE
[Paladin] The Art of War

### ISSUE THREAD

**Issue by M0dinstaller** [dalaranwow/dalaran-wow#2577]
https://github.com/dalaranwow/dalaran-wow/issues/2220
https://github.com/dalaranwow/dalaran-wow/issues/2463

Bug is back.

**Comment by Tarpor** [comment]
No it ain't

**Comment by M0dinstaller** [comment]
You're right, it ain't back, cause it was never fixed.

A level 80 paladin friend tested this for me and just as I thought :

You only fixed the last ranks of exorcism and flash of light.

All the other ranks still reset the swing timer.

I guess you forgot.

**Comment by Tarpor** [comment]
Just tried, rank 8+9 work on exo, rank 7 didnt.

**Comment by Nikvet** [comment]
Tested.The bug exists on low level paladins,but on level 80 - when using Exorcism+Art of War ,Auto-attack swing timer is not reset.

**Comment by Golganeth** [comment]
Right now, last ranks of both FoL and Exorcism seem to reset the swing timer completely. Lower ranks have the same behavior (PTR)

**Comment by Tarpor** [comment]
Broken again on the main realm. All ranks FoL + Exorcism.

**Comment by Tarpor** [comment]
Still broken due to your fixes. Please just revert so its actually useful.

**Comment by robinsch** [comment]
On PTR.

**Comment by Golganeth** [comment]
This is still an issue on the PTR. For all ranks of the spells Exor/FoL

**Comment by robinsch** [comment]
On PTR. Tested myself, working now. Sorry

**Comment by TeridanDW** [comment]
Tested all ranks of _flash of light_ and _exorcism_ on ptr, all of them work as intended.
