### ISSUE TITLE
Omor the Unscarred

### ISSUE THREAD

**Issue by Vaxsysl** [dalaranwow/dalaran-wow#258]
Omor the Unscarred in Hellfire Ramparts is casting his Shadow Bolts from infinite range and attacks players through LoS. One can be at the start of the dungeon and he will hit them through wall for full 1500 dmg per each bolt.

**Comment by Rushor** [comment]
http://wotlk.openwow.com/spell=30686

i think he needs to reset if he leaves his place

**Comment by Rushor** [comment]
a78e3ecbf36d05a4e59f36f59057f6ee00b9e190
- now the boss will evade if it's target is >=90 yards away from the boss
