### ISSUE TITLE
skeleton problem 

### ISSUE THREAD

**Issue by lemi95** [dalaranwow/dalaran-wow#2581]
![wowscrnshot_062515_142428](https://cloud.githubusercontent.com/assets/13122865/8437958/e971b932-1f62-11e5-9d06-9b6cdbc5913c.jpg)

I tried all kinds of things to do ,but I can not get rid of it.....HELPPPPPPPPPPP

**Comment by Rushor** [comment]
YOUR BONES ARE OUR BENEFIT!

**Comment by Golganeth** [comment]
#1971
