### ISSUE TITLE
[Quest] [The Earthbinder]

### ISSUE THREAD

**Issue by Snusnufs** [dalaranwow/dalaran-wow#2582]
Quest http://wotlk.openwow.com/quest=10349

You can't turn in the quest. When you take it it goes auto complete but you can't turn it in. This quest is kinda nice to complete cause it leads to http://wotlk.openwow.com/quest=10351

**Comment by Golganeth** [comment]
Works fine. Most likely it's the general issue with quests not detecting item(s) in your bags. Try retaking the quest and it should be fine.

**Comment by Vaxsysl** [comment]
Quest is bugged again. Taking the quest triggers whisper "up the hill", but NPC is being impossible to talk to regarding the quest. We can't do anything about it since NPC refuses to cooperate (retaking the quest doesn't work).
