### ISSUE TITLE
[Warrior] Recklessness / Shockwave

### ISSUE THREAD

**Issue by Aalhazred** [dalaranwow/dalaran-wow#2584]
Currently Shockwave will not get a 100% critical chance when using Recklessness

proof : http://i.imgur.com/ezDcLoA.png

**Comment by Vaxsysl** [comment]
I think that this was reported already. Confirming in any case.

**Comment by robinsch** [comment]
Proof needed. In DBCs all spells are affected by this (except for Shockwave) Seems like Shockwave is not supposed to work with it.
