### ISSUE TITLE
[NPC] Madame Ruby - Shattrath City

### ISSUE THREAD

**Issue by sifiuocz** [dalaranwow/dalaran-wow#2587]
link: http://wotlk.openwow.com/npc=19663 
This NPC seems to have generic enchanting supplies, but it is not supposed to be like that. 
The main issue about that is that she is the only one vendor that sells Formula: Runed Eternium Rod (link: http://wotlk.openwow.com/item=25849) which is vital for getting Enchanting to 400+ and for any late-game enchants in the game.

**Comment by Rushor** [comment]
if something was bought from another player, the item will be removed for the restoretime from the vendorwindow - this is blizzlike - so no bug here

**Comment by Sagrath** [comment]
fixed
