### ISSUE TITLE
Silencing and Line of sighting mobs

### ISSUE THREAD

**Issue by Clumzyz** [dalaranwow/dalaran-wow#2588]
Hey guys, having a issue with ever mob that if i silence them or try line of sighting them to tank efficiently. They either just stop casting in place or deagro unlike what they are supposed to do which is switch over to melee mode. Can we plz get a fix on this really takes away from the true tanking experience.

**Comment by n-ghost** [comment]
From my experience LoSing NPC casters works just fine (they stop casting and run to you around the corner), but when you try to interrupt them from distance they indeed stand like lemons for the full interrupt/silence duration, unless there is something in their melee range.

**Comment by warcraftgeekygamer** [comment]
LoS works fine.

**Comment by Clumzyz** [comment]
Well in multiple situation LoS doesn't work with questing mobs with just yesterday in Blood Furnace mobs would instantly forget you exist and sit back at where they started so for me to tank and keep most of the agro i would just have to run right on top of um drop and consecration get ready to taunt any thing standing out of it. Idk if this is a lower level thing and they only worked on the Woltk LoS issues but even so silencing should definitely still work as well.

**Comment by Vaxsysl** [comment]
Maybe related or not, but I got this happen during RDF yesterday - mobs were casting while polymorphed.
http://i.imgur.com/hx9OVsV.jpg
http://i.imgur.com/nXHiUbR.jpg

**Comment by n-ghost** [comment]
Yah, was too lazy to report that (>,>), but pve poly became extremely glitchy. Mobs sometimes will also use ranged attacks and abilities as well.

Recasting poly usually helps, but still, should be looked into.

**Comment by Vaxsysl** [comment]
Doesn't help afaik, I kept one mob polymorphed for over 50 seconds since the group was without any coloured items.

**Comment by Clumzyz** [comment]
lol that casting sheep

**Comment by Clumzyz** [comment]
I just really wish there was a fix for this because it's making the 3 points for the silence on my avengers shield worthless

**Comment by Clumzyz** [comment]
soooo

**Comment by Vaxsysl** [comment]
They can use ranged attacks too, this happened a few days ago: http://imgur.com/II6BFxh

**Comment by Golganeth** [comment]
#1954
