### ISSUE TITLE
[Quests] [Northrend] The Hunter and the Prince

### ISSUE THREAD

**Issue by darkwulfv** [dalaranwow/dalaran-wow#2589]
This quest (http://wotlk.openwow.com/quest=13361) cannot be completed because the stone you're supposed to touch to begin the encounter does not spawn anywhere in the Court of Bones.

**Comment by Spruitje** [comment]
Can confirm this, have searched for hours and tried using several guides, youtube vids etc

**Comment by Linandir** [comment]
I can also confirm this. Can't find a clickable stone anywhere. Tried to abandon and get the quest again in hope for them to spawn but nope. Might be that you have to try after a restart of the server or something in case it only spawns once. Gonna try that if I can time it.

**Comment by Rushor** [comment]
the quest was implemented here https://github.com/TrinityCore/TrinityCore/blob/a56a402190c885e51038df55654875cc9e875c03/sql/old/3.3.5a/TDB51_to_TDB52_updates/world/2013_05_22_00_world_sai.sql#L430

the stone spawns after you accepted the quest for 30 seconds, so you need to act quick!

moreover there are 3 different spawnplaces for it:
http://i.imgur.com/xj6vc55.jpg
http://i.imgur.com/Chq4nGZ.jpg
http://i.imgur.com/onH0zPY.jpg

**Comment by Zibathy** [comment]
Not working on Kirin Tor.
