### ISSUE TITLE
Pet Pathing RIP

### ISSUE THREAD

**Issue by moonsado** [dalaranwow/dalaran-wow#2590]
Warlock pets are sort of messed up meaning if I tell my pet to stay in one place well he has a 50/50 chance to run away and despawn losing soul link and potentially not being able to either spellock or pet seduce an enemy.

Don't believe me? 
https://www.youtube.com/watch?v=1_mf_zIu40o
In this video you can see that I have soul link and that my pet is following me, I tell my pet to stay he stays then I use an ability of his and he just runs away losing soul link.
If there was somewhat a possible way to repair this please do so.

**Comment by Lothloryen** [comment]
Hello,

I already had a patch prepared for this, it will be working properly with the next maintenance.

Thank you very much.
