### ISSUE TITLE
Recipe: Wispcloak (Tailoring) - 41609

### ISSUE THREAD

**Issue by Furminator** [dalaranwow/dalaran-wow#2591]
__Issue Present__: After completing all the normal dungeons of Northrend and having the Northrend Dungeonmaster achievement you should be eligible to obtain this recipe from the NPC Charles Worth (__28699__) which is not possible at the moment.

![](http://puu.sh/iL6gD/a4d433b61b.jpg)

![](http://puu.sh/iL6XF/f45af63eb0.jpg)

After completing the required achievement, clicking the dialogue box from Charles Worth does nothing but provide the information of how to obtain this recipe:

![](http://puu.sh/iL6hc/8b555f1e24.jpg)

**Comment by Golganeth** [comment]
#1848
