### ISSUE TITLE
Scent of Blood

### ISSUE THREAD

**Issue by Vidmantasaf** [dalaranwow/dalaran-wow#2592]
The talent Scent of Blood is improperly triggered by indirect hits giving the dks advantage to abuse talent Frost Strike, the Scent of Blood which was never a pick in retail (just wowhead scent of blood and see dk forum posts about the talent, or see all old builds that were 0/53/18) procs off environmental (indirect) damage such as raid aoe damage etc etc etc. Direct damage is considered as single target spells like frost/shadow/fire bolts etc etc and white hits .

**Comment by Tarpor** [comment]
It even procs randomly in dalaran, jumping seems to trigger it aswel, I honestly lost track of what procs it, cause literally everything procs it

**Comment by warcraftgeekygamer** [comment]
brb going to roll DK!

**Comment by robinsch** [comment]
On PTR.

**Comment by Rushor** [comment]
Script/Spell: Scent of Blood will now only proc from direct damage

Issue: https://github.com/dalaranwow/dalaran-wow/issues/2592
commit: a3ddf581e20a5491ff5241b06117510258e83878

**Comment by TeridanDW** [comment]
After few tests on ptr, talent still seems to proc from AoE spells (blizzard, flamestrike, etc).

**Comment by robinsch** [comment]
Ref: 67652685b26f557afbc7ed075007723c1b170773

**Comment by ashido96** [comment]
http://us.battle.net/wow/en/game/patch-notes/3-1-0
Scent of Blood: Will now proc on a dodge, parry or when taking damage, and now grants 10 runic power per charge. Internal cooldown removed.

On live server scent of blood seems to have been completely gutted? Based on patch notes it should still proc on taking dmg from aoe raid mechanics (like death and decay or frostbolt nova type stuff) that are not 'environmental' (such as gas on festergut or pulsing aoe from PP abomination or sindragosa). 

For example the Anub'ar Venomancers (29217) Poison Bolt Volley was not proccing scent of blood when according to patch and talent descriptions it clearly should. 
http://www.wowhead.com/spell=53616/poison-bolt-volley

**Comment by TeridanDW** [comment]
Thank you for the comment @ashido96, however I disagree with it. The talent clearly says:

> You have a 15% chance after dodging, parrying or taking **direct** damage to gain the Scent of Blood effect, causing your next 3 melee hits to generate 10 runic power.

Feel free to prove me wrong by providing a proof like a video from patch 3.1.0 + (wrath only).

Regarding:

> Script/Spell: Scent of Blood will now only proc from direct damage.

Works as intended on PTR.
