### ISSUE TITLE
Death and Decay Threat

### ISSUE THREAD

**Issue by Shadesmar** [dalaranwow/dalaran-wow#2593]
Death and Decay http://wotlk.openwow.com/spell=49938
The Text tells: This ability produces a high amount of threat.
According to wowpedia (http://wow.gamepedia.com/Threat) this threat factor should be 1.9x when in frost presence.
With Frost Presence http://wotlk.openwow.com/spell=48263 activated the DK cause 2x threat. So the combined threat caused by Death and Decay should be 3.8x damage. (both factors stack multiplicatively as described on the wowpedia website)
A guildmate of me will post screenshots that proof that the current threat caused is only the 2x from the frost presence and the 1.9x factor is missing.

This bug has huge impact on DK group tanking: DKs dont have aoe taunts, and relying heavily on DnD threat. The other options (for blood DK tank): blood boil, that causes no extra threat and has kinda low damage, and spreading plagues, those need at least 3 abilities ( for both plagues spreaded) and the caused threat and damage is kinda low too at first (DoT). In addition to this flawed alternatives dnd costs 3 runes!

With the extra threat that is promised in the description DnD still isnt a fire-and-forget weapon in threat realm but it can rightfully claim the place as most important group tanking ability of dks which compensates for non-existent group taunt other tanks have.
Right now its lost runes for tank dks, because threatwise now the only viable solution is to single-focus one after another and pray that the keyboards of the dps' have fallen down simultanously when you as tank engaged.

**Comment by LeandroWT** [comment]
![wowscrnshot_070315_233936](https://cloud.githubusercontent.com/assets/13172807/8506193/eecdc5d2-21de-11e5-8ab1-6695d3d9eb02.jpg)
![wowscrnshot_070315_233938](https://cloud.githubusercontent.com/assets/13172807/8506194/eed1d97e-21de-11e5-978d-e54d7c16938c.jpg)
![wowscrnshot_070315_233931](https://cloud.githubusercontent.com/assets/13172807/8506195/eed3d5ee-21de-11e5-996b-4a860d808862.jpg)

**Comment by Golganeth** [comment]
#2195

**Comment by Shadesmar** [comment]
u cant just say 'it works fine' when it obviously does not. Please, i am really looking forward for an explanation.
This ability should cause a high amount of threat, now it does not.

**Comment by Shadesmar** [comment]
In your link https://github.com/dalaranwow/dalaran-wow/issues/2195 you only say 'it works fine'

Did u read anything of this bug report? It doesnt work fine, it doesnt work like intended, why are u closing this report?
DnD should cause high amount of threat like the the description pointed out. 
Get a threat addon and check it yourself if you dont trust the pictures as proof, but dont close valid bug reports with unqualified comments like 'it works fine' when it is apparent that the opposite is true.

**Comment by Lothloryen** [comment]
Hello there,

I shall take a look into this after the ToC release. Any extra detail will be helpful.

Thank you.

**Comment by Shadesmar** [comment]
the removal of the threat bonus happened in the patch 5.0.4. This change was undocumented, just summarized in the patch notes as 'All classes have been updated with a new talent system, improved abilities, and spells (accessible throughout levels 1-85)' (http://us.battle.net/wow/en/game/patch-notes/5-0-4)

Those detailed changes for this patch can be found in http://wow.gamepedia.com/Patch_5.0.4_%28class_changes%29

i want to add that even with the removal in this patch DnD causes 500% of its damage in threat there, because of the blood presence threat change in 4.3.0 (http://eu.battle.net/wow/en/game/patch-notes/4-3-0). Thats still higher than originally introduced in wotlk (as calculated above 390% together with frost presence)

another source for the increased threat of death and decay ( with the info that this table is valid for the patch 3.0.2 where the threat system got overhauled) is http://wowwiki.wikia.com/wiki/Threat

**Comment by strobe-light** [comment]
It seems as though all of the bug reports on this issue are closed despite the issue still being present, so I'm bumping it in case it was forgotten.
