### ISSUE TITLE
Broken haste on dk

### ISSUE THREAD

**Issue by Vidmantasaf** [dalaranwow/dalaran-wow#2594]
DK has too much haste, some source gives too much, unsure which.
Right now my character has 1.79 with improved Icy talons activated and no bonus haste, and 2.14 without icy talons activated.
Given that my wep speed is 2.7,and Improved Icy talons gives 25% haste it should be 2.7/(1.0+0.25)=2.16, while it is 2.14
While after haste of icy talons it should be 2.14/(1.0+0.25)=1.8 FLAT (it is 1.79  in game)
http://wowwiki.wikia.com/Attack_speed

**Comment by Tarpor** [comment]
Im doing some testing right now on my DK.

He has 9.04% haste from gear, and 2.5 attack speed weapons.

So to start of you calculate the denominator cause we have the numerator of 2.5.
The denominator is calculated by (1+20/100)(1+5/100)(1+0.094), the first being the Impr Icy Talons, second being the ADDITIONAL Impr Icy Talons, and lastly my own haste. Now if you get that number it's 1.37844, so we divide 2.5 by 1.37844 giving me a attackspeed of 1.814, this is upped to 1.82, which  is exactly my DK's speed. Now if I were to get the additional 20% from Icy Talons, I'd have 1.37844*1.20, which is 1.654128. So with Icy Talons my haste would go to 2.5/1.654127 =/= 1.511, ingame my haste says 1.52, so thats right too. 

Looking at your numbers, your numerator is 2.7 and you're calculating the ADDITIONAL Impr Icy Talons as 1 with the Impr Icy Talons, which it isnt. So your haste should be 2.7/(1+20/100)(1+5/100), which is 2.7/1.26, which gives you 2.14 haste. Now for your haste with Icy Talons, it's 2.7/(1.26*1.20). This gives you 1.786 attack speed, going up to 1.79. Works fine, can be closed.
