### ISSUE TITLE
[Mage] Quest: Get the Scoop

### ISSUE THREAD

**Issue by Ironard** [dalaranwow/dalaran-wow#2595]
http://www.wowhead.com/quest=1950/get-the-scoop

You should talk to the kitchen "Plucky Johnson" but nothing happens. Thanks

**Comment by n-ghost** [comment]
Have you emoted /chicken on him before trying to talk?

**Comment by warcraftgeekygamer** [comment]
@Ironard 
You are incorrect in your statement. I was able to complete this quest with no issues. Did you read the comments from that link you posted? If you scroll down on the comments you will find the following:

"You wont be able to talk to him or anything else to progress this quest, so you'll have to /Beckon him."

**Comment by Ironard** [comment]
it worked with the emoticon, thanks to everyone!
