### ISSUE TITLE
[Mage[ Quest: Items of Power

### ISSUE THREAD

**Issue by Ironard** [dalaranwow/dalaran-wow#2596]
http://www.wowhead.com/quest=1948/items-of-power

I collected 10 Whitebark Totem Sticks and i used them on the stone inside the circle. A rod appears on the stoe for like 1 minute but then it disappear and nothing happens. I tried it 3 times. Please fix it it's a class quest. many thanks

**Comment by n-ghost** [comment]
https://github.com/dalaranwow/dalaran-wow/issues/761
