### ISSUE TITLE
Quest: Oh, It's Real

### ISSUE THREAD

**Issue by Ironard** [dalaranwow/dalaran-wow#2599]
http://www.wowhead.com/quest=27221/oh-its-real

I need to talk with Major Mills but it's impossible to talk with him, he hasn't the question mark above too

**Comment by Spruitje** [comment]
After a server crash/restart it is possible to talk and complete this quest
However the followup quest "Take down Tethyr" is also bugged
Tethyr remains stationary at the far end of the docks and only 2 of the 3 cannons seem to work
I did manage to kill him but i never got credit for it

**Comment by necropola** [comment]
It also helps to bring a horde char and kill Major Mills.
After he respawned (takes around 5 minutes) I was able to complete the quest.

**Comment by cuirisse** [comment]
Still having this issue. Tried dropping and retaking the quest. Tried logging out and back in. Nothing.

**Comment by Lothloryen** [comment]
Hello there,

This should be fine already, if anyone experiences any issue let us know, please.

Thank you.
