### ISSUE TITLE
[Borean Tundra][Quest] Abduction still not working

### ISSUE THREAD

**Issue by Snusnufs** [dalaranwow/dalaran-wow#2600]
This quest is still bugged As bho72285 said in his ticket about the same quest. #1381 

"The quest IS completable, but once all of the Sorcerers have been captured, no one else is able to do this. I've stuck around for over an hour today to ensure that these mobs never despawn and respawn as uncaptured sorcerers."

The same issue is still present.

**Comment by deltafoxnine** [comment]
Yes i experienced exactly the same today

**Comment by Spydoc** [comment]
Confirmed. The Captured Sorcerers are still not despawning.

**Comment by DrFuler** [comment]
[04/03/2016] - Still bugged.

**Comment by VonKaufmann** [comment]
Still bugged today.

**Comment by Lothloryen** [comment]
Hello there,

This quest has been corrected and it is already on the live server.

Thank you.
