### ISSUE TITLE
[Northrend][Howling Fjord][Quest] I've got a flying machine!

### ISSUE THREAD

**Issue by InvincibleEagle** [dalaranwow/dalaran-wow#2602]
You can't drop off the relics at the cranes.

**Comment by Naidira** [comment]
I was able to complete this fairly normally.  After acquiring a relic bag, I positioned the flying machine directly inside the iron binding portion of the rope graphic that holds up the drop-off platform.  Pressing Grapple again dropped the relic bag.

**Comment by Ticklebur** [comment]
confirmed, works
