### ISSUE TITLE
[Northrend][Dragonblight][Quest] Attunement to Dalaran bug

### ISSUE THREAD

**Issue by Gibeligob** [dalaranwow/dalaran-wow#2604]
There seems to be something wrong with the quest of Attunement to dalaran for mages. After using the item (Ley line attunement crystal) in the pit of Moonrest Gardens, the quest does not become completed and therefore unable to finish the quest and hand it in.

**Comment by warcraftgeekygamer** [comment]
I can confirm that this quest does not work. Once you find the place on the ground to stand, you can use the attunement crystal. However, after the crystal is used, you are not given completion credit.

This quest was added in patch 3.3.0

http://wotlk.openwow.com/?quest=12172
http://www.wowhead.com/quest=12173/attunement-to-dalaran
http://www.wowhead.com/quest=12173/attunement-to-dalaran#comments
https://www.youtube.com/watch?v=YAB6VZDvI2c

Even though the youtube video was taken during Cataclysm, the quest remains unchanged. You are supposed to be given credit just like the video shows.

**Comment by Golganeth** [comment]
Duplicated, #1658
