### ISSUE TITLE
Yogg-Saron

### ISSUE THREAD

**Issue by Vaxsysl** [dalaranwow/dalaran-wow#2605]
I found nothing under searching "yogg-saron" or "yogg" or "saron".

Yogg-Saron: 33288
Deafening Roar: 64189

We were doing +1 keeper tonight on 25man and he didn't do Deafening Roar, nor did any HM loot drop. First time it happened to my raid group.

**Comment by Tarpor** [comment]
Maelstrom has had this for the last 3 or 4 raid ID's. We sent emails for the lost loot (hint loth huehue)

**Comment by burkey6** [comment]
Its become very frustrating.

**Comment by Lothloryen** [comment]
Hello there,

One question, you did not receive any loot at all or just the additional from the +1 Keeper one?

Thank you.

**Comment by Vaxsysl** [comment]
We received only regular Yogg+4 loot, no hardmode loot. Neither for Vezax, we killed it before 2nd mark after Animus' death, or whatever it is that triggers the hardmode loot table.

**Comment by Lothloryen** [comment]
Okay, thank you Vaxsyls.

I think I got it, have not been able to reproduce the issue on Yogg-Saron after applying a fix. I shall deploy it to Algalon on the next scheduled maintenance, which I will try to do tomorrow morning.

I would like to receive feedback after such maintenance, please.

**Comment by Vaxsysl** [comment]
You'll get it next Sunday / Monday from me. Cheers Lothloryen.

**Comment by burkey6** [comment]
To help target the issue.

Yogg appears to work correctly and give loot on the first attempt providing he casts "Deafening Roar"

After a wipe or possibly even the first attempt in some cases he does not at any point cast "Deafening Roar" regardless of 3-0 keepers present.
I think the trigger for no hardmode loot table is the fact he does not cast "Deafening Roar".

This appears to prove true for 10 and 25 man.

**Comment by Tarpor** [comment]
10 man never casts deafening roar.

**Comment by burkey6** [comment]
thanks Tarpor didnt realise how it was worded changed accordingly.

**Comment by Tarpor** [comment]
We got hardmode loot this time from yogg and he casted Deafening Roar. There was however another bug where the brainportals spawned after like 5 seconds into P2 and caught everyone offguard. (no hm loot from vezax though)
