### ISSUE TITLE
Not enough xp or quests in starting zone.

### ISSUE THREAD

**Issue by ArmandoAlvarezz** [dalaranwow/dalaran-wow#2607]
I did all quests in starting zone  in Durotar and got 5,5 lvl of xp. Not enought to get last quest from my trainer or even learn skills(lvl 6) And next active quest (?) is in Senjin Village where is no class trainer.

**Comment by Vaxsysl** [comment]
You get level 6 if you kill all mobs in your path. Nothing bad with it.

**Comment by Golganeth** [comment]
Invalid report.
