### ISSUE TITLE
Explosive Trap killing low levels in Dalaran

### ISSUE THREAD

**Issue by lmmense** [dalaranwow/dalaran-wow#2608]
Dalaran is supposed to be a safezone, and it's frustrating that you can't take your eyes off the screen for just a second because you have to dodge Explosive Traps. He's been doing this for atleast 3 weeks, and have just shrugged it off every time.

While fixing the bug, could you also hand out some bans to let the community know that it's not O.K? Horde hunters have been harrassing people with this as well, but I forgot to screenshot it as proof.

http://imgur.com/a/R49Sc - Bug abuser in action
http://imgur.com/U4a55n3 - Bug abuser mocking me on the forums.

**Comment by xumae** [comment]
Please do not let this bug abuser get away with such a terrible bug this is deserving of a perm account closure imo

**Comment by lmmense** [comment]
Good thing I provided screenshots, might aswell combine a bug report and an actual report, right? ;p

**Comment by Tarpor** [comment]
rip xumae killed by consecration spammer

**Comment by Vekt** [comment]
I guess it's a good way to avoid slacking in dalaran ahah

**Comment by Golganeth** [comment]
#1196
