### ISSUE TITLE
[Hunter][Spells][Pets] Taming a beast

### ISSUE THREAD

**Issue by Dolmio1** [dalaranwow/dalaran-wow#2610]
Hello, after mondays (6th of july) hotfixes taming a new beast doesn't work. After the 20 second channel nothing happens, and you can't get a new pet at the moment. This should be fixed asap, it's really gamebreaking for hunters.

 As all hunters know that have attempted / killed Algalon, hunter pets sometimes tend to bug out and u have to get a new one after.

When it enters a black hole, the pet is dismissed. Then sometimes when you call it back the pet bar is bugged out, it doesn't really listen to your commands and is just broken in general.

Tried taming wolfs all over, level 79-80 ones in Storm Peaks, lower level ones in Howling Fjord but after the channel nothing happened and i'm currently without a pet on my hunter.

Other hunters confirmed this bug aswell, input in this thread is greatly appreciated to help this issue go away asap.

Best regards.

**Comment by Lothloryen** [comment]
Hello there Dolmio,

Thank you very much for your report, I noticed it when doing several tests for: #2606 
The issue with the tame beast has been corrected and it will be also deployed with the next scheduled maintenance.
