### ISSUE TITLE
[Website] Password-reset feature not working

### ISSUE THREAD

**Issue by NaturelSin** [dalaranwow/dalaran-wow#2611]
The hyperlink isnt directing you anywhere, mouse overing over it and typing down the address shown in the bottom left of your browsers sents u to nowhere aswell

**Comment by Lothloryen** [comment]
Hello Naturel,

This is used to manage only the ingame issues. A new version of the website is going to be released and all the disabled features will be working again. You can write now an e-mail to dalaran.community@gmail.com to get help.

Thank you.
