### ISSUE TITLE
Warrior Rend Missing Instant Damage

### ISSUE THREAD

**Issue by Pvt-8Ball** [dalaranwow/dalaran-wow#2612]
Fairly simple to explain, the Instant damage caused by Rend when it's used against an enemy isn't there.
The DOT part seems to work fine though.

**Comment by n-ghost** [comment]
Rend had no instant damage part 'till Cataclysm.

**Comment by Pvt-8Ball** [comment]
Well the tool tip is wrong in that case, the tool tip ingame says otherwise.

**Comment by critty** [comment]
You're misinterpreting the tooltip. The total damage of all ticks combined is 380 + average weapon damage.

**Comment by Pvt-8Ball** [comment]
You're right, my bad.

**Comment by Golganeth** [comment]
Invalid report, closing up.
