### ISSUE TITLE
Cloak of shadows not removing piercing howl

### ISSUE THREAD

**Issue by xumae** [dalaranwow/dalaran-wow#2615]
Cloak of shadows should remove piercing howl, go to AT and test it. i cant make any more vids of the proof since my upload is too low to stream in my new place sorry.

**Comment by critty** [comment]
Are you sure it should? It used to do on trinitycore but it was changed here: https://github.com/TrinityCore/TrinityCore/issues/7581 I don't think piercing howl is a spell effect and thus it shouldn't be removed. 

About AT:
![wowscrnshot_070815_161210](https://cloud.githubusercontent.com/assets/13227438/8572405/b7300fa2-258c-11e5-8948-08294953c7b2.jpg)

**Comment by Golganeth** [comment]
Thank you @critty. Closing up
