### ISSUE TITLE
Important hunter bug, roar of sacrifice not making you crit immune

### ISSUE THREAD

**Issue by xumae** [dalaranwow/dalaran-wow#2621]
http://i.imgur.com/OTa2TkB.jpg as you can see a mortal strike crit me during roar of sacrifice which should not be possible, pls fix this FAST roar of sac is a very important cd for hunter.

**Comment by Lothloryen** [comment]
Hello there,

This issue is going to be fixed after the next schedule maintenance.

Thank you for your report.

**Comment by xumae** [comment]
Hey man just wanted to thank you on how fast you guys get these bugs under control, ive been on this server since b4 naxx 25 came out. Love it keep up the great work ! :)

Date: Thu, 9 Jul 2015 06:06:59 -0700
