### ISSUE TITLE
[Pet] Owner not getting in combat

### ISSUE THREAD

**Issue by buugss** [dalaranwow/dalaran-wow#2624]
When you send a pet to attack an enemy, you shouldn't be able to mount, drink or get sapped, or do anything that requires you to be out of combat. Little things such as this make a huge difference in PvP and you really should look into it again seeing that you closed other topics that were about this bug.
![nimeton](https://cloud.githubusercontent.com/assets/13255070/8595573/28c3bbf8-2652-11e5-96fe-cd3e26c4d91e.png)
This just doesn't seem right, does it?

**Comment by Rushor** [comment]
ivalid report. if your pet enter combat, the owner should not enter combat.

source:

https://github.com/TrinityCore/TrinityCore/pull/12083

http://www.warcraftmovies.com/movieview.php?id=160065 1:34
http://www.warcraftmovies.com/movieview.php?id=122825 3:20
http://www.warcraftmovies.com/movieview.php?id=152507 9:59
http://www.warcraftmovies.com/movieview.php?id=180949 3:35
