### ISSUE TITLE
[Druid] Omen of Clarity and Primal Precision.

### ISSUE THREAD

**Issue by TheHornfreak** [dalaranwow/dalaran-wow#2626]
Well. Basically. Omen of Clarity and Primal Precision Talents are not working properly; at least with feral druids. I cannot use neither shred nor mangle or whatever besides rake when the clearcasting buff is up. In the talent clearly says (The clearcasting states reduces the mana, rage or energy cost of your next spell by a 100%) Which is not happening.  It lowers the dps by a lot. The problem with Primal Precision is that basically, besides the expertise bonus the talent is useless because by default you recover 100% of your energy if you fail ANY spell in feral in this server. It should spend the energy as usual and then, if you try a finishing moves and it fails it should give you back 80% of that energy not all the energy you spend. On every single spell that you miss.,, Well. That´s all. I hope this issues and the issue with Death and Decay not generating aggro with the dks gets addressed any time soon.

**Comment by M0dinstaller** [comment]
Omen of Clarity sometimes has "fake" procs. It procs but it doesn't really reduce the cost of your next spell. I saw this on boomkin & feral builds, but oddly, never in resto builds, so it may have something to do with melee attacks or damaging spells.
Also, Omen of Clarity procs from way too many things. Changing gear procs it, proccing something (including Omen itself) procs it, summoning someone procs it, changing form procs it, using an item procs it. During the oracle daily quest that asks you to dig treasure, omen randomly procs from nothing (I imagine that this quest uses scripts that somehow act on your character and that makes omen proc).

**Comment by Golganeth** [comment]
Directly related to #491
