### ISSUE TITLE
[Quest] [Deep in the Bowels of The Underhalls]

### ISSUE THREAD

**Issue by Snusnufs** [dalaranwow/dalaran-wow#2627]
The quest in question is working fine but the quest mob http://wotlk.openwow.com/npc=30409 drops a quest start item that cant be looted http://wotlk.openwow.com/item=42772. I have kill him 5 times and I still cant loot the quest start item. I hear the sound that I loot the item but I don't get it in my bags.

I have tried to wait a bit and relogg to see if that helpt but it did not.

Plus there are maybe a bit to many mobs around him.
![mobs](https://cloud.githubusercontent.com/assets/13010665/8610556/caeb8bf2-26b3-11e5-9c23-17d26247c300.png)

**Comment by NotBadGuy** [comment]
Confirming, the quest item that starts a new additional quest cannot be looted for some reason. He likewise drops this quest item only once, first time that you kill him.

**Comment by Lothloryen** [comment]
Working already.
