### ISSUE TITLE
Vault of Archavon - Emblem of Triumph 

### ISSUE THREAD

**Issue by Johanes022** [dalaranwow/dalaran-wow#2629]
Bosses inside VoA 25 drop Emblem of Triumph instead of 
Emblem of Valor (Archavon The Stone Watcher)
Emblem of Conquest (Emalon The Storm Watcher)
i can also add that Emblem of Triumph drops in VoA 10 aswell (both bosses)
ps: i will provide screenshots if needed.

**Comment by Golganeth** [comment]
#2674
