### ISSUE TITLE
Shop issue

### ISSUE THREAD

**Issue by injuryble** [dalaranwow/dalaran-wow#2630]
Hi

I have bought some donation points (25) but for some reason it gave me 27.
but thats not the issue, I bought a boost for 12 donation points but the site took 24 donation points from my account. thats really shit.. is it somehow possible to look up that i had 27 donation points, so i could get my "extra payed" points back?

Dear Injuryble from Algalon

**Comment by injuryble** [comment]
EDIT: My boosted char is bugged.. the stats are all wrong and nothing works proberly.

**Comment by Golganeth** [comment]
Invalid report. The bug tracker only lists in-game issues with quests, NPCs and such. Feel free to send an e-mail to dalaran.community@gmail.com-and your issue will be taken care of.
