### ISSUE TITLE
Charge in Raids

### ISSUE THREAD

**Issue by Kaban99** [dalaranwow/dalaran-wow#2631]
Lately there's been problem with charge, on most raid bosses and even some trash is not possible to use charge. Even if you are in range nothing happens. It's little problem for warrior tanks cause they lose rage that they need to get fast threat

**Comment by Vaxsysl** [comment]
Hmm, thank you for reminding me, this is one bug I forgot to report or reply to. I will confirm this. If there has been any, uh, pathing or other...stuff, updates, we warriors (and ferals) are unable to charge over most of clean ground. I couldn't charge to Patchwerk, that I recall. Some dungeons and locations were always impossible to use charge over, but now even more things got...messed up. I'll give a clear update on this after my next raid I'll do on my warrior.

**Comment by Lothloryen** [comment]
Hello there,

This issue shall be corrected within the next scheduled maintenance.

Thank you very much for the report.
