### ISSUE TITLE
Infinite Looting

### ISSUE THREAD

**Issue by KazJR** [dalaranwow/dalaran-wow#2632]
Not sure if this really constitutes as a "bug" per-se, but I found a dead mob in Dragonblight that can be looted indefinitely for a bag containing 1-2 items worth about 10silver each. Might not seem like alot but racks up over time I suppose.

Screenshots of location & mob:
http://s900.photobucket.com/user/Unsortedfaith/media/WoWScrnShot_071115_101200.jpg.html
http://i900.photobucket.com/albums/ac204/Unsortedfaith/WoWScrnShot_071115_101212.jpg

**Comment by Golganeth** [comment]
#866
