### ISSUE TITLE
Omen of Clarity bug (internal cd)

### ISSUE THREAD

**Issue by Vidmantasaf** [dalaranwow/dalaran-wow#2633]
Omen of Clarity appears to have internal cooldown of 10 seconds which was removed in patch 3.0.3.
I've been testing  it on dummy and it would only refresh duration when 4sec~ is left or spell dissapeared for 30mins(proves 10ICD).
http://www.mmo-champion.com/threads/611019-Blue-Posts-on-Agility-base-crit-OOC-change-Haste-and-Range-Bug BLUEPOST.

**Comment by Vidmantasaf** [comment]
I can add more video footage that explicitly says its retail after 3.0.3 patch

**Comment by Vidmantasaf** [comment]
https://www.youtube.com/watch?v=2_lt9YfVxLo another example (its most obvious while he's hitting the brain (look at badkitty addon)

**Comment by critty** [comment]
"I know it would be impossible to link blue post as they delete everything older than 5 years."
http://urbad.net/blue/ has (I think) all blue posts + links to the original threads. With http://web.archive.org/ you can find most of the old pages.

**Comment by Rushor** [comment]
```sql
UPDATE spell_proc_event
SET Cooldown = 0
WHERE entry = 16864;
```

**Comment by Vidmantasaf** [comment]
https://www.youtube.com/watch?v=RjdQYlhT_5Y more footage (ulduar patch now)

**Comment by burkey6** [comment]
ahh the internal was never removed since it was added and also only thing those videos show is that the druid is using the T8 2 peice set bonus if you count the actual clearcast procs from omen of clarity there is a 10-14 gap also further proving the 10 second internal was still there

**Comment by Vidmantasaf** [comment]
GL to get that many procs (like 1 every sec) with 2% chance :+1:
http://www.wowhead.com/spell=64752/item-druid-t8-feral-2p-bonus#comments
also it is not "different proc" 
![untitled](https://cloud.githubusercontent.com/assets/13163879/8635894/83f58004-2848-11e5-8492-9a85b5f6fd2e.png)

**Comment by Vidmantasaf** [comment]
Just for fun I will keep posting feral PoV videos where it is obvious that clear casting had no ICD on live : 
Northrend Beasts : https://www.youtube.com/watch?v=YbFAtHxlsDk (its blurry but if you look closely it is proccing a lot, 2:40 is like even 2 or 3 in a row)
Jarraxus : https://www.youtube.com/watch?v=538Nff3BofI (during whole video, this guy is full on haste or luck lol)
I am not uploading champions for obvious reasons (any footage is not much about dpsing its more about cc)
Twin Valkyr : https://www.youtube.com/watch?v=3BfplVj3zmk
Anub'arak : https://www.youtube.com/watch?v=4byiwcwuRsI
Lady Deathwhisper : https://www.youtube.com/watch?v=cpzAIJx7ZF8 (bear 1:53 2 cc procs in a row)
Deathbringer Saurfang : https://www.youtube.com/watch?v=kKBUJj8FdiI
really too bored to post more you get the point, there was no ICD on Omen  in retail.

**Comment by burkey6** [comment]
still no patch notes where the internal cd is removed ?

**Comment by burkey6** [comment]
http://wowwiki.wikia.com/Patch_3.0.2

This is the last patch that mentions omen of clarity was changed in documented and undocumented.

possible druids is using 2 piece T8 in all videos ? open minded.

coincidence that this server has 10 second internal aswell ? again open minded.

This is the last input im putting on this i hope you find something  more to solid to prove it wrong : )

Ps: kinda hoping the facts are wrong.

**Comment by burkey6** [comment]
Damnit i was wrong XD
kept searching and found 
https://www.youtube.com/watch?v=gYm2GGjVnno
https://www.youtube.com/watch?v=CHgI-pyhIEI&feature=youtu.be&t=1m1s

Yeah clearly shows it proccing multiple times before existence of T8

Hope this gets fixed soon sorry for doubts.

**Comment by Vidmantasaf** [comment]
even brent approves, pls fix that, save the cat population in server <3

**Comment by Vidmantasaf** [comment]
![animals_828](https://cloud.githubusercontent.com/assets/13163879/8638059/4a8f5cfe-28b6-11e5-80cd-0f2c3c16c63b.jpg)

**Comment by Rushor** [comment]
stop discussion shit...

```sql
UPDATE spell_proc_event
SET Cooldown = 0
WHERE entry = 16864;
```

apply this and everything will work fine

**Comment by Vidmantasaf** [comment]
bump

**Comment by Lothloryen** [comment]
Hello there,

Thank you for the report, the issue has been fixed.

And Rushor, thanks again for your contribution.
