### ISSUE TITLE
General Vezax - Tiger's Fury ( King of the Jungle)

### ISSUE THREAD

**Issue by Vidmantasaf** [dalaranwow/dalaran-wow#2634]
General Vezax do not regenerate energy when Tiger's Fury with King of the Jungle talent is used (should regenerate 60) proof : 
https://www.youtube.com/watch?v=RjdQYlhT_5Y (pay additional attention on animus spawn, druid OoC procs go crazy when haste pot/bloodlust is used)

**Comment by burkey6** [comment]
thats before the ToC/ ICC talent changes

**Comment by Vidmantasaf** [comment]
changes? nerfs? its 60 energy m8 ( just as in 3.3.5a we are playing)

**Comment by Lothloryen** [comment]
Hello there,

This was working already, thank you.
