### ISSUE TITLE
Warrior Talent: Titans Grip

### ISSUE THREAD

**Issue by burkey6** [dalaranwow/dalaran-wow#2639]
Titans Grip is not applying the -10% Physical Damage from the talent to the warrior while it is weilding 2 twohanded weapons.

**Comment by burkey6** [comment]
bump

**Comment by lmmense** [comment]
This needs a serious fix, it's overpowered as hell.

**Comment by burkey6** [comment]
bump

**Comment by Golganeth** [comment]
#1065
