### ISSUE TITLE
[Quest] Guardian of the Monument [11059] - [Drop Rate]

### ISSUE THREAD

**Issue by ashido96** [dalaranwow/dalaran-wow#2641]
The mob Apexis Guardian does not have a 100% drop rate for the quest item Apexis Guardian's Head while on the quest Guardian of the Monument.
Much Sadness for wasting 35 apexis crystals.

http://www.wowhead.com/quest=11059/guardian-of-the-monument
http://www.wowhead.com/npc=22275/apexis-guardian
http://www.wowhead.com/item=32697/apexis-guardians-head

**Comment by Penguindrum** [comment]
Got mine on fifth kill

**Comment by Cone182** [comment]
I have killed him 5 times, no drop yet.

**Comment by ImprezaWoW** [comment]
Different sources show different drop rates, but not one of them shows anywhere near 100%. 
[67%](http://www.wowhead.com/item=32697/apexis-guardians-head)
[43%](https://wotlk-twinhead.twinstar.cz/?item=32697)
[53%](http://wotlk.openwow.com/item=32697)
Is this really a bug when nowhere is it promised that you will get it on the first drop? Don't think so.

**Comment by Golganeth** [comment]
The % drop rate system of some DB sources (like Wowhead or similar) takes into account the total kills, including those that happened when a player didn't have X quest in their log. In this case, people farming crystals without the quest could cause the % to go down drastically.

Judging by the [Wowhead comments](http://www.wowhead.com/quest=11059/guardian-of-the-monument#comments), no one seems to complain about not getting it on their first kill, which leads me to believe it should be indeed 100%

> You need 35 shards to start the quest, the game works the same as the small version, except that you need 4 people standing at each button.
After 6 rounds a giant will spawn, kill it for the quest item!

--------------

Reopening for now.

**Comment by Golganeth** [comment]
The drop rate of the Head has been adjusted and it will be applied to the live realm soon.
