### ISSUE TITLE
Bug abuse: Rogue Spec swapping

### ISSUE THREAD

**Issue by burkey6** [dalaranwow/dalaran-wow#2642]
As i am to currently understand you can gain Overkill or Master of Subtlety after changing to a spec without those talents with a certain method.
1. Start in the spec with the talent you want to abuse.
2. Go into stealth
3. Change your spec to the second spec
4. go into stealth again
5. Wait for when the buff would have faded the leave stealth
6. enjoy your permanent buff without the talent for it and do extra dps you shouldnt be doing

**Comment by Golganeth** [comment]
#2006
