### ISSUE TITLE
Sun Rock Retreat Inn

### ISSUE THREAD

**Issue by Tarpor** [dalaranwow/dalaran-wow#2643]
The Horde Inn in Stonetalon Mountains in Sun Rock Retreat isn't actually counted as an inn. You can make it your home, but the extra rested gain isn't there and neither is the instant logout.

**Comment by nowonshere** [comment]
I went in at the Sun Rock Retreat inn just now & its working properly. I get rested & I can logout instantly.

**Comment by Tarpor** [comment]
well uhhhhh it suddenly seems to work, guess it was temporary or something
