### ISSUE TITLE
Polymorph not subduing targets 

### ISSUE THREAD

**Issue by jdrodgers86** [dalaranwow/dalaran-wow#2645]
I've noticed on several occasions in the Barrens and Waling Caverns that Rank 1 polymorph is working incorrectly. Several mobs will not only follow you around, but they will continue auto attacking, ranged attacking, and even casting spells. Most notably are the Druids of the Fang in WC and the quillboars north of Camp Tur...Tar...whatever in the Barrens.

**Comment by Vaxsysl** [comment]
ALL Polymorph levels are bugging out when subduing. There's a topic related to this. Even ranged attackers can attack through polymorph.

**Comment by Golganeth** [comment]
#2166
