### ISSUE TITLE
Still broken

### ISSUE THREAD

**Issue by muffygb** [dalaranwow/dalaran-wow#2647]
Quest: http://www.wowhead.com/quest=10930
Fumper (Drum): http://www.wowhead.com/item=31825
Sand Gnome: http://www.wowhead.com/npc=22483
Hai'shulud: http://www.wowhead.com/npc=22038
Mature Bone Sifter: http://www.wowhead.com/npc=22482
Problem:
Using Fumper is not spawning anything but despawns clefthoof corpse.

How it should work:
1. Take quest and find a Clefthoof
2. Kill the Clefthoof and use the drum near the corpse;
3. By using the drum near the corpse, you should spawn either 3 Sand Gnomes, 2 Mature Bone Sifter or the Hai'shulud himself.
4. If any of first 2 spawn, kill them, kill more clefthoofs and try again. If "boss" spawns, kill him, loot his organs and turn in the quest.

**Comment by ashido96** [comment]
#611

**Comment by Tarpor** [comment]
you even posted there yourself, why would you triple post it, sigh
