### ISSUE TITLE
Passive auras causing people who receive them to get in combat

### ISSUE THREAD

**Issue by buugss** [dalaranwow/dalaran-wow#2648]
Gaining auras such as Icy Talons, Crusader Aura, Replenishment and many more will cause the receiver to get into combat if the buffing person is in combat. The combat state will fade at the exact moment the buffing person leaves combat or if the buff expires.

**Comment by Klala** [comment]
While I am unable to confirm this, it seems to be right...
I was doing battlegrounds today and I got into combat too many times by just walking past a group of people fighting.
I thought it to be only from priest's vampiric touch but it could also be from other sources...

**Comment by Lothloryen** [comment]
Hello there,

Several cases have been fixed, if you find anything else, please report them individually.

Thank you.
