### ISSUE TITLE
[Northrend][Grizzly Hills][Quest] Free at Last

### ISSUE THREAD

**Issue by InvincibleEagle** [dalaranwow/dalaran-wow#2651]
I don't get credit when I free the golems.

**Comment by n-ghost** [comment]
It's working as intended, you might need to try several times (up to 10, actually), before it works.

http://www.wowhead.com/quest=12099/free-at-last#comments

**Comment by nowonshere** [comment]
I can confirm this is working, you have to find a golem that is working & you should use only melee attack while the golem attacks you then use the item.

**Comment by Lothloryen** [comment]
Hello there,

Yes, just checked and it's working an intended.

Thank you very much.

**Comment by Cone182** [comment]
as a warlock I could not get this quest to work. The item worked on the giants, but gave no credit for it.

**Comment by Sonoor** [comment]
Just have to keep using the item on them, there are some which work and will give you credit.

**Comment by JackMV** [comment]
Can confirm that there are some giants that give no credit when the item works. Even if the quest can still be completed, this does not seem to be working as intended.
