### ISSUE TITLE
Escape From Silverbrook is bugged.

### ISSUE THREAD

**Issue by InvincibleEagle** [dalaranwow/dalaran-wow#2653]
I can control the horse, no worgen attack, and I don't get credit when I ride back to town.

**Comment by warcraftgeekygamer** [comment]
I can confirm this quest is bugged. I was able to control the horse back to town. Worgen did not attack and I did not receive credit for quest completion.

https://www.youtube.com/watch?v=OnbIHB1wBiM - this is how the quest is supposed to work.
https://www.youtube.com/watch?v=6UFEvKrw3qM - another working video

http://wotlk.openwow.com/npc=28019
http://wotlk.openwow.com/quest=13524

**Comment by maegrim** [comment]
For about half the distance the horse ran on its own as it should, then stopped. I ran the rest of the distance controlling it. No credit, and the horse started attacking me as I dismounted.

**Comment by Roxian** [comment]
After abandoning and retaking this quest on my own multiple times I found a solution. I found that with the help of another person I could complete it and get credit. It worked for me and my other party member.

From the moment you hop on the horse with the NPC the other person in your party has to aggro and/or kill the spawned worgens and your horse won't bug out. It is crucial you don't get hit by them. I think that was the problem, once I got hit, I could control it and it would never give me credit.

So if your party member keeps the worgens away from you, the horse will follow the same road as it would in retail. It will only bug out for a few seconds and go under the terrain under Vordrassil just before ariving at Amberpine Lodge. Don't worry, it'll find his way up again. You'll hop off it at the Stablemaster there and get credited. Confirmed on Algalon server.

**Comment by Mantigora** [comment]
Completed quest! I made focus on him and just followed on my own mount. For easier targeting set any icon on him because after jumping over river he goes under ground for a short time.

**Comment by Rushor** [comment]
the horse still drops below the map sometimes, but thats a gernal issue, do hot review this here!

4f7d6649a8278369e0cbdb608eb9b83ad5d56441
whats fixed?
- moved the bad sai to vehicleai, so the horse will no longer behave strange
- sourrounding creature now actually try to attack the horse
- questcredit should always be rewarded

**Comment by Golganeth** [comment]
- When you pick up the quest, the prisoner NPC will drop below the building and head towards the horse
- Along the way there's a few issues with waypoints, while crossing the river for example. Nothing too major
- The Horse's default speed should be slightly increased.
- Some NPCs will get stuck on evade while you escape, so you can't damage them. Even after you complete the quest and leave the horse, they will still be chasing you, and you will not be able to kill them (evade).

**Comment by Rushor** [comment]
yeah these are all general issues :(
