### ISSUE TITLE
[Quest][Argent Tournament] Rescue at Sea

### ISSUE THREAD

**Issue by M0dinstaller** [dalaranwow/dalaran-wow#2654]
Hi there, sorry if this is a duplicate, couldn't find any other issue on that.

I've always noticed how on this server if you attack a mob that is in combat with an NPC, you won't always get credit from killing it. I do not know if such a game mechanic was present on retail or not, but I always assumed it was.

Only problem is that this particular mechanic is now preventing the completion of this quest (and a few others as well, but I don't remember which ones). The quest asks you to kill 11 mobs that are constantly being attacked by NPC's. As such, it makes it very difficult to get credit from the kills and requires you to come when the mobs are still around full hp, and you usually still have to wait for 1 respawn.

I could not find anything on this issue when browsing discussions from retail on this quest, which makes me believe the game mechanic is either not blizzlike or blizz disabled it on some mobs to make questing easier.

**Comment by darkwulfv** [comment]
Yeah, any quest that involves NPC's are made much more difficult due to the NPC's usually getting credit for the kills unless you initiate the fight and deal 50%+ of the damage. This is a problem that is not isolated to this quest, though I don't know if it's actually Blizz-like or not. I don't think it would be though, it seems needlessly frustrating.

**Comment by ashido96** [comment]
I will say specifically for this quest at least that you do not have to initiate the fight to get quest credit, just deal 50% of the max hp. I often complete this by going to the opposite factions ship and killing all the defender's there so i have the fresh vyrkrul spawns all to myself without any guards to kill them off.

**Comment by M0dinstaller** [comment]
Yes indeed, npcs don't tag mobs like players do, as far as I've seen they have to deal a certain % of the mob's hp to make it "theirs".
