### ISSUE TITLE
[Quest][Classic] The Severed Head [1239] and 4 more

### ISSUE THREAD

**Issue by ashido96** [dalaranwow/dalaran-wow#2655]
After Completing The Lost Report [1238] the quest The Severed Head [1239] does not become available from the NPC Nazeer Bloodpike [4791]. As this is the second quest in a series of six quests 4 more are also unobtainable.
The Troll Witchdoctor: http://www.wowhead.com/quest=1240/the-troll-witchdoctor <- this one has comments giving a detailed outline of the entire chain
Marg Speaks: http://www.wowhead.com/quest=1261/marg-speaks
Report to Zor: http://www.wowhead.com/quest=1262/report-to-zor
Service to the Horde: http://www.wowhead.com/quest=7541/service-to-the-horde

The Lost Report: http://wotlk.openwow.com/quest=1238 http://www.wowhead.com/quest=27244/the-lost-report
The Severed Head: http://wotlk.openwow.com/quest=1239 http://www.wowhead.com/quest=1239/the-severed-head
Nazeer Bloodpike: http://wotlk.openwow.com/npc=4791 http://www.wowhead.com/npc=4791/nazeer-bloodpike

**Comment by Rushor** [comment]
http://www.wowhead.com/quest=1239/the-severed-head#comments:id=16532
