### ISSUE TITLE
Balance Druid Lunar Eclipse Bug

### ISSUE THREAD

**Issue by Ginsanity** [dalaranwow/dalaran-wow#2658]
At the end of the duration of Lunar Eclipse (Starfire), the final Starfire after the effect has ended should almost always be a crit when near 30% crit without eclipse. However, even if Starfire is casted while eclipse is up, once it falls off, it no longer has the effect.

This is a major issue as it seriously effects the balance druid rotation, consistency and therefore balance druid's overall dps.

Summary: Eclipse procs, cast starfires, eclipse ends and final starfire does not keep eclipse effect.

**Comment by Illiyara** [comment]
I'm pretty sure it's working as intended.

A casted spell's crit chance is determined when a spell cast finishes, not when it starts. Starfire shouldn't benefit if it lands after the Eclipse buff expires. If it really worked that way, it's would be a part of every moonkin pve guide to make sure that you're casting starfire when lunar eclipse is ending. I haven't seen anyone mention that.

**Comment by Max0r847** [comment]
Yea I noticed this too, it's really annoying. So many wasted casts
