### ISSUE TITLE
Quest: Divination: Gorefiend's Cloak

### ISSUE THREAD

**Issue by Some5576** [dalaranwow/dalaran-wow#266]
Quest Divination: Gorefiend's Cloak - 10635

Issue: You can see the NPCs which you have to attack if you have Spectrecles equiped, but they are not in the line of sight and not attackable at all. (could be because of the Pathfinding System).

They should be attackable and you should be able to farm them and loot the item needed for the quest once you kill them.

NPC - Cleric of Karabor - 21815

http://wotlk.openwow.com/quest=10635
http://www.wowhead.com/quest=10635/divination-gorefiends-cloak

The Clerics of Karabor are located just south of the entrance to the Black Temple and you have to wear the Spectrecles to see them.

The Cloak seems to be a fairly rare drop, I farmed the clerics for about 40 min before I got mine to drop

How the quest has to work:
http://www.youtube.com/watch?v=qtA0SdteUIA

**Comment by Golganeth** [comment]
This is no longer an issue.
