### ISSUE TITLE
Quest - The Relics of Wakening

### ISSUE THREAD

**Issue by Kreatores** [dalaranwow/dalaran-wow#2660]
http://www.wowhead.com/quest=483/the-relics-of-wakening

The chest that should contain Sapphire of the Sky (http://www.wowhead.com/item=3407/sapphire-of-sky) is sparkling, but the item is not in the chest.

**Comment by ashido96** [comment]
Were there any other items in the chest when you looted it? If so, that just means someone was an ass and didn't make the quest item respawn by entirely looting the chest.

**Comment by Golganeth** [comment]
Fixed in-game. This is a rare and general issue with game objects.
