### ISSUE TITLE
[Shaman] Earthliving Weapon + Blessing of Eternals

### ISSUE THREAD

**Issue by Marquito01** [dalaranwow/dalaran-wow#2668]
**How it should work:** On targets below 35%, single target direct heals should **always** trigger earthliving hot (20% chance from [Earthliving Weapon](http://wotlk.openwow.com/spell=51994) + 80% from talent [Blessing of Eternals](http://wotlk.openwow.com/spell=51555)).

Source: http://wow.gamepedia.com/Blessing_of_the_Eternals

**How it works:**

Earthliving procs on targets below 35% from single target direct heals are rare and not guaranteed:

Lesser Healing Wave:
![lesser hw](https://cloud.githubusercontent.com/assets/12214615/8694649/a3da6138-2ae0-11e5-8cb9-f6d0ec175904.png)

Healing Wave:
![hw](https://cloud.githubusercontent.com/assets/12214615/8694656/aa878bf0-2ae0-11e5-8838-f96cd3ccace3.png)

Riptide:
![riptide](https://cloud.githubusercontent.com/assets/12214615/8694662/b2224c2e-2ae0-11e5-9645-611aff4ee0e7.png)

I suspect the 2nd part of talent [Blessing of Eternals](http://wotlk.openwow.com/spell=51555) is not working at all, which is causing the issue.

PS. Although the talent effects chain heal as well (which has innate lower earthliving proc chance), finding the exact proc increase for chain heal is bit more difficult. If anyone finds it pls post it here.

**Comment by robinsch** [comment]
On PTR.

**Comment by Edzero** [comment]
Shaman Earth Living Weapon proc rate now correctly increase in accordance with the Blessing of Eternals talent when the target is below 35% health.

**Comment by robinsch** [comment]
@Lothloryen Not made it to PTR. @TeridanDW Please test after PTR update.

**Comment by TeridanDW** [comment]
Works as intended on PTR.

**Comment by Marquito01** [comment]
If this is supposed to be already on live, its not working at all.

**Comment by Lothloryen** [comment]
@Marquito01 Thank you for the update. @TeridanDW Can you check if this is currently still working? This is already in both, PTR and Algalon.

**Comment by Marquito01** [comment]
Can you reopen this report? It was in the changelog but didn't get fixed. thx

**Comment by robinsch** [comment]
@Lothloryen
