### ISSUE TITLE
[Shaman] Earth Shield Coefficient

### ISSUE THREAD

**Issue by Marquito01** [dalaranwow/dalaran-wow#2669]
**Issue:** Earth Shield has currently incorrect spell power coefficient and therefore scales incorrectly with bonus healing. Current coefficient is approx. 0.4756.

**How it should work:** 
The correct coefficient per 1 charge is [0.286](http://wowwiki.wikia.com/Spell_power_coefficient) (ES coefficient) * [1.88](http://wowwiki.wikia.com/Spell_power) (standard healing spell factor) = **0.538**

![image](https://cloud.githubusercontent.com/assets/12214615/16536269/ddb3b65a-3fef-11e6-9d65-86ef8e4845bd.png)

**Comment by Marquito01** [comment]
Not a programmer but this looks helpful:

https://github.com/TrinityCore/TrinityCore/issues/6268

**Comment by Rushor** [comment]
```c++
// +53.8% from sp bonus
                    float bonus = 0.28f;

                    bonus *= caster->SpellBaseHealingBonusDone(GetSpellInfo()->GetSchoolMask());

                    bonus = caster->ApplyEffectModifiers(GetSpellInfo(), aurEff->GetEffIndex(), bonus);
                    
                    amount = caster->SpellHealingBonusDone(NULL, sSpellMgr->GetSpellInfo(SPELL_SHAMAN_EARTH_SHIELD_HEAL), amount, HEAL);

                    amount += int32(bonus);
```

**Comment by robinsch** [comment]
Tested on PTR. Fix confirmed.

**Comment by Edzero** [comment]
Earth Shield now uses the correct Spellpower coefficient.
