### ISSUE TITLE
Ulduar: Keepers dispawning in the upper level but not spawning in Yogg's room

### ISSUE THREAD

**Issue by chaodhib** [dalaranwow/dalaran-wow#2671]
Hi,

My guild is doing Ulduar 25, spreaded on multiple days. This is now the third week we cant progress through Yogg since a few keepers (most importantly Thorim) keep dispawning (without being talked to) in the central room above Yogg's room. At the same time, they are not spawning in Yogg's room neither. Once a keeper is defeated, we usually discover its bugged disappearance in the next run.

Thank you.

**Comment by Lothloryen** [comment]
Hello there Chaodhib,

Thank you for the report, I missed applying one thing for this. It will be working again as it was before with the next scheduled maintenance.

**Comment by chaodhib** [comment]
Ok awesome.

Allow me to grab this occasion since I had a hard time contacting you and hijack my own report to ask: did you received my email regarding my application for a volunteer developer position in your team?

Thanks.

Best regards,

Chaouki

**Comment by Lothloryen** [comment]
Hello again Chaodhib,

I will take a look, I receive a lot of e-mails on that address.

Thank you very much for your collaboration.
