### ISSUE TITLE
Wintraders

### ISSUE THREAD

**Issue by xumae** [dalaranwow/dalaran-wow#2675]
It's pretty amazing how many players in this malice guild wintrade, this should be ban-able as it is on most servers. Here is the wintrader admitting it,
http://i.imgur.com/b398CdQ.jpg
Wintraders team in question : http://i.imgur.com/JPNvRGD.jpg
I was 33-0 at 2400 mmr and my personal rating was only like 1850 so this is beyond obvious wintrading, admins please check the logs and see who was involved.

**Comment by Golganeth** [comment]
This is the Bug Tracker and as its name suggests, this is not the correct place to report players.
