### ISSUE TITLE
Wotlk Tabard Reputation

### ISSUE THREAD

**Issue by Healionthrope** [dalaranwow/dalaran-wow#2679]
Hi!
The WOTLK reputation tabards ( such as Tabard of the Kirin Tor)  say reputation should be given to  that certain faction when participating in level 80 dungeons. I've tried running 80 dungeons such Normal Mode Utgard Pinnacle, and have received no reputation. I know that this reputation works for lvl 80 Heroic Instances, but not the 80 normal instances.

Thanks a lot!!

**Comment by warcraftgeekygamer** [comment]
For the dev's:

http://www.wowhead.com/item=43157/tabard-of-the-kirin-tor#comments

**Comment by Golganeth** [comment]
#2057 See 1)
