### ISSUE TITLE
Dragonblight: Heated Battle

### ISSUE THREAD

**Issue by InvincibleEagle** [dalaranwow/dalaran-wow#2680]
I don't get credit when I kill most ghouls.

**Comment by nowonshere** [comment]
Yeah, can confirm this. Already wrote an in-game ticket re this.

**Comment by Golganeth** [comment]
#669

**Comment by Kaporalhart** [comment]
You closed the bot hthis thread and the #669 please open one or you'l lthink the problem is solved. The mobs spawn correctly now, but you still can't tag them. Please make the tag work by dealing 10% damage if you can and it will be doable.
