### ISSUE TITLE
Plume of Alystros

### ISSUE THREAD

**Issue by InvincibleEagle** [dalaranwow/dalaran-wow#2681]
He only awakens for a split second after using the quest item, not nearly enough time to attack let alone kill him.

**Comment by nowonshere** [comment]
This quest works, you have to be at near the water facing Alystros then it will come down and attack you...

**Comment by Golganeth** [comment]
#503

**Comment by belegija** [comment]
maybe sometimes he works, but for me now it doesnt work. issue as described in first post.
