### ISSUE TITLE
[Zul'Drak] Skalps!

### ISSUE THREAD

**Issue by InvincibleEagle** [dalaranwow/dalaran-wow#2683]
Whenever I try to scalp some of the trolls (not all), it just say "you can't do that right now".

update: So, after a little bit of trial and error and critical thinking, I've discovered that the scalpable trolls are the head hunters; the strikers (on the bats) cannot be scalped. However, the quest log implies all Heb'Drakkar trolls can be scalped.

**Comment by Golganeth** [comment]
#1454
