### ISSUE TITLE
Object : Everfrost Chip [ID: 193997]

### ISSUE THREAD

**Issue by Klala** [dalaranwow/dalaran-wow#2684]
I was looking for answers but never found any. As I was flying around Dun Niffelem, I was looking around for Everfrost Chips [ID: 193997] but I didn't encounter any which was weird because before completing the quest chain for the sons of hodir faction I could see a few here and there.
So I kept on looking until I found one but when I got close to it it disappeared.
I have encountered this kind of behavior among objects before and realized it is because the area phasing. I assume that the Everfrost Chips [ID: 193997] are spawning in the correct areas but in the wrong area phase. They should be spawning in the area phases so those who finished with the sons of hodir quest chain could see them too.

**Comment by marsalandrei** [comment]
I don't remember seeing any before the phasing, but after the phasing, I wasn't able to find any
