### ISSUE TITLE
>Warlock< fel concentration doesnt work.

### ISSUE THREAD

**Issue by testament707** [dalaranwow/dalaran-wow#2686]
As title saz, fel concentration tallent doesnt work. 70% reduced pushback doesn work at all. Kinda makes Affliction warlock unplayable.

**Comment by arvidinge** [comment]
Have you checked it specifically with the drain spells? it doesn't include shadow bolt (in case you picked it and tried the pushback with shadow bolt)

**Comment by testament707** [comment]
Ofc. All drain spells get pushback as shadow bolt, thats how i detected bug. Im still low lvl so cant tell if unstable affliction and haunt are also bugged with not getting reduced pushback.

**Comment by arvidinge** [comment]
i can confirm this bug

**Comment by arvidinge** [comment]
actually i just checked this again by starting a fight with a random mob in terokkar without the talent (results in 7.5 sec pushback on drain soul), and then picking it up while i fight it, and it's working (2.2 sec pushback). Maybe it doesn't work on certain spell ranks or player levels vs the enemy?
