### ISSUE TITLE
Mobs reset immidiately outside max cast range

### ISSUE THREAD

**Issue by arvidinge** [dalaranwow/dalaran-wow#2688]
I'm on a warlock leveling in durotar. If i put myself at absolute max range (one more step further away and I'm out of range from the mob), cast a shadow bolt and start running away, the mob takes the damage and then immidiately resets (if i also apply corruption before running, it's damage is absorbed while the mob is reseting)

**Comment by arvidinge** [comment]
So far this has only happened around Sen'jin village, killing scorpids.

**Comment by Golganeth** [comment]
#2474
