### ISSUE TITLE
Life tap tooltip error

### ISSUE THREAD

**Issue by arvidinge** [dalaranwow/dalaran-wow#2689]
First rank it says "Converts 78 health into 27 mana" but it actually just converts 27 (or so, not exactly sure) to 27.

**Comment by arvidinge** [comment]
It also Fizzles at 78 health but still doesn't use up nearly all of it when cast.

**Comment by warcraftgeekygamer** [comment]
Life tap will fizzle when you are at extremely low HP - otherwise your character would run out of HP and thus die.

http://wowwiki.wikia.com/Life_Tap
http://www.wowhead.com/spell=1454/life-tap#comments (read the old comments from WotLK)

**Comment by arvidinge** [comment]
It should fizzle at 27 health, not 78.

**Comment by Tarpor** [comment]
I noticed this on my warlock too, it might have something to do with heirlooms.

Example: I have 18% hp and I get fizzled(Can't tap), then when I get to 19% hp, I can tap again, but I only go down to 10% hp.

**Comment by warcraftgeekygamer** [comment]
http://wotlk.openwow.com/spell=1454

for dev's

**Comment by arvidinge** [comment]
I'm not wearing heirlooms btw so i doubt it. probably an inherent error with the spell

**Comment by Rushor** [comment]
Tooltip informations are from your client. Such issues cannot be fixed from serverside. /closing
