### ISSUE TITLE
[Quest] The admiral's orders

### ISSUE THREAD

**Issue by arvidinge** [dalaranwow/dalaran-wow#2690]
Picking up leiutenant benedict's key works but unlocking his chest doesn't (which should reward the click-to-start-quest-item "Aged Envelope" http://www.wowhead.com/item=4881/aged-envelope). There is a cast animation and cast bar when you try to open it, the chest animates opening the lid, immidiately closes, you lose benedict's key, and you don't get the envelope. It also spawns a marine behind you who starts attacking you, he doesn't drop the envelope either when killed.

I killed benedict again and he dropped another key, i tried the chest again, but no luck.

**Comment by Tarpor** [comment]
worked for me, might have respawn timer
