### ISSUE TITLE
[Mage] Fiery Payback 

### ISSUE THREAD

**Issue by Milton3450** [dalaranwow/dalaran-wow#2691]
The disarm and damage reduction with this talent works fine but Pyroblast cast time is only reduced 1.75 sec no matter whether you have 1/2 or 2/2 points spent. With 2/2 spent it should be 3.5 sec. 

To get around this you must go in your second spec (dual spec) and get below 35% hp and then respec back while under 35% and talent works. Also if you logout or go from your second spec you have to do it every time.

I made this issue to sum up the problem with the talent.

Original bug thread here: https://github.com/dalaranwow/dalaran-wow/issues/1778

**Comment by Golganeth** [comment]
Duplicated.
