### ISSUE TITLE
[Hunter] Scatter shot pathing bug, very important!

### ISSUE THREAD

**Issue by xumae** [dalaranwow/dalaran-wow#2692]
When you scatter a moving target they bug around making it literally impossible to land a trap sometimes, how scatter works on dalaranwow:
http://www.twitch.tv/drakedog_ca/c/6971209
how it SHOULD work in 3.3.5
http://www.twitch.tv/drakedog_ca/c/6971216
As you can see, on arena tournament the player stays where they get scattered making it easy to trap as it should be. Please fix this asap! thx

**Comment by Tarpor** [comment]
Ye but lets not forget that when you trinket a scatter shot you are still suck in place

**Comment by xumae** [comment]
Im not sure i know this bug Tarpor, i just scatter trapped a priest in a bg and he trinketed the scatter and walked away from the trap just fine

**Comment by Watterx** [comment]
Related to #1447

**Comment by xumae** [comment]
Dont bring me this bad news Watterx =(

**Comment by xumae** [comment]
Could a GM atleast comment on this, even if it's a hard fix so i know you guys are aware of this very important hunter bug.

**Comment by Tarpor** [comment]
'Watterx commented 2 days ago
Related to #1447, already reported. Does't seem they plan on fixing it anytime soon.' 

u blind xumae?

**Comment by xumae** [comment]
:( pls no mean boys =(

**Comment by Golganeth** [comment]
#1447
