### ISSUE TITLE
[Hunter] Masters call bug

### ISSUE THREAD

**Issue by xumae** [dalaranwow/dalaran-wow#2695]
When you use masters call there is a chance the ability will go on cd and have no effect.
http://www.twitch.tv/drakedog_ca/c/6973346
As you can see at 12 seconds i use my cast @ xumae masters call macro while i am in a frost nova and nothing happens but the ability goes on cool down.

**Comment by Lothloryen** [comment]
Hello there,

I had a fix already prepared, I will deploy it to the server with the next maintenance.

**Comment by xumae** [comment]
Alright cool just wanted to post a video of it :D

Date: Sun, 19 Jul 2015 10:55:13 -0700

**Comment by xumae** [comment]
Bump

**Comment by Lothloryen** [comment]
Hello again,

For some reason the patch to correct this issue was missing. I have now scheduled it for the next maintenance. It works fine for me, however if the issue continues after the fix is applied, let me know.

Thank you.

**Comment by xumae** [comment]
Hey Loth, the bug just happened again vs an ele shams root. Masters call went on cd and i did not get the buff for it even tho my macro is /cast [@xumae] so it cant go to anyone else. Thx


________________________________

**Comment by xumae** [comment]
Hey i know you guys literally dont give a shit about pvp at all, but this bug is still around. Not sure if i should even post tho since you guys dont do anything that has to do with pvp.

**Comment by seork** [comment]
Masters call seems to bug out when the pet is trapped as well and not near the player then the skill is used. it will free itself .But the hunter being out of it's range is left on it's own.

**Comment by Lothloryen** [comment]
Fixed by @robinsch in #3086

**Comment by Serpentsting** [comment]
Is it not fixed. lol.

**Comment by Serpentsting** [comment]
up
