### ISSUE TITLE
[Druid] Druid Balance 4 pieces PVP Proc Issue

### ISSUE THREAD

**Issue by obryss** [dalaranwow/dalaran-wow#2696]
Can u guys take a look on the proc chance of the 4 pieces pvp set on balance druid cuz i tested and it seems quite low to None and i get the proc only from wrath cast. from the dots it doesnt proc at all and doesnt have an internal cooldown so u might check the chances of the proc. Thank you

**Comment by obryss** [comment]
Bump!

**Comment by Rushor** [comment]
http://wotlk.openwow.com/spell=46832
Proc flag 0x00010000, chance = 15, charges - 0

proccs from:
16 Successful damage from harmful magic spell cast

**Your Wrath casts** have a chance to reduce the cast time on your next Starfire by 1.5 sec.

works fine for me
