### ISSUE TITLE
Storm Peaks Foothills phasing

### ISSUE THREAD

**Issue by wkeel1231** [dalaranwow/dalaran-wow#2697]
So ive done every quest outside of one thats in the foothills and cant get to it to do it. I can see the NPC but as soon as I enter the foothills, it phases and disappears. Its stopping me from doing the quest and partially preventing me from getting TLP as well. All the rhinos etc in the foothills disappear and become replaced by drawfs and giants.

Any help?

**Comment by Flagg24** [comment]
I am currently stuck in this phase, as well. However, I am not seeing any quest giver that the OP is seeing. Perhaps it's a quest that I've already completed?

**Comment by Flagg24** [comment]
This seems similar to the issue reported in TrinityCore, here: https://github.com/TrinityCore/TrinityCore/issues/10725

On an alt, I noticed that it started at some point during the Thorim portion of the quest chain with Sons of Hodir.

**Comment by Flagg24** [comment]
Issue in TrinityCore's bug tracker that might help you to track down the phasing issue:
https://github.com/TrinityCore/TrinityCore/issues/10106

**Comment by Flagg24** [comment]
Spoke to a GM in game for a short time before we were disconnected. He mentioned that in my server side tracking of Storm Peaks quests, that I wasn't showing any SoH quests as being completed, which is not correct. I have completed all of the quests.Might want to also check the code related to that.

**Comment by ImprezaWoW** [comment]
Was recently fixed, used to be triggered by doing the quest [The Brothers Bronzebeared](http://www.wowhead.com/quest=12973/the-brothers-bronzebeard) before the Frostborn King quest chain.
