### ISSUE TITLE
[Druid] Tree of Life powershifting

### ISSUE THREAD

**Issue by shaunb19** [dalaranwow/dalaran-wow#2698]
Tree of life and Moonkin form aren't clearing slows when powershifting yet every other form does. this makes resto and balance druids alot less mobile in pvp.

How to reproduce: shift out and back into tree of life or moonkin form using power shifting with a macro like 
# showtooltip

/cast !Tree of Life
or 
# showtooltip

/cast !Moonkin Form
what should happen: all slows/snares should be removed when you do this. it works for all other forms.

Slows are being cleared when going from any other form into these form just not when you powershift in these forms. https://youtu.be/aVePHnXonic video evidence of forms not working correctly. also shown is normal forms working as intended

@Golganeth @Lothloryen

**Comment by Zarjofgt** [comment]
Can confirm, Powershifting ToL will not remove slows, but exiting and entering tree form manually will.

**Comment by AttendantTock** [comment]
Hello,

Has been fixed / cannot replicate on PTR:
https://youtu.be/PXuTSZ46FFY

Closing this old ticket.
