### ISSUE TITLE
Isha Awak

### ISSUE THREAD

**Issue by blorgqq** [dalaranwow/dalaran-wow#2699]
Hello all,

I'm playing on the Kirin'Tor realm and am currently attempting the "Isha Awak" quest. Spent some time now looking for this NPC and failed to find him. I've checked wowhead for positioning and all, cannot seem to find him.

I suspect that this is a bug.

Regards
blorgqq

**Comment by xickoh** [comment]
It is there, check at 63,53.

**Comment by MalkaviaDW** [comment]
The NPC is on its position.
