### ISSUE TITLE
Class bugs (Comment to add more)

### ISSUE THREAD

**Issue by Vidmantasaf** [dalaranwow/dalaran-wow#2700]
Demonology/Destruction Warlock : incorrect order of spellhaste/casting speed talents(decimate/molten core/emberstorm/bane)
Restoration Shaman : Incorrect order of spellhaste/casting speed talents (Tidal Waves/Improved healing waves)
Incorrect spellpower values of earth shield
Earth shield procs before damage is taken (priest prayer of mending is working in similar manner)
^However similar druid/holy paladin talents are working just fine(spellhaste/casting speed)
Balance Druid : Boomkin form regenerates 2% mana from aoe crits such as starfall/hurricane
Druid general (talent) :Omen of Clarity gets used and does no effect if clicked too fast 
Frost dk : incorrect stacking of frost damage multipliers (however fire mage multipliers are just fine)
Blood dk : Dancing rune weapon is not working
Unholy dk : Gargoyle is broken 
Arcane mage : Incorrect stacking of arcane blast (stack applies before spell hits)
Fury Warrior : no -10% dmg penalty for titan's grip talent
Rogue : can abuse to get other specs buffs
Hunter : incorrect running after scatter shot
Will keep updating this as I find more bugs 
Paladin : Hammer of justice does not interrupt nonplayer casting

**Comment by juan9669** [comment]
prot war: recklessness does not proc with shockwave

**Comment by Golganeth** [comment]
Invalid report. Each issue must be reported separately. Do not report stuff that has been reported already. Thanks!
