### ISSUE TITLE
[Quest] High Commander Halford Wyrmbane (bugged but finishable).

### ISSUE THREAD

**Issue by Novenia** [dalaranwow/dalaran-wow#2702]
Link to quest: http://www.wowhead.com/quest=12298/high-commander-halford-wyrmbane

As alliance, you pick this quest up from Greer Orehammer, the Gryphon Master in Westguard Keep. Accepting the quest should put you on an automatic gryphon to Wintergarde Keep in Dragonblight, but this does not happen on this server. You do get credit for "completing" the quest as soon as you accept it so you can just manually run to the destination and turn it in. Not getting the flight is a pain though, as it takes a pretty long time to get there by running (naturally you wouldn't have the Wintergarde flight path yet).

**Comment by warcraftgeekygamer** [comment]
video for the dev's showing how this is supposed to work correctly: https://www.youtube.com/watch?v=qyfhdocFEi0

**Comment by jonanone** [comment]
The taxi path has been added for both versions of the quest (From Westguard Keep and Stars' Rest)

This update will be applied to the live realm soon.
