### ISSUE TITLE
Succubus Quest [Horde]

### ISSUE THREAD

**Issue by Broham7** [dalaranwow/dalaran-wow#2705]
I was doing the warlock succubus quest and after completing "Carendin Summons" Carendin Halgar is so post to give me the quest "Devourer of Souls" so I can continue on with the quest and get my Succubus. There is no quest to be found, no option at all to get it even.

**Comment by arvidinge** [comment]
I'm an orc warlock and i've completed the quest (i can summon succubus). What's your race and level?

**Comment by Broham7** [comment]
I am Undead and lvl 75. (yeah i know, probably should have got it sooner) I completed Carendin summons, the next quest he should have given me should take me to Godrick Farsan, but the quest to take the next step is no where to be found.

**Comment by Broham7** [comment]
I've tried just about everything listed before submitting a ticket. Nothing works and my ticket isn't getting  responded too. Getting kind of butt-flustered about this because I donated for a boost and my class isn't working fully.

**Comment by Sagrath** [comment]
Working
