### ISSUE TITLE
BRD-Hall of Crafting: Golems non-targetable

### ISSUE THREAD

**Issue by koubx** [dalaranwow/dalaran-wow#2707]
Hi, 

The golems in BRD, in the Hall of Crafting (http://wowwiki.wikia.com/Hall_of_Crafting), are not targetable, whereas they should be targetable, attackable and aggressive. The golem reference is this one: http://wowwiki.wikia.com/Warbringer_Construct

**Comment by Khronos-** [comment]
Confirmed.

**Comment by Rushor** [comment]
http://wotlk.openwow.com/npc=8905

**Comment by Rushor** [comment]
they should only be attackable an aggressive after you opened all the boxed in the room for the quest http://wotlk.openwow.com/quest=4123

This works fine on ptr:


http://i.imgur.com/N7cHFuM.jpg

**Comment by TeridanDW** [comment]
Works as intended on ptr.
