### ISSUE TITLE
Active totems LoS bug

### ISSUE THREAD

**Issue by Watterx** [dalaranwow/dalaran-wow#2710]
Active totems (cleansing, healing stream, mana tide, tremor,binding) lose their utility once you are out of LoS with them.

This should not happen. You should still get the benefits from the totems even if you are not in LoS with the totems...

Rerolling I guess, shaman is buggy as hell.

**Comment by M0dinstaller** [comment]
Can confirm this.

This does not happen with buff totems like windfury or strength of earth.

**Comment by robinsch** [comment]
On PTR.

**Comment by Edzero** [comment]
Totems will now function correctly when out of line of sight.

**Comment by ziokisame** [comment]
Still broken, the issue persist. Totem are useless behind LOS

**Comment by TeridanDW** [comment]
Tested all totems mentioned above, all of them worked as intended.
