### ISSUE TITLE
At the Enemy's Gates (daily)

### ISSUE THREAD

**Issue by InvincibleEagle** [dalaranwow/dalaran-wow#2713]
Our horses cannot trample the footmen like they're supposed to (video proof: https://youtu.be/Z6uSqv7aOX8?t=1m55s). Right now, the only way to kill them is to attack them one by one.

**Comment by jonanone** [comment]
Boneguard Footmans are now trampled by the players.

This update will be applied to the live realm soon.

**Comment by Melzy** [comment]
Not sure if this was never applied or if it was fixed but then it broke, but currently you cannot trample over them.
