### ISSUE TITLE
[NPC] Grom'Gol Flight Master Summons Wrong Faction

### ISSUE THREAD

**Issue by ghost** [dalaranwow/dalaran-wow#2714]
Title. Ally is just sprinting into town, attacking flight master, and has a horde of gryphons defending him, ruining STV for anyone trying to level.

**Comment by Rushor** [comment]
DB/Creature: Thysta - Summon the correct 'Enraged Wyvern'

* closes https://github.com/dalaranwow/dalaran-wow/issues/2714
* commit: 57e7fc714ff5b9e13e051a992136ae4c40625a1c
