### ISSUE TITLE
[Quest][Classic] Cleansing of the orb of orahil

### ISSUE THREAD

**Issue by arvidinge** [dalaranwow/dalaran-wow#2715]
The felguard you need to defeat for this quest hits way harder than it should, 3-4 shotting my voidwalker from full health as a level 36 warlock. Comments on wowhead indicates it's easily soloed at level 36 / 37

**Comment by Rushor** [comment]
http://wotlk.openwow.com/quest=4961

**Comment by Rushor** [comment]
it's blizzlike that he hit's like a truck

http://www.wowhead.com/npc=6549/demon-of-the-orb#comments:id=1263872

By cauliflower (231 – 1) on 2010/12/28 (Patch 4.0.3)		
cant solo it at lvl 47 as he practically kills my voidwalker and me in 3 to 4 shots. hardly affected by fear.

/closing
