### ISSUE TITLE
Flare of heavens for shadow priests

### ISSUE THREAD

**Issue by adytzyca** [dalaranwow/dalaran-wow#2717]
Hello, trinket Flare of the Heavens (http://www.wowhead.com/item=45518) absolutely broken for shadow priest, as well as Elemental Focus Stone (http://www.wowhead.com/item=45866), but i really care only about first one. So, after getting that item i'm just arrived to Orgrimmar dolls to check proc rate of this item. I've spent about 141 seconds before it proced first time, then, after 45 seconds GCD expire, i've spent about 120 seconds to trigger proc. Then it was two smooth procs about 45s per one, and then there was 0 procs during x2 attempts 3 minutes each. Meanwhile, i traded that item to warlock for test and he got like ~8 procs per 45 seconds (pure procs per GCD), about 4 procs per 35-40 seconds and several procs with 15-30 seconds above GCD (45 seconds) time. I've also tried trigger that proc without using MB or SW:D, but that did not even happen (and i didn't got any proc WITH using it in my last 3 min attempt as well). One mage from Nebulous with this item also told me that procs are a bit strange, but pretty stable for him. I suspect that this item is kinda broken for DoTs and channeling spells (but works pretty nice for direct spells) and beg you guys to fix that issue if possible, because that item is simply bis for every caster class, including shadow priests and its kinda unfair when one item works fine for one class (like warlock or mage) and totally broken for another one :P.
Regards.
Upd 1: Procs from [Holy Nova] damage pretty nice (like 5 procs in ~45-53s each);
Upd 2: Does not procs from [Mind Sear] or [Mind Flay] or improved DP or DoTs applying;
Upd 3: [Shadow Word : Death] and [Mind Blast] are triggering proc.

**Comment by Vidmantasaf** [comment]
http://www.wowhead.com/item=45518/flare-of-the-heavens#comments
By xenjuarn (676 – 4) on 2009/09/28 (Patch 3.2.2) comment 
atleast read wowhead before going and qqqqqq its a bug.

**Comment by Golganeth** [comment]
#2130
