### ISSUE TITLE
Quests - Sons of Hodir dailies

### ISSUE THREAD

**Issue by Klala** [dalaranwow/dalaran-wow#2719]
Each and every NPC that you are supposed to kill doesn't drop anything but the quest item needed to complete the quests.
The loot tables should be:
* Brittle Revenant: http://www.wowhead.com/npc=30160/brittle-revenant#drops:mode=
* Niffelem Forefather: http://www.wowhead.com/npc=29974/niffelem-forefather#drops:mode=
* Restless Frostborn Ghost: http://www.wowhead.com/npc=30144/restless-frostborn-ghost#drops:mode=
* Restless Frostborn Warrior: http://www.wowhead.com/npc=30135/restless-frostborn-warrior#drops:mode=
* Viscous Oil: http://www.wowhead.com/npc=30325/viscous-oil#drops:mode=
* Stormforged Infiltrator: http://www.wowhead.com/npc=30222/stormforged-infiltrator#drops:mode=

There are more NPCs that are not related to the dailies which also do not have any loot table

**Comment by Khronos-** [comment]
Confirmed.

Was hoping for some JC dailes to be completed while doing SoH but the mobs only drop quest items.
