### ISSUE TITLE
Dungeon Finder - kicking automatically from party after relogging / DCing.

### ISSUE THREAD

**Issue by Vission** [dalaranwow/dalaran-wow#2720]
Hi, I found a problem with DF, many ppl know about it, I think.
If anyone relogs or DCs while in a DF party, he automatically gets kicked, leaving him on the same place where he relogged after logging in, but without the whole party and in a separate dungeon.

This should not happen at all. If anyone relogs / DCs, he should not be kicked, unless the party vote to kicks him.

Thank You for doing anything with this annoying bug :)

**Comment by paladincnn** [comment]
And you can not queue for this instance anymore, which makes it even worse. :(

**Comment by mdl-bbarger** [comment]
It's not just within DF.  I was playing through WC with some friends (we just grouped and walked in) and I DC'd half way through the dungeon. When I relogged I was kicked and in the same spot but in a separate instance. It happened about 3 times that night (bad connection sometimes) with the same results. I had to leave the dungeon, regroup with the friends and re-enter the dungeon then proceed to run through the whole thing to find them.

**Comment by Aridam** [comment]
Confirmed as still happening -- if you relog, restart, or DC, you get automatically kicked out of the Group regardless of whether it's RDF-formed or manually so.

**Comment by Aridam** [comment]
Still happening -- if the Group is a Party (not a Raid), and anyone relogs/DCs, they're auto-kicked.

**Comment by Aridam** [comment]
Still happening across the board -- just-had it happen to me in Wintergrasp, lost all my Ranks upon re-entering, and it was just-ending, so, yeah. That's nice.
