### ISSUE TITLE
[spell] slice and dice

### ISSUE THREAD

**Issue by jessyo** [dalaranwow/dalaran-wow#2723]
yo

slice and dice triggers combat, both for the rogue using it and the target and it shouldnt

http://www.wowhead.com/spell=5171/slice-and-dice

**Comment by sokkye** [comment]
Confirmed, Slice and Dice triggers combat.

**Comment by ImprezaWoW** [comment]
[#200](https://github.com/dalaranwow/dalaran-wow/issues/200)

**Comment by Golganeth** [comment]
This is still an issue.
