### ISSUE TITLE
Ulduar: 1 Keeper achievement  not given after boss is downed

### ISSUE THREAD

**Issue by RazerStylehunter** [dalaranwow/dalaran-wow#2732]
Instance:  Ulduar 10 man mode, Raid ID 743  [Algalon server]
Boss:       Yogg with 1 keeper, Thorim

Issue:   When we downed the boss with 1 keeper, those of us did not get the corresponding achievements that should have come up.

I have full screen-shots of the boss room with only Thorim present, also a recount data for the boss fight, and a picture showing that my Achievement even for [Three lights in the Darkness] did not light up, which is also the case for my group members who previously did not do 1 light. 

https://goo.gl/photos/5CM7YCG3Eu34JXXU7

We should have got this achievement : http://www.wowhead.com/achievement=3158/one-light-in-the-darkness-10-player

and the ones with 3 and 2 keepers also. 

We would like to get the achievements for our group, 

Thanks

**Comment by Tarpor** [comment]
Same with 0 keepers.

**Comment by Crispybuilt** [comment]
Confirmed, our guild did 0 lights on 25 last Wednesday and we didn't get achievement at all.
Hope we can get awarded somehow, it's a very hard thing to achieve and we probably won't plan to do it again.

[img]http://i.imgur.com/T1E2S7v.jpg[/img]

Video of a kill: https://www.youtube.com/watch?v=32HkA7zusSw

**Comment by Tarpor** [comment]
yogg0 achieve was given out today, either fixed or lucky, or cause it was legit :^)

**Comment by ashido96** [comment]
To be re-opened. #3528
