### ISSUE TITLE
Formula: Runed Adamantite Rod

### ISSUE THREAD

**Issue by Nattaszz** [dalaranwow/dalaran-wow#2737]
Please fix the respawn time on the formula for the runed adamantite rod. I've been camping for it for a week now for a friend, but no luck. I've seen at least 30 other people looking for it without luck. Enchanters are getting stuck. I'm not sure if it even spawns at all. On the forum from 1 year ago, a GM said that the respawn time was set at 30 minutes. That is definitely not the respawn time anymore. Chocolatedad opened a new topic on your forum a month ago, but there is still no reaction from a GM on that topic. I also found someone else who put this issue on this bugtracker 3 days ago, also no reaction yet. Please set the respawn time back to 30 minutes or an hour.

**Comment by Tarpor** [comment]
so why would you open a new one when one was opened 3 days ago

**Comment by Nattaszz** [comment]
Because a GM (in game) told me to do so.. and before i could even respond he went offline again. So why not.. i could give it a try. Maybe this way it gets more attention, and hopefully it gets fixed.

**Comment by Golganeth** [comment]
Duplicated #2721
