### ISSUE TITLE
Mounted speed increasing items/talents.

### ISSUE THREAD

**Issue by n-ghost** [dalaranwow/dalaran-wow#2738]
Yet to see one working, seems like something on the way somehow has broken them all.

That includes:

- Pursuit of Justice mounted part (running part works as intended at the same time);
- Mithril Spurs;
- Carrot on a Stick;
- On a Pale Horse mounted part.

Didn't test the Riding Crop yet, but I imagine it's all the same for it.

Checked it all with MonkeySpeed v.3.0.1, not a single thing raises mounted speed above default speed of the mount.

Please look into it.

![wowscrnshot_072715_205340](https://cloud.githubusercontent.com/assets/8515510/8913429/b89900c8-34a1-11e5-8da6-3f87ceeac98d.jpg)

![wowscrnshot_072715_205349](https://cloud.githubusercontent.com/assets/8515510/8913435/bf94edf6-34a1-11e5-9e02-8ce41e430863.jpg)

**Comment by Golganeth** [comment]
- #238
- #1336
- #485
-  On a Pale Horse works fine.
