### ISSUE TITLE
Quest: A Curse Upon Both of Your Clans!

### ISSUE THREAD

**Issue by Crispybuilt** [dalaranwow/dalaran-wow#274]
Quest A Curse Upon Both of Your Clans! - 10544

Issue: Upon using the item on the specific location (where it is supposed to be used), you do not get credit for "burning that object". After using "Wicked Strong Fetish" you are supposed to get credit. You have to curse 5 Bladespire Holds and 2 Bladespire Outposts

![image](https://f.cloud.github.com/assets/5054924/885974/b33d07f4-f9df-11e2-9487-1db1f884cdf6.png)

http://wotlk.openwow.com/quest=10544
http://www.wowhead.com/quest=10544/a-curse-upon-both-of-your-clans

**Comment by Daveonx** [comment]
Tested and working. If players still have issues with completing the quest comment bellow please.

**Comment by datbunneh** [comment]
@Daveonx Quest is barely working - ghosts not always summon, and even if they summon they are not always attackable. Heavily only 10 charges on the quest item makes this quest terrible to complete.
