### ISSUE TITLE
Quest: Gerenzo Wrenchwhistle

### ISSUE THREAD

**Issue by xandayn** [dalaranwow/dalaran-wow#2741]
Gerenzo Wrenchwhistle does not appear to spawn, I waited at his spawn point for over an hour and he did not appear, making the quest Gerenzo Wrenchwhistle impossible to complete.

**Comment by Tarpor** [comment]
Did this last week, are you sure you're at the right spot?

**Comment by xandayn** [comment]
Up next to the waterwheel, right near the vendor, yeah?
