### ISSUE TITLE
Val'anyr, Hammer of Ancient Kings

### ISSUE THREAD

**Issue by Vathdar** [dalaranwow/dalaran-wow#2743]
The "Protection of Ancient Kings" shield http://www.wowhead.com/spell=64413/protection-of-ancient-kings
gained from the "Blessing of Ancient Kings" buff http://www.wowhead.com/spell=64411/blessing-of-ancient-kings
on the wielder of Val'anyr is supposed to stack up to 20,000 damage in overall according to this post on wowhead which quotes a blue post from the official forums. 
http://www.wowhead.com/spell=64411/blessing-of-ancient-kings#comments:id=705808

The shield's damage absorb gets added to and duration gets renewed by heals from other healers who have the "Blessing of Ancient Kings" buff as well. More clarification by Ghostcrawler. 
http://www.wowhead.com/item=46017/valanyr-hammer-of-ancient-kings#comments:id=705194

Currently it doesn't stack with shields from other healers who have the procc active, the shield gets overwritten by subsequent shields instead of stacking.

The fix for this might be available here. https://github.com/TrinityCore/TrinityCore/commit/388250961f24cbe2ba955da6d7446965d058f97d

**Comment by Phenomenal101** [comment]
As Jenahaze has stated in his post it does not correctly proc on a Paladin's Beacon of Light nor Glyph of Holy Light.

**Comment by Zephyrino** [comment]
Bump for visibilty, I can confirm that the Protection of Ancient Kings shield does not currently proc from either Beacon of Light, nor Glyph of Holy Light, which it should be doing.

**Comment by Golganeth** [comment]
Merge with #2375

**Comment by hiooplol** [comment]
updates on this?

**Comment by Phenomenal101** [comment]
Unless you have noticed something new, the only thing I have not tested properly yet is how several Val'anyr shields from different players interact with eachother. Everything else seems to work as intended.

**Comment by hiooplol** [comment]
Current issues with valanyr is this
-  bubbles don’t stack, they overwrite (the big one)
- icd not triggered on equip (dalawow-wide issue)
- proc buff stays after unequip (dalawow-wide issue)
- should not proc on 100% overheal (somewhat issue, in real fight conditions, impact is lower than on Dalaran stairs)
Also the stack/overwrite test is pretty easy and takes 2min in icc

We're alot of valanyr healers waiting for this to be fixed.

**Comment by Pyrehead** [comment]
Hey there. Any plans on getting this fixed now that there's gonna be many more Val'anyrs around? As of now, having more than a single Val'anyr (and God forbid rdudu) in the raid is actually detrimental to the group.
