### ISSUE TITLE
NPC: Sporeggar Spawn

### ISSUE THREAD

**Issue by Crispybuilt** [dalaranwow/dalaran-wow#275]
NPC Sporeggar Spawn -  18358

Issue: The NPC (being unfriendly, neutral or friendly) will trigger if you do any kind of AoE to it (it usually happens when Starving Fungal Giant and Sporeggar Spawn fight with each other and you encounter them with AoE) and it will attack you. 
You cannot resist at all to him since he is not attackable to you.

How it should work: Sporeggar Spawn should not be damaged and it should not "hatch on you or attack you" if there is any friendly fire casted near him or on him such as "Blizzard, Paladin's Consecration, Flamestrike etc.."

http://wotlk.openwow.com/npc=18358

**Comment by Rushor** [comment]
Sporeggar Spawn no longer attacks me if do aoe to Starving Fungal Giant
