### ISSUE TITLE
“The Lost Mistwhisper Treasure” bug

### ISSUE THREAD

**Issue by Gone-deaD** [dalaranwow/dalaran-wow#2760]
when i was doing the quest "The Lost Mistwhisper Treasure", there appears a bug: i can not attack  Warlord Tartek. So i try to let my pet kill him, even so, the quest can not be handled. it seems that the Mistwhisper Treasure i got does not match the quest required. AT last i found that all the members of "Mad heart" can not be attacked. 
the name of my role(hunter) is Emaple.

**Comment by Golganeth** [comment]
#344

**Comment by Milton3450** [comment]
Hi Golganeth, can u please change topic of "Fiery Payback (Very Minor)"? I would like the "very minor" tag removed because it's not very minor. Thx for your time!

**Comment by Gone-deaD** [comment]
I tried it again, and it shows that i have completed the quest, but the NPC do not accept the Mistwhisper Treasure i got. it seems that the Mistwhisper Treasure i got does not match the quest required. 
Thank you.

**Comment by Khronos-** [comment]
Confirmed.

High.Oracle Soo-Say in Rainspeaker Canopy does not accept the quest completion despite the quest log stating it is.

Also a bug appeared: I abandoned and restarted quest (since this has happened before) in order to see if it was a bug. Now I cannot attack Frenzyhearts and cannot flag "At War" with them in the Reputation tab.

Therefore I cannot complete this quest. Requested help from a GM online. Still waiting for help.

**Comment by Khronos-** [comment]
Opened an in-game ticket 7 hours ago, still haven't got any answer, either if it's going to be fixed or to just move along.

This issue is a completely different issue from #344 .

Please do inform us if you want this new issue reported on #344 or not, Golganeth.

**Comment by Golganeth** [comment]
@Milton3450 @Khronos-  It is the same issue, check out the last comment.

**Comment by Milton3450** [comment]
@Golganeth nvm I see Loth has changed it already.

**Comment by Gone-deaD** [comment]
Quest completed, NPC do not accept, restart quest and cannot attack Frenzyhearts, then how can we complete the quest? Then i found the thunter's pet can attak them, so I tried 10 more times, but it is still bugged.
"High.Oracle Soo-Say in Rainspeaker Canopy does not accept the quest completion despite the quest log stating it is." 
Is it true the last comment in  (#344)?? No.
Perhaps you should try to login my role and triy yourself.
Thank you.

**Comment by Gone-deaD** [comment]
Several days has passed, many times have been tried, but the bug still exists, I can not turn the quest in every time after retaking the quest. PLEASE HELP ME! I have changed the name of my role into "Peony". Thank you.
