### ISSUE TITLE
NPC - Hierophant Liandra

### ISSUE THREAD

**Issue by Deedeenka** [dalaranwow/dalaran-wow#2763]
NPC in Borean Tundra needed for quest The Abandoned Reach. She is targetable, but unseenable, probably under ground. Quest is needed for "DEHTA'S little PITA" achievment.

**Comment by Golganeth** [comment]
Fixed in-game. Looks like a rare pathfinding issue, which isn't directly related with the quest/NPC itself. 
The NPC is totally fine now.
