### ISSUE TITLE
It's 

### ISSUE THREAD

**Issue by Thyneffhy** [dalaranwow/dalaran-wow#2765]
he wont attack me when i use the eye sore laser and it makes him regen hes health instantly, and btw hes inside the tower now instead of being at the top of it :s so would appreciate any help with this issue ^^
![wowscrnshot_080815_013945](https://cloud.githubusercontent.com/assets/13701054/9147923/df2f5270-3d6e-11e5-824e-63bbc4d35ad8.jpg)

**Comment by Golganeth** [comment]
It's... duplicated. #549

**Comment by oberinjo** [comment]
you cant be just closing topics without fixing the problem

**Comment by Golganeth** [comment]
I close it because, as I said, it's a duplicated report. http://dictionary.reference.com/browse/duplicated
