### ISSUE TITLE
[Quest] [Barrens] [Chen's Empty Keg]

### ISSUE THREAD

**Issue by saduss** [dalaranwow/dalaran-wow#2768]
I was unable to loot the Chen's Empty Keg in a barrel located in Northern Barrens. I need this item to start the quest. Thanks in advance.

![wowscrnshot_080715_231057](https://cloud.githubusercontent.com/assets/13500898/9149429/3eb128ec-3d5e-11e5-84ea-ac455b3d93fd.jpg)

**Comment by Tarpor** [comment]
Can confirm, same thing on my warlock months ago.

(I guess it does live up to its name)

**Comment by jonanone** [comment]
Working as intended at this moment.
