### ISSUE TITLE
Quest: Betrayal

### ISSUE THREAD

**Issue by warcraftgeekygamer** [dalaranwow/dalaran-wow#2769]
@Golganeth 
@Lothloryen

*Why* was this issue closed? https://github.com/dalaranwow/dalaran-wow/issues/571 It was also ignored here: https://github.com/dalaranwow/dalaran-wow/issues/2576

It may have once worked, but now is *completely broken*. Beginning with step 3, is where the remainder of the quest begins to fall apart. After speaking with **Overlord Drakuru** *(ID:28998)*, you are teleported atop with him where the event begins.

**What happens**: You are teleported with Overlord Drakuru. You tame **Blightblood Troll** *(ID:28931)*. You lose your scourge disguise. Blightblood Troll begins to attack you (instead of attacking Overlord Drakuru). You are given a debuff **Blight Crystal** *(ID:54087)*. This is permanently applied - even if you are **not** standing on the blight crystal explosion. You die from the debuff within a few short seconds.

This last even is not scripted properly - something has obviously broken.

**Video of how it should work**: https://www.youtube.com/watch?v=HM6ZXfjCVvI

@Crispybuilt - thank you very much for your contribution.

**Comment by Golganeth** [comment]
Duplicated. #2576
