### ISSUE TITLE
Death Knight: Dancing Rune Weapon

### ISSUE THREAD

**Issue by aoses** [dalaranwow/dalaran-wow#2773]
So it's completely bugged, you summon the weapon and it just stays there on the ground without doing anything and then just dissapears 3 sec after...

This bug has been reported since a year now, and no one has even checked on it or do anything about it. I consider every talent or class bug is a pretty big major bug, and this is not the exception .

It's really annoying because this adds a really great increase in the DK Dps

**Comment by Golganeth** [comment]
#1098
