### ISSUE TITLE
[NPC] Overlord Agmar

### ISSUE THREAD

**Issue by arvidinge** [dalaranwow/dalaran-wow#2775]
this npc is stuck outside his default position, and it's impossible to turn in quests to him.

**Comment by Golganeth** [comment]
#2948 - 

>If someone starts this quest and then does not go through the dialogue options with Roanauk, Overlord Agmar will remain at the location he walks to for the quest until that person either comes back and completes the dialogue with Roanauk or until the server restarts. Additionally, no one will be able to interact with him to turn quests in or receive quests.

**Comment by DrFuler** [comment]
[11/03/2016] - Still bugged.

**Comment by Sagrath** [comment]
Update, working

**Comment by EMPES** [comment]
Issue still persists

**Comment by jonanone** [comment]
Overlord will despawn and respawn at his home position despite the players go through the dialogue or not. This should fix issues with this npc. These updates will be applied to the live realm soon.

**Comment by GMJeina** [comment]
Greetings, Overlord Agmar seems to be missing again. It shows that he's spawned, but he's nowhere to be seen at this coords, therefore he's unavailable again to players.

**Comment by ImprezaWoW** [comment]
Until it's fixed, if that happens, Agmar will be stuck [here](http://i.imgur.com/NU4qCVq.png), and you need to kill and respawn him ,and he automatically goes back to his spot.

**Comment by Rushor** [comment]
fixed with https://github.com/dalaranwow/dalaran-wow/issues/3807 (the fix is on ptr)
