### ISSUE TITLE
[Quest] Abduction- More Detailed with pictures

### ISSUE THREAD

**Issue by Arrowzinger** [dalaranwow/dalaran-wow#2776]
This Quest is located in Amber Ledge in Borean Tundra, you are supposed to be fighting and then capturing a "Beryl Sorcerer", however when others capture them they do not despawn. 
![wowscrnshot_081015_180254](https://cloud.githubusercontent.com/assets/13681885/9187424/26c347aa-3f9e-11e5-8f64-3916c62bb7af.jpg)
![wowscrnshot_081015_180538](https://cloud.githubusercontent.com/assets/13681885/9187426/2a6ad72e-3f9e-11e5-8ca6-1a13a113ef2c.jpg)
![wowscrnshot_081015_180607](https://cloud.githubusercontent.com/assets/13681885/9187428/2bf80666-3f9e-11e5-85a0-498302d6d609.jpg)

You can see all the captured  Sorcerers, these should be despawning.

Thought I would Open a new case because the last one just linked the last case of this with little information.

Here are some other instances of this: https://github.com/dalaranwow/dalaran-wow/issues/1377
https://github.com/dalaranwow/dalaran-wow/issues/1381
https://github.com/dalaranwow/dalaran-wow/issues/2600

**Comment by Golganeth** [comment]
Duplicated #2600
