### ISSUE TITLE
[Quest] [Barrens] [Verog The Dervish]

### ISSUE THREAD

**Issue by saduss** [dalaranwow/dalaran-wow#2777]
I'm not sure if this quest is bugged or not but I've spent nearly two hours around the stagnant oasis killing Kolkars and clearing out all the camps just to summon Verog. However, after killing so many Kolkars, not one shouted out ""I am slain, summon Verog!" which indicates the spawning of Verog. I also checked the area where he suppose to spawn but there's no sight of him. Please fix this quest. Thank you!

**Comment by Tarpor** [comment]
it works, just low chance

**Comment by Golganeth** [comment]
What I said on #25. Works fine so closing up
