### ISSUE TITLE
Sharing Escort Quests in a Group

### ISSUE THREAD

**Issue by saduss** [dalaranwow/dalaran-wow#2778]
I don't know if this bug occurs for all escort quests but whenever someone in a group accepted an escort quest, the rest of the party members were given an option to either to accept the quest or to decline it. By clicking yes, we should be able to pick up the quest but there's a bug that prevented us from doing so. This is such a hassle because we have to repeat this quest multiple times in order for the rest of the party members to complete it.

**Comment by belegija** [comment]
confirmed so far on every escort quest i stumbled upon ( i am lvl60)

**Comment by swiftdeath** [comment]
Any quest that is shared with group when accepting is like this. Rather annoying when trying to do Ring of Blood or Anguish as well.

**Comment by Golganeth** [comment]
Merge #3337
