### ISSUE TITLE
Daily Quest: Thrusting Hodir's Spear

### ISSUE THREAD

**Issue by Kchekrik** [dalaranwow/dalaran-wow#2779]
There doesnt seem to be any Wyrm's around and havnt been for some days now.
Maybe respawn time i much longer than intended, I dont know, but please look into it.

**Comment by InvincibleEagle** [comment]
I too have noticed how rare they are.

**Comment by Khronos-** [comment]
They are extremely rare indeed. But you can find 1 or 2 flying around every hour.

Another thing I've noticed though, is that there are more Frost Wyrms flying around when you leave the area (try entering Brann's Camp and look back at Dun Niffelem). It seems they are phased in the wrong phase.

Can someone else confirm this?

**Comment by rinleezwins** [comment]
This quest has been working fine for the longest time. There were always several wyrms flying around. For about a week now I have been unable to complete this quest.

**Comment by MalkaviaDW** [comment]
It should be improved already, if still an issue re-open it, please.

**Comment by Bloodhawk92** [comment]
Quest still broken

**Comment by datbunneh** [comment]
Broken, please reopen.
