### ISSUE TITLE
[Quest] [Icecrown][The Last Line of Defence]

### ISSUE THREAD

**Issue by ar1s7717** [dalaranwow/dalaran-wow#2780]
Only two of the fortress's turrets get summoned and when you get on them, you have nothing to hit cause all the undead in the whole valley are dead already. When you unmount the turret, suddenly, all of them are back up alive and kicking your ass.

**Comment by ar1s7717** [comment]
Plus, even if you abandon the quest, all the undead remain in the valley when , normally, the shouldn't

**Comment by Tarpor** [comment]
#343

**Comment by ar1s7717** [comment]
different bugs appear to be still. Like, i noticed that the kills were counted at least. so i got a friend of mine and killed the wyrms together. still, after the completion of the q, and the end of  the battle, the scourge respawns. Still there is an issue with the different phases of the q i think

**Comment by Golganeth** [comment]
This quest is already reported. If you want to add details or valuable information, please do not open a new report and add a comment on the already opened issue instead. Thanks!
