### ISSUE TITLE
Reputation with Thorium brotherhood : broken quest

### ISSUE THREAD

**Issue by Kaporalhart** [dalaranwow/dalaran-wow#2781]
The npc Master Smith Burninate [npc=14624] is supposed to take dark iron residues [item=18945] in exchange of reputation. You can start turning his quest in [quest=7737] once you're friendly up until exalted. 
How it currently works is that the quest you can turn in disappear once you're honored. Then your only source of reputation to get to exalted is Lava cores and fiery cores, that drop from Molten core, and that will take much more time.

**Comment by Kaporalhart** [comment]
Please fix this, i have a 1000 dark iron residue in my bags that took hours of farming blackrock depths. even if i clean molten core, it will take 2 or 3 weeks, and the only thing i want is Formula: Enchant Weapon - Mighty intellect [item=19449] that requires revered from the thorium bortherhood.

**Comment by Golganeth** [comment]
Nothing to fix.

http://www.wowhead.com/item=18945/dark-iron-residue#comments

----------

http://wotlk.openwow.com/quest=13662

> **Gaining Even More Acceptance**
*Additional requirements to obtain this quest:*
- Your reputation with Thorium Brotherhood must be at least Friendly
- Your reputation with Thorium Brotherhood must be lower than Honored

> **Gaining Acceptance**
*Additional requirements to obtain this quest:*
- Your reputation with Thorium Brotherhood must be at least Friendly
- Your reputation with Thorium Brotherhood must be lower than Honored
