### ISSUE TITLE
[Quest] [Howling Fjord] "Crowleg" Dan

### ISSUE THREAD

**Issue by Rolexsweep** [dalaranwow/dalaran-wow#2782]
Not possible to engage "Crowleg" Dan through dialogue. He remains neutral without any possibility of getting him into combat.

**Comment by Tarpor** [comment]
This is in Howling Fjord?..

**Comment by Rolexsweep** [comment]
Howling Fjord, the pirate quest hub just south of the Kalu'ak islands.

**Comment by Golganeth** [comment]
Confirmed, he's missing the gossip option and dialogue. However, you can definitely complete the quest (thanks to #1191). Casting any harmful spell or /startattack macro should help..

**Comment by DrFuler** [comment]
[01/03/2016] - Still missing the dialogue option. (however, as pointed by Golganeth, casting a harmful spell does work.)

**Comment by jonanone** [comment]
The dialog option has been added. Once selected, he will become unfriendly and will attack the player.

This update will be applied soon.
