### ISSUE TITLE
Priest: Talent: Rapture

### ISSUE THREAD

**Issue by MihkelRoogna** [dalaranwow/dalaran-wow#2784]
Rapture does not have an internal cooldown on Algalon server. Both effects proc every time a shield is fully absorbed. There needs to be a 12 second cooldown for both of its effects.

http://forums.elitistjerks.com/topic/97029-wotlk-healing-compendium-v335-fun-in-the-twilight-with-halion/
"The details are a bit more complex, though. Rapture can proc only once every 12s. However, if multiple shields break at exactly the same time and Rapture is not on cooldown, Rapture will proc for most (usually all) of the shields. "

Also some evidence about how it should work on:  http://www.wowhead.com/forums&topic=161137/discipline-priest-guide-3-3-5 

Or just read the talent description.

**Comment by Golganeth** [comment]
Merge with #1691
