### ISSUE TITLE
Wintergrasp Spiritual Immunity

### ISSUE THREAD

**Issue by mnbdru** [dalaranwow/dalaran-wow#2785]
If druid player A uses cyclone on player B with Spiritual Immunity, after cyclone duration finishes, player B looses spiritual immunity and can be killed by anyone at their graveyards. 

Spiritual immunity - http://www.wowhead.com/spell=58729/spiritual-immunity

**Comment by M0dinstaller** [comment]
The bug is still visually active after cyclone.

**Comment by Golganeth** [comment]
Gonna reopen the old issue (#1525) thanks for the report.
