### ISSUE TITLE
Quest: The Swarm Grows (part 3)

### ISSUE THREAD

**Issue by ffighter29** [dalaranwow/dalaran-wow#2787]
So in this quest in flat area in of thousand needles NPC askes of me to kill 5 Silithid Searchers, 5 Silithid Hive Drones and 5 Silithid Invaders. Problem is that there is just one Silithid Invader near cave entrance and he respawns aprox every 5mins so that is 5x5 25mins for one quest...we need more of these Silithid Invaders ASAP!

**Comment by Golganeth** [comment]
I've reopened #69
