### ISSUE TITLE
[Mage] Glyph of Polymorph

### ISSUE THREAD

**Issue by Milton3450** [dalaranwow/dalaran-wow#2788]
When you cast polymorph on a warrior with spell reflect it will not remove dots on yourself. When you have Glyph of Polymorph ofc..
http://www.wowhead.com/spell=56375/glyph-of-polymorph

**Comment by pascagabriel** [comment]
Afaik it shouldn't remove dots on the caster if reflected, even while glyphed. Could be wrong, but the again, you have to prove your claim for me to rebut it.

**Comment by Milton3450** [comment]
I watched some youtube videos but haven't found proof yet.

**Comment by Rushor** [comment]
I will set this "on Hold" for now. Once a proof for this behaviour was found we will reopen the issue. Thanks.
