### ISSUE TITLE
warlock pets

### ISSUE THREAD

**Issue by adytzyca** [dalaranwow/dalaran-wow#2793]
1.Pets spawn with 1% hp/1% mana when dismounted if previosly they have been killed in combat(and obviously resummoned with full full hp/mana);
2.Resummoning a new pet if the current one has low hp/mana will lead to an identical pet-same mana/health pool as the one that's being replaced -;
3.Pets(at least succubus for sure) dont benefit from master's resilience,hence,getting literally 2 shotted.

**Comment by Golganeth** [comment]
They're all duplicated.
1. #1992 
2. #1539
3. #1979
