### ISSUE TITLE
Death Knight area quest: Massacre at Light's Point

### ISSUE THREAD

**Issue by AshManson** [dalaranwow/dalaran-wow#2797]
The cannons needed to kill the 100 scarlet soldiers were not present.  You can not complete the quest line unless you are able to manually kill the 55 elites.

**Comment by Tarpor** [comment]
#1744

**Comment by AshManson** [comment]
I did read that post before making my own.  It was referring to an animation issue, my issue is entirely different.  The cannons were not present at all, meaning I could not complete the quest and can not continue playing my death knight until this issue is resolved.

**Comment by M0dinstaller** [comment]
Check around. I think the cannons can be moved around and since players will move them around they'll end up in unfamiliar places. I found mine in the middle of the mobs.

**Comment by Golganeth** [comment]
This is already reported. They can be moved by players indeed. Make an in-game ticket or wait for a server restart. Or as @M0dinstaller suggested, you might be able to find cannons around. Closing up since it's duplicated.
