### ISSUE TITLE
Death Knight Area Quest: The Light of Dawn

### ISSUE THREAD

**Issue by gchon10** [dalaranwow/dalaran-wow#2798]
Scripting doesn't happen. The NPC scripting doesn't work. The army that you attack with will just stand there and when you walk to the quest area there is nothing there.

**Comment by Tarpor** [comment]
#1744

**Comment by Arrowzinger** [comment]
Still an issue and there hasn't been a response on that thread in a long time. Considering this is one of the most important quests in the game you think they would have fixed it in a year span.

**Comment by Golganeth** [comment]
@Arrowzinger In fact, this quest has been working for a long time. With the recent changes on the core, some issues arose on this one and we're aware so it'll be looked into. Thanks! #276 #1744

**Comment by Arrowzinger** [comment]
Ok thanks Golganeth.
