### ISSUE TITLE
Death Knight Area: Acherus The Ebon Hold

### ISSUE THREAD

**Issue by gchon10** [dalaranwow/dalaran-wow#2799]
Cannot leave this area. Teleporter is broken. No NPCs or vendors spawn in the area. Impossible to leave.

**Comment by Tarpor** [comment]
#1744

**Comment by Golganeth** [comment]
Using the un-stuck feature while on [The Light of Dawn](http://wotlk.openwow.com/quest=12801) will cause this.
Make an in-game ticket and you'll be summoned down. (Duplicated #744)

**Comment by lmodig** [comment]
Wrote an ingame ticket from my character Avancez about 10 days ago. Still no help.
