### ISSUE TITLE
[Quest] Dead-Tooth Jack

### ISSUE THREAD

**Issue by dhosmhea** [dalaranwow/dalaran-wow#2802]
This is a Warrior quest in Elwynn Forest, right after the Defensive Stance quest.  The quest is to kill a Defias bandit called Dead-Tooth Jack, loot his key, and use it to open his nearby strongbox to recover Marshal Haggard's badge.  However, upon doing this sequence, the strongbox was empty - no badge to be found.  The key was consumed in the process.  I've attempted this sequence about six times now, over the course of about an hour, and have tried abandoning and reacquiring the quest, as well as relogging, neither of which helped the issue.

**Comment by fowara** [comment]
I got it to work today. So it seems to be fixed.

**Comment by Golganeth** [comment]
Fixed in-game. This is a rare and general issue with game objects.
