### ISSUE TITLE
Scholomance Transformation bug

### ISSUE THREAD

**Issue by Rkololz** [dalaranwow/dalaran-wow#2803]
hello i have a problem reguarding transformation bug i got from Scholomance i did the dungeon and after pulling some mobs i got mind control and got this wierd transformation i can't get rid of it i tried everything (dying,i did the instace again,polymoprh,clear cache and wtf folders,ressurect from other classes,unstuck) until now nothing worked pls help me i can't mount i even made a ticket sience 5 days my name is rkololz alliance if you need me in game you can find me at 15:00 server time until 17:00 and between 22:00 and 5:00 Thank you Very Much

**Comment by Golganeth** [comment]
#1971
