### ISSUE TITLE
Master's call, you guys have to be kidding me

### ISSUE THREAD

**Issue by xumae** [dalaranwow/dalaran-wow#2810]
https://github.com/dalaranwow/dalaran-wow/issues/2695 
It's actually amazing how long it takes you guys to fix things, loth claimed he had a fix but as i just found out dueling an ele sham a few times masters call is still bugged and doesnt work half the time,. :)

**Comment by Winstrol** [comment]
can confirm its bugged half of the times. happend after the big patch that broke alot of things

**Comment by xumae** [comment]
If you are talking about the patch from yesterday or w/e its been bugged for months but ye lifes hard qq

**Comment by Golganeth** [comment]
#2695
