### ISSUE TITLE
Quest: [Talbuk Mastery] [Nagrand]

### ISSUE THREAD

**Issue by Icyblast** [dalaranwow/dalaran-wow#2811]
Hello there

I would like to report a mob spawn bug
NPC Name: Bach'lor
Quest Drop: [Hoof of Bach'lor]

The mob didn't show up for almost 20hours, I did look for him in many places.
Sadly, no clue. So, it must be a bug.

Thanks

**Comment by sixele** [comment]
I did this quest three days ago, and after someone killed it in front of me, Bach'lor was there again after around 2 RDFs. Did you try walking around the area where he can spawn?

**Comment by M0dinstaller** [comment]
He stands in 1 place north of where the map says he is. Don't rely on the map telling you where quests are done, because it can be wrong.

**Comment by Golganeth** [comment]
Invalid report.
