### ISSUE TITLE
Quest: The Black Knight's Fall

### ISSUE THREAD

**Issue by lowbow** [dalaranwow/dalaran-wow#2814]
Can't summon the Black Knight, because Squire Cavin has no dialog.

**Comment by Golganeth** [comment]
Works fine as long as you do it properly. Closing up

**Comment by lowbow** [comment]
It was not working few days ago, no matter used you battle horse or not. Now it works fine. Very grateful.

**Comment by Golganeth** [comment]
Could've been a punctual glitch with your character, or perhaps you were missing something. In any case, glad to see you were able to complete it.

**Comment by datbunneh** [comment]
Not interactable for me right now even though I'm on this quest, have lance and properly mounted.

**Comment by roblockster** [comment]
Same. Doing the quest properly, does not work fine.
