### ISSUE TITLE
Quest:The Air Stands Still (Icecrown)

### ISSUE THREAD

**Issue by machette23** [dalaranwow/dalaran-wow#2815]
Cant seem to get the kill in my quest log when i kill these npcs for the quest.I use the horn for the help and the dk npcs helps me kill them.I got the 1st hit on the npcs and i held the aggro all the time and still nothing.Its not a group quest and it should be soloable dont know if not using the help will get me accounted for kills.

**Comment by Tarpor** [comment]
It's not about firsthitting or keeping aggro, it's about doing 50% dmg on the mob yourself, not the NPC.

**Comment by Golganeth** [comment]
Duplicated #536

**Comment by UncleCrust** [comment]
So, it's not a group quest but a lone player is supposed to reduce the mob's hp 125K?! My 78 hunter has 13500hp. I don't recall this being the case on BattleNet. No, seriously?!?!
