### ISSUE TITLE
Diminishing Returns

### ISSUE THREAD

**Issue by tripleslash** [dalaranwow/dalaran-wow#2816]
It seems that under certain conditions you can infinitely fear mobs. Just saw a warlock soloing a 3 man group boss by constantly fearing him (fear didn't become less effective over time).

**Comment by Rushor** [comment]
kreatures don't have any dr. thats blizzlike

see http://wowwiki.wikia.com/wiki/Diminishing_returns

**Comment by tripleslash** [comment]
Well thats my bad then, I thought it would also apply to creatures
