### ISSUE TITLE
Major: Mobs stop to attack and do nothing under certain conditions

### ISSUE THREAD

**Issue by tripleslash** [dalaranwow/dalaran-wow#2817]
Me and a friend were doing http://www.wowhead.com/quest=12151/wanton-warlord and that group boss managed to kill me. After I died, the boss just stood there and did nothing (stopped casting spells and autoattacks etc.) and my friend was able to solo him. This happened multiple times to us already. I would guess it might be some bug in the path finding / grid logic.

I would guess the same bug can be reproduced on raid encounters as well.

**Comment by M0dinstaller** [comment]
This is abusable by warlocks and hunters. When they send their pet on a mob and stand far away so the mob attacks the pet, if the pet dies the mob will bug and not move, resulting in an easy kill.

**Comment by Golganeth** [comment]
#828

**Comment by DrFuler** [comment]
17/12/2015: Still bugged.

This should be fixed, as it can be highly abused.

**Comment by carlosoharo** [comment]
this is still happening, should fix it.
