### ISSUE TITLE
A Few Small Changes, big improvements, Huge impact

### ISSUE THREAD

**Issue by heymane** [dalaranwow/dalaran-wow#2820]
I have gathered a compilation of picture examples of things that could be tweaked to give the full retail-like experience and feel to players on this amazing server. These are not game breaking bugs, but they are something i feel hasn't been touched up on yet.

#1: Extremely high loot rates. ![wowscrnshot_081415_115358](https://cloud.githubusercontent.com/assets/13970626/9480100/e5d2167e-4b35-11e5-88e6-57e6cb69c430.jpg)
 This may have been something recently implemented, but i do not think this is retail-like. As you can see in the photo, one mob has been killed and looted and 2 greens drop, but this is pretty frequent not even in dungeons, in the open world, mobs drop blues so frequently that when a player gets a blue item it doesnt feel too rewarding. In my opinion this should be set back to 1x just like retail.

#2: (This is a big one) Mobs Casting While walking in their scripted AI path. ![wowscrnshot_081415_182801](https://cloud.githubusercontent.com/assets/13970626/9480070/b8880eee-4b35-11e5-9270-786a461a02e6.jpg) , This seems to happen with just about every caster mob in the game at the moment. Even though this isnt an enormous problem, it is just scripting, and with this improved, this will feel more and more just like wotlk retail. 

#3: ![wowscrnshot_081615_003433](https://cloud.githubusercontent.com/assets/13970626/9480118/fff672d4-4b35-11e5-9a94-41712b0cf9aa.jpg) This tyrant devilsaur is either too lazy to go walk around or really likes it in this spot... Although this same devilsaur walked around back in 2008. (lol just a tiny improvement idea)

#4: (Big one(probably not a bug, but retail is different)) Hunter pets being waaay too small at level 10 and unrealistic proportion (that size of pet wouldnt do anything to damage anything realisticly, and wouldnt make sense to) from 10 to 20 or 30, pets are rediculously small and doesnt give you that proper hunter feeling apon taming your first pet. It just feels like you tamed a companion that doesnt do anything but follow you. Moving on with hunters comes number 6

#5: The hunter questchain "taming the beast" doesnt work anywhere close to retail-like, the mob abilities dont work like retail, and the tame beast is instant, but that's all though, everything else works amazingly.

I love this server and i'm only making this to help improve the server. Thanks for reading! :D

**Comment by belegija** [comment]
Issue 1) greatly decreases the retail like feeling and should be top priority.

**Comment by Golganeth** [comment]
Most of what you mention is already reported. Please make separated reports for each different issue.
#26 #1356 #1954

**Comment by Alavarin** [comment]
I agree with too high drop rates - Prowlers in Elwynn Forrest dropped me 2 greens, I had a full backpack of that stuff after about half of hour farming.
