### ISSUE TITLE
[Paladin] Spell: Hand of Protection

### ISSUE THREAD

**Issue by emarko** [dalaranwow/dalaran-wow#2821]
Spell: http://www.wowhead.com/spell=1022/hand-of-protection
Hand of Protection is usable while sapped/stunned/blinded, but it shouldn't be usable during these debuffs.

**Comment by M0dinstaller** [comment]
Already reported and closed
https://github.com/dalaranwow/dalaran-wow/issues/1458

Here's TC's thread
https://github.com/TrinityCore/TrinityCore/issues/12101

**Comment by emarko** [comment]
Kiddin me? That report was opened in 2014! 2 0 1 4 !! Is it broken again or what?

**Comment by emarko** [comment]
So?

**Comment by Tarpor** [comment]
lmao what do you expect now? You reported it, good job, let it go, it will be fixed.

**Comment by emarko** [comment]
I expect any approval that this problem will be fixed, lmao.

**Comment by Tarpor** [comment]
maybe the fact that it isn't closed?

**Comment by emarko** [comment]
It means nothing. If it takes 1 year to fix this bug it sucks anyway.

**Comment by Tarpor** [comment]
As mentioned, #1458 , it's already been fixed once, sometimes things slip past/through and they're reversed. Shouldn't be too much of a hastle to fix. Hope your self-entitlement is calmed with logical thinking.

**Comment by emarko** [comment]
Ok

**Comment by Golganeth** [comment]
Hand of Protection can still be used while sapped/stunned/blinded.

**Comment by robinsch** [comment]
Oh I missed the SQL Update
