### ISSUE TITLE
[Spell] Charge / Intercept - Pathing issue

### ISSUE THREAD

**Issue by manabar** [dalaranwow/dalaran-wow#2823]
1) 
When you charge up a hill - whether that be a small one or big one, you fall below the ground.  This makes charge / intercept useless and makes for questing in areas like Feralas and Tanaris practically unplayable.

You can fall below the earth fighting Centipaar's, you can fall beneath fighting scorpids or even ogres in the Tanaris area.  Please fix this warrior game-breaking bug.

2)
I have this issue myself, but also other players are reporting it:
Sometimes (the bug appearance for me was around 10% of charge uses i guess) the warrior doesn't directly charge towards the target when used, but runs to a random spot in the approximate direction (i have experienced deviations of up to 45 degrees so far). The target still gets stunned, but the charge just ends at an empty spot instead of infront of the enemy.

**Comment by Tarpor** [comment]
Pretty sure this is just a pathing bug and has nothing to do with the warrior class itself

**Comment by manabar** [comment]
If it's not a warrior bug, then its still an error that needs to be fixed.  I've fallen through the world in Tanaris, Feralas, Un'goro, Searing Gorge, Blasted Lands, Barrens, 1k Needles, Shimmering "FLATS" and just about everywhere else.  I shouldn't have to choose to NOT use an ability because of this pathing error - it needs to be resolved.

It's a stupid error and the tiniest bump will make you fall through the world and take a durability hit.  All I'm trying to do is play the game.

**Comment by Zoombala** [comment]
Never had a problem with charging/intercept, had some using blink tho'

**Comment by Lothloryen** [comment]
Hello there, 

I have been working for some time trying to improve the overall pathing system and it will affect the Warrior's charge in a positive way. I will deploy it to the live server during this week, it will not be perfect and this issue may still happen - however, it should drastically reduce the chances.

Thank you very much.

**Comment by Lothloryen** [comment]
Hello again,

It is deployed already, the issue with the players falling to the void (not only with charge) should now be drastically reduced.

Thank you.

**Comment by Break977** [comment]
This is still an issue on live.  Fell through the world in both Westfall and Elwynn Forest. If there is a cave structure below, i fell into that, otherwise i fall to the endless void and then die.  Once when i died, I couldnt even release, had to shut down game, and log back in just to get rez'ed.
