### ISSUE TITLE
Centipaar's attack rate

### ISSUE THREAD

**Issue by manabar** [dalaranwow/dalaran-wow#2824]
The Noxious Lair in Tanaris has wasps that will attack 9+ times in between 2 white swings.  There is no 'swarm' bugs, just one mob, hitting 9-10 times in the time it takes to swing a standard weapon twice.  This needs to be resolved.

**Comment by nyrpha** [comment]
same happened to me with several mobs throughout the game, but only very rarely.

**Comment by WriggleMortis** [comment]
I have experienced the same thing as well, but with any and all types of mobs throughout my leveling. There doesn't seem to be any connection with a specific type of mob. The worst was an insect in Tanaris (not a wasp) that hit me 9 times per swing multiple times. Most of the time, I will notice that 3 attacks will come from a single mob per swing.

**Comment by Rushor** [comment]
reason for this is https://github.com/dalaranwow/dalaran-wow/issues/2891

/closed because it's a duplicate
