### ISSUE TITLE
Feared under world

### ISSUE THREAD

**Issue by manabar** [dalaranwow/dalaran-wow#2832]
In Un'goro crater, if you fight a flying mob that fears, you will be feared under the world and take a durability loss.  After you rez, you will be 3 zones away from Un'goro crater.

**Comment by belegija** [comment]
which mob exactly? be more precise please

**Comment by manabar** [comment]
When you are feared by the Pterrodax.  I'm not sure of the frenzied Pterrodax, but it was a normal Pterrodax that caused my character to fall through the world after casting their fear ability.

**Comment by Tarpor** [comment]
Has to do with pathing, not necessarily the pterrodax.

**Comment by manabar** [comment]
Then pathing needs to be made a priority.  Not being able to kill mobs due to falling through the world is ridiculous.

**Comment by Golganeth** [comment]
Pathfinding issue, directly related with #1213
