### ISSUE TITLE
Druid "powershifting" not working in tree form.

### ISSUE THREAD

**Issue by Voidpants** [dalaranwow/dalaran-wow#2834]
When in tree form and the macro "/cast !Tree Form", which recasts tree form and should clear roots/slows (worked on live), roots and slows are not cleared. This is a big deal on fights such as Hodir where this helps druids clear roots. It's also a significant nerf to pvp resto druids.

**Comment by Voidpants** [comment]
Sorry I meant !Tree of Life obviously

**Comment by Golganeth** [comment]
#2698
