### ISSUE TITLE
Hodir flash freeze crashing raid

### ISSUE THREAD

**Issue by Voidpants** [dalaranwow/dalaran-wow#2835]
When you first arrive at Hodir, Flash Freezes are invisible (I believe underground ). If you 1-shot the boss fight without wipes, you will never be able to re-enter the instance because these are not killed and the Hodir encounter is always considered aggroed. It also makes it harder. The current work-around is to just wipe on Hodir once but it is quite annoying.

**Comment by Tarpor** [comment]
It's not that.

**Comment by Golganeth** [comment]
#2087
