### ISSUE TITLE
Resto druid Nightsong regalia (ilvl 219) set bonus

### ISSUE THREAD

**Issue by N0urish** [dalaranwow/dalaran-wow#2836]
After getting two gear tokens from Uld 10 I've decided to grab nightsong gear (ilvl 219) from leather armor vendor in Dalaran. I put gems and enchants on both pieces and decided to equip them to see how's the 2p bonus. The 2p bonus is supposed to increase healing done by swiftmend spell by 10 %. 

I can see no change in healing done by swiftmend, only change is minor difference in sp when changing gear ( 5 sp). Healing done by swiftmend increased from 6953 to 6958. 

Tried relogging, it's not a visual bug.

**Comment by robinsch** [comment]
On PTR
