### ISSUE TITLE
Warlock fear/coil path

### ISSUE THREAD

**Issue by adytzyca** [dalaranwow/dalaran-wow#2837]
So although i've reported this about a year ago,Feared and Death Coiled targets' paths are still bugged   ,drastically reducing the efficiency of the above named abilities.A warlock's burst relies on target not actually teleporting around him when he's coiled or feared,making it impossible to attack and  incredibly frustrating.I have previously reported several warlock  bugs that pretty much make pvp if not impossible,at least a very sad experience.Now i know that pvp related stuff are at the bottom of your priority list,but you'd think 1 year should have been enough time at least to get more than a "duplicate" label.Thank you.

**Comment by Golganeth** [comment]
#1447
