### ISSUE TITLE
Hunter: Animal Handler Talent

### ISSUE THREAD

**Issue by Deushazz90** [dalaranwow/dalaran-wow#2838]
Rank: 2/2
Issue: This talent does not increase the pet's attack power by 10% at max rank.

Tried to dismiss and recall pet so the talent applied currently. This did not fix the issue.

**Comment by Huntatsukage** [comment]
I noticed this earlier too, I have Rank 2/2 on Animal Handler, however my pet's attack power hasn't gone up any. I also dismissed and recalled pet, but still no increase

**Comment by Lothloryen** [comment]
Hello there,

This issue should be solved and it should be working well after the next scheduled server maintenance.

Thank you very much for your report.

**Comment by MrAndersonX** [comment]
Yeah still it's bugged. I leveled it up just now on my hunter and it doesn't do the 10% max ap increase, it only does the 5% ap increase at level 1/2 even though it is skilled 2/2.

**Comment by MrAndersonX** [comment]
Still needs a fix.
