### ISSUE TITLE
Character not appearing

### ISSUE THREAD

**Issue by Sefirosu1** [dalaranwow/dalaran-wow#2845]
hi there!just having an issue I can't find anywhere. I have three characters and none of them show up when I sign into the website. They all appear when I play but none appear on the site (it says no characters found) anyway to fix those?thanks

**Comment by Tarpor** [comment]
The website doesn't support Algalon. For the time being you need a lvl 1 char on kirin tor to link it. The website is getting a revamp relatively soon so hopefuly support for Algalon will be enabled.

**Comment by Golganeth** [comment]
The bug tracker only lists in-game issues (quests, NPCs and such). For more info regarding your problem check out #2107, but it's pretty much what Tarpor said. Closing up
