### ISSUE TITLE
Trial of the Sea Lion (Horde) missing quest objective?

### ISSUE THREAD

**Issue by zykadelic** [dalaranwow/dalaran-wow#2846]
I’ve been looking for [Half Pendant of Aquatic Endurance](http://wowwiki.wikia.com/wiki/Half_Pendant_of_Aquatic_Endurance) for quite some time now, following all the directions suggested on forums and such. I just can’t find it. I know the quest is obsolete anyway, since you can get Aquatic form from the trainer, but still — is this a bug?

**Comment by Sagrath** [comment]
It is working as intended
