### ISSUE TITLE
The air stands still quest-Icecrown

### ISSUE THREAD

**Issue by LucasCruceru** [dalaranwow/dalaran-wow#2847]
in this quest i'm supposed to kill 3 bosses i tried to kill every one of them and suceded but they don't count as i did... its still 0/1... i repeated this a couple of times and its still 0/1 on all 3 bosses... and i think if i don't do that quest i cant get to quartermaster of ebon blade which has some valuables i would like to buy... thanks

**Comment by Tarpor** [comment]
#536

**Comment by Golganeth** [comment]
Duplicated.
