### ISSUE TITLE
Fire mage "Fiery payback" talent bug

### ISSUE THREAD

**Issue by dziugmants** [dalaranwow/dalaran-wow#2850]
Hello,

So the problem with this talent that it doesn't work as intended.

I am adding a screenshot what it should do.

https://cloud.githubusercontent.com/assets/14090931/9629198/91fd8728-5179-11e5-8765-6fe238828bd2.jpg

As you can see, when below 35% health, pyroblast cast time should be reduced by 3.5 sec, so if I dont have any haste, pyroblast cast time should be 1.5 sec,and cooldown should be 5 sec, because originally it's cast time is 5 sec.

And here is screenshot of how "Fiery payback" talent works when I'm below 35% health.

https://cloud.githubusercontent.com/assets/14090931/9629220/b667623c-5179-11e5-95c2-d7b304a6f2f4.jpg

Here you can see, that this talent does work, but instead of reducing my cast time by 3.5 sec, it reduces it only by 1,75 sec, also you can see that cooldown is 2.5 sec instead of 5 sec. So basically it reduces the cast time only by half of what it should be. And cooldown should be 5 sec also. Also i have 1% haste, so the numbers are bit smaller because of that :)

This talent is really important in pvp, so I really hope that it will get fixed soon :)

**Comment by Golganeth** [comment]
#1778
