### ISSUE TITLE
Quest: Timbermaw Ally

### ISSUE THREAD

**Issue by belegija** [dalaranwow/dalaran-wow#2852]
This quest is given by NPC [Grazle](http://wotlk.openwow.com/npc=11554), gives 1000 reputation with Timbermaw Hold and should be repeatable only up until neutral. I am at this moment honored with them and Grazle is still offering the quest. By the looks of it, it is posible to do it even further down the line, making the reputation grind with them extremely easier.
Reference: [Timbermaw Ally](http://wowwiki.wikia.com/wiki/Quest:Timbermaw_Ally_%28RRQ%29) at WoWWiki

**Comment by Tarpor** [comment]
Possible till exalted.

**Comment by jonanone** [comment]
Quest is now only repeatable until Neutral reputation with Timbermaw Hold. This fix will be applied to the live realm soon.
