### ISSUE TITLE
Item-Effect: No Buff-Effect from Buff-Food (Poached Sunscale Salmon | Hot Smoked Bass)

### ISSUE THREAD

**Issue by Rumsteak** [dalaranwow/dalaran-wow#2853]
Item ID: 13932
Item-Name: Poached Sunscale Salmon
Wowhead-Link: http://www.wowhead.com/item=13932

Item ID: 13929
Item-Name: Hot Smoked Bass
Wowhead-Link: http://www.wowhead.com/item=13929

Both Items dont give the Buff-Effect thats named on the item description, they dont give any effect (beside normal Health-Reg) at all.

**Comment by Sagrath** [comment]
Both working as intended
