### ISSUE TITLE
Dire Maul - Immol'thar-Event bugged

### ISSUE THREAD

**Issue by Rumsteak** [dalaranwow/dalaran-wow#2854]
NPC-Name: Immol'thar
NPC ID: 11496
Zone: Dire-Maul (instance)
Wowhead-Link: http://www.wowhead.com/npc=11496

The mob normally has an event where you have to kill the Mana-Mobs around the crystals all over the instance.
Once you killed them, the barrier around Immol'thar is removed and you can kill the boss and finish the part of the instance.

This does NOT work on Dalaran-WoW, we were in this instance twice, cleared all crystals but the barrier remained.
It was possible to pull the boss via a mage that found out he could blink behind the barrier.
Defeating it didnt count and it wasnt possible to finish the instance.

**Comment by Golganeth** [comment]
#2503
