### ISSUE TITLE
[Mob-Problem] Phase Lasher stuck in the ground

### ISSUE THREAD

**Issue by Rumsteak** [dalaranwow/dalaran-wow#2855]
Mob-Name: Phase Lasher
Mob-ID:13196
Zone: Dire-Maul - Warpwood Quarter (instance)
Wowhead-Link: http://www.wowhead.com/npc=13196

Screenshot showing the problem: http://fs1.directupload.net/images/150903/vp74jtyx.jpg

The mob cant move, is stuck in the ground.
Sometimes it is not visible for the players.

**Comment by Golganeth** [comment]
Merge with #2503
