### ISSUE TITLE
[NPC]Warbringer Arix'Amal - Low drop rate of quest-starting item

### ISSUE THREAD

**Issue by AnaxusRath** [dalaranwow/dalaran-wow#2856]
#### NPC ID: 19298

Issue: Item called **Burning Legion Missive** (id 29588) has extremely low drop rate. It drops from **Warbringer Arix'Amal**. I killed him 9 times on 3rd September 2015 and only just got it. The drop rate should be 42 or 50% according to Wowhead and Openwow respectively.

**Burning Legion Missive** starts quest called **A Dark Missive** (id 10395) which is Alliance quest starting an important chain eventually ending with Overlord (id 10400), the "final quest" in Hellfire Peninsula.

*Note*: I have not tested Horde variant of this quest - Razorsaw (id 20798) should drop Burning Legion Missive (id 29590) to start Vile Plans (id 10393).

**Comment by Golganeth** [comment]
#256
