### ISSUE TITLE
[Spell / Paladin] Holy Wrath

### ISSUE THREAD

**Issue by mechacrash** [dalaranwow/dalaran-wow#2857]
https://github.com/dalaranwow/dalaran-wow/issues/2258
previous issue was closed incorrectly.

Expected:
- Damage is dealt to all enemy types. 
- Effects are only applied to undead / demon types.

Current:
- Damage and effects are only applied to undead / demon types

This is a significant problem for prot pali / tankadin - the AoE is a critical addition.

**Comment by DwowSupport** [comment]
Hello mechacrash!
I did a small research regarding this subject, so here is what i find:
Holy wrath spell in TBC expansion looked like that:
"Sends bolts of holy power in all directions, causing 635 to 746 Holy damage to all Undead and Demon targets within 20 yds."
sourse:http://db.lastwow.com/?spell=27139

At WOTLK expansion the spell got changed abit and looked like that:
"Sends bolts of holy power in all directions, causing [399 - 471+0.07*SPH+0.07*AP] to [399 - 471+0.07*SPH+0.07*AP] Holy damage and stunning all Undead and Demon targets within 10 yds for 3 sec."
source:http://wotlk.openwow.com/spell=2812

And at Cata expansion was:
"Sends bolts of holy power in all directions, causing 0 Holy damage divided among all targets within a1 yds and stunning all Demons."
source:http://cata.openwow.com/spell=2812

So as you can see in each expansion the spell was modified in a way. At TBC you can clearly see it did damage only on undead/demon and in Wrath they added the stun but the targets of the spell remained the same. Only in cata they add the part where the spell does damage to every target around you. So the outcome of this report should be tagged as "Invalid" as mentioned in #2258 by Golganeth.
Cheers!

**Comment by mechacrash** [comment]
You've got the right information, but you've come to the wrong conclusion - in WOTLK the spell was changed to deal damage to all enemy types.
quoting you:
At WOTLK expansion the spell got changed abit and looked like that:
 "Sends bolts of holy power in all directions, causing [399 - 471+0.07SPH+0.07AP] to [399 - 471+0.07SPH+0.07AP] Holy damage and stunning all Undead and Demon targets within 10 yds for 3 sec."
 source:http://wotlk.openwow.com/spell=2812

so:
"causing [399 - 471+0.07SPH+0.07AP] to [399 - 471+0.07SPH+0.07AP] Holy damage"
and
"stunning all Undead and Demon targets within 10 yds for 3 sec"
these are separate items.

It's not "causing damage and stunning" - "undead and demons"
it's "causing damage" - "and stunning undead and demons"

the wording is ambiguous, but the nature of the attack within WOTLK was without a doubt damaging to all enemy types. Conversation logs on blizzard's official forums and wowhead during the release/availability window of WOTLK (prior to cataclysm's release) corroborate with this. I can source if need be.

**Comment by Golganeth** [comment]
> #2258
previous issue was closed incorrectly.

No, it wasn't.

Thanks @DwowSupport 

Closing up
