### ISSUE TITLE
[Escort Quests] [Desolace] [Bodyguard For Hire and Gizelton Caravan]

### ISSUE THREAD

**Issue by saduss** [dalaranwow/dalaran-wow#2858]
At this point, both escort quests are not working and the whole caravan event is broken.
Here is the link that summarized these bugged quests and how it should work: https://vanilla-twinhead.twinstar.cz/?issue=3546.

Map: http://i.imgur.com/hu0fFDi.jpg
         http://i.imgur.com/Oj3z0AD.jpg

**Comment by Golganeth** [comment]
Duplicated #231 #443
