### ISSUE TITLE
Hunter spell: Autoshot

### ISSUE THREAD

**Issue by Deushazz** [dalaranwow/dalaran-wow#2859]
Autoshot: "Automatically shoots the target until cancelled."

Autoshot, once engaged in combat and activated (either via another spell, right clicking the enemy, or selecting the Autoshot spell icon) should continuously shoot until cancelled.
Currently it appears there is a line of sight issue.
1. If the enemy goes out of line of sight, the Autoshot spell is still activated, however a tag appears, stating that the enemy is out of sight.
2. If the player or the enemy comes back into line of sight of eachother, the Autoshot spell does not resume shooting.
3. The player needs to manually stop and start attacking again to work.

The player should not need to manually re-activate Autoshot. The spell should automatically resume attacking the enemy once LoS.

This may or may not affect other similar spells (perhaps wands? or melee autoattack under different circumstances).

**Comment by Golganeth** [comment]
Merge with #834
