### ISSUE TITLE
Revenge proc

### ISSUE THREAD

**Issue by Kixum** [dalaranwow/dalaran-wow#2862]
I've just noticed that every block/dodge/parry lets me use Revenge(#19130) 3 times instead of once with Unrelenting Assault talent.(#46860)

That's obviously caused by the fact that Revenge stays usable for the whole duration of the proc, instead of terminating the proc after Revenge is used. This makes no difference without UA, because the duration of the proc is over sooner than you have your Revenge cooldown up.

I believe this was changed towards the end of Wrath and shouldn't work that way on this patch.

**Comment by AnaxusRath** [comment]
Confirmed, seen that happen, is definitely not intended amount of DPS.

**Comment by ConradSilverwind** [comment]
Confirmed.

**Comment by Naidira** [comment]
Bug was noted in TrinityCore itself, but wrongly closed.

https://github.com/TrinityCore/TrinityCore/issues/6090

As noted in the TC post in regards to when the change was implemented, see:  http://www.mmo-champion.com/threads/705578-Icecrown-Citadel-Buff-boosted-to-10/

Change was made in March, well before Cataclysm.

**Comment by robinsch** [comment]
On PTR
