### ISSUE TITLE
NPC type: Wasps 

### ISSUE THREAD

**Issue by Deushazz** [dalaranwow/dalaran-wow#2863]
Issue: Wasps encountered so far (ones in Feralas, below Level 60) cannot be tamed by a hunter. Upon activating tame beast spell, it says "invalid target".
How it should be: They should be tameable. Using "beast lore" spell should work on this.

Not sure if this affects all wasps ingame, some one confirm?

Basically needs the Database updated.

**Comment by LordTmpp** [comment]
Silithid Wasps were sadly not tameable before Cataclysm. The ones in Zangarmarsh seem to be tameable as intended.

**Comment by Rushor** [comment]
> Silithid Wasps were sadly not tameable before Cataclysm. 

Newly tamable.  Not an exotic pet, so all hunters can tame them.  At the moment in the beta, you don’t seem to be able to tame the lower level silithid wasps, only those in Zangamarsh. 

![GitHub Logo](http://i.imgur.com/lzvgiaV.png)
