### ISSUE TITLE
[NPC] Loolruna - Items missing from vendor

### ISSUE THREAD

**Issue by AnaxusRath** [dalaranwow/dalaran-wow#2865]
### NPC Loolruna (id 19694)###
**in Zangarmarsh (at 68.5, 50.2) should be selling three Blacksmithing plans:**

**Plans: Adamantite Plate Bracers (id 23594)**
**Plans: Adamantite Plate Gloves (id 23595)**
**Plans: Adamantite Breastplate (id 23596)**

Each for 6 gold. Those are not available at this moment. 

#### EDIT: Items restocked, my mistake. It still seems confusing that items out of stock don't appear on the vendor, but I am not sure if that is intended or not. This could be possibly closed. ####

**Comment by belegija** [comment]
Items that are out of stock are not supposed to appear on the list, AFAIK.

**Comment by Golganeth** [comment]
Alright. Closing up
