### ISSUE TITLE
Quest: Velrog the Dervish

### ISSUE THREAD

**Issue by lvenonl1** [dalaranwow/dalaran-wow#2866]
Issue: The quest objective is pretty straight forward: Go to the Stagnant Oasis in The Barrens, slay a few Centaurs and then Verog the Dervish should appear inside the Centaur Hut by the base of the mountain:
![43767](https://cloud.githubusercontent.com/assets/14143252/9701698/3e54fd3e-542d-11e5-802d-fa667538c6ab.jpg)
But no matter how many we kill, Verog never spawns.

How it should work: Kill a few Centaurs, then one of them will yell "We are under attack! Summon Verog the Dervish!" (this happens once we deal the last hit on the enemy). Then Verog should spawn inside the hut.

YouTube Link:
https://youtu.be/vtNOhyit3CI?t=7m35s
Open WoW Link:
http://wotlk.openwow.com/quest=851

**Comment by Rushor** [comment]
you have a 3% chance to spawn him

**Comment by lvenonl1** [comment]
On official WoW, was it that low? I remember doing it easily back in the day.

**Comment by Golganeth** [comment]
#25
