### ISSUE TITLE
Quest / NPC: The Battle For The Ebon Hold - Patchwerk

### ISSUE THREAD

**Issue by Golganeth** [dalaranwow/dalaran-wow#287]
http://wotlk.openwow.com/quest=13166

**Issue:** The quest is doable, but the respawn timer of Patchwerk is too long (roughly 1 hour). That can easily cause troubles to players who want to do the quest right after someone has killed the NPC.

**How it should work:** The respawn time of Patchwerk on that phase should be maximum 4-5 minutes (Note: Can't be fixed on the spot).

- Patchwerk - http://wotlk.openwow.com/npc=31099

**Comment by Torrigan** [comment]
Still over an hour respawn timer
