### ISSUE TITLE
Ingame mail not arriving/disappearing

### ISSUE THREAD

**Issue by Spruitje** [dalaranwow/dalaran-wow#2873]
As promised on the forum, now posted on bugtracker:

Simply put, sometimes ingame mail doesn't arrive and so disappears
I have noticed it myself a few time on different occasions, and also here others complaining:

-Auction payments or returned items not arriving
-Mails send to alts not arriving
-Mails send to other accounts not arriving

(i am NOT talking about deleting chars before opening mail etc)

What is expected:
Mail should arrive, ALWAYS or be returned to sender

What happens:
Mail occasionally disappears, sometimes though the 'new mail icon' with sender name is noticed next to minimap

What triggers this:
No clue

This is not a new issue, i started noticing this myself more than a month ago
I send a lot of mail, and also make much use of auction house so at first i didn't really pay attention and didn't notice
Also on regular occasions people in global complain about disappearing mail

**Comment by Darkexecutioner** [comment]
I have noticed the same issue. I see the "new mail icon" and with the sender's name. I go to the mailbox, and there is nothing.

**Comment by KerDW** [comment]
Can confirm, you get the mail notification before you actually receive the package, you have to wait a bit or relog.
