### ISSUE TITLE
[Mage] Spellsteal and Blessing of Sanctuary

### ISSUE THREAD

**Issue by Milton3450** [dalaranwow/dalaran-wow#2874]
I don't get 10% hp (or strength I think) from spellstealing Blessing of Sanctuary. BoS is the prot pala buff that gives 10% str and 10% stam + 3% reduced dmg taken.

**Comment by Rushor** [comment]
> Blessing of Sanctuary can be stolen to reduce all damage you take by 3% for a maximum of 2 minutes.
http://wowwiki.wikia.com/wiki/List_of_magic_effects
http://wowwiki.wikia.com/index.php?title=List_of_magic_effects&diff=2232607&oldid=2131251

So the 10% hp should not work at all here. This works blizzlike then. I will close the issue.
