### ISSUE TITLE
[General] Flying bug - Stuck Bug - Stuck in Air

### ISSUE THREAD

**Issue by mondvrr** [dalaranwow/dalaran-wow#2878]
https://www.youtube.com/watch?v=UUrC9QvJcac&feature=youtu.be

just look at the video, im stuck in the air by only flying, it happens too when i arrival with an automatic fly, i cant disconnect i cant cast nothing i only can alt f4 and relog

**Comment by oddy555** [comment]
It seems like this bug might be a result of the quest last line of defense in icecrown. 
http://www.wowhead.com/quest=13086/the-last-line-of-defense

A friend of mine got the same getting stuck in the air problem yesterday after trying the quest. The quest in itself is broken(neither he and I could complete it) and there's probably something really weird with the phasing which is there after the quest has been taken. Me and my friend has also removed the quest from the log and we're still getting stuck  time from time. 

Another argument for it having to with this quest is that the area I'm getting stuck on is pretty close to the argent vanguard where the quest takes place. 

In the image I'm stuck again. 
![wowscrnshot_040616_184256](https://cloud.githubusercontent.com/assets/5502879/14324966/770d8194-fc27-11e5-9c4c-8ec036967cfe.jpg)

**Comment by Rushor** [comment]
The stuck problem seem to happen only in dalaran and icecrown - maybe phasing related?
