### ISSUE TITLE
Quest: Broken Alliances  ID:793

### ISSUE THREAD

**Issue by Sagrath** [dalaranwow/dalaran-wow#2882]
The Pillar of Opal (#2848) and Pillar of Amethyst (#2858) incorrectly despawn when right-clicked to receive the items Opal Runestone (#4484) and Amethyst Runestone (#4843). The Pillar of Diamond also respawns incorrectly, but it respawns instantly. 

The Pillars of Opal, Amethys, and Diamond should not despawn, and should give their runestones to whoever is clicking on them.

**Comment by jonanone** [comment]
Pillars won't despawn anymore once looted.

The fix will be applied to the live realm soon.

**Comment by Braniacz** [comment]
The Pillar of Diamond still respawns instantly. The other two dont respawn at all and they are not present ingame.
