### ISSUE TITLE
[Quest] Scouring the Desert ID: 9419/9422

### ISSUE THREAD

**Issue by Sagrath** [dalaranwow/dalaran-wow#2886]
The object Silithyst Geyser (#181598) is not working as intended. Either way, when clicking on a Silithyst Geyser, nothing happens. No buff is gained, and thus,  I cannot complete the quest.

Silithyst Geysers need maintenance.

**Comment by MrAndersonX** [comment]
Yeah, I'm also on this quest and click 3 Geysers so far and nothing happened. Bugged, needs a fix.

**Comment by fizzl** [comment]
Me three.

**Comment by Rushor** [comment]
this was fixed with https://github.com/TrinityCore/TrinityCore/commit/f535d59f0f93c959406b80382af6b1902bec5ce2

working fine for me on ptr

http://i.imgur.com/E1fUOhC.jpg

**Comment by TeridanDW** [comment]
Works as intended on ptr, however there are way too few objects http://wotlk.openwow.com/object=181598
