### ISSUE TITLE
Creature: Boss Tho'grun ID: 2944

### ISSUE THREAD

**Issue by Sagrath** [dalaranwow/dalaran-wow#2887]
Boss Tho'grun (NPC#2944 ) of The Badlands, is missing his entire bodyguard. There should be 4 bodyguard and a mystic who heals.
http://www.wowhead.com/npc=2944/boss-thogrun

**Comment by Rushor** [comment]
his bodyguards are there. fixed on live realm (maybe the bodyguards were killed previously)

![GitHub Logo](http://i.imgur.com/loo3xze.jpg)
