### ISSUE TITLE
Puddle breath glitch at Maraudon caves

### ISSUE THREAD

**Issue by Sagrath** [dalaranwow/dalaran-wow#2889]
In the caves of Maraudon (outside the instance), in the orange crystal side, there is a small area with a couple puddles of water under a bridge. Walking in the area displays a breath bar as though you were underwater, and it decreases until you leave. You don't need to be in the water for it to appear.

It's simply land with a couple small puddles, there shouldn't be any underwater breathing bars appearing at all unless submerged in the water, which is too shallow to do (unless I stand correctly).

**Comment by Rushor** [comment]
this also happens on the island in the northern barrens. It's a blizzlike issue :)
