### ISSUE TITLE
Quest: Ursoc, the Bear God (#12236)

### ISSUE THREAD

**Issue by npmusicftw** [dalaranwow/dalaran-wow#2895]
There are multiple spawns of Ursoc (26633). It appears that one spawns for everybody who tries to do the quest, rather than having a world spawn.

**Comment by Lothloryen** [comment]
Corrected.

**Comment by Slashkill** [comment]
Minor techanicality but the friendly NPC u got to assist u here is bugged.

I chose healer form, he went into treeform but after he got a few hits from a bear along the way he suddenly turned into DPS form and never went back to healing causing me to die.

**Comment by roblockster** [comment]
Quest still bugged, not corrected. There are multiple Ursoc spawns, resulting in multiple stuns, etc. and a quite difficult quest. Moreover, as Slash mentioned, the NPC that is supposed to assist the player is bugged and leaves tree form and doesn't heal.

**Comment by Mistarodub** [comment]
@Lothloryen Still bugged. NPC "Tur Ragepaw" assumes his healing form but then leaves it and does nothing during the fight
