### ISSUE TITLE
Pet and mobs falling under texture / Being out of position

### ISSUE THREAD

**Issue by MrAndersonX** [dalaranwow/dalaran-wow#2896]
Hi,

So, alot of times when I target a mob and use skills against it, it just evades them all and resets/moves back to his position/original position. And 90% of the time, either mobs fell under the map, or into textures, or my pet does. And for a bm hunter vs mobs, for his pet to suddenly get under the map and lose all aggro is really really bad. Not to mention the times the pet is going/falling through textures, and when I send him to attack or when he's supposed to defend the hunter, he is still struggling to get out of textures...

**Comment by Golganeth** [comment]
#1955

**Comment by MrAndersonX** [comment]
+1 to this. Hope it gets fixed, and soon.
