### ISSUE TITLE
NPC: Image of commander ameer

### ISSUE THREAD

**Issue by Penguindrum** [dalaranwow/dalaran-wow#2897]
For the quest series started from Commander Ameer in netherstorm http://www.wowhead.com/quest=10339/the-ethereum you are supposed the get further quests from an image of him by activating Ethereum transponder zeta
http://www.wowhead.com/npc=20482/image-of-commander-ameer
However you can get him to appear only once after every server restart.

**Comment by Penguindrum** [comment]
Okay it just took a few tries got him to appear

**Comment by DrFuler** [comment]
18/12/2015: Still bugs SOMETIMES.

Seems to work eventually. For some reason I think what might make have something to deal with having hostile mobs around, as at one point it said "hostile detected, transmission aborted" or something like that.
