### ISSUE TITLE
Ingame laag/delay

### ISSUE THREAD

**Issue by MrAndersonX** [dalaranwow/dalaran-wow#2898]
Hi,

Well, for the past weeks, I keep experiencing ingame laag/delay. The weird part is that during the day it works fine, but at evening-night, it laags/delays like crazy. Now, I donno if it's cause of the population peak or whatever, but I have delay like in everything, from auctioning items, to looting, to using skills, talking to NPC's etc. Is there a solution or fix to this please ? Thanks.

**Comment by Golganeth** [comment]
Might be on your side. Invalid report, the bug tracker only lists in-game issues with quests, NPCs and such.

**Comment by MrAndersonX** [comment]
Donno how it might be on my side, since everytime it happens, my internet and any internet activity works fine. And after 2 server restarts last night, I was laag free, then again it lagged, then it disappeared after some time. Anyways, tx but no tx.
