### ISSUE TITLE
Quest: Cold Hearted (#12856)

### ISSUE THREAD

**Issue by npmusicftw** [dalaranwow/dalaran-wow#2900]
The Freed Proto-Drakes (#29709) are extremely and mind-numbingly bugged in that they only can be controlled on a horizontal plane, and you cannot fly them up and down. This makes things particularly difficult (impossible) to free Valkyr women lower in the city. 

Additionally, they move at walk speed. Not ground mount, not running speed, not even swimming speed. The dragon moves at walking speed, and it takes like 8 minutes to get from Dun Niffelem to Brunnhildar.

**Comment by Golganeth** [comment]
#2412
