### ISSUE TITLE
Quest: Cave Medicine (#13055)

### ISSUE THREAD

**Issue by npmusicftw** [dalaranwow/dalaran-wow#2901]
The object Toxin Gland (#42927) which drops from Infesting Jormungar (#30148) has an incorrect drop rate (which reflects the frequency the item drops including kills from people who don't have the quest. The 5% drop rate is incorrect. The drop rate is rather probably around 40-50% because most people received the item after their 1st kill up to their 6th kill.

**Comment by jonanone** [comment]
The drop rate has been adjusted and it will be applied to the live realm soon.
