### ISSUE TITLE
Quest: Hodir's Tribute (#13559)

### ISSUE THREAD

**Issue by npmusicftw** [dalaranwow/dalaran-wow#2902]
The quest Hodir's Tribute should be available at neutral reputation, rather than friendly.

Also, as of patch 3.3.0:

"The following reputations have been sped up by roughly 30%:
• Argent Crusade
• Alliance Vanguard
• Horde Expedition
• Kirin Tor
• Knights of the Ebon Blade
• Sons of Hodir
• Wyrmrest Accord

Sons of Hodir quests now give more reputation overall."

- Patch notes, 3.3.0, (http://us.battle.net/wow/en/game/patch-notes/3-3-0)

**Comment by Tarpor** [comment]
Talents and abilities are 3.3.5, the rest isn't, it's a progressive server.

**Comment by npmusicftw** [comment]
I appreciate the feedback, Tarpor. I realize that it's a progressive server. Do you have a citation indicating that it strictly applies to talents and abilities? A lot of quests that were changed in 3.3.0 are changed on this server. RDF is available on this server. Many other changes and implemented features are available, even though it's progressive.

Even so, Hodir's Tribute was available at neutral reputation from as far back as as 3.0.8 (that I can find).

http://www.wowhead.com/quest=13559/hodirs-tribute - comments
