### ISSUE TITLE
Updated Information on Drop Rate for Quest: Hot and Cold (#12981) 

### ISSUE THREAD

**Issue by npmusicftw** [dalaranwow/dalaran-wow#2903]
The item that drops for this quest (Essence of Ice [#42246]) has an incorrect drop-rate. 

According to comments on WoWhead (and my memory post 3.3.0):

"This appears to be a 100% drop rate now. However, 6 are now required for the quest, so I suspect either the stack size will change or the requirement will be changed back." - Jerodast, 2009/12/09, Patch 3.3.0 (http://www.wowhead.com/item=42246/essence-of-ice#comments)

"you are right, however it also seems like essence of ice is now a 100% drop rate. i got 6 in a row. Fair trade off having to do 1 more, but it being a 100% drop." - Harmar, 2009/12/08, Patch 3.3.0, (http://www.wowhead.com/quest=12981/hot-and-cold)

The Openwow drop-rate probably includes kills from people without the quest and is now incorrect. 

The drop-rate on Algalon seems much lower than the OpenWoW drop-rate at any rate, but I may just have horrendous fortune.

**Comment by Spruitje** [comment]
It's not your bad fortune, had horrible droprate there too
Major PITA especially if two or more trying to complete this daily and everyone is camping the area trying to tag the mobs for the kill/loot

**Comment by Golganeth** [comment]
Duplicated #944
