### ISSUE TITLE
Dying at the Temple of Life, Storm Peaks

### ISSUE THREAD

**Issue by npmusicftw** [dalaranwow/dalaran-wow#2904]
If you die while doing the quest Changing the Wind's Course (#13058) at the Temple of Life, your body disappears, and when you come back as a spirit to rezz yourself, you can spam click "accept" to no avail. Nothing happens. In fact, if you log out or alt+f4, the spirit healer to rezz you disappears (or at least it did for me).

**Comment by vasius** [comment]
it happened to me excactly the same but as it seems they dont give a fck about it

**Comment by jonanone** [comment]
If Stormhoof dies while completing the quest, you will be teleported to the present so you can't die on the other phase and that should avoid issues dying on the other side.
This update will be applied to the live realm soon.
