### ISSUE TITLE
[Quest] Betrayal 

### ISSUE THREAD

**Issue by sashouktc** [dalaranwow/dalaran-wow#2905]
Currently the quest is impossible to complete unless you're a class that can heal itself with a healing spec. The platform where you fight Drakuru has an aura that deals 1200 damage every 2 seconds. That is not how the fight was. 

http://www.wowhead.com/quest=12713/betrayal#comments - all comments in wowhead suggest there was no such thing and all videos of retail fights show no aura as well. The quest is the end of a long chain and is also an achievement.

**Comment by Golganeth** [comment]
Duplicated #2576
