### ISSUE TITLE
[Quest][Outland] Shutting Down Manaforge Coruu

### ISSUE THREAD

**Issue by Jakiri** [dalaranwow/dalaran-wow#2907]
This applies to all the Shutting Down Manaforge [x] quests in Netherstorm as far as I can tell, but this is the one that I was just doing.

When the technicians run in to stop the shutdown procedure, if you tag them with a spell that doesn't do immediate damage (eg Corruption, Curse of Agony, Unstable Affliction) then the spell will not land (with no combat log notification that it was even cast, so no miss or whatnot) and the shutdown procedure will be immediately stopped.

If you tag them with a damaging spell or attack (eg Wand, Shadowbolt, Haunt) then it works as normal.

**Comment by Rushor** [comment]
script was replaced in https://github.com/TrinityCore/TrinityCore/issues/12724, probably an sai issue then

**Comment by Rushor** [comment]
works fine for me, even if i damage them with dots
