### ISSUE TITLE
Quest: Verog the Dervish

### ISSUE THREAD

**Issue by transroute** [dalaranwow/dalaran-wow#2908]
While the quest states that you should kill many centaurs, before the NPC Verog appears. I have killed as much as you can imagine. Three time did the centaurs yell: "Verog come to us"  or something, in red letters. But he did not appear.
Can you help fix this bug? 
transroute

**Comment by transroute** [comment]
I now this has been asked before... 
But, seriously - that much slaying - it has to be more than 100...

**Comment by exiledone** [comment]
this quest does work...done it on two different toons. first time it took 50+kills second time almost 100.
it depends on how lucky u are. some have completed with 15 kills others over 200

**Comment by transroute** [comment]
Ok. Thanks for the info!
