### ISSUE TITLE
[Quest][Northrend] Help Those That Cannot Help Themselves

### ISSUE THREAD

**Issue by Sagrath** [dalaranwow/dalaran-wow#291]
The problem is that this quest is too much easy to finish, it's easier then it should be.
The quest objective is to use the quest item D.E.H.T.A. Trap Smasher to free 8 Mammoth Calves.
When one release a Mammoth calf, it's counts as like I released 4 Mammoth Calves, so I finished this quest objective after I released only 2 calves instead of 8 as it should be.
If the quest would have worked properly I would have to set free 8 calves and not only 2.

wowhead quest link: http://www.wowhead.com/quest=11876
wowhead quest item link: http://www.wowhead.com/item=35228

**Comment by Rushor** [comment]
todo: move itemscript to spellscript

**Comment by Rushor** [comment]
objects are no longer spammable, you will not get multiple credits

**Comment by Golganeth** [comment]
Completed the quest by spamming the quest item on the same calf. Once it was already completed a cast bar appeared and the animation of the trap happened.

**Comment by Golganeth** [comment]
Fixed now, both in PTR and live realm.

**Comment by Golganeth** [comment]
The following gobject misses a trapped calf
[Mammoth Trap] GUID: 66627 ID: 188029

http://wotlk.openwow.com/npc=25850
>Very minor

**Comment by Rushor** [comment]
i wonder if we could add a label for very-minor issues :)
