### ISSUE TITLE
Caracter stuck in flight

### ISSUE THREAD

**Issue by ciaky78** [dalaranwow/dalaran-wow#2913]
Please unstuck my character Micheline. It got stuck on the fly mount between Dalaran and Storm Peaks. Thanks.

**Comment by Spruitje** [comment]
AFAIK bugtracker is not meant for such request
Describe exactly what happened and what you think might trigger this so it might get prevented in the future(if possible) but if you are really stuck with no solution then the best course of action is to contact a GM ingame by making a ticket

**Comment by Golganeth** [comment]
Invalid report, the bug tracker only lists in-game issues with quests, NPCs and such. On a side note your character should be fine now.
