### ISSUE TITLE
Klyksmas

### ISSUE THREAD

**Issue by Justelis** [dalaranwow/dalaran-wow#2914]
Hello, im trying to change my name and race, but i cant. when i select Change name or change race it drops me to home page, please help me.

**Comment by Tarpor** [comment]
Hi, make a post at http://www.dalaran-wow.com/forums/input-and-assistance/community-support.

They're also working on the website, so some features might be disabled and that could be the reason.

**Comment by Golganeth** [comment]
Invalid report, the bug tracker only lists in-game issues with quests, NPCs and such. You might find [this thread](http://www.dalaran-wow.com/forums/community/general-discussion/topic/6448/race-cange) useful though.
