### ISSUE TITLE
Ulduar ID

### ISSUE THREAD

**Issue by Johanes022** [dalaranwow/dalaran-wow#2915]
After killing Flame Leviathan sometimes( i dont know the circumstances) raid members are not getting ID , makeing other ppl who leave/relog unable to continue the raid.This has been an issue ever since Ulduar release.This has been abused by many guilds (long time ago) killing Flame Leviathan multiple times earning badges without ID.

ps: I dont know if this is duplicate post, but i couldnt find one.

**Comment by Lothloryen** [comment]
Hello there,

For some reason son hotfixes I made for this encounters time ago seem to have stopped working, I shall take a look and implement a new correction soon.

Thank you.

**Comment by DanteMS** [comment]
Still not fixed.
