### ISSUE TITLE
Quest: Warsong Supplies

### ISSUE THREAD

**Issue by transroute** [dalaranwow/dalaran-wow#2918]
In the quest you have to collect for items and I have collected all of them.
In my quest log it says (complete) but when I come to the NPC  Locke Okarr the question
mark is grey, like I have something missing - but I don't. 
So I can't turn in the quest. 
thanks

**Comment by Golganeth** [comment]
General issue. The quest works fine, you have to re-take it.

**Comment by TeridanDW** [comment]
The quest mentioned above is https://wowgaming.altervista.org/aowow/?quest=6571
Item https://wowgaming.altervista.org/aowow/?item=16745 is suppose to drop from https://wowgaming.altervista.org/aowow/?object=178204 with 100% drop chance, but it isn't.
After 10 tries still empty box. Needs to be checked if this quest is doable only once per server restart/crash.
