### ISSUE TITLE
Pet Revive

### ISSUE THREAD

**Issue by starkblacksoul** [dalaranwow/dalaran-wow#2920]
Hello, I can't revive my pet after it dies. My "revive pet" and my husband's "ancesteral spirit" don't work, so I am having to train a new pet every time it dies. Please help! 

Thanks!
Jenn

**Comment by Golganeth** [comment]
Can't reproduce this. Sounds like an issue on your client/side. If you're doing everything as you should and the problem persists, then try clearing your Cache folder. If that still doesn't help out, try to re-install the game from scratch.
