### ISSUE TITLE
Problem with steady shot.

### ISSUE THREAD

**Issue by Venomist** [dalaranwow/dalaran-wow#2921]
I am not well in deep calculating, but what is wrong with steady shot.

Description for my Steady shot is: Unmodified weapon damage + ammo + 275. 
But as you can see, 214 physical is too low for any calculating.

![wowscrnshot_092815_112647](https://cloud.githubusercontent.com/assets/14870083/10132115/107d44ac-65d5-11e5-84f1-de1d3c6260b1.jpg)

![wowscrnshot_092815_113422](https://cloud.githubusercontent.com/assets/14870083/10132128/14e217e8-65d5-11e5-9e19-21bf0d8737b8.jpg)

I dont know, if it is bug or I just cant read, can someone explain me this please?

**Comment by Tarpor** [comment]
It's a bug with the heirloom bow, it's calculating for the level 1 bow.

**Comment by Golganeth** [comment]
Reported on #2427
