### ISSUE TITLE
Bloody Fury (id: 33697) Tooltip Doesn't Update

### ISSUE THREAD

**Issue by npmusicftw** [dalaranwow/dalaran-wow#2922]
The Orc racial does not update its tooltip as it gets more powerful. 

For example, at level 1, it increases SP by 5, and AP by 6. 

At level 60 (and everywhere in between) it continues to say that increases SP by 5 and AP by 6. However, it obviously increases those by a much high amount.

**Comment by Rushor** [comment]
This is a known issue in the wotlk client. Sadly this cannot be fixed. It's only a visual issue, the actual amount for the calculation is increaded correctly.
