### ISSUE TITLE
Some Original /who Chat Commands Not Implemented

### ISSUE THREAD

**Issue by npmusicftw** [dalaranwow/dalaran-wow#2926]
I'm not sure if this issue has been reported, as I could not find any evidence that it has. 

Using /who all, /who -insert race-, and “/who -insert class-” do not work. Using “/who all” finds people with “all” in their name or in the zone that they're in, /who -race- finds a player/players with the race in their name, and /who -class- finds a player named that particular class if he's online. 

The command “/who all” should display everybody who is online of your faction (Or the 70 some listed).
The command “/who -class-” should display everyone of that particular class. 
The command “/who -race-” should display everyone of that particular race.

**Comment by belegija** [comment]
Because you are using them wrong. For class use the switch c- and race r-, like this: /who c-paladin r-human 60-70. This filters all human paladins between levels 60-70.
You are probably comparing to some other private server that has custom commands built in.
All commands on [wowwiki](http://wowwiki.wikia.com/wiki/Who_List)

**Comment by npmusicftw** [comment]
No, I am comparing them to how it was on Blizzard's live servers and how it is STILL functioning on Blizzard's live servers.

However, it is nice to know that those commands you just showed me are in existence! Thanks for that :D

**Comment by Golganeth** [comment]
What @belegija said. This is WoTLK and commands are fine, I can't find any proof stating otherwise.
/who 1-80 (or any other level range you wish)
/who c-$class ($levelrange)
/who r-$race ($levelrange)
/who g-$guildname

Closing up
