### ISSUE TITLE
Upper Blackrock Spire Is Not In Specific Queue

### ISSUE THREAD

**Issue by npmusicftw** [dalaranwow/dalaran-wow#2927]
Currently, when looking to queue for a specific dungeon (level 55-60), the dungeon Upper Blackrock Spire does not make its way to the list. Lower Blackrock Spire does, but Upper is missing.

I found this because Upper is a good place to farm Rugged leather, which I am in a lot of need of. I can't queue for it though, because it's not there!

**Comment by belegija** [comment]
Upper Blackrock Spire is a 10-man raid instance in the Wrath of the Lich King

**Comment by npmusicftw** [comment]
Yes, but it was still on the the RDF tool, as UBRS and LBRS are part of the same instance.

**Comment by Augur89** [comment]
You can get tons of Rugged Leather skinning the yetis on Winterspring, easier than going into a 10 man dungeon ;-)

**Comment by belegija** [comment]
They are part of the same instance but the difficulty of UBRS is tuned for 10man raid and never in WoTLK were you able to queue specific for UBRS ( even makes no sense being 10 man raid).
"Patch 4.0.3a (2010-11-23): Upper Blackrock Spire is now a 5-man dungeon."
Reference: [WoWWiki UBRS](http://wow.gamepedia.com/Upper_Blackrock_Spire_%28original%29)
But to wrap this up, provide evidence for your claims in issues so it can be fixed if needed, or else the devs are closing the issue for being invalid.

**Comment by npmusicftw** [comment]
@ Augur89, Yes, I wound up going there xD

@belegija I realize that patch 4.0.3a made it a 5 man dungeon, but I also know I'm not the only person who recalls seeing it prior to 4.0.3, but perhaps post 3.3.0.

Nonetheless, you're right about having a citation. I will close it for now until I can find evidence.
