### ISSUE TITLE
[Quest][Classic] Dangerous! 

### ISSUE THREAD

**Issue by npmusicftw** [dalaranwow/dalaran-wow#2932]
This quest begins on the billboard in Tauren Mill, but it does not have a yellow “!” on the mini-map, indicating that there is a quest. One has to happen to mouse over the paper and notice that there is a quest there. 

Just need to fix it so that there is an “!” point visible on the mini-map.

**Comment by Rushor** [comment]
http://i.imgur.com/nEDyxvB.jpg it' there make shure, that the low-question marks are enabled on the minimap http://i.imgur.com/rJ9V2Ez.jpg
