### ISSUE TITLE
Dire Maul East partially bugged elite ( holding the key to Dire Maul West)

### ISSUE THREAD

**Issue by MrAndersonX** [dalaranwow/dalaran-wow#2934]
Hi,

Well, did Dire Maul East yesterday, and while starting the Pusillin chase, I noticed he just runs through the air, walls, texture. Even tho he gets where he should be, and he can be chased properly at half the way, and he can be killed for the key, it's still a minor issues but a issue nonetheless.

**Comment by npmusicftw** [comment]
Zone # 2557
Pusillin, NPC # 14354

**Comment by MrAndersonX** [comment]
Tx for the help bro :+1: .

**Comment by PSAlias** [comment]
In addition, it should be noted that after the chase event concludes and the combat event is triggered, making the NPC hostile and spawning in additional mobs, wiping/leaving the instance will reset the NPC to its original position near the start of the instance while still hostile. This allows players to kill and loot Pusillin without having to engage his adds.

**Comment by Rushor** [comment]
moved to https://github.com/dalaranwow/dalaran-wow/issues/2503#issuecomment-261136654
