### ISSUE TITLE
Moonkin form for druids

### ISSUE THREAD

**Issue by rickyayers** [dalaranwow/dalaran-wow#2935]
Moonkin form does not give the armor bonus that it is supose to give while in that form it gives a o% increase.
thank you

**Comment by npmusicftw** [comment]
It works just fine for me. 

What level are you? How much armor do you have prior to and post Moonkin form?

**Comment by rickyayers** [comment]
awesome i just checked and its working now however at level 70 i was getting no increase. thank you
