### ISSUE TITLE
Warlock Pet Attack Power Not Scaling With Certain Abilities

### ISSUE THREAD

**Issue by npmusicftw** [dalaranwow/dalaran-wow#2936]
All threads about this seem to have been closed.

According to this lovely chart on WoWpedia:

**MINION SCALING**

As a warlock improves their stats, their minion also improves.

*Minions inherit their masters' stats as follows:

Spell damage (highest bonus)    15% (as spell damage)
57% (as attack power)
- Minions' offensive spells generally gain bonus damage equal to 100% of the minions' spell power, and minions gain 1 auto-attack DPS per 14 attack power like player characters.

http://wow.gamepedia.com/Minion#Minion_scaling

![wowscrnshot_093015_221952](https://cloud.githubusercontent.com/assets/14337111/10211474/9693406c-67c1-11e5-8538-826a199c714c.jpg)
As you can see, I have 1523 spell power. That includes the **Glyph of Life Tap (#45785)** (which the Felguard is not scaling with).

![wowscrnshot_093015_221949](https://cloud.githubusercontent.com/assets/14337111/10211472/96930782-67c1-11e5-8573-493898d8b360.jpg)
Here, he has 1174 AP. 

![wowscrnshot_093015_222013](https://cloud.githubusercontent.com/assets/14337111/10211475/9693a138-67c1-11e5-83e1-059cd140f6d8.jpg)
Now I have 159 Spellpower.

![wowscrnshot_093015_222015](https://cloud.githubusercontent.com/assets/14337111/10211473/969335ae-67c1-11e5-98bb-7631e7f13111.jpg)
And he scales down to 454 attack power. 

So, with gear, I go from 159 SP to 1523 SP. That was a 1364 SP difference. (*0.57=777.48)
Felguard scaled from 454 AP to 1174 AP. That's a 720 AP difference. (/0.57=1263.16) 

So there is ~100 SP (~57 AP) missing somewhere in that equation. 
A portion of that could be a result of **Glyph of Life Tap (45785)** not scaling. The only time he scales with it is if he's dismissed and resummoned (or mount and dismount). 

![wowscrnshot_093015_223911](https://cloud.githubusercontent.com/assets/14337111/10211724/226e4d96-67c4-11e5-89fa-2ce6105acb21.jpg)

And after resummoning (mount & dismount)
![wowscrnshot_093015_223920](https://cloud.githubusercontent.com/assets/14337111/10211725/226ebfc4-67c4-11e5-8b02-c4eeaa8c146a.jpg)

So, unless I am missing some information, the Felguard should scale with all buffs and temporary SP gains (since he does indeed scale with my trinket procs).

The following items he does not scale with until he is resummoned:
**Glyph of Life Tap (45785)**
**Superior Wizard Oil** (22522)

**Comment by npmusicftw** [comment]
Update: It seems that any change in SP that isn't a trinket or a trained spell does not scale as it is supposed to.

**Comment by Rushor** [comment]
this issue will be handeled in https://github.com/dalaranwow/dalaran-wow/issues/3088
