### ISSUE TITLE
Northrend Skinning

### ISSUE THREAD

**Issue by JackMV** [dalaranwow/dalaran-wow#2939]
Mobs in Northrend are only dropping one leather when skinned. They should be able drop more depending on the mob level and the item skinned. Some examples:

[http://www.wowhead.com/npc=28477/scion-of-quetzlun#skinning](http://www.wowhead.com/npc=28477/scion-of-quetzlun#skinning)
[http://www.wowhead.com/npc=31404/azure-manabeast#skinning](http://www.wowhead.com/npc=31404/azure-manabeast#skinning)
[http://www.wowhead.com/npc=28378/primordial-drake#skinning](http://www.wowhead.com/npc=28378/primordial-drake#skinning)

**Comment by jonanone** [comment]
Some fixes have been made to Northrend skinning loot. These updates will be applied to the live realm soon.
