### ISSUE TITLE
Fishing Bug

### ISSUE THREAD

**Issue by nickl384** [dalaranwow/dalaran-wow#2942]
In patch 3.1.0, a change was made to fishing, as seen here. However, this function is not working on Dalaran WoW.

"You can now fish anywhere, regardless of skill. Every catch has the potential for fishing skill gains, but you are likely to catch worthless junk in areas that are too difficult for your skill."

Source: http://wowwiki.wikia.com/wiki/Patch_3.1#Fishing

**Comment by Golganeth** [comment]
#1275
