### ISSUE TITLE
Iron Rune Constructs and You: Collecting Data

### ISSUE THREAD

**Issue by Ticklebur** [dalaranwow/dalaran-wow#2943]
You can get into the Golem, it puts you on the plate where you need to "collect data",
but when you press the button to start collecting, it does not work.

Tried 5 times, abandoned, retook, repeated 3 times, didn't work at all.

**Comment by wjschock** [comment]
You don't do it at the one that the construct spawns at. Walk towards the cart near the Dude and his rug, and you'll see a blue glowing crystal.

**Comment by Golganeth** [comment]
#470

**Comment by catta000** [comment]
There is no blue glowing crystal visible. Quest works if you stand next to Gwendolyn beside the empty cart (where the blue crystal should be)

![collecting_data](https://cloud.githubusercontent.com/assets/14143422/26704763/b41f5124-4731-11e7-8ee0-66cf5bceee02.jpg)
