### ISSUE TITLE
One of a Kind [Quest] [Northrend]

### ISSUE THREAD

**Issue by aepoirier** [dalaranwow/dalaran-wow#2944]
The quest given to you by NPC Aurastrasza of Wyrmrest Temple requires you (and a friend as this is a 2 person group quest) to kill the magnatuar, Bonesunder, and return with his emblazoned horn. 
The quest mob (Bonesunder) hits way too hard for a mere 2 person quest. As a Ret Paladin in full blues (with Devotion Aura activated no less) I was consistently hit for ~5300 physical damage (non critical). Even with 2 people, this quest mob is MUCH more difficult than it was on retail.

**Comment by AgeAgainst** [comment]
I just attacked him on my level 72 rogue with a whopping 3064 armor and was getting hit for 1200-1400 damage.  However, when he cast Bone Crack, the same thing happened to me that happened to you.  5k+ attacks.

Bone Crack is an attack that has a cast bar that when completed hits anyone in melee range for 200% weapon damage and then puts a debuff on those people that makes them take 100% damage for 20 seconds. Get out of range of bone crack and you'll be fine.

**Comment by Golganeth** [comment]
Nothing seems wrong with this.
