### ISSUE TITLE
Quest: The Northern Pylon #24722

### ISSUE THREAD

**Issue by blahami2** [dalaranwow/dalaran-wow#2946]
Hitting "Examine the pylon" does not mark the quest complete.
Same goes for quests The Eastern Pylon and The Western Pylon.
wowhead: http://www.wowhead.com/quest=24722/the-northern-pylon

**Comment by Golganeth** [comment]
Proof? Just tested all three and they work fine. Make sure you weren't in a raid group.

**Comment by Klala** [comment]
I'm sorry, Golganeth, but it seems the 3 quests really are bugged.
They are indeed work perfectly, when you are solo. If you are in group it doesn't work and hitting "Examine the pylon"  do nothing just as blahami2 says. Please check this again while in group.

**Comment by Golganeth** [comment]
Confirmed none of the three pylon quests work while in a group (not raid, just normal group)
**Workaround:** don't be in a group to examine the pylons.
Also the completion message on the screen is shown twice once a pylon is examined.

- The Northern Pylon - **Quest ID:** *4285* / **Game_object ID:** *164955*

- The Eastern Pylon - **Quest ID:** *4287* / **Game_object ID:** *164957*

- The Western Pylon - **Quest ID:** *4288* / **Game_object ID:** *164956*

---------------------

http://wotlk.openwow.com/quest=4285
http://wotlk.openwow.com/quest=4287
http://wotlk.openwow.com/quest=4288
http://wotlk.openwow.com/object=164955
http://wotlk.openwow.com/object=164957
http://wotlk.openwow.com/object=164956

**Comment by Rushor** [comment]
bb8cc46e6cdef191b91082c02e34126929b09aa5
- all three pylons for all three quests will now reward the credit for the whole group

**Comment by Golganeth** [comment]
The quest can be completed while in a raid group too, which shouldn't happen. But not a big deal
