### ISSUE TITLE
Quest: All Hail Roanauk!

### ISSUE THREAD

**Issue by JackMV** [dalaranwow/dalaran-wow#2948]
If someone starts this quest and then does not go through the dialogue options with [Roanauk](http://www.wowhead.com/npc=26810/roanauk-icemist), [Overlord Agmar](http://www.wowhead.com/npc=26379/overlord-agmar) will remain at the location he walks to for the quest until that person either comes back and completes the dialogue with Roanauk or until the server restarts. Additionally, no one will be able to interact with him to turn quests in or receive quests.

http://www.wowhead.com/quest=12140/all-hail-roanauk

**Comment by Golganeth** [comment]
#2775
