### ISSUE TITLE
[Rogue] Glyph of Hunger for Blood

### ISSUE THREAD

**Issue by KazJR** [dalaranwow/dalaran-wow#2953]
A couple of weeks ago I noticed that the bonus from this glyph did not apply to the buff you got, and thus remained at 8%.
However when I checked it today it was at 5%, thus giving a -3% instead of the intended +3%

Screenshot of the buff: https://gyazo.com/cd8197f5282ea47a34499b4f270d0caf

**Comment by Golganeth** [comment]
Works fine. The glyph extra % increase isn't shown in your buff bar, as intended.
