### ISSUE TITLE
Compiled List of Storm Peaks Bugs

### ISSUE THREAD

**Issue by Cybrok** [dalaranwow/dalaran-wow#2955]
http://textuploader.com/ab8wv

This is a link to a text document (no download) of all the bugs i found while questing through Storm Peaks.

**Comment by Cybrok** [comment]
http://pastebin.ca/3199457
textuploader is gone or somethin, so here, they didnt hold the formatting but, theyre numbered now

**Comment by Golganeth** [comment]
Invalid report. Please make sure the problems aren't reported already and make a separated one for each issue. Adding the text on the report itself (not using external links) would also help a lot. Thanks
