### ISSUE TITLE
 [Untold Truths] - Quest - Borean Tundra - Bugged NPC spawn

### ISSUE THREAD

**Issue by Tandiss** [dalaranwow/dalaran-wow#2957]
Hello,
I found a little bit bugged q named  [Untold Truths].
Quest link:
https://wotlk-twinhead.twinstar.cz/?quest=11614

It's simple, all you need to do is talk to npc named Shadowstalker Luther like this:
https://www.youtube.com/watch?v=PK_25DTfEzs

The problem is, that the NPC [npc ID: 25328]
https://wotlk-twinhead.twinstar.cz/?npc=25328
isn't spawned, or better said, isn't spawned on visible place.
I can target him by typing /target Shadowstalker Luther , but he isn't visible, he is probably spawned somewhere under texture. 

It's important quest, blocking a long chain and it's really simple to fix this problem.

Thank you for your patience,
Tandiss.

**Comment by Golganeth** [comment]
#2766
