### ISSUE TITLE
Item [Hallow's End Pumpkin Treat] is bugged

### ISSUE THREAD

**Issue by Hazarx** [dalaranwow/dalaran-wow#2961]
http://www.wowhead.com/item=20557/hallows-end-pumpkin-treat#comments
Possible effects:
1) http://www.wowhead.com/spell=24924/hallows-end-candy (increases size, makes you orange, attacks have 5% chance to reduce attack speed by 25% Movement speed by 30%.)
2) http://www.wowhead.com/spell=24925/hallows-end-candy (transforms into skeleton, gives underwater breathing)
3) http://www.wowhead.com/spell=24926/hallows-end-candy (transforms into pirate, increases swim speed by 50%)
4) http://www.wowhead.com/spell=24927/hallows-end-candy (transform into ghost (transparent, blueish, levitating), water walking and slow fall, can't fight)

**Comment by Lothloryen** [comment]
Hello there,

Thank you for the report, they will be fine tomorrow most likely.

**Comment by Lothloryen** [comment]
Hello
