### ISSUE TITLE
Eysore blaster for Quest  It's all fun and games loacted in Icecrown

### ISSUE THREAD

**Issue by Jrizzle23** [dalaranwow/dalaran-wow#2965]
They eyesore blaster is only 12600 damage and i think it is supposed to do 126000 damage . The eyesore blaster just does not do enough damage to kill the ocular and it instantly regenerates it's hp. The quest is located in icecrown on northrend.

**Comment by Golganeth** [comment]
The item works as intended (10% hp per hit). There are however reseting/spot issues with the NPC, which are already reported here: #549
