### ISSUE TITLE
Ulduar: The Iron Assembly Health Pools

### ISSUE THREAD

**Issue by npmusicftw** [dalaranwow/dalaran-wow#2967]
I have looked about the bug tracker forums and haven't found any information pertaining to this. If I am wrong (which I most likely am) and this was intended, I must have missed the memo (as I have recently returned to Dalaran-WoW). Perhaps there was an HP buff that I haven't found on the forums yet, but I think this 100% increase is a bit overkill for 10M. 

In the 10 man version of the encounter, all three bosses have over double the HP they are supposed to have. The only reason I learned this is because I kept hitting the enrage in a guild I was pugging with.  I will show you here, in these three videos, the health pools here on Dalaran-WoW:

https://www.youtube.com/watch?v=H1j5yzBFRyU
https://www.youtube.com/watch?v=DLNzh7DwtmI 
https://www.youtube.com/watch?v=ipwvJpETOBo

The last video was sped up to roughly 200% normal speed.

Now, here are videos from retail raids:
https://www.youtube.com/watch?v=vBPyfOnf18g
https://www.youtube.com/watch?v=OGRe4oPJjww
https://www.youtube.com/watch?v=IoORZ310Pl0

Now, I will list the reasons I am convinced that these health pools are incredibly wrong.

This is pre-ToC, which is
 pre-ICC. And ICC 10M bosses even on heroic don't have almost 20M health. Normal-mode Lord Marrowgar has 6.9M health. Each boss of the Iron Council is almost a Marrowgar in health, and that's two raids away and nearly 30 ilvls difference! 
All of the videos from 2009 indicate that they roughly add up to 9M hp on 10M. 
On 25M, they have 10M health each. It doesn't make sense for a raid 2.5 times as large to have health pools only only 1.6 times as large, when they usually had 3-4 times the health of 10M.
http://wowwiki.wikia.com/wiki/Assembly_of_Iron?section=21&action=edit has not been updated since WotLK was current content, and the health pools there coincide with the ones from the videos.

This indicates to me that the health pools on 10M and 25M on Dalaran-WoW are extremely far from Blizzlike, and should be fixed immediately. 

If I missed something, am incorrect about something, or missed a thread on the bug tracker, I apologize! 

Sincerely,

**Comment by npmusicftw** [comment]
Has been brought to my attention that this is indeed an HP buff. Will now close.

**Comment by Phr00tage** [comment]
With ICC being nearby, can this health pool be reduced to Blizzlike values? Is and has always been a blocker to progression, especially on 10man.
