### ISSUE TITLE
Flame Leviathan Vehicles 

### ISSUE THREAD

**Issue by npmusicftw** [dalaranwow/dalaran-wow#2968]
The vehicles from the Flame Leviathan can currently be used to slay the other bosses in the area for guilds who have a hard time killing the bosses. In fact, 25M modes can be killed with 10 people because of the ability to use the vehicles.

As soon as the Flame Leviathan dies, the vehicles should eject all players, and they should not be able to re-enter. 

Here are some videos displaying this mechanic:
https://youtu.be/JvraP9VCkyk?t=4m58s
https://youtu.be/qjyrze0G0KM?t=3m56s
https://youtu.be/XPsL73HkJ5Q?t=2m55s

**Comment by Lothloryen** [comment]
Hello there,

I implemented a mechanic to avoid this issue, however it seems to have stopped working for some reason. I shall take a look and deploy a new correction soon.

Thank you.
