### ISSUE TITLE
Heroic Dungeon ID doesn't reset

### ISSUE THREAD

**Issue by tripleslash** [dalaranwow/dalaran-wow#2969]
Hello everyone,

my heroic dungeon locks for Auchindoun: Sethekk Halls doesn't reset properly. I've done it 3 days ago and the lock is still there. It's supposed to reset everyday.

**Comment by tripleslash** [comment]
Still not reset for me :(

**Comment by Klala** [comment]
This is still a problem, I haven't checked but wouldn't be surprised if more tbc heroics act that way.

**Comment by robinsch** [comment]
Ref: https://github.com/dalaranwow/dalaran-wow/issues/5088
