### ISSUE TITLE
[Quest][Classic] Bloody Breakout

### ISSUE THREAD

**Issue by Sagrath** [dalaranwow/dalaran-wow#297]
http://old.wowhead.com/npc=28912
Koltira Deathweaver fights the scarlet members rather than maintaining an anti-magic zone

**Comment by SoundwaveAU** [comment]
Still an issue as of 23/4/16. Had to run back to my corpse a couple of times while Koltira fought the dude and drained his mana. Managed to eventually take him down.

**Comment by Rushor** [comment]
e92d05bf6b49451a194adcc7275a7dc6af84be62
- the SPELL_ANTI_MAGIC_ZONE should now always be up and the player can benefit from it

**Comment by Golganeth** [comment]
Still broken. Once the first wave arrives, Koltira will move out of its casting magic zone position (battle stance with fists) although the magic zone will still be up.
Once the first wave dies, the magic zone disappears.

**Comment by shadovvs** [comment]
Aside from anti-magic zone, there are some visual bugs like Koltiras armor and him being under the table instead of on it. (http://i.imgur.com/b1fazYL.jpg)

Here is how the quest should look like:
https://www.youtube.com/watch?v=87s-K_3-tpM

**Comment by anderyu** [comment]
I've been trying to complete this quest for multiple days. The guy doesn't shield and I die in three hits. Is there a fix, or can a GM help me through it in game?
