### ISSUE TITLE
[Warlock] Curse of the elements

### ISSUE THREAD

**Issue by moonsado** [dalaranwow/dalaran-wow#2970]
It is suppose to reduce by 165 resists yet people are still able to resist deathcoil, fear, pet seduce etc. It seems strange knowing that they shouldnt be able to RESIST my spells.

**Comment by RazerStylehunter** [comment]
My guess is priest+druid , so Prayer of Shadow Protection + Mark of the Wild
That's: 130+54=184 resists  to shadow spell~

Just my guess.

**Comment by moonsado** [comment]
Hmm I really dont know since Ive only played this game for like9 months. Anyway well i have 103 spell penetration so 184-165=19-103 ??.

**Comment by Rushor** [comment]
works fine for me on ptr
