### ISSUE TITLE
Combat bug from NPCs fighting

### ISSUE THREAD

**Issue by michaelmarne** [dalaranwow/dalaran-wow#2974]
After getting into combat with monsters that are either fighting eachother, or a monster fighting a friendly NPC, the combat will not be cleared until you finish the fight. That is to say, being present when the fight finishes.
If you walk away from the fight, far enough for the combatants to "phase out" by being out of visual range you will be in combat indefinately (requires client restart or entering another zone(?)), no matter if the fight finishes out of your visual range. However, if you return to the fight after being stuck in combat and see that the fight has finished the combat is cleared immediately. 

Maybe it would be possible to clear the combat flag when you exit the visual range instead?

**Comment by Rushor** [comment]
> Maybe it would be possible to clear the combat flag when you exit the visual range instead?

yes this was fixed here https://github.com/TrinityCore/TrinityCore/pull/15538
