### ISSUE TITLE
Soul Siphon Not Working Properly

### ISSUE THREAD

**Issue by npmusicftw** [dalaranwow/dalaran-wow#2975]
Okay, I have just done some testing of my own on a target dummy. The testing I did was with no buffs or debuffs of any kind, just drain soul on a 100% target dummy, with 0-3 afflictions on the target. 

http://wotlk.openwow.com/spell=17805

Soul Siphon 1/2 and 2/2 should work as such: 

*Increases the amount drained by your Drain Life and Drain Soul spells by an additional 3/6% for each of your Affliction effects on the target, up to a maximum of 9/18% additional effect.*

This indicates that Drain Life and Drain Soul should have 4 different settings of damage based on this talent alone. 

Drain Soul with 0 Afflictions, 1, 2, and 3. 

I have tested on a dummy the damage that Drain Soul does with each amount of afflictions.

Drain Soul with **0** afflictions did **1622** damage per tick. 
Drain Soul with **1** affliction did **1714** damage per tick (a 5.672% increase).
Drain Soul with **2** afflictions did **1806** damage per tick (an 11.097% increase).
Drain Soul with **3** afflictions did **1806** damage per tick (an 11.097% increase). 

So, the activation of an additional 6% increase upon having a third affliction on the target is broken in regards to drain soul. Additionally, the % damage increase values are also incorrect. For DPS, .5% or 1% is still a lot. 

The correct values should be as follows.

Drain Soul with **0** afflictions does **1622** damage per tick. 
Drain Soul with **1** affliction *should do* **1719** damage per tick (a 5.672% increase).
Drain Soul with **2** afflictions *should do* **1817** damage per tick (an 11.097% increase).
Drain Soul with **3** afflictions *should do* **1914** damage per tick (an 11.097% increase). 

Now, it may not seem like a significant difference, but lets (theoretically) put it in a raid scenario.

First, let's say it's in the execute phase (the only time we would use it on a boss). 
* We'll have Haunt applied, so it will be doing 23% extra damage.
* We'll have the 12% increase shadow damage on targets below 35% health from the Death's Embrace talent.
* We'll have 15% additional shadow damage-over-time from the Shadow Embrace talent.
* We may have 13% increased magic damage taken from another lock, balance druid, or UH death knight. 
* And we'll have the 400% increased damage for the target being below 25%. 

So in present scenario, we have 1806(1.23)(1.12)(1.15)(1.13)(4) = 12932.3 damage per tick.

In the properly executed scenario, it would be 1914(1.23)(1.12)(1.15)(1.13)(4) = 13706.7

773.4 damage difference, *per tick,* of Drain Soul, from how it is now versus how it should be. That doesn't include other buffs to damage, such as additional spell power, or other % damage based buffs. Because the nature of Drain Soul's damage is multiplicative, and small amount of base damage that is incorrect can magnify into a very large amount of damage missing. 

Please fix!

Also, it doesn't recognize Curse of Elements as an affliction spell, when it is, indeed, an affliction spell. 

Must recognize CoE.

**Comment by npmusicftw** [comment]
I am aware of post 
#1574
That post, however, is incorrect, so I made this one. If this should just be added to that post, I can do that as well.

**Comment by npmusicftw** [comment]
update: It seems to work upon first application, but once a DoT falls off (not sure which one) it resets to the 12% rather than the 18% and will not correct itself.

**Comment by npmusicftw** [comment]
update: it appears to be Corruption that is bugging it. When the corruption debuff runs out of its original duration, it only reads it as having two afflictions on the target. 

To elucidate that, when Corruption is reapplied from Shadow Bolt, Drain Soul, Drain Life, or Haunt, the duration of Corruption is reset, and it rechecks the SP and haste of the caster and applies it to the Corruption. 

However, Drain Soul seems to only read the original duration of the first applied corruption. Once that original timer has passed its time, Corruption is no longer on the target (according to Drain Soul) even though it was actually just reset. 

The only way to truly reset this so that drain soul will do the proper damage is to leave combat, but it will just repeat the same process. Letting Corruption fall off and reapplying it does not fix the issue. 

I *think* that this is the cause of it.

**Comment by PolarCookie** [comment]
This talent counts drain soul itself as one of the affliction effects, this is why you're getting the weird % increases.
If this is bugged I don't know, but the damage increase is not.

drain soul 0/2 soul siphon 1102 damage
drain soul 2/2 soul siphon 1168 damage (6%)
drain soul 2/2 soul siphon 1 afflictions 1234 damage (12%)
drain soul 2/2 soul siphon 2 afflictions 1300 damage (18%)

as for corruption, haven't tested that part

**Comment by npmusicftw** [comment]
Oh, interesting. I never thought about it that way. The talent considers Drain Soul or Drain Life to be one of the factors... I don't even know if that's a bug. 

On the other hand though, the % increases do seem slightly incorrect, nonetheless. Not a true 6% increase each time (at least not during my testing). In fact, looking at the numbers you gave me... 

drain soul 0/2 soul siphon 1102 damage 
drain soul 2/2 soul siphon 1168 damage (6%) **(5.65%)**
drain soul 2/2 soul siphon 1 afflictions 1234 damage (12%) **(10.69%)**
drain soul 2/2 soul siphon 2 afflictions 1300 damage (18%) **(15.23%)**

**Comment by npmusicftw** [comment]
Update: Indeed, that makes a lot of sense. So the % damage values are spot on, it's just that the drain soul itself counts as an affliction spell. That makes more sense. Thank you. I'll now close this post.

**Comment by MrAndersonX** [comment]
Yeah, the talent works fine 1/2 but 2/2 I don't see the extra 9% health increase is it is indeed working properly and 1/2 it does 9% health drain increase for 2 curses + 1 drain.
