### ISSUE TITLE
Bloody strike talent bugged

### ISSUE THREAD

**Issue by elunes** [dalaranwow/dalaran-wow#2976]
Bloody strike talent should increase heart strike dmg with 45% it do with only 22,5%

**Comment by ciccioriccio** [comment]
i've just tested it,and its not true, here the proof: http://imgur.com/MJZbtup
the HS critical dmg have to be 100%dmg(non crit dmg) + 100%(critical dmg)= 200%, 
appling the talent http://wotlk.openwow.com/spell=49534 we have 100%+145%= 245%
it means that if u have 2000 normal dmg, you will have about 4900 critical dmg

**Comment by Golganeth** [comment]
Thanks @ciccioriccio, I've looked into it too and it seems to work just fine. Closing up
