### ISSUE TITLE
Deeprun Tram

### ISSUE THREAD

**Issue by haseo-the-scion** [dalaranwow/dalaran-wow#2977]
I was going to Ironforge and for some bizarre reason, there is a zeppelin stuck in the other end.
![wowscrnshot_103015_011405](https://cloud.githubusercontent.com/assets/13204848/10839714/9b9d4faa-7ead-11e5-8cf1-02c6f864a26d.jpg)

**Comment by benowy** [comment]
yeh i have had that before but with the stormwind boat during a for the horde raid, but for some reason i was the only person able to see it.

**Comment by MalkaviaDW** [comment]
It is a client visual glitch, with a simple relog will disappear.

**Comment by Rushor** [comment]
any source that this issue was also there in retail?
