### ISSUE TITLE
Quest: Dark Horizon

### ISSUE THREAD

**Issue by Taffa2** [dalaranwow/dalaran-wow#2978]
Quest: Dark Horizon (12664)
http://www.wowhead.com/quest=12664/dark-horizon

Issue present:

When you talk to Gorebag (ID:28666) he summons a Flying Fiend but you do not go with it on the tour.

How does it work currently:

When you talk to Gorebag (ID:28666) he summons a Flying Fiend but you do not go with it on the tour.

How it should work:

After you talk with Gorebag (ID:28666) he summons a Flying Fiend.  The Flying Fiend should then grab you and take you on a flying tour of Zul'Drak.  The flight should take about 4 minutes.

Video of how it should work: https://www.youtube.com/watch?v=nFGXj8Kq6xE (starting at the 50 second mark)

Comments: I've read through the Wowhead postings on this quest.  Some mention that you have to stand right on Gorebag to get this to work.  I've stood on this location and all around him, no luck in getting the quest to work.

On the Github interface I do not see an option to add a label, but the labels Northrend and Quest should be added.

**Comment by Taffa2** [comment]
Talked with a friend that was online.  He was able to get the tour to start and to get the quest.

After you talk to Gorebag you don't automatically get on the Flying Fiend (that's still a bug).  But for a fraction of a second when the Flying Fiend spawn's the icon changes to a gear when your cursor is over the Flying Fiend.  So if you spam right click over the Flying Fiend after talking with Gorebag you can get mounted up.  It took about 20 tries.

**Comment by swiftdeath** [comment]
Relogging also fixes it, it did for me atleast

**Comment by Rushor** [comment]
maybe you need to dismount first in order to get mounted on the Flying Fiend?

**Comment by Rushor** [comment]
http://i.imgur.com/IuNPIf2.jpg everything works fine for me. once you clicked on the gossip option you will the mounted on the Flying Fiend and it will start the tour
