### ISSUE TITLE
Paladin: Judgement of Wisdom

### ISSUE THREAD

**Issue by Oceres** [dalaranwow/dalaran-wow#2979]
Hello, 

Yesterday on our raid we expirienced an issue on JoW. It clearly states that all attacks should proc it and grant mana but so far only attacks that can proc it is physical attacks. So in example only our Hunter and me got mana out from it. Looking at recount none of our caster classes ie mage, shadow priest, elemental shaman or moonkin druid got any mana out from it.

**Comment by Rushor** [comment]
source:

Noch ein Beleg für den Manareg auf Offensivzauber: [[http://wowforum.gamona.de/klassenforen-13/ordenshaus-der-paladine-17/aenderung-am-richturteil-der-weisheit-108215.html]] (Anlass des Foreneintrags waren die Änderungen am Richturteil mit Patch 3.0.8)

Noch ein Beleg für den Manareg auf Offensivzauber: [[http://wowforum.gamona.de/klassenforen-13/ordenshaus-der-paladine-17/aenderung-am-richturteil-der-weisheit-108215.html]] (Anlass des Foreneintrags waren die Änderungen am Richturteil mit Patch 3.0.8)

RAWR 2.3.22/2.3.23 (die Versionen für Patch 3.3.5a) gibt für Zauber 24% des Grundmanas pro Minute an. Das Richturteil müsste folglich mindestens 12 mal pro Minute (2% des Grundmanas pro Procc) proccen, denn Rawr rechnet den Managewinn als Minimum ein, sonst passt die ganze Berechnung nicht.

die PPM werden auch für Zauber genutzt, dabei wird die Castzeit der Zauber (anscheinend durch Tempo modifiziert) genutzt, um die Prozentchance zu berechnen. Die Castzeit des Zaubers ist dann sozusagen das Waffentempo, und Instants zählen als 1,5 bzw Tempo modifiziert niedriger als das.

http://forums.elitistjerks.com/index.php?showtopic=44321

scorch @ 1.42s
142 attacks, 49 ticks
Judgement 7s cd
30 attacks, 11 ticks
Wow Web Stats

fireball @ 3.3s
133 attacks, 112 ticks
Judgement 7s cd
50 attacks, 23 ticks
Wow Web Stats

1,42 Sekunden

49/142=0,3450704225352112676056338028169

34% PPC

0,345*60/1,42=14,577464788732394366197183098592PPM

3.3s
133 attacks, 112 ticks

0,8421*60/3,3=15,31PPM

Grade hab ich bei Exorzismus ne Proccchance von 75%

Das ist 0,75*60/1,5=30 Also circa das doppelte. Wodurch die 100% erklärt werden, wenn man Casts mit mehr als 2 Sekunden Castzeit benutzt.







so the ppmchance must be splitted from the Cooldown handling in spell_proc_event

**Comment by Golganeth** [comment]
The part where it should proc from spells works now, but there doesn't seem to be any kind of internal cooldown and it has 100% proc chance.
For the total duration of 1 Judgement (19-20 secs) I could cast around 10-11 Ice Lances on a mage and get a proc for each one of them.

Shouldn't have 100% proc chance and a internal cooldown of (according to sources) 15 ppm.

**Comment by Rushor** [comment]
well i hope robinsch can translate the sources from above for your team - basically blizz invented some kind of cooldown handling AND ppmhandling for the same proc at the same time. currently you can either have ppmchance or cooldown handling in trinitycore - not both :)

**Comment by Golganeth** [comment]
Should be alright as long as some kind of internal cooldown / proc chance reduction is implemented. Right now it's crazy.

**Comment by robinsch** [comment]
Fixed according to Rushors comment
