### ISSUE TITLE
[Quest] How To Win Friends And Influence Enemies

### ISSUE THREAD

**Issue by Sagrath** [dalaranwow/dalaran-wow#298]
http://www.wowhead.com/quest=12720
When "persuadeing" the Scarlet Crusade into talking,  the dialogue is correct, however, it is supposed to come out as you are attacking, not only when one NPC surrenders

**Comment by Rushor** [comment]
https://github.com/TrinityCore/TrinityCore/issues/15001

This quest has worked for a long time. Make sure you do the quest properly:

    - Open the Ornately Jeweled Box (http://www.wowhead.com/item=39418/ornately-jeweled-box)
    - Equip 2x Keleseth's Persuader (http://www.wowhead.com/item=39371/keleseths-persuader)
    - Use only auto-attack and not spells like like Icy Touch and Death Coil (they don't count as strikes)
    -  Preferably attack only 1 single NPC mob, like one of the Scarlet chaplain/priest/dean NPCs.
    - Make sure you don't use a Risen Ghoul, stay away from any scourge NPC who can attack your target

Read http://www.wowhead.com/quest=12720/how-to-win-friends-and-influence-enemies#comments
for more tips on how to avoid problems while trying to do this quest.

as tkrokli said, i cannot find any problems here
