### ISSUE TITLE
Magma Totem Kills Dalaran NPCs

### ISSUE THREAD

**Issue by krusokat** [dalaranwow/dalaran-wow#2980]
I've noticed that it's possible to kill various npc by placing Magma Totem next to them, they will then take one tick of damage, and then proceed to kill it.

Their health is not reset either, they seem to stay at that hp for a while after taking damage.

Fire Nova doesn't do any damage to them tho.

This probably needs to be fixed pretty quick since it has big griefing potential.

This bug noticely works well in the Magus Commerce Exchange in Dalaran, on pretty much all the npcs, but there is probably more.

**Comment by Lothloryen** [comment]
Hello there,

This should be solved already.

Thank you very much.
