### ISSUE TITLE
[Priest] Mind Flay sometimes fails to tick a third time

### ISSUE THREAD

**Issue by Horvic** [dalaranwow/dalaran-wow#2983]
Mind Flay should always tick three times unless something causes spell push back.

To reproduce:
Repeatedly Mind Flay a target that isn't hitting you whilst monitoring ticks per cast.
Eventually the third tick won't go off. Occurs roughly every ten casts but can be less/more frequent.

Haste doesn't seem make any difference, tested at both 640 and 0 same issue.
The type of mob also doesn't seem to make a difference (tested on targets other than dummy).

Video of bug: https://youtu.be/CqcxgRPufWI
Eleven casts, total ticks should be 33 but only 32 ticks actually went off.

**Comment by robinsch** [comment]
On PTR.

**Comment by TeridanDW** [comment]
Hello, after few tests on PTR the result is:

> Mind Flay should always tick three times unless something causes spell push back.

is still an issue.
Now **every second tick** is been skipped.

![image](https://user-images.githubusercontent.com/6797611/31878590-42d864ba-b7e3-11e7-92d8-e90c95a6391e.png)

Short video demonstration:
https://www.youtube.com/watch?v=XXReGSwj5nI&feature=youtu.be

**Comment by robinsch** [comment]
@TeridanDW I can't confirm it on current PTR. Mind Flay ticks just fine.

**Comment by TeridanDW** [comment]
I also can't reproduce it anymore, some commit in the last 9 days must of fixed it.
