### ISSUE TITLE
Donation points refund

### ISSUE THREAD

**Issue by benowy** [dalaranwow/dalaran-wow#2985]
Greetings from Benow

A couple of months ago i donated a lot to this server as it has treated me well, however there was an issue with a few items buying duplicates including: 2 t3 warrior helmets, 2 goblin weather machines, and 4 talismans of the binding, which of course having more than one of any of these is useless to me and are just taking up bank space. a bit after that issue i accidentally bought a second swift spectral tiger which i would like if possible to be refunded as well if at all possible. I have opened tickets, sent emails in the past but in the end i gave up, however now i am trying again as there are more items i would like to get with these vote points instead of having the duplicates which don't benefit me in any way and are just taking up room which could be used for other things. i really hope that these can be refunded as it has been a couple of months now and i never received a response on my email however i read the forum terms of conduct and it told me to come to the bug tracker (which i didn't know existed at the time)  for donation point refunds, so well here i am. All of the duplicates are in the top row of the bank as show here with the screenshot:
http://i.imgur.com/SVlw9B6.jpg
i know i cant really show all of the items however a gm can come and see that i have the duplicates and none are of course fake. and you can log in my purchase history to see these as well. if you require any other information please let me know.

Thank you for reading
Benow

**Comment by Golganeth** [comment]
Invalid report. The bug tracker only lists in-game issues with quests, NPCs and such.
