### ISSUE TITLE
DONATE

### ISSUE THREAD

**Issue by Donsanchezzz** [dalaranwow/dalaran-wow#2986]
Dear Team,

I donated, the money is issued from my card but i didnt get my points. I donated alrady weeks ago and it worked, but now it didnt.

Please help
accname: Sanchez
char: Rozoga@Algalon

**Comment by Golganeth** [comment]
Invalid report. The bug tracker only lists in-game issues with quests, NPCs and such.
Send an e-mail to dalaran.community@gmail.com if you didn't yet.
