### ISSUE TITLE
[warlock][pet] felhunter stats

### ISSUE THREAD

**Issue by PolarCookie** [dalaranwow/dalaran-wow#2988]
there has been reported issues regarding felguard stats and scaling, I don't see anything similar for the poor felhunter who is in a similar situation.
I am only discussing base stats in this issue, not scaling or anything like that

on a naked gnome 80 warlock, the felhunter has the following stats

| stat | value |
| --- | --- |
| str | 179 (minor nitpick: ap increase tooltip is showing x1 scaling when it should be x2) |
| agi | 133 |
| sta | 329 + 72 (when my own stamina tooltip says it should be +28) |
| int | 162 + 53 (correct with my int tooltip) |
| spi | 142 |
| ap | 338 |
| damage | 108-149 |
| armor | 6323 |
| health | 4417 |
| mana | 6246 |

these stats are wrong, especially the final damage which is rougly 1/3 of what it should be

source 1:
the str value is mentioned in the trinity core, issue was closed in 2011
https://github.com/TrinityCore/TrinityCore/issues/2647

source 2:
The trinity core referenced wowwiki, but that particular page has been edited into a redirect
use this link to get the old page
http://wowwiki.wikia.com/wiki/Felhunter?oldid=2714647

source 3:
simcraft for 3.3.5 in file engine/sc_warlock.cpp
https://code.google.com/p/simulationcraft/downloads/detail?name=simc-335-1-win32.zip&can=4&q=

**what the felhunter stats should look like**
unless stated otherwise, both source 2 and 3 agree on the same numbers

| stat | value |
| --- | --- |
| str | 314 |
| agi | 90 |
| sta | 328 |
| int | 150 |
| spi | 209 |
| ap | 608 |
| damage | simcraft says base 309.6-309.6, wowwiki says 333-466 after ap scaling |
| armor | 7782 (only wowwiki gives a number on this) |
| health | 4788 (only simcraft gives a number on this, this is base health before sta) |
| mana | 1559 (only simcraft gives a number on this, this is base mana before int) |

**about the damage**
if base damage is 309.6, then average is 309.6 + 608*2/14 =396,46.
The average of wowwiki is 399,5, so it's pretty close.
This is 198.23 dps, compared to my felhunter's 64.1 dps this is a 134.13 dps difference which equals 1877.72 ap.
Fully geared (4.6k gs, 2899sp), my felhunter has 1900ap and 344-385 damage.
You need ulduar25 gear to get your felhunter back to where he was supposed to start!

**about health**
the felhunter stamina scaling is 9.5 health per stamina
4788 + 328*9.5 = 7904 (not counting the bonus pet stamina from my own stamina)

**about mana**
the felhunter mana scaling is 11.55 per intellect
1559 + 150*11.55 = 3291,5 (not counting the bonus pet intellect from my own intellect)

**conclusion**
the felhunter as is has to low health, to low armor, far to low damage, and much to high mana

**Comment by superchan94** [comment]
same on succubus

**Comment by PolarCookie** [comment]
DB fix using the latest trinity core:

UPDATE world.pet_levelstats
SET hp=4788,mana=1559,armor=7782,str=314,agi=90,sta=328,inte=150,spi=209
WHERE level=80 and creature_entry=417;

while I'm at it, here's for felguard

UPDATE world.pet_levelstats
SET hp=1627,mana=3331,armor=14033,str=314,agi=90,sta=328,inte=150,spi=209
WHERE level=80 and creature_entry=17252;

**Comment by PolarCookie** [comment]
Now for weapon damage it's a bit more.
As I've understood it, there used to be a min/max damage column on the creature_template table but it was removed in favour of having pets wear items.
Table creature_template connects to item_template via creature_equip_template.
The felguard has an entry in creature_equip_template but this references an item that does not exist (id 22199)
So let's add it.

INSERT INTO  world.item_template (entry, name, dmg_min1, dmg_max1, dmg_type1)
VALUES (22199, "Felguard Axe", 329, 495, 0)

Felhunter doesn't have any entries in either tables.
Highest item entry was 56806, so just to be safe...

INSERT INTO  world.item_template (name, dmg_min1, dmg_max1, dmg_type1)
VALUES (156806, "Felhunter Teeth", 310, 310, 0)

INSERT INTO world.creature_equip_template (CreatureID, ItemID1)
VALUES (417, 156806)

give a shout if pets use a different system, or any comments about the numbers.


I've tested these on a database, but not a test server yet.

**Comment by PolarCookie** [comment]
if any hunters has a good source on pet damage, can fix yours too if you help me out.

**Comment by Rushor** [comment]
DB/Pet: Warlock - Update basestats for Felhunter, felguard and succubus

* closes https://github.com/dalaranwow/dalaran-wow/issues/2988
* this only changes the basestats, basedamage was fixed in https://github.com/dalaranwow/dalaran-wow/issues/3237
* commit: 2e97b624ca882378f97134cb5f434d3464366cd7

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
