### ISSUE TITLE
Can't download the patches

### ISSUE THREAD

**Issue by Roflpopz** [dalaranwow/dalaran-wow#2989]
Hi. I can't seem to download the patches which you refer to. All the mirrors are broke from the wiki site.

**Comment by Golganeth** [comment]
Invalid report. The bug tracker only lists in-game issues with quests, NPCs and such.

**Comment by Roflpopz** [comment]
That's also a problem. I can't post a message in the forum, 'cause I haven't created a character in the game. Which I can't do 'cause I can't patch the game. See where I am getting at?
