### ISSUE TITLE
NPC/Quest: Spinebreaker Post

### ISSUE THREAD

**Issue by Aldergar** [dalaranwow/dalaran-wow#299]
The quest tell you to speak to Wing Commander Brack to take a flight to Spinebreaker Post,but the NPC doesn't give you any free flight,and for player that are currently without mounts is annoying reaching the Spinebreaker Post with a normal level 40 mount.

**Comment by Demlock** [comment]
Confirmed

**Comment by Rushor** [comment]
fixed long time ago https://github.com/TrinityCore/TrinityCore/blob/a56a402190c885e51038df55654875cc9e875c03/sql/old/3.3.5a/TDB40_to_TDB41_updates/world/2011_06_17_18_world_misc.sql
