### ISSUE TITLE
triumph emblem farming

### ISSUE THREAD

**Issue by mavol6** [dalaranwow/dalaran-wow#2991]
since the release of toc, ive seen people farming hall of stone heroic for the purpose to get triumph emblems. They do this by entering the dungeon and going straight to brann event, finishing it and looting the chest, this wont save the group to the dungeon and awarding 1 triumph emblem.

**Comment by PolarCookie** [comment]
While the dev's on it, you can also get triumph from CoS (dragon boss), nexus (first boss), oculus (last boss chest), UK (last boss) and archavon on both 10 and 25.

**Comment by Johanes022** [comment]
After fix deleting Emblems of Triumph again wouldnt impact players who obtained them trough ToC(if there are any) considering that there arent 5 or 10 players who did this "farming" but many, and there will be many more after reading this report.Afterall ToC was released 2 days ago and abusing Halls of Stone as mavol6 mentioned can award players 5 Triumph emblems / hour.

**Comment by Lothloryen** [comment]
Hello there,

The issue was corrected already, any feedback will be welcome.

Thank you.

**Comment by Johanes022** [comment]
Archavon and Emalon in VoA 10 and 25 still drop 2x Emblem of Triumph
