### ISSUE TITLE
[Warlock] Infernal Summon 

### ISSUE THREAD

**Issue by moonsado** [dalaranwow/dalaran-wow#2992]
There is a problem with the tooltip information provided to summon infernal it says its a 1.25 second cast with haste.
http://s9.postimg.org/wth82fycv/Wow_2015_11_08_17_57_57.png

And here is the reality of things; 1.5 second cast
http://postimg.org/image/rxt92wtev/

So bascailly the information that is given by the tooltip doesn't correspond to the casting time I am really doing......

**Comment by Lukas45** [comment]
How about we get it fixed so it's actually usable first? Or at least worth using

**Comment by Rushor** [comment]
clientside issue (like any other tooltipupdate), currently there is no option to fix this
