### ISSUE TITLE
[Druid] [Mage] Lifebloom doesn't bloom when removed by spellsteal

### ISSUE THREAD

**Issue by Illiyara** [dalaranwow/dalaran-wow#2996]
The druid spell lifebloom blooms when dispelled. Currently in Dalaran wow, using spellsteal on lifebloom doesn't trigger the bloom effect. Additionally, when it blooms on the mage, the druid gets the mana back.

What should happen is, Spellsteal triggers the bloom effect, healing the druid and restoring its mana and transferring the lifebloom buff to the mage. It then expires and blooms again, healing and restoring mana to the mage. 

The spell blooming upon steal can be seen around 1:10 in this video: https://www.youtube.com/watch?v=fbeJKiW_N5U
At 1:11, the mage steals lifebloom, which heals the druid for 4912. This is the part that isn't working atm.

**Comment by mnbdru** [comment]
I'm not 100% sure about this, but Lifebloom steal should grant only mana to you, and heal to the mage. Also your proof video is from Cata 4.3. Proof is not valid in Wotlk 3.3.5.

http://www.wowhead.com/forums&topic=166347/dispels-vs-resto

**Comment by Illiyara** [comment]
I'm quite sure that spellsteal counts as a dispel for all intents regarding the target spell, including lifebloom interactions. Dispel resistance also applies to it. If it passes a dispel check, it dispels the effect from the target and applies it to the mage. This is from experience, as with for the Owlkin Frenzy post. This one is much harder to find solid video evidence for, and although the details of lifebloom have worked differently from tbc to cata (cheap with no stacking blooms -> doubled cost and stacking blooms, with mana back on bloom --> no mana back, reduced cost, 1 target limitation), spellsteal and dispel have always worked the same way regarding blooms.

 Butt I'll do my best to find a wotlk video.

**Comment by mnbdru** [comment]
You are right, spellsteal counts as a dispell.
http://wowwiki.wikia.com/wiki/List_of_magic_effects
"Lifebloom can be stolen to give you a heal over time. This will, however, proc the lifebloom-on-dispel mechanic."

**Comment by doppin** [comment]
Any update? This combined with the newly discoreved 25-50% healcut bug is devastating.

**Comment by robinsch** [comment]
That was quite complicated.
