### ISSUE TITLE
[Druid] Owlkin Frenzy is removed when leaving moonkin form.

### ISSUE THREAD

**Issue by Illiyara** [dalaranwow/dalaran-wow#2997]
Owlkin Frenzy can only trigger when in moonkin form, but the buff should remain until expiring, regardless of form. Currently, the Owlkin Frenzy buff only lasts while in moonkin form, making it much less useful for pvp. 

Edit:
Here's one filmed in wotlk, season 5, posted 2009.
https://www.youtube.com/watch?v=zpgOvqP_470
0:48, Owlkin Frenzy is triggered, 0:53 he shifts out to heal, Owlkin is still on.
It happens again at 1:49, 2:10, 5:04, 6:55, 7:32. 

The first I posted was from Cata:
https://www.youtube.com/watch?v=fbeJKiW_N5U
at 1:10, owlkin frenzy is triggered. The druid shifts in and out without losing the buff. It's triggered again around 1:25, and again he shifts without losing it.

**Comment by mnbdru** [comment]
The video is from cata 4.3, wheres Owl Frenzy is a passive stat.In Wotlk 3.3.5 it's a talent, and you should loose it after shifting from Moonkin Form. It works as it should.

**Comment by Illiyara** [comment]
Sorry, I was going mainly off my memory, and what I thought would be common sense based on the tooltip wording. OKF wasn't changed in functionality from wotlk to Cata.
Here's one filmed in wotlk, season 5, posted 2009.
https://www.youtube.com/watch?v=zpgOvqP_470
0:48, Owlkin Frenzy is triggered, 0:53 he shifts out to heal, Owlkin is still on.
It happens again at 1:49, 2:10, 5:04, 6:55, 7:32. 
So it is currently bugged on Dalaran. Hope that clears all doubt.

**Comment by mnbdru** [comment]
Can't find any better info regarding Owlkin Frenzy. 
http://wowwiki.wikia.com/wiki/Owlkin_Frenzy
Latest patch change 3.2.0 so i assume its legit. "Note that the effect only applies while in [Moonkin Form]."

**Comment by Rushor** [comment]
case 48391: // Owlkin Frenzy
                spellInfo->Stances = 0;
                break;

this fixed the issue

**Comment by Illiyara** [comment]
mndru, that owlkin frenzy wiki page is about the passive ability/talent (chance to proc). 
"Note that the effect only applies while in [Moonkin Form]" refers only to that proc chance, not the buff itself. If you look down you'll see the related effect, Owlkin Frenzy (the buff itself) is something different. I'd agree that it was poorly worded. 

In any case, I have linked dated videos from both wotlk and cata showing that the owlkin frenzy *buff* should not be removed when one shifts out. All the videos I've seen from wotlk show that the buff doesn't fade. I think that is more definitive than any wiki page or comment, which can be edited.

**Comment by Rushor** [comment]
I think that is more definitive than any wiki page or comment, which can be edited.

wikipages have a history which cannot be deleted. you also get the nessessary infoamtions there

**Comment by Illiyara** [comment]
True, they have a history, but often are not clear on precise mechanics and sometimes are quite ambiguous, as anyone can change them. WoW tooltips themselves can't remove all doubt, and people writing on the wiki can be inaccurate or word things poorly. For a fairly obscure area like a balance druid pvp talent, the wiki article isn't vetted so thoroughly, and these issues can persist. So you can get information, but it's not the "ultimate authority" if one can see the effects in videos.
