### ISSUE TITLE
Minions: Scarlet Ghouls

### ISSUE THREAD

**Issue by Sagrath** [dalaranwow/dalaran-wow#300]
http://www.wowhead.com/npc=28845
Not acting Hostile with Scarlet cusade members only with the Ghosts spawning from the miners, also the damage they do aprox 3-6 is to low, it should be around 50
Scarlet Ghouls are criteria of the quest - The Gift That Keeps On Giving
http://www.wowhead.com/quest=12698

**Comment by Rushor** [comment]
33259682811c58399947ba5704dcb31526212258
- the ghouls will also attack other hostile creatures
- added spawnanimation for the Gift of the Harvester gameobject
- increased damage for the ghouls

**Comment by Golganeth** [comment]
When the miners are turned into ghouls, they keep their mining pick.

> Minor visual issue
