### ISSUE TITLE
[ToC raid] - Acidmaw hitbox

### ISSUE THREAD

**Issue by ashido96** [dalaranwow/dalaran-wow#3001]
Acidmaw's hitbox is small enough that it forces all the melee to stand basically in the hitbox. This creates a large artificial difficulty in that all of the melee will get burning bile while being unable to spread out as they would be able to if they were damaging dreadscale.

Dreadscale has the correctly sized hitbox.

**Comment by LoveDalaranWow** [comment]
It's not only Acidmaw's one, it's the moving worm that has an insanely small hitbox, the stationary worm's hitbox is fine.

**Comment by ashido96** [comment]
As ignis' hitbox got fixed yesterday figured I would come back and check on this one. #3523 
Much appreciated if this could get looked at.
Note: the above comment is incorrect, dreadscale while mobile maintains the same hitbox as when he was stationary, I'm not familiar with acidmaw's hit box as I hardly ever tank him.

**Comment by Lothloryen** [comment]
Hello there,

Thank you for the report, this correction shall be on the live server after the next maintenance.
