### ISSUE TITLE
[Quest] Gerenzo's Orders

### ISSUE THREAD

**Issue by turtleblastoise** [dalaranwow/dalaran-wow#3002]
A quest in Stonetalon Mountains:
http://www.wowhead.com/quest=1090/gerenzos-orders
Nothing happens when you begin the quest. Waves of kobolds are suppose to attack you while you defend Piznik (the questgiver), but nothing happens. Shouldn't quests like these autocomplete?

**Comment by Golganeth** [comment]
Duplicated; #590
