### ISSUE TITLE
[NPC] Borean Tundra - 'Karen "I Dont't Caribou" the Culler'

### ISSUE THREAD

**Issue by RealZwox** [dalaranwow/dalaran-wow#3005]
The Path of 'Karen "I Dont't Caribou" the Culler' is totaly bugy when you pull her infront

**Comment by Golganeth** [comment]
The NPC is lacking SAI and, doesn't eat the caribous around.
The NPC doesn't have any stealthed guard around

> Can be found at 57,56 with several (2 or 3) stealthed guards. She has a special whirlwind attack that does approximately 300 damage on leather.

> pulled her guards while she was eating a deer and she didnt agro

http://www.wowhead.com/npc=25803/karen-i-dont-caribou-the-culler#comments

**Comment by Golganeth** [comment]
The NPC is lacking SAI - doesn't eat the caribous around.
The NPC doesn't have any stealthed guards close to it.

> Can be found at 57,56 with several (2 or 3) stealthed guards. She has a special whirlwind attack that does approximately 300 damage on leather.

> pulled her guards while she was eating a deer and she didnt agro

http://www.wowhead.com/npc=25803/karen-i-dont-caribou-the-culler#comments

**Comment by Golganeth** [comment]
The NPC is lacking SAI - doesn't eat the caribous around.
The NPC doesn't seem to have any stealthed guards close to it.

> Can be found at 57,56 with several (2 or 3) stealthed guards. She has a special whirlwind attack that does approximately 300 damage on leather.

> pulled her guards while she was eating a deer and she didnt agro

http://www.wowhead.com/npc=25803/karen-i-dont-caribou-the-culler#comments

**Comment by Golganeth** [comment]
The guards don't reenter stealth once they evade or respawn.
Karen isn't hostile to players, no matter how close you are or if you attack her. She won't target the players and just cast Whirlwind every now and then.
