### ISSUE TITLE
Object/Quest: The Eye of Archerus

### ISSUE THREAD

**Issue by Sagrath** [dalaranwow/dalaran-wow#301]
http://www.wowhead.com/quest=12636
The Eye of Archerus is controllable immediately. In retail, just as a minor detail, the eye automatically takes itself to the Scarlet area.

**Comment by Rushor** [comment]
fixed long time ago in https://github.com/TrinityCore/TrinityCore/commit/eccb0ed3dac67a7463cc5c1ff5cf2cd3919e7a25
