### ISSUE TITLE
[Quest] Blackfathom Deeps - Blackfathom Villainy (Horde)

### ISSUE THREAD

**Issue by turtleblastoise** [dalaranwow/dalaran-wow#3010]
Quest: http://db.vanillagaming.org/?quest=6561
Quest giver: http://db.vanillagaming.org/?npc=4787
The quest giver is suppose to be neutral to both Alliance and Horde. As of now, I'm not sure about how he reacts towards Alliance players, but he's definitely hostile to Horde players. Also, I believe he's suppose to be dead, but he attacked when I went near him (he doesn't have any animations, he just lays on the ground and does damage to you).

**Comment by Portotada** [comment]
Confirmed
