### ISSUE TITLE
[Item] Blue Pearls drop rate from Small Barnacled Clam

### ISSUE THREAD

**Issue by Alavarin** [dalaranwow/dalaran-wow#3013]
It drops more often than Clam Meat and is not susposed to be.

http://wotlk.openwow.com/item=4611

**Comment by swiftdeath** [comment]
Goes for all clams, they drop all kinds of clam meat, from clam meat to zesty clam meat.

I had the same issue with the pearls. 

Minor issue though, wont be adressed soon.

**Comment by Rushor** [comment]
UPDATE `spell_loot_template` SET `ChanceOrQuestChance`=1 WHERE `entry`=58172 AND `item`=4611;

**Comment by Rushor** [comment]
6cee79419e90d4b141f36bbd3d01201a090098ec
- reduced the dropchance for http://wotlk.openwow.com/item=4611 to 1% (according to wowhead/wowwikicomments)
