### ISSUE TITLE
Soul link bug

### ISSUE THREAD

**Issue by mondvrr** [dalaranwow/dalaran-wow#3016]
Soul Link:  When active, 20% of all damage taken by the caster is taken by your (all pets) or enslaved demon instead. that damage cannot be prevented. Lasts as long as the demon is active and controlled.

Here is the desciption of the skill in a screenshot: http://puu.sh/lEBDW/7652eb43f2.jpg

the problem is there is no buff on the character and it don't share the damage with the pet

Here i have no buff with my pet active : http://puu.sh/lEBsL/1a7df3a2b7.jpg

Here my pet is taking damage and you can see from my addon the damage taken: http://puu.sh/lEBvj/c9bf72479f.jpg

Here is my character taking damage but there is no damage on my pet: http://puu.sh/lEBxT/fa6e1b9403.jpg

**Comment by Golganeth** [comment]
You have not even casted the spell on yourself. False report so closing up

**Comment by mondvrr** [comment]
lol... i think it was passive sorry im retard xD
