### ISSUE TITLE
[Hunter] T9 2 piece Serpent Sting Crit dmg wrong scaling?

### ISSUE THREAD

**Issue by RazerStylehunter** [dalaranwow/dalaran-wow#3017]
With the T9 2 piece bonus, hunter's serpent sting can now be critical strikes. After doing some reading, I noticed that the critical strike damage does not take into account our [Mortal Shots] ability which should increase the bonus damage of a critical strike by 30%

https://www.dropbox.com/s/oejaa66u3ry4mi7/1.png?dl=0    My serpent sting on a dummy without any raid buffs or procs, just with normal gear.

As you can see, the critical damage is roughly 206% percent of the normal tick, this is consistent with the meta gem bonus, 1526 = 741 \* 2 \* (1+0.03).

However, from patch notes, the hunters talent [Mortal Shot] should be able to affect this damage as we are on patch 3.3.5.
http://us.battle.net/wow/en/game/patch-notes/3-3-3
http://wowwiki.wikia.com/wiki/Serpent_Sting

Here I quote from the above link: 
"Mortal Shots: This talent was not correctly buffing Serpent Sting by the full amount." & "Hunter Tier-9 2-Piece Set Bonus: Critical damage from Serpent Sting will now work properly with the Mortal Shots and Expose Weakness talents."

Now since the talent only applies to the "BONUS damage" part (note the meta gem benefits the critical strike damage as whole) which is 206% - 100% = 106%, we should get a critical damage of  100% + 106% \* 1.3 = 237.8% of the normal tick, which should be about 1762.1 instead of 1526. 

This difference in damage will be much larger once considering raid buffs thus hunters in theory could be losing a few hundred DPS from this ~32% difference in damage scaling alone.

Similar issues have been reported elsewhere, link as follow:
https://github.com/TrinityCore/TrinityCore/issues/418
https://github.com/TrinityCore/TrinityCore/issues/15099

Not sure if the current 206% critical damage is working as intended or indeed a scaling issue. I am open to correction if I got any of the calculation wrong above or I missed something. 

Thanks for reading.

**Comment by Sigwastaken** [comment]
Tested today, can confirm the same results.

**Comment by Celfinnel** [comment]
I also got the same results.

**Comment by Winstrol** [comment]
Can confirm, please look into this.

**Comment by TeridanDW** [comment]
Works as intended on PTR.
