### ISSUE TITLE
Summoning lock pet

### ISSUE THREAD

**Issue by superchan94** [dalaranwow/dalaran-wow#3019]
Hi. when you already have 1 pet. and you resummon another one while this one is alive. a new pet doesn't appear. just the old one.

This also makes bug on spells in pet. if you for example use spell lock in a target. and you summon a pet with feldom. your new pet doesn't get spell lock reseted since it's the old pet you had...

let's put an example: in Arena a warrior is killing your pe and it's at 4k. you go with portal hiding and summoning a new pet. when you summon it your pet is at 4k hp  becaue it's the SAME. instead a new one.

Better explained: https://github.com/TrinityCore/TrinityCore/issues/12109

**Comment by Lukas45** [comment]
There is a small workaround.
It will be a new pet (At least it will have full HP/Mana, didn't check CDs) if you Dismiss the pet first.
You can make small macros for that, even though it may be clucky.
eg:
    #showtooltip
    /cast Summon Felhunter
    /stopmacro [nopet:Felhunter]
    /script PetDismiss()

**Comment by Golganeth** [comment]
#1539
