### ISSUE TITLE
Fear Bug

### ISSUE THREAD

**Issue by superchan94** [dalaranwow/dalaran-wow#3020]
As a lock. when you fear someone there are sometimes when you cannot attack him for the first  3-4 seconds. Target get "bugged" running to somewhere and suddenly he teleports to another place randomly. then you can attack him.

(I think this happends on priest aswell. these bugs are textures i think or idk whatever it's a bug)

**Comment by Lukas45** [comment]
It's a player pathing issue, it happens with every kind of fear. The feared player will always see it smoothly, but everyone else can see it fucked up.
It makes Yogg25 really fucking tough because of Melody of the Mind

**Comment by Golganeth** [comment]
#1447
