### ISSUE TITLE
In Game ASAP

### ISSUE THREAD

**Issue by iReapz** [dalaranwow/dalaran-wow#3021]
for what ever reason my charecter in game can not see whispers or guild chat or party chat, the only thing i can see is the chat bubbles if im close enough to the person i have not messed with any of the social setting in game so idk why this is a thing please get back to me asap

**Comment by Golganeth** [comment]
Invalid report. The bug tracker only lists in-game issues with quests, NPCs and such. It looks like it's an issue on your side so this shouldn't go to the bug tracker.
