### ISSUE TITLE
[Rivern Frostwind]  Cannot talk to him after faction change

### ISSUE THREAD

**Issue by alexsanderr5205** [dalaranwow/dalaran-wow#3022]
Hi, after faction change I can't speak with Rivern Frostwind in Winterspring he neutral but attackable for me. So can you give first quest for starting taking reputation with Wintersaber Trainers or make him non-attackable for me?

http://wotlk.openwow.com/npc=10618

**Comment by Rushor** [comment]
8bd6681283a9b3e120e8dbdfb2f497b2d67d7d8f
- you should now be able to talk to him even after a factionchange from horde to alliance

**Comment by alexsanderr5205** [comment]
Not fixed

2016-06-09 12:09 GMT+03:00 Rushor <notifications@github.com>:

**Comment by alexsanderr5205** [comment]
I can attack him, but can`t talk and give quest

2016-06-09 14:11 GMT+03:00 Александр Михеев <alexsanderr5205@gmail.com>:

**Comment by Rushor** [comment]
nono, this change is only on ptr - not yet on the liveserver

**Comment by Golganeth** [comment]
It's on the PTR for testing first, it will be deployed to the live realm in a few days. Make an in-game ticket in the meanwhile if you're having this issue.
