### ISSUE TITLE
Auction house

### ISSUE THREAD

**Issue by chaostod** [dalaranwow/dalaran-wow#3023]
Hi, I would like to know if it could be possible to have some help about my issue here with the auction house. The problem is, when i put stuff to sell, about 5g it actualy put it at 100g for exemple, when i put it for sell. Can I have help. thank you very much.

**Comment by RazerStylehunter** [comment]
Sounds to me like you are putting it on for 5g PER ITEM than per stack

5g * 20 = 100g

Makes a lot of sense to me

**Comment by swiftdeath** [comment]
^

**Comment by Golganeth** [comment]
Indeed. I'm going to close this up, make sure you've set up everything correctly.
