### ISSUE TITLE
[Hunter] Auto-atack bugged (must fix)

### ISSUE THREAD

**Issue by Scrmzzz** [dalaranwow/dalaran-wow#3025]
The hunter auto-attack is bugged . It stops attacking when the enemy goes away from u'r line of sight and it stayis like that. In order for you to hit again, you need to either target the ground and again on the enemy or you just need to change enemys or you need to deactivate and activate autoatack. That means dps loss in pve and pvp and in pvp it can lose you the game big time + its frustrating. You need to make it so that it stops atacking when the enemy goes away from LOS and starts atacking again when you see the enemy. This issue is a must fix in my opinion , as a hunter player and its funny , because I didn't see anyone report this problem...

**Comment by Golganeth** [comment]
#834
