### ISSUE TITLE
[Hunter] Scatter Shot

### ISSUE THREAD

**Issue by luledebule** [dalaranwow/dalaran-wow#3030]
The scatter shot visual is just wrong, my targets keep running forward or whatever the direction theyve been going for and it makes trapping really hard and frustrating as if it wasnt hard enough. The character itself is positioned where the scatter has been used but the visual is just false, I have to backtrack to where i scattered them and throw/lay a trap on that spot even tho theyve already gone 10 yards away from the initial spot. Please this is just groundbreaking for me and I imagine alot of players who do PvP here, to me personally hunter doesnt make sense without scatter combos. Ive already rolled 2 classes with pvp gamebreaking bugs and I beg you dont make me reroll a 3rd class.

**Comment by Rushor** [comment]
yeah i confirm this, this visual bug is really messy

**Comment by Beaastmodeon** [comment]
It is true , I have the same issue on my hunter , thats the reason why I am not playing arenas that much.

**Comment by Rushor** [comment]
please share the fix for it, and i will give you some hunter fixes from my server - let me know if you want something

**Comment by Winstrol** [comment]
Video displaying the issue:
https://www.youtube.com/watch?v=VDUshI-Ul9A

**Comment by Rushor** [comment]
even adding StopMoving() in unit.cpp in the apply of the confusedunitstate does not solve this issue

**Comment by Rushor** [comment]
aka this fix https://github.com/TrinityCore/TrinityCore/commit/3d644d8d119b9009f10ea637c52a01dad32708c9#commitcomment-14805734 no longer works

**Comment by Golganeth** [comment]
#1447

**Comment by Lothloryen** [comment]
Hello there,

Issue corrected #1630
