### ISSUE TITLE
Hacking detected!!!

### ISSUE THREAD

**Issue by exyz3** [dalaranwow/dalaran-wow#3031]
![wowscrnshot_120715_123751](https://cloud.githubusercontent.com/assets/16089992/11626389/9fb24502-9ce2-11e5-9d90-6da561759836.jpg)
![wowscrnshot_120715_124103](https://cloud.githubusercontent.com/assets/16089992/11626399/acca2994-9ce2-11e5-9a9d-a88771a6fdc1.jpg)

Player Zulreghina cought speed hacking through grizzly hills. I spoted him doing this when i was dead and waiting for respawn. When i did respawn he killed me and mount up like he wont be noticed doing again.
In "ss" you can see him "floating" in mid air. Soon after he touched the ground and immediately mount himself. So there wasnt any wierd lagg or bug that coused that.
![wowscrnshot_120715_123751](https://cloud.githubusercontent.com/assets/16089992/11626715/3d9ecdb0-9ce5-11e5-82f9-031563e63b34.jpg)
![wowscrnshot_120715_123743](https://cloud.githubusercontent.com/assets/16089992/11626720/446f8c42-9ce5-11e5-903a-1d8be0c4cf23.jpg)
![wowscrnshot_120715_124103](https://cloud.githubusercontent.com/assets/16089992/11626722/47745792-9ce5-11e5-841c-8a30db3572c3.jpg)

**Comment by exyz3** [comment]
![wowscrnshot_120715_123814](https://cloud.githubusercontent.com/assets/16089992/11626756/8b2186f4-9ce5-11e5-9412-b4fe26959088.jpg)
![Uploading WoWScrnShot_120715_123813.jpg…]()

**Comment by Golganeth** [comment]
Invalid report. The bug tracker only lists in-game issues with quests, NPCs and such. Please report players through an in-game ticket, make sure to add evidence/proof just like you did here. We'll verify the behavior and take care of it, if required. Thanks!
