### ISSUE TITLE
[Item][Trinket] Solace of the Fallen/Defeated bugged.

### ISSUE THREAD

**Issue by Almondswow** [dalaranwow/dalaran-wow#3033]
All 4 versions of this trinket are currently not applying the stacking buff properly with various spells; more specifically, instant cast heals and heal over time spells.

The buff is called "Energized" and the spell id is: 67750

When casting any of the spells listed below on a druid, the buff does not properly apply as it should:

- Rejuvenation
- Lifebloom
- Wild Growth
- Barkskin
- Abolish Poison
- Remove Curse
- Innervate
- Mark of the Wild
- Gift of the Wild

Please note that on top of this, the **over time** effects of any of the listed spells should also apply 1 stack of the "Energized" buff.

The functionality of the **Illustration of the Dragon** Soul trinket from *The Obsidian Sanctum 25* allows for all of the healing over time effects from the druid spells to properly apply a stack of the buff, here on the Dalaran - Algalon server.  If all versions of Solace of the Fallen and Solace of the Defeated copied the functionality of this trinket in regards to spells properly applying the buff, it would be more than acceptable and a great fix. As it currently stands, you must cast a spell that has a cast time or Swiftmend on a Resto Druid to get 1 stack of the buff. This is a huge problem for managing the buff and the stacks of the "Energized" buff.

There are a ton of comments on the wowhead links of each trinket below, regarding which spells should function properly for applying the buff.

The 4 versions of the trinket are:
[Horde] Solace of the Fallen - 245 item level: http://www.wowhead.com/item=47271/solace-of-the-fallen
[Horde] Solace of the Fallen - 258 item level: http://www.wowhead.com/item=47432/solace-of-the-fallen
[Alliance] Solace of the Defeated - 245 item level: http://www.wowhead.com/item=47041/solace-of-the-defeated
[Alliance] Solace of the Defeated - 258 item level: http://www.wowhead.com/item=47059/solace-of-the-defeated

**Comment by Dolmio1** [comment]
#1745

got fixed after 1 year or so after the release of sarth25, apply the same fix from illustration to solace and its done

**Comment by swiftdeath** [comment]
Better use wotlk.openwow.com links mate

Solace of the Fallen (horde) 245/258
http://wotlk.openwow.com/item=47271
http://wotlk.openwow.com/item=47432

Solace of the Defeated (alliance) 245/258
http://wotlk.openwow.com/item=47041
http://wotlk.openwow.com/item=47059

**Comment by Almondswow** [comment]
Any update on this?

**Comment by AgeAgainst** [comment]
I'm only adding to this since OP mentioned Abolish Poison/Remove Curse/Gift

It does not apply one stack of "Energized" buff when a holy paladin casts:

- Sacred Shield 
- Beacon of Light
- Any Blessing

From http://www.wowhead.com/item=47271/solace-of-the-fallen#comments:id=1073023
3.3.5
As a Paladin, I noticed it procs from blessings, too. So just rebless everyone before the pull, and *poof*, instant mp5. :)

**Comment by fsironman** [comment]
Easy DB fix:
https://github.com/TrinityCore/TrinityCore/issues/1896#issuecomment-156679924

-- Solace of the Defeated/Solace of the Fallen (Normal/Heroic) proc fix
DELETE FROM `spell_proc_event` WHERE `entry` IN (67698,67752);
INSERT INTO `spell_proc_event` (`entry`,`SchoolMask`,`SpellFamilyName`,`SpellFamilyMask0`,`SpellFamilyMask1`,`SpellFamilyMask2`,`procFlags`,`procEx`,`ppmRate`,`CustomChance`,`Cooldown`) VALUES
(67698, 0, 0, 0, 0, 0, 0, 65536, 0, 0, 0),
(67752, 0, 0, 0, 0, 0, 0, 65536, 0, 0, 0);

Tested with TDB 335.59

Do it just do it !

**Comment by fsironman** [comment]
![omg it works]
(http://i.imgur.com/RZUUMDA.jpg)

**Comment by Lothloryen** [comment]
Hello there,

Thank for the report and the suggested fix, Fsironman (quite funny character's name, hehe). I shall take a look.

**Comment by Almondswow** [comment]
Thanks for fixing this! Going to Close it!
