### ISSUE TITLE
[Item] Insane blue drop rate on raptors in Wetlands

### ISSUE THREAD

**Issue by Alavarin** [dalaranwow/dalaran-wow#3034]
I was killing raptors around Whelgar's Excavation Site for about half of hour and I've dropped 3 (!!!) Gargoyle's Bites and Yorgen Bracers. It definitely shouldn't work that way.

![1](https://cloud.githubusercontent.com/assets/16082894/11694897/d2b66e12-9eac-11e5-98e1-5a4d87edb918.png)
![2](https://cloud.githubusercontent.com/assets/16082894/11694899/d496c6e6-9eac-11e5-950a-267d37590f48.png)

**Comment by Aporis** [comment]
As far as i know, Blues dropping commonly everywhere except Northrend is currently an intentional feature, not a bug.

**Comment by Rushor** [comment]
The dropchance is around 0.04% for several creatures - cannot see an issue here
