### ISSUE TITLE
Death knight ghoul- any profit from dk haste

### ISSUE THREAD

**Issue by Volodo** [dalaranwow/dalaran-wow#3039]
http://wowwiki.wikia.com/wiki/Risen_Ghoul
Ghouls receive 100% of their master's haste

I tried it today and my ghoul doesnt profit from my haste. Always same attack speed. im not sure about gargoyle cast speed yet. Will test later.

**Comment by Johanes022** [comment]
https://github.com/dalaranwow/dalaran-wow/issues/2091
