### ISSUE TITLE
Blackrock Depths - The Ring of the Law

### ISSUE THREAD

**Issue by Takatifu** [dalaranwow/dalaran-wow#3041]
This boss encounter works fine for the most part except that the NPC dwarf that open the cages, High Justice Grimstone (http://www.wowhead.com/npc=10096/high-justice-grimstone), even though cannot be attacked, is hostile and will engage any party memeber in aggro range. Once he kills everyone in aggro range or no one is in it he resumes the script.
We managed to bypass the issue by not getting close, let him open the cages, and pull the mobs after he despawns. However, even though we finished the event and got to open the exit door, he returned as an invisible mob and killed all of us. We continued thanks to the Reincarnation spell of our healer but apparently it had despawn after killing us since a new party member passed through the arena unharmed.

**Comment by Golganeth** [comment]
#2444
