### ISSUE TITLE
Quest: Abjurist Belmara / Conjurer Luminrath / Cohlien Frostweaver / Battle-Mage Dathric

### ISSUE THREAD

**Issue by DrFuler** [dalaranwow/dalaran-wow#3043]
As of 17/12/15, the following quests are not working:

- Abjurist Belmara
- Conjurer Luminrath
- Cohlien Frostweaver
- Battle-Mage Dathric

All of them seems to have the same problem: when you use the specific item of each of the ghosts (on their proper places), the spirit WILL BE SUMMONED, however it is neutral and CAN'T BE ATTACKED. (however, it might attack you, although it spells don't damage). Therefore, as the spirit can't be attacked, none of the four quests were able to be completed.

**Comment by MrAndersonX** [comment]
Confirmed. Still bugged, needs to be thrown a fix out there.

**Comment by jonanone** [comment]
All the 4 quests works like they are supposed to. 

Once you have killed the mob, and get the quest starting item, you just have to go to some point to use the item and the ghost is supposed to say something and give the credit for the quest. You are not supposed to kill the summoned ghost, just wait for them to complete their animation and you will get the credit.

**Comment by Thimoteus** [comment]
How long do we wait? Abjurist Belmara attacked my pet, so I unsummoned it. Have been waiting for about 5 minutes with no completion.
