### ISSUE TITLE
[NPC] Antipersonnel Cannon in SotA

### ISSUE THREAD

**Issue by Johanes022** [dalaranwow/dalaran-wow#3044]
Ammo of Antipersonel Cannon in battleground Strand of the Ancients seems to scale with spellpower.
As i geared up my character i noticed slight damage increase on demolishers in SotA and it was around 8k, but today i saw full pve geared balance druid dealing nearly 10k damage each hit with cannon.

**Comment by Rushor** [comment]
Vehicle health and damage output in Strand of the Ancients and Lake Wintergrasp now scale with the item level of the operator's gear. Power scaling is now 1% damage and 1% health per average item level.
Patch 3.1.2.

For me this is a blizzlike behaviour. If you find a proff against this, let me know and i will reopen the issue.
