### ISSUE TITLE
[NPC} Time-Lost Proto Drake

### ISSUE THREAD

**Issue by sashouktc** [dalaranwow/dalaran-wow#3047]
I found several threads already made on this matter. I also put up a topic at the PvE section of the forums. People told me it's fine but it isn't. Here are the issues I have found.

1. It does not spawn at all! I have fairly limited camping hours myself, having been in Storm Peaks for a week. However seeing what I've seen (which will further be explained below) I can state he does not spawn.
2. The timer for TLPD is not random. How do I know that? He is a rare spawn of Vyragosa, so they share mechanics, except the fact that TLPD has a 1/6 chance to spawn instead of Vyragosa. That being said I have some logs of me camping and seeing the spawns. I can even confidently state when and where the next spawn will be. That should not be possible.
3. The spawn location is also not random. I have killed Vyragosa over 10 times in the course of this week and found her dead several more all on the same spot (Brunnhildar Village). 

I might be inclined to attribute that to chance, but over 10 spawns on the same location and times I can predict is not random. Other people know that as well otherwise there wouldn't be a Night Elf druid logging 3 minutes before the spawn (I at least have the courtesy to be on the spot 20 minutes before that). 
I have also talked to another TLPD camper who has spent 2 months doing what I'm doing, getting the same results and not seeing a TLPD. 2 months is roughly 180 spawns. And considering he has gotten them all to not have a tlpd spawn means it does not spawn at all. 
And lastly, I have spoken with people who have the drake on the server. No one has gotten it soon. They have all gotten it in the past while there was a gray area about its spawns.

**Comment by Johanes022** [comment]
Long time ago there was an issue with TLPD where he would spawn after server crash/restart and everybody would rush to Storm Peaks afterwards to get their "Rare" mount.Majority of people who own TLPD atm got it this way.

**Comment by sashouktc** [comment]
Well I have been camping since I put this up. I had a time window for 2 spawns, both were at Brunnhildar at the expected times. I would like an answer from the devs on some way to get this mount in-game.

**Comment by sashouktc** [comment]
I no one going to give an official statement on this? Or should we expect nothing to be done since it's not raid content?

**Comment by Flagg24** [comment]
I have been camping heavy, as well and only have ever seen Vyragosa spawn. That's

**Comment by sirpimp** [comment]
I can confirm this...

**Comment by Golganeth** [comment]
#3142
