### ISSUE TITLE
[NPC] Ricket (Storm Peaks)

### ISSUE THREAD

**Issue by Drakenhof** [dalaranwow/dalaran-wow#3048]
wowhead link: http://www.wowhead.com/npc=29428/ricket

This NPC seems bugged. She should gave several quests, but she only gave a few of them, even if you match the requisites of the bugged quests

Quests she should gave and doesn´t:

- "Expression of Gratitude" (http://www.wowhead.com/quest=12836/expression-of-gratitude): She should gave it without any requeriment (beyond reaching level 77). This quests is required for "Ample Inspiration" (http://www.wowhead.com/quest=12828/ample-inspiration), which opens another chain of quests, like "Opening the backdoor" (http://www.wowhead.com/quest=12821/opening-the-backdoor)

- "Overstock" (http://www.wowhead.com/quest=12833/overstock). Daily mission. She should gave it after completing "A delicate touch" (http://www.wowhead.com/quest=12820/a-delicate-touch).

**Comment by Lothloryen** [comment]
Hello there,

Thank you for the report, it will be corrected after the next realm maintenance.
