### ISSUE TITLE
Disengage doesn't reset fall damage

### ISSUE THREAD

**Issue by MecDalaranWoW** [dalaranwow/dalaran-wow#3049]
When a hunter casts disengage while falling, they should have their fall damage reset. This is not currently the case.

How it is now: A hunter jumps from a 100 yard cliff and disengages 10 yards above the ground. He will take damage as he would from jumping off a 100 yard cliff.

How it should be: A hunter jumps from a 100 yard cliff and disengages 10 yards above the ground. He should take damage as though he jumped from a 10 yard height.

**Comment by WhiteNigg** [comment]
Thats not true, you probably are not doing it fast enough cause it works when i do it on my hunter

**Comment by Golganeth** [comment]
I couldn't reproduce this either. Most likely related to #279
