### ISSUE TITLE
DK auto-unstuck issue

### ISSUE THREAD

**Issue by daelysha** [dalaranwow/dalaran-wow#3053]
Whenever a dk uses unstuck in ghost form, it's teleported to Acherus, at the 2nd floor, which has no spirit healer and there's no way to jump off that area. For example, that's what happened to my Dianet dk on Algalon realm after accidentally falling into the Twisting Nether near Blade's Edge as a ghost: I used unstuck and here I am, waiting for a GM to teleport me near a spirit healer. Please fix this!

**Comment by MalkaviaDW** [comment]
This situation should be solved already.
