### ISSUE TITLE
Holypriest Tier 9 4set bonus

### ISSUE THREAD

**Issue by Cryingnugget** [dalaranwow/dalaran-wow#3055]
Just got my 4. setpiece and noticed the Tier9 4set bonus(+10%) neither works for Discipline (Divine Aegis) nor for Holy (Empowered Renew).

f.e. : 
4set active:     yes
spell:              3044
Flashheal:      7275(crit)
Divine Aegis:  2.2k (Grid)(=~2200)         -> 7275/2200 = 0.302 ~30% => 4set not active(not working)

4set active:            yes                  no
spell:                     2961                2948
emp.Renew(3/3):  1521                1515  => 4set not working

Regards // Merry Christmas x)

**Comment by robinsch** [comment]
On PTR
