### ISSUE TITLE
Crashin' & Thrashin'

### ISSUE THREAD

**Issue by Mountandrew** [dalaranwow/dalaran-wow#3057]
This achievement doesn't work for anyone on the server and me, Peanutmm, Boralas and Jujj are all on the server Alganon, and we can't get the Merrymaker title because of this bug. The racer is invisible and there are no abilities. I would appreciate it if you could give Peanutmm, Boralas, and Jujj the achievement so we can get the Merrymaker title, or you know, fix the bug.

**Comment by Naline** [comment]
You don't need that achievement for the Merrymaker title. I'm pretty surrrr.

**Comment by Benna1234** [comment]
Indeed, you don't.

**Comment by Mountandrew** [comment]
You guys are right, I didn't notice that. I'd still love the achievement to be fix though...

**Comment by ImprezaWoW** [comment]
[#3054](https://github.com/dalaranwow/dalaran-wow/issues/3054)
