### ISSUE TITLE
Clamlette Magnifique

### ISSUE THREAD

**Issue by MalkaviaDW** [dalaranwow/dalaran-wow#306]
ID: 33004

This food doesn't restore mana. Only health.

**Comment by n-ghost** [comment]
Still an issue.

**Comment by Spruitje** [comment]
Still an issue
Does give an 'eating'  and 'drinking' bufftimer so also can not be combined with any other drink simultaneous 
Also triggers some cooldown which prevents any drink (or food) to be consumed for a period of time after the Clamette is eaten, while other foods seem to be able to get consumed one right after another

**Comment by Rushor** [comment]
d3fe4615a6c1597d174bd4539b333a65e863d782
- should restore everything now
