### ISSUE TITLE
Wow.exe crash. Error 134

### ISSUE THREAD

**Issue by Exxtra82** [dalaranwow/dalaran-wow#3063]
This application has encountered a critical error:

ERROR #134 (0x85100086) Fatal Condition
Program:	C:\Users\Paolo pc\Documents\Downloads\Wrath of the Lich King 3.3.5a\Wow.exe

Failed to read file WORLD\WMO\DUNGEON\AZJOL_LOWERCITY\AZJOL_LOWERCITY_001.wmo.

Debug Details:

[2] err=0 text=SFileReadFile - WORLD\WMO\DUNGEON\AZJOL_LOWERCITY\AZJOL_LOWERCITY_001.wmo - Data\patch-3.MPQ
[1] err=0 text=ReadSectors/DecompressData failed
[0] err=0 text=ReadSectors/DecompressData failed

admitted that the character is moved, happen again every time this instance will be loaded?
Cache cleared.

Thank You

**Comment by Golganeth** [comment]
Invalid report. The bug tracker only lists in-game issues with quests, NPCs and such.

This looks like an issue on your side (corrupted files most likely) so you should try to re-install the game from scratch.

**Comment by Exxtra82** [comment]
Ok i'll try, ty for support


Il 26 dicembre 2015 09:34:38 PM Golganeth <notifications@github.com> ha 
scritto:
