### ISSUE TITLE
Hunter's agility/attack power ratio

### ISSUE THREAD

**Issue by MrAndersonX** [dalaranwow/dalaran-wow#3065]
Now, from what I understood from ingame stats and also checking on google to confirm + 1 agility = + 1 attack power. Now, I chance my pants with 2 others that give - attack power, but more agility, so the basic attack power should increase, and while I check agility attack power it does, but the total attack power under the damage status drops. I'll throw in some pics to prove my point : 

![wowscrnshot_122615_135617](https://cloud.githubusercontent.com/assets/14181956/12006278/1a861934-abd9-11e5-8f26-856adf8048b9.jpg)
![wowscrnshot_122615_135620](https://cloud.githubusercontent.com/assets/14181956/12006279/1a889772-abd9-11e5-8c6a-b4171dc225f4.jpg)
![wowscrnshot_122615_135625](https://cloud.githubusercontent.com/assets/14181956/12006281/1a8b05ca-abd9-11e5-8ba3-d71fa6911d59.jpg)
![wowscrnshot_122615_135940](https://cloud.githubusercontent.com/assets/14181956/12006280/1a8a0616-abd9-11e5-9f0e-36815c8d13c5.jpg)
![wowscrnshot_122615_135944](https://cloud.githubusercontent.com/assets/14181956/12006283/1a8b02fa-abd9-11e5-9adf-fe33de6c9893.jpg)
![wowscrnshot_122615_135947](https://cloud.githubusercontent.com/assets/14181956/12006282/1a8b1c4a-abd9-11e5-9202-4abae20b26db.jpg)
![wowscrnshot_122615_135950](https://cloud.githubusercontent.com/assets/14181956/12006284/1a9b9f84-abd9-11e5-834f-859917baf0dc.jpg)
![wowscrnshot_122615_135955](https://cloud.githubusercontent.com/assets/14181956/12006285/1aa1de08-abd9-11e5-8b57-fb2c2e2bacb0.jpg)
![wowscrnshot_122615_135959](https://cloud.githubusercontent.com/assets/14181956/12006286/1aa43d7e-abd9-11e5-9f9c-1319ede7e65a.jpg)
![wowscrnshot_122615_140002](https://cloud.githubusercontent.com/assets/14181956/12006287/1aa4f124-abd9-11e5-869e-f3a6fb093de7.jpg)
![wowscrnshot_122615_140005](https://cloud.githubusercontent.com/assets/14181956/12006288/1aa5313e-abd9-11e5-9229-91eb69c00ca9.jpg)

I used 2 different pants to show the stats increase/decrease as the agility increases/attack power decreases. Now I might be wrong, but how does the math go then ? Isn't 1 point of agility = 1 point of attack power ? The agility ingame seems to be like that though. If it's not bugged, can someone explain it to me please ? Thank you and sorry for the trouble.

**Comment by bobansim** [comment]
Hi mate. See if you have upgraded talent [Careful Aim] because it increases your attack power equal to your intellect.

**Comment by MrAndersonX** [comment]
Hi bro. Yeah, I'm a retard. I totally forgot about the talent :). Thank you very much man. Thread/ticket can be closed now I think and I apologize to staff/forum members for the inconvenience.

**Comment by bobansim** [comment]
Ur welcome ;)

**Comment by Golganeth** [comment]
Closing up.
