### ISSUE TITLE
Dire Maul East - Prince Tortheldrin - NPC

### ISSUE THREAD

**Issue by NomadicTurtle** [dalaranwow/dalaran-wow#3066]
Issue:
Npc is not hostile.

What should Happen:
After disbaling the barrier and killing Immol'thar, Prince Tortheldrin should turn hostile and make as a final boss to the instance.

What happens:
After killing Immol'thar, Prince Tortheldrin does not turn hostile and instead remains neutral, hence unkillable.

http://wow.gamepedia.com/Prince_Tortheldrin
http://z4.invisionfree.com/SMDS/ar/t137.htm
https://www.youtube.com/watch?v=hlEcsnNfizI

**Comment by Golganeth** [comment]
Directly related with #2933

**Comment by DrFuler** [comment]
[06/05/2016] - Also having this problem. The quest is currently not completable.
