### ISSUE TITLE
Empty mails from deleted character

### ISSUE THREAD

**Issue by Nimrasil** [dalaranwow/dalaran-wow#3069]
I just created a ticket for the following, but I want to share here as well so others don't do what I just did.

I had a bank alt, but I wasn't happy with her looks, so I mailed all her stuff, including 20 or so frostweave bags, 12 (I think) netherweave bags, diamond tipped staffs, glyphs, dusts and shards and more to my main. 

I've done this many times on retail. 

Then I deleted my bank alt and created a new with the same name. 

After I got a portal to Dalaran for her and did a couple of christmas quests, I logged out and logged on with my main to get mail. 

All the mails from the first bank alt are empty!

The mails I opened disappeared after opening.

Since I wrote the ticket, I've logged out and back in and one of the mails now had content. The one with most of the glyphs.

Unless a GM can help me, there goes a fortune :(

**Comment by Golganeth** [comment]
Greetings @Nimrasil, this is an invalid report, the bug tracker only lists in-game issues with quests, NPCs and such.

> I just created a ticket for the following, but I want to share here as well so others don't do what I just did.

You should use the forums for that, although there are already a lot of threads related to this.

Closing up
