### ISSUE TITLE
[Warrior] Death Wish and Enrage stacking

### ISSUE THREAD

**Issue by ConradSilverwind** [dalaranwow/dalaran-wow#3071]
Death Wish and Enrage are both enrage effects that shouldn't stack together, which increases a warrior's damage by 132% (Titan's Grip has no damage penalty, and warrior gets 2% bonus damage when both effects are up)

How it should work: Only the stronger enrage should count, which is Death Wish.

**Comment by ImprezaWoW** [comment]
[#3071](https://github.com/dalaranwow/dalaran-wow/issues/3071)

**Comment by Rushor** [comment]
you are link #3071 to #3071 ?

**Comment by ImprezaWoW** [comment]
will relink soon, my bad.

**Comment by robinsch** [comment]
On PTR
