### ISSUE TITLE
Hunter pets

### ISSUE THREAD

**Issue by MrAndersonX** [dalaranwow/dalaran-wow#3073]
Hi,

Well, tho I've seen there are some posts out there, I want to make a general one for the problems I've encountered. First off Pathing, the pet 90% doesn't follow the hunter if he climbs down/up, jumps from a platform to another, goes on a boat or any other moving object. Second, alot of the times the pet goes through textures, gets bugged/stucked, falls under map, get misplaced at the same time as the mob he is attacking, bugging them both. Third, alot of the times when u feed the pet and put him in another stance after training him, it won't stick until after u've dismissed/summoned him again which is really annoying tbh. Fourth, sometimes when placing a talent point in the pet tree and mounting/dismounting, the pet loses the last mob/mobs xp and goes back a level with a full bar, and unlearns all the talents. This happened to me just now ( pet was 52, leveled a pet talent, mounted, dismounted, pet returned to lvl 51 with full xp bar and unlearned ALL talents). These pet bugs combined with [Hunter] Pet Talent - Cobra Reflexes #1585 and Hunter: Animal Handler Talent and if you're a good lilttle member and you vote and you use your votepoints to buy a heirloom bow : steady shot + heirloom bow #2427 ( bugged still ). Not to mention that your first minutes as a hunter might be marked by another bug : Hunter's Auto Shot #1156 ( which can be easily reworked to somehow work by making macros, it's still annyoing to just start a class and already notice bugs ). 

With all of the above and more which I forgot/didn't remember to put in, hunters really seem like a non-viable, annoying, and overall bad to play as of this moment. I'm speaking from heart, as a BM hunt I'm struggling hard to manage all the bugs ( especially the talent/pet talents attack power ones, while also being -1 skill cause of steady shot sucking with heirloom ).

**Comment by Aporis** [comment]
I want to add pet Raptors usually keep doing their running animation even if you stay still, there might be some other pets that do this aswell but I have only noticed it with raptors (I personally use a dragonhawk)

**Comment by MrAndersonX** [comment]
The biggest bugs I found atm is : 
1) When using the ability Mend Pet, the tick heals generate a huge amount of threat. A.k.a bugged as fuck, needs a fix. Tbh when I use mend pet in dungeons and even in some raids my pet pulls higher threat than the tank.
2) Pet stats and buffs reset. Like, pet stat gain is fucking horrible. The hp, dmg etc is absolutely horrific.  At 80 my pet is about 6-8k less hp than me unbuffed even tho it's talents/skills/stat gains should make it have way more stamina/hp than me. And always after it gets buffed, if u dismiss it, then resummon it, cause like I have to jump from somewhere or etc, it always loses the HP bonush gained from buffs ( kings, fortitude, gift etc ) and sometimes even the dmg/crit etc bonuses. This is a huge ass problem too atm.

**Comment by MrAndersonX** [comment]
Still bugged as fuck, needs a fix. Wild hunt is also bugged as fuck.

**Comment by robinsch** [comment]
Somebody split this into multiple issues. More then one report per issue is no longer supported.

**Comment by MrAndersonX** [comment]
Yeah, but wild hunt or some pet talents aren't included in those reports. So I wanna make sure they are named/specified.

**Comment by MrAndersonX** [comment]
Alot of pet talents are still bugged, waiting for the changelog to be applied to the live realm. Can we get a timed release on it ? We've been waiting for it to be applied for a while now...

**Comment by MrAndersonX** [comment]
Well Lothloryen said : "Hello there,

The remaining fixes were applied yesterday night already.

Thank you very much."

But still, Wild Hunt is still bugged (no increase stamina or ap), same as pet stats, hit ,expertise, etc and Cobra Reflexes. So, what gives ?....
