### ISSUE TITLE
[Northrend][Grizzly Hills][Quest] Free at Last

### ISSUE THREAD

**Issue by Archcry** [dalaranwow/dalaran-wow#3075]
Related to: https://github.com/dalaranwow/dalaran-wow/issues/2651

I made a new issue because the related linked issue is closed marked as "Working as intended"
The real problem with this quest is the following:

When you use the item on one of the "Runed Giants" you won't get credit for the "freeing" unless you melee the target before "freeing" it.
This is very strange when your character is a caster. It took me some time to find a way to do this quest but now I managed to do it on my mage by first meleeing the target (which is easy because they don't attack, also an issue) and then using the item.

**Comment by wwrpg** [comment]
I found only one works around 79,42. And I don't have to attack first.
All the others either turn green or not green... but never give credit.

**Comment by rinleezwins** [comment]
I can confirm that the quest item works on first try if I use it instantly after autoattacking.

**Comment by Lothloryen** [comment]
Several corrections on this quest, working fine now.
