### ISSUE TITLE
[Northrend][Grizzly Hills][Quest] Anatoly Will Talk

### ISSUE THREAD

**Issue by Archcry** [dalaranwow/dalaran-wow#3077]
Despite bug reports https://github.com/dalaranwow/dalaran-wow/issues/756, https://github.com/dalaranwow/dalaran-wow/issues/2479 and https://github.com/dalaranwow/dalaran-wow/issues/426 bieing closed this quest is still not working as intended.

I managed to do this quest in a very strange way which might be very confusing to people.
There are a couple of issues with this quest:

**1. At first Tatjana was nowhere to be found**
Tatjana was nowhere to be found and her horse was walking around randomly. I had to stand at the questgiver and wait for the horse to pass by in order for it to disappear. Then both Tatjana and her horse spawned at the correct location a couple of minutes later. I kinda assume this issue has happens due to a player not completing the quest (due to reasons blow).

**2. Tatjana spawns under the horse**
When you get to the spot Tatjana and the horse are both present, the strange thing here is that Tatjana spawned under the horse. After reading some of the previous bug reports I shot the "Tranquilizer Dart" at her but I did not get auto mounted as the previous reports indicate. At this point I just mounted the horse by right clicking it, the horse began to move and we left Tatjana behind.

**3. The horse would stop walking when I got attacked by an enemy and would continue running when I killed the enemy**
While the stopping might be working as intended (don't know how it was on retail) the continue walking part is definitely not! The moment I kill the enemy the horse would just continue to walk without me. So I mounted my flying mount and remounted the horse a little bit further down the road.

**4. The horse returns to the position at which we got attacked**
When I remount the horse after a fight with the enemy the horse will first walk back to the spot where the attack took place and then continue onward from there. Considering I had to fly to the horse in order to mount it again it had to run back for a couple of seconds made me confused. This is probaply the part at which players give up the quest all together.

**5. Arriving without Tatjana seems to work just fine**
When I finally got to the questgiver without Tatjana (but with the horse) it would just complete the quest.

I hope I can help some people do the quest with the above instructions and I hope the development team can fix the issue with the detailed information above.

**Comment by jonanone** [comment]
Tatjana mounts on the horse once respawned.
Once the dart is used on Tatjana the horse becomes a mount and it will bring you to the quest ender.
The fix will be applied to the live realm soon.

**Comment by DalaranLantri** [comment]
Glitched it in 2 ways.
**Glitch number 1**: 
Tatjana's Horse27626 and Tatjana27627 do not respawn at the same time (The horse respawns slightly earlier). If the horse is pulled while Tatjana isn't present, and at that time Tatjana's respawn is triggered, she will not spawn on the horse and will not (waited 30-40 minutes) return on it again. The quest will still be completable by shooting the Tatjana on the floor and right-clicking the horse.
**Glitch number 2:** 
- Pull Tatjana
- Pull any other mob
- While in combat, shoot Tatjana with the dart.
- Rightclick the Horse
- You can now control the Horse like a regular mount.
Dismounting and remounting triggers the proper pathing (Tatjana's Horse will run straight through any terrain to return to the regular position, then trigger the normal route.)

Note: even after riding around with Tatjana's Horse, it still spawned before Tatjana.

Tatjana does spawn properly if the horse isn't pulled. Have not been able to glitch it to the point where the quest isn't completable anymore.

**Comment by Zibathy** [comment]
This quest is bugged on Kirin Tor. When I bring the horse to Anatoly nothing triggers, when I dismount nothing triggers, and when I try to mount the horse again... well... this happens:

![wowscrnshot_032217_132351](https://cloud.githubusercontent.com/assets/7729864/24214343/2ee4ba28-0f03-11e7-966e-ad4aa645948f.jpg)
![wowscrnshot_032217_132355](https://cloud.githubusercontent.com/assets/7729864/24214344/2ee57a30-0f03-11e7-864f-90af667eb102.jpg)

**Comment by Rushor** [comment]
the quest was also bugged in serval ways on retail http://www.wowhead.com/quest=12330/anatoly-will-talk#comments
