### ISSUE TITLE
Race Change

### ISSUE THREAD

**Issue by hjalmarwiklander** [dalaranwow/dalaran-wow#3078]
Hi.
I tried to race change but the website took me to the homepage when I clicked it.
Then someone told me I could use the faction change instead and just change race in the same faction.
So I donated and bought the service but that didnt work.
Please help me change race, havent used the faction service yet.

**Comment by Golganeth** [comment]
Invalid report. The bug tracker only lists in-game issues with quests, NPCs and such.

On the side note, the website is being reworked and some features are currently disabled. We shall inform everyone once they are enabled again.

**Comment by hjalmarwiklander** [comment]
Who do I contact then? And where?
