### ISSUE TITLE
Rhok'delar, Longbow of the Ancient Keepers chain quest

### ISSUE THREAD

**Issue by Zelkros** [dalaranwow/dalaran-wow#3084]
Ok so i got the quest for Rhok'delar, Longbow of the Ancient Keepers
 bow and i tried to complete those 3 quests. The one with the 4 demon heads it's bugged: the one in Silithus doesn't drop nothing and i can't find any mobs who drop [Ancient Sinew Wrapped Lamina]. I tried to talk in-game via tickets and they told me to come here. I hope someone can give some answers or at least i want to know if it's a possibility to get that bow.

**Comment by Crispybuilt** [comment]
![image](https://cloud.githubusercontent.com/assets/5054924/12079435/11e31622-b239-11e5-92c7-f74f41d850c7.png)

Check it out

**Comment by Zelkros** [comment]
Yea but that means i can't get it in-game with completing the quests for it? I mean.. this is how they wanted or it's just the thing they will not fix the bugs in the near future? I don't really want to pay for something that i should be able to get "manually". But thanks for your suggestion.

**Comment by Golganeth** [comment]
Already reported on #974 so closing this up. Until this gets fixed make an in-game ticket and we'll do our best to help you out.
