### ISSUE TITLE
Hunter masters call

### ISSUE THREAD

**Issue by xumae** [dalaranwow/dalaran-wow#3086]
I have reported this major hunter bug like 4 times in the past 6 months, masters call does not work half the time, and when you are rooted it works about 1% of the time. When used it will go on cd and give the buff to the pet but not to the hunter also

**Comment by KazJR** [comment]
Still not working, re-open plz

**Comment by Serpentsting** [comment]
https://www.youtube.com/watch?v=qESV4X8nzME

**Comment by Serpentsting** [comment]
bump

**Comment by Serpentsting** [comment]
BUMP.

**Comment by Rushor** [comment]
Scripts/Spells: Hunter Masters Call - Always remove MovementImpairingAuras + Disable cast while pet is dead + disable cast while pet is under CC effect

* closes https://github.com/dalaranwow/dalaran-wow/issues/3086
* commit: d72e2bb4352b70a168ba679e3297674b5b216e40
* the fix will be on ptr soon

**Comment by Rushor** [comment]
Scripts/Spells: Hunters Masters Call - Remove MovementImpairingAuras from owner and pet

* updates https://github.com/dalaranwow/dalaran-wow/issues/3086
* commit: c5d0e90e67275a380e8ee85804a6f726833eb0f7

**Comment by Lothloryen** [comment]
Deployed already, thank you everyone.
