### ISSUE TITLE
Quest: Freedom for All Creatures

### ISSUE THREAD

**Issue by Sagrath** [dalaranwow/dalaran-wow#309]
http://www.wowhead.com/quest=2969
The door to the cage open all the time. So you can not use the key
You can not click on the "Captured Sprite Darter", as well as their release six of them.

**Comment by HansDAndersson** [comment]
The quest seem to almost work now, you can click the cage to release the sprite darters but once you reach the end of the path all of them despawn without giving credit.

**Comment by beregas** [comment]
As 2016, I can confirm the credit is not given after you release and escort them all.

**Comment by bojan112** [comment]
worked for me
here is proof http://i.imgur.com/IACSF9r.jpg

**Comment by Leodimas** [comment]
Can confirm you get credit, but the npc respawns very slow making it almost impossible to turn the quest in before the timer runs out. You would have to pre-clear the whole camp
