### ISSUE TITLE
Infinite summon of skeletons

### ISSUE THREAD

**Issue by Lukas45** [dalaranwow/dalaran-wow#3091]
At the Wrath Gate (out of any phases) there are 4 spots where skeletons (Frail Construct) are infinitely being summoned, and I can't imagine it being good for the server stability. And they can't be killed, maybe with a corrupted ashbringer nearby, but haven't tested
1 skeleton is summoned every 3 second at each spot.
![wowscrnshot_011016_232005](https://cloud.githubusercontent.com/assets/4707702/12224451/fe4c3eaa-b7f0-11e5-9d52-9871ea0317af.jpg)

![ecacd3539a4bbddd672b6cc72bf24d13 1](https://cloud.githubusercontent.com/assets/4707702/12224469/8191511a-b7f1-11e5-933c-982e3ec5d255.jpg)

**Comment by shitserver** [comment]
I think that is improving the server stability alot. :+1: Need more of those.

**Comment by hAkonf** [comment]
Can confirm this. Seems to be summoning a skeleton every 3 second. Some of them does despawn, but it summons more than it despawns.
Can't be killed with ashbringer.

**Comment by hAkonf** [comment]
http://i.imgur.com/guEGWnm.png
This seems to have been fixed. Can be closed I guess.
It doesn't spawn skeletons beyond 2.

Thumbs up loth! :+1:

**Comment by Lukas45** [comment]
Yep seems to be fixed.
Cheers Loth
