### ISSUE TITLE
Meta gems not working

### ISSUE THREAD

**Issue by Dargendarg** [dalaranwow/dalaran-wow#3092]
There is a glitch where meta gems don't give their intended stats even when they look like they're activated. This has happened to me twice. Both times were after I regemmed a required color gem. One time it was with a def rating meta, now it's with a stam and armor meta. 

Someone initially came to me about this bug because their meta wasn't working and I had the same helm and meta. All of my stats added up right at the time. Then later I regemmed a red gem (that my meta required) and it stopped giving me defense rating. I tried taking all armor off, relogging, etc. I even tried to put in a new meta of the same type and it didn't help. I had to change to an entirely different meta. I made sure the new meta was working, and it was. Then later I again regemmed a red gem (that this meta also required) and it stopped giving me the stamina. In both instances the metas look active but when I look at my stats they don't add up.

Extra note: I was wearing the gear while regemming those reds. Not sure if that might have triggered anything.

Not many people are familiar with this bug, but I'm sure it's widespread and unnoticed since it starts out working fine but stops working when you regem something else.

**Comment by tthierolf** [comment]
Did you find a workaround? I'm having the EXACT same issue right now with the Eternal Earthsiege Diamond meta except I have a blue chest that if I equip it the meta stats are applied but if I swap to a new epic chest the stats dont apply. The meta requirements are fulfilled either way without the chest slot in consideration.

**Comment by Dargendarg** [comment]
Yes we are having the exact same problem. Thank you for the pictures they make it a lot easier for people to understand what's going on. The only "workaround" I found was to put in a different meta gem (not the same type) or change the helmet. Those are very good workarounds lol. I just now checked to see if my meta was working and it's not. This is the third time I've experienced this glitch within 2 weeks.

I know switching the meta gem to another meta of the same type doesn't work, but switching to another type does. I haven't tried switching from glitched meta A to meta B and then back to meta A. That might work but idk this is a weird glitch.

The first two times I had this glitch it was with Tempered Titansteel Helm also. When I saw that you had it too I thought the glitch might be tied to that helm, but now I have a different helm and it's glitching too.

I don't know why the admins haven't responded to this yet. It's a huge issue and I think a lot of people have it but don't realize it.

**Comment by Dargendarg** [comment]
Things I've tried:

Re-equipping helm: DID NOT WORK
Re-equipping all gear: DID NOT WORK
Unequipping, logging off, then re-equipping: DID NOT WORK
Yelling at my mom: DID NOT WORK
Regem the meta slot with same type of gem (meta A to meta A): DID NOT WORK
Regem the meta slot with a different type of gem (meta A to meta B): WORKED!!!!!
Regem the meta slot with a different type of gem and then back to original gem type (meta A to meta B to meta A): DID NOT WORK!? 

WTF it worked when I switched gems, but when I switched back it didn't work.

Yes, I have the required gems for each meta.


Meta gems that have glitched on me:

Eternal Earthsiege Diamond (+21 def rating, +5% shield block value)
Austere Earthsiege Diamond (+32 stam, 2% increased armor from items)

**Comment by tthierolf** [comment]
I picked up a Hero's Redemption Faceguard and equipped the same meta in it and it's also bugged, It also happens to activate fine with the blue chest, it's only bugged with the epic Hero's Redemption Breastplate. Tried regemming the gems in the chest and it didnt help.

**Comment by tthierolf** [comment]
More updates before I go to bed. I think the bug now has something to do with which gear slots it's using to calculate whether the meta works. The eternal meta needs 2 red and 1 blue to activate. In my current gear setup where the meta is activated and im receiving its stats I have 1 blue in the helm, 1 blue and 1 purple in the chest, 1 purple in the belt, and 1 blue and 1 purple in the pants. If I unequip my belt, leaving a total of 3 blue and 2 purple gems equipped the meta remains active and stats applied. If I put my belt back on a remove my pants, leaving 2 purple and 2 blue equipped the meta text says it's active however I lose the meta stats on my character window.

**Comment by tthierolf** [comment]
I also just replaced the purple gem in the chest with an orange gem and the meta remains active and the stats applied properly. So it seems like as long as I have a gem that counts as a red in the chest it works. I havent yet tried using a purple gem in the blue socket and seeing if having a gem that counts as red in either socket fixes it.

**Comment by Nimsun** [comment]
I have the same Issue with the "Chaotic skyflare diamond" I was thinking to open a thread about the helmet and not the meta, but since I've found this it might be the meta only? Anyway the helmet is the "Brutal gladiator's plate helm" (Warrior). As the others I have everything required to activate the meta but apparently is not working, I should have 471 hit rating with the meta, but I have only 450. Ty in advance.

**Comment by massa93** [comment]
This bug occurred to me today, i put the "Eternal Earthsiege Diamond" on the head and then one purple on the head and one on my belt, the gem was active but gave no stats. I tried changing meta to another and then back and changing purple to red sockets but it didn't work.
After reading this issue i changed a socket on my chest with a purple one and it worked keeping another purple on head.
