### ISSUE TITLE
Ulduar Achievement

### ISSUE THREAD

**Issue by chfootball25** [dalaranwow/dalaran-wow#3093]
Guild killed Iron Council in Id #335 but because I died, I did not receive credit for the kill. Can link screenshot if necessary.

**Comment by sashouktc** [comment]
I'm pretty sure this is intentional. People have to be alive on kills to get the achievements since those open new raids for them. The interesting part is you can get the achievement for some bosses and you can't for others.

**Comment by hAkonf** [comment]
Definitely not intentional. Funny thing about Iron Council is that you can get the "I choose you" achievements, but still not get the boss kill registered in "Antechamber of Ulduar" achievement. Quite Amusing, except when it happens to you.

**Comment by sashouktc** [comment]
Well you can't get any of the Keepers this way.

**Comment by saltylopez** [comment]
Freya not granting credit when raid members die combined with her Nature Bombs occasionally exploding immediately (#3338) makes trying to do attunement runs unnecessarily frustrating.

**Comment by Lothloryen** [comment]
Hello there,

This issue is now solved, dead players will be granted with the achievements and their criteria.

Thank you very much.
