### ISSUE TITLE
Priest - Dispel Magic Ability Bug

### ISSUE THREAD

**Issue by Zelwindin** [dalaranwow/dalaran-wow#3095]
This spell is intended to two dispel two harmful magic effects on an ally or two helpful off an enemy.

However, the spell will only remove two effects if the effects are "different".

For example, currently, dispel magic will not remove two warlock "Corruption" spells on a single target on a single cast of the ability, it will only remove one.

Dispel Magic will, however, remove one "Corruption" and one "Unstable Affliction".

Please fix and thank you for your hard work :).

**Comment by Johanes022** [comment]
Dont forget Contagion talent (30% dispel resist), have you tested it w/o that talent.

**Comment by Zelwindin** [comment]
Unfortuantly I am actually referring to the corruption ability used by NPC's in Nexus Heroic.

I should have been more specific.

I have tested it through many PvE encounters with different debuffs. Same debuffs don't dispell 2 at once. (So two NPC corruptions, only one corruption will dispel per cast).

I don't PvP enough to definitivly comment on player vs player interaction with the skill, though I imagine the bug is the same.

**Comment by Rushor** [comment]
Works for me. If i cast the spell on a victim with two helpfull auras, it wil remove both at once. Maybe you used the wrong rang.
