### ISSUE TITLE
Warlock Soul Fire Bug

### ISSUE THREAD

**Issue by WhiteNigg** [dalaranwow/dalaran-wow#3100]
Im pretty sure everyone in the server is aware of this but i didnt see any open thread so i ll make it. The soul fire spell is a spell with a base cast time of 6.0 secs there are 2 talents that lower its cast time, 1 is Bane (http://wotlk.openwow.com/spell=17792) and the other one is Decimation (http://wotlk.openwow.com/spell=63167) so according to these 2 Soul Fire's base cast time should now be 4 secs with Bane talent and when Decimation talent procced it would be 4-40% = 2.4 secs.
Thats how it was supposed to work, now what actually happens in the game is that when the talent proccs the first cast reduction is the 40% and then the 2 sec, so thats (6-40%)-2 = 3.6- 2 = 1.6 secs BASE CAST TIME for Soul Fire. This bug is basically making the hybrid spec far superior than every other lock spec.

**Comment by Lukas45** [comment]
#2379

**Comment by Golganeth** [comment]
Duplicated as @Lukas45 pointed out so closing this up.
