### ISSUE TITLE
(Instance/Raid) Nerubian Burrowers are burrowing while on top of Ice Patches

### ISSUE THREAD

**Issue by Muhatihottie** [dalaranwow/dalaran-wow#3103]
twitch broadcast of bug in effect, 2 separate occasions in a ToGC-10. Teamspeak commentary on the matter can provide more info on other occurences.

http://www.twitch.tv/pinkfloyd188/v/36869039

first occurrence at 04:00-04:30, second happens at 10:40.

this bug was just recorded around 04:00 Server Time, 1 hour before raid reset.

**Comment by fsironman** [comment]
fix asap pls.
Compared to https://github.com/dalaranwow/dalaran-wow/issues/2993 (which is still open) this bug makes the boss totally unkillable  and not only a bit harder to kill.

**Comment by Tsunadee** [comment]
This bug is also present on 10man normal, which makes it difficult for a geared group, and I guess very hard if not impossible for an average geared group.
something that should be fixed fast.

**Comment by pertla22** [comment]
Did you plan to implement some fixes to add to not being able to cc them, even if that is allowed and tactic was properly allowed to be used on live servers? Nice going there, trying to fix stuff that isnt even broken just someone said it isnt allowed without any proof. Check stuff out before you plan to fix things that dont need fixing, and actually go and fix stuff that is broken. Jesus christ..

**Comment by Crispybuilt** [comment]
@pertla22 Yeah, that seems about right, they probably went to experiment with some new "hot-fix". The adds can be CC'd with pretty much every kind of CC, not sure why to change it now and break the encounter for no reason...

**Comment by hAkonf** [comment]
Absolutely ridiculous. This needs to be fixed straight away.

**Comment by Muhatihottie** [comment]
i'm in a 25-man normal group and reaching anub in the next 30/45min and am able to do a couple tests if anyone has suggestions/ideas. the attempts will be streamed on the same channel linked in my OP and linked for future viewings afterwards.

**Comment by Muhatihottie** [comment]
the adds seem to be immune to the slowing debuff that gets applied by the ice patches. i believe by making an exception to this debuff, the problem would be resolved.

**Comment by shitserver** [comment]
Shitserver confirmed :-1:

**Comment by Lothloryen** [comment]
Hello there,

Thank you very much for the reports and respectful confirmations, it is really appreciated - it was a mistake made by me 2 days ago when deploying few corrections, I have corrected it already and it will be working after the next scheduled maintenance or server restart.

**Comment by Lukas45** [comment]
Any word on when the next scheduled restart/maintenance will happen?

**Comment by fsironman** [comment]
can we get at least a .reload creature_template 34607 34648 35655 and 35656 thx

I mean how can fixing a gamebreaking bug for the current progression main raid affecting a lot of people not have highest priority?

**Comment by shitserver** [comment]
"after the next scheduled maintenance or server restart" -so difficult to just set up a server restart. *facepalm* :8ball:

**Comment by Kchekrik** [comment]
It was fixed yesterday (Sunday).
