### ISSUE TITLE
The Affray

### ISSUE THREAD

**Issue by DarkOxus** [dalaranwow/dalaran-wow#3107]
The main issue is that I have a warrior, and in order for me to get the berserker instance I need to do a quest called The Affray, but it doesn't work properly. The objective is to stand on a grate, and supposedly mobs will appear and you just have to slay them in order to kill the mini-boss and finish it. I really need the stance, so I need to do that quest...
thanks for your attention and please solve it.

**Comment by Golganeth** [comment]
Already reported on #2471 
Make an in-game ticket and we'll help you out.
