### ISSUE TITLE
Quest: The Swarm Grows

### ISSUE THREAD

**Issue by gotmilk0112** [dalaranwow/dalaran-wow#3108]
http://wotlk.openwow.com/quest=1147

The mob spawns for this quest seem to be bugged, in that there is only one Invader. There are plenty of Drones and Searchers, but literally only one Invader.

According to Wowhead comments and Carbonite's quest helper, the Invader mobs are supposed to spawn inside the little cave, but there are none inside; only drones. Killed all of them and waited for respawns, and still nothing but drones.

**Comment by Golganeth** [comment]
I've reopened #69
