### ISSUE TITLE
ToGC10: Anub'Arak - Burrower damage

### ISSUE THREAD

**Issue by Kalveo** [dalaranwow/dalaran-wow#3111]
Since the hotfix correcting the issue with the Burrowers burrowing on the ice, the adds are hitting much harder than before. On the 10man version our tank is being hit for around 14k damage per hit from the burrowers, might this be related to #2993?

**Comment by hAkonf** [comment]
They hit that hard before. Without the block reduction they hit for about 4.4k. 9 stacks means you will get hit 4.4*3.25=14.3k. Same as before.

**Comment by Kalveo** [comment]
Please correct me if I am wrong, but according to Wowwiki, the 10man burrowers hit for ~2.7k, and the 25man for ~3.5k, neither with a reference to doing more damage in HC. 4.4k base damage in an 50% increase for the 10 man encounter.

**Comment by hAkonf** [comment]
This server has higher values to compensate for 3.3.5 talents.

**Comment by fsironman** [comment]
nevertheless they are still doing way to much dmg on block tanks (#2993?) and this should be fixed asap

**Comment by hAkonf** [comment]
Agreed.

**Comment by Kalveo** [comment]
Just out of interest, exactly what part of the 3.3.0+ talents are you referring to? I have been through all patch notes from ICC (3.3.0) release to 3.3.5a and can't find any changes that could justify a 50% base damage increase

**Comment by ashido96** [comment]
While i know this doesn't really address the actual problem of the block calculations being really bad. 25 man heroic retail kills show tanks getting hit for ~1.5k when they have ALL FOUR of the adds, even with pre-nerf buffs tis a bit absurd. And then on dal-wow you only get two adds on you and each one hits you ~12k.

Go out and find all that excellent block gear, like the level 70 trinket gnomeragan auto-blocker, the blue trinket from lavanthor in heroic violet hold, or the ring from the last boss in heroic utgarde pinnacle. As well as wrists and bracers that can drop from multiple naxx25 bosses (boots BoE). A completed block set will enable a paladin tank to completely avoid stacks on anything but 25 heroic with good positioning. This may or not hold true for warriors as well.

**Comment by hAkonf** [comment]
As a warrior with good block gear you can take less than 40k dmg for the whole encounter.

**Comment by Rushor** [comment]
yes the reason is the wrong calculation of block in general. in https://github.com/dalaranwow/dalaran-wow/issues/2993 i added the blockvalue each time the victim gets the stack in order to compensate the damage. With the merge of https://github.com/dalaranwow/dalaran-wow/issues/2993 it will be fixed. Thank you.

Closing since the issue will be handled in https://github.com/dalaranwow/dalaran-wow/issues/2993
