### ISSUE TITLE
Quest: Speaking With Gan'Zulah - Mob bugged in wall

### ISSUE THREAD

**Issue by gotmilk0112** [dalaranwow/dalaran-wow#3113]
In the process of pulling the named mob for this quest, he reset and...ran straight into the wall and got stuck. Could not get him back out; could not hit him with anything, not even AoE abilities.

http://i.imgur.com/e81bFqv.jpg
http://i.imgur.com/Ssb3Zl5.jpg (using Mind Vision)

When I came back 10 minutes later, the other mobs had respawned, but he was still stuck in the wall.

http://i.imgur.com/r0mMjWv.jpg

**Comment by Golganeth** [comment]
Fixed in-game. This is rare and general issue with NPCs/pathfinding, but the respawning spot is correct and the quest itself works.

**Comment by darm11** [comment]
The mob is still stuck on the wall, just ran in to it for doing the quest and i can't attack it, not even with aoe spells
![wowscrnshot_021416_111447](https://cloud.githubusercontent.com/assets/16447899/13034769/40b29178-d30c-11e5-8e50-a88aa53d7ff5.jpg)

**Comment by ImprezaWoW** [comment]
Seems to happen fairly often with this mob.

**Comment by Rushor** [comment]
propose another xyz position for his spawn and we will change it :)
