### ISSUE TITLE
Death and Decay vs Stealth (rogues/druids)

### ISSUE THREAD

**Issue by Johanes022** [dalaranwow/dalaran-wow#3118]
Death and Decay does not affect players under the effects of stealth if they are out of range of the DK.Only when they are visible(in stealth) by player himself DnD will do damage to them and remove stealth.If they are out of range DnD will do nothing, and will become waste of GCD and runes.

https://www.youtube.com/watch?v=lTK9J9Y7XIo

**Comment by Johanes022** [comment]
i just wana add , as you can see on the first two atempts DnD disappears straight away if you use it on ground where the stealth player is (there is no animation).If you trow it on the ground where theres no player it will show animation, but the enemy stealth player can walk trough that DnD without recieving any damage therefore not leaving stealth.

**Comment by Lukas45** [comment]
Just want to add, not as big, but DnD related.
This is not about players, but NPCs (aka not as big)
If you DND on a mob that is outside the cast radius (30 yards), but is hit by the AOE effect of DND (upto around 40 yards), or, line of sight from the player, the exact same thing will happen.
The GCD, runes and runic power is triggered, despite the effect never actually going off.

**Comment by Golganeth** [comment]
#2586 - The spell effect disappears and does no damage, mostly when the target location is out of LoS (pathfinding issue)

**Comment by robinsch** [comment]
On PTR.

**Comment by Rushor** [comment]
Core/Spell: Allow Death and Decay to target stealthed units

Issue: https://github.com/dalaranwow/dalaran-wow/issues/3118
commit: fad7eb9877af6ea926008bc343009a5ce707656a

**Comment by TeridanDW** [comment]
Works as intended on ptr.
