### ISSUE TITLE
Anub respawning after kill

### ISSUE THREAD

**Issue by shitserver** [dalaranwow/dalaran-wow#3121]
Dear Loth,

you might want to check why Anub 25hc/10hc (probably in normals aswell) respawns after killing him.
It takes about 10-15minutes after dying/looting the corpse for him to respawn. 
It doesn't happen everytime though, my guess is you need to have people staying inside the dungeon waiting.

Since Anub 25hc is the actual endgame boss, dropping BiS pieces (including chest loot), and having those kind of "bugs" is making the raiding experience on this server pointless. 

>>>>High priority<<<<

**Comment by hAkonf** [comment]
Happened in Overdozer today, ofc we didn't kill it again. This needs to be fixed however, because some guilds are in fact abusing it.

**Comment by fsironman** [comment]
![nice bugs](http://i.imgur.com/g9qW6xS.jpg)

**Comment by Lothloryen** [comment]
Hello there,

This issue has been corrected, the fix will be deployed with the next scheduled maintenance.

Thank you
