### ISSUE TITLE
[Quest] For love eternal

### ISSUE THREAD

**Issue by glitterlance** [dalaranwow/dalaran-wow#3124]
While the quest works fine, the cutscene at the end of the quest does not appear. 

http://wowwiki.wikia.com/wiki/Quest:For_Love_Eternal

**Comment by Rushor** [comment]
cb2f315ccdbdb69e3ead348eb31e4171569656ba
- textevent added

**Comment by Golganeth** [comment]
- [19:02:21]That the fates should be so cruel as to permit us only this after a thousand years apart...
- [19:02:26]Do you hate me, my love? That I was forced to destroy your living form, that your spirit be released from unhappy bondage.

**Cerellean should say the 2 quotes above, they are currently set as %s**

-------

- The %s "Anaya's soft voice trails away into the mists. "Know that I love you always..."" almost at the end is missing


http://wowwiki.wikia.com/wiki/Quest:For_Love_Eternal

**Comment by Rushor** [comment]
f090407651a3c80f9af6989cb169d2e563f5b62b
- texttype corrected
- spawntimer for the ghost increased
