### ISSUE TITLE
[Quest] Kaw the Mammoth Destroyer

### ISSUE THREAD

**Issue by wwrpg** [dalaranwow/dalaran-wow#3125]
I hate to re-open an issue that continues to resurface but there is still an issue that makes doing this  VERY hard to complete, at least for most players that I talk with. If it weren't for the fact that this quest unlocks the ability to turn in the ears for reps [http://www.wowhead.com/quest=11866/ears-of-our-enemies](url) I would have just dropped the quest and moved on, since there are plenty of other working quests.

There are two issues I have come across.

1. Sometimes Kaw has an incorrect point of respawn (this was seen in #2511). After a server restart I found that he is back to where he is supposed to be. So this issue has a workaround of just waiting for a server restart. But this only guarantees one player to do the quest every server restart.

2. Kaw remains as an invalid target. 
This is the more critical issue. Once I get on a bull and attack Moria, it starts the script where Kaw jumps on his mount, and should become targetable after killing Moria. But usually I just end up killing Moria, while Kaw remains untargetable through the whole event.

The way it is supposed to work:
You'll first fight Moria, who will die within 3-5 hits with trample. Once that happens, Kaw will dismount and attack you. He hits your mammoth for between 300-400, but you should be able to kill him easily. If you get overwhelmed with adds, just use the AoE fear. Note: Kaw is immune to the fear.

Once he is dead, use the ability to dismount and loot the axe object that is next to his corpse.

I have tried with and without a bull.
I always trigger the event by attacking Moria first, but every time Kaw remains "Invalid" both before and after attacking/killing Moria.
I have seen other players do it, and it almost appears that you have to kill Moria before Kaw can jump on Moria, or target Kaw before he mounts. Like there is a small window of time that Kaw is targetable. Hope this helps track down the issue.

**Comment by wwrpg** [comment]
![wowscrnshot_020416_124653](https://cloud.githubusercontent.com/assets/6560015/12829223/bfe41baa-cb3d-11e5-8ac1-e460cbb7e075.jpg)

**Comment by sashouktc** [comment]
I have it completed on 2 characters. Never had an issue with it. I just killed the mammoth without using a mammoth myself and then killed Kaw. I'm guessing you want a blizzlike quest. I'm just saying it can be complete.

**Comment by wwrpg** [comment]
I just want the quest to work. Seems you were very lucky. 
I talked to another player who had the same problem happen to him too. He thought it only works a couple times after a server restart. And even then it takes a couple tries for the script to work correctly. I also tried without getting on the bull, but Kaw remains an Invalid Target. Maybe I need to kill his mammoth faster?

**Comment by Golganeth** [comment]
Kaw can be killed manually to complete the quest but the mammoth can't be mounted - The quotes are missing and Kaw doesn't mount Morla. Morla simply stands there and can be attacked / killed by players and it won't attack players at all.

https://www.youtube.com/watch?v=S9Amt8EJ8ZU

**Comment by Lothloryen** [comment]
Working fine on Algalon. If anyone experiences any issue let us know, please.

Thank you.

**Comment by roblockster** [comment]
Still broken on Algalon. Kaw still spawning incorrectly and is unreachable.
