### ISSUE TITLE
Debuff cap on raid targets

### ISSUE THREAD

**Issue by adytzyca** [dalaranwow/dalaran-wow#3127]
So as many of you have noticed during 25 man raids , some of your DOTs will stop showing whenever there's a large numbers of debuffs on the boss.Notice that this wasn't a blizzard invented mechanism (unlike early vanilla days when the number of debuffs ACTIVE on the boss was limited to 8),but  is in fact a visual bug that causes server to stop sending you back any information besides the damage your DOTs are doing.This means that whatever addons you might be using to track down your DOTs will stop working and needless to say,if you're playing a shadow priest or affliction warlock the whole experience becomes pretty frustrating as you won't know the exact duration of your dots and therefore  will never be able to play it on its full potential.Hope you guys look into it soon.

**Comment by Dolmio1** [comment]
Yes pls fix.

WotLK Patch 3.0.2 (2008-10-14): There is no longer a limit on the amount of debuffs a target can have on them at any time.
TBC Patch 2.0.1 (2006-12-05): Debuff slot limit increased to 40.
Patch 1.7.0 (2005-09-22): The debuff limit has been increased to 16 (from 8). In addition, the client will now display all 16 debuffs.

Most of the time you see debuffs just fine, but from time to time when there are a lot of debuffs on the boss, the DoTs/debuffs just "disappear". It's only visual however and the debuffs are not in fact gone (i.e. using Immolate and the debuff does not appear on the boss, but the actual damage is being done and recorded by recount/skada.) Happens on probably every kind of DoT/debuff and u can't track them with addons either.

Usually happens with lots of spriests / affli locks in the raid, debuff visual limit seems to be around 100 or so but maybe it's related to server lagg.

Hardcoded debuff cap is 255 if im not mistaken but that's not the case, you never 'knockout' debuffs of other people bc of a debuff cap, (like in tbc the magical '41th debuff'.) The debuffs are there, you just can't see/track them and it's really annoying.

**Comment by sashouktc** [comment]
There is an option that makes you only see your debuffs on the target. I used to have the same issue before I turned it on and now I only see my buffs, making things easy. 

However, even without it, your buffs should be on the top of the pile and there should be no issues with addons.

**Comment by adytzyca** [comment]
@sashouktc : You're wrong,i've been using this option all along and it has nothing to do with your debuffs not showing on boss.

**Comment by Dolmio1** [comment]
Yeah what adytzyca said. You cannot track debuff visual even with addons and they won't show up on the boss when you got a raid setup with 100...120~ debuffs

**Comment by M0dinstaller** [comment]
It seems to be a common bug on private servers. I used to have the same problem trying to sync up my cycle as a feral druid on exca-wow.

**Comment by sashouktc** [comment]
@M0dinstaller Well Excalibur Wow is a tbc server. I am not sure this option was even present in tbc, and based on my experience (as I have 2 bis characters there) it isn't. 
@adytzyca @Dolmio1 - I have a feral druid and once I turned this on only my buffs would be present on the boss. I am 100% positive on this. And seeing how I'm not using any addons maybe that is the problem in your cases.

**Comment by adytzyca** [comment]
@sashouktc Not sure if you're trolling or not.What part of 'most dot users have this option enabled and with 0 results' didnt u understand?the problem being with the server not sending any feedback to the players except the 'damage numbers'.As for you being able to see your 3 dots as feral,i encourage you to try raiding with 24 other people,4 of which are shadow priests and another 4 being affliction warlocks and see for yourself how your little interface option fails miserably.

**Comment by sashouktc** [comment]
I have raided and am raiding. My debuffs are the only ones on the boss and they are perfectly visible. I'm not sure why you have this problem but it's working properly for me for 2 characters (both of which are raiding ULD+).

**Comment by Lanai1** [comment]
@sashouktc  what are you talking about...? Please don't shit up the github with false and incorrect, mmochampion/wowhead comments style opinions, especially if you didn't play retail. This is something completely different from what you are talking about.
@Lothloryen please fix this, makes affliction warlock really irritating and unfun, same for shadow priest, sure it can be done but it makes it way more annoying and more or less impossible to be as effective as you can be when it comes to multidoting, seriously reduces the capabilities of two of the more fun specs in the game. It seems to only happen with a lot of debuffs on the boss, from personal experience it felt like multiples of the same debuffs ie haunt, corruption(used by every lock) vampiric touch... seemed to cause it to happen more often/faster.

**Comment by Demonizer50** [comment]
Of all the triggering things on this server, this is one of the things that needs to be fixed asap. Dolmio1, Lanai1 and Adytzyca are all right in their perspectives on this matter. It makes affliction warlock and shadow priest almost impossible to play and their dps highly depend on applying/reapplying dots at the right times. As this is not blizzlike and this server intends to be blizzlike this is a matter of great importance. There are other matters that needs to be fixed but make this one of your top priorties please.

**Comment by Tarpor** [comment]
My gaming experience decreases vaslty because of this issue.

**Comment by PolarCookie** [comment]
With the same raid setup, it seems to be much worse on gormok than the other ToC bosses.
In my raid I don't see anything anymore (we recently got a new spriest), I mean NOTHING AT ALL.
No haunt, corruption, UA or agony, nothing. Affliction is impossible right now.
The other bosses have varying levels of trouble.
Anub is fine tho, see everything on him.

**Comment by kikomir** [comment]
I've seen this happen only in 25 man raids so I'm just gonna confirm that it *probably* has something to do with the total number of debuffs and that it is making my life miserable as an affliction warlock.

**Comment by Crispybuilt** [comment]
This always happens to us in 25m raids, the target just has too much debuffs and it's impossible to track certain ones (yours) with any kind of addon just because they are not visible.

Not sure if this can be fixed and if the limitation can be increased.

**Comment by robinsch** [comment]
https://github.com/TrinityCore/TrinityCore/issues/17051

On PTR.
