### ISSUE TITLE
[Shaman] Sentry totem and mounting up

### ISSUE THREAD

**Issue by M0dinstaller** [dalaranwow/dalaran-wow#3132]
If you mount up while you have a sentry totem down, you will stop being able to see through it by right-clicking the buff.

I've noticed that putting down a sentry totem gives you not only the sentry totem buff, but also another buff (from the name & icon it seems like either a bug or a makeshift bug fixing). That buff disappears when you mount up.

**Comment by Golganeth** [comment]
Merging with #1301
