### ISSUE TITLE
Raid lockouts bugged

### ISSUE THREAD

**Issue by krellemeister** [dalaranwow/dalaran-wow#3133]
Over the past two weeks I've been in several raids where we did not get locked upon killing a boss. Based on my experiences Vault of Archavon 10 is the worst offender, as it has failed to lock me 4 times in a single week. Another raid this has happened to is Ulduar 25, where it became impossible to zone back in after leaving the instance, as no ID was received. That basically doomed the raid, while giving everyone a second chance to gear up in another raid.

**Comment by sashouktc** [comment]
I even know how this happens. If you wipe on a boss before killing it and you take your corpses by going into the instance there is a good chance (my personal observation, but a fact) that killing the boss will not save you.

**Comment by gotmilk0112** [comment]
This odd bug happens even if you don't wipe. I did a Naxx10 once and we cleared two entire wings, and still did not get saved to the instance.

**Comment by Rushor** [comment]
also happens with Tempest Keep https://github.com/dalaranwow/dalaran-wow/issues/4387

**Comment by plznoz** [comment]
I've seen it happen in ToGC10. You would get an Utgarde Pinnacle hc ID instead of ToGC10 ID for a little while, but would disappear within roughly 30 min of getting it.
