### ISSUE TITLE
Loot lost on Saph

### ISSUE THREAD

**Issue by Skruffy** [dalaranwow/dalaran-wow#3137]
Rolled for the Tank Trinket on 25m saph, but was unable to loot, apparently from a Master Looter change during the fight. This does not make sense. *all other loot was dispersed*
![wowscrnshot_020816_233111](https://cloud.githubusercontent.com/assets/17136983/12908984/456c8548-ceca-11e5-8fc0-9dd57fcb4f5e.jpg)
![wowscrnshot_020816_233112](https://cloud.githubusercontent.com/assets/17136983/12908989/45748ffe-ceca-11e5-991d-e0afc983df98.jpg)
![wowscrnshot_020816_233105](https://cloud.githubusercontent.com/assets/17136983/12908987/457056fa-ceca-11e5-8742-5dc4d894b079.jpg)
![wowscrnshot_020816_233107](https://cloud.githubusercontent.com/assets/17136983/12908985/456d4352-ceca-11e5-8064-0b8d24e81272.jpg)
![wowscrnshot_020816_233108](https://cloud.githubusercontent.com/assets/17136983/12908986/456d6d0a-ceca-11e5-82e7-5fac7b6bd53e.jpg)
![wowscrnshot_020816_233110](https://cloud.githubusercontent.com/assets/17136983/12908988/4570e34a-ceca-11e5-9e57-523e4a31d722.jpg)

**Comment by Golganeth** [comment]
The bugtracker doesn't list this kind of issues, it only lists issues with quests, npc's and such. 
In regards of loot issues send an e-mail to dalaran.community@gmail.com and your issue will be sorted out. Make sure to provide as much info as possible and clear proof/evidence of the problem
