### ISSUE TITLE
Upper Blackrock Spire [Dungeon] / Father Flame [Object] / Solakar Flamewreath [Boss]

### ISSUE THREAD

**Issue by CoFS** [dalaranwow/dalaran-wow#3138]
**Dungeon: Upper Blackrock Spire
Location: The Rookery
Object: 'Father Flame' - Pillar
Boss: 'Solakar Flamewreath'**

http://wowwiki.wikia.com/wiki/The_Rookery
http://wowwiki.wikia.com/wiki/Upper_Blackrock_Spire_(original)

### Currently: 
Looting from the Pillar 'Father Flame' (object) does **NOT** trigger the 'Solakar Flamewreath' boss event. 
(Nothing happens! No boss!)

### How it should work:
Looting from the Pillar 'Father Flame' (object) triggers the 'Solakar Flamewreath' boss event.

http://wowwiki.wikia.com/wiki/Father_Flame
http://wowwiki.wikia.com/wiki/Solakar_Flamewreath

-------------

**Consequently** it boils down to a **Priest problem chain**, here is why:

a) Since 'Solakar Flamewreath' does not spawn, it is impossible to acquire 'Devout Mantle' (*1).

b) Since 'Devout Mantle' is  unobtainable, the quest 'Anthions Parting Words' (*2) cannot be finished with Priests.

c) Since the quest 'Anthions Parting Words' cannot be finished with Priests, the whole remaining Dungeon-Set 2 questchain (*3) cannot be continued/completed with Priests.

d) Since the remaining Dungeon-Set 2 questchain cannot be continued/completed with Priests, the following items are unobtainable: 'Virtuous Crown', 'Viruous Robe', Virtuous Sandals', 'Virtuous Mantle' and 'Virtuous Skirt' ( **=> 5/8 items of the Virtuous-Set (*4) are unobtainable**).

(*1) Dungeon-Set 1 Priest (Shoulder): http://wotlk.openwow.com/item=16695
(*2) Dungeon-Set 2 Quest 'Anthions Parting Words': http://wotlk.openwow.com/quest=9019
(*3) Dungeon-Set 2 Questchain: http://wowwiki.wikia.com/wiki/Dungeon_Set_2
(*4) Dungeon-Set 2 Priest (Set) http://wowwiki.wikia.com/wiki/Vestments_of_the_Virtuous

**Comment by Golganeth** [comment]
Thanks a lot for the detailed report, What you mention is already reported here, though; #1817

**Comment by CoFS** [comment]
Oh shit, is this gonna be fixed anytime soon, because #1817 is from 2014, and still not completed?
