### ISSUE TITLE
The Crown Chemical Co

### ISSUE THREAD

**Issue by ciccioriccio** [dalaranwow/dalaran-wow#3139]
The event Bosses are not in Shadowfang Keep while the event "Love is in the air" is active

**Comment by d157r4c710n** [comment]
Confirmed. The goblin is there and gives the quest "You've been served", as well the Perfume, Cologne, and subpoena required for the quest. Apart from that, the instance is in its normal state with no sign of the chemical co. apothecaries. Unable to complete achievement "Dangerous Love" required for the violet proto-drake as a result. :(

**Comment by sashouktc** [comment]
When I went there yesterday the apothecaries were in there but couldn't be interacted with.

**Comment by Lothloryen** [comment]
Hello there,

Thank you for the report, it was a failure of mine. You can now start the encounter.

**Comment by Lukas45** [comment]
The encounter can be started to get the achievement, but it's not scripted and doesn't drop loot at the moment
