### ISSUE TITLE
Lost in the in-game mail

### ISSUE THREAD

**Issue by tnkrocha1** [dalaranwow/dalaran-wow#3140]
Hi - I hope you can help me.  

I referred a friend to Dalaran-Wow and was granted the X-53 Touring Rocket, however I chose the wrong character by mistake (Sariya) and when it arrived in my inbox, I hit "return" as the item would bind to the wrong character when picked up. Now, of course, it's lost. Would it be possible to send the Rocket to the correct character, Bethia, or recover it somehow? 

I also received two sets of heirloom gear but lost one set when I emailed it to another character.  I would love to be able to recover that second set for Bethia as well.

Thank you for your time and, hopefully, help, and please let me know if you need more information.

**Comment by yellowballonn** [comment]
I GOT SAME PROBLEM. I LOST MY HEIRLOOM

**Comment by yellowballonn** [comment]
GM, please help me, my leather heirloom was not found. a minute ago i create a new character female troll rouge. i sent my heirloom to that account via mailbox. after i play i change my mind, so i sent back my heirloom to my main account again and i delete that account. BUT AFTER I OPEN MAILBOX IN THIS ACCOUNT, THE MAIL ATTACHMENT WAS EMPTY, THERE'S JUST A MONEY ATTACHMENT, pls GM help me recover my item. sorry my english so bad. i hope u reply soon oh GM

**Comment by Lukas45** [comment]
Going from previous ingame issues and their answers I'll just copy what the devs said there.
Open a GM ticket, this a bug tracker and can not be used to resolve ingame issues

**Comment by Golganeth** [comment]
Make an in-game ticket and we'll see what can be done. You should always take any item in your inbox before deleting the character who sent it.

The bugtracker doesn't list this kind of issues, it only lists issues with quests, npc's and such, so closing up.

**Comment by yellowballonn** [comment]
GM NEVER REPLY MY TICKET, AND PEOPLE FORM MY GUILD ALSO SAID, SHE'S PREMIUM USER BUT GM NEVER REPLY
