### ISSUE TITLE
[Quest][Northrend] The Emissary

### ISSUE THREAD

**Issue by M0dinstaller** [dalaranwow/dalaran-wow#3141]
Judging from the [wowhead comments](http://www.wowhead.com/quest=11626/the-emissary#comments), this boss should be "easy".

Quote : "easiest "heres a special item, go kill the big bad" so far :D
[...]
use the trident, and then battle him, hes pretty frickin easy really. scary as all hell when he wakes up but then, wouldn't you be @#$%ed if someone woke you by sticking a fork in you? ;)"

So I think he shouldn't hit you for 33% of your hp in one hit. He hits for 2k on average when at this level you're supposed to be around 6k hp.

**Comment by jonanone** [comment]
The damage will be reduced once impaled. The fix will be applied to the live realm soon.
