### ISSUE TITLE
[Death Knight] Corpse Explosion Animation

### ISSUE THREAD

**Issue by Jkxhrox** [dalaranwow/dalaran-wow#3145]
The animation is still bugged, when you cast it on your pet. It should display the same animation, as your pet counts as a corpse. For PVP Corpse Explosion is the best burst of a dk and it's hard to judge the range of it when it simply disappears. 
Here is a video of Wotlk Retail, showing how it should look on your pet: 
http://www.warcraftmovies.com/movieview.php?id=160057 - Jigs 4 Explodin' on nerds

Not sure, if the Glyph does work correctly as well. Needs more research.

**Comment by Golganeth** [comment]
#2201
