### ISSUE TITLE
Anub spikes hitbox

### ISSUE THREAD

**Issue by Lukas45** [dalaranwow/dalaran-wow#3147]
So I get that you wanted to fix the keyboard turning issue, but this fix seems very similar to your "fix" to the CCable adds. You  could say this is "just because we're bad", but this is not a good/acceptable fix IMHO. Yeah you came up with a fix without gamebreaking the boss, but this is pretty close.
All you did was increase spikes hitbox by around 50%-75%, which is not working very great since the ice trigger hitbox is still the same as before.
Kiting the spikes is now considerably harder due to the increasing speed they now have, mixed the increased hitbox.
When you go on the ice, there's a really high chance that the spikes will still hit you, at least once, maybe twice if they're really fast (from sprint+bop etc) when you're still at the edge due to 80% slow.
If you're at the edge of the ice that the spikes is getting kited around, you will get hit for the full amount (Example - I would have been hit twice if the spikes were to be kited at that path due to the speed after 15 seconds)
![anub spikes](https://cloud.githubusercontent.com/assets/4707702/13061494/85abb336-d438-11e5-8bf5-cbe6caa7038c.jpg)

And to be very honest, I'd rather that you undo your "fix" until you come up with a better solution (like giving them a much greater turn speed) rather than just increasing the hitbox, because it really messes things up.

**Comment by hAkonf** [comment]
And before you could kite it through the patch without it breaking, the fix is much better than before.

**Comment by Lukas45** [comment]
Not something I have ever encountered before from my weekly Anub encounters, but I'd almost prefer that over this though

**Comment by Tarpor** [comment]
Sorry but I've done anub enough after the fix to know that this isnt a real issue. Nobody died from it hitting them in the ice or anything alike, the only time someone died was because of the increased hitbox, which can happen due, but nothing buggy. Even after having kited it across the room and a 10 second bop, nobody actually got hit while on the ice. Maybe you're just too eager and wait too long? 

You state that this isn't a good fix in your opinion, but your opinion doesn't matter. It's a database based on factual information to ensure things work like that they did on retail but you give no information about how it's supposed to be then. Why isn't this the right speed? Maybe it was too slow beforehand and you just got too used to that. Same thing with the hitbox, do you actually have anything?

**Comment by Lukas45** [comment]
The issue is not that we waited too long to go on ice, because we would know if that was the issue.
The issue is that if we're standing on the ice, near the edge (still on the ice mind you), and if the spikes were kite around the ice you were on (like illustrated in the picture), you would get hit by it, while I have no footage of it, it's not that hard to test. 

Regarding the speed, our rogue know, and I know as well from memories, that the spikes could be kited for much longer during Sprint/Dash (example https://www.youtube.com/watch?v=QnNC90O3uU0 - not my footage) - Our rogue got caught sprinting after around 5-6 seconds, despite a proper path around an ice patch.

And you're right, it is my own opinion that this is not a proper fix, but if everything is by fact and not opinions, how are choices made between different fixes?

**Comment by Tarpor** [comment]
Was unclear on your screenshot that you were on the ice. I rest my case. 

Also look we now have videoproof, it seems like the spikes on Dalaran have too much delay in between them popping up, hence the turning is clunky and it was able to be ran around with.

**Comment by Lothloryen** [comment]
Hello there,

Thank you, this issue should be corrected after the next maintenance. Any feedback will be appreciated.

**Comment by hAkonf** [comment]
Just to be clear, what exactly has been changed now?
No damage taken from spikes when you have permafrost debuff?

**Comment by Lothloryen** [comment]
While the players will not be able to avoid the spikes damage by running in circles, the spikes will be working exactly as before.

**Comment by Lukas45** [comment]
Hmm, from a raiding perspective, it did seem like just the damage hitbox was increased by a good amount.
Didn't mean to be rude, but I can only go from observations during a raid, and after the burrowers accident, well yeah.

Any word on when the next maintenance will happen, because it's never says ingame.
