### ISSUE TITLE
Pets on Stormwind ships and Gryphons overshooting Stormwind.

### ISSUE THREAD

**Issue by Arkawn** [dalaranwow/dalaran-wow#3149]
First, I apologize for not recalling the site locations I was travelling to in these bugs.  I have travelled to Darkshore from Stormwind for the "Love is in the air" via ship and each time, my pet drops off the docks and is left behind.  I have tried to "pull" the pet on by travelling higher on the ship but nothing works.

I flew from Ironforge to Stormwind and when I returned from the internet screen swap in flight, I was freefalling to my death.  When I regenned, I was in the graveyard outside of Menethil.

**Comment by Golganeth** [comment]
Pet issue reported here: #3073 

I couldn't reproduce the other issue. Most likely it is related to your graphics and a slow loading of game objects and textures.
