### ISSUE TITLE
irritating bug.

### ISSUE THREAD

**Issue by Zindran** [dalaranwow/dalaran-wow#3154]
I will start out with what happened before this incident: I was tanking in Maraudon(the dungeon, first part), and the server restarted to add Onyxia to the game.
     To my dismay, when the server came back up and I logged back in, I was still in the dungeon, as I am level 39 i was killed by 2 of the monsters inside so I was sent to the graveyard outside of the instance.
     So I walked back to the dungeon and went looking for the entrance to the part of said dungeon and found nothing, so I began to walk back to the Spirit Healer's location and I was dc'd on my way there.
     When I logged back onto the server I was apparently in Eversong Woods in ghost form (Eversong Woods is my race's starting zone.).
     At this point I was irritated more and went to look for a Spirit Healer there and when I went to one of the graveyards there were no Spirit Healers of which to resurrect from.
     So I went to try and get to the portal to the Eastern Plaguelands from Ghostlands and I was not able to enter the portal, to the current moment,(9:57PM PST), I am a prisoner in ghost form to the game.
     If there is anything that can be done about this then I would be ever grateful, my character's name is Sanielor on the realm of Algalon

**Comment by Zindran** [comment]
I eventually found a spirit healer, but I had to wait quite a while for them to appear. I am now able to respawn.

**Comment by Golganeth** [comment]
Invalid report.
