### ISSUE TITLE
Blackrock Depths BUG

### ISSUE THREAD

**Issue by azrielsverrir** [dalaranwow/dalaran-wow#3155]
Ring of Law bug~ NPC who should open the gates started attacking players instead. The NPC became invulnerable and started attacking players. Event stops and Dungeon cannot progress. He shouldnt attack players and he shouldnt be attackable

**Comment by Hazarx** [comment]
I can confirm that it is still bugged. If you don't have any rogue with high skill of lockpick then you will never get a key to go any further. Ring of Law is important part of BRD

**Comment by Lukas45** [comment]
Workaround: Hug the wall at all times to stay out of his aggro range while he's present. Aslong as he doesn't aggro, the dungeon can be completed like normal.

**Comment by Rushor** [comment]
cannot reproduce this anymore
