### ISSUE TITLE
Elemental Invasions

### ISSUE THREAD

**Issue by Klala** [dalaranwow/dalaran-wow#3159]
The whole event is completely missing from the game. I would love to see this work in this server.

http://wowwiki.wikia.com/wiki/Elemental_Invasions

**Comment by gotmilk0112** [comment]
I'd rather the admins focus on fixing the countless bugs and glitches in WOTLK content, instead of implementing vanilla content that almost nobody is going to do.

**Comment by Rushor** [comment]
events are always important :trollface:

**Comment by Rushor** [comment]
fix:

https://github.com/Kittnz/Sunwell/blob/master/sql/events/elemental_invasion.sql

(needs port of the additional sai action)

**Comment by Sagrath** [comment]
Fixed, waiting for further reports
