### ISSUE TITLE
Quest: Changing the Wind's Course

### ISSUE THREAD

**Issue by Sagrath** [dalaranwow/dalaran-wow#316]
Quest: http://www.wowhead.com/quest=13058

Bug: When you use the The Lorehammer (http://www.wowhead.com/item=42918) Stormhoof is being spawned however nothing happens. As result it is impossible to complete this quest.

**Comment by Watterx** [comment]
Still not working..

**Comment by Camarila** [comment]
The NPC is once again unattackable.

At least when using the 'Lorehammer' It correctly turns the user into Stormhoof.

**Comment by deltafoxnine** [comment]
First time i used the Hammer, the NPC wasn't spawned. 

Second time, everything worked as intended

**Comment by aepoirier** [comment]
When I use the Lorehammer, I am immediately able to control Stormhoof, however, North Wind is nowhere to be found. I have tried exiting the vehicle and phasing out of the "timeline", as well as relogging. Still no Wind for me to kill.

**Comment by deasease** [comment]
it works... tho only how... i finally amnaged to hackout how to work with this q
i died 3time, then didnt returned till did all rest q around- now i took my raid and pvp experience, it worked out i used mouse to run around and from him i eventually could use my abilities after used 1st key abiity on him and then run aorund dps him, then when he killed my outter form i continue to tnakspank him(im druid), h died and left horn, it worked

**Comment by fizzl** [comment]
Please re-open still bugged.

Now you get a stormhoof and mount it, but stormhoof is so weak that it is impossible to complete the quest. The abilities do very little damage and The North Wind does so much damage that Stormhoof dies in couple of hits.
