### ISSUE TITLE
Quest: Fueling For The Fire

### ISSUE THREAD

**Issue by gotmilk0112** [dalaranwow/dalaran-wow#3160]
This quest DOES work...however, it's incredibly buggy.

If the abomination goes anywhere near the trolls, it will reset in ~2 seconds and you'll lose control of it.

If any of the trolls aggro to you instead of the abomination, it instantly resets.

This makes the quest frustratingly slow to do, because you can only kill 1 or 2 trolls with each abomination.

**Comment by Golganeth** [comment]
#532

**Comment by Lukas45** [comment]
The easiest way to do this quest is to get a friend to gather up all the trolls for you, and you blow them up when they're near you
