### ISSUE TITLE
Trial of the (Grand) Crusader 25 (Normal + Heroic) Loot Issue

### ISSUE THREAD

**Issue by Crispybuilt** [dalaranwow/dalaran-wow#3166]
**Issue present:** Currently Northrend Beasts, Jaraxxus, Faction Champions and Anub'arak are dropping the incorrent amount of gear items. I am excluding patterns, trophies and crusader orbs from this. So only gear upgrades. This is only for 25 man mode on both normal and heroic.

**How it should work:**
Beasts drop: 2 gear items, they should drop 3
Jaraxxus drops: 2 gear items, he should drop 3
Faction champions drop: 2 gear items, they should drop 3
Anub'arak drops: 2 gear items, he should drop 4

Twins drop the correct amount which is 3

This info comes straight from the live server + since the recent release of Sunwell.pl database, there it seems to work fine.

https://www.youtube.com/watch?v=p541UquLaNE

**Comment by Tarpor** [comment]
Just to clarify, Anub does drop 3 items in 25hc, not 2 as you stated. Seems to be a big issue, maybe this was the case prenerf? I've been trying to look into it and only found 1 real video but they didnt show the loot in that.

**Comment by Crispybuilt** [comment]
Indeed Anub'arak drops 3 items, my mistake there. Though he should drop 4 just like it was on retail.
Just look into it and see if anything can be done

**Comment by sashouktc** [comment]
Not to mention the complete lack of loot tables. 2 items from the same table shouldn't really happen.

**Comment by Crispybuilt** [comment]
Is this going to be fixed any time soon? We're talking here of current end-game content, I'm pretty sure   4 additional items per raid will make all the guilds happy farming Toc

**Comment by Crispybuilt** [comment]
Found a video showing that there are 4 pieces of loot on Anub'arak.
Footage is from retail:
https://youtu.be/-EWFz94HQWI?t=9m13s

**Comment by Lothloryen** [comment]
Thank you for the report, I will take a look.

**Comment by Lothloryen** [comment]
This correction will be deployed with the next scheduled maintenance, thank you very much for the report

**Comment by Crispybuilt** [comment]
Thank you! This will be greatly appreciated from all the guilds, thank you so much.

**Comment by Crispybuilt** [comment]
When can we expect the next maintenance?
We did both 25n/25hc today and the loot was still the same.

**Comment by Crispybuilt** [comment]
Thank you, we got all the loot now today on 25n/25hc. It has been confirmed it is applied on the live server.
