### ISSUE TITLE
Master of Element working when it should not.

### ISSUE THREAD

**Issue by Akkalevil** [dalaranwow/dalaran-wow#3168]
Picture speaks for itself : I'm gaining mana through Master of Elements, but I haven't put a single point in it...
![masterofelements](https://cloud.githubusercontent.com/assets/6848735/13378783/d8ceac16-de11-11e5-9cfe-c730aba13d54.jpg)

**Comment by Tarpor** [comment]
This is with 3/3 Master of Elements, so on top of the 30%, I regain more mana. (a bit below 5% extra)

http://i.imgur.com/b3YOH5U.jpg

**Comment by Rushor** [comment]
This already works fine on PTR. The Master of Element does not procc if you don't have enabled the talent point.
