### ISSUE TITLE
Random arena bugs

### ISSUE THREAD

**Issue by Johanes022** [dalaranwow/dalaran-wow#3172]
Some random arena bugs ive encountered so far are
1) 
Ghost players in 2v2 bracket 
<img src="http://i.imgur.com/fynOUKR.jpg"><img>
making 2v2 match waste of time.After killing the opponents or dying in arena, match wont end.Players who die can release and ressurect.But nobody will win/lose arena rating.The only option here is to relog and leave arena.
2)
After entering arena, you get randomly ported out (you and your team mate) w/o losing or winning arena rating.
3)
Neverending arena start timer - Arena preparation never ends, door doesnt open.Only option is to leave arena.You also wont win/lose arena rating.

**Comment by KerDW** [comment]
I don't think this happens anymore, it used to be a weird bug around 2 years ago. Should be closed unless proof and a way to reproduce it gets posted.

**Comment by Johanes022** [comment]
Yeah , this thread can be closed now since none of this is happening anymore.
