### ISSUE TITLE
Darkmoon Faire not spawning

### ISSUE THREAD

**Issue by tripleslash** [dalaranwow/dalaran-wow#3179]
Hi,

the Darkmoon Faire decided not to visit us this month (maybe all the hate in global made them stay away? :p)

Anyway, can this be looked into?
Greets

**Comment by Tarpor** [comment]
uhh, it was there at the start of the month? You just missed it

**Comment by tripleslash** [comment]
As far as I am aware the Darkmoon announce guy in Orgrimmar is supposed to spawn one week ahead of DMF. I assumed that the faire event was bugged because there was no faire one week later.

**Comment by Golganeth** [comment]
#2849
