### ISSUE TITLE
quest Shipment: Intricate Bone Figure

### ISSUE THREAD

**Issue by medan** [dalaranwow/dalaran-wow#3181]
There is probably phase bug in Storm Peaks. The quest shows the area around 45,60 as place to kill drakes. There should be a lot of drakes flying around, but currently there are no drakes (for me - tested few times). I remember when the server started, it was ok (I started to play here again after two years).
So now you can't do this daily quest easy way, in this area... Also I found that if you fly over those mountanis around (49,59) and you are in "storm peaks" area (phase), you are in correct phase and you can see those drakes. But when you change area, they dissapear. It seems like when you are in "The foot steppes", they dissapear.
There was also an issue with rare drake Viragosa bugged in phase (visible when you are in Storm peaks phase).
And I have to say, I transfered from ally to horde, so there can be some connection with quest lines (less likely I think).

**Comment by Sagrath** [comment]
Finish your quest chains which phase you

**Comment by Dragongl11** [comment]
> Finish your quest chains which phase you

He's right! I got achieve "The Summit of Storm Peaks" and did all the quests there - still trans-phase and in the area The Foot Steppes are not rhinos and drakes, but elite giants. Need to fix it!
