### ISSUE TITLE
[Quest][Northrend] The Lost Mistwhisper Treasure

### ISSUE THREAD

**Issue by Ether009** [dalaranwow/dalaran-wow#3184]
While the bug with being unable to attack Oracle and Frenzyheart directly is annoying, this quest cannot be completed. After getting the treasure and killing Tartek (or killing Tartek and then getting treasure, I've tried both orders), Mistcaller Soo-gan does not accept that the quest is done. This completely blocks progression towards the factions.

**Comment by NovaHiros** [comment]
You can't attack or HARM the frenzy\oracle in any way, you can't AoE them, you can't turn in quests and nothing can be done. This is rep farming, a huge portion of solo playing completely missing (and\or very very buggish). If you can't fix them just put them autocomplete!

**Comment by Ether009** [comment]
Well actually you can attack them with secondary stuff, like hunter pet, elementals, searing totem and so on. That's a completely seperate bug that you can't attack them and has its own issue opened. This is about the quest not being recognized as completed, even if you have the treasure and have killed Tartek.

**Comment by Lothloryen** [comment]
Hello there,

This quest has been corrected and it is already on the live server.

Thank you.
