### ISSUE TITLE
Warrior Cleave

### ISSUE THREAD

**Issue by Zaasu** [dalaranwow/dalaran-wow#3186]
On Algalon the hit boxes seem fairly odd and you often, as a melee, find yourself being either too close or too far away to actually hit your target, most notably with the heart of XT-002 Deconstructor. Of course this is a matter of getting used to a certain boss acting up and simply adapting to it. However, it becomes immensely tricky when you add several targets, and therein Cleave, to the equation. Quite simply Cleave is unable to hit your targets nearest target if not positioned perfectly, which is oftentimes an impossibility due to the odd hit boxes. 

Personally I see the easiest workaround, without affecting game play too much, to be allowing cleave to work in a 360 degree swing from the warrior.

**Comment by Sagrath** [comment]
odd hitboxes?
360 degree? absurd
