### ISSUE TITLE
Cant learn weaponskills.

### ISSUE THREAD

**Issue by tommju** [dalaranwow/dalaran-wow#3189]
I cant learn any 1H weapon skill with my paladin or DK. I have bought the instant 70lvl for my pally, and i think this has something to do with this. Dont please say that ''go and visit the trainer'' because im not a noob with  this game, and ofc i have visited everu weapon trainer in game and still nothing. Stranger it gets, i can equip for example 1H sword, but cant raise the level for the weapon. This is really frustrating, coz i really wanna make prot pally, but with these bugs, can only play with retry... Can u help with this? already made two tickets for this issue, but they just think i cant play the game... Partisaani and Kulinaristi are my char names. Plz

**Comment by Lukas45** [comment]
I assume you were the one asking in Global as well.
Seeing that I /who'd you in Orgrimmar, there is no telling if this is an error on your end.
You're saying you've already learned the weapon skill (1H swords), which should also be the case for BE Paladins since they start with it.
The only way to level the weaponskills is to mobs near your level - training dummys do NOT work for that.

**Comment by tommju** [comment]
Ye, i asked in global. I just cant see those 1H sword or 1h mace skillmeter in my skillsheet, and therefor i cant level those skills up...doesnt matter which kinda mob i try to hit... soooo annoying :/

**Comment by Golganeth** [comment]
Could you provide a screenshot of your skill sheet? Paladins obtain 1h mace/sword skills as soon as they are created, so your issue is very unlikely.

Are you trying to level up your weapons with honorable targets? (those that would grant you experience).

**Comment by tommju** [comment]
I'll try first to download another client, if that would help. Otherwise i send screenshot as soon as possible! Ty ^^

**Comment by tommju** [comment]
![img_1761](https://cloud.githubusercontent.com/assets/18116624/14080930/935adc16-f510-11e5-82d7-84b8f9f88807.JPG)

**Comment by tommju** [comment]
There you go.

**Comment by tommju** [comment]
Now it works!!! it was something to do with the client!!! thx anyway <3

**Comment by Golganeth** [comment]
Alright. Closing up then
