### ISSUE TITLE
Mobs stuck in endless pathfinding

### ISSUE THREAD

**Issue by tripleslash** [dalaranwow/dalaran-wow#3191]
https://db.tt/cuDx3nGZ

See video. Happens a lot.

**Comment by Lukas45** [comment]
Can confirm this is an issue with pets a lot of places, including BGs with buildings like AB and EotS.
Also please fix pet scaling :(

**Comment by tripleslash** [comment]
With the Nostalrius Core being released soon, can we expect a port of their pathfinding system?

**Comment by Rushor** [comment]
moved to https://github.com/dalaranwow/dalaran-wow/issues/1964
