### ISSUE TITLE
Ignis hitbox.

### ISSUE THREAD

**Issue by Akkalevil** [dalaranwow/dalaran-wow#3194]
Ignis' hitbox is far too small. You need to enter deep inside his red circle to touch him, which was not the case on live.

Just look at => https://www.youtube.com/watch?v=L-W4D8zEXUQ this video how the melee can hit from OUTSIDE the red circle (example with the feral at 0:42 or 1:50 who is barely stepping on it or even outside).

This is in insanely infuriating for any melee.

**Comment by sashouktc** [comment]
And actually makes melee a lot worse on Ignis, since you have to lose uptime on boss to avoid aoe.

**Comment by Mazz312** [comment]
Bump since this is still a pretty annoying issue and doesn't seem like a very time-consuming fix.

**Comment by Lothloryen** [comment]
Hello there,

I was at this very moment about to write here, hehe. It has been corrected and it will be applied to the live realm with the next realm restart.

Thank you.
