### ISSUE TITLE
Death Knight Starting Zone -- 3 Issues Total

### ISSUE THREAD

**Issue by rmerges** [dalaranwow/dalaran-wow#3195]
1. Lich King, Prince Valanaar, and other quest givers stand inside of objects they are supposed to be on top of, making clicking on them difficult and sometimes impossible.

2. Koltira drops the Anti-Magic Shield in the Bloody Breakout quest, making the final boss impossible without a party (he does too much damage).

3. Some sort of invisible force instantly killed my character repeatedly in the Death's Breach phase where you turn in the quest "Scarlet Apocalypse." There was some kind of explosion animation nearby, which was perhaps related. I am unable to progress from this point.

**Comment by Golganeth** [comment]
Duplicated. #297 #1744
