### ISSUE TITLE
Character Services 

### ISSUE THREAD

**Issue by revilomoore** [dalaranwow/dalaran-wow#3197]
I am trying to use the faction change on one of my characters but for some reason the only characters that appear are ones I made on the Kirin Tor realm, both of which are under level 3, and my Death Knight (that I don't want to change) on the Algalon realm. Also, when I browse the forums on the dalaran-wow website, I am unable to select any of my main characters to use for my profile. When I select the profile option, it sends me to an error page saying "The page you are looking for cannot be found."

**Comment by Golganeth** [comment]
Invalid report. The bug tracker only lists in-game issues with quests, NPCs and such.

On the side note, the website is being reworked and some features are currently disabled. We shall inform everyone once they are enabled again.
