### ISSUE TITLE
Unable to attack Oracles/Frenzyheart 

### ISSUE THREAD

**Issue by Zaasu** [dalaranwow/dalaran-wow#3199]
There is currently a bug where you're unable to attack Oracles/Frenzyheart throughout the questchain leading up to deciding between the two factions. Even when required by a quest to kill the opposite faction. The mobs still aggro the player.

**Comment by Crispybuilt** [comment]
Confirmed, this bug has been present since like 2 weeks ago. It just says invalid target when trying to attack them.

**Comment by Tarpor** [comment]
A workaround is to do the chicken daily or the treasure daily first. This will grant you rep with the  faction, turning you to hated with the opposing one and being able to attack them for that day. (or logout, haven't tested)

**Comment by Crispybuilt** [comment]
Tried what Tarpor said, didn't work sadly.

Steps I used:
1. Completed the treasure daily from Oracles
2. Went to try to kill some Frenzyheart
3. I was able to target them (with a HP Bar), but whatever skill I tried to use it said: Invalid Target
4. Tried to relog, became even worse, I couldn't see their bars no longer. Still invalid targets.
5. Tried re-taking the quest, same issue.

**Comment by Tarpor** [comment]
Tested it myself, worked differentily from when I did it as said above (July 2015), can confirm that I had the same issue as Crispy.

**Comment by sashouktc** [comment]
You can do damage to them with aoe. That is how I did my quests. Annoying, I know. But it has been that way on every server I've played on so I assume it's not that easy to fix.

**Comment by Crispybuilt** [comment]
What kind of AoE works? I tried Thunderclap/Whirlwind/Flamestrike/Blizzard - non worked.

**Comment by sashouktc** [comment]
Weird. I have a rogue. Fan of Knives works fine. I can't really speak for other classes but people in my guild also completed quests for Oracles with no issues.

**Comment by Golganeth** [comment]
Indeed this new issue seems to have emerged during the last few weeks. It's a slight different issue because it doesn't affect the dailies but the prequests. Looks like an NPC flag issue and occasionally AoE spells or NPCs summoned via quest item/pets allow you to attack them.

Going to merge this with #697.  If you have any other information or different workarounds, please submit them there (#697).

- *Workarounds posted on the old report (may not be working for pre-quests):*

>Turn-in a quest for Oracles and Frenzyheart will be set "at war" until you leave the zone or relog.
>Turn-in a quest for Frenzyheart and Oracles will be set "at war" until you leave the zone or relog.

>If you do first a quest which doesn't require you to kill anything, you will be able to do the other ones flawlessly afterwards.


Closed.

**Comment by Lothloryen** [comment]
You should now be able to attack them, any feedback will be welcome.

Thank you.

**Comment by Zibathy** [comment]
I am unable to attack the Oracles on Kirin Tor. 
![wowscrnshot_041117_143056](https://cloud.githubusercontent.com/assets/7729864/24927188/c06b8dd0-1ec3-11e7-8dc0-9948736a59de.jpg)
