### ISSUE TITLE
Quest:  Dissension Amongst the Ranks...

### ISSUE THREAD

**Issue by Golganeth** [dalaranwow/dalaran-wow#320]
http://wotlk.openwow.com/quest=10776

**Issue:** The provided tabard to complete the quest doesn't disguise the user, and the players are not getting credit upon killing Crazed Colossus.

- **Enchanted Illidari Tabard -** http://wotlk.openwow.com/item=31279
- **Crazed Colossus -** http://wotlk.openwow.com/npc=19823

**Comment by ashido96** [comment]
Make the colossus kills grant credit no matter what until the tabard interaction is fixed?

**Comment by Golganeth** [comment]
Works fine now.
