### ISSUE TITLE
My character get stuck in the air outside of dalaran. 

### ISSUE THREAD

**Issue by oddy555** [dalaranwow/dalaran-wow#3201]
When I want to fly to icecrown sometimes I usually get stuck in the air and can't move. Even if someone summons me I will still be stuck. Only fix is to relog. 

Here's three different instances of when I got stuck. 

![wowscrnshot_040216_111046](https://cloud.githubusercontent.com/assets/5502879/14225453/ad237278-f8c3-11e5-95e2-b5928a6b9db7.jpg)
…]()

![wowscrnshot_020416_205414](https://cloud.githubusercontent.com/assets/5502879/14225441/5ea48f24-f8c3-11e5-8a17-5384cff80634.jpg)

![wowscrnshot_040216_110735](https://cloud.githubusercontent.com/assets/5502879/14225443/66146c3e-f8c3-11e5-802b-0924cd86996b.jpg)

**Comment by Golganeth** [comment]
Duplicated #2878
