### ISSUE TITLE
[Quest] Daily Quest : A blade fit for a Champion

### ISSUE THREAD

**Issue by Crazyphapha** [dalaranwow/dalaran-wow#3206]
I'm currently working on the Crusader title, and I noticed every few days that the faction's main NPC (eg. Marshal Jacob Alerius for Stormwind) would not give any quests. I also noticed that I stopped getting the "A blade fit for a champion" daily after I was done with my home faction, which is coincidentally when this bug started showing up. However, "The edge of Winter" and "A worthy weapon" are still given out.

It looks like the quest is only given by your home faction, which makes grinding for valiant's seals more annoying than it already is.

I am playing a dwarf if that helps.

**Comment by Rushor** [comment]
the questchain works fine for me on ptr. maybe contact a gamemaster to see how your questprogress is and which further quests needs to be done to enable the other quests. thank you
