### ISSUE TITLE
Triggered-on-damage heals & damage

### ISSUE THREAD

**Issue by Golganeth** [dalaranwow/dalaran-wow#3207]
**Issue:** Trigger-on-damage spells will apply heal & damage before the player actually receives damage. Some healing spells become significantly weaker because of this, especially if the affected target is close to full health (resulting in overhealing prior to damage taken).

- [x]  Earth Shield
- [x]  Prayer of Mending
- [x]  Living Seed
- [x]  Thorns (?)

- [x]  Reflective shield:

>Even if there's only 1 HP left on PW:S, it can still reflect back the full amount as if the shield had been at full hp because that calculation is done before the hp of the shield is even checked.

**Comment by LoveDalaranWow** [comment]
This pretty much kills the viability of Holy Priests in most of the content, also drastically reduces the single target healing of Shamans...

**Comment by robinsch** [comment]
1,2,3 on PTR.

**Comment by robinsch** [comment]
Found a way to proc all spells after damage was dealt. On PTR.
