### ISSUE TITLE
[Quest][Northrend] Reconnaissance Flight 

### ISSUE THREAD

**Issue by 1ncredebil** [dalaranwow/dalaran-wow#3211]
#441

Please reopen the quest discussion since I tried completing it twice both times with same negative results. 
First of all, the speed at which the plane is traveling is ridiculous, thus not only making it very irritating, but also close to impossible to accomplish due to your vehicle taking 2% total hp every 2-3 sec and you end up exactly at final coordinates at the last splitsecond (and there should be little tolerance).
Also, the bigger problem is that once the controls of the vehicle are handed to the you, you cannot seem to be able to control the vehicle's height (it is a constant straight line leading to a great height altitude at the final destination, making the "Land vehicle spell" unusable, thus the quest incompletable).

Good news is, everything else about the quest is working properly.
Sorry if I made it sound too complicated : (

**Comment by Lothloryen** [comment]
Hello there,

This quest has been corrected and it is already on the live server.

Thank you.

**Comment by rinleezwins** [comment]
Doesn't seem to be. Just attempted it now, the plane is still slow as hell and I wasn't able to control the plane's height.

**Comment by Golganeth** [comment]
Confirmed that you can't control plane's height, only turn left and right.

**Comment by Rushor** [comment]
speedfix:
UPDATE `creature_template` SET `speed_walk`=10 WHERE  `entry`=28710;

but well the control needs to be fixed first

**Comment by Rushor** [comment]
2c19f7aa61612d1f6c8e2220edcbe3aa7c7972c6
* increase speed for Vic's Flying Machine
* stopcombat after the flight
* updates https://github.com/dalaranwow/dalaran-wow/issues/3211

just found out that you can actually change the high if you use [space]

**Comment by Golganeth** [comment]
Will test later, the current issue didn't let you go down to land. Going up isn't really needed.

**Comment by Golganeth** [comment]
- Visual issues with the way points everytime the plane turns left/right on the way up there.
- When the plane explodes and you control it, it feels very slow unless you press [space]
- You can't control the plane's height unless you press [space] first, you should always be able to control the plane's height.
- Sometimes if you try to control the plane with your mouse it will glitch out and you will only be able to control the plane with arrow keys.
- If the plane dies before you arrive (together with Pilot Vic) you will be stuck in combat. You should die (?) not sure about this one though.

**Comment by Rushor** [comment]
The fixes are working fine, all other issues will be moved to https://github.com/dalaranwow/dalaran-wow/issues/3904

**Updatetext: The speed of Vic's Flying Machine for the quest "Reconnaissance Flight" was increased.**
