### ISSUE TITLE
Quest: The Mist Isn't Listening

### ISSUE THREAD

**Issue by 1ncredebil** [dalaranwow/dalaran-wow#3212]
Hello,

the NPC's that have to be slain for quest
[The Mist Isn't Listening](http://www.wowhead.com/quest=12538/the-mist-isnt-listening) ,
namely [Mistwhisper Oracle](http://www.wowhead.com/npc=28110/mistwhisper-oracle) and
[Mistwhisper Warrior](http://www.wowhead.com/npc=28109/mistwhisper-warrior) cannot be attacked (invalid target).

**Comment by Golganeth** [comment]
Duplicated of #3199

Closed.
