### ISSUE TITLE
[Talent] Aggression

### ISSUE THREAD

**Issue by sashouktc** [dalaranwow/dalaran-wow#3213]
Really not much to say. The Rogue talent Aggression does not properly improve the damage of Eviscerate. The talent is supposed to give 3/6/9/12/15% damage increase to Eviscerate at respective levels. However when I leveled it it resulted in a net increase of 60 damage on both low and top end damage on 5 cp.
ex: 2584 - 3746 without the talent;
2644 - 3806 with it;
Improved Eviscerate grants the appropriate values, which leads me to assume Aggression does in fact add a negligible damage increase to the skill.

**Comment by robinsch** [comment]
Can't confirm. Working fine for me.
