### ISSUE TITLE
I cant login

### ISSUE THREAD

**Issue by xXOnyxiacXx** [dalaranwow/dalaran-wow#3217]
I logged in 30 minutes ago tried to log in again and it said success and stays like that for 2 minutes shows me the realms i click on the realm 30 seconds later it shows me the realm list again wtf is going on why cant i level my character

**Comment by Golganeth** [comment]
Invalid report. The bug tracker only lists in-game issues with quests, NPCs and such.

Clear your Cache folder, make sure your realmlist is correct and that your connection is fine.

Closed.
