### ISSUE TITLE
Netherwing Quest disappeared...

### ISSUE THREAD

**Issue by Pakarax** [dalaranwow/dalaran-wow#3218]
Hello.

Me and my friend were doing quests for Netherwing. So we started this chain, did some quests in a row and now we have the quest, when we have to kill some boss, get the key, and free the dragon. So we did, after letting him free, he took us "on flight" on the ground, then we completed the mission, gained about 49k reputation in Netherwing and that's all. No quests here, nothing. We should get quest to get to the Camp on this flying island, but we didnt recieve it. What now ? We checked all the vendors, even found this flying drake - still no quests. We waited for server shutdown - just to be sure it was something temporary - still nothing after shutdown. What to do now ? We realy want this drake. 

P.S.: We checked that we don't have reputation here "At War"

**Comment by Crispybuilt** [comment]
What is your current reputation with them?

**Comment by Pakarax** [comment]
Neutral 0/3000 , but what happed with this 49k reputation that we got after completing this quest with letting free dragon ?

**Comment by Golganeth** [comment]
Intended behavior. If you can't find the follow-ups, feel free to visit any reliable internet source (WotLK).

Closed.
