### ISSUE TITLE
quest: The Vials of Eternity

### ISSUE THREAD

**Issue by medan** [dalaranwow/dalaran-wow#3219]
Hello, could you please add quest The Vials of Eternity with quest ID 10445 to Soridomi? Curently she offer this quest with ID 13432. The point is that with ID 10445 (which was removed in wotlk) we will be able to complete popular Hand of A'dal achievement.

**Comment by Tarpor** [comment]
Surprise, this is WotLK, so intended and not even close to a bug.

**Comment by medan** [comment]
Thanks for comment Tarpor. I didnt say it is a bug. It is a wish.

**Comment by Tarpor** [comment]
Post it on the forums as a suggestion, this is a bugtracker.

**Comment by Golganeth** [comment]
Not a bug, intended behavior.

Closed
