### ISSUE TITLE
Fishing Issues

### ISSUE THREAD

**Issue by Niaseer** [dalaranwow/dalaran-wow#3220]
Hiya o/

Fishing is somewhat buggy at the moment sometimes when you click the fishing bobber you won't get any fish and then it'll time out leaving the bobber behind; Then if you cast out again you'll have two bobbers up at the same time and either could catch a fish but if the previously bugged one splashes you won't be able to catch the fish.

The speed at which fish are caught seems far too sporadic more so than I remember it being from fishing normally. There is also the issue of the loot window not appearing when the bobber is clicked and then it'll eventually time out.

I hope this information is helpful, please let me know if I need to elaborate further.

**Comment by Tarpor** [comment]
Confirmed, the bobber staying has to do with you moving, you'll just have to wait until that first bobber disappears.

Secondly the issue with no loot window has to do with the bobber being at max range, if it's at max range you won't be able to right-click it.

After having manually fished almost 20000 times farming for my turtle, there is nothing wrong with the timers on fishing.

**Comment by Niaseer** [comment]
Still it isn't a smooth as it is on retail, so I think it's worth looking at again.This is a server which wants to be as blizzlike as possible yes? the fishing is certainly more buggy than retail is.

**Comment by Golganeth** [comment]
Merge #1275
