### ISSUE TITLE
Died in azuremyst isle but respawned in westfall 

### ISSUE THREAD

**Issue by zoraxhelleater** [dalaranwow/dalaran-wow#3222]
I died during a quest in azuremyst isle and when I clicked on "ressurect" I spawned in westfall (eastern kingdoms) even though my body was on the isle in kalimdor, now that is gonna take along time to get back safely.

**Comment by Lukas45** [comment]
That seems to be a common thing when dying from fatigue (don't know if that was the case for you)
For horde, you spawn in The Barrens, no matter where you have died (which I can say from experience after AFKing towards TOC)

**Comment by zoraxhelleater** [comment]
hmmm ok, no it wasnt fatigue it was during combat, but thank you :)
