### ISSUE TITLE
Mark of the wild  BUG

### ISSUE THREAD

**Issue by sean1359** [dalaranwow/dalaran-wow#3223]
Scrolls of in and spirit and other buffs are not stacking properly with MOTW buff instead its being overridden, also other typs of buffs are replaceing it as well

**Comment by hAkonf** [comment]
Scrolls shouldn't stack with other buffs.

**Comment by Crispybuilt** [comment]
This works as intended.

**Comment by Golganeth** [comment]
Intended behavior indeed.

Closed.
