### ISSUE TITLE
Fizzule questgiver for rogue quests is bugged

### ISSUE THREAD

**Issue by KingOfKowz** [dalaranwow/dalaran-wow#3225]
I was doing the level 20 rogue quest line, and it sent me to Taskmaster Fizzule in the barrens. At the end of the first quest that sends you to him, he gives you a whistle that you are supposed to use t make him friendly, but it doesn't work. If I get close, he attacks me, and I wasn't even able to pick up the next quest.

**Comment by KingOfKowz** [comment]
Using the flare gun and saluting like I did the first time, I got it to work, but unfortunately there are a limited amount of charges and you have to do it twice.

**Comment by KingOfKowz** [comment]
Nevermind this, I wasn't aware you had to salute after the two uses of the whistle. Sorry about this

**Comment by Golganeth** [comment]
Closed.
