### ISSUE TITLE
Corruption tooltip ( dmg increase from talents )

### ISSUE THREAD

**Issue by MrAndersonX** [dalaranwow/dalaran-wow#3226]
Hi,

 Well, the skill Corruption ( http://wotlk.openwow.com/spell=47813 ) doesn't seem to have it's tooltip show the dmg increase from the talents Improved Corruption ( http://wotlk.openwow.com/spell=17810 ) and Empowered Corruption ( http://wotlk.openwow.com/spell=32381 ). It shows a little dmg increase from Improved Corruption only for 1/5 rank ( from what I've seen), after which it stops. Is there any hope for a fix ?

**Comment by Rushor** [comment]
clientside issue - this cannot be fixed from serverside - moreover this affects multiple talents in wotlk

**Comment by MrAndersonX** [comment]
So, is there anyway to fix this ? Or is there any client that I can download that will solve this problem ? Since the Dalaren-WoW link for game download doesn't work, I got my client from Warmane. If you could recommend me a client that works properly (a.k.a displays the dmg increase for talents) I would be much obliged.
Thank you.

**Comment by Golganeth** [comment]
Intended behavior. Buff & debuff auras usually never update when modified by talents or glyphs. Your action bar or spellbook tooltips will be reflecting any modification done to the spell.

So to answer your question: check your spellbook / action bar tooltips for accurate damage and modifications. 

/closed

**Comment by MrAndersonX** [comment]
Ok, thank you very much :).
