### ISSUE TITLE
Beer Basted Boar Ribs

### ISSUE THREAD

**Issue by Kalokalo4** [dalaranwow/dalaran-wow#3227]
As a level 5 dwarf hunter (also tried to see if i can at 6) i could aquire the Beer Basted Boar Ribs quest from the NPC Ragnar Thunderbrew in front of the inn in Kharanos in Dun Morogh. No exclamation marks appear and i can not talk to the NPC. I realise that a similar issue was open (#2135) but it was closed a while ago. The quest is not vital, but is is good experience and it is not nice for some new people to see a quest that is not working so early in game. Thank you!

**Comment by Golganeth** [comment]
After some testing I've figured out the quest comes available as soon as you learn 'Cooking'. I wasn't able to find out if this is intended, although I'm gonna assume it's not. Such important requirement would be mentioned somewhere but it's not (wowhead comments, wowwiki...).

For now, just learn 'Cooking' from a trainer to be able to obtain the quest. Going to leave the report open for now.
