### ISSUE TITLE
Incorrect weapon damage after being disarmed.

### ISSUE THREAD

**Issue by rinleezwins** [dalaranwow/dalaran-wow#3229]
I noticed that my weapon damage on the stats panel was wrong sometimes and was wondering what causes it and I finally noticed that it happens every time I get disarmed by a monster.

I am using the heirloom 2H sword, this is the displayed weapon damage after I get disarmed;
![wowscrnshot_041716_202337](https://cloud.githubusercontent.com/assets/12181210/14589463/9369ae06-04da-11e6-8c9d-0e231790112b.jpg)

And this is the correct damage after I re-equip the weapon(that's the simplest solution);
![wowscrnshot_041716_202350](https://cloud.githubusercontent.com/assets/12181210/14589464/9fd0dcbe-04da-11e6-966d-f63a802c1cd4.jpg)

As you can see, the low end damage goes down by a lot and the average damage is lower as a result. I noticed how annoying this is when fighting tar mobs in Ungoro crater - I have to re-equip the weapon every time I kill a mob, that's why I have it on my skillbar.

 I also noticed a similar thing happening with crit chance, when it would go from ~22% to ~12% and I had to fix it be re-equipping my heirloom items with crit on it.

**Comment by Golganeth** [comment]
Duplicated of #1530. 

Closed.
