### ISSUE TITLE
Orgrimmar: Weapon Masters: Will not teach axes

### ISSUE THREAD

**Issue by Klunkejuice** [dalaranwow/dalaran-wow#3230]
I play Paladin (Klunkejuice) on Algalon and can not learn axes in Orgrimmar. The training box is black and if i change filters to available, unavailable or already known nothing happens.

I hope your can fix this bug.

**Comment by Golganeth** [comment]
There's nothing to fix. Make sure you're talking to the correct NPCs. In case you are, it could be a visual bug or an issue with your client. Re-install it if the problem persists.

Both NPCs are working just fine as shown below (in-game ss taken just now):

![image](https://cloud.githubusercontent.com/assets/5057942/14751864/7519d5d4-08cc-11e6-9a1c-b368ce118c71.png)

Closed.
