### ISSUE TITLE
Guardian of Yogg-Saron - Dominate Mind (Dispel)

### ISSUE THREAD

**Issue by tonibgd** [dalaranwow/dalaran-wow#3232]
How it is now:
After purging Dominate Mind of a player the debuff is successfully removed but the player does not regain control over his character for some time (character keeps running like he is still mind controlled).

How it should be:
Purging Dominate Mind of a character should give player back control over it.

Source:

wowhead comments:
http://www.wowhead.com/spell=63042/dominate-mind#comments

TankSpot's Guide::
https://www.youtube.com/watch?v=SFyaloBG7SI&feature=youtu.be&t=1m10s

**Comment by LoveDalaranWow** [comment]
Actually, if you are a warrior or a feral druid who can charge, if you use one of those movement displacing abilities after being mind controlled the character runs to the place you've been mind controlled at the beginning. This persists through death and can only be reset by relogging (/reload doesn't work). This is a huge problem for the classes mentioned before when fighting Yogg.

**Comment by Swork91** [comment]
I've noticed Blackheart the Inciter in Shadow Labyrinth's  Mind Control has the same problem or at least similar. 

After his mind control ends and even after the boss is dead I still seem to be leashed to the location where the boss was. When ever I get too far away I get forced to run back to one location. Video of it here: https://youtu.be/ucQd_osXUkM

On Yogg This actually caused me to run from the brain room, back to the main room, through the ceiling and then go insane.

**Comment by Golganeth** [comment]
#1451 #3485
