### ISSUE TITLE
Murkdeep 

### ISSUE THREAD

**Issue by moodyblues4me** [dalaranwow/dalaran-wow#3233]
The quest [http://wotlk.openwow.com/?search=murkdeep#quests](url). When completing this quest, Murkdeep was down to approximately 50% health when it suddenly disappeared. It didn't go below the ground level, simply disappeared.

**Comment by sixele** [comment]
["It was most likely an issue with NPC/pathfinding but his spot is correct and the quest itself works fine."](https://github.com/dalaranwow/dalaran-wow/issues/3097)

**Comment by Golganeth** [comment]
Currently it seems the event doesn't work as intended. I found some issues, let me shed some light.

- The event consists of three waves of NPCs (3x coastrunners // 2x warriors // 1x hunter 1x Murkdeep, respectively).
- The first wave takes a bit too long to spawn (roughly 1 minute after you clear the camp).
- The waves should spawn near the water and slowly head towards the camp. Currently they just spawn in the same spot and don't move at all.
- If not killed fast enough, the waves will briefly stack on top of each other until the previous one despawns. The next wave shouldn't spawn unless the previous one has been killed.
- The waves seem to have specific spawn & despawn timers. Once their despawn timer hits, they will disappear no matter what, even while fighting them.

**Comment by Lothloryen** [comment]
This was fixed already.

Thank you.
