### ISSUE TITLE
Everlook Alliance Flight Master

### ISSUE THREAD

**Issue by SoundwaveAU** [dalaranwow/dalaran-wow#3235]
Despite tagging her, the flight master at Everlook in Winterspring gives a message saying "You don't know any flight locations connected to this one." when trying to travel somewhere from there, and in turn no flight master in Kalimdor is able to travel to Everlook.

**Comment by Golganeth** [comment]
Make sure you discover the surronding fly paths or you won't be able to fly from/to certain areas. It works as intended.

Closed

**Comment by SoundwaveAU** [comment]
Do you think I'm an idiot? :/

I have most of the flight points in Kalimdor from Silithus to Rut'theran Village. This one particular flight point at Everlook is NOT CONNECTED to any of those.

**Comment by Golganeth** [comment]
This is one of many similar threads that I could find: [click me](http://us.battle.net/wow/en/forum/topic/2228417764)

Make sure you've learned ALL the required paths and they'll get connected with each other.

Thanks
