### ISSUE TITLE
Voidwalker (Warlock pet)

### ISSUE THREAD

**Issue by moodyblues4me** [dalaranwow/dalaran-wow#3236]
At 15,33 by Raven Hill Cemetary (Darkshire), the voidwalker would all of a sudden, go to the nearby tomb while in passive mode. It would also go underground for no reason. It will also not consume shadows automatically. It must be done manually by right clicking the consume shadows icon. I believe there are serious problems with the voidwalker pet....

**Comment by Sagrath** [comment]
Incorrect report, there is no such thing that voidwalker walks around by it self as for its spell if confirmed needs a proper report
