### ISSUE TITLE
[Warlock][Pets] Felguard and Felhunter Base Damage and Base Stats

### ISSUE THREAD

**Issue by Crispybuilt** [dalaranwow/dalaran-wow#3237]
**Issue present:** The base damage of the Felguard and Felhunter is currently not scaled properly. 
**How it should work:** The base damage should have a bit higher value to be more blizzlike.
This info has been taken from the sunwell core as well and there it seems to work fine.

A possible fix for this would be this:

---
- ```
          float level_scale = level / 80.f;
          level_scale = level_scale*level_scale*level_scale;
          case NPC_FELGUARD:
          {
              SetBaseWeaponDamage(BASE_ATTACK, MINDAMAGE, (412.5f - 412.5f/4.0f)*level_scale);
              SetBaseWeaponDamage(BASE_ATTACK, MAXDAMAGE, (412.5f + 412.5f/4.0f)*level_scale);
  
  
              break;
          }
          case 417: //NPC_FELHUNTER:
          {
              SetBaseWeaponDamage(BASE_ATTACK, MINDAMAGE, (309.6f-309.6f/4.0f)*level_scale);
              SetBaseWeaponDamage(BASE_ATTACK, MAXDAMAGE, (309.6f+309.6f/4.0f)*level_scale);
              break;
          }
  ```

---

Pets.cpp file

**Comment by Crispybuilt** [comment]
Also fix for the Base Stats:

              UPDATE world.pet_levelstats
              SET hp=4788, mana=1559, armor=7782, str=314, agi=90, sta=328, inte=150, spi=209
              WHERE level=80 and creature_entry=417;

**Comment by Rushor** [comment]
soncerning the baseattack:
http://rawr.codeplex.com/sourcecontrol/changeset/view/53352#Rawr.Warlock/Pets.cs

```c++
public Felguard(CharacterCalculationsWarlock mommy)
            : base(
                mommy,
                1820f, // baseHealth,
                11f) { // healthPerStamina

            BaseMeleeDamage = (410f + 627f) / 2f;
            DamagePerAttackPower = .187f;

            SpecialCooldown = 6f;
        }
```

the basedamage should be caluclated like this:

mindamage: 410
maxdamage: 627

Attackpower:
AttackPower 57% SP (from WLs) to AP + 2xStr (des Pets)

The baseattackpoweer without any buff to the pet or the warlock should be 20!

The AP-Koeffizient should be 14 %.

Example for mindamage with 0 sp and 314 str.:
410+0,14*(314*2-10) = 496,52

**Comment by Rushor** [comment]
added a more generic one like that now:

```c++
diff --git a/src/server/game/Entities/Pet/Pet.cpp b/src/server/game/Entities/Pet/Pet.cpp
index f27253f..630ab02 100644
--- a/src/server/game/Entities/Pet/Pet.cpp
+++ b/src/server/game/Entities/Pet/Pet.cpp
@@ -972,9 +972,33 @@ bool Guardian::InitStatsForLevel(uint8 petlevel)
 
             SetBonusDamage(val * 0.15f);
 
-            SetBaseWeaponDamage(BASE_ATTACK, MINDAMAGE, float(petlevel - (petlevel / 4)));
-            SetBaseWeaponDamage(BASE_ATTACK, MAXDAMAGE, float(petlevel + (petlevel / 4)));
-
+            switch (GetEntry())
+            {
+                case 17252: // NPC_FELGUARD
+                    SetBaseWeaponDamage(BASE_ATTACK, MINDAMAGE, float(petlevel * 4.112f));
+                    SetBaseWeaponDamage(BASE_ATTACK, MAXDAMAGE, float(petlevel * 6.187f));
+                    break;
+                case 1860: //NPC_VOIDWALKER
+                    SetBaseWeaponDamage(BASE_ATTACK, MINDAMAGE, float(petlevel * 3.375f));
+                    SetBaseWeaponDamage(BASE_ATTACK, MAXDAMAGE, float(petlevel * 5.175f));
+                    break;
+                case 417: // NPC_FELHUNTER
+                    SetBaseWeaponDamage(BASE_ATTACK, MINDAMAGE, float(petlevel * 3.075f));
+                    SetBaseWeaponDamage(BASE_ATTACK, MAXDAMAGE, float(petlevel * 4.725f));
+                    break;
+                case 1863: //NPC_SUCCUBUS
+                    SetBaseWeaponDamage(BASE_ATTACK, MINDAMAGE, float(petlevel * 4.675f));
+                    SetBaseWeaponDamage(BASE_ATTACK, MAXDAMAGE, float(petlevel * 6.85f));
+                    break;
+                case 416: // NPC_IMP
+                    SetBaseWeaponDamage(BASE_ATTACK, MINDAMAGE, float(petlevel * 3.8f));
+                    SetBaseWeaponDamage(BASE_ATTACK, MAXDAMAGE, float(petlevel * 5.725f));
+                    break;
+                default:
+                    SetBaseWeaponDamage(BASE_ATTACK, MINDAMAGE, float(petlevel - (petlevel / 4)));
+                    SetBaseWeaponDamage(BASE_ATTACK, MAXDAMAGE, float(petlevel + (petlevel / 4)));
+                    break;
+            }
             //SetModifierValue(UNIT_MOD_ATTACK_POWER, BASE_VALUE, float(cinfo->attackpower));
             break;
         }
```

the db changes were also added @Crispybuilt 

Game/Pet: Felguard, Felhunter, Voidwalker, Succubus, Imp Base Damage and Felhunter Base Stats

* closes https://github.com/dalaranwow/dalaran-wow/issues/3237
* commit: 1a7ad847ce6e8b07fdc7c939f1428d3740ff7ed7

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
