### ISSUE TITLE
Druid spell bugged: Ferocious Bite

### ISSUE THREAD

**Issue by mimi530** [dalaranwow/dalaran-wow#3239]
Druid's spell (**_Ferocious Bite_**) is bugged. Actually its cost. The skill should cost **35 Energy**, But it costs more. Even when I use **_Berserk_** to reduce the cost, it doesn't work. After using **_Berserk_** it should cost **17 Energy** but it doesn't... It's something about **50 Energy**. Its very difficult for me to do high dps with an issue like that one because I don't have any energy left after a 10s. And there's still 10s of **_Berserk_** left but then i don't have any energy to do more dps. I'm surprised that it hasn't been reported yet. Please fix this and make my life easier :)

**Comment by Lukas45** [comment]
Working as intended, read the spell tooltip.
Ferocious Bite - Rank 8
35 energy - 5 yd range
Instant
Finishing move that causes damage per combo point **and converts each extra point of energy (up to a maximum of 30 extra energy)** into XX additional damage. Damage is increased by your attack power.

**Comment by Golganeth** [comment]
What @Lukas45 said. Please read your spells' tooltips before opening bug reports. If you don't know how to manage your energy, read guides.

Closed.
