### ISSUE TITLE
Druid's Tiger's Fury bug snapshotting

### ISSUE THREAD

**Issue by wawa1234** [dalaranwow/dalaran-wow#3241]
The Tiger's fury spell doesn't work as intended, the effect should increase the damage of dot but it literally doesn't do anything.

I'm new to the server so i'm just lvl 57 at the moment, but my rake does 152 dmg per proc before tiger fury, then I re-apply tiger's fury an trigger rake again and there's no dmg increase. 

Same for Rip and pounce, basically every dot. it's quite huge for pvp and pve in terms of damage upgrade since it can snapshots and bring a new mechanic to the druid. 

thanks for reading.

**Comment by Golganeth** [comment]
All the sources I've been able to find claim that using TF while a bleed is up shouldn't affect its damage at all.

One of the **[examples](http://www.mmo-champion.com/threads/1432256-Rake-Rip-affected-by-Tigers-Fury)**:
> Though it may be obvious I feel it needs to be said - you have to reapply those abilities while Tiger's Fury is active to receive the bonus. And they will maintain that bonus until reapplied or they fall off.

Closed
