### ISSUE TITLE
NPC pets - infinite chase

### ISSUE THREAD

**Issue by moodyblues4me** [dalaranwow/dalaran-wow#3243]
Crawler http://wotlk.openwow.com/npc=6250

Anytime you go to the beach/sea area and pass within aggro range of a murloc with a pet crawler, the crawler will never loose aggro. If more than one, they will follow you until you kill them. Have gone from beach to fly point with 2 in trail. Had to kill before flying.

**Comment by Lukas45** [comment]
Tested and confirmed.

The exact mob in question is Crawler (http://wotlk.openwow.com/npc=6250) which is summoned by a Murloc Hunter (http://wotlk.openwow.com/npc=458). It will continue to pursue until killed or combat is hard-reset.
![8c59f1a3fee2da712fcb3e5e71d3b536 1](https://cloud.githubusercontent.com/assets/4707702/14830099/3543d452-0bef-11e6-8add-e43cb4745552.jpg)
You can see on the leftside minimap my run path, which is pretty farm from the beach (outside of grid range of the Murloc Hunter), and I do not have any reflect damage buffs which could cause a mob to hunt you for longer than the default pursue range.

**Comment by Golganeth** [comment]
This used to happen with some NPC pets in the past but it got fixed. I've tested few ones but they work fine, except this one. Confirmed

If you find any other NPC pets with this behavior submit it here

**Comment by Rushor** [comment]
a6bc9be29d98e05b966122d6bc94648838934eb8
DB/Creature: Crawler - Remove infinite chasing

* closes https://github.com/dalaranwow/dalaran-wow/issues/3243

**Comment by PSAlias** [comment]
Issue persists with **Dalaran Conjuror** (_ID: 1915_) NPCs - their summoned **Voidwalker**(_ID: 1860?_) minions pursue indefinitely. (Spell **Summon Voidwalker** (_ID: 12746_))
Here's one I dragged to UC:
![vwbug](https://cloud.githubusercontent.com/assets/18348509/15985423/a7ec6914-2fa9-11e6-9451-778eeddf39b2.jpg)

**Comment by Rushor** [comment]
4b8394a390e8e10bfd907162f6b5f376bfa361a1
- Voidwalker(ID: 1860?) will also no longer chase infinitly
- testable on ptr

**Comment by PSAlias** [comment]
Fizzle Darkstorm's (NPC ID: 3203) Summon Imp (Spell ID: 11939) spell summons an Imp Minion (NPC ID: 12922) that will sometimes infinitely chase. Unlike the voidwalker above, the imp minion does evade when the player moves far enough away from the summoner, but it does not exit combat with the player or return to its original position. This does not happen every time, suspect it only happens when the imp has already been pulled and then successfully evaded combat once.
