### ISSUE TITLE
Steamwheedle guards not attackable when defending

### ISSUE THREAD

**Issue by Lukas45** [dalaranwow/dalaran-wow#3246]
The Steamwheedle guards (Booty Bay/Everlook/Gadgetzan/Ratchet) guards are not attackable when they attack you in defence.
This is a recent change and not sure if this is intended.

When you attack someone in one of the Steamwheedle towns, the goblins will start to attack you, as they should. When you try to attack them, you will get "Invalid Target" error, while they're hitting you. You can not harm them yourself in any way, either through auto-attacks, spell casts or AOE
![b74d3f9337688efacbd17db43859a9d7 1](https://cloud.githubusercontent.com/assets/4707702/14833131/f57e933e-0bfd-11e6-85c5-ab1e14214b1e.jpg)
You can however harm them with pets that are on defensive, or through reflect damage (Thorns, Ret Aura, Fire Shield etc).
You can still attack them normally if you mark them At War.

This is not a super huge deal, since they don't hit more than 70 per hit any of the places (on cloth), which doesn't seem right either.
But I would rather have their damage upped so they're an actual threat and have them attackable, than the current where they're just a minor annoyance, or at very least have them attackable again so you can get rid of them without running from them.

**Comment by Golganeth** [comment]
Confirmed. Merge with #1677
