### ISSUE TITLE
[Engineering] Rocket Boots Xtreme

### ISSUE THREAD

**Issue by Morden21** [dalaranwow/dalaran-wow#3247]
http://wotlk.openwow.com/item=23824
These boots normally give around a 300% speed boost for 3 seconds, but instead they give a "Spell is not ready yet" message when used. 
The cloth version (http://wotlk.openwow.com/item=35581) may also be broken but i don't have the recipe so i cant confirm that.

**Comment by Coolkira** [comment]
Confirm,broken both.Was making cloth and leather no effects just cd on use  .  it should be fix,50% of engineering is not working  its very useful prof. not only for using 400+.

**Comment by mniamrodzynka** [comment]
Same with the Gnomish Shrink Ray. The dev team doesn't seem to care about engineering.

**Comment by Sagrath** [comment]
Confirmed

**Comment by robinsch** [comment]
On PTR.

**Comment by TeridanDW** [comment]
Works as intended on ptr.
