### ISSUE TITLE
Children's Week - Oracle Child

### ISSUE THREAD

**Issue by phurios** [dalaranwow/dalaran-wow#3250]
Hello

I am sending this just because the quest "Meeting a Great One" of the event doesn't complete, whatever i do. Can you solve the issue?

Best Regards
Ragios

**Comment by adytzyca** [comment]
I have the same problem,i'm getting credit for the "Lordaeon throne room" but i cant turn it in to the orphan

**Comment by sixele** [comment]
Same for "The Biggest Tree Ever!"

**Comment by phurios** [comment]
nope i did the biggest tree ever

**Comment by Lothloryen** [comment]
Hello there,

Try it now and give me feedback about it, please. It should be fine after this morning's maintenance.

Thank you.

**Comment by Lothloryen** [comment]
Closing this, it was already fixed.

Thank you.
