### ISSUE TITLE
Hunter cant equip ammo

### ISSUE THREAD

**Issue by ChristmasK** [dalaranwow/dalaran-wow#3252]
Hello,

My hunter is unable to equip any type of ammo which results in my hunter not having any range capabilities. my arrows and bullets show up as "?" in my bags and tell me that i cannot equip them. my characters name is Christmask- lvl 5 orc hunter. can this issue be fixed?

**Comment by Golganeth** [comment]
Invalid report. The bug tracker only lists in-game issues with quests, NPCs and such.

A lot of people with modified clients (models, visuals from other expansions) seem to have this. Get the normal 3.3.5 client and it will work.

Closed

**Comment by ChristmasK** [comment]
Hello, 

I actually have the 3.3.5 client. Any chance you might have another idea on how to make it work?

**Comment by Jemaris** [comment]
I have the same issue and confirm I have to correct 3.3.5 client. Please help us lowbie Hunters.
