### ISSUE TITLE
Freezing Arrow Bug

### ISSUE THREAD

**Issue by Tritonek** [dalaranwow/dalaran-wow#3254]
Hello.

There is an issue with hunter's ability "Freezing Arrow". It is about that when the ability is used, the trap disappears right away. It is not a big problem for PVE players, but for those who are focusing on pvp (including me) it is a huge trouble.

Could you have a look at it, please?

Regards,
Furax :)

**Comment by RazerStylehunter** [comment]
Can confirm,  tried it on a lv19 wolf in darkshire ,   no trap  shows up, once the arrow hits the ground it just disappears.

**Comment by Lothloryen** [comment]
Hello there,

This issue was generated few days ago with one of the latest maintenance - it is already corrected and it shall be deployed with tomorrow's morning maintenance.

Thank you.
