### ISSUE TITLE
[Tempest Keep - The Eye] Kael'thas Sunstrider Mind Control

### ISSUE THREAD

**Issue by Tarpor** [dalaranwow/dalaran-wow#3257]
### How it is: 
**Kael'thas Sunstriders**' _id:19622_ Mind Control _id:36797_  is affecting the entire raid (party of 3 confirmed, Urek y u die??) as seen on http://imgur.com/j2c57C8.

### How it should be:
The **Mind Control** _id:36797 should only affect 1 member of the raid. 

This bug makes the boss unkillable.

**Comment by Tarpor** [comment]
Only Mind Controls one person since the maintenance. Could not test if Mind Control is dispellable, as nobody in the raid could use a dagger and cast abilities.

**Comment by Lothloryen** [comment]
Corrected then.
