### ISSUE TITLE
Quest marker incorrect

### ISSUE THREAD

**Issue by bobbyboy04** [dalaranwow/dalaran-wow#3259]
The quest "Hidden Enemies" asks you to get an insignia from a mob. The map marker for the quest is around 41.26 in Durotar, but it should be inside the cave at skull rock near 54.11. This is the first part of a chain of quests that end in Ragefire Chasm.

**Comment by Sagrath** [comment]
Confirmed also the quest text mentions skull rock, tho both places have burning blade members

**Comment by Sagrath** [comment]
Q ID 5726

**Comment by Rushor** [comment]
these issues are blizzlike

questpois were bruteforced during wotlk

another example for this http://wowwiki.wikia.com/wiki/Quest:Bring_the_End

> Oddly enough, the objective location is displayed as being in Tirisfal Glades near Agamand Mills on the world map.
