### ISSUE TITLE
[Quest] - Stinglasher

### ISSUE THREAD

**Issue by DrFuler** [dalaranwow/dalaran-wow#3261]
Quest: http://www.wowhead.com/quest=7731/stinglasher
NPC: http://www.wowhead.com/npc=14661/stinglasher

Simple quest in Feralas, you simply need to kill the NPC and loot a quest item from it. However, the NPC seems to be impossible to find. I've used a macro with "/tar Stinglasher", and have found him around the entrance of the eastern hive, however I cannot actually spot him.

While targeting him, I ordered my pet to attack. It just faces a position, and activate its Rabid, but doesn't even move towards the target. I'm concluding then that the NPC Stinglasher is stuck somewhere unreachable. Taking in consideration the position my pet faces when I order it to attack from multiple angles, it seems to me that the NPC is stuck just by the entrance of the eastern hive.

I should also point out that this is not my first time searching for it, and I have searched for quite a while in the past, never to succeed.

All of this evidence makes me believe that this quest can't be completed as it is.

**Comment by Rushor** [comment]
he has some waypoints and actually dropps below the texture, if he starts walking around the cave.

**Comment by Lothloryen** [comment]
Thank you, I have corrected the issue with the waypoints.

**Comment by DrFuler** [comment]
Glad to know it is working now :) (just completed this quest) Thanks for the help!

**Comment by Golganeth** [comment]
It still falls down to textures a lot. The spawn location (at the entrance of the cave) seems to cause this.

**Comment by Ermingske** [comment]
Stinglasher bugs out at his spawn point, he's hidden somewhere, you can only target him with a macro but you can not attack him and he won't move

**Comment by Rushor** [comment]
adding UNIT_STATE_IGNORE_PATHFINDING should help here

**Comment by Rushor** [comment]
5fdf90bf60a8d8e247b30fe1781982965053362b
DB/Creature: Stinglasher

* remove waypoints again
* add CREATURE_FLAG_EXTRA_IGNORE_PATHFINDING
* closes https://github.com/dalaranwow/dalaran-wow/issues/3261

reason for the remove of the waypoint: they create more issues than beeing usefull at all

**Comment by beregas** [comment]
I cannot reach the mob

**Comment by warcraftgeekygamer** [comment]
As of March 11, 2017 this quest is still bugged. I have used a macro with "/tar Stinglasher", and have found him around the entrance of the eastern hive, however I cannot actually spot him.

**Comment by Rushor** [comment]
The fix for it is still active on PTR. I will move it to "Waiting for changelog" so the fix can be reapplied on live again. Thanks.

**Comment by notbetatester** [comment]
Stinglasher still bugged.

**Comment by GeorgeZip1** [comment]
Yes still bugged. Can /tar Stinglasher at the spawn point but can't see and can't attack.
