### ISSUE TITLE
[Hunter] [Spell] Steady shot wrong haste scaling etc.

### ISSUE THREAD

**Issue by RazerStylehunter** [dalaranwow/dalaran-wow#3262]
**Issue Present 1:** The base 15% haste for hunters are not properly calculated when a hunter is casting Steady shot. From both [http://wowwiki.wikia.com/wiki/Steady_Shot] and [http://wow.gamepedia.com/Steady_Shot] along with a lot of online guides, one can see that Steady shots casting time for a hunter (not BM) with 0 haste should be 2/1.15=1.739 sec, however, on the server this is not the case:

Proof: 
![steady shot haste](https://cloud.githubusercontent.com/assets/13498374/14946895/b58b1766-0fef-11e6-95ee-c26b0d71a02a.png)

With 2.07% haste my actual steady shot casting time is 1.78 seconds despite the tooltip saying that it should be 1.7 (if you round it up by using the correct formula 2/1.15/1.02=1.7038 sec)

With 5 points in Improved aspect of the hawk procing my actual steady shot casting time is 1.61 sec, which is 0.1 secs longer than what a 0 haste hunter should have (which is 2/1.15/1.15=1.51 sec)

Why is this 0.1 sec a big deal?   Since BM is not viable for raiding and SV has way too many issues on the server itself, MM hunters are the only option.  The common rotation with Chimera+Aim+SteadyX4 runs on a 10 second rotation which if the haste scaling for steady shot is correct it would be 9.956 seconds total, which matches with the 10 second cooldown of chimera and aimed (0 haste). Without the proper haste application this usual rotation would run for 10+ seconds thus a MM hunter would suffer a DPS loss from not being able to fire Chimera off CD and eventually snowball down the road for long fights. For BM hunters its even worse, that means that they might not be able to reduce their steady shot within the GCD, which is a significant DPS loss. 

**Issue Present 2:**  Pet HP scaling is completely absent. 

Proof: 
![pet scaling](https://cloud.githubusercontent.com/assets/13498374/14946945/888c63d6-0ff0-11e6-9747-2cf1241f3b3e.png)

My pet's stamina is still 906 and has the same HP of 11194 regardless of taking 1 point in Wild Hunt or not, I did make sure to re-summon my pet before and after taking up the talent points. Might not be a huge issue for PVE but for PVP hunters it is.

**Other issues remaining to be fixed which I have tested and confirmed:**
Freezing Arrow Bug: #3254 , Basically puts hunters as the worst PVP class now, also just hunter traps in general, see issue: #3026 
Hunter 2 piece T9 set bonus: #3017 , our increase crit dmg talent not properly applied, dps loss.

With pet scaling an issue at large for BM and SV talent bugs consistent throughout fixes,  hunter as a class from my point of view is an extremely buggy class, all of which leads to negative performances either in PVE or PVP.  would be great if you guys can look into this. 

I am open to corrections if above i got anything wrong. Cheers. 
#3254 #3026 #3017

**Comment by Winstrol** [comment]
Can confirm everything in here.

**Comment by Crispybuilt** [comment]
Can confirm as well what it was said.

**Comment by seork** [comment]
can confirm as well tested it with different weapons as well

**Comment by PolarCookie** [comment]
me and seork did some testing, and here's what we found

0	| 1,804	| 1,634	| 1,7391304348	| 1,5122873346
--- | --- | --- | ---
50	| 1,784	| 1,617	| 1,7130095211	| 1,4895734966
89	| 1,769	| 1,604	| 1,6931736032	| 1,4723248724
139	| 1,751	| 1,588	| 1,6684051187	| 1,4507870597
208	| 1,726	| 1,566	| 1,6353910799	| 1,4220791999
253	| 1,71	| 1,552	| 1,6145551233	| 1,4039609768
302	| 1,694	| 1,538	| 1,5924626349	| 1,3847501173
334	| 1,683	| 1,529	| 1,5783583437	| 1,3724855162
377	| 1,669	| 1,517	| 1,559794501	| 1,3563430443
440	| 1,65	| 1,5	| 1,5333715234	1,3333665421
485	| 1,636	| 1,488	| 1,5150395047	| 1,3174256563
522	| 1,625	| 1,478	| 1,5002916853	| 1,3046014654
814	| 1,544	| 1,408	| 1,3932589044	| 1,2115294821
997	| 1,5   	| 1,369	| 1,3336315939	| 1,1596796469
1837 | 	1,395	| 1,278	| 1,1146615902	| 0,969270948

**Comment by seork** [comment]
Checked out if the weaponspeed had an effect on the steadyshot. did not matter. 
PS the above values have been gotten by using weapons with an internal speed of 2.80 just to exclude any possiblity of it effecting our results.

**Comment by Rushor** [comment]
the reason for the issue:

For the basecalculation it should take 1.5 seconds indeat of 2 seonds

Proof:
1 . Hunter with Auto Shot: 1.8s (should be 2 / 1.15 = 1.74 )
-> 1,5 / 1,15 = 1,3043478260869565217391304347826
1,5 - 1,3043478260869565217391304347826 = 0,19565217391304347826086956521739 // Casttime reduce cuz of haste
2 - 0,19565217391304347826086956521739 = 1,8043478260869565217391304347826 (=1,80s)
correct

2. Hunter with .unaura all (without Auto Shot) and with Serpent's Swiftness: 1.75s (should be 2 / 1.2 = 1.66)
-> 1,5 / 1,2 = 1,25
1,5 - 1,25 = 0,25 // Casttime reduce cuz of haste
2 - 0,25 = 1,75s
correct

3. Hunter with Auto Shot and Serpent's Swiftness: 1.59s (should be 2 / 1.15 / 1.2 = 1.45)
1,5 / (1,15 * 1,2) = 1,0869565217391304347826086956522
1,5 - 1,0869565217391304347826086956522 = 0,41304347826086956521739130434783 // Casttime reduce cuz of haste
2- 0,41304347826086956521739130434783 = 1,5869565217391304347826086956522 (=1,59s)
correct

4. HT (ist 1,653, Soll: 1,538)
1,5 / 1,3 = 1,1538461538461538461538461538462
1,5 - 1,1538461538461538461538461538462 = 0,34615384615384615384615384615385 // Casttime reduce cuz of haste
2 - 0,34615384615384615384615384615385 = 1,6538461538461538461538461538462 (=1,653s)
correct

So the basetime is 1.5 seconds, but for unkown reason there will be a hidden additional 0.5 sec timer which increases the basetimer to 2 seconds


TODO: basecalculation should be 2 seconds

**Comment by robinsch** [comment]
On PTR.

**Comment by Winstrol** [comment]
has this been applied yet? still getting wrong cast time on steady

**Comment by Rushor** [comment]
only on ptr atm

**Comment by fsironman** [comment]
How about you only close the Bugtrack once it is implemented on the Main Realm* so the majority of the Players can actually check and you save work by not having to answer countless is it applied yet questions.

*(Or Label it with "Implemented on Main Realm" or sth. like that)

**Comment by Rushor** [comment]
yeah maybe, i will propose that

**Comment by MrAndersonX** [comment]
Alot of pet talents are still bugged, waiting for the changelog to be applied to the live realm. Can we get a timed release on it ? We've been waiting for it to be applied for a while now...

**Comment by hrtyv** [comment]
Is this still work in progress?

**Comment by robinsch** [comment]
This should be fixed on live.
