### ISSUE TITLE
Glyph of Voidwalker strikes again!

### ISSUE THREAD

**Issue by SaGElock** [dalaranwow/dalaran-wow#3263]
So Glyph of Voidwalker on the Dalaran-WoW private server is not working. The problems I am experiencing are identical to that of Issue #1321 on March 7th 2014 by Naixman. Before I apply the glyph my Voidwalker has 179 Stamina (118+61) and after it remains the same. I have tried many different fixes such as removing the Glyph, clearing my cache folder, the logging back in and reapplying the Glyph, but none seem to work.Other Warlocks say that the glyph works fine for them so I am very confused why it is not working for me. Again the issues are identical to Naixman's from 2014. Thank you for any help.

**Comment by SaGElock** [comment]
![wowscrnshot_050216_064237](https://cloud.githubusercontent.com/assets/19148103/14952780/726883b4-1031-11e6-8a18-1667ceee130d.jpg)
![wowscrnshot_050216_064209](https://cloud.githubusercontent.com/assets/19148103/14952777/6b454be4-1031-11e6-9545-97078ace5b0a.jpg)

**Comment by robinsch** [comment]
On PTR
