### ISSUE TITLE
Several bosses immune to disarm, when they should be.

### ISSUE THREAD

**Issue by Crazyphapha** [dalaranwow/dalaran-wow#3264]
Hello,

Me and my guild are entering togc25, and it seems that Gormok is supposed to be disarmable on live. However, he isn't on this server (probably because he doesn't have his weapon, a large poleaxe, when he should).

**Comment by Lothloryen** [comment]
Hello there,

Gormok the Impaler can only be disarmed on normal modes, not heroic ones. He should have the weapon equiped, just checked it and is fine.

Closing this report, thank you.
