### ISSUE TITLE
[Quest][Outland]Consortium monthly gem reward

### ISSUE THREAD

**Issue by Sagrath** [dalaranwow/dalaran-wow#3265]
Gezhe ID:18265 should be giving a monthly repeatable quest with gem bag rewards
The quests can be taken any day of the month and resets 1st of every month
Gem Stuffed Envelope appears to be for Friendly
www.wowhead.com/?item=25424#00zc

Unmarked Sack of Gems appears to be for Honored
www.wowhead.com/?item=25419

Bulging Sack of Gems appears to be for Revered
www.wowhead.com/?item=25422

Bag of Premium Gems appears to be for Exalted
www.wowhead.com/?item=25423

**Comment by Rushor** [comment]
and currently the quest is not assigned to creature http://de.wowhead.com/npc=18265/gezhe?

**Comment by Rushor** [comment]
works fine for me http://i.imgur.com/T51v7Hw.jpg
