### ISSUE TITLE
my hunter can't use guns

### ISSUE THREAD

**Issue by NickPiazza** [dalaranwow/dalaran-wow#3266]
Hi, I have a lvl 5 troll hunter, and I looted a gun recently that I'd like to epuip, but even though it requires lvl 4 to use (as I mentioned, I'm level 5), the word "gun" is red in the item's text box. When I try to equip it, it says I may not. I can still wield bows, but have not come across a crossbow yet, so I cannot speak for them. I just started playing this server today, and I honestly can't remember if this was a legit thing in WotLK or not, but it doesn't seem right; I always remember being able to use all ranged weapons as a hunter. I hope this gets fixed soon.

**Comment by Lukas45** [comment]
Welcome to the expansion where you have to train weapon skills from the different cities, and have to level up your weapon skill.

You can train Guns from Thunder Bluff and Crossbows from Undercity/Silvermoon City

**Comment by Golganeth** [comment]
Nothing's wrong, you need to learn how to use them, as @Lukas45 explained.

/closed
