### ISSUE TITLE
Duskwood - Raven Hill - Mobs falling though terrain | Also no death animation on skeleton

### ISSUE THREAD

**Issue by lightstylez** [dalaranwow/dalaran-wow#3268]
A lot of the undead type creatures within the area of Raven Hill in Duskwood will fall through the terrain constantly. Sometimes they will get stuck for ages trying to path back up (which they usually do, eventually). I was lvling with a friend and he saw the same as I did, this wasn't just a minor occurrence it happened VERY often. At least 30-40% of the mobs we killed in the area fell through the map when trying to path to us. They would be stuck under the map anywhere from a few seconds up to 30ish seconds, constantly moving around eventually made them path back to ground level. 

Also, a specific type of skeleton there had no death animation and just fell flat on kill (also observed by my mate) sorry I can't remember the mob name.
Edit: I think it was Skeletal Mage / Skeletal Fiend.

Still new to the server, enjoying it so far. Hope these issue's can be fixed :)

**Comment by Rushor** [comment]
https://github.com/TrinityCore/TrinityCore/commit/9ad952c3bc87a03cc39c2c44a301857b8f62df7c

this should improve the "dropping below textures" issue

**Comment by Rushor** [comment]
https://github.com/dalaranwow/dalaran-wow/issues/3374
