### ISSUE TITLE
Speed Glitch

### ISSUE THREAD

**Issue by zoraxhelleater** [dalaranwow/dalaran-wow#3269]
I was playing on my Horde character in STV where suddenly I randomly got a massive speed boost while doing one of the booty bay quests and it kept happening to me on and off and I have landed in hot trouble for it. This is to inform and warn others that this may happen to you and if it does raise a ticket asap.

Please fix this

**Comment by Rushor** [comment]
the speed of the rocket must be reduced to 4 (currently it seems to be 20)

**Comment by Golganeth** [comment]
After several testing I have not been able to reproduce this. I haven't encountered any issue whatsoever. 

Closing this up until more proof to support the bug is given.
