### ISSUE TITLE
Weapon Skills Do Not Increase

### ISSUE THREAD

**Issue by Gallaxey** [dalaranwow/dalaran-wow#3271]
I have tried everything from mobs my own level to the practice dummies in the major cities but my weapon skills do not increase.  They stopped at a certain level and are not increasing but, my profession skills increase just fine.

**Comment by Golganeth** [comment]
Dummies aren't supposed to grant weapon skills, only honorable targets (those that would grant experience). It works fine, it could be a visual issue or bug related to your client, try going offline and clear your Cache folder. If it persists, I'd suggest installing a normal 3.3.5 client (in case you don't have it already).

Closed.
