### ISSUE TITLE
Refer a Friend not working

### ISSUE THREAD

**Issue by NappingAwake** [dalaranwow/dalaran-wow#3272]
Noticed other people have posted but never saw a resolution (besides summoning being a known issue). 

Referral code was p7w9c1. Not getting any experience, and it doesn't say on his account that he has the appropriate number of accepted linking. The summoning icon shows up a few times (making me believe we are linked?), but says Invalid Target. It's the experience I'm interested in.

**Comment by Golganeth** [comment]
#3273
