### ISSUE TITLE
[Quest] "Scoodles"

### ISSUE THREAD

**Issue by Witeness** [dalaranwow/dalaran-wow#3274]
Quest: http://www.wowhead.com/quest=11510
NPC: http://www.wowhead.com/npc=24899 / http://www.wowhead.com/npc=5936

Seems like there is an Orca spawning in the place of Scoodles.

**Comment by Golganeth** [comment]
"Scoodles" is in-game, the NPC patrols. There are also Orcas around.

Closed.
