### ISSUE TITLE
Can not connect.

### ISSUE THREAD

**Issue by Truelotus1991** [dalaranwow/dalaran-wow#3275]
I can not connect to the server nor can i open a ticket on your offical forums because i can not connect. Here's the main issues it keeps saying it needs to update to a newer patch when i try and connect in game i get to the point where it would display the characters but instead of doing that it says i need to update and only gives me the restart button option to update. i'm not sure whats going on there. Also i know i have played on this server before and i have been able to connect and i have created a character on your server yet it still says on your forum i have no character created in which to be able to post on the forums with. so i'm not sure whats going on there either.

**Comment by Golganeth** [comment]
nvalid report. The bug tracker only lists in-game issues with quests, NPCs and such.

On the side note, get a normal 3.3.5 wotlk client and don't load the 'launcher'. Load the 'wow.exe' instead.
If you are trying to login using your e-mail, don't do it, use your account name instead.

Closed.
