### ISSUE TITLE
Can't Connect

### ISSUE THREAD

**Issue by Daithaii25** [dalaranwow/dalaran-wow#3277]
I was able to connect a few hours ago but cannot connect now. On the login screen it keeps connecting, but then gives me the cannot connect error. I've tried resetting my router and computer and deleted the WFT.

**Comment by Serfrost** [comment]
I can confirm the same issue.  Checked the connection logs and they return that the login server is down.

I managed to make it past the login server once, but afterwards upon selecting a server, it refused connection.

Multiple computers, same issue.  Friends in different towns confirm the same.

**Comment by Daithaii25** [comment]
I have a friend who can log in and reports that others are logged in as well. Still not sure what is going on.

**Comment by Serfrost** [comment]
This is strange.  I would assume it isn't an ISP issue considering the differences in location.

Testing pings with command prompt gave results of connection, but the client itself refuses.

**Comment by Serfrost** [comment]
My only hypothesis is that our accounts could be stuck, logged-in.

However, even my friend who has not made a character ... cannot connect.

**Comment by Daithaii25** [comment]
Ya, that is a strong possibility. It doesn't seem to even confirm my accounts. Even when I type the wrong password it does not get past the attempt to connect.

**Comment by Serfrost** [comment]
> 5/9 19:01:23.988  GRUNT: state: LOGIN_STATE_CONNECTING result: LOGIN_OK 
5/9 19:01:45.000  GRUNT: state: LOGIN_STATE_FAILED result: LOGIN_SERVER_DOWN 
5/9 19:01:45.000  GRUNT: state: LOGIN_STATE_FAILED result: LOGIN_FAILED

**Comment by Serfrost** [comment]
I've tried clean client files and nothing changed.

I'm clueless.

**Comment by Daithaii25** [comment]
hopefully it is temporary

**Comment by Serfrost** [comment]
... tried with 5 computers.  No changes.  /mega-sigh

**Comment by Serfrost** [comment]
Here are the tracert logs...

> Tracing route to logon.dalaran-realmlist.org [46.105.108.32]
over a maximum of 30 hops:

  1     3 ms     2 ms     1 ms  192.168.254.254 
  2    38 ms    27 ms    23 ms  173-18-24-1.client.mchsi.com [173.18.24.1] 
  3   145 ms    68 ms    30 ms  172.30.88.169 
  4    30 ms    42 ms    38 ms  172.30.9.161 
  5    65 ms    24 ms    31 ms  173.167.58.117 
  6    70 ms    40 ms    47 ms  hu-2-3-0-5-cr02.350ecermak.il.ibone.comcast.net [68.86.89.181] 
  7   110 ms    50 ms    87 ms  hu-0-18-0-0-pe04.350ecermak.il.ibone.comcast.net [68.86.89.106] 
  8    55 ms    71 ms    64 ms  be100-151.chi-5-a9.il.us [198.27.73.65] 
  9    89 ms    85 ms    64 ms  be100-1005.nwk-5-a9.nj.us [198.27.73.251] 
 10   228 ms   217 ms   216 ms  be100-1006.ldn-5-a9.uk.eu [178.32.135.231] 
 11   272 ms   217 ms   209 ms  be11-1188.rbx-g2-a9.fr.eu [91.121.128.88] 
 12   159 ms   148 ms     *     po7.vss-5a-6k.routers.ovh.net [178.33.100.71] 
 13   252 ms   223 ms   207 ms  ns320313.ip-46-105-108.eu [46.105.108.32] 

Trace complete.

**Comment by Daithaii25** [comment]
still can't connect :(

**Comment by Golganeth** [comment]
Invalid report. The bug tracker only lists in-game issues with quests, NPCs and such. This is not a place to discuss or post constantly, please keep the bug tracker clean for the Dev, guys. Feel free to use the [Community Support](http://www.dalaran-wow.com/forums/input-and-assistance/community-support) or [General Discussion](http://www.dalaran-wow.com/forums/community/general-discussion) section of the forums for that purpose. 

The server is fine so it must be related to your computer / ISP. Check out this [thread](http://www.dalaran-wow.com/forums/input-and-assistance/community-support/topic/7954/constant-disconnection-every-hour) for possible solutions to the issue you're having.

Closed.
