### ISSUE TITLE
Dk bugs

### ISSUE THREAD

**Issue by Dafaqm8** [dalaranwow/dalaran-wow#3278]
Death and Decay - do no damage to invisible targets .

 Summon Gargoyle -  don't attack the target you focuse , you need to move when cast , as him to do damage to some one , if nobody attacks you he will stay afk .
 
Raise Dead + Death Pact -  this combo will make your pet don't appear till a relog , were in a bg or a arena is not possible .

**Comment by Rushor** [comment]
what kind of targets are invisible?

**Comment by Golganeth** [comment]
Duplicated. Please make separated reports for each issue.

#1295 #3118 

Closed.
