### ISSUE TITLE
Mob aggro is acting up

### ISSUE THREAD

**Issue by Mirashu** [dalaranwow/dalaran-wow#3279]
I'm not sure if it is the same world wide or if it is just inside dungeons, however, when I am in a dungeon and I try to pull mobs, any given number doesn't matter as long as I am body pulling (_walking up to the mobs and waiting for them to attack_) but when I do this, many of the mobs, sometimes all the mobs will instantly give of the combat text "**_Changed Target_**" and runs of to another player in the party.

This is also an issue when I have built up aggro by doing damage, but is far less frequent, I have 100% aggro on all the mobs, but then suddenly some of the mobs changes target and starts attacking other players

**Comment by Golganeth** [comment]
Invalid report.

If you walk into NPCs not dealing any aggro whatsoever, they will obviously change target and attack someone who did  (healer / HoT's for example).
Tanks will lose aggro instantly under certain conditions (crowd control, for example).

http://wowwiki.wikia.com/wiki/Aggro

Closed.

**Comment by Mirashu** [comment]
Yes they will change target if someone heals or buffs the tank.

But a Hunter should not get any aggro by switching from Aspect of the Viper to Aspect of the Hawk.

And like I said, they **Instanstly** change target sometimes, even when none of the players have done anything!

Also it should not happen when i have **consecration** on the ground and use **holy shield** and then hunter changes aspect, and gets aggro
