### ISSUE TITLE
Mob packs are not combat linked

### ISSUE THREAD

**Issue by Mirashu** [dalaranwow/dalaran-wow#3281]
Dungeon or Open World, doesn't matter when attack one mob with a ranged attack or a taunt, you will only pull one or two of the mobs in the pack.

For example, in RFC(Ragefire Chasm) in the big room with the last boss, there are many mob packs surrounding the boss, most of them consist of packs of 3, some of them are 4 or 5 and if you pull one mob from either pack, only one or two of them will aggro.

**Comment by Golganeth** [comment]
Duplicated, issue already mentioned on #1954
