### ISSUE TITLE
Forum Character Selection Issue

### ISSUE THREAD

**Issue by Serfrost** [dalaranwow/dalaran-wow#3282]
I've basically searched every page or option on the website to select my character, but all that comes up is "[My Name] No Characters have been found."

**I would prefer** to post this in the forums, but it isn't possible.

**Comment by Lukas45** [comment]
The forum can only find characters on the Kirin Tor server, so all you have to do is make a level 1 character there

**Comment by Golganeth** [comment]
In order to be able to post on the forums create at least one character on Kirin Tor and select it as your main character. Website is under rework and is not synced with Algalon yet.

Closed
