### ISSUE TITLE
Stuck Immortal

### ISSUE THREAD

**Issue by karmal95** [dalaranwow/dalaran-wow#3287]
![image](https://cloud.githubusercontent.com/assets/19359665/15267845/b28bf124-19cd-11e6-8acb-b892fefe6967.png)
I didn't get back from instance after party finished and i logged off. When i logged back i was stuck and 1 hp dead and mobs were still attacking me, i can't do anything as dead and i can't release spirit

**Comment by Rushor** [comment]
yeah really annoying bug :(  this also happens sometimes in bgs if player kill you. there is no way exepct quiting the game in order ro get back controle about the characters. i don't know how to fix this

**Comment by Rushor** [comment]
Use the unstuck feature for such cases

![GitHub Logo](http://i.imgur.com/9aAOPBl.jpg)
