### ISSUE TITLE
Website doesn't recognize new TLDs.

### ISSUE THREAD

**Issue by saatanaperkele** [dalaranwow/dalaran-wow#3289]
Expection:

Registration can be done with a new TLD (.space, etc)

What happens:

Registration rejects email and redirects to empty signup form again.

**Comment by Golganeth** [comment]
Invalid report. The bugtracker only lists in

**Comment by Golganeth** [comment]
Invalid report. The bugtracker only lists in-game issues.

The website is under heavy rework and not all of the e-mail registration TLDS are enabled, it is something we might add in the future. For the time being, you should use one of the standard ones ("gmail.com" or similar).

Closed.
