### ISSUE TITLE
Quest: Sorlof's Booty

### ISSUE THREAD

**Issue by Sagrath** [dalaranwow/dalaran-wow#329]
http://old.wowhead.com/quest=11529 
Players cant use the Cannon to kill Sorlof, and even if they kill Sorlof, upon death the Sorlof's Booty object does not spawn.
http://www.wowhead.com/item=34468
Temporal fix added, spawned the object. with 5 min spawn time.

**Comment by ashido96** [comment]
For anyone coming by this, the loot spawns mostly hidden under his corpse when you kill him. Didn't bother using the cannon.

**Comment by DrFuler** [comment]
[01/03/2016] - Killed Sorlof by myself, not even tried the cannon. The booty DOES dropped after killing it (however as someone else pointed out, it might get hard to see under his colossal body).

**Comment by Rushor** [comment]
this can be fixed with the cannon. 
problem: depending on the visbility range, the boss sometimes appears while you are on the ship - and sometimes not

**Comment by Rushor** [comment]
- the cannon can now be used to kill Sorlof

if the creature is not visible while you drive by with the ship, then the visbility range must be increased. this can only be changed by admins

**Comment by Golganeth** [comment]
Few issues to be polished:
- Visibility problems; Sorlof can't be seen from the boat, or barely.
- The Big Gun: You can spam it, no cast bar, no balls going out of it. You shouldn't be able to spam fire with it

https://www.youtube.com/watch?v=gSbTj6YZAP0 (Cataclysm but accurate)

**Comment by datbunneh** [comment]
@Golganeth 
I wonder why it's closed. This quest either does not work at all or is barely working. Two circles so far and noone spawned.
