### ISSUE TITLE
[Shaman] Glyph of Stormstrike

### ISSUE THREAD

**Issue by Person-guy** [dalaranwow/dalaran-wow#3291]
With Glyph of Stormstrike slotted, the tooltip that shows on an enemy when Stormstrike is used doesn't show the correct percentage. I haven't checked to see if it's a tooltip bug or an actual damage bug, but it says "+20% Nature dmg" instead of the "+28% Nature dmg" it should be with the glyph.

![wowscrnshot_051516_141418](https://cloud.githubusercontent.com/assets/19376155/15275950/8634f0b4-1aa7-11e6-9eb6-2e0671efc66b.jpg)
![wowscrnshot_051516_141434](https://cloud.githubusercontent.com/assets/19376155/15275951/88a7ecd4-1aa7-11e6-805b-6212146eea0a.jpg)

If someone has 2 of these glyphs extra I would be willing to test on dummies, but at the moment I can't afford to remove it.

**Comment by sixele** [comment]
From what I've heard, no matter whether you enhance your spell with talents/glyphs, the tooltip in spellbook will not match the tooltip of the buff when it's active, but it works like it's supposed to. Same thing with Improved Vampiric Embrace (and many many spells from different classes)

**Comment by Golganeth** [comment]
Intended behavior. Buff & debuff auras usually never update when modified by talents or glyphs. Your action bar or spellbook tooltips will reflect any change though.

Closed.
