### ISSUE TITLE
[Donation Issue] Double Charge due to technical error.

### ISSUE THREAD

**Issue by MisterUlysses** [dalaranwow/dalaran-wow#3293]
A while back, I went to donate $26.66 but an issue with the Paymentwall service caused a double charge and a double-up of donation points. I've contact Paymentwall for a refund of the second charge as per your refund policy, but things have been dragging on for weeks now. Is there any way I can get that second charge refunded and the 20 or so donation points removed?

**Comment by MisterUlysses** [comment]
And in case it's relevent, my account name is MrUlysses, and I have 42 donation points currently, when I should only have 21 once the charge is reversed.

**Comment by Sagrath** [comment]
for this kind of issues write an email to
dalaran.community@gmail.com
