### ISSUE TITLE
[Achievement] Warglaives of Azzinoth

### ISSUE THREAD

**Issue by Tarpor** [dalaranwow/dalaran-wow#3297]
There is currently no feat granted for wielding both Warglaives. 

Feat of Strenght that should be granted is _ID:426_ **Warglaives of Azzinoth**

It does exist, /run AddTrackedAchievement(426) , but there's no credit given.
imgur album for proof: [imgur.com/a/dxEjs](http://imgur.com/a/dxEjs)

**Comment by Rushor** [comment]
works fine on PTR.

![GitHub Logo](http://i.imgur.com/bSIE2NF.jpg)
