### ISSUE TITLE
Can't Access Forums / No Characters Found

### ISSUE THREAD

**Issue by lordnicholas85** [dalaranwow/dalaran-wow#3298]
I'm able to login on the site/game, vote receive vote rewards but I cannot participate in forums because I don't have a character yet...? Account Name: LordNicholas85 Character Name: Tagi

**Comment by Golganeth** [comment]
In order to be able to post on the forums create at least one character on Kirin Tor and select it as your main character. Website is under heavy rework and is not synced with Algalon yet. We apologize for the inconvenience.

Closed.
