### ISSUE TITLE
[Ulduar] Twilight Slayer - Whirlwind during CC

### ISSUE THREAD

**Issue by ashido96** [dalaranwow/dalaran-wow#3300]
The Twilight Slayer mob in General Vezax's room will cast his whirlwind ability while under the effect of hunter's freezing trap, as we quickly clear them did not see any other cc on him. Though this did occur on all 3 packs.

http://www.wowhead.com/npc=33823/twilight-slayer

**Comment by Rushor** [comment]
this guy does not have any ai on the ptr realm

**Comment by Golganeth** [comment]
Pretty sure it's a general issue and directly related to #2166 / #2473
