### ISSUE TITLE
[Quest] - Zanzil's Secret

### ISSUE THREAD

**Issue by DrFuler** [dalaranwow/dalaran-wow#3301]
This quest (Zanzil's Secret) is offered by a Booty Bay goblin named Crank Fizzlebub and seems to be broken, therefore not completable. The same goblin offers another quest named "Fool's Stout", which confusingly requires the same quest items, which isn't working as well for the same issue.

The quest work entirely normally up to the point you try to deliver the 12 items required (Zanzil's Mixture) to the quest giver, who don't recognize the quest as completed. It should be noted that the quest itself says it is completed, and because of that even shows the ? mark on the map. However, the quest giver simply don't recognize it as completed and don't accept it.

I had a similar issue with the same character in the quest The Lost Mistwhisper Treasure, at Scholazar Basin (#3176). It seems that since that one was fixed, this should be fixed with ease I guess.

Thanks for the attention.

**Comment by Golganeth** [comment]
I've tested both quests a few times and I couldn't reproduce the problem at all. Try clearing Cache folder and retaking the quest.

Closed

**Comment by DrFuler** [comment]
Thanks for the help. I tried to follow the steps you suggested and it did solved the problem (for both quests).
