### ISSUE TITLE
Formula Goblin Rocket Boots for Engineers 

### ISSUE THREAD

**Issue by wavemanns** [dalaranwow/dalaran-wow#3302]
Formula does not teach item. Right click on formula does nothing.

**Comment by Golganeth** [comment]
Confirmed. The item doesn't seem to have the correct description or use.

![image](https://cloud.githubusercontent.com/assets/5057942/15398412/d0f56874-1de3-11e6-9597-d0d55a05dff8.png)

Item: [Plans: Goblin Rocket Boots](http://wotlk.openwow.com/item=7192)
ID 7192

**Comment by Rushor** [comment]
By kalakala (1,970 – 4·33) on 2009/01/25 (Patch 3.0.8)
Nomore uses Plan to learn, teached by trainers in Ratchet, Gadgetzan and Dalaran at skill level 130
http://www.wowhead.com/item=7192#comments

so you can manually learn from the trainer.

it think the itemdrop should be removed from the world (proof needed)

**Comment by Rushor** [comment]
http://www.wowhead.com/item=7192/schematic-goblin-rocket-boots#comments:id=579921

**Comment by Rushor** [comment]
- removed the item from creature_loot_templates
