### ISSUE TITLE
Quest: Scouting the Sinkholes [11684 / 11713]

### ISSUE THREAD

**Issue by Golganeth** [dalaranwow/dalaran-wow#3304]
**Issue:** The quest item can be used anywhere near the holes but only certain (very specific) spots will grant credit. Green circle areas show the spots where it works, whereas red circle areas will let you cast the item but no credit will be granted. 
(*Basically it works on every spot with extra height while being as close as possible to the center*).

![image](https://cloud.githubusercontent.com/assets/5057942/15400276/3ce79956-1deb-11e6-962d-c78b96153a9b.png)

**How it should work:** Credit should be granted when using the quest item anywhere near the holes. 
The following credit bunny triggers shouldn't be so high:
- **South Sinkhole** - *25664*
- **Northeast Sinkhole** - *25665*
- **Northwest Sinkhole** - *25666*

---------------------------------------------

http://wotlk.openwow.com/quest=11684 (Horde)
http://wotlk.openwow.com/quest=11713 (Alliance)

**Comment by jonanone** [comment]
The issue has been fixed and it will be applied to the live realm soon.

**Comment by Golganeth** [comment]
Works great, credit area is much bigger now.

However, there are still spots where quest item can be used and credit isn't granted. Quest item should only be usable in credit areas. (attached screenshot shows example - south hole, happens in all 3 though)

![image](https://cloud.githubusercontent.com/assets/5057942/15802351/e87738a6-2aae-11e6-9995-0dad42fb72a0.png)
