### ISSUE TITLE
Onyxia's head loot bugged

### ISSUE THREAD

**Issue by AppleCake** [dalaranwow/dalaran-wow#3308]
So we killed Onyxia, and I won the roll on the head, but it got bugged so I couldn't loot it. I was told by the other raid members to make a post about it here. At the point where I took the screenshot, the loot window also stopped working, so I don't have any other proof than part of the raid chat.
http://imgur.com/oBgePU8

While I'm at it, the "Rocket Boots Xtreme" from TBC engineering recipe doesn't work anymore. It just goes on cooldown without anything happening.

**Comment by Golganeth** [comment]
Invalid report. The bug tracker only lists in-game issues. For loot problems make an in-game ticket or send an e-mail to: dalaran.community@gmail.com. Add detailed information and evidence(s).

The issue with Rocket Boots Extreme is already reported - #3247.

Closed.
