### ISSUE TITLE
[Naxxramas] Sapphiron's ability Chill

### ISSUE THREAD

**Issue by ImprezaWoW** [dalaranwow/dalaran-wow#3309]
[Sapphiron's](http://wowwiki.wikia.com/wiki/Sapphiron_(tactics)) ability _[Chill](http://www.wowhead.com/spell=28547/chill)("Chill is an ice storm that drifts around the room at all times after Sapphiron is engaged. There will often be multiple ice storms up. It will deal Frost damage every 2 seconds to everyone within it and slow their movement speed by 50% for 10 seconds._") targets every player in the raid no matter where you're standing, making the raid wipe from incoming damage. Both in 10 man and 25 man.

**Comment by fizzl** [comment]
Yup, standing here with raid wondering what to do.

**Comment by ImprezaWoW** [comment]
Fixed.
