### ISSUE TITLE
Horde - Succubus quest

### ISSUE THREAD

**Issue by kris28tx** [dalaranwow/dalaran-wow#3311]
Blood Elf I have no quests in Silvermoon, UC or Org that allows me to start the questline Devourer of Souls for Succubus pet. I have Imp, VM and FH pets so far. I have checked the forums and also bug tracker.

**Comment by ImprezaWoW** [comment]
[#2705](https://github.com/dalaranwow/dalaran-wow/issues/2705)

**Comment by Sagrath** [comment]
Alamma in SMC gives the quest to start the chain for succubus
