### ISSUE TITLE
[Druid] Critical PVP bug - Last lifebloom tick heals for 25% instead of 50% when under a mortal strike effect

### ISSUE THREAD

**Issue by Plexieglas** [dalaranwow/dalaran-wow#3312]
Tested with mortal strike and wound poison, with and without arena relic.
Please fix, thank you.

**Comment by doppin** [comment]
Yep, tested it for myself, the heal cut is exactly 25% instead of 50% for some reason. Tested Warmane then worked well there.

**Comment by doppin** [comment]
Tested on different server, works there. Report is accurate. Please fix asap.

**Comment by Plexieglas** [comment]
Easy bug to test one of those new developers ( ͡° ͜ʖ ͡°)

**Comment by doppin** [comment]
Closed=fixed?

**Comment by Lothloryen** [comment]
Yes, @robinsch has fixed it and it should be deployed to Algalon with the next scheduled maintenance.

**Comment by doppin** [comment]
cool

**Comment by Plexieglas** [comment]
@robinsch @Lothloryen thanks!! that was very fast :) :+1:

**Comment by doppin** [comment]
Hail new devs!

**Comment by doppin** [comment]
When is the update,

**Comment by Lothloryen** [comment]
Hello there,

It was deployed already, yesterday.

**Comment by Plexieglas** [comment]
Tested & confirmed to be fixed on live. Thanks!
