### ISSUE TITLE
Improved Devotion Aura

### ISSUE THREAD

**Issue by Sammydin** [dalaranwow/dalaran-wow#3315]
Paladin protection talent providing an armor bonus to devotion aura and a 2% healing increase per rank while an aura is active. The devotion aura bonus applies but the extra healing does not.

None of the auras apply bonus healing as they should.

**Comment by Dolmio1** [comment]
It works, tested it

**Comment by Golganeth** [comment]
Thank you @Dolmio1. Just to make sure I tested it too and it works indeed.

Closed
