### ISSUE TITLE
Azjol Nerub First Boss

### ISSUE THREAD

**Issue by Jonny462** [dalaranwow/dalaran-wow#3316]
I think this applies only to normal. I haven't done heroic yet, but I've heard it works fine.

On the first boss you pull the 3 smaller mob groups, and then the boss. While still fighting the first group, the second group will auto aggro you and get pulled for no reason. About 10 seconds after that the 3rd group aggro's, and then the boss. Leaving you with the boss and about 6-9 spiders to kill. It does not happen every time, but in my experience its 4/5. It makes AN almost impossible.

I tested this on my own team and in public groups while leveling. No one in the group was pulling them and none of us were close enough to aggro.

**Comment by ImprezaWoW** [comment]
[#3280](https://github.com/dalaranwow/dalaran-wow/issues/3280)

**Comment by Golganeth** [comment]
I've reopened the old report. Closing this one
