### ISSUE TITLE
DK Leveling zone Speed BUG

### ISSUE THREAD

**Issue by sniffcoke01** [dalaranwow/dalaran-wow#3317]
Hello,

You might wanna take a look at your DK Starting zone. After quest the Eye of Acherus , after finishing controlling the eye , before completing the quest my friend got a bug speed for no reason.
Please fix it or at least test it to be aware of it's existence before assuming that people are using speed hacks. 
Your GM's banned a friend because of this bug so i hope that you might take it in consideration, test it and then reconsider your actions.

If you are in anyway professional how you pretend you are i ask being contacted on my email address: "catalin.lupea@hotmail.com" by a superior of your narrow minded GMs. It`s not about feeling pity for hackers(as the GMs said) it`s about being correct and fixing your mistake.

Waiting for your answer!

Catalin Lupea

**Comment by ImprezaWoW** [comment]
Something like [this](https://youtu.be/X4IqeECfhxU) might have happened. Also happens in retail, can not do anything about it, unfortunately. The ban has been lifted.

**Comment by sniffcoke01** [comment]
Thank you very much for listening and testing it!

I know there many hackers out there and your just trying to do your job, but this time it was not a hack.

Thanks again, and have a good day!

**Comment by MalkaviaDW** [comment]
#3087
