### ISSUE TITLE
[Achievement] The Faceroller

### ISSUE THREAD

**Issue by sixele** [dalaranwow/dalaran-wow#3318]
The achievement [The Faceroller ](http://www.wowhead.com/achievement=3803/the-faceroller) in [Trial of the Champion](http://www.wowhead.com/zone=4723/trial-of-the-champion) does not work as when you throw the hammer at  [Eadric the Pure](http://www.wowhead.com/npc=35119/eadric-the-pure) with him having <15000 HP left, he goes back to friendly as he's supposed to, but no achievement is granted. [At least you can throw the Hammer back, right? Pretty fun.](http://i.imgur.com/uG8vjXR.jpg)

**Comment by Crispybuilt** [comment]
Confirmed, it used to work on the very release, but it's no longer obtainable. Tried several times already with different group setup.

**Comment by sixele** [comment]
Odd thing happened - today my friend linked the achievement to me (06-24), and, quoting the conversation:
>18:53 [Friend]:  [The Faceroller] woat
>19:24 [Me]: whaaa it got fixed?
>19:24 [Friend]: what's the issue ?
>19:25 [Me]: how did you do it? i did it a month ago, made sure eadric is at less than 15k hp, threw the hammer back and didnt get the achievement
>19:25 [Me]: i made a github post about it
>19:25 [Friend]: Oh
>19:25 [Friend]: This one
>19:25 [Me]: and another player even confirmed the achievement is broken
>19:26 [Friend]: Yeah i can confirm that the achievement is broken af too
>19:26 [Friend]: i've been trying it for a month.
>19:26 [Friend]: repeatedly
>19:26 [Me]: but you got the achievement somehow?
>19:26 [Friend]: Well the Boss went low on Hp someone from the group just threw the hammer and we all got the achievement, miracle right 
>19:26 [Friend]: Im happy that i have it
>19:26 [Me]: so odd since it didnt work for us
>19:26 [Friend]: Well
>19:27 [Friend]: That's like atleast my 20th time i've done it. finally it came lol

Which made me think, that if you repeatedly do it in the same way every single day, there's a slight chance that it can actually be obtained? Of course the issue is here nonetheless, but I found this very odd and perhaps worth a mention.

**Comment by LoveDalaranWow** [comment]
> Which made me think, that if you repeatedly do it in the same way every single day, there's a slight chance that it can actually be obtained? > 

This is still inconsistent, killing the boss with his hammer should either give the achievement (as it is supposed to be) or not give it at all, having a % chance to give the achievement randomly (and forcing you to do it over and over when you are supposed to do it only once) doesn't seem completely right.

**Comment by sixele** [comment]
...hello the issue is open and I literally said in the comment that it's not fixed, obviously.

**Comment by Rushor** [comment]
On PTR this Achievement is not even scripted. i will do it from scratch, so loth can pickup the fix and apply it on live :)

**Comment by Rushor** [comment]
Scripts/TrialOfTheChampion: Implement Achievement: The Faceroller

* If the player defeats Eadric the Pure with his own hammer, Eadric the Pure will turn freiendly and the whole instance will get the achievement
* also added a minor spelscript for the reflective shield from Paletress
* closes https://github.com/dalaranwow/dalaran-wow/issues/3318
* commit: ac96339e457b955848d4062df8f4ef84db138548

This fix cannot be tested on PTR, only on live by loth.

**Comment by alexuktc** [comment]
As of today, 09/05/2018 this achievement is still not working.

**Comment by Rushor** [comment]
okay now since the ptr can be used for these tests - i will inspect it again
