### ISSUE TITLE
NPC: Second wave of Infinite Dragonkins CoS

### ISSUE THREAD

**Issue by Sagrath** [dalaranwow/dalaran-wow#332]
In the chamber where Chrono-Lord Epoch is, you have to kill the last wave of Infinite Dragonkins, but players are unable to kill them, only Arthas and players need to heal him.
Infinite Hunter -http://www.wowhead.com/npc=27743
Infinite Agent - http://www.wowhead.com/npc=27744
Infinite Adversary - http://www.wowhead.com/npc=27742

**Comment by Rushor** [comment]
http://i.imgur.com/DHFgxY4.jpg
http://i.imgur.com/mpr1fUh.jpg
http://i.imgur.com/UKCyJw0.jpg
http://i.imgur.com/lAouRft.jpg

everything is attackable
