### ISSUE TITLE
[Quest] The Right Piece of Lord Valthalak's Amulet

### ISSUE THREAD

**Issue by ImprezaWoW** [dalaranwow/dalaran-wow#3320]
For the quest [The Right Piece of Lord Valthalak's Amulet](https://vanilla-twinhead.twinstar.cz/?quest=8991) _(ID:8991)_ you are supposed to kill [Jarien ](https://vanilla-twinhead.twinstar.cz/?npc=16101) and [Sothos](https://vanilla-twinhead.twinstar.cz/?npc=16102), who can be summoned in [Stratholme](http://www.wowhead.com/zone=2017/stratholme). When the [Brazier of Beckoning](http://www.wowhead.com/item=22051/brazier-of-beckoning) is used, both mobs spawn as hostile, but they are unattackable neither by melee hits or by ranged spells, making them unkillable.

**Comment by Golganeth** [comment]
#3098
