### ISSUE TITLE
BWL attunement

### ISSUE THREAD

**Issue by Tyrial** [dalaranwow/dalaran-wow#3323]
At the moment it is impossible to start the attunement chain bc scarshield quatermaster, who drops the quest- starting item (letter) is absent (waited for 20 minutes and killed other mobs sevral times- no spawn). http://www.wowhead.com/quest=7761/blackhands-command - link to quest description and guide on wowhead.

**Comment by Tarpor** [comment]
works fine, couple hours respawn cuz its a rare
