### ISSUE TITLE
RAF XP Bonus not working

### ISSUE THREAD

**Issue by budthechud** [dalaranwow/dalaran-wow#3325]
So there were 6 of us who signed up together.  One person referred another who referred me but I did not get the triple XP bonus.  I was referred, signed up using the link in the email but it's not working.

**Comment by ImprezaWoW** [comment]
Please make an in-game ticket explaining your situation.

**Comment by budthechud** [comment]
I actually did and they told me to read the raf faq.

**Comment by Golganeth** [comment]
Refer-a-friend bonuses works fine, so if you have created the account through the mail you received it should be fine.

Requirements to receive XP bonus:
1) You must have your friend in your friend list, and vice versa.
2) You must be close to each other.
3) You must be in party with your friend.
4) You both must be within the same level range and less than level 60.

------------------

If the issue persists, you can always make an in-game ticket and we'll make sure to check if something went wrong. Make sure to provide both account names.

Thanks!
