### ISSUE TITLE
Quest: Krolmir, Hammer of Storms

### ISSUE THREAD

**Issue by frznfngrs** [dalaranwow/dalaran-wow#3326]
Unable to turn in quest to Throrim at Temple of storms.  He does not have an option.  Quest objective completed, just no turn in.

**Comment by Golganeth** [comment]
You don't turn in the quest in the Temple of Storms. Read your quest log or internet sources if required.

Closed.

**Comment by frznfngrs** [comment]
Then it is worth noting that He didn't properly spawn.  and I flew around that area initially looking for him because it shows he should be there.   So I flew to the temple, and he was there, unable to turn in.   Flew back to the area again later and he was there.  So there is a bug.

**Comment by Golganeth** [comment]
#497
