### ISSUE TITLE
Hunter Aspect Mastery bug

### ISSUE THREAD

**Issue by booohooo** [dalaranwow/dalaran-wow#3328]
Hello. I noticed hunter's Aspect Mastery bonuses are bugged. The most obvious way to see was Aspect of the Hawk bonus. There is no added attack power. Point spent in vain.

**Comment by Golganeth** [comment]
Tested and works as intended. Buff & debuff auras usually never update when modified by either talents or glyphs. Check your action bar and spellbook tooltips to notice modifications done to the spell.

Closed.
