### ISSUE TITLE
Crash on loading

### ISSUE THREAD

**Issue by IgorDubois** [dalaranwow/dalaran-wow#3330]
Hi,
I was going to moonglade but my game crashed when i got close. Since if i try to play my character, my game crashes during the loading. Here is the crash log : 
==============================================================================
World of WarCraft (build 12340)

Exe:      C:\Users\Hippolyte\OneDrive\Documents\WoW\Wrath of the Lich King 3.3.5a\Wow.exe
Time:     May 29, 2016  6:12:57.417 PM
User:     Hippolyte
Computer: MSIGE40
------------------------------------------------------------------------------

This application has encountered a critical error:

ERROR #134 (0x85100086) Fatal Condition
Program:	C:\Users\Hippolyte\OneDrive\Documents\WoW\Wrath of the Lich King 3.3.5a\Wow.exe

Failed to read file World\Maps\Kalimdor\Kalimdor_34_19.adt.

Debug Details:

[2] err=0 text=SFileReadFile - World\Maps\Kalimdor\Kalimdor_34_19.adt - Data\patch.MPQ
[1] err=0 text=ReadSectors/DecompressData failed
[0] err=0 text=ReadSectors/DecompressData failed

WoWBuild: 12340
Settings: 
SET locale "enUS"
SET realmList "logon.dalaran-realmlist.org"
SET hwDetect "0"
SET gxResolution "1600x900"
SET gxRefresh "60"
SET gxTripleBuffer "1"
SET gxMultisampleQuality "0.000000"
SET gxFixLag "0"
SET videoOptionsVersion "3"
SET textureFilteringMode "5"
SET movie "0"
SET mouseSpeed "1"
SET DesktopGamma "1"
SET Gamma "1.000000"
SET readTOS "1"
SET readEULA "1"
SET showToolsUI "0"
SET accounttype "LK"
SET Sound_OutputDriverName "System Default"
SET Sound_MusicVolume "0.5"
SET Sound_AmbienceVolume "0.10000000149012"
SET componentTextureLevel "9"
SET shadowLevel "0"
SET farclip "1277"
SET specular "1"
SET groundEffectDensity "64"
SET groundEffectDist "140"
SET environmentDetail "1.5"
SET extShadowQuality "5"
SET projectedTextures "1"
SET weatherDensity "3"
SET realmName "Algalon - Main Realm"
SET gameTip "122"
SET Sound_MasterVolume "0.10000000149012"
SET Sound_NumChannels "64"
SET Sound_EnableReverb "1"
SET Sound_EnableSoftwareHRTF "1"
SET Sound_EnableHardware "1"
SET Sound_EnableSoundWhenGameIsInBG "1"
SET watchFrameWidth "1"
SET gxWindow "1"
SET gxMaximize "1"
SET timingTestError "0"
SET Sound_SFXVolume "0.10000000149012"

----------------------------------------
               GxInfo
----------------------------------------
GxApi: D3D9
Adapter Count: 1

Adapter 0 (primary):
  Driver: nvd3dum.dll
  Version: 10.18.0013.6451
  Description: NVIDIA GeForce GTX 760M
  DeviceName: \\.\DISPLAY1

``

**Comment by Sagrath** [comment]
client issue
