### ISSUE TITLE
Problem with aggro when using only DoT

### ISSUE THREAD

**Issue by Lunati91** [dalaranwow/dalaran-wow#3333]
Hi.

Sorry for my English, I hope you'll understand what I mean.

I'm a new player and I noticed a bug with my newly created warlock on the server.
When I use DoT spells which doesn't deal direct damage on an enemy and then runs a bit away, I lose aggro after 5 meters. I tested with both DoT spells which doesn't deal direct damage : **Corruption** and **Curse of Agony**, both had the same result. But if I use Immolate or Shadow Bolt and then runs away, it works perfectly  they've a normal aggro loss.

So here is the problem : if using only DoT spells and then running away from mobs (to kite them and create a distance between them and I), they almost instantly lose aggro. It means I always have to deal direct damage spell before using my DoT on enemies or I wouldn't be able to kite them.

I only tried with my warlock but it should work the same with Priest and their Shadow Word : Pain.

**Comment by Rushor** [comment]
any spell which does not deal direct damage seems not to create aggro

**Comment by ashido96** [comment]
The issue is more that after about 40 yards every mob in the game will drop agro and do it's "evade reset" thing and go back to full health. ie. if you're a caster and are leveling you need to kite mobs around their initial position and not backwards on this server.
