### ISSUE TITLE
Felhunter Pet Skills

### ISSUE THREAD

**Issue by MrAndersonX** [dalaranwow/dalaran-wow#3334]
Hi,

I'm having some problems with the warlock pet Felhunter. 
Everytime I summon him, and toggle off the auto-cast for the spells Devour Magic (http://wotlk.openwow.com/spell=19505)  and Spell Lock (http://wotlk.openwow.com/spell=19244) and mount/unmount or just summon a new Felhunter, they get toggled back on. This is really annoying, and even if they still auto-cast, on the pet bar the auto-cast appears to be turned off, but when I check pet skills they are turned on. This is a major issue, because it is very difficult to always remember to toggle it off especially when it's shown as off. Makes controlling the abilities also very difficult.
Don't know about the other abilities, as they represent less of a problem.

Thank you.

**Comment by ImprezaWoW** [comment]
[#1021](https://github.com/dalaranwow/dalaran-wow/issues/1021) General issue with all pets.
