### ISSUE TITLE
Ravenholdt Manor Guards

### ISSUE THREAD

**Issue by socialmedia1** [dalaranwow/dalaran-wow#3336]
Missing text when clicking on any of the guards in Ravenholdt Manor. 
![capture](https://cloud.githubusercontent.com/assets/8617360/15658864/ca86bbf0-2676-11e6-9f45-3359fee3607e.PNG)

**Comment by Rushor** [comment]
text is unneeded  here

fix:

```sql
DELETE FROM `gossip_menu` WHERE  `entry`=4861 AND `text_id`=5935;
```

**Comment by Rushor** [comment]
- wrong text removed
