### ISSUE TITLE
Group quests

### ISSUE THREAD

**Issue by Golganeth** [dalaranwow/dalaran-wow#3337]
When a player picks up a group quest (example: Ring of Blood, Amphiteater of Anguish) the other members will not be able to accept it through him, leading to (in this case) having to kill the boss once for each of the members that need the quest completed.

When one of the players accept a group quest, a small window should pop up asking if the player wants to accept the quest too. The window pops up but when you press accept, nothing happens.

**Comment by ImprezaWoW** [comment]
Similar reports regarding quest sharing:
[2534](https://github.com/dalaranwow/dalaran-wow/issues/2534)
[2778(Escort Quest sharing)](https://github.com/dalaranwow/dalaran-wow/issues/2778)

**Comment by Rushor** [comment]
related https://github.com/TrinityCore/TrinityCore/commit/3c3cde028cbcab64d463707e192fc333d8cadda0

**Comment by Lothloryen** [comment]
Working already, thank you.
