### ISSUE TITLE
[Ulduar] Freya - Nature Bombs Exploding Prematurely

### ISSUE THREAD

**Issue by saltylopez** [dalaranwow/dalaran-wow#3338]
The Nature Bombs used by Freya during phase 2 will occasionally explode immediately as they are placed, instead of waiting the normal 10 seconds.

This seems to happen most often when members of the raid are tightly stacked and can be mitigated by spreading the raid out a bit more.  However, this can be difficult in a melee-heavy 25-man raid, and accidents happen, wiping a raid that is otherwise avoiding the bombs successfully.

This issue, combined with Freya not granting kill credit to players that die during the encounter (#3110 #3093) makes for a frustrating set of circumstances when trying to do attunement runs through Ulduar.

**Comment by Lothloryen** [comment]
Hello there,

This issue will be corrected after the next scheduled maintenance.

Thank you for the report.
