### ISSUE TITLE
Paladin \ Seal of Command and Reckoning

### ISSUE THREAD

**Issue by PinkClassBugs** [dalaranwow/dalaran-wow#3344]
__Current situation__

* When using [_Seal of Command_](http://wotlk.openwow.com/spell=20375) then under the Effects of [_Reckoning_](http://wotlk.openwow.com/spell=20178) the extra swing does not trigger Seal of Command

__Desired situation__

* When using _Seal of Command_ then under the Effects of _Reckoning_ the extra swing triggers Seal of Command

__Spell IDs__

|ID|Name|
|--:|:--| 
|20375|Seal of Command (Buff)|
|20424|Seal of Command (Attack)|
|20178|Reckoning (Buff)|
|32746|Reckoning (extra swing)|
|20182|Reckoning (Talent rank 5)|
|20180|Reckoning (Talent rank 4)|
|20181|Reckoning (Talent rank 3)|
|20179|Reckoning (Talent rank 2)|
|20177|Reckoning (Talent rank 1)|

**Comment by robinsch** [comment]
Please add a proof

**Comment by PinkClassBugs** [comment]
Did some more testing and found out that there is more to this issue, summarized in a new report:

https://github.com/dalaranwow/dalaran-wow/issues/3351
