### ISSUE TITLE
Paladin \ Seal of Command and Vindication

### ISSUE THREAD

**Issue by PinkClassBugs** [dalaranwow/dalaran-wow#3345]
__Current situation__

* If the paladin uses [_Seal of Command_](http://wotlk.openwow.com/spell=20375) and has the _Vindication_ talent specced, the damage dealt by Seal of Command has no chance to trigger the Vindication debuff

__Desired situation__

* If the paladin uses [_Seal of Command_](http://wotlk.openwow.com/spell=20375) and has the _Vindication_ talent specced, the damage dealt by Seal of Command has a chance to trigger the Vindication debuff

__Spell IDs__

|ID|Name|
|--:|:--| 
|20375|Seal of Command (Buff)|
|20424|Seal of Command (Attack)|
|26017|Vindication (Debuff rank 2)|
|67|Vindication (Debuff rank 1)|
|26016|Vindication (Talent rank 2)|
|9452|Vindication (Talent rank 1)|

**Comment by robinsch** [comment]
Please add a proof

**Comment by PinkClassBugs** [comment]
> Seal of Command finds diverse uses, [..], also applying the  [Vindication] AP debuff on multiple targets when Vindication procs. [...]

http://wow.gamepedia.com/index.php?title=Seal_of_Command&oldid=2367694#Usage

---

> When  [Vindication] procs on a weapon swing, the AP debuff is applied to all targets that receive Seal of Command damage.

http://wow.gamepedia.com/index.php?title=Seal_of_Command&oldid=2367694#Notes
