### ISSUE TITLE
hello 

### ISSUE THREAD

**Issue by FabianMihai** [dalaranwow/dalaran-wow#3347]
I THING THIS QUEST IS BUGGED COUS IM STANTING HERE FOR 20 MINUTES AND NO MOSTER APPEARS TO KILL TO DO THE QUEST  [Tears of the Moon] CAN U PLEASE HELP ME ?

**Comment by Golganeth** [comment]
Just checked and the NPC is where it should. Search better.

Closed.

**Comment by Rushor** [comment]
hi :>
