### ISSUE TITLE
DKs can no longer summon their ghouls with Raise Dead.

### ISSUE THREAD

**Issue by syseru** [dalaranwow/dalaran-wow#3348]
Since the latest maintenance updates, DKs can no longer summon their ghouls with the Raise Dead ability, whether they are talented into Master of Ghouls or not. When you attempt to use the ability, it simply does nothing except bug out the cooldown which disallows you from even attempting to re-summon except after a relog or zoning into or out of an area. Neither solves the issue.

**Comment by Lothloryen** [comment]
Hello there,

Thank you for your report, it is really appreciated. Already found what is producing this glitch and it shall be reverted from the main server as soon as I can.
