### ISSUE TITLE
[Quest] The Hero's Arms

### ISSUE THREAD

**Issue by ImprezaWoW** [dalaranwow/dalaran-wow#3349]
Currently no [Scions of Storm](http://www.wowhead.com/npc=30184/scion-of-storm) seem to spawn. They are needed for their drops [Stormhoof's Spear](http://www.wowhead.com/item=42782/stormhoofs-spear) and [Stormhoof's Mail](http://www.wowhead.com/item=42783/stormhoofs-mail) for the quest [The Hero's Arms](http://www.wowhead.com/quest=13049/the-heros-arms).

**Comment by Rushor** [comment]
http://i.imgur.com/2zIfLzz.jpg
http://i.imgur.com/4raBihh.jpg

select * from creature where id=30184

17 creatures are spawned 

tested on local + ptr

**Comment by Klala** [comment]
While this is true, only the lower part of the cave has Scions of Storm wandering about.
There should be more at the entrance and the upper side of the cave

[https://www.youtube.com/watch?v=4ztUvZDXPFM](The Hero's Arms)

**Comment by Zibathy** [comment]
Confirmed that they are missing on upper side of cave. Kirin Tor.

**Comment by TeridanDW** [comment]
Hello, @Zibathy this cave was completely worked in #4353 with the exeption of the mini event.
