### ISSUE TITLE
[NPC] Blood Knight Dawnstar

### ISSUE THREAD

**Issue by ImprezaWoW** [dalaranwow/dalaran-wow#3350]
The NPC [Blood Knight Dawnstar](http://www.wowhead.com/npc=17832/blood-knight-dawnstar), needed for the quest [The Path of the Adept](http://wowwiki.wikia.com/wiki/Quest:The_Path_of_the_Adept) is missing.

**Comment by Rushor** [comment]
http://i.imgur.com/j9OkPbZ.jpg

he's there

tested on local and on ptr server

**Comment by Golganeth** [comment]
It's there in Algalon live realm too.
