### ISSUE TITLE
Paladin \ Seal of Command, unintended short internal cooldown

### ISSUE THREAD

**Issue by PinkClassBugs** [dalaranwow/dalaran-wow#3351]
__Current situation__

* When using [_Seal of Command_](http://wotlk.openwow.com/spell=20375), and a melee swing coincides with an ability, there will be only one proc of Seal of Command instead of two. The same problem occurs under the effects of [_Reckoning_](http://wotlk.openwow.com/spell=20178): the extra swing will not trigger Seal of Command.
* The issue seems to be that Seal of Command has a short internal cooldown that prevents it from procing.

__Desired situation__

* When using [_Seal of Command_](http://wotlk.openwow.com/spell=20375), and a melee swing coincides with an ability, there will be should be a proc of Seal of Command for every attack (swing + ability = 2) that triggers it. Under the effects of [_Reckoning_](http://wotlk.openwow.com/spell=20178) the extra swing should also trigger Seal of Command. (swing + extra swing from Reckoning = 2). If a melee swing under the effects of Reckoning coincides with an ability, there should be three procs (swing + extra swing from Reckoning + ability = 3).
* If it helps to narrow down the issue, Seal of Righteousness procs correctly under all these circumstances. 

__Spell IDs__

|ID|Name|
|--:|:--| 
|20375|Seal of Command (Buff)|
|20424|Seal of Command (Attack)|

__Proof__
It is hard to find proof for something that was never bugged in retail. The way described is the expected behaviour. If this problem occured in retail though, guides would mention it (Retribution guides would tell you about it and might suggest to use a swing timer and not let your swings coincide with abilites, Protection guides would mention it when debating whether to spec Reckoning or not).

**Comment by robinsch** [comment]
Maybe you find something on Youtube.

**Comment by PinkClassBugs** [comment]
@robinsch [WoW 3.2 Ret with Seal of Command - YouTube](https://www.youtube.com/watch?v=EolxL4nrDEE) in the very first seconds (0:02) you see swing plus Crusader Strike triggering two Seal of Command procs as shown by the combat text, also 0:13, 0:46; before 3.2 Seal of Command was PPM based and hit harder, maybe there are still relics from the pre-3.2 logic in the server code that prevent it from proccing in the same moment

**Comment by robinsch** [comment]
No, it has 1 second internal because of procing from self. (Maybe)
I'll fix that, thanks for source.

**Comment by robinsch** [comment]
On PTR
