### ISSUE TITLE
Quest: Mending Fences - Quest Item preforms incorrectly

### ISSUE THREAD

**Issue by Mirashu** [dalaranwow/dalaran-wow#3352]
The quest item "Thorim's Charm of Earth" is supposed to spawn Earthen Ironbane dwarves, which it does, but it only spawns two, and occasionally one, they are supposed to spawn in groups of five, and they are also supposed to spawn on/near the target and start attacking right away.

When the quest item is used, one or two will spawn right next to the player and will not engage, unless you taunt the target with an attack and the target hits the player, only then will the dwarves start to attack.

![wowscrnshot_060216_215536](https://cloud.githubusercontent.com/assets/19287179/15758885/d54f6ada-290c-11e6-9472-cebeb4a51c30.jpg)
![wowscrnshot_060216_215525](https://cloud.githubusercontent.com/assets/19287179/15758886/d550d9b0-290c-11e6-9ccb-d7e3366a99f1.jpg)

**Comment by budthechud** [comment]
Can confirm this action.  I am currently on the quest and I only spawn two fighters who do not attack the target but instead need the target brought to them.  They also do not create the aggro they are supposed to but instead seem to attack normally dealing low/medium threat and one of them taunts every 4-6 seconds.
Everything else seems to be fine but the spawn count and agrro or damage of the npcs does not seem to be working correctly.

**Comment by jonanone** [comment]
Quest item now summons 5 dwarfs that attacks when summoned. The fix will be applied to live realm soon.

**Comment by DalaranLantri** [comment]
Currently spawning 6 dwarfs. @Golganeth managed to spawn 8. 1 initially, and 5 are spawned extra. Only the initial dwarf will run towards mobs. The others will need the mob pulled towards it.

**Comment by Golganeth** [comment]
As soon as the quest item is used one dwarf will spawn. The others will not spawn and charge until the "rock" visually strikes the giant, in some cases up to 9 dwarves will spawn.

Additionally the dwarves will not run away and despawn once a giant is dead. They will be there and won't move at all and take up to 20 seconds to despawn. If an enemy gets close, the old dwarves will charge and players are able to summon new ones (if done fast enough, before old ones disappear) leading to huge group of mobs.

The area seems to lack a few Iron Giants (specially around Fjorn's spawning spot)

https://www.youtube.com/watch?v=CnTDHjrrpCc
