### ISSUE TITLE
Gormok the Impaler, snobolds and fires.

### ISSUE THREAD

**Issue by Crazyphapha** [dalaranwow/dalaran-wow#3353]
Hello,

As of late, the fire bombs thrown by Gormok's snobolds have a way smaller visual than their hitbox, causing people to get hit even if they're not visually in the flames.

Also, fire bombs can apparently stack on a single spot, sometimes oneshotting people in heroic. This might be blizzlike, but I'm not 100% sure so I thought I'd mention it.

Finally, a bug (of which I haven't determined the cause yet) can sometimes cause some snobolds to go invisible and roam around the arena after a wipe, attacking people as if they were alive. The only fix for that is to reset the instance.

Thank you for your attention.

**Comment by Lothloryen** [comment]
Hello there,

This issue has been corrected, it should be active on the live server in few days.

Thank you very much.
