### ISSUE TITLE
Dun Niffelem NPCs are hostile even after doing Sons of Hodir Questline

### ISSUE THREAD

**Issue by Bloodhawk92** [dalaranwow/dalaran-wow#3354]
The NPCs are hostile, meaning we can't do any of the dailies and we can't get the shoulder enchant that we need for PvE.

**Comment by ImprezaWoW** [comment]
Have you tried unchecking the "at War" box next to Sons of Hodir in the Reputations tab?

**Comment by Bloodhawk92** [comment]
Cheers! My mistake
