### ISSUE TITLE
Unholy Blight Stack

### ISSUE THREAD

**Issue by hordecrafter86** [dalaranwow/dalaran-wow#3356]
Unholy Blight does not appear to be stacking correctly. I could not get the damage to stack above 5 stacks, even after stacking it for ten minutes without letting it fall off. Death coil hitting for around 800 which causes the correct 8 damage tick, but as I stack it goes up a little and sometimes goes back down.

**Comment by Golganeth** [comment]
Talent tooltip:
*"Causes the victims of your Death Coil to be surrounded by a vile swarm of unholy insects, taking 10% of the damage done by the Death Coil over 10 sec, and preventing any diseases on the victim from being dispelled"*

Unholy Blight does not have a stacking component and whenever you cast Death Coil again you are supposed to overwrite the rest of the damage.

Incorrect report, closed.

**Comment by hordecrafter86** [comment]
According to the original patch notes from blizzard it does stack:
*Patch 3.2.0* <http://wowwiki.wikia.com/wiki/Patch_3.2.0>* (04-Aug-2009):* This
talent has been redesigned. It no longer deals damage to nearby targets.
Instead, when you deal damage with Death Coil, the target will take
periodic damage for 10 seconds equal to 20% of the damage done by Death
Coil. This damage accumulates in the same way as Ignite
<http://wowwiki.wikia.com/wiki/Ignite> and Deep Wounds
<http://wowwiki.wikia.com/wiki/Deep_Wounds>.

There are also builds on old elites jerks that reference this
(comprehensive DK tanking guide on Dalaran forums). Currently it appears to
stacks while the original ten second unholy blight is in effect then they
appear to start dropping off. I believe based on past forums of retail and
patch notes that this is supposed to stack as long as you reapply before
timer runs out. Thanks for the quick initial response.

**Comment by Golganeth** [comment]
My bad.

**Comment by hordecrafter86** [comment]
k, I thought maybe they had just reduced the damage by 10%, down from 20%. If that is the case though... still seeing some stacking... was able to get it from 8 damage tick up to a 40 damage tick...

**Comment by hordecrafter86** [comment]
also, in 3.3.3:
Unholy Blight: In addition to its previous effects, this talent now also prevents diseases from being dispelled from victims afflicted by Unholy Blight.

"effects" implies more than one thing, ongoing damage and stacking effect.

Sorry to be a bother about all of this. If I need to drop it I will.

**Comment by Golganeth** [comment]
If you have found something about Unholy Blight that isn't working as intended, then consider open a proper and accurate report. This one isn't, since Unholy Blight shouldn't stack.

As I copied earlier:
*Patch 3.3.0 (08-Dec-2009): This talent now deals only 10% of Death Coil damage as a damage-over-time effect on the target.*

**"now deals only 10%"** makes any older behavior irrelevant.

Thanks!

**Comment by hordecrafter86** [comment]
ok, got it, thanks, and sorry for the confusion.

**Comment by robinsch** [comment]
Well I think hordecrafter86 is correct. Damage got nerfed from 20% to 10% in 3.3.0 - this is not related to stacking.

**Comment by robinsch** [comment]
Tested, stacking works correctly.

**Comment by Golganeth** [comment]
I tested this and doesn't work as intended. Also @hordecrafter86 is right when he mentions some kind of weird damage stacking happening right now.

As of this patch it shouldn't have any stacking component, as wowwiki and tooltip implies. Will open an accurate report about this

**Comment by hordecrafter86** [comment]
so should it stack indefinitely or is it limited to the ten second duration
of the dot? That is the first one falls off after ten seconds instead of a
new application keeping it up.

**Comment by Golganeth** [comment]
Yes indeed, the *"deals only 10% damage"* makes reference to the nerf, and it doesn't imply that the stacking damage part was removed. I've totally misread it.

The damage should stack similarly to Sheath of Light from paladins. Example:
- You refresh the blight when it had 3 seconds left, which means 3 ticks of damage left.
- Every tick was doing, for example, 10 damage. This means the old blight had still 30 damage to be done.
- The 30 damage will be equally distributed between the 10 next ticks of the new blight, so it will add 3 damage to each of the 10 ticks.

If you find something that might not be working as intended feel free to report it, but as Robin says it seems to work fine, we both tested it.

/closed

**Comment by hordecrafter86** [comment]
Thank you, that extra bit explanation about the remaining damage being
spaced out really helped my sanity.
