### ISSUE TITLE
[Achievement] Upper Back Pain - keeping two snowbolds alive

### ISSUE THREAD

**Issue by ashido96** [dalaranwow/dalaran-wow#3358]
http://prntscr.com/bc4hzm

http://www.wowhead.com/achievement=3797/upper-back-pain-10-player#comments

Don't know what causes it, you're not given credit when icehowl is killed with 2 snowbolds alive, screenshot for proof.

People in the raid: Camp, Sarilia, Sendreavus, Shoens, Timbosmash, Genocidex, Imc, Laquer, Verna, Wannabe

**Comment by Lothloryen** [comment]
This was working as intended, let me check what happened.

**Comment by ashido96** [comment]
Might be that one of the players the snowbolds was on top of died? 
So the snowbold was still alive but not "attached" to anyone, that might be the issue.

**Comment by Tarpor** [comment]
This also did not work for us a few months ago. No player died.

**Comment by Lothloryen** [comment]
Hello there,

This issue by no having the achievement granted under certain conditions has been corrected. It should be active on the live server in few days.

Thank you very much.
