### ISSUE TITLE
[ToC 10] - Snobold Vassal can attack anyone in raid at unlimited range

### ISSUE THREAD

**Issue by ashido96** [dalaranwow/dalaran-wow#3359]
http://www.wowhead.com/npc=34800/snobold-vassal

When we we're attempting the upper back pain achievement, #3358 we ran into an issue where the snobold on top of our hunter was able to attack our resto druid from across the entire room.
This wouldn't typically be noticed during normal raiding but as we were keeping the snobolds alive throughout the encounter having it hitting the healers made it quite difficult.

**Comment by Lothloryen** [comment]
Hello there,

This issue has been corrected, it should be active on the live server in few days.

Thank you very much.
