### ISSUE TITLE
Prospecting Northrend Ore's Broken.

### ISSUE THREAD

**Issue by tahkune** [dalaranwow/dalaran-wow#3362]
I have been having trouble with prospecting, i have found out that Prospecting any ore is broken " having a chance to yield no gems while prospecting and destroys your ore at the same time".

Can this be revised and balanced so that prospecting ore's will always produces a proper gem amount.

this would be one working example upon prospecting:
Cobalt Ore: 
60% chance to produce 1 uncommon gem
25% chance to produce 2 uncommon gems
10% chance to produce 3 uncommon gems
5% chance to produce 1 rare gem

total chance to proc for a gem or gems from prospecting equals 100% chance.

**Comment by ImprezaWoW** [comment]
[#230](https://github.com/dalaranwow/dalaran-wow/issues/230)
