### ISSUE TITLE
silver covenant guardian mage

### ISSUE THREAD

**Issue by szattara** [dalaranwow/dalaran-wow#3363]
the silver covenant guardian mage in dalaran teleported me to the pad and acted like i was entering the alliance area, but i wasn't.
i was just passing by on my way to the fishing trainer to turn in my daily fish qeust.
it forces the player to stay on the pad since it teleports u every second or so. so ur really just stuck.

-z

**Comment by Rushor** [comment]
this is caused by some player who use the army of dead ghul on the guards - the guards should actually be immune to this

**Comment by Rushor** [comment]
kay the guards and all other npcs in dalaran should no longer be attackable by some pets

and due to this they will no longer act strange and teleport player

**Comment by Golganeth** [comment]
Issue with #2517 still stands though. Corrupted Ashbringer makes random NPCs (included Dalaran) attackable, and makes bankers move out of their spots.

**Comment by szattara** [comment]
tip: if u party up and qeu a dun u wont be stuck anymore.
