### ISSUE TITLE
axe training

### ISSUE THREAD

**Issue by olinger** [dalaranwow/dalaran-wow#3365]
I cannot train the axe skill on my blood elf paladin, neither weapons master in Orgrimmar have anything to train me, even though I don't have either axe skill trained yet.

**Comment by Golganeth** [comment]
Make sure you haven't already learned the skill and that you are talking to the correct NPCs/displaying the options correctly. If steps above didn't help, it could be a visual bug or an issue related to your client. Re-install it if the problem persists.

Both NPCs are working just fine as shown below (in-game ss):

![image](https://cloud.githubusercontent.com/assets/5057942/14751864/7519d5d4-08cc-11e6-9a1c-b368ce118c71.png)

Closed.
