### ISSUE TITLE
Quest / NPC: Harp on This! / Xink's Shredder

### ISSUE THREAD

**Issue by Golganeth** [dalaranwow/dalaran-wow#3367]
**Issue:** You can't enter Xink's Shredder once you summon it with the provided quest item.

http://wotlk.openwow.com/quest=12052
http://wotlk.openwow.com/npc=27061

**Comment by Rushor** [comment]
yes this also counts for many vehicles currently, some tc commit broke it in 2015 (not shure which one)

**Comment by jonanone** [comment]
Once the quest item is used, the player will be automatically mounted on the Xink's Shredder. This fix will be applied to the live realm soon.
