### ISSUE TITLE
[Quest][Classic] Scarlet Prisoner in Brill

### ISSUE THREAD

**Issue by AcadianBacon** [dalaranwow/dalaran-wow#3368]
The Scarlet Prisoner in Brill who gets fed a pumpkin is permanently transformed into a ghoul and is standing away from where he's supposed to be. He doesn't reset even if you turn in the quest.

**Comment by Rushor** [comment]
http://www.wowhead.com/quest=407/fields-of-grief

**Comment by Rushor** [comment]
* add faster respawn for Captured Scarlet Zealot
* actually kill Captured Scarlet Zealot after the morph

**Comment by Golganeth** [comment]
Works great, but the NPC dies (as a ghoul) and respawns right away as human, so it looks weird.

**Comment by Rushor** [comment]
ecce009881995654c63a5067f889549db3749d96
- kay will respawn now after 30 seconds, that will look less weirdo

**Comment by Golganeth** [comment]
The respawn timer is short the first time, but the second time around is around 6 mins, it's probably okay though.
