### ISSUE TITLE
[BUG] Orc Warrior in Valley of Trials Weapon Error

### ISSUE THREAD

**Issue by AcadianBacon** [dalaranwow/dalaran-wow#3369]
The Orc Warrior's starting weapon appears as a question mark, and is not recognized as a weapon by the game. None of the warrior's abilities work because it says that there is no main-hand weapon even though the orc warrior is holding his two-handed axe.

**Comment by Rushor** [comment]
seems to be a client issue, make shure that you download the game correctly http://www.dalaran-wow.com/

http://i.imgur.com/xduhvzW.jpg

**Comment by AcadianBacon** [comment]
That's not the problem, if you were to click on your Battle Stance, you would notice that the 'Heroic Strike' would say 'Requires Melee Weapon' in red, meaning that you can't use it. Even with enough Rage to use it I couldn't, and a lot of other things were in red because they said that I didn't have a melee weapon equipped.

After killing enough things to get a new weapon that solved the problem, it's purely the starter weapon that was the problem.

**Comment by Golganeth** [comment]
It's a client side issue where the game doesn't detect the starter weapon. Rest of the weapons work fine
