### ISSUE TITLE
[BUG] NPC Jamie Nore Geometry/Clipping in Brill Town Hall

### ISSUE THREAD

**Issue by AcadianBacon** [dalaranwow/dalaran-wow#3370]
The NPC Jamie Nore who wanders in the Town Hall in Brill is always either half-way submerged in the ground or completely underground and only pops up sometimes when she walks around.

**Comment by Rushor** [comment]
http://www.wowhead.com/npc=2310/jamie-nore

the rndmmovement was simply wrong  

- rndmmovement removed
