### ISSUE TITLE
[Quest][Classic] Lazy Peons in Valley of Trials stuck in chopping animation

### ISSUE THREAD

**Issue by AcadianBacon** [dalaranwow/dalaran-wow#3371]
Many of the Lazy Peon NPCs get stuck on wood-chopping animations or just stand still, refusing to go to sleep and making it impossible for people to use them for the quest.

**Comment by Rushor** [comment]
true, rebuff time was now reduced to 80 seconds (it was 5 minutes)

**Comment by Golganeth** [comment]
The timer only runs if a player/gm is present, so if the player leaves right away after awakening them, another player will have to sit there.
Fix for AI or make the timer even shorter

**Comment by Rushor** [comment]
hmkay setting it active should work then

**Comment by Rushor** [comment]
creatures are now for a short time "active" and does not require an active gridcell (with player) in order to reapply the sleepbuff
