### ISSUE TITLE
[BUG] Fell through the ground in Western Plaguelands

### ISSUE THREAD

**Issue by whalen525** [dalaranwow/dalaran-wow#3373]
I was questing on my paladin Aldurah on the main realm, and while in Dalson's Farm between the outhouse and the main building I happened to fall through the ground. Now I'm stuck in free fall, unable to so much as log out properly, let alone do anything to escape

**Comment by Rushor** [comment]
https://github.com/dalaranwow/dalaran-wow/issues/3374

**Comment by ImprezaWoW** [comment]
If you're still stuck in this situation, please make an in-game ticket so GMs can assist you.
