### ISSUE TITLE
DB/GO: Archavon's Log - Missing Counter

### ISSUE THREAD

**Issue by Rushor** [dalaranwow/dalaran-wow#3383]
**Description**:
http://www.wowhead.com/object=194356/archavons-log#comments
Archavon's Log should shows the number of:
Horde:  
 Keep Defended: $4024w
 Keep Captured: $4022w

Alliance:
 Keep Defended: $4025w
 Keep Captured: $4023w

**Current behaviour**: Tell us what happens
if you open Archavon's Log the result will be:
```sql
Horde:  
 Keep Defended: 0
 Keep Captured: 0

Alliance:
 Keep Defended: 0
 Keep Captured: 0
```
even if you just won/loose a couple of games/wintergraps

**Expected behaviour**: Tell us what should happen instead
If you open open the book, there should be the number of all won/loosed matches of wintergrasp for the horde and for the alliance.

**Steps to reproduce the problem**:
.go object 87581
.bf start 1
.bf stop 1
open book > see that there will be no change at all

**Comment by Rushor** [comment]
counters should now be displayed correctly
(testable with .bf start 1/ bf stop 1 (3 times))

**Comment by Golganeth** [comment]
Doesn't seem to work on PTR.

**Comment by Rushor** [comment]
works fine here http://i.imgur.com/Usyus1L.jpg

someone needs to enable the battlefield on the worldserverconfig on ptr

# BATTLEFIELD CONFIG
#
#     Wintergrasp.Enable
#         Description: Enable the Wintergrasp battlefield.
#         Default:     0 - (Disabled)
#                      1 - (Enabled, Experimental as in incomplete, bugged and with crashes)Wintergrasp.Enable = 0

**Comment by Golganeth** [comment]
It should work once it's applied to live realm.
