### ISSUE TITLE
[Quest][Classic] Dream Dust in the Swamp

### ISSUE THREAD

**Issue by Rushor** [dalaranwow/dalaran-wow#3389]
http://www.wowhead.com/quest=1116/dream-dust-in-the-swamp

upon reward on creature http://www.wowhead.com/npc=773/krazek he should say some texts

**Comment by Rushor** [comment]
8f25448cac99fb4f651f9ebf0449fc34b042c842
- endevent added

**Comment by Golganeth** [comment]
Says "ACHOO!" twice and the next quote exactly at the same time.

**Comment by Rushor** [comment]
0fc196acc9fac3d356c231d0fcc089265b6f15a9
fixed
