### ISSUE TITLE
[Quest][Classic] Nothing But The Truth

### ISSUE THREAD

**Issue by Rushor** [dalaranwow/dalaran-wow#3392]
http://www.wowhead.com/quest=1383/nothing-but-the-truth

big textevent after reward at npc http://www.wowhead.com/npc=5414/apothecary-faustin missing

**Comment by Rushor** [comment]
c5ce4caf75226712bf3bf6ed37a0222efd1db350
- textevent added

**Comment by Golganeth** [comment]
Apothecary Faustin says: The serum will only take a few minutes to prepare, $N.

yet it only takes 10 seconds to prepare, maybe replace the word 'minutes' for 'seconds'.

**Comment by Rushor** [comment]
2d9c867de841fd6ab2e1573450324e12c4fa0dbc
- minutes > seconds
