### ISSUE TITLE
[Quest][Classic] Barov Family Fortune

### ISSUE THREAD

**Issue by Rushor** [dalaranwow/dalaran-wow#3394]
http://www.wowhead.com/quest=5341/barov-family-fortune
questevent upon reward at creature http://www.wowhead.com/npc=11022/alexi-barov is missing

**Comment by Rushor** [comment]
4785fab7192d1098b8a8c70d5bceeb0fdb0a3a34
- texts added

**Comment by Golganeth** [comment]
Missing texts for Alliance Version it seems, different NPC (Weldon Barov)
http://wotlk.openwow.com/quest=5343 Quest
http://wotlk.openwow.com/npc=11023 NPC

**Comment by Rushor** [comment]
could'nt find anything on him if you compare http://wowwiki.wikia.com/wiki/Alexi_Barov with http://wowwiki.wikia.com/wiki/Weldon_Barov (only some aggrotext)

**Comment by Golganeth** [comment]
Indeed. Nevermind, discarded
