### ISSUE TITLE
Dalaran Arena

### ISSUE THREAD

**Issue by Lukas45** [dalaranwow/dalaran-wow#3397]
the Dalaran Arena (zone: 4378) is not part of the arena shuffle.
Couldn't find anything saying that it's disabled, so well, bugreport!

**Comment by Plexieglas** [comment]
:dancer:

**Comment by Rushor** [comment]
It was said in the forum http://www.dalaran-wow.com/ some time ago. You do not need to open an issue for this. Once the arena will be enabled and implemented, you can open up specified bugreports
