### ISSUE TITLE
[Quest][Classic] A Terrible Purpose

### ISSUE THREAD

**Issue by Rushor** [dalaranwow/dalaran-wow#3400]
```sql
-- A Terrible Purpose  - Reward
UPDATE `quest_template` SET `RewardMailTemplateId`=110, `RewardMailDelay`=86400 WHERE `id`=8287;

DELETE FROM `mail_loot_template` WHERE `entry`=110;
INSERT INTO `mail_loot_template` (`entry`, `item`, `ChanceOrQuestChance`, `groupid`, `mincountOrRef`, `maxcount`) VALUES
(110, 20645, 100, 0, 1, 1);
```

you should get that mail upon reward

**Comment by Rushor** [comment]
011ab81cdaa2166b894837b64da15ab1e2a5bff0
- 24 h after reward of quest http://wotlk.openwow.com/quest=8287 you will get a mail with the item 20645

**Comment by Golganeth** [comment]
The mail is sent to players but there's no item attached to it, only the letter.
Item that should be attached: http://www.wowhead.com/item=20645/natures-whisper
