### ISSUE TITLE
[Quest][Classic] The Tower of Althalaxx

### ISSUE THREAD

**Issue by Rushor** [dalaranwow/dalaran-wow#3405]
http://www.wowhead.com/quest=970/the-tower-of-althalaxx

after you complete that quest, a big textevent should happen

**Comment by Rushor** [comment]
2818956b0f7d3e220541b7f7af8a956325dbaa5f
- texts added

**Comment by Golganeth** [comment]
[18:35:22]Delgren the Purifier says: Soulgem bursts open!
[18:36:02]Delgren the Purifier says: Sargath fades into the mist...

%s needs to be implemented for those two, rest is fine.

**Comment by Rushor** [comment]
70662ae771f471165924f924bad503b002d5cc6d
- added
