### ISSUE TITLE
Mage Talent Ice Barrier

### ISSUE THREAD

**Issue by jonnyrocket0** [dalaranwow/dalaran-wow#3407]
Ice Barrier is not working as intended. It should absorb all damage, not just physical. When I have Ice Barrier up, I still take spell damage. 

From wowpedia:

_Ice Barrier is a mage talent available at level 30. It is an important defensive cooldown, shielding the caster for up to 60 seconds, absorbing damage similarly to a priest's  [Power Word: Shield]. The shield absorbs physical, magical, and most environmental damage (fall damage is not absorbed). Damage from DoTs such as poison is also absorbed._

http://wow.gamepedia.com/Ice_Barrier

**Comment by Rushor** [comment]
http://i.imgur.com/UjLjks5.jpg
Rushor absorbiert Zerrissene Erde von Elementarformer der Ymirjar.(2026 absorbiert)

tested with npc 31267 - it fully absorbs the spelldamage

tested on ptr and locally
