### ISSUE TITLE
Quest : Reclamation

### ISSUE THREAD

**Issue by Kaporalhart** [dalaranwow/dalaran-wow#3408]
For the quest "Reclamation" in sholazar basin, given by the npc Avatar of Freya, each of the 3 recquired mobs (Ugreth of the Thousand tombs, Hailscorn, Bythius the Flesh-Shaper) have a very long respawn timer (about an hour) So only one player can do it every one hour, that's not cool.

**Comment by Kaporalhart** [comment]
Weirdly enough, Bythius the Flesh-Shaper's pet, Cerberon, has a normal spawn rate. he's always there.

**Comment by Rushor** [comment]
adding the new despawn respawn action will work here

**Comment by Golganeth** [comment]
Reopening #1615
