### ISSUE TITLE
[QUEST] Lost But Not Forgotten (Item Drop Rate)

### ISSUE THREAD

**Issue by AcadianBacon** [dalaranwow/dalaran-wow#3409]
Drop rate of Kron's Amulet is set quite low. I killed every Crocolisk in the river three times (amounting to roughly 35-40 mobs) before it dropped. Not sure if it's just bad luck on my part or if the drop rate is set lower than it should normally be.

**Comment by Rushor** [comment]
https://github.com/dalaranwow/dalaran-wow/issues/256
