### ISSUE TITLE
Uld 10 Razorscale not lootable

### ISSUE THREAD

**Issue by Oximusprime** [dalaranwow/dalaran-wow#3410]
We finished up a guild run in Ulduar 10 man just 2 nights ago and when we finished off Razor, she was not lootable.
![wowscrnshot_060516_235818](https://cloud.githubusercontent.com/assets/19806470/15873577/f7856b7a-2cc4-11e6-87e0-e230d8476ee0.jpg)

If at all possible we would enjoy the loot, but please check into this boss to make sure that nothing went wrong in the fight.

Thanks!

**Comment by Golganeth** [comment]
This is a general issue that may happen (very rarely) if Master Looter is changed throughout the fight or if a raid member is offline. Given the circumstances, it's still not guaranteed to happen.

General issue so closing up. Make an in-game ticket
