### ISSUE TITLE
[Paladin] - Exorcism delaying its damage

### ISSUE THREAD

**Issue by NovaHiros** [dalaranwow/dalaran-wow#3411]
Basically what the title says - looks like the damage is "traveling" to the target, and not being istant like it should. Happens in melee range too.

**Comment by robinsch** [comment]
https://github.com/dalaranwow/dalaran-wow/issues/2952

**Comment by NovaHiros** [comment]
Why is this closed? And why are you merging this with a totally different mechanic? I Don't really get it tbh but - as of yesterday exorcism was good as it was - today is another story. Just try it youself.

**Comment by Rushor** [comment]
@NovaHiros: the fix from #2952 also contains a solution for this issue here, so robinsch merged it together. :)

**Comment by NovaHiros** [comment]
Honeslty I can't see why this is closed. One week after the initial report the issue still persist and this is still closed. Issues are different and the fix meant for #2925 probably is the cause for this - exorcism became a "missile" hence doesn't instantly hits the target. Keep this open, please.
