### ISSUE TITLE
[Quest] Unwelcome Guests

### ISSUE THREAD

**Issue by Kaporalhart** [dalaranwow/dalaran-wow#3412]
The quest "Unwelcome guests" in storm peaks, given by Fjorlin Frostbrow in Frosthold, is hard to complete. You're supposed to kill 10 iron dwarves in the cave North-West of Frosthold, Frostgrip's Hollow, but only 3 or 4 dwarves spawn at the entrance of the cave, the rest of it is empty. I had to wait for the them to respawn 3 times to complete the quest.

**Comment by Rushor** [comment]
pls add the questid from wowhead

**Comment by Golganeth** [comment]
http://www.wowhead.com/quest=12876

**Comment by Rushor** [comment]
37557540c19705f7ff8004334f3ac3453cc2c8fc
- added serveral spawnpoints for creatures: 29586, 29843, 29862
