### ISSUE TITLE
[Druid][Tallent] Lunar Guidance

### ISSUE THREAD

**Issue by silvermax1** [dalaranwow/dalaran-wow#3413]
Lunar Guidance
Rank 3
Increases your spell power by 12% of your total Intellect. 
 
The tallent Lunar Guidance currently doesn't show any increase in spell power on your character sheet. I suspect that it doesn't scale in actual combat either.

**Comment by Golganeth** [comment]
Tested in both PTR and live realm and talent works as intended.

Closed.
