### ISSUE TITLE
[Quest] Going Bearback

### ISSUE THREAD

**Issue by Kaporalhart** [dalaranwow/dalaran-wow#3414]
The quest going bearback in stormpeaks, Valley of ancient winters, given by Brijana http://www.wowhead.com/quest=12851/going-bearback is difficult to complete.

There's only one of the 7 worgs you have to burn. the 15 frost giants you have to kill are fine. I had to make 6 trips, going super slow on one of them to hit the same worg twice.

**Comment by Rushor** [comment]
@Kaporalhart: could it be the case, that the other worgs are already killed by some npcs?

**Comment by Kaporalhart** [comment]
Maybe near the entrance of the area, i've seen the female vrykul npcs riding on bears and fighting mobs, but the worgs are supposed to be all over the area, they couldn't have possibly gone so far and kill all but one of them.

**Comment by Rushor** [comment]
hm for me, all worgs will be killed by the other creatures

i will implement a flagextra which prevents specific creatures to kill each other

**Comment by Rushor** [comment]
feb9228c0e7f780535e8d95490d51f842d547b26
 - implemented flag extra: CREATURE_FLAG_EXTRA_NO_CREATURE_DAMAGE for creatures 29358, 29351, 29500, 29498 - so these creatures can no longer be killed by other npcs (this does not affect pets)
