### ISSUE TITLE
[Quest] Cold hearted

### ISSUE THREAD

**Issue by Kaporalhart** [dalaranwow/dalaran-wow#3415]
The npcs for this quest http://www.wowhead.com/quest=12856/cold-hearted , the Brunnhildar Prisonners, have a much too long respawn time.

**Comment by Rushor** [comment]
5177bcee6cba6de24fb7205e760678afeab7fb84
- according to some videos the respawntimer should be around 100 seconds for creature 29639 (remember the corpse delay)

**Comment by darkwyrm88** [comment]
There's an issue with the Captive Proto Drakes. When a player mounts one of them, they are unable to change altitude. You can fly on x/y axis only, not Z.
