### ISSUE TITLE
[Quest ] The Slithering Darkness

### ISSUE THREAD

**Issue by Kaporalhart** [dalaranwow/dalaran-wow#3416]
Same problem as #3412, but here it concerns the ravenous jormungar in Hibernal cavern. (thanks Rushor for taking care of all these so quickly)

**Comment by Kaporalhart** [comment]
Now that i've gone farther into the sons of hodir quest lines, i can see that the cave was phased back then. Be careful to only add the ravenous jormungar to those who are phased.

**Comment by Rushor** [comment]
http://www.wowhead.com/npc=29605/ravenous-jormungar

**Comment by Rushor** [comment]
068780a4874097d89a9d08ebd6c0183d2818562c
- added some further spawns for the creatures which are required for http://www.wowhead.com/quest=12989/the-slithering-darkness
