### ISSUE TITLE
[Item] Bank Bags

### ISSUE THREAD

**Issue by Billyww** [dalaranwow/dalaran-wow#3417]
I put a new bag in my personal bank for storage. I tried putting things in it and they vanished. I tried leaving the area and coming back and put some smaller things from the bank's main slot area into the same bag and it traded for the items I had seen vanish. Not sure why but they are invisible for me.

**Comment by ashido96** [comment]
/rl /reload /reloadui pick your choice and use one.

**Comment by Rushor** [comment]
http://us.battle.net/wow/en/forum/topic/2416202254

either invisible slot in guild bank or use reload ui - this will fix your issue :)
