### ISSUE TITLE
Call to Arms / Specific Battleground

### ISSUE THREAD

**Issue by LoveDalaranWow** [dalaranwow/dalaran-wow#3418]
**Description**: When queueing for a Specific Battleground (most notably the Call to Arms ones), the queue doesn't pop unless the exact number of people required joined that specific Battleground too. Additionally, Call to Arms Battlegrounds are not taken into account for the "Call to Arms" achievement. Seems like the Random Battleground and the specific one queues are completely separate.

**Expected behaviour**: No need to explain how specific queue works, but for the achievement part, even if you win the Call to Arms battleground, it doesn't appear as completed for the achievement progress.

**Steps to reproduce the problem**:

1.  Queue for a specific Battleground
2.  Look at the people queued (usually 0)

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**
http://wowwiki.wikia.com/wiki/Call_to_Arms!_(Alliance)
http://wowwiki.wikia.com/wiki/Call_to_Arms!_(Horde)
http://wowwiki.wikia.com/wiki/Battlegrounds_holiday (as 3.3 the Battleground holidays are called "Call to Arms")

**Comment by Golganeth** [comment]
The achievement is about the quests, not the battleground itself. Merge with #1788
