### ISSUE TITLE
[Item] Emblem drops from Heroic Dungeons

### ISSUE THREAD

**Issue by LoveDalaranWow** [dalaranwow/dalaran-wow#3419]
**Description**:  In different forum threads it has been discussed the way Emblems drops should work, but since the launch of Algalon nothing changed regarding that matter. Most people ignore completely the 5-man instances after getting the required gear to start raiding (some even skip that part), making queue times unnecessarly long (mostly fresh 80s queue for them) and killing the 5-man experience.

**Current behaviour**: Every boss drops only Heroism (regardless your attunements) and you get no extra emblems for finishing a Random WOTLK Dungeon.

**Expected behaviour**: http://www.dalaran-wow.com/forums/news-and-rules/suggestions-and-opinions/topic/2126/algalon-progressive-emblem-drops This is how Emblems drops should work, based on what Devs claimed, there is a specific graph showing everything posted by a member of the staff.

**Steps to reproduce the problem**:
1.  Play a Random Heroic Dungeon
2.  Kill the required bosses and see they drop only Emblems of Heroism
3.  Notice how you don't get the additional emblems for completing the Dungeon

**Comment by ashido96** [comment]
The server is purposely constructed in such a way that there are reduced "catch-up" mechanics, this is entirely intended and not a bug. The only thing to be changed would be getting 2 emblems of heroism when completing the first random heroic each day.

**Comment by LoveDalaranWow** [comment]
Yes, but still the model posted by the staff was a bit different from what is now.
Not to count the instance locks happening even if you queue for a random dungeon.

**Comment by LoveDalaranWow** [comment]
Any ETA for this?

**Comment by Serpentsting** [comment]
Bump.

**Comment by Rushor** [comment]
The system works fine on PTR. Such changes (specific for Dalaran WoW) can only be handled by the server owner.
