### ISSUE TITLE
Visibility Issue

### ISSUE THREAD

**Issue by LoveDalaranWow** [dalaranwow/dalaran-wow#3422]
**Description**: NPCs, Objects, Players appear only when very close to them or after a while standing/moving very close to them (most notably the golem in the Thorim's gauntlet can't be seen properly). This happened to every player, without resolution changes, people from the staff claim that this is a server-side issue and that was supposed to be fixed relatively soon (the statement is about 1 month+ old). This makes extremely tedious farming ores/herbs, finding NPCs for quests or any other kind of use, PvPing in general, where you can't see enemies properly.

**Expected behaviour**: You should be able to see NPCs, Object, Players from a much bigger distance (people used to see other Players from one starting platform of Eye of the Storm to the other).

**Steps to reproduce the problem**:

1. Run/Fly in any zone
2. NPCs, Objects, Players will appear later than they are supposed to do

**Include proofs for this behaviour**

The staff is aware, and any GM can confirm the issue is still a thing.

**Comment by Rushor** [comment]
This is set in the configs in order to reduce lags and high uptimediff. This cannot be changed for now

**Comment by LoveDalaranWow** [comment]
Any ETA for the fix?

**Comment by LoveDalaranWow** [comment]
Too bad, thanks anyway for the reply.
