### ISSUE TITLE
Vault of Archavon entrance requirements and boss despawns

### ISSUE THREAD

**Issue by LoveDalaranWow** [dalaranwow/dalaran-wow#3423]
**Description**: The raid Vault of Archavon in Wintergrasp is accessible by every faction at any moment, regardless of the owner of the Wintergrasp Fortress, also bosses inside do not turn into stone and become invulnerable, nor despawn at all (when not in combat) 10 minutes before a battle is about to begin, as they were supposed to. This creates a situation where the Wintergrasp battle becomes insignificant and there is absolutely no reason for players interested in the raid to join it, since they can enter the raid regardless of the battle outcome, at any time, either walking into the entrance or glitching trough walls (I don't know which walls are involved tho).

**Current behaviour**: As explained before, the raid is accessible by people from the faction not owning Wintergrasp at any given moment. Also, bosses are killable and can be engaged anytime, even during the battle of Wintergrasp.

**Expected behaviour**: People should either get a message when trying to enter the instance or not be allowed at all to enter the keep (glitching the walls or entering after losing a battle, since the main gate is down). Additionally, bosses who are not in combat 10 minutes before the battle starts should become not targetable and immune to damage.

**Steps to reproduce the problem**:

1. Enter the raid when the opposite faction owns the keep.

1. Wheter you own or not the keep (1st part of the issue), just wait in front of a boss and wait until 10 minutes are left before the next battle, nothing will happen to the bosses.

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

http://wowwiki.wikia.com/wiki/Vault_of_Archavon
http://www.wowhead.com/zone=4603/vault-of-archavon#npcs
http://www.wowhead.com/npc=31125/archavon-the-stone-watcher
http://www.wowhead.com/npc=33993/emalon-the-storm-watcher
http://www.wowhead.com/npc=35013/koralon-the-flame-watcher

**Comment by ashido96** [comment]
Specifically involves getting into one of two wedges on the front side with a small flying mount, then using a large mammoth push your character through the wall and spamming jump. Thus jumping into the room in front of the entrance to VoA.

**Comment by kalvindeane** [comment]
Or parking characters inside and using the summon stone.

**Comment by LoveDalaranWow** [comment]
Regardless of the method, it kills the whole Wintergrasp zone and everything related.

**Comment by LoveDalaranWow** [comment]
Is this ever going to be looked at?

**Comment by Lothloryen** [comment]
Every issue will be looked into bit by bit, bumps will not have any effect though.

Thank you.

**Comment by LoveDalaranWow** [comment]
I just asked it since it's one of the few issues who didn't get a single tag, so I was just wondering if people from the staff actually read it and was aware of it, considering it completely breaks one of the zones in Northrend.
My apologies and thanks for the answer.

**Comment by Lothloryen** [comment]
No problem at all, perfectly understandable. 

Thank you.

**Comment by robinsch** [comment]
- [ ] Enter VoA while under enemy faction control
- [ ] Despawn (or put them into Stone) 10min before WG match

**Comment by robinsch** [comment]
1. on PTR.

**Comment by LoveDalaranWow** [comment]
http://www.wowhead.com/forums&topic=138471/anyway-to-get-into-voa-without-owning-wg

Check Crevox's answer, he posted it during the 3.3 patch



Also, this is a reply in the Vault of Archavon comments

**Comment by robinsch** [comment]
All Bosses in Vault of Archavon will now evade and put themselves into stone.
