### ISSUE TITLE
[Warrior][Spell]Charge

### ISSUE THREAD

**Issue by Beatlejuicey** [dalaranwow/dalaran-wow#3424]
When the charge move is used it places you inside the target instead of next to it, and many times you are forced to step back in order to engage "not all the time" but its annoying as hell.
This is an issue that has been reported and dismissed/deleted several times before yet the problem still exists, somebody even went as far to say this is retail like...when clearly it is not.
![wowscrnshot_060916_120945](https://cloud.githubusercontent.com/assets/12934688/15928274/e1ea9248-2e3d-11e6-80ef-3aaa731fdf93.jpg)
https://www.youtube.com/watch?v=5ogzVL4jzRE

**Comment by Rushor** [comment]
cbbab4b67d6db05612f0f3af42185e55362f68fe
http://i.imgur.com/Of3pFXa.jpg
- charge will now calculate unitTarget->GetObjectSize() + unitTarget->GetMeleeReach()
- this fix is only on ptr

**Comment by Beatlejuicey** [comment]
Great work keep it up guys

**Comment by Rushor** [comment]
it's currently only on ptr

**Comment by Lukas45** [comment]
Will this also apply to [Demon Charge](http://wotlk.openwow.com/spell=54785) (Warlock metamorphosis charge), since it suffers from same issue?

**Comment by Rushor** [comment]
all chargeeffects yes
