### ISSUE TITLE
[Spell] [Bug] [Druid] Ferocious Bite too low damage

### ISSUE THREAD

**Issue by Craftymind** [dalaranwow/dalaran-wow#3428]
**Description**: Ferocious Bite, at any rank, do too low damage to any target, regardless of their lvl and armor. It doesn't crit that much, for me at least. Maybe I'm unlucky with RNG or something... but the damage is the main problem.

**Current behaviour**: When executing Ferocious Bite at any number of combos (especially whith bonus energy), the damage dealt to monsters is too low compared to the base damage on the spell and to the level and armor of the mobs.
For example: at lvl 70 (now), when only buffed with my mark of the wild (rank 8), Ferocious bite (rank 6) show that, at 5 combos, deals 1883 - 1949 damage (with 2804 AP in Cat form and 35.14% crit chance). When executed on any lvl 69 or 70 monstre in Tundra Borean, I almost always (let's say 90% of the time) get 1100 normal damage and barely 2200 damage on crits. The remaining 10% of the time, sometimes I get 1400 normal damage and 2400 - 2700 crits.

N.S.: I had this problem since early lvls but it really started to show big difference at this higher lvl. And, I don't have any points in Rend and Tear talent.

**Expected behaviour**: I didn't understand the formula on the wowwiki site, but let me put it this way: Unless all mobs have 50%+ physical damage reduction or something like that, this shouldn't be happening. Something is off here. Be aware that I'm talking about MY character here, I don't know if other druids have the same problem or not.

**Steps to reproduce the problem**:
1. Charge up your combos on the target (4 or 5, because no one uses a finishing move with any less then that number of combos anyway)
2. execute Ferocious Bite
3. Compare the damage dealt to the base damage while taking into consideration the lvl and armor of the monsters. you can even try that on lvl 60-68 mobs if you want.

**Include proofs for this behaviour** I have none !!! I can't take picture of this because it's a series of events, and I can't take a video of it because I don't have a program to do it and my PC is kind of weak for playing live and recording videos...

Ferocious Bite ID: the ID differ from a rank to another, here are the IDs from rank 1 to 8:
1) 22568
2) 22827
3) 22828
4) 22829
5) 31018
6) 24248 (currently at lvl 70)
7) 48576
8) 48577

Have a nice day all !!!

**Comment by Rushor** [comment]
hm there was already an issue about this here https://github.com/dalaranwow/dalaran-wow/issues/3285

are you shure about the wrong armour-damage calculation?

**Comment by Lukas45** [comment]
Since the issue mentioned above doesn't contain much info (OP got deleted).
Did you test the damage on a dummy? Because the armor on the dummy is wonky (doesn't apply fully/too much in certain cases), and is horrible for physical damage testing.

**Comment by dxxa** [comment]
Never seen a player that reporta spells positive buggged of their class, has been always reported bugs in the negative, so the server does not help, you do only your interests
In your class there are many bugs in a positive, return them please let

**Comment by Rushor** [comment]
Fixed with:

https://github.com/TrinityCore/TrinityCore/commit/e8528717a55fbddf1ad6a7061aae5f7e293b18af
https://github.com/TrinityCore/TrinityCore/commit/d9d433f59db477c9e457d0774487a3ae7168bb75
https://github.com/TrinityCore/TrinityCore/commit/19560fcea1222b17119b6ebd124643a88d703c22
https://github.com/TrinityCore/TrinityCore/commit/bad4b059c8652173d97891aa5a8a326ac0718961

With further merges this fix will be applied on the live realm.
