### ISSUE TITLE
[NPC] Ragnaros the Firelord

### ISSUE THREAD

**Issue by PSAlias** [dalaranwow/dalaran-wow#3434]
**Description**: It is possible to kill Ragnaros while he is untargetable. The corpse will remain untargetable, and thus unlootable.

**Current behaviour**: Exactly 3 minutes after combat is initiated with Ragnaros (which occurs following a scripted event started by speaking with Majordomo Executus after his own defeat), Ragnaros enters "Phase 2," "submerges," and becomes invisible and untargetable to players. A number of Son of Flame NPCs are spawned at this time. When all of these are killed or Banished or when 90 seconds have elapsed (whichever comes first) "Phase 2" ends, Ragnaros reappears and another three minute timer begins until "Phase 2" restarts. However, during "Phase 2", Ragnaros retains some or all effects placed on him during combat, including Damage over Time effects, which have the potential to kill him while untargetable. The animations for his death successfully trigger, achievements are granted for his death as normal, and the corpse is visible, but it remains untargetable, and thus unlootable.

**Expected behaviour**: Unsure. It is possible that upon submerging, Ragnaros should become immune to damage or wipe all dubuffs placed on him, or it is possible that killing him in this manner should be doable, but in either case, loot drops should be obtainable.

**Steps to reproduce the problem**:

1. Engage Ragnaros in combat via the event with Majordomo Executus
2. Wait until "Phase 2" when Ragnaros submerges and Son of Flame NPCs are spawned
3. Kill Ragnaros before this phase ends (most likely using any means will trigger the issue, but using DoT effects with sufficient damage to reduce Ragnaros to 0 HP at some point during the submerged phase was the original trigger)

**Include proofs for this behaviour**

http://wow.gamepedia.com/Ragnaros_%28tactics%29

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

NPCs:
Ragnaros: 11502
Majordomo Executus: 12018
Son of Flame: 12143

Spells:
Banish: 710
Ragnaros Submerge Visual: 20567
Ragnaros Submerge Fade: 21107

Zone:
Molten Core: 2717

**Comment by Rushor** [comment]
37dbb8f9838513b88f9df79ea7731dc69cc1cbc1

Scripts/MoltenCore: Raganros - Remove all auras while submerging

* closes https://github.com/dalaranwow/dalaran-wow/issues/3434
