### ISSUE TITLE
[NPC] Defias Traitor won't spawn

### ISSUE THREAD

**Issue by SnowBeard** [dalaranwow/dalaran-wow#3437]
**Description**: This is the 6th quest in the Defias Brotherhood quest chain, where the Defias Traitor should be at the bottom of the of the steps underneath Sentinel Tower in Westfall. When someone is currently doing the escort quest, it is unavailable, however, no one is doing the quest. I have run multiple times from Moonbrook to Sentinel Tower, camped out in front of his spawn point for hours, and asked in general chat as well.  He seems permanently despawned at the moment, preventing anyone from doing the quest or the final quest in the Defias Brotherhood chain of killing Van Cleef in the Deadmines.

**Current behaviour**: Westfall, bottom of Sentinel Tower, permanently despawned Defias Traitor.

**Expected behaviour**: He should spawn and allow people to complete the quest.

**Steps to reproduce the problem**: Just go and see that he is not there, and that waiting for hours does not spawn him, even when you are at that point in the quest chain. 

http://wotlk.openwow.com/npc=467
http://www.wowhead.com/npc=467/the-defias-traitor#screenshots:id=9918

**Comment by Rushor** [comment]
duplicate from #2579
