### ISSUE TITLE
[Quest] The Fleshworks

### ISSUE THREAD

**Issue by budthechud** [dalaranwow/dalaran-wow#3438]
**Description**:Attempted four times while in The Fleshwork in Icecrown to complete a quest.  It appears that when cancelling a spell it cause a critical error.

**Steps to reproduce the problem**:

1. Be on quest Destroying the altars as a druid
2. Attempt to destroy the altar with the quest item
3. Cancel the spell or quickly switch to flight/travel form immediately after completing the channel

**Include proofs for this behaviour**
Here is the critical error in whole: http://pastebin.com/YXt9GkL1

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**
Quest I was on: http://www.wowhead.com/quest=13119/destroying-the-altars
Quest Item to use: http://www.wowhead.com/item=43159/master-summoners-staff

**Include Screenshots from the issue if necessary**
http://i.imgur.com/ZST3mA5.png

**Comment by Rushor** [comment]
e3510b952db21604c6c5d6fa907417b1ad54b580
- criterror removed
- only on ptr

**Comment by budthechud** [comment]
So was it the item causing it or the zone. I'm curious because it seemed to happen after I finished casting and during my travel or flight switching stance switch.

**Comment by Rushor** [comment]
if you use the item and cancel it with [esc] or by casting another spell, you will get the crit error
