### ISSUE TITLE
[Quest] Mantles of the Dawn

### ISSUE THREAD

**Issue by PSAlias** [dalaranwow/dalaran-wow#3439]
**Description**: All 6 Mantles of the Dawn are available from Argent Quartermaster vendors regardless of whether players have completed the prerequisite quests. Also, the three vendors offer the quests independently from each other.

**Current behaviour**: The Mantles of the Dawn and Chromatic Mantles of the Dawn quests are offered independently by each of the three Argent Quartermaster NPCs, Argent Quartermaster Lightspark, Argent Quartermaster Hasana, and Quartermaster Miranda Breechlock, to players that have reached the requisite repuation level with the Argent Dawn faction. Completing one of these quests does not disable the ability to take the other versions. Argent Quartermaster Hasana offers all six Mantles for sale to all characters, regardless of quest completions and reputation with Argent Dawn. (unsure about behavior of other two vendors)

**Expected behaviour**: Players should be unable to purchase Chromatic Mantles until they have completed one of the Chromatic Mantles quests. These quests, as well as purchasing the other Mantles, should require any one of the regular Mantles quests. The Chromatic Mantles quests should require Exalted reputation with AD, and the regular Mantles quests should require Revered. Currently having or completing a version of either quest should disable the ability to obtain the other versions.

**Steps to reproduce the problem**:

1. Interact with Hasana's vendor window while at Neutral reputation with Argent Dawn and note the availability of mantles for purchase
2. Become Exalted with AD and complete the Mantle Quests offered by Breechlock
3. Interact with Hasana and note that she still offers her version of the quests

**Include proofs for this behaviour**

http://www.wowhead.com/quest=5517/chromatic-mantle-of-the-dawn#comments
http://www.wowhead.com/quest=5504/mantles-of-the-dawn#comments

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

NPCs:
Argent Quartermaster Hasana: 10856
Argent Quartermaster Lightspark: 10857
Quartermaster Miranda Breechlock: 11536

Items:
Flame Mantle of the Dawn: 18169
Frost Mantle of the Dawn: 18170
Arcane Mantle of the Dawn: 18171
Nature Mantle of the Dawn: 18172
Shadow Mantle of the Dawn: 18173
Chromatic Mantle of the Dawn: 18182

Quests:
Mantles of the Dawn: 5504 (AQH)
Chromatic Mantles of the Dawn: 5524 (AQH)
Mantles of the Dawn: 5507 (AQL)
Chromatic Mantles of the Dawn: 5521 (AQL)
Mantles of the Dawn: 5513 (QMB)
Chromatic Mantles of the Dawn: 5517 (QMB)

Faction:
Argent Dawn: 529

**Comment by jonanone** [comment]
- Quests won't be repeatable anymore.
- Mantles sold by Hasana requires having completed the prerequisite quests.

This fixes will be applied to the live realm soon.

**Comment by PSAlias** [comment]
The Chromatic Mantles quests appear to still be repeatable.

**Comment by jonanone** [comment]
- Mantles of the Dawn and Chromatic Mantle of the Dawn quests are now exclusive (can only be completed by one of the three npcs that gives the quest)
- More conditions to Mantle items have been added. Now Lightspark and Breechlock will only sell the items once the quests are completed.

**Comment by Edzero** [comment]
Working on PTR.

**Comment by TeridanDW** [comment]
Works as intended on ptr.
