### ISSUE TITLE
[Raise Ally] doesn't work at all ...

### ISSUE THREAD

**Issue by Sartorios** [dalaranwow/dalaran-wow#3440]
**Description**:

death knight spell : [Raise Ally] bug

**Current behaviour**: 

the spell doesn't work at all

**Expected behaviour**: 

it should raise one of the group members as a ghoul.

![avatar1038451_2](https://cloud.githubusercontent.com/assets/19866492/15982418/54c6677c-2f8f-11e6-877c-94cc6fc4b269.gif)

**Comment by Daveonx** [comment]
Reported already.  https://github.com/dalaranwow/dalaran-wow/issues/848
