### ISSUE TITLE
View distance

### ISSUE THREAD

**Issue by Devineshadow** [dalaranwow/dalaran-wow#3441]
Weird view distance:

Whenever I am roaming in the world, no matter ground or fly mount the mobs/pickable objects (mines/herbs/etc) start showing up when I am at a very close proximity. Even on the minimap when I have "find herbs" for example the herbs themselves start glowing on the map when I am extra close to them.
To be honest I have no experience with WoW's GM thing but I've played alot different servers throughout the years, even retail, and this is the first time I encounter such problem. I've asked in global chat ingame about this and it's not just me, everyone seems annoyed by it. Some say the view distance has been reduced on purpose. I found no information about this issue in the forums, so I decided to post/ask here. Is this issue fixable?

**Comment by Rushor** [comment]
Nope this is not fixable currently. If we increase the visibility range the uptime diff will increase X 2. Once we find a solution/improvement for this, we will let you know it in the forum

**Comment by beregas** [comment]
This is very annoying for everything that i am doing either out or indoor

**Comment by robinsch** [comment]
@beregas I will implement a way to dynamic reduce or increase visibility distance according to the amount of player currently online.

**Comment by Dean1989** [comment]
i can't even do a bit of world pvp because i don't see 3m more than my nose

**Comment by robinsch** [comment]
Should be implemented within a few days.

**Comment by beregas** [comment]
No implemention yet?

**Comment by Randomi** [comment]
Is it me or it has been improved lately ?

**Comment by beregas** [comment]
how do i thumbs up this?

**Comment by Rushor** [comment]
http://i.imgur.com/FtUCd3e.png

**Comment by beregas** [comment]
any update on live for this?

**Comment by TeridanDW** [comment]
That's pretty impossible to test on ptr while having only few people online. I can say with the population on ptr we have the normal 90 yards view distance in open world. Marking with waiting for changelog and waiting for feedback from live realms.

**Comment by TeridanDW** [comment]
Possible performance issue (might be related to `uptime diff`).

There are few creatures [Invisible Stalker](http://www.wowhead.com/npc=15214/invisible-stalker) ID - 15214 in Angrathar the Wrathgate, Dragonblight that are constantly summoning [Frail Construct](http://www.wowhead.com/npc=27604/frail-construct) and overtime we get this (within ~ 5mins only):
![image](https://cloud.githubusercontent.com/assets/6797611/25970029/e948dcb4-369f-11e7-90ae-30720e3b41f7.png)
![image](https://cloud.githubusercontent.com/assets/6797611/25970041/f11b28ca-369f-11e7-8adb-cd900d87f613.png)

**Comment by TeridanDW** [comment]
Update: After 1 hour of staying in that area my MS rised from 30 to 221.

**Comment by beregas** [comment]
the question is: will it finally be implemented with icc patch or not??

**Comment by beregas** [comment]
ICC is live for a month, wheres the fix?
