### ISSUE TITLE
Intervene doesn't reduce target's threat by 10%

### ISSUE THREAD

**Issue by LoveDalaranWow** [dalaranwow/dalaran-wow#3442]
**Description**: As the title states, Intervene is supposed to reduce the threat of the target by 10% when used, but it doesn't.

**Expected behaviour**: Upon the use, the threat should be reduced by 10%, but regardless of the threat meter used, this doesn't happen.

**Steps to reproduce the problem**:

1.  Let someone get some threat and then ask him to stop at a given threat
2.  Intervene him
3.  Watch his threat being unchanged

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

http://wotlk.openwow.com/spell=3411

**Comment by Rushor** [comment]
b537cced87b72ed360296da5cd4a375aaa9f91c4
- will now reduce the aggro from the target by 10%
 - only testable on ptr
