### ISSUE TITLE
Valkyrion Must Burn

### ISSUE THREAD

**Issue by sixele** [dalaranwow/dalaran-wow#3443]
**Description**:
The Harpoon Guns usable for the quest [Valkyrion Must Burn](http://www.wowhead.com/quest=12953/valkyrion-must-burn) can be moved around the area, I've heard that you can migrate with them anywhere, even to other zones, but I haven't tried that.
**Current behaviour**: 
Zone: Storm Peaks
Harpoon Guns move around once mounted.
**Expected behaviour**: 
Harpoon Guns should not move around once mounted.
**Steps to reproduce the problem**:

1. Take the mentioned quest;
2. Mount the Harpoon Gun;
3. Use WASD as usual to move around.

**Include proofs for this behaviour**

[How it currently is (sorry for the lag at one point and shitty quality, enough to get the point anyways)](https://youtu.be/ju_paXRNVB0)

**Comment by Rushor** [comment]
4853754feb901b909b6f67f8d0905003fb339ba7
- cannons are no longer moveable
- testable on ptr

**Comment by Alavarin** [comment]
Cool, now quest is uncompletable because of shitty draw distance - you can't see stacks of hay so you can't hit them (even if you point aim exactly at the spot they are).

**Comment by Rushor** [comment]
that a general problem of the visible range - an update for this will be done in the future.

**Comment by beregas123** [comment]
Any update on the visibility issue?

**Comment by Rushor** [comment]
not yet
