### ISSUE TITLE
[NPC] Short John Mithril

### ISSUE THREAD

**Issue by PSAlias** [dalaranwow/dalaran-wow#3444]
**Description**: Short John Mithril's arena events do not correspond to a strict 3 hour schedule

**Current behaviour**: Short John Mithril spawns a chest roughly every 2 hours 50 minutes if players are continually somewhere nearby (he stays loaded). However, if no one opens this chest before the next one is due to be spawned, the event is delayed until someone does, altering the timer schedule. This also occurs if no one is in the area and Short John Mithril is not loaded when the event is due to start. I suspect this is a similar issue to that encountered in #3371, and separate from #85 .

**Expected behaviour**: The event should trigger every three hours at precisely 0000, 0300, 0600, 0900, 1200, 1500, 1800, and 2100 Server Time, regardless of player actions. If a chest is not opened, it should despawn after 15 minutes.

**Steps to reproduce the problem**:
1. Trigger the arena chest event. Open the chest and wait for, at most, 3 hours.
2. When the next chest is spawned, do not open it. Wait for another 3 hours before doing so.
3. Open the subsequent chest and clear the area of all players for 4 hours before returning.

**Include proofs for this behaviour**

http://www.wowhead.com/npc=14508/short-john-mithril#comments

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

Object:
Arena Treasure Chest: 179697

NPC:
Short John Mithril: 14508

Zone:
Stranglethorn Vale: 33

**Comment by PSAlias** [comment]
As of late I've noticed that the chest is spawning with regularity at 0100, 0400, 0700, 1000, 1300, 1600, 1900, and 2200 ST. Unsure if this is simply because players are consistently picking up the chests or if the issue has been fixed, but at least the 3 hr timer is now working correctly.

**Comment by Rushor** [comment]
Same here, the event triggers now every 3 hours.
