### ISSUE TITLE
[NPC][Temple of Ahj'Qiraj] - Battleguard Sartura hits too hard

### ISSUE THREAD

**Issue by Klala** [dalaranwow/dalaran-wow#3445]
**Description**: Battleguard Sartura hits too hard

**Current behaviour**: It happened about a month ago, maybe you fixed it already but I haven't seen any reports about it in here. I went with a group to Ahn'Qiraj 40 and the boss Battleguard Sartura one shotted us all cloth and plate alike. He hits be for 150k (leather) and whirlwind for 300k. our dk tank said he hits him for about 80k. 

**Expected behaviour**: Obviously a vanilla boss shouldn't hit for more than 10k hp (which is the close to or the max hp a tank in vanilla could have) on plate armor

**Steps to reproduce the problem**:

1.  Go into Temple of Ahn'Qiraj
2. Maker your way to Battleguard Sartura and start the fight.
3. Behold his unimaginable damage!

Unfortunately you will have to trust my word because I didn't bother to screenshot or record it, sorry!

**Comment by LoveDalaranWow** [comment]
Yeah, he hits extremely hard even on plates (80k per tick)

**Comment by ashido96** [comment]
Specifically it's his whirlwind thing, normal hits are fine. He seems to move slower during this so if you just have two tanks (or any taunter) kite and continue taunting off eachother you can complete it pretty easily that way as a workaround.

**Comment by Rushor** [comment]
e7a91bd6ee6738c2f7905a0e70d4a2322f45c41d
- limited the damage to 999

**Comment by Golganeth** [comment]
First hit on pull:
> Battleguard Sartura's melee swing hits Golganeth for 14813 Physical.(224054 Overkill).

**Comment by Rushor** [comment]
58efff033f01d700225c548d78d46f104e0cfe7e
- baseattack was way too large
