### ISSUE TITLE
[Quest] Ruthless Cunning #952 

### ISSUE THREAD

**Issue by socialmedia1** [dalaranwow/dalaran-wow#3446]
**Reference the title**:
Previously reported  Quest: Ruthless Cunning 9927

http://www.wowhead.com/quest=9927/
Place Warmaul Ogre Banner on top of a fallen Kil'sorrow agent.
Players are able to place the banner anywhere no condition for area nor Kil'sorrow agent corpse
http://www.wowhead.com/item=25552

Issue was reported and closed in FEB however the issue is still happening. I am able to place the "Warmaul Ogre Banner" anywhere in Kilsorrow Fortress without killing anything and get credit. 
![capture](https://cloud.githubusercontent.com/assets/8617360/15992020/07735f46-3077-11e6-9721-93f3617db49f.PNG)

**Comment by jonanone** [comment]
The flag can only be used now on Kil'sorrow creatures and Giselda. It cannot be used once the quest is completed (but not yet rewarded). The fix will be applied to the live realm soon.
