### ISSUE TITLE
[NPC] Zeptek the Destroyer

### ISSUE THREAD

**Issue by budthechud** [dalaranwow/dalaran-wow#3447]
**Description**: Zeptek spawning without limit

**Current behaviour**: He is spawning without limit
**Expected behaviour**: Zeptek is supposed to spawn and despawn with Warlord Tartek but isn't

**Steps to reproduce the problem**:

1. Kill Tartek without killing Zeptek 

**Include proofs for this behaviour**
http://i.imgur.com/bxVtjV9.jpg

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

http://wowwiki.wikia.com/wiki/Zeptek_the_Destroyer

**Comment by jonanone** [comment]
Zeptek now despawns when Tartek dies. This update will be applied to the live realm soon.
