### ISSUE TITLE
[Quest][Classic] The Tower of Althalaxx

### ISSUE THREAD

**Issue by Aquanis** [dalaranwow/dalaran-wow#3448]
This quest requires the player to slay Athrikus Narassin and retrieve his head.  The drop is apparently broken, as I have killed him several times without seeing the head.

**Comment by Rushor** [comment]
http://www.wowhead.com/quest=1143/the-tower-of-althalaxx

**Comment by Rushor** [comment]
http://i.imgur.com/A2NhYTe.jpg

droppchance is 100 %, works fine
