### ISSUE TITLE
Quest: Into the realm of shadows. Stuck in Shadow Realm

### ISSUE THREAD

**Issue by vinpi** [dalaranwow/dalaran-wow#3453]
**Description**: Stuck in the Shadow Realm when doing the 'into the realm of shadows' questline with death knight after giving horse.

**Current behaviour**: Delivered horse, but did not get to deliver quest (although it says complete), now stuck in Shadow Realm. Has tried to kill horse rider again but cannot take the horse. 

**Expected behaviour**: When delivering the horse I should exit the shadow realm.

**Steps to reproduce the problem**:

1. Get quest and take horse as expected
2. when you get to the hill as soon as you enter death's breach call Salanar.
3. I am now stuck in the shadow realm

**Include proofs for this behaviour**

You can research this on several pages like http://wowhead.com or http://wowwiki.wikia.com or http://www.youtube.com/

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

You can research this on several pages like http://wotlk.openwow.com or http://wowhead.com/

**Include Screenshots from the issue if necessary**

**Comment by Lothloryen** [comment]
Hello there,

This seems an isolated case, many players do it on a daily basis. If anyone experiences this issue again, let us know, please.

Thank you.
