### ISSUE TITLE
[Ulduar] Salvaged Choppers Cannot Ferry Pyrite to Demolishers

### ISSUE THREAD

**Issue by saltylopez** [dalaranwow/dalaran-wow#3454]
Currently, during the siege encounter before Flame Leviathan and the encounter with Flame Leviathan itself, Salvaged Choppers are unable to pickup units of Pyrite.

**Expected behaviour**: 
On retail, Chopper pilots could use an ability (http://www.wowhead.com/spell=67372/grab-pyrite) to hook pyrite units into their passenger seat, ferry that pyrite over to a demolisher and eject the pyrite next to the demolisher.  The Demo gunner would then be able to hook the pyrite to refill their vehicle's ammo.

**Include proofs for this behaviour**
http://wowwiki.wikia.com/wiki/Flame_Leviathan <--- Refers several times to Choppers bringing ammo to Demos, it's also the primary role of a Chopper if the raid is not launching players onto Flame Leviathan.

**Comment by Lothloryen** [comment]
Hello there,

I forgot to update this issue, this was fixed already. Thank you for the report.
