### ISSUE TITLE
[Quest][Alliance] Call of Earth - Slow Respawn

### ISSUE THREAD

**Issue by cosminn123** [dalaranwow/dalaran-wow#3455]
**Description**: The [Restless Spirit of Earth](http://wotlk.openwow.com/npc=17179) have a long respawn time.

**Current behaviour**: After killing the mobs, they respawn way too slow. It takes around 3-4min.

**Expected behaviour**: The respawn time should be reduced by half at least.

**Steps to reproduce the problem**:

1. Get the quest.
2. Kill the mobs.
3. Wait for respawn.

**Include proofs for this behaviour**

Couldn't find proof of actual respawn time.

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

Quest: http://wotlk.openwow.com/quest=9450

Creature: http://wotlk.openwow.com/npc=17179

**Comment by Rushor** [comment]
c98e750a83d26e570fe14462ed107c560ec78fe6
- reduced the respawn to 240 seconds (this does not include the corpse delay)
