### ISSUE TITLE
[NPC] Stormscale Sorceress

### ISSUE THREAD

**Issue by deda2400** [dalaranwow/dalaran-wow#3457]
**Description**:NPC Stormscale Sorceress is missing both spells.

**Current behaviour**: mob is currently only doing melee attacks

**Expected behaviour**: mob should cast frost armor every 10 sec and cast Frostbolt

**Steps to reproduce the problem**:

1. Go to ruins of Mathystra in Darkshore  56.21
2. find stormscale sorcress
3. attack mob

**Include proofs for this behaviour**
http://wotlk.openwow.com/npc=2182
http://wowwiki.wikia.com/wiki/Stormscale_Sorceress
You can research this on several pages like http://wowhead.com or http://wowwiki.wikia.com or http://www.youtube.com/

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

You can research this on several pages like http://wotlk.openwow.com or http://wowhead.com/

**Include Screenshots from the issue if necessary**

**Comment by Rushor** [comment]
07ce3d78181b6726694b7229b82f8df70de8afa2

10 seconds makes no sence, they should cast it every 2300,3900 milliseconds like every other caster in the world
