### ISSUE TITLE
[Quest] Retest Now

### ISSUE THREAD

**Issue by ImprezaWoW** [dalaranwow/dalaran-wow#3460]
**Description**:
Since [#256](https://github.com/dalaranwow/dalaran-wow/issues/256) got closed and, quoting Rushor "there are some quests which require 100% droppchance for some item, pls add a new issue for this, that must be fixed in db then", adding this as a separate issue even though it was in the post mentioned above.
**Current behaviour**: 
[Tainted Essences](http://wotlk.openwow.com/item=44301) for the quest [Retest Now](http://www.wowhead.com/quest=13357/retest-now) are not 100% drops.
**Expected behaviour**: 
The Tainted Essences should be 100% drops.
**Steps to reproduce the problem**:

1. Take the quest Retest Now;
2. Drink the [item provided for the quest](http://www.wowhead.com/item=44307/diluted-cult-tonic);
3. Kill the Cult members.

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

Quest Daily Horde [Retest Now](http://www.wowhead.com/quest=13357/retest-now) ID 13357
Quest Horde (1st time) [Retest Now ](http://www.wowhead.com/quest=13356/retest-now) ID 13356

Quest Daily Alliance [Retest Now](http://www.wowhead.com/quest=13322/retest-now) ID 13322
Quest Alliance (1st time) [Retest Now](http://www.wowhead.com/quest=13321/retest-now) ID 13321

Item [Tainted Essence](http://wotlk.openwow.com/item=44301) ID 44301
Item [Diluted Cold Tonic](http://www.wowhead.com/item=44307/diluted-cult-tonic) ID 44307
**Cult members**
[Dark Subjugator](http://wotlk.openwow.com/npc=32236) ID 32236
[Void Summoner](http://wotlk.openwow.com/npc=32259) ID 32259
[Shadow Channeler](http://wotlk.openwow.com/npc=32262) ID 32262
[Cult Taskmaster](http://wotlk.openwow.com/npc=32268) ID 32268
[Cult Blackguard](http://wotlk.openwow.com/npc=32276) ID 32276
[Vile Torturer](http://wotlk.openwow.com/npc=32279) ID 32279
[Damned Apothecary](http://wotlk.openwow.com/npc=32289) ID 32289
[Cult Alchemist](http://wotlk.openwow.com/npc=32290) ID 32290
[Cult Researcher](http://wotlk.openwow.com/npc=32297) ID 32297
[Cultist Shard Watcher](http://wotlk.openwow.com/npc=32349) ID 32349

**Comment by jonanone** [comment]
Added 100% chance to drop Tainted Essence while using Diluted Cult Tonic.
This update will be applied to the live realm soon.
