### ISSUE TITLE
[Quest] Raptor Mastery (part 4)

### ISSUE THREAD

**Issue by Bonham01** [dalaranwow/dalaran-wow#3465]
**Description**: Final quest in Hemet Nessingwary's Raptor Mastery chain

**Current behaviour**: The raptor needed to complete this quest, Tethis, takes way too long to respawn. I killed the raptors around him at least 6 times before he respawned. I didn't kill him the first time either so he could have been dead for a while before I got there.

**Expected behaviour**: Tethis should respawn faster

**Steps to reproduce the problem**:

1. Get quest 
2. Go there
3. Kill him and wait for him to respawn

**Include proofs for this behaviour**

No proof but it's not hard to recreate

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

Quest: http://wotlk.openwow.com/quest=197
NPC: http://wotlk.openwow.com/npc=730

Similar to issue #3464

**Comment by ImprezaWoW** [comment]
The current respawn timer is 30 minutes. Most of the comments say that the respawn timer should be shorter - some people say 7 minutes, some people say 10, and I found a place which says 15 minutes. I will include every comment I found about it, but keep in mind that the links are from different patches:
[15 minutes](http://looking4group.de/quelthalas/database/?npc=730)
[7 minutes (care for the comment on it)](http://www.wowhead.com/npc=730/tethis#comments:id=927953)
["good 10 minutes"](http://www.wowhead.com/npc=730/tethis#comments:id=59242:reply=323409)
[Someone from 3.3.5a patch confirming that it's 30 minutes(Czech)](https://wotlk-twinhead.twinstar.cz/?npc=730#comments)
[German thread about respawn timers, might have relevant information (Rushor, this is for you!)](https://redmine.rising-gods.de/issues/5485)
