### ISSUE TITLE
[Quest] Foolish Endeavors

### ISSUE THREAD

**Issue by budthechud** [dalaranwow/dalaran-wow#3467]
**Description**: Varidus, Getry, and Suarfang are despawning before the completion of the quest Foolish Endeavor.  Saurfang is spawning and killing everything like he should but when Varidus gets low he just despawns along with every one else involved in the quest.

**Current behaviour**: Varidus Unit disappears between 5-10% health causing Saurfang, and Shadowstalker Getry to despawn and quest must be dropped and restarted when Getry respawns in his tower.

**Expected behaviour**: After the shadow prison the Necrolord approaches the player revealing himself as Saurfang.  The player, Getry, and Saurfang then fight Varidus and the adds spawned from the field.  Saurfang uses Bladestorm to clear the adds and together the three bring down Varidus.

**Steps to reproduce the problem**:
1. Accept quest from Getry
2. Move down to field and wait for RP to complete
3. Wait for Saurfang to reveal himself
4. Attempt to kill Varidus to complete quest

**Quest** : http://www.wowhead.com/quest=11705/foolish-endeavors
**NPCs Involved**
Varidus: http://www.wowhead.com/npc=25618/varidus-the-flenser
Saurfang: http://www.wowhead.com/npc=25256/high-overlord-saurfang
Getry: http://www.wowhead.com/npc=25729/shadowstalker-getry

**Comment by jonanone** [comment]
Just tried 4 times today and worked properly. Closing the issue for now. If the issue happens again please feel free to reopen.

**Comment by Evyll** [comment]
Just did the quest. Same bug as the "Current Behaviour" describes

**Comment by Swork91** [comment]
Issue still exists. Varidus and crew despawn 3 minutes after being engaged if Varidus is not killed soon enough.

**Comment by powerpuffgurl** [comment]
up.

from what i'm reading if we just hit him once we should get the quest done. but they disappear too fast, not enough time for the guy to die.

**Comment by roblockster** [comment]
NPCs despawn before quest is completed. Please reopen.

**Comment by Crispybuilt** [comment]
Can confirm on PTR the issue still persists, re-opening.

**Comment by Aridam** [comment]
Confirmed -- despawned after a few minutes (approximately 3m). Need to help burst down otherwise it's just not doable.
