### ISSUE TITLE
[NPC] Christi Stockton

### ISSUE THREAD

**Issue by sixele** [dalaranwow/dalaran-wow#3469]
**Description**:
Very important bug (sike). Missing emote.
**Current behaviour**: 
Christi Stockton does not respond to /drink.
**Expected behaviour**: 
She responds to /drink with "One more bottle? I don't see any reason why not!" and then laughs.
**Steps to reproduce the problem**:

1. Go to Christi Stockton in Dalaran;
2. emote /drink;
3. nothing happens.

**Include proofs for this behaviour**
http://wowwiki.wikia.com/wiki/Christi_Stockton
http://www.wowhead.com/npc=32337/christi-stockton#comments:id=527097

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

Christi Stockton, NPC ID 32337

**Comment by Rushor** [comment]
sweet

**Comment by Rushor** [comment]
c8f5adb96f36c009ccb08d721ff25f47245386a4
DB/Creature: Christi Stockton - Add emotescript

* closes https://github.com/dalaranwow/dalaran-wow/issues/3469
