### ISSUE TITLE
Argent Pony Bridle not unlocking the new features for the argent companion

### ISSUE THREAD

**Issue by LoveDalaranWow** [dalaranwow/dalaran-wow#3470]
**Description**: After the purchase and use of the Argent Pony Bridle for the Argent Squire/Bruntling pet, he still acts as a normal vendor.

**Expected behaviour**: He's supposed to give you the chance of use him as a mailbox, guildbank and that feature has a 4hour cooldown (pet still summonable), as this video shows https://www.youtube.com/watch?v=7Vectgmyto4&fmt=22

**Steps to reproduce the problem**:

1.  Buy the APB and use it
2.  Summon the companion
3.  Notice the missing features

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

http://www.wowhead.com/item=47541/argent-pony-bridle
http://www.wowhead.com/spell=62609/argent-squire 
http://www.wowhead.com/item=45022/argent-gruntling

https://www.youtube.com/watch?v=7Vectgmyto4&fmt=22

**Comment by ImprezaWoW** [comment]
[#2535](https://github.com/dalaranwow/dalaran-wow/issues/2535)
