### ISSUE TITLE
Lockboxes in Angor Fortress - Blasted Lands

### ISSUE THREAD

**Issue by Lukodi** [dalaranwow/dalaran-wow#3471]
**Description**: The lockboxes have a wrong respawn rate, as in, they don't really respawn at all.

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who) The lockboxes for lockpicking don't respawn.

**Expected behaviour**: Tell us what should happen instead They should respawn.

**Steps to reproduce the problem**:

1. Make them respawn
2. 
3. 

**Include proofs for this behaviour**

You can research this on several pages like http://wowhead.com or http://wowwiki.wikia.com or http://www.youtube.com/

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

You can research this on several pages like http://wotlk.openwow.com or http://wowhead.com/

**Include Screenshots from the issue if necessary**

**Comment by Golganeth** [comment]
#1667

**Comment by swiftdeath** [comment]
Still an issue.

**Comment by tyler200100** [comment]
Confirmed. Its been 2 hours.

**Comment by Rushor** [comment]
the issue will be handled in https://github.com/dalaranwow/dalaran-wow/issues/1667. pls add the gameobjectids in that issue https://github.com/dalaranwow/dalaran-wow/issues/1667 thank you.
