### ISSUE TITLE
[BUG] Valley of ancient winters mobs not dropping loot

### ISSUE THREAD

**Issue by Zallera** [dalaranwow/dalaran-wow#3472]
Currently some Mobs in the valley of ancient winters in storm peaks are not dropping loot.

The mobs: 
Stoic Mammoth (http://www.wowhead.com/npc=30260/stoic-mammoth)
Ravenous Jormungar (http://www.wowhead.com/npc=30291/ravenous-jormungar)
and Roaming Jormungar (http://www.wowhead.com/npc=30422/roaming-jormungar)
in the valley of ancient winters area of storm peaks only seem to be dropping quest items. 

Instead the mobs should be dropping items off their respective loot tables. I was able to loot quest items off the mammoths but nothing else after killing several dozen mobs in the area.

**Comment by jonanone** [comment]
Added missing loot for the 3 creatures. The fix will be applied to the live realm soon.

**Comment by Zallera** [comment]
The problem seems to be back, killed about 2 dozen of the above mobs this morning on my alt and didn't see even a single grey drop, one of the recent fixes seems to have broken it because the mobs were dropping items a few days ago when i was mining in the area.
