### ISSUE TITLE
[Quest] The Shining Light

### ISSUE THREAD

**Issue by cybergeek94** [dalaranwow/dalaran-wow#3473]
**Description**:
This quest is assigned by Ares the Oathbound in the Utgarde Catacombs zone of Howling Fjord.

He asks you to go down into the deepest area of the Catacombs to retrieve the Sacred Artifact item. He gives the player a buff, Shining Light (10 min), which instantly kills any ghouls or maggots that come near the player in the area leading up to the artifact.

**Current behaviour**: 
When the player picks up the Sacred Artifact item, the Shining Light buff immediately fades, leaving the player defenseless against the horde of ghouls between him/her and the stairs back up to Ares.

**Expected behaviour**: 
The Shining Light buff should remain on the player until they turn in the quest to Ares the Oathbound.

**Steps to reproduce the problem**:

1. Get the quest.
2. Pick up the Sacred Artifact.
3. Note that the Shining Light buff has faded.

**Evidence**

See the following video:

https://youtu.be/6khs0bXfcgI?t=52s

Though the quality is horrible, it is not hard to tell that the buff remains on the player after retrieving the Sacred Artifact item, as it kills ghouls as he/she runs back through them to turn the quest in.

**Impact**

The quest is far from impossible to complete if the player has good enough mitigation/shields or group CC to get back through the mobs alive. However, depending on the class and spec, it may require using some very long cooldown abilities, or enduring a somewhat long corpse run back from Valgarde (releasing from the catacombs doesn't seem to link to the graveyard outside the entrance to Utgarde Keep proper; I was sent back to Valgarde).

**Comment by Golganeth** [comment]
Confirmed, currently the buff disappears shortly after the Sacred Artifact is picked. It should last until quest is rewarded.

http://wotlk.openwow.com/spell=43202
http://wotlk.openwow.com/quest=11288

**Comment by Lothloryen** [comment]
Corrected, it is already on the PTR.

Thank you for the report.
