### ISSUE TITLE
[NPC] Morin Cloudstalker

### ISSUE THREAD

**Issue by Emaziz** [dalaranwow/dalaran-wow#3474]
**Description**:
Missing NPC patrol path

**Current behaviour**: 
Morin Cloudstalker is standing still at 57,61 in Mulgore

**Expected behaviour**:
Morin Cloudstalker is supposed to patrol the road between the crossroads next to Camp Mojache and the crossroads south of Ravaged Caravan

**NPC with path**: http://wotlk.openwow.com/npc=2988

**Comment by Rushor** [comment]
c8bb5b7585b052468df11137be42e26893d7904f
- pathing added
