### ISSUE TITLE
Barkskin

### ISSUE THREAD

**Issue by fixlol** [dalaranwow/dalaran-wow#3476]
**Description**:

**Current behaviour**: the spell Barkskin (druid) can not dispel be on this server, this is not correct it is a magical effect, even addons blizzard indicate that you can dispel it or spellsteal.

**Steps to reproduce the problem**:

1. when the druid Barkskin active is not possible to dispel it or spellsteal
2. 
3. 

**Include proofs for this behaviour**

http://wotlk.openwow.com/spell=22812

**Comment by Golganeth** [comment]
It can be dispelled and stolen with Spellsteal, works as intended.

Closed
