### ISSUE TITLE
Spell / Aura: Focused Assault [46392]

### ISSUE THREAD

**Issue by Golganeth** [dalaranwow/dalaran-wow#3478]
The spell effect should fade as soon as the player leaves Warsong Gulch. Currently it persists.

http://wotlk.openwow.com/spell=46392

**Comment by Rushor** [comment]
54aec37f5188ab136969474d9daf345180be871b
Game/Battlegrounds: WS - Remove BG_WS_SPELL_FOCUSED_ASSAULT + BG_WS_SPELL_BRUTAL_ASSAULT on RemovePlayer

* closes https://github.com/dalaranwow/dalaran-wow/issues/3478

this will only work if the player will be removed from the battleground

**Comment by Edzero** [comment]
This issue still persists on the live realm. Can somebody give it the proper milestone or label so it can be pushed to Algalon?
