### ISSUE TITLE
Vengence talent, Balance tree

### ISSUE THREAD

**Issue by rioux123** [dalaranwow/dalaran-wow#3479]
*Vengence talent seems broken.**:

The bonus damage dosnt seems to apply. I normaly do around 60-80 dmg with my moon fire, and i crit at around 140-150. It should be way more with vengence ( 100% bonus damage to crits) .

 It should be way more with vengence ( 100% bonus damage to critics).

Anyone noticed the same thing?

**Comment by Golganeth** [comment]
Works as intended. 

Closed
