### ISSUE TITLE
[Achievement] With Open Arms

### ISSUE THREAD

**Issue by DalaranLantri** [dalaranwow/dalaran-wow#3480]
**Description**:
With Open Arms is an achievement granted for killing Kologarn without killing any of Kologarn's arms.
**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
When you do not kill any arms, there is no credit given for the achievement upon killing Kologarn.
**Expected behaviour**: Tell us what should happen instead
Upon killing Kologarn without killing either Left Arm or Right Arm, the achievement With Open Arms should be granted to all the players in the raid.
**Steps to reproduce the problem**:

1. Don't kill Left Arm + Right Arm
2. Kill Kologarn
3. no achieve

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

Kologarn: 32930
Left Arm: 32933
Right Arm: 32934
Ulduar: 4273
With Open Arms 10: 2951
With Open Arms 25: 2952

**Comment by Crispybuilt** [comment]
Confirmed.

**Comment by RazerStylehunter** [comment]
Confirmed,  we ran it twice over the past two weeks and never got it.

**Comment by Lothloryen** [comment]
Hello there,

My apologies, since I did not get any report until now I thought this achievement was working already. Nonetheless, it shall be working after the next scheduled maintenance.

Thank you very much for the heads up.
