### ISSUE TITLE
QUEST Impossible to start - Fate, Up Against Your Will

### ISSUE THREAD

**Issue by killverme** [dalaranwow/dalaran-wow#3489]
**Description**: Important quest line for a great PVE content 

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
 Jaina Proodmore its not beside the King of stormwind, making it impossible to continuos the quest.
**Expected behaviour**: Tell us what should happen instead
After Accepting the quest, the player shoudl talk to Jaina Proodmore when ready to start the quest.
**Steps to reproduce the problem**:

1. 
2. 
3. 

**Include proofs for this behaviour**

You can research this on several pages like http://wowhead.com or http://wowwiki.wikia.com or http://www.youtube.com/
https://www.youtube.com/watch?v=yXnAZZC6OTU - in this video theres no soud of the conversastion.

http://wowwiki.wikia.com/wiki/Quest%3AFate%2C_Up_Against_Your_Will 
Descreption of quest in wowwiki.
**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

You can research this on several pages like http://wotlk.openwow.com or http://wowhead.com/

**Include Screenshots from the issue if necessary**

**Comment by Golganeth** [comment]
Related to #2404. The fixes are currently on PTR for further testing, applied to live realm soon.
