### ISSUE TITLE
[BUG, MOB, PET] Ghost saber don't spawn

### ISSUE THREAD

**Issue by Vern0m** [dalaranwow/dalaran-wow#3490]
**Description**: As hunter, i'm trying to have ghost saber as pet. First, I think they are less cat figurine as normal. I found only 3 in all the map.
I've done 3 sessions to try to see this mob. Last during 2hours, I had ~50 grey items cat figurine but never saw him...
In wowhead or petopia comments, people said got him in 8~15 figurines.

**Current behaviour**: In darkshore, when clicking on cat figurine, ghost saber never spawn.

**Expected behaviour**: Ghost saber should randomly spawn and attack player.

**Steps to reproduce the problem**:

1. Go to Ruins of Mathystra in darkshore ~(58.0; 20.0)
2. Click on cat figurine, got grey item cat figurine.
3. Click on cat figurine again.
4. Click on cat figurine again.
5. Again, again, again...

**Include proofs for this behaviour**

How it supposed to work : https://youtu.be/-fN7uw0wU74?t=202

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

Cat figurine container : http://wotlk.openwow.com/object=13359
Mob ghost saber : http://wotlk.openwow.com/npc=3619

Thanks.

**Comment by Rushor** [comment]
there are 2 types of cat figures
http://wotlk.openwow.com/object=13359
https://db.rising-gods.de/?object=13873

only https://db.rising-gods.de/?object=13873 is the one which will spawn you the Ghost saber for a specifix percent chance. so you must just search for http://wotlk.openwow.com/?object=13873 and it will spawn.

**Comment by ImprezaWoW** [comment]
Tried it today to make sure because of some tickets, yes [_it does drop_ ](http://i.imgur.com/7ABlyk8.png)
