### ISSUE TITLE
Mending Fences Quest:  Sons of Hodir questline

### ISSUE THREAD

**Issue by phillyfire** [dalaranwow/dalaran-wow#3491]
Mending Fences problem with charm

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
On the quest Mending Fences when I used the quest's included charm it generates helper dwarves to defeat the elite giant mobs and I have no problem.

Until I get to the boss mob at the end named Fjorn.  Then no matter how I try to target or use the charm on Fjorn the UI repeatedly tells me "invalid target" when I attempt to activate the charm with the boulder I obtain right next to where Fjorn spawns.

I tried  using different boulders and it did not help.

I tried varying the kill order, IE doing Fjorn first instead of the other five giants first.

I tried to dropping the quest and re-obtaining it and obtained no difference whatever.

I watched a video online where the guy has no problem using the charm on Fjorn and I personally completed this quest with no issue a few months back on my first toon.

**Expected behaviour**: Tell us what should happen instead
I don't know what I could do to just have the charm activate on the main boss, Fjorn, the way it should by generating the helper dwarves.

**Steps to reproduce the problem**:

1. Obtain the quest and the included charm. 
2. Obtain the necessary boulder.
3. Attempt to activate the charm on Fjorn.

**Include proofs for this behaviour**
I will edit this later with a screen print.
You can research this on several pages like http://wowhead.com or http://wowwiki.wikia.com or http://www.youtube.com/

I have watched videos and have completed this quest repeatedly in the past with no problems.

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

You can research this on several pages like http://wotlk.openwow.com or http://wowhead.com/

**Include Screenshots from the issue if necessary**

**Comment by Lothloryen** [comment]
Hello there,

Thank you very much for your report - it is really appreciated. The issue with Fjorn reappeared after one of the latest maintenances. However it has been fixed today and it shall be on the live server after the next realm restart.

Regards.

**Comment by phillyfire** [comment]
OMG ty so much.
