### ISSUE TITLE
[Ulduar] Assembly of Iron Issues

### ISSUE THREAD

**Issue by saltylopez** [dalaranwow/dalaran-wow#3493]
- Currently, if a player attempts to purge, dispel, or spellsteal Runemaster Molgeims Shield of Runes in the Assembly of Iron encounter, it will result in the runemaster immediately gaining the 50% damage buff.

The Spell itself: www.wowhead.com/spell=63489
The Buff: www.wowhead.com/spell=63967

Instead, a successful purge, dispel, or spellsteal should result in Runemaster Molgeim losing the shield and no subsequent buff should be applied.  In the case of spellsteal, the mage should receive the damage shield and can try to break the shield with damage to receive the 50% damage buff themselves.

I have tested this by spamming purge on him when he casts the spell.  My recount shows that I successfully dispelled an effect, but Runemaster still received the 50% damage buff every time.

Proof: http://wowwiki.wikia.com/wiki/Assembly_of_Iron
" Shield of Runes - Shield absorbs up to 50,000 heroic 20,000 normal damage. If the shield absorbs the total amount this gives Molgeim a 50% damage increase for 15 seconds. Should be purged, dispelled or spellstolen. "

https://youtu.be/vBPyfOnf18g (skip to 2:58)

- An additional bug is that Rune of Death's damage should be checked once again.  After the fix for #3231 was applied, it seemed to work for one week, then the next week it was back to doing 7k damage per tic.  It should do 3.5k damage every half second on 25 man and 2.75k damage per half second on 10 man.

These bugs basically make it mandatory to kill Molgeim first.

**Comment by LoveDalaranWow** [comment]
Most of the times I've been in Ulduar doing this boss, I noticed that the debuff could never be dispelled at all (I was trying myself do dispelling it every single time). Regardless of the buff, the runes still do a lot of damage and it's impossible to get out without dying unless you are a tank or you pop a defensive cd before they spawn, hoping to be the target.
I've never seen anyone in this server killing Steelbreaker first in about 1 year in this server...

**Comment by saltylopez** [comment]
The damage buff cannot be dispelled but the damage absorption buff can if you are quick enough (read spamming) to dispel after he casts shield of runes. I wouldn't have known the purges were successful without recount though.

**Comment by Zallera** [comment]
On the subject of the Assembly of Iron they have basically double the health pool they do in retail, It seems to have been brought up a year and a half ago: 
https://github.com/dalaranwow/dalaran-wow/issues/2967
but the health pools are still seem doubled.

**Comment by Lothloryen** [comment]
Hello there,

This should be solved after the next scheduled maintenance. 

Thank you for the reports.
