### ISSUE TITLE
[Hunter] [Spell] [Auto shot] Auto Shot getting canceled while casting offensive spells

### ISSUE THREAD

**Issue by RazerStylehunter** [dalaranwow/dalaran-wow#3495]
**Description**:
Hunters auto shot casting are getting stuck and canceled while we run our normal rotation. This should not happen since auto shot should be firing continuously during our offensive spell casting.

**Current behaviour**: 
While targeting any hostile target, after a few shots of Steady shot, Auto shot will stop and not fire. This happens even if all offensive spells are marcoed with /cast !Auto Shot , I have tested both with and without marcos. results are the same.  I first noticed it early this morning, previously this was not the case. 

**Expected behaviour**: 
Autoshot  should be casting continuously on the target regardless of any offensive spell casting such as steady shot, it should not be canceled.  Normally this is the highest dmg portion for MMhunters.

**Steps to reproduce the problem**:

1.  Target a dummy , run the normal chimera shot - aimed - Steady shot X 4 rotation
2.  About 3-4 casts in, auto shot will start to stop and then reappear every 8-9 seconds
3.  observe huge DPS lose

**Include proofs for this behaviour**
![13](https://cloud.githubusercontent.com/assets/13498374/16343678/1bdc91ec-39fe-11e6-8b05-fafa1718243d.png)
Above is a recount pic from a 3.5 min normal MMhunter  DPS rotation on a dummy. I was under Viper so ignore the actual dmg, but notice that  Auto shot only fired 19 times, while Chimera and Aimed thats on a 10 second CD fired 17 times.   No target switching was involved in the process. 

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**
http://wow.gamepedia.com/Steady_Shot
http://wow.gamepedia.com/Auto_Shot
Steady shot runs on a different timer than auto shot, casting steady should not be able to cancel it.
Auto shot will continuously fire with offensive spell casts.

**Comment by Coztume** [comment]
Can confirm, really needs to be addressed asap.

**Comment by robinsch** [comment]
@RazerStylehunter Did this appear after the last update? Because https://github.com/dalaranwow/dalaran-wow/issues/834 also describes the same problem.

**Comment by RazerStylehunter** [comment]
Yes, I assume it did. It was normal a few days ago, I noticed this cuz after the reset today my raid DPS dropped by like 30%  compared to previous runs last week.

**Comment by RazerStylehunter** [comment]
Just another side note,  after about an hour of hitting dummies, it seems to be a de-coupling issue with Auto-shot and all other hunter offensive spells in general, the timer of auto-shot is not 100% independent. 

During the rotation, sometimes the auto-shot stops at when the hunter fires Chimera or Aimed, but the chances of that happening is slightly less compared to steady shot, especially if one marco all instant casts with  /cast !auto shot.  If one adds arcane shot in the rotation, this auto-shot canceling happens too but less frequently.

**Comment by robinsch** [comment]
https://github.com/TrinityCore/TrinityCore/pull/14889
https://github.com/TrinityCore/TrinityCore/issues/15724

**Comment by Winstrol** [comment]
can only confirm what others have said, quite gamebreaking bug.

**Comment by xelvani** [comment]
if you cast any spell the same time with auto shot will stop
if you hide behind rock or tree for 1 sec and back will stop the auto shot again
if anyone CC you after that the auto shot will stop
sometime if you cast steadyshot  the auto will be canceled or delay

the only way to back auto shot again you have to untarget then target again

**Comment by robinsch** [comment]
@Winstrol @xelvani Did this happen before or just recently? I really don't know what should have break this.

**Comment by Coztume** [comment]
What xelvani describes is mothing new and is described in another issue. This started friday night approx.

**Comment by xelvani** [comment]
@robinsch will i start playing in this server for 2 weeks and start with me from lvl 1
and also the pet a bet crazy 2

**Comment by Lancespace** [comment]
It started happening more or less a week ago. Please fix it, this makes hunter class totally useless.

**Comment by robinsch** [comment]
@Lothloryen I can't confirm it. Can you please check it.

**Comment by kyhnau** [comment]
Is there an estimate on this problem yet?
This should have a high priority!
Have started to see hunters being replaced in raids for other classes now that they are nerfed with 1-2k dps due to this problem.

The problem came after your change to the LoS problem, but caused even bigger issues, LoS could be solved with a simple /cast !Auto attack macro implemented into the spells but this is just unbearable.

**Comment by Golganeth** [comment]
PTR:

- [ ] *if you cast any spell the same time with auto shot will stop*
- Not confirmed

----------------------

- [ ] *if you hide behind rock or tree for 1 sec and back will stop the auto shot again*
- Confirmed, /cast !auto shot solves it

------------------------

- [ ] *if anyone CC you after that the auto shot will stop*
- Confirmed, /cast !auto shot solves it, tested with .aura 66007

------------------------

- [ ] *sometime if you cast steadyshot the auto will be canceled or delay *
- Not confirmed

**Comment by xelvani** [comment]
@Golganeth @robinsch     *sometime if you cast steadyshot the auto will be canceled or delay *
i can record video for this if you want

**Comment by Lothloryen** [comment]
Hello there,

Already found what was causing this issue - for some weird reason, there was a commit lacking. The bug with no Auto Shots being cast while spamming Steady Shot or other spells will be corrected with the next scheduled maintenance.

**Comment by Golganeth** [comment]
@xelvani sure thing, we have detected the issue so it should be solved after the next scheduled maintenace (as @Lothloryen just mentioned) probably later tonight.

Any feedback, footage once the correction is applied will be very appreciated.

**Comment by tyler200100** [comment]
There is an issue that may be related to this involving switching targets and your autoshot no longer working. The steps to reproduce are as follows. Target a npc or dummy and begin autoshoting. Cast steady shot and then switch to another enemy target. You will not start auto attacking this target. If you start shooting abilities at it you still will not auto attack but your Auto shot ability will flicker red as if it was working. The only way to fix this I have found is clearing your target and re-targeting it.  Furthermore following the same procedure but this time using this macro for steady shot in attempt to fix the issue.

#showtooltip Steady Shot
/cast !Auto Shot
/cast Steady Shot

This caused my steady shot to shoot at the dummy I was targeting but my auto attacks kept shooting at the previous target. This was harder to reproduce then the first issue but still occurred every once in a while. I'm not exactly certain what caused it to happen.

**Comment by Coztume** [comment]
@tyler200100 The issue described in this report was something that happened after a server restart and was fixed a couple of days later. In other words, you're better off reporting it elsewhere.
