### ISSUE TITLE
[Ulduar] - Ignis - Iron Construct Threat

### ISSUE THREAD

**Issue by ashido96** [dalaranwow/dalaran-wow#3496]
When iron construct reaches 15 stacks of their heat debuff and gain "molten" debuff their agro table resets.

http://www.wowhead.com/npc=33121/iron-construct
http://www.wowhead.com/spell=65667/heat
http://www.wowhead.com/spell=62373/molten
http://www.wowhead.com/spell=62382/brittle

**Comment by Lothloryen** [comment]
Hello there,

This is intended.

http://wowwiki.wikia.com/wiki/Ignis_the_Furnace_Master

http://www.tentonhammer.com/guides/ulduar-ignis-strategy

Thank you.

**Comment by peszmerd** [comment]
15 stacks instead of 10 are intended, or are You talking about the aggro reset part? Since the link you have provided clearly state 10 stacks to became molten.

**Comment by peszmerd** [comment]
@Lothloryen
