### ISSUE TITLE
[Quest][Midsummer Fire Festival] Torch Catching (More Torch Catching)

### ISSUE THREAD

**Issue by Stihii** [dalaranwow/dalaran-wow#3497]
**Description**: Both the Torch Catching and More Torch Catching can be completed without doing anything:

**Current behaviour**: This happened in Rut'theran Village (but it probably happens everywhere). I finished the Torch Tossing quest (which worked fine) and then I accepted the Torch Catching quest. I did not receive [Unlit Torches] and I was able to complete the quest without doing anything. I then accepted it again and completed it the same as before (this one might be the More Torch Catching quest). Both times I received the gold, exp and rewards.

**Expected behaviour**: More details about both quests: http://wowwiki.wikia.com/wiki/Quest:Torch_Catching_(Alliance)

**Comment by Rushor** [comment]
This works fine on PTR. If i accept the quest, the item will be provided and the quest is NOT on autocomplete

http://wotlk.openwow.com/?search=Torch+Catching#quests

![GitHub Logo](http://i.imgur.com/sbRL193.jpg)
