### ISSUE TITLE
[Quest] Fringe Science Benefits + Amped For Revolt - More Issues

### ISSUE THREAD

**Issue by Mazz312** [dalaranwow/dalaran-wow#3500]
This quest tree, which was implemented semi-recently, is completely broken and actually causing additional problems in Icecrown that weren't there previously.

I know there is an open issue for this already but this needs to be bumped hard, because some of the mobs involved are causing pretty major problems for the zone as a whole. Particularly the way the flying mobs work right now.

This is a list of issues with this quest tree, in no particular order:

1. The player is not receiving the infra-green phase when entering the bomber (nor is the phase buff used at all), which is likely the source of the phasing problems detailed in the comments below.
[The vision spell = 59651]

2. The bomber doesn't have the shield at all, as it does in retail, instead just converting any damage taken into the fires, and periodically just killing the bomber if you get behind on said fires. With no shield, you must be in AA mode to deal with the mass of Gargoyles that spawn or you will burn out and fall to your death, which means you have to resurrect under the ridiculous gargoyles who will likely kill you again. 
[The shield is spell = 59288]

3. The Gargoyle Ambushers have a massive aggro radius, which includes an unlimited z-axis. This means if you are near the ground, like after ressing when your fighter is shot down, you will immediately pull aggro and get bolted for 9000 by their spell (in leather). They cast with a 1.5s cast time. 

4. The phasing of the mobs/gargoyles seems to be broken, which means these gargoyles exist at all times for every character in the area, regardless of if you're on the quest or not. This means a large part of the middle of icecrown is quite nearly unpassable. I think this is tied to the lack of the infra-green phase toggle.

5. There are not enough Enraged Fleshstalkers spawning and/or the skeletons are not tagged as bombardment infantry. There is zero possibility you can actually get all 40/50 mobs killed in one pass currently, exasperating the above gargoyle issues. 

6. The scourge war machines used in Amped for Revolt! are also not phased, which means they attack players in Valley of Lost Hope, where many earlier Icecrown quests are located. 

7. The Frostbrood Sentries have all the same aggro radius problems as the Gargoyles, but with even more fun attached. While targeted and attacked by ability #2 in the bomber's AA mode, they take zero damage from it. This makes Amped for Revolt! and the follow up daily impossible to finish currently. 

8. Finishing Fringe Science Benefits unlocks the Amped for Revolt! daily as well as its own, which I think is incorrect.

9. When finishing the quest (if you don't get shot down), the plane will dump you near the front of the gate with no parachute, resulting in either your death or very low health and potential aggro from any of the mobs in that area.

IDs:
Quests
Fringe Science Benefits = 13373
-> Riding the Wavelength: The Bombardment = 13406
Amped for Revolt! = 13374
-> Total Ohmage: The Valley of Lost Hope! = 13376

Important Mobs
Gargoyle Ambusher = 32769 or 32188 (could be part of the issue with phasing)
Frostbrood Sentry = 31721
Scourge War Machine = 32154

**Comment by Golganeth** [comment]
Please leave feedback on #759, there's a report already opened. Just copy paste in a comment, in order to have all the info in one place, makes Devs life easier. Thanks in advance!
