### ISSUE TITLE
[Vehicle] Kor'Kron War Riders can damage players

### ISSUE THREAD

**Issue by cybergeek94** [dalaranwow/dalaran-wow#3501]
I was killing Anub'Ar cultists in the Icemist Village area of Dragonblight when I suddenly died for no apparent reason. I look up and a level 79 undead priest is flying away on a Kor'Kron War Rider. I look at my combat log and see that it was the War Rider's Big Blue ability that killed me in a single hit. You can see my combat log in the following screenshot: 

![](http://i.imgur.com/VHW6Uvm.jpg)

According to [the description of this ability](http://www.wowhead.com/spell=47434/big-blue) (and the vehicle's purpose in the quest), it should only be able to damage [Anub'ar Blightbeasts](http://www.wowhead.com/npc=26607/anubar-blightbeast).

Given the ease with which this ability could be abused in world PVP, I hope a fix is implemented quickly.

**Comment by Lothloryen** [comment]
Hello there,

Thank you for the report, it is really appreciated. The fix for this issue shall be deployed with the next server restart.

Regards.
