### ISSUE TITLE
The Keepers of Ulduar (25 player) - Freya's kill didn't count

### ISSUE THREAD

**Issue by Craftymind** [dalaranwow/dalaran-wow#3502]
**Description**: I Killed freya in Ulduar (25) but the kill didn't count into " The Keepers of Ulduar (25 player) " achievement. Even in statistics the kill didn't appear. I killed Thorim, Hodir and Mimiron in the same raid, but they did count normally into the achievement.

**Current behaviour**: I was doing Ulduar (25) today (26/06/2016) with my guild " Team Dai Gurren " and some pick-ups, from 00:30 am till 6:30 am server time. We killed every boss until Yogg saron (which we didn't kill). I did get the proper achievements and the kills counted... all of them, except one: Freya !
We killed her exactly at 3:09 am server time (as shown later on the screenshot of skada). All 24 players with me got the kill counted, except me, maybe because I died at the very end of the fight (around 6% left) the bug happened. Some people in the raid confirmed that this bug happened to them too (not getting the kill counted when you finish the fight dead on freya). Many people died during the fight and got resurrected, finished the fight alive, got the kill counted. I only died once during the fight (around 6%) but finished the fight dead. I realized that the kill was not counted few minutes later when I checked the Keepers achievement, but when I run back to screen shot Freya's corpse, it was already gone. However, I have some screens shots that prove that I was in that fight (like Skada dps meter and the loot that I did get from that kill, and only can get from Freya). The raid members can testify for me as well.

**Expected behaviour**: Well, what should happen instead is obvious. I should get the kill counted regardless of being alive or not after the fight finishes.

**Steps to reproduce the problem**:

1. Engage Freya at Ulduar (25 player)
2. Die near the end (around 10% or less of her HP)
3. stay dead till Freya is dead (no resurrection)
4. See if you get the kill counted or not

**Include proofs for this behaviour**
Me checking The keepers of Ulduar (25 player) achievement after Freya's death: as you can see, she didn't count.
![wowscrnshot_062616_031849](https://cloud.githubusercontent.com/assets/19840534/16360839/f40809a4-3b6e-11e6-8caa-fc48865502b9.jpg)

The " Legplates of the Wayward Vanquisher " that I earned from killing Freya:
![wowscrnshot_062616_032836](https://cloud.githubusercontent.com/assets/19840534/16360845/7034a05a-3b6f-11e6-8b96-c61216b25088.jpg)

The exact time of death of freya as shown by my skada addon:
![wowscrnshot_062616_033524](https://cloud.githubusercontent.com/assets/19840534/16360867/90ee7766-3b70-11e6-9093-1597f312da2a.jpg)

The Keepers achievement after I finished the raid for today:
![wowscrnshot_062616_073924](https://cloud.githubusercontent.com/assets/19840534/16360874/2d3d932c-3b71-11e6-931b-d1d82393de51.jpg)

The statistics of Ulduar (25 player) also shows that the kill didn't count. However it shows that I killed Hodir 2 times which is false because this raid was my 1st time in Ulduar EVER on this server. So I presume that Freya's kill got bugged and got counted as a Hodir kill instead, maybe ?!:
![wowscrnshot_062616_074153](https://cloud.githubusercontent.com/assets/19840534/16360885/843eb7a0-3b71-11e6-9227-be005017d71f.jpg)

**Comment by Golganeth** [comment]
Already reported. #3093
