### ISSUE TITLE
Npcs moving while casting spells

### ISSUE THREAD

**Issue by drewqt** [dalaranwow/dalaran-wow#3503]
1. Familiars in the valley of trials and guarenteed around the world
2. they should obviously stand still while casting
3. ......
as a new player this gives me a feeling that the server isn't all that well put together if this is the first bug I've come across. love the server tbh fam but this put a frown on my face.

**Comment by ImprezaWoW** [comment]
[#2473](https://github.com/dalaranwow/dalaran-wow/issues/2473)
