### ISSUE TITLE
Shadow Word  Pain

### ISSUE THREAD

**Issue by NeptuNeJaV** [dalaranwow/dalaran-wow#3504]
**Description**:
just levelling a priest. put 2 points to Shadow word pain . the damage still remains at 10 ( same as before putting talent points into it)
**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
Same damage remains as before putting talent points into it
**Expected behaviour**: Tell us what should happen instead
i expect the talent to really improve the damage by 6%
**Steps to reproduce the problem**:

1. fix it?
2. fix.
3. fix!

**Include proofs for this behaviour**

You can research this on several pages like http://wowhead.com or http://wowwiki.wikia.com or http://www.youtube.com/

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

You can research this on several pages like http://wotlk.openwow.com or http://wowhead.com/

**Include Screenshots from the issue if necessary**
![wowscrnshot_062616_151014](https://cloud.githubusercontent.com/assets/5540450/16360971/2ad3637a-3bb0-11e6-99af-c7a966e1fa1c.jpg)

**Comment by DalaranLantri** [comment]
Tested, works fine. Keep in mind that with small numbers, percentages are really small aswell.

**Comment by NeptuNeJaV** [comment]
oops my bad.  I'm sorry!  apologize for the inconvenience
