### ISSUE TITLE
[Achievement]Torch Juggler Granted Everywhere

### ISSUE THREAD

**Issue by Stihii** [dalaranwow/dalaran-wow#3505]
**Description**: I was able to receive Torch Juggler achievement despite not being in Dalaran.

**Current behaviour**: I had 5 torches in my inventory; I hotkeyed them to a key and then started spamming them while being in Exodar (if I recall correctly; but for sure I was not in Dalaran, my character did not even get to Dalaran yet). Did that for a minute or so and I got the achievement. Character that I got this achievement on is Nalhar on server Algalon.

**Expected behaviour**: The achievement should be received only if done in Dalaran as it is said here: http://wowwiki.wikia.com/wiki/Torch_Juggler . Not sure about the mechanics if they work correctly seeing how easily I did the achievement and what a long article the wiki has about it :)

**Comment by Rushor** [comment]
69a8d2a58d157a51909007fbd85f8939760d27a0
- now only diable in dalaran
- on ptr

**Comment by Rushor** [comment]
I tested this. I was not able to use the Juggling Torches, there is no visual effect when using them. I did all the quests, added all of the achievements and still nothing. So basically the Achievement isn't bugged, but the item itself is. It used to work though. I'm going to put this for someone else to test and make sure 100%.

**Comment by Rushor** [comment]
the ach. is not working on PTR because the spell is not scripted. But the restriction for the Achievement works fine. Loth needs to apply the fix directly on the live realm :)
