### ISSUE TITLE
[Quest] Chicken Party! 

### ISSUE THREAD

**Issue by axenon** [dalaranwow/dalaran-wow#3506]
**Description**: 

Chicken Party! quest can not be completed.

**Current behaviour**: 

The Frenzyheart Tribe daily quest Chicken Party! (http://www.wowhead.com/quest=12702/chicken-party) can not be completed due to few problems. The item provided (http://www.wowhead.com/item=38689/chicken-net) does not work properly, it doesn't wrap the escaping chickens when thrown. Sometimes when chicken starts to run away from the radius of thrown area, we can see "Evade" text. Also chickens are unclickable despite of the loot icon when pointed. In addition this quest was working about one week ago, it didn't require to throw net, we could just simply pick up chickens from the ground.

**Expected behaviour**: 

Chickens should be wrapped with net when the quest item (http://www.wowhead.com/item=38689/chicken-net) is used on them and in this time we could be able to pick a chick up, to get Captured Chicken (http://www.wowhead.com/item=38483/captured-chicken) in bag and get a credit.

**Comment by Rushor** [comment]
issue will be fixed in https://github.com/dalaranwow/dalaran-wow/issues/3466

closing cuz duplicate
