### ISSUE TITLE
Risen Ally!/Raise Ally spell

### ISSUE THREAD

**Issue by Darthblaider** [dalaranwow/dalaran-wow#3510]
The new patch that included fixing Raise Ally for DK's is fabulous but it still has some "minor" issues.

When somebody dies and you resurrect them it doesn't always give them the prompt to accept it, or it does and disappears after a very short moment. 
When resurrecting somebody as a ghoul, there's about 2-3ish seconds where they cannot move or do anything before they truly activate as the character. 
In the occasion that a character is properly resurrected while acting as a ghoul and they accept it, they become locked in place and can do nothing other than explode the ghoul in which case the rez doesn't actually work and they still have to wait out the 5minute timer on the ghoul.

Further investigation is require but for now I'm too busy turning my friends into ghouls.

**Comment by Golganeth** [comment]
#848
