### ISSUE TITLE
[Quest]The Storm King's Vengeance

### ISSUE THREAD

**Issue by tzupax** [dalaranwow/dalaran-wow#3511]
**Description**:So Gymer wants me to hop on his back and destroy 100 Scourge and kill Algar the Chosen, Thrym and Prince Navarius.  
http://www.wowhead.com/quest=12919/the-storm-kings-vengeance
 
**Current behaviour**: After i kill the 100 scourge the giant will bug out and won't use any skills to kill the elites for the quest and also won't let you dismount off him. 

I did the quest again after some time and first i killed the elites and after that the scourge and it didn't bug out and have completed the quest.

**Expected behaviour**:Even after you killed the 100 scourge you could've still kill the elites.
 
**Steps to reproduce the problem**:

1.Talk to the giant and hop on his head.
2. Kill only the 100 scourge.
3. Try use any abilities after that and also try to dismount.

**Comment by jonanone** [comment]
The abilities seems to be working okay. The problem seems to be related to the aura that makes the player control Gymer. The overall behaviour has been improved to avoid this issues. This update will be apply to the live realm soon.
