### ISSUE TITLE
Charge and Intercept being interrupted

### ISSUE THREAD

**Issue by doppin** [dalaranwow/dalaran-wow#3513]
Hi!

I really think it is not normal that both warrior charge and intercept can be interrupted by stuns, seductions, sheeps, etc. Meaning: you get stunned while pressing charge it will cast the spell, add the cooldown but will keep ypu in place. Same with intercept.

You should be stunned on your charged target not your starting position. Use both spells in 2 seconds, get both interrupted, then stand in your starting place and be useless for the next charge. Is it really the way it should work? Doubt.

Please take care of this.

**Comment by Rushor** [comment]
maybe related to recent charge + interept changes

**Comment by doppin** [comment]
No, it was like this before too
2016. jún. 27. 19:28 ezt írta ("Rushor" <notifications@github.com>):

**Comment by doppin** [comment]
I would also like to add, since the rework Charging underground is very frequent, rarely happened before, pathing was better. Really, i charged underground in the last 2-3 weeks already more than for 1 year before, not exxagerating. Something seriously wrong here.

**Comment by doppin** [comment]
Update:
CHarged underground already more in two weeks than i did in 2 years before that. What the hell is going on?

**Comment by Golganeth** [comment]
The pathfinding issue might be related to #3424 fix, since it now places the warrior closer to the target in general.

**Comment by doppin** [comment]
More concerned about them being interrupted anyways, going underground is a well know private server issue but these two spell being interruptable is not tolerable.

**Comment by doppin** [comment]
Please return the old version, its so fucking unplayable now....

**Comment by robinsch** [comment]
@Rushor

**Comment by robinsch** [comment]
On PTR.

**Comment by robinsch** [comment]
Tested on PTR. Fix confirmed.

**Comment by robinsch** [comment]
Can someone confirm this is fixed on live.
