### ISSUE TITLE
Halaa bombing

### ISSUE THREAD

**Issue by pizzamonkey** [dalaranwow/dalaran-wow#3515]
**Description**:
Nothing happens when you try to repair the Wyvern posts.

**Current behaviour**: 
When you right click on either the bomb wagon or the Wyvern post it does nothing. 

**Expected behaviour**: 
Normally you repair some wyvern/griffin posts, then you fly around and bomb Halaa.

**Steps to reproduce the problem**:
1. Go to Halaa.
2. Go to the bombing post
3. Right click on it
4. Observe that nothing happens

**Include proofs for this behaviour**
Sorry, but I don't have the capability to do this :(
Although I assume this just h

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**
The zone is Nagrand, in the pvp area. Halaa.

**Comment by Rushor** [comment]
https://github.com/dalaranwow/dalaran-wow/issues/3346
