### ISSUE TITLE
DK's on your Kirin Tor

### ISSUE THREAD

**Issue by pizzamonkey** [dalaranwow/dalaran-wow#3516]
**Description**:
I know this is really specific and won't effect anybody else, but I was playing with a friend, but we didn't have any characters the same level. So we decided to make death knights. But you can only make one DK per realm, so we decided "eh, to hell with it. Let's just play on the low-pop realm for a bit, we won't interact with people anyway" We tried it and in both cases it said "You need to have reached level 55 in at least one realm in order to make a Death Knight". Even though we both had characters above 55 in Algalon. 

**Steps to reproduce the problem**:

1. Try to make a DK on Kirin Tor

**Comment by Golganeth** [comment]
Kirin Tor and Algalon are currently separated realms and we don't plan to sync them in the near future.
One is progressive, the other has all content released. Currently you need to have a Level 55 in the realm where you want to create a Death Knight.

Closed.
