### ISSUE TITLE
Mirror Image Threat Issue.

### ISSUE THREAD

**Issue by Nendii** [dalaranwow/dalaran-wow#3520]
Mirror Image currently not working as it should regarding the threat.

-55342 
Creates copies of the caster nearby, which cast spells and attack the mage's enemies. Lasts 30 sec.

When using the spell as it is now, my threat against current target is going up and down, and if I do certain spells I pretty much overaggro instantly, making the spell pretty much useless for raiding enviorment. I cant see the reason why it does what it do, but it needs to be fixed. 
I would appricaite if you could take a look into this to find a better understanding of whats going on...

-Nendi

**Comment by RazerStylehunter** [comment]
Here's some of my experience with this: Mirror image does not alter your threat, once popped it kinda "hides" your aggro in the threat table (assuming it was not targeting you in the first place) ,  once mirror image is over, I assume it restores all of the aggro generated (by both your and the images) during the process of the duration, which if during the duration you generated a lot of threat (by using CDs and pots and whatnot), the mob will target you. 

now if the mob was already targeting you and you pop mirror image, i would guess it would have a 1/4 chance you target you after mirror image was popped, if not, and you overaggro your own image, then its gonna be a dog fight for threat between you and your images. 

I assume its working as intended, although I personally do not have a lot of first hand experiences with mages, this is just some feedback and observation from guildies/raids/pugs/etc.

**Comment by LoveDalaranWow** [comment]
Sometimes when MI ends, the mage using it gets some insane amounts of threat (omen says something about 40 millions instant threat) and eventually ythe mage overaggroes, even if his threat is fine for all the rest of the fight.

**Comment by Golganeth** [comment]
Merge with #998
