### ISSUE TITLE
[Ulduar] Freya Seeds Weird/No visual

### ISSUE THREAD

**Issue by ashido96** [dalaranwow/dalaran-wow#3521]
Seeds during phase 2 of the freya fight could only be identified by the green glow and lacked the "seed" part of the visual.

This was specifically on hard mode with all 3 keepers up.

i think this is the 10 man version of the spell, wasn't able to find the "object" for the seed.
http://www.wowhead.com/spell=64587/nature-bomb

**Comment by Lothloryen** [comment]
Hello there,

Thank you for your report  - I have checked in both 10 and 25 players mode and they have the proper models and effects.

[https://gyazo.com/c236c6b79c786080c8fc6ff171b623ce](url)

Regards.

**Comment by ashido96** [comment]
Went and did freya again last night on 25 man, seeds all have the correct visual but there no longer seems to be animation for freya "throwing" the seeds. They just instantly appear on the ground instead right now.
Shown at: https://youtu.be/mc2ZOf3CkKA?t=6m14s
