### ISSUE TITLE
[Trials of the Crusader] Northrend Beasts - Heroic mechanics in Normal Mode

### ISSUE THREAD

**Issue by saltylopez** [dalaranwow/dalaran-wow#3522]
There are two issues related to timing in the Northrend Beasts encounter in Trials of the Crusader.  I noticed them in the 25 man encounter, but they may also be present in the 10 man version.

- This server seems to have them set to a 9 or 10 minute enrage/berserk when it should be 15 minutes.  Per the wowwiki entry on Beasts of Northrend: "Berserker Enrage Each of the beasts enrages 15 minutes after it entered the arena, increasing all damage done by 500%, and becoming immune to taunt."

http://wowwiki.wikia.com/wiki/Beasts_of_Northrend

The wowhead entry for Icehowl also confirms a 15 minute berserk on the side panel:
http://www.wowhead.com/npc=34797/icehowl#comments

According to this video, it looks like the 9 minute berserk is a heroic mode mechanic:
https://www.youtube.com/watch?v=E1SR_XoFPm8

- In normal mode, different phases of the fight are able to begin before the previous phase's bosses have been killed.  This was most apparent when Icehowl would emerge before both worms were dead.  This is a mechanic that should only exist in the heroic version of the encounter.  Per the wowwiki entry:

"Strategy: Heroic mode

Like normal mode, this is a three-phase encounter. However, the three phases are now on a timer and do not wait for the raid to kill the previous phase's boss. These timers are quite tightly tuned (2-3 min each). This makes the fight a major DPS race and you may have bosses overlap for a short time."

The 10 and 25 man normal versions of this encounter should only transition to new phases of the encounter after the previous phase's bosses have been killed.

Thank you for your time and dedication to improving the server.

**Comment by Lothloryen** [comment]
Hello Saltylopez,

Thank you very much for this report, it is really appreciated.

The enrage timer is intended, in order to emulate the pre-nerf status of the raid. 

However, regarding the entrance of the next boss - you are right, it must be only on heroic. In fact, I thought I implemented this system only for heroic until now; I have just taken a look to the code and it is not so, I will work on it.

Again, thank you.

**Comment by saltylopez** [comment]
Doesn't increasing the hp already emulate the pre-nerf status without having to change the berserk timer though?

**Comment by Lothloryen** [comment]
Every known pre-nerf mechanic is implemented in the WoTLK raids. 

It has nothing to do with the Hit Points buff that the bosses have, which was applied thanks to the community decision a long time ago in order make it more challenging due the current patch's talents.

The issue with the next boss entrance being also executed in normal mode has been already corrected, it shall be deployed to Algalon with the next scheduled maintenance.

Thank you.

**Comment by saltylopez** [comment]
Ah, I just saw the patch changes at the bottom of the wowwiki.  Thanks for your time Loth.
