### ISSUE TITLE
[Item] Atiesh, Greatstaff of the Guardian

### ISSUE THREAD

**Issue by PSAlias** [dalaranwow/dalaran-wow#3525]
**Description**: The legendary item Atiesh has a couple minor bugs associated with it. The aura is sometimes misapplied and the portal is not functioning correctly.

**Current behaviour**: Atiesh, Greatstaff of the Guardian has a use effect that creates a Portal to Karazhan. However, this portal does not teleport the user when interacted with while not in a raid, as it connects to a point inside Karazhan. The item also has an equip aura that buffs the wielder and group members within a certain radius. When the wielder dies, the aura is continually (attempted to be) re-applied, causing the error message "You are dead" to appear for the wielder every few seconds until they are revived. The aura does not automatically re-apply itself to the revived character.

**Expected behaviour**: The Portal to Karazhan should be usable by the wielder and his group members, and should teleport them to a spot just outside Karazhan in Deadwind Pass (see video under proof). The aura should not be re-applied to a dead wielder until after they revive.

**Steps to reproduce the problem**:
1. Equip Atiesh, Greatstaff of the Guardian while not in a raid
2. Use Atiesh, Greatstaff of the Guardian and attempt to use the created portal
3. Die while still having the item equipped, wait several seconds to see the "You are dead" message, then resurrect and note the missing aura

**Include proofs for this behaviour**
http://www.wowhead.com/item=22631/atiesh-greatstaff-of-the-guardian#comments
https://www.youtube.com/watch?v=dQkpFKkC4nE

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

Object:
Portal to Karazhan: 181146

Spells:
Power of the Guardian: 28142, 28143, **28144**, 28145

Items:
Atiesh, Greatstaff of the Guardian: 22589, 22630, **22631**, 22632

Zone:
Deadwind Pass: 41
Karazhan: 3457

**Note that all bugs were observed using a Horde priest character. Some alternate versions may not reflect this behavior. IDs for the tested versions have been put in bold.**

**Comment by Darthblaider** [comment]
I've definitely used the portal to troll people at the end of raids on my mage. Definitely works. Caster just can't go through first, as with any other portal.

**Comment by PSAlias** [comment]
Interesting... As you can see in the video, you're supposed to be able to walk through alone, though.

**Comment by Darthblaider** [comment]
The only real difference is that in retail it teleported you outside the dungeon and on dalaran it teleports you right inside instead. So you have to be in a raid group to enter the dungeon, and if you're teleporting other players you have to wait for them to go in first

**Comment by Darthblaider** [comment]
Also, the video is from cataclysm, which dalaran isnt.

**Comment by PSAlias** [comment]
Actually, it's from MoP, but I can't see any record of it ever being changed.

**Comment by Rushor** [comment]
> The only real difference is that in retail it teleported you outside the dungeon 

will fix this

**Comment by Rushor** [comment]
DB/Item: Atiesh, Greatstaff of the Guardian - Teleport player in front of Karazhan

* closes https://github.com/dalaranwow/dalaran-wow/issues/3525
* commit: 6c345ed83e2b1f7b982ce917fcd958775cff61a4

![GitHub Logo](http://i.imgur.com/RTJilzR.jpg)

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
