### ISSUE TITLE
Swift Raptors are cars

### ISSUE THREAD

**Issue by davideCremona** [dalaranwow/dalaran-wow#3526]
**Description**: Mounts viewed as cars

**Current behaviour**: Today (30/06/2016) I have just bought all the three 100% mounts and they are not Raptors (as my 60% mount) but they are viewed as yellow cars.

**Expected behaviour**: The mounts should be rendered as Raptors instead of cars

**Include proofs for this behaviour**

Screenshot: http://imgur.com/VPWA1Rb

My pg name: Automag

**Comment by Golganeth** [comment]
Oh boy, that's some nice car mount right there! (I gotta admit that was genuinely hilarious).

Sadly there's not much we can do since it's a client-side issue (modified files/models). Get a normal WotLK client and it should be fine.

Closed.

**Comment by ImprezaWoW** [comment]
LOL

**Comment by davideCremona** [comment]
It was the client =)

**Comment by Rushor** [comment]
gz :D
