### ISSUE TITLE
Rogue Vanish and Mob Aggros

### ISSUE THREAD

**Issue by Ryladen** [dalaranwow/dalaran-wow#3527]
I am not clearly sure what causes the problem but especially after the new fix, vanish does not make mobs leave you. They keep attacking after vanishing and break your stealth.
**Current behaviour**: I experienced this bug several times in Dragonblight zone, server time 2:50am - 30.06.2016

**Expected behaviour**: Vanish should cut out all the combat and make the mob leave you.

**Steps to reproduce the problem**:

1. Simply attack a mob
2. I am not certainly sure but use some poisons on it
3. Vanish and see that it doesn't leave you

**Comment by Ryladen** [comment]
I'm %100 sure now that vanish does not stop the combat if you have attacked a mob. Moreover, the mob starts to follow and attack you till the end of the world, or until it dies. I am starting to think that it is a problem about mobs ending the combat.

**Comment by robinsch** [comment]
On PTR.
