### ISSUE TITLE
[Ulduar] Yogg'saron One Light in the Darkness Achievment

### ISSUE THREAD

**Issue by ashido96** [dalaranwow/dalaran-wow#3528]
If you wipe on a one light run and then successfully clear one light on a second (or later) attempt you do not get the "One Light in the Darkness" achievement.
http://www.wowhead.com/achievement=3158/one-light-in-the-darkness-10-player

For future reference, there's a couple things I'm coming across that had 'fixes' applied in the past that are no longer working. Will it be seen if comments are made on closed issues?

#2732

**Comment by Lothloryen** [comment]
Hello there,

Thank you for the report - yes, it shall be seen if you comment there. I will take a look.
