### ISSUE TITLE
[Quest] Escort Quest, "A Fine Mess"

### ISSUE THREAD

**Issue by deljgu** [dalaranwow/dalaran-wow#353]
In Gnomeregan, there is an unconscious goblin named Kernobee, somewhere in dormitory area. He offers an escort quest, "A Fine Mess", that should make him make a run for his life, alongside players. He, however, never starts moving, thus breaking the quest.

**Comment by Demlock** [comment]
Confirmed

**Comment by Sagrath** [comment]
Kernobee is supposed to get up, and players are supposed to escort him to Clockwerk Run (the entrance of the instance). He should follow you. If you're in a group, he should follow the person who initiated the quest. Everyone should still be able to accept the quest. There is one ambush for him at the front entrance.

**Comment by Rushor** [comment]
c158f129fa8433e033f3122621868809cfa0e572
- little Kernobee will now the player
- little Kernobee gives questcredit once it reaches point -332.2f, -2.8f, -152.8f near the entrance and despawn and give questcredit to the whole group

**Comment by Golganeth** [comment]
- Kernobee doesn't say any quote at all, not once quest is picked nor when quest is completed. I couldn't find any relevant info about this so probably intended, looks weird but a proof is needed to back this up.
- Kernobee doesn't aggro enemies at all. According to wowhead comments it should (only if you fight them) Proof needed

> Apparently Kernobee only aggros other enemies if you fight them. Very easy for a rogue or druid to stealth by everyone. There is 1 ambush near the front entrance though.
http://www.wowhead.com/quest=2904/a-fine-mess#comments

**Comment by Zibathy** [comment]
Doesn't move at all on Kirin Tor.
![wowscrnshot_011617_141424](https://cloud.githubusercontent.com/assets/7729864/21997687/2c569988-dbf6-11e6-80fa-6884b01f316b.jpg)

**Comment by Rushor** [comment]
1.) yes it's intended that he has no texts
2.) not shure i cannot find any infos about this quest. please push the fix like it is currently on live. it's a huge improvement. ty.

**Comment by TeridanDW** [comment]
Regarding:

> 2.) not sure i cannot find any infos about this quest. please push the fix like it is currently on live. it's a huge improvement. ty.

Thats intended behaviour for him, proof:
https://www.youtube.com/watch?v=Bv0WKTNodJI

Everything works as intended on ptr.

**Comment by Spambanjo** [comment]
Still a problem on Kirin Tor
