### ISSUE TITLE
Reign of the Unliving / Reign of the Dead missing cooldown

### ISSUE THREAD

**Issue by hAkonf** [dalaranwow/dalaran-wow#3530]
**Description**: 
This trinket is currently a lot stronger than it should be, because of it missing the cooldown of 2 seconds.

**Current behaviour**: There is no cooldown for gaining a Mote of Flame/Shard of Flame stack.

**Expected behaviour**: There should be a 2 second cooldown for gaining a Mote of Flame/Shard of Flame stack (even says so in the tooltip).

**Steps to reproduce the problem** (on a mage):

1. Cast Frostfire Bolts until you get a hot streak
2. Cast another Frostfire Bolt, and then cast a Pyroblast straight after
3. Repeat until you crit both, and observe your Mote of Flame/Shard of Flame stacks go up by 2 instead of 1.

![euu2nzm](https://cloud.githubusercontent.com/assets/183054/16495408/929f35fc-3eed-11e6-9793-81ff2ef298b3.png)

2 Stacks gained, whereas only one should be possible every 2 seconds.

**Additional information**:

http://wotlk.openwow.com/item=47182 alliance
http://wotlk.openwow.com/item=47188 alliance hc
http://wotlk.openwow.com/item=47316 horde
http://wotlk.openwow.com/item=47477 horde hc

http://wotlk.openwow.com/spell=67713 Mote of Flame (aura from normal)
http://wotlk.openwow.com/spell=67759 Shard of Flame (aura from hc)

http://wotlk.openwow.com/spell=67714 Pillar of Flame (proc from normal)
http://wotlk.openwow.com/spell=67760 Pillar of Flame (proc from hc)

**Comment by robinsch** [comment]
On PTR.
