### ISSUE TITLE
[ToC] Anub'arak - scarbs respawn as neutral version on death

### ISSUE THREAD

**Issue by ashido96** [dalaranwow/dalaran-wow#3532]
The scarabs that spawn during anub'arak work fine.
Though when they die they will instantly repsawn as a neutral/yellow version that wont move or attack, generally just being annoying and filling up nameplate space and distracting people away from the ones that need to be killed.

http://www.wowhead.com/npc=34605/swarm-scarab

**Comment by Lothloryen** [comment]
Hello there,

Thank you very much, I have been notified about this issue today, it seems yesterday's update broke something related to the scarabs - I shall correct and deploy it as soon as I can.
