### ISSUE TITLE
Bugged Quest

### ISSUE THREAD

**Issue by Delahunts** [dalaranwow/dalaran-wow#3533]
There is a bugged quest called "Propaganda War" located in Dustwallow Marsh, uppon a ship.

Whenever i go there, dead bodies starting attacking me, without being able to hit them (as their dead lel). Also, the quest item is nowhere around there.

**Comment by ImprezaWoW** [comment]
Can not confirm. All movs were alive when I boarded the ship. Did not see any corpses that could attack me either, and the killed mobs didn't attack me. Also, [the quest item is in its correct place.](http://imgur.com/a/Vwf0G)
