### ISSUE TITLE
[Ulduar] Yogg-Saron - Cloud Desynchronization

### ISSUE THREAD

**Issue by saltylopez** [dalaranwow/dalaran-wow#3534]
This has sort of been a problem since we've started doing Yogg.  If some players died and others managed to stay alive after a wipe (usually because of Hodir) then those two sets of players would become desynchronized and see different sets of clouds.  Previously, you could fix this issue by forcing the alive players to wipe and making everybody zone in at the same time.

Last night, a new issue (for us anyway) popped up.  Clouds that moved out of draw distance would no longer appear to move on our clients, but I guess they were still moving server-side.  Players would think they were safe to move somewhere that their client showed no clouds, but server-side actually had clouds there.  It was causing clouds to get popped from literally across the room.

This is quite a problem as the clouds on the outer-ring of Yogg's room will move out of draw distance.  We were able to get around it in 10 man by parking the entire raid on Yogg's inner ring of clouds, but this option will not really work in 25 man.

We also had a new (possibly unrelated) bug where Yogg aggro'd characters before all of the keepers were dead. It seemed to be caused by walking too close to the ring outside the Keeper rooms that looks down on Sara.

**Comment by Lothloryen** [comment]
Hello there,

Thank you for your report. This is directly related with the visibility distance, indeed - system which I am currently trying to improve, as well as keep increasing the values bit by bit. It should be much better in 1-2 weeks.

If the aggro issue repeats again, let me know and I shall take a look into it.

Regards.
