### ISSUE TITLE
Divination: Gorefiend's Armor, Cloak, Truncheon

### ISSUE THREAD

**Issue by MrAndersonX** [dalaranwow/dalaran-wow#3535]
**Description**:
These are quests that are part of a large quest chain.
**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
The quests are handed out by "The Ancient Shadowmoon Spirit at the Altar of Shadows in southeast Shadowmoon Valley". While I did encounter the NPC and got the quests and completed them after the server had a restard, now when I went to turn the quests in, the NPC was replaced by another NPC named Terong Gorefiend (which I think is the NPC the quests are talking about, the one I should find but later during the quest chain etc).
**Expected behaviour**: Tell us what should happen instead
The NPC should spawn once I equip the Spectrecles (http://wotlk.openwow.com/item=30719) and I should be able to talk to him and to turn the quests in. Before the server restart he wasn't where he was supposed to be also.
Links to the quests : 
http://wotlk.openwow.com/quest=10634 Divination: Gorefiend's Armor
http://wotlk.openwow.com/quest=10635 Divination: Gorefiend's Cloak
http://wotlk.openwow.com/quest=10636 Divination: Gorefiend's Truncheon
**Steps to reproduce the problem**:
1. Just head to the targeted area and u will see the NPC is missing/replaced by Teron Gorefiend.
2. 
3. 

**Include proofs for this behaviour**
https://postimg.org/image/bpreug8s7/ - without Spectrecles
https://postimg.org/image/9n6zzl9n5/  - with Spectrecles
You can research this on several pages like http://wowhead.com or http://wowwiki.wikia.com or http://www.youtube.com/
http://www.wowhead.com/npc=21797/ancient-shadowmoon-spirit
And this is the link to see the NPC that currently replaces him: 
http://www.wowhead.com/quest=10644/teron-gorefiend-lore-and-legend
**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**
NPC ID nr# is 21797 I think.
You can research this on several pages like http://wotlk.openwow.com or http://wowhead.com/

**Include Screenshots from the issue if necessary**

**Comment by Rushor** [comment]
script for https://github.com/dalaranwow/dalaran-wow/issues/3561 is broken, i will fix both issues in https://github.com/dalaranwow/dalaran-wow/issues/3561
