### ISSUE TITLE
Commander Hobb

### ISSUE THREAD

**Issue by MrAndersonX** [dalaranwow/dalaran-wow#3536]
**Description**:
He is a NPC that should appear in horde camp "Sanctum of the Stars" in Shadowmoon Valley.
**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
Currently, he is either invisible or missing, and only a weapon (his weapon), a flying burning axe is in his place as a target.
**Expected behaviour**: Tell us what should happen instead
The NPC should appear.
**Steps to reproduce the problem**:

1. 
2. 
3. 

**Include proofs for this behaviour**
https://s32.postimg.org/d6qniy54l/Wo_WScrn_Shot_070116_180300.jpg - picture
https://s32.postimg.org/mtkgovj6d/Wo_WScrn_Shot_070116_180314.jpg - picture
You can research this on several pages like http://wowhead.com or http://wowwiki.wikia.com or http://www.youtube.com/
http://www.wowhead.com/npc=23434/commander-hobb
**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**
ID nr# 23434 I think.
You can research this on several pages like http://wotlk.openwow.com or http://wowhead.com/

**Include Screenshots from the issue if necessary**

**Comment by jonanone** [comment]
The issue has been fixed and now the NPC will be visible. The fix will be applied to the live realm soon.
