### ISSUE TITLE
Lvl 60 hunter epic weapon quest chain (ancient petrified leaf)

### ISSUE THREAD

**Issue by Tyrial** [dalaranwow/dalaran-wow#3538]
Quest chain could not be completed atm due to critical issues:
1. Stave of the ancients quest: Solenor the slayer (silithus demon) does not drop the head (tryed to kill in grp and solo with/without pet)
2. A proper string quest: the quest item (mature black dragon sinew) should drop (according to wowhead) from any black dragon in burning steppes, but it doesnt, though while having a quest in quest log and hovering the cursor over black dragons in BS it shows mature black dragon sinew 0/1(this item also should drop from onyxia both lvl 60 and lvl 80 versions, but i didnt had a chance to test it).
3 Lock' delar stave of the ancient keepers: After completeion of the main quest chain and getting the bow Hastat the ancient should have dialog (you must have a bow with you!!!!), through wich you can obtain the staff, but atm he does not have this dialog even if you have the bow.
Non critical issues:
Stave of the ancients quest:
1. Demons are generally not scripted: quest says you must be alone (without pet), but atm you can be with pet and in grp  with other character's actively participatig in killing process (heals, buffs dps)
2. None of the demons transforms into his real form
3. Klinfran the crazed (burning steppes demon) cant be killed by lvl 60 hunter due to insane damage of his spells (around 4k and it doesnt seem to have a large cd), unless you bring lvl 80 to help.
Other parts/quests in this chain work fine or are at least completeable atm.

**Comment by Golganeth** [comment]
#974
