### ISSUE TITLE
Molten Armor - Not correct crit chance/value after relog/disconect

### ISSUE THREAD

**Issue by JarlBallin** [dalaranwow/dalaran-wow#3539]
**Description**: Bugged crit chance/value for Molten Armor

**Current behaviour**: After a relog or a disconect, when you log back in, you still have Molten Armor buff, but the crit chance is reduiced. You have to re-apply molten armor after relog/DC to get the correct crit value.

**Expected behaviour**: The crit chance should be the same when u login after a relog/disconect, rather than dropping crit chance and having to re-apply.

**Molten Armor ID:** 30482 

**My YouTube link displaying the problem:** https://www.youtube.com/watch?v=dmSJQoADYow

**Comment by JarlBallin** [comment]
Can you also label this with: Spells/Auras ?

**Comment by JarlBallin** [comment]
Any update on this?

**Comment by JarlBallin** [comment]
@robinsch

**Comment by robinsch** [comment]
@JarlBallin Can't confirm this. Working fine on PTR. Can you link me your spec, might be related to some talents increasing Spirit (Those should be applied before Molten Armor).

**Comment by JarlBallin** [comment]
@robinsch I use normal frostfire spec; no talents increasing spirit. I use Glyph of Molten Armor, which gives me additional 20 % of my spirit as crit rating. Here's the spec: http://wotlk.openwow.com/talent#oZfVcbRhIhVubhctbIccoc

Doesn't make sense when u relog / DC, and login again, u have lower crit chance, and have to re-apply molten armor for correct crit value...

**Comment by robinsch** [comment]
Yes I see it, then it's already fixed on PTR. Glyph auras are now applied before normal auras. See https://github.com/dalaranwow/dalaran-wow/issues/3587

**Comment by robinsch** [comment]
Tested on PTR. Fix confirmed.

**Comment by JarlBallin** [comment]
Lovely! <3 :D

**Comment by TeridanDW** [comment]
Works as intended on ptr.
