### ISSUE TITLE
lvl 60 priest epic staff quest "the balance of light and shadow"

### ISSUE THREAD

**Issue by Tyrial** [dalaranwow/dalaran-wow#3540]
You should not be able to see the questgiver Eris Havenfire while not having eye of divinity equipped- this part works fine.
Currently quest cannot be completed due to event not starting (peasants are not coming, undeads not spawning, basically you accept the quest and nothing happens).
how it should be - http://wowwiki.wikia.com/wiki/Quest:The_Balance_of_Light_and_Shadow
https://www.youtube.com/watch?v=mW6JJshDOm8

**Comment by robinsch** [comment]
https://github.com/TrinityCore/TrinityCore/issues/11961
@Rushor

**Comment by sixele** [comment]
wow hello [#2436](https://github.com/dalaranwow/dalaran-wow/issues/2436) :(

**Comment by Golganeth** [comment]
#2436

**Comment by rustypickle** [comment]
I have the same issue, and I have both eye trinkets, just need the splinter you get from this quest. Rip.
