### ISSUE TITLE
[Shaman] Earth Shield Crit Chance

### ISSUE THREAD

**Issue by Marquito01** [dalaranwow/dalaran-wow#3541]
**Current behaviour**:  Earth Shield is critting based on spell crit chance of the target instead of spell crit chance of the shaman that casted it.

**Expected behaviour**: Earth Shield should crit based on the spell crit chance of the shaman: 
http://wowwiki.wikia.com/wiki/Patch_3.0.8
"Earth Shield: Now correctly uses the Shaman's own spell critical strike chance to determine the chance of a critical heal."

**Steps to reproduce the problem**: Cast earth shield on a war / dk, and observe 

**Include proofs for this behaviour**

War figurine (war with 0% spell crit chance)
![es crit on war](https://cloud.githubusercontent.com/assets/12214615/16541010/8e6aec7e-4078-11e6-98ff-cb81fed91782.png)

Mage figurine (mage with +- 20% spell crit chance)
![es mage](https://cloud.githubusercontent.com/assets/12214615/16541017/aca9a9a0-4078-11e6-94c2-2298dd9d11b9.png)

And screen of the healer's ES crit chance (39%)
![shaman](https://cloud.githubusercontent.com/assets/12214615/16541027/da3aa824-4078-11e6-8ecc-ea3fd777f539.png)

Special thx to Tydon for being my test figurine!

/Edit

Just finished testing with a bigger sample:

In whole Nax10 I had 5 ES crits out of 584 procs = 0.9% 
My crit chance was +- 40%.

![es nax](https://cloud.githubusercontent.com/assets/12214615/16542750/d507fa90-40b5-11e6-9251-6ea670911763.png)

This bug cripples the spell in pve, as tanks have very low spell crit chance and its quite serious bug for pvp/arenas as well, because the spell crit chance on a melee arena partner will be very low.

**Comment by robinsch** [comment]
On PTR.

**Comment by robinsch** [comment]
Tested on PTR. Fix confirmed.

**Comment by robinsch** [comment]
Can someone confirm this is fixed on live?

**Comment by Marquito01** [comment]
Confirmed, works on live for a year or so.
