### ISSUE TITLE
[Paladin] Blessing of might

### ISSUE THREAD

**Issue by Hellafreshlobster** [dalaranwow/dalaran-wow#3543]
**Description**: Blessing of might is not giving correct Attack power

**Current behaviour**: Blessing of might won't apply ranks past rank 6 when casting.

**Expected behaviour**:  Blessing of might should update its buff with new ranks.

I haven't seen anyone else bring this issue up, would appreciate a response so i can know if this has been an existing problem, or something new.

Thanks,
Corellon

**Comment by Tarpor** [comment]
What do you mean exactly? I seem to have 0 issues with any blessing of might's attack power. Could you provide screenshots of your character with and without buff?

**Comment by Hellafreshlobster** [comment]
After looking at the numbers, it is giving the correct amount of attack power. The buff just displays the wrong numbers on my buff bar.


Before
![wowscrnshot_070416_133139](https://cloud.githubusercontent.com/assets/20258378/16569490/e915196e-41eb-11e6-8956-625de10da4a5.jpg)



After
![wowscrnshot_070416_132847](https://cloud.githubusercontent.com/assets/20258378/16569492/f6827ce0-41eb-11e6-88df-50e29329e2d3.jpg)


So, not as big of an issue as i thought, but it might still need looking at.

**Comment by robinsch** [comment]
Same as on retail. Buff tooltips don't scale.
