### ISSUE TITLE
Character sheet values bugged

### ISSUE THREAD

**Issue by Carpathea** [dalaranwow/dalaran-wow#3545]
**Description**:
Hit rating and trinket tooltip bugs.

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
 My hit rating is, it says 123 when i hover over it, the tool tip read chance to hit a mob of level 80 increased by 300% but nothing else
 On my trinket sundial of the exiled it says increased spell power by 50,000. Which is clearly not right.

**Expected behaviour**: Tell us what should happen instead
Im not sure how it is supposed to look but i feel like i should get an itimized level hit rating listing. i.e chance to hit a 81,82,83,84 boss etc. (as its has always been this way im not sure how its supposed to look but by talking to members of the server it seems wrong). The trinket spell power value is clearly wrong

**Steps to reproduce the problem**:

1. Log on
2. Press C, to bring up character menu
3. hover over sundial of the exiled and hit rating

**Include proofs for this behaviour**
http://i.imgur.com/gZOSV9N.jpg
http://i.imgur.com/uEYrnPD.jpg

**Comment by ImprezaWoW** [comment]
Can be caused by a modified client or a corrupted file, perhaps even some addon. Reinstalling a regular 3.3.5a client should fix the problem.

**Comment by Carpathea** [comment]
I went to the warmane download and it seems to have fixed this and elv which is nice thanks!
