### ISSUE TITLE
Mail items disappeared after sending

### ISSUE THREAD

**Issue by kewiener** [dalaranwow/dalaran-wow#3551]
As the title says some of my heirlooms that I sent over to my character disappeared after I sent them.
I sent 3 items: Heirloom chest legs and the staff.
The only thing that I recivied was the staff and a letter named after the heirloom chest.
I'm posting this here since I've spent way to much time to get these vote points and a GM never responds to my ticket after hours of waiting.

**Comment by DalaranLantri** [comment]
This isn't the place for these issues. They got lost because you deleted your character. Please wait patiently for your ticket to be answered.
