### ISSUE TITLE
Flight Paths Bugged at Landing

### ISSUE THREAD

**Issue by MahinChicken** [dalaranwow/dalaran-wow#3553]
**Description**:
Multiple flight paths in Northrend seem to be bugged on landing
**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
When you land after using a flight path, your toon floats a couple of feet ing the air.  You are unable to move, cast, hearth, or anything.  You also cannot log out.  The only way to free yourself is to use Alt + F4, and when you log back in you will be on the ground and can proceed normally.
This problem occurs randomly, but on multiple flight paths in Northrend, especially when flying to Ulduar or the Argent Tournament Grounds.  It doesn't occur every time, or to every character, but it happens frequently to my toon Mahin on Algalon.
**Expected behaviour**: Tell us what should happen instead
You should land and be able to move normally, not be stuck in the air unable to do anything.
**Steps to reproduce the problem**:
There really aren't any steps beyond taking a flight path from say Dalaran to Ulduar.  
1. 
2. 
3. 

**Include proofs for this behaviour**

You can research this on several pages like http://wowhead.com or http://wowwiki.wikia.com or http://www.youtube.com/

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

You can research this on several pages like http://wotlk.openwow.com or http://wowhead.com/

**Include Screenshots from the issue if necessary**

**Comment by Golganeth** [comment]
Must be related to #2878 / phasings
