### ISSUE TITLE
Quest Bug: Do Your Worst

### ISSUE THREAD

**Issue by caramelsumo** [dalaranwow/dalaran-wow#3554]
**Description**: The quest "Do Your Worst" is not easily completed without many deaths. As soon as you hop into the Refurbished Demolisher and begin moving towards the quest area, Frostbrood Sentries will immediately begin attacking the siege unit, destroying it within seconds. After the demolisher is destroyed, they will attack and kill the player.

The flying units above (i.e. the frost wyrms and gargoyles) seem to home in on vehicles. This makes sense for the flying rail shooter daily, but is detrimental to completing this quest.

Edit: The workaround is to kill the mobs yourself without the help of the siege unit... all 172 of them.

**Current behaviour**: Frostbrood Sentries and Gargoyle Ambushers attack and destroy the Refurbished Demolisher.
**Expected behaviour**: Frostbrood Sentries and Gargoyle Ambushers ignore the Refurbished Demolisher.

**Steps to reproduce the problem**:
1. After accepting the quest, jump into the Refurbished Demolisher.
2. Attempt to move towards the quest area.

**Research:**
I entered the wowhead pages for both the Alliance and Horde versions of this quest, and performed a Ctrl+F for the terms "frost," "wyrm," "dragon," and "gargoyle." They did not yield any useful results, which indicates that the flying mobs are not a factor while questing in retail, and should not be part of the quest.

**IDs:**
QuestID: 13394 (Alliance) & 13305 (Horde)
Frostbrood Sentry ID: 31721
Gargoyle Ambusher ID: 32188
Refurbished Demolisher ID: 31830

**Comment by jonanone** [comment]
Hi, this issue has been solved already and it is in testing process. It will be applied to the live realm soon.

**Comment by Crispybuilt** [comment]
As mentioned by the OP:
*Edit: The workaround is to kill the mobs yourself without the help of the siege unit... all 172 of them.*
