### ISSUE TITLE
[Alchemy] Crazy Alchemist's Potion

### ISSUE THREAD

**Issue by Marquito01** [dalaranwow/dalaran-wow#3557]
**Current behaviour**: [Crazy Alchemist's Potion](http://wotlk.openwow.com/item=40077) does not currently proc a random additional potion.

**Expected behaviour**: The potion should have a proc chance (rather high) for an additional potion effect. 

Best proc list I found, also with some proc explanations http://www.mmo-champion.com/threads/680639-Holy-Paladin-PvE-Guide-and-FAQ mentions these procs:  
[Potion of Wild Magic](http://wotlk.openwow.com/item=40212), [Potion of Speed](http://wotlk.openwow.com/item=40211), [Powerful Rejuvenation Potion] (http://wotlk.openwow.com/item=40087), [Indestructible Potion](http://wotlk.openwow.com/item=40093), [Runic Mana Potion](http://wotlk.openwow.com/item=33448), [Runic Health Potion](http://wotlk.openwow.com/item=33447), Mighty Resistance Potions

**Comment by jonanone** [comment]
Now using the crazy alchemist potion has a chance of applying another extra effect to the player.

This update will be applied to the live realm soon.
