### ISSUE TITLE
[ToC] Faction Champs have no global cooldown

### ISSUE THREAD

**Issue by ashido96** [dalaranwow/dalaran-wow#3559]
The faction champs don't have a global cool down on their abilities for example the mage can cast 
Arcane Blast then follow up with Arcane Barrage and Arcane Explosion with 0.5 seconds effectively one shoting who-ever he's targeting.

**Comment by Tarpor** [comment]
He casts arcane blast, while he casts, the global cooldown goes off, and then he uses an instant cast spell? Your example isn't really accurate

**Comment by ashido96** [comment]
Arcane blast was cast, then arcane barrage was cast correctly, then arcane explosion *incorrectly* followed approximately 0.2 seconds later ignoring what is seen as the global cooldown for players.

**Comment by Rushor** [comment]
spellcooldown should be implemented already. see https://github.com/dalaranwow/dalaran-wow/issues/182 for details

https://github.com/dalaranwow/dalaran-wow/issues/182#issuecomment-229751678
