### ISSUE TITLE
Lifebloom targets

### ISSUE THREAD

**Issue by hairybeast2** [dalaranwow/dalaran-wow#3560]
**Description**: a Druids lifebloom spell can currently be cast on multiple targets

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
When casting lifebloom on a second player, the original (first) players lifebloom hot is not deactivated 

**Expected behaviour**: Tell us what should happen instead 
Lifebloom should be removed from the previous target when cast on someone new

**Steps to reproduce the problem**:

1.  Cast lifebloom on an ally
2.  Cast lifebloom on another group member/ally
3. 

**Include proofs for this behaviour**

You can research this on several pages like http://wowhead.com or http://wowwiki.wikia.com or http://www.youtube.com/

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

Lifebloom spell id: 33763 (this is the id for the new ver. Of wow on wowhead, not sure if it's the same?).

You can research this on several pages like http://wotlk.openwow.com or http://wowhead.com/

**Include Screenshots from the issue if necessary**

**Comment by Golganeth** [comment]
This is WoTLK. 

Closed

**Comment by fsironman** [comment]
Why are you not providing any proof of this behaviour?

Lifebloom had no  Limit to the Number of targets in WotLK
