### ISSUE TITLE
UBRS Solakar Flamewreath 

### ISSUE THREAD

**Issue by mnbdru** [dalaranwow/dalaran-wow#3562]
Solakar Flamewreath is spawned at the end of the "Father Flame" event in the Upper Blackrock Spire Rookery. You need to "use" or loot "Father Flame" to start the event, where 6 waves of mobs starts coming towards you, last wave being Solakar Flamewreath.

Currently, when you press on or loot "Father Flame" nothing happens, event is not triggered and you can't get access to Solakar boss.

Quote explaining how it works:

> "Walkin and head to the left - it doesn't matter whether you kill the two guards or not - and you will see a glowing crystal near the wall. Click it as to loot, and you can get Father Flame. By right clicking it you'll see a yell, and two dragonkin will come to attack you. There are 6 waves of two dragonkin each, with about 30 seconds of downtime between them (as I did this on my 80 pally not sure if its 30 seconds from the time you kill them or the time that they spawn, since I killed them almost instantly). After the 6th wave Solakar will yell at you and spawn. "

 
http://www.wowhead.com/npc=10264/solakar-flamewreath#comments

http://wowwiki.wikia.com/wiki/Solakar_Flamewreath

**Comment by ImprezaWoW** [comment]
Reported in [1817](https://github.com/dalaranwow/dalaran-wow/issues/1817).
