### ISSUE TITLE
Website not Showing Characters

### ISSUE THREAD

**Issue by Fapmonsoon** [dalaranwow/dalaran-wow#3565]
**Description**: Cannot post to forums because my account says "No Characters Found". I have used the donation service already and items properly appeared in my mailbox. 

**Current behaviour**: On website when I attempt to use the forums it says "You must have a character selected to post to forums" On the main page where it says my name, under it, it states there are no characters found. I have searched the site and every option and cannot find a way to select one. 

**Expected behaviour**: When creating a character I would assume it would recognize characters and either on the screen where it says "No Characters Found" or in the account settings somewhere having the option to select it. 

**Steps to reproduce the problem**:

1. Create an account
2. Log in and create a character
3. Go to the website 

**Include proofs for this behaviour**
There is nothing that I can prove other then to take a screenshot of the website.

**Comment by Morens-D** [comment]
You can report only in-game issues via Bug Tracker.
Visit #2107 for more info regarding your issue, please.
