### ISSUE TITLE
[Item] Banshee Rod

### ISSUE THREAD

**Issue by ImprezaWoW** [dalaranwow/dalaran-wow#3566]
**Description**:
The stats for the item Banshee Rod of the Moon/of the Sun are incorrect.
**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
The item gives +0 Stamina
**Expected behaviour**: Tell us what should happen instead
The item should give +1 Stamina
**Steps to reproduce the problem**:
1. Loot Banshee Rod from Dr. Whitherlimb (recently implemented mob)

**Include proofs for this behaviour**

http://www.wowhead.com/item=31270/banshee-rod
http://wowwiki.wikia.com/wiki/Banshee_Rod

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**
Banshee Rod item ID 31270
**Include Screenshots from the issue if necessary**
http://i.imgur.com/zeGYkN2.png
http://i.imgur.com/4utQN3d.png

**Comment by Rushor** [comment]
Clientissue. The enchants are set by ItemRandomProperties.dbc (see https://trinitycore.atlassian.net/wiki/display/tc/item_enchantment_template). So this cannot be changed (except with hacks, but we don't like them)
