### ISSUE TITLE
Global bug-mob appearance distance

### ISSUE THREAD

**Issue by senpai12305** [dalaranwow/dalaran-wow#3568]
**Description**:

**Current behaviour**: Many people have same issue, we can see mobs when its too late. Something like "runnin, runnin... and giant spider is like 2 meter from me". 

**Expected behaviour**: Can you please investigate what is the reason of this issue and... please, solve this problem? It is very very annoying... thank you

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Include proofs for this behaviour**

You can research this on several pages like http://wowhead.com or http://wowwiki.wikia.com or http://www.youtube.com/

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

You can research this on several pages like http://wotlk.openwow.com or http://wowhead.com/

**Include Screenshots from the issue if necessary**

**Comment by ImprezaWoW** [comment]
This was intentionally done to reduce lag. The view distance is being gradually increased. You can also go  to Menu>Video>Effects>View Distance and set it to highest, if it is not.

**Comment by beregas** [comment]
any idea how long does it gonna take to get back to normal levels?
