### ISSUE TITLE
Druid: HoT amounts changed.

### ISSUE THREAD

**Issue by Akensai** [dalaranwow/dalaran-wow#3569]
**Description**: 
Druid Healing Over Time abilities are healing for much less than they should be after the recent patch.

**Steps to reproduce the problem**:

1. Just use rejuvenation and compare to any WoTLK video or before the last patch.

In my case, (PvP Geared) rejuvenation was healing for around 2400-2500 per tick. Now it is between 1700-1800. All videos show closer to the former numbers. I am not sure if this effects all HoT spells as I am unsure what the others generally healed for. I believe it effects all of them.

**Comment by robinsch** [comment]
DOTs and HOT were double scaling for a long it, this was fixed. Please calculate it with coeff and your spell power for correct results.
