### ISSUE TITLE
Just Following Orders

### ISSUE THREAD

**Issue by dailyspesh** [dalaranwow/dalaran-wow#3570]
**Description**: 
It's not currently possible to complete this quest with the Injured Rainspeaker Oracle and continue with the quest line.

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who) 
Nothing happens when clicking on this NPC (it has a grey ? above its head).

**Expected behaviour**: Tell us what should happen instead
A crocodile should spawn and needs to be killed in order to complete the quest but nothing happens, resulting in a quest that's not able to be completed. 
**Steps to reproduce the problem**:

1. Accept "Just Following Orders" from Frenzyheart Hill.
2. Go to the Injured Rainspeaker Oracle described in the quest text and attempt to complete the quest.
3. Watch as nothing happens!

**Include proofs for this behaviour**

You can research this on several pages like http://wowhead.com or http://wowwiki.wikia.com or http://www.youtube.com/

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

You can research this on several pages like http://wotlk.openwow.com or http://wowhead.com/

**Include Screenshots from the issue if necessary**

**Comment by jonanone** [comment]
Injured Rainspeaker Oracle behaviour has been updated to not stay bugged when someone doesn't accept Fortunate Misunderstandings quest.
Now it should work fine every time.

This update will be deployed to the live realm soon.
