### ISSUE TITLE
The Cell - NPC stuck in map, not attackable

### ISSUE THREAD

**Issue by callmestabby** [dalaranwow/dalaran-wow#3573]
**Description**:

**Current behaviour**: The NPC General Ceruleon is stuck halfway through the map. he is targetable, however attacks state that he is too far away.

**Expected behaviour**: He should be attackable and drop the necessary quest item.

Screenshot here: http://i.imgur.com/bJveNY6.png

**Comment by ImprezaWoW** [comment]
Can be fixed in-game by a GM, the chance for the NPC to spawn the way provided is very, very low and can happen to generally any mob.
