### ISSUE TITLE
Quest.  [Shoot 'Em Up] 

### ISSUE THREAD

**Issue by xStiven** [dalaranwow/dalaran-wow#3575]
Quest name: Shoot 'Em Up
Wowhead link: http://www.wowhead.com/quest=13069/shoot-em-up
How it supposedly, works on official servers; https://www.youtube.com/watch?v=KqGiOV8Dofg
What is wrong:  Problem is simple - "harpon" skill on the turret, is doing no damage to drakes.

**Comment by xStiven** [comment]
Well, since im doin icecrown now, i guess im just goin to post all broken quests in this thread,

Quest name: 
How it supposed to work: https://www.youtube.com/watch?v=HiM_PIRx0hk
Whats wrong: Second enemy NPC - "Brita" (female with bow), isn't activating after Volgul death, which makes that quest undonable.

**Comment by DalaranLantri** [comment]
#1898 #2628 duplicate.
