### ISSUE TITLE
High Priestess Jeklik

### ISSUE THREAD

**Issue by Braniacz** [dalaranwow/dalaran-wow#3578]
**Description**:
High Priestess Jeklik doesn't fly down from the ledge after you start the encounter.

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
This boss is located in lvl 60 raid (Zul'Gurub). Npc's name is High Priestess Jeklik. After you start the fight, boss stay's on the ledge and doesnt want to fly down, thus it's nearly imposible to kill it for certain classes/specs.
**Expected behaviour**: Tell us what should happen instead
Boss should fly down so u can start the process of execution.
**Steps to reproduce the problem**:

1. Go in Zul Gurub.
2. Find the High Priestess Jeklik (bat boss).
3. Start the fight.

**Include proofs for this behaviour**
https://www.youtube.com/watch?v=9nHAzd8VpTc
You can research this on several pages like http://wowhead.com or http://wowwiki.wikia.com or http://www.youtube.com/

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**
High Priestess Jeklik:npc=14517
You can research this on several pages like http://wotlk.openwow.com or http://wowhead.com/

**Include Screenshots from the issue if necessary**

**Comment by jonanone** [comment]
High Priestess Jeklik will now fly down when engaged.

This update will be applied to the live realm soon.

**Comment by Melzy** [comment]
This bug still exists.

**Comment by Edzero** [comment]
On PTR:

She will now fly down and engage properly. Uses the correct abilities.

Sometimes the Bloodseeker Bats she summons will get stuck up on the ledge where she was originally standing.

Other than that she is working very well.

**Comment by Rushor** [comment]
DB/Instances/Zul'gurub: High Priestess Jeklik

- Jeklik is now able to fly down when engaged.

Closes https://github.com/dalaranwow/dalaran-wow/issues/3578

commit: 9ffa5872551c2915c4ed532a14691959c1759ee6

**Comment by Rushor** [comment]
Reference: https://github.com/dalaranwow/dalaran-wow/issues/4124

**Comment by Rushor** [comment]
already on PTR
