### ISSUE TITLE
Quest: The Grand Melee

### ISSUE THREAD

**Issue by Kaara** [dalaranwow/dalaran-wow#358]
Hello,

http://www.wowhead.com/quest=13772/the-grand-melee

This quest is bugged. I got on the argent mount. But i cannot fight them, i cannot click on Are you ready to fight ?

**Comment by roblockster** [comment]
Sometimes NPCs say you already fought them when you didn't, and the chat option does not appear. Other times the NPCs run out and immediately reset.
