### ISSUE TITLE
Flight Form does not benefit from crusader aura while on the ground

### ISSUE THREAD

**Issue by Klala** [dalaranwow/dalaran-wow#3580]
**Description**: Flight Form and Swift Flight Form do not benefit from the paladin's crusader aura while being on the ground.

**Current behaviour**: When you are in flight form, and you are moving on the ground while having a paladin's crusader aura, your speed does not increase to 120% but instead stays on 100%. Works correctly while flying.

**Expected behaviour**: Both flight forms should benefir from crusader aura while on the ground.

**Steps to reproduce the problem**:

1. Use flight form while being with a paladin in a group while he is using crusader aura
2. try to follow the paladin while he is mounted with his swift ground mount
3. notice that he is faster than you

**Comment by robinsch** [comment]
Please post a proof from retail

**Comment by Klala** [comment]
Unfortunately, I do not have a proof. Also according to wowwiki it seems like it works as intended.

"Patch 3.2.0 (04-Aug-2009): This ability now also grants its **flying** speed increase to a druid's Flight Form and Swift Flight Form."
