### ISSUE TITLE
Rogue's talent Honor Among Thieves

### ISSUE THREAD

**Issue by Jiaku** [dalaranwow/dalaran-wow#3582]
**Description**:
The problem with a talent is that if you are on a battleground you will get combat as soon as you come close to the battle, the only way to get rif od the combat is to go away for 40 yards.
**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
Rogue does get combat as soon someone crit within 40 yards(i assume) 
**Expected behaviour**: Tell us what should happen instead
Rogue does not get combat unless you have combat points on target. Or you don't get combat even if you have combat points and target and you don't attack it.
**Steps to reproduce the problem**:

1. Get Honor Among thieves 3/3
2. Enter BG
3. Come close to the battle.

**Include proofs for this behaviour**

You can research this on several pages like http://wowhead.com or http://wowwiki.wikia.com or http://www.youtube.com/

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**
spell=51701

**Include Screenshots from the issue if necessary**

**Comment by robinsch** [comment]
"You can research this on several pages like http://wotlk.openwow.com or http://wowhead.com/" is not valid. Please fill those things out next time.

**Comment by robinsch** [comment]
On PTR.
