### ISSUE TITLE
[Quest] Everything Must Be Ready

### ISSUE THREAD

**Issue by Bonham01** [dalaranwow/dalaran-wow#3584]
**Description**:
This is the alliance quest that leads players to Fort Wildervar in Howling Fjord. It unlocks quests there.

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
The quest doesn't become available until the player completes the quest All Hail the Conqueror of Skorn (http://www.wowhead.com/quest=11250/all-hail-the-conqueror-of-skorn)

**Expected behaviour**: Tell us what should happen instead
It should become available after the player completes the quest Mission: Plague This! http://www.wowhead.com/quest=11332/mission-plague-this

**Steps to reproduce the problem**:

1. Complete Mission: Plague This!
2. Go to Quartermaster Brevin at Westguard Keep
3. See that quest is not available
4. Complete All Hail the Conqueror of Skorn
5. See that quest is now available

**Include proofs for this behaviour**

See current/expected behavior

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

http://www.wowhead.com/quest=11406/everything-must-be-ready
Also see current/expected behavior

**Include Screenshots from the issue if necessary**

Notes:
I know this is minor, but it makes players do quests out of order if following a guide or trying to do the most efficient routes for questing. Thanks for your hard work.

**Comment by jonanone** [comment]
Quest prerequisite has been updated. This update will be applied to the live realm soon.
