### ISSUE TITLE
[Quest][Loot] - Raising Hodir's Spear

### ISSUE THREAD

**Issue by Klala** [dalaranwow/dalaran-wow#3585]
I have encountered additional mobs which have no loot tables while questing around storm peaks.
The following mobs don't drop anything but quest items:
Stoic Mammoths
Stormforged Ambusher

http://www.wowhead.com/npc=30260/stoic-mammoth#drops
http://www.wowhead.com/npc=30208/stormforged-ambusher#drops

There might be more mobs in that area that has no loot table as I have already made a report about it a while back. I will update here if I will find more.

**Comment by jonanone** [comment]
Missing loot for both creatures has been added. This will be deployed to the live realm soon.
