### ISSUE TITLE
Unable to loot at Four Hoursemen 10 man

### ISSUE THREAD

**Issue by petakaa** [dalaranwow/dalaran-wow#3586]
**Description**: We could not loot the items from the chest due to a combat bug. 

**Current behaviour**: We relogged and left combat but still no dice. In the screenshot we are in Master Looter, so we tried to use Free for All, still couldn't loot. Nobody wanted the mail shoulders, but I really need that chest token. Please fix :)

**Expected behaviour**: I would love to get that Chest token, would be great.

**Steps to reproduce the problem**: This was due to a combat bug, so I am not really sure how looting system can be fixed.

1. 
2. 
3. 

**Include proofs for this behaviour**

SCREENSHOT: http://puu.sh/q3vjy.jpg

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

Raid ID: 260 (Naxx 10)

Item: Chestguard of the Lost Vanquisher

**Include Screenshots from the issue if necessary**

**Comment by DalaranLantri** [comment]
The loot likely bugged out because you changed the loot system. Please open an in-game ticket, this is not the place for these kind of issues.
