### ISSUE TITLE
Expertise from Glyph of Seal of Vengeance doesn't apply after the logging in

### ISSUE THREAD

**Issue by DanteMS** [dalaranwow/dalaran-wow#3587]
**Current behaviour**: previously applied Seal of Vengeance with Glyph of Seal of Vengeance won't give you 10 expertise if you'll log out and log in back. After the logging in you need to reapply Seal of Vengeance to get 10 expertise from the glyph.

**Steps to reproduce the problem**:

1. Apply Seal of Vengeance with Glyph of Seal of Vengeance.
2. Log out.
3. Log in.

![wowscrnshot_071616_142940](https://cloud.githubusercontent.com/assets/8601667/16894618/43620d56-4b64-11e6-8d52-891a3276a3ea.jpg)
![wowscrnshot_071616_143000](https://cloud.githubusercontent.com/assets/8601667/16894619/4920e96a-4b64-11e6-9fd0-20d9ad329315.jpg)
![wowscrnshot_071616_143007](https://cloud.githubusercontent.com/assets/8601667/16894626/79770c2a-4b64-11e6-8fe4-4560cf391748.jpg)

**Comment by DanteMS** [comment]
Also when you're removing that glyph 10 expertise bonus doesn't disappear until Seal of Vengeance will fade out or will be reapplied.

**Comment by robinsch** [comment]
On PTR.

**Comment by robinsch** [comment]
Tested on PTR. Fix confirmed.

**Comment by TeridanDW** [comment]
The relog issue is working as intended on ptr, however 2 issues remain:
 
 - > Also when you're removing that glyph, 10 expertise bonus won't disappear until Seal of Vengeance will fade out or will be reapplied.

 - player casts http://wotlk.openwow.com/spell=31801 or http://wotlk.openwow.com/spell=31892 and then apply the http://wotlk.openwow.com/item=43869 ,the +10 expertise is not added (player needs to recast the seal to the +10 expertise).

Marking as waiting for changelog, if you wish to add something here change the label again please.
