### ISSUE TITLE
[Quest] - Emergency Measures\Cave Medicine

### ISSUE THREAD

**Issue by Klala** [dalaranwow/dalaran-wow#3588]
Both quests work fine. The problem is, there are less spawns of worgs and worms than intended.
There should be more worgs and worms at the entrance of the cave and a little bit outside of it.
This is also true for the Cave Mushrooms.
Also, The worms are in a 'borrowed' state (like the ones in hellfire peninsula) which shouldn't happen.

https://www.youtube.com/watch?v=7zMqTeJCiLE
https://www.youtube.com/watch?v=3-1cbxoCWQw

**Comment by Daveonx** [comment]
Cave Mushroom hasn't been corrected yet, still only 6 spawned in-game.

**Comment by Rushor** [comment]
DB/Quests: Cave Medicine - Add 15 more Cave Mushrooms

* closes https://github.com/dalaranwow/dalaran-wow/issues/3588
* 2cb9210854260cc72295d3f71e7ebd7d16fc5730

Added 15 more spawnpoints for Cave Mushroom gameobjects.

**Comment by Rushor** [comment]
**The issue with spawns of worgs and worms will be moved to https://github.com/dalaranwow/dalaran-wow/issues/4360.** The only thing the tester needs to check in this issue then is the spawn of the mushrooms

https://github.com/dalaranwow/dalaran-wow/issues/3588#issuecomment-260760682

**Comment by TeridanDW** [comment]
Works as intended on ptr (Cave Mushroom corrected).
