### ISSUE TITLE
Pets, DKs and Hunter

### ISSUE THREAD

**Issue by WhiteNigg** [dalaranwow/dalaran-wow#3589]
Some time during the last week the dk and hunter pets were completely screwed. It seems like they no longer scale with the owners stats. I ll talk about dk pets first, so the ghoul should get 100% of its master's STR and stam assuming somone is speced into [http://wotlk.openwow.com/spell=49572](url) and using [http://wotlk.openwow.com/item=43549](url) + whatever stats the ghoul has on its own and from the buffs provided by the raid. Thats not real tho according to print screens i ll show you.
These are my Dk's stats [http://prntscr.com/btmwnq](url)
and these are my ghoul's stats [http://prntscr.com/btmw0l](url) these are with just my class buffs, blood presence and Horn of winter. What really happens is that the pet instead of scaling with whatever stats the owner has at a specific time they get a portion of stats that their owner had the moment they were summoned cause when i summoned my pet with normal Death's Choice proc (450str) [http://prntscr.com/btnk2e](url) it had 4530 str instead of 4100 as shown in the previous screenshot which is +430 while the proc is  450 so they dont scale with 100% of the master's stats as they should. Which means (tested it) that if you mount up after you have summoned your ghoul with all your procs up and then dismount, the ghould will not keep the stats it had when you summoned it with all your procs up, it will instead benefit from the stats you currently have One last thing for some reason when you summon the ghoul it come with 30% hp.
For hunters now, the pet is utter garbage the scaling is close to nothing here are my hunter's stats 1st and pet's 2nd [http://prntscr.com/btmvk7](url)  [http://prntscr.com/btmvg1](url) check the agility "scaling" its just not there and another pair of screen shots if the pet's dmging abilities  [http://prntscr.com/btmuts](url)  [http://prntscr.com/btmuxt](url) and that's a lvl 80 hunter 5.2k gs not a 50 lvl one. I admit i didnt do as much research for hunter as i did for dks but i think you can tell the difference on how shit pets now are.

**Comment by ciccioriccio** [comment]
confirmed, my pet did around 800dps selfbuffed, now only 350

**Comment by Devineshadow** [comment]
Don't forget Gargoyle's. They seem wiped too, dealing 600 dmg no matter what ;o

**Comment by DalaranLantri** [comment]
Please add any comments to #3088 , duplicate, closing.

**Comment by WhiteNigg** [comment]
Its a new issue not the same that Dolmio described, If you didnt bother reading it says "last week".
Pets were already badly scripted and the last update seems to have screw them up more than they already were...
