### ISSUE TITLE
Account registration page does not accept character "+" in email fields

### ISSUE THREAD

**Issue by roots84** [dalaranwow/dalaran-wow#3590]
**Description**:
The account registration page (http://www.dalaran-wow.com/account/register/code/xxxxxx) does not accept the character "+" in the email fields.

**Current behaviour**:
Error "You must type an Email" is thrown once account creation page is submitted.

**Expected behaviour**: Tell us what should happen instead
Account should be created successfully.

**Steps to reproduce the problem**:
http://imgur.com/a/safxE - See screenshots 1 and 2

Regards,
Stefan

**Comment by robinsch** [comment]
This is the ingame bugtracker.
