### ISSUE TITLE
[NPC] Colonel Kurzen

### ISSUE THREAD

**Issue by cybergeek94** [dalaranwow/dalaran-wow#3592]
Name: Colonel Kurzen
Area: The Stockpile
Zone: Stranglethorn Vale

http://db.vanillagaming.org/?npc=813

This NPC has an absurdly long respawn time on this server; though I haven't timed it, it must be at least 15 minutes.

I cannot find any references to what his respawn time was on retail, but since he is the objective of the quest of the same name, his long respawn time is a massive bottleneck for players questing in the area.

I feel his respawn time should be lowered to something more reasonable, say, five minutes or less, or something comparable to the enemies leading up to him, which are also objectives in the "Colonel Kurzen" quest.

Admittedly, it has been a while since I've had to wait very long for him to respawn, so if his respawn time has been lowered already, please close this issue.

**Comment by ImprezaWoW** [comment]
Current respawn time is 30 minutes. Did not find any proof that it should be lower.
