### ISSUE TITLE
[NPC Ability] Contagion of Rot

### ISSUE THREAD

**Issue by abonander** [dalaranwow/dalaran-wow#3593]
This ability seems to be primarily used by [Zanzil Zombie](http://db.vanillagaming.org/?npc=1488) in Stranglethorn Vale.

For some reason, these mobs can apply multiple copies of this disease, either with a 5% or 10% chance to spread on hit. In the following series of screenshots, I have 4 different diseases on me (3x 10%, 1x 5%); a little later, I gained a 5th, another one of the 10% version.

N.B. the 5% version may be applied by one of the named undead mobs in the area, I'm not sure. I didn't really feel like sifting back through my combat log to find when each disease got applied (if it even went back that far).

Imgur album: http://imgur.com/a/6DuU7
My cursor is not visible for some reason but you can tell which debuff a given tooltip pertains to by its relative position in each screenshot.

I can find little reference to how this disease was intended to behave on retail, but given that for a class like Warrior, with the only way to remove diseases being consumables like [Jungle Remedy](http://db.vanillagaming.org/?item=2633), which usually only remove one disease and have a >1m cooldown, this is a great annoyance. As far as I can tell, the effects of the disease do not stack, so it's mostly just unnecessary additional disspells.

**Comment by Rushor** [comment]
DB/Spell: Contagion of Rot - prevent stacking

* the debuff http://wotlk.openwow.com/spell=7103 can no longer be applied muktiple times on the same target
* closes https://github.com/dalaranwow/dalaran-wow/issues/3593
* commit: d64ea1a4d214bfd02221bab079a25b14128dc687
