### ISSUE TITLE
Quest: Kindness

### ISSUE THREAD

**Issue by MrAndersonX** [dalaranwow/dalaran-wow#3594]
**Description**:
Mordenai at Netherwing Fields in Shadowmoon Valley wants you to feed 8 Mature Netherwing Drakes.

Mature Netherwing Drake fed (8)

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
The dragons do not come down once the meat is placed and they do not get a 45 second debuff. They need to be aggroed (flying mount + attack risking death many times...) and after they attack the meat needs to be placed on the ground and endure the mobs' dmg, while the player stops his attacks and waits for the dragon to feed.
Sometimes they appear to just be standing on the ground, though that is a visual bug, so if the player attempts to feed them, it won't work. Attacking them also won't work, resulting in a "Out of range" citation.
**Expected behaviour**: Tell us what should happen instead
The dragons should come down from the sky, eat the meat, and get a 45 second debuff that doesn't allow them to be fed again.
**Steps to reproduce the problem**:
1. Place meat on the ground.
2. 
3. 

**Include proofs for this behaviour**

You can research this on several pages like http://wowhead.com or http://wowwiki.wikia.com or http://www.youtube.com/

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**
Quest ID is nr.#10804 I think.
You can research this on several pages like http://wotlk.openwow.com or http://wowhead.com/
http://www.wowhead.com/quest=10804/kindness
**Include Screenshots from the issue if necessary**
Forgot to take some screenshots. Sorry.

**Comment by dreamingdust** [comment]
Hello,

The current behaviour you mentioned is one of the possibilities that can make the Quest work. The other way to complete the Quest is to put the meat somewhere where the Drakes fly over. My guess is that the meat itself has an aura and whenever a Drake enters the range of the aura it starts the script (I may not be right so I need a confirmation of this, that I cannot provide). Following what I just wrote, I believe you have placed the meat too far from any Drakes.

Also, there is a debuff on the Drake after you get credit for feeding it. During the debuff the Drake stays on the ground and cannot be fed.

I can confirm that some of the Drakes are not flying back in the air after getting fed, and they need to be attacked. Upon attack they get into state of Evasion and reset their position.

Unfortunately I cannot provide screenshots because when I did the Quest I had no problems and took none.

**Comment by MrAndersonX** [comment]
Well, even if the meat has a aura, the drakes do not get attracted to it cause they never get closer to the ground. And after you pull one out of the sky, if they bug and stay on the ground, you need to go back into the sky and attack him once again, cause you seeing him stay on the ground is just a visual glitch so...there's that.
Also did not take any screenshots which I sorely regret not doing right now...

**Comment by dreamingdust** [comment]
My point was that you weren't close enough to the drakes. If you follow one of the drakes you will see they have a path they are following. In case to get a drake come to the ground to be fed, one needs to place the meat beneath the drake's path. Whenever the drake flies above the meat, it will get attracted and come down. The drakes don't have to be close to the ground or on it in case to get attracted.

**Comment by MrAndersonX** [comment]
I don't need to be close to the drakes. And I can't move the ground/world. The meat placed on the ground should attract the drakes but it doesn't. And they do not come down. This discussion seems pointless right now...
Fyi, they fly way too high to even have a shot of attracting one.

**Comment by Randomi** [comment]
Just wanted to confirm, that's pretty annoying.

**Comment by Pentex11** [comment]
The quest was fixed, and it was just tested on the PTR. It works fine now. The fix will be applied soon.
#Closed

**Comment by TeridanDW** [comment]
When the player plant the meat, the gameobject is spawned exacly on the same cordinates as the player but in higher Z , this is how it looks:
![wowscrnshot_033117_220354](https://cloud.githubusercontent.com/assets/6797611/24565541/3db19794-165e-11e7-9611-0b87367875d3.jpg)
![image](https://cloud.githubusercontent.com/assets/6797611/24565511/21c8a630-165e-11e7-9512-201384184e2a.png)
 - there is a missing emote when the drake eats
 - there is a missing emote 35 when the drake reaches the ground
 - the drake stays on the ground for longer period of time than he should

Reference from retail:
https://www.youtube.com/watch?v=P4_GaDmQWJI
