### ISSUE TITLE
[Item/Profession] Pristine Glowbear Pelt has incorrect disenchant table

### ISSUE THREAD

**Issue by cybergeek94** [dalaranwow/dalaran-wow#3595]
http://wotlk.openwow.com/item=51958

I just had a **Pristine Glowbear Pelt of the Hierophant** disenchant into a [Small Glowing Shard](http://wotlk.openwow.com/item=11138) (usually disenchanted from items with a level requirement of 31-35):

![see chat log](http://i.imgur.com/bLge3ha.jpg)
See my chat log where Enchantrix helpfully logged the event.

As the Auctioneer tooltip says, it should have a disenchant table comparable to that of items of the same level.

I don't really care about getting the wrong shard, it was amusing enough that I'm not bothered by it.

**Comment by robinsch** [comment]
On PTR.
