### ISSUE TITLE
Netherwing quest chain Bugged

### ISSUE THREAD

**Issue by Hellafreshlobster** [dalaranwow/dalaran-wow#3596]
**Description**:
My character cannot start the chain for the Netherwing faction

**Current behaviour**: 
Mordenai starts the netherwing chain, but when i talk to him he has no quests available.
I think this might have something to do with my faction change, though i don't remember if i had started the chain before transfer.

Would appreciate if someone could look into this, or tell me if they have had similar problems.
Thanks, 
Fistymc

**Comment by dreamingdust** [comment]
Hello,

Would you like to give a bit more information upon your problem?
With the current information I can point out two possibilities.
1) You are under the level requirement for the first Quest of the chain, "Kindness" (70).
2) You have done the first part of the chain, that ends with the Quest "Ally of the Netherwing" and you don't have the Artisan Riding skill (allows you to ride mounts with speed of 280% or higher). In case to unlock the next Quest in the chain "Blood Oath of the Netherwing" you need to have the above mentioned Artisan Riding skill learnt.
Source for both my statements: http://wowwiki.wikia.com/wiki/Quest:Blood_Oath_of_the_Netherwing

**Comment by Hellafreshlobster** [comment]
Thats not what the issue is, as I am already level 80 with the artisan riding skill. I haven't started it already ether, as I have no rep with netherwing. 
I might have started before faction change, but as it stands its still a bug if I don't have rep or can't get the quests.
