### ISSUE TITLE
[Meta gem] Powerful Earthstorm Diamond, Powerful Earthsiege Diamond etc

### ISSUE THREAD

**Issue by Tiptoptup** [dalaranwow/dalaran-wow#3598]
So I recently tested those two meta gems with a rogue friend.

We mainly tested with 5cp Kidney Shot = 5 seconds stun.

So with the Powerful Earthstorm Diamond (gives 15% stun reduction) which should reduce the 5 seconds stun to 4.25 was still a 5 seconds stun. Kind of an important problem on the pvp scene since this meta gem is supposed to prevent 5 second Kidney Shot into a sap. And that's impossible for any class without stun reduction in talents. Of course it helps a lot with all other stuns too.

Then shortly after we tried the Powerful Earthsiege Diamond which is a 10% stun reduction. Was thinking it might work since it's a wotlk meta and the one above is a tbc meta but was same result there, the 5 second Kidney Shot was still for 5 seconds compared to the correct 4.5 seconds.

**Comment by robinsch** [comment]
It seems like the tooltip is wrong. It should decrease only by 10% according to spell 55358 (Earthsiege Stun Duration Reduction). This is also confirmed by comments (http://www.wowhead.com/item=25896/powerful-earthstorm-diamond#comments)

The 10% decreased stun duration however is working correctly, please keep in mind that the combat timer is 5 seconds (increased with delay) and a full CP kindey shot is 6 seconds -> reduced to 5,4 seconds.
