### ISSUE TITLE
Dalaran-Wow Website Bug issues

### ISSUE THREAD

**Issue by CowboyBird** [dalaranwow/dalaran-wow#3600]
**Description**:
Hey so I noticed when I made an account for this server that your guys' name algorithm on your website doesn't allow names of 3 letter length. My actual name is Ian but I had to use my middle name David when creating my account because the website wouldn't let me use my real name. It's not that big of a deal, but when you have new people coming to the server who have small names like me, it could discourage them from using your server so you should look into fixing that.

**Comment by fsironman** [comment]
Not sure if trolling but why would you even use your real name on a private server?

**Comment by ImprezaWoW** [comment]
The Bug Tracker is for in-game bugs.
Many changes to the website will come when the website is reworked.
