### ISSUE TITLE
Shadowmeld 

### ISSUE THREAD

**Issue by Frobent** [dalaranwow/dalaran-wow#3601]
**Description**: Most of the time it wont get you out of combat on PVE, mobs will still chase you even if they are far way from you

**Current behaviour**: mobs will still chase you even if they are far way from you, also has issues inside dungeons were the mobs still chase you even after using the skill far away from the combat itself
**Expected behaviour**: it should get you out of combat , "Using shadowmeld will temporarily remove you from combat. When you cancel the effect, all aggro that was held towards you is restored if you are still close to hostile mobs". it does none of this things properly

**Steps to reproduce the problem**: Just get a bunch of mobs to follow you and then try Shadowmeld.  bad things will happend, for example.

1. the mobs will still follow you and you will still obviously be in combat,
2. the mob will stare at you for a long time and then either resume hitting you for no reason or stay put for a few seconds and leave

**Include proofs for this behaviour**
This is a known issue that has not ben resolved, need proof just ask around

http://www.wowhead.com/spell=58984

**Include Screenshots from the issue if necessary**

**Comment by mnbdru** [comment]
I haven't experienced this kind of bug. May i ask what's your level and what's mobs level that you trying to shadowmeld? I might be that the mobs lvl are way higher than yours and that's why u fail to loose combat, or maybe mobs have ability to see thru stealth (for example ghouls at stratholme)

**Comment by Frobent** [comment]
i'm level 74 now, but it happends with Mobs of all kind, no particular elvel or ability to see through Stealth, it happends with every mob.  i'm not the only one suffering this, asking the Global chat will spawn a lot of Night elves with the same problem if not every one of them

**Comment by KobalAlgalon** [comment]
Spell [Shadowmeld] don't reset combat in PvP. (I first use "stopattack", after [shadowmeld] or killed player and use [shadowmeld] and combat reset after 7 seconds.) 
In PvE vs mob's - combat reset. Please view screenshot.
![b9cf1b2c-2d4d-11e5-8fb2-abd8fac7442a](https://cloud.githubusercontent.com/assets/13100570/17052422/123ba29a-5006-11e6-9057-c5a173e8aa31.jpg)

**Comment by robinsch** [comment]
@Lothloryen works on PTR as far as I've tested it.

**Comment by robinsch** [comment]
Closed because working on PTR.
