### ISSUE TITLE
Race Change Bug on site

### ISSUE THREAD

**Issue by Carpathea** [dalaranwow/dalaran-wow#3602]
When i click race change through the account character services it redirects me back  to the home page of the site.

Cant really provide more info tbh

**Comment by ImprezaWoW** [comment]
The Bug Tracker is for in-game bugs. 
Anyways, this function was disabled in the website for a reason that we know, and until the website is reworked, you can open an in-game ticket in order to be flagged for race change.

**Comment by Carpathea** [comment]
Thank you i have opened a ticket yesterday at the same time i made this post
