### ISSUE TITLE
Eye of Eternity - getting out

### ISSUE THREAD

**Issue by sebastienwood** [dalaranwow/dalaran-wow#3603]
**Description**: when you're doing EoE, there's no way out other than dying

**Expected behaviour**: having a "normal" way to get out

**Steps to reproduce the problem**:

1. Fight and win EoE on your beautiful drake
2. Wander, for eternity

Note: it also seems like the shield of the drake is bugged

Thanks for your attention !

**Comment by ImprezaWoW** [comment]
[#1366](https://github.com/dalaranwow/dalaran-wow/issues/1366)
