### ISSUE TITLE
Character name's not showing on website.

### ISSUE THREAD

**Issue by melidian** [dalaranwow/dalaran-wow#3604]
**Description**:
When I go to change my "main character" on the website the characters I have on on Algalon - Main Realm don't show only my characters on the other realm. So this is a problem because my main character is on Algalon.
**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)

**Expected behaviour**: Tell us what should happen instead

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Include proofs for this behaviour**

You can research this on several pages like http://wowhead.com or http://wowwiki.wikia.com or http://www.youtube.com/

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

You can research this on several pages like http://wotlk.openwow.com or http://wowhead.com/

**Include Screenshots from the issue if necessary**

**Comment by ImprezaWoW** [comment]
The Bug Tracker is made for in-game bugs, not website issues.
Nonetheless, we are aware of this issue and it will be fixed when the website is reworked. For now, you can connect a character from the Kirin Tor realm in order to use the forums.
