### ISSUE TITLE
Shifting Naaru Sliver

### ISSUE THREAD

**Issue by burningcrusader** [dalaranwow/dalaran-wow#3606]
**Description:**
The Shifting Naaru Sliver is a best in slot trinket for 70 twinks that drops from Entropius in the raid Sunwell Plateau. It got 54 haste as stat and if used it creates a circle animation on the ground that grants the caster 320 spell power over 15 seconds. It works like a paladins Consecration, if you remain in it, it will damage you, if not, you won't get damaged. Same goes for trinket except that you get 320 spell power, if moving outside the animation the effect is lost. 

**Current behavior: Tell us what happens in detail (Where, When, What, Why, Who):**
Currently the animation works when you use the trinket. it puts a purple circle on the ground that vanishes after 15 seconds. During the 15 seconds, NO Spell power is added. The haste given by the trinket works. Used it different times of the day/ different places. Also tried running in and out of the circle without any success. 

**Expected Behavior:**
Standing in this purple circle animation will grant the caster with spell power over 15 seconds if remaining in the circle. The animation continues for 15 seconds until it vanishes. 54 Haste is always granted. 

**Steps to reproduce the problem:**
  
 1: Equip the trinket
 2: Use the trinket
 3: Stand in the animation for the effect of the trinket 

You can research this on several pages like http://wowhead.com or http://wowwiki.wikia.com or http://www.youtube.com/

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**
Wowhead, Twinstar and Openwow all have the same ID for this trinkets spell: 45042
As well as the ID for the trinket: 34429

**Screenshots:**

Using the trinket in-game, notice that there's no buff:

![wowscrnshot_072216_090133](https://cloud.githubusercontent.com/assets/20592479/17049197/1ce9ab84-4fec-11e6-9fd2-121bc6d7d9ad.jpg)

**Comment by robinsch** [comment]
On PTR.
