### ISSUE TITLE
RE : Cursed Talismans

### ISSUE THREAD

**Issue by Vern0m** [dalaranwow/dalaran-wow#3607]
Hello

Can you check this issue, please ?
https://github.com/dalaranwow/dalaran-wow/issues/257

Same problem as alliance player.
Drop rate of Cursed Talisman is very low.
http://wotlk.openwow.com/item=30157

I dont understand Sagrath's message.
Seems there is no horde quest... http://wotlk.openwow.com/item=30157#objective-of

Ty.

**Comment by ImprezaWoW** [comment]
No need to open a duplicate report. Closing.
