### ISSUE TITLE
Horde: Quest: Brutal Armor

### ISSUE THREAD

**Issue by Freshshaven** [dalaranwow/dalaran-wow#3608]
**Description**:

Brutal Armor is a Level 20 Horde Quest for Warriors, wherein you need to gather various materials (10 Iron Bars, 10 Powdered Azurite, 15 Smoky Iron Ingots, and 1 Vial of Phlogiston). Once you have gathered all of these materials, you return to the quest giver (Thun'grim Firegaze) who should then accept the items and let you proceed onto the next quest.

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)

What happens instead is that his floating question mark stays greyed out, even if you have all the materials.

**Expected behaviour**: Tell us what should happen instead

You should be able to hand in all materials with no issue and proceed with the next quest.

**Steps to reproduce the problem**:

1. Accept quest, gather materials
2. Return to quest giver
3. Try and hand in

**Include proofs for this behaviour**

http://www.wowhead.com/quest=1838/brutal-armor
http://www.wowhead.com/item=7126/smoky-iron-ingot
http://www.wowhead.com/item=7127/powdered-azurite
http://www.wowhead.com/item=3575/iron-bar
http://www.wowhead.com/item=6841/vial-of-phlogiston
http://www.wowhead.com/item=7587/thungrims-instructions

**Include Screenshots from the issue if necessary**

![wowscrnshot_072316_232631](https://cloud.githubusercontent.com/assets/3117427/17080572/eeff06be-512c-11e6-8dbe-c17483487c0b.jpg)

**Comment by ImprezaWoW** [comment]
Rare issue, can happen to any quest. Abandoning and retaking fixes it.
