### ISSUE TITLE
Autorepeat spells not switching to your active target

### ISSUE THREAD

**Issue by SVD200** [dalaranwow/dalaran-wow#3609]
Autoshot does not switch to new target after switching targets without being turned off and then back on:

**Current behaviour**: If a hunter who has auto shot active on one target switches to another target, autoshot will continue to hit the original target, and once original target is dead auto shot will not be used at all

**Expected behaviour**: Once the hunter switches target autoshot should start going towards the new target

**Steps to reproduce the problem**:

1. autoshot one NPC
2. either "tab target" or manually target a new NPC, you will notice autoshot will still be directed to your original target, but any other abilities will go towards your new target
3. turn autoshot on then back on and it will be directed to your correct target

**Comment by 161732** [comment]
Wanding currently has the same behavior.

**Comment by robinsch** [comment]
@Lothloryen I can't confirm this. It's working fine on PTR. Are the autoshot fixes applied yet?
