### ISSUE TITLE
[NPC][MULGORE] GHOST HOWL

### ISSUE THREAD

**Issue by Dean1989** [dalaranwow/dalaran-wow#3610]
i'm wondering if this npc exist on the server, with 3 chars i never found it.
it's a rare lvl 12 with a 1.5/2.5 hours respawn, it should walk in circle around thunderbluff.
http://wowwiki.wikia.com/wiki/Ghost_Howl
http://www.wowhead.com/npc=3056/ghost-howl

**Comment by ImprezaWoW** [comment]
Yes, it does exist, has a 2h45min respawn timer.
