### ISSUE TITLE
Fatal Errors while in Dalaran and WG only

### ISSUE THREAD

**Issue by lildevilre** [dalaranwow/dalaran-wow#3612]
[criterror1.txt](https://github.com/dalaranwow/dalaran-wow/files/384613/criterror1.txt)

i keep getting this crit error report, mostly seems in dalaran with a bit of lag, any help would be appreciated

**Comment by Swork91** [comment]
I got a similar issue and disabling GearScore & Recount resolved it. I would try that and see if it helps.

**Comment by lildevilre** [comment]
Well I have had an issue with my recount and GS. Sometimes they just disappear! UGH idk.

**Comment by sebastienwood** [comment]
Disabled both addons and didnt work yet. Those criticals errors happen everywhere, particularly while RDF.

**Comment by Rushor** [comment]
The bug tracker only lists in-game issues with quests, NPCs and such.

This is definitely an issue on your side (corrupted files most likely) so you should try to re-install the game from scratch.
