### ISSUE TITLE
plz delete

### ISSUE THREAD

**Issue by maxcarey** [dalaranwow/dalaran-wow#3613]

**Comment by robinsch** [comment]
Please post a direct link or quote you statements (1 to 6).

**Comment by maxcarey** [comment]
http://www.mmo-champion.com/threads/670120-Raging-Deathbringer
have a look at the comments and dates from Zint and Venida.
----
http://www.wowhead.com/item=49500/raging-deathbringer#comments
Also see comments from Tahara and Brachamul
----
Also found this out as i was looking for more proof. The proc is also able to be trigger from ranged abilities. Here is a pic of some1 testing this on retail http://i37.tinypic.com/5vd2lw.gif
----
http://www.wowhead.com/spell=69212/shadow-bolt#used-by-item
and finally heres the wowhead page for the proc spell showing no cooldown.
