### ISSUE TITLE
Yulda the Stormspeaker

### ISSUE THREAD

**Issue by ImprezaWoW** [dalaranwow/dalaran-wow#3614]
**Description**:
Yulda the Stormspeaker is located at 24.61, in the bigger house in the west of Valkyrion in Storm Peaks.
**Current behaviour**:
There are 2 Yulda the Stormspeakers in the same area.
**Expected behaviour**: Tell us what should happen instead
There should be only one Yulda the Stormspeaker.
**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**
Yulda the Stormspeaker NPC ID 30046
**Include Screenshots from the issue if necessary**
http://i.imgur.com/wCukG0a.jpg

**Comment by jonanone** [comment]
Removed wrong npc spawn.

This will be applied to the live realm soon.
