### ISSUE TITLE
[Pattern: Fur Lining Fire Resist] NOT DROPPING 

### ISSUE THREAD

**Issue by maxcarey** [dalaranwow/dalaran-wow#3615]
**Description**:
[Pattern: Fur Lining Fire Resist] NOT DROPPING 
**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
currently the recipe is not dropping at all
**Expected behaviour**: Tell us what should happen instead
What should happen is that the Skeletal Runesmith should have a 0.6% chance to drop the recipie. 

**Steps to reproduce the problem**:

1. Include the pattern to the Skeletal Runesmith's loot table
2. Check the rest of the fur lining resist patterns as Ive not yet seen a player with one of them.
3. Also check the drop rate of the other patterns that the Skeletal Runesmith is meant to drop.

**Include proofs for this behaviour**
http://www.wowhead.com/npc=31321/skeletal-runesmith

Ive farmed them for 7 hours and have offered a reward in global for a few days just for some1 to link their leather working with it learned and nothing as yet. So i can say that I am very confident that the pattern is not dropping at all.

**Comment by robinsch** [comment]
https://en.wikipedia.org/wiki/Law_of_large_numbers

This is RNG. Receip is in loot list.
