### ISSUE TITLE
Rogue talent malice not being correct

### ISSUE THREAD

**Issue by NikaFK** [dalaranwow/dalaran-wow#3616]
**Description**:

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
Malice rogue talent is only giving 5% melee crit
**Expected behaviour**: Tell us what should happen instead
It should increase all attacks made by the rogue with 5% meaning it will also affect spell crit but does not for the time being as it is a global critical chance increase
**Steps to reproduce the problem**:

1. have a rogue
2. check spell crit without malice
3. then spec into malice and then inspect spell crit

**Include proofs for this behaviour**
http://wowwiki.wikia.com/wiki/Malice_(rogue_talent)

You can research this on several pages like http://wowhead.com or http://wowwiki.wikia.com or http://www.youtube.com/

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

**Include Screenshots from the issue if necessary**
http://imgur.com/DBxrs2c
http://imgur.com/a/E8ZgH

**Comment by robinsch** [comment]
This is incorrect. Malice is SPELL_AURA_MOD_WEAPON_CRIT_PERCENT. It should only increase melee crit chance.
