### ISSUE TITLE
Hunter's pet

### ISSUE THREAD

**Issue by Illiry** [dalaranwow/dalaran-wow#3618]
**Description**: Hunter Pet

**Current behaviour**: Every time i dismount, pet apears whithout +-20% hp  that he has before mounted.

**Expected behaviour**: To have pet same HP before char mounted & after dismount

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Include proofs for this behaviour**
1) http://imgur.com/a/GVbm7

**Comment by robinsch** [comment]
https://github.com/dalaranwow/dalaran-wow/issues/3088
