### ISSUE TITLE
Two Blacksmithing Quest Bugs

### ISSUE THREAD

**Issue by CowboyBird** [dalaranwow/dalaran-wow#3619]
**Description**:
So I have the same issue for two of my blacksmithing quests. For both: "The Great Silver Deceiver" and "The Art of the Imbue". I have obtained all of the materials I need for the quests but it just won't let me turn them in. This is a huge issue because I have other blacksmithing quests where I need the Plans obtained from these quests to complete them. I also cannot find those items on the Auction House because I presume the quest is bugged for the entire server so no one can make the items. 

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
So I obtain all of the materials I need to complete the quests (Mithril Bars, Iron Bars, and Citrine) and go to turn them into the quest giver out in Stranglethorn Vale and it acknowledges that I have all of the materials needed, but the Complete Quest button doesn't light up and I am unable to click it. 

**Expected behaviour**: Tell us what should happen instead
It is expected that the button would just light up and I can complete the quests.

**Steps to reproduce the problem**:

1.  Obtain the quest
2.  Get all of the materials
3.  Go in to turn the quest

**Comment by PSAlias** [comment]
Try abandoning and retaking the quests a few times, this sometimes happens with all quests that require materials.

**Comment by Golganeth** [comment]
If you have all the materials, abandon and retake it as @PSAlias mentioned. It's a general issue where some items aren't detected in your bags. You will not lose any items by doing this.

Closed
