### ISSUE TITLE
Shaman Spell: Windfury Weapon

### ISSUE THREAD

**Issue by Crispybuilt** [dalaranwow/dalaran-wow#362]
Windfury doesn't share cooldown if the players has enchanted both weapons with Windfury (Main Hand & Off Hand)

It has to share the cooldown, both cannot proc at the same time. There has to be internal cooldown of 2-3 seconds atleast.

WoWhead: http://www.wowhead.com/spell=8232/windfury-weapon#comments

**Comment by klm670** [comment]
Just tested. They share ICD. It won't proc more than once every 3 seconds.

**Comment by Rushor** [comment]
works fine for me
