### ISSUE TITLE
[Priest] Serendipity/Surge of Light talents

### ISSUE THREAD

**Issue by PSAlias** [dalaranwow/dalaran-wow#3620]
**Description**: Surge of Light procs sometimes do not trigger Serendipity.

**Current behaviour**: Spell criticals have a chance to trigger the Surge of Light talent, which causes the next Flash Heal (or Smite) spell cast to be an instant cast. Usually, casting Flash Heal triggers the Serendipity talent, which adds a stacking buff to the caster that reduces the cast time of the next Greater Heal or Prayer of Healing. This includes Flash Heals affected by Surge of Light. However, if the Surge of Light was triggered by a Flash Heal (possibly also Binding Heal, untested), and the Surge of Light proc is used *immediately* to cast another Flash Heal, only the first of these casts will stack Serendipity.

**Expected behaviour**: Serendipity should stack twice in this situation. I suspect that an internal cooldown was recently added to the Serendipity talent in order to fix the issue #1150, in which Binding Heal would stack Serendipity twice per cast instead of once. If this cooldown could be altered to only affect Binding Heal, it would solve the issue.

**Steps to reproduce the problem**:

1. Have talent points in both Surge of Light and Serendipity
2. Cast Flash Heal until a Surge of Light proc is triggered, keeping Serendipity stacks below two
3. Immediately use Surge of Light to cast Flash Heal again, note that this does not add an additional stack of Serendipity

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

Spells:
Binding Heal (IDs: 32546, 48119, 48120)
Surge of Light (IDs: 33150, 33151, 33154)
Serendipity: (IDs: 63730, 63731, 63733, 63734, 63735, 63737)
Flash Heal: (IDs: 2061, 9472, 9473, 9174, 10916, 25233, 25235, 38588, 43431, 48070, 48071, 56331, 66104, 68023, 68025, 71782, 71783)

**Comment by robinsch** [comment]
On PTR.

**Comment by kalvindeane** [comment]
Confirmed working on PTR.
