### ISSUE TITLE
[Quest/NPC] Into the Pit/Hyldsmeet Warbear

### ISSUE THREAD

**Issue by cybergeek94** [dalaranwow/dalaran-wow#3621]
During the quest [Into the Pit](http://www.wowhead.com/quest=12997/into-the-pit), **some** of the [Hyldsmeet Warbear](http://www.wowhead.com/npc=30174/hyldsmeet-warbear) will target and attack the player instead of the [Warbear Matriarch](http://www.wowhead.com/npc=29918/warbear-matriarch) mount. This, obviously, can cause the player to die while mounted.

These NPCs should not damage the player while mounted on the Warbear Matriarch; they should damage the mount. Otherwise, this defeats the purpose of the mount.

I didn't notice I was taking damage until I had aggroed more than one Hyldsmeet Warbear. N.B. they somehow body-pulled; I did not deliberately attack additional mobs. Not every NPC spawned in the pit exhibits this behavior. This may be important in reproducing the problem.

Combat log screenshot:
![](http://i.imgur.com/CgTCyrM.jpg)

**Comment by jonanone** [comment]
Warbears won't attack the players anymore.

This update will be applied soon.
