### ISSUE TITLE
Toc10/25 Lord Jaraxxus - Incinerate flesh damage reduction

### ISSUE THREAD

**Issue by hAkonf** [dalaranwow/dalaran-wow#3622]
**Description**:

**Current behaviour**: Damage reduction persists even after debuff is healed off before the duration ends. No matter how quickly it's healed off, the damage reduction is there for the full duration (15s).

**Expected behaviour**: Damage reduction should be removed when debuff is removed.

**Steps to reproduce the problem**:

1. Be the lucky winner of an incinerate flesh
2. See that damage is reduced while you got debuff
3. See that damage is reduced even after it's healed off.

http://www.wowhead.com/spell=66237/incinerate-flesh

http://wotlk.openwow.com/spell=66237
http://wotlk.openwow.com/spell=67049
http://wotlk.openwow.com/spell=67050
http://wotlk.openwow.com/spell=67051

**Comment by Mike-Hunt** [comment]
Do you have proof of this? I'm looking at logs from Jaraxxus25h this week and cannot see this behavior.
![image](https://cloud.githubusercontent.com/assets/18732159/17275603/e24edbd6-5750-11e6-84b0-30062fac32bb.png)
Katang gets affected by the Incinerate Flesh debuff at 10:53:37.894, and it is healed off 5.791 seconds later at 43.685.
If the damage penalty lasted the full 15s duration, it would have stopped affecting damage at 52.894. As is evident in the snip, there are Mind Flay ticks at 44.137, 44.949, 45.841 (after the debuff is healed off, but before the 15s duration is completed) where Katang is dealing full damage (2860 noncrit/5976 crit = identical to the tick damage before Incinerate Flesh was applied). 
Therefore the debuff is not bugged in this situation in the way you described. Only one of the Mind Flay ticks had reduced damage, and it was within the 5.791 second time frame of the debuff being present before it was healed off.
It might be that the bug you are describing only occurs situationally, I'm not sure how.

**Comment by hAkonf** [comment]
Must've misread my timestamps
