### ISSUE TITLE
Azjol Nerub

### ISSUE THREAD

**Issue by sebastienwood** [dalaranwow/dalaran-wow#3624]
**Description**: 
At Azjol Nerub, normal mode :
- first boss is undoable if the minions before him are engaged (compared to what "normal" difficulty should be)
- Hadronox (2nd boss) : any wipe and the Crushers shall become legion (3 of them are a pain, but each wipe multiply this number by 2). Hadronox may engage (through her grab), but she can run away just after this engage.

**Steps to reproduce the problem**:
1. Go to Azjol Nerub with people which just earned access to Azjol Nerub.
2. Try to do the first boss in the normal way, killing the minions before him
3. Try to do Hadronox, but wipe one or two times

This is a common problem for people actually leveling in this range of level.

**Comment by TeridanDW** [comment]
1-st issue is been worked on in #3280
Regarding 2-nd issue, is this still happening on Algalon?

**Comment by ashido96** [comment]
The encounter follows how it works on retail and resets fully on a wipe. There may or may not be some other things, but duplicating crushers is not one.

**Comment by TeridanDW** [comment]
Thank you @ashido96 , closing this report. If you would like to add something regarding first issue please continue in #3280 .
