### ISSUE TITLE
Balance druid: Starfall and Stealth

### ISSUE THREAD

**Issue by mnbdru** [dalaranwow/dalaran-wow#3625]
**Description**:
Balance druid Starfall puts anyone (rogue, feral druid, shadowmeld) out of stealth at any distance 0-36yards.

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
when ever you use Starfall it automaticly damages sthealth'ed players around you, without any exception. 

**Expected behaviour**: Tell us what should happen instead
Starfall shouldn't damage or put player out of stealth, unless the caster can clearly see the target being close to him in stealth. 

**Steps to reproduce the problem**:

1. Cast starfall
2. Run around like headless chicken
3. Watch all stealth'ed players getting damage

More/better proof may be needed:
https://www.youtube.com/watch?v=pM8OKLJI6BI
http://www.mmo-champion.com/threads/622394-What-s-wrong-with-starfall-breaking-stealth/page3

> "stars would no longer target a stealthed opponent. The AE splash from a star hitting another target will contine to take a stealther out of stealth." direct quote, complete with typo.

> now... I don't know about you but that sounds pretty balanced to other spell. Stars TARGET players in the area to do damage, not cause damage to an area. The AoE affect from it hitting a player hits rogues just like any other AoE spell.

**Comment by robinsch** [comment]
This is wrong. In WOTLK Starfall always did damage to all enemies even if stealthed.

**Comment by robinsch** [comment]
http://truewow.org/forum/viewtopic.php?t=35080
http://www.arenajunkies.com/topic/42265-starfall-taking-players-out-of-stealth/
