### ISSUE TITLE
Death Knight Pestilence on Twin Val'kyr Fight

### ISSUE THREAD

**Issue by Mike-Hunt** [dalaranwow/dalaran-wow#3626]
**Description**: Using Pestilence on the Twin Val'kyr encounter in To(G)C allows Death Knights to benefit from the +50% damage boost of Light/Dark Essence on both targets with his/her disease damage.

**Current behaviour**: 
As an example a Death Knight takes the Dark Essence (+50% damage to Fjola Lightbane and -50% damage to Eydis Darkbane), then applies Frost Fever and/or Blood Plague to Fjola, they will have the +50% boost (as intended). Then when the DK uses pestilence, the Frost Fever and/or Blood Plague that is spread to Eydis will also have the +50% damage boost from Dark Essence (this is not intended, it should be -50%)

**Expected behaviour**: 
In the above scenario, the diseases on the off-target (Eydis) will do -50% damage than normal (resulting in the DK doing roughly 4 times less disease damage to the off-target than they do to the main target, 0.5 x normal damage vs 2 x normal damage).

**Steps to reproduce the problem**:
1. Play a DK 
2. Take Dark Essence, apply diseases to Fjola Lightbane
3. Pestilence and look at damage dealt to Eydis Darkbane

**Include proofs for this behaviour**
World of Logs (retail, 3.3.0a, Gemg has Dark Essence)
![image](https://cloud.githubusercontent.com/assets/18732159/17277984/92752aaa-5793-11e6-97b3-922c5faa42a4.png)
World of Logs (Dalaran, Icespear has Dark Essence)
![image](https://cloud.githubusercontent.com/assets/18732159/17278099/80259d90-5797-11e6-9d00-58024aaf7103.png)

The retail numbers aren't exactly 4 times less on the off-target than the main target, its closer to 3 times and I'm not sure why that is. There's probably a difference due to multiplicative vs additive increases, inconsistent resistance rng, and I didn't track trinket/ring etc procs which adds more variance, but the point remains valid.

This also (directly) impacts Wandering Plague damage on this fight, making the bug quite a significant dps difference.

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**
**55078** Blood Plague
**55095** Frost Fever
**67178** Dark Essence
**67224** Light Essence
**34496** Eydis Darkbane
**34497** Fjola Lightbane

**Comment by robinsch** [comment]
@Lothloryen Please check if this commit is on master
https://github.com/TrinityCore/TrinityCore/commit/52c0fc96bb4a8a62218bd383f360c0e1350ef62a

**Comment by robinsch** [comment]
@Lothloryen This is working fine on PTR as linked https://github.com/dalaranwow/dalaran-wow/issues/3626#issuecomment-237837523. Please port this commit to master.
