### ISSUE TITLE
Quest: Drop It then Rock It!

### ISSUE THREAD

**Issue by Kaara** [dalaranwow/dalaran-wow#363]
Hello, 

http://www.wowhead.com/quest=11429

This quest is bugged. I droped the banner, but the event where i need to defend it doesnt work. No mobs come to attack the banner.

**Comment by Mantigora** [comment]
Quest not working after latest updates. Same issue - even does not starts.

**Comment by Lebaowski** [comment]
Confirmed broken after the update like Mantigora reported, no mobs are spawned after using the banner.

**Comment by martijnhaah** [comment]
confirm. doesnt work.

**Comment by krashan34** [comment]
Still does not work

**Comment by Spydoc** [comment]
Confirmed. It's still not working.

**Comment by belegija** [comment]
no defenders spawn, banner still follows you like a pet, and not able to finish it in any way

**Comment by vdanielpop** [comment]
Confirmed, no defenders spawn.

**Comment by Mantigora** [comment]
Confirmed. Does not work!

**Comment by marsalandrei** [comment]
No mobs spawn. Is this one of those quests that only works after server restart?

**Comment by Golganeth** [comment]
The quest can't be completed right now. The workaround is no longer working because mobs don't spawn at all. Also, when the banner is placed, it follows the player around (it shouldn't move).

**Comment by Lothloryen** [comment]
Hello there,

This quest has been corrected and it is already on the live server.

Thank you.

**Comment by Raulfin** [comment]
not working on KT, placing the banner spawns no defenders and the banner acts like a pet.

**Comment by Edzero** [comment]
Kirin Tor does not receive the same updates as Algalon.

**Comment by Raulfin** [comment]
why is that?
