### ISSUE TITLE
Teleport on frostbite proc

### ISSUE THREAD

**Issue by sebastienwood** [dalaranwow/dalaran-wow#3630]
**Description**: when frostbite procs on a mob that tries to runaway, the mobs is teleported.

**Expected behaviour**: frostbite procs on a mob that tries to runaway shouldnt make him teleport.

**Steps to reproduce the problem**:
1. Have a mage with frostbite talent
2. Attack a mob that tries to runaway (humanoids) (I don't know if it's mandatory for him to have "friends" around)
3. Get the mob low hp (the threshold at which he runs away) with a frost spell that procs frostbite

**Comment by sebastienwood** [comment]
Kinda same problem on Death Knight's Death Grip. When used on a caster mob, the mob glitches and get back to it's original position.

**Comment by Rushor** [comment]
Core/SmartAI: delay SMART_ACTION_FLEE_FOR_ASSIST if creature is rooted/stunned.

* closes https://github.com/dalaranwow/dalaran-wow/issues/3630
* commit: 02a248be7a5f21dde144f680d4890f90345e86c8

**Comment by TeridanDW** [comment]
Works as intended on PTR.

Issue might of been related to #1447.
