### ISSUE TITLE
distance totems

### ISSUE THREAD

**Issue by fixlol** [dalaranwow/dalaran-wow#3631]
hi, I have seen on this server bug on a shaman totems, when the shaman places the 4 totems they are too close together, almost attaccati.non know if it's a bug, but it is very annoying because you can hardly distinguish between them .
this is a picture of the correct placement of the totems:
http://imgur.com/a/aPqy9
http://imgur.com/a/glFDo

I can even wrong, but I'm sure you are very close to each other, if you can control and give me an answer? thank you

I did the screen: this is the totem distance in our server:
http://imgur.com/a/BTCyt
http://imgur.com/a/VKZJi

**Comment by robinsch** [comment]
On PTR.

**Comment by fixlol** [comment]
what it means on ptr? we are resolving it?

**Comment by robinsch** [comment]
On PTR means a fix has been applied on the test realm.

**Comment by robinsch** [comment]
Tested.

**Comment by TeridanDW** [comment]
Works as intended on ptr.
