### ISSUE TITLE
Kyle's Gone Missing mulgore quest bugged

### ISSUE THREAD

**Issue by yooper2211** [dalaranwow/dalaran-wow#3632]
**Description**: I killed over 50 plainstriders and no one has loot for this queest

**Current behaviour**: No quest item loot

**Expected behaviour**: There should be item when i slain plainstrider

**Comment by Raltharan** [comment]
Can confirm quest bugs after using the meat once without Kyle around. Quest item is unobtainable even after abandoning and retaking quest.

Steps to reproduce the problem:
1. Use the item Tender Plainstrider meat (without Kyle around)
2. Kill Plainstriders to obtain the quest item again
3. Notice it doesn't drop anymore - abandon quest, retake, try again.
Quest item does not drop

**Comment by yooper2211** [comment]
Kyle wont eat meat, one more bug, i finally found meat after getting lvl 11 in mulgore ?!?!?! he jus run by meat, wont even take a look at it

**Comment by jonanone** [comment]
Loot chance has been increased to 30% (It was only 10, so now the quest item will appear more often)
In order to Kyle eat the meat you have to be near him. That part seems to be working ok.

This update will  be applied to the live realm soon.
