### ISSUE TITLE
[Item] Burning Essence

### ISSUE THREAD

**Issue by DalaranLantri** [dalaranwow/dalaran-wow#3633]
**Description**:
Burning Essence is an item required for the +20 fire resistance enchant on head or legs.
**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
Burning Essence is not dropping from the Dark Coffer
**Expected behaviour**: Tell us what should happen instead
Burning Essence has a chance to drop 1 or 2 times from the Dark Coffer.
**Steps to reproduce the problem**:

1. Obtain the Dark Keeper Key from any of the Darkkeepers.
2. Open the Dark Coffer 
3. Never get any burning essences

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**
http://www.wowhead.com/object=160845/dark-coffer
http://www.wowhead.com/item=11751/burning-essence
http://www.wowhead.com/item=11197/dark-keeper-key

**Comment by jonanone** [comment]
Burning Essences will now be dropped from the Dark Coffer.

This update will be applied soon.

**Comment by Edzero** [comment]
Working on PTR.

**Comment by bojan112** [comment]
what about other 2 items that come from that coffer, eye of kajal and black blood of the tormented

**Comment by Rushor** [comment]
could you post the itemids ot it?

**Comment by Rushor** [comment]
Edit: Tested it on PTR and yes that works fine too.

![GitHub Logo](http://i.imgur.com/wrpSw07.jpg)

**Comment by TeridanDW** [comment]
Works as intented on ptr.
