### ISSUE TITLE
[Item] Siegebreaker Plate 4-set non-functional/tooltip broken

### ISSUE THREAD

**Issue by cybergeek94** [dalaranwow/dalaran-wow#3634]
If you view the in-game tooltip for [the Siegebreaker Plate set](http://www.wowhead.com/item-set=831/siegebreaker-plate) (T8 Prot Warrior):

![](http://i.imgur.com/zX0XoS9.jpg)

You'll see that the 4-set bonus doesn't actually display a number. According to some group-members, the bonus doesn't actually do anything either, so it may not be implemented at all. 

[According to WoWHead](http://www.wowhead.com/spell=64936/item-warrior-t8-protection-4p-bonus), this set bonus should provide a 20% reduction to magical damage taken while using Shield Block.

**Comment by robinsch** [comment]
This is just a visual bug. It's working fine.
