### ISSUE TITLE
Deviate Hides

### ISSUE THREAD

**Issue by ImprezaWoW** [dalaranwow/dalaran-wow#3635]
**Description**:
The quest Deviate Hides is a quest available once you hit level 13, and has no prerequisite quests.
**Current behaviour**: 
The quest Deviate Hides can only be picked up by Horde players who are level 13 and over.
**Expected behaviour**: 
The quest Deviate Hides should be available to both Horde and Alliance players who are level 13 and over.
**Steps to reproduce the problem**:

1.  Go to the cave above Wailing Caverns as Alliance, and go to the same place as Horde;
2.  Only one faction will be able to pick up the quest.
**Include proofs for this behaviour**

http://db.vanillagaming.org/?quest=1486#comments:id=929044
http://www.wowhead.com/quest=1486/deviate-hides#comments - plenty of comments here in patch 3.3.0 and lower which mention Alliance side doing the quest. 
**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**
[Deviate Hides](http://wowwiki.wikia.com/wiki/Quest:Deviate_Hides) Quest ID 1486

**Comment by jonanone** [comment]
This quest is now also available for the alliance.

This update will be applied to the live realm soon.
