### ISSUE TITLE
Server Auto Ban Issue

### ISSUE THREAD

**Issue by Ryladen** [dalaranwow/dalaran-wow#3636]
**Description**: I was complaining about that goldselling website and got banned.

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who) 07:13 gmt +2 05.08.2016 algalon realm, A stupid druid pm'ed me. ***games.com gold selling buy bla bla bla. I clicked report spam, and then tried to ask global if I could ignore anything that included the name. bam. I got banned. Twice(with my other account too)

**Expected behaviour**: Maybe auto ban could be a little more specific so that people who do not advertise wouldn't get banned.

**Steps to reproduce the problem**:

1. type that website to global
2. wait 0.1 sec
3. banned

Listen. I've donated a lot of times for this server and I know people do so too. Why have I got banned just for complaining about a stupid gold selling website? I couldn't believe my eyes! Please atleast unban me and my friends account we both got banned.

**Comment by Lothloryen** [comment]
Write an e-mail to dalaran.community@gmail.com and we will help you. Not a bug tracker matter.

**Comment by Ryladen** [comment]
I apologise, thank you for responding

**Comment by Randomi** [comment]
3 days since i wrote to you and nobody responded me yet.
