### ISSUE TITLE
[Quest][Northrend] There Exists No Honor Among Birds

### ISSUE THREAD

**Issue by Kaara** [dalaranwow/dalaran-wow#364]
Hello,

http://www.wowhead.com/quest=11470

This quest is bugged. I have summoned the hawk but i cannot fly with him, nor pick the eggs, he has only 1 ability on his action bar called Attack.

**Comment by belegija** [comment]
At this point:
- Still cannot fly
- Still eggs wont despawn after being looted

**Comment by Rushor** [comment]
6f2525f51aaf3ae95db28aa9b1225a5274bb2a10
- eggs will despawn afrer beeing looted
- bird can fly now

**Comment by MalkaviaDW** [comment]
- Eggs can be looted multiple times. Didn't see them to despawn.

**Comment by Pentex11** [comment]
Standing next to the eggs and using the spell does nothing.

**Comment by Rushor** [comment]
Scripts/Spells: Scriptsupport for despawn of eggs for quest: There Exists No Honor Among Birds

* closes https://github.com/dalaranwow/dalaran-wow/issues/364
* egg will despawn after collection for 120 seconds
* commit: 580764a77a0882ef05b36410dfc452c798005d06
