### ISSUE TITLE
Suspended

### ISSUE THREAD

**Issue by ylob** [dalaranwow/dalaran-wow#3641]
Hello, so my account got suspended because i was been asking for someone from "gold selling site" to help me but i got suspended. I know this is not place where should i put this info but i cant type anything in forum because i dont have main character and i cant change him (idk how) SO please unban me because it is not my fault, my char name Viliam

**Comment by ImprezaWoW** [comment]
This is the in-game bug tracker. Regarding your issue please contact us at dalaran.community@gmail.com
