### ISSUE TITLE
wrong info about heirlooms

### ISSUE THREAD

**Issue by Gemiirki** [dalaranwow/dalaran-wow#3643]
**Description**: heirlooms 

**Current behaviour**: Well i buyed an ring there is unique, but not then i hold on it on denate buy its says nothing about its unique, so i just buyed 2

**Steps to reproduce the problem**:

1.  well i can send the orther back to ya and gets my donate point back

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

**Include Screenshots from the issue if necessary**

![wtf](https://cloud.githubusercontent.com/assets/20961108/17578774/ca8de7b8-5f8d-11e6-845f-5b8b74f42390.png)

Its might be me there did misunderstod something

**Comment by robinsch** [comment]
This is the ingame bugtracker. Please take this one to the support forums.

**Comment by Gemiirki** [comment]
In order to create a forum thread, you must have created a character in game and select him as you main character on the website

**Comment by robinsch** [comment]
Create a character on Kirin Tor.

**Comment by Gemiirki** [comment]
ok ty

**Comment by Lukas45** [comment]
This is actually an error on OpenWoWs part (http://wotlk.openwow.com/item=50255), where it draws the tooltips from
