### ISSUE TITLE
cant see my charater in account log in on website

### ISSUE THREAD

**Issue by Gemiirki** [dalaranwow/dalaran-wow#3644]
**Description**: i just don't got any char on my account log on the website.

**Current behaviour**: I tryed going supporting for something i did wrong about my char, think i did delete the main char not sure so like to change it

**Expected behaviour**: It shuold show me, my priest Gemzi
![bug](https://cloud.githubusercontent.com/assets/20961108/17585768/e534e546-5fbd-11e6-850e-96d5520735bb.png) 
![bug 2](https://cloud.githubusercontent.com/assets/20961108/17585870/8ffc82c2-5fbe-11e6-9658-4d775fd1b284.png)

**Include Screenshots from the issue if necessary**

**Comment by robinsch** [comment]
This is the ingame bugtracker. This belogs to the forums.

**Comment by Gemiirki** [comment]
In order to create a forum thread, you must have created a character in game and select him as you main character on the website

**Comment by Gemiirki** [comment]
my warrior was on same server it did show it
