### ISSUE TITLE
Quest - A Cleansing Light

### ISSUE THREAD

**Issue by jesflow97** [dalaranwow/dalaran-wow#3646]
**Description**: The quest is not at the npc. 

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)

**Expected behaviour**: Tell us what should happen instead

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Include proofs for this behaviour**

You can research this on several pages like http://wowhead.com or http://wowwiki.wikia.com or http://www.youtube.com/

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

You can research this on several pages like http://wotlk.openwow.com or http://wowhead.com/

**Include Screenshots from the issue if necessary**

**Comment by Golganeth** [comment]
The quest shows up properly as long as you meet the requirements. The quest will swap to [Fel Armaments](http://wotlk.openwow.com/quest=10421) (repeatable) once completed.

Closed
