### ISSUE TITLE
Sunwell bosses

### ISSUE THREAD

**Issue by jesflow97** [dalaranwow/dalaran-wow#3647]
**Description**:
Felmyst and kil'jaeden

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
Felmyst is bugging out after 30 sec. kil'jaeden dosnt respawn if wipe.

**Expected behaviour**: Tell us what should happen instead

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Include proofs for this behaviour**

You can research this on several pages like http://wowhead.com or http://wowwiki.wikia.com or http://www.youtube.com/

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

You can research this on several pages like http://wotlk.openwow.com or http://wowhead.com/

**Include Screenshots from the issue if necessary**

**Comment by Golganeth** [comment]
Merge #3574
