### ISSUE TITLE
UH Ghoul energy problem

### ISSUE THREAD

**Issue by Johanes022** [dalaranwow/dalaran-wow#3648]
**Description**:While having Claw on autocast unholy ghoul should have minimum 40 enegry allowing player to use Gnaw.

**Current behaviour**: While Claw is on autocast ghoul runs out of energy (energy goes down to 0 ) not allowing player to use Gnaw ability, and if you are lucky you might be able to use Gnaw before ghoul wastes energy on claw.
[This is how it currently works on Dalaran wow](https://www.youtube.com/watch?v=XJBSBquIR_c)

**Expected behaviour**: While Claw ability is on autocast ghoul should keep at least 40 enery allowing player to use Gnaw.
[This is how it works on other private server](https://www.youtube.com/watch?v=IzVnbno1_z4)

**Steps to reproduce the problem**:
1. Turn Claw on auto attack and watch

**Include proofs for this behaviour**
- https://youtu.be/BYK6OkFwbv8?t=221
- https://youtu.be/-3lphQWHEto?t=68
- https://youtu.be/Cp3nIhf2tfk?t=284

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**
[Claw](http://wotlk.openwow.com/spell=62225)
[Gnaw](http://wotlk.openwow.com/spell=47481)

**Comment by Golganeth** [comment]
#1959
