### ISSUE TITLE
Rune of the Fallen Crusader low ppm rate

### ISSUE THREAD

**Issue by Johanes022** [dalaranwow/dalaran-wow#3649]
**Description**:
Patch 3.1.0 (14-Apr-2009): Strength bonus reduced to 15%. Chance to proc **_doubled_**.

**Current behaviour**: 
Ive downloaded addon Procodile and left my character to autoattack training dummy for ~20min
During that time Rune of the Fallen Crusader proced 13 times wich makes ppm less then 1 (0.63%)
I used [Relentless Gladiator's Greatsword](http://wotlk.openwow.com/item=42334) for testing

**Expected behaviour**: 
Rune of the Fallen Crusader proc rate should be 2 ppm

**Steps to reproduce the problem**:
1. Download addon that can track ppm of items/spells like Procodile
2. Start autoattacking training dummy and leave it for some time
3. See results

**Include proofs for this behaviour**
- Screenshot of test ive made on Dalaran-wow
<img src="http://image.prntscr.com/image/045ae1181d124d16812c63ca9b61beb2.jpeg"><img>
- [Screenshot](http://image.prntscr.com/image/ce65b8be9092489cb4a9083cc4263796.jpeg) of google search (i couldnt find the text showing on wowhead)
- Wowwiki 3.1.0 patch changes states that proc chance doubled while strentgh bonus reduced to 15%
http://wowwiki.wikia.com/wiki/Rune_of_the_Fallen_Crusader

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**
[Rune of the Fallen Crusader](http://wotlk.openwow.com/spell=53344)

**Comment by robinsch** [comment]
On PTR.

**Comment by robinsch** [comment]
Fix confirmed on PTR.

**Comment by Johanes022** [comment]
Report was closed and added to update list 15days.PPM is still the same.I asume it hasnt been applied to live yet, but some of the reports like https://github.com/dalaranwow/dalaran-wow/issues/1992 have been applied already.

**Comment by TeridanDW** [comment]
Did some testing for this issue on the ptr, after 15 mins spamming blood strike and plague strike (with 8%+ hit and 33 expertise) on Shadron, these are the results:
![image](https://cloud.githubusercontent.com/assets/6797611/24560314/ea28d15e-164a-11e7-99f2-c7b5b11dbd3e.png)

Now, it might be a bit too many procs, also noticed a proc can happen within the duration of a proc, not sure if it intended.

**Comment by Edzero** [comment]
The amount of procs you get will depend on your weapon speed and talents.

It should work on a base PPM of 2 which means your weapon swing speed / (60/2) = proc rate.

A 3.6 base speed weapon (not actual weapon speed) will give an average of 12% proc chance per hit. When taking buffs such as Heroism/Bloodlust, Icy Talons, Improved Icy Talons, Unholy Presence and Speed (from Potion of Speed) the *actual* proc rate will be higher than 2 per minute.

As far as I am aware, there is not meant to be an internal cooldown on this proc so having a proc occur within the duration of a proc is correct - it should simply perform the heal and refresh the duration of the buff.

To give an example, with a 3.6 base speed weapon with Icy Talons, Improved Icy Talons and Unholy Presence, the actual weapon speed will be 2.07. Giving 28 (rounded down) swings per minute each with a proc rate of 12% = average PPM of 3.36.

**Comment by Edzero** [comment]
I tried using the same add-on which you are using @TeridanDW but I found an issue with it (at least on my end). When the buff procs twice within 15 seconds and refreshes it, Procodile is not counting the second proc, so it is giving inaccurate results. Perhaps this is some difference in settings or configurations but I feel it is worth noting. For my testing I've just used /combatlog and parsed it to check for procs to be sure.

3.6 speed no buffs/specials, 52 procs in 30 minutes making it an average proc rate of 1.73 every minute. It should be 2 every minute. It's off by ~13.5% 

Same 3.6 speed but with haste making it 2.48, 86 procs in 30 minutes making it an average proc rate of 2.86 every minute. It should be 2.9 every minute. It's off by ~1.3%.

Assuming the first test was poor RNG it seems to be working as intended.  To be sure I will perform one more test with the 3.6 weapon as well as some tests when dual wielding. This will be done later and I'll update this comment when complete.

As a side note, Procodile was showing a 5 second internal cooldown for this. I think this is actually correct from my memory but I don't have proof either way. If that is how it is currently configured it should be left at that value, and if it has no ICD then that is also fine for now.

**Comment by robinsch** [comment]
Waiting for PTR update.

**Comment by TeridanDW** [comment]
Hello, after few tests on PTR this seems to work as intended.
However I would like a second opinion by our new tester.

![wowscrnshot_101917_111255](https://user-images.githubusercontent.com/6797611/31760925-fe65b066-b4be-11e7-92c4-2e90ef30a5db.jpg)

~ 10 mins long fight.

**Comment by AttendantTock** [comment]
Hello,

Since Procodile doesn't seem reliable with chained procs (I had 5 procs in 7 auto attacks! And many times 2-3 in a row), I tested with a simple /cancel aura /cast Howling Blast to keep track.

Two 15min runs:

With a 3.6 speed weapon hasted to 1.58s, I had 84 procs, or **5.6 ppm** average.
With those base speed / haste settings, the expected ppm would be:
(3.6 / (60 / 2) * (60 / 1.58) = **4.56 ppm**
The results seem generous for this run, but acceptable. I had some insane proccing streaks I admit :)
![capture d ecran 2017-10-22 a 15 00 28](https://user-images.githubusercontent.com/29557022/31862879-8ee1609c-b73d-11e7-9675-3b7b3f5e937d.png)


With a 3.6 speed weapon hasted to 2.86s, I had 37 procs, or **2.47 ppm** average.
With those base speed / haste settings, the expected ppm would be:
(3.6 / (60 / 2) * (60 / 2.86) = **2.52 ppm**
Now the results are a bit below average but much closer to the expected value. No insane lucky chains of procs this time...
![capture d ecran 2017-10-22 a 15 24 15](https://user-images.githubusercontent.com/29557022/31862881-94433f92-b73d-11e7-9136-9fea64e155a7.png)

I conclude that the PPM seems fine on PTR.
