### ISSUE TITLE
[Quest][Outlands][Mag'har faction]More Warbeads!

### ISSUE THREAD

**Issue by Randomi** [dalaranwow/dalaran-wow#3650]
Hello, the repeatable quest for grinding Mag'har reputation should give 500 rep per turn in, which is not the case since it gives 250 rep atm. It seems there is an identical issue for the alliance counterpart, the Kurenai faction. ( https://github.com/dalaranwow/dalaran-wow/issues/1373 ) It's a minor issue, ofc, but it still doubles the time needed to get exalted with Mag'har/Kurenai.

Every video on youtube and wow database can confirm this.

**Comment by Rushor** [comment]
duplicate https://github.com/dalaranwow/dalaran-wow/issues/3837
