### ISSUE TITLE
Quest] Kaw the Mammoth Destroyer 

### ISSUE THREAD

**Issue by Varith123** [dalaranwow/dalaran-wow#3651]
When i try to do this quest http://www.wowhead.com/quest=11879/kaw-the-mammoth-destroyer, Moria spawns as it should but kaw himself is somewhere below ground, can be found with track humanoids or just /tar kaw.

**Comment by Golganeth** [comment]
Fixed in-game. Some NPCs may rarely drop below the ground. Feel free to make an in-game ticket should you encounter any similar issue in the future.

Closing since the quest itself works fine.
