### ISSUE TITLE
GM services help Ingame

### ISSUE THREAD

**Issue by Gemiirki** [dalaranwow/dalaran-wow#3653]
Well its easyere to just do it in this way, i have tryed for some time now to get pass for contacting an GM ingame, Off game, here And tryed to chect postet on the website, i really want to know how to get to a GM about the ingame stuff so i can being survices for i am going to being little tide of donation to a game i dont get any help then i have a problem so i just wanna know how to get any contact to an GM there can handle problems ingame.

**Comment by Golganeth** [comment]
You can make an in-game ticket or send us an e-mail to: dalaran.community@gmail.com - Only send an e-mail if your problem is regarding donation issues, password recovery and such.

This is the bug tracker for in-game issues.

Closed
