### ISSUE TITLE
World Defense Channel

### ISSUE THREAD

**Issue by Klala** [dalaranwow/dalaran-wow#3654]
**Description**: World Defense Channel isn't working properly

**Current behaviour**: World Defense Channel or (WDC for short) doesn't work correctly atm. While it does occasionally warn you about certain pvp events (for example winterspring fields) usually it functions just like the regular defense channel.
**Expected behaviour**: WDC should warn you about ALL the PvP events that happens EVERYWHERE in the world. Yes, this might spam you but this is the reason you are not joined to that channel by default.

**Steps to reproduce the problem**:
1.  type /Join WorldDefense and press enter
2. Wait for either faction to attack any opposite faction (NPCs not players) or just capture a place (like the hellfire overlook or halaa or the barrens crossroads or southshore.
3. Notice that you are not getting warned for those events while you are not in the actual zone. You should be warned even in an instance that southshore for example is under attack.

I've been in the WDC for weeks now and haven't seen any warning about other places being attacked. Even in days where people called for help against a horde invasion to ironforge.
This channel is helpful for people who would like to do pvp quests such as hellfire daily pvp or eastern plaguelands tower control.

**Proof:** https://www.youtube.com/watch?v=ZJGvm11sBqg

**Comment by Aridam** [comment]
Confirmed.

**Comment by Aridam** [comment]
This seems to have gone unnoticed -- currently World Defense is indeed broken in that it does _not_ report anything _unless_ you're within the same-exact Zone, which is what Local Defense is for anyway; it's not doing what it should be as described in detail by the original poster of this issue.

**Comment by Aridam** [comment]
Still broken as before on Live.

**Comment by robinsch** [comment]
@Lothloryen

**Comment by maciejpk** [comment]
as of 2020-10-10, still broken. This is troublesome during city bosses
