### ISSUE TITLE
[Quests][Northrend] General Cerulean in untargetable location

### ISSUE THREAD

**Issue by Haleorn** [dalaranwow/dalaran-wow#3658]
**Description**:

Mob General Cerulean sits under his platform (where the ground underneath the platform object is, I guess) rather than on top of it, so is unable to be targetted. Doesn't seem to be able to be hit by AoE to lure him out either. Being unable to kill him means you can't obtain item 35669 (Energy Core) and so causes the main Coldarra quest chain to break at [71] The Cell. 

**Current behaviour**: 

Sits in an untargettable spot underneath his platform.

**Expected behaviour**:

Should sit on top of his platform like the animated pinata he is, ready to crack open for quest candy.

**Include proofs for this behaviour**

http://imgur.com/a/Jwhwe

**Comment by Golganeth** [comment]
Fixed in-game. General and rare pathfinding issue with some NPCs. Feel free to make an in-game ticket should you encounter a similar issue again in the future

Closing since the related quest works and the default NPC position is correct.
