### ISSUE TITLE
Cant log in

### ISSUE THREAD

**Issue by ExtremeL0rd** [dalaranwow/dalaran-wow#3660]
Hi yesterday i have experienced problem with logging in,when i enter username and password it says Conecting,then i waited but nothing happens i tried to relaunch game,to restart pc and everything but 
nothing helped,and then it says that i have problem with my internet connection but internet its alright 
![wowscrnshot_081616_184808](https://cloud.githubusercontent.com/assets/21064153/17707915/df817db6-63e2-11e6-9a2d-fee746639da5.jpg)
![wowscrnshot_081616_185414](https://cloud.githubusercontent.com/assets/21064153/17707922/e6e2bd72-63e2-11e6-99b2-d8ac693cb6b4.jpg)

**Comment by Golganeth** [comment]
This is the wrong place for your matter, the bugtracker lists in-game issues (regarding quests, NPCs..) that require a fix.

The servers are fine, so make sure that your realmlist is correct: **set realmlist logon.dalaran-realmlist.org**

If the advice above didn't help, make also sure you're using the correct client and try contacting your ISP, they could be having issues. 

Closed.
