### ISSUE TITLE
Intervene get rogues out of stealth

### ISSUE THREAD

**Issue by InshadowsAlgalon** [dalaranwow/dalaran-wow#3662]
**Description**:
Intervene get rogues out of stealth in any range, without rogue being in combat, nothing. It just straight up destealths the rogue.
**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
When enemy warrior Intervenes other enemy, and friendly rogue is in stealth, it unstealths the rogue. Happens mostly in bgs to me, i think same will be happening in arenas. It is almost impossible for rogue to play here. Random entering in combat when no enemy is around, mookins Starfall hits rogues in stealth, and now Intervene get them unstealthed without a reason. Please fix it.
**Expected behaviour**: Tell us what should happen instead
Nothing should happen, rogue should continue to be in stealth, unless he attacks.

**Steps to reproduce the problem**:
1. Make warrior Intervene someone in BG ( Allhazred, alliance warrior, uses this bug to the fullest)
2. Get unstealthed
3. Get totally screwed

**Include proofs for this behaviour**
No pic now, just get into bg and see it, really easy to reproduce. http://www.wowhead.com/spell=3411/intervene
Says nothing about getting ppl out of stealth.
You can research this on several pages like http://wowhead.com or http://wowwiki.wikia.com or http://www.youtube.com/
Issues without proofs will be closed and tag On Hold will be added until the proof is provided.

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**
3411 i guess thats the ID
You can research this on several pages like http://wotlk.openwow.com or http://wowhead.com/

**Include Screenshots from the issue if necessary**

**Comment by kalvindeane** [comment]
As far as I am aware, Starfall is meant to affect stealthed players in this patch.

**Comment by robinsch** [comment]
@kalvindeane Has nothing to do with this report. If you find sources on this for 3.3.5 (only video source!) then feel free to open a issue.

**Comment by robinsch** [comment]
@Lothloryen Works fine on PTR.

**Comment by kalvindeane** [comment]
The OP said "mookins Starfall hits rogues in stealth" which is what I was reacting to. :)

**Comment by szattara** [comment]
bump

**Comment by szattara** [comment]
gamemaster ingame told me to bump this post so that's why i did,
looks like my last post was removed

**Comment by robinsch** [comment]
This is working on PTR - I can't help with that. We have to wait for @Lothloryen

**Comment by szattara** [comment]
y thats what the gm told me, it was working but not yet been applied. oooooh mighty lothloryen creator off our azaroth pls apply this and i will sacrifice 10gnomes

**Comment by robinsch** [comment]
@szattara You might explain it abit more? I thought Intervene removed a friendly rogues stealth on hit?

**Comment by robinsch** [comment]
@Lothloryen Still can't confirm.

**Comment by kalvindeane** [comment]
@Robinsch From what I've been told by some warriors in-game, Intervene is removing stealth on enemies within X range.

**Comment by szattara** [comment]
it removes players from stealth and put them in combat ( ferals,rogue's)
i don't know about the range, all i know is that a Orc warr can intervene at lets say blood elf tower in Eots and i(nelf druid) pop out of stealth while i'm at Mage Tower.

**Comment by InshadowsAlgalon** [comment]
Range of getting out of stealth is huge, like really huge, maybe infinite. Considering stealth is one of rogue's main mechanics, i just dont understand how it is not fixed yet. More and more warriors know this bug, and will constantly intervene a friendly target just to get rogues out of stealth. What about rated matches-arenas, u get awards for that, and as a rogue u cant do anything. Half of the time u get intervened out, other half-u spend 10 sec behind the pillar to re-stealth, but u can not cause the combat bug xD Very Fun Happy Times...

**Comment by robinsch** [comment]
This is working on Algalon PTR. There is nothing I can do about this @Lothloryen seems to be very busy lately.

**Comment by robinsch** [comment]
My bad. Was broken on our branch too. Fix on PTR.

**Comment by robinsch** [comment]
@Lothloryen Already tested can be applied on live.

**Comment by Lothloryen** [comment]
Thank you @robinsch , already applied on live.
