### ISSUE TITLE
Can't post threads on forum.

### ISSUE THREAD

**Issue by Bjrklund** [dalaranwow/dalaran-wow#3663]
Hi.
My name is Chris and I have a problem with the dalaran-wow website. I tried post a thread there yesterday about this guild I am about to start and today but I tried again, got the same result. I think I have also send a mail to your dalaran mail aswell, but I haven't got any response so I try it here aswell.
So about the thread. I was about to post a thread on the forums at dalaran-wow. When i was finished with all the writing I pressed submit and BAM! There it was "You've been blocked". So apperently the DDoS or CloudFlare or whatever services you're using to protect the website from people posting advertisment has also made the system to think that I am an advertisment person aswell or something. I hope by creating this bugtracker/issue/problem I have I hope that the staff of dalaran may be able to solve it. 
The ID for the problem is this: CloudFlare Ray ID: 2d387c3465f036ea

Kind regards
Chris

**Comment by kalvindeane** [comment]
Happens a lot. There is probably a word or phrase in your post that is being blocked.

Sometimes the phrases they block don't make any sense to block.

**Comment by Bjrklund** [comment]
Yeah. I manage to post by cutting the whole post up into four pieces so it's all good ^^
