### ISSUE TITLE
Hunter problems

### ISSUE THREAD

**Issue by AurexXx** [dalaranwow/dalaran-wow#3665]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (OLD - ... tags should no longer be used)
[//]: # (Priority - ... tags are assigned by team members)

**Description**: I have few problems with my hunter.
1. When I ssummon my pet, or just dismount or do somthing similar that makes my pet reapear it allways have only half of his HP no mater the pet I choose.
2. Multi shot no longer regenerates mana from every hit.
**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)

**Expected behaviour**: Tell us what should happen instead

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Include proofs for this behaviour**

You can research this on several pages like http://wowhead.com or http://wowwiki.wikia.com or http://www.youtube.com/
Issues without proofs will be closed and tag On Hold will be added until the proof is provided.

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

You can research this on several pages like http://wotlk.openwow.com or http://wowhead.com/

**Include Screenshots from the issue if necessary**

**Comment by robinsch** [comment]
On PTR.

**Comment by robinsch** [comment]
Fix confirmed on PTR.

**Comment by Edzero** [comment]
Pets now appear with the correct amount of hp (if a pet is missing hp when dismissed, it will still be missing  that amount of hp when called again, this is intentional).

Multi-shot now grants mana for each hit whilst using Aspect of the Viper.
