### ISSUE TITLE
Account is locked.

### ISSUE THREAD

**Issue by serbian7** [dalaranwow/dalaran-wow#3666]
Every time i try to log in into my old account i get the following message : " You have applied a lock to your account. You can change your locked status by calling your account lock phone number". 
I havent played for a while here and I wish to get back to it but due to this I cant. 
I'll add the picture as well.
![wowscrnshot_081716_151343](https://cloud.githubusercontent.com/assets/21082103/17737444/74545bb6-648d-11e6-8128-674ce111cbca.jpg)

**Comment by Morens-D** [comment]
Greetings serbian7!

Bug tracker is only for in-game issues.
Write an e-mail to dalaran.community@gmail.com and we will try to help you.

**Comment by serbian7** [comment]
Alright thanks!
