### ISSUE TITLE
Absorption Effects

### ISSUE THREAD

**Issue by lizardman67** [dalaranwow/dalaran-wow#3667]
Description:Absorption Effects

**Current behaviour**: Currently any sort of absorption shield effect prevents  interupting player  when capping flags in battlegrounds 

**Expected behaviour**: Capping should be interupted whenever any direct damage strikes the player. No matter if he has some shield or not. 

**Steps to reproduce the problem**:
1. Use any sort oh shield and try to cap the flag 
2. Use any direct dmg on capping player.
3. Capping  wont be interupted

**Include proofs for this behaviour**
Not much of proof but its discused in this topic on wowhead.
http://www.wowhead.com/forums&topic=153563/disc-priest-pvp-how-to-interrupt-a-flag-capper

**Comment by robinsch** [comment]
This works fine on PTR. @Lothloryen

**Comment by AgeAgainst** [comment]
25 days ago this was working fine on the PTR.  Still broken on Algalon, people still abusing this bug to cap nodes in AB and cap flags in both WSG & EoTS.  

Can we get this fix pushed to live?

**Comment by Lothloryen** [comment]
Hello there,

It should be fine now.
