### ISSUE TITLE
Krik'thir the Gatewatcher encounter in Azjol-Nerub!

### ISSUE THREAD

**Issue by Nikvet** [dalaranwow/dalaran-wow#3668]
Npc : http://www.wowhead.com/npc=28684/krikthir-the-gatewatcher
Description: Krik'thir the Gatewatcher encounter is not scripted as it should be. The way it's scripted right now makes impossible to succeed. ( I'm tanking on normal difficulty and we're always wiping. )

Right now, when the waves are engaging, after the first wave is engaged, there are seconds (around 30 I think) before the next wave is engaging, save goes for wave 3 and the boss himself. 
How it should be: After the first wave is pulled, the next wave is supposed to engage 6-7 seconds after the first wave adds are killed, same goes for wave 3. When the wave 3 adds are dead there should be 13-14 sec before the boss engages the group.
Also when the boss is yelling for sending the groups, he's yelling 4-5 seconds before they begin to engage on the group. ( Watch the second video )

**Steps to reproduce the problem**:

1. Enter Azjol-Nerub.
2. Go where the first boss encounter is.
3. Start the encounter by pulling the left side adds.

I've watched several videos in Youtube:
https://www.youtube.com/watch?v=uIKfsbvu7QE
https://www.youtube.com/watch?v=-ZOvkzvqZoc

**Comment by sebastienwood** [comment]
Issue #3624

**Comment by Golganeth** [comment]
Merge #3624
