### ISSUE TITLE
Dungeon.

### ISSUE THREAD

**Issue by Bjrklund** [dalaranwow/dalaran-wow#3669]
I was doing Auchindoun ShadowLabs on normal mode. I encounter the first boss Blackheart the Inciter, I defeat him. In this fight with him he uses an ability called **INCITE CHAOS**; 
_"Full party mind control. The party will go free for all, and start randomly killing each other. He will not take part in this fight. Lasts approx 15 seconds. Dumps aggro. The first one is cast about 20 seconds in the fight, then again approximately every 40 seconds during the whole fight"_. 
So after I was done defeating him I move along down the corridor that you're suppose to follow. And here's the issue, when reaching the corner of that corridor, my toon instantly auto turns and runs back towards where Blackheart was defeated. I loose all controll over my toon, I can turn him, I can't stop him, I can't use any ability what so ever. My question is this a bug, cause then I would appriciate if it got fixed so I can finish this instance properly.

Kind Regards.
//Chris.

**Comment by Golganeth** [comment]
Duplicate #1451

After being affected by an NPC mind control, your character may get teleported back to the spot where it got mind controlled. Using spells such as Charge will also cause this until player relogs.

Make a quick relog and it should be fine.

**Comment by Bjrklund** [comment]
And you are sure that If I relog I won't be thrown out of the dungeon?
Thanks for the reply btw.
//Chris
