### ISSUE TITLE
Referal-friend bug

### ISSUE THREAD

**Issue by nikolaipka** [dalaranwow/dalaran-wow#3671]
On Friday night server vrashed and since then i don't get exp bonus from a friend referal. I submitted ticket and nothing. First of all when i registered here 2-3 weeks ago i didn't get connected with the player who send me refferal. Again nothing from GM support. So i made second account to support myself and now I don't get bonus again, while my support char get the bonus.

account: nikolaipka

**Comment by ImprezaWoW** [comment]
Please contact us at dalaran.community@gmail.com ; the Bug Tracker is not a place for this.
