### ISSUE TITLE
Missing Items

### ISSUE THREAD

**Issue by 123tomtom123** [dalaranwow/dalaran-wow#3672]
Items sent from one character to another have gone missing.

I sent heirloom items from my alliance druid "syphexx" to my horde pally "khaila" as I wanted to create a horde druid instead. i logged onto my pally to find a mail but none of the Items were attached!

items were leather heirloom shoulders
leather heirloom chest.
heirloom ring
2 x hierloom haste trinkets
and the heirloom 2H Mace

Please can you get my items back?

**Comment by ImprezaWoW** [comment]
The bug tracker is not  for lost loot. Please create an in-game ticket for your problem.

**Comment by 123tomtom123** [comment]
Hi, thank you for your response. I have created a ticket but am yet to hear
back...
