### ISSUE TITLE
Warlock Fear and death coil

### ISSUE THREAD

**Issue by adytzyca** [dalaranwow/dalaran-wow#3673]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (OLD - ... tags should no longer be used)
[//]: # (Priority - ... tags are assigned by team members)

**Description**:

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)

**Expected behaviour**: Tell us what should happen instead

**Steps to reproduce the problem**:

1. When casting fear or death coil on an enemy that's close range,it makes him teleport around,making it impossible to cast anything on the specific target.The target would appear to be in one place,however,upon trying to cast on him,you get the "target needs to be in front of you" error message.
2.
3. 

**Include proofs for this behaviour**

You can research this on several pages like http://wowhead.com or http://wowwiki.wikia.com or http://www.youtube.com/
Issues without proofs will be closed and tag On Hold will be added until the proof is provided.

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

You can research this on several pages like http://wotlk.openwow.com or http://wowhead.com/

**Include Screenshots from the issue if necessary**

**Comment by Golganeth** [comment]
#1447

**Comment by adytzyca** [comment]
is great that you guys are linking the issue to 2014 report posts,but is there actually anything else u can do about it?

**Comment by ImprezaWoW** [comment]
We can also inform you that the Developers have 942 other issues to work on, and we can only be patient until the issue that matters to you is fixed, just like the other issues that matter to other players. We link older open issues to avoid duplicate reports, and we are terribly sorry if you feel that it is unfair to have your issue closed even though your topic was already covered in the linked post.

**Comment by adytzyca** [comment]
yea,pardon me for raising  a question after 2 years of waiting,guess patience isnt really my virtue

**Comment by kalvindeane** [comment]
Please don't reply to issues unless you have something extra to contribute please guys. Bumps won't make things move faster, if anything it will slow them down.
