### ISSUE TITLE
Bugged Quest The relics of wakening

### ISSUE THREAD

**Issue by fgordop** [dalaranwow/dalaran-wow#3674]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (OLD - ... tags should no longer be used)
[//]: # (Priority - ... tags are assigned by team members)

**Description**:

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)

**Expected behaviour**: Tell us what should happen instead

**Steps to reproduce the problem**:

1. We cant finish the quest  "The relics of wakening", there is a body on the chest that we dont know why is it there, and when we open the box, in shows nothing when it should appear the item "Rune of nesting", the corpse is named "Romerdemon"
2. 
3. 

**Include proofs for this behaviour**

You can research this on several pages like http://wowhead.com or http://wowwiki.wikia.com or http://www.youtube.com/
Issues without proofs will be closed and tag On Hold will be added until the proof is provided.

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

You can research this on several pages like http://wotlk.openwow.com or http://wowhead.com/

**Include Screenshots from the issue if necessary**

![wowscrnshot_082116_184710](https://cloud.githubusercontent.com/assets/21162314/17840167/cf9d6504-67d4-11e6-8af8-63bae90c78df.jpg)

**Comment by ImprezaWoW** [comment]
[#2016](https://github.com/dalaranwow/dalaran-wow/issues/2016)
