### ISSUE TITLE
Shadow dance disappear after vanish.

### ISSUE THREAD

**Issue by Jiaku** [dalaranwow/dalaran-wow#3679]
[//]: # (INFORMATION ABOUT TAGS) #rogue
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (OLD - ... tags should no longer be used)
[//]: # (Priority - ... tags are assigned by team members)

**Description**:Shadow dance and vanish

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who) If you have shadow dance up and you use vanish, shadow dance buff disappear 

**Expected behaviour**: Tell us what should happen instead: After you use vanish shadow dance buff doesn't go away
**Steps to reproduce the problem**:

1. Use shadow dance
2. Use vanish

**Include proofs for this behaviour**
https://youtu.be/HO5-y7hRYo0?t=1m18s
As you can see in the clip rogue vanishes blind and still has shadow dance up.

http://wotlk.openwow.com/spell=51713

**Comment by robinsch** [comment]
On PTR.

**Comment by robinsch** [comment]
Fix confirmed on PTR.

**Comment by TeridanDW** [comment]
Works as intended on ptr.
