### ISSUE TITLE
Spell delay

### ISSUE THREAD

**Issue by Jiaku** [dalaranwow/dalaran-wow#3680]
[//]: # (INFORMATION ABOUT TAGS) #spells
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (OLD - ... tags should no longer be used)
[//]: # (Priority - ... tags are assigned by team members)

**Description**: Server has delay on each and every spell. So even if you use instant ability it doesn't go off immediately, there is delay about 0.2 seconds. (having  40ms in game, so latency isn't the problem) Usually it doesn't but if you are playing on rogue, you can really vanish and instantly cheap chot your target.

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who) Server has about 0.2 seconds delay.

**Expected behaviour**: Tell us what should happen instead If you press spell it uses it instantly, without delays

**Steps to reproduce the problem**:

1. Use an instant spell

**Comment by robinsch** [comment]
This is intended. On retail you had a delay between 1-400ms because all non self casts where handled in batches.

**Comment by Alistories** [comment]
I may be wrong, but I don't recall having this issue before where I accidentally backstabbed after vanish because of delay because they're in the same keybind

**Comment by sys6x** [comment]
Also, when a mob dies and it selects another, it takes a while before starting actions, even if it should be able to do them...not sure if related
