### ISSUE TITLE
Loosing stealth for no reason

### ISSUE THREAD

**Issue by Jiaku** [dalaranwow/dalaran-wow#3681]
[//]: # (INFORMATION ABOUT TAGS) #rogue
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (OLD - ... tags should no longer be used)
[//]: # (Priority - ... tags are assigned by team members)

**Description**: As said in the title sometimes rogues do loose stealth for no reason, On BG and Arena.

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who) Loosing stealth for no reason(no dots, no AoE nearby)

**Expected behaviour**: Tell us what should happen instead Rogue do not loose stealth unless there is a reason to that.

**Steps to reproduce the problem**:

1. Can't really pinpoint, it happens very rarely.

http://wotlk.openwow.com/spell=1787

**Comment by kalvindeane** [comment]
If it happens then please record the combat log to see what caused it and take screenshot or video as evidence

**Comment by InshadowsAlgalon** [comment]
It was happening due to warrior Intervene, but it got fixed.

**Comment by Jiaku** [comment]
It happens whenever pakadin uses salvation
