### ISSUE TITLE
Wild hunt Tenacity talent bugged hunter

### ISSUE THREAD

**Issue by schoefel** [dalaranwow/dalaran-wow#3682]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (OLD - ... tags should no longer be used)
[//]: # (Priority - ... tags are assigned by team members)

**Description**:
The talent of Tenacity pets of hunters "Wild hunt" does not increase stamina or AP.
**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
The talent isn't working(haven't tested rank 2 though.
**Expected behaviour**: Tell us what should happen instead
Rank 1/2
It should: Increase the contribution your pet gets from your Stamina by 20% and attack power by 15%
Rank 2/2
It should: Increase the contribution you pet gets from your Stamina by 40% and attack power by 30%
**Steps to reproduce the problem**:

1. get a Tenacity pet with enough talent points
2. take the wild hunt talent
3. notice it doesn't do anything

**Include proofs for this behaviour**

You can research this on several pages like http://wowhead.com or http://wowwiki.wikia.com or http://www.youtube.com/
Issues without proofs will be closed and tag On Hold will be added until the proof is provided.

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

You can research this on several pages like http://wotlk.openwow.com or http://wowhead.com/

**Include Screenshots from the issue if necessary**

**Comment by Golganeth** [comment]
#2910 - On PTR for testing purposes, if everything is fine it will be deployed to live realm.
