### ISSUE TITLE
Rage generation bugged

### ISSUE THREAD

**Issue by rbccrew** [dalaranwow/dalaran-wow#3683]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (OLD - ... tags should no longer be used)
[//]: # (Priority - ... tags are assigned by team members)

**Description**: Rage generation when hit is not scaling as intended.

**Current behaviour**: Low level warriors (and I believe druid, I haven't tested them) do not generate as much rage as they should when hit.

**Expected behaviour**: Rage generation when hit formula at low levels should not be the same as at level 80. Currently, you need to be hit for the same amount of damage as you would at level 80 to generate 1 rage (I believe it's around 180 damage, but I couldn't find any proof) which means you need to be hit for ~90%hp at level 10 when your max health is around 200hp to generate just 1 rage.

**Steps to reproduce the problem**:

1. Create a low level warrior
2. Pull a mob and don't attack it
3. Generate almost no rage

**Include proofs for this behaviour**

http://wowwiki.wikia.com/wiki/Rage#Formulae

**Comment by robinsch** [comment]
We're using formulars from http://wowwiki.wikia.com/wiki/Rage#Formulae.

As you can see in this video the rage gain on damage is correct at low levels: https://www.youtube.com/watch?v=G4VXd6FBrnY
