### ISSUE TITLE
Eye of Eternity Needs to be of Critical Priority! 

### ISSUE THREAD

**Issue by npmusicftw** [dalaranwow/dalaran-wow#3687]
I am opening a new tag, which will be closed, because this is a critical issue that needs to be fixed immediately. As noted on the original post, it has been over 2 years now. One of your dominant claims about this server is the impeccable scripting of the raids. Your well-written page on your website _"Why Dalaran"_ should be a fiery motivation to pride yourselves in a sterling representation of one of the first raids people will be doing on your server! 

I quote from Crispybuilt: 

**Vortex, which should pick up the entire raid, only picks up one person** at the moment. He is getting damaged as he should and the player can cast instant spells as intended.
Vortex is missing one big major animation at the moment. There are small visual sparks flying around him when he picks up a player. They are more like lighting storm sparks which can be seen around Malygos.That is at the moment completely missing.

**How it should work:** http://youtu.be/J81w3FFcojs?t=3m31s
**How does it work at the moment:** http://youtu.be/3-u5v2RwC5U?t=50s

**After the Vortex is and animation is over, all the players will lose combat** and re-enter the next second for some reason, making this slightly easier, since things such as potions can be used again. That should currently not be the case and should not happen.

**Vortex should be delayed** a bit (starts 3 seconds after Malygos flies to center, not instant like here on Dalaran WoW) before starting to being active: This is due the quote he says before picking up players (check quote report down below). This is not working as intended.

**Deep Breath animation**: Currently the animation happens, but it is not on the ground but for some reason in the air at his mouth directly, like there is invisible barrier up there for some reason. Most likely invisible world barrier at coordinate Z is glitching this out, 99% sure. This doesn't work as intended, the breath should hit the ground. This was working on Kirin Tor just fine.

How it should work: http://youtu.be/J81w3FFcojs?t=7m24s
How does it currently work at the moment: http://youtu.be/3-u5v2RwC5U?t=4m2s

**Comment by Lothloryen** [comment]
Thank you for the report, most of those feature were implemented - it seems previous patches broke them an no one has reported them until now. I will take a look into it.
