### ISSUE TITLE
Hunter's pets' Health Points after dismount

### ISSUE THREAD

**Issue by uyso** [dalaranwow/dalaran-wow#3688]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (OLD - ... tags should no longer be used)
[//]: # (Priority - ... tags are assigned by team members)

**Description**: Since like one months or so, we, hunters are reporting the following issue: Whenever we mount and dismount, our pet's health goes from Full, or whatever it is when we mount to 33% or 50% upon dismount.

**Current behaviour**: When you have a pet out and mount, then dismount, pet's health refreshes to 33% or 50%

**Expected behaviour**: When you mount, and your pet hp is, let's say 100%, it should be 100% when you dismount too.

**Steps to reproduce the problem**:

1. Get a hunter with pet.
2. Mount.
3. Dismount.

**Include proofs for this behaviour**

http://wotlk.openwow.com/spell=27639 

Spell ID is spell=27639, the spell is called Call Pet. 

PROOF: http://wowwiki.wikia.com/wiki/Call_Pet 

"Call Pet is very useful in situations where you have had to run away from a mob and your pet is almost dead. Send the pet after something a fair distance away, run in the opposite direction and when out of range the pet will despawn; **when you cast Call Pet, the pet will reappear with full health**.
If you use [Dismiss Pet] when in battle, casting **Call Pet will bring back the pet with the same Health as when it was dismissed**.
If the pet auto despawns because of range, casting **Call Pet will bring back the pet with Full Health.**"

Everywhere I read about Call pet, it says FULL HEALTH upon return.
This particular bug renders hunter NOT VIABLE in battleground where you have to mount/dismount constantly... Please Dala-wow staff, take a look at this annoying bug.

**Comment by Lothloryen** [comment]
#1992 

Hello there, thank you for the report. This issue was fixed already and it will be deployed with the next scheduled maintenance.
