### ISSUE TITLE
Is there a patch I'm missing?

### ISSUE THREAD

**Issue by FidelCashfl0w** [dalaranwow/dalaran-wow#3689]
I'm a new player and everytime I go to make a character, it wants to patch the game and then it says there's a problem downloading the patch, or something to that extent. I also cannot move my mouse pointer for some odd reason?

**Comment by kalvindeane** [comment]
Make sure you are logging in with your account name and not your email address.

**Comment by FidelCashfl0w** [comment]
I was just wondering also why my cursor is not moving? is this a common issue?
