### ISSUE TITLE
Warrior Talent/Spell: Death Wish

### ISSUE THREAD

**Issue by Crispybuilt** [dalaranwow/dalaran-wow#369]
Issue: When a warrior in Fury Spec uses ability "Death Wish" and if the talent "Enrage" procs, the Death Wish will go down. Basically, Enrage Consumes Death Wish which shouldn't happen.

Both buffs can stay on the player without going down or consuming each other. You can have both, Enrage and Death Wish at the same time.

http://www.wowwiki.com/Death_Wish
http://wotlk.openwow.com/spell=12292
http://www.wowwiki.com/Enrage_(warrior_talent)

**Comment by Rushor** [comment]
https://github.com/TrinityCore/TrinityCore/issues/14035

that was fixed with the new spell_stacking system in 2014
