### ISSUE TITLE
DEAD NPC DESPAWN TIMERS INCORRECT

### ISSUE THREAD

**Issue by npmusicftw** [dalaranwow/dalaran-wow#3692]
NPC DESPAWN TIMER
Dead NPC's despawn way too quickly. If my memory servers me properly, patch 3.3.5 showed no differences in despawn timers since 2.4.2 (http://us.battle.net/wow/en/game/patch-notes/2-4-2. Your timers seem to be as follows:

Looted corpse: ~30 seconds till despawn.
Unlooted corpse: ~45 seconds till despawn.

Blizzard had/has it as follows:
Looted corpse: ~120 seconds (2 min.) till despawn.
Looted, but salvageable corpse (skinning, engineering, mining, herbalism): ~300 seconds (5 min.) till despawn.
Unlooted corpse: ~300 seconds (5 min.) till despawn.

_"I slapped on my Boots of the Bay and nuked some bloodsail pirates. By using mana shield (expires after 1 minute) as a timer, I observed the following:_

_**looted immediately, despawned after 3rd cast (2 minutes)_
_**looted after 1 minute, despawned after 4rd cast (3 minutes, which is 2 minutes after looting)_
_**uninspected, despawned after 6th cast (5 minutes)_
_**inspected, despawned after 5.2 minutes (5 minutes after inspection)_
_**inspecting each minute, lasted 10 casts (did not wait for despawn) - mob did respawn at 8.4 minutes._ _**Killed the second mob, looted and the new corpse despawned after 2 minutes while original corpse still there._
_**killed and looted a jaguero stalker (skinnable). The corpse despawned 5 minutes after looting._

**So, it seems that 2 minutes is the despawn time for looted corpses (unless salvagable, then it's 5 minutes). If there's loot it will despawn after 5 minutes. Inspecting the loot resets the timer."**

Sources:
http://gaming.stackexchange.com/questions/78923/how-long-do-corpses-remain
http://us.battle.net/wow/en/game/patch-notes/2-4-2 (second to last bullet).

**Comment by tripleslash** [comment]
One of the fundamental issues within MaNGOS is that creatures cannot respawn until their previous dead body is despawned. Fixing the respawn time would therefore make it impossible for mobs to respawn in their proper time. This is also the reason why GUIDs of spawned objects in MaNGOS are always the same, unlike retail where each spawn of a creature gets the GUID assigned at spawn time.

**Comment by Golganeth** [comment]
#971
