### ISSUE TITLE
[Togc25] Jaraxxus - Nether Power - "Invisible Stacks"

### ISSUE THREAD

**Issue by ashido96** [dalaranwow/dalaran-wow#3694]
On hold until logs? This was during one of those weird runs where the entire raid doesn't get a save as well if that means anything for a bug report.

When fighting Jaraxxus on 25 heroic the raid can run into a situation where Jaraxxus' fell lightning will do 30k+ damage even after all of his nether power stacks have been spellstolen or dispelled. The general current belief is that he gains "invisible stacks" of nether power when an interrupt fails or he gets moved while casting (maybe? doesn't happen 100% of the time, or maybe it does and there's not enough "invisible stacks" to notice it).

**Expected behavior**: fell lightning should not be instantly one shotting 4 raid member when he has no stacks of nether power.
1.  do togc25 heroic and fight jaraxxus
2.  RNG happens, haven't had this happen for at least a month now 

**Include proofs for this behaviour**: This does happen, unfortunately the person who normally does our logs didn't have it turned for the first couple of bosses, I will of course edit this if I can get a hold of logs in the future.

You can research this on several pages like http://wowhead.com or http://wowwiki.wikia.com or http://www.youtube.com/
Issues without proofs will be closed and tag On Hold will be added until the proof is provided.

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**
http://www.wowhead.com/spell=66528/fel-lightning
http://www.wowhead.com/spell=67009/nether-power#used-by-npc
http://www.wowhead.com/npc=34780/lord-jaraxxus

**Comment by plznoz** [comment]
Has been an issue since forever, and devs have claimed to have fixed it several times. Still happens almost every week.

**Comment by Rushor** [comment]
https://github.com/TrinityCore/TrinityCore/commit/4a38773e3e74af329aa13e2a506ef824f2a6e4d3

on ptr, maybe the fix was not yet applied on the live algalon realm

**Comment by TeridanDW** [comment]
I can't reproduce this issue on ptr.

> TrinityCore/TrinityCore@4a38773

**Comment by plznoz** [comment]
This has been fixed for a good while on live server. Have not seen it happen in maybe 6 months on live server (used to happen almost every week before that)

**Comment by TeridanDW** [comment]
Thank you @plznoz  for the information, maybe @Lothloryen  will still want to add it as notification in next changelog so i won't change the label.
