### ISSUE TITLE
quest

### ISSUE THREAD

**Issue by mrrobeasca** [dalaranwow/dalaran-wow#3695]
**Description**: quest don't appear on map

**Current behaviour**: so i was leveling and i finished a quest. when i looked on the map to see where the next quest is the numbers appeard for like 2 seconds and then they disappeard. i reloged,rebooted pc and downloaded wow again and it still didn't work some guy in my guild said he had the same issue but somehow he fixed it (he doesn't remember how). i tried everything i even deleted the folders: WTF,interface,cache and logs but it still doesn't work and when i click on the circle with the number in the middle the blue mark appears and stays there until i click on another circle

**Expected behaviour**: the quest should appear in the map

**Steps to reproduce the problem**: i don't know 

https://cloud.githubusercontent.com/assets/21986060/18244706/2af08d96-736a-11e6-830e-a02349a3d925.jpg

https://cloud.githubusercontent.com/assets/21986060/18244740/58102f8e-736a-11e6-9c47-d3c5473a04d0.jpg

https://cloud.githubusercontent.com/assets/21986060/18244748/64188272-736a-11e6-83f4-7e804a5d098c.jpg

https://cloud.githubusercontent.com/assets/21986060/18244732/4d245686-736a-11e6-8d90-9811f2d63f03.jpg

**Comment by Jokey123** [comment]
This isn't a problem that should be reported on the Bugtracker, because you are the only person who is actually facing it, with a couple of other people. Try disabling some of your addons, they could take an effect on your UI. And if that doesn't work then try downloading the client from another server then changing the realmlist to: set realmlist logon.dalaran-realmlist.org
Goodluck.

**Comment by Golganeth** [comment]
Invalid report, the bug tracker only lists issues with quests, NPCs, etc.

It's a client related issue, try turning in or abandoning a quest and it should be fine. On the screenshot there doesn't seem to be any addon being used.

Make sure to check out our [**game client**](http://www.dalaran-wow.com/game-client/) if you haven't already.

Closed
