### ISSUE TITLE
The quest: Fire upon the water not working

### ISSUE THREAD

**Issue by Larsm1980** [dalaranwow/dalaran-wow#3697]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (OLD - ... tags should no longer be used)
[//]: # (Priority - ... tags are assigned by team members)

**Description**:
Cant set fire to the sails. with the flask in the inventory/bag. so i cant complete the quest
**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)

**Expected behaviour**: Tell us what should happen instead

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Include proofs for this behaviour**

You can research this on several pages like http://wowhead.com or http://wowwiki.wikia.com or http://www.youtube.com/
Issues without proofs will be closed and tag On Hold will be added until the proof is provided.

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

You can research this on several pages like http://wotlk.openwow.com or http://wowhead.com/

**Include Screenshots from the issue if necessary**

**Comment by Golganeth** [comment]
You should try using the quest item on the Sails.

![image](https://cloud.githubusercontent.com/assets/5057942/18273201/825b546c-743c-11e6-8bcf-b3f92ca99c8e.png)

Closed
