### ISSUE TITLE
NPC: Defias Bandit

### ISSUE THREAD

**Issue by Crispybuilt** [dalaranwow/dalaran-wow#37]
Defias Bandit - 116

Issue: After their hp goes down to 52-55% they will enable their abillity called "Snap Kick"

Then the debuff is applied on the player and it expires with a cooldown, it can be applied 2-3 more times max and then the player becomes immune to it.
 In this case you still get kicked by their "Snap Kick" but there is no debuff shown on you which means that you can get kicked endlessly.

For example, if you pull 5-6 of them at the same time, you might get stuck because they'll be kicking you all the time.

Diminishing Return works fine but they just keep kicking you even DR expires, thats the problem.

**Comment by Rushor** [comment]
i think this was fixed some time ago

**Comment by Rushor** [comment]
because creature cooldown for spells is not implemented yet - the real reason for this issue is https://github.com/dalaranwow/dalaran-wow/issues/182

duplicate  - closing
