### ISSUE TITLE
Achievement: Friend or Fowl?

### ISSUE THREAD

**Issue by Crispybuilt** [dalaranwow/dalaran-wow#370]
Friend or Fowl? ID: 1254
Slay 15 turkeys in 3 minutes.

NPC: Fjord Turkey - 24746
http://wotlk.openwow.com/npc=24746

The achievement criteria simply doesn't work. I've killed 35 turkeys in less then 3 minutes and achievement didn't pop.

Once you kill the first Turkey, the counter should start (3 minutes) and if you kill 14 more turkeys under 3 minutes you get achievement.

http://wotlk.openwow.com/achievement=1254
http://www.wowhead.com/achievement=1254/friend-or-fowl

**Comment by Augur89** [comment]
Confirmed, just kill 15 Turkeys (no more, no less) and then log off. When you log in you'll be attacked by a big group of angry turkeys and the achievement will be there.

**Comment by Blackoutx** [comment]
Confirmed this log out log in method, just did it

**Comment by Golganeth** [comment]
Still an issue. Achievement should pop as you complete it once you're online, not after a relog.

**Comment by Golganeth** [comment]
Seems fixed.
