### ISSUE TITLE
all enemies except casters missing weapons

### ISSUE THREAD

**Issue by sarcn** [dalaranwow/dalaran-wow#3700]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (OLD - ... tags should no longer be used)
[//]: # (Priority - ... tags are assigned by team members)

**Description**:

All enemies that normally wield melee or ranged weapons are missing them, with the exception of casters, who all wield the exact same blue staff.

Melee enemies attack with their fists. Enemies that use ranged or thrown weapons don't have attack animations at all.

This applies to every single enemy that I have ever encountered since joining the server. I'm currently a level 37 undead.

**Expected behaviour**:

Should be self-explanatory. Enemies should be using weapons.

**Steps to reproduce the problem**:

1. Create a character.
2. Look at any non-caster humanoid enemy that uses a ranged or melee weapon, anywhere in the game world.

Since this involves (as far as I can tell) the majority of NPCs in the world, providing IDs isn't feasible. However, here are screenshots of each specific issue:

Ogre is missing his weapon. On the right, you can see an example of the staff that every caster in the world uses.
![image](https://cloud.githubusercontent.com/assets/22039173/18293652/7ad5be3e-7451-11e6-8767-0f4bba85bb68.png)

Ranged enemy with no weapon. No attack animation. Purple damage text confirming that he is attacking me.
![image](https://cloud.githubusercontent.com/assets/22039173/18293687/bb4656d6-7451-11e6-8b57-c0186169d17c.png)

Again, two trolls on the left missing their weapons. Another example of the caster staff.
![image](https://cloud.githubusercontent.com/assets/22039173/18293708/da30e1ce-7451-11e6-958d-4900a1e2e405.png)

**Comment by kalvindeane** [comment]
This is not the case for me. Seems to be an issue with your client and not the server itself.

**Comment by sarcn** [comment]
Great. Thanks for the help, asshole.
