### ISSUE TITLE
You're not getting notified when you get items in the mail

### ISSUE THREAD

**Issue by Klala** [dalaranwow/dalaran-wow#3705]
**Description**: You're not getting notified when you get items in the mail. This is sometimes confusing when you get something via mail but you don't remember how or where you got it.

**Current behaviour**: When you get a mail with an item you and you take the item the game doesn't let you know what you just received.

**Expected behaviour**: You should get a notification just like when you find an item when a mob drop it. "You have received X"

**Steps to reproduce the problem**:

1. Send yourself an item via mail
2. Open and take the item
3. Notice you're not getting any messages.

**Include proofs for this behaviour**
https://www.youtube.com/watch?v=XggIgyG06-E
2:45 he's taking items from the mail with an addon and you can see his chat window messages about the items he gets.

**Comment by robinsch** [comment]
Hey, nice find. A fix was applied on PTR and will be deployed on live on the next update.

**Comment by TeridanDW** [comment]
Works as intended on ptr.
