### ISSUE TITLE
Druid Tranquility Not Usable

### ISSUE THREAD

**Issue by strobe-light** [dalaranwow/dalaran-wow#3706]
**Description**: Tranquility is currently bugged somehow and is not usable.
If you cast it, you get an error message: "Out of Range", despite the fact that Tranquility is not a targeted spell. I checked with multiple other druids to confirm that it wasn't an isolated addon/ui issue. This is the case for all ranks of the spell.

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**
http://wotlk.openwow.com/spell=48445

**Comment by Lothloryen** [comment]
Hello there,

Thank you, it will be corrected after the next maintenance.
