### ISSUE TITLE
Quest : Triage BUG and more 

### ISSUE THREAD

**Issue by bgOverpower** [dalaranwow/dalaran-wow#3707]
**Description**:
I haven't been playing in a while and once I returned I noticed some bugs relating quests that didn't occur before. 
**Current behaviour**: 
One was when I accept quests sometimes they dont show in my quest log and I need to relog to refresh that. The other one was I actually had one accepted quest that never appeared I finally figured it out and finished it. But another quest bugged out similarly named Triage in Dustwallow Marsh for alliance. I failed the quest and now I cant redo it and my max quest acceptance is 24 instead of 25.
I wrote about this to some dalaran wow mail but no response.
**Expected behaviour**: 
I should be able to have my quests appear after I accept them, also if I abandon quest it should get  out of my quest log and finally I should be able to have 25 / 25 quests not 24/25 and have my quest log full. Also the quest Triage never reapeared and when I talk to the Q giver I cant do anything about it.
Last thing is there are a lot of bot spammers, whenever I log in I get whispered by afkers or none afkers who dont reply.
**Steps to reproduce the problem**:

![wowscrnshot_082715_221812](https://cloud.githubusercontent.com/assets/22072121/18343150/d836fd62-75ba-11e6-8f32-52321807d481.jpg)
![wowscrnshot_090816_114936](https://cloud.githubusercontent.com/assets/22072121/18343174/f1b314ba-75ba-11e6-8ef8-16de83754ef3.jpg)

**Include proofs for this behaviour**
http://wowwiki.wikia.com/wiki/Quest_Log - 25 Q limit
http://www.wowhead.com/quest=6624/triage - The Quest

P.S. If you need something else since I didnt come up with more feel free to ask. The other quest that used to be bugged and thus my q  log was 23 / 25 max. It was a cooking quest in Tanaris 
http://www.wowhead.com/quest=6610/clamlette-surprise But instead of cheder wanted alterac cheese.

**Comment by Golganeth** [comment]
The quest issue could be related to your client. Keep in mind though some quests have timers and even if you abandon them, they won't show as 'active' until the objective fails or player relogs. 
Close the game completely, clear your Cache folder and disable any addon that could be causing the problem. If the issue persists, make sure to check out our game-client.

About the scammers, feel free to make an in-game ticket to report them. Here's a [**useful link**](http://www.dalaran-wow.com/forums/news-and-rules/suggestions-and-opinions/topic/8996/spam) with some more information about the current situation.

Closed.

**Comment by bgOverpower** [comment]
Thank you one of the addons was making my quest vanish. I will try to figure why and the quests prolly are from addons as well since I asked a friend he doesnt have the problem.
