### ISSUE TITLE
Turgid the Vile

### ISSUE THREAD

**Issue by powerpuffgurl** [dalaranwow/dalaran-wow#3708]
He should be in that place, not under the building (unreachable)
https://www.youtube.com/watch?v=lslEgQmrN4g

**Comment by Golganeth** [comment]
I've just checked the NPC in-game and he wasn't under the building, but I've reset it anyway.
It's a general and rare pathfinding issue with some NPCs, so feel free to make an in-game ticket should you encounter a similar issue again in the future.

**Comment by powerpuffgurl** [comment]
Hey, I don't have access for dalaran-wow? What happened?
