### ISSUE TITLE
Annoying stuff

### ISSUE THREAD

**Issue by Hannal123** [dalaranwow/dalaran-wow#3713]
Hello Dalaran community & staff, today I've decided to make a list on a few annoying things that I've experienced so far on your server since I started playing here, like 1,5 year ago.

Let's begin by pointing out lag, that's right, "LAG". This issue is probably the most annoying and sad part of the server, because when I play pvp on my warrior it takes almost 2 seconds for me to use my shield bash and spell reflection macros etc etc... This is something that you guys really need to fix, and I am not stating that it's an easy fix, but it just has to change.

Fix the website armory / pvp ladder

Get a moderator or spam filter for global chat, and this isn't coming from the right person, I know, but it's definetly something that you should consider doing because it affects the community.

I also asked a few friends about their opinion on Staff / ticket support. These are their opinions:

More responsive ticket support

More GM interaction and news on what they've been doing lately with the server

I love this server, but I hate the community and pvp sadly. But here you have a list of important things, especially the lag.

**Comment by kalvindeane** [comment]
Github is used for bug reports for the developers.

Please refrain from posting issues that are not bug reports here. Thank you.
