### ISSUE TITLE
[Temple of Ahn'Qiraj] Large Scarab Coffers

### ISSUE THREAD

**Issue by Bonham01** [dalaranwow/dalaran-wow#3714]
**Description**:
The Large Scarab Coffers inside the Temple of Ahn'Qiraj do not spawn properly. These coffers contain items necessary to obtain T2.5 gear (idols and scarabs).
**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
Scarab coffers do not spawn
**Expected behaviour**: Tell us what should happen instead
Scarab coffers should spawn
**Steps to reproduce the problem**:

1. Go to AQ40
2. Check coffer spawns
3. See they do not spawn

**Include proofs for this behaviour**

Here is a screenshot of one of the coffer spawns. See that there is no coffer (this is a freshly cleared AQ40, nobody else looted coffers)

http://imgur.com/a/jLq3r

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

Here is the wowhead page with all the spawn points marked on the map as well as the loot that should be contained inside

http://www.wowhead.com/object=180690/large-scarab-coffer

**Include Screenshots from the issue if necessary**

**Comment by robinsch** [comment]
Added the spawns to AQ20 and AQ40. On PTR and waiting for update on live.

**Comment by Bonham01** [comment]
Thank you for your quick response. Much appreciated

**Comment by TeridanDW** [comment]
Works as intended on ptr.
