### ISSUE TITLE
Help Tavara Priest Quest can't be completed

### ISSUE THREAD

**Issue by TACOSPIES** [dalaranwow/dalaran-wow#3716]
**Description**: Help Tavara Priest quest doesn't complete. Prevents me from doing priest quests.

**Current behaviour**: In Azuremyst Isle, on the main server, I have a Draenei priest who could not complete this quest when I was first able to complete it. I used both Gift of Naaru and Flash Heal, and neither of them worked. After reading some of the other reports of it (from the non-private servers) I decided I would come back when i had more healing spells. I can use Gift of Naaru, Flash Heal, Heal, Renew, and Holy nova, and none of them work. She does heal, but the quest doesn't track that she's been healed, and will keep her health new health level. You cannot talk to her, and after a few moments she will kneel down again (Where, When, What, Why, Who)

**Expected behaviour**: You should heal her (with any priest related spell) and then the quest tracker should say "Completed: Heal Tavara 1/1"

**Steps to reproduce the problem**:

1. Walk up to Tavara
2. Use any heal spell (as a priest)

**Include proofs for this behaviour**

![wowscrnshot_091516_114522](https://cloud.githubusercontent.com/assets/22223828/18562848/59e8d5d6-7b3a-11e6-9f6c-c08019846933.jpg)

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills** 71551

**Include Screenshots from the issue if necessary**

![wowscrnshot_091516_114522](https://cloud.githubusercontent.com/assets/22223828/18562848/59e8d5d6-7b3a-11e6-9f6c-c08019846933.jpg)

**Comment by ImprezaWoW** [comment]
[#3518](https://github.com/dalaranwow/dalaran-wow/issues/3518)
