### ISSUE TITLE
Mine nods in The Ghostlands

### ISSUE THREAD

**Issue by nifaro** [dalaranwow/dalaran-wow#3718]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (OLD - ... tags should no longer be used)
[//]: # (Priority - ... tags are assigned by team members)

**Description**: Mining veins issue

**Current behaviour**: The mine veins in The Ghostlands are all 3 on top of each other - copper, tin and silver. There are far more than it should i feel like, not to mention they respawn fairly quickly on this server and you level your mining too fast if you go around Ghostlands a few times which is disproportionate for the level you are.
**Expected behaviour**: They should be single vein like everywhere else in the world. So far the Ghostlands is the only place that I've seen this problem

**Include proofs for this behaviour**

http://i.imgur.com/3KotcHR.jpg

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

Could not find the IDs

**Comment by Golganeth** [comment]
#1208

**Comment by Hyp3rViper** [comment]
As of 19-12-2017, this still happens. Every node in the Ghostlands seems to be comprised of Copper, Tin and Silver ore at the same time.

**Comment by daunte5386** [comment]
As of 12/3/2018, this still happens.  Every node in the Ghostlands has copper, tin and silver at the same time.

**Comment by xnemeyethx** [comment]
Confirmed.
