### ISSUE TITLE
Bug Neatherweave bag makes my items disappear

### ISSUE THREAD

**Issue by hsmbt2** [dalaranwow/dalaran-wow#3719]
Hi guys so i reacently got a neatherweave bag and when i tried to put anyitems in it they disappeared. not overly upset about the items lost except for my enchanted gold bloodrobe which can only be gotten from the warlock quest. thanks again for the assistance and hope you can squash this bug

Thanks Again 
Character name Malreth (undead warlock lvl 37{at this time})

**Comment by Golganeth** [comment]
Can't reproduce it. Item was probably vendored to NPC or sent to your mailbox. Provide footage for the behavior (if you can).

Closed
