### ISSUE TITLE
Warrior rage gain at low levels

### ISSUE THREAD

**Issue by Larsy93** [dalaranwow/dalaran-wow#3720]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (OLD - ... tags should no longer be used)
[//]: # (Priority - ... tags are assigned by team members)

**Description**: Not gaining the correct amount of Rage when getting hit at low level as a prot warrior.

**Current behaviour**: Not gaining the correct amount of Rage when getting hit at low level.

**Expected behaviour**: We should get more Rage when getting hit.

**Steps to reproduce the problem**:

1. Make a Warrior (low level)
2. Pull a mob and look at the ragebar
3. See that rage isnt gained properly

**Include proofs for this behaviour**

http://puu.sh/rhIXm/16b2eac8d0.jpg

http://wowwiki.wikia.com/wiki/Rage#Formulae

**Comment by Golganeth** [comment]
#3683
