### ISSUE TITLE
[Glyph] Glyph of Charge

### ISSUE THREAD

**Issue by glitterlance** [dalaranwow/dalaran-wow#3722]
The glyph works only when it comes to the range indicator. It does not increase the range of the spell. This seems to be a reoccurring bug though.

I checked it after standing at exactly 30 range. I could taunt but not charge. I could cast charge only when I was within 25 yards which is the default range without the glyph.

**Comment by robinsch** [comment]
Can't confirm. Working fine on PTR. Tested at 30 yard range with .gps command.

**Comment by Larsy93** [comment]
still not working

**Comment by kalvindeane** [comment]
Could you post proof of this if possible please?

**Comment by Larsy93** [comment]
Well the tooltip changes so the ability shows as useable at 30 yards but
you have to get 5 yards closer than that to use charge. It keeps fooling me
to believe that i can charge when i infact cant.

Den 18 okt. 2016 8:25 em skrev "Edhelas" <notifications@github.com>:

**Comment by kalvindeane** [comment]
I was asking for proof such as screenshots or a video. ^_^

**Comment by Larsy93** [comment]
Well i replaced the glyph and it is quite costly coming in at 75ish gold,
but everyone knows its bugged and it should not be hard for you to test.

2016-10-18 22:41 GMT+02:00 Edhelas <notifications@github.com>:

**Comment by Larsy93** [comment]
Getting my ass over to orgrimmar to buy the glyph :)

2016-10-18 22:41 GMT+02:00 Edhelas <notifications@github.com>:

**Comment by Larsy93** [comment]
https://youtu.be/xs3xeIxQdng

There you go.

**Comment by kalvindeane** [comment]
Excellent! Also could you refrain from making a new post about an existing issue in the future - it's easier for us to manage if we don't have duplicate threads.

Thank you. =)

**Comment by Larsy93** [comment]
yes, my bad, just wanted to do a proper one this wasnt using the correct template, but i guess this will do :)

**Comment by Larsy93** [comment]
When can one expect this kind of thing to be solved?

**Comment by robinsch** [comment]
@Larsy93 No ETA for any issue. Bumping doesn't change things.

**Comment by Rushor** [comment]
The issue was fixed on PTR. With further merges this issue will be fixed on the live-realm too.

Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
