### ISSUE TITLE
Temple of Ahn'Qiraj Loot Table Issues

### ISSUE THREAD

**Issue by Bonham01** [dalaranwow/dalaran-wow#3723]
**Description**:
Flaws in the Ruins of Ahn'Qiraj and the Temple of Ahn'Qiraj loot tables. I've cleared the AQ40 trash 4-5 times now and only have 6 AQ40 specific idols. I had over 40 of the AQ20 specific idols drop during this time (they shouldn't drop at all). 
**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
Currently, the idols that should drop only from AQ20 are dropping in both AQ20 and AQ40. Therefor the droprates for the AQ40 idols are significantly reduced.
**Expected behaviour**: Tell us what should happen instead
The correct idols should drop only from the instances they were intended to drop from.
**Steps to reproduce the problem**:

1. Go to AQ40
2. Kill trash
3. Loot AQ20 idols from trash and see the absence of AQ40 idols needed for tier 2.5 gear

**Include proofs for this behaviour**

See the screenshot below to see me looting AQ20 idols from a fresh AQ40

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

Idols that should drop ONLY from AQ20:

Alabaster Idol; http://www.wowhead.com/item=20873/alabaster-idol
Vermillion Idol: http://www.wowhead.com/item=20872/vermillion-idol
Jasper Idol: http://www.wowhead.com/item=20870/jasper-idol
Amber Idol: http://www.wowhead.com/item=20869/amber-idol
Lambent Idol: http://www.wowhead.com/item=20868/lambent-idol
Azure Idol: http://www.wowhead.com/item=20866/azure-idol
Obsidian Idol: http://www.wowhead.com/item=20871/obsidian-idol
Onyx Idol: http://www.wowhead.com/item=20867/onyx-idol

Idols that should drop ONLY from AQ40:

Idol of Death: http://www.wowhead.com/item=20876/idol-of-death
Idol of Life: http://www.wowhead.com/item=20879/idol-of-life
Idol of Night: http://www.wowhead.com/item=20875/idol-of-night
Idol of Rebirth: http://www.wowhead.com/item=20878/idol-of-rebirth
Idol of Strife: http://www.wowhead.com/item=20881/idol-of-strife
Idol of the Sage: http://www.wowhead.com/item=20877/idol-of-the-sage
Idol of the Sun: http://www.wowhead.com/item=20874/idol-of-the-sun
Idol of War: http://www.wowhead.com/item=20882/idol-of-war

**Include Screenshots from the issue if necessary**

http://imgur.com/a/Aleft
http://imgur.com/a/Ml1nP
I can always attach more screenshots if you want. They are dropping quite a lot from the AQ40 trash.

**Notes**

I know this is minor, but for achievement farmers/lore enthusiasts this causes a big issue when trying to obtain older gear sets. This issue is made worse by the fact that the scarab coffers (the main source for idols/scarabs) don't spawn properly either (see this other ticket I have open: #3714). Anything that can be done about this is greatly appreciated. 
I will also be testing AQ20 later today to see if the AQ40 idols drop in there. If so, I will update this post.
Thanks as always.

Edit: AQ40 is the only raid that has this issue. AQ20 is fine.

**Comment by robinsch** [comment]
Hey I've removed the AQ20 idols from all AQ40 NPCs. It's still pending to be updated on live.

**Comment by TeridanDW** [comment]
Did a full clear on trash on both AQ 25 and 40, the idols were dropping correctly according to the difficulty.
Works as intended on ptr.
