### ISSUE TITLE
BENEDICTION STAFF QUEST BROKEN ( THE BALANCE OF LIGHT AND SHADOW )

### ISSUE THREAD

**Issue by rustypickle** [dalaranwow/dalaran-wow#3724]
THE PRIEST QUEST " THE BALANCE OF LIGHT AND SHADOW " IS BUGGED, WHEN I START THE QUEST, NONE OF THE PEASENTS SPAWN FOR THE ACTUAL QUEST, THEREFORE NOT BEING ABLE TO COMPLETE IT, I ALREADY HAVE 2 / 3 REAGENTS FOR THIS QUEST CHAIN AND THE QUEST IS THE FINAL PART! PLEASE ID LITERALLY LOVE YOU IF YOU COULD FIX THIS BUG JUST IN THE QUEST SO I CAN FULLY COMPLETE IT <3 
                                  
https://www.youtube.com/watch?v=mw2wKA1iPyw
                                    VIDEO FOR REFERANCE

![capture](https://cloud.githubusercontent.com/assets/22358578/18735150/7de08c0e-8030-11e6-8e5c-3a8f1648812a.JPG)
 normally where peasents would be spawning ** ^

**Comment by Golganeth** [comment]
#2436

**Comment by rustypickle** [comment]
will this quest be implemented at any point?
