### ISSUE TITLE
Warlock minion instant heal

### ISSUE THREAD

**Issue by nemmjuuk** [dalaranwow/dalaran-wow#3725]
**Description**:
Warlock minions can be instantly healed by the player using their mount.

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
Warlock minions with less then full health can be instantly healed when the player uses their mount and dismounts again. The moment the player unmounts, the minion respawns with full health.
**Expected behaviour**: Tell us what should happen instead
Minions should respawn with their previous health, or auto-healed over time. Not sure how the original  mechanic in retail WOTKL was. 
**Steps to reproduce the problem**:
1.  Summon a voidwalker and have it take some damage.
2.  Mount up. Minion despawns.
3.  Unmount a second later. Minion respawns fully healed. 

Since this is trivial to reproduce I'm not Including proofs for this behaviour**

**Comment by robinsch** [comment]
Can't confirm. Working fine on PTR.

**Comment by nemmjuuk** [comment]
It might work on the PTR but it's a real issue in the live game.  Both my warlock and my wife's warlock can demonstrate it in-game if needed.

**Comment by robinsch** [comment]
@nemmjuuk Hey, this doesn't mean we won't look into the issue. I'm working on a different branch then the live realm currently is - so if something works on PTR and doesn't on Alagon live realm the only one who can help is @Lothloryen who is pretty busy these days.

**Comment by Rushor** [comment]
this fixed the issue https://github.com/Aokromes/TrinityCore/commit/d716e6049a9ee3e0876f5bfc384d70e2280c86c5

**Comment by Edzero** [comment]
Pets now appear with the correct amount of hp.
