### ISSUE TITLE
Camera angle is bugged

### ISSUE THREAD

**Issue by Dasgul** [dalaranwow/dalaran-wow#3726]
Hey Dalaran Wow

I tried to zoom to get a hook in the fishing skill, but when i got all close, i couldnt zoom back out, and now im kinda stuck with a view as my character sees :(

Can you help me zoom out.

Regards Dasgul

**Comment by Golganeth** [comment]
It is in your side, check your settings and setup the Key Bindings.
Esc -> Key Bindings

Closed
