### ISSUE TITLE
Cracked Silithid Carapace

### ISSUE THREAD

**Issue by peszmerd** [dalaranwow/dalaran-wow#3729]
**Description**: Item "Cracked Silithid Carapace" should drop from Silithids while on a "The Swarm Grows" quest.

**Current behaviour**: The item is not dropping at all, while being on that quest.

**Expected behaviour**: Cracked Silithid Carapace should drop on sight from mobs mentioned in quest The Swarm Grows. 

**Include proofs for this behaviour**

http://db.vanillagaming.org/?quest=1148
http://db.vanillagaming.org/?item=5877#wh-comments

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

http://wotlk.openwow.com/item=5877

**Comment by robinsch** [comment]
Can't confirm. Here is the loot table:
"4130"	"5877"	"0"	"12"	"0"	"1"	"0"	"1"	"1"	""
"4131"	"5877"	"0"	"0,3"	"0"	"1"	"0"	"1"	"1"	""
"4132"	"5877"	"0"	"8"	"0"	"1"	"0"	"1"	"1"	""
"4133"	"5877"	"0"	"4"	"0"	"1"	"0"	"1"	"1"	""
