### ISSUE TITLE
Achievement: Higher learning

### ISSUE THREAD

**Issue by Naabcake** [dalaranwow/dalaran-wow#373]
The books are not despawning after being read.

**Comment by Rushor** [comment]
0ab365ee62e8c81ad7127b2e2149d29ab58fe6c6
- they will despawn now after 240000 milliseconds after beeing opened

**Comment by Golganeth** [comment]
The books despawn instantly and not after 4 mins. They don't seem to respawn at all (waited around 10 mins~).
The book that has been read is still permanent visible in GM mode so even if they would respawn, I assume it would be the same book, making the despawn useless. Only crash/restart changes them.

One of the random books for each location should respawn instead.

**Comment by Rushor** [comment]
Ref: https://github.com/TrinityCore/TrinityCore/issues/6608

**Comment by Rushor** [comment]
DB/Gameobject: Higher Learning - Apply SAI despawn script

* updates: https://github.com/dalaranwow/dalaran-wow/issues/373
* commit: 4f0fc4b1bc15f388db255bc7a7ac35f594b009ac

Applied the fix from https://github.com/TrinityCore/TrinityCore/issues/6608#issuecomment-269047214. However two bugs still exists:


    1.) gameobject wont disappear from client even if it despawns, you have to lose it manually (no means     to refresh visibility)
    2.) cooldown may be extended to 3hours + 4 minutes if player clicks the book just before despawn

This cannot be fixed at the current state of the core, but it's a huge improvment.
