### ISSUE TITLE
Quest The Scepter of Celebras

### ISSUE THREAD

**Issue by Jindra555** [dalaranwow/dalaran-wow#3733]
As seen in this report: https://github.com/dalaranwow/dalaran-wow/issues/762

There has been a partial fix - the event works up to the point of the book spawn. It either doesn't spawn or does so underground, so it cannot be clicked and the event is impossible to complete.

**Comment by ImprezaWoW** [comment]
You have left a comment at #762 , no need to create a duplicate report.
