### ISSUE TITLE
Dead toon continues to take infinite damage

### ISSUE THREAD

**Issue by leftfielder21** [dalaranwow/dalaran-wow#3736]
Not sure what to do here. My toon is dead, but he continues taking infinite damage and there's no option to respawn. So basically, I'm stuck. I can't even log-out or exit game w/o doing a hard restart. Please advise. Thanks!
![wowscrnshot_092916_154420](https://cloud.githubusercontent.com/assets/22532577/18975218/640c55f0-865d-11e6-9a14-94bf0b510bed.jpg)

**Comment by Golganeth** [comment]
Already handled in-game.
