### ISSUE TITLE
Forging an Alliance

### ISSUE THREAD

**Issue by deathara1** [dalaranwow/dalaran-wow#3738]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (OLD - ... tags should no longer be used)
[//]: # (Priority - ... tags are assigned by team members)

**Description**: Forging an Alliance is not working. When I talk to King Jokkum, I don't get the option to start a dialogue.

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who) King Jokkum offers no dialouge

**Expected behaviour**: Tell us what should happen instead King Jokkum should have an option to deliver Fjorn's Anvil

**Steps to reproduce the problem**:

1. Take the quest "Forging an Alliance
2. Talk to King Jokkum
3. No dialouge

**Include proofs for this behaviour**
http://www.wowhead.com/quest=12924/forging-an-alliance

You can research this on several pages like http://wowhead.com or http://wowwiki.wikia.com or http://www.youtube.com/
Issues without proofs will be closed and tag On Hold will be added until the proof is provided.

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills** 12924 - Quest ID

You can research this on several pages like http://wotlk.openwow.com or http://wowhead.com/

**Include Screenshots from the issue if necessary**

Note: If you complete Battling the Elements, it completes the quest for you.

**Comment by Golganeth** [comment]
There should not be any dialogue with King Jokkum. Make sure to read sources to know how quests work. Works as intended

Closed
