### ISSUE TITLE
Deep Ocean, Vast Sea bug

### ISSUE THREAD

**Issue by zerozero7** [dalaranwow/dalaran-wow#3739]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (OLD - ... tags should no longer be used)
[//]: # (Priority - ... tags are assigned by team members)

**Description**: Can't collect quest item from container

**Current behaviour**: After clicking on lockbox, there is no "container" field with quest item

**Expected behaviour**: There should be quest item inside the lockbox

**Steps to reproduce the problem**:

1. Click on  lockbox

**Include proofs for this behaviour**

http://www.wowhead.com/item=12192/mist-veils-lockbox#screenshots

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**
Quest id: 982

**Comment by Golganeth** [comment]
Fixed in-game. This is a rare and general issue with game objects, where they get stuck.
The quest itself works fine. Try again now

Closed
