### ISSUE TITLE
[BUG] SHAMAN ENHANCER SUMMONING FERAL SPIRITS RESETTED ABILITIED

### ISSUE THREAD

**Issue by xeon001** [dalaranwow/dalaran-wow#3745]
Hi there,

Each time I newly cast "feral spirit" with my enhancer, the stun of the wolves is resetted on automatic even though I just have put it on manual the last time I summoned them. 

Is this possible to be fixed? 

Very Best Regards

Nipok

**Comment by Golganeth** [comment]
You should try to disable the skills through your pet's spellbook for now.
#1021
