### ISSUE TITLE
Mail

### ISSUE THREAD

**Issue by SweVulpesZerda** [dalaranwow/dalaran-wow#3746]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (OLD - ... tags should no longer be used)
[//]: # (Priority - ... tags are assigned by team members)

**Description**: send mail from one character to another but the items just dissaperd

**Current behaviour**: I sent a mail from my mage to my priest and attached my heirloom gear but the gear just dissaperd and now its gone

**Expected behaviour**: i want my gear

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Include proofs for this behaviour**

You can research this on several pages like http://wowhead.com or http://wowwiki.wikia.com or http://www.youtube.com/
Issues without proofs will be closed and tag On Hold will be added until the proof is provided.

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

You can research this on several pages like http://wotlk.openwow.com or http://wowhead.com/

**Include Screenshots from the issue if necessary**

**Comment by robinsch** [comment]
Please write a ticket ingame.

**Comment by SweVulpesZerda** [comment]
Mail send from character Disconected to Iamatank it was a chest piece a
staff and shoulders

Den 6 okt 2016 17:25 skrev "robinsch" <notifications@github.com>:
