### ISSUE TITLE
Quest: Adversarial Blood

### ISSUE THREAD

**Issue by DrFuler** [dalaranwow/dalaran-wow#3750]
**Description**: The quest Adversarial Blood (Terokkar Forest) doesn't seems to be working properly.

**Current behaviour**: In the quest, you are supposed to summon 4 mobs using the dialog option of the Skull Pile, which is an object in the middle of Terokk's Rest. However, the only dialog available is for summoning Terokk himself, which I can only assume is the next quest in the quest line. Since I can't summon any of the 4 mobs to complete this quest, I can't get the Time-Lost Offering item to actually summon Terokk. I do have at least 10 Time-Lost Scrolls in my inventory, the items necessary for summoning one of the mobs.

**Expected behaviour**: There should be 4 dialog options right now, one for each one of the mobs.

**Steps to reproduce the problem**:

1. Get the quest.
2. (maybe) Farm the Time-Lost Scrolls (the dropping of those is working fine)
3. Try to summons the mobs through the Skull Pile.
4. Fail.

**Include proofs for this behaviour**

http://www.wowhead.com/quest=11072/adversarial-blood#comments

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**: Object 185913 (Skull Pile)

**Include Screenshots from the issue if necessary**

https://s16.postimg.org/3r83djead/Wo_WScrn_Shot_100716_140618.jpg

**Comment by Golganeth** [comment]
The quest works as intended. There shouldn't be 4 dialog options on Terokk's pile.

Closed

**Comment by DrFuler** [comment]
I'm sorry for misreading it.
