### ISSUE TITLE
Quest: A Fall From Grace

### ISSUE THREAD

**Issue by NJdeering** [dalaranwow/dalaran-wow#3751]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (OLD - ... tags should no longer be used)
[//]: # (Priority - ... tags are assigned by team members)

**Current behaviour**: When you ring the bell, the guards do not move. The High Abbot does not talk to you.

**Expected behaviour**: The guards should leave once the bell is rung and go up to the top of the tower. The High Abbot's dialogue changes to something else to complete the quest.

**Comment by Pentex11** [comment]
Can confirm. If you ever encounter this bug, make a ticket and a GM will assist you in completing it, while it's being worked on.

**Comment by ImprezaWoW** [comment]
Can not confirm on live. There are 2 guards besides High Abbot Landgren,  once you pull the rope they both say:

> Devout Bodyguard says: Hey, who rang the bell?
> Devout Bodyguard says: Hey, who rang the bell?

and they both run up to the Abbey Bell Rope, then turn around and run back. There is enough time to talk to High Abbot Landgren.

Can only assume that["At least 2 bodyguards are standing on top of each other when I attempted to run this quest."]( https://github.com/dalaranwow/dalaran-wow/issues/289#issuecomment-126271349).
Meaning, while the 2 original bodyguards run up, the duplicates are not leaving Landgren's side.
That is not the case now, but I guess it can be checked out what makes duplicates spawn unnaturally.

Anyhow, I've seen this quest bug out in this manner around once/twice a year and a server reset fixes the issue. It is working now and GM assistance is not needed.

**Comment by roblockster** [comment]
Seems to be same issue as in #289. Perhaps this works sometimes, but it's bugged out. It's possible what is causing it is some weird combination you wouldn't see on PTR: two people doing quest independently, or someone pulling rope without the disguise? IDK
