### ISSUE TITLE
Hunter pet's damage

### ISSUE THREAD

**Issue by Tritonek** [dalaranwow/dalaran-wow#3771]
Hello,

there is an issue with hunter pet's damage. The problem has been there for a while now. Hunter pets deal ridiculously low damage with their **Bite (rank 11)** ability. The damage is even lower than they do with their auto attacks. And since the pets are the main source of damage for Beast master hunters, they make this spec unplayable. (Bite does around 150 damage in beast mastery spec). While on other servers it is like three times more. I have not tried any pet with claw, but I suppose the same problem would occur.

I know most of the people will say, play maksmanship or survival hunter, you do not need the pet that much in these two specs, but still I think it is something that might be worth fixing, because BM hunters are kinda fun :).

Regards,
Furax

**Comment by ImprezaWoW** [comment]
Would appreciate if you used the template and added proof such as screenshots of how it is, and if possible, of how it should be.

**Comment by Tritonek** [comment]
Alright, I made a new ticket, this one can be closed.
