### ISSUE TITLE
Hunter pet damage

### ISSUE THREAD

**Issue by Tritonek** [dalaranwow/dalaran-wow#3774]
**Description**: 
Hello,
there is an issue with hunter pet's damage. The problem has been there for a while now. Hunter pets deal ridiculously low damage with their Bite (rank 11) ability. The damage is even lower than they do with their auto attacks. And since the pets are the main source of damage for Beast master hunters, they make this spec unplayable. (Bite does around 150 damage in beast mastery spec). While on other servers it is like three times more.

I compared the damage from Dalaran server and Warmane server (Blackrock PVP realm).

**Current behaviour**: As said above, the pet's damage is very low compared to the dmg from other servers. From the bite ability it is like 3 times lower, and auto attacks are probably halved.

**Expected behaviour**: Instead of doing some 150 damage with bite and over 200 damage with auto attacks to a cloth user (not even talking about other armor users), the damage should be way higher.

**Steps to reproduce the problem**:
1. Increase the damage of pet's auto attacks.
2. Increase tha damage of pet's ability Bite(rank 11)  http://www.wowhead.com/spell=17253/bite

**Include proofs for this behaviour**
Screenshots from Dalaran server (with my hunter Furax) and Warmane server (with my hunter Trito)

![1](https://cloud.githubusercontent.com/assets/18738446/19220247/18ff3464-8e29-11e6-8fa1-8b5299515808.jpg)
![2](https://cloud.githubusercontent.com/assets/18738446/19220248/1e0df4fe-8e29-11e6-9eb5-a0727d3aeee2.jpg)

**Comment by Edzero** [comment]
If possible could you try to find the co-efficient for the abilities that are doing incorrect damage and form them into a table? It would make it easier for the developers if they have more information to help them.

Thank you.

**Comment by Tritonek** [comment]
(Bite rank 11) spell code 52474
(Claw rank 11) spell code 52472

The coefficients should be:
the damage formula is the same of cataclysm

min damage = (118 + ((RAP * 0.40) * 0.20)) phisical damage
max damage = (168 + ((RAP * 0.40) * 0.20)) phisical damage

I found it on some other forum, where someone was reporting the bug (from the year 2011):
https://github.com/TrinityCore/TrinityCore/issues/3253

Sadly I cannot find any website to prove it right or wrong, but after the calculations the damage for the abilities fits.

**Comment by Edzero** [comment]
Excellent.

**Comment by robinsch** [comment]
On PTR.

**Comment by Edzero** [comment]
Bite ability is still not scaling with the gear of the Hunter.

It seems to be within the range of the tooltip damage (118-168) regardless of the stats of the hunter.

**Comment by Rushor** [comment]
we need the gernal petscale update first:

Core/Pet: Corrected scaling in InitStatsForLevel

This was added in https://github.com/dalaranwow/dalaran-wow/issues/3088, so pls test this ticket once https://github.com/dalaranwow/dalaran-wow/issues/3088 was applied on ptr again. ty

**Comment by robinsch** [comment]
@TeridanDW Can you test this?

**Comment by TeridanDW** [comment]
I am not  sure here. If I use this:

> min damage = (118 + ((RAP * 0.40) * 0.20)) phisical damage
> max damage = (168 + ((RAP * 0.40) * 0.20)) phisical damage

damage still seems low, because target has 0 resilience and 0.57% prysical reduction from armor.
Then for min damage --> (118 + ((761* 0.40) * 0.20)) = 178.88
and the values are lower on PTR:
![wowscrnshot_101817_154759](https://user-images.githubusercontent.com/6797611/31719560-8aa589aa-b41c-11e7-966a-d6080abbd73b.jpg)

**Comment by TeridanDW** [comment]
Updated above.

**Comment by AttendantTock** [comment]
Hello everyone,
Here are some numbers I produced to highlight the difference between measured and expected:

> **Notes:**
> There is a 0.6% damage reduction via armor of target (naked lvl80 gnome).
> NO other modifier (hunter talents, pet talents, happiness, glyphs, any kind of buff/debuff).
> AP value used are flat during the test runs (no procs, no cooldowns).

> **TEST RUN NAME (PlayerRangedAP)**
> - measured:
>  	 Bite ability damage / normalised hits (= #hits + 2x #crits)
> - formula:
>  	 uses the proposed formula written above (average base + 8% scaling on PlayerRangedAP)
> 		 => 0.5 * ((118 + PlayerRangedAP * 0.4 * 0.2) + (168 + PlayerRangedAP * 0.4 * 0.2))
> 		 => 143 + PlayerRangedAP * 0.08


**NAKED BITE TEST (420)**
 - measured: 50683/346 = **146** per hit
 - formula: 143 + 420 * 0.08 = **177**

**1k0 AP BITE TEST (1036)**
 - measured: 51880/331 = **156** per hit
 - formula: 143 + 1036 * 0.08 = **226**

**2k4 AP BITE TEST (2400)**
 - measured: 54101/302 = **179** per hit
 - formula: 143 + 2400 * 0.08) = **335**

**3k3 AP BITE TEST (3317)**
 - measured: 50273/261 = **193** per hit
 - formula: 143 + 3317 * 0.08 = **408**

**4k5 AP BITE TEST (4483)**
 - measured: 50133/237 = **212** per hit
 - formula: 143 + 4483 * 0.08 = **502**

**5k2 AP BITE TEST (5237)**
 - measured: 50930/227 = **224** per hit
 - formula: 143 + 5237 * 0.08 = **562**

**6k6 AP BITE TEST (6633)**
 - measured: 50373/205 = **246** per hit
 - formula: 143 + 6633 * 0.08 = **674**

**Comment by robinsch** [comment]
Yeah it takes the pet attack power -> so it's like basedmg + playerAP * 0.22 * 0.08

**Comment by robinsch** [comment]
Ref: https://github.com/dalaranwow/principal/commit/b916132688118897687caf225cfbceb9ca1d8ca4

**Comment by Lothloryen** [comment]
On PTR now.

**Comment by AttendantTock** [comment]
Hello,

I tested the fix and the numbers seem alright now:

6k6 RangedAP give ±650 dmg/bite
![capture d ecran 2017-10-22 a 16 44 54](https://user-images.githubusercontent.com/29557022/31863663-7e930fa0-b748-11e7-87ab-8d3d9fffaeb1.png)

3k5 RangedAP give ± 420 dmg/bite
![capture d ecran 2017-10-22 a 16 49 38](https://user-images.githubusercontent.com/29557022/31863696-13bc0492-b749-11e7-93f8-c9084f0bf5e5.png)
