### ISSUE TITLE
Log in update

### ISSUE THREAD

**Issue by oren7** [dalaranwow/dalaran-wow#3777]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (OLD - ... tags should no longer be used)
[//]: # (Priority - ... tags are assigned by team members)

**Description**:

**Current behaviour**: I try to login WoW needs update update dosent work need restart restart dosent help

**Expected behaviour**: Should not ask for update

**Steps to reproduce the problem**:

1. Log in 
2. 
3. 

**Include proofs for this behaviour**

You can research this on several pages like http://wowhead.com or http://wowwiki.wikia.com or http://www.youtube.com/
Issues without proofs will be closed and tag On Hold will be added until the proof is provided.

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

You can research this on several pages like http://wotlk.openwow.com or http://wowhead.com/

**Include Screenshots from the issue if necessary**

**Comment by Majd123** [comment]
Are you sure that you are using your account name and not your e-mail adress? The client asks for an update whenever you use the e-mail adress instead of the account name.

**Comment by Golganeth** [comment]
Invalid report. Run WoW as Admin and make sure you are using your account name to login, and not your e-mail.

Closed

**Comment by oren7** [comment]
still dosent let me says "unable to connect"

2016-10-16 15:32 GMT+03:00 Golganeth <notifications@github.com>:

**Comment by Golganeth** [comment]
You should use the correct client and correct realmlist. **set realmlist logon.dalaran-realmlist.org**
