### ISSUE TITLE
Petrified Lichen Guard

### ISSUE THREAD

**Issue by Bartimeut** [dalaranwow/dalaran-wow#3778]
**Description**: http://www.wowhead.com/item=25828 

**Current behaviour**: Currently when a block happens it deals a flat 12-14 damage shown as lightning shield in recount.
**Expected behaviour**: What it should be doing is applying a stacking poison dot every time a block happens.
http://www.wowhead.com/spell=32642

**Steps to reproduce the problem**:

1. Ran several dungeons and checked recount
2. 
3. 

**Include proofs for this behaviour**
![wowscrnshot_101616_112216](https://cloud.githubusercontent.com/assets/22870675/19418514/1c9b7fb4-9393-11e6-885d-edc780b17ce0.jpg)

**Include Screenshots from the issue if necessary**

**Comment by Golganeth** [comment]
#3135
