### ISSUE TITLE
Quest: Return of the High Chief

### ISSUE THREAD

**Issue by Crispybuilt** [dalaranwow/dalaran-wow#378]
Quest Return of the High Chief - 12069

Issue: The quest doesn't have event or script which has to be included, it is too easy for players to complete it.
 The problem is, after us the item on the specfic location, object spawns near you and you are able to loot it and complete the quest instantly, That is not how it's supposed t work.

How it's supposed to work: You have to click on the object, then the NPCs talks, goes near the water and a encounter between Taurens and Spiders begins as you can see on the video. After some time, the NPC [Under-King Anub'et'kan]  has to spawn and you have to fight him. After he is defeated, he will drop down his container (object) which contains the quest item.

Temporary solution (by default): The object is lootable by all the players around the zone / area.
![image](https://f.cloud.github.com/assets/5054924/923699/05151828-ff53-11e2-8768-b33313028cb7.png)

http://www.wowhead.com/quest=12069/return-of-the-high-chief
http://www.youtube.com/watch?v=m26PcoscSW8
http://wotlk.openwow.com/quest=12069

**Comment by Lothloryen** [comment]
Working properly since long time ago.

**Comment by Golganeth** [comment]
For the 'item is already being used' issue, see #58 for workarounds.
