### ISSUE TITLE
Glyph of Charge not working, still 25 yards, tooltip @ 30 yards

### ISSUE THREAD

**Issue by Larsy93** [dalaranwow/dalaran-wow#3781]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (OLD - ... tags should no longer be used)
[//]: # (Priority - ... tags are assigned by team members)

**Description**: The tooltip updates to reflect the change to 30 yards, but the range of the spell doesn't increase.

**Current behaviour**: The tooltip updates to reflect the change to 30 yards, but the range of the spell doesn't increase.

**Expected behaviour**: The spell should increase its range up to 30 yards like the tooltip and the glyph says it should.

**Steps to reproduce the problem**:

1. get a warrior
2. get charge glyph
3. compare charge & taunt since taunt is a 30 yard spell.
4. see that it doesnt work

**Include proofs for this behaviour**

https://www.youtube.com/watch?v=xs3xeIxQdng

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

http://wotlk.openwow.com/item=43397

**Include Screenshots from the issue if necessary**

https://www.youtube.com/watch?v=xs3xeIxQdng

**Comment by kalvindeane** [comment]
#3722
