### ISSUE TITLE
Wild Hunt [Hunter]

### ISSUE THREAD

**Issue by Serpentsting** [dalaranwow/dalaran-wow#3783]
**Description**:
The talent of Tenacity pets of hunters "Wild hunt" does not increase stamina or AP.

**Current behaviour:** Tell us what happens in detail (Where, When, What, Why, Who)
The talent isn't working

**Expected behaviour**: Tell us what should happen instead
Rank 1/2
It should: Increase the contribution your pet gets from your Stamina by 20% and attack power by 15%
Rank 2/2
It should: Increase the contribution you pet gets from your Stamina by 40% and attack power by 30%

**Steps to reproduce the problem:**

1. Tame a Tenacity Pet
2. Take "Wild Hunt" Talent
3. It doesn't do anything.

Its a very critical pet talent for hunters
Also #1378 doesn't fixed.

**Comment by plznoz** [comment]
#2910

**Comment by Serpentsting** [comment]
#2910 closed as i see

**Comment by kalvindeane** [comment]
Make sure you are dismissing the pet and then bringing it out again, as mentioned in #2910.

This is still working correctly on the PTR so I'll close this for now. If dismissing and calling the pet again still doesn't work for you please provide proof in #2910.
