### ISSUE TITLE
Error Sound

### ISSUE THREAD

**Issue by Lightburns** [dalaranwow/dalaran-wow#3784]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (OLD - ... tags should no longer be used)
[//]: # (Priority - ... tags are assigned by team members)

**Description**: Whenever you attack and kill a NPC a error sound is triggered.

**Current behaviour**: After killing a NPC with a melee weapon there is a error sound in the background and a message appears on screen displaying 'Invalid target'.

**Expected behaviour**: After killing a NPC there should be no error sound in the background or error displayed text prompt.

**Steps to reproduce the problem**:

1.  Create a Blood Elf Paladin, male or female.
2.  Attack nearby Mana Wyrm NPC or any other NPC.
3.  When delivering a killing blow, the 'Invalid Target' red text appears on the screen and an error sound is triggered in the background.

**Include proofs for this behaviour**

You can research this on several pages like http://wowhead.com or http://wowwiki.wikia.com or http://www.youtube.com/
Issues without proofs will be closed and tag On Hold will be added until the proof is provided.

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

You can research this on several pages like http://wotlk.openwow.com or http://wowhead.com/

**Include Screenshots from the issue if necessary**

**Comment by Crispybuilt** [comment]
That looks like a Client issue rather than a server side issue.
Re-check this with a different client.

**Comment by Golganeth** [comment]
Indeed, I don't think this a server side issue at all. I can't reproduce it either. Please make sure it is not your client or any of the addons you may be using.

Closed
