### ISSUE TITLE
The Cell quest bugged

### ISSUE THREAD

**Issue by Kixur413** [dalaranwow/dalaran-wow#3785]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (OLD - ... tags should no longer be used)
[//]: # (Priority - ... tags are assigned by team members)

Quest bug: The Cell.

General Cerulean is bugged out. Cannot cast or melee

**Expected behaviour**: Shouldnt be bugged in the ground.

**Comment by Golganeth** [comment]
Fixed in-game. General and rare pathfinding issue with some NPCs. Feel free to make an in-game ticket should you encounter a similar issue again in the future

Closing since the related quest works and the default NPC position is correct.
