### ISSUE TITLE
Kaw The Mammoth Destroyer bugged, again.

### ISSUE THREAD

**Issue by Kixur413** [dalaranwow/dalaran-wow#3786]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (OLD - ... tags should no longer be used)
[//]: # (Priority - ... tags are assigned by team members)

Kaw feel through the earth again. You can /tar him but cant see.

**Comment by Golganeth** [comment]
Fixed in-game. General and rare pathfinding issue with some NPCs. Feel free to make an in-game ticket should you encounter a similar issue again in the future.

**Comment by TheRealestMcCoy** [comment]
I see it is bugged again. However opening a ticket some times at night my time sucks since no gm's are usually around. Any way of moving him just off the platform so this wont happen again? I know it wont be blizz like but the quest should be more complete-able instead of waiting for GM's to fix.

**Comment by Rushor** [comment]
What exactly was bugged? If the issue still exists please open up a detailed new issue with the error/fault. Thank you! :)
