### ISSUE TITLE
[Quest] Thel'zan's Phylactery'

### ISSUE THREAD

**Issue by styled81** [dalaranwow/dalaran-wow#3787]
This quest happens in Dragonblight.

[http://www.wowhead.com/quest=12467/chasing-icestorm-thelzans-phylactery](url)
[https://www.youtube.com/watch?v=rzY3ztPHtho](url)

I want to spawn Icestorm by speaking with the gryphon rider "wyrmbait". 
The problem is that it is impossible to speak with wyrmbait because their is no option to speak with him.

If i could speak with him he will get icestorm so i could kill the dragon  and loot the quest item from him.

I can find this same problem twice here but both are closed and temperarely fixed back then.

[https://github.com/dalaranwow/dalaran-wow/issues/2533](url)
[https://github.com/dalaranwow/dalaran-wow/issues/449](url)

**Comment by Edzero** [comment]
This was working a couple of weeks ago for me.

Most likely the NPC needs to be reset I would think. Make an in-game ticket and keep me informed here when you get an answer.

**Comment by styled81** [comment]
Ok, the quest was reset when i arrived for 5 th in two days and it worked perfectly! whoohoo
So if somebody resetted this quest ty very much, now i can finish this fabolus questline!

**Comment by Rushor** [comment]
> Most likely the NPC needs to be reset I would think. Make an in-game ticket and keep me informed here when you get an answer.

The reason for this problem is that the creature sometimes forget to readd it's gossip option. If we set him active, the problem should be solved

**Comment by Rushor** [comment]
Scripts/The Battle for the Undercity: Set "Wyrmbait" and Icestorm always active 

* they will no longer stuck in one place and "Wyrmbait" will always readd his gossip option if you don't follow his path
* closes https://github.com/dalaranwow/dalaran-wow/issues/3787
* updates https://github.com/dalaranwow/dalaran-wow/issues/2404
* commit: 7d69df31096663c1074f161acfc50a92468d8a8a

**Comment by bay530** [comment]
npc "wyrmbait" still needs to be reset sometimes to add gossip option.

**Comment by Rushor** [comment]
the fix was not yet applied on live.

**Comment by meinhardis** [comment]
when fix will be applied? (thx in advance)

**Comment by Rushor** [comment]
First the fix needs to be applied on PTR. Then a tester will recheck the fix and make shure that everything works fine with fix. Then if loth has time he will applay the fix on the live realm.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by beregas** [comment]
Talked to Wyrmbait, he rushed forward, 1 min later nothing happened, he returns, and cant talk to him again.
Broken event.

**Comment by Rushor** [comment]
that was also fixed on PTR

**Comment by TeridanDW** [comment]
Hello, after few attempts on this encounter this:

> Talked to Wyrmbait, he rushed forward, 1 min later nothing happened, he returns, and cant talk to him again.

is still happening, also according to https://www.youtube.com/watch?v=rzY3ztPHtho
 -  npc https://wowgaming.altervista.org/aowow/?npc=27843 should be flying not walking
 -  npc https://wowgaming.altervista.org/aowow/?npc=26287 should be flying higher from the ground and land when he reaches his last waypoint
 - the visual spell (chains) from the cannons were used only the first time I tryed the encounter and never again after that.

Here is what I mean within a video:
https://www.youtube.com/watch?v=stVCJfP1Vb0&feature=youtu.be

Note: Sorry for the music, forgot to turn it off, mute it if you want.

**Comment by TeridanDW** [comment]
Updated the comment above after the recent update on PTR.
Up to @Rushor to decide if he wants to be pushed like this or work on the visual issues (pointed above).

**Comment by Rushor** [comment]
yeah better push it like that because the issue that the creature is not active breaks the whole questchain

**Comment by DalaranDude** [comment]
Please reset "Wyrmbait" because no one can currently talk to him to start the event

**Comment by Selyara** [comment]
The Quest is still bugged, I cant even talk to Wyrmbait and GMs dont reply to my ticket.

**Comment by ChickenSteven** [comment]
Seem's Wyrmbait is still bugged and you cannot even speak to him and no reply from GM's, Come on guys! I'm trying to level here!
