### ISSUE TITLE
Decimation and Hand of Protection interaction

### ISSUE THREAD

**Issue by strobe-light** [dalaranwow/dalaran-wow#3789]
**Current behaviour**: Currently, a warlock under the effect of the buff Hand of Protection is unable to gain the Decimation buff at all (the warlock becomes unable to apply/refresh the Decimation buff, due to being immune to it)

**Expected behaviour**: There should be no such interaction between the spells.

**Steps to reproduce the problem**:
1. Play a demonology warlock
2. Get a paladin to cast Hand of Protection on you
3. Shadow Bolt, Incinerate or Soul Fire a target below 35%
4. Receive no Decimation buff

**Include proofs for this behaviour**

https://www.youtube.com/watch?v=04_Jfft8Q7Y
You can see on the scrolling battle text that I am getting immunity to the Decimation effect, and the buff is not refreshing.

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**
Decimation: http://wotlk.openwow.com/spell=63167
Hand of Protection: http://wotlk.openwow.com/spell=10278

**Comment by robinsch** [comment]
On PTR.

**Comment by TeridanDW** [comment]
Works as intended on ptr.

**Comment by TeridanDW** [comment]
Hm this used to work on the old PTR, however currently it doesn't.
You can see the buff from decimation gets "absorbed" by hand of protection.
![image](https://user-images.githubusercontent.com/6797611/31815487-7f32d38c-b595-11e7-95a6-da552585c54f.png)

**Comment by robinsch** [comment]
Updated.

**Comment by TeridanDW** [comment]
Works as intended on PTR.
