### ISSUE TITLE
druid restoration

### ISSUE THREAD

**Issue by fixlol** [dalaranwow/dalaran-wow#3792]
I ask gentlemen gm to review the restoration druid, I played in many WotLK bliz like servers but in this server the druid restoration  did something strange on healing (care too much), as well as insect swarm(http://wotlk.openwow.com/spell=48468) make damage 900/1000 dmg per second, and it seems to me too much, I know wrathefull restoration druid who do not care too much so as in this server, and do not do so much damage that I receive on this server, I have more than 1200 resilence and receive 1000 dmg insect swarm to the second I think too much. I'm not an expert druids, but please gm of giving a controlled in talent because there is something wrong

**Comment by Golganeth** [comment]
Please make a proper report with the template and add specific information about what you are reporting, as well as valid proof/evidence, so that we can take a look.

Invalid, closed.
