### ISSUE TITLE
Ulduar - Thorim Does not Gain any Stacks (Damage Buff) of Lightning Charge

### ISSUE THREAD

**Issue by Zelwindin** [dalaranwow/dalaran-wow#3796]
**Description**: 

Thorim, in both 10 and 25 man Ulduar, does not gain any "stacks" of his damage buff as he should.

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)

Thorim does not gain any stacks of his damage buff.

**Expected behaviour**: Tell us what should happen instead

After the arena/tunnel events, Thorim engages the raid. At this point, every so often, he should be gaining a stacking damage buff.

**Steps to reproduce the problem**:
1. Engage Thorim in Ulduar 10 or 25
2. Complete the Arena/Tunnel (phase 1) of the encounter and aggro Thorim.
3. In phase 2 of the encounter, observe that Thorim does not gain any stacks of his damage buff (which is caused by the skill Lightning Charge).

**Include proofs for this behaviour**

I can provide any proof as needed, but it's a simple bug to reproduce and everyone who has ever done the encounter knows that he should be gaining the stacks :). PS: This bug did not exist on Dalaran until about a month or so ago.

You can research this on several pages like http://wowhead.com or http://wowwiki.wikia.com or http://www.youtube.com/
Issues without proofs will be closed and tag On Hold will be added until the proof is provided.

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

Thorim: 32865
Lightning Charge: 62466

You can research this on several pages like http://wotlk.openwow.com or http://wowhead.com/

**Include Screenshots from the issue if necessary**

**Comment by Crispybuilt** [comment]
I knew there was something weird about Thorim the last time I did it.
We tried Hard Mode and he really wasn't gaining any stacks from Lighting Charges. And now we have the same confirmation from the easy mode as well.

Are the stacks possibly just invisible? Yet he's still gaining them?
Who knows.

**Comment by Zelwindin** [comment]
This is now working properly! On both normal and hard mode 25! Thank you! :).

Haven't tried on 10 yet, when I do I will post here.

**Comment by Lothloryen** [comment]
Hello there,

Yes, it got broken with one of the latest updates. However it was corrected again 2 days ago.

Thank you for the reports.
