### ISSUE TITLE
Herald of War

### ISSUE THREAD

**Issue by MrAndersonX** [dalaranwow/dalaran-wow#3798]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (OLD - ... tags should no longer be used)
[//]: # (Priority - ... tags are assigned by team members)

**Description**:
As the quest description says, a portal should open up and you should be able to talk with Thrall and continue the chain quest. That doesn't happen.
**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)

**Expected behaviour**: Tell us what should happen instead

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Include proofs for this behaviour**

You can research this on several pages like http://wowhead.com or http://wowwiki.wikia.com or http://www.youtube.com/
Issues without proofs will be closed and tag On Hold will be added until the proof is provided.

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

You can research this on several pages like http://wotlk.openwow.com or http://wowhead.com/
http://www.wowhead.com/quest=13257/herald-of-war
**Include Screenshots from the issue if necessary**

**Comment by Edzero** [comment]
Duplicate thread, closing.

https://github.com/dalaranwow/dalaran-wow/issues/2404
