### ISSUE TITLE
A Ritual Of Flame: Leyara never comes out

### ISSUE THREAD

**Issue by AurexXx** [dalaranwow/dalaran-wow#3799]
**Description**: Hi, 
It'ss about 3 hours that I try to complete  [A Ritual of Flame] quest on my 85lvl hunter named "Aurex" nothing works Leyara never comes from portal bar filled up tryed:
1. Abandoning an retaking quest
2. Tryed not killing mobs and killing
3.Tryed reloading, login out and in, just siting in one place till I afk nothing,
p.s. I did all steps once with pet and once without it rly nothing works can't think of anything else google and wowhead cant offer anything eather plz help.
p.p.s. few times bar filled up in mather of seconds
![wowscrnshot_110116_210225](https://cloud.githubusercontent.com/assets/21065406/19903256/b45163b0-a076-11e6-8c6f-4b56ef6ad7ae.jpg)

**Comment by Edzero** [comment]
Dalaran-WoW is a WotLK server.

Looks like you've posted in the wrong repository.
