### ISSUE TITLE
Warrior: Charge doesn't aim correctly

### ISSUE THREAD

**Issue by Gordin508** [dalaranwow/dalaran-wow#38]
I have this issue myself, but also other players are reporting it:
Sometimes (the bug appearance for me was around 10% of charge uses i guess) the warrior doesn't directly charge towards the target when used, but runs to a random spot in the approximate direction (i have experienced deviations of up to 45 degrees so far). The target still gets stunned, but the charge just ends at an empty spot instead of infront of the enemy.

**Comment by taralej90** [comment]
The pathing for Charge works in a really weird way. As it was reported, sometimes the mob gets stunned and I'm running into some random direction close to it. Generally speaking, pathing through obstacles is problematic on the server and Warriors are the class that suffers the most from this.

**Comment by Rushor** [comment]
merged issue with https://github.com/dalaranwow/dalaran-wow/issues/2823, pls add any further information in https://github.com/dalaranwow/dalaran-wow/issues/2823
