### ISSUE TITLE
CANT CREATE ACCOUNT

### ISSUE THREAD

**Issue by atch95** [dalaranwow/dalaran-wow#3801]
have been trying to create an account for 2 days now, ive tried over 5 browsers and tried on 3 different internets and still getting this error
An error has ocurred during your account registration, please try again and if the problem persists please contact with the adminsitration.
![omg](https://cloud.githubusercontent.com/assets/23213198/19927680/619a1de8-a0c0-11e6-938b-b1ba5ddbfb9d.png)

**Comment by Rushor** [comment]
You should try with a different browser and/or a longer last name, add some letters to it if the problem persists.

Closed.
