### ISSUE TITLE
Satchel Of "Helpful" Goods (Chance to roll caster item is too low.)

### ISSUE THREAD

**Issue by Elfonee** [dalaranwow/dalaran-wow#3802]
Issue: https://www.youtube.com/watch?v=sORxP-X6_NU&feature=youtu.be

The Satchels chance to roll a Agility/Stamina on a level 36-45 bag is way too high. (http://wowwiki.wikia.com/wiki/Satchel_of_Helpful_Goods) (Lower level versions are wonky as well but I don't have that recorded so I'm starting here.

It doesn't say what the odds are of getting a melee or caster item from the bag are but I find it hard to believe the average is somewhere between 13% - 20%. In the video 25% of the bags contained a caster item 10/40. However, in my experience that's just on a good day of opening bags, and the real average is much lower than 25%. I've opened I don't even know how many bags from level 36-45 (36-45 only awards Rings and Shoulders from opening the Satchel.) I would assume around 200-250 bags between all of my characters and I still need 3 more rings, it's rather baffling.

**Comment by Rushor** [comment]
i moved your issue and your description to https://github.com/dalaranwow/dalaran-wow/issues/29
