### ISSUE TITLE
Can't link hc DC

### ISSUE THREAD

**Issue by ashido96** [dalaranwow/dalaran-wow#3803]
Attempt to link heroic death choice in chat
Proceed to get stopped by url detector
This also occurs with one of the two caster necks from the heroic eye of eternity quest, sorry I can't remember/get info on which one it was.

**Comment by Crispybuilt** [comment]
Actually it's not only Death's Choice issue, but a couple more of HC items from Trial of the Grand Crusader can't be linked for some reason. They are just filtered as they are links, weird issue indeed.

**Comment by Pentex11** [comment]
Greetings. We are aware of the current situation, and it is already being worked on.
Have a nice day.
Pentex

Closed.
