### ISSUE TITLE
[Quest] Blood Oath of the Horde

### ISSUE THREAD

**Issue by Rushor** [dalaranwow/dalaran-wow#3805]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (OLD - ... tags should no longer be used)
[//]: # (Priority - ... tags are assigned by team members)

**Description**:

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
http://de.wowhead.com/quest=11983/blutschwur-der-horde#videos
The creatures doesn't transform once you selected their gossip options

**Expected behaviour**: Tell us what should happen instead
The creatures transform once you selected their gossip options (see http://de.wowhead.com/quest=11983/blutschwur-der-horde#videos and http://wotlk.openwow.com/npc=26433 http://wotlk.openwow.com/npc=26432

**Include proofs for this behaviour**
http://de.wowhead.com/quest=11983/blutschwur-der-horde#videos

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**
http://wotlk.openwow.com/npc=26433 http://wotlk.openwow.com/npc=26432

You can research this on several pages like http://wotlk.openwow.com or http://wowhead.com/

**Include Screenshots from the issue if necessary**
http://i.imgur.com/95eCxqS.jpg

**Comment by Rushor** [comment]
Scripts/Spells: Taunka'le Refugee Transform for quest: Blood Oath of the Horde
* the creatures will now transform once the gossip option was selected and the text was announced
* closes https://github.com/dalaranwow/dalaran-wow/issues/3805
* commit: c07f37146deefb7cb4b67617818d1e51e2acc58d

**Comment by TeridanDW** [comment]
I was told this is not on PTR yet, changing label.

**Comment by TeridanDW** [comment]
After a quick test on PTR, this:

> the creatures will now transform once the gossip option was selected and the text was announced

is not happening. 
 - I've also found a visual bug, if the player speaks with 1 of the npcs that is sleeping and sitting they don't lose their BYTE_1 and we get this:
![image](https://user-images.githubusercontent.com/6797611/31612883-fd970752-b289-11e7-91e7-daabe282c29a.png)

 - The sleeping should have a visual effect over them:
![image](https://user-images.githubusercontent.com/6797611/31612995-6de927c4-b28a-11e7-8c27-ce193d471729.png)
I think the spell is https://wowgaming.altervista.org/aowow/?spell=45787 but I'm not sure (not sniffed).

**Comment by Lothloryen** [comment]
Hello there,

It was my bad, it was missing one thing. Now it should be fine.

Thank you.
