### ISSUE TITLE
[Quest] From the Depths of Azjol-Nerub

### ISSUE THREAD

**Issue by Rushor** [dalaranwow/dalaran-wow#3806]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (OLD - ... tags should no longer be used)
[//]: # (Priority - ... tags are assigned by team members)

**Description**:
http://www.wowhead.com/quest=12036/from-the-depths-of-azjol-nerub

Will not be completed at the moment.

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
Will not be completed at the moment.

**Expected behaviour**: Tell us what should happen instead
One you run over the trigger, the quest should be completed.

**Include proofs for this behaviour**
http://www.wowhead.com/quest=12036/from-the-depths-of-azjol-nerub#videos:id=78088

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

http://www.wowhead.com/quest=12036/from-the-depths-of-azjol-nerub

**Comment by Rushor** [comment]
DB/Quest: From the Depths of Azjol-Nerub - now completable again

* closes https://github.com/dalaranwow/dalaran-wow/issues/3806
* commit: dc463317f44a1f318576022708ec8f17bd798812

**Comment by TeridanDW** [comment]
I was told this is not on PTR yet, changing label.

**Comment by TeridanDW** [comment]
According to this video:
https://www.youtube.com/watch?v=YjUpyVbpsXw
I wasn't able to get the credit, trigger not visible in GM mode.
