### ISSUE TITLE
[Quest] All Hail Roanauk!

### ISSUE THREAD

**Issue by Rushor** [dalaranwow/dalaran-wow#3807]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (OLD - ... tags should no longer be used)
[//]: # (Priority - ... tags are assigned by team members)

**Description**:
http://www.wowhead.com/quest=12140/all-hail-roanauk
Overlord Agmar get stuck if noone uses his gossipoption after the quest "All Hail Roanauk!" was accepted. He will stay there forever without resetting.

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
Overlord Agmar get stuck if noone uses his gossipoption after the quest "All Hail Roanauk!" was accepted. He will stay there forever without resetting.

**Expected behaviour**: Tell us what should happen instead
He should reset and run to his homeposition after 5 minutes.

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

http://www.wowhead.com/quest=12140/all-hail-roanauk

**Comment by Rushor** [comment]
DB/Creature: Overlord Agmar - Always reset after 5 Minutes

* closes https://github.com/dalaranwow/dalaran-wow/issues/3807
* commit: 6ffdc4f83f40838b9325ec93f0cd45339cb19ef9

**Comment by TeridanDW** [comment]
After few tests on this mini event here is what I saw:
 - npc https://wowgaming.altervista.org/aowow/?npc=26379 should lose BYTES_1 = 1 sitting during the event so we don't get this
![wowscrnshot_101617_124553](https://user-images.githubusercontent.com/6797611/31606027-995decc4-b270-11e7-8847-e8b467c2957d.jpg)
 - npc https://wowgaming.altervista.org/aowow/?npc=26379 should lose npcflag= 1 so this is not possible during the event:
![wowscrnshot_101617_125101](https://user-images.githubusercontent.com/6797611/31606159-04a55166-b271-11e7-8b5d-2201f383d177.jpg)
 - npc https://wowgaming.altervista.org/aowow/?npc=26379 is missing SET_ACTIVE = 1 so he doesn't get stucked if there is noone around him while the event is running
 - npc https://wowgaming.altervista.org/aowow/?npc=26437 that are part of this mini event are missing orientation change and kneel emote when they are around Icemist
![image](https://user-images.githubusercontent.com/6797611/31606681-72acc83c-b272-11e7-913d-6f7ddb6eae94.png)
 - npc https://wowgaming.altervista.org/aowow/?npc=26379 disappears way too fast, players should be able to turn the quests before he disappears.

reference from retail:
https://www.youtube.com/watch?v=z1cDafMJhgc

This:

> Overlord Agmar - Always reset after 5 Minutes

is working as intended on PTR.
