### ISSUE TITLE
[Quest] Spread the Good Word

### ISSUE THREAD

**Issue by Rushor** [dalaranwow/dalaran-wow#3808]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (OLD - ... tags should no longer be used)
[//]: # (Priority - ... tags are assigned by team members)

**Description**:
wotlk.wowhead.com/?quest=12218
If you eject from the vehicle, the vehicle will never despawn and it will not respawn at it's spawnplace. Due to this issue, some player will not find any vehicles around the horde base if the server is up for several hours.
**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
If you eject from the vehicle, the vehicle will never despawn and it will not respawn at it's spawnplace. Due to this issue, some player will not find any vehicles around the horde base if the server is up for several hours.
**Expected behaviour**: Tell us what should happen instead
The vehicle should despawn 10 seconds after the player is ejected.

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**
wotlk.wowhead.com/?quest=12218

**Comment by Rushor** [comment]
DB/Quest: Spread the Good Word - Despawn vehicle after 10 seconds after ejection

* closes https://github.com/dalaranwow/dalaran-wow/issues/3808
* commit: 0c291bd18e9e610ff5f30afd6de245372e6c9702

**Comment by TeridanDW** [comment]
On PTR this:

> Despawn vehicle after 10 seconds after ejection

is not happening, they stay where i left them.

**Comment by TeridanDW** [comment]
Works as intended on PTR now.

@Rushor maybe add a condition here so only players with quest https://wowgaming.altervista.org/aowow/?quest=12218 are able to enter the vehicle, currently everyone can.
