### ISSUE TITLE
[Spell] Devour Ghoul

### ISSUE THREAD

**Issue by Rushor** [dalaranwow/dalaran-wow#3809]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (OLD - ... tags should no longer be used)
[//]: # (Priority - ... tags are assigned by team members)

**Description**:
spell=50430 doesn't have any function. you can use the spell on the dragonvehicle for the quest : quest=12498
**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
spell=50430 doesn't have any function. you can use the spell on the dragonvehicle for the quest : quest=12498
**Expected behaviour**: Tell us what should happen instead
spell=50430 should regenerate the health and the mana of the dragonvehicle.

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**
spell=50430
quest=12498

**Comment by Rushor** [comment]
DB/Spell: Implement mechanic for spell 'Devour Ghoul'

* closes https://github.com/dalaranwow/dalaran-wow/issues/3809
* commit: d5ab2d31d7364b46e2d86a33efe4e949fd509024

**Comment by TeridanDW** [comment]
Works as intended on PTR.
