### ISSUE TITLE
[Quest] Return to Angrathar

### ISSUE THREAD

**Issue by Rushor** [dalaranwow/dalaran-wow#3810]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (OLD - ... tags should no longer be used)
[//]: # (Priority - ... tags are assigned by team members)

**Description**:
http://www.wowhead.com/quest=12500
After you completed the quest, you should see an ingame cinematic https://www.youtube.com/watch?v=iLANMJF-s5A
**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
After you completed the quest, you will not see the ingame cinematic
**Expected behaviour**: Tell us what should happen instead
After you completed the quest, you should see an ingame cinematic

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**
http://www.wowhead.com/quest=12500

**Comment by Rushor** [comment]
DB/Creature: Saurfang the Younger - Add movie after quest 'Return To Angrathar' is finished

* once you rewarded the quest 12500 you will see the ingame cinematic
* closes https://github.com/dalaranwow/dalaran-wow/issues/3810

**Comment by TeridanDW** [comment]
After trying it on 2 horde character without any addons with .add quest 12500 and manually turning it no cinematic was played for me.

**Comment by TeridanDW** [comment]
Works as intended on PTR now.
