### ISSUE TITLE
[bug] Prospecting sometimes fails, with no chat log entry

### ISSUE THREAD

**Issue by BloodyIron** [dalaranwow/dalaran-wow#3811]
**Description**:
10-15% of the time when I prospect ore, the game makes a ding sound and nothing comes out. My inventory doesn't change, the chat log says nothing. This has been consistently happening for over a week now.

**Expected behaviour**: Tell us what should happen instead
Prospecting should never fail.

**Steps to reproduce the problem**:

1. Prospect enough, say 10-15 stacks of Saronite ore, and pay attention to each prospect

**Comment by Rushor** [comment]
moved to https://github.com/dalaranwow/dalaran-wow/issues/230

**Comment by BloodyIron** [comment]
Thanks @Rushor ! my bad D:
