### ISSUE TITLE
quest item; shattered necklace

### ISSUE THREAD

**Issue by w00tnoway** [dalaranwow/dalaran-wow#3812]
lvl 37 item begins a quest but when right clicked you hear the error sound and nothing happens

**Comment by Rushor** [comment]
cannot confirm this. if you are alliance and at least level 37 you can start the quest http://i.imgur.com/lXMEgP1.jpg

**Comment by w00tnoway** [comment]
no no you have to try it as a horde character bro


________________________________
Van: Rushor <notifications@github.com>
Verzonden: dinsdag 8 november 2016 22:40
Aan: dalaranwow/dalaran-wow
CC: w00tnoway; Author
Onderwerp: Re: [dalaranwow/dalaran-wow] quest item; shattered necklace (#3812)


cannot confirm this. if you are alliance and at least level 37 you can start the quest http://i.imgur.com/lXMEgP1.jpg

[http://i.imgur.com/lXMEgP1.jpg]

-
