### ISSUE TITLE
debuff working incorrectly

### ISSUE THREAD

**Issue by w00tnoway** [dalaranwow/dalaran-wow#3813]
crushridge mage in ruins of alterac when it casts it's frost bolt that puts a debuff on you that slows you, the debuff is applied before the bolt actually hits you

**Comment by Rushor** [comment]
npc=2255

cannot confirm this http://i.imgur.com/1G311CV.jpg

the debuff will be applied once the bolt hits the player. maybe cuased by the huge freezes and lags recently
