### ISSUE TITLE
invisible wall undercity bug

### ISSUE THREAD

**Issue by w00tnoway** [dalaranwow/dalaran-wow#3817]
**Description**: invisible wall in undercity apothecarium please see screenshot where horse is shown jumping against invisible wall

**Current behaviour**: when trying to jump over that curb you run into an invisible wall, you also can not walk over the curb have you walk around it

**Expected behaviour**: being able to jump the curb

**Steps to reproduce the problem**:

1. go to the apothecarium
2. try to jump the curb shown in the screenshot

**screenshot**
http://imgur.com/a/lu4Iu

**Comment by Rushor** [comment]
That's not an issue. You were never able to jump over this back in wotlk from 2008 till 2010.

Btw such walls are integrated from the gameclient. I cannot be changed from the server and it's not a game issue.
