### ISSUE TITLE
invisible wall orgrimmar bug

### ISSUE THREAD

**Issue by w00tnoway** [dalaranwow/dalaran-wow#3819]
**Description**: run up at this curb in orgrimmar at a certain angle and you run into an invisible wall, its exactly at the spot depicted in the screenshot im supplying. not difficult to re-produce

**Current behaviour**: please see description

**Expected behaviour**: should not run into invisible wall

**Steps to reproduce the problem**:

1. run up at curb at certain angle coming out of The Drag

**screenshot**
http://imgur.com/a/9J9s2   character depicted running while not moving, sadly cannot supply video.

**Comment by Rushor** [comment]
There is no wall. http://i.imgur.com/pfJaPpN.jpg
try to get a fresh clean installed wotlk client.

**Comment by w00tnoway** [comment]
come ingame ill show  you it, its fairly easy to reproduce


________________________________
Van: Rushor <notifications@github.com>
Verzonden: woensdag 9 november 2016 11:06
Aan: dalaranwow/dalaran-wow
CC: w00tnoway; Author
Onderwerp: Re: [dalaranwow/dalaran-wow] invisible wall orgrimmar bug (#3819)


There is no wall. http://i.imgur.com/pfJaPpN.jpg
try to get a fresh clean installed wotlk client.

[http://i.imgur.com/pfJaPpN.jpg]

-

**Comment by w00tnoway** [comment]
you are standing at the wrong place


________________________________
Van: Rushor <notifications@github.com>
Verzonden: woensdag 9 november 2016 11:06
Aan: dalaranwow/dalaran-wow
CC: w00tnoway; Author
Onderwerp: Re: [dalaranwow/dalaran-wow] invisible wall orgrimmar bug (#3819)


There is no wall. http://i.imgur.com/pfJaPpN.jpg
try to get a fresh clean installed wotlk client.

[http://i.imgur.com/pfJaPpN.jpg]

-

**Comment by Rushor** [comment]
whatever causes that issue, it cannot be fixed by us, because it's a client side issue
