### ISSUE TITLE
players all naked at random moments/login

### ISSUE THREAD

**Issue by w00tnoway** [dalaranwow/dalaran-wow#3826]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (OLD - ... tags should no longer be used)
[//]: # (Priority - ... tags are assigned by team members)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Description**: everyone i see is naked, happens at random moments or at login

**Current behaviour**: please see description

**Expected behaviour**: should not happen at login or at random moments

**Steps to reproduce the problem**:

1. login
2. come out of dungeon
3. hearthstone

**screenshot**
http://imgur.com/a/eP1xh

**Comment by Rushor** [comment]
that issue also happens on retail and is blizzlike.

Naked Bug

    I know everyones probably seen the naked bug at one point or another. If you haven't its when all players around you are essentially without armor (sometimes you can see shoulders or weapons etc but nothing else). Lately this has been happening more frequently than it used to. From once a week maybe to like 2-3 times per night. It usually happens when you zone in or come back from a wipe. Has anyone else noticed an increase in the frequency of this?

source: http://www.mmo-champion.com/threads/636939-Naked-Bug

**Comment by w00tnoway** [comment]
u didnt answer my launcher question in the shadowmeld thread bro :P

**Comment by Rushor** [comment]
launcher to fix client issues? no this will not happen and please research your issues on the internet first in order to decide if it is a blizzlike issue or not. thank you
