### ISSUE TITLE
[NPC] Stonegazer

### ISSUE THREAD

**Issue by Rushor** [dalaranwow/dalaran-wow#3834]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (OLD - ... tags should no longer be used)
[//]: # (Priority - ... tags are assigned by team members)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Description**:
http://www.wowhead.com/npc=18648/stonegazer
Should have some waypoints.

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
Has no waypoints.
**Expected behaviour**: Tell us what should happen instead
Should have some waypoints.

**Include proofs for this behaviour**
http://www.wowhead.com/npc=18648/stonegazer#map
You can research this on several pages like http://wowhead.com or http://wowwiki.wikia.com or http://www.youtube.com/
Issues without proofs will be closed and tag On Hold will be added until the proof is provided.

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**
http://www.wowhead.com/npc=18648
You can research this on several pages like http://wotlk.openwow.com or http://wowhead.com/

**Include Screenshots from the issue if necessary**

**Comment by Rushor** [comment]
DB/Creature: Stonegazer - Add waypoints

* closes https://github.com/dalaranwow/dalaran-wow/issues/3834
* commit: 9a947cc75be07000be3131466b85d19d70793a9e

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by TeridanDW** [comment]
He is immune to roots, however he does get the visual effects of the spells that snare him (he does not lose movement speed so he is immune to them too), is this intended or a bug?
The path is working properly.

**Comment by Rushor** [comment]
not related to the report

**Comment by TeridanDW** [comment]
My comment was a bit misleading, he is suppose to be immune to roots and snares:

> By keller999 (5,567 – 1·21·28) on 2006/12/10 (Patch 2.0.1)		
> Immune to snares, roots, etc. Not really soloable as a mage, at least. Doesn't have anything special and doesn't hit especially hard, but two are probably required to take him down.

The question was regarding the visual part only.

**Comment by Rushor** [comment]
oh i see, hm i remember such behaviour with the valks on the lichking. not sure if intended or not.

**Comment by TeridanDW** [comment]
Immunities are correct, I couldn't find any data on visual effect (if it's suppose to be there or not).
Note: He is also immune to fear/death coil, which is working properly on ptr.
