### ISSUE TITLE
[Event] Dark Portal Event

### ISSUE THREAD

**Issue by Rushor** [dalaranwow/dalaran-wow#3835]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (OLD - ... tags should no longer be used)
[//]: # (Priority - ... tags are assigned by team members)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Description**:
The event with all creatures which will run towards the Dark Portal in Outland is missing currently.

**Comment by Rushor** [comment]
DB/Event: Implement Dark Portal Event

* closes https://github.com/dalaranwow/dalaran-wow/issues/3835

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by TeridanDW** [comment]
Hello, few issues that i saw here:
 - npc http://wotlk.openwow.com/npc=19455 should have movement event
 - mages around the portal should have aura in creature addon
![image](https://cloud.githubusercontent.com/assets/6797611/24519031/7c2c1184-158c-11e7-920f-9689ed622a24.png)
![image](https://cloud.githubusercontent.com/assets/6797611/24519039/857aa318-158c-11e7-8325-4b86c9721654.png)
 - npc http://wotlk.openwow.com/npc=19425 should have movement event
 - npc http://wotlk.openwow.com/npc=18969 is attacking npcs http://wotlk.openwow.com/npc=16831
 - no infernals http://wotlk.openwow.com/npc=18946 are spawned during the event
 - no fel soldiers http://wotlk.openwow.com/npc=18944 are spawned during the event (during waves)

**Comment by Rushor** [comment]
well the dark portal event onyl includes the waves of attackers - if there are missing movement events for the static spawns pls open individusl issues - thanks!

**Comment by TeridanDW** [comment]
No, they are part of the event.
Reference from retail legion from 30.03.2017:
https://www.youtube.com/watch?v=Q-Q86JfA_64&feature=youtu.be
