### ISSUE TITLE
[NPC] Ulduar - Thorim Dmg Buff Not Stacking Again

### ISSUE THREAD

**Issue by Zelwindin** [dalaranwow/dalaran-wow#3836]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (OLD - ... tags should no longer be used)
[//]: # (Priority - ... tags are assigned by team members)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Description**:

Thorim is not gaining stacks from Lightning Charge again.

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)

Thorim gains no stacking dmg buff from his Lightning Charge.

**Expected behaviour**: Tell us what should happen instead

Thorim should be getting a stacking dmg buff from his Lightning Charge ability.

**Steps to reproduce the problem**:

1. Engage Thorim in Ulduar
2. Complete gauntlet and move to phase 2.
3. Notice Thorim does not gain a stacking damage buff

**Include proofs for this behaviour**

Easy to test but can provide SS next week if needed.

This was fixed last week but is now broken again :(.

You can research this on several pages like http://wowhead.com or http://wowwiki.wikia.com or http://www.youtube.com/
Issues without proofs will be closed and tag On Hold will be added until the proof is provided.

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

You can research this on several pages like http://wotlk.openwow.com or http://wowhead.com/

Thorim: ID 32865
Lightning Charge: 62279

**Include Screenshots from the issue if necessary**

**Comment by Rushor** [comment]
related to https://github.com/dalaranwow/dalaran-wow/issues/3796

**Comment by Zelwindin** [comment]
This is now working again on 10 man. Will see about 25 on Friday.

**Comment by Zelwindin** [comment]
Works on 25 man as well, again.

**Comment by Rushor** [comment]
well then /closed
