### ISSUE TITLE
I can't select a char to use forrums on main website page

### ISSUE THREAD

**Issue by l337g0g0** [dalaranwow/dalaran-wow#3839]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (OLD - ... tags should no longer be used)
[//]: # (Priority - ... tags are assigned by team members)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Description**:
I can't select a char to use forrums on main website page
**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
right now, don't know why.
**Expected behaviour**: Tell us what should happen instead
I should be able to chat on forums.
**Steps to reproduce the problem**:
just log in and try and post.
1. 
2. 
3. 

**Include proofs for this behaviour**

You can research this on several pages like http://wowhead.com or http://wowwiki.wikia.com or http://www.youtube.com/
Issues without proofs will be closed and tag On Hold will be added until the proof is provided.

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

You can research this on several pages like http://wotlk.openwow.com or http://wowhead.com/

**Include Screenshots from the issue if necessary**

**Comment by Rushor** [comment]
Wrong Report. The issue tracker is only for ingamereport (f.ex wrong spelldamage). Please contact a Gamemaster for such problems. Thank you

**Comment by Edzero** [comment]
The solution is to make a character on Kirin your realm btw, in case anybody else comes here looking for an answer.

**Comment by l337g0g0** [comment]
Why can't i use the PVP realm algalon?

**Comment by Edzero** [comment]
Because the website is not linked to algalon correctly. No more bumping in her though please, use the forum for questions :)
