### ISSUE TITLE
[NPC] Seer Nakha

### ISSUE THREAD

**Issue by Rushor** [dalaranwow/dalaran-wow#3840]
http://wotlk.openwow.com/npc=23265

That creature is not spawned currently.

**Comment by Rushor** [comment]
DB/Creature: Add spawnpoint for Seer Nakha

* closes https://github.com/dalaranwow/dalaran-wow/issues/3840
* commit: a1dc0aad5d6183cd182343ed1f11630e798ceabf

**Comment by TeridanDW** [comment]
Works as intented on ptr.
