### ISSUE TITLE
[NPC] Pulik Swiftsnip <Barber>

### ISSUE THREAD

**Issue by Rushor** [dalaranwow/dalaran-wow#3841]
http://de.wowhead.com/npc=29145/pulik-flinkschnitt#comments:id=601996

That creature is not spawned currently.

**Comment by Rushor** [comment]
DB/Creature: Add spawnpoint for Pulik Swiftsnip

* closes https://github.com/dalaranwow/dalaran-wow/issues/3841
* commit: 95a1ee96abfc0fbecfc64a0ca223f1ae716c1759

![GitHub Logo](http://i.imgur.com/NMuaPTV.jpg)

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by TeridanDW** [comment]
He is spawned indeed, however he is not clickable, is this intended for this creautre?

**Comment by Rushor** [comment]
DB/Creature: Pulik Swiftsnip - Enable gossip + spawn Barber Chair

* updates: https://github.com/dalaranwow/dalaran-wow/issues/3841
* commit: 1152a274015bcca423fb5d8f3eaa381cd7f58668

![GitHub Logo](http://i.imgur.com/Bi71wIR.jpg)

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
