### ISSUE TITLE
[NPC][Shadow Labyrinth] Trash script rework

### ISSUE THREAD

**Issue by Rushor** [dalaranwow/dalaran-wow#3842]
All trash creatures in that instance must be cleaned up

* add all spells and abilities
* add creature texts
* increase respawntime
* add all creature texts

**Comment by Rushor** [comment]
DB/Creature: Add scripts and texts for all creatures in Shadow Labyrinth

* commit: c268e71c5d8d1bc511f44ceb525aca890b035b3b
* closes https://github.com/dalaranwow/dalaran-wow/issues/3842
* Texts on Aggro was added for following creatures:
http://wotlk.openwow.com/npc=18635
http://wotlk.openwow.com/npc=18640
http://wotlk.openwow.com/npc=18794
http://wotlk.openwow.com/npc=18796
http://wotlk.openwow.com/npc=18631
http://wotlk.openwow.com/npc=18637
http://wotlk.openwow.com/npc=18848
http://wotlk.openwow.com/npc=18830
http://wotlk.openwow.com/npc=18638
http://wotlk.openwow.com/npc=18634
http://wotlk.openwow.com/npc=18636
http://wotlk.openwow.com/npc=18632
http://wotlk.openwow.com/npc=18639

Creatureabilities and spells was added/updated for several creatures:
http://wotlk.openwow.com/npc=18794
http://wotlk.openwow.com/npc=18633
http://wotlk.openwow.com/npc=18635
http://wotlk.openwow.com/npc=18640
http://wotlk.openwow.com/npc=18641
http://wotlk.openwow.com/npc=18642
http://wotlk.openwow.com/npc=18796
http://wotlk.openwow.com/npc=18631
http://wotlk.openwow.com/npc=18637
http://wotlk.openwow.com/npc=18848
http://wotlk.openwow.com/npc=18830
http://wotlk.openwow.com/npc=18638
http://wotlk.openwow.com/npc=18634
http://wotlk.openwow.com/npc=19208
http://wotlk.openwow.com/npc=19209
http://wotlk.openwow.com/npc=18636
http://wotlk.openwow.com/npc=18632
http://wotlk.openwow.com/npc=18639

```sql
('Cabal Cultist - On Aggro - Say Line 0');
('Cabal Cultist - On Reset - Cast \'Thrash\'');
('Cabal Cultist - On Victim Casting - Cast \'Kick\'');
('Cabal Executioner - On Aggro - Say Line 0');
('Cabal Executioner - In Combat - Cast \'Whirlwind\'');
('Cabal Executioner - Between 0-30% Health - Cast \'Enrage\' (No Repeat)');
('Cabal Executioner - Target Between 0-20% Health - Cast \'Execute\'');
('Cabal Acolyte - On Aggro - Say Line 0');
('Cabal Acolyte - Friendly At 1000 Health - Cast \'Heal\' (Normal Dungeon)');
('Cabal Acolyte - Friendly At 1000 Health - Cast \'Heal\' (Heroic Dungeon)');
('Cabal Acolyte - On Friendly Unit Missing Buff \'Renew\' - Cast \'Renew\' (Normal Dungeon)');
('Cabal Acolyte - On Friendly Unit Missing Buff \'Renew\' - Cast \'Renew\' (Heroic Dungeon)');
('Cabal Acolyte - Out of Combat - Cast \'Shadow Defense\'');
('Cabal Summoner - On Aggro - Say Line 0');
('Cabal Summoner - Between 0-90% Health - Cast \'Summon Cabal Deathsworn\' (No Repeat)');
('Cabal Summoner - Between 0-40% Health - Cast \'Summon Cabal Acolyte\' (No Repeat)');
('Cabal Summoner - In Combat - Cast \'Fireball\' (Normal Dungeon)');
('Cabal Summoner - In Combat - Cast \'Fireball\' (Heroic Dungeon)');
('Cabal Deathsworn - On Aggro - Say Line 0');
('Cabal Deathsworn - In Combat - Cast \'Knockdown\'');
('Cabal Deathsworn - In Combat - Cast \'Black Cleave\' (Normal Dungeon)');
('Cabal Deathsworn - In Combat - Cast \'Black Cleave\' (Heroic Dungeon)');
('Cabal Deathsworn - Between 0-30% Health - Cast \'Enrage\' (No Repeat)');
('Cabal Assassin - On Aggro - Say Line 0');
('Cabal Assassin - On Aggro - Cast \'Cheap Shot\'');
('Cabal Assassin - In Combat - Cast \'Crippling Poison\'');
('Cabal Assassin - In Combat - Cast \'Wound Poison\'');
('Cabal Assassin - Out of Combat - Cast \'Stealth\'');
('Cabal Shadow Priest - On Aggro - Say Line 0');
('Cabal Shadow Priest - In Combat - Cast \'Shadow Word: Pain\' (Normal Dungeon)');
('Cabal Shadow Priest - In Combat - Cast \'Shadow Word: Pain\' (Heroic Dungeon)');
('Cabal Shadow Priest - In Combat - Cast \'Mind Flay\' (Normal Dungeon)');
('Cabal Shadow Priest - In Combat - Cast \'Mind Flay\' (Heroic Dungeon)');
('Cabal Shadow Priest - Out of Combat - Cast \'Shadowform\'');
('Cabal Zealot - On Aggro - Say Line 0');
('Cabal Zealot - In Combat - Cast \'Shadow Bolt\' (Normal Dungeon)');
('Cabal Zealot - In Combat - Cast \'Shadow Bolt\' (Heroic Dungeon)');
('Cabal Zealot - Between 0-30% Health - Cast \'Shape of the Beast\' (No Repeat)');
('Cabal Spellbinder - On Aggro - Say Line 0');
('Cabal Spellbinder - In Combat - Cast \'Shadow Bolt\'');
('Cabal Spellbinder - On Victim Casting - Cast \'Spell Shock\'');
('Cabal Warlock - On Aggro - Say Line 0');
('Cabal Warlock - In Combat - Cast \'Seed of Corruption\' (Normal Dungeon)');
('Cabal Warlock - In Combat - Cast \'Seed of Corruption\' (Heroic Dungeon)');
('Cabal Warlock - In Combat - Cast \'Shadow Bolt\' (Normal Dungeon)');
('Cabal Warlock - In Combat - Cast \'Shadow Bolt\' (Heroic Dungeon)');
('Cabal Warlock - Out of Combat - Cast \'Demon Armor\'');
('Cabal Familiar - In Combat - Cast \'Firebolt\' (Normal Dungeon)');
('Cabal Familiar - In Combat - Cast \'Firebolt\' (Heroic Dungeon)');
('Fel Guardhound - On Victim Casting - Cast \'Spell Lock\'');
('Cabal Ritualist - Out of Combat - Cast \'Crystal Channel (Dungeon)');
('Cabal Ritualist - Out of Combat - Set Random Phase(1, 4) (No Repeat) (Dungeon)');
('Cabal Ritualist - In Combat - Cast \'Fire Blast\' (Normal Dungeon)');
('Cabal Ritualist - In Combat - Cast \'Fire Blast\' (Heroic Dungeon)');
('Cabal Ritualist - In Combat - Cast \'Flame Buffet\' (Dungeon)');
('Cabal Ritualist - In Combat - Cast \'Gouge\' (Dungeon)');
('Cabal Ritualist - On Aggro - Increment Phase By 1 (Phase 1) (No Repeat) (Dungeon)');
('Cabal Ritualist - Combat CMC - Cast \'Frostbolt\' (Phase 1) (Normal Dungeon)');
('Cabal Ritualist - Combat CMC - Cast \'Frostbolt\' (Phase 1) (Heroic Dungeon)');
('Cabal Ritualist - In Combat - Cast \'Frost Nova\' (Phase 1) (Normal Dungeon)');
('Cabal Ritualist - In Combat - Cast \'Frost Nova\' (Phase 1) (Heroic Dungeon)');
('Cabal Ritualist - In Combat - Cast \'Gouge\' (Phase 2) (Dungeon)');
('Cabal Ritualist - Between 30-100% Mana - Decrement Phase By 1 (Phase 2) (Dungeon)');
('Cabal Ritualist - On Aggro - Increment Phase By 1 (Phase 4) (Dungeon)');
('Cabal Ritualist - Combat CMC - Cast \'Arcane Missiles\' (Phase 4) (Normal Dungeon)');
('Cabal Ritualist - Combat CMC - Cast \'Arcane Missiles\' (Phase 4) (Heroic Dungeon)');
('Cabal Ritualist - Between 0-15% Mana - Increment Phase By 1 (Phase 4) (No Repeat) (Dungeon)');
('Cabal Ritualist - In Combat - Cast \'Addle Humanoid\' (Phase 4) (Dungeon)');
('Cabal Ritualist - In Combat - Cast \'Gouge\' (Phase 8) (Dungeon)');
('Cabal Ritualist - Between 30-100% Mana - Decrement Phase By 1 (Phase 8) (Dungeon)');
('Cabal Ritualist - On Aggro - Say Line 0');
('Fel Overseer - On Aggro - Say Line 0');
('Fel Overseer - In Combat - Cast \'Frightening Shout\'');
('Fel Overseer - In Combat - Cast \'Mortal Strike\'');
('Fel Overseer - In Combat - Cast \'Uppercut\'');
('Fel Overseer - On Aggro - Cast \'Intercept\'');
('Cabal Fanatic - On Aggro - Say Line 0');
('Cabal Fanatic - In Combat - Cast \'Fixate\'');
('Malicious Instructor - On Aggro - Say Line 0');
('Malicious Instructor - In Combat - Cast \'Disarm\'');
('Malicious Instructor - In Combat - Cast \'Shadow Nova\'');
('Malicious Instructor - In Combat - Cast \'Mark of Malice\'');
('Summoned Cabal Acolyte - Friendly At 1000 Health - Cast \'Heal\' (Normal Dungeon)');
('Summoned Cabal Acolyte - Friendly At 1000 Health - Cast \'Heal\' (Heroic Dungeon)');
('Summoned Cabal Acolyte - On Friendly Unit Missing Buff \'Renew\' - Cast \'Renew\' (Normal Dungeon)');
('Summoned Cabal Acolyte - On Friendly Unit Missing Buff \'Renew\' - Cast \'Renew\' (Heroic Dungeon)');
('Summoned Cabal Acolyte - Out of Combat - Cast \'Shadow Defense\'');
('Summoned Cabal Deathsworn - In Combat - Cast \'Knockdown\'');
('Summoned Cabal Deathsworn - In Combat - Cast \'Black Cleave\' (Normal Dungeon)');
('Summoned Cabal Deathsworn - In Combat - Cast \'Black Cleave\' (Heroic Dungeon)');
('Summoned Cabal Deathsworn - Between 0-30% Health - Cast \'Enrage\' (No Repeat)');
```

**Comment by TeridanDW** [comment]
There are few issues with these SAIs what should be fixed before pushing to live, however i would like to add there are a lot of other issues too. If there is desire to work on this dungeon i have recorded the entire dungeon with all mini event (+ sniff ofc).
Issues with these SAIs:
 - ('Cabal Acolyte - Friendly At 1000 Health - Cast \'Heal\' (Normal Dungeon)');
('Cabal Acolyte - Friendly At 1000 Health - Cast \'Heal\' (Heroic Dungeon)'); have masive range which cause this:
![wowscrnshot_040517_200342](https://cloud.githubusercontent.com/assets/6797611/24719702/5b64a05e-1a43-11e7-9482-c99c0db1a09b.jpg)
![wowscrnshot_040517_200246](https://cloud.githubusercontent.com/assets/6797611/24719703/5b64f77a-1a43-11e7-895a-1c4544aac9ff.jpg)

 - because if this issue the acolytes tend to spam their on aggro speech

 - ('Cabal Acolyte - Out of Combat - Cast \'Shadow Defense\''); shadow defense seems to be spammed a lot because the acolytes lose the buff while out of combat for some reason (probably because issue 1 > they evade)

 - when npc http://wotlk.openwow.com/npc=18667 is pulled all creatures in the room should be pulled also (if they are alive)
 - spell http://wotlk.openwow.com/spell=33676 should NOT be casted if there is only 1 player in the dungeon

There are more issues with skeleton and the 3-rd boss's summoning portals that attack player and the event of the last boss is missing.

If you wish to work more on this dungeon please consider watching this video as it contains a lot of details:
https://www.youtube.com/watch?v=tGY5s_81Rng&feature=youtu.be

**Comment by Rushor** [comment]
> spell http://wotlk.openwow.com/spell=33676 should NOT be casted if there is only 1 player in the dungeon

was tempfixed with https://github.com/dalaranwow/dalaran-wow/issues/482

**Comment by Rushor** [comment]
* Scripts/ShadowLabyrinth: Blackheart the Inciter  - All creatures in his room will now get in combat once the boss gets in combat
* DB/Gameobject: Set Door behind Blackheart the Inciter into the correct phase
* DB/Creature: Cabal Acolyte - Cast 'Renew' At 4000 Health (NH) and At 7000 Health (HC)

**Comment by Rushor** [comment]
* Game/Conditions: Implement CONDITION_IN_COMBAT
* DB/Conditions: Cabal Acolyte - Only Run Cabal Acolyte SAI in Combat
