### ISSUE TITLE
[Transport] Orgrim's Hammer - Death by Fall Dmg upon Login

### ISSUE THREAD

**Issue by MrAndersonX** [dalaranwow/dalaran-wow#3845]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (OLD - ... tags should no longer be used)
[//]: # (Priority - ... tags are assigned by team members)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Description**:

Upon loging in to the game, while aboard the Orgrim's Hammer, I died instantly after logging in from fall dmg.

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
You die if you log out/log in while aboard Orgrim's Hammer from fall damage.

**Expected behaviour**: Tell us what should happen instead
 
You should not die if you log out/log in while aboard it.

**Steps to reproduce the problem**:

1. Board Orgrim's Hammer.
2. Log out.
3. Log in.

**Include proofs for this behaviour**

https://postimg.org/image/idx96tuc1/

You can research this on several pages like http://wowhead.com or http://wowwiki.wikia.com or http://www.youtube.com/
Issues without proofs will be closed and tag On Hold will be added until the proof is provided.

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

You can research this on several pages like http://wotlk.openwow.com or http://wowhead.com/

**Include Screenshots from the issue if necessary**

**Comment by Rushor** [comment]
also happens upon changing the country with a ship while jumping

**Comment by MrAndersonX** [comment]
Uh, what :D ?

**Comment by Rushor** [comment]
1.) Jump before the transportship switches the continent (f.ex from durotar to tirisfal)
2.) You will notice falldamage and in some cases you will die

**Comment by MrAndersonX** [comment]
Oh, got it. Ty.

**Comment by Rushor** [comment]
Game/Player: Disable falldamage on transports

* closes https://github.com/dalaranwow/dalaran-wow/issues/3845
* commit: d2438b6270135fb8a465dd4378282cea44b4f1f2

**Comment by TeridanDW** [comment]
Works as intended on ptr.
P.S. I will asume this is a workaround for the issue as player are suppose to take falldamage on transports too.

**Comment by Aridam** [comment]
Since my issue report regarding aerial Charge got referenced here and then got closed, I'm posting an additional problem regarding what I've reported about it: It seems that the distance fallen doesn't (often?) reset if Charge _does_ (rarely) work while falling -- still taking Damage from falling after landing following a rare working aerial Charge.

**Comment by Aridam** [comment]
Still happening.

**Comment by Aridam** [comment]
Bump.

Charge still isn't preventing Fall Damage -- huge issue when trying to save your own skin.

"Fixed - Waiting for PTR update" label has been on for over a year.

https://www.youtube.com/watch?v=re49dMn22gc
