### ISSUE TITLE
[Classic] Echeyakee's Grace missing

### ISSUE THREAD

**Issue by Rushor** [dalaranwow/dalaran-wow#3847]
Current behavior: The buff is not received on completion of the Echeyakee quest.

Expected behavior: Receive a +2(?) Spirit buff for 30mins called Echeyakee's Grace

Steps to reproduce:

    Get the quest from Sergra Darkthron in The Barrens.
    Summon Echeyakee with the horn and kill/subdue him.
    Hand in quest to get buff.

http://wotlk.openwow.com/spell=5320
http://wotlk.openwow.com/quest=881
http://wotlk.openwow.com/npc=3338

**Comment by Rushor** [comment]
DB/Creature: Sergra Darkthorn - Apply 'Echeyakee's Grace' on reward of quest: Echeyakee

* closes https://github.com/dalaranwow/dalaran-wow/issues/3847

![GitHub Logo](http://i.imgur.com/A0aHt31.jpg)

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by TeridanDW** [comment]
Works as intented on ptr.
P.S. What kind of a buff is this, 30mins and no buff icon? Only stat change.

**Comment by Rushor** [comment]
well yeah it's strange 

ID - 5320
Attributes: 0x08000080 (SPELL_ATTR0_HIDDEN_CLIENTSIDE, SPELL_ATTR0_CASTABLE_WHILE_SITTING)

But blizzlike as far as i know
