### ISSUE TITLE
[BG] Arathi Basin - Creature and Gameobjectspawns + Phasing

### ISSUE THREAD

**Issue by Rushor** [dalaranwow/dalaran-wow#3849]
Several creatures are missing in arathi Basin.

http://www.wowhead.com/npc=15074
http://www.wowhead.com/npc=15075
http://www.wowhead.com/npc=15062
http://www.wowhead.com/npc=15089
http://www.wowhead.com/npc=15107
http://www.wowhead.com/npc=15108
http://www.wowhead.com/npc=15086
http://www.wowhead.com/npc=15087
http://www.wowhead.com/npc=15045
http://www.wowhead.com/npc=15046
http://www.wowhead.com/npc=15063
http://www.wowhead.com/npc=15064
http://www.wowhead.com/npc=15065
http://www.wowhead.com/npc=15066
http://www.wowhead.com/npc=15071
http://www.wowhead.com/npc=15072

**Comment by Rushor** [comment]
DB/Creature: Add several creatures and objects in Arathi Basin

* closes https://github.com/dalaranwow/dalaran-wow/issues/3849
* these creatures and objects are only visible with GM ON for now. Phasingmechanic will be implemented soon (maybe @robinsch will do this <3)

**Comment by Rushor** [comment]
Robin added the missing phasemask script. Depending on the state of capuring, undead or humans will spawn now (including the gameobject)

**Comment by TeridanDW** [comment]
There is something wrong here:
 - mine/bs doesn't have human spawns (gm mode on)
 - phasing is happening only the first time when a base is captured, after that all spawns in that base disappear (tested solo, phasing out and in)
 - when a player tries to capture the flag on any base there should be a visual element around there flag (while its been captured) that indicates someone is capturing it.

**Comment by Rushor** [comment]
yep we need to reapply it
