### ISSUE TITLE
[Quest][Northrend] We Strike!

### ISSUE THREAD

**Issue by Daveonx** [dalaranwow/dalaran-wow#385]
Once players accept the quest and event to assault Steeljaw's Caravan but nothing happens, Longrunner Proudhoof  just stands there.

http://www.wowhead.com/quest=11592#comments

**Comment by fatninjadude** [comment]
I got the same result, but I got it working by getting Proudhoof into combat. Pull any close mob towards him and the event will trigger.

**Comment by Rushor** [comment]
fixed long time ago

http://i.imgur.com/sNssNDX.jpg
http://i.imgur.com/E08761q.jpg
http://i.imgur.com/vO1gBj3.jpg

**Comment by Aridam** [comment]
Confirmed as not working -- once accepted, the speech Longrunner Proudhoof gives goes through, but afterwards, nothing happens, as he and the Warsong Caravan Guards don't even move; abandoned the Quest to retake, but now I can't even take it up from him again -- it's just not there now.
