### ISSUE TITLE
[NPC] Arcane Anomaly

### ISSUE THREAD

**Issue by Rushor** [dalaranwow/dalaran-wow#3851]
npc= 16488

how the creature should work:

at 1% HP the creature should cast http://wotlk.openwow.com/spell=29880 on itself. if it reaches 1% Mana, the creature will die and cast spell http://wotlk.openwow.com/spell=29882.

Currently the creature just casts the manashield at 75% HP

source: http://www.wowhead.com/npc=16488/arcane-anomaly#comments:id=116199

**Comment by Rushor** [comment]
DB/Creature: Arcane Anomaly - Add Invincibility combat script

* closes https://github.com/dalaranwow/dalaran-wow/issues/3851

![GitHub Logo](http://i.imgur.com/0iWg7fg.jpg)

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by TeridanDW** [comment]
Works as intended on ptr.
