### ISSUE TITLE
[NPC][Ragefire Chasm] Molten Elemental

### ISSUE THREAD

**Issue by Rushor** [dalaranwow/dalaran-wow#3852]
The only bug i found so far in this istance is the missing ability http://wotlk.openwow.com/spell=7942 since they are fireelementals, this immunity should be added (npc=11321)

**Comment by Rushor** [comment]
DB/Creature: Molten Elemental - Add fire-immunity

* closes https://github.com/dalaranwow/dalaran-wow/issues/3852
* commit: 47e8af88ff5c01de66bcac7155d67dd0c1910733

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by TeridanDW** [comment]
Works as intended on ptr.
