### ISSUE TITLE
[NPC] Restless Skeleton - reputation

### ISSUE THREAD

**Issue by Rushor** [dalaranwow/dalaran-wow#3853]
http://wotlk.openwow.com/npc=17261
Restless Skeleton gives rep for Sha'tar.

They should give rep for The Violet Eye http://wotlk.openwow.com/faction=967, like every other creature in that instance.

**Comment by Rushor** [comment]
DB/Creature: Restless Skeleton - should give reputation for The Violet Eye

* before they gave rep for the faction Sha'tar. Thats wrong because every creature in Karazhan should give rep for The Violet Eye
* closes https://github.com/dalaranwow/dalaran-wow/issues/3853

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by TeridanDW** [comment]
A bit hard to test this issue without #2767 :)

**Comment by TeridanDW** [comment]
Works as intended on ptr.
