### ISSUE TITLE
[NPC] Darmuk

### ISSUE THREAD

**Issue by Rushor** [dalaranwow/dalaran-wow#3855]
The respawntimer for that creature is too high. 

it should be around 1 minute: http://www.wowhead.com/npc=28793/darmuk#comments:id=547486
(Re-spawns in 1 minute (always re-spawns on the west edge of the bridge).)

**Comment by Rushor** [comment]
DB/Creature: Darmuk - reduce respawntimer

* closes https://github.com/dalaranwow/dalaran-wow/issues/3855
* commit: 167b0be465268fc6051bc9f97f15496a8de45a86

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by TeridanDW** [comment]
Works as intended on ptr. However the part:

> (always re-spawns on the west edge of the bridge)

might of been changed in #4443 , but i don't think its so important where at which point of his path he spawns.
