### ISSUE TITLE
[NPC] Blight Geist

### ISSUE THREAD

**Issue by Rushor** [dalaranwow/dalaran-wow#3856]
The respawntimer for that creature is too high.

It should respawn after ~30 seconds in order to complete the quest faster

http://www.wowhead.com/npc=28750/blight-geist#comments:id=875602
Very Good mob to grind without a lot of attention...

> As i´m playing at work... It´s perfect, since i´m blood DK.
> 
> Go atop Voltarus, and keep killing... Fastest respawn rate ever. 1.7k XP at 78 and shoulder/chest heirloons. Drop 20s some cloth/greys/greens per kill.
> 
> 8-10s per kill, 10s respawn = safe non-stop killing spree.
> 
> In this moment Watch 1st season of reaper and slow lvling a DK. Why the dumbs use bots, when we can do the job by ownselfs, safely and watching a good serie while doing that?
> Last edited by magux on 2009/10/26 (Patch 3.2.2)
> 
>     WolfAddict on 2009/11/13 (Patch 3.2.2)
>     Actually, I've had these guys respawn no longer than 3 seconds after they die. They're in groups of 3 and they just keep respawning. Perfect for classes that can grind hours on end without downtime, such as the Death Knight, Fury Warrior or Retribution Paladin. Typically, a leveling character might activate the Betrayal quest and cause the grinding spot to become a deathpit. Unless you're able to heal yourself, you'd have to stop and wait for that person to finish the quest or fail it.
>

**Comment by Rushor** [comment]
DB/Creature: Blight Geist - reduce respawntimer

* close https://github.com/dalaranwow/dalaran-wow/issues/3856
* commit: f177ff081919db7737bf3a6e27fc80a9a17574d3

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by TeridanDW** [comment]
Hm, on ptr these creatures are on 10 secs respawn timer (without the corpse delay timer), is it intended?According to the comment, it is.

**Comment by Rushor** [comment]
hm well if it works nice. (the 30 seconds in my first text were only guessed value)
