### ISSUE TITLE
[Quest] An Improper Burial - Too less creaturespawns

### ISSUE THREAD

**Issue by Rushor** [dalaranwow/dalaran-wow#3857]
quest=10913

There are too less spawns for Slain Auchenai Warrior (npc=21846) and Slain Sha'tar Vindicator (npc=21859). You need 16 to complete the quest, but there are only 11 spawns currently.

Moreover the respawntimer of the creatures should be reduced to 100 seconds.

**Comment by Rushor** [comment]
DB/Creature: Add missing Slain Auchenai Warrior + Slain Sha'tar Vindicator spawns

* closes https://github.com/dalaranwow/dalaran-wow/issues/3857
* commit: 0c41f1143118deda6953a451010ebd5c6b2b4078
* added 24 additional spawns for Slain Auchenai Warrior (npc=21846) and Slain Sha'tar Vindicator

The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by TeridanDW** [comment]
Works as intented on ptr.
