### ISSUE TITLE
[NPC] Mechagnome Pilot 

### ISSUE THREAD

**Issue by Jokey11** [dalaranwow/dalaran-wow#3860]
http://www.wowhead.com/npc=33216/mechagnome-pilot

This NPC spawns whenever you kill the following: 
http://www.wowhead.com/npc=34161/mechanostriker-54-a

The Mechagnome Pilots are untargettable. They do a decent amount of damage, and players are unable to kill them. The only way of getting rid of them is by using Retribution Aura + Thorns, but, it takes quite some times and gets the players stuck in combat, which is pretty frustrating.

@Lothloryen

**Comment by Jokey11** [comment]
@Lothloryen

**Comment by Rushor** [comment]
DB/Creature: Mechagnome Pilot (Ulduar) - Remove unattackable flags in combat

* commit: bcaf778e2934b0cfbd3fdd7a57a44df5ee84f4e0

The vehicles are not spawned on ptr (this fix cannot be tested by normal testers) @Lothloryen
