### ISSUE TITLE
[NPC] Issue buying noggenfogger

### ISSUE THREAD

**Issue by ashido96** [dalaranwow/dalaran-wow#3868]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (OLD - ... tags should no longer be used)
[//]: # (Priority - ... tags are assigned by team members)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

When i talk to marin noggenfogger the dialogue option for "show me what you have to sell" (sorry, whatever it's called) does nothing. Like the npc buy/sell window doesn't open, nothing happens.

http://wotlk.openwow.com/npc=7564

**Comment by Rushor** [comment]
http://www.wowhead.com/npc=7564/marin-noggenfogger#comments:id=4419

You must complete the quest line that begins with The Thirsty Goblin (//www.wowhead.com/?quest=2605) before Marin Noggenfogger will sell Noggenfogger Elixir to you.

![GitHub Logo](http://i.imgur.com/lVCiRfB.jpg)
![GitHub Logo](http://i.imgur.com/lVCiRfB.jpg)
