### ISSUE TITLE
[Quest] Fate, Up Against Your Will

### ISSUE THREAD

**Issue by Crispybuilt** [dalaranwow/dalaran-wow#3870]
- **Prequest** - *Fate, Up Against Your Will* ID: 13369

**Issues found:** Once you pick up the quest, Jaina will open a portal for you which will lead to Orgimmar, that happens, but the missing part is the dialogue before you both enter the portal.
Jaina should say the following quotes:
- *Lady Jaina Proudmoore says: Do not do anything that would incite the Horde, <name>. The Warchief has agreed to see us on good faith.*
- *Lady Jaina Proudmoore says: Let's go.*

--------
After that point you should BOTH get teleported to Orgrimmar at Thrall, **Jaina however doesn't.**

On arrival, the Kor'kron Elites in the throne room come up to attack before Thrall calls them off. Lady Sylvanas Windrunner is also in attendance, kneeling before Thrall. 
**(The elites do not get around the player, while they should, and Slyvanas appears to be mounted on a horse standing infront of Thrall while she should be kneeling.)**

- **Now the important part is that the entire dialogue is missing between Jaina, Thrall and Slyvanass.**
**The dialogue goes something like this:**

- *Thrall says: Kor'kron, stand down!*
- *Thrall says: Jaina...*
- *Lady Jaina Proudmoore says: Thrall, what has happened? The King is preparing for war...*
- *Thrall says: Jaina, what happened at the Wrathgate. It was a betrayal from within...*
- *Lady Sylvanas Windrunner says: Lady Proudmoore, the Warchief speaks the truth. This subterfuge was set in motion by Varimathras and Grand Apothecary Putress. It was not the Horde's doing.*
- *Lady Sylvanas Windrunner says: As the combined Horde and Alliance forces began their assault upon the Wrathgate, an uprising broke out in the Undercity. Varimathras and hordes of his demonic brethren attacked. Hundreds of my people were slain in the coup. I barely managed to escape with my life.*
- *Thrall says: The Horde has lost the Undercity.*
- *Thrall says: We now prepare to lay siege to the city and bring in the perpetrators of the unforgivable crime to justice.*
- *Thrall says: Know this, Jaina: War with the Alliance is not in our best interests. If we are forced into a conflict, the Lich King will destroy our divided forces in Northrend.*
- *Thrall says: We will make this right, Jaina. Tell your king all that you have learned here.*
- *Lady Jaina Proudmoore says: I will deliver this information to King Wrynn, Thrall, but...*
- *Lady Jaina Proudmoore says: Bolvar was like a brother to him. In the King's absence, Bolvar kept the Alliance united. He found strength for our people in our darkest hours. He watched over Anduin, raising him as his own.*
- *Lady Jaina Proudmoore says: I fear that the rage will consume him, Thrall. I remain hopeful that reason will prevail, but we must prepare for the worst... for war.*
- *Lady Jaina Proudmoore says: Farewell, Warchief. I pray that the next time we meet it will be as allies.
Jaina takes the portal back to Stormwind City.*
- *Thrall says: Kor'kron, prepare transport to the Undercity.*

-------------
**Links:** http://wotlk.openwow.com/quest=13369
http://wowwiki.wikia.com/wiki/Quest:Fate,_Up_Against_Your_Will
**Video Link:** https://www.youtube.com/watch?v=yXnAZZC6OTU

------------------

**Comment by Rushor** [comment]
alright, that's just a phasing issue

**Comment by Rushor** [comment]
fixed with the recent reapply of all db fixed on ptr (no specific commit needed)

![GitHub Logo](http://i.imgur.com/QA8AnRm.jpg)

**Comment by Edzero** [comment]
This quest is working much better now but I think it can be polished a little bit more before being moved to the live realm.

Jaina doesn't come appear in Orgrimmar until the player gets close enough to Thrall. So unless the player moves to Thrall, the event won't start. There is also a second spawn of Sylvannas for some reason.

Currently looks like this

https://drive.google.com/open?id=0B4oLoQsMtUhCZTUzRG93MDVDY0U

**Comment by Rushor** [comment]
well the scriptstart requires an areatrigger. in sniffs the areatriggers was also used for the eventstart on retail. so i think this is intended blizzlike

**Comment by Edzero** [comment]
In the video retail video from the OP it triggers without the player needing to go to Thrall.

I'll leave that decision with you. What about the spare Sylvannas?

**Comment by Rushor** [comment]
i removed the double spawn of her, seems that an update on the ptr is missing here
