### ISSUE TITLE
[Quest] The Battle For The Undercity - Horde Version

### ISSUE THREAD

**Issue by Crispybuilt** [dalaranwow/dalaran-wow#3873]
- **Final quest** - The Battle For The Undercity ID: 13267

- **Issue present:** You are not able to accept this quest from Vol'jin after turning in the #3872 (A Life Without Regret)
Vol'jin simply doesn't offer the quest to a player for some particular reason.

- **How it should work:** You should be able to get the quest from Vol'jin after turning in the #3872.

---------------------

Now, I have bypassed that by simply adding the quest to my log via command and I was able to speak to Thrall to start the Battle For the Undercity.

- **Issue 2 present:** When Thrall calls the wind to clear the path to the outer section of the city, wind clears it just fine, **BUT** from that point the event bugs out and you aren't able to proceed. Varimathras simply doesn't show up at the scenery and nothing happens from that point.

**How it should work:** 
- *Thrall yells: ONWARD!*
- *The party reaches the ruins entrance.*
- *Thrall says: Great wind brother, clear our path!*
- *<A wind clears away the blight from Thrall's path>*
- *Thrall enters the courtyard, and Varimathras appears.*

After this little dialogue and when the wind clears the path, you should reach the outer section of the city and Varimathras should appear.

**From this point I couldn't test the quest anymore since it wasn't doable.**

---------------------------------

**Links:** http://wotlk.openwow.com/quest=13267
**Video Links:** https://www.youtube.com/watch?v=flPCbRZAaQI

**Comment by Rushor** [comment]
the creature runs too fast

**Comment by Rushor** [comment]
k that's just some internal issue with the ptr and the recent changes to the escortscripts in general. It will be fixed internal for other escortquests too. it's not related to the uc-fix. also you get the quest added in your log by vol'jin, once you rewarded the quest http://wotlk.openwow.com/quest=13266. this cannot be done differently atm :)

**Comment by Rushor** [comment]
Update: It't totally related to the recent scriptwaypoint/escortai changes for the smoothed movement implementation. This will be fixed soon by robin :)

**Comment by robinsch** [comment]
@robinsch

**Comment by TeridanDW** [comment]
The answer for issue 1:

>  you get the quest added in your log by vol'jin, once you rewarded the quest http://wotlk.openwow.com/quest=13266. this cannot be done differently atm :)

Issue 2 didn't came up for me, works as it should on ptr.

So marking as "Fixed - Waiting for changelog" and if someone wants to add anything else please continue in this report - #2404

**Comment by Crispybuilt** [comment]
**Small issue, but pretty big detail** (This is the first time ever in Wrath of the Lich King that Sargeras's voice was heard)
*I think you forgot to implement the voice of Sargeras*
Chat box was there, but no voice sound implementation was done in the script.
**A distant voice yells: YOU HAVE FAILED ME, VARIMATHRAS!**

/script PlaySoundFile("Sound\\Creature\\Sargeras\\WG_Sargeras_HOR01.wav")

**Comment by Lothloryen** [comment]
Corrected the voice of Sargeras.

**Comment by Aridam** [comment]
Updating this here to mention that Sylvanas' waypoints get a bit wonky at the inner-sanctum of the Undercity -- more specifically, at the Bank section in the center of the place: she gets stuck there, constantly going left-right at the edge of one of the very walls of it. Getting into fights thereafter _does_ fix her but partially, as afterwards, she kinda lags behind. Not a critical issue as the Quest is still doable (doing it at the moment and no actual, active hindrance is at play because of this), but throwing this in here as something to improve.

**Comment by Crispybuilt** [comment]
Small glitch here:
"Thrall sits down every time he stops"
- For example right before Varimathras is about to spawn. 
@Rushor look into that
