### ISSUE TITLE
[Spell] Fire Nova - Range

### ISSUE THREAD

**Issue by PentexGM** [dalaranwow/dalaran-wow#3874]
While testing the following: https://github.com/dalaranwow/dalaran-wow/issues/3131 
I found out that Fire Nova can be used from a way greater distance than it is supposed to. If you check the report that I linked, it clearly states: **The caster must be within 30 yards of the totem to use this ability**. 
As it turns out, this spell has no limit. It can be cast from a long distance, maybe 60-70+ yards.
**Current behaviour**: The spell can be cast from more than 30 yards of the totem.

**Expected behaviour**: The spell cannot be cast from more than 30 yards of the totem.

**Steps to reproduce the problem**:

1.  Summon any Fire Totem
2.  Move a long distance away from it, target the totem and then .distance - make sure that it is more than 30 yards.
3. Cast Fire Nova.

Spell ID: 61657

**Comment by robinsch** [comment]
On PTR.

**Comment by Rushor** [comment]
Script/Spell: Fixed range check for Fire Nova

Issue: https://github.com/dalaranwow/dalaran-wow/issues/3874
commit: 1adfabd190e8f5095ca40c3bad24f520dfbf5d18

**Comment by Crytexx** [comment]
Were you testing it as elemental shaman? 
[Elemental Reach], now also affects [Fire Nova] (previously named [Fire Nova Totem]) - Patch 3.3.0 (undocumented changes)

**Comment by TeridanDW** [comment]
Hello, after some tests on this issue original problem is indeed fixed and working as intended on ptr.
However the addition from @Crytexx :

> [Elemental Reach], now also affects [Fire Nova] (previously named [Fire Nova Totem]) - Patch 3.3.0 (undocumented changes)

is not fixed.
Talent  Elemental Reach https://wowgaming.altervista.org/aowow/?spell=29000 has:

> Increases the range of your Lightning Bolt, Chain Lightning, **Fire Nova**, and Lava Burst spells by 6 yards.

Which doesn't seems to have any effect on fire nova spell.
Reopening and leaving for Developers to decide.

**Comment by robinsch** [comment]
@TeridanDW Please create a new ticket.

**Comment by TeridanDW** [comment]
#4914
