### ISSUE TITLE
[The Eye of Eternity] Flame Shield

### ISSUE THREAD

**Issue by datbunneh** [dalaranwow/dalaran-wow#3877]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (OLD - ... tags should no longer be used)
[//]: # (Priority - ... tags are assigned by team members)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Description**: During Phase 3 of Malygos encounter in The Eye Of Eternity raid instance Wyrmrest Skytalon's ability Flame Shield can never be cast.

**Current behaviour**:
During [Phase 3](http://wowwiki.wikia.com/wiki/Malygos_(tactics)#Phase_Three) of [Malygos](http://www.wowhead.com/npc=28859/malygos) encounter in [The Eye Of Eternity](http://www.wowhead.com/the-eye-of-eternity) raid instance [Wyrmrest Skytalon's](http://www.wowhead.com/npc=32535/wyrmrest-skytalon) ability [Flame Shield](http://www.wowhead.com/spell=57108/flame-shield) can never be cast.

An error message "No target" is displayed instead.

**Expected behaviour**: [Flame Shield](http://www.wowhead.com/spell=57108/flame-shield) should be cast and a buff [Flame Shield](http://www.wowhead.com/spell=75926/flame-shield) should appear on your [Wyrmrest Skytalon](http://www.wowhead.com/npc=32535/wyrmrest-skytalon) reducing damage taken by 80% and lasting 2/3/4/5/6 seconds depending on how many combo points were consumed.

**Steps to reproduce the problem**:

Reproduced in both situations:
* Target [Malygos](http://www.wowhead.com/npc=28859/malygos), cast [Flame Spike](http://www.wowhead.com/spell=56091/flame-spike) to build at least one combo point on him, make sure your [Wyrmrest Skytalon](http://www.wowhead.com/npc=32535/wyrmrest-skytalon) has at least 25 energy and then try to cast [Flame Shield](http://www.wowhead.com/spell=57108/flame-shield) while [Malygos](http://www.wowhead.com/npc=28859/malygos) is still targeted.
* Target any [Wyrmrest Skytalon](http://www.wowhead.com/npc=32535/wyrmrest-skytalon) (including your own) from your group, cast [Revivify](http://www.wowhead.com/spell=57090/revivify) to build at least one combo point on him, make sure your [Wyrmrest Skytalon](http://www.wowhead.com/npc=32535/wyrmrest-skytalon) has at least 25 energy and then try to cast [Flame Shield](http://www.wowhead.com/spell=57108/flame-shield) while selected [Wyrmrest Skytalon](http://www.wowhead.com/npc=32535/wyrmrest-skytalon) from your group is still targeted.

**Include proofs for this behaviour**

* http://wowwiki.wikia.com/wiki/Malygos_(tactics)#Phase_Three
* http://www.wowhead.com/npc=28859/malygos#article

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

* [The Eye Of Eternity](http://www.wowhead.com/the-eye-of-eternity)
* [Malygos](http://www.wowhead.com/npc=28859/malygos) - 28859
* [Wyrmrest Skytalon](http://www.wowhead.com/npc=32535/wyrmrest-skytalon) - 32535
* [Flame Spike](http://www.wowhead.com/spell=56091/flame-spike) - 56091
* [Revivify](http://www.wowhead.com/spell=57090/revivify) - 57090
* [Flame Shield](http://www.wowhead.com/spell=57108/flame-shield) - 57108
* [Flame Shield](http://www.wowhead.com/spell=75926/flame-shield) (buff) - 75926

**Include Screenshots from the issue if necessary**

Screenshot was not taken during Malygos encounter itself, but behavior is exactly the same.
![wowscrnshot_112316_012829](https://cloud.githubusercontent.com/assets/9550798/20546163/326b19c0-b11c-11e6-9efd-ee6f2b5c34d0.jpg)

**Comment by Crispybuilt** [comment]
Merging with #3858
