### ISSUE TITLE
[Quest] [Northrend] Shoot'em up

### ISSUE THREAD

**Issue by MrAndersonX** [dalaranwow/dalaran-wow#3879]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (OLD - ... tags should no longer be used)
[//]: # (Priority - ... tags are assigned by team members)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Description**:

While handling the Jotunheim Rapid-Fire Harpoon there are 2 bugs encountered : 

1) You can use Energy Reserve to always have full energy. It does not have the 30 sec cooldown it should have that is mention in the skill description.
2) The Rapid-Fire Harpoon deals no dmg or it's bugged or the Proto-Drake are out of vision even tho they appear to be in sights.

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)

 This quest is bugged and can't be finished due to the fact that the Proto-Drake's can't be shot down.

**Expected behaviour**: Tell us what should happen instead

1) You should only be able to use Energy Reserver once every 30 sec.
2) The continous dmg from the Rapid-Fire Harpoon should kill the Proto-Drakes.

**Steps to reproduce the problem**:

1.  Take the quest.
2.  Try to shoot down Proto-Drakes.
3.  Use/spam Energy Reserve.

**Include proofs for this behaviour**

https://postimg.org/gallery/fu3keyfq/
http://wotlk.openwow.com/quest=13069
http://www.wowhead.com/quest=13069/shoot-em-up
https://www.youtube.com/watch?v=CC1-RJ_TsI0
http://wowwiki.wikia.com/wiki/Quest:Shoot_'Em_Up

You can research this on several pages like http://wowhead.com or http://wowwiki.wikia.com or http://www.youtube.com/
Issues without proofs will be closed and tag On Hold will be added until the proof is provided.

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

You can research this on several pages like http://wotlk.openwow.com or http://wowhead.com/

**Include Screenshots from the issue if necessary**

**Comment by Rushor** [comment]
moved to https://github.com/dalaranwow/dalaran-wow/issues/1898
