### ISSUE TITLE
[Raid] [Loot] Glitch/Unable to loot

### ISSUE THREAD

**Issue by MrAndersonX** [dalaranwow/dalaran-wow#3881]
#[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (OLD - ... tags should no longer be used)
[//]: # (Priority - ... tags are assigned by team members)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Description**:

Hi. I hope I'm not making a duplicate post, but I see there's a problem with looting in almost all encounters (raids). I experienced one myself today on a Obsidium Sanctum 3D run. After the Raid Leader used Master Loot to distribute most of the drop, he left before he traded the final pieces of gear. Because of this, I got screwed on a piece of gear (mainly the gloves : Gloves of the Lost Vanquisher; 
http://www.wowhead.com/item=40615/gloves-of-the-lost-vanquisher). Morengs (GM) tried to help me ingame, but I was still forced to send a mail and now I'm waiting for a reply and hopefully the item (MrAnderson2008@yahoo.com is my email).
I got lucky this time (was the only one in the 10 man raid under 5k gs) and I doubt I'll have the time/luck again as I did today.

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)

If the raid leader leaves suddenly, or if alot of raiders leave, the loot sometimes bug. I have no way to say exactly how it happens or in what conditions or if it happens for all the raids or not. It definitely happens for Sartharion tho.

**Expected behaviour**: Tell us what should happen instead

The loot should be lootable even if some of the raiders leave or even the raid master looter or raid leader.

**Steps to reproduce the problem**:

1.  Join a raid.
2.  Tell raiders to leave after the boss is down, or tell the raid/loot master to leave.
3.  Try to loot.

**Include proofs for this behaviour**

https://postimg.org/gallery/2fgwq2z2w/

You can research this on several pages like http://wowhead.com or http://wowwiki.wikia.com or http://www.youtube.com/
Issues without proofs will be closed and tag On Hold will be added until the proof is provided.

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

You can research this on several pages like http://wotlk.openwow.com or http://wowhead.com/

**Include Screenshots from the issue if necessary**

**Comment by Rushor** [comment]
well we will move this to https://github.com/dalaranwow/dalaran-wow/issues/3462, thanks for the detailed report. :)
