### ISSUE TITLE
[Interface] Inspecting Other Player's Talents Issue

### ISSUE THREAD

**Issue by sixele** [dalaranwow/dalaran-wow#3882]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (OLD - ... tags should no longer be used)
[//]: # (Priority - ... tags are assigned by team members)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Description**:
I... I don't even know how to describe it. You inspect someone's talents, but when you hover over another player, it shows that player's talents, not the ones that you chose to inspect at first. Basically, just watch the video. I don't click on other players, I just hover over them, and it switches to their talents. Pretty annoying when trying to inspect someone in areas of concentrated population.
This issue does not persist neither with the Compare achievements, nor Character of PvP tab when inspecting. **Only talents.**
**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
Read description and look at the video link.
**Expected behaviour**: Tell us what should happen instead
I'm fairly sure it should not happen and you should only see the talents of the player who you inspected, until you click on another player (not hover over them)
**Steps to reproduce the problem**:

1. Inspect a chosen player;
2. Go to their talents;
3. Hover over another player.

**Include proofs for this behaviour**

https://youtu.be/56wFz6h6h58 - might be not the best quality, but enough to get the point for sure.

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

**Comment by Rushor** [comment]
Not a serverside issue.

This happens because another mod requests inspect data, most likely your tooltip addon showing talents. There is not much to do about this unless I were to make Examiner cache all three talents tabs, but I wont. Currently it requests each tree from the last requested player, but this is global, meaning any mod which requests inspect data on another player, will also update this cache. 

maybe caused by recount or other addons. Try to disable them and find the missmatching addon that causes this issue. Thank you.

**Comment by sixele** [comment]
Oh I'm sorry, you are correct. If anyone happens to stumble across the same problem, apparently the addon GearScoreLite was the one which caused this issue for me. If disabled, everything works fine.

**Comment by shadovvs** [comment]
You can fix this by adding one line of code in GearScoreLite.lua `GearScore_HookSetUnit(arg1, arg2)` function. Edit GearScoreLite.lua with NotePad, go to the line 144 `if ( GS_PlayerIsInCombat ) then return; end` and add this line below it:

`if ( InspectTalentFrame ~= nil and InspectTalentFrame:IsShown() and InspectTalentFrame:IsVisible()) then return; end`

**Comment by datbunneh** [comment]
@shadovvs, can you please tell me (if it's possible) how to implement the following instead - return when any inspection tab is open (Character/PvP/Talents) **and** the inspected target's name on top of the frame is not equal to the target's name currently inspected by GearScore.
