### ISSUE TITLE
Quest: The Videre Elixir

### ISSUE THREAD

**Issue by Daveonx** [dalaranwow/dalaran-wow#389]
To find the evoroot required for the quest, players need to buy bait that Gregan sells and place it next to Miblon, once its placed he should move and the wall behind him should dissapear for a few moments so players can collect the required evoroot. But once the bait is placed nothing happens, Miblon just stands there.

http://www.wowhead.com/quest=4041
http://www.wowhead.com/item=11141
http://www.wowhead.com/npc=9467

**Comment by Demlock** [comment]
Yes but still, it would be much better if the quest actually did as it was intended for it to do.

**Comment by Spruitje** [comment]
one year later...still not working as intended :(
Completeable with the mount method though, tricky jump with the mount from the ledge through the crack in the wall

**Comment by Rushor** [comment]
16aa9602c28f62bc62e7c49424c8e3babbe1e55b
6621dbea45b18c30219e077cffe0dcf3be6f1502
- should now be completable easier

**Comment by Golganeth** [comment]
Works much better. Needs some polishments. No animations once the bait is placed and the wall simply disappears.
