### ISSUE TITLE
[GO] Ulduar Pure Saronite Deposit no longer respawns

### ISSUE THREAD

**Issue by brianyee** [dalaranwow/dalaran-wow#3892]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (OLD - ... tags should no longer be used)
[//]: # (Priority - ... tags are assigned by team members)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Description**: The Pure Saronite Deposit in Ulduar no longer respawns. I'm not sure if this is intended or not, but it used to respawn every hour.

**Current behaviour**: A 2nd Pure Saronite node was added in General's room, but they no longer respawn after the initial mining.

**Expected behaviour**: Both nodes should respawn

**Steps to reproduce the problem**:
Take the Saronite nodes from General's room and neither respawn an hour later

**Include proofs for this behaviour**

You can research this on several pages like http://wowhead.com or http://wowwiki.wikia.com or http://www.youtube.com/
Issues without proofs will be closed and tag On Hold will be added until the proof is provided.

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

Pure Saronite Deposit ID = 195036

**Include Screenshots from the issue if necessary**

**Comment by Rushor** [comment]
It's intended that they should not respawn by default https://github.com/TrinityCore/TrinityCore/commit/f191471a8af92169e15d3429d1db52faef774e93
