### ISSUE TITLE
 [72] [The Focus on the Beach](Part 3 of 16)

### ISSUE THREAD

**Issue by smegbird** [dalaranwow/dalaran-wow#3905]
Captain Emmy Malin doesnt drop the ring to complete the quest, ive killed her three times already.

**Comment by Crispybuilt** [comment]
The quest item drops fine, invalid report.
![image](https://cloud.githubusercontent.com/assets/5054924/20758591/a1ab1930-b71a-11e6-9b9b-5b0808530f53.png)
