### ISSUE TITLE
[Warlock] Stamina gear and spell power

### ISSUE THREAD

**Issue by WhiteNigg** [dalaranwow/dalaran-wow#3909]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

So what happens right now is that if you put on as much gear with stamina as you can, tank trinks stamina gems pvp gear etc and then summon your pet, according to this http://wotlk.openwow.com/spell=35696(url) you get some spell power from the extra stamina your pet has from all the stamina gear, but when u remove the stamina gear the spell power gained when u summon the pet stays there and since you put on your normal gear you gain even more spell power so its basically free spell power.

How it should work is, if you summon the pet with the stamina gear and then change to your normal gear the spell power gained from stamina should be removed instead of stacking on top of your normal spell power.

reproducing this is quite easy

1. get as much stamina gear as you can pvp stuff tank trinks stamina gems etc
2. equip that gear and summon your pet
3. change to your normal caster gear 
4. and then compare the spell power you have when you summon the pet without the stamina gear on

these are my stats with as much stamina gear as i could get for the test, and that is the 4 232ilvl pvp pieces and a coren trinket +170 stam http://prntscr.com/ddpo8g(url)
these are my stats when i summon the pet with the stamina gear on http://prntscr.com/ddponl(url)
and these are my stats after i change back to normal gear http://prntscr.com/ddpoz4(url) 
these are my stats with normal gear no pet http://prntscr.com/ddppis(url)
and these are with the pet summoned without the stamina gear http://prntscr.com/ddpptf(url)
the difference might not seem big but that is because i was using only 5 pieces not enchanted/gemed with stamina so the difference was 252 stamina which converts into 13 spell power now imagine that on a large scale with full stamina gear on gems trinks etc. As i ve seen warlocks having close to 20k more hp with their stamina gear on and my current hp is 21.9k with 1434 stamina with the stamina value being this http://prntscr.com/ddptrw(url) 20k more hp would mean 

13/252=0.05 which is the stamina to spell power ratio according to the numbers i just presented
and the hp to stamina ratio according to my own stamina as shown before is 14160/1434=9.9.
So 20k more hp means 2020 more stamina which then means 2020*0.05=101 spell power for free without doing anything but swapping gear and summoning the pet

The pet used was always imp.

My numbers might be a bit off since i dont have a full stamina set so one of the many warlocks using that be kind enough to post some more evidence since they are actually fixing stuff now

**Comment by Rushor** [comment]
live scaling and updating the stats every ~10 seconds is completely missing

**Comment by WhiteNigg** [comment]
The stats remain the same until you resummon the pet but sure i can make a video if u need more proof, even tho its a well known bug at least for the ppl in the top guilds

**Comment by Rushor** [comment]
Game/Petscaling: Live scaling from auras with type SPELL_AURA_MOD_SPELL_DAMAGE_OF_STAT_PERCENT and SPELL_AURA_MOD_SPELL_HEALING_OF_STAT_PERCENT

* closes https://github.com/dalaranwow/dalaran-wow/issues/3909
* commit: 729cf1785ec76ad338843d188d83b55b0b0cc098

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by TeridanDW** [comment]
Hello, after some tests on PTR I think there is something very wrong with how the bonus spell damage is been calculated from talent https://wowgaming.altervista.org/aowow/?spell=35693.
Screenshots below are from new character lvl 80, no gear/glyphs 
![wowscrnshot_102017_212145](https://user-images.githubusercontent.com/6797611/31836160-f1fe848c-b5dc-11e7-9836-0fee1f22b2c5.jpg)
![wowscrnshot_102017_212243](https://user-images.githubusercontent.com/6797611/31836161-f3746f3e-b5dc-11e7-941c-c484673564aa.jpg)
![wowscrnshot_102017_212314](https://user-images.githubusercontent.com/6797611/31836164-f4d4502e-b5dc-11e7-85be-d89c1025ee31.jpg)

The diffrence of the spell power happened when I resummoned the pet.

Note: The dynamic change of spell power (with the change of gear/stats) works but until the issue with the insane spell power bonus is resolved this shouldn't go to live.

**Comment by TeridanDW** [comment]
Linking this report with #1160 as they go together. I will retest this again when the spell power scaling is corrected.

**Comment by MalkaviaDW** [comment]
Hello there, 

This was already fixed on the live realm.

Cheers!
