### ISSUE TITLE
Achievement: Don't Look Up!

### ISSUE THREAD

**Issue by Crispybuilt** [dalaranwow/dalaran-wow#391]
Achievement: Don't Look Up!
Clear the hallway before Scourgelord Tyrannus in The Pit of Saron on Heroic Difficulty without anyone taking icicle damage on the first try.

Once you get into the tunnel there should be triggers all over the players for the Snow Rocks to start falling down from the celling, if nobody gets hit by them at all, and if you manage to kill all the trash on first try, you will recieve this achievement.
Also, Scourgelord has to yell and quote this: "Rimefang! Trap them within the tunnel! Bury them alive!"

The script can be related and some simillarities can be found in Ulduar, "Hodir's encounter".

This is how it has to work:
http://www.youtube.com/watch?v=yQ3agrSMtwg
http://www.wowhead.com/achievement=4525/dont-look-up
http://www.wowwiki.com/Don%27t_Look_Up

**Comment by Rushor** [comment]
the instance is not released. it will be fixed on the betarealms
