### ISSUE TITLE
DB/Quest: Battle at Valhalas - Ad despawnevent for Prince Sandoval

### ISSUE THREAD

**Issue by Rushor** [dalaranwow/dalaran-wow#3918]
DB/Quest: Battle at Valhalas - Ad despawnevent for Prince Sandoval

* previously Prince Sandoval got stuck if the player died
* now: Prince Sandoval will despawn if he killed a player and Geirrvif will fly down again, so player can retake the quest
* commit: 1b81988f9017ba5564b04014a3bff4e03f5a121d

http://wotlk.openwow.com/npc=31135
http://wotlk.openwow.com/quest=13219
http://wotlk.openwow.com/npc=14688

**Comment by TeridanDW** [comment]
After few tests the solution doesn't seem to work as I was able to stuck the encounter just by instantly releasing spirit on death.
![image](https://user-images.githubusercontent.com/6797611/32142573-c1c98ed4-bca2-11e7-91de-db27a748ebff.png)

**Comment by Rushor** [comment]
cannot reproduce this on my local, but i added a despawn event for the creature if it is 50 seconds out of combat now

**Comment by TeridanDW** [comment]
Works as intended on PTR.
