### ISSUE TITLE
Improved Devouring Plague talent bug

### ISSUE THREAD

**Issue by SexYPopCorN** [dalaranwow/dalaran-wow#3927]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: 

Improved Devouring Plague is not increasing periodic damage by 5/10/15%.

**Expected behaviour**: 

Should increase periodic damage of Devouring Plague by 5/10/15%.

**Steps to reproduce the problem**:

1. Cast untalented Devouring Plague, check for damage per tick.
2. Invest points in talent.
3. Cast talented Devouring Plague, check for damage, compare to untalented.

**Include proofs for this behaviour**

Not sure how I can make a proof. Easy to reproduce.

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

http://wotlk.openwow.com/spell=63625

**Include Screenshots from the issue if necessary**

**Comment by SexYPopCorN** [comment]
Here is some kind of proof.

I had 5 stacks of shadow weaving (10 % damage increase) when i casted both normal and improved version of DP. Shadow weaving is not an issue, it works perfectly.

Damage without talents:
![devouring plague untalented](https://cloud.githubusercontent.com/assets/7539182/20870448/abdf85f0-ba88-11e6-8199-42866083478d.jpg)

Damage with talents:
![devouring plague talented](https://cloud.githubusercontent.com/assets/7539182/20870486/3db18ca8-ba89-11e6-8ab0-4134819ae7b1.jpg)

**Comment by Golganeth** [comment]
Works fine on PTR.
