### ISSUE TITLE
Improved Mark of the Wild Cosmetic Bug

### ISSUE THREAD

**Issue by Zibathy** [dalaranwow/dalaran-wow#3928]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: 
The armor bonus for Improved Mark of the Wild is not represented in the buff icon but it is working as intended in the defenses tab.

**Expected behaviour**: 
Should say 91 armor rather than 65 (+40%; 2 levels in "improved mark of the wild" talent) for the buff icon. This is represented in the spell icon and the correct armor and stats are added. 

**Steps to reproduce the problem**:
1. Cast an Improved Mark of the Wild.

![wowscrnshot_120416_141238](https://cloud.githubusercontent.com/assets/7729864/20870901/3e199d22-ba55-11e6-91fa-613922b8678d.jpg)
![wowscrnshot_120416_141241](https://cloud.githubusercontent.com/assets/7729864/20870902/3e19d102-ba55-11e6-8e90-55d875a944f8.jpg)
![wowscrnshot_120416_141247](https://cloud.githubusercontent.com/assets/7729864/20870900/3e17f42c-ba55-11e6-8615-82106e30a18a.jpg)
![wowscrnshot_120416_160442](https://cloud.githubusercontent.com/assets/7729864/20870903/3e1a3e26-ba55-11e6-8666-2e85c405a4ef.jpg)

**Comment by Golganeth** [comment]
Hey @Zibathy 

This is same case as on retail, where they don't scale. The buff & debuff tooltips don't take into account any talents/glyphs, so they will always show the default amount.

You can check the correct amount in your action bar/spellbook tooltip.

Closed.

**Comment by Zibathy** [comment]
Oh really? Alright, neat. I clearly didn't know that.
