### ISSUE TITLE
Quest: Drag and Drop

### ISSUE THREAD

**Issue by Sagrath** [dalaranwow/dalaran-wow#393]
http://wowhead.com/quest=13318 A quest
http://wowhead.com/quest=13323 A daily
http://wowhead.com/quest=13352 H quest
http://wowhead.com/quest=13353 H daily

You are supposed to use the orb of illusion on the dark subjugator to transform them but nothing happens. Can't complete quest. 
http://wowhead.com/item=44246/orb-of-illusion
http://wowhead.com/npc=32236/dark-subjugator
I believe using the orb should cast this spell on them.
http://wowhead.com/spell=5513

**Comment by ashido96** [comment]
This quest works if you stand at maximum range from the subjugator, stutter step forward until you can use the quest item.

**Comment by Lothloryen** [comment]
Working already.
