### ISSUE TITLE
[NPC] Dredge Striker Skinning

### ISSUE THREAD

**Issue by p3ak** [dalaranwow/dalaran-wow#3931]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**:
When you Skin the NPC, it gives you either
http://www.wowhead.com/item=2934 (Ruined Leather Scraps) or
http://www.wowhead.com/item=2318 (Light Leather)

**Expected behaviour**:
The NPC should drop either
http://www.wowhead.com/item=8170 (Rugged Leather) or
http://www.wowhead.com/item=4304 (Thick Leather) or
http://www.wowhead.com/item=8171 (Rugged Hide) or
http://www.wowhead.com/item=8169 (Thick Hide)

**Steps to reproduce the problem**:

1. Go to Silithus
2. Kill Dredge Striker
3. Skinn it

**Include proofs for this behaviour**
http://www.wowhead.com/npc=11740/dredge-striker#skinning

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**
[NPC] Dredge Striker = 11740

**Comment by Rushor** [comment]
https://github.com/dalaranwow/dalaran-wow/issues/2770
