### ISSUE TITLE
[Boss] Expertise / boss parry

### ISSUE THREAD

**Issue by plznoz** [dalaranwow/dalaran-wow#3939]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**:
There are currently two things wrong related to expertise on bosses:
1. Currently you only need 21 expertise to avoid getting dodges from the back of the boss. (Boss has too low dodge chance)
2. Bosses does not parry at all when attacking from the front of the boss.

**Expected behaviour**:
1. You should need 26 expertise to avoid getting dodges when attacking from the back of the boss.
2. Bosses should be able to parry attacks made from the front of the boss (56 expertise hard cap)

Quoting http://wowwiki.wikia.com/wiki/Expertise:
> For boss-level mobs (which are calculated as your level + 3) the soft cap is 6.5% dodge or 26 expertise (200 expertise rating), and the hard cap is 14% parry or 56 expertise (431 expertise rating). Melee DPS classes will usually focus on the soft cap, since bosses cannot Parry when attacked from behind.

**Steps to reproduce the problem**:

1. Get 21 expertise
2. Hit boss from front and back
3. Observe the lack of dodge from the back and parries from the front.

**Include proofs for this behaviour**
"Proof" dalaran bosses do not parry (You can look at every boss / every week)
http://www.worldoflogs.com/reports/ftb0wg5gkfa9vpw7/details/12/?s=97&e=520 Prot paladin 28 expertise
![http://i.imgur.com/hbbo4zz.png](http://i.imgur.com/hbbo4zz.png)

"Proof" melee dps don't get dodges with 21 expertise:
http://www.worldoflogs.com/reports/ftb0wg5gkfa9vpw7/details/0/?s=97&e=520 Fury warrrior 21 expertise
![http://i.imgur.com/YgCU0HH.png](http://i.imgur.com/YgCU0HH.png)

Proof how it's supposed to work:
http://wowwiki.wikia.com/wiki/Expertise (also quoted above)

**Comment by plznoz** [comment]
This also means parry hasting on bosses most definitely doesn't work.
https://avengingwrathy.wordpress.com/2010/01/15/bosses-who-parry-haste/

**Comment by Rushor** [comment]
fix inc

**Comment by Rushor** [comment]
Core/Entities: Fix flag CREATURE_FLAG_EXTRA_NO_PARRY_HASTEN implementation. (#17548)

Signed-off-by: robinsch <robin.schriever.hude@web.de>
* commit: cb608eba589ddd393a43d166f7ff5de3f74c0a39

Game/Unit: Enable Parry for all units except totems and creatures with CREATURE_FLAG_EXTRA_NO_PARRY (research needed which of them should not parry)
Game/Unit: Increase dodge chcnace for bosses to 6.5% dodge (5.9 + 0.6 from defense skill difference)

* closes https://github.com/dalaranwow/dalaran-wow/issues/3939
* commit: bcb6d82a19befcb00b1671e015805acbb4a5cab3

**Comment by swiftdeath** [comment]
Has this fix been applied or not?

**Comment by StheNoble** [comment]
if thats actually fixed and working as retail now, that should be announced publicly. many poeple dont stack expertise because it was never necessary and will be cucked by that change if they dont get informed about it @Lothloryen

**Comment by StheNoble** [comment]
btw, is parry hasting correctly disabled for most of the ICC bosses? only Deathwhisper and Sindragosa should parry haste, i just hope we dont face parry hasting now on all bosses because that change.

source: https://avengingwrathy.wordpress.com/2010/01/15/bosses-who-parry-haste/

**Comment by mercred** [comment]
Could someone comment if this fix is actually "Fixed On Live Server"?
