### ISSUE TITLE
Dancing Rune Weapon Not casting stuff still! 

### ISSUE THREAD

**Issue by Darthblaider** [dalaranwow/dalaran-wow#3948]
Dancing rune weapon for death knights is supposed to copy EVERYTHING a death knight does. 
One example is that Death Knights are supposed to be able to cast rune weapon then rune tap for twice the amount of healing and this doesn't happen AT ALL. It pretty much just applies disease which only count as yours for a few seconds and then poof it's useless again aside from auto attacks.

**Comment by Rushor** [comment]
https://github.com/dalaranwow/dalaran-wow/issues/1098
