### ISSUE TITLE
[Quest][Northrend] Kaw the Mammoth Destroyer

### ISSUE THREAD

**Issue by TheRealestMcCoy** [dalaranwow/dalaran-wow#3956]
**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
Currently he is not on the p;atform as he should be. He seems to be fallen through the terrain.
**Expected behaviour**: Tell us what should happen instead
He should spawn ontop of the platform.
**Steps to reproduce the problem**:

1. Kill
2. Wait for respawn
3. See if he falls through.

**Include proofs for this behaviour**
http://www.wowhead.com/quest=11879/kaw-the-mammoth-destroyer
https://youtu.be/fyKtyJggwxo
You can research this on several pages like http://wowhead.com or http://wowwiki.wikia.com or http://www.youtube.com/
Issues without proofs will be closed and tag On Hold will be added until the proof is provided.

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**
http://www.wowhead.com/npc=25802/kaw-the-mammoth-destroyer
You can research this on several pages like http://wotlk.openwow.com or http://wowhead.com/

**Include Screenshots from the issue if necessary**
![wowscrnshot_121116_112541](https://cloud.githubusercontent.com/assets/12252441/21081441/f5d1651e-bf94-11e6-94b4-41692ad08337.jpg)

**Comment by Rushor** [comment]
![GitHub Logo](http://i.imgur.com/gdDvbJT.jpg)
![GitHub Logo](http://i.imgur.com/bxQLtu7.jpg)
![GitHub Logo](http://i.imgur.com/zG8SXFa.jpg)
![GitHub Logo](http://i.imgur.com/H2dEFTS.jpg)

Did it like you said.

    Kill
    Wait for respawn
    See if he falls through.

However i cannot reproduce this on PTR. 

Once the liveserver was updated with the recent mergefixes thiss issue should be solved. Thank you.

**Comment by Aridam** [comment]
To update on this here, the Quest works and is completable, but is in need of improvements -- namely one, which is the fact that Kaw proceeds to attempt to mount his Mammoth NPC, but it doesn't work and he just gets stuck on the ledge of the platform until his mount's been killed.

**Comment by TeridanDW** [comment]
Please continue in #4627 as there is more information there.
