### ISSUE TITLE
Quest: That's Abominable!

### ISSUE THREAD

**Issue by Sagrath** [dalaranwow/dalaran-wow#396]
http://www.wowhead.com/quest=13264/thats-abominable  - H quest
http://www.wowhead.com/quest=13289/thats-abominable  - A daily
http://www.wowhead.com/quest=13288/thats-abominable  - A quest
Players are able the summon the Reanimated Abomination but  the pet does not have pet control panel what is needed for the quest to be completed

How should it work: http://www.youtube.com/watch?v=mhvrLmicm4s

**Comment by ashido96** [comment]
As this quest became available again with the fix to icecrown phasing with recent updates. It's still bugged as described above, chilled guts drop at a correct rate and the Reanimated Abomination can be summoned correctly but it lacks a pet control panel with appropriate controls.

**Comment by Miztiq** [comment]
Confirming that it still dont give any pet control panel. So still bugged.

**Comment by Cone182** [comment]
still bugged

**Comment by deasease** [comment]
still same, fucksake

**Comment by MrAndersonX** [comment]
Confirmed - bugged. Needs a fix.

**Comment by Albulinek** [comment]
Still bugged

**Comment by NovaHiros** [comment]
This is still bugged - like i'm writing pretty much everywhere, just let these quests be auto-complete. Icecrown is a mess full of bugs and it's even hard to tell if you're going the right direction while trying to complete quests!

**Comment by DrFuler** [comment]
[22/04/2016] - Still bugged.

This need an urgent fix because it stop a whole quest tree.

**Comment by Lothloryen** [comment]
Hello there,

This quest has been fixed, it will be deployed with the next scheduled maintenance.

Thank you.

**Comment by whimsicalcyn** [comment]
Bugged again I guess?  No pet controls and not giving credit for killing the necessary bad guys.

**Comment by whimsicalcyn** [comment]
I found a workaround bug.  I summoned my trees (balance druid) and the pet bar for them always gets stuck on even after they disappear.  Then I used the kit and the pet bar changed to include the abomination's abilities.

May still be bugged for classes who can't summon anything though.
