### ISSUE TITLE
Warrior Character Missing Stances??

### ISSUE THREAD

**Issue by jameswilly16** [dalaranwow/dalaran-wow#3960]
I have created a Character and have played it for a long time however I have lost both my defence and berserker stances, and only have battle stance

I should be able to select either Stances to use with my level 50 warrior

I have tried several fixes myself which include

1. reload the game
2. reload the game interface
3. tried to follow up and look for old quest that may have missed however all seem completed

I have attached the follow screen show to show were it missing.
![stances gone](https://cloud.githubusercontent.com/assets/24521673/21095777/ec5c1538-c0ac-11e6-8cbb-e038a564dfb5.jpg)

and my spell book
![spellbook1](https://cloud.githubusercontent.com/assets/24521673/21095788/fb7d985c-c0ac-11e6-86b0-3dbf6e97f682.jpg)

![spellbook2](https://cloud.githubusercontent.com/assets/24521673/21095793/017dbff2-c0ad-11e6-9c93-117de7eba5bd.jpg)

![spellbook3](https://cloud.githubusercontent.com/assets/24521673/21095798/05967ce6-c0ad-11e6-9ce6-23a745fd35ae.jpg)
please only having battle stance again is painful

****

**Comment by Rushor** [comment]
Hello there,

please open up an ingame-ticket for such cases. A gamemaster will readd the spell for you. Thank you very much!
