### ISSUE TITLE
[Warlock] [Pet] Resistance

### ISSUE THREAD

**Issue by Horvic** [dalaranwow/dalaran-wow#3965]
Pet resistance is being calculated incorrectly for Burning Bile among other spells (probably everything)

**Current behaviour:**

Warlock pets receive too much damage from Burning Bile.

**Expected behaviour:**

The damage from Burning Bile should be much lower.

**Steps to reproduce the problem:**

1. Have a warlock pet at Northrend Beasts
2. Get Burning Bile
3. Stand next to your pet and see how much damage it takes.

**Include proof for this behaviour:**

**_Normal Trial of the Crusader:_**

World of logs from retail 25-11-09
http://www.worldoflogs.com/reports/a1klqhl4cgrm959i/spell/67621/?s=3741&e=4077

http://www.worldoflogs.com/reports/a1klqhl4cgrm959i/log/?s=3741&e=4077
Query Set: 
[{"spellNames": ["Burning Bile"], "targetNames": ["Pagyal"]}]

![ss 2016-12-13 at 02 59 59](https://cloud.githubusercontent.com/assets/13931276/21127859/2866d0fe-c0ee-11e6-993b-977868645281.png)

You can see the warlock imp "Pagyal" takes Burning Bile ticks ranging from 70 to 623, with an average hit of 224.36 and an average resist of 2537.48

World of logs from Dalaran-wow 02-04-16
http://www.worldoflogs.com/reports/d6kb318eampren7p/spell/67621/?s=75&e=382

http://www.worldoflogs.com/reports/d6kb318eampren7p/log/?s=75&e=382
Query Set: 
[{"spellNames": ["Burning Bile"], "targetNames": ["Rulnar"]}]

![ss 2016-12-13 at 04 40 18](https://cloud.githubusercontent.com/assets/13931276/21127869/43dbb584-c0ee-11e6-9407-4847adff745b.png)

The warlock imp takes Burning Bile ticks ranging from 1320 to 2857, with an average hit of 2114.2 and an average resist of 1046.86

**_Heroic Trial of the Crusader:_**

World of logs from retail 07-03-10
http://www.worldoflogs.com/reports/d58l6v8mlsxjy5f1/spell/67623/?s=1699&e=2208

http://www.worldoflogs.com/reports/d58l6v8mlsxjy5f1/log/?s=1699&e=2208
Query Set: 
[{"spellNames": ["Burning Bile"], "targetNames": ["Tarnar"]}]

![ss 2016-12-13 at 04 30 09](https://cloud.githubusercontent.com/assets/13931276/21127877/4d7720ba-c0ee-11e6-8ffc-824e36dd0149.png)

The warlock imp "Tarnar" takes ticks ranging from 1692 to 3703, with an average hit of 2511 and an average resist of 6397.25

World of logs from Dalaran-wow 26-11-16
http://www.worldoflogs.com/reports/ojl2u05kl8st0kus/spell/67623/

http://www.worldoflogs.com/reports/ojl2u05kl8st0kus/log/?s=93&e=526
Query Set: 
[{"spellNames": ["Burning Bile"], "targetNames": ["Pigbis", "Kartip"]}]

![ss 2016-12-13 at 04 36 24](https://cloud.githubusercontent.com/assets/13931276/21127881/53efa69c-c0ee-11e6-83e0-55b879c9fa25.png)

The warlock imps "Pigbis" and "Kartip" take ticks ranging from 3493 to 7020, with an average hit of 5590.42 and an average resist of 2788.92

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills:**

Burning Bile: http://wotlk.openwow.com/spell=66869

Possible future issues in ICC:

Festergut's Vile Gas - http://wotlk.openwow.com/spell=71218
Sindrogosa's Unchained Magic (Heroic Mode) - http://wotlk.openwow.com/spell=69762  / 
Instability - http://wotlk.openwow.com/spell=69766

After checking out the above I noticed the source of the Burning Bile aoe damage on retail was the player inflicted with the debuff rather than Dreadscale himself.
This is probably the reason friendly fire doesn't work for skada/recount/logs on this fight and any others like it.

**Comment by Rushor** [comment]
Fixed with:

Core/Pet: Corrected scaling in InitStatsForLevel

* all pets got aoe reduce spell avoidance and resistance (http://wotlk.openwow.com/?search=avoidance#spells) with that fix
Issue: https://github.com/dalaranwow/dalaran-wow/issues/3088
* commit: accc10a6640343df08d6918e24ff3413bc9adf5c
by @robinsch
