### ISSUE TITLE
[Spell] PX-238 Winter Wondervolt removed by using pvp trinket.

### ISSUE THREAD

**Issue by Alistories** [dalaranwow/dalaran-wow#3977]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: The PX-238 Winter Wondervolt buff is removed when one activates the pvp trinket under any effect; (possibly with no effect as well).
**Expected behaviour**: It should not be removed from anything except for death.

1. Get the buff.
2. Use your pvp trinket under any effect

Spell id: 26157

**Comment by Rushor** [comment]
http://wotlk.openwow.com/spell=26157 is atransform spell. pvp trinkets remove all transform. hm

**Comment by Alistories** [comment]
Still never experienced this in retail for some reason

**Comment by Rushor** [comment]
maybe we need to check if the transform is a buff or a debuff, in order to remove it

**Comment by Rushor** [comment]
Core/Aura: Don't remove holiday transform spells at trinket usage

Issue: https://github.com/dalaranwow/dalaran-wow/issues/3977
by @robinsch
