### ISSUE TITLE
Heroics and Emblem Gain

### ISSUE THREAD

**Issue by alexuktc** [dalaranwow/dalaran-wow#3978]
[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
When you kill a heroic boss you get Emblem of Heroism. 

**Expected behaviour**: Tell us what should happen instead
At our point in the progression people should be getting Emblem of Triumph from heroic bosses. Once ICC is out the first random heroic of the day should give 2 Emblems of Frost and there should be Weekly Raid quests giving 5 EoF and Triumph.

**Steps to reproduce the problem**:
Fairly simple:
1. Go to a heroic
2. Kill a boss
3. Profit?

**Include proofs for this behavior**
I don't need to. It's considered a wanted behavior on this server. Also as it has been mentioned before, all the Emblem drop mechanics have been explained on our server already - http://www.dalaran-wow.com/forums/news-and-rules/suggestions-and-opinions/topic/2126/algalon-progressive-emblem-drops

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**
Too many to list, and not important anyway.

**Include Screenshots from the issue if necessary**
They aren't, the issue is well known and documented. 

Now, I am hoping I can get in a discussion with GMs and/or developers and make my case as to why the current system on the server is flawed and how it can be improved. First thing first, the best solution will be to use the ToC/ICC system as that is truly Blizzlike and this server strives to be so. 

However I can understand your desire not to give "catch up" mechanics to people on lower tier levels. 

I have mentioned this several times in the past and never got an answer from someone with the authority to give one. If you can bar entry to certain raids based on Achievements you can change looting rules based on them as well. The link I provided has Lothloryen specifically saying that. I don't want a super easy EoT farm for people attuned to ICC. Most of us have been running ToC for a while and cannot really find an appropriate way to spend the EoTs we have. 

My main concern will be our inability to obtain Emblems of Frost outside of ICC and the few quest chains concerning the ICC dungeons. (I also need confirmation on that but I am fairly certain about it) The Damage, Healing and Health buff will never be applied to ICC meaning it will be really hard for all but the most advanced guilds. And you will need TogC gear to be able to meet enrage timers and whatnot. 

I believe the first random heroic of the day should give 2 EoFs and Weekly Raids should be allowed for people who are attuned to ICC. Even on live these were a big part of the EoF gain and it allowed people who were close, but not quite there yet to actually participate in progression. 

The current system just creates an elitism between top raiding guilds, who poach their most geared players in order to be able to match the requirements for ICC.

**Comment by Rushor** [comment]
as already said in https://github.com/dalaranwow/dalaran-wow/issues/3419 only loth can directly make those changes. On PTR this works completely different.
