### ISSUE TITLE
[ToC][Boss] Paladin Divine shield does not switch Impale aggro

### ISSUE THREAD

**Issue by plznoz** [dalaranwow/dalaran-wow#3979]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**:
When you use divine shield, Anub'arak's impale will still follow you.

**Expected behaviour**: 
When you use divine shield impale should select a new target while retaining their speed.

**Steps to reproduce the problem**:

1. Get chased by anub'arak in burrow phase as a paladin.
2. Use divine shield.
3. See that spikes follow you.

**Include proofs for this behaviour**
> Aggro dropping abilities (Feign Death, Vanish, Divine Shield, Iceblock) will cause the spikes to change target, but their speed will not be reduced.

http://wowwiki.wikia.com/wiki/Anub'arak_(Crusaders'_Coliseum_tactics)

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**
Divine shield:
http://wotlk.openwow.com/spell=63148

Impale:
http://wotlk.openwow.com/spell=65919
http://wotlk.openwow.com/spell=67858
http://wotlk.openwow.com/spell=67859
http://wotlk.openwow.com/spell=67860

**Comment by Rushor** [comment]
Scripts/TrialOfTheCrusader: Anubarak Spike will now follow normal aggro behaviour 

* Feign Death, Vanish, Divine Shield, Iceblock and silimar effects will now cause the creature to select a new target
* closes https://github.com/dalaranwow/dalaran-wow/issues/3979
* commit: 1771497dbc1b98039ab8df66c0a7bc7ef17a88d6

This fix can only be tested on live/livebranch.
