### ISSUE TITLE
[Ulduar] Doors in Descent to Madness not opening

### ISSUE THREAD

**Issue by Dartheus** [dalaranwow/dalaran-wow#3990]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Big doors between the main central area and General Vezax should be linked to the big mob in front of it, currently, most raids bypass it by running around the add without pulling it. Sometimes, the doors behind the add don't open after killing all 4 keepers, killing the add doesn't open them afterwards.

**Expected behaviour**: The last door before Gen. Vezax should be linked to the mob in front of it, opening only after it has been defeated

**Steps to reproduce the problem**:

1. Defeat all Keepers encounters
2. Kill the first Vezaxx trash
3. Bypass the Faceless Horror
4.  Door is opened without requiring you to kill the Faceless Horror

or

1. Defeat all Keepers encounters
2. Kill the first Vezax trash
3. Door behind the Faceless Horror is closed
4. Kill Faceless Horror
5. Door doesn't open, preventing further progress without GM assistance

Faceless Horror - 33772 (NPC)

**Comment by Dartheus** [comment]
adding sorta proof on how it should work: https://us.battle.net/forums/en/wow/topic/15098119834

"If you're talking about the first Faceless who spawns a shield and summons a voidwalker at 50%, upon killing him you can click the door and open it. You'll have a ramp to your left that takes you to General Vezax's room."

**Comment by Keader** [comment]
if i remember right, Faceless Horror is not requeriment for this door unlock.

**Comment by Rushor** [comment]
@Keader 100 % shure?

**Comment by Keader** [comment]
90% sure. After kill the last keeper, some trigger should send emote saying that Decent to Madness door is unlocked

**Comment by Rushor** [comment]
you may now some words from the emotetext? i will search for the broadcasttext id then :)

**Comment by Rushor** [comment]
alright here we have the emote: https://youtu.be/xlT0idl-tMw?t=2168

'<name of gameobject> unlocks!'

**Comment by Rushor** [comment]
and here we have the final proof: https://youtu.be/i2ZTL6Qo14g?t=2165

the emote was already popped up even if the Faceless Horror wasn't killed. Closing for now. :)

And ty @Keader for your help!! <3
