### ISSUE TITLE
[Ulduar] [Yogg-Saron] Malady of the Mind

### ISSUE THREAD

**Issue by Dartheus** [dalaranwow/dalaran-wow#3991]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Malady of the mind spreads to multiple targets upon expiration

**Expected behaviour**: Malady should spready only to 1 random target in range upon expiration

**Steps to reproduce the problem**:

1. Get affected by Malady of the Mind
2. Have more people within 10yards
3. Watch the madness

**Include proofs for this behaviour**

http://www.wowhead.com/spell=63830/malady-of-the-mind
"Inflicts 5000 Shadow damage and causes the enemy target to run in horror for 4 sec, then attempts to jump to another enemy within 10 yds. Also reduces Sanity by 3%." 

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

Malady of the Mind - 63830 (Spell)
Sara - 33134 (NPC)

**Include Screenshots from the issue if necessary**

This is a separated bug issue from #3564

**Comment by Rushor** [comment]
everything will be fixed together in this issue https://github.com/dalaranwow/dalaran-wow/issues/3564

**Comment by Dartheus** [comment]
Thanks @Rushor , wasn't sure if this wasn't being put off just because it was listed with multiple issues in #3564

**Comment by Rushor** [comment]
if there is an ticket already with multiple issues, just add it then :) Thanks.
