### ISSUE TITLE
Paladin "Sacred Cleansing" Talent & Proc

### ISSUE THREAD

**Issue by Tonixqt** [dalaranwow/dalaran-wow#3992]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: When paladins are using "Cleanse" (with the Holy talent named "Sacred Cleansing") : 
1) They seem to have too often the buff enabling them to increase resistance to Disease, Magic & Poison.
2)  Once they have the buff, they clearly resist more than they should.
Making things really umbalanced in the most of situation versus a holy paladins

**Expected behaviour**:  When paladins are using "Cleanse" (with the Holy talent named "Sacred Cleansing") : 
1) They only should have 10/20/30% (depending on the awarded points in "Sacred Cleansing) chance to get the buff.
2) Once they have buff, its should increase resistance to Disease, Magic & Poison by 30%

**Steps to reproduce the problem**:

1.  Take any caster or rogue with poisoned weapons 
2.  Wait for the paladin's buff after Cleanse 
3.  You nearly can't apply spells or poisons 

Hard to prove mathematically, but its blatant when you're doing some BGs or Arenas trying to apply poisons/spells on target who get the buff from Paladin cleanse

Spell ID: 53551

**Comment by robinsch** [comment]
Values are correct, that's RNG sadly.
