### ISSUE TITLE
I used my vote points, wrong character

### ISSUE THREAD

**Issue by mrandarkan** [dalaranwow/dalaran-wow#3997]
This is my fault. Please help me. I want to buy Blue Skeletal Horse for my Algalon character "Henip" but i did one mistake. This horse come my other character on Algalon "Hallelujax". I tried "Return" button for my 10 vote points but ı lost my points and my horse :( Anyone can help me or how can i do anything ?

http://i.hizliresim.com/3v7P8O.jpg

Thanks for everything.

**Comment by Crispybuilt** [comment]
Invalid report.
