### ISSUE TITLE
I used my vote points, wrong character

### ISSUE THREAD

**Issue by mrandarkan** [dalaranwow/dalaran-wow#3998]
#Sorry ı cannot do anything. I dont know this report system. Help me please.

[//]:VoteShop

[//]: # [General - Items]
![wowscrnshot_122116_184403](https://cloud.githubusercontent.com/assets/24701534/21400022/2bd71546-c7bf-11e6-828e-9b313a76f17d.jpg)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

This is my fault. Please help me. I want to buy Blue Skeletal Horse for my Algalon character "Henip" but i did one mistake. This horse come my other character on Algalon "Hallelujax". I tried "Return" button for my 10 vote points but ı lost my points and my horse :( Anyone can help me or how can i do anything ?

**Comment by Rushor** [comment]
![GitHub Logo](http://i.imgur.com/dAJRsN2.jpg)
![GitHub Logo](http://i.imgur.com/b39p4tZ.jpg)
![GitHub Logo](http://i.imgur.com/GhEMHCC.jpg)

The issuetracker is for ingame/servside issues only. Please write an Ingame-issue to a Gamemaster and the Gamemaster will then help you as soon as he can. Thank you.
