### ISSUE TITLE
[Quest][Northrend] Cutting Off the Source - Missing Gameobject

### ISSUE THREAD

**Issue by Rushor** [dalaranwow/dalaran-wow#4002]
For quest http://www.wowhead.com/quest=11602/cutting-off-the-source, there must be spawned more Nerub'er Egg Sacs http://wotlk.openwow.com/object=187655.

I will add 18 additional spawnpoints.

**Comment by Rushor** [comment]
Also the summoned creatures from the eggs Nerub'ar Swarmer http://wotlk.openwow.com/npc=25295 should attack the player on summon.

**Comment by Rushor** [comment]
DB/Quest: Cutting Off the Source - Add additional spawns for object ' Nerub'ar Egg Sac'

* closes https://github.com/dalaranwow/dalaran-wow/issues/4002
* commit: 28cae5df0f0ff33875a922b59516e82302d64c1a

DB/Creature: Nerub'ar Swarmer - Add attackstart on Spawn

* updates https://github.com/dalaranwow/dalaran-wow/issues/4002
* commit: a6cfd51e5020916431bbbf1dd5cd5822e5671501

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by TeridanDW** [comment]
After few tests on PTR:

> DB/Quest: Cutting Off the Source - Add additional spawns for object ' Nerub'ar Egg Sac'

Works as intended.

> DB/Creature: Nerub'ar Swarmer - Add attackstart on Spawn

Doesn't work unless the player moves after they summon, if not:
![wowscrnshot_110117_121153](https://user-images.githubusercontent.com/6797611/32270301-0b18b6b6-befe-11e7-82df-7f376aa6a954.jpg)

**Comment by TeridanDW** [comment]
Works as intended on PTR.
