### ISSUE TITLE
[Mechanic] Using defensive cooldowns when spell is mid air is pointless

### ISSUE THREAD

**Issue by Jiaku** [dalaranwow/dalaran-wow#4009]
**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
If you are warrior or rogue and you see spell is mid air poppin cloak or reflect/shieldwall is pointless due to damage will go through.
**Expected behaviour**: Tell us what should happen instead
you can use defensive cooldowns like cloak/reflect/shieldwall even when spell is mid air
**Steps to reproduce the problem**:

1. Start a duel against mage
2. Do a shatter combo
3.  Use cloak/reflect/shieldwall mid air of shatter combo

Cloak of shadows [http://wotlk.openwow.com/spell=31224]
Spell reflection [http://wotlk.openwow.com/spell=23920]
Shied wall [http://wotlk.openwow.com/spell=871]

**Comment by Rushor** [comment]
confirmed

**Comment by Rushor** [comment]
Ref: https://github.com/TrinityCore/TrinityCore/issues/577

**Comment by Rushor** [comment]
https://github.com/FeenixServerProject/Archangel_2.4.3_Bugtracker/issues/342

hm yeah https://eu.battle.net/forums/en/wow/topic/17614451290

> The fact that this post is upvoted deeply worries me.

> You can't reflect spells that are in mid-air, the cast has to have finished while Spell Reflect was up, not before.

So it's blizzlike. Thanks @robinsch 
@Jiaku if you find a source for shieldwall, please open a new issue
