### ISSUE TITLE
Quest: Seeds of Chaos

### ISSUE THREAD

**Issue by Sagrath** [dalaranwow/dalaran-wow#402]
http://www.wowhead.com/quest=13172

Keritose Bloodblade gives a gossip option that allows you to mount a skeletal gryphon for a quest called "Seeds of Chaos", but it won't work with/without quest picked up.

http://www.wowhead.com/npc=30946/keritose-bloodblade

Note: If you walk by foot and kill NPCs without the vechile they do not count towards the quest objactive.

**Comment by deasease** [comment]
works perfect counts everythign except plague hounds, tho fly mount must summon manually, but it work perfect as intended
