### ISSUE TITLE
[Feast of Winter Veil] Presents & Food

### ISSUE THREAD

**Issue by DrFuler** [dalaranwow/dalaran-wow#4027]
**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
Actually, two things:

1) I cannot get any Graccu's Mince Meat Fruitcake to complete the 'Tis the Season achievement, which sucks big time for someone like me who plays solely to get achievements. (I have all gear, just can't get the food). Basically, **I did the quests last year** and I have no idea where the food went, but now I can't redo the quests, so no food for me.

2) Cannot get any presents now that is 25 of december, while everyone is getting presents. **I got them last year**, but haven't got any these year. C'mon, last night I was at my family christmas party (irl) and everyone was getting presents but me, let me have this at least in game :X

**Expected behaviour**: Tell us what should happen instead

1) I expect to be able to complete the game achievements.  Apparently I'm stuck without having any way of getting the food required for achievement, therefore being doomed forever to live an existence without completing the 'Tis the Season achievement, and by consequence, Merrymaker. 

http://www.wowhead.com/achievement=277/tis-the-season
http://www.wowhead.com/item=21215/graccus-mince-meat-fruitcake#comments

On top of that, similar thing has happened to players of the original Blizzard servers, and the GMs have helped them out. For instance, on the second link above, there is a commenting reporting exactly that. Additionally, here is a proof of it (found it in someone's post):

https://postimg.org/image/nkbpds46b/

2) I haven't been naughty this year, so I expected to get something from the Great-father Winter.

**Steps to reproduce the problem**:

1) Play Dalaran WoW for 2 years in a row
- Do the Feast of the Winter Veil quests when you are in a low level
- Not be able to get the christmas hat that year because level 50 players can't do WofLK heroics
- Next year go for the heroics now you are level 80
- Get the hat
- But now your food is gone and there is no way to get it back
- Don't get the achievement you have been looking for for 2 years
- Cries in the corner of your tiny bedroom

2) Don't be naughty
- Don't get presents anyway this year
- =(

**Include proofs for this behaviour**

https://postimg.org/image/nkbpds46b/
^ same link as above, proving that GMs in Blizzard server has helped players with this issue before.

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

1) item=21215 (Graccu's Mince Meat Fruitcake)

**Include Screenshots from the issue if necessary**

2) https://s28.postimg.org/yfrvq6nt9/Wo_WScrn_Shot_122516_121011.jpg

**Comment by Rushor** [comment]
The reset for those quests will be done upon the next hours/days. Keep calm it will be done soon :)

Thank you.

**Comment by Rushor** [comment]
```sql
DELETE FROM character_queststatus_seasonal WHERE quest IN (6961,6962,6963,6964,6983,6984,7021,7022,7023,7024,7025,7042,7043,7045,7061,7062,7063,8746,8762,8763,8799,8827,8828);
DELETE FROM character_queststatus WHERE quest IN (6961,6962,6963,6964,6983,6984,7021,7022,7023,7024,7025,7042,7043,7045,7061,7062,7063,8746,8762,8763,8799,8827,8828);
DELETE FROM character_queststatus_rewarded WHERE quest IN (6961,6962,6963,6964,6983,6984,7021,7022,7023,7024,7025,7042,7043,7045,7061,7062,7063,8746,8762,8763,8799,8827,8828);
```

**Comment by DrFuler** [comment]
That is all I needed to know, thanks a lot Rushor :) looking forward to get it done.

**Comment by DrFuler** [comment]
Hey... I don't wanna be annoying, but I have been checking constantly for the past days and so far the reset haven't been on in the server.

Furthermore, today (01/01/2017), the event NPCs were no longer available (at least in Orgrimmar), which is odd because the ingame calendar says the event would go until tomorrow (the 2nd of january), and a lot frustrating because I haven't been able to complete the achievements yet (because of the issue originally reported here).

**Comment by Rushor** [comment]
I cannot change anything here. I did everything i could and informed the staffmember and the server owner.
