### ISSUE TITLE
[Quest][Northrend] The Restless Dead

### ISSUE THREAD

**Issue by Daveonx** [dalaranwow/dalaran-wow#403]
When players use Holy Water (id=43153) on the corpse of the Reanimated Crusaders players don't get any credit.

http://www.wowhead.com/quest=13110/the-restless-dead

**Comment by Rushor** [comment]
http://i.imgur.com/qSPC3pb.jpg works fine, you need to have quest 13104 rewarded in order to turn that quest 13110 in
