### ISSUE TITLE
[Quest][WotlK] Gamel the Cruel 

### ISSUE THREAD

**Issue by Rushor** [dalaranwow/dalaran-wow#4034]
[//]: # (***************************************************************)
[//]: # (** DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED **)
[//]: # (***************************************************************)

**Description:**
http://wotlk.openwow.com/quest=11619

Endevent for this quest is missing :) 

https://youtu.be/Y0lwVLflq_0?t=54

**Comment by Rushor** [comment]
DB/Quest: Gamel the Cruel - Add RP Endevent for Karuk and Ariut

* closes https://github.com/dalaranwow/dalaran-wow/issues/4034
* commit: 7b48288b09bb02e5187b4493ef1326e5afbb1abd

![GitHub Logo](http://i.imgur.com/R1u0pZk.jpg)

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by TeridanDW** [comment]
Works as intended on PTR.
