### ISSUE TITLE
Achievement: Soul Power

### ISSUE THREAD

**Issue by Crispybuilt** [dalaranwow/dalaran-wow#406]
Achievement: Soul Power - 4522

Issue: The achievement will pop regardless if you met or haven't met conditions to obtain it. Currently it pops every time you kill the boss.

How it should work: You should be only able to obtain that achievement IF you met the criteria for it which is: To defeat the boss with at least 4 Corrupted Soul Fragments alive.

Video how it has to look: http://www.youtube.com/watch?v=1gg7Ojsti2U

---

Minor Issue: Boss is also missing quote on the end when he dies which is:
"My soul for you, master." 
and emote: "Singing sounds, passing into dying sounds."

http://wotlk.openwow.com/achievement=4522
http://www.wowhead.com/achievement=4522/soul-power

**Comment by Rushor** [comment]
This was fixed with https://github.com/TrinityCore/TrinityCore/commit/e8c7d476416bcc42cf938178c729ac437ea9884e. Working on PTR.
