### ISSUE TITLE
Quest: Gorgrom the Dragon-Eater

### ISSUE THREAD

**Issue by solasgg** [dalaranwow/dalaran-wow#408]
http://www.wowhead.com/quest=10802/gorgrom-the-dragon-eater

The idea is to collect 3 grisly totem items from ogres, then summon Gorgrom the Dragon-Eater using the trap that you get from npc, using it on the Altar. Summoned  Gorgrom the Dragon-Eater is 139k hp elite that should walk into the trap and die, after that player must plant 3 grisly totems to complete the quest. The elite walking into a trap part doesn't work, he simply stands doing nothing, luring him doesn't do anything and planting 3 totems on the corpse doesn't work.

**Comment by Demlock** [comment]
The totem part works, well, quite well. You can plant them on the corpse for credit but the corpse needs to be summoned by you. Otherwise you can't plant totems on the body summoned by someone else. Furthermore, the script part with trap still doesn't work!

**Comment by jonanone** [comment]
Gorgrom the Dragon-Eater spawns and walks into the trap and dies. Then you can place the flags on the body. Working as intended.
