### ISSUE TITLE
[NPC] Quartermaster Miranda Breechlock

### ISSUE THREAD

**Issue by Klala** [dalaranwow/dalaran-wow#4097]
**Current behaviour**: Quartermaster Miranda Breechlock doesn't give you an option to buy argent dawn goods, however other Quartermasters of the argent dawn do let you purchase goods.

**Expected behaviour**: Quartermaster Miranda Breechlock should let you buy argent dawn goods

**Steps to reproduce the problem**:

1. Go to light's chapel at eastern plaguelands
2. Talk to buy argent dawn goods
3. Notice she gives you no option to buy anything.

I am currently revered with the argent dawn, just in case you wondered.

**Comment by Rushor** [comment]
works fine on PTR.

![GitHub Logo](http://i.imgur.com/MVv6Yyj.jpg)

you need to complete specific quests first:

```sql
INSERT INTO `conditions` VALUES (15, 3461, 0, 0, 0, 2, 0, 12846, 1, 0, 1, 0, 0, '', 'I need another Argent Dawn Commission. - Must not already have Argent Dawn Commission');
INSERT INTO `conditions` VALUES (15, 3461, 0, 0, 0, 8, 0, 5401, 0, 0, 0, 0, 0, '', 'I need another Argent Dawn Commission. - Must have completed Argent Dawn Commission Quest Alliance');
INSERT INTO `conditions` VALUES (15, 3461, 0, 0, 1, 2, 0, 12846, 1, 0, 1, 0, 0, '', 'I need another Argent Dawn Commission. - Must not already have Argent Dawn Commission');
INSERT INTO `conditions` VALUES (15, 3461, 0, 0, 1, 8, 0, 5503, 0, 0, 0, 0, 0, '', 'I need another Argent Dawn Commission. - Must have completed Argent Dawn Commission Quest Mage');
INSERT INTO `conditions` VALUES (15, 3461, 0, 0, 2, 2, 0, 12846, 1, 0, 1, 0, 0, '', 'I need another Argent Dawn Commission. - Must not already have Argent Dawn Commission');
INSERT INTO `conditions` VALUES (15, 3461, 0, 0, 2, 8, 0, 5405, 0, 0, 0, 0, 0, '', 'I need another Argent Dawn Commission. - Must have completed Argent Dawn Commission Quest Horde');
INSERT INTO `conditions` VALUES (15, 3461, 1, 0, 0, 8, 0, 5401, 0, 0, 0, 0, 0, '', 'I would like to buy from you. - Must have completed Argent Dawn Commission Quest Alliance');
INSERT INTO `conditions` VALUES (15, 3461, 1, 0, 1, 8, 0, 5503, 0, 0, 0, 0, 0, '', 'I would like to buy from you. - Must have completed Argent Dawn Commission Quest Mage');
INSERT INTO `conditions` VALUES (15, 3461, 1, 0, 2, 8, 0, 5405, 0, 0, 0, 0, 0, '', 'I would like to buy from you. - Must have completed Argent Dawn Commission Quest Horde');
INSERT INTO `conditions` VALUES (15, 3461, 2, 0, 0, 8, 0, 5401, 0, 0, 0, 0, 0, '', 'Miranda, could you please tell me the insignia cost of items - Must have completed Argent Dawn Commission Quest Alliance');
INSERT INTO `conditions` VALUES (15, 3461, 2, 0, 1, 8, 0, 5503, 0, 0, 0, 0, 0, '', 'Miranda, could you please tell me the insignia cost of items - Must have completed Argent Dawn Commission Quest Mage');
INSERT INTO `conditions` VALUES (15, 3461, 2, 0, 2, 8, 0, 5405, 0, 0, 0, 0, 0, '', 'Miranda, could you please tell me the insignia cost of items - Must have completed Argent Dawn Commission Quest Horde');
```

**Comment by Klala** [comment]
That's only partially correct. I figured this problem is happening because the recent fix for that particular quest but this is not correct.

This NPC is supposed to sell you Argent Dawn goods from being friendly and above. The quest you are talking about only unlocks additional shoulder enchants from revered and another shoulder enchant from exalted, however, the regular [goods](http://wowwiki.wikia.com/wiki/Miranda_Breechlock#Sold_Goods) should be sold regardless of those quests being completed or not. the only requirement for those goods is reputation.

http://wowwiki.wikia.com/wiki/Miranda_Breechlock?oldid=2445319

**Comment by Klala** [comment]
Please reopen this issue

**Comment by Rushor** [comment]
oh alright, will add this tomorrow :)

**Comment by Rushor** [comment]
DB/Creature: Miranda Breechlock - Option "I would like to buy from you." - Must only have Argent Dawn friendly up to exalted

* closes https://github.com/dalaranwow/dalaran-wow/issues/4097
* commit: 0434ab1bee34ac5589925f5a8cb9b21ecae810df
* The condition, that specific enchants only show up if Mantles of the Dawn  or Chromatic Mantle of the Dawn already works fine on PTR.
* old conditions for gossip option replaced with the reputation check @Klala 

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
