### ISSUE TITLE
Quest: The Black Knight's Orders

### ISSUE THREAD

**Issue by Golganeth** [dalaranwow/dalaran-wow#410]
http://www.wowhead.com/quest=13663

**Issue:** Upon using the provided item "Enchanted Bridle" next to the Gryphon, you are not getting automatically carried to the Black Knight's house, therefore, that part of the quest is impossible to complete.

* Enchanted Bridle - http://www.wowhead.com/item=45083
* Black Knight's Gryphon - http://www.wowhead.com/npc=33513
* Black Knight's Gryphon (once you use the Bridle) - http://www.wowhead.com/npc=33519

**Just a side note:** it's part of the chain quest to achieve "It's Just a Flesh Wound" -  http://www.wowhead.com/achievement=2773

**Comment by Lothloryen** [comment]
Working properly since long time ago.
