### ISSUE TITLE
Quest: Teleport This!

### ISSUE THREAD

**Issue by Crispybuilt** [dalaranwow/dalaran-wow#411]
Quest Teleport This! - 10857
Issue: After you use "Mental Interference Rod" on any of the "Cyber-Rage Forgelords" you do not have control over them. Instead, a buff applies on you which is called "Mental Interference". It shouldn't work like that.

How it should work, from WoWHead: You must use the Rod to Mind Control one of the Cyber-Rage Forgelords near the portals and use their Detonate ability while standing next to it. If your pet bar doesn't show up, the ability's hot-key should default to Ctrl+5.

- 16943 - Cyber-Rage Forgelord
- 31678 - Mental Interference Rod

http://www.wowhead.com/quest=10857/teleport-this
http://wotlk.openwow.com/quest=10857

Another tip: if the pet bar doesn't appear, try using this macro:
/Script PetActionBarFrame : Show()

**Comment by Demlock** [comment]
Works completely now
