### ISSUE TITLE
[Quest][NPC][Northrend] Xink's Shredder

### ISSUE THREAD

**Issue by Crispybuilt** [dalaranwow/dalaran-wow#412]
NPC Xink's Shredder - 27061

Issue: Vehicle works fine and the abilites but the only minor bug is that if you use Launch Saw Blades or Twisting Blade on no target, it will damage you and the vehicle.

How it should work: If you attempt to cast that on no target, it shouldn't damage you.

http://www.wowhead.com/npc=27061/xinks-shredder#abilities
This is part of the quest: 
http://www.wowhead.com/quest=12052

**Comment by Rushor** [comment]
todo: add spell attribute

**Comment by Rushor** [comment]
- spell 47938  can no longer target yourself

morepver these is another issue currently, you cannot enter Xink's Shredder after you summoned it. please open a new issue for this. you can test it if you target the vehicle and cast spell 47920 on it

**Comment by Golganeth** [comment]
#3367

**Comment by Golganeth** [comment]
Tested it by casting 47920 on vehicle. Twisting Blade still kills you if you cast the spell while having NO target.

**Comment by Rushor** [comment]
ah k EffectChainTarget = 1 is the problem here, like for the deathstorm spell

**Comment by Rushor** [comment]
e41e1a0656d5453f4353d6eca2d7e546254fd01b
99e6daa28c62a5bdbef255c9af937553220b36d7

conditions added
