### ISSUE TITLE
[Hunter][Skills]Volley turns hunter around.

### ISSUE THREAD

**Issue by sulblazer** [dalaranwow/dalaran-wow#4125]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: 
When casting volley, the execution of the spell channel will rotate the character to face away from the volley location.  I have not tested to see if this happens with all Hunter races, but I play a male dwarf with a wolf as a pet and this certainly happens.  I have, however, seen follow hunters (female dranei) also get turned around while in an instance. 

**Expected behaviour**: Tell us what should happen instead
While casting volley, the hunter channeling the spell should not be turned around.  It certainly did not do that on retail.

**Steps to reproduce the problem**:
Have a hunter cast Volley.  It may take a few times, but inevitably, the hunter will be turned around.

**Comment by Rushor** [comment]
added the issue to this ticket https://github.com/dalaranwow/dalaran-wow/issues/835. hank you.
