### ISSUE TITLE
Phasing during fear

### ISSUE THREAD

**Issue by Tonixqt** [dalaranwow/dalaran-wow#4130]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: 
During the fear, the phasing isnt working well. People are randomly displaced, but the animation of the character isnt following. At the end of the fear, the character who were feared is just teleported at his real place.

**Expected behaviour**: When a character is feared, it should be randomly moved & we should see him doing it. 

**Steps to reproduce the problem**:

1. Do a duel
2. Using fear
3. Notice the phasing isnt working well

**Include proofs for this behaviour**

**Include Screenshots from the issue if necessary**

**Comment by Rushor** [comment]
https://github.com/dalaranwow/dalaran-wow/issues/1447 duplicate, the fix for it will be tested on ptr
