### ISSUE TITLE
NPC: Umbraglow Stinger

### ISSUE THREAD

**Issue by Crispybuilt** [dalaranwow/dalaran-wow#414]
NPC Umbraglow Stinger - 18132

Issue: His ability "Glowing Blood" doesn't work correctly. Upon applied on the target, player can still go Invisible, in Stealth or even Prowl.

How it should work: Player should not be able to go invisible, stealth or prowl if the debuff us applied on him.

http://wotlk.openwow.com/spell=35325
http://wotlk.openwow.com/npc=18132
http://www.wowhead.com/npc=18132/umbraglow-stinger

**Comment by Rushor** [comment]
162a65c62f6e13c23edb0ae8f482058ef7a44679
- u can no longer use stealth if you have that aura 35329

**Comment by Golganeth** [comment]
35325*

**Comment by Golganeth** [comment]
Glowing Blood 35325 still broken

**Comment by Rushor** [comment]
85d4f37b73ef2d228ca932ce9076f4a833186b22
- added
