### ISSUE TITLE
Instant level 70 Service- "Instant 70 + 2 Heirloom items + Tome of Cold Weather Flying" Error

### ISSUE THREAD

**Issue by santelmo666** [dalaranwow/dalaran-wow#4143]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
  After donating 25€ in the account "santelmo95" (29 donation points), I chose the second option to boost my character named "Ildren" to level 70 (23 donation points) which includes the normal green gear and the 900 gold, but also two heirloom items and the Tome of Cold Weather Flying. What happened is that after I requested the service and did everything you told me to (log in first with the character to skip the initial video, and log off), the character didn't get the boost or the green items. It was still teleported to Stormwind next to the inkeeper, got the 900 gold, the 2 heirloom items and the Tome of Cold Weather Flying.
**Expected behaviour**: Tell us what should happen instead
  The second option to boost the character, that costs 23 donation points: "Instant 70 + 2 Heirloom items + Tome of Cold Weather Flying" , is supposed to (as the title says) boost the character to level 70, send 2 heirloom items and send the Tome of Cold Weather Flying but also, send 900 gold and the green gear. 
**Steps to reproduce the problem**:

1. Prepare the character for the boost: Create the character > skip initial video > log off;
2. Pay the second option of the instant level 70 service: "Instant 70 + 2 Heirloom items + Tome of Cold Weather Flying" (23 donation points);
3. Log in.

**Include proofs for this behaviour**
http://www.dalaran-wow.com/account/character/instant-70/

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**
Items I have got: Stained Shadowcraft Spaulders- [itemID=42952]
Stained Shadowcraft Tunic- [itemID=48689]
Tome of Cold Weather Flying- [itemID=49177]

**Include Screenshots from the issue if necessary**
![instant 70](https://cloud.githubusercontent.com/assets/23239587/21729078/5422fe6e-d441-11e6-9924-0d5e8bc0aa1e.jpg)
![wowscrnshot_010617_110014](https://cloud.githubusercontent.com/assets/23239587/21729085/59f00b98-d441-11e6-8e79-eb25c5cfdc39.jpg)
![wowscrnshot_010617_110856](https://cloud.githubusercontent.com/assets/23239587/21729091/5e72b2ec-d441-11e6-98dc-0f4a0863c0a2.jpg)
![wowscrnshot_010617_173135]
![wowscrnshot_010617_191900](https://cloud.githubusercontent.com/assets/23239587/21729930/2dae5ab8-d445-11e6-83b2-32c1272a1d1e.jpg)

**Comment by Rushor** [comment]
-- GM ONLY --
The issuetracker is for ingame/serverside issues only. Please write an Ingame-issue to a Gamemaster and the Gamemaster will then help you as soon as he can. Thank you.

![GitHub Logo](http://i.imgur.com/bYkYeGQ.png)

**Comment by Rotteknuser** [comment]
I did the boost and got my dude up to lvl 70, but no gear and no gold, so I thought i try again, that time i got level 70 and gear but no gold....... wy is it happening? do i get the gold soon?
