### ISSUE TITLE
Quest: WANTED: Boss Grog'ak

### ISSUE THREAD

**Issue by Golganeth** [dalaranwow/dalaran-wow#415]
http://wotlk.openwow.com/quest=9820

**Issue:** Alliance players should not be able to pick up mentioned quest from the "Wanted Poster" of Zabra'jin (which is an Horde camp).

Once Alliance players complete it, they are not able to be rewarded since the NPC is only friendly to the Horde.
This ends up on the player sending a ticket saying he can't hand it in, when in the first place, the faction should not have that quest available.

* *Wanted Poster* - http://wotlk.openwow.com/object=184660

**Comment by Rushor** [comment]
http://i.imgur.com/yk5Dbeo.jpg

was already fixed

**Comment by Golganeth** [comment]
Wrong poster the quest isn't from Blade's Edge, it's from Zangarmarsh. Still available to Alliance players when it should only be available to Horde.

[Wanted Poster] GUID: 22646 ID: 182165
http://www.wowhead.com/quest=9820/wanted-boss-grogak

**Comment by Rushor** [comment]
551f1116b54ba439b0e0e40e7829aea644ca98ec
- added the racecondition for http://www.wowhead.com/quest=9820/wanted-boss-grogak
