### ISSUE TITLE
RAF ~ Mail Issues ~ HELP :)

### ISSUE THREAD

**Issue by hibestfriend** [dalaranwow/dalaran-wow#4158]
My friend refereed me to Dalaran-WoW and i got premium, he got the Mounts but we are not getting the 3x exp and or summoning and I accidentally hit "Return" on one of the items I bought with DP and I'm not able to get it back?

**Comment by Golganeth** [comment]
The bug tracker only lists in-game issues with quests, NPCs and such. Please write an ingame ticket and your issue will be sorted out.

Closed.
