### ISSUE TITLE
Quest: We have the Power - Horde / Alliance

### ISSUE THREAD

**Issue by Crispybuilt** [dalaranwow/dalaran-wow#417]
Quest We have the Power - 12197/12131

Issue: The quest items that drop from Rune-Smith Durar and Rune-Smith Kathorn should be 100%. Currently, they do drop but not always, I killed Kathorn 4 times and then it dropped it, same with Durrar. The drop chance has to be corrected.

http://wotlk.openwow.com/npc=26409
http://wotlk.openwow.com/quest=12197
http://wotlk.openwow.com/quest=12131

**Comment by Xehpo** [comment]
As of today (01/24/15) Kathorn dropped it the first time I killed him (maybe luck), but Durar... well, I'll have to farm him some more, I guess.

**Comment by LoopyDemon** [comment]
It did not drop the first time I killed either of them.

**Comment by Zoombala** [comment]
Still the drop rate on Kathorn not fixed

**Comment by aepoirier** [comment]
Commenting to update that this issue is still unresolved. I am on my 4th Kathorn kill with no power cell drop.

**Comment by Archcry** [comment]
I can confirm this, not 100%

**Comment by MrAndersonX** [comment]
Confirmed - bugged. Needs a fix.

**Comment by rinleezwins** [comment]
Still...

**Comment by Lothloryen** [comment]
Hello there,

Corrected.
