### ISSUE TITLE
[Blacksmithing] - You can learn weaponsmith recipes while being armorsmith.

### ISSUE THREAD

**Issue by Klala** [dalaranwow/dalaran-wow#4175]
**Current behaviour**: You can learn weaponsmith recipes while being armorsmith.

**Expected behaviour**: You shouldn't be able to learn weaponsmith recipes while being armorsmith.

**Steps to reproduce the problem**:

1. Finish the quests to be an armorsmith and go talk to the weaponsmith in dalaran or any other city where there is a weaponsmith trainer.
2. Learn what he has to offer you (some of those recipes can be learned and that's correct but recipes like "Light Earthforged Blade" which does require you to be weaponsmith shouldn't be learnable)

In the following link it explains how only a blacksmith who have learned the weaponsmithing specialty can learn this recipe.
http://wowwiki.wikia.com/wiki/Light_Earthforged_Blade

While on this link it tells you that prior to 2.0.3 you had to have the weaponsmith specialty to learn the recipe.
http://wowwiki.wikia.com/wiki/The_Shatterer

**This fix should be applied to all recipes which have a specialty requirement on the crafted item**

**Comment by Rushor** [comment]
moved to https://github.com/dalaranwow/dalaran-wow/issues/1483
