### ISSUE TITLE
Quest: Showdown - Alliance / Horde 

### ISSUE THREAD

**Issue by Crispybuilt** [dalaranwow/dalaran-wow#418]
Quest Showdown - 10806 / 10742

Issue: The event is missing for this quest. For the horde currently, if you use 	Rexxar's Battle Horn, it will spawn both Rexxar and Goc but the event will not trigger or start, therefore Goc is not attackable and you are unable to finish the quest.

As for the alliance: If you use Sablemane's Signet apsolutely nothing happens.
- Sablemane's Signet - 31808
- Rexxar's Battle Horn -31146

____________________________
Temporary solution for now: You could just spawn Goc and make him attackable by anyone with respawn timer of 5 minutes.

How it should work: 
http://www.youtube.com/watch?v=utv6UA1lSBY - Alliance Version

http://www.wowwiki.com/Quest:Showdown_(Alliance)
http://www.wowwiki.com/Quest:Showdown_(Horde)

http://wotlk.openwow.com/quest=10806 Alliance
http://wotlk.openwow.com/quest=10742 Horde

**Comment by jonanone** [comment]
Using the quest item near the Altar of Goc will summon Goc and your faction hero (The quest giver) to help you fight Goc. The fix will be applied to the live realm soon.

**Comment by Rushor** [comment]
DB/Quests/Blade Edge Mountains: Showdown.

Using the quest item near the Altar of Goc will summon Goc and your faction hero (The quest giver) to help you fight Goc.
Quest item is not usable while Goc is already summoned around the Altar.

Closes https://github.com/dalaranwow/dalaran-wow/issues/418

* commit: a0d46131058549c26f5377b890f1d20f969aa042
* commit: 4f5d375aa370f9949c161c5abba152d9ed3d2790
