### ISSUE TITLE
NPC: Kurzen Commando

### ISSUE THREAD

**Issue by Crispybuilt** [dalaranwow/dalaran-wow#42]
NPC Kurzen Commando - 938

Issue: The issue is related with #41 
They are floating above the ground when in stealth and when engaged into combat. 
They are not standing on the solid texture.

**Comment by TheLichWarrior** [comment]
o yea change of style haha

**Comment by Rushor** [comment]
caused by wrong byte types in creature_(template_)addon.

**Comment by Rushor** [comment]
http://i.imgur.com/oEg2p5i.jpg
http://i.imgur.com/xd77qKu.jpg
http://i.imgur.com/Ni6v0jk.jpg

already fixed by tc
