### ISSUE TITLE
Quest: Warning: Some Assembly Required

### ISSUE THREAD

**Issue by Golganeth** [dalaranwow/dalaran-wow#421]
http://wotlk.openwow.com/quest=11310

**Issue:** Currently, after using "Abomination Assembly Kit" you summon the abomination but you can't get control over it, it just spawns and stands there.
* Mindless Abomination - http://wotlk.openwow.com/npc=23575

**How it should work:** After using the item, you summon and control the "Mindless Abomination" to slay 20 plagued Vrykuls. To accomplish that, your abomination will get the following skills:
* Plagued Blood Explosion - http://wotlk.openwow.com/spell=42166
* Thunderclap - http://wotlk.openwow.com/spell=61359

**Video of how it has to look like:** http://www.youtube.com/watch?v=YVVIAilj-AI

**Comment by Golganeth** [comment]
- Credit not given sometimes after using [Plagued Blood Explosion](http://wotlk.openwow.com/spell=42166)
- The NPCs [Plagued Dragonflayer Rune-Caster](http://wotlk.openwow.com/npc=24198) don't die and don't give credit. This causes the player to get stuck in combat or unable to move sometimes. The other NPCs work fine.

**Comment by ashido96** [comment]
Using Thunderclap or Meele attacks to kill any of the mobs will not give quest credit, making this very slow and painstaking to complete.

http://wotlk.openwow.com/spell=61359

**Comment by deltafoxnine** [comment]
I couldn't summon the abomination, then i dismissed my pet, and it worked!

**Comment by rinleezwins** [comment]
Stuck at 4/20 not getting credit for the monsters killed by explosion.

**Comment by Lothloryen** [comment]
Quest working as intended.
