### ISSUE TITLE
Quest: Vision Guide

### ISSUE THREAD

**Issue by Crispybuilt** [dalaranwow/dalaran-wow#422]
**Quest Vision Guide - 10525**

**Issue:** When you use the Item (Fiery Soul Fragment - 30481) it sends you on flying journey where you have to discover artifact inside the cave. 
When you arrive at the destination the quest does not get completed.

**Minor Issue:** The player is not transformed into a wisp, and he should. He has to be transformed into a Red Wisp during the travel.
![image](https://f.cloud.github.com/assets/5054924/919149/c06fe25a-fec3-11e2-9768-5eeb6300f46b.png)

**Hot fix:** 
- Basically just add a trigger zone, when the player successfuly arrives there and steps inside the zone, the quest is completed.

**Hot fix for model:** 
- Simply morph player into a Wisp (ID: 10045) and add the color of being red once he uses the item and starts flying, when he arrives on location, .demorph the player back to his usual state.

___________________________________
http://www.wowhead.com/quest=10525/vision-guide
http://www.wowwiki.com/Quest:Vision_Guide
http://wotlk.openwow.com/quest=10525
http://wotlk.openwow.com/item=30481

**Comment by Demlock** [comment]
This quest works.

**Comment by Rushor** [comment]
fixed in https://github.com/TrinityCore/TrinityCore/commit/5ac2f87c1400f004d6e2ed162512c85e6f1ed860
