### ISSUE TITLE
[EN][Spell][Paladin]Hand of Reckoning 

### ISSUE THREAD

**Issue by TheRealestMcCoy** [dalaranwow/dalaran-wow#4221]
**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
After a little testing i noticed that with taunt on my pally with 0%hit but the 1% from heroic presence. Out of 10 taunts on 10 diff creatures taunt did not miss once. 
**Expected behaviour**: Tell us what should happen instead
IN WoTLK taunts are spell based and require spell hit which why is most tanks can glyph 8%. Taunt should not alwaysd hit if under the spell hit. This was not changed until Cata making taunts unmissable.
**Steps to reproduce the problem**:

1. Have no hit if possible and or glyph
2. run around taunt creatures 
3. 

**Include proofs for this behaviour**
You can see in the screen shot i have 0 hit raiting but again have 1% from heroic presence but made 9 taunt 90% hits and 1 crit taunt 10% thats 100% with out missing 1 time at 0 hit. 

![wowscrnshot_011317_223058](https://cloud.githubusercontent.com/assets/12252441/21952043/fd5cd466-d9df-11e6-9a3f-bebaacb44c3b.jpg)

After doing another test out of 17 taunts of npc's not attacking me 13 hits 2 crits and 2 misses. These where all level 80mobs. To need 17% hit with only 1 from racial i think i would miss more. 

![wowscrnshot_011317_224337](https://cloud.githubusercontent.com/assets/12252441/21952115/ea8ea60a-d9e1-11e6-950a-e4cd7cea07bf.jpg)
 
You can research this on several pages like http://wowhead.com or http://wowwiki.wikia.com or http://www.youtube.com/
Issues without proofs will be closed and tag On Hold will be added until the proof is provided.
[Hand of Reckoning](http://wotlk.openwow.com/spell=62124)
**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

You can research this on several pages like http://wotlk.openwow.com or http://wowhead.com/

**Include Screenshots from the issue if necessary**

Here are all patch notes for this spell

Small Patch 4.0.1 (12-Oct-2010): Removed miss chance of this effect. (Untested, based of testing on Growl and Dark Command)
Hotfix (2009-08-08): "Hand of Reckoning is no longer able to be used on targets that are immune to taunt, including players." 
Patch 3.2.0 (04-Aug-2009): Redesigned. Now does damage only when the target does not currently have the caster targeted, but damage done increased to 50% of attack power, occurring after the taunt effect is applied.
Patch 3.1.0 (14-Apr-2009): Now affected by Benediction.
Patch 3.0.8 (2009-01-20): Added.

**Comment by Mike-Hunt** [comment]
The 17% spell hit cap that you are quoting is for players against mobs 3 levels higher, i.e. against bosses. You were testing as a level 80 player against level 80 mobs which means that the spell hit requirement is 4% (source: http://wowwiki.wikia.com/wiki/Spell_hit).
With the Draenei racial, that means that you had a 3% miss chance against the mobs you were taunting, rather than the 16% chance you suggest. Regardless, a sample size of 17 is too small to indicate proof of much at all.

**Comment by TheRealestMcCoy** [comment]
I will get more sample sizes from raid bosses as we get into raiding this weekend. But i heard some other haven't noticed any taunts missing.

**Comment by Rushor** [comment]
created new level 80 paladin, no spellhit added, taunted level 80 elite > several misses

http://i.imgur.com/kgH9sGI.jpg

Works fine for me on PTR.
