### ISSUE TITLE
Fragments of Val'anyr drop rate

### ISSUE THREAD

**Issue by Dibbarra** [dalaranwow/dalaran-wow#4258]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
Yogg-Saron (25m) is suppose to have a 100% fragment droprate, but one currently does not drop when he is killed (people currently screenshot the kill and submit a GM ticket). Also, other bosses seem to have much lower than expected drop rates.
**Expected behaviour**: Tell us what should happen instead
Yogg should always drop a fragment, and other bosses should have an increased drop rate for hard-mode fights. A comment in the source also seems to suggest that Hodir HM can possibly drop two (hard mode loot cache and normal loot cache). Other comments suggest that normal mode drop rate is 10%, and 15% for hard modes.
WoW website lists the drop rates with qualitative assessments of drop rates.
**Steps to reproduce the problem**:

1. kill yogg.
2. loot.
3. probably no fragment.

**Include proofs for this behaviour**
- http://www.wowhead.com/item=45038/fragment-of-valanyr#comments
- http://wow.gamepedia.com/Fragment_of_Val%27anyr
- http://us.battle.net/wow/en/item/45038#tab=dropGameObjects
**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**
- http://www.wowhead.com/item=45038/fragment-of-valanyr

**Comment by Rushor** [comment]
duplicate https://github.com/dalaranwow/dalaran-wow/issues/2247

the fix will be tested on ptr

**Comment by Dibbarra** [comment]
That fix does not seem to address other bosses and the extremely low drop rate observed in general. What about HM Hodir having a chance to drop two fragments?

**Comment by Rushor** [comment]
HM Hodir drop already works fine on ptr
