### ISSUE TITLE
[NPC][WotlK] Ironwool Mammoth, Part 2, patrolling event

### ISSUE THREAD

**Issue by Teridan-dal-wow** [dalaranwow/dalaran-wow#4275]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Hello! There should be a group of Ironwool Mammoths http://wotlk.openwow.com/npc=29402 patrolling, however the event is missing on the server.
This report will contain 2 parts. 

Part 1:

- Ironwool Mammoths http://wotlk.openwow.com/npc=29402 shown on the picture below should be removed as they are invalid spawns, because they should be part of the event described in Part 2 of this report.
![wowscrnshot_012017_163630](https://cloud.githubusercontent.com/assets/6797611/22154861/dec1b232-df35-11e6-9823-4bd3d9cedb7d.jpg)
![wowscrnshot_012017_163608](https://cloud.githubusercontent.com/assets/6797611/22154878/ee689750-df35-11e6-928e-342001edf6b8.jpg)

**Expected behaviour**: 
Part 2:
- Recorded video from retail legion from 20.01.2017 of the event:
https://www.youtube.com/watch?v=hSZ7u79gVeo
- You can see the coordinates under the portrait of my char, that will help for wp locations.
- There is ingame timer bottom right for respawn timer, lenght of the event and a way to set the correct run speed of the mammoths. (My guess its around 300%)
- My speed ingame is 100% normal + 310% epic mount + 10% guild perk.

Conditions:
1) There can not be more than 1 group of mammoths patrolling at the same time.
2) The group has a leader and if he is killed a new one is choosen. (Randomly i asume)
3) The group is not linked, meaning you can kill one without the rest engaging you.
4) At the both ends of the patrol, the group leader gains temporaly movement increase  so he can move to lead possitioning.
5) Players can kill up to 4 mammoths, but  as long as  there is 1 alive the event continues its loop.( Dead mammoths do NOT respawn, only after the event is over( all 5 are dead) a new pack spawns.)
6) The respawn time of the event starts once the last mammoth from the group dies.
7) The despawn timer for the bodies of the mammoths is the same like on any other creature in the world.

**Comment by Rushor** [comment]
we can only fix the movement and the spawnposition at the current state of the core. everything else (leader patrole position change, linked respawn for tempsummons, follow action for tempspawns must all be fixed in core first)

summon @robinsch here (i know you hate db stuff) but a general core implementation for such detailed things would be pretty nice :)

so 
we need a way that alows us to:

1.)  make creatures respawn only if all linked creatures (in creature_formation or sth. else) are killed
2.) After the leader of a groupformation was killed > a new guid will be choosen and that one will lead the rest of the members

**Comment by Rushor** [comment]
@Teridan-dal-wow you are https://www.youtube.com/channel/UCjIDZUP9H06NIBPApW6I3GA?

**Comment by Rushor** [comment]
DB/Creature: Ironwool Mammoth - Add Pathing and Formation

* closes: https://github.com/dalaranwow/dalaran-wow/issues/4275
* commit: b66bad299b6d9866c99cc5700f4cdc30ee8536e2

![GitHub Logo](http://i.imgur.com/CD2JbRr.jpg)

The two points i mentioned in my last post, cannot be fixed currrently. Once a way was implemented in core i will fix it : :)

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by Teridan-dal-wow** [comment]
Feedback for this report from TrinityCore rev. 02633a332cf7 2017-02-09.

 - Their movement speed of the Mammoths seems to be slower than on retail.
How did i test it? Set my movement speed to normal and use any 100% speed ground mount and run after the pack, i am gaining on them, while on retail as soon as i touch the ground with my mount i am starting to fall behind the pack rapidly (check the video above at 2.09s).
 - Regarding the "workaround", its acceptable however i found a small bug, if you kill the pack leader far away from the first wp, the other 4  Mammoths will wait still for their leader to respawn. Here is the tricky part - you need to have 1 person at the first wp and 1 where the 4 mammoths are waiting. As soon as the leader respawns and passes thought the first wp the 4 mammoths will start running toward thier leader (ignoring all wps, line of sight even textures (yes my vmaps and mmaps are installed properly)) in a straight line. If the description wasn't very clear i can record a video if you want me to.
Possible solution might be for the 4 mammoths to wait still until their leader passes though the last wp that they did and then to start running back to him.

**Comment by Teridan-dal-wow** [comment]
Can 

> Their movement speed of the Mammoths seems to be slower than on retail.

be fixed now that we have #4453 ?

**Comment by Rushor** [comment]
which movement speed do you suggest?

currently: speedwalk = 0.666668, speed_run = 1.5

**Comment by Teridan-dal-wow** [comment]
Hm, they should never walk (from what i saw on retail), so speed_run should be changed (but only for the ones that are part of the event, not for all mammoths) and its hard to give value here. Should be around 300% player movement speed, based on the mount test on retail (where i had 100%normal + 310% mount + 10% guild perk).

**Comment by Rushor** [comment]
would you like to test it locally with speed_run = 1.9 (added for all mammoths then, i will limit that on PTR to match only the affected guids with the path)

**Comment by Teridan-dal-wow** [comment]
speed_run = 2.9 seems about right to me.

**Comment by Rushor** [comment]
this shoudl fix it then:

```sql
-- Ironwool Mammoth SAI
UPDATE `creature` SET `saiscriptflag`=1 WHERE  `guid` IN (116908, 116909, 116910, 116911, 116907);
SET @GUID := -116908;
DELETE FROM `smart_scripts` WHERE `entryorguid` IN (-116909, -116910, -116911, -116907, -116908) AND `source_type`=0;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(-116909,0,0,0,25,0,100,0,0,0,0,0,208,0,2.9,0,0,0,0,1,0,0,0,0,0,0,0,"Ironwool Mammoth - On Reset - Set Speed Run 2.9"),
(-116910,0,0,0,25,0,100,0,0,0,0,0,208,0,2.9,0,0,0,0,1,0,0,0,0,0,0,0,"Ironwool Mammoth - On Reset - Set Speed Run 2.9"),
(-116911,0,0,0,25,0,100,0,0,0,0,0,208,0,2.9,0,0,0,0,1,0,0,0,0,0,0,0,"Ironwool Mammoth - On Reset - Set Speed Run 2.9"),
(-116907,0,0,0,25,0,100,0,0,0,0,0,208,0,2.9,0,0,0,0,1,0,0,0,0,0,0,0,"Ironwool Mammoth - On Reset - Set Speed Run 2.9"),
(-116908,0,0,0,25,0,100,0,0,0,0,0,208,0,2.9,0,0,0,0,1,0,0,0,0,0,0,0,"Ironwool Mammoth - On Reset - Set Speed Run 2.9");
```

**Comment by Rushor** [comment]
yep works fine:)

DB/Creature: Ironwool Mammoth - Update speedrate of pathing formation in stormpeaks 

* updates: https://github.com/dalaranwow/dalaran-wow/issues/4275
* commit: 0451db6d42a5b116d54b39501fad7f525a0122b1
