### ISSUE TITLE
[NPC][WotlK] Savage Hill Brute/Mystic/Scavenger, missing spawn loc and emote

### ISSUE THREAD

**Issue by Teridan-dal-wow** [dalaranwow/dalaran-wow#4283]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: There are some missing npc spawn locations of Savage Hill Brute http://wotlk.openwow.com/npc=29623 , Savage Hill Mystic http://wotlk.openwow.com/npc=29622 and Savage Hill Scavenger http://wotlk.openwow.com/npc=29404 and some of the npcs in these camps should be sleeping (check video for which exacly).
These screenshots are from the server with some of the missing emotes:
![wowscrnshot_012117_152911](https://cloud.githubusercontent.com/assets/6797611/22174957/98b8dbbc-dff3-11e6-9123-466eff7f5423.jpg)
![wowscrnshot_012117_152848](https://cloud.githubusercontent.com/assets/6797611/22174958/a3289d58-dff3-11e6-9c5e-3697ff63e6e6.jpg)
![wowscrnshot_012117_152725](https://cloud.githubusercontent.com/assets/6797611/22174959/a99536ce-dff3-11e6-87be-d0b155109701.jpg)

And this one is from the spot with the missing npcs:
![wowscrnshot_012117_152922](https://cloud.githubusercontent.com/assets/6797611/22174962/c2d9039a-dff3-11e6-89f2-ec58b51e9f3a.jpg)

**Expected behaviour**: Video from retail legion from 21.01.2017:
https://www.youtube.com/watch?v=wlzHDLHDMOo

Comment:
First i though that the sleep emote should be regain after mob reset instantly (which did not happen), then i waited 5 mins (again didnt happen), then i moved out of the area and back in to see the emote(sleep) was applied instantly after the server send me the updated state of the npc when moving back to the area. This does not seem right to me, maybe tweak it abit like:
-instantly gain the emotestate after npc reset
-add cd after npc resets (npc reset > 2 mins stays awake and then goes back to sleep)

Regarding the missing npcs:
-Brutes and Scavenger have random movement around their spawn location.
-Mystics are not moving at all.
Total missing npcs: 1 Brute, 2 Scavengers, 5 Mystics

**Comment by Rushor** [comment]
nice report, going to fix this now :)

**Comment by Rushor** [comment]
and yeah we will do this better than blizz. If the creature evades it will regain it's sleep emote directly

**Comment by Rushor** [comment]
DB/Creature: Savage Hill Brute/Mystic/Scavenger- Add missing spawn loc and emotes

* closes: https://github.com/dalaranwow/dalaran-wow/issues/4283
* commit: 95598b95dfb3ac8667640a85f53921e64358b5bc

![GitHub Logo](http://i.imgur.com/cPdjKZB.jpg)
![GitHub Logo](http://i.imgur.com/X0JtDrF.jpg)

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by Teridan-dal-wow** [comment]
Feedback for this report from TrinityCore rev. 02633a332cf7 2017-02-09.

Works exacly like on retail. Thank you for your work!

**Comment by Teridan-dal-wow** [comment]
Revisited all Savage Hill Brutes/Mystics/Scavengers and changed:
-set random movement radius to 5 to all of the savages that use it (some didn't had it)
-removed 1 wrong spawn
-added few missing spawns around K3
-added few paths
-added few missing gameobjects (Charred Wreckage) around K3
How it looks:
![image](https://cloud.githubusercontent.com/assets/6797611/23095774/39a34c08-f618-11e6-81de-e16f8fdf462b.png)
![image](https://cloud.githubusercontent.com/assets/6797611/23095777/46aca6d8-f618-11e6-8ad1-c659b1226d90.png)

``` sql
UPDATE `creature` SET `spawndist` = 5 WHERE `guid` IN (73938, 73939, 73945, 113309, 11770, 117088, 117083, 117089, 113328, 117091, 117094, 117090, 113319, 117092, 113318, 117082);
UPDATE `creature` SET `position_x` = 6102.8701 , `position_y` = -938.3048 , `position_z` = 389.905 , `MovementType` = 1 WHERE `guid` = 117090; 
UPDATE `creature` SET `position_x` = 6117.615 , `position_y` = -972.562 , `position_z` = 399.042 WHERE `guid` = 117094; 
UPDATE `creature` SET `position_x` = 6122.43 , `position_y` = -872.295 , `position_z` = 383.3940 , `MovementType` = 1 WHERE `guid` = 117092; 
UPDATE `creature` SET `MovementType` = 1 WHERE `guid` = 117083; 

SET @OGUID:= 4000084;
DELETE FROM `gameobject` WHERE `guid` BETWEEN @OGUID+0 AND @OGUID+4; 
INSERT INTO `gameobject` (`guid`, `id`, `map`, `zoneId`, `areaId`, `spawnMask`, `phaseMask`, `position_x`, `position_y`, `position_z`, `orientation`, `rotation0`, `rotation1`, `rotation2`, `rotation3`, `spawntimesecs`, `animprogress`, `state`, `VerifiedBuild`) VALUES 
(@OGUID+0, 191537, 571, 0, 0, 1, 1, 6001.688, -890.6218, 358.6693, 5.218536, 0, 0, -0.5075378, 0.8616294, 300, 100, 1, 23420), -- 191535 (Area: 4419)
(@OGUID+1, 191537, 571, 0, 0, 1, 1, 6047.78, -866.0516, 364.0948, 4.939284, 0, 0, -0.6225138, 0.7826088, 300, 100, 1, 23420), -- 191537 (Area: 4419)
(@OGUID+2, 191537, 571, 0, 0, 1, 1, 6107.474, -866.6121, 379.1167, 6.021387, 0, 0, -0.1305256, 0.9914449, 300, 100, 1, 23420), -- 191537 (Area: -1)
(@OGUID+3, 191531, 571, 0, 0, 1, 1, 6051.873, -910.7667, 374.5605, 3.019413, 0, 0, 0.9981346, 0.06105176, 300, 100, 1, 23420), -- 191531 (Area: -1)
(@OGUID+4, 191533, 571, 0, 0, 1, 1, 6129.224, -911.353, 386.6187, 0.9948372, 0, 0, 0.4771585, 0.8788173, 300, 100, 1, 23420); -- 191533 (Area: -1)
DELETE FROM `gameobject_addon` WHERE `guid` BETWEEN @OGUID+0 AND @OGUID+4;

DELETE FROM `creature` WHERE `guid` = 117082;
DELETE FROM `creature_addon` WHERE `guid` = 117082;

SET @CGUID := 5004970;
DELETE FROM `creature` WHERE `guid` BETWEEN @CGUID+0 AND @CGUID+5;
INSERT INTO `creature` (`guid`, `id`, `map`, `zoneId`, `areaId`, `spawnMask`, `phaseMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `VerifiedBuild`) VALUES
(@CGUID+0, 29404, 571, 0, 0, 1, 1, 0, 0, 5977.539, -874.7954, 345.9525, 2.646924, 300, 10, 0, 1, 0, 1, 0, 0, 0, 23420), -- 29404 (Area: 4419)
(@CGUID+1, 29404, 571, 0, 0, 1, 1, 0, 0, 6011.596, -838.8746, 353.5265, 4.378798, 300, 10, 0, 1, 0, 1, 0, 0, 0, 23420), -- 29404 (Area: 4419)
(@CGUID+2, 29404, 571, 0, 0, 1, 1, 0, 0, 6024.435, -897.7316, 365.8187, 5.316259, 300, 10, 0, 1, 0, 1, 0, 0, 0, 23420), -- 29404 (Area: 4419)
(@CGUID+3, 29404, 571, 0, 0, 1, 1, 0, 0, 6056.145, -874.5873, 367.8378, 5.114534, 300, 10, 0, 1, 0, 1, 0, 0, 0, 23420), -- 29404 (Area: 4419) (possible waypoints or random movement)
(@CGUID+4, 29404, 571, 0, 0, 1, 1, 0, 0, 6043.876,  -966.822,  400.565, 0.8177619, 300, 10, 0, 1, 0, 1, 0, 0, 0, 23420), -- 29404 (Area: 4419)
(@CGUID+5, 29623, 571, 0, 0, 1, 1, 0, 0, 6016.407, -1002.734, 423.3258, 0.3572843, 300, 10, 0, 1, 0, 1, 0, 0, 0, 23420); -- 29623 (Area: 4419)
DELETE FROM `creature_addon` WHERE `guid` BETWEEN @CGUID+0 AND @CGUID+5;
INSERT INTO `creature_addon` (`guid`, `path_id`, `mount`, `bytes1`, `bytes2`, `emote`, `auras`) VALUES
(@CGUID+0, 0, 0, 0, 1, 0, ''), -- 29404
(@CGUID+1, 0, 0, 0, 1, 0, ''), -- 29404
(@CGUID+2, 0, 0, 0, 1, 0, ''), -- 29404
(@CGUID+3, 0, 0, 0, 1, 0, ''), -- 29404
(@CGUID+4, 0, 0, 0, 1, 0, ''), -- 29404
(@CGUID+5, 0, 0, 0, 1, 0, ''); -- 29623


-- Pathing for Savage Hill Brute Entry: 29623 'TDB FORMAT' 
SET @NPC := 113326;
SET @PATH := @NPC * 10;
UPDATE `creature` SET `spawndist`=0,`MovementType`=2,`position_x`=6161.293,`position_y`=-422.618,`position_z`=415.5368 WHERE `guid`=@NPC;
DELETE FROM `creature_addon` WHERE `guid`=@NPC;
INSERT INTO `creature_addon` (`guid`,`path_id`,`mount`,`bytes1`,`bytes2`,`emote`,`auras`) VALUES (@NPC,@PATH,0,0,1,0, '');
DELETE FROM `waypoint_data` WHERE `id`=@PATH;
INSERT INTO `waypoint_data` (`id`,`point`,`position_x`,`position_y`,`position_z`,`orientation`,`delay`,`move_type`,`action`,`action_chance`,`wpguid`) VALUES
(@PATH,1,6161.293,-422.618,415.5368,0,0,0,0,100,0), -- 22:59:51
(@PATH,2,6180.214,-413.2049,415.7153,0,0,0,0,100,0), -- 22:59:57
(@PATH,3,6154.252,-433.754,414.5311,0,0,0,0,100,0); -- 23:00:13 
-- Pathing for Savage Hill Brute Entry: 29623 'TDB FORMAT' 
SET @NPC :=  113325;
SET @PATH := @NPC * 10;
UPDATE `creature` SET `spawndist`=0,`MovementType`=2,`position_x`=6103.771,`position_y`=-434.4144,`position_z`=414.2494 WHERE `guid`=@NPC;
DELETE FROM `creature_addon` WHERE `guid`=@NPC;
INSERT INTO `creature_addon` (`guid`,`path_id`,`mount`,`bytes1`,`bytes2`,`emote`,`auras`) VALUES (@NPC,@PATH,0,0,1,0, '');
DELETE FROM `waypoint_data` WHERE `id`=@PATH;
INSERT INTO `waypoint_data` (`id`,`point`,`position_x`,`position_y`,`position_z`,`orientation`,`delay`,`move_type`,`action`,`action_chance`,`wpguid`) VALUES
(@PATH,1,6103.771,-434.4144,414.2494,0,0,0,0,100,0), -- 22:59:50
(@PATH,2,6121.354,-444.062,411.8011,0,0,0,0,100,0), -- 22:59:55
(@PATH,3,6136.764,-445.9435,412.2024,0,0,0,0,100,0), -- 23:00:01
(@PATH,4,6127.846,-445.2137,411.5941,0,0,0,0,100,0), -- 23:00:13
(@PATH,5,6113.883,-440.4421,413.1418,0,0,0,0,100,0), -- 23:00:17
(@PATH,6,6097.099,-420.5607,418.1551,0,0,0,0,100,0); -- 23:00:23
-- Pathing for Savage Hill Brute Entry: 29623 'TDB FORMAT' 
SET @NPC := 113310;
SET @PATH := @NPC * 10;
UPDATE `creature` SET `spawndist`=0,`MovementType`=2,`position_x`=6240.377,`position_y`=-609.4531,`position_z`=418.8567 WHERE `guid`=@NPC;
DELETE FROM `creature_addon` WHERE `guid`=@NPC;
INSERT INTO `creature_addon` (`guid`,`path_id`,`mount`,`bytes1`,`bytes2`,`emote`,`auras`) VALUES (@NPC,@PATH,0,0,1,0, '');
DELETE FROM `waypoint_data` WHERE `id`=@PATH;
INSERT INTO `waypoint_data` (`id`,`point`,`position_x`,`position_y`,`position_z`,`orientation`,`delay`,`move_type`,`action`,`action_chance`,`wpguid`) VALUES
(@PATH,1,6240.377,-609.4531,418.8567,0,0,0,0,100,0), -- 23:15:45
(@PATH,2,6224.994,-612.3428,415.8263,0,0,0,0,100,0), -- 23:15:48
(@PATH,3,6235.434,-609.459,417.5555,0,0,0,0,100,0), -- 23:15:57
(@PATH,4,6248.069,-610.5052,419.8713,0,0,0,0,100,0); -- 23:16:02
-- Pathing for Savage Hill Brute Entry: 29623 'TDB FORMAT' 
SET @NPC := 113313;
SET @PATH := @NPC * 10;
UPDATE `creature` SET `spawndist`=0,`MovementType`=2,`position_x`=6227.61,`position_y`=-671.0212,`position_z`=415.3917 WHERE `guid`=@NPC;
DELETE FROM `creature_addon` WHERE `guid`=@NPC;
INSERT INTO `creature_addon` (`guid`,`path_id`,`mount`,`bytes1`,`bytes2`,`emote`,`auras`) VALUES (@NPC,@PATH,0,0,1,0, '');
DELETE FROM `waypoint_data` WHERE `id`=@PATH;
INSERT INTO `waypoint_data` (`id`,`point`,`position_x`,`position_y`,`position_z`,`orientation`,`delay`,`move_type`,`action`,`action_chance`,`wpguid`) VALUES
(@PATH,1,6227.61,-671.0212,415.3917,0,0,0,0,100,0), -- 23:15:54
(@PATH,2,6247.896,-678.7141,417.2262,0,0,0,0,100,0), -- 23:16:03
(@PATH,3,6267.256,-682.9299,418.9757,0,0,0,0,100,0), -- 23:16:11
(@PATH,4,6289.021,-682.3413,422.3364,0,0,0,0,100,0), -- 23:16:19
(@PATH,5,6275.357,-684.1752,419.9809,0,0,0,0,100,0), -- 23:16:26
(@PATH,6,6249.997,-679.3331,417.5082,0,0,0,0,100,0); -- 23:16:30
-- Pathing for Savage Hill Brute Entry: 29623 'TDB FORMAT' 
SET @NPC := 113312;
SET @PATH := @NPC * 10;
UPDATE `creature` SET `spawndist`=0,`MovementType`=2,`position_x`=6208.514,`position_y`=-630.8281,`position_z`=412.9504 WHERE `guid`=@NPC;
DELETE FROM `creature_addon` WHERE `guid`=@NPC;
INSERT INTO `creature_addon` (`guid`,`path_id`,`mount`,`bytes1`,`bytes2`,`emote`,`auras`) VALUES (@NPC,@PATH,0,0,1,0, '');
DELETE FROM `waypoint_data` WHERE `id`=@PATH;
INSERT INTO `waypoint_data` (`id`,`point`,`position_x`,`position_y`,`position_z`,`orientation`,`delay`,`move_type`,`action`,`action_chance`,`wpguid`) VALUES
(@PATH,1,6208.514,-630.8281,412.9504,0,0,0,0,100,0), -- 23:26:20
(@PATH,2,6206.603,-639.7648,412.171,0,0,0,0,100,0); -- 23:26:27
```

**Comment by Rushor** [comment]
DB/Creature: Stormpeaks - Savage Hill Brutes/Mystics/Scavengers - Add missing spawns, addons and paths

* closes: https://github.com/dalaranwow/dalaran-wow/issues/4283
* thanks to Teridan
* commit: eca4969847286833ce52200efe2ccb577cb96f04

**Comment by Rushor** [comment]
DB/Creature: Savage Hill Scavenger, Savage Hill Mystic and Savage Hill Brute - Remove SAI for Standstate check since Standstates/Bytes are removed generic on aggro of a creature now

* updates: https://github.com/dalaranwow/dalaran-wow/issues/4283
* commit: 3aecc878f1869c4e190c5209abfe52df6c8f43d2
