### ISSUE TITLE
[NPC][WotlK] Janks's mine event

### ISSUE THREAD

**Issue by Teridan-dal-wow** [dalaranwow/dalaran-wow#4284]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: 
- There is a minefield in Stormpeaks with npc Janks  http://wotlk.openwow.com/npc=29429 in the middle of it. He is missing his speach and emote.
- There are alive and moving Savage Hill Scavengers http://wotlk.openwow.com/npc=29404 around the field (they should be spawned dead and untargetable( by players)).
![wowscrnshot_012117_164327](https://cloud.githubusercontent.com/assets/6797611/22175189/cc9f7ee0-dff8-11e6-9077-bcd84217c3be.jpg)

- The mines around him also can be improved abit:
-their respawn timer should be 10 secs(check video below), currently its ~ 5mins
-their dmg seems to be half of retail's value(750-1000)(check the video below)
-when you get hit by a mine there is a strange report of it in the combat log (check screenshot)(check video for how it should be).
![wowscrnshot_012117_163326](https://cloud.githubusercontent.com/assets/6797611/22175149/1ef6c8f2-dff8-11e6-8e70-a9abbebf7a4a.jpg)

**Expected behaviour**: Video from retail legion from 21.01.2017:
https://www.youtube.com/watch?v=PG7_0oinTTc
Janks should be always sitting, once his event starts he stands and at the end of the event he sits back again. Event cd is 1 min.
The missing speach for Janks:
[17:00:54] Janks says: Is it true?! Has someone finally come to get me out of this place?
[17:00:58] Janks says: No... no... that's not it, is it? That heartless lout probably sent you after the tools, didn't he?
[17:01:03] Janks says: Well... I guess I'll just keep an eye on the turrets... or something.
[17:01:08] Janks sighs.

**Comment by Rushor** [comment]
DB/Creature: Add Minievent for Janks and emotes for Savage Hill Scavengers

* closes: https://github.com/dalaranwow/dalaran-wow/issues/4284
* update the respawntime for landmines to 10 seconds
* remove wrong combatlog message
* commit: 383a0666b8a9d738aa880f8f1d2e9c7dc9559b79

![GitHub Logo](http://i.imgur.com/Ws4XcYN.jpg)

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by Teridan-dal-wow** [comment]
Feedback for this report from TrinityCore rev. 02633a332cf7 2017-02-09.

 - Found a small issue with Janks - he facing slightly in the wrong direction (check video 0.36s).

Everything else works exacly like on retail. Thank you for your work!

**Comment by Teridan-dal-wow** [comment]
> Found a small issue with Janks - he facing slightly in the wrong direction (check video 0.36s).

fix:

``` sql
UPDATE `creature` SET `position_x` = 6037.139 , `position_y` = -652.1522 , `position_z` = 369.8987 , `orientation` = 4.536977 WHERE `guid` = 118868; 
```

**Comment by Rushor** [comment]
DB/Creature: Update position of Janks

* updates: https://github.com/dalaranwow/dalaran-wow/issues/4284
* commit: 426f4c676d891b7bdc2e07bc0d95594ca6c2d96b

**Comment by Teridan-dal-wow** [comment]
Found a small issue with janks's script. On retail when someone goes near him and trigger his speech this happens:
-player triggers the speech
-janks stands up
-janks faces the player that triggered the speech
-janks says first text..... and so on
On the server the -3rd element is missing, if it can't be added a workaround is:
``` sql
UPDATE `creature` SET `orientation` = 5.000360 WHERE `guid` = 118868; 
```
so he faces the way to the maze (even though the correct orientation is the one from the sniff in 3-rd comment).

**Comment by Rushor** [comment]
it can be fixed with:

```sql
-- Janks SAI
SET @ENTRY := 29429;
UPDATE `creature_template` SET `AIName`="SmartAI" WHERE `entry`=@ENTRY;
DELETE FROM `smart_scripts` WHERE `entryorguid`=@ENTRY AND `source_type`=0;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(@ENTRY,0,0,0,25,0,100,0,0,0,0,0,90,1,0,0,0,0,0,1,0,0,0,0,0,0,0,"Janks - On Reset - Set Flag Standstate Sit Down"),
(@ENTRY,0,1,2,10,0,100,0,1,10,55000,55000,80,@ENTRY*100+00,0,0,0,0,0,1,0,0,0,0,0,0,0,"Janks - Within 1-10 Range Out of Combat LoS - Run Script"),
(@ENTRY,0,2,0,61,0,100,0,1,10,55000,55000,64,1,0,0,0,0,0,21,50,0,0,0,0,0,0,"Janks - Within 1-10 Range Out of Combat LoS - Store Targetlist");

-- Actionlist SAI
SET @ENTRY := 2942900;
DELETE FROM `smart_scripts` WHERE `entryorguid`=@ENTRY AND `source_type`=9;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(@ENTRY,9,0,0,0,0,100,0,0,0,0,0,48,1,0,0,0,0,0,1,0,0,0,0,0,0,0,"Janks - On Script - Set Active On"),
(@ENTRY,9,1,0,0,0,100,0,0,0,0,0,91,1,0,0,0,0,0,1,0,0,0,0,0,0,0,"Janks - On Script - Remove Flag Standstate Sit Down"),
(@ENTRY,9,2,0,0,0,100,0,1000,1000,0,0,66,0,0,0,0,0,0,12,1,0,0,0,0,0,0,"Janks - On Script - Set Orientation Stored Target"),
(@ENTRY,9,3,0,0,0,100,0,0,0,0,0,1,0,5000,0,0,0,0,1,0,0,0,0,0,0,0,"Janks - On Script - Say Line 0"),
(@ENTRY,9,4,0,0,0,100,0,5000,5000,0,0,1,1,5000,0,0,0,0,1,0,0,0,0,0,0,0,"Janks - On Script - Say Line 1"),
(@ENTRY,9,5,0,0,0,100,0,5000,5000,0,0,1,2,5000,0,0,0,0,1,0,0,0,0,0,0,0,"Janks - On Script - Say Line 2"),
(@ENTRY,9,6,0,0,0,100,0,5000,5000,0,0,1,3,5000,0,0,0,0,1,0,0,0,0,0,0,0,"Janks - On Script - Say Line 3"),
(@ENTRY,9,7,0,0,0,100,0,3000,3000,0,0,90,1,0,0,0,0,0,1,0,0,0,0,0,0,0,"Janks - On Script - Set Flag Standstate Sit Down"),
(@ENTRY,9,8,0,0,0,100,0,1000,1000,0,0,66,0,0,0,0,0,0,8,0,0,0,0,0,0,4.5369,"Janks - On Script - Set Orientation 4,5369"),
(@ENTRY,9,9,0,0,0,100,0,0,0,0,0,48,0,0,0,0,0,0,1,0,0,0,0,0,0,0,"Janks - On Script - Set Active Off");
```

**Comment by Rushor** [comment]
DB/Creature: Stormpeaks - Janks - Add orientationchange to invoker on start of OOC Event

* updates: https://github.com/dalaranwow/dalaran-wow/issues/4284
* commit: a7c71a65a86ac2d2c81c9449dff5ea13d4377129
