### ISSUE TITLE
[NPC][WotlK] Icetip Crawler, missing wps

### ISSUE THREAD

**Issue by Teridan-dal-wow** [dalaranwow/dalaran-wow#4293]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Npc Icetip Crawler http://wotlk.openwow.com/npc=29461 has a path which is missing and respawn timer is incorect.

![wowscrnshot_012317_115603](https://cloud.githubusercontent.com/assets/6797611/22199383/5b83e7f2-e163-11e6-936f-8f6b182aa60c.jpg)

**Expected behaviour**: Video from retail legion from 23.01.2017:

https://www.youtube.com/watch?v=x7akyYBuM68

 - Respawn timer should be 30 secs (currently its ~ 5 mins). Tested on retail with 1 person in the cave( no bonus spawns).
Proof: https://www.youtube.com/watch?v=8wy2158NOzc
Related to #487

**Comment by Rushor** [comment]
oh there are even more paths :) with the sniff we can see all the waypoints and convert them very easiliy. ty!

**Comment by Teridan-dal-wow** [comment]
Updated first post, appologies, should of searched first.

**Comment by Rushor** [comment]
DB/Creature: Storm Peaks - Add Pathing for Icetip Crawler and Crystalweb Spitter + Reduce respawntime of Icetip Crawler 

* closes: https://github.com/dalaranwow/dalaran-wow/issues/4293
* commit: 8f85e870a1e4766a0810e319555703111ad05039
* minimum respawntimer is 1 minute, i had to add that instead

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by Teridan-dal-wow** [comment]
Dam, you weren't kidding when you said there are even more paths :)
:+1:

**Comment by Teridan-dal-wow** [comment]
Feedback for this report from TrinityCore rev. 02633a332cf7 2017-02-09.

 - Found an issue here - there are 3 Icetip Crawler at the end of the cave, however only 2 of the have paths, while the 3-rd one is just standing (i do believe i sniffed all 3 of them, if not i can do it again just let me know).

![image](https://cloud.githubusercontent.com/assets/6797611/22837190/2621d6f0-efc8-11e6-9588-049a7a82eb2f.png)

Everything else works great. Thank you!

**Comment by Teridan-dal-wow** [comment]
Path for the spider on the left:
``` sql
-- Pathing for Icetip Crawler Entry: 29461 'TDB FORMAT' 
SET @NPC := 98067;
SET @PATH := @NPC * 10;
UPDATE `creature` SET `spawndist`=0,`MovementType`=2,`position_x`=6848.937,`position_y`=-1556.673,`position_z`=355.3038 WHERE `guid`=@NPC;
DELETE FROM `creature_addon` WHERE `guid`=@NPC;
INSERT INTO `creature_addon` (`guid`,`path_id`,`mount`,`bytes1`,`bytes2`,`emote`,`auras`) VALUES (@NPC,@PATH,0,0,1,0, '');
DELETE FROM `waypoint_data` WHERE `id`=@PATH;
INSERT INTO `waypoint_data` (`id`,`point`,`position_x`,`position_y`,`position_z`,`orientation`,`delay`,`move_type`,`action`,`action_chance`,`wpguid`) VALUES
(@PATH,1,6848.937,-1556.673,355.3038,0,0,0,0,100,0), -- 11:52:28
(@PATH,2,6862.551,-1579.194,353.2139,0,0,0,0,100,0), -- 11:52:31
(@PATH,3,6859.242,-1558.487,356.1682,0,0,0,0,100,0), -- 11:52:35
(@PATH,4,6837.857,-1543.034,354.8413,0,0,0,0,100,0), -- 11:52:38
(@PATH,5,6862.619,-1534.586,355.0396,0,0,0,0,100,0), -- 11:52:41
(@PATH,6,6861.767,-1522.72,356.2763,0,0,0,0,100,0), -- 11:52:45
(@PATH,7,6892.106,-1531.099,357.7832,0,0,0,0,100,0), -- 11:52:46
(@PATH,8,6895.456,-1527.811,357.995,0,0,0,0,100,0), -- 11:52:49
(@PATH,9,6879.614,-1540.735,356.9181,0,0,0,0,100,0), -- 11:52:51
(@PATH,10,6844.354,-1551.556,354.872,0,0,0,0,100,0), -- 11:52:59
(@PATH,11,6850.502,-1569.829,354.1755,0,0,0,0,100,0), -- 11:53:02
(@PATH,12,6869.496,-1581.584,352.1438,0,0,0,0,100,0), -- 11:53:04
(@PATH,13,6844.835,-1557.409,354.9437,0,0,0,0,100,0), -- 11:53:11
(@PATH,14,6843.8,-1533.681,354.5943,0,0,0,0,100,0), -- 11:53:14
(@PATH,15,6871.786,-1546.35,356.2852,0,0,0,0,100,0), -- 11:53:16
(@PATH,16,6893.968,-1524.249,358.1816,0,0,0,0,100,0), -- 11:53:21
(@PATH,17,6862.103,-1522.481,356.4301,0,0,0,0,100,0), -- 11:53:26
(@PATH,18,6863.676,-1529.807,355.7071,0,0,0,0,100,0), -- 11:53:31
(@PATH,19,6836.955,-1541.844,354.6504,0,0,0,0,100,0), -- 11:53:32
(@PATH,20,6858.183,-1555.743,355.8944,0,0,0,0,100,0), -- 11:53:35
(@PATH,21,6862.919,-1578.824,353.3674,0,0,0,0,100,0), -- 11:53:38
(@PATH,22,6850.38,-1567.292,355.092,0,0,0,0,100,0), -- 11:53:42
(@PATH,23,6852.746,-1531.732,355.5432,0,0,0,0,100,0), -- 11:53:45
(@PATH,24,6877.852,-1528.467,356.5175,0,0,0,0,100,0), -- 11:53:49
(@PATH,25,6855.149,-1525.095,356.092,0,0,0,0,100,0); -- 11:53:53
```

**Comment by Rushor** [comment]
DB/Creature: Stormpeaks - Icetip Crawler - Add one missing path

* updates: https://github.com/dalaranwow/dalaran-wow/issues/4293
* commit: f635e3a281634d831b67f22f1bd2ab9a24d3b3c3

**Comment by Teridan-dal-wow** [comment]
I made a mistake here, the spider should be running, updated the post above with `move_type=1`

**Comment by Rushor** [comment]
DB/Creature: Stormpeaks - Icetip Crawler - Add run mode

* updates: https://github.com/dalaranwow/dalaran-wow/issues/4293
* commit: 3278981336031bab9ef80fe10896ddc8a0021043

```sql
UPDATE `waypoint_data` SET `move_type`=1 WHERE `id`=@PATH;
```
