### ISSUE TITLE
[NPC][WotlK] Brunnhildar Challenger, missing emote

### ISSUE THREAD

**Issue by Teridan-dal-wow** [dalaranwow/dalaran-wow#4306]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Npc Brunnhildar Challenger http://wotlk.openwow.com/npc=29366 is missing an emote, there are just standing still:
![wowscrnshot_012417_140130](https://cloud.githubusercontent.com/assets/6797611/22246430/a703e116-e23d-11e6-8d8f-37634c723688.jpg)

**Expected behaviour**: They are suppose to be sparring in pairs of 2.
Video from retail legion from 24.01.2017:
https://www.youtube.com/watch?v=JmXDA08AzmA

**Comment by Rushor** [comment]
thanks! i added it together in https://github.com/dalaranwow/dalaran-wow/issues/2414 (need to be tested on PTR.

**Comment by Teridan-dal-wow** [comment]
@Rushor 
Thanks for the link, forgot to search again :/
Could you clarify what do you mean by:

> DB/Creature: Victorious Challenger & Brunnhildar Challenger - should be friendly by default

Because this is true only if the player has taken the quest The Crone's Bargain
 http://wotlk.openwow.com/quest=12841 and has the costume http://wotlk.openwow.com/spell=55012.
If that is not the case then setting them to friendly by default is not correct and you see that the only friendly target in the entire village are the proto drakes. 
Proof: video above
Thanks!

**Comment by Rushor** [comment]
oh alright then the report from the user in https://github.com/dalaranwow/dalaran-wow/issues/2414 was simply wrong

**Comment by Rushor** [comment]
alright updated the script again https://github.com/dalaranwow/dalaran-wow/issues/2414#issuecomment-260727598 thank you!

**Comment by TeridanDW** [comment]
What is reported here is working on ptr.
