### ISSUE TITLE
[NPC][WotlK] Brunnhildar Riding Bear and Brunnhildar Bearhandler

### ISSUE THREAD

**Issue by Teridan-dal-wow** [dalaranwow/dalaran-wow#4307]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: 
 - Part 1: There is 1 missing spawn of Brunnhildar Riding Bear http://wotlk.openwow.com/npc=29549 here:
![wowscrnshot_012417_142239](https://cloud.githubusercontent.com/assets/6797611/22247114/cae06d68-e240-11e6-8087-5fa504d3a8d0.jpg)

 - Part 2: Npc Brunnhildar Bearhandler http://wotlk.openwow.com/npc=29551 should have a leash at the 2 Brunnhildar Riding Bear next to him, but they don't.

**Expected behaviour**: Video from retail legion from 24.01.2017:
https://www.youtube.com/watch?v=K99syTRJWMM

**Comment by Teridan-dal-wow** [comment]
How does this effect looks like when you engage 1 of them?
 - The 2 bears and the handler and linked as group (if you pull one all 3 of them will engage you)
 - The leash visual persists throughout the combat

![wowscrnshot_012417_143700](https://cloud.githubusercontent.com/assets/6797611/22247556/1818b624-e243-11e6-8839-b92ac09a8659.jpg)

**Comment by Rushor** [comment]
hm there is currently a core issue, all spells with SPELL_ATTR1_CHANNELED_2 make the unit stop moving. i will push the fix anyways, the generic fix for the movement must be fixed from an other developer

**Comment by Rushor** [comment]
DB/Creature: Brunnhildar Riding Bear and Brunnhildar Bearhandler

* add formations: Brunnhildar Riding Bear and Brunnhildar Bearhandler should attack together
* add Chain spells for Brunnhildar Riding Bear
* spawn one missing Brunnhildar Riding Bear 
* closes: https://github.com/dalaranwow/dalaran-wow/issues/4307
* commit: 10b06c3b0efb68d9b8c4d81b349fbd1c7cd3c32b

![GitHub Logo](http://i.imgur.com/NBcihqu.jpg)

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by Rushor** [comment]
changed SAI script 

```sql
-- Brunnhildar Riding Bear (29549)
UPDATE creature_template SET AIName='SmartAI', ScriptName='' WHERE entry=29549;
DELETE FROM smart_scripts WHERE entryorguid IN(29549, -105872, -105871, -105870, -105869) AND source_type=0;
INSERT INTO smart_scripts VALUES (-105872, 0, 0, 1, 1, 0, 100, 1, 5000, 5000, 0, 0, 18, 16777216, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 'Brunnhildar Riding Bear - Out of Combat - Add Unit Flag');
INSERT INTO smart_scripts VALUES (-105872, 0, 1, 0, 61, 0, 100, 0, 0, 5000, 0, 0, 11, 46674, 2, 0, 0, 0, 0, 10, 106192, 29551, 1, 0, 0, 0, 0, 'Brunnhildar Riding Bear - Out of Combat - Cast Rope Beam Right');
INSERT INTO smart_scripts VALUES (-105872, 0, 2, 0, 4, 0, 100, 0, 0, 0, 0, 0, 19, 16777216, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 'Brunnhildar Riding Bear - On Aggro - Remove Unit Flag');
INSERT INTO smart_scripts VALUES (-105871, 0, 0, 0, 1, 0, 100, 1, 5000, 5000, 0, 0, 11, 66206, 2, 0, 0, 0, 0, 10, 106192, 29551, 1, 0, 0, 0, 0, 'Brunnhildar Riding Bear - Out of Combat - Cast Rope Beam Left');
INSERT INTO smart_scripts VALUES (-105870, 0, 0, 1, 1, 0, 100, 1, 5000, 5000, 0, 0, 18, 16777216, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 'Brunnhildar Riding Bear - Out of Combat - Add Unit Flag');
INSERT INTO smart_scripts VALUES (-105870, 0, 1, 0, 61, 0, 100, 0, 0, 5000, 0, 0, 11, 46674, 2, 0, 0, 0, 0, 10, 106191, 29551, 1, 0, 0, 0, 0, 'Brunnhildar Riding Bear - Out of Combat - Cast Rope Beam Right');
INSERT INTO smart_scripts VALUES (-105870, 0, 2, 0, 4, 0, 100, 0, 0, 0, 0, 0, 19, 16777216, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 'Brunnhildar Riding Bear - On Aggro - Remove Unit Flag');
INSERT INTO smart_scripts VALUES (-105869, 0, 0, 0, 1, 0, 100, 1, 5000, 5000, 0, 0, 11, 66206, 2, 0, 0, 0, 0, 10, 106191, 29551, 1, 0, 0, 0, 0, 'Brunnhildar Riding Bear - Out of Combat - Cast Rope Beam Left');
```
