### ISSUE TITLE
[NPC][WotlK] Kirgaraak, wrong spawn loc, reset condition

### ISSUE THREAD

**Issue by Teridan-dal-wow** [dalaranwow/dalaran-wow#4308]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Npc Kirgaraak http://wotlk.openwow.com/npc=29352 
 - Is spawned at the wrong spot, needs to be moved slightly, currently he is here:
![wowscrnshot_012417_154625](https://cloud.githubusercontent.com/assets/6797611/22249602/533a84fe-e24c-11e6-9a46-f2d41dc7f050.jpg)

But he should be here:
![wowscrnshot_012417_154632](https://cloud.githubusercontent.com/assets/6797611/22249613/64451926-e24c-11e6-98e8-fd3a7ab1be42.jpg)

 - Kirgaraak has a special reset condition - as you can see on both screenshots he is chained, that means he cant run very far away from his spawn location. Currently on the server he can be pull very far away without reset:
![wowscrnshot_012417_151519](https://cloud.githubusercontent.com/assets/6797611/22249712/c038ddda-e24c-11e6-93e1-10b435cf19b5.jpg)

Reset range seems to be ~ 50 yards

 - Also, you can see on the video below, Kirgaraak does not lose "his chains" when pulled at max range.

**Expected behaviour**: Kirgaraak has a very short leash range, if a player tries to grip/pull/pushback out of his maximum leash-range he will reset. Video from retail legion from 24.01.2017:
https://www.youtube.com/watch?v=NA5urdbxQ9Q

**Comment by Rushor** [comment]
alright we will need to overwrite his updateai to make him reset after a specific distance, will do this this evening :)

**Comment by Rushor** [comment]
Game/SmartScripts: Implement SMART_ACTION_CHECK_HOME_DIST for Kirgaraak

* This check let the creature reset/evade if it move x yards away from his homeposition
* also change the spawnplace for Kirgaraak
* Kirgaraak will now evade after 61 yards distance to his spawnplace (value from video)
* closes: https://github.com/dalaranwow/dalaran-wow/issues/4308
* commit: f81f200c2be19eccfbc8b4dca7b12d7ae062e24b

![GitHub Logo](http://i.imgur.com/1lFlFke.jpg)

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by Teridan-dal-wow** [comment]
This fix is not added to Trinitycore, so i cant give any feedback :(

**Comment by Rushor** [comment]
yes not all fixes will be pushed to tc, some are closed source only and will be reviewed by the testers from dalaran-wow :)

**Comment by Teridan-dal-wow** [comment]
I see, then i will skip the reports that are not TC.

**Comment by TeridanDW** [comment]
Small correction to this creature's SAI, he should never die. He can be dropped to 1 hp but not less.
Proof: https://www.youtube.com/watch?v=bLyEsHZ-fSs

``` sql
-- Kirgaraak SAI
SET @ENTRY := 29352;
UPDATE `creature_template` SET `AIName`="SmartAI" WHERE `entry`=@ENTRY;
DELETE FROM `smart_scripts` WHERE `entryorguid`=@ENTRY AND `source_type`=0;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(@ENTRY,0,0,0,2,0,100,512,0,5,0,0,80,@ENTRY*100+00,2,0,0,0,0,1,0,0,0,0,0,0,0,"Kirgaraak - Between 0-5% Health - Run Script"),
(@ENTRY,0,1,0,25,0,100,512,0,0,0,0,45,1,1,0,0,0,0,11,24921,200,0,0,0,0,0,"Kirgaraak - On Respawn - Set Data Cosmetic Trigger"),
(@ENTRY,0,2,0,25,0,100,0,0,0,0,0,42,0,5,0,0,0,0,1,0,0,0,0,0,0,0,"Kirgaraak - On Reset - Reset Invincibility Hp");

-- Actionlist SAI
SET @ENTRY := 2935200;
DELETE FROM `smart_scripts` WHERE `entryorguid`=@ENTRY AND `source_type`=9;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(@ENTRY,9,0,0,0,0,100,0,0,0,0,0,33,30221,0,0,0,0,0,24,0,0,0,0,0,0,0,"Kirgaraak - On Script - Quest Credit 'The Warm-Up '"),
(@ENTRY,9,1,0,0,0,100,0,0,0,0,0,102,0,0,0,0,0,0,1,0,0,0,0,0,0,0,"Kirgaraak - On Script - Set Health Regeneration Off"),
(@ENTRY,9,2,0,0,0,100,0,0,0,0,0,27,0,0,0,0,0,0,1,0,0,0,0,0,0,0,"Kirgaraak - On Script - Combat Stop"),
(@ENTRY,9,3,0,0,0,100,0,0,0,0,0,2,35,0,0,0,0,0,1,0,0,0,0,0,0,0,"Kirgaraak - On Script - Set Faction 35"),
(@ENTRY,9,4,0,0,0,100,0,5000,5000,0,0,24,0,0,0,0,0,0,1,0,0,0,0,0,0,0,"Kirgaraak - On Script - Evade"),
(@ENTRY,9,5,0,0,0,100,0,10000,10000,0,0,2,0,0,0,0,0,0,1,0,0,0,0,0,0,0,"Kirgaraak - On Script - Set Faction 0");
```
How it looks now:
![image](https://cloud.githubusercontent.com/assets/6797611/24323168/84ea9144-117a-11e7-9198-740c6ec4e915.png)

**Comment by Rushor** [comment]
DB/Creature: Kirgaraak - Add Invincibility Hp on end of the fight

* readd Invincibility Hp on reset + improve related evade script
* updates: https://github.com/dalaranwow/dalaran-wow/issues/4308
* commit: 448f2b721a001cc551d4c7435b5b490e109ffccb

Thanks!
