### ISSUE TITLE
[NPC][WotlK] Stormpeak Wyrm and Stormpeak Hatchling, missing spawn loc/paths

### ISSUE THREAD

**Issue by Teridan-dal-wow** [dalaranwow/dalaran-wow#4312]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Npc Stormpeak Wyrm http://wotlk.openwow.com/npc=29753 and Stormpeak Hatchling http://wotlk.openwow.com/npc=29755 have some of their spawn locations and paths missing. Area relevent for this report:
![wowscrnshot_012517_092828](https://cloud.githubusercontent.com/assets/6797611/22281662/d9bded9c-e2e0-11e6-99b2-f7ba42865e17.jpg)

**Expected behaviour**: Video from retail legion from 25.01.2017:
Part 1 - https://www.youtube.com/watch?v=b2yY8vVGPQg
Part 2 - https://www.youtube.com/watch?v=7xduEDpbCpw

Note: The Stormpeak Hatchling that are spawned on the server here:
![wowscrnshot_012517_094955](https://cloud.githubusercontent.com/assets/6797611/22282213/b09c343e-e2e3-11e6-9c21-1c5f28f27a51.jpg)

 are missing the "sleep" emote every 60 secs (check part 2 video).

**Comment by Rushor** [comment]
wow there is not a single spawn in that area currently :O the fix for this will be a huge change!

**Comment by Rushor** [comment]
so every Stormpeak Hatchling should have the randommovement, but they fall asleep every 60 seconds right?

**Comment by Teridan-dal-wow** [comment]
Correct and they are not sync-ed.

**Comment by Rushor** [comment]
DB/Creature: Stomr Peaks - Stormpeak Wyrm and Stormpeak Hatchling Addmissing spawn loc/paths and emotes

* closes https://github.com/dalaranwow/dalaran-wow/issues/4312
* commit: 637e51d3fe144954243f2f7f2676a55fc34985d0
* commit: c6a25913a7bca8a7d11b9700612a341b21436904

![GitHub Logo](http://i.imgur.com/4B0wVmg.png)
![GitHub Logo](http://i.imgur.com/bIl1s10.jpg)

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by Teridan-dal-wow** [comment]
Feedback for this report from TrinityCore rev. 02633a332cf7 2017-02-09.
Found few issues here:
 - There are 2 Stormpeak Wyrms that are missing an emote "sit" here:
![wowscrnshot_021017_205330](https://cloud.githubusercontent.com/assets/6797611/22840248/6124f3d8-efd5-11e6-8a1b-e7fb4b208241.jpg)
![wowscrnshot_021017_205325](https://cloud.githubusercontent.com/assets/6797611/22840247/6121c758-efd5-11e6-8c1f-15ec7e87d26b.jpg)

 - There are 3 Stormpeak Hatchling that has really strange random movement and they go under the nest here:
![wowscrnshot_021017_205315](https://cloud.githubusercontent.com/assets/6797611/22840284/8f0f4f28-efd5-11e6-9e58-f19f5bd1bb4d.jpg)
![wowscrnshot_021017_205248](https://cloud.githubusercontent.com/assets/6797611/22840285/8f102b64-efd5-11e6-920e-480f2fb895fb.jpg)

 - The random movement radius of Stormpeak Hatchling on retail seems to be abit smaller than what we have on the server (really hard to notice) and the hatchlings are walking on retail, but on the server they are running (i mean when out of combat while they are randomly moving around).

Everything else works exacly like on retail. Thanks for your work!

**Comment by Rushor** [comment]
k i will remove the rndmmovement for the onces that are really close to the edge (that makes them fall trough the nest) + add the sit emote

**Comment by Rushor** [comment]
DB/Creature: Storm Peaks - Stormpeak Wyrm and Stormpeak Hatchling - Reduce randommovement radius + Add sit emote for two Stormpeak Wyrm 

* updates: https://github.com/dalaranwow/dalaran-wow/issues/4312
* commit: d600fbd8b85a8c5c1752b8f6d1c1e1c1ad1cabe4
