### ISSUE TITLE
[NPC][WotlK] Stormforged Iron Giant, missing paths, emote, 1 spawn locs, mini event

### ISSUE THREAD

**Issue by Teridan-dal-wow** [dalaranwow/dalaran-wow#4315]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: 
Part 1: 
 - Npc Stormforged Iron Giant http://wotlk.openwow.com/npc=29375 has a missing path, currently he is just standing still (check part 1 video):
![wowscrnshot_012517_110401](https://cloud.githubusercontent.com/assets/6797611/22284063/22e37ebc-e2ee-11e6-9bd5-766ca8e0119a.jpg)

Part 2:
 - There is 1 missing spawn locations for Stormforged Iron Giant
![wowscrnshot_012517_114703](https://cloud.githubusercontent.com/assets/6797611/22285399/3479e5d4-e2f4-11e6-8914-0e29a5c19c03.jpg)

 - These 3 Giants should have a "roar" emote (chech begining of part 2 video).
 - Npc Fjorn http://wotlk.openwow.com/npc=29503 has a small event (he is move away from the forge some few seconds and going back, which is working on the server) that is also missing the "roar" emote at the end of it (check end of part 2 video).

Part 3:
 - There is a mini event that Fjorn http://wotlk.openwow.com/npc=29503 sends 1 Stormforged Iron Giant from the forge towards Dun Niffelem (check part 3 video).
 - CD of this event 5-8 minutes.

**Expected behaviour**: Video from retail legion from 25.01.2017:
Part 1- https://www.youtube.com/watch?v=UTtb4F4U8mw
Part 2- https://www.youtube.com/watch?v=PKzld3lVpA0
Part 3- https://www.youtube.com/watch?v=sWrnE-74R0I

P.S. For part 1 of this report, I am not really sure if these npcs use wps or its just a random movement generator, if its the second one, just ignore that part of the report. Thanks.

**Comment by Rushor** [comment]
yep (Part 1:) thats randommovement. actually like 99% of creatures that stop their movement for 2-3 seconds have randommovement, but in this case the radius for the rndmmovement is increased

**Comment by Rushor** [comment]
path for the eventspawn

```sql
-- Pathing for  Entry: Entry: 'TDB FORMAT' 
SET @NPC := XXXXXX;
SET @PATH := @NPC * 10;
UPDATE `creature` SET `spawndist`=0,`MovementType`=2,`position_x`=7199.968,`position_y`=-3600.629,`position_z`=827.002 WHERE `guid`=@NPC;
DELETE FROM `creature_addon` WHERE `guid`=@NPC;
INSERT INTO `creature_addon` (`guid`,`path_id`,`mount`,`bytes1`,`bytes2`,`emote`,`auras`) VALUES (@NPC,@PATH,0,0,1,0, '');
DELETE FROM `waypoint_data` WHERE `id`=@PATH;
INSERT INTO `waypoint_data` (`id`,`point`,`position_x`,`position_y`,`position_z`,`orientation`,`delay`,`move_type`,`action`,`action_chance`,`wpguid`) VALUES
(@PATH,1,7199.968,-3600.629,827.002,0,0,0,0,100,0), -- 10:38:27
(@PATH,2,7189.104,-3563.368,827.3765,0,0,0,0,100,0), -- 10:38:31
(@PATH,3,7188.668,-3539.213,827.3962,0,0,0,0,100,0), -- 10:38:38
(@PATH,4,7195.016,-3509.103,828.8126,0,0,0,0,100,0), -- 10:38:43
(@PATH,5,7214.329,-3441.1,837.9941,0,0,0,0,100,0), -- 10:38:53
(@PATH,6,7208.163,-3399.303,842.7413,0,0,0,0,100,0), -- 10:39:01
(@PATH,7,7204.88,-3331.804,843.1924,0,0,0,0,100,0), -- 10:39:06
(@PATH,8,7207.137,-3299.045,837.8273,0,0,0,0,100,0), -- 10:39:16
(@PATH,9,7231.24,-3264.245,837.8268,0,0,0,0,100,0), -- 10:39:22
(@PATH,10,7253.341,-3234.825,837.8268,0,0,0,0,100,0), -- 10:39:27
(@PATH,11,7269.063,-3209.878,837.8268,0,0,0,0,100,0), -- 10:39:31
(@PATH,12,7296.788,-3181.641,837.8268,0,0,0,0,100,0), -- 10:39:36
(@PATH,13,7337.208,-3163.068,837.8268,0,0,0,0,100,0), -- 10:39:44
(@PATH,14,7364.17,-3148.588,837.8268,0,0,0,0,100,0), -- 10:39:47
(@PATH,15,7395.288,-3140.528,837.8268,0,0,0,0,100,0), -- 10:39:52
(@PATH,16,7421.594,-3121.072,837.8268,0,0,0,0,100,0); -- 10:39:57
-- 0x20197C47601CAFC00000360000087213 .go 7199.968 -3600.629 827.002
```

i would script it like that:

spawn the npc, let him move the path (no tempspawn)

the time he needs to walk to it's destiny is 1:50 minutes, so add him a 5 minute respawntimer

i will do it this evening :)

**Comment by Rushor** [comment]
hm i need to respawn all entries of them, everything is wrong in this zone currently xd

**Comment by Rushor** [comment]
DB/Creature: Stormforged Iron Giant - Misc updates

* set Stormforged Iron Giant active (increased sight distance)
* increase rndmmovement for Stormforged Iron Giant to 26 yards
* spawn two missing Stormforged Iron Giant (one static spawn, one eventspawn with waypoints)
* add roar emotescript for Stormforged Iron Giant every 13 - 16 seconds
* add wps for eventspawn of Stormforged Iron Giant
* closes: https://github.com/dalaranwow/dalaran-wow/issues/4315
* commit: 23f9ae98cc7697b7fbd421006d1c35d9ef6101f3

![](https://i.gyazo.com/644665cc40c0c351132f256ee6f1db41.gif)

![GitHub Logo](http://i.imgur.com/tgVcVJQ.jpg)

- the tiny giants are trigger to show his wps (they won't be visiable ingame later) :)

**Comment by Teridan-dal-wow** [comment]
Feedback for this report from TrinityCore rev. 02633a332cf7 2017-02-09.

 - Small issue - Regarding the mini event - The giant seems to despawn before he reaches his final destination here:
![wowscrnshot_021017_211832](https://cloud.githubusercontent.com/assets/6797611/22840647/158ae6e2-efd7-11e6-981b-426a241e4251.jpg)

Everything else works exacly like on retail. Thank you for your work!

**Comment by Rushor** [comment]
hm then that wp was not sended to the client, i will update it manually

**Comment by Rushor** [comment]
DB/Creature: Stormforged Iron Giant -Add missing waypoint for movement event 

* updates: https://github.com/dalaranwow/dalaran-wow/issues/4315
* commit: 7e6d9d1c04c24a6ae32b112ccd72915ff94be8a7
