### ISSUE TITLE
[NPC][WotlK] Romping Rhino, missing paths

### ISSUE THREAD

**Issue by Teridan-dal-wow** [dalaranwow/dalaran-wow#4317]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Npc Romping Rhino http://wotlk.openwow.com/npc=30447 has all of its paths missing, currently its just standing still.
![wowscrnshot_012517_125911](https://cloud.githubusercontent.com/assets/6797611/22288317/136314a0-e2ff-11e6-8211-78fa053e4309.jpg)
![wowscrnshot_012517_125857](https://cloud.githubusercontent.com/assets/6797611/22288319/1365335c-e2ff-11e6-9788-feac8a73a815.jpg)
![wowscrnshot_012517_125851](https://cloud.githubusercontent.com/assets/6797611/22288316/1362de86-e2ff-11e6-9be9-548fa2999891.jpg)
![wowscrnshot_012517_125927](https://cloud.githubusercontent.com/assets/6797611/22288318/136437a4-e2ff-11e6-80e8-37d91da13daf.jpg)
![wowscrnshot_012517_125917](https://cloud.githubusercontent.com/assets/6797611/22288315/1362c0b8-e2ff-11e6-9df8-b65f7e359da4.jpg)

**Expected behaviour**: Video from retail legion from 25.01.2017:
Part 1- https://www.youtube.com/watch?v=3lZCtTxpBvU
Part 2- https://www.youtube.com/watch?v=SzW6seDUMM4
Part 3- https://www.youtube.com/watch?v=XWDSaijTH4E

**Comment by Rushor** [comment]
part 1:

```sql
-- Pathing for  Entry: Entry: 'TDB FORMAT' 
SET @NPC := XXXXXX;
SET @PATH := @NPC * 10;
UPDATE `creature` SET `spawndist`=0,`MovementType`=2,`position_x`=8000.43,`position_y`=-2945.279,`position_z`=1136.98 WHERE `guid`=@NPC;
DELETE FROM `creature_addon` WHERE `guid`=@NPC;
INSERT INTO `creature_addon` (`guid`,`path_id`,`mount`,`bytes1`,`bytes2`,`emote`,`auras`) VALUES (@NPC,@PATH,0,0,1,0, '');
DELETE FROM `waypoint_data` WHERE `id`=@PATH;
INSERT INTO `waypoint_data` (`id`,`point`,`position_x`,`position_y`,`position_z`,`orientation`,`delay`,`move_type`,`action`,`action_chance`,`wpguid`) VALUES
(@PATH,1,8000.43,-2945.279,1136.98,0,0,0,0,100,0), -- 12:02:14
(@PATH,2,7999.445,-2947.021,1137.515,0,0,0,0,100,0), -- 12:02:14
(@PATH,3,7997.969,-2949.635,1138.265,0,0,0,0,100,0), -- 12:02:14
(@PATH,4,7996.984,-2951.377,1138.89,0,0,0,0,100,0), -- 12:02:14
(@PATH,5,7995.016,-2954.861,1139.64,0,0,0,0,100,0), -- 12:02:14
(@PATH,6,7993.539,-2957.475,1140.265,0,0,0,0,100,0), -- 12:02:14
(@PATH,7,7991.57,-2960.959,1140.89,0,0,0,0,100,0), -- 12:02:14
(@PATH,8,7988.617,-2966.186,1141.515,0,0,0,0,100,0), -- 12:02:14
(@PATH,9,7985.554,-2971.575,1141.815,0,0,0,0,100,0), -- 12:02:14
(@PATH,10,7985.554,-2971.575,1141.815,0,0,0,0,100,0), -- 12:02:14
(@PATH,11,7994.182,-2964.05,1141.526,0,0,0,0,100,0), -- 12:02:17
(@PATH,12,7998.432,-2960.3,1140.776,0,0,0,0,100,0), -- 12:02:17
(@PATH,13,8001.432,-2957.8,1140.276,0,0,0,0,100,0), -- 12:02:17
(@PATH,14,8004.085,-2955.57,1139.719,0,0,0,0,100,0), -- 12:02:19
(@PATH,15,8001.085,-2952.82,1138.969,0,0,0,0,100,0), -- 12:02:19
(@PATH,16,7997.585,-2949.57,1138.719,0,0,0,0,100,0), -- 12:02:19
(@PATH,17,7994.585,-2946.82,1137.969,0,0,0,0,100,0), -- 12:02:19
(@PATH,18,7989.085,-2941.07,1137.469,0,0,0,0,100,0), -- 12:02:19
(@PATH,19,7993.485,-2939.445,1136.842,0,0,0,0,100,0), -- 12:02:22
(@PATH,20,8001.987,-2909.999,1137.335,0,0,0,0,100,0), -- 12:02:23
(@PATH,21,8001.031,-2905.984,1137.753,0,0,0,0,100,0), -- 12:02:27
(@PATH,22,8006.789,-2934.026,1136.72,0,0,0,0,100,0), -- 12:02:28
(@PATH,23,8000.539,-2945.026,1137.47,0,0,0,0,100,0); -- 12:02:28
-- 0x20197C47601DBBC00000360000082C98 .go 8000.43 -2945.279 1136.98

-- Pathing for  Entry: Entry: 'TDB FORMAT' 
SET @NPC := XXXXXX;
SET @PATH := @NPC * 10;
UPDATE `creature` SET `spawndist`=0,`MovementType`=2,`position_x`=7959.272,`position_y`=-2884.071,`position_z`=1133.766 WHERE `guid`=@NPC;
DELETE FROM `creature_addon` WHERE `guid`=@NPC;
INSERT INTO `creature_addon` (`guid`,`path_id`,`mount`,`bytes1`,`bytes2`,`emote`,`auras`) VALUES (@NPC,@PATH,0,0,1,0, '');
DELETE FROM `waypoint_data` WHERE `id`=@PATH;
INSERT INTO `waypoint_data` (`id`,`point`,`position_x`,`position_y`,`position_z`,`orientation`,`delay`,`move_type`,`action`,`action_chance`,`wpguid`) VALUES
(@PATH,1,7959.272,-2884.071,1133.766,0,0,0,0,100,0), -- 12:02:17
(@PATH,2,7945.515,-2879.25,1132.664,0,0,0,0,100,0), -- 12:02:17
(@PATH,3,7943.628,-2882.781,1133.216,0,0,0,0,100,0), -- 12:02:17
(@PATH,4,7927.119,-2913.68,1135.113,0,0,0,0,100,0), -- 12:02:17
(@PATH,5,7926.772,-2914.314,1135.204,0,0,0,0,100,0), -- 12:02:17
(@PATH,6,7928.581,-2928.274,1138.02,0,0,0,0,100,0), -- 12:02:18
(@PATH,7,7931.831,-2954.774,1138.77,0,0,0,0,100,0), -- 12:02:18
(@PATH,8,7937.19,-2978.99,1139.8,0,0,0,0,100,0), -- 12:02:23
(@PATH,9,7938.92,-2983.871,1138.668,0,0,0,0,100,0), -- 12:02:26
(@PATH,10,7944.67,-2987.621,1137.918,0,0,0,0,100,0), -- 12:02:26
(@PATH,11,7971.077,-2990.12,1138.138,0,0,0,0,100,0), -- 12:02:27
(@PATH,12,7992.952,-2975.797,1142.036,0,0,0,0,100,0), -- 12:02:29
(@PATH,13,7988.995,-2947.633,1138.8,0,0,0,0,100,0), -- 12:02:32
(@PATH,14,7980.995,-2897.633,1138.05,0,0,0,0,100,0), -- 12:02:32
(@PATH,15,7969.358,-2887.465,1135.122,0,0,0,0,100,0), -- 12:02:40
(@PATH,16,7965.608,-2886.215,1134.622,0,0,0,0,100,0); -- 12:02:40
-- 0x20197C47601DBBC00000360000082C9B .go 7959.272 -2884.071 1133.766
```

**Comment by Rushor** [comment]
hm i need to respawn all entries of them, everything is wrong in this zone currently xd

**Comment by Rushor** [comment]
ah btw @Teridan-dal-wow, you don't need to follow every member of a group

Example: Group has one leader and 3 npcs follow him

Then you only need to follow the leader once, you can kill all follower and the leader after that since the path for the follower will be handled in core :)

**Comment by Rushor** [comment]
DB/Creature: Stormpeaks - Romping Rhino - All all spawns and waypoints

* closes: https://github.com/dalaranwow/dalaran-wow/issues/4317
* commit: f892ba907e68156ebe20049d7f7cf2b04c2a5822

total paths:

![GitHub Logo](http://i.imgur.com/BpdPeVZ.jpg)

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by Rushor** [comment]
![4f000837af5964db47ad396804c8906f](https://cloud.githubusercontent.com/assets/5568820/22310137/7164e70a-e34e-11e6-8ae4-4ee25fa011e4.gif)

![777d7c67a43144274e690bc0f5f4c4ad](https://cloud.githubusercontent.com/assets/5568820/22310138/71659204-e34e-11e6-9a4d-9d99eea280b2.gif)

**Comment by Teridan-dal-wow** [comment]
Feedback for this report from TrinityCore rev. 02633a332cf7 2017-02-09.

Works exacly like on retail. Thank you for your work!

**Comment by Teridan-dal-wow** [comment]
Small note: on retail they seems to be moving abit faster. Suggestion based on eye check:

``` sql
UPDATE `creature_template` SET `speed_run` = 1.4992063 WHERE `entry` = 30447; 
```
Change from 0.992063 to  1.4992063

**Comment by Rushor** [comment]
DB/Creature: Romping Rhino - Increase run speed

* updates: https://github.com/dalaranwow/dalaran-wow/issues/4317
* commit: c16d46f3693475c41d4269762661d56c59b9efd6
