### ISSUE TITLE
Website and Vote Problem Ingame

### ISSUE THREAD

**Issue by spore007** [dalaranwow/dalaran-wow#4319]
I have a lvl 71 char ingame called Masharis.
1 hour ago Ive just purchased a Heirloom like 4 times the same ring because it didnt show me Ive recieved it or ordered succesfully my ring.So now I have like 4 rings instead of 1 in the mail.Can I have a refung for the 3 other rings which cost 35vp or whatever it is.
-By the way ingame its possible to have only 1 ring per acc.And I have like 4 now.
I havent picked neither of the 4 now.I Only need 1 and refund for the Vpoints on the 3 others.

Also I cant find my char or any other char to make him my main and make a Forum ticket...it seems not to be working.

**Comment by Edzero** [comment]
This is not the place to report such an issue. 

You can try making a ticket or emailing to seek assistance.

Only characters on Kirin Tor can be selected on the forum.
