### ISSUE TITLE
[NPC][WotlK] Stormrider and Snowdrift Jormungar, missing paths

### ISSUE THREAD

**Issue by Teridan-dal-wow** [dalaranwow/dalaran-wow#4325]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Npc Stormrider http://wotlk.openwow.com/npc=29624 and Snowdrift Jormungar http://wotlk.openwow.com/npc=29390 are missing all of their paths. Area relevent to this report:
![wowscrnshot_012617_124803](https://cloud.githubusercontent.com/assets/6797611/22328590/c615a574-e3c5-11e6-8906-5c6e5436acf3.jpg)
![wowscrnshot_012617_124751](https://cloud.githubusercontent.com/assets/6797611/22328592/c6170ce8-e3c5-11e6-972e-9030e9c82f4b.jpg)
![wowscrnshot_012617_124741](https://cloud.githubusercontent.com/assets/6797611/22328591/c616718e-e3c5-11e6-8234-32020ff84aa1.jpg)
![wowscrnshot_012617_124739](https://cloud.githubusercontent.com/assets/6797611/22328594/c61909bc-e3c5-11e6-97aa-a40ea4eb2b89.jpg)
![wowscrnshot_012617_124733](https://cloud.githubusercontent.com/assets/6797611/22328595/c61c1012-e3c5-11e6-952d-9557b402969e.jpg)
![wowscrnshot_012617_124724](https://cloud.githubusercontent.com/assets/6797611/22328593/c617a7a2-e3c5-11e6-8c81-3f94994640f8.jpg)
![wowscrnshot_012617_124717](https://cloud.githubusercontent.com/assets/6797611/22328596/c62c96f8-e3c5-11e6-9ecd-a2e358027525.jpg)
![wowscrnshot_012617_124707](https://cloud.githubusercontent.com/assets/6797611/22328598/c62f4d80-e3c5-11e6-85c6-140a35998a4a.jpg)
![wowscrnshot_012617_124659](https://cloud.githubusercontent.com/assets/6797611/22328597/c62ef286-e3c5-11e6-837c-1c03b31669ff.jpg)

**Expected behaviour**: Video from retail legion from 26.01.2017:
Part 1- https://www.youtube.com/watch?v=KJJu34xR_2Q
Part 2- https://www.youtube.com/watch?v=QQ5skgjziLk
Part 3- https://www.youtube.com/watch?v=_Wix_8biXEU
Part 4- https://www.youtube.com/watch?v=3yw4ND988iU

**Comment by Teridan-dal-wow** [comment]
Updated with part 4, as i missed 1 spawn (i think that spawn is missing on the server)

**Comment by Rushor** [comment]
btw @Teridan-dal-wow you may need to update the sniffer https://community.trinitycore.org/topic/12264-trinity-cores-sniffer-for-wow-71523420/

with every patch the sniffer needs to be updated too

simply delete the old one and copy the new one in the wow folder

**Comment by Teridan-dal-wow** [comment]
Thank you, will do.

**Comment by Rushor** [comment]
really great sniffing here

**Comment by Rushor** [comment]
DB/Creature: Stormrider and Snowdrift Jormungar - Add 34 Paths

* closes: https://github.com/dalaranwow/dalaran-wow/issues/4325
* commit: f0dc039451f93833a3db9339fb7392a84f8587de

![GitHub Logo](http://i.imgur.com/gHVeHG0.jpg)

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by Teridan-dal-wow** [comment]
Feedback for this report from TrinityCore rev. 02633a332cf7 2017-02-09.

Works exacly like on retail. BIG Thank you for your work!
