### ISSUE TITLE
[NPC][WotlK] Stormforged Taskmaster, missing speech

### ISSUE THREAD

**Issue by Teridan-dal-wow** [dalaranwow/dalaran-wow#4326]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Npc Stormforged Taskmaster http://wotlk.openwow.com/npc=29369 has a missing speech.
![wowscrnshot_012617_133347](https://cloud.githubusercontent.com/assets/6797611/22329909/1f459162-e3cc-11e6-85ad-ca4f10622315.jpg)

**Expected behaviour**: Every ~ 45 secs Stormforged Taskmaster should stop his patrol, face the nearest  Captive Mechagnome http://wotlk.openwow.com/npc=29384 , use emote "point" and say 1 of the speeches below (randomly).
Video from retail legion from 26.01.2017:
https://www.youtube.com/watch?v=DyEjvxs5yUI
Speeches:
[13:37:27] Stormforged Taskmaster says: A pack of mechanical squirrels could mine faster than you!
[13:36:39] Stormforged Taskmaster says: You! You're not fit to punch arclight spanners from copper plates. Get out of my sight!
[13:35:40] Stormforged Taskmaster says: Any worker who doesn't make his quota will be ingots before the day is out!
[13:35:04] Stormforged Taskmaster says: You're not worth the scrap you're made from!
[13:34:21] Stormforged Taskmaster says: A pack of mechanical squirrels could mine faster than you!
[13:33:28] Stormforged Taskmaster says: You! You're not fit to punch arclight spanners from copper plates. Get out of my sight!
[13:32:52] Stormforged Taskmaster says: Any worker who doesn't make his quota will be ingots before the day is out!
[13:21:38] Stormforged Taskmaster says: Any worker who doesn't make his quota will be ingots before the day is out!
[13:21:38] Stormforged Taskmaster says: Any worker who doesn't make his quota will be ingots before the day is out!
[13:32:52] Stormforged Taskmaster says: Any worker who doesn't make his quota will be ingots before the day is out!
[13:35:04] Stormforged Taskmaster says: You're not worth the scrap you're made from!
[13:21:38] Stormforged Taskmaster says: Any worker who doesn't make his quota will be ingots before the day is out!
[13:21:38] Stormforged Taskmaster says: Any worker who doesn't make his quota will be ingots before the day is out!
[13:32:52] Stormforged Taskmaster says: Any worker who doesn't make his quota will be ingots before the day is out!
[13:35:04] Stormforged Taskmaster says: You're not worth the scrap you're made from!

**Comment by Rushor** [comment]
@Teridan-dal-wow this creature you showed in the video is the only one doing the speech? 

or do you know if there are also other Stormforged Taskmasters that talk those sentences to nearest Captive Mechagnome?

**Comment by Teridan-dal-wow** [comment]
I will check, give me a moment.

**Comment by Teridan-dal-wow** [comment]
The answer to your question is that every Stormforged Taskmasters does the speech with the exeption of this one:
![wowscrnshot_012617_150757](https://cloud.githubusercontent.com/assets/6797611/22332382/4ff79424-e3d9-11e6-9c99-caf66a0d0223.jpg)
As he is the only one that has no contact with the Captive Mechagnome, because he patrols outside only. I would like to add also few things that i missed such as:
- The player needs to be very close to the Taskmasters in order to "see" what they are saying.
- Just noticed there are few missing Captive Mechagnome  http://wotlk.openwow.com/npc=29384 at the entrace of the cave:
On server:
![wowscrnshot_012617_150418](https://cloud.githubusercontent.com/assets/6797611/22332506/f7a5a602-e3d9-11e6-90e4-672015201cd1.jpg)
on Retail:
![wowscrnshot_012617_150410](https://cloud.githubusercontent.com/assets/6797611/22332519/02fc8566-e3da-11e6-9fc2-c748ad4c8f65.jpg)
- There are few missing carts with ore at the entrance of the cave:
On server:
![wowscrnshot_012617_150449](https://cloud.githubusercontent.com/assets/6797611/22332574/3dfd70f8-e3da-11e6-81fb-925b1c32af60.jpg)
On retail:
![wowscrnshot_012617_150458](https://cloud.githubusercontent.com/assets/6797611/22332599/577f68d8-e3da-11e6-9f6e-ab4571a88bbf.jpg)
![wowscrnshot_012617_151620](https://cloud.githubusercontent.com/assets/6797611/22332619/78adb744-e3da-11e6-927d-fb94d7e17696.jpg)

I think the file should have them, if not i will do new one.

**Comment by Rushor** [comment]
alright thanks, i will check

**Comment by Rushor** [comment]
alright the script is added, sadly the sniffer didn't tracked the gnomes and the ores at the start of the gave - could you sniff that startarea again pls? thanks (remeber to start the sniffer at far distance from the cave) :)

@Teridan-dal-wow

**Comment by Teridan-dal-wow** [comment]
Will be up in 3 mins.

**Comment by Teridan-dal-wow** [comment]
Done.

**Comment by Rushor** [comment]
DB/Creature: Stormpeaks - Stormforged Taskmaster - Add speech and missing spawns for creatures and gameobjects

* closes: https://github.com/dalaranwow/dalaran-wow/issues/4326
* commit: 302ed41d1b45e2ab9ddb91c88d6e8e149e59dbbe

![GitHub Logo](http://i.imgur.com/N6QVL7t.png)
![GitHub Logo](http://i.imgur.com/WOjuVAK.png)

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by Teridan-dal-wow** [comment]
Feedback for this report from TrinityCore rev. 02633a332cf7 2017-02-09.

Works exacly like on retail. Thank you for your work!

**Comment by Rushor** [comment]
DB/Creature: Stormforged Taskmaster - Readd waypoint_data and simpify actionlist (we are now able to pause waypoint_data movement)

* updates: https://github.com/dalaranwow/dalaran-wow/issues/4326
* commit: 41e287ba21dadeaad0642b766d7e37fafcc54169
