### ISSUE TITLE
[HUNTER] Cobra Strikes bug?

### ISSUE THREAD

**Issue by invictusfun** [dalaranwow/dalaran-wow#4329]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: I was trying BM with hunter and working arround the Cobra Strikes talent to do some DPS calculations and i thinks this talent is bugged, i see no stats coming out in the screen.

**Expected behaviour**: So, When i crit with my Arcane Shots the buf for my pet should appear and it doenst, when i'm without the pet it pops out but with no pet its uselees beacause the buf goes to the pet not to me.. 

**Steps to reproduce the problem**:

1. Having a BM HUNTER with cobra strikes 3/3
2. Trying to fight a mob with and without a pet
3. Whatch the stats and bufs to see if its ok or bugged

Maybe its me, i'm doing something wrong but i saw in this error alreadu talked here but a long time ago, is it possible that it was not fixed? 

thanks a lot
Cheers

**Comment by Rushor** [comment]
Works fine on PTR.

**Comment by invictusfun** [comment]
I will try to make some pics

**Comment by invictusfun** [comment]
Weird, yeasterday i wanst pop up the talend at all, now i could make it 2 or 3 times, is it possible that i have just low crit rating and i do realy poor crit strikes with arcane shot?

**Comment by invictusfun** [comment]
you can close the issue lol i'm just noob and with low crit rating

**Comment by Rushor** [comment]
kk /closed
