### ISSUE TITLE
Quest: Escape from Silverbrook

### ISSUE THREAD

**Issue by Golganeth** [dalaranwow/dalaran-wow#433]
www.wowhead.com/quest=12308

**Issue:** Upon picking up the quest, the escort event doesn't start and the cage will remain closed.

**How it should work:** Once you pick up the quest, the cage opens automatically and the guy named "Caged Prisoner" becomes "Freed Alliance Scout". After saying few quotes, he leads you to "Ducal's Horse", and you will both mount it up to start the journey back to home. A massive amount of speedy "Silverbrook Worgen" will start to chase the Horse.
You will have three skills to protect yourself:
* **Burning oil -** 48677
* **Gallop -** 48768
* **Trample**- 48783

Once you successfully arrive to Amberpine Lodge, the quest gets completed.

**Video of how it should work:** http://www.youtube.com/watch?v=s8_7E7YLAqM

-------------------------------------------------------

* **Caged Prisoner -** http://www.wowhead.com/npc=27499
* **Freed Alliance Scout-** http://www.wowhead.com/npc=27411
* **Ducal's Horse** (On the following link he is lacking the skill "Burning Oil") - www.wowhead.com/npc=27409
* **Silverbrook Worgen -** http://www.wowhead.com/npc=27417

------------------------------------------

**Comment by Lothloryen** [comment]
Hello there,

This quest shall be working again after the next update.

Thank you.
