### ISSUE TITLE
[NPC][WotlK] Frostborn Scout and Frostfeather Witch/Frostfeather Screecher

### ISSUE THREAD

**Issue by Teridan-dal-wow** [dalaranwow/dalaran-wow#4330]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Part 1: Npc Frostborn Scout http://wotlk.openwow.com/npc=29811 should be spawned on 7 diffrent locations around storm peaks, guarded by 1 Frostfeather Witch http://wotlk.openwow.com/npc=29793 or 1 Frostfeather Screecher http://wotlk.openwow.com/npc=29792. Currently he is spawned on 5 of these 7 locations. The missing 2 are here:
![wowscrnshot_012617_171846](https://cloud.githubusercontent.com/assets/6797611/22339241/faa6353e-e3f1-11e6-8f55-9f776c8b69e8.jpg)
![wowscrnshot_012617_171409](https://cloud.githubusercontent.com/assets/6797611/22339240/faa0cc52-e3f1-11e6-9b6a-3b126e758eb7.jpg)

Part 2: The harpy that is guarding him is moving randomly, which is incorrect. She should be standing still facing the scout and do nothing else.
![wowscrnshot_012617_172806](https://cloud.githubusercontent.com/assets/6797611/22339265/0ea9b696-e3f2-11e6-8bbf-408677cd917e.jpg)

**Expected behaviour**: Video from retail legion from 26.01.2017:
https://www.youtube.com/watch?v=53zDfl_FcOA

**Comment by Rushor** [comment]
DB/Creature: Stormpeaks - Frostborn Scout and Frostfeather Witch/Frostfeather Screecher - Add missing spawns + remove randommovement

* closes: https://github.com/dalaranwow/dalaran-wow/issues/4330
* commit: b2fe3ecc8f2a2dd4da703dc0f435ba94dc43a814
* commit: 539db9ec31c8902879bbf6777f3ff3b8140fc214

**Comment by Teridan-dal-wow** [comment]
Feedback for this report from TrinityCore rev. 02633a332cf7 2017-02-09.

Works exacly like on retail. Thank you for your work!
