### ISSUE TITLE
[EN][Object] Holiday Events

### ISSUE THREAD

**Issue by TheRealestMcCoy** [dalaranwow/dalaran-wow#4333]
**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
Seems evey holiday items thast dont belong are up.
**Expected behaviour**: Tell us what should happen instead
Only current holiday items should be up.
**Steps to reproduce the problem**:

1. Wait for holiday look for these items
2. 
3. 

**Include proofs for this behaviour**
**Both are these are related to Halloween Event**
4 Wickerman in Goldshire
![wowscrnshot_012617_210022](https://cloud.githubusercontent.com/assets/12252441/22358101/97fb5e78-e40a-11e6-8e7b-b5aba42a1fdf.jpg)

![wowscrnshot_012617_212249](https://cloud.githubusercontent.com/assets/12252441/22358508/a55e138c-e40d-11e6-85ca-f134a7ed72f8.jpg)

2 Water Barrels in Goldshire
![wowscrnshot_012617_210153](https://cloud.githubusercontent.com/assets/12252441/22358166/0f1b657a-e40b-11e6-8c24-1eac8a15d9bb.jpg)

![wowscrnshot_012617_210559](https://cloud.githubusercontent.com/assets/12252441/22358221/4e01e9d0-e40b-11e6-9178-d8a3cced660c.jpg)

You can research this on several pages like http://wowhead.com or http://wowwiki.wikia.com or http://www.youtube.com/
Issues without proofs will be closed and tag On Hold will be added until the proof is provided.

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**
[Water Barrel](http://wotlk.openwow.com/object=186234)
Wickerman in goldshire

Also I do not have the pics or all locations but some of the Flame Wardens are up all the time. I know the one in Arathi Highlands for the alliance is always up.

**Comment by Rushor** [comment]
cannot confirm anything of that 

http://i.imgur.com/6ucoL6Y.jpg
http://i.imgur.com/Qk3zwyG.jpg

It was already fixed on PTR. The fix will be moved to the live realm with further changelogs. Thanks for report.

**Comment by TeridanDW** [comment]
> cannot confirm anything of that
