### ISSUE TITLE
[EN][Profession][Wintergrasp]Herbalism

### ISSUE THREAD

**Issue by TheRealestMcCoy** [dalaranwow/dalaran-wow#4334]
Couple Issues
1.Can the respawn rate on actual Frost Lotus be check in Wintergrasp or the spawn share rate? There should be 157 spawn locations.

2. Herb phasing in wintergrasp
**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
**Issue 1** 
I have only ever found 1 Frost Lotus spawn in Wintergrasp. Frost Lotus should share respawns with frozen ferbs. 
Comment from wowhead patch 3.0.8
I been running around Wintergrasp and marking out where I found Frost Lotuses and I have noticed that they share the same spawn spot as Frozen Herbs.
**Issue 2**
I have noticed a herb and some ore mines phased based on where you are in witergrasp. 
Some are based on a Dragon Blight phase. Up at glacial falls.
**Expected behaviour**: Tell us what should happen instead
Frost Lotus should share respawn with frozen herbs.
No herbs should phase in Wintergrasp.
**Steps to reproduce the problem**:

1. 
2. 
3. 

**Include proofs for this behaviour**
Herb can be seen
![wowscrnshot_012617_222348](https://cloud.githubusercontent.com/assets/12252441/22359577/7243b124-e416-11e6-814f-daf7d8637f12.jpg)

Move a inch herb dissappears.
![wowscrnshot_012617_222353](https://cloud.githubusercontent.com/assets/12252441/22359582/7ca791d0-e416-11e6-8984-dece0d2c8436.jpg)

You can research this on several pages like http://wowhead.com or http://wowwiki.wikia.com or http://www.youtube.com/
Issues without proofs will be closed and tag On Hold will be added until the proof is provided.

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**
[Frozen Herb](http://www.wowhead.com/object=190176/frost-lotus#herbalism)
You can research this on several pages like http://wotlk.openwow.com or http://wowhead.com/

**Include Screenshots from the issue if necessary**

**Comment by Rushor** [comment]
moved to https://github.com/dalaranwow/dalaran-wow/issues/1208, that issue will be reopenend once the posted stuff was tested. ty.
