### ISSUE TITLE
[NPC][WotlK] Stormforged Loreseeker and Stormforged Pillager, missing paths and incorrect spawn loc

### ISSUE THREAD

**Issue by Teridan-dal-wow** [dalaranwow/dalaran-wow#4336]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: 
 - Part 1: 
Npc Stormforged Loreseeker http://wotlk.openwow.com/npc=29843 is not casting his spell http://wotlk.openwow.com/spell=12550 out of combat (upon spawn or spell expire).
![wowscrnshot_012717_115730](https://cloud.githubusercontent.com/assets/6797611/22367154/bf81ee52-e488-11e6-984b-c74ec9a149c9.jpg)

Instead he casts it upon engaging in combat:
![wowscrnshot_012717_115733](https://cloud.githubusercontent.com/assets/6797611/22367171/db14608c-e488-11e6-9a82-dbb15b48cbb3.jpg)

 - Part 2:
Npc Stormforged Loreseeker http://wotlk.openwow.com/npc=29843 and npc Stormforged Pillager http://wotlk.openwow.com/npc=29586 are missing their paths (the once that should have atlest) and emote.

 - Part 3:
Npc Stormforged Loreseeker http://wotlk.openwow.com/npc=29843 and npc Stormforged Pillager http://wotlk.openwow.com/npc=29586 have ~50% of their spawns slightly in a wrong position.
Example from server:
![wowscrnshot_012717_122136](https://cloud.githubusercontent.com/assets/6797611/22367644/6400d8f6-e48b-11e6-8325-cac85decb9c2.jpg)
From retail:
![wowscrnshot_012717_122240](https://cloud.githubusercontent.com/assets/6797611/22367658/775eaa18-e48b-11e6-92d7-464616a27e79.jpg)

Note: This is just 1 example, there are alot more, maybe it will be easier if all spawns are removed and new ones are placed based on sniff?

**Expected behaviour**: 
Part 1: Stormforged Loreseeker is suppose to cast his shield out of combat (on spawn and on spell expire, screenshot from retail):
![wowscrnshot_012717_120814](https://cloud.githubusercontent.com/assets/6797611/22367269/601ad176-e489-11e6-916d-bd552eef271f.jpg)
Part 2 & 3: Video from retail legion from 27.01.2017:
https://www.youtube.com/watch?v=mUuFf-uFwzY

**Comment by Rushor** [comment]
hm yeah Teridan-dal-wow i would respawn everything if you want

are you shure that the file contains all spawns and paths?

**Comment by Rushor** [comment]
@Teridan-dal-wow

**Comment by Teridan-dal-wow** [comment]
Yes, there are few patrols (~5), most of them are just standing still.

**Comment by Rushor** [comment]
kk thx

**Comment by Rushor** [comment]
alright respawned all, need to add path + emotes now

**Comment by Rushor** [comment]
DB/Creature: Stormforged Loreseeker and Stormforged Pillager - Complete Respawn + add path and emotescripts + Update Script for 'Lightning Shield'

* closes: https://github.com/dalaranwow/dalaran-wow/issues/4336
* commit: a5aabbc40e712b098205f0f92eadad149cadab83

![GitHub Logo](http://i.imgur.com/x1jBnyw.jpg)
![GitHub Logo](http://i.imgur.com/0aleya7.jpg)
![GitHub Logo](http://i.imgur.com/xgT9Lc0.png)
![GitHub Logo](http://i.imgur.com/XRB3sHQ.png)

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by Teridan-dal-wow** [comment]
Feedback for this report from TrinityCore rev. 02633a332cf7 2017-02-09.

Found few double spawns here:
![wowscrnshot_021017_221027](https://cloud.githubusercontent.com/assets/6797611/22842491/124c0e78-efde-11e6-82d6-464c004023bf.jpg)
![wowscrnshot_021017_221016](https://cloud.githubusercontent.com/assets/6797611/22842496/12529126-efde-11e6-86f4-5cee144f4e60.jpg)
![wowscrnshot_021017_221011](https://cloud.githubusercontent.com/assets/6797611/22842494/12514d20-efde-11e6-977e-44bc799af343.jpg)
![wowscrnshot_021017_221005](https://cloud.githubusercontent.com/assets/6797611/22842492/124c4e24-efde-11e6-95c6-5b279bc9877b.jpg)
![wowscrnshot_021017_220948](https://cloud.githubusercontent.com/assets/6797611/22842493/1250c562-efde-11e6-961e-b3ce304803c5.jpg)
![wowscrnshot_021017_221103](https://cloud.githubusercontent.com/assets/6797611/22842495/1252263c-efde-11e6-9afd-c11302e11f51.jpg)

And 1 wrong spawn that i can't find on retail here:
![wowscrnshot_021017_221139](https://cloud.githubusercontent.com/assets/6797611/22842532/2bc0022e-efde-11e6-9495-9e7a51980f35.jpg)

Also i found a mistake in my report - npc http://wotlk.openwow.com/npc=29751 is missing an emote, he should be laying down on the ground (check video above at 2:55s).

**Comment by Rushor** [comment]
DB/Creature: Stormforged Loreseeker and Stormforged Pillager - Remove duplicate spawns + add emotestate for Drom Frostgrip

* updates: https://github.com/dalaranwow/dalaran-wow/issues/4336
* commit: b8f15d351cc29a7644002dcd5289a4f44e0da37b
