### ISSUE TITLE
[NPC][WotlK] Stormcrest Eagle, missing path and wrong state

### ISSUE THREAD

**Issue by Teridan-dal-wow** [dalaranwow/dalaran-wow#4338]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Npc Stormcrest Eagle http://wotlk.openwow.com/npc=29854 is missing 1 spawn and 2 paths and the rest of them are flying while they should be sitting.
![wowscrnshot_012717_162351](https://cloud.githubusercontent.com/assets/6797611/22374307/63b54094-e4ae-11e6-8269-6ba3adcf28ff.jpg)

**Expected behaviour**: Video from retail legion from 27.01.2017:
https://www.youtube.com/watch?v=ZCyvCfw5bPY

**Comment by Teridan-dal-wow** [comment]
What is done here:
 - added the 4 missing spawns
 - changed the position of the ones that were present to match sniff
 - added sit emote to the ones that should have it
 - added 2 paths (both 100% handmade because wp creator doesn't find paths for any eagle (maybe because they are fying))
``` sql
SET @CGUID := 5004753;
DELETE FROM `creature` WHERE `guid` BETWEEN @CGUID+0 AND @CGUID+4;
INSERT INTO `creature` (`guid`, `id`, `map`, `zoneId`, `areaId`, `spawnMask`, `phaseMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `VerifiedBuild`) VALUES
(@CGUID+0, 29854, 571, 0, 0, 1, 1, 0, 0, 6648.753, -543.8864, 1116.368, 6.178465, 120, 0, 0, 0, 0, 0, 0, 0, 0, 23420), -- 29854 (Area: -1)
(@CGUID+1, 29854, 571, 0, 0, 1, 1, 0, 0, 6668.192, -559.2666, 1119.507, 2.251475, 120, 0, 0, 0, 0, 0, 0, 0, 0, 23420), -- 29854 (Area: -1)
(@CGUID+2, 29854, 571, 0, 0, 1, 1, 0, 0, 6706.833, -570.6165, 1139.007, 5.445427, 120, 0, 0, 0, 0, 0, 0, 0, 0, 23420), -- 29854 (Area: -1)
(@CGUID+3, 29854, 571, 0, 0, 1, 1, 0, 0, 6797.91, -432.407, 1309.6, 2.363997, 120, 10, 0, 0, 0, 2, 0, 0, 0, 23420); -- 29854 (Area: -1) (possible waypoints or random movement)
DELETE FROM `creature_addon` WHERE `guid` BETWEEN @CGUID+0 AND @CGUID+2;
INSERT INTO `creature_addon` (`guid`, `path_id`, `mount`, `bytes1`, `bytes2`, `emote`, `auras`) VALUES
(@CGUID+0, 0, 0, 1, 1, 0, ''),
(@CGUID+1, 0, 0, 1, 1, 0, ''),
(@CGUID+2, 0, 0, 1, 1, 0, '');
DELETE FROM `creature_addon` WHERE `guid` IN (75092, 75096, 75093, 75097, 75098, 75095);
INSERT INTO `creature_addon` (`guid`, `path_id`, `mount`, `bytes1`, `bytes2`, `emote`, `auras`) VALUES
(75092, 0, 0, 1, 1, 0, ''),
(75096, 0, 0, 1, 1, 0, ''),
(75093, 0, 0, 1, 1, 0, ''),
(75097, 0, 0, 1, 1, 0, ''),
(75098, 0, 0, 1, 1, 0, ''),
(75095, 0, 0, 1, 1, 0, '');
UPDATE `creature` SET `position_x` = 6696.017 , `position_y` = -485.5855 , `position_z` = 1194.805 , `orientation` = 1.291544 , `spawntimesecs` = 120 WHERE `guid` = 75093; 
UPDATE `creature` SET `position_x` = 6697.544 , `position_y` = -462.1154 , `position_z` = 1178.335 , `orientation` = 6.161012 , `spawntimesecs` = 120 WHERE `guid` = 75097; 
UPDATE `creature` SET `position_x` = 6711.4 , `position_y` = -533.5759 , `position_z` = 1212.667 , `orientation` = 1.169371 , `spawntimesecs` = 120 WHERE `guid` = 75092; 
UPDATE `creature` SET `position_x` = 6647.161 , `position_y` = -479.3048 , `position_z` = 1167.311 , `orientation` = 2.408554 , `spawntimesecs` = 120 WHERE `guid` = 75095; 
UPDATE `creature` SET `position_x` = 6674.972 , `position_y` = -463.7826 , `position_z` = 1179.887 , `orientation` = 6.056293 , `spawntimesecs` = 120 WHERE `guid` = 75098; 
UPDATE `creature` SET `position_x` = 6707.448 , `position_y` = -521.2218 , `position_z` = 1211.72 , `orientation` = 5.51524 , `spawntimesecs` = 120 WHERE `guid` = 75096; 
UPDATE `creature` SET `spawntimesecs` = 120 WHERE `guid` = 75094; 
SET @NPC := 75094; 
SET @PATH := @NPC * 10;
UPDATE `creature` SET `spawndist`=0,`MovementType`=2,`position_x`=6671.44,`position_y`=-410.871,`position_z`=1189.35 WHERE `guid`=@NPC;
DELETE FROM `waypoint_data` WHERE `id`=@PATH;
INSERT INTO `waypoint_data` (`id`,`point`,`position_x`,`position_y`,`position_z`,`orientation`,`delay`,`move_type`,`action`,`action_chance`,`wpguid`) VALUES
(@PATH,1,6671.44,-410.871,1189.35,0,0,2,0,100,0), 
(@PATH,2,6623.24,-432.985,1189.35,0,0,2,0,100,0), 
(@PATH,3,6589.78,-495.543,1195.29,0,0,2,0,100,0),
(@PATH,4,6624.64,-554.703,1195.29,0,0,2,0,100,0), 
(@PATH,5,6677.07,-588.908,1195.29,0,0,2,0,100,0), 
(@PATH,6,6677.07,-588.908,1195.29,0,0,2,0,100,0), 
(@PATH,7,6803,-556.99,1195.29,0,0,2,0,100,0), 
(@PATH,8,6811.62,-483.225,1195.29,0,0,2,0,100,0),
(@PATH,9,6764.48,-411.193,1195.29,0,0,2,0,100,0),
(@PATH,10,6693.83,-399.055,1195.29,0,0,2,0,100,0);
SET @NPC := @CGUID+3; 
SET @PATH := @NPC * 10;
UPDATE `creature` SET `spawndist`=0,`MovementType`=2,`position_x`=6797.91,`position_y`=-432.407,`position_z`=1309.6 WHERE `guid`=@NPC;
DELETE FROM `waypoint_data` WHERE `id`=@PATH;
INSERT INTO `waypoint_data` (`id`,`point`,`position_x`,`position_y`,`position_z`,`orientation`,`delay`,`move_type`,`action`,`action_chance`,`wpguid`) VALUES
(@PATH,1,6797.91,-432.407,1309.6,0,0,2,0,100,0), 
(@PATH,2,6735.54,-395.891,1309.6,0,0,2,0,100,0), 
(@PATH,3,6661.84,-397.912,1309.6,0,0,2,0,100,0),
(@PATH,4,6605.58,-456.592,1309.6,0,0,2,0,100,0), 
(@PATH,5,6602.97,-530.773,1309.6,0,0,2,0,100,0), 
(@PATH,6,6653.91,-595.69,1309.6,0,0,2,0,100,0), 
(@PATH,7,6734.36,-601.493,1309.6,0,0,2,0,100,0), 
(@PATH,8,6795.45,-549.087,1309.6,0,0,2,0,100,0);
```
![image](https://cloud.githubusercontent.com/assets/6797611/22889331/6c37d70c-f211-11e6-9afa-add8298bb874.png)

Questiong:
TC wiki says for `creature` `curhealth ` Storage used by core. "Always set as 1" but sniff says 0, which one to use?
How can i increase the movement speed of creature (out of combat) to more than just the normal speed?

**Comment by Rushor** [comment]
curhealth = 0 is also fine,

How can i increase the movement speed of creature (out of combat) to more than just the normal speed (walk/run/fly)?

if you use the waypoint_data table you can define walking and running by changing the `move_type`. Set everything to 1 and it will run.

example:

```sql
SET @NPC := @CGUID+3; 
SET @PATH := @NPC * 10;
UPDATE `creature` SET `spawndist`=0,`MovementType`=2,`position_x`=6797.91,`position_y`=-432.407,`position_z`=1309.6 WHERE `guid`=@NPC;
DELETE FROM `waypoint_data` WHERE `id`=@PATH;
INSERT INTO `waypoint_data` (`id`,`point`,`position_x`,`position_y`,`position_z`,`orientation`,`delay`,`move_type`,`action`,`action_chance`,`wpguid`) VALUES
(@PATH,1,6797.91,-432.407,1309.6,0,0,1,0,100,0), 
(@PATH,2,6735.54,-395.891,1309.6,0,0,1,0,100,0), 
(@PATH,3,6661.84,-397.912,1309.6,0,0,1,0,100,0),
(@PATH,4,6605.58,-456.592,1309.6,0,0,1,0,100,0), 
(@PATH,5,6602.97,-530.773,1309.6,0,0,1,0,100,0), 
(@PATH,6,6653.91,-595.69,1309.6,0,0,1,0,100,0), 
(@PATH,7,6734.36,-601.493,1309.6,0,0,1,0,100,0), 
(@PATH,8,6795.45,-549.087,1309.6,0,0,1,0,100,0);
```

I'm not sure why you added "2" in `move_type`. `move_type` can always only be 0 (walk) or 1 (run) and has nothing to do with the movementtype from the creature table :)

**Comment by Rushor** [comment]
> (both 100% handmade because wp creator doesn't find paths for any eagle (maybe because they are fying)

yeah, some creature there use splinemovement, that does not generate any movement smgs

**Comment by Rushor** [comment]
oh and don't forget to add the path assigned to the guid in the creature_addon table

```sql
DELETE FROM `creature_addon` WHERE `guid`=@NPC;
INSERT INTO `creature_addon` (`guid`,`path_id`,`mount`,`bytes1`,`bytes2`,`emote`,`auras`) VALUES (@NPC,@PATH,0,0,1,0, '');
```

**Comment by Teridan-dal-wow** [comment]
> oh and don't forget to add the path assigned to the guid in the creature_addon table

Right, my bad, thank you.

> you added move_type = 2 because it defined with 2 - flying 

I did try that one too, didn't really notice any diffrence (maybe because the creature is flying only).

> yeah always set it to 1, it's an issue with the wpp then

Right.

**Comment by Rushor** [comment]
and one more info:

if the movement is still too low for whatever reason you can still increase speed_walk and speed_run in the creature_template

**Comment by Teridan-dal-wow** [comment]
I was just about to ask exacly about speed_run :D 
Updated second post with all tips, thank you.

**Comment by Rushor** [comment]
@Teridan-dal-wow you can now see the current uses guids there https://github.com/dalaranwow/dalaran-wow/blob/master/ID-List

**Comment by Rushor** [comment]
DB/Creature: Stormcrest Eagle - Add missing path and emotes

* closes: https://github.com/dalaranwow/dalaran-wow/issues/4338
* thanks to Teridan
* commit: 6a69f1577adc951f75e5e8d7c751d604030307b7

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
