### ISSUE TITLE
[NPC][WotlK] Frostborn Stormrider, missing patrol

### ISSUE THREAD

**Issue by Teridan-dal-wow** [dalaranwow/dalaran-wow#4340]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Npc Frostborn Stormrider http://wotlk.openwow.com/npc=30166 who is riding a
Stormcrest Eagle http://wotlk.openwow.com/npc=29854 has few issues:
 -  There should be a Frostborn Stormrider riding a Stormcrest Eagle here, standing still:
![wowscrnshot_012717_172005](https://cloud.githubusercontent.com/assets/6797611/22375981/f177ce8c-e4b4-11e6-9be6-ea47c1a55afa.jpg)

 - Currently on the server there is a patrol path of Frostborn Stormrider riding a Stormcrest Eagle (over Frosthold), if a player has a flying mount, he can go closer you him and right click on his mount, which will lead to mounting his eagle and gaining control of it.
![wowscrnshot_012717_165432](https://cloud.githubusercontent.com/assets/6797611/22375746/021ad442-e4b4-11e6-930a-89e342d04c8f.jpg)

 - The movement speed of the rider over frosthold should be increased to match retail value.
 - There is a second patrol of Frostborn Stormrider riding a Stormcrest Eagle which is missing on the server (check part 2 video below).
**Expected behaviour**: Video from retail legion from 27.01.2017:
Part 1-https://www.youtube.com/watch?v=kOcHH7d8myU
Part 2-https://www.youtube.com/watch?v=0SycKeHpT8Y

**Comment by Teridan-dal-wow** [comment]
For this report:
- added 1 missing spawn
- increased eagle's movement speed abit (no sniff data, visual comparisment with retail only)
``` sql
DELETE FROM `creature` WHERE `guid` = 5004757;
INSERT INTO `creature`  (`guid`, `id`, `map`, `zoneId`, `areaId`, `spawnMask`, `phaseMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `VerifiedBuild`) VALUES
(5004757, 30013, 571, 0, 0, 1, 1, 0, 0, 6599.463, -285.6094, 984.0918, 0.5585054, 120, 0, 0, 0, 0, 0, 0, 0, 0, 23420);
UPDATE `creature_template` SET `speed_run` = 2 WHERE `entry` = 30013; 
```
 

> There is a second patrol of Frostborn Stormrider riding a Stormcrest Eagle which is missing on the server .

This works fine on TC.
To do:
- Fix the "mounting" bug (stil digging around the tables)

**Comment by Rushor** [comment]
> Fix the "mounting" bug (stil digging around the tables)

Try it with https://trinitycore.atlassian.net/wiki/display/tc/conditions there should be something for spellclick/vehicles

**Comment by Teridan-dal-wow** [comment]
Second post updated.

**Comment by Rushor** [comment]
DB/Creature: Frostborn Stormrider - add missing patrol, spawns and spellclickconditions

* closes: https://github.com/dalaranwow/dalaran-wow/issues/4340
* thanks to Teridan
* also added the missing spawns and paths that were already fixed by TC
* commit: d3397da2ee8bae125a8fb8839b777d34474474e6

![GitHub Logo](http://i.imgur.com/trZCnsD.jpg)

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
