### ISSUE TITLE
[NPC][WotlK] Stormforged Saboteur, missing paths/emotes

### ISSUE THREAD

**Issue by Teridan-dal-wow** [dalaranwow/dalaran-wow#4341]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Npc Stormforged Saboteur http://wotlk.openwow.com/npc=31693 is missing all its paths and emotes. Area relevent to this report:
![wowscrnshot_012717_180004](https://cloud.githubusercontent.com/assets/6797611/22377457/ae9f4a94-e4ba-11e6-9f1f-4be3c5e7567a.jpg)

**Expected behaviour**: Video from retail legion from 27.01.2017:
https://www.youtube.com/watch?v=18LNXUC7T70

**Comment by Rushor** [comment]
DB/Creature: Stormpeaks - Stormforged Saboteur - Add missing paths

* closes: https://github.com/dalaranwow/dalaran-wow/issues/4341
* commit: 71b59c586d82b287906379205b8b6a493a9c1031

![GitHub Logo](http://i.imgur.com/c6vpu0L.jpg)

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by Teridan-dal-wow** [comment]
Feedback for this report from TrinityCore rev. 02633a332cf7 2017-02-09.

Works exacly like on retail. Thank you for your work!

**Comment by Teridan-dal-wow** [comment]
Small corrections. 1 of those 2 npcs should be standing at the tend with random movement only.
![image](https://cloud.githubusercontent.com/assets/6797611/23202973/3262e43e-f8e9-11e6-8f08-4da9a44ba2b6.png)

``` sql
UPDATE `creature` SET `position_x` = 7707.387 , `position_y` =  -2402.524 , `position_z` = 1078.971 ,`spawndist` = 5 , `MovementType` = 1 WHERE `guid` = 88121; 
DELETE FROM `waypoint_data` WHERE `id`= 881210;
```

**Comment by Rushor** [comment]
the creature addon needs to be deleted too here

**Comment by Rushor** [comment]
DB/Creature: Stormforged Saboteur - Replace one path with randommovement and update position

* updates: https://github.com/dalaranwow/dalaran-wow/issues/4341
* commit: cccf9510832230b914f8c888840de0b6568521ec

**Comment by Teridan-dal-wow** [comment]
Right, updated. 
I would like to add these creatures also have lower hp pool than the normal lvl 79/80 creatures.

**Comment by Teridan-dal-wow** [comment]
Looked thoughout some sites and couldn't find any information of these npcs have low hp pool during wotlk. Also the normal lvl 80 npc after blizz's stat squish has 5.5k so that would mean they had a normal stats during wrath.
![image](https://cloud.githubusercontent.com/assets/6797611/23273137/86d25d7e-fa06-11e6-86c1-bb9dd1e0384c.png)

**Comment by Rushor** [comment]
DB/Creature: Stormforged Saboteur - Increase healthpoints to match level 79 -80 creatures

* updates: https://github.com/dalaranwow/dalaran-wow/issues/4341
* commit: 7b7062e6957893944b0b1bc7bd18ef66a7301762

**Comment by Teridan-dal-wow** [comment]
Appologies for noticing these things 1 by 1, but its just how it happend. Saboteurs also do less damage than they should do for their level. I think they share the same issue like #4343 
One more detail for them, as they wear 2x handed weapons, they should attack with both of the as a dual wielding style. Currently they attack only with their main hand weapon and the off-hand is not used at all.

**Comment by Teridan-dal-wow** [comment]
Fix for the issue above.
``` sql
-- Stormforged Saboteur SAI
SET @ENTRY := 31693;
UPDATE `creature_template` SET `AIName`="SmartAI" WHERE `entry`=@ENTRY;
DELETE FROM `smart_scripts` WHERE `entryorguid`=@ENTRY AND `source_type`=0;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(@ENTRY,0,0,0,25,0,100,0,0,0,0,0,11,42459,0,0,0,0,0,1,0,0,0,0,0,0,0,"Stormforged Saboteur - On Reset - Cast 'Dual Wield'");
```
![image](https://cloud.githubusercontent.com/assets/6797611/23872138/ccdab50e-0835-11e7-81d4-1c3246348fda.png)

**Comment by Rushor** [comment]
easier: 
```sql 
UPDATE `creature_addon` SET `bytes2`=0 WHERE  `guid` IN (SELECT `guid` FROM `creature` WHERE `id`=31693); 
``` 
:)

**Comment by Teridan-dal-wow** [comment]
Yep, that works too, didn't know byte2=0 does that too.

**Comment by Rushor** [comment]
DB/Creature: Stormforged Saboteur - Increase Damage and enable 'Dual Wield'

* updates: https://github.com/dalaranwow/dalaran-wow/issues/4341
* commit: 0ee62c2fbf9b147e21be8c651d80d781712b597f
