### ISSUE TITLE
[NPC][WotlK] Ancient Sentinel, missing spawns/paths/level

### ISSUE THREAD

**Issue by Teridan-dal-wow** [dalaranwow/dalaran-wow#4343]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Npc Ancient Sentinel http://wotlk.openwow.com/npc=31797 is missing almost all of its spawns, all of its paths and its lvl 1?
![wowscrnshot_012717_191642](https://cloud.githubusercontent.com/assets/6797611/22380200/36189624-e4c5-11e6-9f2f-7f90f10f9b2e.jpg)
There is also a spawned brann (probably part of some quest, please check on ptr if he is there too):
![wowscrnshot_012717_191654](https://cloud.githubusercontent.com/assets/6797611/22380240/5ae5b806-e4c5-11e6-8557-6feedaa900b8.jpg)
Note: He isn't there on retail.

**Expected behaviour**: Video from retail legion from 27.01.2017:
https://www.youtube.com/watch?v=Q-3HygfqfKU

**Comment by Rushor** [comment]
hm brann is not there for me on ptr, maybe a tempbug from some quest - i will add the spawns and paths now from scratch

**Comment by Rushor** [comment]
DB/Creature: Stormpeaks - Ancient Sentinel - Add missing spawns/paths/level 

* closes: https://github.com/dalaranwow/dalaran-wow/issues/4343
* commit: f4fc4c9ed46cd4e5eb429ef7d1dcd2f57dca0043

![GitHub Logo](http://i.imgur.com/Aj1MPi0.png)
![GitHub Logo](http://i.imgur.com/KISPyXQ.jpg)
![GitHub Logo](http://i.imgur.com/aJ1XqZb.jpg)

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by Teridan-dal-wow** [comment]
Found where this Brann comes from.
There is an item called Brann's Communicator http://wotlk.openwow.com/item=40971 which summons Brann based on the faction of the player that used it. The item itself has 2 mins cd, so the max time that these "Branns" should stay spawned in the world should be. I think its alot more than that currently.
 - Can someone, who has this item in-game, test the despawn time for his Brann and post it here please.

**Comment by Rushor** [comment]
the despawntime for him is blizzlike set to: -- Duration: ID (25)  180000, 0, 180000 milliseconds -- 

http://wotlk.openwow.com/spell=55038

**Comment by Teridan-dal-wow** [comment]
Feedback for this report from TrinityCore rev. 02633a332cf7 2017-02-09.

Works exacly like on retail. Thank you for your work!

**Comment by Teridan-dal-wow** [comment]
Hm, there seems to be an issue with their scaling. They have low hp pool and doing less damage than they should:
![image](https://cloud.githubusercontent.com/assets/6797611/23202452/a8e409d8-f8e6-11e6-858a-63c9daea0e0a.png)

Also openwow says they should have 2 spells:
http://wotlk.openwow.com/spell=5568 and http://wotlk.openwow.com/spell=12612
While wowhead says only:
http://www.wowhead.com/spell=12612/stomp

They are casting only http://wotlk.openwow.com/spell=5568 at the moment, however the damage of that spell is low too.

**Comment by Rushor** [comment]
DB/Creature: Ancient Sentinel - Increase health by 129 percent, increase damage by 300 percent,  update SAI to always cast 'Stomp' and 'Trample'

* updates: https://github.com/dalaranwow/dalaran-wow/issues/4343
* commit: c55a27208b1e492264b5f0cc6f2bea55a443ea36
