### ISSUE TITLE
[NPC][WotlK] Servant of Hodir, missing spawns

### ISSUE THREAD

**Issue by Teridan-dal-wow** [dalaranwow/dalaran-wow#4346]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Npc Servant of Hodir http://wotlk.openwow.com/npc=30881 is missing all of its spawns (he should be spawned dead). Area relevent to this report:
![wowscrnshot_012817_122544](https://cloud.githubusercontent.com/assets/6797611/22395936/08be0746-e555-11e6-9d78-c44c5200cfde.jpg)

**Expected behaviour**: Video from retail legion from 28.01.2017:
https://www.youtube.com/watch?v=SLZZ0qTScyY

**Comment by Rushor** [comment]
that sounds like an easy fix for you (with the help of the wpp) would you like to do this @Teridan-dal-wow ? :)

**Comment by Teridan-dal-wow** [comment]
Working one other report, almost done.

**Comment by Teridan-dal-wow** [comment]
What i did so far for this report:
- spawned the creatures
- added dead emote and hp bar to show = dead
``` sql
SET @CGUID := 5004725;
DELETE FROM `creature` WHERE `guid` BETWEEN @CGUID+0 AND @CGUID+3;
INSERT INTO `creature` (`guid`, `id`, `map`, `zoneId`, `areaId`, `spawnMask`, `phaseMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `VerifiedBuild`) VALUES
(@CGUID+0, 30881, 571, 0, 0, 1, 1, 0, 0, 7483.364, -1855.742, 1474.344, 4.363323, 120, 0, 0, 0, 0, 0, 0, 0, 32, 23420),
(@CGUID+1, 30881, 571, 0, 0, 1, 1, 0, 0, 7501.811, -1849.362, 1474.344, 4.834562, 120, 0, 0, 0, 0, 0, 0, 0, 32, 23420),
(@CGUID+2, 30881, 571, 0, 0, 1, 1, 0, 0, 7458.983, -1928.875, 1474.344, 4.468043, 120, 0, 0, 0, 0, 0, 0, 0, 32, 23420),
(@CGUID+3, 30881, 571, 0, 0, 1, 1, 0, 0, 7506.01, -1923.566, 1473.698, 1.256637, 120, 0, 0, 0, 0, 0, 0, 0, 32, 23420);
DELETE FROM `creature_addon` WHERE `guid` BETWEEN @CGUID+0 AND @CGUID+3;
INSERT INTO `creature_addon` (`guid`, `path_id`, `mount`, `bytes1`, `bytes2`, `emote`, `auras`) VALUES
(@CGUID+0, 0, 0, 7, 0, 65, 0),
(@CGUID+1, 0, 0, 7, 0, 65, 0),
(@CGUID+2, 0, 0, 7, 0, 65, 0),
(@CGUID+3, 0, 0, 7, 0, 65, 0);
```
Still wondering around how to make them:
- passive towards everyone around them
- unattackable by anyone

**Comment by Rushor** [comment]
> Still wondering around how to make them: passive towards everyone around them + unattackable by anyone

add unit_flags in the creature_template (remember to copy the existing unitflag from the creature_template)

in this example it would be
32768+256+512+8 https://trinitycore.atlassian.net/wiki/display/tc/creature_template#creature_template-unit_flags

**Comment by Teridan-dal-wow** [comment]
Done.

**Comment by Rushor** [comment]
DB/Creature: Servant of Hodir -- Add missing spawns and emotes

* closes: https://github.com/dalaranwow/dalaran-wow/issues/4346
* thanks to Teridan
* commit: fc0062dc807806356222de835ab6ee80de3b9c67

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by Teridan-dal-wow** [comment]
I was thinking about adding 512 but considering there aren't any npcs around, i didn't, my bad.
128, i don't fully understand what it does?
32768 Hm...what? Only swim?

**Comment by Teridan-dal-wow** [comment]
Also i would like to add that `minlevel = 60` and `maxlevel =76`  in `creature_template` are not correct. Proof:
![wowscrnshot_021217_203737](https://cloud.githubusercontent.com/assets/6797611/22864974/8dbb0a56-f163-11e6-99aa-4b06301e88f2.jpg)
![wowscrnshot_021217_203735](https://cloud.githubusercontent.com/assets/6797611/22864975/8dbb3df0-f163-11e6-8e4f-041587271b5b.jpg)
![wowscrnshot_021217_203728](https://cloud.githubusercontent.com/assets/6797611/22864977/8dbd031a-f163-11e6-9546-d21b5e8b347b.jpg)
![wowscrnshot_021217_203742](https://cloud.githubusercontent.com/assets/6797611/22864976/8dbcd34a-f163-11e6-9169-a724c1a81ad8.jpg)
I can't really find any data besides wowhead comment of saying "I saw one that was level 7, right next to one that was level 70. I'm guessing their levels are picked at random.".
So my suggestion is:
``` sql
UPDATE `creature_template` SET `minlevel` = 1 , `maxlevel` = 80 , WHERE `entry` = 30881;
```

**Comment by Rushor** [comment]
128 does this: UNIT_FLAG_NOT_ATTACKABLE_1

and yeah 32768 was the unit-flag that was already in the creature_template from previous sniffs from retail version 3.3.5. if it was already set like that in the past we should not remove it :)

**Comment by Rushor** [comment]
some more info on what fields can be changed and what not (if you don't want to hackfix) https://trinitycore.atlassian.net/wiki/display/tc/World

I know unit_flags is not listed there, just wanna let you know for the future

**Comment by Rushor** [comment]
DB/Creature: Servant of Hodir - Update levelrange

* updates: https://github.com/dalaranwow/dalaran-wow/issues/4346
* commit: 19d97776a9ef0fcd9cb3076f9b2a34d3779ffcb5
