### ISSUE TITLE
[NPC][QUEST][WotlK] Hyldsmeet Proto-Drake and "The Drakkensryd", missing paths

### ISSUE THREAD

**Issue by Teridan-dal-wow** [dalaranwow/dalaran-wow#4349]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Part 1: Npc Hyldsmeet Proto-Drake http://wotlk.openwow.com/npc=29625 is missing all of its paths. Area relevent to this report:
![wowscrnshot_012817_131418](https://cloud.githubusercontent.com/assets/6797611/22396230/985df986-e55c-11e6-888c-947c59a0f8d4.jpg)

Part 2: A player can "mount up" the drakes even without having the quest The Drakkensryd http://wotlk.openwow.com/quest=12886 , this should not be possible.
On server:
![wowscrnshot_012817_131305](https://cloud.githubusercontent.com/assets/6797611/22396298/c8de52c6-e55d-11e6-9eba-17205cdea4ac.jpg)
On retail:
![wowscrnshot_012817_133038](https://cloud.githubusercontent.com/assets/6797611/22396309/0576db72-e55e-11e6-81e3-17e0cb06a30e.jpg)

Part 3: There is a strange issue with the riders of the drakes, as they appear when you look from specific angle (video of what i mean):
https://www.youtube.com/watch?v=Hk55XfxPvwI

**Expected behaviour**: Video from retail from 28.01.2017:
https://www.youtube.com/watch?v=_xfdWFQbqZU

Other retail videos of quest The Drakkensryd:
https://www.youtube.com/watch?v=oCcyIi7sqZE
https://www.youtube.com/watch?v=iOsSlNdcvb4
https://www.youtube.com/watch?v=ThoMdRcTucg

Related to #388 and #4348

**Comment by Teridan-dal-wow** [comment]
Note: TC has the paths for all drakes around the temple working very well.

**Comment by Rushor** [comment]
Hm yeah, that works on PTR aswell, i will reassign the pathing then

**Comment by Rushor** [comment]
DB/Creature: Hyldsmeet Proto-Drake and quest "The Drakkensryd" - Add better questscript + reassign paths 

* closes: https://github.com/dalaranwow/dalaran-wow/issues/4349
* commit: b87df5896e797895420a165d6c6903488a60bcaf

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by TeridanDW** [comment]
Npc http://wotlk.openwow.com/npc=29754 should be flyer
``` sql
UPDATE `creature_template` SET `InhabitType` = 4 WHERE `entry` = 29754; 
```
Is everything from TC regarding this quest added in this commit? 
 - in particular when player accepts the quest he is mounted on drake and when that drake reaches the top of the temple it starts to fly around it with the other drakes.
 - (that's not working on TC) currently when the player uses the hook to get to other drake, the npc on that drake doesn't engage the player first and when the player attacks it, it doesn't fight back (auto attack).

**Comment by Rushor** [comment]
it's a flyer yes and everything from tc + a few own corrections were added. howver the part "..when that drake reaches the top of the temple it starts to fly around it with the other drakes..." is not working correctly. we could add it if we get correct paths for it :)

**Comment by TeridanDW** [comment]
What do you mean, that worked on TC?

**Comment by Rushor** [comment]
the part: "...when player accepts the quest he is mounted on drake.." + the drake flys on top of the temple -  this works on ptr now
