### ISSUE TITLE
[NPC][WotlK] Stormforged Artificer and Mechagnome Laborer, missing spawns/paths/emotes

### ISSUE THREAD

**Issue by Teridan-dal-wow** [dalaranwow/dalaran-wow#4350]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Npc Stormforged Artificer http://wotlk.openwow.com/npc=29376 is missing few spawns and paths, npc Mechagnome Laborer http://wotlk.openwow.com/npc=29389 is missing few spawns and emotes for all. 
![wowscrnshot_012817_140258](https://cloud.githubusercontent.com/assets/6797611/22396511/f49e8664-e563-11e6-9ba1-0761780bef8e.jpg)
![wowscrnshot_012817_140312](https://cloud.githubusercontent.com/assets/6797611/22396512/f5e569e8-e563-11e6-95b8-7047f4da60e2.jpg)
![wowscrnshot_012817_140742](https://cloud.githubusercontent.com/assets/6797611/22396513/f79dbd44-e563-11e6-9de1-967fc681aea9.jpg)
![wowscrnshot_012817_140942](https://cloud.githubusercontent.com/assets/6797611/22396514/f9c5ef10-e563-11e6-9bdb-4ac8c08bfd66.jpg)

**Expected behaviour**: Video from retail legion from 28.01.2017:
https://www.youtube.com/watch?v=xK2mFp6OPdk
Note: The emote of Mechagnome Laborer should be done all the time, on the video its visual bug (once i zone out and in the area they will start to do it again).

**Comment by Teridan-dal-wow** [comment]
Ok this is what got so far:
- added the missing spawns,
- added the missing emotes,
- removed the offhand weapon (no idea why they had one, on retail there isn't 2-nd weapon),
- "tryed" to add the path.

``` sql
UPDATE `creature_equip_template` SET `ItemID2` = 0 WHERE `CreatureID` = 29389 AND `ID` = 1; 
SET @CGUID := 5004718;
DELETE FROM `creature` WHERE `guid` BETWEEN @CGUID+0 AND @CGUID+4;
INSERT INTO `creature` (`guid`, `id`, `map`, `zoneId`, `areaId`, `spawnMask`,`phaseMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `VerifiedBuild`) VALUES
(@CGUID+0, 29389, 571, 0, 0, 1, 1, 0, 0, 7293.587, -470.1617, 813.5577, 4.537856, 300, 0, 0, 0, 0, 0, 0, 0, 0, 23420),
(@CGUID+1, 29389, 571, 0, 0, 1, 1, 0, 0, 7293.417, -488.4973, 808.6491, 1.692969, 300, 0, 0, 0, 0, 0, 0, 0, 0, 23420),
(@CGUID+2, 29389, 571, 0, 0, 1, 1, 0, 0, 7304.67, -420.914, 828.00, 1.239184, 300, 0, 0, 0, 0, 0, 0, 0, 0, 23420),
(@CGUID+3, 29389, 571, 0, 0, 1, 1, 0, 0, 7281.28, -554.9857, 790.8633, 1.623156, 300, 0, 0, 0, 0, 0, 0, 0, 0, 23420),
(@CGUID+4, 29389, 571, 0, 0, 1, 1, 0, 0, 7344.75, -583.0433, 784.5452, 6.178465, 300, 0, 0, 0, 0, 0, 0, 0, 0, 23420);
SET @CGUID := 5004723;
DELETE FROM `creature` WHERE `guid` BETWEEN @CGUID+0 AND @CGUID+1;
INSERT INTO `creature` (`guid`, `id`, `map`, `zoneId`, `areaId`, `spawnMask`,`phaseMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `VerifiedBuild`) VALUES
(@CGUID+0, 29376, 571, 0, 0, 1, 1, 0, 0, 7301.355, -600.3701, 785.4073, 2.939438, 300, 10, 0, 0, 0, 1, 0, 0, 0, 23420),
(@CGUID+1, 29376, 571, 0, 0, 1, 1, 0, 0, 7298.605, -707.8301, 791.0391, 0.08726646, 300, 0, 0, 0, 0, 0, 0, 0, 0, 23420);
SET @CGUID := 5004718;
DELETE FROM `creature_addon` WHERE `guid` BETWEEN @CGUID+0 AND @CGUID+4;
INSERT INTO `creature_addon` (`guid`, `path_id`, `mount`, `bytes1`, `bytes2`, `emote`, `auras`) VALUES
(@CGUID+0, 0, 0, 0, 0, 173, 0),
(@CGUID+1, 0, 0, 0, 0, 173, 0),
(@CGUID+2, 0, 0, 0, 0, 173, 0),
(@CGUID+3, 0, 0, 0, 0, 173, 0),
(@CGUID+4, 0, 0, 0, 0, 173, 0);
DELETE FROM `creature_addon` WHERE `guid` = 115103; 
DELETE FROM `creature_addon` WHERE `guid` = 115137;
DELETE FROM `creature_addon` WHERE `guid` = 115138;
DELETE FROM `creature_addon` WHERE `guid` = 115166;
DELETE FROM `creature_addon` WHERE `guid` = 115146;
DELETE FROM `creature_addon` WHERE `guid` = 115105;
INSERT INTO `creature_addon` (`guid`, `path_id`, `mount`, `bytes1`, `bytes2`, `emote`, `auras`) VALUES
(115103, 0, 0, 0, 0, 173, 0),
(115137, 0, 0, 0, 0, 173, 0),
(115138, 0, 0, 0, 0, 173, 0),
(115166, 0, 0, 0, 0, 173, 0),
(115146, 0, 0, 0, 0, 173, 0),
(115105, 0, 0, 0, 0, 173, 0);
SET @NPC := 114076;
SET @PATH := @NPC * 30;
UPDATE `creature` SET `spawndist`=0,`MovementType`=2,`position_x`=7314.199,`position_y`=-551.4256,`position_z`=790.2863 WHERE `guid`=@NPC;
DELETE FROM `creature_addon` WHERE `guid`=@NPC;
INSERT INTO `creature_addon` (`guid`,`path_id`,`mount`,`bytes1`,`bytes2`,`emote`,`auras`) VALUES (@NPC,@PATH,0,0,1,0, '');
DELETE FROM `waypoint_data` WHERE `id`=@PATH;
INSERT INTO `waypoint_data` (`id`,`point`,`position_x`,`position_y`,`position_z`,`orientation`,`delay`,`move_type`,`action`,`action_chance`,`wpguid`) VALUES
(@PATH,1,7314.199,-551.4256,790.2863,0,0,0,0,100,0), -- 17:49:44
(@PATH,2,7314.155,-533.1339,795.4913,0,0,0,0,100,0), -- 17:49:50
(@PATH,3,7314.24,-515.4728,800.0459,0,0,0,0,100,0), -- 17:49:58
(@PATH,4,7314.282,-496.5888,805.4148,0,0,0,0,100,0), -- 17:50:06
(@PATH,5,7314.319,-496.879,804.9178,0,0,0,0,100,0), -- 17:50:20
(@PATH,6,7314.247,-515.4914,800.1111,0,0,0,0,100,0), -- 17:50:32
(@PATH,7,7314.142,-533.0886,795.3215,0,0,0,0,100,0), -- 17:50:40
(@PATH,8,7314.213,-536.0686,794.3182,0,0,0,0,100,0), -- 17:50:47
(@PATH,9,7314.286,-551.5284,790.1588,0,0,0,0,100,0), -- 17:50:55
(@PATH,10,7314.396,-564.356,786.7234,0,0,0,0,100,0), -- 17:51:00
(@PATH,11,7314.272,-564.4451,786.4498,0,0,0,0,100,0), -- 17:51:04
(@PATH,12,7314.262,-564.0789,786.9169,0,0,0,0,100,0), -- 17:51:07
(@PATH,13,7314.447,-551.2629,790.3757,0,0,0,0,100,0), -- 17:51:12
(@PATH,14,7314.164,-533.2013,795.3361,0,0,0,0,100,0), -- 17:51:18
(@PATH,15,7314.244,-515.594,800.0362,0,0,0,0,100,0), -- 17:51:26
(@PATH,16,7314.288,-496.711,805.4045,0,0,0,0,100,0), -- 17:51:35
(@PATH,17,7314.319,-496.879,804.9178,0,0,0,0,100,0), -- 17:51:48
(@PATH,18,7314.248,-515.4978,800.2227,0,0,0,0,100,0), -- 17:52:00
(@PATH,19,7314.139,-533.0303,795.4509,0,0,0,0,100,0), -- 17:52:09
(@PATH,20,7314.211,-536.2501,794.4503,0,0,0,0,100,0), -- 17:52:16
(@PATH,21,7314.271,-551.5024,790.1894,0,0,0,0,100,0), -- 17:52:22
(@PATH,22,7314.394,-564.5654,786.5979,0,0,0,0,100,0), -- 17:52:28
(@PATH,23,7314.272,-564.4451,786.4498,0,0,0,0,100,0), -- 17:52:33
(@PATH,24,7314.229,-564.3193,786.8964,0,0,0,0,100,0), -- 17:52:34
(@PATH,25,7314.199,-551.2913,790.5046,0,0,0,0,100,0), -- 17:52:40
(@PATH,26,7314.156,-533.1941,795.4749,0,0,0,0,100,0), -- 17:52:46
(@PATH,27,7314.239,-515.5245,800.0317,0,0,0,0,100,0), -- 17:52:54
(@PATH,28,7314.291,-496.7062,805.2924,0,0,0,0,100,0), -- 17:53:03
(@PATH,29,7314.319,-496.879,804.9178,0,0,0,0,100,0), -- 17:53:17
(@PATH,30,7314.246,-515.4983,800.2458,0,0,0,0,100,0); -- 17:53:28
```
Now about the path i sniffed it 4 times just to be sure and i still get the same result which is:
![wowscrnshot_021217_181154](https://cloud.githubusercontent.com/assets/6797611/22863783/1667a220-f14f-11e6-9250-214fe4c910cf.jpg)

And on the waypost creator i got strange "picture" even though the npc is walking in a straight line only:
![image](https://cloud.githubusercontent.com/assets/6797611/22863796/3c150a1c-f14f-11e6-9aeb-d2f067747c7d.png)
Sniff from the picture above in main folder named "31".

**Comment by Rushor** [comment]
> P.S. I know in this case its easier to add the wps manually but i would like to learn how to do it with sniffs for more complicated and long paths.

You need to sort out the unneeded point. mark them in the editor and use 'cut' to remove them. it will automatically reoder the point order

**Comment by Rushor** [comment]
> DELETE FROM `creature_addon` WHERE `guid` = 115103; 

instead o coping that over and over you can use:

```sql
DELETE FROM `creature_addon` WHERE `guid`  IN (115103, 115138, xxx);
```

and yeah adding wps is a lot of work, every time you need to recheck all points, remove or add unneeded/needed points

**Comment by Rushor** [comment]
but always keep in mind it's just emulation, it can never be exactly like on retail :)

**Comment by Rushor** [comment]
DB/Creature: Stormforged Artificer and Mechagnome Laborer - Add missing spawns/paths/emotes

* closes: https://github.com/dalaranwow/dalaran-wow/issues/4350
* thanks to Teridan
* commit: 8882619a04689ad2805c2dcc840c1acb3121fb0b

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by Teridan-dal-wow** [comment]
> but always keep in mind it's just emulation, it can never be exactly like on retail :)

But it can be as close as possible. :)

**Comment by Teridan-dal-wow** [comment]
Think in this report i made a mistake because i get a database error, this should fix it:
``` sql
UPDATE `creature_addon` SET `auras` = '' WHERE `guid` IN (135117, 115137, 5004718, 5004719, 5004720, 115103, 5004721, 5004722, 115138, 115166, 115146, 115105, 5004725, 5004726, 5004727, 5004728);
DELETE FROM `creature_addon` WHERE `guid` IN (127005, 0);
```
auras were set to 0

**Comment by Rushor** [comment]
DB/Creature: Stormforged Artificer and Mechagnome Laborer - Remove creature_addon aura error

* updates: https://github.com/dalaranwow/dalaran-wow/issues/4350
* commit: 780a2ff02e9043d251a76720448e7fa1d40c1e2d

Added, ty!
