### ISSUE TITLE
[NPC][WotlK] Mechagnome Attendant, missing spawn

### ISSUE THREAD

**Issue by Teridan-dal-wow** [dalaranwow/dalaran-wow#4352]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Part 1: Npc Mechagnome Attendant http://wotlk.openwow.com/npc=30170 has few missing spawns with emote here:
![wowscrnshot_012817_152516](https://cloud.githubusercontent.com/assets/6797611/22396978/572c7f16-e56e-11e6-9adc-d9c2bed890c1.jpg)

Part 2: Gameobject "Fire" is missing (on the right side) and gameobject "anvil" has the wrong direction.

**Expected behaviour**: Video from retail legion from 28.01.2017:
https://www.youtube.com/watch?v=srvoX6vT78M

**Comment by Teridan-dal-wow** [comment]
Corrected the wrong position of Attendant Tock http://wotlk.openwow.com/npc=30190 and 2 models to match the colors on retail, also added the missing spawns with the proper colors:
``UPDATE `world`.`creature` SET `position_x` = '8266.42' , `position_y` = '-437.11' , `position_z` = '970.68' , `orientation` = '4.223697' WHERE `guid` = '6337'; ``

``UPDATE `world`.`creature` SET `modelid` = '24109' WHERE `guid` = '116766'; ``

``UPDATE `world`.`creature` SET `modelid` = '24109' WHERE `guid` = '116775'; ``

``INSERT INTO `world`.`creature` (`guid`, `id`, `map`, `zoneId`, `areaId`, `spawnMask`, `phaseMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `VerifiedBuild`) VALUES ('165617', '30170', '571', '0', '0', '1', '1', '24109', '0', '8235.30', '-467.78', '970.81', '5.497787', '300', '0', '0', '11770', '3809', '0', '0', '0', '0', '0'); ``

``INSERT INTO `world`.`creature` (`guid`, `id`, `map`, `zoneId`, `areaId`, `spawnMask`, `phaseMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `VerifiedBuild`) VALUES ('165618', '30170', '571', '0', '0', '1', '1', '24103', '0', '8280.50', '-458.18', '970.81', '5.375614', '300', '0', '0', '11770', '3809', '0', '0', '0', '0', '0'); ``

``INSERT INTO `world`.`creature` (`guid`, `id`, `map`, `zoneId`, `areaId`, `spawnMask`, `phaseMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `VerifiedBuild`) VALUES ('165619', '30170', '571', '0', '0', '1', '1', '24121', '0', '8256.40', '-427.76', '975.94', '4.18879', '300', '0', '0', '11770', '3809', '0', '0', '0', '0', '0'); ``

``INSERT INTO `world`.`creature` (`guid`, `id`, `map`, `zoneId`, `areaId`, `spawnMask`, `phaseMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `VerifiedBuild`) VALUES ('165620', '30170', '571', '0', '0', '1', '1', '24121', '0', '8276.78', '-439.93', '970.81', '6.143559', '300', '0', '0', '11770', '3809', '0', '0', '0', '0', '0'); ``

``INSERT INTO `world`.`creature` (`guid`, `id`, `map`, `zoneId`, `areaId`, `spawnMask`, `phaseMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `VerifiedBuild`) VALUES ('165621', '30170', '571', '0', '0', '1', '1', '24121', '0', '8255.53', '-427.16', '975.87', '4.18879', '300', '0', '0', '11770', '3809', '0', '0', '0', '0', '0'); ``

``INSERT INTO `world`.`creature` (`guid`, `id`, `map`, `zoneId`, `areaId`, `spawnMask`, `phaseMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `VerifiedBuild`) VALUES ('165622', '30170', '571', '0', '0', '1', '1', '24121', '0', '8254.60', '-426.66', '975.87', '4.29351', '300', '0', '0', '11770', '3809', '0', '0', '0', '0', '0'); ``

Also i would like to ask if its ok if the anvil is fixed manually or we are waiting for general fix for all issues of that kind?

P.S. How you i post code and look good like most people on TC do?

**Comment by Rushor** [comment]
we don't put '' around number + use this

```sql
INSERT INTO ...

and again with  ``` at the end for posting sqls

**Comment by Rushor** [comment]
> Also i would like to ask if its ok if the anvil is fixed manually or we are waiting for general fix for all issues of that kind?

general stuff that will get fixed once https://github.com/TrinityCore/TrinityCore/commit/2967bf59b4a47837b85c995b732a6761c9c35f7e was merged

**Comment by Teridan-dal-wow** [comment]
Thank you, will fix the look tomorrow and add the fire.

**Comment by Teridan-dal-wow** [comment]
Does this look better?

``` sql
UPDATE `creature` SET `position_x` = 8266.42 , `position_y` = -437.11 , `position_z` = 970.68 , `orientation` = 4.223697 WHERE `guid` = 6337;
UPDATE `creature` SET `modelid` = 24109 WHERE `guid` = 116766;
UPDATE `creature` SET `modelid` = 24109 WHERE `guid` = 116775;
DELETE FROM `creature` WHERE `guid`=500000;
INSERT INTO `creature` (`guid`, `id`, `map`, `zoneId`, `areaId`, `spawnMask`, `phaseMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `VerifiedBuild`) VALUES (500000, 30170, 571, 0, 0, 1, 1, 24109, 0, 8235.30, -467.78, 970.81, 5.497787, 300, 0, 0, 11770, 3809, 0, 0, 0, 0, 0);
DELETE FROM `creature` WHERE `guid`=500001;
INSERT INTO `creature` (`guid`, `id`, `map`, `zoneId`, `areaId`, `spawnMask`, `phaseMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `VerifiedBuild`) VALUES (500001, 30170, 571, 0, 0, 1, 1, 24103, 0, 8280.50, -458.18, 970.81, 5.375614, 300, 0, 0, 11770, 3809, 0, 0, 0, 0, 0);
DELETE FROM `creature` WHERE `guid`=500002;
INSERT INTO `creature` (`guid`, `id`, `map`, `zoneId`, `areaId`, `spawnMask`, `phaseMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `VerifiedBuild`) VALUES (500002, 30170, 571, 0, 0, 1, 1, 24121, 0, 8256.40, -427.76, 975.94, 4.18879, 300, 0, 0, 11770, 3809, 0, 0, 0, 0, 0);
DELETE FROM `creature` WHERE `guid`=500003;
INSERT INTO `creature` (`guid`, `id`, `map`, `zoneId`, `areaId`, `spawnMask`, `phaseMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `VerifiedBuild`) VALUES (500003, 30170, 571, 0, 0, 1, 1, 24121, 0, 8276.78, -439.93, 970.81, 6.143559, 300, 0, 0, 11770, 3809, 0, 0, 0, 0, 0);
DELETE FROM `creature` WHERE `guid`=500004;
INSERT INTO `creature` (`guid`, `id`, `map`, `zoneId`, `areaId`, `spawnMask`, `phaseMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `VerifiedBuild`) VALUES (500004, 30170, 571, 0, 0, 1, 1, 24121, 0, 8255.53, -427.16, 975.87, 4.18879, 300, 0, 0, 11770, 3809, 0, 0, 0, 0, 0);
DELETE FROM `creature` WHERE `guid`=500005;
INSERT INTO `creature` (`guid`, `id`, `map`, `zoneId`, `areaId`, `spawnMask`, `phaseMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `VerifiedBuild`) VALUES (500005, 30170, 571, 0, 0, 1, 1, 24121, 0, 8254.60, -426.66, 975.87, 4.29351, 300, 0, 0, 11770, 3809, 0, 0, 0, 0, 0);

```

Also i would like to ask if i can (when inserting creature/object) to skip the columns that i don't want to edit (so they can use their default values) ?
Is it correct to have separate line for each DELETE FROM and INSERT INTO if they are the same creatures/objects as the ones above?

**Comment by Rushor** [comment]
that is better, but i suggest to post it like that:

```sql
SET @CGUID := 5004712;
DELETE FROM `creature` WHERE `guid` BETWEEN @CGUID+0 AND @CGUID+5;
INSERT INTO `creature` (`guid`, `id`, `map`, `zoneId`, `areaId`, `spawnMask`, `phaseMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `VerifiedBuild`) VALUES 
(@CGUID+0, 30170, 571, 0, 0, 1, 1, 24109, 0, 8235.30, -467.78, 970.81, 5.497787, 300, 0, 0, 11770, 3809, 0, 0, 0, 0, 0),
(@CGUID+1, 30170, 571, 0, 0, 1, 1, 24103, 0, 8280.50, -458.18, 970.81, 5.375614, 300, 0, 0, 11770, 3809, 0, 0, 0, 0, 0),
(@CGUID+2, 30170, 571, 0, 0, 1, 1, 24121, 0, 8256.40, -427.76, 975.94, 4.18879, 300, 0, 0, 11770, 3809, 0, 0, 0, 0, 0),
(@CGUID+3, 30170, 571, 0, 0, 1, 1, 24121, 0, 8276.78, -439.93, 970.81, 6.143559, 300, 0, 0, 11770, 3809, 0, 0, 0, 0, 0),
(@CGUID+4, 30170, 571, 0, 0, 1, 1, 24121, 0, 8255.53, -427.16, 975.87, 4.18879, 300, 0, 0, 11770, 3809, 0, 0, 0, 0, 0),
(@CGUID+5, 30170, 571, 0, 0, 1, 1, 24121, 0, 8254.60, -426.66, 975.87, 4.29351, 300, 0, 0, 11770, 3809, 0, 0, 0, 0, 0);
```

so we define the guids with SET @CGUID := 5004712; (5004712, because other guids are already in use)

With those definitions we dont't need to update all guids, but instead only the first one.

Moreover if we spawn several creatures you only need to put:

```sql
INSERT INTO `creature` (`guid`, `id`, `map`, `zoneId`, `areaId`, `spawnMask`, `phaseMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `VerifiedBuild`) VALUES 
```
one time on top, not for every creature :)

Everything else is fine!

**Comment by Rushor** [comment]
ah btw, you can get an easy output for those sqls (if you spawn creatures) if you use the https://github.com/TrinityCore/WowPacketParser If you setup the config in the release folder correctly it will generate a sql for all objects that were sniffed.

in the sniff you posted it would look like this:

```sql
# TrinityCore - WowPacketParser
# File name: Mechagnome Attendant --23420_2017-01-28_15-24-03.pkt
# Detected build: V7_1_5_23420
# Detected locale: enUS
# Targeted database: WrathOfTheLichKing
# Parsing date: 02/12/2017 12:34:39

DELETE FROM `creature` WHERE `guid` BETWEEN @CGUID+0 AND @CGUID+14;
INSERT INTO `creature` (`guid`, `id`, `map`, `zoneId`, `areaId`, `spawnMask`, `phaseMask`, `PhaseGroup`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `VerifiedBuild`) VALUES
(@CGUID+0, 30170, 571, 0, 0, 1, 1, 0, 0, 0, 8320.115, -562.2943, 982.0875, 3.682645, 120, 0, 0, 0, 0, 0, 0, 0, 0, 23420), -- Mechagnome Attendant (Area: -Unknown-)
(@CGUID+1, 30170, 571, 0, 0, 1, 1, 0, 0, 0, 8340.337, -553.6027, 982.0875, 0.418879, 120, 0, 0, 0, 0, 0, 0, 0, 0, 23420), -- Mechagnome Attendant (Area: -Unknown-)
(@CGUID+2, 30170, 571, 0, 0, 1, 1, 0, 0, 0, 8310.562, -513.3287, 982.0876, 1.500983, 120, 0, 0, 0, 0, 0, 0, 0, 0, 23420), -- Mechagnome Attendant (Area: -Unknown-)
(@CGUID+3, 30170, 571, 0, 0, 1, 1, 0, 0, 0, 8305.598, -541.0457, 982.0876, 4.258604, 120, 0, 0, 0, 0, 0, 0, 0, 0, 23420), -- Mechagnome Attendant (Area: -Unknown-)
(@CGUID+4, 30170, 571, 0, 0, 1, 1, 0, 0, 0, 8280.492, -458.1798, 970.8063, 5.375614, 120, 0, 0, 0, 0, 0, 0, 0, 0, 23420), -- Mechagnome Attendant (Area: -Unknown-)
(@CGUID+5, 30170, 571, 0, 0, 1, 1, 0, 0, 0, 8276.771, -439.9294, 970.8063, 6.143559, 120, 0, 0, 0, 0, 0, 0, 0, 0, 23420), -- Mechagnome Attendant (Area: Mimir's Workshop)
(@CGUID+6, 30170, 571, 0, 0, 1, 1, 0, 0, 0, 8256.393, -427.7562, 975.9382, 4.18879, 120, 0, 0, 0, 0, 0, 0, 0, 0, 23420), -- Mechagnome Attendant (Area: Mimir's Workshop)
(@CGUID+7, 30170, 571, 0, 0, 1, 1, 0, 0, 0, 8235.307, -467.7742, 970.8063, 5.497787, 120, 0, 0, 0, 0, 0, 0, 0, 0, 23420), -- Mechagnome Attendant (Area: Mimir's Workshop)
(@CGUID+8, 30190, 571, 0, 0, 1, 1, 0, 0, 0, 8266.422, -437.1101, 970.6813, 4.223697, 120, 0, 0, 0, 0, 0, 0, 0, 0, 23420), -- Attendant Tock (Area: Mimir's Workshop)
(@CGUID+9, 30170, 571, 0, 0, 1, 1, 0, 0, 0, 8255.535, -427.159, 975.8688, 4.18879, 120, 0, 0, 0, 0, 0, 0, 0, 0, 23420), -- Mechagnome Attendant (Area: Mimir's Workshop)
(@CGUID+10, 30170, 571, 0, 0, 1, 1, 0, 0, 0, 8254.598, -426.665, 975.8688, 4.29351, 120, 0, 0, 0, 0, 0, 0, 0, 0, 23420), -- Mechagnome Attendant (Area: Mimir's Workshop)
(@CGUID+11, 29424, 571, 0, 0, 1, 1, 0, 0, 0, 8157.537, -313.0399, 960.6993, 0.4014257, 120, 0, 0, 0, 0, 0, 0, 0, 0, 23420), -- Stormforged Lightning Target (Area: Mimir's Workshop) (Auras: )
(@CGUID+12, 29424, 571, 0, 0, 1, 1, 0, 0, 0, 8117.354, -340.2348, 962.35, 3.543018, 120, 0, 0, 0, 0, 0, 0, 0, 0, 23420), -- Stormforged Lightning Target (Area: Mimir's Workshop)
(@CGUID+13, 29424, 571, 0, 0, 1, 1, 0, 0, 0, 8121.007, -332.3373, 1017.364, 0.01745329, 120, 0, 0, 0, 0, 0, 0, 0, 0, 23420), -- Stormforged Lightning Target (Area: Mimir's Workshop) (Auras: )
(@CGUID+14, 29424, 571, 0, 0, 1, 1, 0, 0, 0, 8088.429, -359.6336, 988.0741, 4.34587, 120, 0, 0, 0, 0, 0, 0, 0, 0, 23420); -- Stormforged Lightning Target (Area: Mimir's Workshop)
DELETE FROM `creature_addon` WHERE `guid` BETWEEN @CGUID+0 AND @CGUID+14;
INSERT INTO `creature_addon` (`guid`, `path_id`, `mount`, `bytes1`, `bytes2`, `emote`, `auras`) VALUES
(@CGUID+0, 0, 0, 7, 1, 0, ''), -- Mechagnome Attendant
(@CGUID+1, 0, 0, 7, 1, 0, ''), -- Mechagnome Attendant
(@CGUID+2, 0, 0, 7, 1, 0, ''), -- Mechagnome Attendant
(@CGUID+3, 0, 0, 7, 1, 0, ''), -- Mechagnome Attendant
(@CGUID+4, 0, 0, 7, 1, 0, ''), -- Mechagnome Attendant
(@CGUID+5, 0, 0, 7, 1, 0, ''), -- Mechagnome Attendant
(@CGUID+6, 0, 0, 7, 1, 0, ''), -- Mechagnome Attendant
(@CGUID+7, 0, 0, 7, 1, 0, ''), -- Mechagnome Attendant
(@CGUID+8, 0, 0, 0, 1, 0, ''), -- Attendant Tock
(@CGUID+9, 0, 0, 7, 1, 0, ''), -- Mechagnome Attendant
(@CGUID+10, 0, 0, 7, 1, 0, ''), -- Mechagnome Attendant
(@CGUID+11, 0, 0, 0, 1, 0, ''), -- Stormforged Lightning Target
(@CGUID+12, 0, 0, 0, 1, 0, ''), -- Stormforged Lightning Target
(@CGUID+13, 0, 0, 0, 1, 0, ''), -- Stormforged Lightning Target
(@CGUID+14, 0, 0, 0, 1, 0, ''); -- Stormforged Lightning Target

DELETE FROM `gameobject` WHERE `guid` BETWEEN @OGUID+0 AND @OGUID+11;
INSERT INTO `gameobject` (`guid`, `id`, `map`, `zoneId`, `areaId`, `spawnMask`, `phaseMask`, `PhaseGroup`, `position_x`, `position_y`, `position_z`, `orientation`, `rotation0`, `rotation1`, `rotation2`, `rotation3`, `spawntimesecs`, `animprogress`, `state`, `VerifiedBuild`) VALUES
(@OGUID+0, 191549, 571, 0, 0, 1, 1, 0, 8432.629, -213.3004, 825.5626, 3.054327, 0, 0, 0.9990482, 0.04361926, 120, 255, 0, 23420), -- Nidavelir Mole Machine (Area: -Unknown-)
(@OGUID+1, 191549, 571, 0, 0, 1, 1, 0, 8363.065, -207.4323, 846.0056, 3.961899, 0, 0, -0.9170599, 0.3987495, 120, 255, 0, 23420), -- Nidavelir Mole Machine (Area: -Unknown-)
(@OGUID+2, 192125, 571, 0, 0, 1, 1, 0, 8231.716, -451.4526, 968.3688, 3.176533, 0, 0, -0.9998474, 0.01746928, 120, 255, 1, 23420), -- Mimir's Anvil (Area: Mimir's Workshop)
(@OGUID+3, 192128, 571, 0, 0, 1, 1, 0, 8264.213, -432.4033, 975.7786, 1.134463, 0, 0, 0.5372992, 0.8433917, 120, 255, 1, 23420), -- Metal Bars (Area: Mimir's Workshop)
(@OGUID+4, 192128, 571, 0, 0, 1, 1, 0, 8281.357, -432.069, 970.723, 3.438303, 0, 0, -0.9890156, 0.1478114, 120, 255, 1, 23420), -- Metal Bars (Area: Mimir's Workshop)
(@OGUID+5, 192125, 571, 0, 0, 1, 1, 0, 8262.046, -430.2878, 968.2716, 4.206246, 0, 0, -0.8616285, 0.5075394, 120, 255, 1, 23420), -- Mimir's Anvil (Area: Mimir's Workshop)
(@OGUID+6, 192128, 571, 0, 0, 1, 1, 0, 8246.777, -424.7074, 970.723, 5.113817, 0, 0, -0.5519361, 0.8338864, 120, 255, 1, 23420), -- Metal Bars (Area: Mimir's Workshop)
(@OGUID+7, 192128, 571, 0, 0, 1, 1, 0, 8243.935, -429.881, 970.723, 5.201083, 0, 0, -0.5150375, 0.8571676, 120, 255, 1, 23420), -- Metal Bars (Area: Mimir's Workshop)
(@OGUID+8, 192126, 571, 0, 0, 1, 1, 0, 8206.017, -453.8472, 970.2606, 0.1396245, 0, 0, 0.06975555, 0.9975641, 120, 255, 1, 23420), -- Workshop Fire (Area: Mimir's Workshop)
(@OGUID+9, 192128, 571, 0, 0, 1, 1, 0, 8233.997, -434.3795, 970.723, 4.206246, 0, 0, -0.8616285, 0.5075394, 120, 255, 1, 23420), -- Metal Bars (Area: Mimir's Workshop)
(@OGUID+10, 192126, 571, 0, 0, 1, 1, 0, 8274.951, -404.6783, 968.8022, 4.572764, 0, 0, -0.7547092, 0.6560594, 120, 255, 1, 23420), -- Workshop Fire (Area: Mimir's Workshop)
(@OGUID+11, 192126, 571, 0, 0, 1, 1, 0, 8226.525, -410.5521, 970.4272, 5.235988, 0, 0, -0.5, 0.8660254, 120, 255, 1, 23420); -- Workshop Fire (Area: Mimir's Workshop)
DELETE FROM `gameobject_addon` WHERE `guid` BETWEEN @OGUID+0 AND @OGUID+11;

DELETE FROM `creature_template_addon` WHERE `entry`=29424;
INSERT INTO `creature_template_addon` (`entry`, `path_id`, `mount`, `bytes1`, `bytes2`, `emote`, `auras`) VALUES
(29424, 0, 0, 0, 1, 0, ''); -- 29424 (Stormforged Lightning Target)


DELETE FROM `creature_model_info` WHERE `DisplayID` IN (26241, 24121, 24115, 24103);
INSERT INTO `creature_model_info` (`DisplayID`, `BoundingRadius`, `CombatReach`, `Gender`, `DisplayID_Other_Gender`) VALUES
(26241, 0.375, 0.75, 0, UNKNOWN),
(24121, 0.31, 1, 2, UNKNOWN),
(24115, 0.465, 1.5, 2, UNKNOWN),
(24103, 5, 1, 2, UNKNOWN);
```

some stuff is useful, other is not useful, moreover `PhaseGroup` must be removed because `PhaseGroup` is for > wod content only. you decide what output is useful and what not :)

**Comment by Rushor** [comment]
DB/Creature: Mechagnome Attendant - Add missing creature and gameobject spawns and update models

* closes: https://github.com/dalaranwow/dalaran-wow/issues/4352
* thanks to Teridan
* commit: 7a558193d77695c5706d09f1ede37f62c473edfd

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by Teridan-dal-wow** [comment]
Thank you, thats very helpful tips!
