### ISSUE TITLE
Purchased an item in the donation shop and never received it in the mail.

### ISSUE THREAD

**Issue by Zibathy** [dalaranwow/dalaran-wow#4354]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

In my experience buying an item was instant, however in this case it was not. Now I think this problem lies somewhere between the completion of a transaction, the dalaran-wow website, and the game itself. I ordered two items (Red Wolf and Furor's bag) and never received them. I ordered them yesterday, gave you guys 42 bucks, and spent 21 of the 42 donation points. 

I believe the issue was spending the donation points before the donation was "registered" on the website. I doubt this would be seen if I posted it on the forum so I am putting it here. If you could tell me where to move this or, even better, help me, that would be great. I'm not spending any more of the donation points I have left until I know the system is working. 

Thank you

**Comment by MalkaviaDW** [comment]
Hello there, 

Write to the support email: dalaran.community@gmail.com, please.  And explain the situation there (including character's name). It will be solved as soon as possible.

Cheers!

**Comment by Zibathy** [comment]
Thank you so much. Sorry for cluttering up the bug reporter!
