### ISSUE TITLE
[EN][Stormwind][Object]Archbishop Alonsus Faol

### ISSUE THREAD

**Issue by TheRealestMcCoy** [dalaranwow/dalaran-wow#4356]
**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
The plaque on the fountain is sitting straigh up
**Expected behaviour**: Tell us what should happen instead
The plaque should be laid down flat on the fountain.
**Steps to reproduce the problem**:

1. GO to Stormwind to the Cathedral check plaque
2. 
3. 

**Include proofs for this behaviour**
How it looks.
![wowscrnshot_012917_010807](https://cloud.githubusercontent.com/assets/12252441/22402306/6c038f28-e5bf-11e6-85e1-69ffbf2c0ada.jpg)
![wowscrnshot_012917_011106](https://cloud.githubusercontent.com/assets/12252441/22402313/d9b3ef90-e5bf-11e6-9002-610121f731bf.jpg)

How it should look.
http://wow.zamimg.com/uploads/screenshots/normal/39925-archbishop-alonsus-faol.jpg
You can research this on several pages like http://wowhead.com or http://wowwiki.wikia.com or http://www.youtube.com/
Issues without proofs will be closed and tag On Hold will be added until the proof is provided.

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**
I think this is the right ID.
http://www.wowhead.com/object=177199/archbishop-alonsus-faol
You can research this on several pages like http://wotlk.openwow.com or http://wowhead.com/

**Include Screenshots from the issue if necessary**

**Comment by Rushor** [comment]
will be fixed once https://github.com/TrinityCore/TrinityCore/pull/14146 was merged on the live realm.
