### ISSUE TITLE
[NPC][WotlK] Tracker Thulin, missing emote

### ISSUE THREAD

**Issue by Teridan-dal-wow** [dalaranwow/dalaran-wow#4359]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: 
 - Part 1:
Npc Tracker Thulin http://wotlk.openwow.com/npc=29695 is missing an emote (he should be sitting) and is slightly in the wrong position.
![wowscrnshot_012917_110931](https://cloud.githubusercontent.com/assets/6797611/22403012/6f0b7628-e613-11e6-9dc3-f42113b130b6.jpg)
 - Part 2:
There should be a gameobject "bag" next to him, which should not be "clickable" by players. (its there just to improve the story of this quest http://wotlk.openwow.com/quest=12855 / http://wotlk.openwow.com/quest=12910 )
Proof: https://www.youtube.com/watch?v=aypXfa20lNI

On retail:
![wowscrnshot_012917_111826](https://cloud.githubusercontent.com/assets/6797611/22403052/b6b11c70-e614-11e6-81d4-802fd8ea306c.jpg)

**Expected behaviour**: Video from retail legion from 29.01.2017:
https://www.youtube.com/watch?v=ih_xz-Sny7w

**Comment by Teridan-dal-wow** [comment]
Hello, i have been digging around tc for the past few days and i wanted to try to fix something else, so after few hours of headaches i came up with this:
"Potential fix" for part 1 of this report -
``INSERT INTO `world`.`creature_addon` (`guid`, `bytes1`, `bytes2`, `emote`) VALUES ('152125', '1', '1', '13');``
 ``UPDATE` `world`.`creature` SET `position_x` = '7313.96' , `position_y` = '-1611.88' , `position_z` = '944.59' , `orientation` = '1.798' WHERE `guid` = '152125'``

Regarding part 2 of the report, i can't find the gameobject in the database, so i tried creating a new one using this information:
[0] UpdateType: CreateObject1
[0] Object Guid: Full: 0x2C3CD04760BB3B80000C1D000008E709 GameObject/0 R3892/S3101 Map: 571 Entry: 191726 Low: 583433
[0] Object Type: GameObject (5)
[0] NoBirthAnim: False
[0] EnablePortals: False
[0] PlayHoverAnim: False
[0] HasMovementUpdate: False
[0] HasMovementTransport: False
[0] Stationary: True
[0] HasCombatVictim: False
[0] HasServerTime: False
[0] HasVehicleCreate: False
[0] HasAnimKitCreate: False
[0] HasRotation: True
[0] HasAreaTrigger: False
[0] HasGameObject: False
[0] HasSmoothPhasing: False
[0] ThisIsYou: False
[0] SceneObjCreate: False
[0] HasPlayerCreateData: False
[0] PauseTimesCount: 0
[0] Stationary Position: X: 7312.415 Y: -1610.487 Z: 944.2941
[0] Stationary Orientation: 4.991644
[0] GameObject Rotation: X: 0 Y: 0 Z: -0.6018143 W: 0.7986361
[0] OBJECT_FIELD_GUID: 583433/8.175638E-40
[0] 1: 793856/1.112429E-39
[0] 2: 1622883200/1.079321E+20
[0] 3: 742182983/2.683202E-12
[0] OBJECT_FIELD_TYPE: 33/4.624285E-44
[0] OBJECT_FIELD_ENTRY: 191726/2.686653E-40
[0] OBJECT_DYNAMIC_FLAGS: 4294901760/NaN
[0] OBJECT_FIELD_SCALE_X: 1061158912/0.75
[0] GAMEOBJECT_DISPLAYID: 7678/1.075917E-41
[0] GAMEOBJECT_PARENTROTATION + 3: 1065353216/1
[0] GAMEOBJECT_BYTES_1: 4278191361/-1.701672E+38

But no object ever spawns for me. This is what i tried:
"guid"	"id"	"map"	"zoneId"	"areaId"	"spawnMask"	"phaseMask"	"position_x"	"position_y"	"position_z"	"orientation"	"rotation0"	"rotation1"	"rotation2"	"rotation3"	"spawntimesecs"	"animprogress"	"state"	"VerifiedBuild"
"191726"	"3"	"571"	"0"	"0"	"1"	"1"	"7312.41"	"-1610.49"	"944.294"	"4.99164"	"0"	"0"	"0"	"0"	"0"	"0"	"0"	"0"
And it clearly didn't work.

**Comment by Teridan-dal-wow** [comment]
Think i found my mistake. This should be the "potential fix" for part 2 of the report:

``INSERT INTO `world`.`gameobject` (`guid`, `id`, `map`, `zoneId`, `areaId`, `spawnMask`, `phaseMask`, `position_x`, `position_y`, `position_z`, `orientation`, `rotation0`, `rotation1`, `rotation2`, `rotation3`, `spawntimesecs`, `animprogress`, `state`, `VerifiedBuild`) VALUES ('191726', '191726', '571', '0', '0', '1', '1', '7312.41', '-1610.49', '944.294', '4.99164', '0', '0', '0', '0', '0', '0', '0', '0'); ``

**Comment by Rushor** [comment]
quick info how it should look like:

```sql
DELETE FROM `creature_addon` WHERE `guid`=152125;
INSERT INTO `creature_addon` (`guid`, `bytes1`, `bytes2`) VALUES (152125, 1, 1);
UPDATE `creature` SET `position_x` = 7313.96 , `position_y` = -1611.88 , `position_z` = 944.59 , `orientation` = 1.798 WHERE `guid` = 152125;
DELETE FROM `gameobject` WHERE `guid`=4000082;
INSERT INTO `gameobject` (`guid`, `id`, `map`, `zoneId`, `areaId`, `spawnMask`, `phaseMask`, `position_x`, `position_y`, `position_z`, `orientation`, `rotation0`, `rotation1`, `rotation2`, `rotation3`, `spawntimesecs`, `animprogress`, `state`, `VerifiedBuild`) VALUES
(4000082, 191726, 571, 0, 0, 1, 1, 7312.415, -1610.487, 944.2941, 4.991644, 0, 0, -0.6018143, 0.7986361, 120, 255, 1, 23420); 
```

so we don't put '' around every number + alsways add delete statements before insert + emote in creature_addon is not needed if you already use Bytes 1 with value 1 which defines sitting

if you have any queststions for further fixes let me know :)

**Comment by Rushor** [comment]
DB/Creature: Tracker Thulin- Add missing emote + gameobject

* closes: https://github.com/dalaranwow/dalaran-wow/issues/4359
* commit: 78d9425f7fbc5617b2111b1b852dd5488ee1c567

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by Teridan-dal-wow** [comment]
Thank you, got a question, why did you choose guid = 4000082  considering that last guid in gameobject table is 165990? Sorry if its stupid question, just starting and everything is new to me.

**Comment by Rushor** [comment]
we use high guid number to prevent further erros if we merge tc fixes in the dalaran-wow source
