### ISSUE TITLE
[ToC][Gormok] Rising Anger / Snobolds

### ISSUE THREAD

**Issue by plznoz** [dalaranwow/dalaran-wow#4366]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)

1. Rising Anger goes beyond 4 stacks, even if nobody dies with a Snobold on their back.
2. Snobolds that are on the back of a player that dies will walk around on the ground attacking highest threat AND won't cause another Rising Anger stack.

**Expected behaviour**: Tell us what should happen instead
1. If nobody dies with Snobold on their back, the Rising Anger stacks shouldn't go above 4 (one stack every time Gormok throws out a new Snobold).
2. Snobolds that kill a player should walk to boss and be thrown out again on another player and cause another Rising Anger stack (Can go higher than 4 this way).

**Steps to reproduce the problem**:

1. Engage Gormok
2. Kill all Snobolds without anyone dying
3. See that Rising anger stacks go beyond 4 afterwards.

**Include proofs for this behaviour**
[20:11:59.218] Gormok the Impaler gains Rising Anger (5) from Gormok the Impaler
http://www.worldoflogs.com/reports/ae66lwkb5pr3wabm/sum/damageDone/?s=103&e=535

#4365 
The issue referenced above has a video showing it.

Quoting wowhead comment:
http://www.wowhead.com/spell=66636/rising-anger#comments
> Each time Gormok the Impaler throws a snobold Rising Anger stacks 1 stack on him. Additionally if someone with a snobold on them dies that snobold runs back to the boss and then the boss throws it again which causes an additional stack of Rising Anger. If the person dies after Gormok is dead then the snobold jumps off and has to be tanked.

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**
http://wotlk.openwow.com/spell=66636 Rising Anger
http://wotlk.openwow.com/?search=gormok#npcs Gormok

**Include Screenshots from the issue if necessary**

**Comment by DarthGM** [comment]
This also means that using any immunity effect (BoP/Iceblock etc.) will drop the snobold to the ground and kind of trivialize this mechanic, as they don't need to be killed as quickly since they can just be offtanked by a plate dps etc.

**Comment by plznoz** [comment]
Last time I played mage and iceblocked, it didn't throw the snobold off my back (This was about a year ago)
In my experience they only go to the ground when people die while having them on their backs.

**Comment by Rushor** [comment]
Scripts/TrialOfTheCrusader: Gormok - Only use 4 Snobold

* closes: https://github.com/dalaranwow/dalaran-wow/issues/4366
* commit: 857b774f50870ff7f53a23d671fd1bc8417d33ec

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by Teridan-dal-wow** [comment]
Reference from retail of what should happen with snobolds when target uses immunity effect. Video from retail legion from 11.02.2017:
https://www.youtube.com/watch?v=PjYlP6BYpng&feature=youtu.be

**Comment by plznoz** [comment]
@Teridan-dal-wow Same behaviour as dalaran currently (at least with iceblock). Thanks for confirmation.

@Rushor Will snobolds now run back to boss and be thrown out again and cause an additional stack if people die with it on their back? Cheers.

**Comment by Rushor** [comment]
on ptr they do that, yes

**Comment by Rushor** [comment]
already on PTR
