### ISSUE TITLE
Instance: Obsidian Sanctum - Invisible Triggers / NPCs

### ISSUE THREAD

**Issue by Crispybuilt** [dalaranwow/dalaran-wow#437]
*Instance: Obsidian Sanctum (10 Player)*

- **Issue** - After some time in the instance, after you defeat or pull trash and you kill most of them, players will sometimes get stuck in combat because of the invisible trigger which will do damage to them.

The possible name of the trigger / npc that was hiting them was probably: **Fire Cyclone** but there is definetly something else

- This issue has to be researched and investigated.

http://wotlk.openwow.com/npc=30648

**Comment by Lothloryen** [comment]
Working properly since long time ago.
