### ISSUE TITLE
[Achievement] Blade's Edge Bomberman

### ISSUE THREAD

**Issue by alexuktc** [dalaranwow/dalaran-wow#4371]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
Several issues I have noticed:
1. The cannons start firing too early. By the time you are in range to use the bombs they start firing again. It's more hassle than it was on Retail!
2. The cannons fire more than they should. They should fire less, so you actually have some time to stop.
3. VERY IMPORTANT!! The quest item bug is fixed on this server for some reason! On Retail you could queue up and fire 2 bombs at the same time granted that you fired up the second one while the first one was still being casted. This is pretty much what made the achievement doable.
4. My casts get interrupted quite a lot. From what I have noticed it's due to the fact that the UI tells me I'm in range to cast it but I'm not. Couple that with the firing mechanics on this server and it is quite an issue. 
5. Respawn time of the bombs is too high and some bombs do not respawn unless you manually go and see them.

**Expected behaviour**: Tell us what should happen instead
1. I'm not sure if they start firing too early or their range is too big. That is up to you to find. either way, the video I will provide (from Wotlk) shows that it is not how it is on our server.
2. From what I noticed on the video and our server, the cannons fire 4 times in a fast succession and then fire again way too fast. This results in you getting the damage buff twice in a row and it pretty much raping.
3. This is not a discussion on whether it was right or not. A Blizzlike server should follow how things were on Retail. As it stands 1 small mistake (as small as issue 4 where you get interrupted) pretty much means you can't get the achievement. Using this trick people were able to get dismounted, get back up again and finish it with time to spare.
4. If the green circle is shown, the cast should be successful, even if I move away during that cast.
5. In the video you can easily see the bombs recharging within a 1 minute period.
**Steps to reproduce the problem**:

1. Try to do the quest
2. ???
3. See the issues

**Include proofs for this behaviour**
https://www.youtube.com/watch?v=M8TLbjYWFaw

http://www.wowhead.com/achievement=1276/blades-edge-bomberman#comments

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**
achievement=1276

No screenshots necessary, the video is more than enough.

**Comment by Rushor** [comment]
duplicate https://github.com/dalaranwow/dalaran-wow/issues/2739
