### ISSUE TITLE
Pet resurrection in BGs [Hunter]

### ISSUE THREAD

**Issue by KerDW** [dalaranwow/dalaran-wow#4373]
Current behaviour: Pets are sometimes not resurrecting with you when they die in the same BG previously. This happens with hunter's pets as far as I am concerned, not sure about other classes with pets.

Expected behaviour: Pets should resurrect with you in the Spirit Healer in BGs even if they died before and you were still alive.

Steps to reproduce the problem:

1- Be in a BG.
2- Your pet dies.
3- You die and resurrect at the BG's Spirit Healer.
4- Summon and/or check your pet. 

This does not happen all the time but when it does it keeps doing it until you resurrect your pet yourself, at least as a hunter.

**Comment by Rushor** [comment]
intended as far as i know: https://github.com/dalaranwow/dalaran-wow/issues/3741

https://github.com/dalaranwow/dalaran-wow/issues/3741#issuecomment-251396756

**Comment by KerDW** [comment]
@Rushor Yeah that was a bug, I am talking about pets in BGs specifically here, a bug that appeared recently at least as far as I know. 

"There a Spirit Guide resurrects all nearby players on a regular cycle, with a dialog box displaying the time until resurrection. Unlike Spirit Healers found in the rest of the world, players resurrected by Spirit Guides are restored to full health and mana, as are any pets or minions."
Source: http://wow.gamepedia.com/Battleground

**Comment by Rushor** [comment]
post the info in the related isse on github pls. thank you
