### ISSUE TITLE
[Reputation][NPC][Kalimdor] Steamwheedle Cartel

### ISSUE THREAD

**Issue by Moonsstyler** [dalaranwow/dalaran-wow#4382]
[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Once you have hit Revered with: 
     - Booty Bay, Bloodsail Buccaneers (Stranglethorn Vale) which include: Deckhand, Elder Magus, Mage, Raider, Swabby, Corsair.
     - Ratchet, Southsea Freebooters (The Barrens) which include: Brigand, Cannoneer, Cutthroat and Privateer, stop giving spillover reputation with the other three Steamwheedle Cartel factions.
     - Gadgetzan, Southsea Pirates (Tanaris) which include: Dock Worker, Freebooter, Pirate and Swashbuckler stop giving spillover reputation with the other three Steamwheedle Cartel factions.
     - Wastewander (Tanaris) which include: Assassin, Bandit, Rogue, Scofflaw and Thief, stop giving spillover reputation to the other three Steamwheedle Cartel factions once you hit Honored.
     - Venture Co. (Stranglethorn Vale and Grizzly Hills) which include: Strip Miner, Tinkerer, Surveyor, Miner, Geologist and Foreman, stop giving spillover reputation with the other three Steamwheedle Cartel factions once you hit Honored.

Before reaching Revered with lets say Gadgetzan, the Southsea Pirates give you +5 Reputation with Gadgetzan and +2 Reputation spillover to the other three Steamwheedle Cartel factions, upon hitting Revered the reputation gained earlier stops. This happens with _some_ "Named" NPCs from those Bandit/Pirate factions, e.g Andre Firebeard, "Pretty Boy" Duncan. 

Baron Longshore (Southsea Freebooters - The Barrens) keeps giving +25 Ratchet reputation and +12 spillover after reaching Revered with Ratchet.

**Expected behaviour**: Once you hit Revered with any of the Steamwheedle Cartel factions, the Pirate/Bandit factions listed above are still supposed to give you the **_SPILLOVER_** reputation for Steamwheedle Cartel.

**Steps to reproduce the problem**:

1.  Gain/Reach Revered with Booty Bay/Ratchet/Gadgetzan. 
2.  Try killing any of the Bandits/Pirates tied to one of those factions. (e.g Ratchet -> Southsea Freebooters)
3.  Enjoy the 0 reputation gained.

**Include proofs for this behaviour**:

Here is a link with all the NPCs that are supposed to reward Reputation with the
[Steamwheedle Cartel](http://wow.gamepedia.com/Mobs_which_affect_reputation_with_Steamwheedle_Cartel).

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

Some of the locations of those NPCs is _unknown_ on WowHead.
[Andre Firebeard - WowHead](http://www.wowhead.com/npc=7883)
[Andre Firebeard - OpenWow](http://wotlk.openwow.com/npc=7883)
[Southsea Freebooter - WowHead](http://www.wowhead.com/npc=7856)
[Southsea Freebooter - OpenWow](http://wotlk.openwow.com/npc=7856)

[Baron Longshore - WowHead](http://www.wowhead.com/npc=3467)
[Baron Longshore - OpenWow](http://wotlk.openwow.com/npc=3467)
[Southsea Cannoneers - WowHead](http://www.wowhead.com/npc=3382)
[Southsea Cannoneers - OpenWow](http://wotlk.openwow.com/npc=3382)

**Include Screenshots from the issue if necessary**
When under Revered:
![wowscrnshot_020717_185850](https://cloud.githubusercontent.com/assets/25615134/22706792/44ec5ac0-ed79-11e6-8628-1eb059ee54f5.jpg)

-->>

![wowscrnshot_020717_185855](https://cloud.githubusercontent.com/assets/25615134/22706801/4a42da6c-ed79-11e6-8f55-45ee8e702dce.jpg)

When over Revered:
![wowscrnshot_020717_190850](https://cloud.githubusercontent.com/assets/25615134/22706863/7ed0f084-ed79-11e6-8895-fb17f00bb626.jpg)

-->>

![wowscrnshot_020717_190904](https://cloud.githubusercontent.com/assets/25615134/22706871/882b0048-ed79-11e6-841e-49653243f239.jpg)

Killing a _named_ NPC over Revered:
![wowscrnshot_020717_190952](https://cloud.githubusercontent.com/assets/25615134/22706889/9a45eed2-ed79-11e6-9b70-2182f9937607.jpg)

-->>

![wowscrnshot_020717_190959](https://cloud.githubusercontent.com/assets/25615134/22706898/a0db22d0-ed79-11e6-8b9d-9b1ec0a1c700.jpg)

**Comment by Rushor** [comment]
DB/Creature: Update Steamwheedle Cartel Rep and give Steamwheedle Cartel rep until exalted for 35 npcs

* closes: https://github.com/dalaranwow/dalaran-wow/issues/4382
* commit: 5ed05040448fa7ea2578b701f6206ac15e507b1e

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
