### ISSUE TITLE
[Priest][Item] Priest T8 Shadow 2P inactive

### ISSUE THREAD

**Issue by Dovilacus** [dalaranwow/dalaran-wow#4385]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote 
http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
Devouring Plague is not getting damage bonus from having two T8 shadow priest pieces equiped.

**Expected behaviour**: Tell us what should happen instead
Devouring Plague should get 15% damage modifier while wearing the refered items.

**Steps to reproduce the problem**:
I observed the damage caused by Devouring Plague's periodic tick in function of spell power on a 0/0/0 spec (to avoid any SP modifiers from talents), this while wearing and while not wearing the set.

![t0setup](https://cloud.githubusercontent.com/assets/25619125/22711928/d8a8c306-ed7a-11e6-9cb7-83ae6c25acc6.png)
![t8_2setup](https://cloud.githubusercontent.com/assets/25619125/22711937/e28a9354-ed7a-11e6-9ca4-0fc99271c74d.png)

**Include proofs for this behaviour**
Raw data:
![datatable](https://cloud.githubusercontent.com/assets/25619125/22712332/51675950-ed7c-11e6-88ec-d1acbd5b54c3.png)
"BlizzDP" being what I expect the blizzlike damage for each DP tick, assuming the formula to calculate the damage is either (base+SPcoef)×K×1.15 or base×SPcoef×K×1.15, where "K" is a damage modifier that remains unchanged during the observations.

Graphs:
![t8_2testdtd](https://cloud.githubusercontent.com/assets/25619125/22712531/00f3095a-ed7d-11e6-9efb-5235440eb450.png)

![t8_2testenhc](https://cloud.githubusercontent.com/assets/25619125/22712540/06a45e4e-ed7d-11e6-9f3f-e26a33dc3475.png)

As you can see there is no modifier between the test with and without the T8 (2) set, since the linearizations are almost coincident.
Note that there are only four points in Elder Nadox due to the fact that in combat, the player can only equip weapon, offhand and wand, this however given the nature of the game, didn't affect significatively the precision of the results.

![blizzliketested](https://cloud.githubusercontent.com/assets/25619125/22712851/34793e42-ed7e-11e6-8229-d4e2675a19c2.png)
Compairson to what I suspect should be the blizzlike slope.
Blizzlike linearization equation: y=0,2126x+197,28

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

http://wotlk.openwow.com/spell=64906#itemsets
http://wotlk.openwow.com/spell=48300

**Include Screenshots from the issue if necessary**

Thank you for your attention on the issue.
Kind regards,
Dovilacus.

**Comment by Rushor** [comment]
Scripts/Spells: Priest Devouring Plague - Increase damage if player has Item - Priest T8 Shadow 2P Bonus

* closes: https://github.com/dalaranwow/dalaran-wow/issues/4385
* commit: 4baf43964527ba88f97b65e40ec6bd115509645a

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
