### ISSUE TITLE
Tempest Keep Not giving raid ID

### ISSUE THREAD

**Issue by Drawsblood** [dalaranwow/dalaran-wow#4387]
**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
Just cleared TK and did not receive a raid ID, was wondering why I started seeing so many Ashes around. :^)

**Expected behaviour**: Tell us what should happen instead

Obtain ID upon killing boss.

**Steps to reproduce the problem**:

1. Enter dungeon
2. kill boss
3. dont get saved

**Comment by alexuktc** [comment]
I am not sure how you accomplished that. but as one of the people with the Ashes I can assure this is not the case for us. Don't assume people have abused just because they have Ashes.

**Comment by Drawsblood** [comment]
Just reporting a bug I found while doing TK yesterday.  Please calm down .

**Comment by Rushor** [comment]
duplicate of https://github.com/dalaranwow/dalaran-wow/issues/3133
