### ISSUE TITLE
[Dungeon][Event][Love is in the Air]Crown Chem Co. 

### ISSUE THREAD

**Issue by TheRealestMcCoy** [dalaranwow/dalaran-wow#4388]
**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
Doing the first random Cron Chem Co dungeon does not grant Heart SHaped Box. The dungeon is not completing after killing so you get deserter if you just leave.
**Expected behaviour**: Tell us what should happen instead
After killing Hummel you should receive the box and be able to leave with out getting deserter
**Steps to reproduce the problem**:

1. Queue up for Camp Chem
2. Kill boss
3. Leave

**Include proofs for this behaviour**
![wowscrnshot_020817_214844](https://cloud.githubusercontent.com/assets/12252441/22767289/632fc9f2-ee48-11e6-8d0d-74d64d9c789e.jpg)

You can research this on several pages like http://wowhead.com or http://wowwiki.wikia.com or http://www.youtube.com/
Issues without proofs will be closed and tag On Hold will be added until the proof is provided.

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

You can research this on several pages like http://wotlk.openwow.com or http://wowhead.com/
[Heart-Shaped Box](http://www.wowhead.com/item=54537/heart-shaped-box)
[Trigger to receive box](http://www.wowhead.com/quest=25485/world-event-dungeon-hummel)
**Include Screenshots from the issue if necessary**

**Comment by TheRealestMcCoy** [comment]
Issue 2:

Quest: You've Been Served is not complete-able.

Whats wrong.
You pick the quest up just inside SFK after turning in the previous quest. You are granted a bag that contains 3 items. To turn this quest in you should talk to Hummel. Currently he is already a enemy npc.

How it should work.(If i remember correctly.)
You go talk to Hummel to turn in the quest. He should also offer a dialogue to start the fight. 

[Quest](http://www.wowhead.com/quest=14488/youve-been-served)

**Comment by TheRealestMcCoy** [comment]
[Dungeon Video Link](https://www.youtube.com/watch?v=cw7jErF8mLA)

The zone should also not include any other NPCs it should be only these bosses.

Also the boss should drop 226 gear? Not sure if this is due to progression server or how this works.

**Comment by Lothloryen** [comment]
Hello there,

I thought this was applied on live since it was working already, nonethess, it will be applied after the next scheduled maintenance.

Thank you very much.

**Comment by TheRealestMcCoy** [comment]
When do you do maint? Ive only been here since the end of last year.

**Comment by ErasmusHereticus** [comment]
Event still not fixed.

**Comment by datbunneh** [comment]
@Lothloryen Can't turn in "You've Been Served" quest.

**Comment by Lothloryen** [comment]
Hello there,

After the last maintenance the proper emblems will drop as well as the items (from the Heart-Shaped box), based on each player's progression.

Regards.

**Comment by datbunneh** [comment]
@Lothloryen What about the quest?
