### ISSUE TITLE
[Quest][Item][WotlK]  Shoveltusk Ligament - too low droppchance

### ISSUE THREAD

**Issue by Rushor** [dalaranwow/dalaran-wow#4400]
http://wotlk.openwow.com/item=33611

The dropchance for those items should be around 45 percent, as you can see here https://www.youtube.com/watch?v=8eqbtJjYSXM&hd=1

**Comment by Rushor** [comment]
DB/Item: Shoveltusk Ligament - Increase droppchance to 45 percent

* closes: https://github.com/dalaranwow/dalaran-wow/issues/4400
* commit: 01be2ff1c3e7ad2a060f210037b864f407f05851

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by TeridanDW** [comment]
Works as intended on PTR.
