### ISSUE TITLE
Level 80 bosses inside Shadowfang Keep

### ISSUE THREAD

**Issue by warcraftgeekygamer** [dalaranwow/dalaran-wow#4401]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behavior**: Tell us what happens in detail (Where, When, What, Why, Who)
On February 10, 2017 I joined the random dungeon finder and queued for SFK (Shadowfang Keep). Once inside, it was discovered that the three level 82 bosses for the Love is in the Air event had spawned. These three elites spawn near the horse stables.

It was impossible for the entire group to proceed past these mobs simply because they ran after all of us -- even if we tried to stay as far away as we could. We tried to hug the wall to no avail. These elites should ONLY be spawned for the level 80 dungeon event.

This was reported in 2016 for the same reason: https://github.com/dalaranwow/dalaran-wow/issues/3162
According to the report dated 2016, it was fixed.

**Expected behavior**: Tell us what should happen instead

These elites should ONLY spawn for the level 80 dungeon event.

http://wotlk.openwow.com/npc=36565
http://wotlk.openwow.com/npc=36272
http://wotlk.openwow.com/npc=36296

**Steps to reproduce the problem**:

1.  Level a character to level 20-25
2.  Go inside SFK
3.  Kill first boss
4. Proceed to courtyard
5. Get pwned by the level 82 elites because you are only level 20-25

**Include proofs for this behavior**

https://www.youtube.com/watch?v=Rbwx7J7Yv8A
http://www.wowhead.com/love-is-in-the-air#comments
http://www.wowhead.com/npc=36565/apothecary-baxter
http://www.wowhead.com/npc=36272/apothecary-frye
http://www.wowhead.com/npc=36296/apothecary-hummel

**Comment by Rushor** [comment]
will be fixed once https://github.com/TrinityCore/TrinityCore/pull/19076/files was merged

or:

if a similar script was already assigned (make the creatures friendly (faction 35 by default) + add them a gossip option to start the event + add the condition to see the gossip option only at level 75-80 )
