### ISSUE TITLE
[Ulduar][General Vezax] Divine Plea and other mana spells - Wrong mechanic

### ISSUE THREAD

**Issue by Klala** [dalaranwow/dalaran-wow#4417]
**Current behaviour**: Currently when you start general vezax with Divine Plea on before the pull you immidiately lose it after you pull it, Making the paladin tank wait 1 min for another Divine Plea.

**Expected behaviour**: You shouldn't lose Divine Plea on aggro when you face General Vezax

**Steps to reproduce the problem**:

1. Go to ulduar and use Divine Plea before pulling Vezax
2. After using Divine Plea pull Vezax
3. Notice that you lost Divine Plea

source:
http://wowwiki.wikia.com/wiki/General_Vezax?oldid=2327907

It notes all the things that suppose to work on the Aura of Despair ability.

Also, I'd like to add that rogues have a problem with energy regeneration.
Energy regeneration works fine but Combat potency and relentless strikes energy bonus do not proc.
I believe that Aura of Despair should be effective against mana sources only. This might also be the case for rage based classes and runic power but I have no characters of the sort to test these things out.

The link also mentions that Fel Mana Potion and Dark Rune should also work to regain mana, that also should be true for Demonic Rune.

**Comment by Rushor** [comment]
http://www.mmo-champion.com/threads/649075-General-Vezax
Re: General Vezax

    For a paladin on Vezax, the following DO NOT return mana:

    - Divine Plea
    - Illumination
    - Blessing of Wisdom
    - Judgement of Wisdom
    - Lay on Hands
    - MP5 from any source (gear, potions, flasks, food)
    - Mana potions

    Abilities that WILL reduce or return mana
    - Benediction
    - Divine Illumination
    - Glyph of Seal of Wisdom
    - Libram of Renewal
    - Dark Rune
    - Spiritual Attunement
    - Judgement of the Wise 

Well on retail Divine Plea does not work during the encounter (as you can see in the mmo post). so either the buff stays and has no effect or the buff will simply get removed on start of the fight against General Vezax. Both will prevent the player from getting mana.

I'm not shure how it was on 3.3.5 or how it is on retail currently. maybe someone could provide a source how it should be (video/texts)

I will set this issue "On Hold" until we get a source for it.

(Note: the aura that is reponsible for the remove of Divine Plea is http://wotlk.openwow.com/?spell=62692 which is casted on all player once you start the fight against General Vezax)

**Comment by Klala** [comment]
Sorry, I should have left a link with the source for this report.
http://wowwiki.wikia.com/wiki/General_Vezax?oldid=2327907

It notes all the things that suppose to work on the Aura of Despair ability.

Also, I'd like to add that rogues have a problem with energy regeneration.
Energy regeneration works fine but Combat potency and relentless strikes energy bonus do not proc.
I believe that Aura of Despair should be effective against mana sources only. This might also be the case for rage based classes and runic power but I have no characters of the sort to test these things out.

The link also mentions that Fel Mana Potion and Dark Rune should also work to regain mana, that also should be true for Demonic Rune.

**Comment by Rushor** [comment]
hm actually this was fixed some time ago here https://github.com/dalaranwow/dalaran-wow/issues/3451 maybe the fix was removed from live again - it works on PTR

**Comment by Klala** [comment]
Well I can confirm that Divine Plea works. It just gets removed if you use it before pulling the boss.

I wanted to post it there but I felt that it was irrelevent for the source report so I made a new one for that which also reminded me about the energy regeneration problem.

**Comment by Rushor** [comment]
pls update the first post with the infos from https://github.com/dalaranwow/dalaran-wow/issues/4417#issuecomment-279361452. thanks

**Comment by alexuktc** [comment]
Okay, just want to mention that I killed Vezzax yesterday and the only energy regen I got was from a resto druid's Revitalize talent. Combat Potency does not work at all. I have not tried Relentless Strikes.

**Comment by TheRealestMcCoy** [comment]
I have encountered this issue with my paladin tank as well. It was really bad tanking this until i learned what was happening.
