### ISSUE TITLE
crash during northrend flight point travel

### ISSUE THREAD

**Issue by Raulfin** [dalaranwow/dalaran-wow#4418]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

Crash traveling to Amberpine Ridge, Grizzly Hills, Northrend from west Northrend. happened on two consecutive trips.

crash log; http://pastebin.com/t2dASGWy

**Comment by Rushor** [comment]
Cannot confirm this on PTR. Please make shurer that you have the correct client installed/downloaded

**Comment by Edzero** [comment]
One possible cause for this is the quest in Icecrown "The Last Line of Defense"

If you've reached that part of the chain but not completed it, it will cause issues when using flight paths in Northrend. 

Temporary fix for the player is to complete that quest.

**Comment by Rushor** [comment]
related to https://github.com/dalaranwow/dalaran-wow/issues/2878 then?

**Comment by Raulfin** [comment]
toon is only 73 at time of the crash, so haven't started questing IC yet. Had a similar issue using the free flight path from Dal to ToC, crash was just as ToC was loading.
client version is the version linked to from dal-wow.com.
