### ISSUE TITLE
[NPC][TBC] Ring of Observance - Entrance to Auchenai Crypts  Events

### ISSUE THREAD

**Issue by Rushor** [dalaranwow/dalaran-wow#4420]
http://wotlk.openwow.com/npc=19416

Those creatures should be spawned and handle a talk-emote every few seconds + should have the insisible aura just like http://wotlk.openwow.com/npc=19879

http://wotlk.openwow.com/npc=19697
Should have a conversation with his mother every 270 seconds.

http://wotlk.openwow.com/npc=19698
Greatfather Aldrimus should handle a talk emote every few seconds.

source:

Ha'lei giggles.
Ha'lei says: "You promise?"
Ha'lei tugs on Clarissa's robe.
Ha'lei says: "Mommy, Greatfather says everything will be ok."
Clarissa wipes the tears away.
Clarissa says: "Mommy is going to make sure you're ok, baby."
<pause a few minutes>

Clarissa says: "Please, father, I do not have your strength. I cannot do this on my own. Please help me..."
<pause a few minutes>

Ha'lei giggles.
Ha'lei says: "I'll tell her, Greatfather."
Ha'lei tugs on Clarissa's robe.
Ha'lei says: "Don't cry, Mommy. Greatfather says not to worry."
Clarissa wipes the tears away.
Clarissa says: "In the end, we will all be together, sweetheart."
<pause a few minutes>

Ha'lei laughs.
Ha'lei says: "I will, Greatfather."
Ha'lei tugs on Clarissa's robe.
Ha'lei says: "Mommy, Greatfather told me that he will watch over us and make sure we're ok."
Clarissa wipes the tears away.
Clarissa says: "Oh sweetheart, grandpoppy has passed. It will be ok."

<frequently repeated>
Clarissa says: "Father, give me strength to go on."

http://www.wowhead.com/quest=29595/everything-will-be-alright#comments:id=1589247

**Comment by Rushor** [comment]
DB/Creature: Ring of Observance - Entrance to Auchenai Crypts Events with Ancient Draenei Spirit, Greatfather Aldrimus, Ha'lei and Clarissa

* closes: https://github.com/dalaranwow/dalaran-wow/issues/4420
* commit: 93fe9d3c613684bde4f2f7b216820392fb4f64b9

![GitHub Logo](http://i.imgur.com/r4s0rrI.jpg)
![GitHub Logo](http://i.imgur.com/u3g77AA.jpg)
![GitHub Logo](http://i.imgur.com/oYpkqx8.jpg)

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by Rushor** [comment]
@Teridan-dal-wow guids: 5004729 - 5004733 are now in use, just to let you know for further fixes

**Comment by Teridan-dal-wow** [comment]
Thank you.
