### ISSUE TITLE
Warrior Cleave

### ISSUE THREAD

**Issue by tonystark9911** [dalaranwow/dalaran-wow#4426]
**Current behaviour**: 
Cleaving range is not working as it is suposed to, examples of this in ToC are snowbolds, mistresses and infernals on jaraxus and anubarak ads, unless they are inside boss hitbox you wont be able to cleave them unless you are targetting the ads themselves.

**Expected behaviour**:

https://www.youtube.com/watch?v=1mYHEzHuld8&t=276s

This a link from a retail video where you can clearly see the warrior positioning and how his cleave will hit 3 targets even while targetting the boss.

**Steps to reproduce the problem**:

Get the same positioning of the ads and the warrior, try to cleave, only anubarak gets damaged by the cleave.

**Comment by tonystark9911** [comment]
Also considering some hitbox issue

**Comment by plznoz** [comment]
I second this. Seems to be worse on larger hitboxes (some range calculation that's fucked?)

**Comment by Teridan-dal-wow** [comment]
Hello,
This is general issue that affects all "cleave kind" spells and all creatures in the world (not only TOC ones). In warrior's case the `cleave spell` is one of the main spells thats why its so noticiable, also in the world players rarely encounter creatures with large(massive) hitboxes.
I think there was someone on TC that was working on that and it was almost ready, but i can't find the report right now (been looking for more than an hour for it).

> Seems to be worse on larger hitboxes (some range calculation that's fucked?)

This.

**Comment by plznoz** [comment]
[https://github.com/TrinityCore/TrinityCore/pull/16290](https://github.com/TrinityCore/TrinityCore/pull/16290) Probably this.

**Comment by Teridan-dal-wow** [comment]
Yes, thats the one.

**Comment by Rushor** [comment]
merged to https://github.com/dalaranwow/dalaran-wow/issues/1386 + updated the linked issue to a more generic one.
