### ISSUE TITLE
[NPC][Classic] Demetria - missing guards

### ISSUE THREAD

**Issue by Rushor** [dalaranwow/dalaran-wow#4429]
http://wotlk.openwow.com/npc=12339

her waypoints + speed needs to be updated + some guards for her are missing as you can see in http://www.wowhead.com/npc=12339/demetria#screenshots:id=381724

**Comment by Rushor** [comment]
DB/Creature: Demetria - Add missing guards, update path and speed

* closes: https://github.com/dalaranwow/dalaran-wow/issues/4429
* commit: c813de2abbfe2802ce8190fada9c357a22a4eecb

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by TeridanDW** [comment]
Works as intended on PTR.
