### ISSUE TITLE
[Quest][TBC] The Thunderspike - Missing visuals

### ISSUE THREAD

**Issue by Rushor** [dalaranwow/dalaran-wow#4431]
http://wotlk.openwow.com/quest=10526

The questscript should look like this https://www.youtube.com/watch?v=b1jzMFRaGfg

Currently the weapon switch, orientation changes and texts are missing.

**Comment by Rushor** [comment]
also the object http://wotlk.openwow.com/object=184737 should be despawned once the creature changes it's equip

**Comment by Rushor** [comment]
DB/Quest: The Thunderspike - Add spawn-in script and visual details

* closes: https://github.com/dalaranwow/dalaran-wow/issues/4431
* commit: e967e6b4ac417d6e6a44ad36191eb95f371c2d4c

![GitHub Logo](http://i.imgur.com/i5rBP6r.jpg)

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by TeridanDW** [comment]
Works as intended on PTR.
