### ISSUE TITLE
[GOBJ] Mammoth Carcass and Mammoth Meat, wrong spawns

### ISSUE THREAD

**Issue by Teridan-dal-wow** [dalaranwow/dalaran-wow#4449]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Gameobject Mammoth Carcass http://wotlk.openwow.com/object=192693 and Mammoth Meat http://wotlk.openwow.com/object=191567 should not be constantly spawned, instead there should be an Ironwool Mammoth http://wotlk.openwow.com/npc=29402
On server:
![image](https://cloud.githubusercontent.com/assets/6797611/23066444/46868002-f523-11e6-98a4-74a91d83795f.png)
On retail:
![image](https://cloud.githubusercontent.com/assets/6797611/23066426/3bb36ea6-f523-11e6-8943-a75b96a464c0.png)

Additional information:
Quest http://wotlk.openwow.com/quest=12828 --> Object  http://wotlk.openwow.com/object=191553 ---> Item http://wotlk.openwow.com/item=40686 --> throw at Npc http://wotlk.openwow.com/npc=29402 leads to explosion and the posted above gameobjects to spawn on the ground for limited time.

What is done:
-removed the 7 gobjects
-added the missing mammoth
-set random movement to 1 mammoth that should have it
-increase the random movement radius for all mammoths that use random movement.
``` sql
DELETE FROM `gameobject` WHERE `guid` BETWEEN 57902 AND 57907;
DELETE FROM `gameobject` WHERE `guid` = 60056;
SET @CGUID := 5004922;
DELETE FROM `creature` WHERE `guid` = @CGUID+0;
INSERT INTO `creature` (`guid`, `id`, `map`, `zoneId`, `areaId`, `spawnMask`, `phaseMask`, `modelid`, `equipment_id`, `position_x`, `position_y`, `position_z`, `orientation`, `spawntimesecs`, `spawndist`, `currentwaypoint`, `curhealth`, `curmana`, `MovementType`, `npcflag`, `unit_flags`, `dynamicflags`, `VerifiedBuild`) VALUES
(@CGUID+0, 29402, 571, 0, 0, 1, 1, 0, 0, 6457.956, -1283.934, 463.8988, 3.151358, 300, 10, 0, 1, 0, 1, 0, 0, 0, 23420); -- 29402 (Area: -1)
DELETE FROM `creature_addon` WHERE `guid` = @CGUID+0;
INSERT INTO `creature_addon` (`guid`, `path_id`, `mount`, `bytes1`, `bytes2`, `emote`, `auras`) VALUES
(@CGUID+0, 0, 0, 0, 1, 0, ''); -- 29402
UPDATE `creature` SET `MovementType` = 1 WHERE `guid` = 116905;
UPDATE `creature` SET `spawndist` = 10 WHERE `guid` IN (116889, 116890);
UPDATE `creature` SET `spawndist` = 10 WHERE `guid` BETWEEN 116896 AND 116906;
```

**Comment by Rushor** [comment]
committed with your name - thanks !

DB/Gameobject: Mammoth Carcass and Mammoth Meat - remove wrong spawns, add one missing Mammoth, update randommovement range

* closes: https://github.com/dalaranwow/dalaran-wow/issues/4449
* commit: 660377e7421f866dfff8ce1d93ad5ca0691eb56a

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
