### ISSUE TITLE
[Item] Dog Whistle / Tracking Hound

### ISSUE THREAD

**Issue by plznoz** [dalaranwow/dalaran-wow#4456]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
The summoned dog is level 80 (on a level 80, I assume it's lower with lower level chars).
Having high level makes this low level item useful in end game raids, where it shouldn't be.

**Expected behaviour**: Tell us what should happen instead
The summoned dog should be level 30.

**Steps to reproduce the problem**:
1. Get Dog Whistle from SM Library
2. Use item
3. Look at Tracking Hound's level

**Include proofs for this behaviour**
http://wowwiki.wikia.com/wiki/Dog_Whistle quote:
> The summoned hound is level 30, and will attack anything that attacks its summoner.

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**
http://wotlk.openwow.com/item=3456 Dog Whistle
http://wotlk.openwow.com/spell=9515 Summon Tracking Hound
http://wotlk.openwow.com/npc=6867 Tracking Hound

**Comment by Teridan-dal-wow** [comment]
Additional information:
 - In the DB the Hound has the correct `minlvl=30` and `maxlvl=30` 
 - In the DB the Dog Whistle uses the correct spell 9515
 - Even though the hound is set at lvl 80 (for level 80 char) its damage doesn't scale, but hp does.
![image](https://cloud.githubusercontent.com/assets/6797611/23095928/38816f00-f61b-11e6-87f4-14100320d55d.png)

**Comment by plznoz** [comment]
Having level 80 should make it able to hit more though right?

**Comment by Teridan-dal-wow** [comment]
Maybe, but thats irrelevent as it shouldn't be scaled above level 30 (min level to use the item is 25 so it should scale with the owner only from 25 to 30).

**Comment by plznoz** [comment]
Yeah, but I mean right now when it's level 80.
http://www.worldoflogs.com/reports/ilfjla9k6figdqn0/details/80/?s=2852&e=3255

**Comment by Rushor** [comment]
level must be set in core sadly

**Comment by Rushor** [comment]
Game/Spells: Tracking Hound - Limit level to 30

* closes: https://github.com/dalaranwow/dalaran-wow/issues/4456
* commit: 3306f8cb5adab2be27a19aba366faedd1bb92bf9

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
