### ISSUE TITLE
Cleansed Songflower - Songflower Serenade

### ISSUE THREAD

**Issue by Horvic** [dalaranwow/dalaran-wow#4457]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**:
Clicking the Cleansed Songflower in Felwood gives you the buff Songflower Serenade.
This buff should only be applied below level 65 but also works at 65-80 on Dalaran.

**Expected behaviour**:
The buff should only be applied at level 64 and lower.

**Steps to reproduce the problem**: https://youtu.be/QTJToHnsZNM

1. Go to Felwood and find a cleansed songflower or cleanse a corrupted songflower yourself.
2. Click it on a level 80 character.
3. Get Songflower Serenade.

**Include proofs for this behaviour**

http://wowwiki.wikia.com/wiki/Songflower_Serenade
"If the player is above level 65, he will not receive the buff."

http://wowwiki.wikia.com/wiki/Cleansed_Songflower
"This buff will not apply to players above level 65."

http://www.wowhead.com/object=164882/cleansed-songflower#comments
"This buff applies up to level 64 only. At level 65, opening a cleansed songflower has no effect"

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

Corrupted Songflower - http://wotlk.openwow.com/?search=Corrupted+Songflower
Cleansed Songflower - http://wotlk.openwow.com/?search=cleansed+songflower
Songflower Serenade - http://wotlk.openwow.com/spell=15366

**Comment by Horvic** [comment]
Noticed this has already been fixed and is on PTR along with everything else we'll never see hit the live realm.

**Comment by Rushor** [comment]
> Noticed this has already been fixed and is on PTR along with everything else we'll never see hit the live realm.

According to the latest news a huge update will be made in the next 1-2 months afaik
