### ISSUE TITLE
[Quest][TBC] Escape from Coilskar Cistern - Wrong Faction Change

### ISSUE THREAD

**Issue by Rushor** [dalaranwow/dalaran-wow#4462]
http://wotlk.openwow.com/npc=21027

During the escortevent of this creature, the summoned hostile nagas does not attack npc=21027.

npc=21027 shoudl always attack them.

**Comment by Rushor** [comment]
Scripts/Outland: Earthmender Wilda now attacks during the escortevent of quest: Escape from Coilskar Cistern

* closes: https://github.com/dalaranwow/dalaran-wow/issues/4462
* commit: 8e67b7e40da73f80351e47b1148bb3f44509d0ae

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by TeridanDW** [comment]
Works as intended on PTR.

Note: She behaives strange, when engaged in combat --> attacker killed --> she runs to next waypoint --> then back to previous one --> then walks again
