### ISSUE TITLE
[NPC] Trade Master Kovic - Missing Aggro text

### ISSUE THREAD

**Issue by Rushor** [dalaranwow/dalaran-wow#4467]
http://wotlk.openwow.com/npc=8444

should say a text on aggro

Source: http://wow.gamepedia.com/Trade_Master_Kovic#Quotes

**Comment by Rushor** [comment]
DB/Creature: Trade Master Kovic - Add aggrotext

* closes: https://github.com/dalaranwow/dalaran-wow/issues/4467
* commit: 9d3c1e36d21095eadb669a1ac0bec32da9ba3e7d

![GitHub Logo](http://i.imgur.com/41RS6nk.jpg)

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by TeridanDW** [comment]
After a fast test on PTR,
 - there is no text on aggro (after ~20 attempts/pulls)
