### ISSUE TITLE
Kirin Tor realm - quest ID 3367

### ISSUE THREAD

**Issue by Pellaeon83** [dalaranwow/dalaran-wow#4476]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

There is an issue with quest ID 3367 - Suntara Stones in Searing Gorge.

This is an escort quest which starts the chain of quests, but after taking it, NPC does not start his journey. Therefore quest is impossible to finish.

**Comment by Rushor** [comment]
it was fixed on algalon, so you need t wait until the fix was merged to kirin tor realm

https://github.com/dalaranwow/dalaran-wow/issues/74
