### ISSUE TITLE
[NPC] Creatures with wrong exp awards

### ISSUE THREAD

**Issue by Teridan-dal-wow** [dalaranwow/dalaran-wow#4477]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: There are some creatures that should not award any exp at kill, but currently they do.

 1) - Npc http://wotlk.openwow.com/npc=8901 and Npc http://wotlk.openwow.com/npc=9956
![image](https://cloud.githubusercontent.com/assets/6797611/23329921/5735d5c8-fb4b-11e6-923f-5c1fa7f44f30.png)

Both of these creatures awards the exp as if they have the normal hp pool for that level, but they don't. As they have reduced hp pool, I suggest to:
``` sql
UPDATE `creature_template` SET `ExperienceModifier` = 0.3 WHERE `entry` IN (8901, 9956);
```
Additional information:
http://wotlk.openwow.com/npc=8901 has `minlvl=52 = 712hp` and `maxlvl=53 = 736hp`
http://wotlk.openwow.com/npc=9956 has `minlvl=54 = 760hp` and `maxlvl=55 = 785hp`
While a normal creature in the world ~lvl 55 has ~ 3300hp and currently awards the same exp as the ones above.

http://www.wowhead.com/npc=8901/anvilrage-reservist#comments

http://www.wowhead.com/npc=9956/shadowforge-flame-keeper#comments

> By PieceOfSheet (2,730 – 9·22) on 2007/12/02 (Patch 2.3.0)		
> These drop the Shadowforge Torch which you will need 2 of them in order to light the 2 braziliers which will open the door to the next boss. Keep in mind that each torch has a 5 min duration, which means it will dissapaer in 5 minutes if not used. So once you kill the Flame Keeper, go directly to one of the braziliers which is near the door to the final boss. You gotta do this fast, even though the mobs are non elites, they respawn 30 seconds after being killed.

Also the respawn time of them should be really low (from comments 20s), however currently they have 5 mins. Suggestion:
``` sql
-- Anvilrage Reservist
UPDATE `creature` SET `spawntimesecs` = 30 WHERE `guid` IN (45955, 45956, 45958, 45959, 46654, 46655, 46690, 46856, 46892, 46893, 46895, 46896, 46960, 46962, 46963, 46969, 46970, 46994, 47086, 47087, 48173, 48174, 48203, 48209);
UPDATE `creature` SET `spawntimesecs` = 30 WHERE `guid` BETWEEN 46657 AND 46673;
UPDATE `creature` SET `spawntimesecs` = 30 WHERE `guid` BETWEEN 46724 AND 46745;
UPDATE `creature` SET `spawntimesecs` = 30 WHERE `guid` BETWEEN 46965 AND 46967;
UPDATE `creature` SET `spawntimesecs` = 30 WHERE `guid` BETWEEN 46977 AND 46979;
UPDATE `creature` SET `spawntimesecs` = 30 WHERE `guid` BETWEEN 46990 AND 46992;
UPDATE `creature` SET `spawntimesecs` = 30 WHERE `guid` BETWEEN 47045 AND 47051;
UPDATE `creature` SET `spawntimesecs` = 30 WHERE `guid` BETWEEN 47077 AND 47081;
UPDATE `creature` SET `spawntimesecs` = 30 WHERE `guid` BETWEEN 47205 AND 47207;
UPDATE `creature` SET `spawntimesecs` = 30 WHERE `guid` BETWEEN 47209 AND 47216;
UPDATE `creature` SET `spawntimesecs` = 30 WHERE `guid` BETWEEN 88903 AND 88907;

-- Shadowforge Flame Keeper
UPDATE `creature` SET `spawntimesecs` = 300 WHERE `guid` IN (47302, 47303, 91119, 91120);
```
Also from wowhead comment:
> Once you light the 2 braziliers, the door will open and the mobs will no longer respawn.

Currenltly the part "mobs will no longer respawn" doesn't work, they still do.

 2) - Npc http://wotlk.openwow.com/npc=18212 awards the full amount of exp and shares the same issue as the one above.
![image](https://cloud.githubusercontent.com/assets/6797611/23330505/0d5c09ba-fb58-11e6-9c05-d6e3a187243e.png)
Same suggestion as above:
``` sql
UPDATE `creature_template` SET `ExperienceModifier` = 0.3 WHERE `entry` = 18212; 
```
Additional information:
http://wotlk.openwow.com/npc=18212 has `minlvl=62 = 1336 hp` and `maxlvl=63 = 1382hp`
While a normal creature in the world ~ lvl 63 has ~ 5200 hp (depends on the class).

http://www.wowhead.com/npc=18212/mudfin-frenzy#comments

> By tatsuhakyan (479 – 1·5) on 2008/05/11 (Patch 2.4.1)		
> i've found it to be quite easy farming these guys as a 62 feral druid (with the underwater breathing pots). swipe spam is all it takes. i've only attempted up to four groups at a time (16 total mobs) but it was still quite easy and definitely survivable. netting about 50g/hour, 100 unidentified plants/hour, and a slow 32,000xp/hour unrested.

 3) - Npc http://wotlk.openwow.com/npc=32593 is awarding exp as if it an elite creature. These creatures are mostly consmetic and my suggestion for them is:
``` sql
UPDATE `creature_template` SET `ExperienceModifier` = 0 WHERE `entry` = 32593; 
```
![image](https://cloud.githubusercontent.com/assets/6797611/23332304/20d7649e-fb80-11e6-9977-86fa73c3ae70.png)

 4) - Npc http://wotlk.openwow.com/npc=29209 is part of a encounter and shouldn't award any exp. My suggestion is:
``` sql
UPDATE `creature_template` SET `ExperienceModifier` = 0 WHERE `entry` = 29209; 
```
![image](https://cloud.githubusercontent.com/assets/6797611/23332407/cc476576-fb81-11e6-9a46-dd97648a61b8.png)

**Comment by Rushor** [comment]
in order to disable experience, you can set CREATURE_FLAG_EXTRA_NO_XP_AT_KILL

https://trinitycore.atlassian.net/wiki/display/tc/creature_template

**Comment by Teridan-dal-wow** [comment]
Right, but that is if i want to remove it completely, however that is not true for each case above, as there are proofs that 1) and 2) give exp.

**Comment by Rushor** [comment]
modifier should only be changed if the creature should still give any kind of exp, if you wanna disable it we should use teh flagextra then :)

**Comment by Rushor** [comment]
for the despawnfeature we can use this:

```sql
-- Anvilrage Reservist SAI
SET @ENTRY := 8901;
UPDATE `creature_template` SET `AIName`="SmartAI" WHERE `entry`=@ENTRY;
DELETE FROM `smart_scripts` WHERE `entryorguid`=@ENTRY AND `source_type`=0 AND `id`=5;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(@ENTRY,0,5,0,11,0,100,0,0,0,0,0,41,1,0,0,0,0,0,1,0,0,0,0,0,0,0,"Anvilrage Reservist - On Respawn - Despawn Instant");

-- Conditions generated by SAI-Editor
DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId`=22 AND `SourceGroup`=6 AND `SourceEntry`=8901;
INSERT INTO `conditions` (`SourceTypeOrReferenceId`,`SourceGroup`,`SourceEntry`,`SourceId`,`ElseGroup`,`ConditionTypeOrReference`,`ConditionTarget`,`ConditionValue1`,`ConditionValue2`,`ConditionValue3`,`NegativeCondition`,`ErrorType`,`ErrorTextId`,`ScriptName`,`Comment`) VALUES
(22,6,8901,0,0,13,1,5,3,0,0,0,0,"","Despawn Anvilrage Reservist if TYPE_LYCEUM is DONE");
```

of course it must be added for every creature in that room then

**Comment by Rushor** [comment]
the despawnscript should only be added for Shadowforge Flame Keeper, not for Anvilrage Reservist right?

**Comment by Rushor** [comment]
DB/Creature: Despawn Shadowforge Flame Keeper if Lyceum Doors to Magmus are opened

* updates: https://github.com/dalaranwow/dalaran-wow/issues/4477
* commit: 81b5bec4a56dd0760bf5ce89cf71513926cbe5b1

**Comment by Teridan-dal-wow** [comment]
I think so, but not sure. All i found was this:

> By Bowserkills7 (3,806 – 8·25) on 2013/05/27 (Patch 5.3.0)		
> This is still correct information. To light the brazziers to open the doors in this area you need to find the Shadowforge Flame Keeper among the huge amounts of adds in this area that respawn.

But i will asume its only the flame keepers. Also some of the comments mentioned that these flame keeprs spawn on random places in that room (not sure how trustable that statment can be, as they have paths (3 out of the 4)). There is 1 that spawns and has path right next to the doors and for me it makes abosolusly 0 sence in these creature having only 30 secs respawn time as a group can get there kill 1 for 1 torch, wait 30 secs and kill the same one for 2-nd one. So i changed their respawn timer back to 5mins (for flame keeprs only).

**Comment by Rushor** [comment]
DB/Creature: Misc Respawn and Experience updates

* Anvilrage Reservist + Shadowforge Flame Keeper - Update Respawntimer
* Reduce Exp for Anvilrage Reservist + Shadowforge Flame Keeper
* Remove Exp for  Skittering Swarmer + Carrion Beetle
* Reduce Exp for Mudfin Frenzy
* closes: https://github.com/dalaranwow/dalaran-wow/issues/4477
* commit: 24da0ec103cfb6ef35ed770228c6b9e0dad71cfc

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.


Thanks!
