### ISSUE TITLE
[Npc][TBC] Bloodscale Sentry, missing SAI

### ISSUE THREAD

**Issue by Teridan-dal-wow** [dalaranwow/dalaran-wow#4478]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**:  Npc http://wotlk.openwow.com/npc=20090  is missing his SAI.
![image](https://cloud.githubusercontent.com/assets/6797611/23330778/b0ed40ec-fb5f-11e6-8172-b3306bd88315.png)

My suggestion is:
``` sql
DELETE FROM `creature_text` WHERE `entry` = 20090;
INSERT INTO `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `BroadcastTextId`, `TextRange`, `comment`) VALUES
(20090,0,0,'You are spotted by the %s!',16,0,100,0,0,0,0,0,'');

-- Bloodscale Sentry SAI
SET @ENTRY := 20090;
UPDATE `creature_template` SET `AIName`="SmartAI" WHERE `entry`=@ENTRY;
DELETE FROM `smart_scripts` WHERE `entryorguid`=@ENTRY AND `source_type`=0;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(@ENTRY,0,0,0,2,0,100,0,0,25,20000,20000,39,50,1,0,0,0,0,11,0,30,0,0,0,0,0,"Bloodscale Sentry - Between 0-25% Health - Call For Help"),
(@ENTRY,0,1,0,4,0,100,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,"Bloodscale Sentry - On Aggro - Say Line 0");
```
Additional information:

> By uigrad (6,177 – 1·3·57) on 2007/02/13 (Patch 2.0.7)		
> These things are nasty. They'll "call for help" when they get low on hp, and I've seen as many as 9 creatures around come running.
> 
> Make sure to draw them far away from everything else, unless you are ready to do some major AoE

How it looks like:
![image](https://cloud.githubusercontent.com/assets/6797611/23331015/ca26e6c0-fb65-11e6-97cd-3c5f94976fbf.png)

**Comment by Teridan-dal-wow** [comment]
Also when you engage him he is suppose to play an emote:
![image](https://cloud.githubusercontent.com/assets/6797611/23330981/3e350b9c-fb65-11e6-8ff5-df4add34b21f.png)

Updated first post with that.

**Comment by Rushor** [comment]
DB/Creature: Bloodscale Sentry - Add aggrotext and Call For Help at 25 percent

* closes: https://github.com/dalaranwow/dalaran-wow/issues/4478
* commit: 246adb5d517488f940a368be0a3d53bed385dadb

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
