### ISSUE TITLE
Quest: The Chain Gun And You

### ISSUE THREAD

**Issue by Warlockboss** [dalaranwow/dalaran-wow#448]
This is a quest in Dragonblight. You have to use 7th Legion Chain Gun vehicle. Use abilities to call and defend injured soldiers. Now when you use call for a soldier he appears behind you and stays here, of course none credit is given for that.
video http://www.youtube.com/watch?v=oMEfAy62s0M
http://www.wowhead.com/quest=12457

**Comment by Lothloryen** [comment]
Working properly since long time ago.
