### ISSUE TITLE
[NPC][TBC] Bloodscale Overseer, missing emote

### ISSUE THREAD

**Issue by Teridan-dal-wow** [dalaranwow/dalaran-wow#4480]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Npc http://wotlk.openwow.com/npc=20088 is missing an emote on aggro and he is not calling for help.

**Expected behaviour**: Npc http://wotlk.openwow.com/npc=20088 is suppose to ask nearby slaves (npc http://wotlk.openwow.com/npc=18123 ) for help on aggro and there should be an emote saying that.
Screenshot from retail:
![image](https://cloud.githubusercontent.com/assets/6797611/23331343/7c7226f4-fb6c-11e6-81e2-089a7e4e4f71.png)

My suggestion:
``` sql
DELETE FROM `creature_text` WHERE `entry` = 20088;
INSERT INTO `creature_text` (`entry`, `groupid`, `id`, `text`, `type`, `language`, `probability`, `emote`, `duration`, `sound`, `BroadcastTextId`, `TextRange`, `comment`) VALUES
(20088,0,0,'%s calls for a nearby slave to assist him!',16,0,100,0,0,0,0,0,'');


-- Bloodscale Overseer SAI
SET @ENTRY := 20088;
UPDATE `creature_template` SET `AIName`="SmartAI" WHERE `entry`=@ENTRY;
DELETE FROM `smart_scripts` WHERE `entryorguid`=@ENTRY AND `source_type`=0;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(@ENTRY,0,0,0,0,0,100,0,2000,2000,5000,5000,11,9080,0,0,0,0,0,2,0,0,0,0,0,0,0,"Bloodscale Overseer - In Combat - Cast 'Hamstring' (Phase 1) (No Repeat)"),
(@ENTRY,0,1,0,0,0,100,0,5000,5000,10000,10000,11,34812,0,0,0,0,0,2,0,0,0,0,0,0,0,"Bloodscale Overseer - In Combat - Cast 'Curse of Nazjatar' (Phase 1) (No Repeat)"),
(@ENTRY,0,2,0,0,0,100,0,0,0,25000,25000,39,20,0,0,0,0,0,10,0,18123,0,0,0,0,0,"Bloodscale Overseer - In Combat - Call For Help"),
(@ENTRY,0,3,0,0,0,100,0,0,0,25000,25000,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,"Bloodscale Overseer - In Combat - Say Line 0");
```
How it looks like:
![image](https://cloud.githubusercontent.com/assets/6797611/23331519/5bfa367e-fb70-11e6-87f7-7f758efa937b.png)

**Comment by TheRealestMcCoy** [comment]
Are the Wrekt Slaves connected to the Overseer. And if you kill the Overseer does slaves turn yellow and run alway?

**Comment by Teridan-dal-wow** [comment]
Connected as if they are linked together, no. I can kill the overseer but the slaves will still continue to fight with me.
![image](https://cloud.githubusercontent.com/assets/6797611/23332786/29bf3c8c-fb88-11e6-9323-7b7c1e999455.png)

The behaviour that you are talking about happens in the dungeons, but not in the open world (to my knowledge).

**Comment by Rushor** [comment]
on aggro event can also be used here :)

```sql
-- Bloodscale Overseer SAI
SET @ENTRY := 20088;
UPDATE `creature_template` SET `AIName`="SmartAI" WHERE `entry`=@ENTRY;
DELETE FROM `smart_scripts` WHERE `entryorguid`=@ENTRY AND `source_type`=0;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(@ENTRY,0,0,0,0,0,100,0,2000,2000,5000,5000,11,9080,0,0,0,0,0,2,0,0,0,0,0,0,0,"Bloodscale Overseer - In Combat - Cast 'Hamstring'"),
(@ENTRY,0,1,0,0,0,100,0,5000,5000,10000,10000,11,34812,0,0,0,0,0,2,0,0,0,0,0,0,0,"Bloodscale Overseer - In Combat - Cast 'Curse of Nazjatar'"),
(@ENTRY,0,2,0,4,0,100,0,0,0,0,0,39,20,0,0,0,0,0,10,0,18123,0,0,0,0,0,"Bloodscale Overseer - On Aggro - Call For Help"),
(@ENTRY,0,3,0,0,0,100,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,"Bloodscale Overseer - In Combat - Say Line 0");
```

**Comment by Teridan-dal-wow** [comment]
Hm, i do have on aggro script on my side, think i worked after posting the initial report and changed it, but forgot to update it here. Yes on aggro is better.

**Comment by Rushor** [comment]
DB/Creature: Bloodscale Overseer - Add aggrotext and Call For Help

* closes: https://github.com/dalaranwow/dalaran-wow/issues/4480
* commit: d30df80fda2bdf23e4f710b7e7851a6628059aab

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
