### ISSUE TITLE
[NPC][TBC] Wrekt Slave, missing spell

### ISSUE THREAD

**Issue by Teridan-dal-wow** [dalaranwow/dalaran-wow#4482]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Npc http://wotlk.openwow.com/npc=18123 is not casting spell http://wotlk.openwow.com/spell=34789

**Expected behaviour**: The slave is suppose to cast spell http://wotlk.openwow.com/spell=34789 on aggro on himself and one 1 more slave near him ( at ~ 20 yards max distance) with visual effect between them. It is possible that one slave is in combat (who casts the spell) and one isn't, the result will be that the second one won't enter combat from that spell, but as soon as he recive a part of that shared damage, he will engage.

This is how it should look like (screenshot from retail):
![image](https://cloud.githubusercontent.com/assets/6797611/23332896/305091de-fb8a-11e6-9488-1f95b130ca45.png)

All slaves are suppose to run (at sub 15% hp) for help.

**Comment by Teridan-dal-wow** [comment]
For the flee part this should work:
``` sql
-- Wrekt Slave SAI
SET @ENTRY := 18123;
UPDATE `creature_template` SET `AIName`="SmartAI" WHERE `entry`=@ENTRY;
DELETE FROM `smart_scripts` WHERE `entryorguid`=@ENTRY AND `source_type`=0;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(@ENTRY,0,0,0,0,0,100,0,100,100,4000,4000,11,11978,0,0,0,0,0,2,0,0,0,0,0,0,0,"Wrekt Slave - In Combat - Cast 'Kick' (Phase 1) (No Repeat)"),
(@ENTRY,0,1,0,4,0,100,1,0,0,0,0,11,36167,0,0,0,0,0,1,18123,10,0,0,0,0,0,"Wrekt Slave - On Aggro - Cast 'Shared Bonds' (No Repeat)"),
(@ENTRY,0,2,0,2,0,100,0,0,15,60000,60000,25,1,0,0,0,0,0,1,0,0,0,0,0,0,0,"Wrekt Slave - Between 0-15% Health - Flee For Assist");
```

**Comment by TheRealestMcCoy** [comment]
so there was a flee just not turning neutral?

**Comment by Teridan-dal-wow** [comment]
No, the flee wasn't related to what you said in the other issue, they flee when they drop to sub 15% hp, its not releted to the overseer.

**Comment by Rushor** [comment]
DB/Creature: Dreghood Drudge + Wrekt Slave - Add damagesplit and Flee For Assist

* closes: https://github.com/dalaranwow/dalaran-wow/issues/4482
* commit: a8e89886a9e36689fb8d891feb418b875c7b7aa0

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by Teridan-dal-wow** [comment]
> Add damagesplit

How if i may ask? :)

**Comment by Rushor** [comment]
the condition for the entry was missing + the flag for spell to be castable while moving
