### ISSUE TITLE
[Quest] The Book of Ur - long respawn time

### ISSUE THREAD

**Issue by warcraftgeekygamer** [dalaranwow/dalaran-wow#4495]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**:  The [Book of Ur](http://wotlk.evowow.com/?item=6283) has an extremely long re-spawn timer on it. This item is found inside [Shadowfang Keep](http://wowwiki.wikia.com/wiki/Shadowfang_Keep_(original)) located in [Silverpine Forest](http://wotlk.evowow.com/?zone=130). The quest begins with NPC [Keeper Bel'dugur](http://wotlk.evowow.com/?npc=2934) and ends with NPC [Keeper Bel'dugur](http://wotlk.evowow.com/?npc=2934). Once the [Book of Ur](http://wotlk.evowow.com/?item=6283#objective-of-quest) has been looted by one player, the remaining players must wait for up to 15 minutes or longer before the book will re-spawn.

**Expected behaviour**:  Players should not be waiting up to 15 minutes in between each re-spawn. When a player has retrieved the [Book of Ur](http://wotlk.evowow.com/?item=6283#objective-of-quest), this book should re-spawn after a period of a few seconds.

**Steps to reproduce the problem**:

1.  Level to 26
2. Speak to [Keeper Bel'dugur](http://wotlk.evowow.com/?npc=2934) located in the inner-ring of the Apothocareum in the Undercity
3. Obtain quest [The Book of Ur](http://wotlk.evowow.com/?quest=1013) from [Keeper Bel'dugur](http://wotlk.evowow.com/?npc=2934)
4. Travel to Shadowfang Keep located in Silverpine Forest
5. Advance through the dungeon until you arrive at [Fenrus the Devourer](http://wotlk.evowow.com/?npc=4274)
6. Loot the [Book of Ur](http://wotlk.evowow.com/?item=6283)
7. Observe for up to 15 minutes or longer as the book re-spawns

**Include proofs for this behaviour**

http://www.wowhead.com/quest=1013/the-book-of-ur#comments
http://wowwiki.wikia.com/wiki/Quest:The_Book_of_Ur
http://wowwiki.wikia.com/wiki/The_Book_of_Ur

Unfortunately, Youtube does not have a video for this quest.

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

game object: [6283](http://wotlk.evowow.com/?item=6283)

**Comment by Rushor** [comment]
duplicate https://github.com/dalaranwow/dalaran-wow/issues/2230  The fix needs to be tested on PTR

**Comment by warcraftgeekygamer** [comment]
It does appear that this is duplicate. However, it does not change the fact that this needs to be corrected. How do we test this on PTR?

**Comment by Rushor** [comment]
you cannot test it. read what i wrote in the linked issue and read the bugtracker instructions first. thanks.

> The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
> This means that the issue exists in game at the moment i wrote this message.
> Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
> Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

> However, it does not change the fact that this needs to be corrected. 

If you copy an issue that was already reported in this issue https://github.com/dalaranwow/dalaran-wow/issues/2230 ( <- KLICK ON THAT LINK) than it's simply useless.
