### ISSUE TITLE
[Mage] Game/Spells: Update Blink mechanic ofTARGET_DEST_CASTER_FRONT_LEAP

### ISSUE THREAD

**Issue by Rushor** [dalaranwow/dalaran-wow#4496]
* blink in abyss
*  blink by path ( rechecking each step )
* where player can walk - blink will available there
* implemented check on dynamic objects (locked doors and etc)
*  implemented total path of blink.

**Comment by Rushor** [comment]
* commit: ec36765e9a9d38ee42367bfb6b5f9401159ec2df

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by TeridanDW** [comment]
Related report #2495
