### ISSUE TITLE
[Quest]Northrend] Bring 'Em Back Alive - Wrong NPC spawn

### ISSUE THREAD

**Issue by Rushor** [dalaranwow/dalaran-wow#4498]
NPC guid 95550 and 95521 are both spawned really close to the questgiver.

according to https://youtu.be/ZhmDRtQw8yI?t=105 there should be no swine near the questgiver.

**Comment by Rushor** [comment]
DB/Creature: Remove 2 wrong Unliving Swine spawns

* closes: https://github.com/dalaranwow/dalaran-wow/issues/4498
* commit: 7936591c8d2612784418a0b0bbd7ef6875ac2326

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by TeridanDW** [comment]
Hello, just letting you know that all creatures in this area were checked and moved/deleted in #4555. I would like to ask this commit to not be applied on PTR as it might break part of #4555.
Thank you.
