### ISSUE TITLE
[NPC][WotlK] Thalgran Blightbringer, missing emote

### ISSUE THREAD

**Issue by Teridan-dal-wow** [dalaranwow/dalaran-wow#4506]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Npc http://wotlk.openwow.com/npc=28443 is missing an emote.
![image](https://cloud.githubusercontent.com/assets/6797611/23461599/3f6741a2-fe93-11e6-9053-f7d46a2e1fa5.png)

**Expected behaviour**: He should look like this:
![image](https://cloud.githubusercontent.com/assets/6797611/23461646/6bb000a0-fe93-11e6-82f7-481c754201cd.png)

Tried with creature_addon aura but didn't work for me, but this did:
``` sql
-- Thalgran Blightbringer SAI
SET @ENTRY := 28443;
UPDATE `creature_template` SET `AIName`="SmartAI" WHERE `entry`=@ENTRY;
DELETE FROM `smart_scripts` WHERE `entryorguid`=@ENTRY AND `source_type`=0;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(@ENTRY,0,0,0,1,0,100,1,0,0,0,0,11,26047,0,0,0,0,0,1,0,0,0,0,0,0,0,"Thalgran Blightbringer - Out of Combat - Cast 'Birth' (No Repeat)"),
(@ENTRY,0,1,0,0,0,100,0,13000,19000,15000,25000,11,51854,0,0,0,0,0,5,0,0,0,0,0,0,0,"Thalgran Blightbringer - In Combat - Cast 'Deathbolt' (No Repeat)"),
(@ENTRY,0,2,0,0,0,100,0,4000,7000,9000,17000,11,54210,1,0,0,0,0,5,0,0,0,0,0,0,0,"Thalgran Blightbringer - In Combat - Cast 'Rain of Fire' (No Repeat)"),
(@ENTRY,0,3,0,25,0,100,0,0,0,0,0,11,51841,0,0,0,0,0,1,0,0,0,0,0,0,0,"Thalgran Blightbringer - On Reset - Cast 'Blightbringer'");
```

**Comment by Rushor** [comment]
i will also update the combattimer for him, since he often selfinterrupts his own spells on cast

**Comment by Rushor** [comment]
okay i had to move this to an actionlist

```sql
-- Actionlist SAI
SET @ENTRY := 2844300;
DELETE FROM `smart_scripts` WHERE `entryorguid`=@ENTRY AND `source_type`=9;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(@ENTRY,9,0,0,0,0,100,0,6000,6000,0,0,11,51841,0,0,0,0,0,1,0,0,0,0,0,0,0,"Thalgran Blightbringer - On Script - Cast 'Blightbringer'");
```

since the cast of birth would not be displayed if the cast of 'Blightbringer' is called in reset + i moved the cast of 'Birth' to "EVENT_RESPAWN" since that emerge event should only happen on spawn of the creature

**Comment by Rushor** [comment]
DB/Creature: Thalgran Blightbringer - Update combattimer, move Cast 'Birth' to Respawn, add Cast 'Blightbringer' after 6 seconds after spawn

* closes: https://github.com/dalaranwow/dalaran-wow/issues/4506
* commit: 54afc30d28a7bf386fa2ae8ed6aa98db4b1e3ca0

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
