### ISSUE TITLE
[NPC][Classic] Remove wrong Dark Iron Text from Horde Scout (It should only say 'Time to die, $C.')

### ISSUE THREAD

**Issue by Rushor** [dalaranwow/dalaran-wow#4515]
http://wotlk.openwow.com/npc=11680

should not tell the Dark Iron Texts

**Comment by Rushor** [comment]
DB/Creature: Remove wrong Dark Iron Text from Horde Scout (It should only say 'Time to die, $C.')

* commit: f0efb64cfb321d41d92686c7f8c168ac765a6043

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by TeridanDW** [comment]
Works as intended on PTR.
