### ISSUE TITLE
[NPC][WotlK] Venomtip, Monte Muzzleshot, Pitch

### ISSUE THREAD

**Issue by Teridan-dal-wow** [dalaranwow/dalaran-wow#4523]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: 
Npc http://wotlk.openwow.com/npc=28358 is missing his path
Npc http://wotlk.openwow.com/npc=27987 has wrong state
Npc http://wotlk.openwow.com/npc=28097 is missing some elements of his SAI

**Expected behaviour**: 
Venomtip - added paths with delay  + 1  Bonescythe Ravager that i missed - done.
Monte Muzzleshot - appears stuned he should look like this:
![image](https://cloud.githubusercontent.com/assets/6797611/23566063/f73784c4-0058-11e7-8071-aee746edaef7.png)
but it looks like that:
![image](https://cloud.githubusercontent.com/assets/6797611/23566085/0a4175e8-0059-11e7-8a5d-386cd33efd41.png)

The problem here - sniff says he used emotestate 483 (TC doesn't have info for this one) and spell http://wotlk.openwow.com/spell=50544 has effect 1 stun, which seems to cause the problem.
I tryed using emote 383 as it looks exacly like on retail however after i start server the npc seems stunned again, i have zone out of the area and back in and then it looks as it should. On relog same problem happens (needs a rezone to look correct).
Also tryed with SAI , same effect as above.

Npc http://wotlk.openwow.com/npc=28097 is missing an emote out of combat - added
There is a missing mini event too. Video of the mini event only:
https://www.youtube.com/watch?v=J9muUTYs2tQ&feature=youtu.be

The guards has SAI and i don't want to break it, but the  speech from npc http://wotlk.openwow.com/npc=28095 seems to be working however the timing it wrong.

He should say when out of combat one of these texts every 15 secs randomly:
[20:47:37] Tracker Gekgek says: Careful! NO let it scratch you LIKE LAST TIME
[20:47:52] Tracker Gekgek says: Dumb! Don't shoot AT it! Gekgek want trophy IN ONE piece!
[20:48:52] Tracker Gekgek says: No let it get away! We got it this time.
[20:49:07] Tracker Gekgek says: Gekgek finally trap dumb cat. You Gekgek's NOW!

The spell that pitch uses to fear the guards is http://wotlk.openwow.com/spell=51344
```

**Comment by Teridan-dal-wow** [comment]
Will add 1 more npc here:
Npc http://wotlk.openwow.com/npc=28217 should have 6 spawns, currently there are 5 spawned. The missing one should be here:
![wowscrnshot_030317_221127](https://cloud.githubusercontent.com/assets/6797611/23567406/c2eb2d46-005e-11e7-8448-00153b20eb8c.jpg)

Added the missing spawn. As this npc is part of escort quest it will need a path, however you can copy the path of the one right next time him and modify the first wp.
 Sniff says all 6 of them should have spell http://wotlk.openwow.com/spell=51329 on spawn. Checked their SAI and its there:
``` sql
-- Injured Rainspeaker Oracle SAI
SET @ENTRY := 28217;
UPDATE `creature_template` SET `AIName`="SmartAI" WHERE `entry`=@ENTRY;
DELETE FROM `smart_scripts` WHERE `entryorguid`=@ENTRY AND `source_type`=0;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(@ENTRY,0,0,1,11,0,100,512,0,0,0,0,11,51329,2,0,0,0,0,1,0,0,0,0,0,0,0,"Injured Rainspeaker Oracle - On Respawn - Cast 'Feign Death'"),
(@ENTRY,0,1,14,61,0,100,512,0,0,0,0,81,1,0,0,0,0,0,1,0,0,0,0,0,0,0,"Injured Rainspeaker Oracle - On Respawn - Set Npc Flag Gossip"),
(@ENTRY,0,2,3,62,0,100,0,9677,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,"Injured Rainspeaker Oracle - On Gossip Option Select - Say Line 1"),
(@ENTRY,0,3,4,61,0,100,512,0,0,0,0,28,51329,0,0,0,0,0,1,0,0,0,0,0,0,0,"Injured Rainspeaker Oracle - On Gossip Option Select - Remove Aura - Feign Death"),
(@ENTRY,0,4,5,61,0,100,512,0,0,0,0,81,3,0,0,0,0,0,1,0,0,0,0,0,0,0,"Injured Rainspeaker Oracle - On Gossip Option Select - Remove Aura - Set NPC Flags - Quest + Gossip"),
(@ENTRY,0,5,15,61,0,100,512,0,0,0,0,72,0,0,0,0,0,0,7,0,0,0,0,0,0,0,"Injured Rainspeaker Oracle - On Gossip Option Select - Close Gossip"),
(@ENTRY,0,6,0,62,0,100,0,9677,0,0,0,85,51382,2,0,0,0,0,7,0,0,0,0,0,0,0,"Injured Rainspeaker Oracle - On Gossip Option Select - Invoker Cast Forcecast Summon Huge Crocolisk"),
(@ENTRY,0,7,0,64,0,100,512,0,0,0,0,98,9684,13124,0,0,0,0,7,0,0,0,0,0,0,0,"Injured Rainspeaker Oracle - On Gossip Hello - Send Gossip Menu"),
(@ENTRY,0,8,10,62,0,100,512,9684,0,0,0,2,774,0,0,0,0,0,1,0,0,0,0,0,0,0,"Injured Rainspeaker Oracle - On Gossip Option Select - Set Faction (Alliance)"),
(@ENTRY,0,9,10,62,0,100,512,9684,0,0,0,2,775,0,0,0,0,0,1,0,0,0,0,0,0,0,"Injured Rainspeaker Oracle - On Gossip Option Select - Set Faction (Horde)"),
(@ENTRY,0,10,11,61,0,100,512,0,0,0,0,64,1,0,0,0,0,0,7,0,0,0,0,0,0,0,"Injured Rainspeaker Oracle - On Gossip Option Select - Store Targetlist"),
(@ENTRY,0,11,0,61,0,100,512,0,0,0,0,80,@ENTRY*100+00,2,0,0,0,0,1,0,0,0,0,0,0,0,"Injured Rainspeaker Oracle - On Gossip Option Select - Run Script"),
(@ENTRY,0,12,0,19,0,100,0,12570,0,0,0,1,1,0,0,0,0,0,1,0,0,0,0,0,0,0,"Injured Rainspeaker Oracle - On On Quest Accept - Fortunate Misunderstandings - Say Line 2"),
(@ENTRY,0,13,0,40,0,100,512,64,28217,0,0,80,@ENTRY*100+01,2,0,0,0,0,1,0,0,0,0,0,0,0,"Injured Rainspeaker Oracle - On Reached WP80 - Run Script"),
(@ENTRY,0,14,0,61,0,100,512,0,0,0,0,11,58806,0,0,0,0,0,1,0,0,0,0,0,0,0,"Injured Rainspeaker Oracle - On Respawn - Cast 'Permanent Feign Death (Drowned Anim)'"),
(@ENTRY,0,15,0,61,0,100,512,0,0,0,0,28,58806,0,0,0,0,0,1,0,0,0,0,0,0,0,"Injured Rainspeaker Oracle - On Gossip Select - Remove Aura Permanent Feign Death");
```
But ingame the animation is missing ?
![image](https://cloud.githubusercontent.com/assets/6797611/23567931/2886f408-0061-11e7-896c-43d8b16e9099.png)

**Comment by Teridan-dal-wow** [comment]
Regarding

> He should say when out of combat one of these texts every 15 secs randomly:

maybe this spell has something to do with it - http://wotlk.openwow.com/spell=52162

**Comment by Rushor** [comment]
concerning the emote it needs to be fixed in core first https://github.com/TrinityCore/TrinityCore/issues/15873

**Comment by Rushor** [comment]
DB/Creature: Several changes for Venomtip, Monte Muzzleshot, Pitch

* Add pathing for Bonescythe Ravager, Venomtip
* Add correct emotestate for Monte Muzzleshot 
* Add Emote and Event for Pitch,Frenzyheart Tracker and Tracker Gekgek
* Update Texts and Timer for Tracker Gekgek
* Add fake death emote for Injured Rainspeaker Oracle and one missing spawn
* closes: https://github.com/dalaranwow/dalaran-wow/issues/4523
* commit: 65b7a1edcd278342c8a0d1150bdbf8e5320866cb

![GitHub Logo](http://i.imgur.com/fCeWC4C.jpg)
![GitHub Logo](http://i.imgur.com/XZ0u6pl.jpg)
![GitHub Logo](http://i.imgur.com/ECnKMdY.jpg)
![GitHub Logo](http://i.imgur.com/N3TEU5p.jpg)
![GitHub Logo](http://i.imgur.com/kNmmR6M.jpg)

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
