### ISSUE TITLE
Quest: Redemption

### ISSUE THREAD

**Issue by Golganeth** [dalaranwow/dalaran-wow#453]
http://wotlk.openwow.com/quest=5742

**Issue:** Upon picking up the quest, the NPC doesn't offer any option to start the dialogue.

* *Tirion Fordring* - http://wotlk.openwow.com/npc=1855

**Comment by Golganeth** [comment]
The quest is doable but doesn't have an intended behavior. I couldn't find a single proof or evidence stating you have to /sit. Considering it's a very specific mechanic it's impossible it worked like that on retail.

http://www.wowhead.com/quest=5742#comments - No one mentions it
https://www.youtube.com/watch?v=Fiu_sVevUyw - Triggering the gossip while mounted

**Comment by Demlock** [comment]
Confirmed. Can also confirm that there were no comments till now on any of the major WoW knowledge databases about character and /sit mechanic.

**Comment by Rushor** [comment]
c80c86868c8e6468955b11764e886fc618a4017e
- sitcondition removed
