### ISSUE TITLE
[ZonePhasing][IceCrown]Shadow Vaults

### ISSUE THREAD

**Issue by TheRealestMcCoy** [dalaranwow/dalaran-wow#4531]
**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
SO Shadow Vaults has alot of phasing issues when doing the quests. Each time you complete a quest it phases to the final phase. Picking up the next quest changes the phase to the final phase. So you have to fly away and come back to get to the proper phase.
**Expected behaviour**: Tell us what should happen instead
The zone should not final phase till the last quest.
**Steps to reproduce the problem**:

1. GO to shadow vault
2. Start its all fun and games
3. kill the eye notice you are in final phase

**Include proofs for this behaviour**

You can research this on several pages like http://wowhead.com or http://wowwiki.wikia.com or http://www.youtube.com/
Issues without proofs will be closed and tag On Hold will be added until the proof is provided.

In this screen shot you can see the chat message showing me just turning in the first quest with the area phasing.
![wowscrnshot_030617_001356](https://cloud.githubusercontent.com/assets/12252441/23597558/db61c26e-0201-11e7-9ff8-671dbe4f6fae.jpg)

I have more screen shots in between quests if needed.
**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

I will list of all the quest in this quest line.
http://www.wowhead.com/quest=12887/its-all-fun-and-games
http://www.wowhead.com/quest=12891/i-have-an-idea-but-first
http://www.wowhead.com/quest=12893/free-your-mind
http://www.wowhead.com/quest=12896/if-he-cannot-be-turned
http://www.wowhead.com/quest=12898/the-shadow-vault (This quest should cause the final phase to unlock this reputaion faction.)

You can research this on several pages like http://wotlk.openwow.com or http://wowhead.com/

**Include Screenshots from the issue if necessary**

**Comment by Rushor** [comment]
already works fine on PTR. The phase update is handled like that:

```sql
INSERT INTO `spell_area` (`spell`, `area`, `quest_start`, `quest_end`, `aura_spell`, `racemask`, `gender`, `autocast`, `quest_start_status`, `quest_end_status`) VALUES (30181, 4477, 0, 12896, 0, 1101, 2, 1, 64, 11);
INSERT INTO `spell_area` (`spell`, `area`, `quest_start`, `quest_end`, `aura_spell`, `racemask`, `gender`, `autocast`, `quest_start_status`, `quest_end_status`) VALUES (30181, 4477, 0, 12897, 0, 690, 2, 1, 64, 11);
```

![GitHub Logo](http://i.imgur.com/sMi9Efp.jpg)

**Comment by TheRedSpark** [comment]
Is there a way to force phase into the final stage so I could turn in "Vandalizing Jotunheim" quest.I have no quest to pick up so I can't phase into the final stage.Stuck in the 1st stage where everything is aggressive in the vault.

**Comment by Rushor** [comment]
Please write an Ingame-issue to a Gamemaster and the Gamemaster will then help you as soon as he can. Thank you.

![GitHub Logo](http://i.imgur.com/bYkYeGQ.png)
