### ISSUE TITLE
[Quest][WotlK] Oracle's fraction chain is broken.

### ISSUE THREAD

**Issue by Flowneee** [dalaranwow/dalaran-wow#4537]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: After killing [Artruis the Heartless](http://www.wowhead.com/npc=28659/artruis-the-heartless), 1 NPC alive left (Oracle or Frenzyheart, depends on what fraction you want), which complete daily quest (for Oracles it is ["Hand of the Oracles"](http://www.wowhead.com/quest=12689/hand-of-the-oracles)), and after that next quest don't appear.

Video how it works now: https://www.youtube.com/watch?v=KG8hHRSJbJM

**Expected behaviour**: After completing ["Hand of the Oracles"](http://www.wowhead.com/quest=12689/hand-of-the-oracles), same NPC should give next quest ["Return of the friendly Dryskin"](http://www.wowhead.com/quest=12695/return-of-the-friendly-dryskin).

Video how it should work (since 1:52): https://www.youtube.com/watch?v=7CEzuqPHnIQ

**Steps to reproduce the problem**:

1. Kill [Artruis the Heartless](http://www.wowhead.com/npc=28659/artruis-the-heartless) (save Oracle during encounter).
2. Complete ["Hand of the Oracles"](http://www.wowhead.com/quest=12689/hand-of-the-oracles).
3. No further quest.

**Realm**: Algalon.

**P.S.**

I have a reports from other players that Frenzyheart Tribe chain broken aswell, good if someone can prove it.

**Comment by Senjan92** [comment]
Can confirm Flowneee's report. No such quest was available for me after choosing to spare the Frenzyheart one. I got the reputation back to Honored as intended, but returning back to the base granted me no new daily quests as promised from the retail counterpart.

**Comment by Teridan-dal-wow** [comment]
Hello. Could you tell us on which realm is this happening? Did the encounter worked like on the video you linked? Thanks.

This on working fine on my server.
![image](https://cloud.githubusercontent.com/assets/6797611/23622129/229c3886-02a6-11e7-85ed-7bae271b401b.png)

**Comment by pharZyde** [comment]
Can confirm Flowneee's report. I had the same problem. I turned in the quest "A Hero's Burden" after killing Artruis the Heartless and sparing Jaloot's life. Afterwards I could turn in the quest "Hand of the Oracles" for Jaloot but i never got the quest "Return of the Friendly Dryskin" (the quest you are supposed to get by Jaloot, travel back to the oracles village and get the dailies afterwards)

**Comment by Senjan92** [comment]
This is on Algalon (main realm, right?). And yeah we're alliance if that helps.

Hey Teridan-dal-wow, does the Frenzyheart quests work for you if you choose to spare the other guy instead? I'm talking about those dailies that should pop up in their base camp.

**Comment by Teridan-dal-wow** [comment]
Ok, here is what i found so far, the encounter works correctly for me too. Once you drop npc http://wotlk.openwow.com/npc=28659 to 30% the player has to choose which npc (http://wotlk.openwow.com/npc=28667 or http://wotlk.openwow.com/npc=28668) to kill. 
After you kill http://wotlk.openwow.com/npc=28659 the npc you choose will go to its spawn location and should offer quest for oracles quest http://wotlk.openwow.com/quest=12689 or for frenzyheart http://wotlk.openwow.com/quest=12582 however both of these quests are not offered.

The sai for both creatures seems fine to me:
``` sql
-- Zepik the Gorloc Hunter SAI
SET @ENTRY := 28668;
UPDATE `creature_template` SET `AIName`="SmartAI" WHERE `entry`=@ENTRY;
DELETE FROM `smart_scripts` WHERE `entryorguid`=@ENTRY AND `source_type`=0;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(@ENTRY,0,0,1,11,0,100,513,0,0,0,0,81,0,0,0,0,0,0,1,0,0,0,0,0,0,0,"Zepik the Gorloc Hunter - On Respawn - Set Npc Flag  (No Repeat)"),
(@ENTRY,0,1,2,61,0,100,513,0,0,0,0,18,512,0,0,0,0,0,1,0,0,0,0,0,0,0,"Zepik the Gorloc Hunter - On Respawn - Set Flag Immune To NPC's (No Repeat)"),
(@ENTRY,0,2,0,61,0,100,512,0,0,0,0,11,52182,0,0,0,0,0,1,0,0,0,0,0,0,0,"Zepik the Gorloc Hunter - On Respawn - Cast 'Tomb of the Heartless' (No Repeat)"),
(@ENTRY,0,3,4,38,0,100,512,1,1,0,0,2,14,0,0,0,0,0,1,0,0,0,0,0,0,0,"Zepik the Gorloc Hunter - On Data Set 1 1 - Set Faction 14"),
(@ENTRY,0,4,5,61,0,100,512,0,0,0,0,28,52182,0,0,0,0,0,1,0,0,0,0,0,0,0,"Zepik the Gorloc Hunter - On Data Set 1 1 - Remove Aura 'Tomb of the Heartless'"),
(@ENTRY,0,5,0,61,0,100,512,0,0,0,0,49,0,0,0,0,0,0,18,40,0,0,0,0,0,0,"Zepik the Gorloc Hunter - On Data Set 1 1 - Start Attacking"),
(@ENTRY,0,6,7,38,0,100,512,1,2,0,0,2,250,0,0,0,0,0,1,0,0,0,0,0,0,0,"Zepik the Gorloc Hunter - On Data Set 1 2 - Set Faction 250"),
(@ENTRY,0,7,8,61,0,100,512,0,0,0,0,18,512,0,0,0,0,0,1,0,0,0,0,0,0,0,"Zepik the Gorloc Hunter - On Data Set 1 2 - Set Flag Immune To NPC's"),
(@ENTRY,0,8,0,61,0,100,512,0,0,0,0,11,52182,0,0,0,0,0,1,0,0,0,0,0,0,0,"Zepik the Gorloc Hunter - On Data Set 1 2 - Cast 'Tomb of the Heartless'"),
(@ENTRY,0,9,0,6,0,100,512,0,0,0,0,45,1,2,0,0,0,0,10,202971,28659,0,0,0,0,0,"Zepik the Gorloc Hunter - On Just Died - Set Data 1 2"),
(@ENTRY,0,10,11,38,0,100,512,1,5,0,0,2,250,0,0,0,0,0,1,0,0,0,0,0,0,0,"Zepik the Gorloc Hunter - On Data Set 1 5 - Set Faction 250"),
(@ENTRY,0,11,12,61,0,100,512,1,5,0,0,19,512,0,0,0,0,0,1,0,0,0,0,0,0,0,"Zepik the Gorloc Hunter - On Data Set 1 5 - Remove Flag Immune To NPC's"),
(@ENTRY,0,12,13,61,0,100,512,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,"Zepik the Gorloc Hunter - On Data Set 1 5 - Say Line 0"),
(@ENTRY,0,13,14,61,0,100,512,0,0,0,0,49,0,0,0,0,0,0,10,202971,28659,0,0,0,0,0,"Zepik the Gorloc Hunter - On Data Set 1 5 - Start Attacking"),
(@ENTRY,0,14,0,61,0,100,512,0,0,0,0,28,52185,0,0,0,0,0,1,0,0,0,0,0,0,0,"Zepik the Gorloc Hunter - On Data Set 1 5 - Remove Aura 'Bindings of Submission'"),
(@ENTRY,0,15,16,38,0,100,512,1,4,0,0,2,250,0,0,0,0,0,1,0,0,0,0,0,0,0,"Zepik the Gorloc Hunter - On Data Set 1 4 - Set Faction 250"),
(@ENTRY,0,16,17,61,0,100,512,0,0,0,0,18,512,0,0,0,0,0,1,0,0,0,0,0,0,0,"Zepik the Gorloc Hunter - On Data Set 1 4 - Set Flag Immune To NPC's"),
(@ENTRY,0,17,18,61,0,100,512,1,4,0,0,81,2,0,0,0,0,0,1,0,0,0,0,0,0,0,"Zepik the Gorloc Hunter - On Data Set 1 4 - Set Npc Flag Questgiver"),
(@ENTRY,0,18,19,61,0,100,512,0,0,0,0,41,120000,0,0,0,0,0,1,0,0,0,0,0,0,0,"Zepik the Gorloc Hunter - On Data Set 1 4 - Despawn In 120000 ms"),
(@ENTRY,0,19,0,61,0,100,512,0,0,0,0,24,0,0,0,0,0,0,1,0,0,0,0,0,0,0,"Zepik the Gorloc Hunter - On Data Set 1 4 - Evade"),
(@ENTRY,0,20,0,9,0,100,0,0,20,15000,18000,11,52761,0,0,0,0,0,5,0,0,0,0,0,0,0,"Zepik the Gorloc Hunter - Within 0-20 Range - Cast 'Barbed Net'"),
(@ENTRY,0,21,0,9,0,100,0,5,30,12000,15000,11,52889,0,0,0,0,0,5,0,0,0,0,0,0,0,"Zepik the Gorloc Hunter - Within 5-30 Range - Cast 'Envenomed Shot'"),
(@ENTRY,0,22,0,9,0,100,0,0,5,15000,18000,11,52873,0,0,0,0,0,5,0,0,0,0,0,0,0,"Zepik the Gorloc Hunter - Within 0-5 Range - Cast 'Open Wound'"),
(@ENTRY,0,23,0,9,0,100,512,5,30,3000,7000,11,52758,2,0,0,0,0,5,0,0,0,0,0,0,0,"Zepik the Gorloc Hunter - Within 5-30 Range - Cast 'Piercing Arrow'"),
(@ENTRY,0,24,0,9,0,100,512,0,5,30000,40000,11,52886,2,0,0,0,0,5,0,0,0,0,0,0,0,"Zepik the Gorloc Hunter - Within 0-5 Range - Cast 'Spike Trap'"),
(@ENTRY,0,25,0,2,0,100,0,0,30,30000,30000,11,52895,0,0,0,0,0,1,0,0,0,0,0,0,0,"Zepik the Gorloc Hunter - Between 0-30% Health - Cast 'Bandage'");
```
and 
``` sql
-- Jaloot SAI
SET @ENTRY := 28667;
UPDATE `creature_template` SET `AIName`="SmartAI" WHERE `entry`=@ENTRY;
DELETE FROM `smart_scripts` WHERE `entryorguid`=@ENTRY AND `source_type`=0;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(@ENTRY,0,0,1,11,0,100,512,0,0,0,0,81,0,0,0,0,0,0,1,0,0,0,0,0,0,0,"Jaloot - On Respawn - Set Npc Flag "),
(@ENTRY,0,1,2,61,0,100,512,0,0,0,0,18,512,0,0,0,0,0,1,0,0,0,0,0,0,0,"Jaloot - On Respawn - Set Flag Immune To NPC's"),
(@ENTRY,0,2,0,61,0,100,512,0,0,0,0,11,52182,0,0,0,0,0,1,0,0,0,0,0,0,0,"Jaloot - On Respawn - Cast 'Tomb of the Heartless'"),
(@ENTRY,0,3,4,38,0,100,512,1,1,0,0,2,14,0,0,0,0,0,1,0,0,0,0,0,0,0,"Jaloot - On Data Set 1 1 - Set Faction 14"),
(@ENTRY,0,4,5,61,0,100,512,0,0,0,0,28,52182,0,0,0,0,0,1,0,0,0,0,0,0,0,"Jaloot - On Data Set 1 1 - Remove Aura 'Tomb of the Heartless'"),
(@ENTRY,0,5,0,61,0,100,512,0,0,0,0,49,0,0,0,0,0,0,18,40,0,0,0,0,0,0,"Jaloot - On Data Set 1 1 - Start Attacking"),
(@ENTRY,0,6,7,38,0,100,512,1,2,0,0,2,250,0,0,0,0,0,1,0,0,0,0,0,0,0,"Jaloot - On Data Set 1 2 - Set Faction 250"),
(@ENTRY,0,7,8,61,0,100,512,0,0,0,0,18,512,0,0,0,0,0,1,0,0,0,0,0,0,0,"Jaloot - On Data Set 1 2 - Set Flag Immune To NPC's"),
(@ENTRY,0,8,0,61,0,100,512,0,0,0,0,11,52182,0,0,0,0,0,1,0,0,0,0,0,0,0,"Jaloot - On Data Set 1 2 - Cast 'Tomb of the Heartless'"),
(@ENTRY,0,9,0,6,0,100,512,0,0,0,0,45,1,1,0,0,0,0,10,202971,28659,0,0,0,0,0,"Jaloot - On Just Died - Set Data 1 1"),
(@ENTRY,0,10,11,38,0,100,512,1,3,0,0,2,250,0,0,0,0,0,1,0,0,0,0,0,0,0,"Jaloot - On Data Set 1 3 - Set Faction 250"),
(@ENTRY,0,11,12,61,0,100,512,0,0,0,0,19,512,0,0,0,0,0,1,0,0,0,0,0,0,0,"Jaloot - On Data Set 1 3 - Remove Flag Immune To NPC's"),
(@ENTRY,0,12,13,61,0,100,512,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,"Jaloot - On Data Set 1 3 - Say Line 0"),
(@ENTRY,0,13,14,61,0,100,512,0,0,0,0,49,0,0,0,0,0,0,10,202971,28659,0,0,0,0,0,"Jaloot - On Data Set 1 3 - Start Attacking"),
(@ENTRY,0,14,0,61,0,100,512,0,0,0,0,28,52185,0,0,0,0,0,1,0,0,0,0,0,0,0,"Jaloot - On Data Set 1 3 - Remove Aura 'Bindings of Submission'"),
(@ENTRY,0,15,16,38,0,100,512,1,4,0,0,2,250,0,0,0,0,0,1,0,0,0,0,0,0,0,"Jaloot - On Data Set 1 4 - Set Faction 250"),
(@ENTRY,0,16,17,61,0,100,512,0,0,0,0,18,512,0,0,0,0,0,1,0,0,0,0,0,0,0,"Jaloot - On Data Set 1 4 - Set Flag Immune To NPC's"),
(@ENTRY,0,17,18,61,0,100,512,0,0,0,0,81,2,0,0,0,0,0,1,0,0,0,0,0,0,0,"Jaloot - On Data Set 1 4 - Set Npc Flag Questgiver"),
(@ENTRY,0,18,19,61,0,100,512,0,0,0,0,41,120000,0,0,0,0,0,1,0,0,0,0,0,0,0,"Jaloot - On Data Set 1 4 - Despawn In 120000 ms"),
(@ENTRY,0,19,0,61,0,100,512,0,0,0,0,24,0,0,0,0,0,0,1,0,0,0,0,0,0,0,"Jaloot - On Data Set 1 4 - Evade"),
(@ENTRY,0,20,0,9,0,100,0,0,5,15000,20000,11,52943,0,0,0,0,0,5,0,0,0,0,0,0,0,"Jaloot - Within 0-5 Range - Cast 'Lightning Whirl'"),
(@ENTRY,0,21,0,9,0,100,0,0,5,15000,18000,11,52944,0,0,0,0,0,5,0,0,0,0,0,0,0,"Jaloot - Within 0-5 Range - Cast 'Lightning Strike'"),
(@ENTRY,0,22,0,9,0,100,0,0,5,20000,25000,11,52964,0,0,0,0,0,5,0,0,0,0,0,0,0,"Jaloot - Within 0-5 Range - Cast 'Spark Frenzy'"),
(@ENTRY,0,23,0,2,0,100,0,0,30,9000,12000,11,52969,0,0,0,0,0,1,0,0,0,0,0,0,0,"Jaloot - Between 0-30% Health - Cast 'Energy Siphon'");
```

So wait for dev to look at this issue.
P.S. The first time it worked for me because i added manually the quest to my questlog, however the player can't do that.

**Comment by Teridan-dal-wow** [comment]
@Senjan92  Yes, I do get them after that:
![image](https://cloud.githubusercontent.com/assets/6797611/23626221/c3cdca22-02b4-11e7-8c40-0a0bc9235fa0.png)

**Comment by pharZyde** [comment]
Is it possible that a GM just "gives" us the needed quest into our quest log? So we do not have to wait until this issue is fixed

**Comment by Senjan92** [comment]
Welp, I went back there to double-check and redo it just in case I missed something. Just as I killed Artruis, a yellow question mark appears above the frenzyheart guy. I talk to him, and "deliver the quest" Frenzyheart Champion.

Afterwards, he has nothing to say to me. And Frenzyheart Hill has no quests of any sort to provide me.


<img src="http://imgur.com/Ro9bv6L" alt="image" style="max-width:100%;">

http://imgur.com/Ro9bv6L

**Comment by Rushor** [comment]
Also works fine on PTR. The fix  for it will be applied with further merges. Please contact a gamemaster that researches the current state of you questlog, your current reputation and you auras. If he find anything special he can give us the error causing spell/quest etc. If not he will add/reset teh quest for you.

Simply open an ingameticket for it. Thanks

![GitHub Logo](http://i.imgur.com/bYkYeGQ.png)

**Comment by Craftymind** [comment]
Hello,

Just to reconfirm what's happening in-live (Algalon server). I just finished the chain quests to unlock the Oracles reputation dailies, up to the quest "Hand of the Oracles" ( http://www.wowhead.com/quest=12689/hand-of-the-oracles ). But the NPC Jaloot ( http://www.wowhead.com/npc=28667/jaloot ) doesn't give me the last quest "Return of the Friendly Dryskin" ( http://www.wowhead.com/quest=12695/return-of-the-friendly-dryskin ) to return to Rainspeaker Canopy and unlock the dailies.

Here is a screenshot showing my reputation status and me completing the 1st mentioned quest and showing the bug:
![wowscrnshot_040517_141939](https://cloud.githubusercontent.com/assets/19840534/24708621/50c2d5c8-1a0f-11e7-815d-59588cac3078.jpg)

**Comment by Senjan92** [comment]
Unfortunate, we can only hope this gets seen by the in-game GMs anytime soon.

...Although my ticket has been ment to be "serviced soon" in soon exactly a month .__.'

**Comment by Craftymind** [comment]
Also, the 1st quest mentioned ( http://www.wowhead.com/quest=12689/hand-of-the-oracles ) seems to have not registered as completed: 
![wowscrnshot_040517_154518](https://cloud.githubusercontent.com/assets/19840534/24711301/70aa514c-1a17-11e7-952c-b3e04c199de9.jpg)

**Comment by ImprezaWoW** [comment]
Seemed to work fine for my character on Algalon, so I can not explain where is the issue. Would appreciate if someone recorded their issue, since there's definitely over 20 tickets with the issue that can not be replicated by everyone in the server. Unfortunately adding and completing the quest manually by a GM did not seem to work for players (at least I got that feedback), so the only way to get it to work for the people who have the issue is to figure where's the problem, fix it and push it to live. :-1:

**Comment by Flowneee** [comment]
@ImprezaWoW the problem is no one can contact with GM (I waited for an answer on my ticket about 2 weeks, and many of my friends can't contact with GM), they just don't answer. After that i dropped ticket, cuz it interferes with the interface.
