### ISSUE TITLE
[NPC][Classic] Gravis Slipknot - Wrong Itemmodel

### ISSUE THREAD

**Issue by Rushor** [dalaranwow/dalaran-wow#4539]
http://wotlk.openwow.com/npc=14221

Uses the wrong item modelid + has the wrong spawnlocation according to his first pathpoint.

**Comment by Rushor** [comment]
DB/Creature: Gravis Slipknot - Update Itemid and spawnposition

* closes: https://github.com/dalaranwow/dalaran-wow/issues/4539
* commit: b834cf1161d9ec4d97d663334c5cabe6ddebfec0

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by TeridanDW** [comment]
Hm @Lothloryen, can we merge this report and #991 and add them together on PTR for test + my position and SAI changes that are posted in the other report please?
