### ISSUE TITLE
[NPC][Classic]  Magistrix Eredania - Invisible

### ISSUE THREAD

**Issue by Rushor** [dalaranwow/dalaran-wow#4540]
http://wotlk.openwow.com/npc=16160

Is sometimes invisible because of wrong modelid settings.

**Comment by Rushor** [comment]
DB/Creature: Magistrix Eredania - Should always be visible

* closes: https://github.com/dalaranwow/dalaran-wow/issues/4540
* commit: cd1330c1d17e10d66704947d528cdf282e01b895

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by TeridanDW** [comment]
Works as intended on PTR.
