### ISSUE TITLE
[Mechanic] Respawn behavior of world creatures

### ISSUE THREAD

**Issue by Teridan-dal-wow** [dalaranwow/dalaran-wow#4541]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

Description: When a world creature spawns/respawns there should be 5 secs "grace" period of which the creature won't engage a player, but will defend itself if attacked. 

**Current behaviour**: 
Situation 1 - Npc vs Player

 - When a npc spawns near player, it will engage immediately (if the creature is aggresive).
 - When a npc spawns (the npc has no movement) and player moves near it - creature will attack immediatly.
 - When a npc spawns (the npc has random/wp movement) and player moves near it - creature will attack immediatly.
 - When a npc spawns (the npc has no movement) and player stays still - creature will never attack the player, however as soon as the player moves it will attack him.

Situation 2 - Npc vs Npc - lets spawn 2 npcs (npc 1  and npc 2) with factions that are aggresive toward each other.

 - When npc 1 (has no movement) and npc 2 (has no movement) spawns they will ignore each other forever, however as soon as 1 of them moves (doesn't matter the reason) they will "detect" each other and start to fight.
 - When npc 1 (has random/wp movement) and npc 2 (has no movement) spawns, they will start to fight immediately (as one of them was moving and they "detect" each other).
 - When npc 1 (has random/wp movement) and npc 2 (has random/wp movement) spawns, they will start to fight immediately (as one of them was moving and they "detect" each other).

**Expected behaviour**: 
Situation 1 - Npc vs Player 
Regardless if the npc has any kind of movement or not, it should have a 5 secs "grace" timer on spawn/respawn.
Proof: https://www.youtube.com/watch?v=G4hclNIgIuQ&feature=youtu.be

Regarding

> - When a npc spawns (the npc has no movement) and player stays still - creature will never attack the player, however as soon as the player moves it will attack him.

thats a bug and should never happen.

Situation 2 - Npc vs Npc

The 5 secs "grace" timer does **not** exits in situation 2.

Will add proof later.

Regarding

>  - When npc 1 (has no movement) and npc 2 (has no movement) spawns they will ignore each other forever, however as soon as 1 of them moves (doesn't matter the reason) they will "detect" each other and start to fight.

thats a bug, both npcs should fight regardless of their movement.

**Comment by Rushor** [comment]
Ref: https://github.com/mangosArchives/serverZero_Rel19/commit/51b8fef1a5b31b7caecefbeb0107acf64f359c6d which needs updates for the player condition

**Comment by Rushor** [comment]
Game/Creature: Implement CONFIG_CREATURE_RESPAWN_AGGRO_DELAY which handles a delay between when a creature spawns and when it can be aggroed 

* closes: https://github.com/dalaranwow/dalaran-wow/issues/4541
* commit: ab7ef4722298b41f22134567b2f6f36e866db42b

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by Teridan-dal-wow** [comment]
Does 

> CONFIG_CREATURE_RESPAWN_AGGRO_DELAY

solves all issues listed above?

**Comment by Rushor** [comment]
yep it was more simple than expected because the checks for it was already there, i only had to add a timer for it
