### ISSUE TITLE
[NPC][Classic] Duke Ragereaver - Missing spawn, path and script

### ISSUE THREAD

**Issue by Rushor** [dalaranwow/dalaran-wow#4550]
http://www.wowhead.com/npc=10820/duke-ragereaver

Is missing his spawn, path and script.

**Comment by Rushor** [comment]
DB/Creature: Duke Ragereaver - Add spawn, path and combatscript

* closes: https://github.com/dalaranwow/dalaran-wow/issues/4550
* commit: 6db72aeabdf4e4bbcbbc43a62900483265548ba8

Thanks to TC

**Comment by TeridanDW** [comment]
Works as intended on PTR.

**Comment by TeridanDW** [comment]
Note: He is missing his loot table 
http://www.wowhead.com/npc=10820/duke-ragereaver#drops:0-18+1
