### ISSUE TITLE
[Item][Consumable] Stormchops

### ISSUE THREAD

**Issue by plznoz** [dalaranwow/dalaran-wow#4556]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
1. When using Stormchops it starts damaging the player (not the enemy), when hit. This can be (ab)used to gain an advantage for warriors (rage).
2. You can have both the Electrified and a Well fed buff.

**Expected behaviour**: Tell us what should happen instead
1. It should damage the enemy
2. Electrified should overwrite Well fed, and Well fed should overwrite Electrified (You should only be able to have one of them active).

**Steps to reproduce the problem**:
1. Use Stormchops
2. Get hit by enemy (try with a friendly player close to you getting hit aswell, I believe this triggers it aswell)
3. Observe damage to self

**Include proofs for this behaviour**
>Stormchops does overwrite any other Well-Fed buffs you might have, and Stormchops' buff can be overwritten by a Well-Fed buff.

http://www.wowhead.com/spell=43758/stormchops#comments:id=279588

From dalaran-wow live realm:
>Grove Walker's melee swing hits PLAYER for 207 Physical.
PLAYER's Lightning Zap hits PLAYER for 24 Nature.
Grove Walker's attack was dodged by PLAYER.
PLAYER's Paragon fades from PLAYER.
Grove Walker's melee swing hits PLAYER for 208 Physical.
PLAYER's Lightning Zap hits PLAYER for 37 Nature.(Critical)
Grove Walker's melee swing hits PLAYER for 214 Physical.
PLAYER's Lightning Zap hits PLAYER for 30 Nature.
Grove Walker's melee swing hits PLAYER for 248 Physical.
PLAYER's Lightning Zap hits PLAYER for 47 Nature.(Critical)
Grove Walker's melee swing hits PLAYER for 234 Physical.
PLAYER's Lightning Zap hits PLAYER for 43 Nature.(Critical)
Grove Walker's attack was parried by PLAYER.
Grove Walker's attack was parried by PLAYER.
Grove Walker's melee swing hits PLAYER for 263 Physical.
PLAYER's Lightning Zap hits PLAYER for 23 Nature.
Grove Walker's melee swing hits PLAYER for 204 Physical.
PLAYER's Lightning Zap hits PLAYER for 28 Nature.
Grove Walker's melee swing hits PLAYER for 232 Physical.
PLAYER's Lightning Zap hits PLAYER for 19 Nature.
Grove Walker's attack was dodged by PLAYER.
Grove Walker's melee swing hits PLAYER for 244 Physical.
PLAYER's Lightning Zap hits PLAYER for 25 Nature.
Grove Walker's attack was dodged by PLAYER.
Grove Walker's attack was parried by PLAYER.
Grove Walker's melee swing hits PLAYER for 269 Physical.
PLAYER's Lightning Zap hits PLAYER for 33 Nature.(Critical)
Grove Walker's melee swing hits PLAYER for 271 Physical.
PLAYER's Lightning Zap hits PLAYER for 32 Nature.
Grove Walker's melee swing hits PLAYER for 248 Physical.
PLAYER's Lightning Zap hits PLAYER for 25 Nature.
Grove Walker's attack was dodged by PLAYER.

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**
http://wotlk.openwow.com/item=33866 Stormchops
http://wotlk.openwow.com/spell=43730 Electrified (Buff received from using Stormchops)
http://wotlk.openwow.com/spell=43731 Lightning Zap (Damage done with Electrified buff)

**Comment by Rushor** [comment]
spellgroup stacking roule was already fixed for this spell in 

DB/Spell: Implement spell_group from Sunwell.pl

* Issue https://github.com/dalaranwow/dalaran-wow/issues/1510
* commit: 424ed6af17475e0984dcda50ff1598607ef21796

**Comment by Rushor** [comment]
Game/Spells: Stormchops - Enable targeting of enemies for AoE 

* closes: https://github.com/dalaranwow/dalaran-wow/issues/4556
* commit: 0bb05d8159bae38159d83262fe4d49f120b783b7

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
