### ISSUE TITLE
how to unbann account :'( ?

### ISSUE THREAD

**Issue by riiccardo** [dalaranwow/dalaran-wow#4558]
hi every one i newest player wow and i resently met with hack in wow 
and download and use it for 2 days 
unfortunly GM saw and banned me 
how can i unbanned my account besause 
I once made the mistake and I have no notification from the GM 
GM: dont use hack again if you do you will banned soon
but i realy sad after that GM Dont let me to Explain why i use 
just for lvl up
no for another reason

**Comment by Rushor** [comment]
-- GM ONLY --
The issuetracker is for serverside and gamemechanic issues only. Please write an Ingame-issue to a Gamemaster (with a new created account if needed) and the Gamemaster will then help you as soon as he can. Thank you.

![GitHub Logo](http://i.imgur.com/bYkYeGQ.png)
