### ISSUE TITLE
[Wow Wotlk] (Dalaran Wow) Quest Named: New beginning: Chest empty

### ISSUE THREAD

**Issue by HSreaver** [dalaranwow/dalaran-wow#4563]
Chest empty, allows the cast bar of t pick up the item in Westfall, but there is no item in the chest.

**Comment by Teridan-dal-wow** [comment]
Hello, could you go to http://wotlk.openwow.com/ or http://wowhead.com/ find the quest you mentioned and link it here please.
The only quest i found called "New beginning" is this one http://wotlk.openwow.com/quest=13009 , but thats in The Storm Peaks and it doesn't involve any chests or Westfall ?

**Comment by Rushor** [comment]
invalid report, pls read https://github.com/dalaranwow/dalaran-wow/wiki/Dalaran-WoW-Bug-Tracker---Guidelines before opening a report and don't delete the issue template. thanks

**Comment by TheRealestMcCoy** [comment]
@Teridan-dal-wow i know rushor already closed this for good reason. However looking over all the westfall quest with a chest only one i say was the captains chest. If you want to look into that quest. The quest would be http://wotlk.openwow.com/quest=140

**Comment by Teridan-dal-wow** [comment]
@TheRealestMcCoy Thank you for the time invested in investigating this "issue". I did check quest =140 and all works correctly.
![image](https://cloud.githubusercontent.com/assets/6797611/23964137/23c5e384-09bc-11e7-8236-e5eb51410297.png)
![image](https://cloud.githubusercontent.com/assets/6797611/23964145/2b29700a-09bc-11e7-9402-0564775ff14f.png)

Note: This chest is questender and it doesn't have a loot table (like normal chests do) so i would assume  thats not the chest @HSreaver spoke about.

**Comment by TheRealestMcCoy** [comment]
Well i have no clue the only other one i know that may have a chest quest is the rogue quest line. But i know for sure that one does work.
