### ISSUE TITLE
[NPC][General] Scrapbot - should be friendly to all

### ISSUE THREAD

**Issue by Rushor** [dalaranwow/dalaran-wow#4582]
http://wotlk.openwow.com/npc=29561

should have faction 35 and be friendly to all.

**Comment by Rushor** [comment]
DB/Creature: Scrapbot - should be friendly to all
* commit: 17963e297dfce65983984cb225c42ec0c4b58ad0

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by TeridanDW** [comment]
Works as intended on PTR.
