### ISSUE TITLE
[NPC][Classic] Chicken - Missing %s in texts

### ISSUE THREAD

**Issue by Rushor** [dalaranwow/dalaran-wow#4584]
http://wotlk.openwow.com/npc=620

Emotetexts given by that creature for the quest http://wotlk.openwow.com/quest=3861 is missing a %s which handles the creature's name inside the text.

**Comment by Rushor** [comment]
DB/Creature: Chicken - Update text with %s in order to display the name of it
* commit: c4d919f20e8eca4d8109d13bb03dc088321409c7

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by TeridanDW** [comment]
Works as intended on PTR.
