### ISSUE TITLE
[NPC][WotlK] Northrend Daily Dungeon Image Bunny

### ISSUE THREAD

**Issue by Teridan-dal-wow** [dalaranwow/dalaran-wow#4605]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: 
Npc http://wotlk.openwow.com/npc=32265 is suppose to be spinning around, which is not happening now and there is a visual bug with some models.
Example from Algalon:
![ezgif com-optimize](https://cloud.githubusercontent.com/assets/6797611/24080409/3aab7dd2-0ca7-11e7-8658-66cd2e124920.gif)

**Expected behaviour**: 
Gif from retail:

![ezgif com-optimize 1](https://cloud.githubusercontent.com/assets/6797611/24080424/8dc87830-0ca7-11e7-8f1f-a6129824b994.gif)

**Comment by Rushor** [comment]
do you know any script that already exist where a creature spins around?

**Comment by Rushor** [comment]
moverotate could fix it

**Comment by Teridan-dal-wow** [comment]
I can't think of any at the moment.

**Comment by Rushor** [comment]
edit: the modelstuff does not even work on ptr, will rewrite it from scratch

**Comment by Teridan-dal-wow** [comment]
Ok, if you are going to that, keep in mind the link between quest and creature shown for the currently avaliable quests on Algalon and the future ones that will show up. For example - http://www.wowhead.com/quest=24590/lord-marrowgar-must-die and other raid/dungeon bosses/creatures.

**Comment by Rushor** [comment]
yep will keep an eye on this

**Comment by Rushor** [comment]
Scripts/Dalaran: Archmage Lan'dalock - Add spawn and rotation for images

* closes: https://github.com/dalaranwow/dalaran-wow/issues/4605
* commit: a3b905d96ffdeb39d40327c965bda30ab48127e8

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by Teridan-dal-wow** [comment]
Does 

> Scripts/Dalaran: Archmage Lan'dalock - Add spawn and rotation for images

means that you added the images for that mage only? If so its my bad i didn't said that the other mage should have the same images behind him, related to the quest that he offers.
http://wotlk.openwow.com/npc=31439

**Comment by Rushor** [comment]
which models should appear for that one?

**Comment by Teridan-dal-wow** [comment]
The other mage http://wotlk.openwow.com/npc=31439 offers 4 quests (everyday one is  choosen randomly) and images behind him are the objectives of these 4 quest. 
Example for http://wotlk.openwow.com/quest=13240 we should have http://wotlk.openwow.com/npc=27641 as image behind him again spinning.
 I can't show it from retail because these quests were remove when RDF tool was implemented.

**Comment by Rushor** [comment]
okay like that http://wotlk.openwow.com/npc=31631, i will add it for him
