### ISSUE TITLE
[NPC][Item][Classic] Defender of the Timbermaw

### ISSUE THREAD

**Issue by Rushor** [dalaranwow/dalaran-wow#4615]
Source: 
https://www.youtube.com/watch?v=42QFS7qJyVo&feature=youtu.be&t=5m35s

http://wotlk.openwow.com/item=21326

The creature summoned by this spell should cast http://wotlk.openwow.com/npc=15720  http://wotlk.openwow.com/spell=20295.

**Comment by Rushor** [comment]
DB/Creature: Timbermaw Ancestor (Item) - Add combatability 'Lightning Bolt'

* closes: https://github.com/dalaranwow/dalaran-wow/issues/4615
* commit: 37a7d5b1af1d3693a64f858c5f8b0fa5ddc5d08c

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by TeridanDW** [comment]
After a fast test on PTR:

>  - DB/Creature: Timbermaw Ancestor (Item) - Add combatability 'Lightning Bolt'

can not be tested because the creature doesn't have a mana pool and can't cast 'Lightning Bolt'
![image](https://user-images.githubusercontent.com/6797611/35584555-05271abc-05fe-11e8-9f75-b6f87899217f.png)

Maybe change his class?
``` sql
UPDATE `creature_template` SET `unit_class` = 2 WHERE `entry` = 15720; 
```
