### ISSUE TITLE
Wyrmrest Vanquisher Attacks Player

### ISSUE THREAD

**Issue by Xandriarn** [dalaranwow/dalaran-wow#4620]
Dismounting the Wyrmrest Vanquisher causes you to take melee attacks from the Wyrmrest Vanquisher who appears to be invisible. 

He should just fly away when you dismount. 

Entering Combat with a mob causes the Wyrmrest Vanquisher to immediately plummet toward the ground or suddenly teleport on the ground.

Entering combat should have no effect on the position or direction of the Wyrmrest Vanquisher.

The quest item Ruby Beacon of the Dragon Queen (#38302) cannot be used in the Wicked Coil.

The item says it can be used in the Wicked Coil, but it cannot. It needs to be usable in the Wicked Coil.

The flying into the ground bug happened during the quest On Ruby Wings. It was more annoying than anything since you could just fly back up.

When I attempted to dismount to fight Antiok after killing Thiassi I was melee'd to death before I could engage Antiok. I saw an undead warlock that this appeared to happed to as I was running back to my corpse as well. Fortunately Antiok was still dismounted and I could kill him to complete the quest. 

I then summoned the Wyrmrest Vanquisher again to fly me back to the temple (which did not work on the Wicked Coil as the tooltip says). Upon dismounting at the top of the temple I was melee'd to death again. See screenshot.

![image](https://cloud.githubusercontent.com/assets/25491266/24165964/b5e8121e-0e3f-11e7-9bbf-01fc45a8dcbf.png)

**Comment by Rushor** [comment]
This will be fixed once https://github.com/TrinityCore/TrinityCore/commit/96f90381e3ed696861354ea4ddf4ac0c495031c5 was merged. Currently all vehicles with SAI behave a bit strange. Once that fix was applied all those issues are solved. 

More infos on that here: https://github.com/TrinityCore/TrinityCore/issues/7450
