### ISSUE TITLE
[Spell/Ability][Warrior] Berserker Rage

### ISSUE THREAD

**Issue by TheRealestMcCoy** [dalaranwow/dalaran-wow#4628]
**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
Does not gain rage when taking damage from beserker rage.
**Expected behaviour**: Tell us what should happen instead
berserker rage should grant the warrior extra rage from taking damage
**Steps to reproduce the problem**:

1. Use beserker rage
2. check for rage gains from damage
3. 

**Include proofs for this behaviour**
![no rage](https://cloud.githubusercontent.com/assets/12252441/24291680/544680fe-1060-11e7-939b-35d2317c4ab9.png)

You can research this on several pages like http://wowhead.com or http://wowwiki.wikia.com or http://www.youtube.com/
Issues without proofs will be closed and tag On Hold will be added until the proof is provided.

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**
[Beserker Rage](http://wotlk.openwow.com/spell=18499)
Berserker Rage
Instant	30 sec cooldown
The warrior enters a berserker rage, removing and granting immunity to Fear, Sap and Incapacitate effects and generating extra rage when taking damage. Lasts 10 sec.
You can research this on several pages like http://wotlk.openwow.com or http://wowhead.com/

**Include Screenshots from the issue if necessary**

**Comment by Rushor** [comment]
This works fine on PTR. (it's hardcoded so it might not be displayed in the logs)

```c++
void Unit::RewardRage(uint32 damage, uint32 weaponSpeedHitFactor, bool attacker)
{
    float addRage;

    float rageconversion = ((0.0091107836f * getLevel() * getLevel()) + 3.225598133f * getLevel()) + 4.2652911f;

    // Unknown if correct, but lineary adjust rage conversion above level 70
    if (getLevel() > 70)
        rageconversion += 13.27f * (getLevel() - 70);

    if (attacker)
    {
        addRage = (damage / rageconversion * 7.5f + weaponSpeedHitFactor) / 2;

        // talent who gave more rage on attack
        AddPct(addRage, GetTotalAuraModifier(SPELL_AURA_MOD_RAGE_FROM_DAMAGE_DEALT));
    }
    else
    {
        addRage = damage / rageconversion * 2.5f;

        // Berserker Rage effect
        if (HasAura(18499))
            addRage *= 2.0f;
    }

    addRage *= sWorld->getRate(RATE_POWER_RAGE_INCOME);

    ModifyPower(POWER_RAGE, uint32(addRage * 10));
}
```

**Comment by TheRealestMcCoy** [comment]
OK that could be it then.

**Comment by Zarjofgt** [comment]
The skill doubles the rage gained from damage, and such rage does not show up in combat logs.
