### ISSUE TITLE
Achievement / NPC: Leeeeeeeeeeeeeroy! / Rookery Whelp

### ISSUE THREAD

**Issue by Crispybuilt** [dalaranwow/dalaran-wow#463]
- *Achievement: Leeeeeeeeeeeeeroy!* - 2188
- *NPC:  Rookery Whelp* - 10161
- *Instance: Blackrock Spire* - 1583

**Issue** - Upon entering room and walking over the eggs, the NPCs *Rookery Whelp*'s are not spawning. 

- *How it should work:* When walking across the room, (Zone: The Rookery) near the objects **"Rookery Egg"** *(ID: 175124)*, each egg that you *"activate"(walk across)*, should spawn a **Rookery Whelp**.
Rookery Whelp has an ability called: **Fireball**

**Fireball** - 145

Also at current state, eggs are triggable (clickable) by players even they shouldn't be, just a minor bug. They dissapear upon being clicked or upon player walks over them.

- If you manage to kill 50 whelps in 15 seconds, you will get achievement. The counter starts from the first whelp you kill and it resets again after 15 seconds are up.

![image](https://f.cloud.github.com/assets/5054924/933779/e03ec4a8-005c-11e3-9a78-9a569ad2f7d4.png)

**How it should work as on retail**: http://www.youtube.com/watch?v=MEUBQqQk9o4&noredirect=1
________________________________________

http://www.wowhead.com/achievement=2188/leeeeeeeeeeeeeroy
http://wotlk.openwow.com/achievement=2188
http://wotlk.openwow.com/npc=10161
http://www.wowhead.com/npc=10161
http://wotlk.openwow.com/spell=145

**Comment by natrixas** [comment]
Still not working,

**Comment by Spruitje** [comment]
Don't know why this is still open
The eggs are now working as intended, just walk over/close to them and whelps will appear
Recently got the achievement, can be closed

**Comment by Golganeth** [comment]
Works now as intended.
