### ISSUE TITLE
[NPCS][Dragon Blight] Wrathgate NPCS

### ISSUE THREAD

**Issue by TheRealestMcCoy** [dalaranwow/dalaran-wow#4630]
**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
Currently the npcs at the wrath gate are friendly. 
**Expected behaviour**: Tell us what should happen instead
These npcs should be hostile until the quest line is completed. Upon completion of the quest line the npcs should phase out. 
**Steps to reproduce the problem**:

1. Do not complete quest line
2. Go to wrathgate 
3. 

**Include proofs for this behaviour**
Have not completed quest line to get achv can see npcs are green.
![wowscrnshot_032417_094804](https://cloud.githubusercontent.com/assets/12252441/24296825/0088a87c-1077-11e7-9b88-f2f0fe784bea.jpg)

You can research this on several pages like http://wowhead.com or http://wowwiki.wikia.com or http://www.youtube.com/
Issues without proofs will be closed and tag On Hold will be added until the proof is provided.

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**
List of npcs
http://www.wowhead.com/npc=27605/colossal-abomination
http://www.wowhead.com/npc=27631/angrathar-aberration
http://www.wowhead.com/npc=27603/angrathar-necrolord
http://www.wowhead.com/npc=27604/frail-construct
http://www.wowhead.com/npc=27691/frenzied-gargoyle
http://www.wowhead.com/npc=27611/plague-eruptor
You can research this on several pages like http://wotlk.openwow.com or http://wowhead.com/

**Include Screenshots from the issue if necessary**

Not sure about this NPC. There is a Reconstructed Wyrm here as well. He is also friendly.
http://www.wowhead.com/npc=27693/reconstructed-wyrm
![wowscrnshot_032417_095622](https://cloud.githubusercontent.com/assets/12252441/24297237/657113c2-1078-11e7-89ad-d9d9a72a8dc0.jpg)

**Comment by TheRealestMcCoy** [comment]
Also the as an alliance some of the warsong npcs are friendly.
![wowscrnshot_032417_095454](https://cloud.githubusercontent.com/assets/12252441/24297123/f59530ce-1077-11e7-9d81-c3a7f402baae.jpg)

**Comment by TheRealestMcCoy** [comment]
This is from a char that has completed the quest line and the horde NPCs are also friendly.
![wowscrnshot_032417_100524](https://cloud.githubusercontent.com/assets/12252441/24297512/70d8f8c8-1079-11e7-9347-49d4549889e1.jpg)

**Comment by Rushor** [comment]
Phasing already works on PTR. Faction related issue was fixed in https://github.com/dalaranwow/dalaran-wow/issues/2930 (nned to be tested on PTR)
