### ISSUE TITLE
Quest Chain: Battle at Valhalas - All quests

### ISSUE THREAD

**Issue by Crispybuilt** [dalaranwow/dalaran-wow#465]
**Critical Issue for all the quests** - Quests are currently all available from the Geirrvif and they shouldn't be. They need to be given to a player in chronological order just like Zul'Drak arena chain quests for example. They are not scripted, every event is missing.

**Minor Issue** - Geirrvif location has to be on top of the arena to observe and not directly inside the arena where events happen.

Player is able to start the chain quest once he has completed **Battle at Valhalas - 13213** from **The Bone Witch - 30232** 

http://www.wowhead.com/quest=13213/battle-at-valhalas
________
**Quest Battle at Valhalas: Fallen Heroes - 13214**

- **Issue:** The entire event and speech is missing from it which leads to more quests.

- **How it should work:** Upon accepting the quest *(13214)*, quest giver *(Geirrvif - 31135)* should start roleplay event the following quotes: 

- When you pick the quest:
**Geirrvif says:** *Valhalas is yours to win or die in, [PLAYER NAME]. But whatever you do, stay within the bounds of the arena. To flee is to lose and be dishonored.*
**Geirrvif yells**: *[PLAYER NAME] and [HIS/HER] comrades in arms have chosen to accept honorable combat within the sacred confines of Valhalas.*
**Geirrvif yells**: *There can only be one outcome to such a battle: death for one side or the other. Let [PLAYER NAME] prove [HIM/HER]self upon the bones of these outsiders who have fallen before!*
*The fallen heroes of Valhalas emerge from the ground to do battle once more!* - GENERAL SCREEN MESSAGE

- Upon defeat she says this: 
**Geirrvif yells:** *[PLAYER NAME] has defeated the fallen heroes of Valhalas battles past. This is only a beginning, but it will suffice.*

- After that, **6** NPCs inside the area will spawn:

**(Eldreth - 31195)** and the creature will become attackable after few seconds. The creature has the following abilites (link down below): *Arcane Shot*, *Magic Dampening Field*, *Shoot*. 
**(Geness Half-Soul - 31193)** and the creature will become attackable after few seconds. The creature has the following abilites (link down below): *Brutal Fist*, *Snap Kick*
**(Father Jhadras - 31191** and the creature will become attackable after few seconds. The creature has the following abilites (link down below): *Heal*, *Holy Smite*
**(Masud - 31192** and the creature will become attackable after few seconds. The creature has the following abilites (link down below): *Cleave*, *Whirlwind*
**(Rith - 31196)** and the creature will become attackable after few seconds. The creature has the following abilites (link down below): *Demoralizing Shout*, *Sunder Armor*
**(Talla- 31194)** and the creature will become attackable after few seconds. The creature has the following abilites (link down below): *Sinister Strike*

- Upon defeating all 6 creatures, the player will get the credit, it should count also if you are in group.

**Arcane Shot** - 34829
**Magic Dampening Field** - 44475
**Shoot** - 15620

**Brutal Fist** - 61041
**Snap Kick** - 46182

**Heal** - 15586
**Holy Smite** - 25054

**Cleave** - 15496
**Whirlwind** - 41057

**Demoralizing Shout** -61044
**Sunder Armor** - 58461

**Sinister Strike** - 14873

http://www.wowwiki.com/Eldreth
http://www.wowwiki.com/Father_Jhadras
http://www.wowwiki.com/Masud
http://www.wowwiki.com/Masud
http://www.wowwiki.com/Rith
http://www.wowwiki.com/Talla

http://wotlk.openwow.com/npc=31195
http://wotlk.openwow.com/npc=31193
http://wotlk.openwow.com/npc=31191
http://wotlk.openwow.com/npc=31192
http://wotlk.openwow.com/npc=31196
http://wotlk.openwow.com/npc=31194
http://wotlk.openwow.com/npc=31135
http://www.wowwiki.com/Quest:Battle_at_Valhalas:_Fallen_Heroes
http://wotlk.openwow.com/quest=13214

____________________________________________

**Quest Battle at Valhalas: Khit'rix the Dark Master - 13215**

- **Issue:** The entire event and speech is missing from it which leads to more quests.

- **How it should work:** Upon accepting the quest *(13215)*, quest giver *(Geirrvif - 31135)* should start roleplay event the following quotes: 

- When you pick up the quest:
**Geirrvif says:** *Prepare yourself. Khit'rix will be entering Valhalas from the southeast. Remember, do not leave the ring or you will lose the battle.*
**Geirrvif yells:** [PLAYER NAME] *has accepted the challenge of Khit'rix the Dark Master. May the gods show mercy upon [HIM/HER] for Khit'rix surely will not.*
*Khit'rix the Dark Master skitters into Valhalas from the southeast!* - /NPC EMOTE
**Khit'rix the Dark Master yells:** *When I am done here, I am going to mount your heads upon the walls of Azjol-Nerub!*

- Upon defeat she says this: 
**Geirrvif yells:** *Khit'rix the Dark Master has been defeated by [PLAYER NAME] and [HIS/HER] band of companions. Let the next challenge be issued!*

 After that, an NPC inside the area will spawn.

**(Khit'rix the Dark Master - 31222)** and the creature will become attackable after few seconds. The creature has the following abilites (link down below): *Mind Flay*, *Psychic Scream*, *Summon Bone Spiders*. 

- Upon defeating acreature, the player will get the credit, it should count also if you are in group.

**Mind Flay** - 38243
**Psychic Scream** - 22884
**Summon Bone Spiders** - 61055

http://wotlk.openwow.com/npc=31222
http://www.wowwiki.com/Quest:Battle_at_Valhalas:_Khit%27rix_the_Dark_Master
http://wotlk.openwow.com/quest=13215
http://www.wowwiki.com/Khit%27rix_the_Dark_Master
http://wotlk.openwow.com/npc=31135
____________________________________________

**Quest Battle at Valhalas: The Return of Sigrid Iceborn - 13216**

- **Issue:** The entire event and speech is missing from it which leads to more quests.

- **How it should work:** Upon accepting the quest *(13216)*, quest giver *(Geirrvif - 31135)* should start roleplay event the following quotes: 

- When you pick up the quest:
**Geirrvif says:** *I can hear Sigrid Iceborn approaching from the northwest. She has been informed that she cannot use her proto-drake in battle here. Do not leave the battle ring!*
**Geirrvif yells:** *Sigrid Iceborn has returned to the heights of Jotunheim to prove herself against [PLAYER NAME]. When last they met, [PLAYER NAME] bester her in personal combat. Let us see the outcome of this match.*
*Circling Valhalas, Sigrid Iceborn approaches to seek her revenge!* - GENERAL SCREEN MESSAGE
**Sigrid Iceborn yells:** *Ah, there you are! Remember me? Of course you do! Wait right there, I'm coming down.*
**Sigrid Iceborn yells:** *I told you I'd be better prepared when next we meet. I've fought and won the Hyldsmeet, trained at Valkyrion, and here I am. Come and get some!*

- Upon defeat she says this: 
**Geirrvif yells:** [PLAYER NAME] *has defeated Sigrid Iceborn for a second time. Well, this time he did it with the help of his friends, but a win is a win!*

 After that, an NPC inside the area will spawn.

**(Sigrid Iceborn - 31242)** and the creature will become attackable after few seconds. The creature has the following abilites (link down below): *Disengage*, *Flash Freeze*, *Frostbite Weapon*, *Throw*

- Upon defeating acreature, the player will get the credit, it should count also if you are in group.

**Disengage** - 57635
**Flash Freeze** - 61170
**Frostbite Weapon** - 61165
**Throw** - 61168

http://wotlk.openwow.com/npc=31242
http://www.wowwiki.com/Quest:Battle_at_Valhalas:_The_Return_of_Sigrid_Iceborn
http://wotlk.openwow.com/quest=13216
http://www.wowwiki.com/Sigrid_Iceborn
http://wotlk.openwow.com/npc=31242
____________________________________________

**Quest Battle at Valhalas: Carnage! - 13217**

- **Issue:** The entire event and speech is missing from it which leads to more quests.

- **How it should work:** Upon accepting the quest *(13217)*, quest giver *(Geirrvif - 31135)* should start roleplay event the following quotes: 

- When you pick up the quest:
**Geirrvif says:** *Carnage is coming! Remember, no matter what you do, do NOT leave the battle ring or I will disqualify you and your group.*
**Geirrvif yells:** *From the bowels of the Underhalls comes Carnage. Brave and foolish [PLAYER NAME] has accepted the challenge. [PLAYER NAME] and [HIS/HER] group stand ready to face the monstrosity.*
*Lumbering in from the south, the smell of Carnage precedes him!* - GENERAL SCREEN MESSAGE

- Upon defeat she says this: 
**Geirrvif yells:** *The horror known as Carnage is no more. Could it be that [PLAYER NAME] is truly worthy of battle in Valhalas? We shall see.*

 After that, an NPC inside the area will spawn.

**(Carnage - 31271)** and the creature will become attackable after few seconds. The creature has the following abilites (link down below): *Smash*, *War Stomp*

- Upon defeating acreature, the player will get the credit, it should count also if you are in group.

**Smash** - 61070
**War Stomp** - 61065

http://wotlk.openwow.com/npc=31271
http://www.wowwiki.com/Quest:Battle_at_Valhalas:_Carnage!
http://wotlk.openwow.com/quest=13217
http://www.wowwiki.com/Carnage
http://wotlk.openwow.com/npc=31242

___________________________________

**Quest Battle at Valhalas: Thane Deathblow - 13218**

- **Issue:** The entire event and speech is missing from it which leads to more quests.

- **How it should work:** Upon accepting the quest *(13218)*, quest giver *(Geirrvif - 31135)* should start roleplay event the following quotes: 

- When you pick up the quest:
**Geirrvif says:** *Look to the southeast and you will see the thane upon the platform near Gjonner the Merciless when he shows himself. Let him come down. Stay within the ring of Valhalas.*
**Geirrvif yells:** *Thane Banahogg returns to Valhalas for the first time in ages to prove that the vrykul are the only beings worthy to fight within its sacred ring. Will [PLAYER NAME] prove him wrong?*
*Thane Banahogg appears upon the overlook to the southeast!* - GENERAL SCREEN MESSAGE
**Thane Banahogg yells:** *ENOUGH! You tiny insects are not worthy to do battle within this sacred place! You do not fight with honor! Do do not even ascend!*
**Thane Banahogg yells:** *Fight me and die you cowards!*
**Thane Banahogg says:** *Haraak foln!*

- Upon defeat she says this: 
**Geirrvif yells:** *Thane Banahogg the Deathblow has fallen to [PLAYER NAME] and [HIS/HER] fighting companions. [HE/SHE] has but one challenge ahead of [HIM/HER]. Who will it be?*

 After that, an NPC inside the area will spawn.

**(Thane Banahogg =The Deathblow= - 31277)** and the creature will become attackable after few seconds. The creature has the following abilites (link down below): *Execute*, *Leap*, *Punt*, *Whirlwind*.

- Upon defeating acreature, the player will get the credit, it should count also if you are in group.

**Execute** - 61140
**Leap** - 61134
**Punt** - 61133
**Whirlwind** - 61139

http://wotlk.openwow.com/npc=31277
http://www.wowwiki.com/Quest:Battle_at_Valhalas:_Thane_Deathblow
http://wotlk.openwow.com/quest=13218
http://www.wowwiki.com/Thane_Banahogg
http://wotlk.openwow.com/npc=31242

__________________________

**Quest Battle at Valhalas: Final Challenge - 13219**

- **Issue:** The entire event and speech is missing from it which leads to more quests.

- **How it should work:** Upon accepting the quest *(13219)*, quest giver *(Geirrvif - 31135)* should start roleplay event the following quotes: 

- When you pick up the quest:
**Geirrvif says**: *It's too late to run now. Do not leave the ring. Die bravely, [PLAYER NAME]!*
**Geirrvif yells:** *From the depths of Icecrown Citadel, one of the Lich King's chosen comes to put an end to the existence of [PLAYER NAME] and [HIS/HER] friends.*
**Geirrvif yells:** *Warriors of Jotunheim, I present to you, Blood Prince Sandoval!*
*Without warning, Prince Sandoval magically appears within Valhalas!* - (This is General Screen message / warning)
**Prince Sandoval yells:** *Hardly a fitting introduction, Spear-Wife. Now, who is this outsider that I've been hearing so much about?*
**Prince Sandoval yells:** *I will make this as easy as possible for you. Simply come here and die. That is all that I ask for your many trespasses. For your sullying this exlated place of battle.*
**Prince Sandoval yells:** *FOR YOUR EFFRONTERY TO THE LICH KING!*

- Upon defeat she says this: 
**Geirrvif yells:** *The unthinkable has happened... [PLAYER NAME] has slain Prince Sandoval!*
**Geirrvif yells:** *In defeating him, [HE/SHE] and [HIS/HER] fighting companions have proven themselves worthy of battle in this most sacred place of vrykul honor.*
**Geirrvif yells:** *ALL HAIL [PLAYER NAME], CHAMPION OF VALHALAS!*

 After that, an NPC inside the area will spawn.

**(Prince Sandoval - 14688)** and the creature will become attackable after few seconds. The creature has the following abilites (link down below): *Ember Shower*, *Engulfing Strike*, *Fire Nova*, *Fire Shield*.

- Upon defeating acreature, the player will get the credit, it should count also if you are in group.

**Ember Shower** - 61145
**Engulfing Strike** - 61162
**Fire Nova** - 61163
**Fire Shield** - 61144

http://wotlk.openwow.com/npc=14688
http://www.wowwiki.com/Quest:Battle_at_Valhalas:_Final_Challenge
http://wotlk.openwow.com/quest=13219
http://www.wowwiki.com/Prince_Sandoval
http://wotlk.openwow.com/npc=31242

**Video of how the last quest has to work:** 
http://www.youtube.com/watch?v=7HagFk5vRZo
http://www.youtube.com/watch?v=sRAVuT6KvUw

**Comment by Lothloryen** [comment]
Hello there,

This quests were already corrected time ago.

Thank you.

**Comment by roblockster** [comment]
After dying to Prince Sandoval in The Final Challenge, Prince Sandoval does not reset and cannot be attacked. After attempting to fix the situation by dropping the quest and retaking it, after dropping the quest it cannot be picked up again.

**Comment by TeridanDW** [comment]
Hello @roblockster , the issue you are experiencing has been fixed in #3918. However it is not on live realm yet.
Workaround for the issue is to do the quest after server crash/restart without dieing (so the encounter doesn't get stuck).
