### ISSUE TITLE
Random Dungeon Finder not random

### ISSUE THREAD

**Issue by Hr46ph** [dalaranwow/dalaran-wow#4654]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
I've been queuing for random dungeons since level 15, and been doing the same on several other characters and accounts (my son plays too). The thing is, with every level range comes several dungeons within that range. I've been almost exclusively getting only 1 dungeon from that list. I've seen Deadmines, Gnomeregan, SM (2),  Ulda, DM, BDDB.

I have never seen RC, WC, SK, Stockades, the list goes on and on.

**Expected behaviour**: Tell us what should happen instead
A reasonable chance to get a different dungeon when queuing 20 times during a day. While in theory, pure randomness could put me in the same dungeon every time during my entire lifetime, it is highly unlikely.

**Steps to reproduce the problem**:

1. Queue for a dungeon several times during different level ranges
2. See how often it puts you in the same dungeon.

**Include proofs for this behaviour**
Not sure how I can "prove" this one but the problem has been during all RDF ranges on different characters on different accounts. Whenever I enter the dungeon, the whole group basically complains and sometimes people leave because they don't want to do it again.

Thanks!

**Comment by TheRealestMcCoy** [comment]
What dungeon you also get depends on what levels are queuing up as well. Should see what levels are getting put in party and see the specific list if they are all high enough for those other dungeons.

**Comment by Hr46ph** [comment]
Can you please let me know the duplicate because I cannot find it.

If it is invalid, how can I improve so that it is accepted?

Thanks!

**Comment by robinsch** [comment]
Hey, just as @TheRealestMcCoy said. Everybody that queues for Dungeon finder joins the pool with the selected (or instances you can join) instances. You just having bad luck that's all. No bug here.

**Comment by Hr46ph** [comment]
Look at:
http://wowwiki.wikia.com/wiki/Dungeon_Finder#Dungeon_finder_instance_breakdown

And compose me a group of different levels, then find me single dungeon that would only fit that group. It is impossible.

I've leveled 9 levels the past few days and almost exclusively got BRD. For 9 levels, almost exclusively a single dungeon.

- On multiple accounts
- On different characters
- Online others complain about it.

I don't think I am just unlucky.

**Comment by robinsch** [comment]
> I have never seen RC, WC, SK, Stockades, the list goes on and on.

I personaly saw RC WC and Stockades.

**Comment by Hr46ph** [comment]
Of course you have :).

Ok. Every time I get the same dungeon I could ask every person who got that dungeon for the I-dont-know-how-many-time again to post here.

Would that be helpful?

I don't know, what can I tell you? I've done my job.

**Comment by robinsch** [comment]
Yes, and I can tell you that it's working fine. You are unlucky.
