### ISSUE TITLE
Quest: The summoning Chamber

### ISSUE THREAD

**Issue by Sagrath** [dalaranwow/dalaran-wow#466]
http://www.wowhead.com/quest=10602 (H)
http://www.wowhead.com/quest=10585 (A)

How it should work :

Drop the item Elemental Displacer from a creature inside the Deathforge and use it near the fetid pool to disrupt the summoning, it will spawn an elemental (Infernal Oversoul) you have to kill to complete the quest .

How it does work :

Using the Elemental Displacer has no effect, Infernal Oversoul is already spawned but you cant attack it.

**Comment by Daveonx** [comment]
Quest is working for both factions and [Infernal Oversoul] (http://www.wowhead.com/npc=21735/infernal-oversoul) is targetable by players. Minor issues with the quest is that he only spawns in one spot outside of the summoning area, when he should spawn in the center. Other issue is that he can be spawned infinite ammount by players who use the [Elemental Displacer](http://www.wowhead.com/item=30672/elemental-displacer)

**Comment by Rushor** [comment]
e812a3542a8aebc65143bcb0e1b3cb79de34ca93
- creature now spawn in the middle of the green slime
- creature is no longer summonable if there ais already a spawned unit of 21735 in 100 yards range

**Comment by Golganeth** [comment]
Requires improvements.

The displacer should only be usable inside the Chamber. You can't summon several elementals if you are close (you won't be able to use the quest item) however you can spam the quest item if you go far away. If you do, several elementals will have spawned once you go back to the spawning spot.

**Comment by Rushor** [comment]
thats derb :(

**Comment by Rushor** [comment]
4c35038800d3138b440b2c4fe282eb60d2b2d36e

* Cast 'Disrupt Summoning Ritual' only near Invis Deathforge Caster

**Comment by Jezzybane** [comment]
As far as i can see you can't finish the quest at all atm. Nowhere inside you can actually use the displacer and the graphics for the ritual aint even up. Nothing spawns.
