### ISSUE TITLE
Culling of Stratholme - Arthas reset on Mal'Ganis

### ISSUE THREAD

**Issue by Xandriarn** [dalaranwow/dalaran-wow#4662]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
Today while in a Heroic RDF group for Culling of Stratholme, one of our group activated Arthas from his 'waiting' location in Market Square while the group went to kill the Infinite Corruptor optional boss. We made it back just in time to see the gate close and Arthas start the encounter after his RP elements were complete. As luck would have it, only one member of our group made it under the gate before it closed on us. As expected, he and Arthas died and after resurrecting the player we waited for Arthas to respawn in Market Square so we could redo the boss encounter. After several minutes, one member ported back to the beginning where Arthas was waiting for the intro roleplay to begin. When activated, he did the entire intro speech and it looked like the instance would have to be done all over again. However, when it was time for the 10 waves of scourge, those did not spawn and Arthas went to the next checkpoint in front of the Town Hall. We did have to re-fight the waves of Infinite Dragonflight inside the town hall but again skipped the Chrono Lord boss battle and went directly to Market Row to go thru the long corridor of scourge. Once thru that area we were able to start the final Arthas RP and engage Mal'Ganis. However, we had to fight two copies of the boss. We did get credit for completing the dungeon upon killing one of them but the other did not despawn and we had to finish them both to complete the encounter. 

**Expected behaviour**: Tell us what should happen instead
After a wipe on the boss, Arthas should have respawned behind the Market Row gate where he waits for the player to tell him the Mal'Ganis encounter is ready to begin. Also, if a wipe occurs Mal'Ganis should not spawn again forcing you to fight two copies of him. If not for our very well geared tank we would not have been able to finish this.

**Steps to reproduce the problem**:

1. Run CoS instance up to the point that Arthas is waiting for you to start the Mal'Ganis encounter. 
2. Tell Arthas to start but don't enter the boss fight (or wipe on purpose).
3. Have to reset from the beginning (minus scourge waves and boss battles).

**Include proofs for this behaviour**

http://www.wowhead.com/the-culling-of-stratholme
http://www.wowhead.com/npc=26533/malganis

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

You can research this on several pages like http://wotlk.openwow.com or http://wowhead.com/

**Include Screenshots from the issue if necessary**

**Comment by TeridanDW** [comment]
I couldn't test this on the ptr, however i can confirm that:

> After a wipe on the boss, Arthas should have respawned behind the Market Row gate where he waits for the player to tell him the Mal'Ganis encounter is ready to begin.

is correct. 
Additional information - everytime Arthas stops and "asks" the party group for confirmation if they are ready (so he can continue ahead) is considered as a "checkpoint". And if the group wipes and the event ends at that point, the group should see and be able to continue from the last checkpoint which arthas passed before the wipe. In the case above that should be:

> Arthas should have respawned behind the Market Row gate

Retail uses an interesting mechanic for these cases (however i am not sure if that was the case during wrath retail) where arthas should move from checkpoint 1 to checkpoint 2 and then on reach checkpoint 2 despawns and at the same time spawns again (diffrent creature spawns on checkpoint 2) and this repeats at every checkpoint. With that in mind if group wipes we can respawn only the last "Arthas" as he will be the valid one and this:

> Also, if a wipe occurs Mal'Ganis should not spawn again forcing you to fight two copies of him.

should not happen.

**Comment by Rushor** [comment]
The instance has been rewritten with https://github.com/TrinityCore/TrinityCore/pull/17860. Once this fix has been merged it will be apllied on the live realm in the future.
