### ISSUE TITLE
Recruit a Friend Summons

### ISSUE THREAD

**Issue by Bonecramp** [dalaranwow/dalaran-wow#4663]
Recruit a Friend works as it is supposed to, however, there is no option to Grant a Level in the last 20 I've played with my daughter. The Summon a Friend feature does not work at all unless we are close to each other, and in that case, what is the point.

**Comment by Edzero** [comment]
The summon part is contained in #1935

The grant a level has certain conditions attached to it but it should be working correctly. Bare in mind that the person who was recruited can grant levels to the person who did the recruiting, and only that way around. You can't grant levels past 60.

**Comment by Bonecramp** [comment]
Thank you.
