### ISSUE TITLE
Demolishing Megalith

### ISSUE THREAD

**Issue by PheonixArrow** [dalaranwow/dalaran-wow#4664]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - Normal)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
Doesn't spawn (Go to 69.62 to see the pictures online where i took them)
**Expected behaviour**: Tell us what should happen instead
Spawn and roam around
**Steps to reproduce the problem**:

1. Start the quest
2. Go there
3. See that hes not there

**Include proofs for this behaviour**
Pictures : 
http://imgur.com/a/z2x4I
Him on WoWHead : http://www.wowhead.com/npc=24371/megalith ID= 24371
Quest WoWHead ally: http://www.wowhead.com/quest=11359/demolishing-megalith ID= 11359
Quest WoWHead hor: http://www.wowhead.com/quest=11367/demolishing-megalith ID= 11367
Guide on youtube: https://www.youtube.com/watch?v=Y3NfytTse38

**Include Screenshots from the issue if necessary**
http://imgur.com/a/z2x4I

**Comment by Golganeth** [comment]
Invalid report, the NPC is spawned. Closing up

**Comment by Dancingirl** [comment]
No he's not there...

**Comment by Dancingirl** [comment]
It's a quest AFTER the Lodestone when we have to kill him so for this specific quest ''Demolishing Megalith'' he doesnt spawn.
