### ISSUE TITLE
[NPC][Quest][Outland] "Trial of The Naaru: Tenacity" and Millhouse Manastorm

### ISSUE THREAD

**Issue by Craftymind** [dalaranwow/dalaran-wow#4665]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
I reached the last boss in **the Arcatraz heroic** and started the fight. [Millhouse Manastorm](http://www.wowhead.com/npc=20977/millhouse-manastorm) is released during the fight but he does absolutely nothing. I complete the fight, kill the boss and nothing happens (Same thing happens in the normal mode of the Arcatraz). Of course, my quest [Trial of The Naaru: Tenacity](http://www.wowhead.com/quest=10886/trial-of-the-naaru-tenacity) didn't complete.

**Expected behaviour**: Tell us what should happen instead
[Millhouse Manastorm](http://www.wowhead.com/npc=20977/millhouse-manastorm) once released, should walk and join the fight on the last boss, as seen here: https://youtu.be/MtNX8bZoDuM?t=799. Once the fight is over, the quest [Trial of The Naaru: Tenacity](http://www.wowhead.com/quest=10886/trial-of-the-naaru-tenacity) should complete.

Also, the NPC [Warden Mellichar](http://www.wowhead.com/npc=20904/warden-mellichar), who starts the fight, should be attackable from the start, however he's not currently. On the live server, we just need to walk near him to trigger the fight. Also, the spawn timer of each miniboss is relatively long. it should be much quicker as seen here: https://youtu.be/MtNX8bZoDuM?t=672.

**Steps to reproduce the problem**:

1. Acquire the [warpforged key](http://www.wowhead.com/item=30634/warpforged-key) and go to [the Arcatraz](http://www.wowhead.com/the-arcatraz) on heroic mode
2. Clear your way through until the last boss
3. Engage in the last fight
4. Notice the long spawn time of each miniboss + [Millhouse Manastorm](http://www.wowhead.com/npc=20977/millhouse-manastorm)'s behavior

**Include proofs for this behaviour**
![wowscrnshot_041017_175228](https://cloud.githubusercontent.com/assets/19840534/24874991/7166b7fa-1e1e-11e7-9dc0-41b6b46a84a3.jpg)

As you can see, even though the fight is over and the last boss is dead, [Millhouse Manastorm](http://www.wowhead.com/npc=20977/millhouse-manastorm) did not even move from his initial spot.

I'm only 1 step away to get my [Tempest key](http://wowwiki.wikia.com/wiki/Tempest_Key_guide) and this happens... Come on dalaran-wow :(

**Comment by ashido96** [comment]
#2666
