### ISSUE TITLE
Auction House implement full API

### ISSUE THREAD

**Issue by fsironman** [dalaranwow/dalaran-wow#4668]
**Current behaviour**:
Any Auction House addon cannot make use of the getall function in the Auction House API introduced in 2.4
http://wowwiki.wikia.com/wiki/API_QueryAuctionItems?oldid=1732901

**Expected behaviour**:
Auction House Addon making use of the getall function should get the whole AH listing in one query instead of having to scan the Auction House page by page.

**Steps to reproduce the problem**:
1.  Use Auctioneer Suite 5.8.4723 try to make a "fast" scan of the AH
2.  Scan is not working Auctioneer is scanning page by page.

**Include proofs for this behaviour**:
>  When using the "fast forward" button, from the "Scan Control Console", your client pulls the entire Auction House contents at once, so the scan is extremely fast [...]

http://wowwiki.wikia.com/wiki/Auctioneer_(AddOn)?oldid=2257361

**Easy Steps to fix the problem**:
Commit to TC which enables this:
https://github.com/TrinityCore/TrinityCore/pull/16469

**Comment by Rushor** [comment]
The issue was fixed in https://github.com/TrinityCore/TrinityCore/commit/3aaeb574050668e5a240078f6e40337c3975d110 in will be apllied with the next merge from TC Commits to the Dalaran-WoW-Source-Code.
