### ISSUE TITLE
[Spell] Casting spells doesn't reset melee swing timer

### ISSUE THREAD

**Issue by plznoz** [dalaranwow/dalaran-wow#4679]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
Casts does not reset the swing timer. Meaning a spellcaster could gain damage standing melee and auto attacking. Especially significant for elemental shamans with Flametongue Weapon.

**Expected behaviour**: Tell us what should happen instead
Casts that has a cast time should reset the swing timer.

**Steps to reproduce the problem**:
1. Play a caster, elemental shaman for example (Also easily observed with Warlock Imp).
2. Stand melee, cast lightning bolt continuously with auto attack enabled.
3. Observe melee swings between casts.

**Include proofs for this behaviour**
**Dalaran behaviour:**
http://www.worldoflogs.com/reports/cz8s20gav6o28xno/log/?s=2932&e=3357
`[{"eventTypes": [1, 2], "sourceNames": ["Hakonf"]}]`
![http://i.imgur.com/iCWGe7q.png](http://i.imgur.com/iCWGe7q.png)

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

**Comment by TeridanDW** [comment]
Confirmed. Spell casts seems to delay the swing timer instead of reseting it.

**Comment by Hanzemon** [comment]
I need to know, was that possible back in vanilla 1.12.1 to attack in between cast and the attack timer doesn't get reseted but delayed?. If you know this was possible at that patch specifically please respond to this, and if you have any prove it would be handy if you post it too.

**Comment by robinsch** [comment]
@TeridanDW Can you check this on PTR? As far as I can tell it works fine on PTR.

**Comment by TeridanDW** [comment]
Yes ofcourse. Tested and the result is the same @plznoz described.
An easy way to test it is to stay in melee distance for a creature > attack it > spam lighting bolt (or similar spell) > notice you do 1 autoattack between each cast.

**Comment by Hanzemon** [comment]
There is a Vanilla 1.12.1 server and the last patch change removed the spellcast between attacks so if you start casting a sell while you're attacking it will reset the attack timer so you have to wait 2 seconds + Weapon Speed Delay  to start attacking again, so, if there is any proof that in Blizzards Vanilla wow you were able to cast between Auto-Attacks without getting it resetted the way i just explained i would appreciate it :). The gm told me that if i find any proof that in Blizzard's vanilla it was like that the y could change it back.

**Comment by Hanzemon** [comment]
So in the end it is correct getting an attack in between casts when in melee, right? Or is it the problem, because it is the only mechanic that can make Enh Shamans viable for PvE in vanilla, i don't mean to be annoying.

**Comment by TeridanDW** [comment]
Works as intended on PTR.

@Hanzemon, I'm sorry I can't provide any information about how this mechanic worked back in vanilla, because I simply don't know (maybe it was the same, maybe it was added/changed in later patch).

**Comment by robinsch** [comment]
Can you confirm that instant spells work as intended too? For example shamans shocks don't reset swing timer.

**Comment by TeridanDW** [comment]
Confirmed that is works correctly with instant spells too (tested the shocks).

**Comment by Chenocide** [comment]
@TeridanDW How does this work for enhancement?

**Comment by TeridanDW** [comment]
@Chenocide it's on live, you can test it yourself. Everything should work properly for enhancement shamans.
