### ISSUE TITLE
[Mechanic] Black Qiraji Battle Tank missing audio

### ISSUE THREAD

**Issue by Chenocide** [dalaranwow/dalaran-wow#4684]
**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)

The Black Qiraji Battle tank mount is missing the sound of its "special" animation (the animation the mount makes when  you stand still and press space). 

The mount does perform the animation but the sound effect is missing. 

**Expected behaviour**: Tell us what should happen instead

When you stand still while mounted and press space, all mounts have a special animation. The Black Qiraji Battle Tank should perform the animation, along with the added sound effect. 

I know it's trivial at best but it really bugs me. 

**Steps to reproduce the problem**:

1. Mount up on the Black Qiraji Battle Tank.
2. Press space while standing still.
3. Profit???

**Include proofs for this behaviour**

You can research this on several pages like http://wowhead.com or http://wowwiki.wikia.com or http://www.youtube.com/
Issues without proofs will be closed and tag On Hold will be added until the proof is provided.

Video proof of the sound + animation from 2 seperate sources:

https://youtu.be/4bhqTc3RIvM?t=4s

https://youtu.be/gFSpaJT5B2k?t=1m15s

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

Black Qiraji Battle Tank item ID - 21176
Black Qiraji Battle Tank mount  - 15711
Missing sound                           - 15961

You can research this on several pages like http://wotlk.openwow.com or http://wowhead.com/

**Include Screenshots from the issue if necessary**

Youtube video of the missing audio:

https://youtu.be/3BMUk1F43Kk

**Comment by TeridanDW** [comment]
Thank you for the report @Chenocide .
Sound id is 15961 (i think).
http://www.wowhead.com/npc=15711/black-qiraji-battle-tank#sounds

**Comment by Rushor** [comment]
The special sounds for the mounts are handled by dbc, which cannot be changed here. 

Also i think that's intended. At least i could not found any source from wotlk patch 3.3.5 that shows that the pet should handle this sound. All other Qiraji Battle Tank mounts also don't play the special sound.

Closed for now until a source was profided that shows that the special sound for the Qiraji Battle Tanks was already there in 3.3.5.

Thank you.
