### ISSUE TITLE
VoA 10 loot bug

### ISSUE THREAD

**Issue by darkwyrm88** [dalaranwow/dalaran-wow#4686]
Vault of Archavon 10 man boss bugged during loot. 
Two druid items dropped. I master looted the first one, but when I went to do the second one, the loot window closed and I was unable to re-open it to masterloot the second item.
Item lost was [Hateful Gladiator's Wyrmhide Gloves]
Character: Fayrmune
Instance ID: 152
Archavon the Stone Watcher

**Comment by Edzero** [comment]
You will need to submit an in-game ticket with proof attached to resolve this.
