### ISSUE TITLE
[Website] Forgot password

### ISSUE THREAD

**Issue by v2b87** [dalaranwow/dalaran-wow#4698]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: The forgot password feature does not work. What comes up when you click the link is a page titled 'The page you are looking for cannot be found.'

**Expected behaviour**: The forgot password page should load correctly.

**Steps to reproduce the problem**:

1. Navigate to dalaran-wow website
2. Press 'account'
3. Press 'forgot password'

I understand the website was going through a construction period, but that was a year ago. Why is this feature still not working?

**Comment by TeridanDW** [comment]
Hello @v2b87 , the bugtracker is only for ingame issues. The only one that can answer your question is the server owner and he is aware of this issue.
Thank you.
