### ISSUE TITLE
Cant talk ingame :S?

### ISSUE THREAD

**Issue by Tacobo** [dalaranwow/dalaran-wow#4701]
![help](https://cloud.githubusercontent.com/assets/28494261/25816250/c69fabe4-3423-11e7-80f0-5ae30d81d33f.png)

Hey 

I can not talk to anyone for fifty thousand days, someone else who has the same problem?
Have tried to contact GM but they have not responded to 4 days now?

Anyone who has tips on what i can do?

**Comment by alexuktc** [comment]
Damn bruh. You must have done something very bad to get such a long chat ban.

**Comment by Tacobo** [comment]
I just started the account and bought instant 70 so that's strange

**Comment by TeridanDW** [comment]
Hello @Tacobo  , your account has been muted (for a reason probably), please write an ingame ticket and wait for GM to investigate your case.
Thank you.

**Comment by Tacobo** [comment]
@TeridanDW I been waiting for 4 days, like a said! so trying to reach a gm here !
