### ISSUE TITLE
[Quest bug] Recover the Key! 

### ISSUE THREAD

**Issue by Suprimee** [dalaranwow/dalaran-wow#4702]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
Hinterlands. When you complete the Quest Recover the Key! you can get the Quest again and again... the Quest must be not repeatable but it is and you can get a lot of levels from one Quest

**Expected behaviour**: Tell us what should happen instead
After completing the Quest you shouldn't be able to do it again and again 

**Steps to reproduce the problem**:

1. Go Hinterlands 
2. Take the Quest Recover the Key! 
3. Complete the Quest and take it again 
4. Repeat again step 2 and 3

**Include proofs for this behaviour**
http://www.wowhead.com/quest=7846/recover-the-key

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**
[quest=7846]

**Comment by TeridanDW** [comment]
Hello @Suprimee , thank you for the report, however this was already reported in #3893.

**Comment by Suprimee** [comment]
You are welcome, I hope soon to be fixed 
Have a nice day
