### ISSUE TITLE
[Black Temple] Illidary Council

### ISSUE THREAD

**Issue by alexuktc** [dalaranwow/dalaran-wow#4703]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
Two issues arise during this encounter:
1. The bosses do not die simultaneously. 3 of the bosses (The Mage, the Paladin and the Priest) die at the same time because they have the same health pool. The Rogue has a higher health pool (with around 120k more HP) and stays alive when they all die. 
2. Given enough time (I did not test exactly how much) they will respawn. Now this is following an Illidan kill.
- Basically you kill council and then kill Illidan. I went on the next day, the Teleport NPC did not give me the option to TP to Council so I got suspicious. Council was spawned and the door to Illidan was closed (even though he was already killed in that ID). We killed Council again and we saw Akama. His script went off again and he opened the door. Illidan was not present so nothing happened after that. It allows for farming (not that it's a big issue to farm outdated content)
**Expected behaviour**: Tell us what should happen instead
1. Bosses share a healthpool. 1 damage dealt to 1 boss means 1 damage done to the other 3. This is counteracted by a 75% damage reduction on all bosses. If one boss dies all bosses should automatically die. Now the damage reduction seems to work fine, as the Rogue takes way too much damage between the 120k and dying when the other bosses are dead.
2. They should not respawn. 

**Steps to reproduce the problem**:

1. Simply kill the boss. It's impossible to kill it without encountering the issue.
2. Go in the instance after 2-3 hours (or the next day if it takes longer).

**Include proofs for this behaviour**
https://www.youtube.com/watch?v=6vqFch6fGBM

**Comment by TeridanDW** [comment]
Hello, thank you for the report @alexuktc .
Confirming issue 1. the rogue indeed has more base hp (1222k) while the rest have 1062k. Also their shared hp mechanic seems to work in a very strange way. When you kill one of them the rest die 1 by 1 with short delay. Here is what i mean:
![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/6797611/25961919/8d1b35d8-3684-11e7-8d7d-02604d2af287.gif)

Regarding:

> This is counteracted by a 75% damage reduction on all bosses.

Could you explain what do you mean by that please? 
I saw this buff on 1 of them:
![image](https://cloud.githubusercontent.com/assets/6797611/25962053/08b6b58c-3685-11e7-8e16-18fbccc7d079.png)
is this what you mean?

Regarding issue 2. the bosses have 7d respawn timer on ptr. If they respawn there must be a core issue, I can't say more here.

I would like to add 2 more issue:

 3. If the group kills 1 of the 3 bosses ([High Nethermancer Zerevor]( http://www.wowhead.com/npc=22950/high-nethermancer-zerevor ) , [Gathios The Shatterer](http://www.wowhead.com/npc=22949/gathios-the-shatterer) , [Lady Malande](http://www.wowhead.com/npc=22951/lady-malande)) _**while**_  [Veras Darkshadow](http://www.wowhead.com/npc=22952/veras-darkshadow) has casted spell [Vanish](http://www.wowhead.com/spell=41476/vanish) and he is invisible ,he will die with that aura on him which makes him invisible to the group (they can't loot him).

**ID - 41476 Vanish**
Effect 2: Id 6 (SPELL_EFFECT_APPLY_AURA)
BasePoints = 9999
Targets (1, 0) (TARGET_UNIT_CASTER, NO_TARGET)
Aura Id 18 (SPELL_AURA_MOD_INVISIBILITY), value = 9999, misc = 4 (4), miscB = 0, periodic = 0

 4. Will update

**Comment by alexuktc** [comment]
From what I remember the rogue does indeed have more HP than the other bosses. This is to make sure you cannot just zerg him. The boss is not intended to have dps focused on him. Truth to be told all bosses should have different HP pools but die around the same time due to boss mechanics. 
An example is the priest having the least HP, but casting shield on herself which increases her HP and being the most often target for blessings from the paladin. The mage used to wipe any melee that tried to attack it.

> Could you explain what do you mean by that please?

Certainly. If you deal an attack normally doing 1k damage on 1 target, the attack will deal 250 (25%) damage to your target. The rest 750 damage will be evenly distributed between the other 3 bosses. This was the most crucial mechanic, because considering the low HP each boss has on his own you could just zerg one like no tomorrow. This makes sure you deal all the required damage to kill the boss. 

I do not have any specific logs, but I was a tester for another tbc server and this was very well documented there. If you have a command dealing exact damage to a unit you should be able to check if a reduction is working. 

Considering that the rogue now has 150k more HP than the other bosses, it would take ~600k damage to kill him after they die.

**Comment by Rushor** [comment]
The whole encounter has been rewritten here: https://github.com/TrinityCore/TrinityCore/commit/5af1fa22733c64e97f60967b36ea970a355d0598

With future merges the fix will be applied on the live realm. Thank you.

The issue was fixed by a developer and will be tested on the Public Test Realm in the future (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm in the future.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
