### ISSUE TITLE
Vote items

### ISSUE THREAD

**Issue by robika9** [dalaranwow/dalaran-wow#4708]
When I move cursor over items that can be purchased through vote points, it doesn't show details about the item(stats like strenght, agility, stamina etc.). I don't know if other face the same problem. (cursor isn't showed in the screenshot) 

![bez naslova](https://cloud.githubusercontent.com/assets/28685019/26032881/f0dc0dba-389e-11e7-90f5-f5b48c920d7d.jpg)

**Comment by TeridanDW** [comment]
Hello @robika9 , the bugtracker is only for in-game issues.
Reference for your issue - http://www.dalaran-wow.com/forums/input-and-assistance/community-support/topic/10197/vote-shop-bug
