### ISSUE TITLE
BM Pet low damage (BITE)

### ISSUE THREAD

**Issue by danysilva** [dalaranwow/dalaran-wow#4713]
Hi,

 I have been noticed that my pet does low damage, but now i realize that my pet ability (BITE) does not add any attack-power or anything, i have 4000 attack power and 700 Sp in the pet extra damage, BITE still do the damage amount of damage (160-200), i check in WoW head ( http://ptr.wowhead.com/spell=17253/bite#changelog ) ,(114-168+((RangeAttackPower(if 4000)x0.40)x 0.20)) = 320+168 =488 at least :)
![wowscrnshot_052117_132612](https://cloud.githubusercontent.com/assets/20100435/26283457/6f7755c8-3e29-11e7-8bf2-69ffc668a01d.jpg)
![wowscrnshot_052117_132623](https://cloud.githubusercontent.com/assets/20100435/26283459/7bae14d0-3e29-11e7-8f8f-5b747a387cb8.jpg)

**Comment by TeridanDW** [comment]
Hello @danysilva , thank you for the report.
This issue have been reported and addressed in #3774 and #3088.
