### ISSUE TITLE
[NPC] Young Wendigo (BUG)

### ISSUE THREAD

**Issue by sedenha** [dalaranwow/dalaran-wow#4717]
There's one Young Wendigo (NPC ID #1134) that's is bugged, and it is evading all kind of attacks in the coordinates [43.5 ; 54.4].
It should be fixed (when you attack it, you became permanently in combat mode).
![wowscrnshot_052417_213707](https://cloud.githubusercontent.com/assets/28940372/26432510/9ebe60a0-40d2-11e7-8f7e-ef7805d89982.jpg)

**Comment by Rushor** [comment]
moved to https://github.com/dalaranwow/dalaran-wow/issues/1954
