### ISSUE TITLE
[ICC] Dogs in front of putricide respawning (24 hours)

### ISSUE THREAD

**Issue by ashido96** [dalaranwow/dalaran-wow#4724]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
Precious and stinky respawn after rotface and festergut have already been killed in that raid lock out.
All the trash seems to currently re spawn at 24 hours after death (is this a bug?).
http://www.wowhead.com/npc=37217/precious
http://www.wowhead.com/npc=37025/stinky

**Expected behaviour**: Tell us what should happen instead
Precious should never respawn after rotface dies.
Stinky should never respawn after festergut dies.
http://www.wowhead.com/npc=36627/rotface
http://www.wowhead.com/npc=36626/festergut

**Comment by Rushor** [comment]
This has already been fixed on PTRand only needs to be apllied on the liverealm with the next updates.

```diff
@@ -378,6 +378,8 @@ class npc_stinky_icc : public CreatureScript
                _events.ScheduleEvent(EVENT_DECIMATE, urand(20000, 25000));
                _events.ScheduleEvent(EVENT_MORTAL_WOUND, 2*IN_MILLISECONDS);
                _events.ScheduleEvent(EVENT_DOUBLE_DAMAGE, 4*IN_MILLISECONDS);
                if (_instance->GetBossState(DATA_FESTERGUT) == DONE)
                    me->DespawnOrUnsummon();
            }

            void EnterCombat(Unit* /*target*/)

@@ -558,6 +558,8 @@ class npc_precious_icc : public CreatureScript
                _events.ScheduleEvent(EVENT_SUMMON_ZOMBIES, urand(20*IN_MILLISECONDS, 22*IN_MILLISECONDS));
                _events.ScheduleEvent(EVENT_DOUBLE_DAMAGE, 4*IN_MILLISECONDS);
                _summons.DespawnAll();
                if (_instance->GetBossState(DATA_ROTFACE) == DONE)
                    me->DespawnOrUnsummon();
            }

            void NormalDamage()
```
