### ISSUE TITLE
[ICC] Intercept/Charge on Sindragosa

### ISSUE THREAD

**Issue by plznoz** [dalaranwow/dalaran-wow#4727]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
Currently you can't use intercept in the Sindragosa room. It says either "Target too close" or "no path available" on both Sindragosa and the Ice Tombs.

**Expected behaviour**: Tell us what should happen instead
You should be able to intercept these targets.

**Steps to reproduce the problem**:

1. Play warrior on Sindragosa
2. Try to Intercept Sindragosa AND the Ice Tombs
3. Fail miserably

**Include proofs for this behaviour**
[https://youtu.be/YNdsWejfKyE](https://youtu.be/YNdsWejfKyE)

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**
Intercept id: **20252**
Charge id: **11578**

**Comment by TeridanDW** [comment]
Hello, this should be fixed with #3655.

**Comment by Crispybuilt** [comment]
Charge/Interecept on Sindragosa if fixed, however it doesn't work on Ice Tombs.
