### ISSUE TITLE
Lich King Thunderstorming

### ISSUE THREAD

**Issue by Drawsblood** [dalaranwow/dalaran-wow#4733]
[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
You are able to Thunderstorm spawned adds off the Lich King's throne during transitions. 

**Expected behaviour**: Tell us what should happen instead
No knockback on adds

**Steps to reproduce the problem**:

1.  Go to lich king
2. get to transition phase
3. thunderstorm

**Comment by Lothloryen** [comment]
Hello, thank you for the report.

It has been already corrected, it will be deployed during the next maintenance.
