### ISSUE TITLE
[ICC][Lady Deathwhisper hc] Cult Adherent and Cult Fanatic knockback interrupt

### ISSUE THREAD

**Issue by plznoz** [dalaranwow/dalaran-wow#4735]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
Currently you can stop them from casting Dark Martyrdom by using Typhoon or Thunderstorm.

**Expected behaviour**: Tell us what should happen instead
You should not be able to stop them from casting Dark Martyrdom.

**Steps to reproduce the problem**:

1. Play Deathwhisper hc
2. Typhoon/Thunderstorm when the adds try to cast Dark Martyrdom
3. Profit

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**
Fanatic Dark Martyrdom: 71236
Adherent Dark Martyrdom: 70903

**Comment by Lothloryen** [comment]
Hello there,

Thanks a lot for the report, this issue has been already corrected and it shall be applied to the live server with the next maintenance.
