### ISSUE TITLE
[ICC][Valithria Dreamwalker] Glyph of Holy Light not double dipping from Twisted Nightmares

### ISSUE THREAD

**Issue by strobe-light** [dalaranwow/dalaran-wow#4745]
**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
Glyph of Holy Light should double dip from all +% healing modifiers. Currently it does from standard ones (Divinity, Tree of Life aura), but not from Twisted Nightmares.

**Expected behaviour**: Tell us what should happen instead
Glyph of Holy Light should double dip from Twisted Nightmares. 
By double dip, I mean for example at 10 stacks of Twisted Nightmares (+100% healing) that Holy Light should heal for 2x normal healing, then Glyph of Holy Light should heal for 2x its normal healing as well, resulting in Glyph of Holy Light Heal = Pre-stacks Holy Light Heal x 2 x 0.1 x 2 = Pre-stacks Holy Light Heal x 0.4 (not including other modifiers)

**Steps to reproduce the problem**:

1. Play a Paladin on Dreamwalker
2. Go into Portals and take stacks of the Twisted Nightmares debuff
3. Cast Glyphed Holy Light on a target next to Dreamwalker

**Include proofs for this behaviour**
Dalaran
![image](https://user-images.githubusercontent.com/15903359/26979815-800c7dc4-4d73-11e7-8817-dc06fef0ab75.png)
At [20:04:37.968], HL heals for 24635 on Ordo and Glyph heals Dreamwalker for 2610 despite Ryley having 6 stacks (+60% healing). Suppression is not active on Dreamwalker at the time.
Expected Value: 24635 x 0.1 x 1.06 (ToL Aura) x 1.6 (Twisted Nightmares) = 4178.
Actual Value: 24635 x 0.1 x 1.06 (ToL Aura) = 2611. 
Therefore it is not double dipping

[Retail](http://www.worldoflogs.com/reports/ax7c5fwljuvuuir1/xe/?s=14240&e=14579&x=sourceName+%3D+%22Galadedrid%22%0D%0AAND+type+%3D+TYPE_HEAL%0D%0AAND+spell+%21%3D+%22Judgement+of+Light%22%0D%0AOR+spell+%3D+%22Twisted+Nightmares%22%0D%0AAND+type+%3D+TYPE_DAMAGE%0D%0AAND+targetName+%3D+%22Galadedrid%22%0D%0AOR+sourceName+%3D+%22Galadedrid%22%0D%0AAND+spell+%3D+%22Avenging+Wrath%22%0D%0AOR+spell+%3D+%22Guardian+Spirit%22%0D%0AOR+spell+%3D+%22Suppression%22%0D%0AAND+targetName+%3D+%22Valithria+Dreamwalker%22)
![image](https://user-images.githubusercontent.com/15903359/26979931-ef244796-4d73-11e7-8155-5ec775d4cca6.png)
At [23:51:48.639], HL heals for 44948 and Glyph heals Dreamwalker for 10505 with Galadedrid having 11 stacks (+110% healing).
44948 x 0.1 x 1.06 (ToL Aura) x 1.05 (Divinity) x (2.1) (Twisted Nightmares) = 10505. GoHL is clearly double dipping.

[Wowhead strategy discussion](http://www.wowhead.com/forums&topic=157793/a-question-about-beacon-and-dreamwalker)

> Your glyph heals for up to 10% of the original heal, but this amount receives all the relevant +% healing bonuses again.
This starts with your 5% divinity bonus, goes through 6% aura/tree bonus, 5% glyphed seal of light bonus, (now) 20% zone bonus, stacks bonus and ends with every temporary cooldown bonus.
If you have 20 stacks, then your glyph with CDs heals for up to
0.1 * 1.05 * 1.05 * 1.06 * 1.2 * 1.2 * 1.35 * 3 = 68% of the original heal
So while the bonus from healing someone with +% healing received talents is low at the begining, it scales very well with other buffs, especialy the stacks from the portals. Healing yourself with only 5% bonus received healing can result into the glyph heal being actualy higher than the original spell after 30 stacks, so imagine there is 40% bonus to the glyph heal instead.

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**
Twisted Nightmares: 71940
Holy Light: 48782
Glyph of Holy Light: 54968

**Comment by Rushor** [comment]
reason is that the spell has SPELL_DAMAGE_CLASS_NONE and therefore the bonus will not be calculated.

**Comment by Rushor** [comment]
Game/Spells: Glyph of Holy Light + Beacon of Light heal should have Damageclass: Magic to enable double dipping from percent mods

* closes: https://github.com/dalaranwow/dalaran-wow/issues/4745
* commit: ddaf789978fe2232010e12e73173fc8430a4ec86

The issue was fixed by a developer and will be tested on the Public Test Realm in the future (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm in the future.
This means that the issue exists in game at the moment i wrote this message.
**Only once the issue was marked with "Fixed - On Live Server", you can find the fix on your game server.**
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
