### ISSUE TITLE
warlock questline

### ISSUE THREAD

**Issue by laura379** [dalaranwow/dalaran-wow#4748]
Hello
I have completed the level 30 warlock quest for the blue robe, but i didnt get it as a reward and somehow i passed the level 20 for the succubus, also making me unable to complete the one for fellhound. There is no need for screenshots, i'm a level 46 blood elf warlock in need of help.

**Comment by Rushor** [comment]
Please write an Ingame-issue to a Gamemaster and the Gamemaster will then help you as soon as he can. Thank you.

The gamemaster will add you the item if you didn't got it. Thank you.

The quest itself and the itemreward works fine on PTR.

![GitHub Logo](http://i.imgur.com/bYkYeGQ.png)
