### ISSUE TITLE
NPC: Forged Iron Trogg - Halls of Stone

### ISSUE THREAD

**Issue by Crispybuilt** [dalaranwow/dalaran-wow#475]
**NPC Forged Iron Trogg - 27979**

- Issue: **Forged Iron Trogg** *(s)* are friendly during the encounter. They are not supposed to be friendly to players.

- How it should work: **Forged Iron Trogg** upon spawning has to attack nearby players, they also have one ability/spell called **Lighting Shock** - 50900 (2 second cast)

*5 Man Normal*
**Forged Iron Trogg** - 27979
**"Lighting Shock"** - 50900

*5 Man Heroic*
**Forged Iron Trogg** - 31390
**"Lighting Shock"** - 50900

![image](https://f.cloud.github.com/assets/5054924/938327/6620d874-00fb-11e3-85bc-e67e8b367b34.png)

http://wotlk.openwow.com/npc=27979
http://wotlk.openwow.com/npc=31390
http://wotlk.openwow.com/spell=50900
http://www.wowhead.com/npc=27979/forged-iron-trogg#abilities:mode=heroic

**Comment by Rushor** [comment]
it's attackable already http://i.imgur.com/JJhR545.jpg
