### ISSUE TITLE
[Warlock] Decimation and soul shard usage

### ISSUE THREAD

**Issue by ashido96** [dalaranwow/dalaran-wow#4760]
**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
If the duration of the decimation buff expires while casting soul fire it will consume a soul shard at the end of the cast when it should not.

**Expected behaviour**: Tell us what should happen instead
It should not consume the soul shard. 

https://wowgaming.altervista.org/aowow/?spell=63165
https://wowgaming.altervista.org/aowow/?spell=47825 (and other ranks)

**Comment by robinsch** [comment]
Proof?

**Comment by vasius** [comment]
after 20 casts on dummy i saw that it consumes the shard if u have one in your bag and if not then the cast goes to its full but at the end instead of release the ball it just fails

**Comment by TeridanDW** [comment]
Hello @vasius, @robinsch was asking for proof that what is said in the report was true for retail (wrath), like a video or some source of information.
