### ISSUE TITLE
website shop sorting

### ISSUE THREAD

**Issue by aglarcz** [dalaranwow/dalaran-wow#4761]
**Current behaviour**: clicking on category in website shops does nothing

**Expected behaviour**: clicking on for example "vote points" category should sort items by their cost

**Steps to reproduce the problem**:

1. open vote or donate shop
2. click on "vote points" category
3. items still listed randomly

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

its website problem, no IDs etc needed

**Comment by Rushor** [comment]
The issuetracker is for serverside and gamemechanic issues only. Please write an Ingame-issue to a Gamemaster and the Gamemaster will then help you as soon as he can. Thank you.

![GitHub Logo](http://i.imgur.com/bYkYeGQ.png)
