### ISSUE TITLE
Reedem vote points - WEBPAGE Problem

### ISSUE THREAD

**Issue by mbless** [dalaranwow/dalaran-wow#4762]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

On 23Jun2017 I reedemed  vote points for ONE unit of "Stained Shadowcraft Spaulders".  I confirmed this item one time and 70 vote points were withdrew and a second item was.

Only 1 item should have been sent and 35 vote points should have been withdrew

**Steps to reproduce the problem**:

1. Go to http://www.dalaran-wow.com/shop/vote/
2. Select item to send
3. Confirm item for the total amount of vote points

**Comment by steampunkdurotan** [comment]
I have a problem with the voting as well, I vote, but get no points. I  tried to get some shouldars, but it says I have to be a premium member for some reason, lol?

**Comment by Rushor** [comment]
The issuetracker is for serverside and gamemechanic issues only. Please write an Ingame-issue to a Gamemaster and the Gamemaster will then help you as soon as he can. Thank you.

![GitHub Logo](http://i.imgur.com/bYkYeGQ.png)
