### ISSUE TITLE
Midsummer fire festival

### ISSUE THREAD

**Issue by steampunkdurotan** [dalaranwow/dalaran-wow#4763]
Trying to complete the Midsummer events and the bonfire for Bloodmyst island is not there. Literally the Flame Keeper is all that is there.

**Comment by datbunneh** [comment]
I've just completed the achievement yesterday no problem.

**Comment by steampunkdurotan** [comment]
How did you manage to put out a fire that isn't there? I am literally there now.
![wowscrnshot_062417_102740](https://user-images.githubusercontent.com/29671447/27570194-c58b8786-5ac1-11e7-82a8-b13cb459774f.jpg)

**Comment by steampunkdurotan** [comment]
how did you put out a fire that isn't there?
I am here now.
![wowscrnshot_062617_224141](https://user-images.githubusercontent.com/29671447/27570203-e1bf91d6-5ac1-11e7-86c0-fbcc0116718e.jpg)

**Comment by Rushor** [comment]
Please write an Ingame-issue to a Gamemaster and the Gamemaster will then help you as soon as he can. Thank you.

![GitHub Logo](http://i.imgur.com/bYkYeGQ.png)
