### ISSUE TITLE
Raf Bug

### ISSUE THREAD

**Issue by Kazzi82** [dalaranwow/dalaran-wow#4765]
Hello Dalaran-wow
first tings first I LOVE THIS Wotlk best time in Wow... Love it love you!
second thing my Gf refered me to join soo x3 xp and a Mount for 2...
the only problem is. she havent got the mount(X-53 touring rocket) jet 
and i donatet 10 bucks to you for the mount... 
plx respond
Kazzi Out

**Comment by Rushor** [comment]
The issuetracker is for serverside and gamemechanic issues only. Please write an Ingame-issue to a Gamemaster and the Gamemaster will then help you as soon as he can. Thank you.

![GitHub Logo](http://i.imgur.com/bYkYeGQ.png)
