### ISSUE TITLE
The new weekly raid quest not available to hand in after completion

### ISSUE THREAD

**Issue by SadhuArch** [dalaranwow/dalaran-wow#4766]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**:
Take weekly raid quest from Archmage Lan'dalock (NPC ID=20735) outside the Violet Hold in Dalaran. This week it's Malygos Must Die! (quest ID=24584). Kill Malygos, get credit for quest. Head to Dalaran to hand it in to Archmage Lan'dalock and it's not possible.

**Expected behaviour**:
Same NPC (Archmage Lan'dalock (NPC ID=20735) who gives the quest should be able to complete it.

**Steps to reproduce the problem**:
1. Take the weekly quest from Archmage Lan'dalock in Dalaran
2. Kill the boss (Malygos for this week) and get credit for the kill (this is no issue)
3. Head to Dalaran and try hand it in to the same NPC (Archmage Lan'dalock outside the Violet Hold)

**Include proofs for this behaviour**
https://i.imgur.com/aCgoIrz.jpg
As you can see from this screenshot the quest is completed **(Malygos slain: 1/1 (Complete)**. But the NPC has a gray question mark above his head. And in the Objectives list to the right of the screen it reads "Return to Archmage Lan'dalock in Dalaran."

When spoken to this is his only dialog option: _(which is one of the daily heroic quests)_
https://i.imgur.com/EQ9tSWq.jpg

**Comment by Rushor** [comment]
This works already fine on PTR. Nevertheless i added the correct queststarter/ender for that npc again.

That fix needs to be apllied on the live sever then.

http://i.imgur.com/TRoVrcm.jpg

DB/Creature: Archmage Lan'dalock - Add ids for queststarter and questender

* closes: https://github.com/dalaranwow/dalaran-wow/issues/4766
* commit: 5d0c9a58764a0fee2be6cccf487e8089a0f43f00

**Comment by plznoz** [comment]
@Rushor It's week 2 now and people who did the quest the first week can't pick up a new weekly.

**Comment by Rushor** [comment]
@plznoz really?
