### ISSUE TITLE
Warlock demology Bug (talent decimation and molten core)

### ISSUE THREAD

**Issue by BIaireau** [dalaranwow/dalaran-wow#4771]
Don't know if its just for me but theses 2 talents (decimation and molten core) does not work. i mean i get the buff but its dont do the effets or anything. my decimation dont reduce the cast time and molten core dont affect my immolate or incinerate . Someone can help me ?

**Comment by Rushor** [comment]
https://wowgaming.altervista.org/aowow/?spell=63165

I cannot confirm this on PTR.

Without decimation buff (rank 1) http://i.imgur.com/ww4QbD0.jpg > 6 seconds casttime of Soul Fire
With http://i.imgur.com/Rh2MYbP.jpg http://i.imgur.com/Rh2MYbP.jpg > 4.8 seconds casttime

6 - (0.20 * 6) = 4.8.

Works fine for me.

Maybe you need to check you talents again. Ask a gamemaster that may help you. Thanks
