### ISSUE TITLE
[Quest][Classic] Hilary's Necklace - Missing Endevent

### ISSUE THREAD

**Issue by Rushor** [dalaranwow/dalaran-wow#4776]
https://wowgaming.altervista.org/aowow/?quest=3741

There should be an endevent after you completed this quest (including two textlines)

source: https://www.youtube.com/watch?v=pKcvDCGIGFE

**Comment by Rushor** [comment]
DB/Quest: Hilary's Necklace - Add quest endevent

* closes: https://github.com/dalaranwow/dalaran-wow/issues/4776
* commit: 45ce0c471deb9b3003063f171b025179232e8167

The issue has been fixed by a developer and will be tested on the Public Test Realm in the future (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm in the future.
This means that the issue exists in game at the moment i wrote this message.
**Only once the issue was marked with "Fixed - On Live Server", you can find the fix on your game server.**
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.

**Comment by TeridanDW** [comment]
Works as intended on PTR.
