### ISSUE TITLE
[Quest][Northrend] The fallen sisters

### ISSUE THREAD

**Issue by koray61** [dalaranwow/dalaran-wow#4777]
Recently i've tried to do this quest and what you exactly need to do is free the chill nyrmph from it's evil powers by using an item lurielle's pendant but when using it on the creature instead of getting them free from their evil powers nothing happens and he just aggro's you

http://www.wowhead.com/quest=11314/the-fallen-sisters

Also here is an explaination how it should work: https://www.youtube.com/watch?v=Y2ZLZJwQfvU

Screenshot of issue: <a href="http://nl.tinypic.com?ref=5vws2a" target="_blank"><img src="http://i67.tinypic.com/5vws2a.jpg" border="0" alt="Image and video hosting by TinyPic"></a>

**Comment by koray61** [comment]
When using the quest item on the creature it should free from it's evil powers but instead he just aggro's you and nothing happens

**Comment by Rushor** [comment]
we already discussed this in https://github.com/dalaranwow/dalaran-wow/issues/1665#issuecomment-224668632 and we were not able to find a source that you get an errormessage at 100 %.

In WotlK you could only get the credit if you used the item at 30 % HP https://www.youtube.com/watch?v=bmXfzAAyWbs

Nevertheless i will add that you are no longer able to cast the spell if the chill nymph has 100 % HP, but instead only at 0-30 % HP.

**Comment by Rushor** [comment]
DB/Quest: The fallen sisters - Conditions for spell Lurielle's Pendant

* cast Lurielle's Pendant only at targets (Chill Nymphs) with equal or lower 30 percent health
* closes: https://github.com/dalaranwow/dalaran-wow/issues/4777
* commit: e023a5ae4c0682fb50228c3f6b43d7332a169f1c

![](http://i.imgur.com/XlZQVzt.jpg) > at 100 percent health

_________________________
![](http://i.imgur.com/02X9e2l.jpg) 
![](http://i.imgur.com/wJGDhjp.jpg)
 > at <= 30 percent health

**Comment by koray61** [comment]
Well didn't knew that you don't have to make any changes if it was supposed to be used at 30% hp didn't knew that tho sorry for the confusing and my mistake didn't read well than .. my fault !

**Comment by TeridanDW** [comment]
Condition works as intended on PTR.

Note: Error message if quest item used at 100% hp still unknow.
