### ISSUE TITLE
[Dungeon] The Violet Hold

### ISSUE THREAD

**Issue by koray61** [dalaranwow/dalaran-wow#4779]
The voilet hold dungeon once you get in the dungeon the portals are already active which is not supposed to be until you speak with the npc that starts the event and even mobs keep spawning without even starting the event which also should not be that way

The dungeon just keeps bugging entirely out please take a look at the scripts of the dungeon itself and corect whatever is needed cause its getting out of hand

This dungeon is litteraly bugged it is not even possible to do this dungeon right everything bugs out in this dungeon please do something about it or at least disable this dungeon until furher plans or whenever you fix the ciritcal issue's within the dungeon itself

EDIT: The bosses work fine but the dungeon itself is the main critical issue that has to be looked at the wave spawning portals etc)

We haven't spoken to the ally that starts the event of the dungeon and the portals are already there which is not supposed to be like that and minions keep appearing out of the portals as well and they all form in a group at the door and trying to break the gate

Screenshot and a example of what's going on throughout the dungeon itself: <a href="http://nl.tinypic.com?ref=eg6ah3" target="_blank"><img src="http://i66.tinypic.com/eg6ah3.jpg" border="0" alt="Image and video hosting by TinyPic"></a>

**Comment by koray61** [comment]
The portals should not be active as long as you haven't spoken with the lady shown in the picture neither the creatures should not spawning as long as you haven't spoken with the lady as i've mentioned already

**Comment by Rushor** [comment]
issue moved to https://github.com/dalaranwow/dalaran-wow/issues/3452 - it will be fixed there. Thanks
