### ISSUE TITLE
[Dungeon] Azjol-Nerub

### ISSUE THREAD

**Issue by koray61** [dalaranwow/dalaran-wow#4780]
Hodronox the second boss of this dungeon is pretty bugged alot of adds keeps spawning constantly during at the time and hi's hitpoints stay at max health whenever you keep damaging him

**Comment by ashido96** [comment]
The hitpoints stay at  max due to how he interacts with the adds (working correctly), when he is pulled up to the top (or allowed to come up top after you kill the 3 crushers) the adds will stop spawning.

**Comment by Rushor** [comment]
Yep that's an intended behaviour - Make shure that you kill the adds away from him and you will be able to kill the boss once the last add was killed. Thanks.
