### ISSUE TITLE
[Dungeon Finder] Teleportation

### ISSUE THREAD

**Issue by koray61** [dalaranwow/dalaran-wow#4781]
Sometimes i've experienced a bug that when you leave out of the dungeon to repair something for example and try to re-teleport to the dungeon it says invalid teleportation location or something like that so that means that you cannot teleport back into the dungeon while your group is still active in its process throughout the dungeon

**Comment by ashido96** [comment]
This happens when falling, flying, swimming, (on mount sometimes), etc... get off all at mounts and stop movement and you should be able to tp in just fine.

**Comment by Rushor** [comment]
Yes that's intended behaviour to prevent buguse inside the dungeonThank you
