### ISSUE TITLE
[World Events] Midsummer Festival

### ISSUE THREAD

**Issue by koray61** [dalaranwow/dalaran-wow#4782]
In certain places the midsummer festival is still active as you can grab the 10% xp from the large pole for example in howling fjord at camp winterhoof and so on there might be other places as well where midsummer festival is still active

<a href="http://nl.tinypic.com?ref=f4fz84" target="_blank"><img src="http://i67.tinypic.com/f4fz84.jpg" border="0" alt="Image and video hosting by TinyPic"></a>

**Comment by Rushor** [comment]
This was already fixed on PTR and will get merged from TC soon.

Closed - as the fix for it will get merged soon.
