### ISSUE TITLE
Website password reset is broken (404)

### ISSUE THREAD

**Issue by Gephorian** [dalaranwow/dalaran-wow#4787]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)

From the login page, hitting "Forgot password" does nothing. Copying the URL into the address bar results in a 404 from Cloudflare.

**Expected behaviour**: Tell us what should happen instead

The "Forgot Password" page/form should appear.

**Steps to reproduce the problem**:

1. Go to http://www.dalaran-wow.com/account/
2. Either click "Forgot password?" or copy/paste http://www.dalaran-wow.com/forgot-password/ into the address bar
3. You will get no response on the login page or a 404 if copied and pasted

**Include proofs for this behaviour**

n/a - website related

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

n/a - website related

**Include Screenshots from the issue if necessary**

**Comment by Rushor** [comment]
The issuetracker is for serverside and gamemechanic issues only. Please write an Ingame-issue to a Gamemaster and the Gamemaster will then help you as soon as he can. (Or create a new Ingame-Account in order to be able to talk with a gamemaster with you new level 1 character) Thank you.

![GitHub Logo](http://i.imgur.com/bYkYeGQ.png)
