### ISSUE TITLE
Wintergrasp Shoulders for S8 still unavailable

### ISSUE THREAD

**Issue by roblockster** [dalaranwow/dalaran-wow#4793]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Wintergrasp Titan-Forged shoulder items not available

**Expected behaviour**: Wintergrasp shoulder pieces should be available

**Steps to reproduce the problem**:

1. Look at Wintergrasp gear vendor's item selection
2. See that shoulders are not available
3. /wrists

**Include proofs for this behaviour**
http://wowwiki.wikia.com/wiki/Stone_Guard_Mukar

**Comment by Edzero** [comment]
@Lothloryen pls halp.
