### ISSUE TITLE
[Quest] A Fall From Grace

### ISSUE THREAD

**Issue by koray053** [dalaranwow/dalaran-wow#4795]
You cannot speak with the npc called High Abbot Landgren after you have ringed the bell

http://www.wowhead.com/quest=12274/a-fall-from-grace

**Comment by ashido96** [comment]
https://github.com/dalaranwow/dalaran-wow/issues/289

**Comment by Badjourasmix** [comment]
A few months ago I did with my paladin and it was working, I was trying to do it today with my Death Knight and the guards dont go up and you cant talk to the npc. Something I've noticed is that when the server restarts some quests start working again.

**Comment by Edzero** [comment]
Several quests will only work for the first person after a server restart
