### ISSUE TITLE
Toravon in VoA10 not Spawn Broken Attum

### ISSUE THREAD

**Issue by Nasfratus** [dalaranwow/dalaran-wow#4797]
Dear Dalaran-WoW,
Toravon in VoA10 have broken attum.
Official attum for spawn Toravon in VoA10 was you need clear ToC10, but its not true ... 
In VoA10 for spawn Toravon you need now ToC10+ToC25 ... if anyone have only ToC10 Toravon not spawn.
 
Toravon the Ice Watcher 10 will require Trial of the Crusader 10. this was writed on website before Toravon and season was opened..
But now still you need too ToC25 if you dont have ToC25 in VoA10 Toravon not spawn.

**Comment by ashido96** [comment]
#4767 duplicate,
