### ISSUE TITLE
Heirloom not mailed correctly

### ISSUE THREAD

**Issue by enemyr000** [dalaranwow/dalaran-wow#4801]
Hello! I play in the server algalon and had a weird bug. I wanted to change one of my characters race and name so i deleted with the intention of starting from zero, so i got all the gold that i could and mailed what was important, a Arcanite Reapear heirloom too. The thing is, after deleting the character i went on to check on my hunter(named Nettuno), the mail was there but not the item, and it's still there but no item at all, hope i can get some help and thanks for the attention!

**Comment by warcraftgeekygamer** [comment]
The trick is not to burn your house down before you sell it.

http://www.dalaran-wow.com/forums/community/general-discussion/topic/10647/missing-heirlooms-mail
