### ISSUE TITLE
Solstice Hunters

### ISSUE THREAD

**Issue by koray053** [dalaranwow/dalaran-wow#4802]
Whenever the solstice hunter begins to transform into a wolf hi's attack animation does not seem to be normal as it should be 

<a href="http://nl.tinypic.com?ref=fyn1qw" target="_blank"><img src="http://i64.tinypic.com/fyn1qw.jpg" border="0" alt="Image and video hosting by TinyPic"></a>

**Comment by ashido96** [comment]
Once again, what is the mob ID, does it change ID after it transforms, is it an entirely different mob, is there any other relevant information here that might be required to know what the bug actually is.

**Comment by koray61** [comment]
@ashido96 The mob id is http://www.wowhead.com/npc=26389/solstice-hunter it does not have a follow up ID when he transfors its just the one that i've mentioned above (link) ones whenever the human transforms into a wolf creature hi's attack animation does not show up but whilst he deals damage the only thing that is kinda bugged here is that their attack animations are missing

**Comment by TeridanDW** [comment]
Hello and thank you for the report @koray053.
I can't reproduce the problem on PTR, I see them auto attacking me normaly.
![image](https://user-images.githubusercontent.com/6797611/31586544-27603dce-b1db-11e7-806c-65f34eded694.png)
