### ISSUE TITLE
[Quest] Silver Lining

### ISSUE THREAD

**Issue by koray61** [dalaranwow/dalaran-wow#4804]
When you pick up the ghoul it should dissepear far as i know but it just stands at the same place and you can just constantly click on him to recieve 0 out of 5 times to get the quest completed easily

EXACT NAME OF THE NPC: Gooey Ghoul Drool

http://www.wowhead.com/quest=12643/silver-lining

**Comment by ashido96** [comment]
Stop leaving out relevant information, there's a template for people like you to use, stop deleting it.
http://www.wowhead.com/npc=29856/gooey-ghoul-drool
http://www.wowhead.com/spell=55363/create-gooey-ghoul-drool
http://www.wowhead.com/item=38687/gooey-ghoul-drool
