### ISSUE TITLE
[Quest] It Rolls Downhill

### ISSUE THREAD

**Issue by koray053** [dalaranwow/dalaran-wow#4807]
**Current behaviour**: When you use the following quest item called Scepter of Suggestion on the Blight Geist the Blight Geist does not follow you when you have charmed him with the quest item mentioned above the Blight Geist stands still at the place were you have charmed him and does not move any further as hi's being stuck after you have used the quest item as i have mentioned before
**Expected behaviour**: When you have used the quest item Scepter of Suggestion the Blight Geist should follow you when hi's being charmed
**Steps to reproduce the problem**:

1. Use the Scepter of Suggestion on the Blight Geist while you're on the quest
2. 
3. 
**Include proofs for this behaviour**
Quest: http://www.wowhead.com/quest=12673/it-rolls-downhill
Quest Item: http://www.wowhead.com/item=39157/scepter-of-suggestion
Npc/Creature: http://www.wowhead.com/npc=28750/blight-geist

<a href="http://nl.tinypic.com?ref=b4ckrc" target="_blank"><img src="http://i63.tinypic.com/b4ckrc.jpg" border="0" alt="Image and video hosting by TinyPic"></a>

**Comment by TeridanDW** [comment]
#4642
