### ISSUE TITLE
[Quest] Valkyrion Must Burn

### ISSUE THREAD

**Issue by koray053** [dalaranwow/dalaran-wow#4810]
Current behaviour: Everything seem to work fine you can hop on the harpoon machine to shoot fired harpoons but the only issue here is that a sack is missing something that looks like it in order to make an house burn
Steps to reproduce the problem: Hop on the harpoon machine and look at the valkyrion houses there should be sacks around the corners of each house as i've watched an youtube video of the quest

Video of explanation: https://www.youtube.com/watch?v=nPjjRCWut8I

Include proofs for this behaviour

Quest: http://www.wowhead.com/quest=12953/valkyrion-must-burn
Quest Item: http://www.wowhead.com/item=42160/incendiary-harpoons
Npc/Creature: None

<a href="http://nl.tinypic.com?ref=2s7e3qb" target="_blank"><img src="http://i64.tinypic.com/2s7e3qb.jpg" border="0" alt="Image and video hosting by TinyPic"></a>

**Comment by Coztume** [comment]
Already reported in #3443, they are there but you just can't see them due to the reduced draw distance.
Also use the search function before submitting a bug report in the future, not the first duplicate you've made.

**Comment by TeridanDW** [comment]
#3443
