### ISSUE TITLE
[Mage][Talent] Hot Streak

### ISSUE THREAD

**Issue by Synathy** [dalaranwow/dalaran-wow#4816]
**Current behaviour**
The mage's Hot Streak isn't consummed until Pyroblast **hits** his target.

**Expected behaviour**
Hot Streak's buff should be consummed once the mage **uses** Pyroblast.

**Steps to reproduce the problem**
1. Get Hot Streak's talent
2. Get the buff "Hot Streak" by doing two critical hits, one after the other within 10 seconds using any of these spells: Fireball, Fire Blast, Scorch, Living Bomb (the explosion upon debuff's fade away) or Frostfire Bolt
3. Keep an eye on Hot Streak and use Pyroblast

**Proofs for this behaviour**
April's 3rd, 2010 video: https://www.youtube.com/watch?v=RA8n2gyenbU
- At 0:14, the player gains Hot Streak. He's currently casting Fireball (finishing casting a Fireball, he's casting another one).
- At 0:16, the mage finishes casting his Fireball and uses Pyroblast right after, he no longers have Hot Streak.
- At 0:18, Pyroblast hits the boss.

**Spells ID**
- **Hot Streak spell id (Buff) : 48108**
- Pyroblast (rank = id) : 1=11366, 2=12505, 3=12522, 4=12523, 5=12524, 6=12525, 7=12526, 8=18809, 9=27132, 10=33938, 11=42890, 12=42891
- Hot Streak spell id (Talent 1/3) : 44445
- Hot Streak spell id (Talent 2/3) : 44446
- Hot Streak spell id (Talent 3/3) : 44448

**Comment by plznoz** [comment]
https://github.com/dalaranwow/dalaran-wow/issues/2186

**Comment by TeridanDW** [comment]
Will be handled in #2186.
