### ISSUE TITLE
refer a freind mount not working  on kt

### ISSUE THREAD

**Issue by oorworm** [dalaranwow/dalaran-wow#4827]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

The refer a freind mount can not be send to characters wich are located on the kirin Tor server.

It would be cool if this would be possible aswel.

Regards Oorworm

**Comment by Rushor** [comment]
The issuetracker is for serverside and gamemechanic issues only. Please write an Ingame-issue to a Gamemaster and the Gamemaster will then help you as soon as he can. (Or create a new Ingame-Account in order to be able to talk with a gamemaster with you new level 1 character) Thank you.

![GitHub Logo](http://i.imgur.com/bYkYeGQ.png)

**Comment by oorworm** [comment]
Hello
Ik am not sure if there is an admin on kirin tor.Only thing i want is the recruit a freind mount x-53 ons the character Bluezz ons That server.Ik can not send it there over the website.
Can u arange Thatcher pls for me.
Regards


Verzonden vanaf mijn Samsung Galaxy-smartphone.
-------- Oorspronkelijk bericht --------Van: Rushor <notifications@github.com> Datum: 29/07/17  11:09  (GMT+01:00) Aan: dalaranwow/dalaran-wow <dalaran-wow@noreply.github.com> Cc: oorworm <nataschsimons@gmail.com>, Author <author@noreply.github.com> Onderwerp: Re: [dalaranwow/dalaran-wow] refer a freind mount not working on kt
  (#4827) 
Closed #4827.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/dalaranwow/dalaran-wow","title":"dalaranwow/dalaran-wow","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/dalaranwow/dalaran-wow"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Closed #4827."}],"action":{"name":"View Issue","url":"https://github.com/dalaranwow/dalaran-wow/issues/4827#event-1184458703"}}}
