### ISSUE TITLE
[Dungeon][Creature] Pit of Saron - Ick

### ISSUE THREAD

**Issue by koray053** [dalaranwow/dalaran-wow#4838]
Current behaviour: Ick & Krick the boss when the encounter casts the following spell called explosive the spell usually isn't showing up as it's supposed to for example the explosives and such http://www.wowhead.com/spell=69263/explosive-barrage

Video how it's supposed to be: https://www.youtube.com/watch?v=qwEFrHnMyyQ_A skip to 1:10 to see the retail functional explosive barrage spell and how it's supposed to be shown

Npc Creature: http://www.wowhead.com/npc=36476/ick
Npc Spell: http://www.wowhead.com/spell=69263/explosive-barrage

**Comment by koray053** [comment]
EDIT: http://www.wowhead.com/spell=69263/explosive-barrage it works on normal but not on heroic just noticed that

**Comment by Lothloryen** [comment]
Hello there, It will be corrected after the next realm restart.

Thank you.
