### ISSUE TITLE
Item: Carrot on a Stick

### ISSUE THREAD

**Issue by Sagrath** [dalaranwow/dalaran-wow#485]
Carrot on a Stick is a trinket reward from a quest you get in The Shimmering Flats to get Gahz'Rilla's electrified scale
Quest: http://old.wowhead.com/quest=2770
It should increase your mount speed by 3% but it does not

**Comment by Rushor** [comment]
8accf896f228bbc2ea3ccf85d98a3b1438d70ef4
- speedbuff will now be added

**Comment by Golganeth** [comment]
Seems to add too much % when below level 70. Around 5% for 60% mount and 6% for 100% mounts (instead of 3%)

The in-game tooltip doesn't mention "Does not work for players above level 70." internet tooltips do though.
