### ISSUE TITLE
Quest objective tracker not working

### ISSUE THREAD

**Issue by lucas180692** [dalaranwow/dalaran-wow#4850]
hello people,

ive downloaded the WOTLK client from the dalaran site and started playing. but for some reason my quest objective tracker is not working. anyone who can help me?

**Comment by Crispybuilt** [comment]
Sometimes it glitches out for no apparent reason, so all you have to do is to drop out a quest from your log and it will be visible again.

**Comment by lucas180692** [comment]
the weird thing is, it happens to all quests.. and only to one character :p

**Comment by Rushor** [comment]
This is a client side issue only. Try to delete you cache and relog/reload. Also make sure that you dsiable all your addons

It's also an isue on retail.

Please see:
https://www.google.de/search?source=hp&q=Quest+objective+tracker+not+working+blizzard

for more information.
