### ISSUE TITLE
'Dinner Impossible' achievement with LITERALLY impossible criteria.

### ISSUE THREAD

**Issue by Senjan92** [dalaranwow/dalaran-wow#4854]
**Current behaviour:** Within the 'Cooking' tab of **Professions** in Achievements, a criteria for the **'Chef' title** ('Hail to the chef'), is to complete a sub-achievement called **[Dinner Impossible]**. In this achievement, you are to present a [Great Feast] within five battlegrounds:

Alterac Valley, Arathi Basin, Warsong Gulch, Strand of the Ancients & Eye of the Storm.

**However**, the achievement lives up to its name as impossible due to it being **impossible to queue for Strand of the Ancients on the Algalon - Main Realm (PVP)**, making the criteria impossible to fulfill.
______________________________________________________________________________________________________________

**Expected behaviour**: As in retail, one would simply just queue for the battleground, and upon granted entrance go in and place down the [Great Feast] just like any other battleground, then complete the objective for said achievement. 

**Steps to reproduce the problem**:

1. Be high enough level to be eligible to queue for Strand of the Ancients. (80, AFAIK?)
2. Attempt to queue for the battleground.
3. Sadly receive the message **"This Battleground has been disabled. You can't join the queue."**
, and thus have no possible way to fulfill your achievement criteria. 

**Included proofs for this behaviour:**

The achievement & criteria: http://www.wowhead.com/achievement=1785/dinner-impossible
The feast to complete said criteria: http://www.wowhead.com/item=34753/great-feast
The way shown to complete said criteria: https://www.youtube.com/watch?v=d8kOqTafJP4

Notice in the Youtube-video how the objectives subtract one-by-one upon [Great Feast] placement. 
**(The achivement is objective-toggled and can be seen to the right.)**

![abc1](https://user-images.githubusercontent.com/17743672/29615032-b363c96a-880c-11e7-9c78-2e7834343a37.png)
![abc2](https://user-images.githubusercontent.com/17743672/29615033-b3642a54-880c-11e7-912c-a37f40def263.png)

**Comment by TeridanDW** [comment]
Hello @Senjan92,
 There isn't any bug here that should be fixed, achievement is working properly, it's just that the battleground is closed for the moment. When it is opened everyone will be able to complete it.

**Comment by Lothloryen** [comment]
Hello there,

Since Strand of the Ancients has received several corrections, it will be open again tomorrow.

Thank you.
