### ISSUE TITLE
[Priest][Spell] Renew doesn't crit

### ISSUE THREAD

**Issue by mattdotax** [dalaranwow/dalaran-wow#4859]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Renew spell ticks doesn't crit.

**Expected behaviour**: Renew ticks should be able to crit normally depending on the priest crit rating

**Steps to reproduce the problem**: cast renew with every priest spec and watch if it ever crits.

**Include proofs for this behaviour**:
Ticks from Renew can crit. The crit for each tick is calculated individually based on the crit levels of the priest at the time the spell was cast. From https://wow.gamepedia.com/Renew

**Spell ID**: [spell=48068] https://wowgaming.altervista.org/aowow/?spell=48068

**Comment by TeridanDW** [comment]
Hello @mattdotax, thank you for the report.
Can confirm the issue on ptr.
Additional information from http://www.wowhead.com/spell=139/renew#comments


> 2 | By Olicon (274 – 5) on 2009/05/19 (Patch 3.1.1)
> How does the crit gets calculated? Does each tick has your crit chance, or is your crit chance divided up as well?
> 2ov3rk11l on 2009/06/01 (Patch 3.1.2)
> I believe the instant renew effect is applied right after you cast the spell, and so it would just get your normal crit chance. //www.wowhead.com/?spell=63543 

Issue may be related to #3055

**Comment by Marquito01** [comment]
Renew ticks (all wotlk hots, except rejuv with T9) couldnt crit during wotlk, thats from cata+. Only thing that can crit on renew is Empowered Renew from holy tree.

https://typehforheals.com/2010/09/23/cataclysm-beta-haste-and-hots-a-quick-example/
