### ISSUE TITLE
[NPC] Argent Guard Thaelrid (Kirin Tor)

### ISSUE THREAD

**Issue by Devhis** [dalaranwow/dalaran-wow#4863]
**Current behaviour**: The questgiver in Blackfathom Deeps Argent Guard Thaelrid is currently a hostile mob on the Kirin Tor server (at least on Horde Side), making it unable to give the quest Blackfathom Villany, which he is supposed to give. 

**Expected behaviour**: The NPC Argent Guard Thaelrid should be friendly for both Alliance and Horde, giving a chance for said quest to be completable.

**Steps to reproduce the problem**:

1. Clear Blackfathom Deeps up onto the first boss Ghamoo-ra as an Horde character.
2. Enter the cave nearby where Argent Guard Thaelrid is.
3. Observe that he is a hostile, without possible interaction except combat.

**Include proofs for this behaviour**
Here you can see the Argent Guard Thaelrid in Kirin Tor server as a Horde character.
http://imgur.com/1DcpRgT

http://wowwiki.wikia.com/wiki/Scout_Thaelrid
Here is Argent Guard Thaelrid's WoWWiki page, you can confirm that he is supposed to friendly for both Alliance and Horde.
Note- The NPC name has since been updated to Scout Thaelrid but this doesn't change anything, since even before the update he was friendly, as is on Algalon server.

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

You can research this on several pages like https://wowgaming.altervista.org/aowow/ or https://wowhead.com/

**Include Screenshots from the issue if necessary**

**Comment by TeridanDW** [comment]
This is working as intended on PTR, it will be applied on KT in the future (I can't say when exacly).
![image](https://user-images.githubusercontent.com/6797611/31547583-8b75e87e-b030-11e7-8f32-85bdfef202d8.png)

**Comment by Devhis** [comment]
So anything that is bugged on Kirin Tor will just be marked as Invalid Report? Sorry to say but from the answer I've got it seems like this issue is never going to be fixed.
