### ISSUE TITLE
RDF Glitch

### ISSUE THREAD

**Issue by robbbs** [dalaranwow/dalaran-wow#4869]
Every time I join a new rdf queue it says <1min for about a second then jumps to this ongoing counter... Since this glitch I've not been able to find a group... I first thought it could be that no one else was queuing so I went on to my rouge of similar level and queued for only one specific dungeon and someone was in the queue (the timer glitch is not on that toon), then when I relog to the glitched toon and try the same dungeon the counter glitch still happens, not showing my roles selected or anything. This is extremely frustrating because PvE is why I play the game and put most of game time on this server and on this toon :(
![glitch](https://user-images.githubusercontent.com/31719562/30145856-5a635b9e-9362-11e7-8840-d47c85330f3a.png)

**Comment by ashido96** [comment]
If the queue pops and someone is afk you get pushed to the end of the queue (stupid slothlorian), could this be happening while you are afk? I've never personally ran into my own role never showing up.

**Comment by Lothloryen** [comment]
Hello there,

This issue should be already solved and on live. Also, @ashido96 , keep it respectful, please.

Thank you for the report.
