### ISSUE TITLE
T10 Resto Druid 4set

### ISSUE THREAD

**Issue by Slashkill** [dalaranwow/dalaran-wow#4873]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)

Currently i've tried to proc Resto Druid 4set T10 in Combat and Out of Combat neither seems to work. There is the possibility that the procs seem to occur on targets already affected by Rejuvenation which i haven't actually checked but that should still not occur.

I can't seem to get any procs in any way using 4set.

**Expected behaviour**: Tell us what should happen instead

Expected behaviour - Every single Tick of Rejuvenation should have 2% chance to proc a new rejuv and a new target unaffected by Rejuvenation for 100% of it's original duration. (Should be affected by glyphs to).

It should be able to be procced in and out of combat.

**Steps to reproduce the problem**:

1.  Equipp T10 4set for Resto Druid
2.  Cast Rejuvenation as many times as u can and keep doing that for about 5 minutes.
3.  Look for any fresh duration Rejuvenations that you havent hardcasted yourself

**Include proofs for this behaviour**
I can't provide with proof of it not proccing since i wasn't expecting it to not work the only time i tried it. I tested it for a whole night of Lady Deathwhisper 25 HC progress about 2 weeks ago and i never noticed a single proc in or out of combat.

**Comment by StheNoble** [comment]
works fine for me on live. Easy way is to check world of logs for current fights on dala and deuids you know have 4pc. check healing done by spell and see that you can see 2 diffrent rejuvination healing spells. while one is responsible for 1-2% total healing (4pc proc)

**Comment by TeridanDW** [comment]
Closing based on @StheNoble reply, otherwise please provide proof that there is an issue.
