### ISSUE TITLE
Fixes from PTR never get applied to live server

### ISSUE THREAD

**Issue by tripleslash** [dalaranwow/dalaran-wow#4878]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: All fixes that are marked as closed here are never actually fixed on live server

**Expected behaviour**: Fixes that are marked as closed should be applied to live server

**Steps to reproduce the problem**:

1. Submit a bug report
2. Watch Rushor close it in 1 day and mark as fixed
3. See how its not fixed on live server after 12 months

**Include proofs for this behaviour**

https://www.youtube.com/watch?v=X9F6teu_8Bw

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

You can research this on several pages like https://wowgaming.altervista.org/aowow/ or https://wowhead.com/

**Include Screenshots from the issue if necessary**

**Comment by MalkaviaDW** [comment]
Fixes are slowly being applied on live, closing this.
