### ISSUE TITLE
BUG DK PET

### ISSUE THREAD

**Issue by eccencolife111** [dalaranwow/dalaran-wow#4881]
1 bug. cast [summon gargoyle].  50% of cases when called, she runs after you for 5 seconds and only then starts to beat. And the funniest thing is that she can start to hit another target.
2 bug. cast [raise the dead]. pet revives with 20% HP==>> should be 100%

**Comment by TeridanDW** [comment]
Issue 1 is fixed here #2213
Issue 2 is fixed here #3963
