### ISSUE TITLE
[Item][Classic] Can't learn the Raptor Hide Belt Pattern

### ISSUE THREAD

**Issue by Klala** [dalaranwow/dalaran-wow#4889]
**Current behaviour**: Pattern: Raptor Hide Belt can be purchased from alliance verdors and sold in the neutral auction house for horde players, however, when I tried to learn it it gave me the "You can never use that item"

**Expected behaviour**: The Pattern: Raptor Hide Belt should work for both horde and alliance.

**Steps to reproduce the problem**:

1. Try to learn the Pattern: Raptor Hide Belt as a horde player.

http://wowwiki.wikia.com/wiki/Pattern:_Raptor_Hide_Belt

Note: This might be also the case for alliance players, I haven't checked that part yet.

**Comment by TeridanDW** [comment]
Hello @Klala 
I don't think there is an issue here. Item http://www.wowhead.com/item=13288/pattern-raptor-hide-belt can only be learned by alliance player and if you transfer to horde this recipe should change to http://www.wowhead.com/item=13287/pattern-raptor-hide-harness as stated in wowhead.

> This item will be converted to Pattern: Raptor Hide Harness if you transfer to Horde.

**Comment by Klala** [comment]
Hi @TeridanDW 
I realize the information could be misleading but if you check more comments you'll see comments like these:

**"I had no such trouble with this. I created a death knight (cheater way of doing things that require travel), headed out to Androd Fadran, nabbed the pattern along with a few other Alliance only recipes, then went off to Booty Bay. Had a friend on their horde character stationed near the auction house, so I posted it, they bought it right off. They were able to fetch the pattern from their mailbox with no change to it at all. My leather worker then received it via mail from them, and still no change. So now he has the raptor hide harness AND raptor hide belt recipes known. :)**

**See both of them on the my leather working list here: http://tinypic.com/r/2s79wnl/5"** From patch 3.3.3

**"Confirmed that Horde can have this pattern without it changing to the harness pattern. You MUST have the raptor hide harness pattern learned first before putting this pattern in your inventory or it will change to the Horde-only harness pattern."** 

I think the provided picture is more than enough proof.

**Comment by TeridanDW** [comment]
Thank you for the the reply @Klala .
Proof accepted and suggested fix is:

- remove the faction restriction from both http://www.wowhead.com/item=13288/pattern-raptor-hide-belt and http://www.wowhead.com/item=13287/pattern-raptor-hide-harness for learning them.

``` sql
UPDATE `item_template` SET `FlagsExtra` = 0 WHERE `entry` IN (13288, 13287); 
```

Result:
![image](https://user-images.githubusercontent.com/6797611/31180591-b2af1b96-a927-11e7-9330-c8efe6717caa.png)
![image](https://user-images.githubusercontent.com/6797611/31180613-bd35b94e-a927-11e7-8091-843644c3ae84.png)

**Comment by Chenocide** [comment]
#4618

**Comment by TeridanDW** [comment]
My bad, duplicate with #4618

**Comment by einzel** [comment]
Although this shows as being resolved, I receive "you can never use this item" when trying to learn Raptor Hide Harness on Dranei leatherworker.
