### ISSUE TITLE
[Instance][ICC][NPC] Flesh-Eeating Insect Reputation

### ISSUE THREAD

**Issue by Crispybuilt** [dalaranwow/dalaran-wow#4905]
- **Issue present**: On a 10 man N/HC mode Flesh-Eeating Insects currently provides 16 Reputation per kill. This shouldn't be the case since there are dozen being spawned in the "tank-room" before Putricide.
This provides an easy way to grind up your Ashen Verdict reputation and get your hands on your ring.

- **How it should work:** Flesh-Eating Insect **(ID: 37782)** should provide 2 Reputation points per kill.

- **IDs:** Flesh-Eating Insect *37782*
----------
*In total after clearing the room I've got the following results:*
- **Initial Reputation:** Friendly (3151)
- **Reputation after clearing the Putricide Room:** Honored (1573)
- **Total reputation earned just in that room**: 4422

**Comment by TeridanDW** [comment]
Hm, where do you get the information that is should be 2 reputation per kill?
Wowhead:

> 15 reputation with The Ashen Verdict (stops at Revered)

WowDB

> Kill reputation:
> +15 The Ashen Verdict

The only thing I noticed is that they should stop giving reputation once the player reach Revered (It was set on Exalted in my DB). Maybe a developer can check this.

``` sql
UPDATE `creature_onkill_reputation` SET `MaxStanding1` = 6 WHERE `creature_id` = 37782;
```

**Comment by Crispybuilt** [comment]
I forgot to include Human Racial, my bad. (15+1[10%]) Also, I'm not sure if WoWhead info is acurate enough on this one. I've checked several other online dbs and everywhere it said 15, but in some the cases said 2.
It says 2 Points for me in my DB by default, haven't even tackled with it, so I'm not 100% sure which one is true.
By the logic of such a small, meaningless NPC 15 seems quite an odd number.

I'll have to check few more things

**Comment by Rushor** [comment]
any news on this? 2 rep/kill or 15/kill ?

**Comment by Crispybuilt** [comment]
As there is insufficent evidence on this one, it will have to stay 15 for now until this is investigated thoroughly.
