### ISSUE TITLE
Druid Talent: Omen of Clarity

### ISSUE THREAD

**Issue by Kagebista** [dalaranwow/dalaran-wow#491]
Hello i noticed smt strange about talant Omen of Clarity

1st few times i get the buff but i dont get the no energy cost on my next skill

2nd i noticed that if i have the buff on me and i use FB buff is removed and FB consume all my energy 35+30

**Comment by Rushor** [comment]
https://github.com/TrinityCore/TrinityCore/issues/3088 reproduction in the last comment
