### ISSUE TITLE
Improved Devouring Plague

### ISSUE THREAD

**Issue by Aetharon** [dalaranwow/dalaran-wow#4910]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

After the recent wave of hotfixes, the shadow tree talent Improved Devouring Plague has had its damage significantly reduced. At 3/3 Improved Devouring Plague, the initial damage should be 30% of the total periodic effect. Testing with Recount provided me with the following numbers : Improved Devouring Plague 535 - normal hit, Devouring Plague 11936 - divided into 8 ticks, two of which were criticals. Every periodic tick of Devouring plague ammounted to 1173. Thus, 30% of the base 8 ticks would be 30% of 9384 or 2815.2 on a normal hit. 
This means that the current value for Improved Devouring Plague is at least five times lower than it should.

**Steps to reproduce the problem**:
1. Put the respective 3 points into the Shadow tree - Improved Devouring Plague
2. Cast on any training dummy
3. Observe the outcome, using Recount or something similar

**Include proofs for this behaviour** 
As proofs to this, I included three consecutive tests that provided roughly the same results.

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**
The IDs in question are https://wotlk.evowow.com/?spell=48300 Devouring Plague and https://wotlk.evowow.com/?spell=63627 Improved Devouring Plague 3/3

**Include Screenshots from the issue if necessary**
First Test : http://i346.photobucket.com/albums/p436/Aetharon/WoWScrnShot_101517_174530_zpsgll77yyf.jpg
Second Test : http://i346.photobucket.com/albums/p436/Aetharon/WoWScrnShot_101517_174936_zpsikidxv9q.jpg
Third Test : http://i346.photobucket.com/albums/p436/Aetharon/WoWScrnShot_101517_174831_zps9mgtbcyi.jpg

I have also included the third test directly in case the links fail to open properly:

![wowscrnshot_101517_174936](https://user-images.githubusercontent.com/29013316/31585959-050e88a0-b1d3-11e7-9b9c-7c7126409d06.jpg)

**Comment by TeridanDW** [comment]
Hello @Aetharon, thank you for the report.
I did few fast tests on ptr and it seems the basic formula for the damage is correct as i get this:
![image](https://user-images.githubusercontent.com/6797611/31586276-5de5185a-b1d7-11e7-9e3e-d3b922acd1a7.png)

which is exacly 30% of the spell. The exact values are:
 - initial damage (at rank 3) = 472
 - 8 x 197 = 1576

**Comment by TeridanDW** [comment]
It seems the initial damage (provided by spell https://wowgaming.altervista.org/aowow/?spell=63627 rank 1, 2, 3) ignores the caster's spell power, which should not be happening.
Check in initial damage from the screenshot above and this one:
![image](https://user-images.githubusercontent.com/6797611/31586895-73e3977c-b1e0-11e7-9ee1-b194fdb31537.png)

**Comment by robinsch** [comment]
Waiting for PTR Update.

**Comment by TeridanDW** [comment]
Works as intended on PTR.

![wowscrnshot_101617_111156](https://user-images.githubusercontent.com/6797611/31601573-fbcf7ade-b262-11e7-8687-11b53135529a.jpg)

Damage values:

initial damage (at rank 3) = 876
8 x 365 = 2920
