### ISSUE TITLE
[NPC] Amberpelt Clefthoof and Lighning Wasp

### ISSUE THREAD

**Issue by Hephaetorix** [dalaranwow/dalaran-wow#4911]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: The NPCs [Amberpine Clefthoof](http://www.wowhead.com/npc=22287/amberpelt-clefthoof) and [Lightning Wasp](http://www.wowhead.com/npc=22182/lightning-wasp) appear at Bash'ir Landing in Blade's Edge Mountains.

**Expected behaviour**: These NPCs were removed from the game in patch 2.1, and should not spawn.

**Steps to reproduce the problem**:

1. Fly to Bash'ir Landing
2. Observe mobs
3. 

**Include proofs for this behaviour**

Wowhead comments on the removal:
http://www.wowhead.com/npc=22287/amberpelt-clefthoof#comments:id=112619
http://www.wowhead.com/npc=22182/lightning-wasp#comments:id=264097

Note that #4006 fixes a similar issue with 2.1 removed mobs.

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

Amberpelt Clefthoof: [22287](http://www.wowhead.com/npc=22287/amberpelt-clefthoof)
Lightning Wasp: [22182](http://www.wowhead.com/npc=22182/lightning-wasp)

**Include Screenshots from the issue if necessary**

![image](https://user-images.githubusercontent.com/27331687/31591524-8125d91e-b1ee-11e7-841c-c4dd97dd6610.png)

**Comment by TeridanDW** [comment]
Hello and thank you for the report @Hephaetorix.
I can confirm they should not exist in-game anymore.

**Comment by TeridanDW** [comment]
**Suggested fix:**

``` sql
DELETE FROM `creature` WHERE `id` IN (22287, 22182);
DELETE FROM `creature_addon` WHERE `guid` IN (SELECT `guid` FROM `creature` WHERE `id` IN (22187, 22182));
```

**Comment by TeridanDW** [comment]
Works as intended on PTR.

**Comment by Hephaetorix** [comment]
NPCs still spawn on live

![image](https://user-images.githubusercontent.com/27331687/35260072-5e3d1ebc-ffd7-11e7-883b-65f6b617d38d.png)

**Comment by Lothloryen** [comment]
Thank you for the report, it has been updated already.
