### ISSUE TITLE
Warlock pets

### ISSUE THREAD

**Issue by zyklonb** [dalaranwow/dalaran-wow#4916]
If you currently have no pet active and you summon a pet it starts with 15% hp, it should have 100%.

If you already have i.e an imp active and u summon a new imp, the new one have 100% as it should, however if u have a felhunter and u want to summon an imp the imp now has 15% hp and vice versa.

https://youtu.be/vZA0MPMfWkc

**Comment by TeridanDW** [comment]
Hello and thank you for the report @zyklonb, this issue should be already handled in #3963.
If the problem persists after #3963 is applied on live realm this report will be reopened.

**Comment by robinsch** [comment]
Waiting for PTR update.

**Comment by tripleslash** [comment]
Same with DK pets

**Comment by TeridanDW** [comment]
Hello, at @Lothloryen is the label correct here?

**Comment by robinsch** [comment]
Yeah I think it was pushed as a hotfix

**Comment by Lothloryen** [comment]
Hello there,

Yes, this is already on live - it should affect all pets. If there is still an issue with their health let us know, please.
