### ISSUE TITLE
[Quest][Classic] Revenge of Gann

### ISSUE THREAD

**Issue by Imbarawr** [dalaranwow/dalaran-wow#4924]
Same issue that has already been mentioned [here.](https://github.com/dalaranwow/dalaran-wow/issues/634) The respawn time of the Bael Modan Flying Machine is very long and this results in long wait time if you quest in a group.

**Comment by TeridanDW** [comment]
Hello and thank you for the report @Imbarawr, however like you pointed the issue is already handled in #634. There is no need to create new report.

**Comment by Imbarawr** [comment]
It was also said in 634 that the respawn timer was altered to 60 seconds. This is not the case at the moment, the respawn timer seems to be at 15 minutes again.

**Comment by TeridanDW** [comment]
That's correct, because it's not on live realm yet. You can check the label of each report (top right) and when you see "Fixed - On Live Realm" then you can test it yourself.

**Comment by Imbarawr** [comment]
Aah, now I understand. Thank you very much for explaining!
