### ISSUE TITLE
Quest item for "Containing the Rot" bugged

### ISSUE THREAD

**Issue by kaciko** [dalaranwow/dalaran-wow#4925]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

I've been farming  "Rot Resistant Organ" for the quest "Containing the Rot" for a few good days already. I killed over 150 mobs, yet it didn't drop...

In this reference it says it is a %3 drop rate, which takes 33-34 creeps for a %100 chance.

Here is the link of the item: http://www.wowhead.com/item=36800
Here is the link to the quest: http://www.wowhead.com/quest=12100

**Comment by Imbarawr** [comment]
That is not the way percentage works. I would recommend you to [read this](http://wowwiki.wikia.com/wiki/Drop_rate) about how drop rates works.

**Comment by kaciko** [comment]
I think i know very well how percentages work, i have been killing these mobs for a very long time now and still no drop. This issue has been mentioned in the past and its clearly a bug.

**Comment by alexuktc** [comment]
The drop rate is indeed lower than it has to be. However when it comes to statistics 33 kills do not guarantee a drop. Each kill has its own 3% chance which does not accumulate. 

I personally killed over 400 mobs on my character to get the quest item. I do not think this is normal.

**Comment by TeridanDW** [comment]
Hello thank you for the report and the comments to everyone, however I don't see a bug (or something that needs adjusting here). Yes the drop rate of this item is indeed low but that's  also confirmed by wowhead. Unless someone provide any relevent information for an issue here I will close this report.

Note: Elks have 2% drop chance and the Bears have 4%, if that helps you get the quest done faster.
