### ISSUE TITLE
Distract not working properly

### ISSUE THREAD

**Issue by Desecrator** [dalaranwow/dalaran-wow#4928]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: After last fixes, the Distract ability of Rogue got bugged. Every time i use it, instead of facing the point, they face directly towards me and charge to attack.

**Expected behaviour**: It should make mobs face the direction of the Distract point of impact

**Steps to reproduce the problem**:

1. Go in stealth
2. Trow Distract at any mob, best to be aggressive mob
3. Mobs charge you, instead of turing away to the point of impact of Distract

**Include proofs for this behaviour**

http://www.wowhead.com/spell=1725/distract

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

http://www.wowhead.com/spell=1725/distract

**Include Screenshots from the issue if necessary**

i can't make a photo atm, but you can try it with any rogue and you will see.

**Comment by TeridanDW** [comment]
Hello and thank you for the report @Desecrator.
After few tests on PTR I wasn't able to reproduce this issue. The creature always did what it should:
![image](https://user-images.githubusercontent.com/6797611/31854013-2e1e43da-b69b-11e7-9d75-3120e5b54d84.png)

It will be great if you could tell me where exacly did you saw this issue @Desecrator and what was your level and the level of the creature, thanks.
If this issue can be reproduced I will reopen the report, for now closing.

**Comment by Desecrator** [comment]
Please don't try on PTR try it no live server Algalon. Even mobs 3-4 levels under me are facing me instead of the point of impact of Distract. Can confirm bug is till there
