### ISSUE TITLE
Quest: Trail of Fire

### ISSUE THREAD

**Issue by Crispybuilt** [dalaranwow/dalaran-wow#493]
**Quest Trail of Fire** - *11241*
**NPC** - *Apothecary Hanes =Royal Apothecary Society=* *(ID: 23784)

- **Issue:** The quest event doesn't want to start to escort the NPC.

- **Video of how it should work:** http://www.youtube.com/watch?v=WKhpw0T0aUo

__________________

http://wotlk.openwow.com/quest=11241
http://www.wowhead.com/quest=11241/trail-of-fire
http://www.wowwiki.com/Quest:Trail_of_Fire

**Comment by rAtllerAt** [comment]
As of 6th of April, 2015 this is still a problem

**Comment by Lothloryen** [comment]
Hello there,

This quest was already deployed.
