### ISSUE TITLE
[Mobs] Bristleback Geomancer

### ISSUE THREAD

**Issue by Imbarawr** [dalaranwow/dalaran-wow#4930]
**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
When interupting Bristleback Geomancer in Agama'gor, just north of Camp Taurajo in The Barrens, they stand at range waiting for the interuption CD to go away and then continues to cast spells. They do not move in melee range. We used Wind Shear as interupt.

**Expected behaviour**: Tell us what should happen instead
When interupted the Bristleback Geomancer should move into melee range.

**Steps to reproduce the problem**:

1.  Go to Agama'gor in The Barrens, just north of Camp Taurajo
2.  Aggro a Bristleback Geomancer and interupt him while he's casting
3.  Observe as Bristleback Geomancer continous to stay at range and not move into melee.

**Include proofs for this behaviour**
N/A

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**
N/A

**Include Screenshots from the issue if necessary**
N/A

**Comment by TeridanDW** [comment]
Hello, this creature shares the same issue as #4929, please comment there. There is no need to open separate report of each npc that has this problem.

Note: Please use https://wowgaming.altervista.org/aowow/ and provide the needed ids for each creature, spell, gameobject, quest, item in future reports. Thank you.
