### ISSUE TITLE
Skadi in Utgarde Pinnacle can't be downed by harpoons

### ISSUE THREAD

**Issue by sebastienwood** [dalaranwow/dalaran-wow#4932]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: 
The encounter with Skadi on Utgarde Pinnacle in normal difficulty can't be completed (on Kirin Tor realm). He never gets in the position to be targeted by the harpoons. 

**Expected behaviour**: Tell us what should happen instead
The encounter should be scripted so that Skadi could be downed with the harpoons in the phase 1 of the fight.

**Steps to reproduce the problem**:

1. Go to Utgarde Pinnacle in normal difficulty (couldn't yet confirm this bug on heroic difficulty)
2. Launch the fight with Skadi (3rd boss of the instance)
3. Try to do something with the harpoons

**Include proofs for this behaviour**

Record from retail back in 2008:
https://www.youtube.com/watch?v=Y0wDGhrLRi0

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

Skadi : http://www.wowhead.com/npc=26693/skadi-the-ruthless (ID : 26693)
Utgarde Pinnacle : http://www.wowhead.com/utgarde-pinnacle (couldn't find an ID for an instance :/)

Edit : removed Kirin Tor tag as it seems to scare people

**Comment by SirSlacksALot** [comment]
**Current behaviour**:
This issue also exists in heroic mode (Kirin Tor):  Skadi never flies in front of the harpoons and the group never receive the alert 'Skadi is within range of the harpoon launchers'. 

Due to this issue, U.P. cannot be (and to my knowledge, has never been) completed. If a group is assigned this dungeon as a random, all members must camp out in order to avoid the deserter debuff.

**Comment by TeridanDW** [comment]
Hello, this is outdated report. When Kirin Tor is updated this issue should be solved.
