### ISSUE TITLE
[Mobs] Burning Blade Apprentice

### ISSUE THREAD

**Issue by Imbarawr** [dalaranwow/dalaran-wow#4934]
Current behaviour: Tell us what happens in detail (Where, When, What, Why, Who)
When interupting Burning Blade Apprentice in Thunder Ridge, Durotars, they stand at range waiting for the interuption CD to go away and then continues to cast spells. They do not move in melee range. We used Wind Shear as interupt.

Expected behaviour: Tell us what should happen instead
When interupted the Burning Blade Apprentice should move into melee range.

Steps to reproduce the problem:

1. Go to Thunder Ridge in Durotar, at [Fizzle Darkstorm](http://db.vanillagaming.org/?npc=3203)
2. Aggro a Burning Blade Apprentice and interupt him while he's casting
3. Observe as Burning Blade Apprentice continous to stay at range and not move into melee.

Include proofs for this behaviour
N/A

Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills
N/A

Include Screenshots from the issue if necessary
N/A

**Comment by TeridanDW** [comment]
Hello, this creature shares the same issue as #4929, please comment there. There is no need to open separate report of each npc that has this problem.

Note: Please use https://wowgaming.altervista.org/aowow/ and provide the needed ids for each creature, spell, gameobject, quest, item in future reports. Thank you.

**Comment by Imbarawr** [comment]
@TeridanDW I understand. Just to be clear, if I run into more of these issues I'll comment in the same format as you've done in 4929? No need for separate reports?

**Comment by TeridanDW** [comment]
That's right.
