### ISSUE TITLE
Achievement: Respect Your Elders

### ISSUE THREAD

**Issue by Revennaras** [dalaranwow/dalaran-wow#494]
_Defeat Elder Nadox in Ahn'kahet on Heroic Difficulty without killing any Ahn'kahar Guardians._
- **Issue here:** cannot be obtained properly because Ahn'kahar Guardian have infinite Immortal Aura (Immune to Damage) & he also doesn't spawn where is he supposed to spawn (original Nadox spawn point). Issue is that he spawns where current boss location is which makes this achievement impossible to obtain. Also take note that you have to add the global messege when Guardian Spawns - **An Ahn'kahar Guardian hatches!**
- **How it should work**: Ahn'kahar Guardian has to spawn on the starting location of the boss and the boss has to be nuked down before the add reaches him so the boss cannot be affected by Immortal Aura. **(Guardian Aura - 56153)**. The range of  it has to be 80 yards and not unlimited.

**NPC Included:** 
_5 Man Normal_
**Ahn'kahar Guardian** - 30176

_5 Man Heroic_
**Ahn'kahar Guardian** - 31441

They also have ability called **Sprint** _(ID:56354)_
How it should work: A proper video guideline can be shown here: http://www.youtube.com/watch?v=bqiUKHRlOyQ

---

http://www.wowhead.com/spell=56153
http://wotlk.openwow.com/spell=56354
http://wotlk.openwow.com/npc=30176
http://wotlk.openwow.com/npc=31441
http://wotlk.openwow.com/achievement=2038
http://www.wowhead.com/achievement=2038/respect-your-elders

**Comment by Rushor** [comment]
This was completely reworked in https://github.com/TrinityCore/TrinityCore/commit/297e63da362adaaec13617c253194726c47f60e2 and already works fine on PTR.

The fix for it will be applied on the live realm with further changelogs.

**Comment by TeridanDW** [comment]
Hello, few more improvements can be done on this fight.
 - the adds should spawn from the eggs around the room, not under the boss ever.
 - when adds spawn they should jump forward (depending on their summoning angle) then take a target and engage
 - on spawn the guardian should send general message not emote.
 - eggs should despawn(when adds spawn from them) and spawn during the fight (very short respawn timer)

This:
> Ahn'kahar Guardian has to spawn on the starting location of the boss and the boss

is incorrect.

This:

> The range of it has to be 80 yards and not unlimited.

is working on PTR.

Reference from retail for this issue:
https://www.youtube.com/watch?v=4oP4KQRY-gc&feature=youtu.be
https://www.youtube.com/watch?v=8-tk0kAXyu4
