### ISSUE TITLE
Can't enter Trial of the Champion

### ISSUE THREAD

**Issue by sebastienwood** [dalaranwow/dalaran-wow#4940]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
On the Kirin Tor server the 5 man dungeon Trial of the Champion is locked, either in normal or heroic mode. Shouldn't happen on Kirin Tor server where no progression feature is available.
It is written "You are already locked to this instance", but actually no one can do it as fresh 80.

**Expected behaviour**: Tell us what should happen instead
Entering the instance should be feasible as long as you have attained level 80, like all others dungeons/raids.

**Steps to reproduce the problem**:

1. Try to tag or enter Trial of the Champion

**Include proofs for this behaviour**

Any guide written for retail fresh level 80 take into account that Trial of the Champion is doable (i. e. : https://www.engadget.com/2010/05/19/the-light-and-how-to-swing-it-gearing-a-new-level-80-tankadin/)

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

MapID is 542.

Edit : removed the Kirin Tor tag on title because it seems to scare people

**Comment by Karkazz** [comment]
Confirmed

**Comment by TeridanDW** [comment]
Hello, this is outdated report. When Kirin Tor is updated this issue should be solved.
