### ISSUE TITLE
[Mechanic] Additional Global Cooldowns

### ISSUE THREAD

**Issue by datbunneh** [dalaranwow/dalaran-wow#4942]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: After some of the recent updates we occasionally get some "additional" global cooldowns that prevent us from casting.

**Expected behaviour**: No additional global cooldowns should appear.

**Steps to reproduce the problem**:

1. Non-stop cast some instant spells on a dummy.

**Include proofs for this behaviour**

Proof not needed here I believe.

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

It's a generic issue.

**Include Screenshots from the issue if necessary**

Here is a video instead. The bug can be witnessed in the middle and at the end of the video:
https://www.youtube.com/watch?v=E0-kEhKTeI0

**Comment by TeridanDW** [comment]
Hello, I've also noticed this on PTR, but i though it was result ot .cheat cast command. Guess it wasn't.

**Comment by Lothloryen** [comment]
@datbunneh Thank you for your report, is this only happening since this morning?

**Comment by Lothloryen** [comment]
Hello again, found what was causing it, it will be fine again within the next maintenance. Thank you.

**Comment by datbunneh** [comment]
Yes, I believe this one only appeared today. Thanks, for quick reponse.

**Comment by ashido96** [comment]
Oh this was an actual bug? I thought it was just some latency bull shit. It's been around for well over a year at this point (all the ret paladin melee spells). Thanks for the fix.

**Comment by datbunneh** [comment]
@ashido96 No, this issue was fixed the same exact day it appeared.
