### ISSUE TITLE
[NPC] Bloodscalp Witch Doctor does not perform attacks

### ISSUE THREAD

**Issue by Imbarawr** [dalaranwow/dalaran-wow#4943]
**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
When engaging Bloodscalp Witch Doctor: https://wowgaming.altervista.org/aowow/?npc=660 in Stranglethorn Vale he does not perform any attacks. He uses his abilities(earthgrab totem and enrage) just fine. 
If the player walks up to the NPC they will attack with their weapon but they do not move towards the player.

**Expected behaviour**: Tell us what should happen instead
When engaging Bloodscalp Witch Doctor: https://wowgaming.altervista.org/aowow/?npc=660 in Stranglethorn Vale they should move towards and attack the player.

**Steps to reproduce the problem**:

1. Go to Zuuldaia Ruins in Stranglethorn Vale 
2.  Find Bloodscalp Witch Doctor and engage
3. Observe as Bloodscalp Witch Doctor does not perform attacks

**Include proofs for this behaviour**
N/A

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**
Bloodscalp Witch Doctor: https://wowgaming.altervista.org/aowow/?npc=660

**Include Screenshots from the issue if necessary**
N/A

**Comment by Imbarawr** [comment]
Same issue can be observed on Venture co. Strip Miner - https://wowgaming.altervista.org/aowow/?npc=674

When on range the NPC casts his Dynamite and then just stands there doing nothing. If you step into melee range he will attack. If you step out again he stands still and does not perform any attacks.

**Comment by TeridanDW** [comment]
Thank you for the report @Imbarawr.
These creatures indeed share the same problem (wrong CMC flag on their spell).

Suggested fix:
``` sql
-- Bloodscalp Witch Doctor SAI
SET @ENTRY := 660;
UPDATE `creature_template` SET `AIName`="SmartAI" WHERE `entry`=@ENTRY;
DELETE FROM `smart_scripts` WHERE `entryorguid`=@ENTRY AND `source_type`=0;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(@ENTRY,0,0,0,0,0,100,0,2000,3000,10000,11000,11,8376,0,0,0,0,0,1,0,0,0,0,0,0,0,"Bloodscalp Witch Doctor - In Combat - Cast 'Earthgrab Totem'"),
(@ENTRY,0,1,0,2,0,100,513,0,30,0,0,11,8599,2,0,0,0,0,1,0,0,0,0,0,0,0,"Bloodscalp Witch Doctor - Between 0-30% Health - Cast 'Enrage' (No Repeat)");

-- Venture Co. Strip Miner SAI
SET @ENTRY := 674;
UPDATE `creature_template` SET `AIName`="SmartAI" WHERE `entry`=@ENTRY;
DELETE FROM `smart_scripts` WHERE `entryorguid`=@ENTRY AND `source_type`=0;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(@ENTRY,0,0,0,0,0,100,0,2000,6000,12000,15000,11,7978,0,0,0,0,0,2,0,0,0,0,0,0,0,"Venture Co. Strip Miner - In Combat - Cast 'Throw Dynamite'");
```

**Comment by Imbarawr** [comment]
Was in the middle of updating when you posted but I make another comment in case an update gets missed.

Something similar is also affecting Zanzil Witch Doctor: https://wowgaming.altervista.org/aowow/?npc=1490 making them behave strange. They're casting Shadow Bolts when on range but they are not casting it on CD. If you run into melee range they will however start melee damage and if they run out of mana they will run to the player and perform melee attacks.

**Comment by Imbarawr** [comment]
Missclick, nevermind me.

**Comment by TeridanDW** [comment]
Works as intended on PTR.
