### ISSUE TITLE
Battle for the Undercity

### ISSUE THREAD

**Issue by hulleri12** [dalaranwow/dalaran-wow#4946]
There is currently a bug when completing battle for the undercity. When doing the quest chain I got to Vol'jin outside Undercity and accepted the quest. I waited around for about 3-5 minutes and asked in global chat if the quest was bugged. Turns out it is not bugged and I simply removed the quest for no reason. After that I hearthed out to Dalaran however, my Orgrimmar and Undercity are still locked in for the Battle for the Undercity. At this time I cannot use the ah, trainers, or any vendors in either city. Yet I do not have the quest in my questlog and I have looked around to pick up the quest again and cannot get it back.

**Comment by TeridanDW** [comment]
Hello and thank you for the report @hulleri12.
This issue should be solved soon on live.
