### ISSUE TITLE
[Quest] Speaking with Nezzliok

### ISSUE THREAD

**Issue by Imbarawr** [dalaranwow/dalaran-wow#4947]
**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
When doing the quest Speaking with Nezzliok: http://www.wowhead.com/quest=585/speaking-with-nezzliok you're supposed to loot three skulls from three gameobjects.
http://www.wowhead.com/object=2892/ziatajai-trophy-skulls
http://www.wowhead.com/object=2891/baliamah-trophy-skulls
http://www.wowhead.com/object=2893/zulmamwe-trophy-skulls

The respawn timer of these gameobjects is very long(upwards to 10 minutes) resulting in strange waiting time when questing in group.

**Expected behaviour**: Tell us what should happen instead
Reduce the spawning time of the gameobject to reduce waiting time when questing in group.

**Steps to reproduce the problem**:

1. Acquire quest Speaking with Nezzliok: http://www.wowhead.com/quest=585/speaking-with-nezzliok
2. Loot any of the three gameobjects containing the skulls.
3. Wait for it to respawn.

**Include proofs for this behaviour**
N/A

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**
Quest: Speaking with Nezzliok: http://www.wowhead.com/quest=585/speaking-with-nezzliok

Gameobjects:
http://www.wowhead.com/object=2892/ziatajai-trophy-skulls
http://www.wowhead.com/object=2891/baliamah-trophy-skulls
http://www.wowhead.com/object=2893/zulmamwe-trophy-skulls

**Include Screenshots from the issue if necessary**
N/A

**Comment by TeridanDW** [comment]
Hello and thank you for the report @Imbarawr.
In my DB they have 15 mins respawn timer. I couldn't find any information for their respawn time, but 15 mins seems high indeed. My suggestion is 5 mins for each:
``` sql
UPDATE `gameobject` SET `spawntimesecs` = 300 WHERE `id` BETWEEN 2891 AND 2893; 
```

**Comment by Imbarawr** [comment]
I tried to find information on the subject aswell and the only thing I could find was youtube videos of people doing the quest. Those videos are however significantly newer than WOTLK. In the videos the object does not despawn at all after being looted which would suggest a shorter period than 5 minutes. I do not know if this was the case in WOTLK.

https://youtu.be/-gd_tynH2ww?t=1m20s

**Comment by TeridanDW** [comment]
Works as intended on PTR.
