### ISSUE TITLE
[NPC] King Bangalash summoned panthers do not attack

### ISSUE THREAD

**Issue by Imbarawr** [dalaranwow/dalaran-wow#4950]
**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
When fighting King Bangalash: https://wowgaming.altervista.org/aowow/?npc=731 he summons two panthers to fight for him. At the moment the two summoned panthers does not perform any attacks.

**Expected behaviour**: Tell us what should happen instead
The summoned panthers should attack the player.

**Steps to reproduce the problem**:

1. Go to King Bangalash in Stranglethorn Vale
2. Aggro King Bangalash
3. Wait for him to spawn panthers and observe as they do not perform any attacks.

**Include proofs for this behaviour**
N/A

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**
King Bangalash: https://wowgaming.altervista.org/aowow/?npc=731

**Include Screenshots from the issue if necessary**
N/A

**Comment by TeridanDW** [comment]
Thank you for the report @Imbarawr.
The issue here is that the npcs summoned by spell https://wowgaming.altervista.org/aowow/?spell=8816 are considered guardians of King Bangalash and can't be scripted with SAI (atlest doesn't seems to work for me).
Issues:
 - Once they are summoned if the player doesn't move or aggro them in any way they don't act at all.
 - They should despawn if King Bangalash resets, because he will cast his spell 1 more time and they will become 4.

**Comment by TeridanDW** [comment]
**Suggested fix:** (a bit hacky)
``` sql
-- Jungle Panther SAI
SET @ENTRY := 31636;
UPDATE `creature_template` SET `AIName`="SmartAI" WHERE `entry`=@ENTRY;
DELETE FROM `smart_scripts` WHERE `entryorguid`=@ENTRY AND `source_type`=0;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(@ENTRY,0,0,0,1,0,100,0,0,0,1000,1000,49,0,0,0,0,0,0,25,10,0,0,0,0,0,0,"Jungle Panther - Out of Combat - Start Attacking"),
(@ENTRY,0,1,0,1,0,100,0,10000,10000,10000,10000,41,0,0,0,0,0,0,1,0,0,0,0,0,0,0,"Jungle Panther - Out of Combat - Despawn Instant");
```

**Comment by TeridanDW** [comment]
Works as intended on PTR.
