### ISSUE TITLE
[NPC] Zanzil Witch Doctor not performing attacks on CD

### ISSUE THREAD

**Issue by Imbarawr** [dalaranwow/dalaran-wow#4951]
**Current behavior**: Tell us what happens in detail (Where, When, What, Why, Who)
Zanzil Witch Doctor: https://wowgaming.altervista.org/aowow/?npc=1490 
They're casting Shadow Bolts when on range but they are not casting it on CD resulting in a strange behavior where there is significant downtown in their rotation. If you run into melee range they will however start melee attacks and if they run out of mana they will run to the player and perform melee attacks.

**Expected behaviour**: Tell us what should happen instead
Run towards the player and perform auto attacks and Shadow Bolts or stand on range and cast Shadow Bolts more frequently than what they are doing now.

**Steps to reproduce the problem**:

1. Go to Ruins of Aboraz in Stranglethorn Vale
2. Aggro a Zanzil Witch Doctor while on range
3. Observe their behavior

**Include proofs for this behaviour**
N/A

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**
Zanzil Witch Doctor: https://wowgaming.altervista.org/aowow/?npc=1490

**Include Screenshots from the issue if necessary**
N/A

**Comment by TeridanDW** [comment]
Thank you for the report @Imbarawr.
The issue is caused by having CMC flag on his spell and longer than 3 secs cooldown.
Also this creature is missing 1 combat spell.

How it looks now:

![image](https://user-images.githubusercontent.com/6797611/31943291-f5c9eeca-b8d0-11e7-83e3-937f0258fade.png)


**Suggested fix:**
``` sql
-- Zanzil Witch Doctor SAI
SET @ENTRY := 1490;
UPDATE `creature_template` SET `AIName`="SmartAI" WHERE `entry`=@ENTRY;
DELETE FROM `smart_scripts` WHERE `entryorguid`=@ENTRY AND `source_type`=0;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(@ENTRY,0,0,0,0,0,100,0,1000,1000,0,0,11,9613,64,0,0,0,0,2,0,0,0,0,0,0,0,"Zanzil Witch Doctor - In Combat - Cast 'Shadow Bolt'"),
(@ENTRY,0,1,0,0,0,100,0,0,0,10000,11000,11,15038,0,0,0,0,0,1,0,0,0,0,0,0,0,"Zanzil Witch Doctor - In Combat - Cast 'Scorching Totem'");
```

**Comment by TeridanDW** [comment]
Works as intended on PTR.
