### ISSUE TITLE
[Quest] Mok'thardin's Enchantment - Gameobject respawn timer

### ISSUE THREAD

**Issue by Imbarawr** [dalaranwow/dalaran-wow#4952]
**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
The quest Mok'thardin's Enchantment: https://wowgaming.altervista.org/aowow/?quest=573 takes you to Nek'mani Wellspring where you should take some Holy Spring Water from the spring at the top. Once looted the gameobject despawns. This results in other players being forced to wait to loot the Holy Spring Water. Current respawn time seems to be the standard 15 minutes.

**Expected behaviour**: Tell us what should happen instead
Since it is a spring where water flows continually players should not have to wait for the gameobject to respawn. 

**Steps to reproduce the problem**:

1. Acquire quest Mok'thardin's Enchantment: https://wowgaming.altervista.org/aowow/?quest=573
2. Go to Nek'mani Wellspring
3. Loot the Holy Spring Water and wait for the gameobject to respawn

**Include proofs for this behaviour**
N/A

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**
Mok'thardin's Enchantment: https://wowgaming.altervista.org/aowow/?quest=573
Holy Spring Water: https://wowgaming.altervista.org/aowow/?item=737
The Holy Spring: https://wowgaming.altervista.org/aowow/?object=759

**Include Screenshots from the issue if necessary**
N/A

**Comment by TeridanDW** [comment]
Thank you for the report @Imbarawr.
The respawn timer is indeed long and none of the comments in wowhead even mentioned someone waiting for it. Also in my DB it is set at 2 seconds.

**Suggested fix:**
``` sql
UPDATE `gameobject` SET `spawntimesecs` = 2 WHERE `guid` = 10121; 
```

**Comment by TeridanDW** [comment]
Works as intended on PTR.
