### ISSUE TITLE
[Mage] Missile Barrage Is Consumed At The End Of Channeling Arcane Missiles

### ISSUE THREAD

**Issue by datbunneh** [dalaranwow/dalaran-wow#4955]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Missile Barrage is consumed at the end of channeling Arcane Missiles.

This issue is mentioned in comment to ticket #2186 but seems to be not taken care of.

**Expected behaviour**: Missile Barrage is consumed at the start of channeling Arcane Missiles.

**Steps to reproduce the problem**:

1. Cast Arcane Blast until you get Missile Barrage talent proc.
2. Start casting Arcane Missiles.
3. Notice that Missile Barrage buff disappears only after you finish channeling Arcane Missiles.

**Include proofs for this behaviour**

This guide seems to be done on retail:
https://www.youtube.com/watch?v=eLe1GacBNsk&t=504

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

Arcane Blast - 42897
Arcane Missiles - 42846
Missile Barrage - 54490

**Include Screenshots from the issue if necessary**

https://www.youtube.com/watch?v=72bBuweHlT4

**Comment by TeridanDW** [comment]
Thank you @datbunneh, this one is missing there. Will add it in the original report.

**Comment by datbunneh** [comment]
@Lothloryen This one is mentioned in changelog although it was NOT fixed yet on live server.

**Comment by Lothloryen** [comment]
@datbunneh You are totally right, my mistake. It is removed already. This is still being working on.

Thank you for the heads up.

**Comment by robinsch** [comment]
Ref: https://github.com/dalaranwow/principal/commit/228db68f84716f6050f933c3b2bf31185c21d259
