### ISSUE TITLE
[Mage] Hot Streak Is Consumed On Pyroblast Hit/Miss

### ISSUE THREAD

**Issue by datbunneh** [dalaranwow/dalaran-wow#4956]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Hot Streak is consumed on Pyroblast hit/miss.

This issue is mentioned in ticket #2186 but seems to be not taken care of. @TeridanDW seems to be unable to reproduce it.

**Expected behaviour**: Hot Streak is consumed on Pyroblast cast.

**Steps to reproduce the problem**:

1. Cast Fireball or Frostfire Bolt until you get Hot Streak talent proc.
2. Cast Pyroblast.
3. Notice that Hot Streak buff disappears only after your Pyroblast hits/misses the target.

**Include proofs for this behaviour**

This guide seems to be done on retail:
https://www.youtube.com/watch?v=Jh3m394Sbm4&t=454

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

Fireball - 42833
Frostfire Bolt - 47610
Pyroblast - 11366
Hot Streak - 44448

**Include Screenshots from the issue if necessary**

https://www.youtube.com/watch?v=o-ATLQb86W8

**Comment by TeridanDW** [comment]
Yes, thank you @datbunneh, the "Hot Streak" buff shares the same issue like the other buffs mentioned there. Also the other report is still open that's why issue is still present in-game. If you want you can copy this information to the other report but it's already known.
