### ISSUE TITLE
[NPC] Southsea Freeboter does not attack

### ISSUE THREAD

**Issue by Imbarawr** [dalaranwow/dalaran-wow#4957]
**Current behaviour**:
When you aggro a Southsea Freebooter: https://wowgaming.altervista.org/aowow/?npc=7856 in Lost Rigger Cove, Tanaris, at range they don't start attacking you unless you run into melee distance. Once engaged in melee the NPC will then attack you and follow you.

**Expected behaviour**:
Should run towards the player and start attacking him.

**Steps to reproduce the problem**:

1. Go to Lost Rigger Cove in Tanaris
2. Aggro a Southsea Freeboter while at range
3. Observe as Southsea Freeboter doesn't perform any attacks.

**Include proofs for this behaviour**
N/A

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**
Southsea Freeboter: https://wowgaming.altervista.org/aowow/?npc=7856

**Include Screenshots from the issue if necessary**
N/A

**Comment by TeridanDW** [comment]
Hello and thank you for the report @Imbarawr.
Issue confirmed on PTR.

How it looks now:
![image](https://user-images.githubusercontent.com/6797611/32016378-76614d98-b9cc-11e7-9319-4c52e02cacf5.png)

**Suggested fix:**
``` sql
-- Southsea Freebooter SAI
SET @ENTRY := 7856;
UPDATE `creature_template` SET `AIName`="SmartAI" WHERE `entry`=@ENTRY;
DELETE FROM `smart_scripts` WHERE `entryorguid`=@ENTRY AND `source_type`=0;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(@ENTRY,0,0,0,0,0,100,0,0,0,2000,2200,11,6660,64,0,0,0,0,2,0,0,0,0,0,0,0,"Southsea Freebooter - In Combat - Cast 'Shoot'"),
(@ENTRY,0,1,0,2,0,100,1,0,15,0,0,25,1,0,0,0,0,0,1,0,0,0,0,0,0,0,"Southsea Freebooter - Between 0-15% Health - Flee For Assist (No Repeat)");
```

**Comment by TeridanDW** [comment]
On PTR:
-- Southsea Freebooter SAI
still doesn't use his range spell, is it possible that he miss equipment so he just stays. If so this is what he should have:

``` sql
DELETE FROM `creature_equip_template` WHERE `CreatureID`= 7856;
INSERT INTO `creature_equip_template` (`CreatureID`, `ID`, `ItemID1`, `ItemID2`, `ItemID3`, `VerifiedBuild`) VALUES
(7856,1,1897,0,2552,18019);
```

**Comment by TeridanDW** [comment]
-- Southsea Freebooter SAI
doesn't want to use his range spell (shoot) and still has the original issue pointed above. SAI is correct equip table is correct and it works properly on my local server. I don't know why it doesn't on PTR.

**Comment by Rushor** [comment]
need to cast the spell triggered then it will work

**Comment by TeridanDW** [comment]
Works as intended on PTR.
