### ISSUE TITLE
[Spell] Fire Nova (shaman)

### ISSUE THREAD

**Issue by balazskvr** [dalaranwow/dalaran-wow#4958]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**:
Fire Nova is treated as a spell cast by the totem (which is correctly considered as the shaman's pet).

**Expected behaviour**:
The caster should be the shaman, so any damage caused should count as the shaman's damage and the combat log should also state that the shaman is the one that deals the damage. (this also applies to threat ofc)

**Steps to reproduce the problem**:

1. Drop a fire totem
2. Cast Fire nova (cause damage)
3. Check combat log

**Include proofs for this behaviour**

https://www.youtube.com/watch?v=xOAVlW9Qwns&t=
https://www.youtube.com/watch?v=gPho09nW5tE&t=

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

Spell ID (rank1): 1535 (https://wowgaming.altervista.org/aowow/?spell=1535)

**Include Screenshots from the issue if necessary**

--

**Note**

https://github.com/TrinityCore/TrinityCore/blob/3.3.5/src/server/scripts/Spells/spell_shaman.cpp#L571-L627

**Comment by robinsch** [comment]
@TeridanDW Can you confirm that it still checks for totem -> player line of sight?

**Comment by robinsch** [comment]
Added missing ranks.

**Comment by TeridanDW** [comment]
@robinsch the second part of your fix:

> Added missing ranks.

is not on ptr or not working (tested with rank 9)

**Comment by balazskvr** [comment]
Here are some additional info:
https://github.com/TrinityCore/TrinityCore/pull/18292

**Comment by Lothloryen** [comment]
Try it now, please.

**Comment by robinsch** [comment]
@TeridanDW

**Comment by TeridanDW** [comment]
Works as intended on PTR now.
Thank you.
