### ISSUE TITLE
[Raid] Zul'aman "encounter in progress bug" after a wipe

### ISSUE THREAD

**Issue by Ilovemultiboxing** [dalaranwow/dalaran-wow#4960]
Current behaviour:
After a wipe on a boss (I tried it on 3 of them already), you can't enter in the raid anymore unless you disband the raid and reform it(because it says "encounter still in progress"). 

Note : that only works if you didn't kill anyboss already, if you did, you just can't enter anymore unless there's a server restart.

Expected behaviour:
After a wipe you should be able to release and run in the raid

Steps to reproduce the problem:
Wipe on a boss in Zul'aman

**Comment by TeridanDW** [comment]
Hello and thank you for the report @Ilovemultiboxing.
It's general issue with all bosses/encounters in the game, if the bosses does not reset (on wipe) before every player releases this issue occures.
Workaround is setting them active like here  #3099

**Comment by Ilovemultiboxing** [comment]
You're welcome Teridan, 

So what you're saying is that all players need to release before the boss comes back to his original place ?

I hope we'll see this fix somewhat soon then ;)

**Comment by TeridanDW** [comment]
No @Ilovemultiboxing, the other way around.
There must be atlest 1 person inside the raid (dead **without** releasing spirit) to see the boss resets properly and then this bug won't happen.

**Comment by Ilovemultiboxing** [comment]
Mmmmh that's weird, I tried both way and it seems that it doesn't work, I even tried to enter in the raid with one player when all of the others were still in it dead w/o releasing and it doesn't work too. Seems to be like that for everybosses of Zul'aman only. Never seen it happens elsewhere since I always have atleast one toon still in the raid cause I click the release on all of them and take my time

**Comment by Lothloryen** [comment]
Hello there,

This should be just an isolated issue, however, if it happens more than once there might be a specific problem with that boss. Could you please let me know which with wich encounter you experienced the aforementioned problem?

**Comment by Ilovemultiboxing** [comment]
Hey Lothloryen, 

Def not an isolated issue sadly, happened today again, as always, one wipe and the instance is locked because of the combat bug, it happens on atleast 3 bosses so far. Nalorakk, Akil'zon, Halazzi
