### ISSUE TITLE
[Quest][Classic] Venomhide Eggs

### ISSUE THREAD

**Issue by Imbarawr** [dalaranwow/dalaran-wow#4964]
**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
The quest Venomhide Eggs: https://wowgaming.altervista.org/aowow/?quest=13887 is currently avaliable without finishing the pre-quest Toxic Tolerance: https://wowgaming.altervista.org/aowow/?quest=13850

**Expected behaviour**: Tell us what should happen instead
Players should have to complete Toxic Tolerance to be able to pick up Venomhide Eggs.

**Steps to reproduce the problem**:

1. Go to Mor'vek in Un'Goro Crater: https://wowgaming.altervista.org/aowow/?npc=11701
2. See that both quests are avaliable.
3. N/A

**Include proofs for this behaviour**
N/A

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**
Venomhide Eggs: https://wowgaming.altervista.org/aowow/?quest=13887
Toxic Tolerance: https://wowgaming.altervista.org/aowow/?quest=13850
Mor'vek: https://wowgaming.altervista.org/aowow/?npc=11701

**Include Screenshots from the issue if necessary**
N/A

**Comment by TeridanDW** [comment]
Thank you for the report @Imbarawr.
Issue confirmed on PTR.

**Suggested fix:**
``` sql
UPDATE `quest_template_addon` SET `PrevQuestID` = 13850 WHERE `ID` = 13887; 
```

**Comment by TeridanDW** [comment]
Works as intended on PTR.
