### ISSUE TITLE
[Quest NPC] Lar'kowi mate drops two quest items

### ISSUE THREAD

**Issue by Imbarawr** [dalaranwow/dalaran-wow#4965]
**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
When doing the quest The Scent of Lar'Korwi: https://wowgaming.altervista.org/aowow/?quest=4291 Lar'Korwi Mate: https://wowgaming.altervista.org/aowow/?npc=9683 currently drops two (2) Ravasaur Pheremone Gland: https://wowgaming.altervista.org/aowow/?item=11509

**Expected behaviour**: Tell us what should happen instead
Should only drop one (1).

**Steps to reproduce the problem**:

1. Acquire quest The Scent of Lar'Korwi: https://wowgaming.altervista.org/aowow/?quest=4291
2. Kill Lar'Korwi Mate
3. See that they drop two (2) Ravasaur Pheremone Gland: https://wowgaming.altervista.org/aowow/?item=11509

**Include proofs for this behaviour**
https://imgur.com/a/Q49iJ

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**
The Scent of Lar'Korwi: https://wowgaming.altervista.org/aowow/?quest=4291
Ravasaur Pheremone Gland: https://wowgaming.altervista.org/aowow/?item=11509
Lar'Korwi Mate: https://wowgaming.altervista.org/aowow/?npc=9683

**Include Screenshots from the issue if necessary**
See proof

**Comment by TeridanDW** [comment]
Hello and thank you for the report @Imbarawr.
Wowhead says indeed 1 item should drop pet kill.

**Suggested fix:**
```sql
UPDATE `creature_loot_template` SET `MaxCount` = 1 WHERE `Entry` = 9683 AND `Item` = 11509; 
```
