### ISSUE TITLE
Drop rates seems high at levelrange 50-60

### ISSUE THREAD

**Issue by Imbarawr** [dalaranwow/dalaran-wow#4967]
**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
While killing Winterfall Ursa: https://wowgaming.altervista.org/aowow/?npc=7438 and Winterfall Shaman: https://wowgaming.altervista.org/aowow/?npc=7439 in Winterfall Village in Winterspring I recieved quite many rares and an epic. This could just be luck but it could also be  faulty drop rates.

**Expected behaviour**: Tell us what should happen instead
Could be an enormous amount of luck but might be worth checking it out.

**Steps to reproduce the problem**:

1. Kill Winterfall Ursa and Winterfall Shaman in Winterfall Village
2. Observe drop rate
3. 

**Include proofs for this behaviour**
N/A
**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**
Winterfall Shaman: https://wowgaming.altervista.org/aowow/?npc=7439
Winterfall Ursa: https://wowgaming.altervista.org/aowow/?npc=7438

**Include Screenshots from the issue if necessary**
N/A

**Comment by Imbarawr** [comment]
Not only in Winterfall Village. I have recieved five (5) epic world drops today in the range between lvl 50-57. I find it very hard to believe this is pure luck. The drops has come from mobs in Un'Goro Crater, Felwood and Winterspring.

**Comment by TeridanDW** [comment]
Hello, this topic was discussed already here #1356
