### ISSUE TITLE
[Quest][Northrend] Krolmir, Hammer of Storms

### ISSUE THREAD

**Issue by Kaara** [dalaranwow/dalaran-wow#497]
Hello,

http://www.wowhead.com/quest=13010

This quest is bugged. I got to friendly, i done the chain quest. When i ask King Jokkun to tell me the story, i cannot click to see the story.

**Comment by ciccioriccio** [comment]
Quest is bug again... i completed the quests before, got neutral reputation with the Sons of Hodir, but when i talk King Jokkun nothing happens, just like i dont have the quest

**Comment by Golganeth** [comment]
Note: Currently Thorim is a bit too slow so King Jokkum will do the script like talking to a wall. Thorim's arrival should be faster

**Comment by Golganeth** [comment]
Note: Currently Thorim is a bit too slow so King Jokkum will do the script like he's talking to a wall. Thorim's arrival should be faster.
After the event, Thorim should stay there for a short while so that players can get the quest rewarded, and then despawn.
