### ISSUE TITLE
[Spell] Damage does not break Entangling Roots, PvE

### ISSUE THREAD

**Issue by Imbarawr** [dalaranwow/dalaran-wow#4977]
**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
While doing the Ring of Blood event in Nagrand, Outland we where able to keep the NPC rooted in place while a warlock and a druid went all out in damage. We kept the NPC rooted until it died.

**Expected behaviour**: Tell us what should happen instead
A certain amount of damage should break the Entangling Roots.

**Steps to reproduce the problem**:

1. Go to Ring of Blood in Nagrand, outland
2. Start the event
3. When a mob spawns, root it and nuke to see when it breaks.

**Include proofs for this behaviour**
N/A

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**
Entangling Roots: http://www.wowhead.com/spell=339/entangling-roots

**Include Screenshots from the issue if necessary**
N/A

**Comment by TeridanDW** [comment]
Hello and thank you for the report @Imbarawr.
Issue confirmed on PTR.
Additional info: There seems to be some threshold of damage and if the player stays under it, the roots won't break (regardless how many attacks/spells direct or dots are done). After he passes it they break.

**Comment by robinsch** [comment]
I can't confirm that. I just rooted a NPC and it broke with one Wrath and MF tick.

**Comment by Imbarawr** [comment]
@robinsch Try lower level spells, it seems that it breaks easier at higher level. Like the threshold is set to a fixed amount of damage. That you son't reach on lower levels.

**Comment by StheNoble** [comment]
I cant confirm this on live either. 

For example we sometimes spamroot beasts on Sauerfang in ICC where the beasts still move a few yards in between the 1.2seconds until next cast lands because they breake from damage within this 1.2 sec. 

roots break reliably on their damage treshhold from my perspective.

**Comment by TeridanDW** [comment]
Hello, after few fast tests on PTR this:

> Additional info: There seems to be some threshold of damage and if the player stays under it, the roots won't break (regardless how many attacks/spells direct or dots are done). After he passes it they break.


is still a problem.
Maybe this commit is not on PTR yet or not working.

Note: Thank you for the comment @StheNoble, however this report is valid and the issue was found.

**Comment by robinsch** [comment]
The threshold is based on player health in PvE combat, before it was based on creature health which caused it not to break versus high hp npcs. I'm pretty sure this should work in most cases.

**Comment by TeridanDW** [comment]
Hello, after a second look in to this it makes all the sence to be like you said @robinsch.
Thank you.

**Comment by Lothloryen** [comment]
Updated.
