### ISSUE TITLE
Warrior: Heroic Strike/Cleave - Incorrect auto-cancellation based on Rage.

### ISSUE THREAD

**Issue by Aridam** [dalaranwow/dalaran-wow#4981]
**Current behaviour**: Heroic Strike/Cleave get the error "Interrupted" if they are queued and the Rage you have goes below the minimum required Rage at any time while they're still queued, and thus get auto-cancelled on their own before you even get to swing.

**Expected behaviour**: There should be no auto-cancellation with "Interrupted" being said due to not having enough Rage at any time before the actual attack -- if you attempt to swing with HS/Cleave queued, that's when they're supposed to be cancelled and instead trigger the Auto-Attack for not having the minimum Rage needed. This is so that if at any time, right as you are about to swing, your Rage goes up to at least the minimum required Rage to use, you are able to attack with HS/Cleave as queued.

**Steps to reproduce the problem**:

1. Attack anything;
2. Queue either Heroic Strike or Cleave before your next Auto-Attack;
3. Still before your next swing, drop your Rage below the required and observe the immediate auto-cancellation + "Interrupted" error.

**Include proofs for this behaviour**

Heroic Strike IDs (for all Ranks):
https://wotlk-twinhead.twinstar.cz/?spell=78
https://wotlk-twinhead.twinstar.cz/?spell=284
https://wotlk-twinhead.twinstar.cz/?spell=285
https://wotlk-twinhead.twinstar.cz/?spell=1608
https://wotlk-twinhead.twinstar.cz/?spell=11564
https://wotlk-twinhead.twinstar.cz/?spell=11565
https://wotlk-twinhead.twinstar.cz/?spell=11566
https://wotlk-twinhead.twinstar.cz/?spell=11567
https://wotlk-twinhead.twinstar.cz/?spell=25286
https://wotlk-twinhead.twinstar.cz/?spell=29707
https://wotlk-twinhead.twinstar.cz/?spell=30324
https://wotlk-twinhead.twinstar.cz/?spell=47449
https://wotlk-twinhead.twinstar.cz/?spell=47450

Cleave IDs (for all Ranks):
https://wotlk-twinhead.twinstar.cz/?spell=845
https://wotlk-twinhead.twinstar.cz/?spell=7369
https://wotlk-twinhead.twinstar.cz/?spell=11608
https://wotlk-twinhead.twinstar.cz/?spell=11609
https://wotlk-twinhead.twinstar.cz/?spell=20569
https://wotlk-twinhead.twinstar.cz/?spell=25231
https://wotlk-twinhead.twinstar.cz/?spell=47519
https://wotlk-twinhead.twinstar.cz/?spell=47520

**Comment by robinsch** [comment]
No this is intended, before you would always miss the auto attack if you had Cleave or Heroic Strike queued.

**Comment by Aridam** [comment]
What I meant in what I was trying to describe was that, let's say you have 25 Rage. Auto-Attack is on and the Swing Timer is counting down. You have Heroic Strike (default -- no Improved Heroic Strike or anything else that modifies its Rage cost -- so that makes it 15 Rage needed to use it).

So currently you have the ability to use HS since you have 25 Rage and default HS is 15 Rage.

Let's say you use default Thunder Clap -- which is 20 Rage. You now have 5 Rage.

What currently happens (and what I'm reporting) is that even _while_ the Swing Timer isn't even over yet, HS (as well as Cleave is queued that instead) gets cancelled just for dropping down below the minimum -- _before_ you even get to the point of being about to swing at your Target and are in Melee Range to do so.

What I was describing in how it "should" be (could be wrong due to memory), was that none of that should happen at all, _unless_ the Swing Timer is done _and_ you're in Melee Range about to swing at your Target -- which is what you described in your reply. What you described as HS/Cleave getting cancelled when in Melee Range and swinging with not enough Rage for either Abilities queued is correct just to say, and is working as it's intended here, so no problems there -- the problem with this lies in HS/Cleave getting auto-cancelled _anytime else_, or not even within Melee Range to swing at your Target even if the Swing Timer is done.

However, currently not finding Retail video proof as hard-solid evidence of this, or any written or slightly-above that would suffice for that matter.
