### ISSUE TITLE
General Ability: Auto Attack - Incorrect Swing Timer reset.

### ISSUE THREAD

**Issue by Aridam** [dalaranwow/dalaran-wow#4982]
**Current behaviour**: Mounting resets the Swing Timer on your Auto Attack.

**Expected behaviour**: Mounting shouldn't reset the Swing Timer on your Auto Attack.

**Steps to reproduce the problem**:

1. Mount up;
2. Immediately dismount to attack and notice how you're not attacking until the equivalent of your Attack Speed's time has passed.

**Include proofs for this behaviour**

Auto Attack ID: https://wotlk-twinhead.twinstar.cz/?spell=6603

Also I've noticed while testing on a Heroic Training Dummy, if I dismount into a Charge and leave the Dummy before I get to use my bugged Auto Attack, I get stuck in Combat -- only by running back to it to finally swing and then leave it again can I disengage.

**Comment by robinsch** [comment]
Please find a proof (video from retail prefered).

**Comment by Aridam** [comment]
Currently unable to find for this as well -- Retail WotLK information on such subtle subjects is proving to be a bother so many years later, compared to how easy it used to be then. However looking back and searching around for actions and more which cause Swing Timer resets, I could be wrong, but then again, now I'm split and can't actually be sure, as castables, other Abilities and forms of attack, and even some world actions (like Mining), impede a Swing Timer reset, so mounting could be one of those many as well.

Until proof to this report or against it is found -- having revisited this now -- I'm currently not certain.

**Comment by Aridam** [comment]
Bump.

https://www.youtube.com/watch?v=qtFM6_MuMjk

This video was recording for a different report but I accidentally managed to recreate this issue at random -- watch until nearly the end where it happens: Swing Timer is over, I intercept, but no Auto Attack happens. Watch the Rage for example, and for any other pointers -- no gain in Rage, nothing else happening, so it can't be that there _was_ an Auto Attack happening but it just visually didn't show.

This in fact _does_ happen at random, as I haven't figured out a way to _force_ it -- sometimes it happens _minutes_ after mounting up and then dismounting to Charge at something, and sometimes it just happens mid-Combat like here as shown.

Huge bug for Warriors -- can't really do much with no Rage 'cause of random "missing" Auto Attacks.
