### ISSUE TITLE
Wintergarde mine (needs more mobs spawned)

### ISSUE THREAD

**Issue by descendance** [dalaranwow/dalaran-wow#499]
So basicly the are around 7-8 miners in the whole mine spawned took me 3-4 clears to finish Not in our Mine quest. You need to spawn some more miners, i am not 100% sure this is retail vid but there are much more mobs in it http://www.youtube.com/watch?v=v3z9BETOoEs

**Comment by Golganeth** [comment]
Amount of NPCs hotfixed on Algalon.

**Comment by moljac89** [comment]
again, low amount of NPCs, need more.

**Comment by Golganeth** [comment]
Confirmed.

- NPC ID: **27401** [Risen Wintergarde Miner](http://wotlk.openwow.com/npc=27401)
- Related quest ID: *12269* - [Not In Our mine](http://wotlk.openwow.com/quest=12269)

**Comment by Golganeth** [comment]
The amount of NPCs is pretty much correct, however most of them are lacking SAI and just stand still.
