### ISSUE TITLE
Warrior Talent: Sweeping Strikes -- Retaliation not consuming any charges.

### ISSUE THREAD

**Issue by Aridam** [dalaranwow/dalaran-wow#4991]
**Current behaviour**: While Sweeping Strikes is up, Retaliation isn't consuming any of its charges when you proc a Retaliation counterattack and there's at least one more enemy in Range of the original attacker.

**Expected behaviour**: Sweeping Strikes should be procced by Retaliation counterattacks when there is a valid enemy within Melee Range of the first attacker to proc it upon.

**Steps to reproduce the problem**:

1. Use Sweeping Strikes;
2. Use Retaliation;
3. Have at least two enemies attack you and look at SS -- no charges consumed.

**Include proofs for this behaviour**

Sweeping Strikes ID: https://wotlk-twinhead.twinstar.cz/?spell=12328

Proof of this being patched on Retail to do this: http://wowwiki.wikia.com/wiki/Patch_1.9.0 -- "Sweeping Strikes - Whirlwind and Retaliation will now correctly consume the charges from Sweeping Strikes." (scroll down and find it or Ctrl-F "Retal")

**Comment by robinsch** [comment]
A patch log from 1.9 is pretty old. You might find a video tho.

**Comment by Aridam** [comment]
This might be a bust as upon closer examination (since this can be difficult to deduct), it seems that Retaliation isn't massively-consuming SS in the following videos stopped at key times -- even with fewer, more distinguishable attacks, closeby victims who trigger the counterattacks don't seem to trigger Sweeps as well, but correct me if my deduction is wrong here.

Retail WotLK videos:
https://youtu.be/rNVoMGRg4QE?t=166
https://youtu.be/IijlbG7yrlc?list=PL036713627CC61696&t=163
https://youtu.be/3cGqlcE44m0?t=921
https://youtu.be/3cGqlcE44m0?t=960

Notice how for example in Klinda's video against the Rogue with the Shadowfiend popping up, despite the SF being near the Rogue enough, Retaliation procs don't seem to consume SS, but rather any swings and damaging Abilities. Then, in the second one, against the two people in AB, the same thing seems to occur -- other forms of attack proc SS inbetween the two victims of it, but Retaliation just doesn't seem to lower the counter by itself as well.

Veev's extracts makes that even more obvious -- especially the second one, where one can easily count down Retaliation synced with Sweeping Strikes and look at the much lower number of other attacks. For example against the Rogue/Priest team in Arena, by the time he activates Retaliation and gets to proc it, SS is at 4 charges left. Retaliation then counterattacks twice, but no SS are consumed at all.

Check for yourself to make sure I'm not deducting wrong, but personally, this might as well be a false alarm and closed -- pardon if that's so. You were correct in calling out the age of the Vanilla patch's note on this subject.

**Comment by Aridam** [comment]
Confirmed as a pre-WotLK mechanic -- report was a false alarm; Retaliation not supposed to consume SS charges.
