### ISSUE TITLE
[NPC] Two Big Roys in the world

### ISSUE THREAD

**Issue by Imbarawr** [dalaranwow/dalaran-wow#4993]
**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
There are currently two Big Roy: http://www.wowhead.com/npc=24785/big-roy in the world.

**Expected behaviour**: Tell us what should happen instead
Should only be one.

**Steps to reproduce the problem**:

1. Go to the location of Big Roy: http://www.wowhead.com/npc=24785/big-roy
2. Observe that there is two of them
3. 

**Include proofs for this behaviour**
https://imgur.com/a/xBTRs

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**
Big Roy: http://www.wowhead.com/npc=24785/big-roy

**Include Screenshots from the issue if necessary**
See proof

**Comment by TeridanDW** [comment]
Thank you for the report @Imbarawr.
Issue confirmed on PTR.
-- delete the extra creature

``` sql
SET @NPC := 203496;
SET @PATH := @NPC * 10;
DELETE FROM `creature_addon` WHERE `guid`=@NPC;
DELETE FROM `waypoint_data` WHERE `id`=@PATH;
DELETE FROM `creature` WHERE `guid`=@NPC;
```

**Comment by TeridanDW** [comment]
Works as intended on PTR.
