### ISSUE TITLE
[Quest] Two Hellscream's Vigil quests

### ISSUE THREAD

**Issue by Imbarawr** [dalaranwow/dalaran-wow#4994]
**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
There are currently two identical quests called Hellscream's Vigil:http://www.wowhead.com/quest=11586/hellscreams-vigil in Borean Tundra. According to wowhead there are two quests but it seems one of them is a follow-up from the Warchief's Command: Northrend(that is not avaliable in 3.3.5): http://www.wowhead.com/quest=28711/warchiefs-command-northrend

**Expected behaviour**: Tell us what should happen instead
There should only be one.

**Steps to reproduce the problem**:

1. Go to Borean Tundra, where to zeppelin stops
2. Go to the questgiver just where you step off the zeppelin
3. See that there are two identical quest avaliable

**Include proofs for this behaviour**
N/A

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**
Hellscream's Vigil:http://www.wowhead.com/quest=11586/hellscreams-vigil

Warchief's Command: Northrend: http://www.wowhead.com/quest=28711/warchiefs-command-northrend
Hellscream's Vigil, follow-up quest to Warchief's Command: http://www.wowhead.com/quest=11585/hellscreams-vigil

**Include Screenshots from the issue if necessary**
N/A

**Comment by TeridanDW** [comment]
Thank you for the report @Imbarawr.
Issue confirmed on PTR.
-- add exclusive group to these 2 quests so only 1 can ever be taken

``` sql
DELETE FROM `quest_template_addon` WHERE `ID` IN (11585, 11586);
INSERT INTO `quest_template_addon` (`ID`, `MaxLevel`, `AllowableClasses`, `SourceSpellID`, `PrevQuestID`, `NextQuestID`, `ExclusiveGroup`, `RewardMailTemplateID`, `RewardMailDelay`, `RequiredSkillID`, `RequiredSkillPoints`, `RequiredMinRepFaction`, `RequiredMaxRepFaction`, `RequiredMinRepValue`, `RequiredMaxRepValue`, `ProvidedItemCount`, `SpecialFlags`) VALUES
(11585,0,0,0,0,0,11585,0,0,0,0,0,0,0,0,0,0),
(11586,0,0,0,0,0,11585,0,0,0,0,0,0,0,0,0,0);
```

**Comment by STARRHELD** [comment]
Isn't there a condition checking if the nagrand questline is done?
```SQL
DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId`=19 AND (`SourceEntry`=11586 OR `SourceEntry`=11585);
INSERT INTO `conditions` (`SourceTypeOrReferenceId`,`SourceEntry`,`ConditionTypeOrReference`,`ConditionValue1`,`Comment`) VALUES 
(19, 11585, 14, 10172, "Accept quest 11585 - Quest 10172 needs to be incomplete"),
(19, 11586, 8, 10172, "Accept quest 11586 - Quest 10172 needs to be rewarded");

UPDATE `quest_template_addon` SET `ExclusiveGroup`=11585 WHERE `ID` IN (11585,11586);
```

**Comment by TeridanDW** [comment]
Hello,
Regarding:

> Isn't there a condition checking if the nagrand questline is done?

what does nagrand quest chain has to do with these 2 quests (11585,11586)?
Might be wrong here, but I don't see any connection.

**Comment by Imbarawr** [comment]
@TeridanDW http://wowwiki.wikia.com/wiki/Quest:Hellscream%27s_Vigil

**Comment by STARRHELD** [comment]
Same quest just differentiates if you have done the quest chain in Nagrand.

**Comment by TeridanDW** [comment]
Alright, thank you both. Now it makes sense.
Full version should be:
``` sql
DELETE FROM `conditions` WHERE `SourceTypeOrReferenceId`=19 AND (`SourceEntry`=11586 OR `SourceEntry`=11585);
INSERT INTO `conditions` (`SourceTypeOrReferenceId`, `SourceGroup`, `SourceEntry`, `SourceId`, `ElseGroup`, `ConditionTypeOrReference`, `ConditionTarget`, `ConditionValue1`, `ConditionValue2`, `ConditionValue3`, `NegativeCondition`, `ErrorType`, `ErrorTextId`, `ScriptName`, `Comment`) VALUES
(19,0,11585,0,0,14,0,10172,0,0,0,0,0,'','Accept quest 11585 - Quest 10172 needs to be incomplete'),
(19,0,11586,0,0,8,0,10172,0,0,0,0,0,'','Accept quest 11586 - Quest 10172 needs to be rewarded');

DELETE FROM `quest_template_addon` WHERE `ID` IN (11585, 11586);
INSERT INTO `quest_template_addon` (`ID`, `MaxLevel`, `AllowableClasses`, `SourceSpellID`, `PrevQuestID`, `NextQuestID`, `ExclusiveGroup`, `RewardMailTemplateID`, `RewardMailDelay`, `RequiredSkillID`, `RequiredSkillPoints`, `RequiredMinRepFaction`, `RequiredMaxRepFaction`, `RequiredMinRepValue`, `RequiredMaxRepValue`, `ProvidedItemCount`, `SpecialFlags`) VALUES
(11585,0,0,0,0,0,11585,0,0,0,0,0,0,0,0,0,0),
(11586,0,0,0,0,0,11585,0,0,0,0,0,0,0,0,0,0);
```

**Comment by TeridanDW** [comment]
Works as intended on PTR.
