### ISSUE TITLE
Problem with instant 70

### ISSUE THREAD

**Issue by kittyop** [dalaranwow/dalaran-wow#4995]
Greetings,

As first sorry for my english.

Whats the problem ?

I bought donation points for 25€ for my instant 70level boost. After logout i choose the instant 70+ flying , after all steps and procedures i completed it and then login on my character and this character still on lvl 26 a nothing changes.

Nickname of the characeter: Kittyop

Many thanks to everyone who can help (this is not my first donate)

**Comment by kittyop** [comment]
Next problem what i found that is i cant find this character on account manager . It says (u must create a character ) , that i have a character which i choose to boost.

Thanks again

**Comment by Imbarawr** [comment]
I think the reason you see "You must create a character" is because that part of the website is connected to the Kirin Tor realm, not Algalon. If you create a character on Kirin Tor it will show up.

**Comment by kittyop** [comment]
@Imbarawr one of the problem solved. Many thanks for answer, i will create a character on kirin tor. But most important thing, i need to solve my level boost ( Its not my first lvl boost. First one works well this second is bugged)
