### ISSUE TITLE
[NPC] Bloodspore Firestarter not performing melee

### ISSUE THREAD

**Issue by Imbarawr** [dalaranwow/dalaran-wow#4996]
Current behaviour: Tell us what happens in detail (Where, When, What, Why, Who)
After engaging Bloodspore Firestarter in Borean Tundra and the NPC mana is out he will no longer perform attack if the player is at range. He will not move towards the player. If the player steps in he will start melee attacks, if player steps out from melee range the mob follows and performs melee.

Edit: NPC is also moving while casting

Expected behaviour: Tell us what should happen instead
When out of mana the NPC should move towards the player and begin melee attack.

Edit: Should stand still while casting.

Steps to reproduce the problem:

1. Find NPC
2. Aggro and let the NPC use all mana
3.Observe at range as NPC won't move into melee

Include proofs for this behaviour
N/A

Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills
Bloodspore Firestarter: http://www.wowhead.com/npc=25470/bloodspore-firestarter

Include Screenshots from the issue if necessary
N/A

**Comment by TeridanDW** [comment]
Hello and thank you for the report @Imbarawr, however in this case I will ask you to check this creature after report #4552 is on live, because I remember making a new SAI for him.

**Comment by Imbarawr** [comment]
@TeridanDW Will do. I searched before I posted but was too specific I'm afraid :)
