### ISSUE TITLE
General: Interactions with Objects/NPCs - "That is already being used"/unresponsiveness.

### ISSUE THREAD

**Issue by Aridam** [dalaranwow/dalaran-wow#4998]
**Current behaviour**: Interacting with anything that is considered borderline-far (just almost out of reach to interact) bugs whatever you're interacting with out, as so:

In the case of Objects (such as Mining/looting etc.), the specified interaction doesn't complete, and retries result in the error "That is already being used." -- only relogging serves as a workaround to this.

In the case of NPCs, trying to trigger scripts (for example vendoring, training -- virtually anything) receives no response despite the selection of the option -- re-interacting resolves it but is still tedious.

Both force one to make sure they're not too far when interacting with anything, in order to avoid either of these occurrences.

**Expected behaviour**: These interactions shouldn't bug out -- if you're within their range of interaction, there shouldn't be any exceptions in the form of these two repeatable anomalies.

**Steps to reproduce the problem**:

Object bug reproduction:
1. Find a Vein to use Mining on, or a Chest to loot;
2. Stand as far-back as you can while still being able to interact;
3. Attempt to do so and watch as the action doesn't finish;
4. Retry and notice the failure accompanied by the error "That is already being used";
5. Relog and retry but closer -- should work this time.

NPC bug reproduction:
1. Find any NPC (Vendor, Trainer, etc.);
2. Stand as far-back as you can while still being able to interact;
3. Pick a script option -- no response;
4. Close interaction window and retry while standing closer this time -- should work now.

**Comment by sebastienwood** [comment]
Confirmed on Algalon and Kirin Tor.

Can reveal problematic on certain quest like Return of the High Chief in Dragonblight (http://www.wowhead.com/quest=12069/return-of-the-high-chief) where you can't take the WoW Object this NPC drops : http://www.wowhead.com/npc=26608/under-king-anubetkan

Thought this may be another problem as distance does affect the possibility to pick the object (multiple attempts were made).

+1

**Comment by TeridanDW** [comment]
Hello and thank you for the report @Aridam.
Issue confirmed on PTR.
Additional info: The problem is general and it affects all lootable GOs ingame.

Note: I remember writting a report for this issue, but I can't seem to find it now.

**Comment by AwkwardAlex** [comment]
I'd like to point one interesting thing. Over the past few weeks I've spent a lot of time mining and I've noticed that only some nodes are affected by this bug. For example, there is one in a cave in the Storm Peaks that has bugged like this at least a dozen of time, while others around of them are working perfectly fine.

**Comment by Aridam** [comment]
This still happens with NPCs at random times -- approaching them and triggering a script with them (speech bubble, training, etc.) doesn't work, forcing me to re-interact with them in order to trigger whatever script of theirs I want properly.

**Comment by Aridam** [comment]
Reconfirming AwkwardAlex's post that this happens especially frequently with certain interactables -- the Flight Master in Orgrimmar tends to give this bug for example.

**Comment by Aridam** [comment]
Any progress?

**Comment by Lothloryen** [comment]
Already on live, thank you.
