### ISSUE TITLE
Distract still not working properly!!!

### ISSUE THREAD

**Issue by Desecrator** [dalaranwow/dalaran-wow#5000]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: After last fixes, the Distract ability of Rogue is still not fixed. Every time i use it, instead of facing the point, they face directly towards me and charge to attack.

**Expected behaviour**:  It should make mobs face the direction of the Distract point of impact

**Steps to reproduce the problem**:

1. Go in stealth
2. Trow Distract at any mob, best to be aggressive mob
3. Mobs charge you, instead of turing away to the point of impact of Distract

**Include proofs for this behaviour**

http://www.wowhead.com/spell=1725/distract

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

http://www.wowhead.com/spell=1725/distract

**Include Screenshots from the issue if necessary**

And please try not on PTR, but on live. I will be there online most of time, so if needed i will gladly show you the problem.

**Comment by Lothloryen** [comment]
Duplicated #4935

**Comment by Desecrator** [comment]
Can you please come in game next to me and we can test it!

**Comment by Desecrator** [comment]
I know what i am talking about

**Comment by Lothloryen** [comment]
#4935
