### ISSUE TITLE
Quest: Homeward Bound - Auto-completion upon accepting.

### ISSUE THREAD

**Issue by Aridam** [dalaranwow/dalaran-wow#5001]
**Current behaviour**: The Quest "Homeward Bound" given by Pao'ka Swiftmountain found in Highperch located in the Thousand Needles auto-completes upon accepting.

**Expected behaviour**: The Quest should complete once you've fully-escorted the NPC -- _not_ when you accept it.

**Steps to reproduce the problem**:

1. Go to Highperch, in the Thousand Needles (the Wyvern area);
2. Get to the end where the high cliff is at -- that's where Pao'ka stands;
3. Accept the Quest -- notice it auto-completes and you can just disregard the NPC and go hand it in already.

Quest ID: https://wowgaming.altervista.org/aowow/?quest=4770

**Comment by TeridanDW** [comment]
Hello and thank you for the report @Aridam.
Issue confirmed on PTR.
Note: Creature has core script.

![image](https://user-images.githubusercontent.com/6797611/32619855-8972e720-c584-11e7-97be-2f9aa2916dee.png)

**Comment by TeridanDW** [comment]
Works as intended on PTR.

Note: There seems to be an issue with escort quests where the creature (that is been escorted - Pao'ka Swiftmountain in this case) does not follow the waypoints properly. Meaning if he engages a creature -> kills it -> runs ahead few wps -> reaches the said wp and runs back to the prevous (correct one) wp and starts to walk.
This is the second escort quest that I see this behaviour so it must be general issue?

**Comment by Aridam** [comment]
Can't tell as the general gist is that they mostly-run and if you make sure Mobs don't hit them they just keep running -- I've no clear memory of what happens if they fight as well and then go back to their preceding waypoint to continue again from there so I won't give false claims.
