### ISSUE TITLE
[UI] /Who list argument strings broken

### ISSUE THREAD

**Issue by Siggrdrifa** [dalaranwow/dalaran-wow#5002]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: 

>  When you type /who with an argument string like "c-Priest", "g-GuildName" or ""r-Orc", the game doesnt recognise the command, same thing if you try to type this in the /who windows' search bar.
> Some of the arguments, howerver, ARE working, specifically "z-" and "#number"

**Expected behaviour**:    

> The argument strings "c-" "r-" should filter out everyone in /who list if they are not from the set class/race/guild.
> For example, if I type "/who c-Priest g-Potatohead 80" into the chat, the game should return a list of all online Level 80 Priests that currentl§ belong to the Potatohead guild.
> Same thing if I input " r-"Blood Elf" z-"Ashenvale" 20-35 "  in the who list search bar, should return any level 20-35 Blood elf currently in Ashenvale

-
**Steps to reproduce the problem**:

> 1.  Type /who with some string arguments (z-/c-/r-/g-/level) or go to Social>Who List and add arguments to the search bar.

**Include proofs for this behaviour**

http://wowwiki.wikia.com/wiki/Who

http://wowwiki.wikia.com/wiki/MACRO_who

 Including SSs with 0 addons for confirmation.

**Include Screenshots from the issue if necessary**
![wowscrnshot_110217_201558](https://user-images.githubusercontent.com/33332434/32355017-399a31f0-c00b-11e7-8eec-2ff74c810093.jpg)
![wowscrnshot_110217_201646](https://user-images.githubusercontent.com/33332434/32355019-39c2caac-c00b-11e7-980b-fcb354890e80.jpg)
![wowscrnshot_110217_201710](https://user-images.githubusercontent.com/33332434/32355022-39f20808-c00b-11e7-9d2b-b3c54541547f.jpg)

**Comment by robinsch** [comment]
Fixed with https://github.com/dalaranwow/principal/commit/22b2c713587de83c8b05ba0d2b4cc0bd3ceb09df

**Comment by Boralamt** [comment]
This issue seems to be present on the latest release.
