### ISSUE TITLE
Distract still not working properly!!! Evidence!!!

### ISSUE THREAD

**Issue by Desecrator** [dalaranwow/dalaran-wow#5003]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: After last fixes, the Distract ability of Rogue is still not fixed. Every time i use it, instead of facing the point, they face directly towards me and charge to attack

**Expected behaviour**:  It should make mobs face the direction of the Distract point of impact

**Steps to reproduce the problem**:

1. Go in stealth
2. Trow Distract at any mob, best to be aggressive mob
3. Mobs charge you, instead of turning away to the point of impact of Distract

**Include proofs for this behaviour**

Here are links to the videos, sorry for the short videos but i have a 500mb limit to upload.
1st video is to a non aggressive mob - https://vimeo.com/240999607
2nd video is to aggressive mob - https://vimeo.com/240999823

Hope now you will stop closing my issues and look in to it!

**Comment by alexuktc** [comment]
Interesting. How many types of mobs act this way and in how many areas? I will go and try to replicate when I have the time. 

It is possible that it is based on the mobs themselves or a talent. I am combat, so I am missing some of your talents.

**Comment by robinsch** [comment]
Merged and fixed with https://github.com/dalaranwow/dalaran-wow/issues/4935

**Comment by Desecrator** [comment]
Every mob in every area acts like this! There is no difference

**Comment by Lothloryen** [comment]
@Desecrator Try it now, it should be fine.
