### ISSUE TITLE
Herbs in general

### ISSUE THREAD

**Issue by Ninielle** [dalaranwow/dalaran-wow#5004]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Herbs in general are scarce. Some zones are almost completely empty, or have no herb from a type which it should have. Leveling herbalism by itself takes days, not to mention alchemy or inscription. I searched for other topics about this mentioning the problem isn't exactly only with the nodes, but their respawn time as well. But those topics were years old and it's still a problem.
Anyone working on it, or can we expect fixes about this in the near future?

**Steps to reproduce the problem**:

1. Tried gathering Netherbloom in Netherstorm with little to no success. Same with Shadowmoon Valley in case of Nightmare Vine. Only a few nodes of Briarthorn in Westfall. Almost no nodes of Goldclover in Grizzly Hills. Etc..
2. After looting some nodes, they respawn right after, happened to find 2 nodes on top of each other (or lapping each other).
3. Some nodes didnt respawn for hours.

**Comment by TeridanDW** [comment]
Hello and thank you for the report @Ninielle,
@Rushor maybe there is something wrong with the spawn of the GOs as I can't see them even in GM mode  or in the pooling?
![image](https://user-images.githubusercontent.com/6797611/32619382-44d571ce-c583-11e7-83f4-8b6c87772ce4.png)

**Comment by Rushor** [comment]
mainissue for this is here https://github.com/dalaranwow/dalaran-wow/issues/1208 - please post you issue in the linked ticket. thanks.
