### ISSUE TITLE
{Quest} Thalorien Dawnseeker

### ISSUE THREAD

**Issue by Warlorct** [dalaranwow/dalaran-wow#5007]
Server: Kirin-Tor
Character Name: Warlorct

Quest: Thalorien Dawnseeker

I can locate the remains or Thalorien Dawnseeker, and interact with him.  There is no conversation to start the quest for the sword though.

**Comment by Zarjofgt** [comment]
Can you kirin tor monkies sod off?

**Comment by TeridanDW** [comment]
Hello,
Quest works fine on PTR.
![image](https://user-images.githubusercontent.com/6797611/32620017-2d4277a8-c585-11e7-8846-48832cba37fc.png)
