### ISSUE TITLE
Cannot interact with "The sons of Hodir"

### ISSUE THREAD

**Issue by Bjoornevatn** [dalaranwow/dalaran-wow#5013]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: After a relogg I could not interact with "The sons of Hodir" now it is bugged so that I only can attack them. Tried to relogg and (/Reload). But for no good.
PS: I have done all the pre-quests so that I can actually do their quests.

**Expected behaviour**: Should be able to interact with them (Speaking, shopping, taking and delivering quests)

Regards

Brede Koppen

**Comment by AgeAgainst** [comment]
Not sure what causes it, but sometimes you can end up going back "at war" with Sons.  It is very common to hear people saying "I can only attack the Sons of Hodir npcs".

Press U to bring up your Reputation tab.  Scroll down to The Sons of Hodir, click on the name "The Sons of Hodir".  A window will pop up and you'll see 3 checkboxes.  At War (which I'm guessing for you has a pair of swords that are crossed as an X), Move to Inactive and Show as Experience Bar.  Click on the crossed swords and you should be able to interact with the quest NPCs again.
