### ISSUE TITLE
No northrend transport music

### ISSUE THREAD

**Issue by FireheartBDG** [dalaranwow/dalaran-wow#5018]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Regular zone music plays on the transport (zepplin/boat)

**Expected behaviour**: Walking onto the transport triggers this music: https://www.youtube.com/watch?v=dumZn8MrX6M

**Steps to reproduce the problem**:

1. Walk onto the transport
2. Experience disappointment

**Include proofs for this behaviour**
retail clip: https://www.youtube.com/watch?v=1UOYZ-eRtEs

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

http://www.wowhead.com/sound=14952/zone-northrentransportday
http://www.wowhead.com/sound=14953/zone-northrentransportnight
I included the night link but i dont remember it being used during night (or at all), maybe as a follow up after the first song plays but its been a while...

**Include Screenshots from the issue if necessary**

**Comment by Lothloryen** [comment]
Hello there,

Thank you so much for recalling me this with your report, I am really grateful, this is one of the things that I remember with a lot of affection from the WoTLK days. I have already implemented this and it will be active within next maintenance (less than 30 minutes).
