### ISSUE TITLE
[Naxxramas] Thaddius Casts Ball Lightning Once Before Becoming Attackable

### ISSUE THREAD

**Issue by datbunneh** [dalaranwow/dalaran-wow#5025]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Thaddius casts Ball Lightning once before becoming attackable. Potentially killing one of the raid members.

**Expected behaviour**: This mechanic should be triggered only when nobody is in melee range of boss.

**Steps to reproduce the problem**:

1. Kill Feugen and Stalagg and jump down to Thaddius platform.
2. Notice that he casts Ball Lightning before becoming attackable even if there are people in his melee range.

**Include proofs for this behaviour**

https://www.youtube.com/watch?v=L7YR3UPlec8&t=205

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

Thaddius - 15928
Ball Lightning - 52779, 59801, 64888, 64974

**Include Screenshots from the issue if necessary**

N/A

**Comment by Crispybuilt** [comment]
Issue addressed already in #1415

Will copy the path:
By Nikvet:
- *5.Ball Lightning is not properly scripted. Thaddius is casting Ball Lightning when his target is not in his melee range,no matter if there are other players in his melee range.Thaddius should only cast Ball Lightning when there is no one in his melee range including his target.If there are other players in his melee range,he should just move towards him.*

**Comment by datbunneh** [comment]
@Crispybuilt @Lothloryen I don't think that such huge reports are effective. It's better to decompose them onto separate issues and fix one by one according to severity and priority. Otherwise it's hardly ever going to be addressed because of its sheer size and most likely a bunch of points will be simply left unnoticed.
