### ISSUE TITLE
[Naxx] Combat bug after gluth

### ISSUE THREAD

**Issue by ashido96** [dalaranwow/dalaran-wow#5028]
After Gluth dies in Naxxramas the entire raid will be stuck in combat, the combat bug will persist after a full raid wipe as well if you fight any trash mob or boss as well. 

http://www.wowhead.com/npc=15932/gluth

**Comment by TeridanDW** [comment]
Hello @ashido96,
Steps to reproduce the issue here will be great, as I have tried to 2 characters in diffrent situations but couldn't get the combat state after boss is dead.

**Comment by Zarjofgt** [comment]
It seems to happen only after a decimate has occured.

**Comment by TeridanDW** [comment]
Thank you @Zarjofgt, think I found the issue:
 - Decimate seems to hit the triggers in the tunnel which can cause them to stay in combat with the raid (just guess).
![image](https://user-images.githubusercontent.com/6797611/32621480-9162372a-c588-11e7-96e6-7b9e6d7bee34.png)

**Comment by TeridanDW** [comment]
Works as intended on PTR.

**Comment by Lothloryen** [comment]
Hello there,

Trying a different approach, it should be on live realm with the next maintenance.

**Comment by Lothloryen** [comment]
It was already deployed - let me know if it still happens, please.

Thank you.

**Comment by datbunneh** [comment]
@Lothloryen Seems to not be fixed yet. Tested out in Naxxramas 10 today. I was out of the combat after the fight, but some raid members were still in. So after buffing the raid I've got combat too.

**Comment by Lothloryen** [comment]
Hello again, if you experience it again, write an ingame ticket, please, we have now some tools in order to try to identify the source of the combat bugs on real time.

**Comment by datbunneh** [comment]
@Lothloryen It's going to be tricky since GMs do not respond instantly and you can't really stop the raid for that. I'll try and will see what happens.

**Comment by Lothloryen** [comment]
Hello there,

Did it happened again lately?
