### ISSUE TITLE
[Quest] Bring 'Em Back Alive

### ISSUE THREAD

**Issue by robinsch** [dalaranwow/dalaran-wow#5029]
**Expected behaviour**: Tell us what should happen instead
Kodo's should have a Sprint ability on slot 1, hand in kodo spell should be on slot 2.
(http://www.wowhead.com/spell=45876/stampede)

When using the "hand in Kodo" spell you should exit the vehicle and say one random line.
The character should say it with a yellow text.
"One more beast saved from certain death!"
"The Scourge are no match for me, Torp!"
"Door-to-door kodo delivery!"
"Delivered as promised, Torp!"
"Here's your kodo, Torp!"

Farmer Torp should always reply:
"YES! It worked!"

When using the item on the Kodo a "emote" (/me) should appear:
"Infested Kodo Beast is cured!"

When using the item on the kodo the green aura should disappear.

The quest should have a 10 minute time limit.

**Include proofs for this behaviour**
https://www.youtube.com/watch?v=ZhmDRtQw8yI

**Comment by robinsch** [comment]
```sql
UPDATE `quest_template` SET `TimeAllowed` = 6000 WHERE `ID` = 11690;
```

**Comment by TeridanDW** [comment]
Hello,
I've been looking into this quest for the past hour or two and I saw few more missing or wrong things on PTR.
Here is the complete (in my mind fully blizzlike) version of this quest. Made from TC base + @robinsch's report + my additions in conditions and some visual improvements.
This is how it looks like now:
https://www.youtube.com/watch?v=heIVfzivJ7M&feature=youtu.be
