### ISSUE TITLE
[Quest] Magic Carpet Ride

### ISSUE THREAD

**Issue by robinsch** [dalaranwow/dalaran-wow#5030]
The quest should be auto completed. You don't have to ride the carpet to get the quest credit.

https://www.youtube.com/watch?v=cPfggtCt72I

**Comment by TeridanDW** [comment]
After few tests on  PTR:
 - Quest does get auto completed now but there are 2 issues with it:
1. Type of quest should not be this:
![image](https://user-images.githubusercontent.com/6797611/32701669-85792b2e-c7e2-11e7-9bd7-699c5adad5cb.png)

2. There isn't an option at Yanni to fly down:
![image](https://user-images.githubusercontent.com/6797611/32701681-a8a65b76-c7e2-11e7-8db1-0855a93fb663.png)
