### ISSUE TITLE
Jewelcrafters healing statues do not work.

### ISSUE THREAD

**Issue by Bjoornevatn** [dalaranwow/dalaran-wow#5034]
[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: The healing statues made by the (Jewelcrafter) Do not heal. It just run to the enemies and stands by them.

**Expected behaviour**: When summoned it should stay still and use it's powers to heal the caster until all it's powers are used up and it persists to exist.

**Steps to reproduce the problem**:

1. Use the golem
2. It runs to enemy (Not the caster)
3. Stands still

**Include proofs for this behaviour**

You can research this on several pages like http://wowhead.com or http://wowwiki.wikia.com or http://www.youtube.com/
Issues without proofs will be closed and tag On Hold will be added until the proof is provided.

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

You can research this on several pages like https://wowgaming.altervista.org/aowow/ or https://wowhead.com/

**Include Screenshots from the issue if necessary**

**Comment by TeridanDW** [comment]
Hello and thank you for the report @Bjoornevatn.
These statues + some more enginnering items should be fixed when #1294 is applied.
