### ISSUE TITLE
Warrior; Talent: Second Wind - Reprocs from damaging Roots (Entangling Roots).

### ISSUE THREAD

**Issue by Aridam** [dalaranwow/dalaran-wow#5036]
**Current behaviour**: Damaging Roots like Entangling Roots keep reproccing Second Wind with every tick in which they do Damage to the victim Warrior who has Second Wind -- basically every tick as if seems to perform a recheck on the Root application and thus refreshes Second Wind with each and every damaging tick; it's acting as though it's being _actually_ reapplied which it's not. I'm mentioning damaging Roots in general because of Entangling Roots and _all_ of its NPC variations seem to do so, thus it is likely that any ER-like Ability acting this way could cause the same bug.

**Expected behaviour**: Second Wind's supposed to proc only when being victim to Stun and Root _applications_.

**Steps to reproduce the problem**:

Make sure you have Second Wind.

1. Find a Mob that uses a variation of Entanging Roots or any similar damaging Root -- Players work as well (AKA the Druid for Player-cast Entanging Roots/Nature's Grasp);
2. Be victim to Entangling Roots (or any similar damaging Root that operates in that manner);
3. Wait for every tick while watching the SW Buff -- upon each and every damaging tick, SW gets refreshed as if you're actually getting the Root reapplied.

**Include proofs for this behaviour**

SW IDs:
https://wowgaming.altervista.org/aowow/?spell=29834
https://wowgaming.altervista.org/aowow/?spell=29838

Entangling Roots (Druid): https://wowgaming.altervista.org/aowow/?search=Entangling+Roots#abilities

Nature's Grasp (Druid): https://wowgaming.altervista.org/aowow/?search=Nature%27s+Grasp

Once again note that these links point to _Druids_ -- even Mobs' variations of Entangling Roots and such of the like cause this bug -- for example the Thistleshrub ones in Tanaris have a 15s-long ER that does the exact same thing; refer to other sources for finding their specific IDs and many more, as going out of the way to find each and every ID of every variation -- furthermore implying that it may not be _just_ ER but any other ER-esque Root under a different name acts this way, only broadens the already-seemingly-large list of affected damaging Roots that can refresh Second Wind.

Retail proof: https://www.youtube.com/watch?v=nD2stcm4W8M&feature=youtu.be&t=434 -- look at Nature's Grasp proccing the auto-ER; count the Debuff down as it ticks while looking at Second Wind and note how it's not being refreshed, unlike currently here.

**Comment by TeridanDW** [comment]
Hello and thank you for the report @Aridam.
Issue confirmed on PTR.
Check combat log:
![image](https://user-images.githubusercontent.com/6797611/32612298-95fed530-c570-11e7-8062-fef1e9f1694a.png)

**Comment by Aridam** [comment]
Posting here once more to update on the matter at hand: I was correct in my initial assumption of SW being bugged in that _any_ damaging Root may cause this.

Harold Lane's Bear Trap causes this bug as well, as it _too_ is a damaging Root -- it's a Bleed ticking every 2s for 10s total (https://wowgaming.altervista.org/aowow/?spell=53432).

This seems to confirm that _any and all_ damaging Roots refresh Second Wind's duration per tick of the inflicted Root.
