### ISSUE TITLE
Algalon down

### ISSUE THREAD

**Issue by lkrocek** [dalaranwow/dalaran-wow#5037]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

Algalon realm is down at least for 30mins now, but can connect to kirin tor.

Usually when it's down, it's up within 5mins. Something went wrong...

**Comment by fsironman** [comment]
OVH has/had a major outage

**Comment by lkrocek** [comment]
it is working now 👍
