### ISSUE TITLE
Reaching out to become developer here

### ISSUE THREAD

**Issue by Fapswhenoom** [dalaranwow/dalaran-wow#5039]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**:
After leaving the scene for about a year I have reacquired interest to develop for private servers again.

**Expected behaviour**: 
Someone contacts me for a chat on skype or discord.

**Steps to reproduce the problem**:
1.  Read this ticket
2.  Contact me
3. Free part-time developer
4. Better server :)

**Include proofs for this behaviour**
I was involved on another private server that has shut down due to bad management. 

The whole situation put me off bigtime, but after a year I feel I want to give developing/investing/spending time on a private server another go.

I have 3 years of professional experience as a test engineer (c/c++ field) and have been active for the past 2 years as a C#/C++ developer.

I have experience with Git, Jenkins, CMake, Visual Studio, C, C#, C++, python, JIRA, Agile software development, CI workflows and test automation.

Relevant for you guys: I was mostly involved in scripting Ulduar encounters and fixing bugs in the c++ code of the fork we used (mostly related to boss scripting - NOT DB work). I'm reasonably familiar with Trinity core development but my main view on all this is that software is software so my professional experience should translate well into potential work here.

I do not seek any form of compensation, I decided I am going to play here and I am merely offering free help with bugfixing. Had a look at the issue tracker and there are definitely a few things I could have a look at.

Anyways, 

Sorry for posting this here, I felt like the forums was not the ideal place to post this.

KR

**Comment by Crispybuilt** [comment]
Hello,
this is not the place where you post something like this. 
Kindly contact our administration by sending them an e-mail.
