### ISSUE TITLE
NPC: Forgotten Depths High Priest

### ISSUE THREAD

**Issue by Crispybuilt** [dalaranwow/dalaran-wow#504]
**NPC - Forgotten Depths High Priest** *(IDs: 30203, 30543, 31037)*

- **Issue present:** The creatures have visual bug with their weapon model I believe, instead of the top of the weapon, blue/white boxes are shown. I also believe this could be some sort of a effect / enchant around the weapon which has broken animation.

- **Possible fix** - it should be the best for now either to find a diferent weapon for the NPC or simply remove it. (The weapon looks simillar to the Staff from Pit of Saron - **Engraved Gargoyle Femur** *(ID:50273)*, but the cyan color instead of default blue. 

*Screenshots*:
![image](https://f.cloud.github.com/assets/5054924/942868/7290406e-01db-11e3-9a20-82f24159bf47.png)
![image](https://f.cloud.github.com/assets/5054924/942869/7a958576-01db-11e3-9bec-decf9619f795.png)
![image](https://f.cloud.github.com/assets/5054924/942871/b2fc1f42-01db-11e3-8cc8-58009dcfd3d1.png)

________________
http://www.wowwiki.com/Forgotten_Depths_High_Priest

**Comment by Rushor** [comment]
already fixed, there is no buggex weopon anymore http://i.imgur.com/8aK9GCq.jpg
