### ISSUE TITLE
General - Switching Weapons doesn't properly reset the Swing Timer.

### ISSUE THREAD

**Issue by Aridam** [dalaranwow/dalaran-wow#5041]
**Current behaviour**: Switching Weapons isn't resetting the Swing Timer to that of the corresponding Weapon properly.

**Expected behaviour**: When switching Weapons, the ongoing Swing Timer should immediately reset to the according currently-switched-to Weapon -- every single time, with every newly-equipped one.

**Steps to reproduce the problem**:

1. Have multiple Weapons -- can be of varying Attack Speeds, but doesn't really impact the end result of the testing (two weapons are pretty much enough);
2. Proceed to switch among all carried Weapons;
3. Take note of the time that passes inbetween each and every switch -- the Swing Timer isn't resetting properly at all (evident the most with slow Weapons).

**Comment by TeridanDW** [comment]
Hello and thank you for the report @Aridam.
Issue confirmed on PTR.
To clarify at the moment of weapon switch the swing timer is not reset with the new one (based on the speed of the new weapon), instead 1 more autoattack is been made with the old speed and then the new speed kicks in.

**Comment by Aridam** [comment]
That is precisely the explanation to what happens with the Swing Timer at the moment -- old ST is kept for the post-switch Auto-Attack each and every single time indeed.
