### ISSUE TITLE
''Turning Point'' Quest in Netherstorm

### ISSUE THREAD

**Issue by Mickekk** [dalaranwow/dalaran-wow#5044]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: I've picked up the quest ''Turning Point'' from ''Voren'thal the Seer'' in Shattrath City and I was provided with ''Voren'thal's Package''. When I've opened it, I received two items - ''Socrethar's Teleportation Stone'' and ''Voren'thal's Presence''. ''Socrethar's Teleportation Stone'' works normally when used, but when I try to use ''Voren'thal's Presence'' on ''Socrethar'' in order to make him vulnerable to attacks and spells, nothing happens. I abandoned the quest and retook it, but the result is the same.

**Expected behaviour**: When ''Voren'thal's Presence'' is used on ''Socrethar'' he should become vulnerable to player's attacks and spells.

**Steps to reproduce the problem**:

1. Pick up the quest from ''Voren'thal the Seer'' and receive ''Voren'thal's Package''.
2. Open ''Voren'thal's Package'' and receive ''Socrethar's Teleportation Stone'' and ''Voren'thal's Presence''
3. Using ''Socrethar's Teleportation Stone'' is optional, since I have flying mount, but when ''Voren'thal's Presence'' is used on ''Socrethar'' in order to make him vulnerable to attacks and spells, nothing happens.

**Include proofs for this behaviour**

http://www.wowhead.com/quest=10507/turning-point - URL for the quest
https://www.youtube.com/watch?v=HzY4yJirM8Q - Video that shows how ''Voren'thal's Presence'' works

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

http://www.wowhead.com/item=30259/vorenthals-presence - ''Voren'thal's Presence'' (doesn't work)
http://www.wowhead.com/npc=20132/socrethar - NPC on whom ''Voren'thal's Presence'' should be used.

**Include Screenshots from the issue if necessary**

**Comment by Lothloryen** [comment]
Hello there,

Thank you for your report, it has been corrected and the fix will be applied to the live realm with the next maintenance, which will be in 1-2 hours.

Regards.
