### ISSUE TITLE
[Mechanic] Sitting increases Health Regen more than it should.

### ISSUE THREAD

**Issue by Aridam** [dalaranwow/dalaran-wow#5048]
**Current behaviour**: Sitting is increasing Health Regeneration from Spirit by 50% -- as of now I have 33 HPR outside of Combat as a Warrior and sitting down increases it to 50 which is 50% flat increase.

**Expected behaviour**: Sitting should increase Health Regeneration from Spirit by 33% -- in my case as someone who has 33 HPR it should be 33 + 33% = 43.89 HPR ergo 44 HPR, _not_ 50.

**Steps to reproduce the problem**:

1. Check your Health Regeneration by hovering over your Spirit and checking how much HP you regenerate outside of Combat;
2. Stand up and wait -- take note of how much HPR you get; it's correct;
3. Now sit down and wait again -- take not of how much HPR you get this time; it's incorrect -- more than you should be getting.

http://wowwiki.wikia.com/wiki/Health_regeneration
http://wowwiki.wikia.com/wiki/Sit

**Comment by TeridanDW** [comment]
Hello, after few tests on PTR, here is my math:
![image](https://user-images.githubusercontent.com/6797611/32701578-19a3f2b8-c7e1-11e7-9271-f235bef7a674.png)

Standing:
36 hp per second - correct
Sitting:
55 hp per second - incorrect
Should be:
36*0.33 + 36 = 47,88 (but I get 55 hp regen ingame)

**Comment by Aridam** [comment]
The math is correct, yes -- 36 while standing, but amplified by 50% (result being this) while sitting, when it should be amplified by 33% which is the exact result you gave, ergo 48 in this case.
