### ISSUE TITLE
[Mechanic] Sitting does not result in getting a Crit.

### ISSUE THREAD

**Issue by Aridam** [dalaranwow/dalaran-wow#5050]
**Current behaviour**: If you're sitting down, the first Melee hit you get never changes into a sure-shot Crit.

**Expected behaviour**: If you're sitting down and something hits you in Melee, that hit should have a 100% chance to Crit on you.

**Steps to reproduce the problem**:

1. Sit down;
2. Have something or someone attack you in Melee;
3. Take note of how the first hit isn't a forced Crit before you're auto-stood up from it.

http://wowwiki.wikia.com/wiki/Sit

**Comment by urecheandu** [comment]
reckbombs have been fixed, so this is not a useful mechanic anymore. however it is a bug nonetheless.
I have tested it myself

**Comment by TeridanDW** [comment]
Hello, after few tests on PTR, the "forced" Crit doesn't happen.

![image](https://user-images.githubusercontent.com/6797611/32701499-e194fca6-c7df-11e7-9b31-95394b562305.png)
![image](https://user-images.githubusercontent.com/6797611/32701500-e8f243be-c7df-11e7-85ff-1ecc7cd2615c.png)

**Comment by Aridam** [comment]
Looks like it, yes -- no 100% Crit there upon the still-sitting victim.
