### ISSUE TITLE
[Quest] The Hero's Arms

### ISSUE THREAD

**Issue by Sprangle** [dalaranwow/dalaran-wow#5052]
Current behaviour: In this quest, you have to kill "Scion of Storm" in order to get the two items "Stormhoof's Mail" and "Stormhoof's Spear". There are in all 4 of the Scion of Storm, and one of them is unreachable, without certain conditions. Alongside that, the drop rate of these two items is insanely low.

Expected behaviour: There should be way more Scion of Storms to kill or a high boost to the drop chance of these items. The first solution would imitate the original quest in original WoW.

I've used about 2 hours trying to get the spear which hasn't dropped yet. This quest is needed to be done in order to progress since you won't get other quests until you've completed this one.

**Comment by Lothloryen** [comment]
Hello there, check it after the next maintenance (in about an hour), it should be better.

Thank you for your report.
