### ISSUE TITLE
[Quest] The Drakkensryd

### ISSUE THREAD

**Issue by Sprangle** [dalaranwow/dalaran-wow#5053]
Current behaviour: When accepting this quest you get to ride on a dragon which should take you to the place where the dragons but the "Hyldsmeet Drakerider" does not respawn on these dragons, and therefore the quest cannot be done. 

Expected behaviour: The rider should respawn on the back of the dragons. 

This quest is a key quest within a quest chain, so being unable to complete this quest, forces you to find another place to do some questing.

**Comment by Lothloryen** [comment]
#5051
