### ISSUE TITLE
My Character Stuck Under Map

### ISSUE THREAD

**Issue by Tennivan** [dalaranwow/dalaran-wow#5054]
Hello, My Character Got Stuck Under Map and I cant do anythink.
when I was in Dalaran I went to the portal to Orgrimmar and my game Crashed when I relog I spawned flying in Dalaran and I flyed automaticly to Orgrimmar under ground then I stoped in the Middle of the The Great Sea and stuck I am ,,Falling'' I cant mount or Auto Unstuck so I don't know what I need to do can someone help me?
Server Sylvanas Tennivan Demon Hunter 110.

Sorry About English.

**Comment by Lothloryen** [comment]
Hello there, I believe your report does not belong here. You should open an ingame ticket and ask for GM help.

Regards.
