### ISSUE TITLE
Druid Relic "Idol Of Lush Moss" Not Working Correctly

### ISSUE THREAD

**Issue by kaciko** [dalaranwow/dalaran-wow#5056]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: 
The Emblem of Justice druid relic "Idol of Lush Moss" not working as intended. Without the relic on, the tooltip of LB rank-3 shows 441heatlh/9sec. With the Relic on, the tooltip correctly becomes:
441+125=588/9sec (with talents coefficient included).

With one stack of LB rank-3, the extra healing per tick should be:
-initial LB heal 441/9sec=49hps
-LB heal with relic on:for 588/9sec=65.3hps
The difference is 65.3-49=~16hps PER STACK of lifebloom.
However, the actual HPS remains the same ~ ~16hps extra healing, regardless of the LB stacks (1,2,3).

**Expected behaviour**: 
Obviously, the LB heal should increase ~16hps per LB stack.
1LB stack = ~16hps more
2LB Stacks = ~32hps more
3LB stacks = ~48hps more

**Steps to reproduce the problem**:
Use a druid, cast and monitor HPS for 1x LB, 2xLB and 3xLB
Repeat WITH the "Idol of Lush Moss"
Notice only ~16hps is added.

**Comment by TeridanDW** [comment]
Hello and thank you for the report @kaciko.
Issue confirmed on PTR, also math is right.
