### ISSUE TITLE
Quest: Ursoc, the Bear God / NPC: Hierophant Thayreen

### ISSUE THREAD

**Issue by Crispybuilt** [dalaranwow/dalaran-wow#5057]
**Issue present:**
- Sometimes Hierophant Thayreen *(27295)* wouldn't offer the final quest of the chain to Alliance players even though they have completed the previous quests in the chain.

**How it should work:**
- NPC should always offer the quest to players once the entire chain is completed.

Quest ID: 12249
NPC ID: 27295

-------

Reminder

**Comment by Lothloryen** [comment]
Hello there,

Thank you for the report / reminder. Did few checks and the quest is properly being offered after the player has completed http://www.wowhead.com/quest=12248/vordrassils-sapling and http://www.wowhead.com/quest=12250/vordrassils-seeds

Closing this, if anyone else experiences any issue even after completing such quests, feedback would be appreciated so we can do further checks.

Thank you very much.

**Comment by ShiroNoHikage** [comment]
I'm having the same issue, but i'm sure i completed the quests "Vordrassil's sapling" and "Vordrassil's seed". My character is Bellmont, Alliance's DK on Algalon.

**Comment by Crispybuilt** [comment]
Will re-search on PTR how exactly is the issue reproduced. 
- (Possible re-log)
- (Phase issue in some different area)
- (Live Server Crash while on a quest, mid quest chain)
- (Another quest interfering with this chain)

**Comment by Crispybuilt** [comment]
Quest progression for **HORDE**:
Horde 15 [74] Vordrassil's Fall & Horde 15 [74] The Darkness Beneath
Horde 15 [75] The Bear God's Offspring & Horde 15 [74] A Possible Link
Horde 15 [74] Vordrassil's Seeds & Horde 15 [75] Destroy the Sapling
Horde 15 [75G] Ursoc, the Bear God

Quest progression for the **ALLIANCE**
Alliance 15 [74] The Failed World Tree & Alliance 15 [74] A Dark Influence
Alliance 15 [74] A Possible Link & Alliance 15 [75] Children of Ursoc
Alliance 15 [75] Vordrassil's Sapling & Alliance 15 [75] Vordrassil's Seeds
Alliance 15 [75G3] Ursoc, the Bear God

@ShiroNoHikage Is your character on Alliance or Horde?:

**Comment by ShiroNoHikage** [comment]
@Crispybuilt my character is an Alliance one, a Death Knight named Belmont.
I'm sure I completed all the pre-quests (at least I reached the two last ones).
I've discussed on the chat with other players, many of them have got the issue too, and completed the quest only after a GM forced the quest in their quest log.

**Comment by Crispybuilt** [comment]
Re-opening then this issue, thank you Shiro,

**Comment by Lothloryen** [comment]
Hello again,

You are totally right. Did few checks and indeed, you have properly done the whole chaining. I have researched thoroughly and found the issue that was causing this problem, it will be fixed with the next maintenance.

Thank you for your report.

**Comment by Mistarodub** [comment]
"Quest progression for HORDE:
Horde 15 [74] Vordrassil's Fall & Horde 15 [74] The Darkness Beneath
Horde 15 [75] The Bear God's Offspring & Horde 15 [74] A Possible Link
Horde 15 [74] Vordrassil's Seeds & Horde 15 [75] Destroy the Sapling
Horde 15 [75G] Ursoc, the Bear God"
Finished "Attack on Silverbrook" quest just now, which has to be prerequisite for Horde 15 [74] Vordrassil's Fall & Horde 15 [74] The Darkness Beneath from NPC "Windseer Grayhorn", but they're not there - Windseer offers me only 5 out of 7 quests (8th is "Ursoc, the Bear God", which I don't have access to yet).
