### ISSUE TITLE
Warrior: Slam - Swing Timer not paused during Slam casts.

### ISSUE THREAD

**Issue by Aridam** [dalaranwow/dalaran-wow#5058]
**Current behaviour**: While Slam is being cast, the ongoing Swing Timer isn't being paused, but instead keeps ticking away.

**Expected behaviour**: Casting Slam should pause the Swing Timer for as long as the cast is going.

**Steps to reproduce the problem**:

1. Learn Slam;
2. Begin casting this Ability;
3. Track your Swing Timer -- a way to do that is using the addon Quartz for its Swing function to display a bar for your Swing Timer; note how you proceed to swing earlier than you should, thus, the Swing Timer isn't put on hold during any Slam casts, be it 1.5s, or 1/0.5s in case of the Improved Slam Talent.

**Include proofs for this behaviour**

http://wowwiki.wikia.com/wiki/Slam -- specifically "Patch 3.0.2 (14-Oct-2008): Slam now suspends the weapon swing timer rather than resetting it."

List of Slam IDs: https://wowgaming.altervista.org/aowow/?search=Slam#abilities (scroll down to the one that says just "Slam" and has 8 Ranks total).

Improved Slam IDs (just in case): https://wowgaming.altervista.org/aowow/?search=Slam#talents

**Comment by TeridanDW** [comment]
Hello and thank you for the report @Aridam.
Issue confirmed on PTR
![wowscrnshot_112217_153956](https://user-images.githubusercontent.com/6797611/33130297-889e4eea-cf9b-11e7-8ad5-d20d71f44647.jpg)
![wowscrnshot_112217_153958](https://user-images.githubusercontent.com/6797611/33130303-8c4f2348-cf9b-11e7-8bdd-c44e6ea6e989.jpg)
