### ISSUE TITLE
Warrior; Talents: Sweeping Strikes - Cleave now does not consume the intended amount of charges.

### ISSUE THREAD

**Issue by Aridam** [dalaranwow/dalaran-wow#5060]
**Current behaviour**: Cleave consumes only one charge of Sweeping Strikes per usage.

**Expected behaviour**: Cleave is supposed to consume Sweeping Strikes charges by the amount of Targets it hits.

This used to work up until a day ago (max two), but it seems I suppose a recent restart to apply fixes has caused a side-effect and this is now bugged-out and applies only one SS proc as opposed to two if using normal Cleave or three if using the Glyph of Cleaving.

**Steps to reproduce the problem**:

1. Use Sweeping Strikes;
2. Use Cleave on two Targets (three if using the Glyph of Cleaving);
3. Notice how SS procs only once from Cleave instead of 2/3 times.

Cleave IDs: https://wowgaming.altervista.org/aowow/?search=Cleave#abilities (only with the "Warrior" tag)
SS ID: https://wowgaming.altervista.org/aowow/?spell=12328
Glyph of Cleaving ID (don't know why but just in case to be sure): https://wowgaming.altervista.org/aowow/?item=43414

**Comment by TeridanDW** [comment]
Hello, I would like to for a proof here as it doesnt make sence to me if this report is valid so #5014 sholdn't be.

**Comment by Aridam** [comment]
Just rifled through all the patches as seen in http://wowwiki.wikia.com/wiki/Patches up to 3.3.5a for matches for Cleave and Sweeping Strikes -- nothing found in them.

However, when searching for Sweeping Strikes being combined with Cleave, results are mixed -- some say it works, some don't, to the point it seems as though people don't know what they're talking about; might have to resort to finding video proof, which as many know, Arms PvE Warriors in Wrath are hardly-played and even less-so recorded, and in PvP, few Warriors use HS/Cleave to begin with, and they only use SS with the same mindset as that, unless free due to the Glyph for it -- gonna be a doozy.

Just in case, putting the various sources pointing towards this working.

http://www.wowhead.com/forums&topic=49313&p=489556 -- old Wrath (2008, presumably patch 3.0.2, which mentions nothing of Cleave + Sweeping Strikes in any way).

https://www.gamefaqs.com/boards/534914-world-of-warcraft/41711618 -- note how this seems biased because of the mention of Whirlwind which as shown and already-known had been previously-patched to consume one stack of SS per _usage_ rather than per _Target_, so this sounds like a suspicious mixed bag.

There are also other sources, but from private servers where people imply Cleave procs SS twice/thrice, and they're Vanilla/BC, and considering I've just rifled-through all the pre-Cataclysm patchnotes and saw nothing, it can't be sure whether that _is_ indeed intended; it seems it was done post-WotLK as there are some Cataclysm-time posts on official Blizzard forums and so forth.

This is pretty-much up in the air -- gonna need video proof, and preferably, WotLK-time; the patchnotes contain many holes and are missing changes and even hotfixes, so we can't be sure until some solid and naturally, difficult-to-find proof is found and provided here.

**Comment by Aridam** [comment]
https://hilbert.wordpress.com/sweeping-strikes-guide/ -- dates back to Vanilla it seems -- most of the information is now-invalid or altered for WotLK, but there are interesting link-ups with Cleave that can relate to the previous massive wall just above this; check the parts specifically-mentioning Cleave.

Also checking for Sweeping Strikes + Cleave, the macro:

/cast Sweeping Strikes
/cast Cleave

would show a lot -- not sure what to make of that to help.

**Comment by Aridam** [comment]
Coming back to reconfirm:

http://www.wowhead.com/forums&topic=49313&p=489556
https://gamefaqs.gamespot.com/boards/534914-world-of-warcraft/53799587

Also currently Sweeping Strikes has two charges expended on successful Cleaves already so I guess it got reverted a while after this report?

Either way, it's intended.
