### ISSUE TITLE
Halls of reflection early boss agrro

### ISSUE THREAD

**Issue by Kennehsauce** [dalaranwow/dalaran-wow#5061]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
Halls of Reflection bosses, Falric, Marwyn, aggroing before proper wave. Hunter explosive trap hits boss causing aggro.
**Expected behaviour**: Tell us what should happen instead
Should not aggro before wave 5 or 10.
**Steps to reproduce the problem**:

1. Hunter places Explosive trap near boss
2. Trap is sprung by mob
3. Trap hits boss causing them to aggro earlier than intended

**Include proofs for this behaviour**
https://imgur.com/tbIbGlv

**Comment by Zarjofgt** [comment]
Not an issue with HoR, but the explosive trap. It hits friendly players, invisible world triggers and pretty much anything.

**Comment by TeridanDW** [comment]
This:

> Not an issue with HoR, but the explosive trap. It hits friendly players, invisible world triggers and pretty much anything.
