### ISSUE TITLE
[Mechanic] Can Mount-up via Ground Mounts in the water.

### ISSUE THREAD

**Issue by Aridam** [dalaranwow/dalaran-wow#5067]
**Current behaviour**: You can cast Ground Mounts while in the water.

**Expected behaviour**: Like other basic actions (Flying Mounts, Food, Drink), summoning a Ground Mount should also be prohibited if you're in the water.

**Steps to reproduce the problem**:

1. Go in any water;
2. Use a Ground Mount -- works; not supposed to.

**Comment by Rushor** [comment]
in deep water or only in water?

**Comment by Rushor** [comment]
nope this behaviour is intended https://github.com/TrinityCore/TrinityCore/pull/17488

proof here : https://www.youtube.com/watch?v=FlGxBOs2YTw&feature=youtu.be&t=22

If you find a proof from patch 3.3.5 that shows that you were not allowed to mount in water, please post the link and we will change it. thanks.

**Comment by Aridam** [comment]
Point taken -- will keep in mind.
