### ISSUE TITLE
[Quest][Northrend] When all else fail

### ISSUE THREAD

**Issue by styled81** [dalaranwow/dalaran-wow#5071]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
Storm peaks. NPC Ricket at K3. After accepting this quest you have to speak witk Ricket again, click on the gossip"Im ready to head further into storm peaks", she wil put you on a rocket and send you away.

**Expected behaviour**: Tell us what should happen instead
After accepting this quest i can click on the gossip but nothing happens. You wont be transported to the next village

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Include proofs for this behaviour**

You can research this on several pages like http://wowhead.com or http://wowwiki.wikia.com or http://www.youtube.com/

https://www.youtube.com/watch?v=EmW_72zioB8

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

Ricket at K3 in stormpeaks

You can research this on several pages like https://wowgaming.altervista.org/aowow/ or https://wowhead.com/

**Include Screenshots from the issue if necessary**

**Comment by sebastienwood** [comment]
Also happen on Kirin Tor

**Comment by Rushor** [comment]
https://wowgaming.altervista.org/aowow/?search=When+all+else+fail
