### ISSUE TITLE
Gunship 10n - Wipe bugs the instance

### ISSUE THREAD

**Issue by sebastienwood** [dalaranwow/dalaran-wow#5072]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
When you suffer from a wipe in the Gunship fight (Icecrown Citadel), the 2nd try usually make the instance bug. All the raid is in the air and you can just watch the fight and wait to die. It seems that the allied ship can't make it to its battle position.

**Expected behaviour**: Tell us what should happen instead
The fight should not bug after a wipe.

**Steps to reproduce the problem**: (we did try this 2 time on 2 different weeks to be sure)
1. Try and wipe on first try on Gunship
2. Get back and try again
3. Optionnal - Strange enough, all tries after the bug doesn't seems to bug.

**Include proofs for this behaviour**
-> Not relevant

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

Skybreaker 
- Entry ID: 192242 or 12345001 
- Display ID: 8254

Orgrim's Hammer 
- Entry ID: 192241 or 12345000
- Display ID: 8253

**Include Screenshots from the issue if necessary**

Nota : it happens on Kirin Tor server

**Comment by Crispybuilt** [comment]
**Kirin Tor**

------------

**Comment by sebastienwood** [comment]
How should I bug report for Kirin Tor for it to be valid ?
Thanks,

**Comment by Crispybuilt** [comment]
Thank you very much for your report, we appreciate it. Bug Tracker is primarily used for Algalon (which is our Main Realm).
You can always toss a report here, but it will be marked as duplicated/invalid. 
I'm sorry about that.
