### ISSUE TITLE
[Kirin Tor][Mechanic] Damage when landing from flying mount

### ISSUE THREAD

**Issue by sebastienwood** [dalaranwow/dalaran-wow#5073]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
When you land with your flying mount, if you don't wait for a few seconds before dismounting you'll receive heavy damages from "falling".

**Expected behaviour**: Tell us what should happen instead
The fall damage should take into account the height at which we dismount.

**Steps to reproduce the problem**: (happened across multiple characters quite frequently)

1. Fly high
2. Go down real fast and dismount real quick (like if you were farming for exemple)
3. Check damage received

**Include proofs for this behaviour**
-> not relevant

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**
-> not relevant

**Include Screenshots from the issue if necessary**

**Comment by Rushor** [comment]
Kirin Tor is outdated concerning specific fixes.

On PTR this should already work since that fix (https://github.com/TrinityCore/TrinityCore/commit/fcbbc60b93625211d958431461345fede9dcbe46) was applied already
