### ISSUE TITLE
some achiwments and title 

### ISSUE THREAD

**Issue by Ethernal0** [dalaranwow/dalaran-wow#5078]
Some achiwments and Title 
--
We cant do ach for title Chef, cuz some Rbg are locked to use Great feast , so will u fix that ?

**Comment by TeridanDW** [comment]
Nothing to fix, achievement will be avaliable when the battleground is.

**Comment by Ethernal0** [comment]
i wasn't searching to fix something , i wanted to ask can i have
achievement even i havn't finish all ,,, i know u can do it ?

2017-11-21 16:58 GMT+01:00 Teridan <notifications@github.com>:

**Comment by Chenocide** [comment]
They either can't or won't give out achievements. Wait for the BG to come out.
