### ISSUE TITLE
Chimera disarm on another hunter

### ISSUE THREAD

**Issue by Johanes022** [dalaranwow/dalaran-wow#5082]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: When you use chimera shot with Scorpid sting up on another hunter it doesnt disarm ranged weapon on hunter.Bars show that you cant shoot arrows (they gray out) but you actualy still can as normal.And its only hunter-on-hunter situation.Warrior and rogue disarm work fine when used on hunter as well as chimera disarm on warrior and rogue.

**Expected behaviour**: Chimera shot should disarm ranged weapon too when used in combination with scorpid sting.
**Steps to reproduce the problem**:

1. as hunter duel another hunter
2. apply scorpid sting  than use chimera shot to disarm hunter
3. switch to "disarmed" hunter and try to shoot auto attack/special abilities

**Comment by TeridanDW** [comment]
Hello and thank you for the report @Johanes022.
Issue confirmed on PTR with 1 clarification that the target of Chimera shot (with scorpid sting on it) doesn't need to be hunter the effect just doesn't disarm ranged slot in general.

**Comment by robinsch** [comment]
It clearly states for me that it should only disarm main hand weapon. 

Aura Id 67 (SPELL_AURA_MOD_DISARM)

otherwise it would be SPELL_AURA_MOD_DISARM_RANGED.

I will close this until a video from retail is provided.
