### ISSUE TITLE
[Vanilla][Reputation] Steamwheedle Cartel

### ISSUE THREAD

**Issue by Tziva** [dalaranwow/dalaran-wow#5083]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: 
Since the issue #4809 was closed without any proof, I'm addressing it anew. Upon reaching certain reputation status with the Steamwheedle Cartel, it is impossible to lower those reputations by killing Booty Bay Bruisers. Instead, only Bloodsail Buccaneer reputation goes up.

**Expected behaviour**:
By killing Booty Bay Bruisers, the reputation with all 4 goblin cities should go down, regardless of your status with them.

**Steps to reproduce the problem**:

1. Get revered with Steamwheedle Cartel
2. Kill a Booty Bay Bruiser
3. Observe that only Bloodsail Buccaneer reputation rises.

**Include proofs for this behaviour** "Each Bruiser killed rewards y reputation with Bloodsail Buccaneers, subtracts 2x reputation from Booty Bay, and subtracts x reputation with Everlook, Gadgetzan, and Rachet." taken from https://wow.spectralcoding.com/insane/

You can research this on several pages like http://wowhead.com or http://wowwiki.wikia.com or http://www.youtube.com/

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**
Booty Bay Bruiser -> 4624

You can research this on several pages like https://wowgaming.altervista.org/aowow/ or https://wowhead.com/

**Include Screenshots from the issue if necessary**
![wowscrnshot_111517_030815](https://user-images.githubusercontent.com/33547662/32813577-a8a84210-c9b3-11e7-937a-fd9ed41e2ee7.jpg)
![wowscrnshot_111517_031653](https://user-images.githubusercontent.com/33547662/32813583-affb8c7a-c9b3-11e7-9476-1806f96a2ae3.jpg)

**Comment by TeridanDW** [comment]
Hello and thank you for the report @Tziva.
Issue confirmed at PTR.
![image](https://user-images.githubusercontent.com/6797611/33127161-080b1e9e-cf90-11e7-934c-59e10c0c6714.png)

Thank you for mentioning this:

> Get revered with Steamwheedle Cartel

it made all the diffrence.

**Comment by TeridanDW** [comment]
Possible fix added, should be tested on PTR.
