### ISSUE TITLE
Quest ''Mutiny on the Mercy''

### ISSUE THREAD

**Issue by Mickekk** [dalaranwow/dalaran-wow#5086]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**:
Only one ''Mutinous Sea Dog'' spawned. No respawns at all, after one hour. Thus, the ''I've Toured the Fjord'' achievement isn't attainable without this quest chain.

Boat on which the quest is done is having some more bugs.
1. My pet disappears on the boat.
2. I am able to use mount in the closed areas of the ship,

**Expected behaviour**:
There should be a lot of these NPCs under the deck with 2 minutes respawn time.

**Steps to reproduce the problem**:

1. Pick up a quest from ''Captain Ellis''
2. Kill one ''Mutinous Sea Dog''
3. No more NPCs to kill

**Include proofs for this behaviour**

http://www.wowhead.com/npc=25026/mutinous-sea-dog - Ship has to have a lot of these NPCs under the deck.

In order to drop - http://www.wowhead.com/item=34387/barrel-of-blasting-powder

Video - https://www.youtube.com/watch?v=qHPzdao_zIk

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

You can research this on several pages like https://wowgaming.altervista.org/aowow/ or https://wowhead.com/

**Include Screenshots from the issue if necessary**

**Comment by Mickekk** [comment]
It appears that all of them are stuck on small glacier in the water.

**Comment by TeridanDW** [comment]
Duplicate with #457
