### ISSUE TITLE
Auchindoun : Sethekk Halls (heroic) ID extension

### ISSUE THREAD

**Issue by Aetharon** [dalaranwow/dalaran-wow#5088]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
As referenced in issues  #3730, #3104, #1866, #2969 and #5045 over the past two years, the ID lockout for Sethekk Halls on heroic mode extends itself for various periods of time. The cause seems yet unclear, partly because it might be a fault of coding rather than gameplay. What I am asking for, on behalf of those that have had this issue over time, is merely what the game is supposed to give. There have been fixes to prevent abuse and it is quite frustrating to see that some of us have to deal with this problem still.

I have noticed one thing the day the last set of fixes added the proper behaviour on the Anzu encounter.
That day, the animation was not successful, as I mentioned in #5045, thus Anzu was not summoned. However, the ID lockout persisted to the following day. Again, a part of this issue. After the encounter was finally fixed the following day, I was able to summon Anzu on the lockout of the previous day.
It would seem that the persistent lockout issue has to do with the other bosses that lock you to the dungeon. I do kill Darkweaver Syth and Talon King Ikiss when I proceed through the dungeon.

**Expected behaviour**: Tell us what should happen instead
Any heroic dungeon ID should refresh at 04:59 server time. There should be no exception.

**Steps to reproduce the problem**:

1. Enter Auchindoun: Sethekk Halls on heroic mode
2. Proceed through the dungeon
3. Observe the ID lockout not refreshing for days in a row

**Include proofs for this behaviour**
Issues #3730, #3104, #1866, #2969 and #5045.

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**
https://wotlk.evowow.com/?npc=23035 - Anzu
https://wotlk.evowow.com/?npc=18473 - Talon King Ikiss
https://wotlk.evowow.com/?npc=18472 - Darkweaver Syth

**Comment by Aetharon** [comment]
The issue persists, yet again. Can there be an explanation, please? What was meant to be a daily chance turned into a weekly chance and it is remarkably frustrating to see no reaction.

**Comment by Aetharon** [comment]
After being once again locked for several days on the same ID, I have proceeded once more through the dungeon. After killing Talon King Ikiss, the gate once again did not open, as referenced in issue #5045. I strongly expect the lockout to extend once more, since no answer of any kind was provided regarding this.

**Comment by Aetharon** [comment]
Frustratingly enough, I anticipated correctly. The ID of the previous day's run has extended once again. I would enjoy knowing that this issue is acknowledged, at least. It seems to have been ignored all this time, blatantly and unresponsively.

**Comment by robinsch** [comment]
@Lothloryen Could my change be pushed on live for a test?

**Comment by Lothloryen** [comment]
Yes, included it for the next maintenance already.

Thank you.

**Comment by robinsch** [comment]
Ref: https://github.com/dalaranwow/dalaran-wow/issues/5045#issuecomment-347834468
