### ISSUE TITLE
[Quest][Northrend] Fervor of the Frostborn

### ISSUE THREAD

**Issue by Sagrath** [dalaranwow/dalaran-wow#509]
The gossip menu option of the npc "Fjorlin Frostbrow" which is necessary to select from in order to be able to advance through the quest, is missing.
This gossip menu option supposed to trigger an event which the player mount a "stromcrest Eagle" and continue through the quest.
Only after the player rides the Stormcrest Eagle, it's possible to find the "Battered Storm Hammer". 
If this quest would have been working properly, the gossip menu option was visible and available for select which is not the case now.

quest link: http://www.wowhead.com/quest=12874
"Fjorlin Frostbrow" link: http://old.wowhead.com/npc=29732
"Stormcrest Eagle" link: http://www.wowhead.com/npc=29854
"The Iron Watcher" link: http://old.wowhead.com/npc=30142

**Comment by Mantigora** [comment]
confirmed.
Gossip menu option of the npc "Fjorlin Frostbrow" which is necessary to select from in order to be able to advance through the quest, is missing.
Flying to event location with mount we see that npc and object is not spawned.

**Comment by Rushor** [comment]
http://i.imgur.com/w3c4qae.jpg http://i.imgur.com/cgSAUal.jpg flying event is fixed

**Comment by Rushor** [comment]
http://i.imgur.com/Sgd9ecf.jpg http://i.imgur.com/ocL6pyj.jpg

creature can also be killed - only thing which needs to be fixed here is to increase the speed of the flying eagle a bit (it's really slow currently)

vehiclespeed increased a bit

**Comment by Golganeth** [comment]
Flying event works great,

The vehicle is still a bit too slow, should be faster.

For reference;
https://www.youtube.com/watch?v=iTfV9tY7gCQ

**Comment by Rushor** [comment]
should be around 3 minutes now
