### ISSUE TITLE
Quest: Captain's Cutlass (ID: 615)

### ISSUE THREAD

**Issue by Puzzola** [dalaranwow/dalaran-wow#5091]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: 
"The Captain's Cutlass" quest is not available, even after finishing "The Monogrammed Sash" quest.

**Expected behaviour**:
I should be able to get the quest from Captain Hecklebury Smotts but i'm not.

QUEST ID: 615

**Comment by TeridanDW** [comment]
Hello and thank you for the report @Puzzola.
Quest 615 shouldn't be avaliable to you. You can look here:
https://wowgaming.altervista.org/aowow/?search=The+Captain%27s+Cutlass
Instead https://wowgaming.altervista.org/aowow/?quest=8553 should be.

**Comment by Puzzola** [comment]
Thank you @TeridanDW.
The right quest number is 8553 and not 615 but the problem persists.

**Comment by TeridanDW** [comment]
Alright, issue is indeed valid.
Quest https://wowgaming.altervista.org/aowow/?quest=8553 is not offered.
![untitled](https://user-images.githubusercontent.com/6797611/33146409-b4566c4e-cfcc-11e7-820f-eb2c00d54263.png)

Will look in to the issue.

**Comment by TeridanDW** [comment]
Issue should be fixed, but needs to be tested on PTR first.
