### ISSUE TITLE
[NPC] High Priest Talet-Kha spamming Renew.

### ISSUE THREAD

**Issue by Aridam** [dalaranwow/dalaran-wow#5094]
**Current behaviour**: The NPC in Borean Tundra's Temple City of En'kilah called High priest Talet-Kha spams Renew when brought down enough.

**Expected behaviour**: Shouldn't spam Renew but just cast it once when they're forced to do so.

**Steps to reproduce the problem**:

1. Get to the Spire of Pain located in the Temple City of En'kilah, the Borean Tundra;
2. Kill the Mobs inside to make the High Priest attackable;
3. Bring him down enough to force him to cast Renew -- notice it's being spammed multiple times in the same second, rather than only used once when that happens.

**Include proofs for this behaviour**

Talet-Kha's ID: https://wowgaming.altervista.org/aowow/?npc=26073

**Comment by TeridanDW** [comment]
Hello and thank you for the report @Aridam.
Issue confirmed on PTR.
![image](https://user-images.githubusercontent.com/6797611/33122784-dae8e8ce-cf80-11e7-9e33-0fc102eaef2d.png)

I would also like to add 2 missing details here:
 - While the creature is inactive it's name should not be visible, in other words creature should be untargeatble
Add unit_flags=33554432

![image](https://user-images.githubusercontent.com/6797611/33122993-82b59aa2-cf81-11e7-90f8-351252fac252.png)

 - While the creature is inactive it should be a flying and lose that on engage.

Proof for both of these can be seen here (at 0:30s):
https://www.youtube.com/watch?v=vHF2eqIJtBA

**Comment by Aridam** [comment]
Right -- supposed to be untargetable and slightly-hovering as well indeed.
