### ISSUE TITLE
API

### ISSUE THREAD

**Issue by lkrocek** [dalaranwow/dalaran-wow#5097]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

Hello, I would like to provide my guild members at least some information out of game, is possible to make some API at least for reading? My idea ... 
public: armory, achievements
private(can be hosted on dalaran site from security reasons): guild chat, calendar

I can do it at my own but at least need provide these data ...

**Comment by Chenocide** [comment]
I doubt you would ever get anything like this. Dal-wow can't even change the default realm for the website to Algalon, so I really doubt they would ever get around to making something like this. Personally I would be happy if they implemented Armory but I don't think they have the time and resources.

**Comment by TeridanDW** [comment]
Hello,
Please continue the subject on the forums, bugtracker is only for ingame issues.
