### ISSUE TITLE
Midnight does not reset hp and provide no loot

### ISSUE THREAD

**Issue by lkrocek** [dalaranwow/dalaran-wow#5098]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Algalon**

**Current behaviour**: First boss of Karazhan, Midnight in second phase, when the horse and horseman is merged, the HP of boss is not resets and after kill it provides no loot, so we are not able to get a mount from boss. It happened 2 last raid resets.

**Expected behaviour**: After merge rider and horse it should reset HP to full and provide a loot after kill.

**Comment by TeridanDW** [comment]
Hello and thank you for the report @lkrocek.
I tried to reproduce this issue on PTR but I couldn't. Can you provide any steps or hints, did you do something special for this to happen?
I tried to "kill" the horse first but they merged with the rider at low hp and they did reset to full hp, same think with rider first as target.
![image](https://user-images.githubusercontent.com/6797611/33121416-56c4886c-cf7d-11e7-8586-131cfb7d6fad.png)
![image](https://user-images.githubusercontent.com/6797611/33121462-81a8fc66-cf7d-11e7-8433-5c7af125ecdb.png)
![image](https://user-images.githubusercontent.com/6797611/33121480-8b463234-cf7d-11e7-8561-a501c05a7033.png)

For now closing, if any additional information comes up will review again.

**Comment by lkrocek** [comment]
We were damaging horseman first instead of horse before merge, I think this is the important point here.

We were 2 guys there, tank and healer (both 80lvls).

To prevent charges and damage to healer, healer was standing up on wagon with hay visible on your screenshots.
