### ISSUE TITLE
Reset time value for macro /castsequence does not work properly

### ISSUE THREAD

**Issue by lkrocek** [dalaranwow/dalaran-wow#5099]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: I did simple macro for my warrior for sequence Whirlwind(8s CD) -> bloodthirst(4s CD) -> bloodthirst(4s CD). Whirlwind is for me most important, so whenever I will do a delay I want to reset it. So I did /castsequence reset=8 ..., but the reset=8 isn't 8 seconds! sometimes it take 10 seconds sometimes it take 15 seconds. I don't see there any value when it resets, it's really random but bigger value.

**Expected behaviour**: /castsequence reset=8 should reset after 8 seconds.

**Comment by TeridanDW** [comment]
Hello @lkrocek, macros are client side stuff and in this case the 8 sesc will be valid only if you don't spam click it (1 click wait 8 secs).
