### ISSUE TITLE
NPC: Warbringer Goredrak - Spawnpoint slightly-off.

### ISSUE THREAD

**Issue by Aridam** [dalaranwow/dalaran-wow#5102]
**Current behaviour**: Very-minor miscalculation at the moment: Warbringer Goredrak within Coldarra in the Borean Tundra is spawned a bit off from the circular pedestal(?) he's supposed to be on.

**Expected behaviour**: He's supposed to be right in the middle of that spot.

**Steps to reproduce the problem**:

1. Go to Coldarra, the Borean Tundra;
2. Approximately closely south-west of the center/The Nexus, look for the Warbringer;
3. Check the location -- he's just a bit to the south of the pedestal itself instead of right in the middle of it.

**Include proofs for this behaviour**

https://s18.postimg.org/dm4ablcq1/Wo_WScrn_Shot_112217_050152.jpg

Again, this is incredibly-minor and nothing special as he's basically right next to his intended spawnpoint -- just figured I'd report this as a miscellaneous thing to look into in the background.

**Comment by mayras321** [comment]
how do I repot a bug thay keep deleting my post I cant get where I can type on line 1.2.3. 
it just sends me to some formats that says if I remve it thay will close my thang

**Comment by TeridanDW** [comment]
Hello and thank you for the report @Aridam.
A lot of rework was done for almost all creatures in Coldarra in #4576 but I haven't changed the position of Warbringer there, so I will do it in this report.

**Comment by TeridanDW** [comment]
How it looks like now:
![image](https://user-images.githubusercontent.com/6797611/33117156-0eb63a78-cf70-11e7-8456-d8fe9335822a.png)

**Comment by Aridam** [comment]
Looks precise to me.
