### ISSUE TITLE
[Rare Mob] Loque' Nahak

### ISSUE THREAD

**Issue by alexuktc** [dalaranwow/dalaran-wow#5105]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
Simple and easy to test bug. Skinning Loque' Nahak gives you a blue item on top of the leather. Not much of an issue, but it's just not correct. Afair it gives a blue cloak, effectively making him give 2 cloaks (one on loot and one on skinning)
**Expected behaviour**: Tell us what should happen instead
Should not happen.
**Steps to reproduce the problem**:

1.  Kill
2.  Loot
3.  Skin

**Include proofs for this behaviour**
No skinner left at the moment, but this is easy enough to test.

**Comment by TeridanDW** [comment]
I don't know what to say here. Retail bug?
http://www.wowhead.com/npc=32517/loquenahak#skinning

**Comment by alexuktc** [comment]
Yeah, seems so.
