### ISSUE TITLE
Quest: The Iron Colossus

### ISSUE THREAD

**Issue by Sagrath** [dalaranwow/dalaran-wow#511]
What should happen, what happens instead:
You should mount up on "Tamed Jormungar" and defeat the Iron Colossus, Instead you cant mount up on "Tamed Jormungar" - you click on him and nothin happen. (the only prob is the "Tamed Jormungar")

The quest - http://old.wowhead.com/quest=13007
Iron Colossus - http://old.wowhead.com/npc=30300

**Comment by Cone182** [comment]
Quest still bugged, can be killed manually.

**Comment by ar1s7717** [comment]
you shouldn't have to organize a 5 man party to complete a 1 man q...still, doable

**Comment by sklivvz** [comment]
Still bugged, completely unfeasible to do without assistance

**Comment by Lothloryen** [comment]
Hello there,

This quest has been corrected and it is already on the live server.

Thank you.
