### ISSUE TITLE
Quest; Northrend: The Might of the Horde - Several improvements needed.

### ISSUE THREAD

**Issue by Aridam** [dalaranwow/dalaran-wow#5113]
**Current behaviour**: Quest works and is completable but there are several errors with it:

1. No dialogue scripts -- when using the Quest Item, when Mobs appear, etc.;
2. Banner follows you instead of being stationary;
3. Banner doesn't insta-despawn upon completion of the Quest's objective.

**Expected behaviour**: https://youtu.be/mWmcs-1qxI0?t=37

**Steps to reproduce the problem**:

1. Go to Agmar's Hammer, in Dragonblight, and get "Victory Nears..." -- continue from there to get to the Quest in question;
2. Get to Icemist Village and use the Quest Item;
3. Observe the errors with the provided video taken into consideration.

**Include proofs for this behaviour**

Quest ID and some more information: https://wowgaming.altervista.org/aowow/?quest=12053

**Comment by TeridanDW** [comment]
Hello and thank you for the report @Aridam 
I did script that quest in #859
