### ISSUE TITLE
Mechanic: Charge - Incorrect arriving point on Target.

### ISSUE THREAD

**Issue by Aridam** [dalaranwow/dalaran-wow#5123]
**Current behaviour**: Charge stops you at your Target at the very border of its Hitbox (half-in I'd even say; Range-wise it seems something like 3- yards), and also, it doesn't calculate a moving Target's position correctly -- the result of that is a sometimes-misplaced arrival point (at times even behind your Target).

**Expected behaviour**: Charge mechanics should stop you just-outside of your Target's Hitbox -- at about 5yd (maximum Interact/Melee combat Range) -- and account for mobility of the Target if that is present.

**Steps to reproduce the problem**:

For the outstretched arrival point:

1. Charge any stationary Target;
2. Note the stopping point -- on the very Hitbox itself (borderline halfway-inside);

For the mobility that's unaccounted for:

1. Charge any moving Target (especially those moving _towards_ you);
2. Note the stopping point -- off-side (if towards, you basically end up _behind_ it).

**Include proofs for this behaviour**

Pay _very_ close attention to the Range post-arrival, _and_ the accuracy against moving Targets.

https://youtu.be/nD2stcm4W8M?t=22
https://youtu.be/nD2stcm4W8M?t=32
https://youtu.be/nD2stcm4W8M?t=59
https://youtu.be/nD2stcm4W8M?t=94
https://youtu.be/nD2stcm4W8M?t=147

The list goes on -- just watch any and/or more videos by Klinda/Swifty/Veev etc. in faster motion or skip to moments of Charge mechanic usage, and observe.

The way this affects Charge mechanic _here_ is so big that even mere _Mobs_ moving (especially towards you) just messes with the arrival point, and even _stationary_ Targets of _any_ sort make your Charges arrive literally in their face pretty much.

Note: As implied, this affects the Charge _mechanic_ (ergo all Abilities that use this) -- notice Charge/Intercept/Intervene acting the same way across the board.

**Comment by Zarjofgt** [comment]
Its also about the enemy not stopping. When you charge mimirons tank for example, it will keep moving through you a significant distance. It should stop as soon as you are in melee range.

**Comment by Aridam** [comment]
Hm, that one might be an issue with some specific Hitboxes (likely bigger size) and/or Mob AI (ergo, in correlation to your position/movement)?

Speaking of Hitboxes of differing size there are some Mobs with quite the odd Hitbox -- been doing the Magnataur-related Quests in Dragonblight here. They seem to behave incorrectly in regards to the size of their Hitbox corresponding to the actual Range of abilities -- especially Charge; running away 8+ yards yet still can't Charge them (icons didn't even lit up for either Charge or Intercept).

Guess it's a running theme with bigger-sized Mobs or something.

**Comment by TeridanDW** [comment]
Thank you for the report @Aridam,
Report related to #3655

**Comment by robinsch** [comment]
Please report here again after https://github.com/dalaranwow/dalaran-wow/issues/3655 hits live.
