### ISSUE TITLE
[Item] Bountiful Feast - Not restoring Health/Mana.

### ISSUE THREAD

**Issue by Aridam** [dalaranwow/dalaran-wow#5126]
**Current behaviour**: Not sure about the Mana portion, but the Bountiful Feast doesn't restore any Health.

**Expected behaviour**: It should do that, as the tooltip says.

**Steps to reproduce the problem**:

1. Make the necessary Foods and buy an empty basket from one of the Vendors for the Event;
2. Make the Bountiful Feast and then place it down;
3. Eat from it -- no Health restored (again, not sure about Mana since I'm a Warrior).

**Include proofs for this behaviour**

Item ID: https://wowgaming.altervista.org/aowow/?item=46887

**Comment by Aridam** [comment]
Update: Confirmed that it doesn't restore Mana either.

**Comment by TeridanDW** [comment]
Hello and thank you for the report @Aridam,
Issue confirmed on PTR.
