### ISSUE TITLE
Mechanic; Item(?): First Aid - Not working on Stealthed Targets.

### ISSUE THREAD

**Issue by Aridam** [dalaranwow/dalaran-wow#5127]
**Current behaviour**: Odd occurrence just now on a Friendly Rogue I wanted to heal -- using a Frostweave Bandage on them while they were under the effects of Stealth seemed to have broken it and thus, my Bandage didn't heal them at all if they remained Stealthed. Not sure if this happens with pretty much every single Bandage from First Aid but confirmed it happened with the lesser Frostweave Bandage at the very least.

**Expected behaviour**: It should work -- Buff was up even, ticks were happening, Channeled Cast was channelling down, but no heals were being made, no changes to receiving Stealthed Friendly's HP whatsoever.

**Steps to reproduce the problem**:

1. Make a Bandage (can use normal Frostweave one for exact replicating);
2. Get someone to go into Stealth;
3. Use the Bandage on them -- nothing.

Also, might want to test on Prowling Druids and other forms of Stealth (though I suspect it's the same anyway).

**Comment by TeridanDW** [comment]
Hello and thank you for the report @Aridam,
I can't seems to be able to reproduce the issue on PTR, as it works properly:
![image](https://user-images.githubusercontent.com/6797611/33514883-95380a7c-d763-11e7-8d7a-d871612bcc37.png)

**Comment by Aridam** [comment]
Just retested -- seems to have been a one-time thing. Works indeed. Confirmed invalid.
