### ISSUE TITLE
NPC; Northrend: Commander Jordan - Two spawns.

### ISSUE THREAD

**Issue by Aridam** [dalaranwow/dalaran-wow#5130]
**Current behaviour**: Apparently there are two of the same NPC in the Barracks of New Hearthglen, Dragonblight: Commander Jordan -- one's at the elongated table up the three steps, while the other I just tagged and killed for a Quest I have was also spawned at the right, smaller table before that one.

**Expected behaviour**: There should be only one spawn of this NPC, not duplicates.

**Steps to reproduce the problem**:

1. Go to New Hearthglen, in southeastern Dragonblight;
2. Go inside the Barracks -- navigate up to the command-hall-looking room;
3. One Jordan at the end where the "grand" table is, and one at the smaller tables before that (right one, specifically).

**Comment by TeridanDW** [comment]
Hello and thank you for the report @Aridam,
Issue confirmed on PTR. Wowhead says only 1 creature in the barracks named Jordan.
Deleting this one:
![image](https://user-images.githubusercontent.com/6797611/33515035-dfdd9356-d765-11e7-8aac-1d0f45e5bc18.png)
