### ISSUE TITLE
Quest; Item; NPC; Northrend; Mechanic: Worm Wrangler - Improvements needed.

### ISSUE THREAD

**Issue by Aridam** [dalaranwow/dalaran-wow#5133]
**Current behaviour**: Quest is doable, albeit in an abusable fashion, and as such, could use some improvements:

1. The Quest Item can spawn the collectible Quest Items you need without having a Target on (lootable box spawns under you as thus); it also works on invalid Jormungars (tested on the Feeders instead of the Spawns -- box spawned under the Feeder when it shouldn't work);
2. The Quest Item doesn't force the Spawn to despawn as you capture it with it.

**Expected behaviour**: https://youtu.be/Yo9AJtcxKm4?t=79 -- uses Quest Item on Spawn, resulting in it despawning and getting the box with the lootable Quest Item for the objective to spawn underneath.

**Steps to reproduce the problem**:

1. Go to the Crystal Vice, and take the Quest from Zort;
2. Use the Quest Item given without a Target -- box spawns successfully, underneath you (it shouldn't at all);
3. Use the Quest Item given on an invalid Mob for the objective (as I said, I tested on the big Ice Heart Jormungar Feeders just to see) -- works by spawning it underneath them (it shouldn't at all);
4. Use the Quest Item given on a _valid_ Mob (the small Ice Heart Jormungar Spawns) -- works, but the Mob doesn't despawn alongside that.

**Include proofs for this behaviour**

Quest ID: https://wowgaming.altervista.org/aowow/?quest=12078
Quest Item (given usable one) ID: https://wowgaming.altervista.org/aowow/?item=36771
Ice Heart Jormungar Spawn ID: https://wowgaming.altervista.org/aowow/?npc=26359

**Comment by TeridanDW** [comment]
Hello and thank you for the report @Aridam,
Both issues confirmed on PTR.

**Comment by Rushor** [comment]
Both issue fixed with https://github.com/dalaranwow/dalaran-wow/issues/5423
