### ISSUE TITLE
[Death Knight][Pet] Ghoul despawn delay after using Death Pact

### ISSUE THREAD

**Issue by Zarjofgt** [dalaranwow/dalaran-wow#5143]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
The ghoul from Rise Dead doesnt despawn immediately after using death pact, therefore delaying the start of the raise dead cooldown by 20 seconds or so.

**Expected behaviour**: Tell us what should happen instead
The ghoul should despawn immediately after dying, regardless of how it dies.

**Steps to reproduce the problem**:

1. Summon a ghoul with raise dead.
2. Use death pact.
3. Observe that it leaves a corpse for 20 seconds, and therefore your raise dead cooldown doesnt start until it despawns.

**Include proofs for this behaviour**

"Patch 3.1.0 (14-Apr-2009): Duration lowered to 60 sec. and cooldown lowered to 3 min. The cooldown on this ability now begins when the pet dies rather than when it is summoned. **This pet now despawns instantly when it dies**. In addition, this ability can no longer be used while riding any type of vehicle. The Risen Ghoul is also now properly immune to Charm, Fear, Sleep, and Horror."
(http://wowwiki.wikia.com/wiki/Raise_Dead_(death_knight_ability))

Raise dead: https://wowgaming.altervista.org/aowow/?spell=46585
Death pact: https://wowgaming.altervista.org/aowow/?spell=17698

**Comment by TeridanDW** [comment]
Hello and thank you for the report @Zarjofgt.
Issue confirmed on PTR, however I would like to add that this happens only if the DK doesn't have talent  [Master of Ghouls]

**Comment by swiftdeath** [comment]
Agreed with Teridan, the pet instantly dies when it's a Master of Ghouls ghoul.

**Comment by Zarjofgt** [comment]
But there is still an issue when you dont have the talent? Why do you randomly close issues @robinsch

**Comment by Lothloryen** [comment]
Hello there,

It is not randomly closed; @robinsch deployed a fix at the same moment that he closed it, however he forgot to add the label. Since we have a private repository you can not see it, but it looks like: 

https://gyazo.com/bd7e865d9c7083abc76ca68a3ffa9fd0

Thank you.

**Comment by Zarjofgt** [comment]
Alright, Im sorry
