### ISSUE TITLE
NPC; Northrend: Crusader Dargath - Slightly-incorrect spawnpoint and no levitation.

### ISSUE THREAD

**Issue by Aridam** [dalaranwow/dalaran-wow#5145]
**Current behaviour**: Crusader Dargath at Dargath's Demise in Zul'Drak is not spawned at the exact spot but a bit to the side (similar to the Mob I had reported in Coldarra); he's also not levitating, but is instead standing-solid on the ground.

**Expected behaviour**: http://www.wowhead.com/npc=29468/crusader-dargath#comments -- he's basically supposed to be in the middle of those wisps of light, and levitating slightly.

**Steps to reproduce the problem**:

Go to his area in Zul'Drak and look at him -- his spawn is off and he isn't levitating.

**Include proofs for this behaviour**

https://s18.postimg.org/gdlt7vzd5/Wo_WScrn_Shot_120117_163512.jpg -- current spawn, no levitation.

Incredibly-minor thing, like the Coldarra Mob I had reported.

**Comment by TeridanDW** [comment]
Hello and thank you for the report @Aridam,
I don't think this report is valid as I looked into the 3 crusaders and fixed their position and emotes in #5017.
Here is a proof from 2008 at 1:00
https://www.youtube.com/watch?v=Wn0HOE3dSFo

**Comment by Aridam** [comment]
I've just revisited Dargath to be sure of this.

As seen in the WoWHead screenshot, as well as your provided video, he's supposed to be standing in that visual effects that is the wisps of light, while levitating.

So, just as initially-reported, Dargath is still the same way on Live: https://s18.postimg.org/790vtu0vd/Wo_WScrn_Shot_120217_151121.jpg -- not levitating; as well as https://s18.postimg.org/b5e7pttkp/Wo_WScrn_Shot_120217_151128.jpg -- see the wisps and see Dargath himself, as he's not placed in them.

**Comment by TeridanDW** [comment]
Alright, the report is valid. The confusion came from that I see a diffrent thing on PTR than what it is on live.
Anyway here is how it looks now:
![image](https://user-images.githubusercontent.com/6797611/33516686-ba49bb6e-d77f-11e7-8727-24e500331882.png)

Corrected position and hover mode.
