### ISSUE TITLE
NPC; Mechanic; Northrend: Sky Terror - Not attacking.

### ISSUE THREAD

**Issue by Aridam** [dalaranwow/dalaran-wow#5147]
**Current behaviour**: The Sky Terrors at The Argent Stand in Zul'Drak don't engage, even if they're aggroed explicitly -- they instead just keep on flying about, and they get one stuck in Combat.

**Expected behaviour**: They should engage and attack.

**Steps to reproduce the problem**:

1. Go to The Argent Stand in Zul'drak;
2. Locate and engage a Sky Terror;
3. Note how it just doesn't give a flying damn about anything's existence -- including yours.

**Include proofs for this behaviour**

Sky Terror's ID: https://wowgaming.altervista.org/aowow/?npc=28246

**Comment by TeridanDW** [comment]
Hello and thank you for the report @Aridam,
I will close this report because this creature is part of a "bigger picture/event" and it will be best to be fixed together with the event.
More information can be found here #4646
