### ISSUE TITLE
Ulduar Attunement  Issue

### ISSUE THREAD

**Issue by Siggrdrifa** [dalaranwow/dalaran-wow#5148]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: 
Around 5am server time, we were doing a Ulduar10 attunement run (ID1792), 1 or 2 minutes after killing the boss Thorim, the server crashed, coming back online a couple minutes later, but it left us without the achievement for said kill, and the boss dead, leaving us unable to complete the full attunement.

**Expected behaviour**: Boss kill should have counted towards achievement, or at the very least be still alive for us to kill him again. A lot of people is losing a week of progression because of this. And its not the first time that happens.
![wowscrnshot_120217_011731](https://user-images.githubusercontent.com/33332434/33512476-1e141d8a-d710-11e7-91a1-2be7fe23dd20.jpg)
![wowscrnshot_120217_032124](https://user-images.githubusercontent.com/33332434/33512477-1e340bea-d710-11e7-9aba-6e348fb5a409.jpg)

**Steps to reproduce the problem**:

1. Kill a boss needed to get achievement

2. Experience a server crash shortly after

3. Lose achievement/progress

**Comment by TeridanDW** [comment]
Hello and thank you for the report @Siggrdrifa.
There is nothing that can be done to avoid scenarios like this one, to my knoledge. It's how the core saves the progress of the world every X minutes and if the server crash just before a save, the last few minutes are lost.
Best thing you can do is write a detailed in-game ticket and plaining the your issue and providing as much as possible proofs.

**Comment by datbunneh** [comment]
@TeridanDW But why is the boss dead then?

**Comment by TeridanDW** [comment]
Hello @datbunneh,
Ask @Lothloryen for more details about the saving process.
I this case (Ulduar Keepers) my guess is that they are linked as 4 must be dead to continue to Vezax and instance progress might be saved in a diffrent way/place.
