### ISSUE TITLE
Instance / NPC: Caverns of Time: The Culling of Stratholme / Infinite Corruptor

### ISSUE THREAD

**Issue by Crispybuilt** [dalaranwow/dalaran-wow#515]
**Instance**: *The Culling of Stratholme* - 4100
**NPC/BOSS** - Infinite Corruptor - 32313

-  **Issue** - there is no event which starts the timer for Infinite Corruptor, the event / timer has to start once you talk to Prince Arthas to start the culling of the stratholme.

- *Infinite Corruptor is the heroic-only boss located within the Culling of Stratholme. In order for him to be available, you must complete the timed event in under 25 minutes, rewarding you with The Culling of Time - achievement.*

**How it should be resolved**: This issue could be resolved just like for Algalon, the first time you pull Algalon, 60 minute timer starts until he despawns. Here, the same thing should happen, once you accept the gossip option from Arthas the 25 minute timer starts up, if you don't reach Infinite Corruptor in 25 Minutes, he despawns.

- **Infinite Corruptor** has the following abilites: *Void Strike*, Corrupting Blight

**Void Strike** - 60590
**Corrupting Blight** - 60588

- He also has to yell following quotes upon pull:
*How dare you interfere with our work here!*

- Upon he despawns (after 25 minutes are up):
*My work here is finished*

- Once he is dead:
*My time... has run out...*

- You also get the following achievement once you defeat him: **The Culling of Time** - *1817*

**Video of how it should work**: http://www.youtube.com/watch?v=0c4klfwcyxg&feature=youtu.be&t=9m24s
_____________

http://www.wowhead.com/zone=4100/the-culling-of-stratholme
http://www.wowhead.com/npc=32273#abilities
http://wotlk.openwow.com/npc=32273#criteria-of

**Comment by urdarchina** [comment]
"The Culling of Time" achievement doesn't work, you can kill the Infinite Corruptor and not get the achievment. This is a problem because this achievement is needed for the "Glory of the Hero" meta achievement.

**Comment by Golganeth** [comment]
This has been working for a while, report shouldn't be opened.

Closed
