### ISSUE TITLE
[Quest][Mechanic][Northrend] Leave No One Behind - Improvement needed.

### ISSUE THREAD

**Issue by Aridam** [dalaranwow/dalaran-wow#5151]
**Current behaviour**: Quest works, however there is an abusable bug that can affect the NPCs and their corresponding Objectives: If one leads the NPCs to any Hostile Mobs to engage them, then proceed to kill them, when the NPCs reset back to following you a while after, they then trigger their script of dying and whatnot, which shouldn't happen, and in turn, it also triggers something else which shouldn't happen -- completion of the Objective.

In other words, the Quest can be abused to be done in this unintended way.

**Expected behaviour**: NPCs shouldn't die after getting out of Combat, nor should that mark the Objective corresponding to them each as completed.

**Steps to reproduce the problem**:

1. Take the Quest from Dr. Rogers at Drak'Sotra, in Zul'Drak;
2. Get to any of the three NPCs and use the Quest Item to begin escorting them back;
3. Lead them to a Mob to have it attack them (not you), so the NPC being escorted engages;
4. Kill the Mob so that the NPC leaves Combat and resets after a bit;
5. Watch as they trigger their script of dying, alongside the marking of their select Objective as accomplished.

**Include proofs for this behaviour**

IDs to the Quest's NPCs:
https://wowgaming.altervista.org/aowow/?npc=28133
https://wowgaming.altervista.org/aowow/?npc=28143
https://wowgaming.altervista.org/aowow/?npc=28141

Quest Item's ID: https://wowgaming.altervista.org/aowow/?item=38330

Quest's ID: https://wowgaming.altervista.org/aowow/?quest=12512

**Comment by TeridanDW** [comment]
Hello and thank you for the report @Aridam,
Issue confirmed on PTR.
![image](https://user-images.githubusercontent.com/6797611/33995254-19312e40-e0e6-11e7-9fa1-43f49b0a994c.png)

**Comment by Rushor** [comment]
That's a general problem with debuffs which should not be removed while the creature resets/evades.
