### ISSUE TITLE
Spirit Heal buff

### ISSUE THREAD

**Issue by Johanes022** [dalaranwow/dalaran-wow#5153]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: When you ressurect in battleground you get buff named Spirit Heal wich should reduce spell cost by 100% for 6 seconds after you ressurect.Right now you get the buff but spells still cost to cast.

**Expected behaviour**: Spirit heal buff should reduce spell cost by 100% for 6 seconds after you ressurect.

**Steps to reproduce the problem**:

1. Die and ressurect in BG
2. While buff is on you try buffing/casting any spell and observe.It consumes your mana as if there is no buff at all.
3. 

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

http://www.wowhead.com/spell=44535/spirit-heal

**Comment by TeridanDW** [comment]
Hello and thank you for the report @Johanes022.
Issue confirmed on PTR.
Just to clarify the spell players get when they join a BG and the BG haven't started yet is https://wowgaming.altervista.org/aowow/?spell=44521 which works properly.
When a player is resurected by Spirit healer in a BG he gets spell https://wowgaming.altervista.org/aowow/?spell=44535 on him for 6 seconds and this spell has no effect at all.

**Comment by robinsch** [comment]
Can't confirm on my PTR. Working fine and reducing the spell costs by 100%.

**Comment by TeridanDW** [comment]
Visually it shows that I can cast the spell but when I try I get the error of missing rage/mana/runic power
![image](https://user-images.githubusercontent.com/6797611/34518774-abc0d654-f089-11e7-9c1e-5e8a227db915.png)

**Comment by robinsch** [comment]
I haven't tested with Rage spells only with mana spells.

**Comment by TeridanDW** [comment]
Hm this might be my mistake because:
 - Spell https://wowgaming.altervista.org/aowow/?spell=44521 has:

> Apply Aura: Mod Power Cost School Percent (**Physical**, Holy, Fire, Nature, Frost, Shadow, Arcane) [127]
> Value: -100

and works on rage spells.

 - While spell https://wowgaming.altervista.org/aowow/?spell=44535 has:

> Apply Aura: Mod Power Cost School Percent (Holy, Fire, Nature, Frost, Shadow, Arcane) [127]
> Value: -100

physical spells are not there so this means it's intended to not reduce rage spells to 0 for 6 secs?

Also just checked mana spells and they do cost 0 for 6 secs.

@Johanes022 which spells did you notice that costed mana during these 6 secs?

**Comment by Johanes022** [comment]
So far from what ive noticed its Mark and Gift of the Wild
https://www.youtube.com/watch?v=wELhKuGJ7J0

**Comment by robinsch** [comment]
It doesn't consume mana. It increases your mana because of the Mark / Gift.
