### ISSUE TITLE
[Ulduar] Combat Bug After Defeating Assembly Of Iron

### ISSUE THREAD

**Issue by datbunneh** [dalaranwow/dalaran-wow#5154]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: raid was in combat after defeating Assembly of Iron.

**Expected behaviour**: raid should not be in combat after defeating Assembly of Iron.

**Steps to reproduce the problem**:

Can't tell the exact steps. Personally I overagrroed Runemaster Molgeim, died and was resurrected, don't know if that matters. Here is the order in which we killed them:
1. Runemaster Molgeim
2. Steelbreaker
3. Stormcaller Brundir

It might depend on the event during which we kill some of the bosses. E.g. Stormcaller Brundir being killed during casting Overload.

**Include proofs for this behaviour**

Combat bug is known to be not intended.

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

Runemaster Molgeim - 32927
Steelbreaker - 32867
Stormcaller Brundir - 32857

**Include Screenshots from the issue if necessary**

N/A

**Comment by TeridanDW** [comment]
Thank you for the report @datbunneh.
As @Lothloryen said in #5028:

> Hello again, if you experience it again, write an ingame ticket, please, we have now some tools in order to try to identify the source of the combat bugs on real time.

It will be very helpful to have a ticket when this happens so a GM can see which creature create this issue.
Closing the report for now but will keep it in mind.
