### ISSUE TITLE
Fear and Death coil path

### ISSUE THREAD

**Issue by adytzyca** [dalaranwow/dalaran-wow#5156]
**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
Fear and Death coil path makes it impossible to cast anything on the target
**Expected behaviour**: Tell us what should happen instead
Feared and death coiled targets should run in a somewhat liniar,predictible way, not to appear to be in one place but to actually be behind you and to be teleporting around
**Steps to reproduce the problem**:

1. Fear path bugged
2. Death coil path bugged
3. 

**Include proofs for this behaviour**

You can research this on several pages like http://wowhead.com or http://wowwiki.wikia.com or http://www.youtube.com/
Issues without proofs will be closed and tag On Hold will be added until the proof is provided.

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

You can research this on several pages like https://wowgaming.altervista.org/aowow/ or https://wowhead.com/

**Include Screenshots from the issue if necessary**

**Comment by TeridanDW** [comment]
Thank you for the report @adytzyca.
Duplicate with #1447 continue there.
