### ISSUE TITLE
Sindragosa bugged on Kirin Tor server

### ISSUE THREAD

**Issue by Imisstheoldkanye** [dalaranwow/dalaran-wow#5161]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
During her air phase in the normal 10 man ICC raid instance, Sindragosa will freeze people in blocks of ice which are then to be used as shield to protect from her frost missile damage. This works fine, however the ice tombs cannot be damage. Auto attacks and targeted spells and abilities will not occur when targeting one, and AoEs will not damage them either.
**Expected behaviour**: Tell us what should happen instead
Sindragosa's ice tombs are supposed to be damageable so that the raid can break the frozen people out of them once the air phases are ending. In its current state, Sindragosa effectively cannot be killed.
**Steps to reproduce the problem**:

1. Enter Sindragosa's Lair in Ice Crown Citadel
2. Start the fight with Sindragosa by clearing all the trash, and killing Rhimefang and Spinestalker.
3. Attempt to damage the ice tombs that Sindragosa encases 2 people in during the air phases (first air phase starts at 85% health).

**Comment by SirSlacksALot** [comment]
The ice tombs work on Algalon. Other Kirin Tor bug reports have been closed with the comment "When Kirin Tor is updated this issue should be solved" which is excellent. The players of Kirin Tor would greatly appreciate any insight into the expected timing of the roll out. We are a very patient bunch, but please give us some sort of timeframe. Thank you.
![image](https://user-images.githubusercontent.com/33267982/33578443-c94fc4f2-d903-11e7-8db6-f88404b39d63.png)

**Comment by Lothloryen** [comment]
Hello there,

We will keep you updated about when we will perform some upgrades on Kirin Tor.

Thank you.

**Comment by Boberthy** [comment]
Any estimate on when Kirin Tor will be updated? I'm a little worried since this thread is over a year old.
