### ISSUE TITLE
[Rogue] Killing Spree

### ISSUE THREAD

**Issue by Jiaku** [dalaranwow/dalaran-wow#5162]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
Attacking an enemy every 0.5 seconds with both weapons until 5 attacks are made. According to the recount killing spree does 5 attack with each weapons.
**Expected behaviour**: Tell us what should happen instead
Attacking an enemy every 0.5 seconds with both weapons until 5 attacks are made and increasing all damage done by 20% as ability says. Does 5 attack with both weapons but damage is combined from two weapons.
**Steps to reproduce the problem**:

1. Use killing spree on dummy
2. Use melee attacks dummy
3.  There is almost no difference.

**Include proofs for this behaviour**
http://wowwiki.wikia.com/wiki/Killing_Spree

-  Patch 3.1.0 (14-Apr-2009): Now also increases all damage done by the rogue while active by 20%

**Comment by alexuktc** [comment]
The attacks are considered "Killing Spree" on recount. On one hand I do see the damage increase on the character panel, but on the other hand my recount has yet to show the Killing Spree Strikes doing more damage than the normal attacks. And I have timed everything to include all procs possible. 

I will do further tests with no procs available, but I doubt it will be different.

**Comment by Jiaku** [comment]
Yes  recount records "Killing spree"  as "Killing spree" but it does 10 assaults 5 assaults with each weapon, should do however 5 assaults with both weapons(damage of both weapons combined as one assault) and +20% damage during "Killing spree"

**Comment by alexuktc** [comment]
Killing Spree has a duration, during which your damage on the character panel is indeed increased. However the recount itself does not show the hits themselves to be stronger than normal attacks. I have no tested yet, so I will need some time before I comment further.

**Comment by Jiaku** [comment]
Any news?

**Comment by alexuktc** [comment]
In all fairness when I tried with 0 procs and a 1-3 weapon it turned out as expected. When I put a weapon with a bigger damage difference there were a lot of issues. Considering I had done over 15 Killing Sprees the damage difference alone should not be statistically significant. 

Otherwise it worked as intended.

**Comment by TeridanDW** [comment]
Hello and thank you for the report @Jiaku.
I've also checked this on PTR and from the simple test I did it seems it works properly.
White hits ~ 50-55 (that's main hand + off hand as they have the same speed) without Killing Spree
![image](https://user-images.githubusercontent.com/6797611/33994741-649c4a60-e0e4-11e7-984a-cf1d75b2c0ff.png)

And 65 (that's main hand + off hand as they have the same speed) white hits during Killing Spree
![image](https://user-images.githubusercontent.com/6797611/33994829-aecfa384-e0e4-11e7-9f1d-6737980a9ea3.png)

If you (or someone else) can provide a proof from Algalon that the extra damage is missing please do so.

**Comment by TeridanDW** [comment]
Here are the 20% in character panel also:
![image](https://user-images.githubusercontent.com/6797611/33995034-4fc854fc-e0e5-11e7-872e-f54de0220da6.png)
