### ISSUE TITLE
ToC and Ulduar kill credit not given on killing bosses due to server

### ISSUE THREAD

**Issue by notaslave** [dalaranwow/dalaran-wow#5164]
**Current behavior**: Tell us what happens in detail (Where, When, What, Why, Who)
When I killed Thorim in Ulduar 10m on my shaman and Twin Val'kyr ToC 25 on my rogue I didn't receive credit for the kill, receive emblems,  or earn progress on my achievements, and therefor attunement due to slight server rollbacks however loot from the bosses were kept and not lost at all from what I understand.
**Expected behavior**: Tell us what should happen instead
Shouldn't have happened at all
**Steps to reproduce the problem**:

1. let the server crash
2. 
3. 
I would like to point out I'm not the only one who had this issue on the ulduar run. We've had a ticket in since the run and nobody has gotten around to it yet.
**Include proofs for this behaviour**
![wowscrnshot_120517_165028](https://user-images.githubusercontent.com/17308094/33635169-948274fc-d9dc-11e7-85b4-c26be4b8f28c.jpg)
![wowscrnshot_120517_165026](https://user-images.githubusercontent.com/17308094/33635172-97751b24-d9dc-11e7-8c9d-8b130003c61f.jpg)
![wowscrnshot_120517_164940](https://user-images.githubusercontent.com/17308094/33635175-9ab175f8-d9dc-11e7-9f81-d9e38af79a15.jpg)
sorry the screenshots are the most proof I can provide.

**Comment by MalkaviaDW** [comment]
Hello there, 

As mentioned in #5148 this is an issue that can only be solved with an in-game ticket.

Cheers!
