### ISSUE TITLE
shorter berserker time of razzorscale

### ISSUE THREAD

**Issue by lkrocek** [dalaranwow/dalaran-wow#5168]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

Razzorscale in ulduar has berserker after 5-6 mins after pull but should be 8-10 minutes.

It's hard for decent geared group.

http://wowwiki.wikia.com/wiki/Razorscale

**Comment by Crispybuilt** [comment]
Hello,

Razorscale's Berserk timer is a pre-nerf version of Ulduar, which is to be intended.

*As of patch 3.1.1, Razorscale has a ten minute berserk timer across all phases.*
