### ISSUE TITLE
Misc: Artisan Riding 

### ISSUE THREAD

**Issue by Tomson90** [dalaranwow/dalaran-wow#517]
Artisan Riding always costs 5k gold when u want to buy it in Warsong Hold,doesnt matter if u have exalted or revered with Warsong Offensive,or Horde Expedition 

Discounts : http://www.wowwiki.com/Riding

**Comment by Rushor** [comment]
it will be reduced if you have higher reputation http://i.imgur.com/ImRelsS.jpg

that's working already
