### ISSUE TITLE
Fear/Death Coil path

### ISSUE THREAD

**Issue by adytzyca** [dalaranwow/dalaran-wow#5173]
Hello,
ive just noticed you deployed another patch of 'hot fixes' none of which happens to be the death coil/fear path that makes every warlock's life miserable, so i've decided to raise awareness by reminding you about this bug that ,for the record, ive reported since 2014 and which no one seems to be giving a crap about.
So the bug is that feared/death coiled targets teleport around the caster, making it impossible to cast anything on them.

**Comment by KerDW** [comment]
Gonna add that this happens too with Scatter Shot and probably any other disorient effect, which makes landing traps harder.

The cause of this bug seems to be movement speed since scatter+trapping mounted targets is almost impossible due to this bug.

**Comment by kysqt** [comment]
Indeed, trying to land a scatter+freezing on a mounted and moving player is nearly impossible.

**Comment by TeridanDW** [comment]
Hello and thank you for the comments,
Please continue in #1447

**Comment by Lothloryen** [comment]
Hello there,

This issue has been corrected, it should be fine after the next scheduled maintenance.

Thank you for the reports.
