### ISSUE TITLE
Player not aggroing/losing aggro if standing in the water - Darkshore

### ISSUE THREAD

**Issue by ck75w** [dalaranwow/dalaran-wow#5174]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: When a player (in this case a level 15 Druid) stands near an hostile NPC in the Cliffspring River area of Darkshore (in this case a level 15 Moonstalker), they will not aggro the mob as long as the player stays in the water. If the player attacks a mob and gets aggro (in this case a level 14 Rabid Thistle Bear nearby), and gets into the water again, the player will lose the aggro.

**Expected behaviour**: The player should get attacked by the mob regardless of being in the water or not. If the player attacks a mob and gets aggro, he should not lose it when getting into the water.

**Steps to reproduce the problem**:

1. Go to the Cliffspring River area in Darkshore
2. Walk up to the Moonstalker NPC standing alongside the river
3. Stand near or attack it while being in the water

**Include proofs for this behaviour**

![screenshot from 2017-12-10 14-41-13](https://user-images.githubusercontent.com/26232978/33809991-a94b0ba6-dddd-11e7-92ad-fc10d8d7ec94.png)

![screenshot from 2017-12-10 15-44-34](https://user-images.githubusercontent.com/26232978/33810031-4ba26eb2-ddde-11e7-820d-7bcafc0e0c76.png)

**Include Screenshots from the issue if necessary**

[An album offering further details on the issue.](https://imgur.com/a/JaTVB)

**Comment by TeridanDW** [comment]
Hello and Thank you for the report @ck75w.
This creature behavior is intended and correct. There are creatures that can walk only on ground, some can only swim, some can swim and walk on ground, depends on their type.
With that been said I did take a look in-game and I found a bug with the "land only" creature.
If player aggro 1 of them, then enter a water they stop to chaise, but then the player leaves the water on the other shore of the river, the creature will walk though the water anyway to get to the player.
Or when the player is just jumping in the walker creature just passes thought it anyway.
Example:
https://www.youtube.com/watch?v=8mQJczoXCBg&feature=youtu.be
