### ISSUE TITLE
 [Verog the Dervish]

### ISSUE THREAD

**Issue by VukadinNedeljkovic** [dalaranwow/dalaran-wow#5175]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Doesn't appear even if I kill every creep in quest pin radius.

**Expected behaviour**: Verog the Devish should appear after killing few Kolkar NPCs

**Steps to reproduce the problem**:

1. Take Quest.
2. Go to and see.

**Include proofs for this behaviour**

https://www.youtube.com/watch?v=ZfCwY6FVhg4

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

http://www.wowhead.com/quest=851/verog-the-dervish

**Include Screenshots from the issue if necessary**

**Comment by Lothloryen** [comment]
Hello there,

Thank you very much for your report. This quest works as it should, each Kolkar has a 5% chance to trigger Verog's mini event.

**Comment by VukadinNedeljkovic** [comment]
Thank you. Nice to know chances.
