### ISSUE TITLE
DK Blood tap spell bug

### ISSUE THREAD

**Issue by Rshaviz** [dalaranwow/dalaran-wow#5176]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Death knight's spell "Blood tap" doesn't properly work. When i use Blood tap spell blood(or death) rune doesn't activates (immediately), bug appears in unholy  dps specialization mostly ( sometimes it works properly in blood specialization)
EDIT: Looks like Blood tap spell ignores blood runes that already become death runes (doesn'n reset cooldown of it)

**Expected behaviour**: When using Blood tap spell it should activate even unactive blood rune as death rune.

**Steps to reproduce the problem**:

1. At unholy pve dps speccialized DK using "Blood strike" twice to make blood runes inactive.
2. using spell "Blood tap".
3. Blood/Death rune still on cooldown.

**Include proofs for this behaviour**

https://wotlk.evowow.com/?spell=45529

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

https://wotlk.evowow.com/?spell=45529

**Include Screenshots from the issue if necessary**

**Comment by swiftdeath** [comment]
What I've noticed is this happening to Death Runes only. Blood Tap always works for me in Unholy, as I have no conversion to Death Runes there. 

The question is, the spell tooltip says it converts a BLOOD rune into a DEATH rune. If it's already a DEATH rune it can't convert the BLOOD rune into a DEATH rune, thus not making it available after using Blood Tap. This is could very well be the issue we're having right now. 

I have been searching for proof regarding this issue myself a year back, but could not find any retail evidence that Blood Tap should activate an already converted Blood Rune.

As you've shown, EvoWoW tooltip says the following:
Effect #1: Activate Rune: (Death)Value: 1
Effect #2: Apply Aura: Convert Rune (Death) [3]Value: 1
Effect #3: Energize: (Runic Power)Value: 10

Seeing this, it should infact also activate an already converted Blood Rune. 

I would like to see what the Devs have to say about this not yet confirmed bug. What I do know is that it's a pain when playing frost and you are in need of an 'emergency' or 'optimization' rune.

- Urth
