### ISSUE TITLE
[Icc] Falling through the floor in frostmourne

### ISSUE THREAD

**Issue by Zarjofgt** [dalaranwow/dalaran-wow#5178]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
Players sometimes fall through the floor in the frostmourne room.

**Expected behaviour**: Tell us what should happen instead
Players should not fall through the floor in the frostmourne room.

**Steps to reproduce the problem**:

1.  get ported into frostmourne
2.  shapeshift/do nothing special
3.  Observe that you fall through the floor

This happened to me three times when I shifted out of bear form in there, but it happened to a mage and shaman as well for seemingly no reason.

**Comment by Lothloryen** [comment]
Hello there,

Thank you for the report, this issue shall be on Algalon with the next maintenance.
