### ISSUE TITLE
the cipher of damnation. last quest

### ISSUE THREAD

**Issue by Radschpud** [dalaranwow/dalaran-wow#5179]
I summond the giant. but cant attack him.
![wowscrnshot_121217_154337](https://user-images.githubusercontent.com/14928789/33890731-5c157010-df54-11e7-9ca0-4343b7fe6a94.jpg)

#625

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Comment by TeridanDW** [comment]
Hello @Radschpud,
As you have seen #625 there is a comment:

> @DrFuler you need to talk to the guys in the background. click on the gossipoption and the event will start. This behaviour is blizzlike.

Maybe this is why you can't target him.
Also next time please just comment in the existing bug report, no need of a new one when there is already and existing one.
Thank you.
