### ISSUE TITLE
Instance / NPC: Onyxia's Lair / Onyxia

### ISSUE THREAD

**Issue by Crispybuilt** [dalaranwow/dalaran-wow#518]
Instance: Onyxia's Lair - 2159
NPC/BOSS: Onyxia (10 & 25) - 10184 / 36538

**Issue** - Onyxia is missing her visual flying effects, All the visual effects that should be present during an air phase are shown here:
She is basically fly glitching, walking like a normal npc on the ground instead of actual, nice visual flight (for example like Sindragosa Air Phase or Sindragosa Arrival)

____________________________
___________________________
**Other than that, encounter works flawlessly, it should also be fully hardcore after proper mask is up on the next update, so air phase, flame breath, Bellowing Roar etc cannot be interuptable, re-tauntable with any skills or spells - revamped**
**Also, she doesn't cast Flame Breath in 3rd phase for some reason, which has to be a critical fix or it's way too easy**

_____________
_______________

![image](https://f.cloud.github.com/assets/5054924/943055/85a2308e-01ec-11e3-91a1-2166bdc22fbf.png)

It would be wise to download WoWModelViewer_7.0.5 and check the all there.

___________
https://code.google.com/p/wowmodelviewer/downloads/detail?name=WMV_Binary_v0705_Win32.zip&can=1&q=
http://wotlk.openwow.com/npc=10184
http://wotlk.openwow.com/npc=36538

**Comment by DanteMS** [comment]
If during 2nd phase Onyxia uses Breath in time of the starting of 3rd phase, she will stuck in the air till the end of the fight.

![wowscrnshot_061616_205602](https://cloud.githubusercontent.com/assets/8601667/16170345/5e73e8e8-3558-11e6-94af-93cb11820db6.jpg)
