### ISSUE TITLE
Receiving Mail, But Don't Appear in Inventory

### ISSUE THREAD

**Issue by Shanegsta** [dalaranwow/dalaran-wow#5182]
So first thing I tried looking for a support email of some sort on the website however, whenever I click support it basically just refreshes the page. so I decided to try this. My man bug encounter is that when I donated I purchased some Heirloom gear, I reviewed the mail, but when I collected the items they never appeared in my inventory. If I could get some help on this issue that would be great. 

Thanks! :)

Account: evanshane
Email: Evanshaney@gmail.com

**Comment by Chenocide** [comment]
Write to this:
dalaran.community@gmail.com
