### ISSUE TITLE
Hunter pets - Taunt constantly overrides Bite auto-cast

### ISSUE THREAD

**Issue by Legim** [dalaranwow/dalaran-wow#5185]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

Current behaviour: The ravager pet has several abilities to toogle on auto-cast. However, there is a conflict between Taunt and Bite. Bite is never remembered as an auto-cast. Taunt is constantly overriding Bite as the primary auto-cast ability whenever the pet re-appears (via mount or dismiss)

This means that if Bite is put on autocast and Taunt is off, after mount and dismount, for example, Taunt will be on auto-cast and Bite no longer be on auto-cast. 
It is properly working for all other pet abilities (meaning they remain in autocast).

I tested on my Ravager, where I noticed the bug. However, other hunters have told me that their ravagers are fine, but they find the same bug on cats. Perhaps the bug exists in this particular type of ravager.
Please give a closer look to this issue, since it is seriously affecting dps, as Bite is never on auto-cast and it is not doable to manually do it.

Expected behaviour: Taunt should remain as non-autocast, while Bite should be on auto-cast every time.

Steps to reproduce the problem:

1. On a hunter with a ravager pet, put Bite on autocast and Taunt off.
2.  Mount and dismount
3. Bite will be off and taunt will be on

**Include proofs for this behaviour**

![image](https://user-images.githubusercontent.com/34605602/34072926-ba2cb3e4-e287-11e7-9f8f-6aa7e316f156.png)

**Comment by TeridanDW** [comment]
Hello and thank you for the report @Legim.
I've just tested the issue on PTR, but I wasn't able to reproduce it. For me it worked properly, tried ravager and wolf.
Could you switch your pet with some other one and see if you have the same problem?

**Comment by Legim** [comment]
Thanks for taking your time to test this issue.
In fact, I tamed another ravager and it does work well. I also tested with my crab, and it's working properly. Probably, the bug only happens with a specific type of ravager. In this case, I tamed the bugged one in hellfire peninsula. 
I guess I'll just level a new one. Thanks :)
