### ISSUE TITLE
Equipment Manager bug

### ISSUE THREAD

**Issue by kysqt** [dalaranwow/dalaran-wow#5189]
So while opening a gear slot with Equipment Manager and clicking another gear set that doesn't use the selected item, it will have a chance, or will delete that piece of gear. This happened to me a few days ago with my [medallion of the horde] my luck that it's an easily replaceable trinket, but for some reason I'm not able to buy another one from the vendor, A gm sent me one through the mail with the same issue, not able to put it in my bags, because it's unique...so now I have a ghost trinket.

Last time this happened to me it was sent back to me through the mail, for whatever reason it hasn't come back. My mail box is not full. Proof it's not on my character or in my bank: https://gyazo.com/ca41739f6a6897cbfbd32e48306dd3a9

**Comment by kysqt** [comment]
Proof I cannot loot it: https://gyazo.com/1f9fa75e09f5a82af61e937e3a78b2c0

**Comment by Lothloryen** [comment]
This was already solved ingame, it was a visual issue.

Thank you.
