### ISSUE TITLE
Quest: Mission: Plague This!

### ISSUE THREAD

**Issue by Crispybuilt** [dalaranwow/dalaran-wow#519]
Quest Mission: Plague This! - 11332
- **Issue present** - The Gyphon Master (_23859_ - **Greer Orehammer** ) is not giving or offering a gossip to player so he can start the event and fly over the zone _New Amagand_
- _He should also give the player the bombs which will be dropped on the location_
- **Comment from WoWhead** - _Greer Orehammer is the flight master on the little wall inside westguard keep. Speak to him and he will fly you to drop the bombs on the plague tanks._

_Those who don't know wot to do... Talk To Flight Master He has option select that and u'll start flying..._

**Temporary that could work** - Make a gossip option that will give player bombs, player will have to walk to there and use the bombs on the _New Agamand Plague Tank Bunny_ to get the credit. He can use it multiple times on a one tank.

Make sure u have free space and as well as don't be impatient if u miss the gryphon will fly in for another circle giving u chance to bomb!

---

http://www.wowhead.com/quest=11332/mission-plague-this
http://wishead.wowis.org/?npc=24290

**Comment by rszczykno** [comment]
It works now as intended.

**Comment by Lothloryen** [comment]
Working properly since long time ago.

**Comment by TeridanDW** [comment]
Hello, after few tests on this quest i found some issues:

 - the gossip menu text offered by npc http://www.wowhead.com/npc=23859/greer-orehammer is wrong and it should be:

``` sql
UPDATE `gossip_menu_option` SET `option_text` = 'Greer, I need a gryphon to ride and some bombs to drop on New Agamand!' WHERE `menu_id` = 9546 AND `id` = 2; 
```
Proof:
![image](https://cloud.githubusercontent.com/assets/6797611/25332277/7c532b8c-28ee-11e7-90f5-5cd65285ea99.png)

 - Quest credit is not given to player when he uses item http://www.wowhead.com/item=33634/orehammers-precision-bombs while riding the griphon taken from npc http://www.wowhead.com/npc=23859/greer-orehammer
Instead the player have to walk to the area > use the item > get the credit , without using the gryphon (which is wrong).
Possible solution:
``` sql
-- New Agamand Plague Tank Bunny SAI
SET @ENTRY := 24290;
UPDATE `creature_template` SET `AIName`="SmartAI" WHERE `entry`=@ENTRY;
DELETE FROM `smart_scripts` WHERE `entryorguid`=@ENTRY AND `source_type`=0;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(@ENTRY,0,0,0,8,0,100,0,43404,0,5000,5000,11,43419,0,0,0,0,0,7,0,0,0,0,0,0,0,"New Agamand Plague Tank Bunny - On Spellhit 'Mission: Plague This!: Orehammer's Precision Bombs Dummy' - Cast 'Mission: Plague This!: Kill Credit'");
```

 - When a player hits the Plague Tanks with item http://www.wowhead.com/item=33634/orehammers-precision-bombs flames should spawn over it, which doesn't happen currently.
Proof:
https://www.youtube.com/watch?v=39QRMgoiNm8
![image](https://cloud.githubusercontent.com/assets/6797611/25333898/ede7b82a-28f4-11e7-9614-4ab7c1d12569.png)

Needs a sniff for the issue to be fixed properly
