### ISSUE TITLE
The Crone stucked in Karazhan

### ISSUE THREAD

**Issue by lkrocek** [dalaranwow/dalaran-wow#5192]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

Hello, I was 4 times in KZ and 3 times The crone was stucked. We killed 4 pre-bosses but the crone was unattackable and encounter was over after leave it saying encounter is in progress and we cannot do anything.

We were there in 4 80 lvls ppl.

**Comment by Crispybuilt** [comment]
#3935
