### ISSUE TITLE
[Hunter Quest. ID=7636] Stave of the Ancients

### ISSUE THREAD

**Issue by Legim** [dalaranwow/dalaran-wow#5198]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: There are two issues:
This quest is a Hunter quest-chain started by Molten Core item [Ancient Petrified Leaf]
1) The four demons are in a human form. Normally, one talks to them and forces them to transform into their demon form. However, when talking to them, they have no text whatsoever, so there is no way of forcing them to transform (See Screenshot "Selenor"). However, they can be attacked through an AOE spell, like volley.

2) However, it is possible to engage them into combat by attacking through an AOE spell, like Volley. Through this way it is possible to obtain all the demon heads, except for Selenor (See Screenshot "Loot"). This one does not drop any quest item, which makes it impossible to continue the chain quest started by the Ancient Petrified Leaf.

![selenor](https://user-images.githubusercontent.com/34605602/34320513-d29998cc-e7f3-11e7-9dbf-c4d1f471f37c.png)
![loot](https://user-images.githubusercontent.com/34605602/34320514-d2bb88f6-e7f3-11e7-83fd-304210b1c8e0.png)

**Expected behaviour**: 1) The demons should have a speech option to force them to transform, and Selenor should drop the quest item when killed.

**Steps to reproduce the problem**:

1.Obtain the quest "Stave of the Ancients" (quest-chain started by Ancient Petrified Leaf).
2. Find Selenor in Silithus, at 24,75.
3. Engage combat with Selenor, using Volley, and kill him.

**Comment by TeridanDW** [comment]
Hello and thank you for the report @Legim,
I will link this report to #974 and continue there.
Note: Fixing only this creature is not enough, all 4 of them needs to be reviewed to proper fix.
