### ISSUE TITLE
Dying Soldiers giving xp upon being killed

### ISSUE THREAD

**Issue by koenvdbrandt** [dalaranwow/dalaran-wow#5201]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
The Dying Soldiers in The Broken Front in Icecrown have 126 hp and give the same experience as the other lvl 80 mobs with 12,6k hp upon being killed.

**Expected behaviour**: Tell us what should happen instead
I assume the should not give experience upon being killed.

**Steps to reproduce the problem**:

1. Go to the Broken Front in Icecrown with a character which is not lvl 80
2. Kill a Dying Soldier
3. Test if you receive experience

**Include proofs for this behaviour**
I found this out while leveling on my mage, but my alts are now all lvl 80, so I can't provide any screenshots of the event.

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**
http://www.wowhead.com/npc=31304/dying-soldier#comments

**Include Screenshots from the issue if necessary**
-

**Comment by Nostealth** [comment]
https://imgur.com/a/WF6XI I hope i don't get banned for this. Went with my dk to see if it's true in order to provide proof.It is right..they do give XP and lots of it..can be easily abused by players.

**Comment by Lothloryen** [comment]
Hello there,

This issue has been corrected already and will be fixed within the next realm mainteance. Thank you very much for your reports.
