### ISSUE TITLE
Priest Spell Circle of Healing

### ISSUE THREAD

**Issue by Mariijanee** [dalaranwow/dalaran-wow#5203]
This spell has not properly worked for months and months. 
Circle of Healing is supposed to be a "smart" heal, which heals targets in range with the lowest health at the time of use. Currently in game, the spell does indeed heal targets, but the "smart" aspect of the heal does not work.

Posting logs sadly wont help with proving this issue because all it shows is the fact that the spell actually healed someone. It is just not properly healing the correct targets. 

This fix would make Holy a very solid healing spec with the 4 piece tier 10 bonus and proper gear. Giving raid teams the option to bring a holy priest would be a huge asset. Currently holy priests are only brought for cooldowns, and fixing this would make them a powerfull healing class.

**Comment by TeridanDW** [comment]
Hello and thank you for the report @Mariijanee.
Could you provide any proof that there should be a "smart" heal please.
Spells:
https://wowgaming.altervista.org/aowow/?spell=34861
https://wowgaming.altervista.org/aowow/?spell=34863
https://wowgaming.altervista.org/aowow/?spell=34864
https://wowgaming.altervista.org/aowow/?spell=34865
https://wowgaming.altervista.org/aowow/?spell=34866
https://wowgaming.altervista.org/aowow/?spell=48088
https://wowgaming.altervista.org/aowow/?spell=48089

> Heals up to 5 friendly party or raid members within 15 yards of the target for 958 to 1058.

**Comment by kysqt** [comment]
Doesn't chain heal and holy light glyph have the smart heal? doesn't say they do on tool-tip. The only thing I can think of that does is  [Ancestral Awakening] https://wowgaming.altervista.org/aowow/?spell=51558 shaman talent.

https://wowgaming.altervista.org/aowow/?spell=1064#.
https://wowgaming.altervista.org/aowow/?item=41106

**Comment by kysqt** [comment]
http://wowwiki.wikia.com/wiki/Circle_of_Healing

**Comment by TeridanDW** [comment]
> Patch 3.0.2 (14-Oct-2008): Circle of Healing (Holy): Now works on any targets in the caster’s raid, and is now a "smart" heal and chooses the lowest health targets to heal first within its range. Also now has a 6 second cooldown. Also no longer will heal summoned Snakes from Hunter’s Snake Trap.

**Comment by robinsch** [comment]
It currently is a smart heal, please post a video or something where you can clearly see it's not working on live.

Reading through the code is sorts all valid raid members by health pct.
