### ISSUE TITLE
Heroic: The Steamvault

### ISSUE THREAD

**Issue by joki8** [dalaranwow/dalaran-wow#5204]
I actived the mechanism at second boss but door to final boss still closed.

http://www.wowhead.com/the-steamvault
![bez nazvu](https://user-images.githubusercontent.com/34829069/34334776-ac570620-e949-11e7-964f-ce5e8fd91b92.jpg)
![xxx](https://user-images.githubusercontent.com/34829069/34334779-b5561e78-e949-11e7-8814-fb26a88e4750.jpg)

**Comment by alexuktc** [comment]
Did you activate the mechanics at the first boss? Because you need both. It has been a while since I was last there but when I was I had no issues.

**Comment by joki8** [comment]
My mistake sorry.
