### ISSUE TITLE
[Spell] Invisibility - Does not reset threat

### ISSUE THREAD

**Issue by shibuyaku** [dalaranwow/dalaran-wow#5206]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

Mage Spell ID: 66
http://www.wowhead.com/spell=66/invisibility

**Current behaviour**: Using Invisibility takes you out of combat, if not interrupted by taking damage or casting, after 3 seconds. Threat is restored after going visible again (time running out or removing the buff https://wowgaming.altervista.org/aowow/?spell=66). It basically works like mirror images right now, regarding threat.

**Expected behaviour**: Invisibility should reduce all threat on the mage by 33% every second. That threat should never be restored, thus reducing all threat by 99% after 3 seconds.

**Steps to reproduce the problem**:

1. Overaggro any boss heavily while using mirror images (130%+).
2. Use Invisibility (Spell ID 66) 5 seconds before mirror images runs out. 
3. Click  Invisibility (Spell ID 66) away after mirror images runs out.
4. Boss attacks you - no aggro reduced. (Also reproduceable without the Mirror Images interaction, but its quite easy to prove something is wrong like this).

**Include proofs for this behaviour**
You will find tons of comments regarding the threat wipe/threat reduce functionality on wowhead, even specifically from 3.3.5 Patch.
http://www.wowhead.com/spell=66/invisibility#comments:id=1105311
http://www.wowhead.com/spell=66/invisibility#comments:id=535201:reply=68423

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**
Mage Spell ID: 66

**Include Screenshots from the issue if necessary**
Will make a video in the next raid im in to showcase this.

**Comment by TeridanDW** [comment]
Hello and thank you for the report @shibuyaku!
Issue confirmed on PTR.
The missing threat reduction might be related to spell https://wowgaming.altervista.org/aowow/?spell=35009

**Comment by TeridanDW** [comment]
Hello after a quick test on PTR, the original issue persists. Threat is still been restored when the mage leaves invisibility.

![image](https://user-images.githubusercontent.com/6797611/35531551-fd2067f6-053f-11e8-9d13-a7fc1ac320a6.png)
