### ISSUE TITLE
Quest: The Brothers Bronzebeard

### ISSUE THREAD

**Issue by Crispybuilt** [dalaranwow/dalaran-wow#522]
**Quest The Brothers Bronzebeard** - *12973*

- **Issue**: The entire quest event is not scripted at all, it's a massive script to develop because it contains a lot of roleplay and flying objects.

**Video of how it should work:** http://www.youtube.com/watch?v=JRsRjaGV3jA

_____
http://www.wowhead.com/quest=12973/the-brothers-bronzebeard#comments

**Comment by Lothloryen** [comment]
Deployed long time ago.
