### ISSUE TITLE
[PVP] Bug in Stormwind

### ISSUE THREAD

**Issue by KatieConstance** [dalaranwow/dalaran-wow#5225]
[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: So, I have noticed lately when I'm in Stormwind, although I'm in an allied city and my PVP is disabled, it doesn't show me as rested and I can be attacked by Hordes. You can see on the screenshot that I've attached, PVP is disabled, I don't get the rested sign even though I spend more than 10-15 minutes over there. This thing happens on my character - Constance, and on another character Ilithion. 

**Expected behaviour**: Player should be rested while in an allied city and shouldn't be attacked by the opposite faction when PVP is disabled. 

**Steps to reproduce the problem**:
1. No clue
2. 
3. 

**Include proofs for this behaviour**

You can research this on several pages like http://wowhead.com or http://wowwiki.wikia.com or http://www.youtube.com/
Issues without proofs will be closed and tag On Hold will be added until the proof is provided.

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

You can research this on several pages like https://wowgaming.altervista.org/aowow/ or https://wowhead.com/

**Include Screenshots from the issue if necessary**

**Comment by TeridanDW** [comment]
Hello @KatieConstance,
I've tried to reproduce the issue on PTR, but I couldn't. Maybe the problem is generated by some of your addons.
![image](https://user-images.githubusercontent.com/6797611/34487028-2a3ff596-efdb-11e7-86ea-8cc87d1687e2.png)
![image](https://user-images.githubusercontent.com/6797611/34487033-3346e9a6-efdb-11e7-8481-961e920b3963.png)
![image](https://user-images.githubusercontent.com/6797611/34487260-43aa593a-efdc-11e7-9997-52a9048a3b62.png)

**Comment by KatieConstance** [comment]
Well, Ironforge is fine. Stormwind is the problem. I tried the pvp toggle, not working. I stayed there for more than half an hour, came to SW with a horde alt, still got attacked. No use.

**Comment by TeridanDW** [comment]
![image](https://user-images.githubusercontent.com/6797611/34492340-c97f9382-efef-11e7-8d19-77edbbb58d35.png)
![image](https://user-images.githubusercontent.com/6797611/34492346-cd836fa8-efef-11e7-957f-40a4b3f33c50.png)
![image](https://user-images.githubusercontent.com/6797611/34492777-d28e4138-eff1-11e7-8f6f-8846b0659612.png)

**Comment by KatieConstance** [comment]
Got fixed somehow :D I did try everything u said in the pic before, got a hordie to test, was still bugged. Now when I relogged seems fine. Donno if you fixed it or it got fixed itself, but thanks ^^
