### ISSUE TITLE
Applying patch failed

### ISSUE THREAD

**Issue by balancepower** [dalaranwow/dalaran-wow#5234]
Hello,

dear community of Dalaran WoW.. please could you help me out ? 
I wanted to start play on your server, just downloaded the game.. realm list is set on right.. everything was downloaded and installed correctly on uTorrent.. 
No when I log in via my mail adress, it starts to apply patch, but it stays at 0% ..
Then says i have to restart the launcher.. i did multiple times..
But stil, its ,,failing to apply the patch,, .. dont know why.. 
Please help me ! 
Thanks :)

**Comment by TeridanDW** [comment]
Hello @balancepower,

> No when I log in via my mail adress, it starts to apply patch, but it stays at 0% ..

Use your username instead of email adress and the problem will be solved.

**Comment by balancepower** [comment]
I cant use the Forum til I dont create any character in-gaime
And using my username does not solve it.
