### ISSUE TITLE
[NPC] Arcanist Uovril

### ISSUE THREAD

**Issue by Hephaetorix** [dalaranwow/dalaran-wow#5244]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Arcanist Uovril does not exist.

**Expected behaviour**: Arcanist Uovril should exist, standing in the Alliance emblem room in Dalaran

**Steps to reproduce the problem**:

1. Go to Alliance emblem room in Dalaran
2. Observe absence of NPC
3. 

**Include proofs for this behaviour**

NPC was added in patch 3.3.0 along with ICC, since it's out he should be too.

http://www.wowhead.com/npc=37942/arcanist-uovril
http://wowwiki.wikia.com/wiki/Arcanist_Uovril

**Include Screenshots from the issue if necessary**

![image](https://user-images.githubusercontent.com/27331687/34703557-8e5d1a82-f4c1-11e7-814d-42224fead008.png)

**Comment by Rushor** [comment]
http://www.wowhead.com/npc=37942/arcanist-uovril#comments:id=981209

**Comment by TeridanDW** [comment]
Works as intended on PTR.

**Comment by DanteMS** [comment]
Why is he still not there?
