### ISSUE TITLE
First boss in Karazhan loot bug.

### ISSUE THREAD

**Issue by punims** [dalaranwow/dalaran-wow#5250]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: First boss in Karazhan after being killed doesn't seem to drop loot, or loot is not accessible as if the boss wasn't tagged properly.

**Expected behaviour**: The boss should just drop the loot once he is dead.

**Steps to reproduce the problem**:

1. Kill the boss, 80% of the time he won't drop his loot.
2. If needed you can spectate one of my kills and see the bug for yourselves.

**Include proofs for this behaviour**

http://www.dalaran-wow.com/forums/input-and-assistance/community-support/topic/11259/karazhan-s-first-boss-loot

made this forum post earlier in the week, it contains enough screen shots of the bug in action
(you can see the time I said no loot and the time combat ended... clearly there was no loot)

**Comment by Lothloryen** [comment]
Hello there,

Thank you for the report, I will take a look.

**Comment by Lothloryen** [comment]
Hello again,

I do not seem able to reproduce this issue, could you provide further steps about how you achieve it, please?

**Comment by Chenocide** [comment]
Happens around 50% of my kills. Have no clue how to replicate it, cause it appears to happen randomly. Boss dies but doesn't drop anything at all.

**Comment by Lothloryen** [comment]
Hello there,

Thank you, did some changes, hopefully it will fix the issue - I can't be sure since I still do not seem able to reproduce it. Feedback will be welcome.

Regards.

**Comment by punims** [comment]
Will check during the reset tomorow, thanks.

**Comment by punims** [comment]
Hey, so I just killed the boss, the correct text appeared when he mounted, but his HP didn't reset, also no loot dropped yet again

https://imgur.com/a/8VTXp

**Comment by Chenocide** [comment]
![](https://puu.sh/ziuAN/b3732622e7.jpg "")

**Comment by Lothloryen** [comment]
Hello again,

Found the original issue that was causing it, it should be fine now- I haven't achieved to reproduce it after the fix. It is already applied and the ID's have been reseted so you can do it again this week.

Regards.

**Comment by punims** [comment]
Thanks loth, keep it up

**Comment by punims** [comment]
Also to update, the two times I went in to Karazhan he dropped the loot +
his lines were all correct, thanks for the fix ;)

Also any chance we can talk about me applying for a GM? The application
should be somewhere in your emails. But the server really needs more active
GMs, tickets are really pilling up.

<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avg.com
<http://www.avg.com/email-signature?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
