### ISSUE TITLE
Rogue Stealth Bug

### ISSUE THREAD

**Issue by Skarendy** [dalaranwow/dalaran-wow#5253]
Stealth ability says ''Allows the rogue to sneak around, but reduces your speed by 25%. Lasts until cancelled''. but when i look at buffs corner (upper right) it says ''Stealthed. Movement speed slowed by 30%'' so i give one of my unspent talents to ''Camouflage'' but it is still 30%.

**Comment by Golganeth** [comment]
Hey @Skarendy 

The buff & debuff tooltips don't take into account any talents/glyphs, so they will always show the default amount, just like on retail.

You can check the correct amount in your action bar/spellbook tooltip.

Closed.
