### ISSUE TITLE
Expose Armor + Sunder Armor

### ISSUE THREAD

**Issue by alexuktc** [dalaranwow/dalaran-wow#5254]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
The effects of both stack.
**Expected behaviour**: Tell us what should happen instead
They should not stack under any circumstance. 
**Steps to reproduce the problem**:

1.  Put Expose Armor on unit and test your damage.
2.  Also put Sunder Armor on the same unit and test your damage again.
3. Observe a noticeable increase in your hits.

**Include proofs for this behaviour**
https://wow.gamepedia.com/Expose_Armor - changelog saying they should not stack.

**Include Screenshots from the issue if necessary**

Showing the Sinisters with 5x Sunder on the target without EA.
![without ea](https://user-images.githubusercontent.com/24550199/34908038-f13ca8ec-f891-11e7-9358-71a88900358e.png)

Showing the Sinisters with 5x Sunder on the target with EA.
![with ea](https://user-images.githubusercontent.com/24550199/34908040-f535d86a-f891-11e7-806a-4fcb7b06f8f0.png)

Notes - this is at 0% ArP, with no weapon, ring or trinket procs. I used 2 1-3 damage daggerс for the smallest weapon damage variance. Samе buffs were used in both testing - 5x Sunder, FF and EA.

**Comment by Jiaku** [comment]
i can confirm that, those effects do stack.

**Comment by koenvdbrandt** [comment]
When you're testing this, could you test if Sunder Armor and the Mutated Slash from the Abomination on the Professor Putricide fight stack too? If the armor debuffs stack when they're not supposed to, maybe Sunder Armor and Mutated Slash stack too. I have no proof of this, just a feeling that they might stack.

**Comment by Jiaku** [comment]
Any news?

**Comment by Lothloryen** [comment]
Hello,

This will be fixed after the next scheduled maintenance.
