### ISSUE TITLE
Onyxia's Lair ID 1069 - Kill coincided with a server crash

### ISSUE THREAD

**Issue by Aetharon** [dalaranwow/dalaran-wow#5256]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
As the title says, the kill happened at the same time with a server crash, at 01:00 ST, 14th of January 2018. Several people got their achievement stripped after the server came back online and there was no loot.
**Expected behaviour**: Tell us what should happen instead
Pretty much none of those should happen, please address this as soon as possible.

**Include proofs for this behaviour**
![wowscrnshot_011418_020031](https://user-images.githubusercontent.com/29013316/34911291-5e70cb62-f8d0-11e7-98ef-902b4282e693.jpg)

**Comment by Aetharon** [comment]
I have contacted most of the players in need of assistance and mentioned they need to open a ticket. I will need some news before this issue is closed.

**Comment by Zarjofgt** [comment]
Aetharon you buttgoblin you know this isnt a valid issue

**Comment by Aetharon** [comment]
It is an issue that concerns at least the 9 people who got their achievement stripped by the crash. If it doesn't follow the proper structure, so be it, yet it needs to be acknowledged.

**Comment by TeridanDW** [comment]
#5148
