### ISSUE TITLE
Rogue Quest: Plundering the Plunderers

### ISSUE THREAD

**Issue by godlegos** [dalaranwow/dalaran-wow#526]
This rogue quest is supposed to give a set of tools from Wrenix's Gizmotronic Apparatus, but it doesn't. I made it all the way to the lockbox before realizing I didn't have the tools to handle slaying Polly.

**Comment by Rushor** [comment]
already fixed with https://github.com/TrinityCore/TrinityCore/commit/1521352d346c91fe7b63020b175141bc4866b41e
