### ISSUE TITLE
[Quest][Classic] Ammo for Rumbleshot - Ammo Crate Respawntimer

### ISSUE THREAD

**Issue by Blademans** [dalaranwow/dalaran-wow#5263]
Quests Ammo for Rumbleshot no quest items.

**Comment by Rushor** [comment]
https://wowgaming.altervista.org/aowow/?quest=5541

The respawntimer for that gameobject is way too high. Should be around 300 seconds - not 900 sec.

**Comment by TeridanDW** [comment]
Works as intended on PTR.
