### ISSUE TITLE
[ICC] Raging Spirits Have A Chance To Evade And Rejoin Combat After Frostmourne Room

### ISSUE THREAD

**Issue by datbunneh** [dalaranwow/dalaran-wow#5264]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Sometimes during The Lich King encounter Raging Spirits stuck in one spot while being unattackable (they evade when you try to). As far as I remember on normal mode it was not a problem since you could simply forget about them. However on heroic they seem to become active after players come back from Frostmourne Room during 3rd phase. Last attempt we had 2 of them bugged, so after returning from that room we had 3 active Raging Spirits ready to wipe us.

**Expected behaviour**: Raging Spirits should never get stuck and evade players' attacks.

**Steps to reproduce the problem**:

1. Start The Lich King encounter.
2. During any of the transition phases try to do multiple things with them - taunt them, attack them, don't touch them, try being close and far away from them while doing everything I mentioned before, try different distances and timing (as soon as they spawn or later).

**Include proofs for this behaviour**

Raging Spirits evading during The Lich King encounter cannot be intended.

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

Raging Spirit - 36701

**Include Screenshots from the issue if necessary**

TBD

**Comment by StheNoble** [comment]
seems to be similar/related to #5219

**Comment by Lothloryen** [comment]
#5219
