### ISSUE TITLE
Drak'Tharon keep mobs

### ISSUE THREAD

**Issue by descendance** [dalaranwow/dalaran-wow#527]
Some of the mobs are not linked together properly like the 2 trolls at the end of the first room,also before the dino boss there is a patrol of 1 troll on a raptor and 2 raptors that should be linked together. After the dino boss when you get up the stairs the mobs there should fight each other and there should be dead trolls on the ground instead the mobs are standing next to each other and wont fight unless you interact/pull them, there are also some batriders that are flying too low and are unattackable to the player.

Anyway this is how it should look like 
http://www.youtube.com/watch?v=LxLpkIh6twA
start from 3:50min

**Comment by Golganeth** [comment]
#2046
