### ISSUE TITLE
Midsummer NPCs

### ISSUE THREAD

**Issue by Hephaetorix** [dalaranwow/dalaran-wow#5272]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: [Stranglethorn Vale Flame Warden](https://wotlk-twinhead.twinstar.cz/?npc=25915), [Stranglethorn Vale Flame Keeper](https://wotlk-twinhead.twinstar.cz/?npc=25920), [Summer Scorchling](http://www.wowhead.com/npc=26401/summer-scorchling), and [Festival Scorchling](http://www.wowhead.com/npc=26520/festival-scorchling) appear year-round in Stranglethorn Vale.

**Expected behaviour**: These NPCs should only appear during the Midsummer event.

**Steps to reproduce the problem**:

1. Go to Stranglethorn Vale outside of Midsummer time.
2. Observe NPCs.
3. 

**Include proofs for this behaviour**

https://wow.gamepedia.com/Flame_Wardens
https://wow.gamepedia.com/Flame_Keeper
https://wow.gamepedia.com/Summer_Scorchling
https://wow.gamepedia.com/Festival_Scorchling

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

* Stranglethorn Vale Flame Warden: [25915](https://wotlk-twinhead.twinstar.cz/?npc=25915)
* Stranglethorn Vale Flame Keeper: [25920](https://wotlk-twinhead.twinstar.cz/?npc=25920)
* Summer Scorchling: [26401](http://www.wowhead.com/npc=26401/summer-scorchling)
* Festival Scorchling: [26520](http://www.wowhead.com/npc=26520/festival-scorchling)

**Include Screenshots from the issue if necessary**

![image](https://user-images.githubusercontent.com/27331687/35259845-15cd5fa8-ffd6-11e7-8173-beafb18c378f.png)

![image](https://user-images.githubusercontent.com/27331687/35259867-230be4fa-ffd6-11e7-844c-ac14ccec0cf9.png)

**Comment by Lothloryen** [comment]
Hello there,

Thank you for the report, it has been corrected already.
