### ISSUE TITLE
Judgements of the Wise

### ISSUE THREAD

**Issue by Grivvik** [dalaranwow/dalaran-wow#5278]
In the Retribution talent tree for Paladins, the skill "Judgements of the Wise" is supposed to give 25% base mana to the caster and 1% mana/5 seconds to 10 party or raid members at a 33/66/100% chance. Currently, the skill will give the 1% mana correctly but only give the caster 15% of his mana. This was verified using the Simple Unit Frames addon and setting the MP gauge to percentage while out of combat. No buff or gear to intellect was used in the test.

**Comment by TeridanDW** [comment]
Hello and thank you for the report @Grivvik.
I can't confirm the issue. The spell returns exacly 25% of the paladin's **base mana**.
http://wowwiki.wikia.com/wiki/Base_mana
![image](https://user-images.githubusercontent.com/6797611/35532534-3cefb708-0543-11e8-9424-70f2ba645fb3.png)

Next time please don't delete the template but fill it instead, thank you.
