### ISSUE TITLE
Getting Unstuck

### ISSUE THREAD

**Issue by NateDogg1232** [dalaranwow/dalaran-wow#5286]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

I'm a bit of an idiot and got my character (Finnthedog-Agalon) stuck in a way that is probably stupid. My character had fallen off of Teldrassil right above Rut'Theran Village, and in an attempt to get to my character to ressurect it, I had thrown my ghost down there too, and missed the branch my character had hit. As a result, my wisp is stuck in Rut'Theran Village with no way to get to my corpse

![bildo](https://user-images.githubusercontent.com/12480453/35783261-18af923a-09b9-11e8-9d43-e04e6145cb1b.png)

**Comment by Golganeth** [comment]
Greetings, I have revived you in-game. 
In case something similar happens to you again, keep in mind that you can use the in-game "unstuck" option. All you have to do is:
> - Click the red question mark in your interface bar
> - Click "Character Stuck"
> - Click "Auto-Unstuck"

If your character is dead while you do this, seemingly nothing will happen, but if you re-log you will be teleported to your starting zone, where you can talk to the NPC Spirit Healer and get yourself revived (if you do this and you are above level 10 you will get a ress sickness though).

Hope this helped, cheers.
Closing up.
