### ISSUE TITLE
PvP combat rule

### ISSUE THREAD

**Issue by Jiaku** [dalaranwow/dalaran-wow#5294]
[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
Combat PvP rule is 6 seconds right now.
**Expected behaviour**: Tell us what should happen instead
Combat PvP rule should be 5 seconds. It is always been 5 seconds, ive got no clue why it has been changed. You can ask anyone who does PvP decently they will say 5 seconds is how things should be
**Steps to reproduce the problem**:

1. Get in combat
2. Wait till you leave
3. 

**Include proofs for this behaviour**

You can research this on several pages like http://wowhead.com or http://wowwiki.wikia.com or http://www.youtube.com/
Issues without proofs will be closed and tag On Hold will be added until the proof is provided.

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

You can research this on several pages like https://wowgaming.altervista.org/aowow/ or https://wowhead.com/

**Include Screenshots from the issue if necessary**

**Comment by alexuktc** [comment]
http://wowwiki.wikia.com/wiki/Combat

**Comment by Jiaku** [comment]
Thanks for the link, it says 5 seconds.

**Comment by Johanes022** [comment]
Sometimes in arena it takes up to 15 seconds to leave combat.

**Comment by AttendantTock** [comment]
Hello,

I can confirm that on the current PTR, the timer to get out of PVP combat seems to be 6 seconds.
https://www.youtube.com/watch?v=KC2duY2Im0Q

**Comment by Johanes022** [comment]
https://youtu.be/IZuLhUYPYwA?t=917

**Comment by Lothloryen** [comment]
Hello there,

Thank you for the reminder, corrected already.

**Comment by Lothloryen** [comment]
Hello there,

Thank you for the reminder, corrected already. We introduced some fixes not long ago @Johanes022  that should have fixed those situations.
