### ISSUE TITLE
Fear pathing

### ISSUE THREAD

**Issue by Jiaku** [dalaranwow/dalaran-wow#5295]
[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
For the love of god, it is so broken you literally can not predict where target will end up because you can not trust yourr own screen. At the end of fear(1-2 seconds left on fear), feared target runs/teleports to other place.
**Expected behaviour**: Tell us what should happen instead
Fear should end where it shows and not somewhere else.
**Steps to reproduce the problem**:

1. 
2. 
3. 

**Include proofs for this behaviour**

You can research this on several pages like http://wowhead.com or http://wowwiki.wikia.com or http://www.youtube.com/
Issues without proofs will be closed and tag On Hold will be added until the proof is provided.

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

You can research this on several pages like https://wowgaming.altervista.org/aowow/ or https://wowhead.com/

**Include Screenshots from the issue if necessary**

**Comment by Golganeth** [comment]
Give feedback on #1447 

Closing up
