### ISSUE TITLE
Cloak and Chains of ice interaction

### ISSUE THREAD

**Issue by Jiaku** [dalaranwow/dalaran-wow#5296]
[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
If you press cloak you will resist slow but not Frost Fever
**Expected behaviour**: Tell us what should happen instead
You resist slow and frost fever
**Steps to reproduce the problem**:

1. use chains of ice on cloak
2. 
3. 

**Include proofs for this behaviour**

You can research this on several pages like http://wowhead.com or http://wowwiki.wikia.com or http://www.youtube.com/
Issues without proofs will be closed and tag On Hold will be added until the proof is provided.

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

You can research this on several pages like https://wowgaming.altervista.org/aowow/ or https://wowhead.com/

**Include Screenshots from the issue if necessary**

**Comment by Golganeth** [comment]
Greetings.
Cloak of Shadows doesn't grant an immunity effect, it just increases your chance to resist spells by 90%.
Please open another report if what you meant is that Chains of Ice effect never goes through, and only frost fever can apply if lucky enough.

Closing up

**Comment by Jiaku** [comment]
Would be cool if you could check the issue before closing it. It happens 100% time otherwise i woudn't report this issue.

Open thread.
