### ISSUE TITLE
mouse cursor bug

### ISSUE THREAD

**Issue by gnaruwar** [dalaranwow/dalaran-wow#5299]
**Current behaviour**:  i really never had any kind of problems untill i decided to download dalaran wow and i got this problem: whenver i try to rotate my cam with left or right click the cursor jump to the center of the screen, and sometimes my camera rotates of some grades (i cannot confirm with certain this cause when this happen it's a lot fast)

**Expected behaviour**:  the cursor shouldn't jump and camera shoulden't rotate

**Steps to reproduce the problem**:
after various research on web i tried some things:
1. modify mouse and in game sensibility
2. i changed in my Windows settings the zoom from 150% to 100%

**Include proofs for this behaviour**
there's a link of an other user that have my same exactly problem :

https://www.youtube.com/watch?v=pIaSqrWIoJs

thank you for helping us!

**Comment by Jiaku** [comment]
Id suggest Interface>Camera>Camera following Style change in to never adjust.
But sometimes it happens with me as well and restarting wow usually helps.

**Comment by Golganeth** [comment]
Bugtracker is for ingame server-side issues. This is directly related to your client and/or possibly camera settings. Please make sure to check them out.

Closing up
