### ISSUE TITLE
The thane of Voldrune quest

### ISSUE THREAD

**Issue by descendance** [dalaranwow/dalaran-wow#530]
When you mount the dragon and if you use the wing buffet or pretty much any other ability on Thane Ericsson, the dragon will go to attack him in meele range and just get stuck in the bottom of the tower, where thane is,(no matter what, i was flying on the dragon in front of thane and still the dragon went on his own to meele the NPC and than plunged into the ground and got stuck in front of the tower entrance). You will have to unmount the dragon and reset combat and pick the dragon again. 

In the end what i had to do is mount the dragon and fly to the roof of the tower and dissmount it and fight Thane 1v1.

**Comment by Golganeth** [comment]
Hotfixed. Now players won't need a flying mount to kill the NPC manually.

**Comment by Mantigora** [comment]
Thane Torvald Eriksson is now trying to hide. LoS.

![wowscrnshot_020916_235932](https://cloud.githubusercontent.com/assets/10964125/12932019/52ba3712-cf89-11e5-9860-598db239ab92.jpg)

**Comment by Lothloryen** [comment]
Working as intended now.

**Comment by Dancingirl** [comment]
No it ain't. On this day, it's still impossible to kill thane with the dragon, it always say i'm out of range and when i try to knock him with wing buffet or get too close, I get knocked back at the bottom of the tower.
