### ISSUE TITLE
[ICC raid] Mobs randomly disappear when they reach 5% health

### ISSUE THREAD

**Issue by JohnADC** [dalaranwow/dalaran-wow#5310]
**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
Inside Icecrown Citadel raid trash mobs and mobs spawned by boss randomly sometimes disappear when they reach 5% health. Obviously shouldn't happen. 
Also it seems they are not lootable when disappearing this way.

**Expected behaviour**: Tell us what should happen instead
They shouldn't disappear?

**Steps to reproduce the problem**:

Kill trash or boss spawned mobs inside icc raid. When some of them reach 5% hp they disappear.

**Include proofs for this behaviour**
Happens randomly and i have no capabilitys to film it.

You can research this on several pages like http://wowhead.com or http://wowwiki.wikia.com or http://www.youtube.com/
Issues without proofs will be closed and tag On Hold will be added until the proof is provided.

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

You can research this on several pages like https://wowgaming.altervista.org/aowow/ or https://wowhead.com/

**Include Screenshots from the issue if necessary**

**Comment by Lothloryen** [comment]
Hello there,

Thank you very much, this is a very weird issue, I will take a deep look. Could you please let me know when did this start happening? Since this is the first time I hear about this, I guess is not happening a lot or it only does under very specific circumstances - every additional information will be welcome.

**Comment by JohnADC** [comment]
I think i noticed it two weeks ago, but i can't be sure since I couldn't raid for two weeks before that. Happens actually quite often, I guess no one really cares much. Happened for example about 6-7 time in the last raid, we only did pp hc and try lk hc, trash before pp a few of them disappeared and two times it happened with raging spirits aswell at 5%.
