### ISSUE TITLE
Magic Rooster visual bug

### ISSUE THREAD

**Issue by punims** [dalaranwow/dalaran-wow#5313]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
Hey, so if you mount your Magic Rooster while already mounting a magic rooster, a visual bug occurs and you'll be seen as if you're running at 100% speed though you're mounted.

**Expected behaviour**: Tell us what should happen instead
Well I'm not even sure you should be able to cast a mount while mounted, Magic Rooster acts pretty weird in general. But yeah this is just one other problem. If you mount the magic rooster while mounted the visuals shouldnt change.

**Steps to reproduce the problem**:

1. Mount your rooster
2. Cast the mount again
3. you wont see the rooster

**Include proofs for this behaviour**

https://imgur.com/a/tE5wH

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

You can research this on several pages like https://wowgaming.altervista.org/aowow/ or https://wowhead.com/

**Include Screenshots from the issue if necessary**

**Comment by Rushor** [comment]
Cannot reproduce this on PTR
