### ISSUE TITLE
[Quest][Classic] Garments of Spirituality priest quest (troll) not working

### ISSUE THREAD

**Issue by magohamote** [dalaranwow/dalaran-wow#5319]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**:
In the class quest Garments of Spirituality, for priest, horde, troll, I cannot heal Grunt Kor'ja.

**Expected behaviour**:
I should be able to heal Grunt Kor'ja and reinforce her.

**Steps to reproduce the problem**:
1. go next to Grunt Kor'ja 
2. try to heal with Lesser heal (rank 2) - not working
3. try to reinforce with Power word: Fortitude (rank 1) - not working

**proofs for this behaviour**
https://youtu.be/Q9tZKK-99Zo

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**
http://www.wowhead.com/npc=12430/grunt-korja

**Comment by Rushor** [comment]
looks like the creature is immune to PC on reset. will remove that flag for the script on reset.
