### ISSUE TITLE
Spell Alert disapeared

### ISSUE THREAD

**Issue by estebanjim** [dalaranwow/dalaran-wow#5322]

**Comment by estebanjim** [comment]
Hello, i'm trying to figure out what is wrong with my game, you see, i'm playing fire mage and i would like to have a spell alert when my pyroblast procs, i know the spell alerter option should be in the interface options of the game but i havn't found it and i also know it's not an addon issue because it doesn't work even with all the addons disabled. I get the buff of Hot Streak when pyroblast procs but no shiny border around the spell in the bar or shiny visual effect on the screen. Help me please thanks.

**Comment by Zarjofgt** [comment]
This was not implemented in wotlk

**Comment by Golganeth** [comment]
Invalid report.

**Comment by Golganeth** [comment]
Invalid report. In WotLK some addons may be needed in order to get some alerts displayed on the screen.

Closing up.
