### ISSUE TITLE
[Spell] Stacking Shattrah Flasks

### ISSUE THREAD

**Issue by alexuktc** [dalaranwow/dalaran-wow#5326]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
I can stack flasks. The items in question are:
Shattrah Flask of Relentless Assault and Flask of Endless Rage.
**Expected behaviour**: Tell us what should happen instead
They should not stack. 
**Steps to reproduce the problem**:
It is kind of convoluted, but I stumbled upon it after one of my tbc raids.

1.  Go into a raid where Shattrah Flask of Relentless Assault can be used. 
2. Use a mage portal to get out of it. 
3. You will lose the buff of the flask but the AP bonus will remain. 

**Include proofs for this behaviour**
I will post screenshots of my AP with the Flask of Endless Rage on me and without. Once I run out of the Shattrah Flask of Relentless Assault I will post a 3rd image.

I don't need to post proof that it should not happen. 

With 2 Flasks:
https://imgur.com/7oj3Osw

Without the normal flask: (no Shattrah flask buff is present)
https://imgur.com/wQ4ztrZ

My Flask ran out with my poisons. You can see the difference in AP. I even caught the buff fading
https://imgur.com/dhqPZrP

I assume this happens with other flasks too. As I have recreated the issue that would be up to you to find out.

**Comment by alexuktc** [comment]
An issue this big is not getting any attention?

**Comment by alexuktc** [comment]
Updating. All flasks can be used outside of the raids they are designated for.
All flasks stack with the lvl 75 craftable versions. They also stack with each other! I have 6 flasks currently active on my character and I can choose a lvl 75 flask for a 7th. 

While the bonus for physical dps is good, it is outright amazing for caster dps as they have 2 flasks they can use for a bonus higher than what the lvl 75 flask provides.

**Comment by kysqt** [comment]
Delet

**Comment by alexuktc** [comment]
Update:

http://www.wowhead.com/item=34537/bloodberry-elixir Bloodberry Elixir works this way as well. You get it in SWP, go out and you can stack it with everything else, since the buff disappears but the actual bonuses remain.
