### ISSUE TITLE
Dissapearing/MiA bosses in 5 man dungeons/heroics

### ISSUE THREAD

**Issue by hairychestfan** [dalaranwow/dalaran-wow#5328]
**Current behaviour**:  
I have witnessed some bosses disappear mid fight never to be seen or heared from again.. this has happened to me with the following bosses:  
*Grand Magus Telestra* (The Nexus)(making the dungeon unable to complete due to not killing all bosses) she dissapeared just before she was about to do the split i think we were mid fight with her.
*Novos The Summoner* (Drak Thalon Keep)  2 times, once he just wasn't there and second time he disappeared when we nearly killed him he was on 10% health..
*Ley Guardian Eregos* (The Oculus) this has happened to me 3 times on this boss. one time he was not in the dungeon at all. second time during a fight when he was at about 30% health, and third time also during fight he vanished. he was on about 60% health
This does not happen every time but occasionally and its really annoying. 

**Expected behaviour**: Bosses should be there and killable and lootable

**Steps to reproduce the problem**:

1. Que up for dungeons
2. Engage in combat with the bosses (if they are there)
3. Repeat until it happens to you (it will)

**Include proofs for this behaviour**

http://www.blogcdn.com/www.joystiq.com/media/2008/10/the-oculus.jpg

http://www.wowhead.com/npc=27656/ley-guardian-eregos
http://www.wowhead.com/npc=26631/novos-the-summoner
http://www.wowhead.com/npc=26731/grand-magus-telestra

**Comment by MalkaviaDW** [comment]
Hello, 

Thank you for the report, write a ticket in-game so a Game Master can be present with you and take a look next time, please.

Cheers!
