### ISSUE TITLE
RaF email problem

### ISSUE THREAD

**Issue by sidomin97** [dalaranwow/dalaran-wow#5341]
2 my friends cant see anything in their e-mail boxes, but i sent invtitations for RaF

**Comment by Golganeth** [comment]
RaF system works fine, so make sure you followed all the steps properly. Here is a detailed guideline about the feature from our forums: [Check out this link.](http://www.dalaran-wow.com/forums/news-and-rules/rules-and-guidelines/topic/2565/how-to-use-the-recruit-a-friend)

If you did all the steps, check the spam folder of your inbox, just in case. If the issue persist please make an in-game ticket.

Cheers, closing up.
