### ISSUE TITLE
Skipping lines in talent tree

### ISSUE THREAD

**Issue by lkrocek** [dalaranwow/dalaran-wow#5346]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Please do not close or delete this ticket, I found an issue which is extremely hard to reproduce it I was trying to reproduce it but without success, so I want to keep this ticket opened if someone else will be lucky with this.**

**Current behaviour**: In some situation I was be able to do reset of **some** talent points as a furry warrior I lost first 3 lines of talent points in arms tree (talent points on 4th line persisted and was able use 15 talent points whenever I can).

In case I was be able to figure out some similar but not same issue (please do not fix this maybe is a key to discovery the issue) and also thing this is about 80% reproducible: 
1. Queue random dungeon finder for heroic dungeons
2. Go to trainer and reset my current talent tree
3. Setup new tree
4. Enter the RDF
5. Re-spec on second talent spec
6. Re-spec back once more on new one
7. Observe the tree has been completely reset
 
**Expected behaviour**: not be able reset **some** points

I feel it's not limited by class, but maybe by first tree in order.

**Comment by cofpa** [comment]
i was lvling my dk and i can put my talents in one row of frost.... but then the second row cant put any of the. now i have 42 unspent talent points cant q for rdf or anything please help

**Comment by Rushor** [comment]
combined with https://github.com/dalaranwow/dalaran-wow/issues/5471
