### ISSUE TITLE
Friendly reputation with Timbermaw Hold in Winterspring/Felwood but right-clicking attacks

### ISSUE THREAD

**Issue by atomicsitup** [dalaranwow/dalaran-wow#5352]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: I have Friendly reputation with Timbermaw Hold and am attempting to turn in the quest "Winterfall Ritual Totem". Kernda in Timbermaw Hold has a question mark above him to turn in the quest, but when I mouseover the NPC it has a knife and when I try to right-click the NPC it starts attacking and I can never turn in the quest.

**Expected behaviour**: I should not be able to attack friendly targets and also be able to turn in completed quests to them.

**Steps to reproduce the problem**:

1. Right-click engages Kernda in combat
2. Tried to set key-binding to interact with target but has the same effect.
3. 

http://www.wowhead.com/npc=11558/kernda

http://www.wowhead.com/quest=8471/winterfall-ritual-totem

![wowscrnshot_031618_175326](https://user-images.githubusercontent.com/10440365/37548013-142a90a8-2943-11e8-8e65-ae5694dcd7e8.jpg)

**Comment by panoptikoe** [comment]
Have you unchecked the 'at war' box in the reputation box?

**Comment by atomicsitup** [comment]
Ahh jeez, I feel silly. Thank you so much.
