### ISSUE TITLE
[Quest][Northrend] The Air Stands Still [13125]

### ISSUE THREAD

**Issue by Sagrath** [dalaranwow/dalaran-wow#536]
The Ebon Watcher at the Valley of Echoes in Icecrown wants you to kill Salranax the Flesh Render, Underking Talonox and High Priest Yath'amon.
Now two of each is spawned for diferrent phasemasks for phase mask 2 and phase mask 128 The problem is that the phase mask is siwtched amoung the two createrus and the one the player can kill does not grant the the kill credit.
Salranax the Flesh Render - http://www.wowhead.com/npc=30829
Underking Talonox - http://www.wowhead.com/npc=30830
High Priest Yath'amon - http://www.wowhead.com/npc=30831
Quest - http://www.wowhead.com/quest=13125/the-air-stands-still

**Comment by deltafoxnine** [comment]
Quest is seriously bugged. 

On Salranax the NPC won't help unless they somehow get hit by him, i.e I use Divine Shield so he aggroes the NPC instaed.

On Talonox I just don't get the credit even though i do the most damage. But atlease the NPC helps and don't let me die.

Yath'amon worked fine.

**Comment by Cone182** [comment]
When I used the provided quest item, it did do nothing.

**Comment by AgeAgainst** [comment]
As of 26 November 2015, this quest still doesn't work properly.  No credit for killing King Talonox with death knights.

**Comment by Reechter** [comment]
Can confirm as of 01 January 2016. Nuking with everything I am worth and still cannot get credit for the kill using the summoned DKs.

**Comment by codyflood** [comment]
Updating that as of February 20th 2016, quest still doesn't work, not receiving credit for kills

**Comment by Vandreth** [comment]
Cannot receive credit for any of the kills when summoning a knight of the Ebon Blade.

**Comment by Reechter** [comment]
To those struggling to finish this quest;

The only way to guarantee you get credit is by NOT using the summoned mobs. The best way is to group up with a few others and do it like a group quest. This is complicated by the fact that the quest takes place in a phased zone, so only people at the same stage of the quest as you can help you.

Good luck, let's hope they fix this soon.

**Comment by Lothloryen** [comment]
Hello there,

This quest has been corrected and it is already on the live server.

Thank you.

**Comment by ImprezaWoW** [comment]
Recently I noticed a decent amount of people complaining about High Priest Yath'amon not giving credit, even after trying multiple times. All tickets were about this one mob in particular. Maybe it's worth looking over?

**Comment by Golganeth** [comment]
What @ImprezaWoW said. There's some issues with getting credit, especially with that one NPC. Might be worth adding a script to ease getting kill credit from the Creatures oF this quest (similarly to Heated Battle)

Salranax the Flesh Render - **[ID: 30829](http://www.wowhead.com/npc=30829)**
Underking Talonox - **[ID: 30829](http://www.wowhead.com/npc=30830)**
High Priest Yath'amon - **[ID: 30829](http://www.wowhead.com/npc=30831)**

**Comment by Rushor** [comment]
todo: implement flagextra: deal damage like a player

**Comment by Rushor** [comment]
now you need to do at least 1 dmg in order to get the questcredit (no matter how much dmg the helpfull creature dealed on the victim)

**Comment by Zibathy** [comment]
Still doesn't work on Kirin Tor.
![wowscrnshot_041117_155841](https://cloud.githubusercontent.com/assets/7729864/24930724/2980e05c-1ed0-11e7-9adf-0fc53e646e7e.jpg)
![wowscrnshot_041117_155958](https://cloud.githubusercontent.com/assets/7729864/24930725/298117fc-1ed0-11e7-8389-e19136890f1e.jpg)
![wowscrnshot_041117_160011](https://cloud.githubusercontent.com/assets/7729864/24930723/297ef328-1ed0-11e7-9ba3-949d1d4d05d7.jpg)
![wowscrnshot_041117_160112](https://cloud.githubusercontent.com/assets/7729864/24930726/29848c8e-1ed0-11e7-9101-21d59f6b056f.jpg)

**Comment by UncleCrust** [comment]
I get no credit for killing any of them using my lvl 78 hunter (13.5k hp). I shoot first then call the NPC and, of course, stay in the battle hitting with everything I have along with my pet.
March 26, 2020.
