### ISSUE TITLE
[Mechanic] Loot Issue for questing with party

### ISSUE THREAD

**Issue by HS-Disq** [dalaranwow/dalaran-wow#5367]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)

Quests that require you to loot items, for instance Stromgarde Badges in Arathi Highlands, are showing on corpses that they can be looted by everyone. These quest items aren't shared as they aren't unique. That is by design. However, if one person loots it, the other party members still see it sparkle and can loot it. The loot window opens and shows nothing. The sparkle stays until the corpse disappears. While this is confusing at times, it also prevents mobs from being skinned.

**Expected behaviour**: Tell us what should happen instead

Once a quest item is looted, it should not sparkle anymore. While it's not bound to whomever the loot is assigned to, it should stop if it's already looted.

**Steps to reproduce the problem**:

1. Have a party of 2 or more people.
2. Have a quest that requires you to loot non-unique Quest Items. Example being Stromgarde Badges, but any quest will do (we have seen this behaviour from level 10 to 37).
3. Kill mobs that drop the loot required for the quest. All party members will see it.
4. One loots the quest item, the rest will still see it sparkle and can loot it.

**Include proofs for this behaviour**

I do not have proof of this at this moment. However, it is easily reproducible and I can give the proof at some point tonight (CEST timezone).

**Include Screenshots from the issue if necessary**

**Comment by Rushor** [comment]
Ref: https://github.com/TrinityCore/TrinityCore/commit/d8911a9dd6c4458d05e3a806f95170d6400726ee
