### ISSUE TITLE
Open-world mobs with loot despawning too fast

### ISSUE THREAD

**Issue by HS-Disq** [dalaranwow/dalaran-wow#5368]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)

Open-World mobs that have loot on them despawn too fast. This is with all open-world mobs, this behaviour is not seen with bosses. At the current time, they are despawning within two minutes after killing them without them being looted.

**Expected behaviour**: Tell us what should happen instead

Mobs that are looted should despawn in two minutes.
Mobs that are uninspected should despawn in five minutes.

Every time you inspect a mob for it's loot, the timer should reset back to five minutes if it still has loot on it. Once all loot of the mob is gone, it should despawn after two minutes.

**Steps to reproduce the problem**:

1. Kill a mob
2. Time it without looting it. It should be under 2 minutes.
3. Kill a mob
4. Time it and loot it. It should be under 2 minutes. (Which should be the case for this one as it's looted).

**Include proofs for this behaviour**

While there never was any sort of information from Blizzard's end, patch 2.4.2 did showed one line in it's patch notes that read this:

"Looting a boss while a player is outside of the instance will no longer cause the corpse to despawn in 2 minutes if the player still has loot on the corpse."

http://us.battle.net/wow/en/game/patch-notes/2-4-2

It's written way at the bottom under Bug Fixes.

In 2012, which was during the time of Mists of Pandaria, this was tested on Bloodsail Buccaneers by a mage using the Mana Shield Timer. His findings can be found here.

https://gaming.stackexchange.com/questions/78923/how-long-do-corpses-remain

**Include Screenshots from the issue if necessary**

**Comment by Rushor** [comment]
duplicate and moved to https://github.com/dalaranwow/dalaran-wow/issues/971
