### ISSUE TITLE
why cant i login

### ISSUE THREAD

**Issue by Consonan** [dalaranwow/dalaran-wow#5370]
1. i cant login to game server (in the username and password filling part)
2. even if i managed to login, the "retrieving character info" part would take a really long time, in the end it just brings me to login screen and says "disconnected form server"
3. even if i managed to pick a character and play, it would stuck on the first loading screen of the game for more than 15 minutes, then it just back to the login screen and says "disconnected from server"
4. even if i managed to get pass through the loading scree, i can only play for about 10-15 minutes, before the game would stop and lag, i cant do anything, then it brings me back to the login screen and says "disconnected form server"

i have try to change realms, tried to disable firewall, tried anything, but nothing seems to make a difference

P.S i have a really really fast internet, so this is not the problem

**Comment by Rushor** [comment]
Invalid report. The bug tracker only lists in-game issues with quests, NPCs and such. This is not a place to discuss or post constantly, please keep the bug tracker clean for the Dev, guys. Feel free to use the [Community Support](http://www.dalaran-wow.com/forums/input-and-assistance/community-support) or [General Discussion](http://www.dalaran-wow.com/forums/community/general-discussion) section of the forums for that purpose. 

The server is fine so it must be related to your computer / ISP. Check out this [thread](http://www.dalaran-wow.com/forums/input-and-assistance/community-support/topic/7954/constant-disconnection-every-hour) for possible solutions to the issue you're having.

Closed.
