### ISSUE TITLE
(Tallent) Improved Mark of the wild

### ISSUE THREAD

**Issue by schoefel** [dalaranwow/dalaran-wow#5371]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
The talent "Improved Mark of the Wild isn't increasing the buff properly
**Expected behaviour**: Tell us what should happen instead
Improved Mark of the Wild(Restoration talent) should increase the effects of Mark of the Wild by 40%
**Steps to reproduce the problem**:

1. Take Improved Mark of the Wild
2. Cast Mark of the Wild
3. notice that the numbers in the tooltip of the spell and the buff are very different

**Include proofs for this behaviour**

https://www.dropbox.com/s/focpiz0upl02bnq/Screenshot%202018-03-31%2012.25.29.png?dl=0
https://www.dropbox.com/s/urcnw6xzt27nb2d/Screenshot%202018-03-31%2012.26.02.png?dl=0

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**
Improved mark of the Wild(rank 2): https://wowgaming.altervista.org/aowow/?spell=17051
Mark of the Wild(rank 8): https://wowgaming.altervista.org/aowow/?spell=26990
You can research this on several pages like https://wowgaming.altervista.org/aowow/ or https://wowhead.com/

**Include Screenshots from the issue if necessary**

**Comment by schoefel** [comment]
The same goes for Gift of the Wild: https://wowgaming.altervista.org/aowow/?spell=26991

**Comment by Rushor** [comment]
-- Retail Bug --
This is same case as on retail, where they don't scale. The buff & debuff tooltips don't take into account any talents/glyphs, so they will always show the default amount.

You can check the correct amount in your action bar/spellbook tooltip.

Closed.

Also see: https://github.com/dalaranwow/dalaran-wow/issues/3928
