### ISSUE TITLE
[Event] Hard Boiled achievement

### ISSUE THREAD

**Issue by HS-Disq** [dalaranwow/dalaran-wow#5374]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)

The achievement Hard Boiled for Noblegarden is not popping up. In a party of 3 where we used Blossoming Branch on each other, the rabbits are pooping eggs, but no achievement is popping up.

**Expected behaviour**: Tell us what should happen instead

Once the rabbit poops in the Golakka Hot Springs in Un'Goro, the achievement should pop up.

**Steps to reproduce the problem**:

1. Either open a Brightly Coloured Egg to become a rabbit or use Blossoming Branch to become one.
2. Go to Golakka Hot Springs in Un'Goro.
3. Wait a minute.

**Include proofs for this behaviour**

https://www.youtube.com/watch?v=D-ArdOISG5w

**Comment by alexuktc** [comment]
We did that in parties of 2 (both last year and this year) and it worked like a charm.

**Comment by HS-Disq** [comment]
It could be that Noblegarden is required? Cuz I noticed a few hours later that all the Brightly Coloured Eggs and Noblegarden Vendors are gone, even though it's still Easter.

**Comment by Rushor** [comment]
Yes Nobelgarden is required. 

Works very well on PTR if the event is active.

![GitHub Logo](https://i.imgur.com/7sqWsaL.jpg)

You may need to contact a gamemaster which will help you.
