### ISSUE TITLE
[Quest][Northrend] It Goes to 11...

### ISSUE THREAD

**Issue by Crispybuilt** [dalaranwow/dalaran-wow#538]
**Quest It Goes to 11...** - *11421*

- **Issue:** Players are unable to interact with Vrykul Harpoon Gun (ID:27992) after using the item **Harpoon Control Mechanism** (ID:34032) on it.

- **How it should work** - There should be Dragonflayer Defender (ID:24533) spawning all over the place *(and they will attack you)* once player attempts to use the **Vrykul Harpoon Gun**. You also have to destroy the buildings and you get general message upon destroying:

- *Direct hit on the dockhouse! Dragonflayer Defenders have been alerted!* - when you destroy **Dragonflayer Dockhouse**

- *The longhouse is destroyed Alarms can be heard in the distance.* - when you destroy **Dragonflayer Longhouse**

- *The Vrykul Storage Facility is up in flames! Dragonflayer Defenders have been alerted!* - when you destroy **Dragonflayer Storage Facility**

_____________

**Simply add trigger zones/bunnies down there once the arrow hits the location, give player a credit.**

- **Video how it should work**: http://www.youtube.com/watch?v=NGwvNoZo5PU

______________

http://www.wowhead.com/quest=11421
http://www.wowhead.com/item=34032
http://www.wowhead.com/npc=24533/dragonflayer-defender
http://wotlk.openwow.com/object=19301

**Comment by Lothloryen** [comment]
Hello there,

This quest will be working after the next realm restart.

Thank you.

**Comment by sixele** [comment]
Currently the Defenders do not spawn (you can burn down the houses, though), might be because of the short view distance?

**Comment by Ston3y** [comment]
There are no Defenders visible, but when you activate the harpoon's second ability it magically kills one of the nonexistent defenders. Activate it eight times and you complete the quest.

**Comment by Sagrath** [comment]
Confirmed no defenders spawn

**Comment by beregas** [comment]
Still cannot see Defenders
