### ISSUE TITLE
(Please, read) wrong item

### ISSUE THREAD

**Issue by natokra** [dalaranwow/dalaran-wow#5388]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: 
I changed some vote points for 3 heirloom parts but I picked wrong since I think that the item will give me intelect or agility depending on my speciality as the item said but i think that the item db is displaying the blizzard db item. 

the item's id that I want to change are:
48687 (chest)
44103 (shoulder)
50255 (finger) x1

the item's id that i want are:
48689 (chest)
42952 (shoulder)
42991 (trinket)

**Expected behaviour**: can you change my two parts for the two that I wanted? 

Thanks anyway

**Comment by Golganeth** [comment]
This is the ingame bugtracker, which lists ingame issues that can affect players. Please take this one to the in-game support ticket system.

Closing

**Comment by natokra** [comment]
i submited a ticket 5 days ago and still don't have an answer. That's why I post here

**Comment by StheNoble** [comment]
5 days? pls be patient, others waiting weeks and months sometimes. (pls dont shoot the messanger)
