### ISSUE TITLE
[Achievement] I've had worse

### ISSUE THREAD

**Issue by alexuktc** [dalaranwow/dalaran-wow#5392]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
You kill the Black Knight without anyone in the party taking damage from an explosion and you do not get the achievement.
**Expected behaviour**: Tell us what should happen instead
The party should get the achievement if you manage to do so.
**Steps to reproduce the problem**:

1.  test
2. ?
3. Profit

http://www.wowhead.com/achievement=3804/ive-had-worse

**Comment by Rushor** [comment]
https://wowgaming.altervista.org/aowow/?achievement=3804

**Comment by Rushor** [comment]
Yes an Achievement spellhit script is missing there.

**Comment by Rushor** [comment]
![GitHub Logo](https://i.imgur.com/oLlWIJn.jpg)
