### ISSUE TITLE
Misc: Chat /Busy Command

### ISSUE THREAD

**Issue by Daveonx** [dalaranwow/dalaran-wow#54]
When players use the /busy command they still receive whispers when they shouldn't.

**Comment by npmusicftw** [comment]
If I am not mistaken, the whisper has always gone through when /dnd was initiated. It was just "acceptable" not to respond because the system sent the above message "-name- does not wish to be disturbed."

**Comment by Rushor** [comment]
if i understand everything right, http://us.battle.net/wow/en/forum/topic/2522075136 shows that the whisper with dnd flag is working correctly - closing

**Comment by Golganeth** [comment]
Not so sure about that one @Rushor. If I recall correctly, in WoTLK the feature would block every incoming whisper.

That thread is from Cataclysm (release: 2010, thread is from 2011). Gonna try and find some relevant info about this.
