### ISSUE TITLE
Quest/NPC: Potential for Brain Damage = High / Ethereum Essence

### ISSUE THREAD

**Issue by Crispybuilt** [dalaranwow/dalaran-wow#540]
**Quest Potential for Brain Damage = High** - *10385*
**NPC Ethereum Essence** - *29482*

- **Issue**: You are unable to attack the NPCs **Ethereum Relay** *(ID:20619)* after you use the **Ethereum Essence** *(ID:29482)* on yourself. It says it's invalid target or not in the line of sight.
In the other hand, they are easily seeable and targetable, pathfinding issue probably.

- **Related to issue**: #266, #509

- **How it should work:** You should be able to attack the NPCs once you see them. Currently only Game Masters with .damage can kill them and get the credit.

_________________________
http://wotlk.openwow.com/quest=10385
http://www.wowhead.com/quest=10385/potential-for-brain-damage-high
http://www.wowhead.com/item=29459
http://wotlk.openwow.com/npc=20619
http://wotlk.openwow.com/item=29482

**Comment by Demlock** [comment]
Works fine

**Comment by Daveonx** [comment]
Tested and working perfectly.

**Comment by Golganeth** [comment]
I think it could use some extra NPCs here and there. I counted like 10 in the whole area and 15 are needed
http://wotlk.openwow.com/npc=20619
