### ISSUE TITLE
Quest: Birds of a Feather

### ISSUE THREAD

**Issue by Crispybuilt** [dalaranwow/dalaran-wow#541]
**Quest Birds of a Feather** - *9397*
**THE QUEST IS WORKING AND DOABLE BUT NOT IN A PROPER WAY - too easy to complete**

- **Issue**: The quest doesn't work properly, it has to be corrected. Basically the issue is that you can use the **Empty Birdcage** *(ID:23485)* everywhere in the Hellfire Zone and it will automatically give you the item: **Caged Female Kaliri Hatchling** and complete your quest giving you credit. - that is wrong.

- **How it should work** - You have to go to zone **Den of Haal'esh** in Hellfire Peninsula & click on the objects *181582* - **Kaliri Nest**, the object will despawn and it will spawn either **Male Kaliri Hatchling** *(17039)* (70% chance Male) or **Female Kaliri Hatchling** *(17034)* (30% chance Female). Your goal is then to Capture Female Kaliri Hatchling and then you get the credit. Target it and use the **Empty Birdcage** *(ID:23485)*

_______________
http://wotlk.openwow.com/npc=17039
http://wotlk.openwow.com/npc=17034
http://www.wowhead.com/item=23485
http://www.wowhead.com/quest=9397/birds-of-a-feather

**Comment by Demlock** [comment]
Confirmed

**Comment by Rushor** [comment]
already works fine 

http://i.imgur.com/M2uR432.jpg
http://i.imgur.com/9JV1DNA.jpg
