### ISSUE TITLE
The sound is crackles

### ISSUE THREAD

**Issue by samantha23325** [dalaranwow/dalaran-wow#5412]
I noticed that the in game sound is crackly, music, ambient sounds, general sounds etc, has a crackle.

**Comment by Zarjofgt** [comment]
It might be your ears

**Comment by Chenocide** [comment]
In any case, it can only be client related, not server related.

**Comment by Golganeth** [comment]
It is not a server-side issue so we can't do much about it. I would suggest reinstalling your client or checking for corrupted files.

Closing up
