### ISSUE TITLE
Sholazar Basin reputation qeuests

### ISSUE THREAD

**Issue by Real-Scaramouche** [dalaranwow/dalaran-wow#5418]
**Current behaviour**: Sholazar Basin map reputation quests with Frenzyheart/Oracle

**Expected behaviour**: Messed up quest with Frenzyhearts and cannot procceed with "Heroe's Burden" quest chain.

I've done this zone like 5 times already and twice I had achi 75/75.
Now I'm stuck with 55/75 and there's not a single NPC that gives a quest in this zone. I've spent whole weekend and whole day yesterday flying inch by inch through this zone and found absolutely nothing..
I do not know where I've stopped with Frenzyhearts quest chain. I'm attaching my reputation screenshot.
I'm the completionist type of person and not having to complete this quest achi bothers me greatly.
![reputation q](https://user-images.githubusercontent.com/32997636/39203514-a9ff9636-47fd-11e8-89c5-164b3e820ace.png)

**Comment by Rushor** [comment]
Comments for the questchain can be found here: http://de.wowhead.com/faction=1104/stamm-der-wildherzen#english-comments and here http://et.worldofwarcraft.wikia.com/wiki/Frenzyheart_Tribe

Please contact a gamemaster. He will help you to find which quests you have already done - and on which current step you are on the questline. Thank you.

![GitHub Logo](http://i.imgur.com/bYkYeGQ.png)

**Comment by Golganeth** [comment]
You should get an addon such as EveryQuest that will help you track the quests you have done, so that you can figure out where you stopped. 

Cheers

**Comment by Real-Scaramouche** [comment]
Well guys, thank you very much for the help and tips!!

**Comment by Golaman2** [comment]
I got almost the same issue but with the opening quest for the factions in Sholazar Basin! I opened a ticket! I hope you will notice :)
