### ISSUE TITLE
[Quest][Northrend] Worm Wrangler

### ISSUE THREAD

**Issue by Imbarawr** [dalaranwow/dalaran-wow#5423]
**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
When using the provided item [Sturdy Crates](http://www.wowhead.com/item=36771/sturdy-crates) it gives you a quest item containing the jormungar spawn but the jormungar spawn does not despawn. You can stay at one jormungar spawn and repeat the procedure 3 times and you're done.

**Expected behaviour**: Tell us what should happen instead
The jormungar spawn should despawn after being captured.

**Steps to reproduce the problem**:

1. Acquire quest
2. Find Jormungar Spawn
3. Use quest item

**Include proofs for this behaviour**
N/A.

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**
Quest: http://www.wowhead.com/quest=12078/worm-wrangler

**Include Screenshots from the issue if necessary**
N/A

**Comment by TeridanDW** [comment]
Hello,
This should solve the problem but I haven't test it.
``` sql
-- Ice Heart Jormungar Spawn SAI
SET @ENTRY := 26359;
UPDATE `creature_template` SET `AIName`="SmartAI" WHERE `entry`=@ENTRY;
DELETE FROM `smart_scripts` WHERE `entryorguid`=@ENTRY AND `source_type`=0;
INSERT INTO `smart_scripts` (`entryorguid`,`source_type`,`id`,`link`,`event_type`,`event_phase_mask`,`event_chance`,`event_flags`,`event_param1`,`event_param2`,`event_param3`,`event_param4`,`action_type`,`action_param1`,`action_param2`,`action_param3`,`action_param4`,`action_param5`,`action_param6`,`target_type`,`target_param1`,`target_param2`,`target_param3`,`target_x`,`target_y`,`target_z`,`target_o`,`comment`) VALUES
(@ENTRY,0,0,0,9,0,100,0,0,5,10000,15000,11,43358,0,0,0,0,0,2,0,0,0,0,0,0,0,"Ice Heart Jormungar Spawn - Within 0-5 Range - Cast 'Gut Rip'"),
(@ENTRY,0,1,0,8,0,100,0,47431,0,0,0,41,0,0,0,0,0,0,1,0,0,0,0,0,0,0,"Ice Heart Jormungar Spawn - On Spellhit 'Capture Jormungar Spawn' - Despawn Instant");
```
