### ISSUE TITLE
[Mechanic] Charge not working if used while falling.

### ISSUE THREAD

**Issue by Aridam** [dalaranwow/dalaran-wow#5426]
**Current behaviour**: Using Abilities incorporating the Charge mechanic (Charge, Intervene, Intercept, Feral Charge - Bear, Demon Charge, etc.) while falling doesn't work.

**Expected behaviour**: One is supposed to save themself from falling by using a Charge mechanic Ability just-before sticking the landing from falling down.

**Steps to reproduce the problem**:

1. Drop from a high place;
2. Use a Charge mechanic Ability on something (spam it);
3. Watch as you fail to save yourself from falling.

**Include proofs for this behaviour**

https://www.youtube.com/watch?v=jlImCxoqgEQ

Charge Rank 1, 2, 3 Spell IDs, Feral Charge - Bear Spell ID, Demon Charge Spell ID found at: https://wowgaming.altervista.org/aowow/?search=Charge#abilities

Intercept Spell ID: https://wowgaming.altervista.org/aowow/?spell=20252

Intervene Spell ID: https://wowgaming.altervista.org/aowow/?spell=3411

If I've missed any Abilities using the same mechanic, feel free to add them.

**Comment by Rushor** [comment]
related and will be improved together with https://github.com/dalaranwow/dalaran-wow/issues/3845
