### ISSUE TITLE
[Core] Using Abilities from-GCD-to-GCD randomly bugs-out.

### ISSUE THREAD

**Issue by Aridam** [dalaranwow/dalaran-wow#5427]
**Current behaviour**: Using Abilities back-to-back sometimes bugs-out and fails to use the next Ability due to a failure in recovering from the previous GCD, effectively making both quick button-mashing _and_ pinpoint-timing GCDs backfire at times.

The entire delay from this occurring is ~0.1s and is noticeable as your Action Bars go dimmed when this happens (as when you're using an Ability and about to trigger a GCD), and you fail to use the Ability you're trying to use right as your previous GCD finishes, forcing you to either cope with this and be fractionally-slower at times, or be slower on purpose to avoid this happening.

**Expected behaviour**: This shouldn't happen. As of writing this I keep testing with both button-mashing _and_ calm presses with precise timing (not using snowfallkeypress either), and it happens in both instances, while I have ~40ms all the time with no random own-sided Internet issues.

**Steps to reproduce the problem**:

1. Go to something for practice -- like a Target Dummy;
2. Keep using Abilities which trigger a GCD back-to-back;
3. Keep track of this bug -- either make it as precisely-timed with calm presses or simply button-mash as hard as possible.

For better testing I advise precise calm presses while keeping Combat Log open while looking for the failure report due to "(Not yet recovered)", and the on-screen error "Ability is not ready yet."

**Include proofs for this behaviour**

I do not have recording software present so I am unable to provide solid proof first-hand, but anyone can test this (especially those with a good connection and no side-issues).

Here is a screenshot of precisely-timed calm presses while spamming Rend on a single Mob -- note the Combat Log report, as well as the red-tinted on-screen error: https://s9.postimg.cc/9ybe61da5/Wo_WScrn_Shot_042818_150034.jpg

**Comment by TeridanDW** [comment]
Hello,
Issue is probably the same as https://github.com/dalaranwow/dalaran-wow/issues/4922#issuecomment-347478467

**Comment by Aridam** [comment]
Correct -- I had forgotten about this report for a while now until I recently came back.

Just-tested with other issues regarded by the original report you linked (like trying to switch Stances back-to-back), and this applies to those actions as well, so it's the same type of report.

**Comment by Golganeth** [comment]
Gonna close this then. Let's use #4922 to provide extra feedback or any relevant info about the issue.
