### ISSUE TITLE
Group Questing and Looting/RDF/Mob Aggro etc.

### ISSUE THREAD

**Issue by Muncic** [dalaranwow/dalaran-wow#543]
Hello, Just to let you know, I have been "saving" the issues so I can write them all down in 1 go  ... so here I go ...
1. Group Questing and Looting

I've been doing a lot of quests with friends and the main problem with it ... is that sometime we have to wait for everyone to get their Quest items witch have low % of drop rate and they are needed in a high amount. Since I was on retail for a long time, every time you Quest with with someone in the group, all of you 2-5 get the Quest item regardless if u take it the first or the last member, the fact is, if 1 quest item is needed, only 1 mob is need to be killed not 2-5. There are a lot of these and they are hard to do when you have max 15 mobs on a 10 item loot quest and to top it all of ... the drop chance is not 100%.

1.1. Quests in General

A lot of them are bugged, TBH a would suggest that you make them "complete" on pick up so people don't get confused and waste time on bugged quests, just untill you fix the whole thing, this is just a suggestion so don't point me out :)

Most bugged quests are escort Quests (Escort in Feralas [the chicken], Escort in Thousand needles [The Female Tauren that is picked up along the first quests, can't remember the name] didn't really bugg but the NPC attacked a mob witch was underground), mostly NPC crash into the mountains or go in a different path, kind of annoying when they pull 469876 extra adds around them

For e.g. "The Road to Falcon Watch", the dude dropped into the ground a few time, which OFC scared the hell out of me!  

And some quests have such a low drop rate on Quest items, that it takes about 45-60 minutes to farm out, not too mention that if you are in a group ... it will take forever (Boiling Blood, this one has a low drop rate on retail, but here it's insanely low)

Also, while in a group Item Quests (the Ones that start a Quest) Should be pickup able from all the party members not only the "fastest" one
1. Random Dungeon Finder

Oh man now this one my favorite, so basically the main problem about this is not getting the extra reward, neither the xp or the satchel AND WHEN you do get the satchel it buggs and gives you nothing, just an empty box.

2.1 

Another bugg is, sometimes the dungeon does not register the dungeon as in "complete" so when you press "Leave party" after completing the instance you get "Deserter" because the system is out of order. Which is OFC a problem

2.2

Oh yea, almost forgot ... you should not be able to port in or out while in combat ... which is possible at this moment

2.3

And one last thing, the terrain is a bit bugged, mages can blink into the floor and drop dead, and the mobs get kicked into the floor as-well which makes the whole group enter the "combat bugg" issue, and since the server is new the healers are not that geared and they need to drink up ... It makes the instance a Long and Painful
1. Mob Aggro

This is a small detail but still;
Grey mobs have a larger "aggro" range then they should, I remember going 5 yards from a mob on Retail and not pulling it, but here I have to stay away atleast 20 yards, almost as he is green/any-other color

3.1.

And most of the mobs stop following their "target" wayyyyyy too early, the range zone is like 30 yards and it is either you attack them 1 by 1 or you don't attack at all (maybe I'm wrong but tbh it feels odd and out of order) 
1. Mob casters and "Tanks" with silence

ALOT of mobs are bugged in a way that when you silence them keep casting like nothing happened, it's is like they just moved and started to cast the spell again, Makes it kind of useless for us to use interrupts and such abilitys

ALSO Some mobs are bugged in a way that they can silence you till the end of time, you wouldn't be able to cast 1 spell next to them (On the start in Durotor, the Human "fortress" has some marines that can do that), I had to melee/wand those mobs because other casts would fail
1. Some random buggs

5.1 Zul'Farrak

5.1.1 
The NPCs that are suppose to be released for the Event to start ... they get stuck near the cages

5.1.2
The boss "Witch Doctor Zum'rah" that is near the "graves" doesn't drop any loot and the chest is bugged

5.1.3
Antu'sul Doesn't summon his "pets" in the fight

5.2 Scarlet Monastery

5.2.1
Cathedral = mobs can get bugged at the door near the entrance in the cathedral
Library = The last boss usually has 100% chance to make a "Bubble" shield at 50% HP which can't be dispelled or anything, people usually stun him at 60% and he skips that party of the fight

5.3 Rare world mobs

5.3.1 Pre-TBC part

Sorry about this but WHAT THE HELL is with them? They Have a High Respawn time and everything but they are useless, They don't drop any special items, not worth the XP (same as normal mobs, maybe 10% more), they do more damage and at some quest lines they get in the way just because they are near someone that has to be killed for a quest. You can atleast boost the xp gain to be worth x 3 from a normal mob, people would stop and kill it then, or make them drop something, cause this is useless (JUST AN OPINION! DONT HATE ME FOR IT! :D )

5.3.2 TBC

Today, I've entered Outland and found 2 Rare mobs in 1 Hour, that is way 2 fast and the 2nd one (The Worm in Hellfire) I've killed it 2 times already, it is like the respawn is 10-15 minutes or even less. It is suppose to be hard and rare to find so if this is the way it will stay ... well I suppose it is your choice.

Well I've Ran out of ideas for now, I will write down and get back too you when I see/encounter some more of them. Have a pleasant evening

By: Muncic and Theunit

**Comment by cover25** [comment]
Confirmed. Questing in a party is incredibly painful and honestly shouldn't be a bug lasting for two years...

**Comment by bushig** [comment]
Double that. Also combat bug is really annoying.

**Comment by Darkexecutioner** [comment]
"1. Group Questing and Looting" Confirmed. It makes leveling with friends annoying and slow.
The combat bug is quite common. I have to Alt+F4 a few times a day.

**Comment by Rushor** [comment]
90% of this is already fixed on PTR. For the stuff that is not fixed yet on PTR please open a new issue. Thanks.

And also: only report one bug / ticket if the issues are nor related to each other. Thanks a lot.
https://github.com/dalaranwow/dalaran-wow/wiki/Dalaran-WoW-Bug-Tracker---Guidelines
