### ISSUE TITLE
[Warrior][Talent] Sweeping Strikes is proccing from applying Rend.

### ISSUE THREAD

**Issue by Aridam** [dalaranwow/dalaran-wow#5433]
**Current behaviour**: Sweeping Strikes gets depleted whenever Rend gets applied.

**Expected behaviour**: That shouldn't happen.

**Steps to reproduce the problem**:

1. Have two+ Targets around you;
2. Activate Sweeping Strikes;
3. Apply Rend on one Target and look at Sweeping Strikes;
4. Notice Sweeping Strikes gets a charge expended for nothing every single time you apply Rend.

**Include proofs for this behaviour**

Sweeping Strikes ID: https://wowgaming.altervista.org/aowow/?spell=12328
Rend IDs for all Ranks (look at the ones only tagged with "Warrior"): https://wowgaming.altervista.org/aowow/?search=Rend#abilities

**Comment by Aridam** [comment]
Yeah it's not even supposed to do anything like that because it's not an actual attack that should expend Sweeping Strikes -- quite the bother.

**Comment by Aridam** [comment]
Still an issue.

**Comment by Rushor** [comment]
okay yes that can be fixed by checking the spellproc event

**Comment by Golganeth** [comment]
@wrathofthebug The spell_proc_event makes reference to the events (procs) that have a chance of becoming active when casting a spell, and it must be adjusted internally. @Rushor was just leaving a note for himself/Devs.

Long story short, gotta wait for the fix to be applied to the live realm.
