### ISSUE TITLE
[Achievement] To the Looter Go the Spoils

### ISSUE THREAD

**Issue by Golganeth** [dalaranwow/dalaran-wow#5435]
The item [Autographed Picture of Foror & Tigule](http://www.wowhead.com/item=18228/autographed-picture-of-foror-tigule) isn't in the DB and can't be looted from NPCs or players, so the players can't get the achievement: [To the Looter Go the Spoils](http://www.wowhead.com/achievement=1166/to-the-looter-go-the-spoils).

**Achievement ID:** 1166
**Item ID:** 18228

http://www.wowhead.com/achievement=1166/to-the-looter-go-the-spoils
http://www.wowhead.com/item=18228/autographed-picture-of-foror-tigule

**Comment by Rushor** [comment]
Player should be able to have loot, will implement loot for them.
