### ISSUE TITLE
Stuck in Realms of Shadows

### ISSUE THREAD

**Issue by Imbarawr** [dalaranwow/dalaran-wow#5438]
**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
My DK is currently stuck in Realms of Shadows. After completing the quest I got phased out to normal. I then turned in another quest and got phased back into Realms of Shadows. I tried killing another guy to take his horse, thinking that might get me back, but once I killed him the only option was to attack the horse, not mount it.

I've tried relogging and dieing, does not fix the issue.

**Expected behaviour**: Tell us what should happen instead
N/A

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Include proofs for this behaviour**

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

**Include Screenshots from the issue if necessary**

**Comment by Rushor** [comment]
Please write an Ingame-issue to a Gamemaster and the Gamemaster will then help you as soon as he can. (Or create a new Ingame-Account in order to be able to talk with a gamemaster with you new level 1 character) Thank you.

![GitHub Logo](https://i.imgur.com/PlMRkvE.jpg)
