### ISSUE TITLE
Quest: Banshee's Revenge

### ISSUE THREAD

**Issue by Crispybuilt** [dalaranwow/dalaran-wow#544]
--
**Quest Banshee's Revenge** - *13142*
--
- **Issue present**: Once you click on the object **Warhorn of the Jotunheim** *(ID:193028)* nothing happens, it is supposed to start the grand event where you have to fight against **Overthane Balargarde** *(ID:31016)* & his proto-drake **Safirdrang** *(ID:31050)*

- **How it should work**: *
There is insanely large roleplay event on the beginning so I will go step by step how it should work*

- **Video of how it should work** 
- http://www.youtube.com/watch?v=kCrglF1XJoA
- http://www.youtube.com/watch?v=EoTyQrl_aV8

This is also a pre-quest for the: **Battle at Valhalas** chain quest which unclocks entire chain quest, and is explained here: #465 

- **Overthane Balargarde** have the following abilites: *Blizzard*, *Frostbolt*, *Heroic Leap*, *Whirlwind*
He is also completely 100% immune to any kind of interupts, apsoultely anything at all.
Also, remember to add him his weapon to his hands. When he is casting he has to remove weapon from hands, and when he is attacking physically he needs to do it with a two hand weapon.

______________________
- **Blizzard:** 61085
- **Frostbolt:** 15043
- **Heroic Leap:** 60108
- **Whirlwind:** 61076

_____________________

- **Safirdrang** has these abilites: *Safirdrang's Chill*, *Safirdrang's Chill*

__________________
- **Safirdrang's Chill**: 4020
- **Safirdrang's Chill**:4307

*Fully manually Written by -- how it should work*
_________________________________________________________
_________________________________________________________

- 1st - Once you click on the horn, NPC **Possessed Vardmadra** *(ID:31029)* will appear/spawn *(flying in the air as shown on the video)* and yell the following quote:
- *Possessed Vardmadra yells: He's on his way!*

_______
- 2nd - Group of Proto-Drake Riders will appear flying within the tower on the left & right side (possibly these creatures: **Njorndar Spear-Sister** *(ID:30243)* riding **Njorndar Proto-Drake** *(ID:30272)*, two on each side flying, one behind your character (horn) and one behind the boss *(as show on the video, they all have to face him (npcs have to be faced to him - purely cosmetic npcs)).* So 6 Cosmetic Proto Drake Riders in total.
_______

- 3rd - The boss arrives, **Overthane Balargarde** *(ID:31016)* on his Blue Proto-Drake Called **Safirdrang** *(ID:31050)*. (He has to be faced to you after arrival)
After he is "set up" he will yell the following quote:
*Overthane Balargarde yells: You think to challenge me? You haven't earned the right!*
_______

- 4th -  **Possessed Vardmadra** yells then this quote:
*Possessed Vardmadra yells: Wrong, Balargarde. You WILL accept this challenge!*
and **Overthane Balargarde** answers with this quote:
*Overthane Balargarde yells: Vardmadra?! Did the Lich King send you personally?*
_______

- 5th - After that he jumps off his Proto-Drake **Safirdrang** and withdraws his weapon and he has to be faced to **Possessed Vardmadra** and do the /emote talk. After his final line he has to do /roar emote.
He will do it after he is finished with this quote:
*Overthane Balargarde yells: Very well. I will dispatch these creatures. It is only an inconvenience. Prepare to die!*
_______

- 6th - **Overthane Balargarde** becomes hostile and triggable and player is able to attack him. However, his Proto-Drake **Safirdrang**  stays up in the air neutral for now.
**Possessed Vardmadra** must lock her vision and *body-follow* (watch) **Overthane Balargarde** everywhere where he moves on the throne.
_______

- 7th - On 80% of HP he will call his Proto-Drake **Safirdrang** to aid him in the fight. He will yell the following quote:
*Overthane Balargarde yells: Safirdrang, let them feel the chill of Icecrown!*
_______

- 8th - **Safirdrang** will then use his abilites *Safirdrang's Chill* and *Safirdrang's Chill* down on the player or a zone near him.
_______

- 9th - On 50% **Overthane Balargarde** and **Safirdrang** will stop their scripts & he will become interactive and immune to any kind of damage from a player or a pet. He will yell this quote: 
*Overthane Balargarde yells:** *STOP! Kneel fools, it's the Lich King!* 
**Overthane Balargarde** uses /emote kneel down.
_______

- 10th - **The Lich King** *(ID: 31083)* fades in/appears on the edge of the platform. (He has to be non-interactive or even targetable to players)
Then The Lich King yells the following quote and does /emote talk: 
*The Lich King yells: Honor guard stay where you are.*
/script PlaySoundFile("Sound\\Creature\\LichKing\\SF_Lich King_Event01.wav")

_______

- 11th - **The Lich King** faces himself to **Possessed Vardmadra** and she kneels down before him. He starts walking towards her and he will yell the following quote:
- *The Lich King yells: Vardmadra. I'd wondered where you disappeared to. How is Iskalder?*

- /script PlaySoundFile("Sound\\Creature\\LichKing\\SF_Lich King_Event02.wav")
- **Possessed Vardmadra** responds with: 
- *Possessed Vardmadra yells: My lord.*

_______

- 12th - **The Lich King** does his /emoteshout 6, and the /emote talk again and does the following quote: 
*The Lich King yells: I see through your disguse, Lady Nightswood. YOU THINK THAT YOU CAN FOOL ME?!*
/script PlaySoundFile("Sound\\Creature\\LichKing\\SF_Lich King_Event03.wav")
_______

- 13th - **The Lich King** strikes down (/emote weapon attack) **Possessed Vardmadra** with Frostmourne in his hands and **Possessed Vardmadra** dies.
**The Lich King** laughs and does his /emote laugh.
**Lady Nightswood** ghost *(ID:30955)* appears behind the **Warhorn of the Jotunheim** floating next to it. 
She does the following emote:
*Lady Nightswood smiles and flies off to return to possessing The Bone Witch.* (that npc has to be friendly to everyone)
______

- 14th - **The Lich King** faces himself to **Overthane Balargarde** and does /emote of poiting frostmourne to him (EmotePoint 5). 
**The Lich King yells this then**: 
*The Lich King yells: You may continue your combat, overthane.*
/script PlaySoundFile("Sound\\Creature\\LichKing\\SF_Lich King_Event04.wav")
**Overthane Balargarde yells:** 
*Overthane Balargarde yells: But, my lord...?*
_______

- 15th - **The Lich King** does /emoteshout 6 and yells following quote:
*The Lich King yells:But nothing! Finish them! DO NOT FAIL ME, BALARGARDE!* - during this quote he also does /emote battleroar 2 shout.
/script PlaySoundFile("Sound\\Creature\\LichKing\\SF_Lich King_Event05.wav")
_______

- 16th - **The Lich King** walks back to his point where he spawned (slowly) and turns back / faces away to **Overthane Balargarde**.
**Overthane Balargarde** becomes active and attackable for a player (he is no longer immune)
**Overthane Balargarde yells following quote**:
*Overthane Balargarde yells: DIE DOGS!*
_______

- 17th - **Overthane Balargarde** & Proto-Drake **Safirdrang** will become active and their script will continue.

_______

- 18th - After you successfuly kill the **Overthane Balargarde** you get the credit for completing the quest (quest should also be completed while in group)

_______

- 19th - **The Lich King** will slowly walk towards the dead **Overthane Balargarde's** body & when he arrives he will do /emote talk 8 and yell the following quote:
**The Lich King yells: You have bested one of my finest, but your efforts are for naught.**
/script PlaySoundFile("Sound\\Creature\\LichKing\\SF_Lich King_Event06.wav")
Then he repeats the same emote again and says:
*The Lich King yells: The frozen heart of Icecrown awaits....*
/script PlaySoundFile("Sound\\Creature\\LichKing\\SF_Lich King_Event07.wav")
_______

- 20th - **The Lich King** dissapears from the effect of using "teleport spell* (not sure which one is in the database)
**Overthane Balargarde's** body also despawns together with all the cosmetic Dragons around flying in the air with including **Safirdrang** (remember that his script for him also has to stop after you kill Overthane)**

_______
_______

![image](https://f.cloud.github.com/assets/5054924/944645/bdcdb3de-02c8-11e3-8d14-38e0ab2039a6.png)
![image](https://f.cloud.github.com/assets/5054924/944647/d7a4aaf6-02c8-11e3-960c-0e681efa2591.png)
![image](https://f.cloud.github.com/assets/5054924/944652/a916a4e0-02c9-11e3-85da-d0c305cfed3d.png)
![image](https://f.cloud.github.com/assets/5054924/944667/f81dc608-02ca-11e3-8b6e-f5622cdf656d.png)

_______________________________________________________
http://www.wowhead.com/npc=31083/the-lich-king
http://wotlk.openwow.com/npc=30955
http://www.wowwiki.com/Quest:Banshee's_Revenge
http://www.wowhead.com/quest=13142/banshees-revenge
http://www.wowhead.com/npc=31016
http://wotlk.openwow.com/quest=13142
http://wotlk.openwow.com/npc=31016
http://wotlk.openwow.com/npc=31029
http://wotlk.openwow.com/npc=31050

**Comment by taralej90** [comment]
The horn sparkles but it cannot be interacted with...

**Comment by ashido96** [comment]
Confirmed, horn still unclickable.

**Comment by Spruitje** [comment]
Confirmed it too
I could click the horn, but nothing spawns, the horn became unclickable after that

**Comment by Blackoutx** [comment]
Still not working as of today

**Comment by DrFuler** [comment]
[07/04/2016] - Seems to be still bugged.

(blew the horn, nothing spawned, the horn is no longer clickable)

**Comment by Lothloryen** [comment]
Already on the live server.

**Comment by Crispybuilt** [comment]
All I have to say, Loth you are a god. Kudos to you for fixing this. Cheers
