### ISSUE TITLE
need help with boost

### ISSUE THREAD

**Issue by aciddeath** [dalaranwow/dalaran-wow#5448]
i boosted my mage Kelmer the other day, everyone is telling me it should of been instant and suggested i make a post here, please help! thank you!****

**Comment by Golganeth** [comment]
This is the in-game bugtracker, which lists in-game issues that may have a direct impact on players.
Make sure that you didn't make a mistake and boosted the wrong character.
Please contact us at dalaran.community@gmail.com explaining your problem. Include your account name, character, and any other relevant info.

Closing up
