### ISSUE TITLE
[Dungeon] Trial of the Champion 5 hc - Argent Confessor

### ISSUE THREAD

**Issue by alexuktc** [dalaranwow/dalaran-wow#5460]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
Two issues arise with this achievement:
1. Only 3-4 memories can be summoned by this boss.
2. You do not get credit for killing the memories.

Combine 1 and 2 and the achievement cannot be completed. 
**Expected behaviour**: Tell us what should happen instead
The boss should summon all of the mentioned memories at random and killing them should award the achievement credit.
**Steps to reproduce the problem**:

1. Get the boss in the instance
2. Test
3. Notice what is posted above.

http://www.wowhead.com/achievement=3802/argent-confessor

**Comment by Rushor** [comment]
Yeah i have a fix for this (for issue 2)

Do you know what's the reason for issue 1? 

It is using switch (urand(0, 24)) - so all memories should be able to be summoned
