### ISSUE TITLE
[Instance] Ahn'kahet: The Old Kingdom -> Plague Walker ->Aura of Lost Hope: incorrectly applied

### ISSUE THREAD

**Issue by Alistri** [dalaranwow/dalaran-wow#5464]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: 
**a)**
The first patrol of NPC 1х["Plague Walker"](http://www.wowhead.com/npc=30283/plague-walker) + 2х[Ahn'kahar Web Winder](http://www.wowhead.com/npc=30276/ahnkahar-web-winder) in ["Ahn'kahet: The Old Kingdom"](http://www.wowhead.com/ahnkahet-the-old-kingdom) independently enter into battle, being 100 meters from a group of players. The first to enter the battle is the ["Plague Walker"](http://www.wowhead.com/npc=30283/plague-walker), casting the  ["Aura of Lost Hope"](http://www.wowhead.com/spell=56710/aura-of-lost-hope). 
And usually it happens that this patrol resorts at a time when the group is still fighting with the first mobs - in this case, usually a wipe occurs. 

**b)**
In addition, in subsequent packs, NPC ["Plague Walker"](http://www.wowhead.com/npc=30283/plague-walker) constantly casts (stack) the aura of ["Aura of Lost Hope"](http://www.wowhead.com/spell=56710/aura-of-lost-hope) on the player if it is nearby **_not in combat mode_**.  In this case, the packs do not aggro on the players immediately as the first patrol-pack.

**Expected behaviour**: The ["Aura of Lost Hope"](http://www.wowhead.com/spell=56710/aura-of-lost-hope) should be imposed only if the  ["Plague Walker"](http://www.wowhead.com/npc=30283/plague-walker)  is in combat mode.

**Steps to reproduce the problem**:

1. Enter the dungeon ["Ahn'kahet: The Old Kingdom"](http://www.wowhead.com/ahnkahet-the-old-kingdom).
2. **a)** Stand in front of the first mobs (as in the screenshot) and wait for the patrol.
3. **b)** Approach the ["Plague Walker"](http://www.wowhead.com/npc=30283/plague-walker)  closer 100m (but do not engage in battle).

**Include proofs for this behaviour**
**Include Screenshots from the issue if necessary**
1) I'm standing and waiting for the patrol.
![1](https://user-images.githubusercontent.com/39156867/39926096-c9f522bc-5536-11e8-901b-463210be459b.jpg)

2) The patrol appeared, but has not yet approached 100 m.
![2](https://user-images.githubusercontent.com/39156867/39926150-f0dec680-5536-11e8-8e9d-210227b45612.jpg)
![3](https://user-images.githubusercontent.com/39156867/39926192-1453df92-5537-11e8-982e-5f2eb7cb529b.jpg)

3) The patrol approached 100 meters and the  ["Aura of Lost Hope"](http://www.wowhead.com/spell=56710/aura-of-lost-hope) hung on me. The patrol immediately agro.
![4](https://user-images.githubusercontent.com/39156867/39926203-1b2a5544-5537-11e8-9821-28156bdfc927.jpg)

![5](https://user-images.githubusercontent.com/39156867/39926281-5bd89ba0-5537-11e8-9c96-7c880cb321dd.jpg)

**Comment by Alistri** [comment]
It seems to me that the range of the aura is correct: on the website www.wowhead.com states that _Radius ["Aura of Lost Hope"](http://www.wowhead.com/spell=56710/aura-of-lost-hope): 99 yards_. The problem is that it works all the time, not when the NPC ["Plague Walker"](http://www.wowhead.com/npc=30283/plague-walker)  is in combat mode.

**Comment by Rushor** [comment]
okay yeah - now the walker will only cast the spell on aggro (when getting in combat) and not all the time. Fix will be tested on PTR. Thank you.
