### ISSUE TITLE
[Quest] Mission: Possible but Not Probable - not working

### ISSUE THREAD

**Issue by ptaluc** [dalaranwow/dalaran-wow#5478]
I am doing this quest but I am not getting any credit for killing the necessary mobs.  Number of kills remains at zero no matter how many I kill.

**Comment by Rushor** [comment]
Cannot confirm this on PTR.

![GitHub Logo](https://i.imgur.com/zTYbodN.png)

There needs to be a tiny event for that quest. I will add that later.
