### ISSUE TITLE
[Quest][Northrend] Second Chances

### ISSUE THREAD

**Issue by Sagrath** [dalaranwow/dalaran-wow#548]
http://old.wowhead.com/quest=12847
In the quest Second Chances, is a failure at the end of it.

You kill the Archbishop Landgren ( http://www.wowhead.com/npc=29542 ) and invoke the portal (http://www.wowhead.com/item=40730), he should appear in Lord Commander Arete

( http://www.wowhead.com/npc=29560 ) and will ship the quest, the problem is not displayed
by Lord commander Arete nowhere to finish.

**Comment by Rushor** [comment]
fixed by tc http://i.imgur.com/FKJdD6l.jpg http://i.imgur.com/vBYSte9.jpg
