### ISSUE TITLE
[Warlock] Doomgaurd despawns

### ISSUE THREAD

**Issue by Ghonorhea** [dalaranwow/dalaran-wow#5483]
Current behaviour: Doomgaurd summoned by killing an NPC with Curse of Doom despawns within 10 seconds.

Expected behaviour: Doomgaurd should stay untill killed or despawns naturally, if enslaved it should stay enslaved for 5minutes.

Steps to reproduce the problem: Kill NPC with Curse of Doom, watch doomgaurd quickly dissapear after.

**Comment by Rushor** [comment]
https://wowgaming.altervista.org/aowow/?spell=18662
