### ISSUE TITLE
3D Secure verification failed.

### ISSUE THREAD

**Issue by ZGTrader92** [dalaranwow/dalaran-wow#5485]
I have problem donating for Donation Points with my Visa/Debit card. When I try to verify my personal information with my bank verification Erste Steieremarkische bank it says : Verification was successfull and we verified it,when I press OK button there is a page from Paymentwall that its denied.. I have account on Paymentwall ...

**Comment by Golganeth** [comment]
This is the in-game bugtracker, which lists in-game issues that can affect players.
Please contact us at dalaran.community@gmail.com explaining your problem. Include your account name and any other relevant info.

Closing up

**Comment by ZGTrader92** [comment]
Hello,my account name is Jonnybravo92. I have problem buying donate points
via your Paymentwall donation platform.When I press OK on my banks page for
3D secure check the window pop out Secure Ogone that its denied.. Then it
brings me back to the page where I enter my informations and card number  it
says : 3DSecurity verification failed.

2018-05-25 13:52 GMT+02:00 Golganeth <notifications@github.com>:

**Comment by Golganeth** [comment]
Please contact us at dalaran.community@gmail.com explaining your problem. Include your account name and any other relevant info.
