### ISSUE TITLE
[Item] Incorrect drops of recipes

### ISSUE THREAD

**Issue by Jindra555** [dalaranwow/dalaran-wow#5486]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

## Certain recipes have incredibly low drop rate, 0.5 % or even lower, where they by all indices shouldn't. 

I am using evowow's database to show the drop percentage. While i realize that Dalaran db is not 100% exact copy of trinity in all regards, it's still using the emulator and that's the best point to start. The wowhead percentage of drops roughly match what's in the evowow db, but there is one major flaw that happened with recording of these drops.
Each of these recipes can drop ONLY for players who have the corresponding profession and ONLY if they haven't learned said recipe yet. Wowhead's data collection didn't take this into consideration. The drop chance is skewed by all the people killing the mobs without having the needed requirements. As a result, it only seems very small whereas in reality it's considerably higher, but non-req players are taken out of the drop chance altogether.

I know that wowhead comments are hardly an objective source of data, but many of them seem to agree on the fact that farming these recipes doesn't take very long. We can make a sort of rough statistic (taking into consideration only wotlk-era comments, of course) that should make it clear that these recipes really were not dropping at these rates which are comparable to world drops.

Concerning Alchemy, LW, Ench and BS recipes below:

## A L C H E M Y

Recipe: Mighty Arcane Protection Potion
https://wotlk.evowow.com/?item=44564
http://www.wowhead.com/item=44564
Drops off Cult Researcher, NPC ID 32297 at 0,5 % and Frostbrood Spawn NPC ID 31702 at 0,5 %

From the comments: This was gotten by various people on the 5th, 10th, 3rd and 2nd kills. Another said it took 5 minutes of killing. One player claimed to be able to get all 5 of these potion recipes in one hour. I believe all the references made are concerning the cultists, not the frost wyrms.

Recipe: Mighty Fire Protection Potion
https://wotlk.evowow.com/?item=44565
http://www.wowhead.com/item=44565
Drops off Skeletal Runesmith, NPC ID 30921 at 0,2 %

From the comments: Two people reported taking 15 minutes to farm this recipe. 

Recipe: Mighty Frost Protection Potion
https://wotlk.evowow.com/?item=44566
http://www.wowhead.com/item=44566
Drops off Damned Apothecary, NPC ID 32289 at 0,3 %

From the comments: One player spent "almost an hour" getting this. Another got it in 30 minutes of farming, along with two other drops on this list. Other reported times were 1,5 hours, 45 minutes and 10 hours (without getting it, either an outlier or the person was doing something wrong).

Recipe: Mighty Nature Protection Potion
https://wotlk.evowow.com/?item=44567
http://www.wowhead.com/item=44567
Drops off Cult Alchemist, NPC ID 32290 at 0,4 %

From the comments: Farming times here vary from 10 minutes to 4+ hours or 100+ mobs wihtout success. This is scarce data, but important, as it shows that while more abundant than our current drops, it's nowhere near guaranteed.

Recipe: Mighty Shadow Protection Potion
https://wotlk.evowow.com/?item=44566
http://www.wowhead.com/item=44566
Drops off Cultist Shard Watcher, NPC ID 32349 at 0,5 % 

From the comments: One player had to kill 50 mobs, another one 137. One spent three hours on farming this. 

## L E A T H E R W O R K I N G

Pattern: Fur Lining - Fire Resist
https://wotlk.evowow.com/?item=44559
http://www.wowhead.com/item=44559
Drops off Skeletal Runesmith, NPC ID 30921 at 0,2 %

From the comments: One person spent a hour farming, another said it was in the "usual" range of 25-100 kills per item.

Pattern: Fur Lining - Frost Resist
https://wotlk.evowow.com/?item=44560
http://www.wowhead.com/item=44560
Drops off Damned Apothecary, NPC ID 32289 at 0,5 %

From the comments: Farm times were 23 minutes and 4 hours.

Pattern: Fur Lining - Shadow Resist
https://wotlk.evowow.com/?item=44561
http://www.wowhead.com/item=44561
Drops off Cultist Shard Watcher, NPC ID 32349 at 1,7 % 

From the comments:  34 (2x17), 60, 85 (5x17), 118, 159 kills.

Pattern: Fur Lining - Nature Resist
https://wotlk.evowow.com/?item=44562
http://www.wowhead.com/item=44562
Drops off Cult Alchemist, NPC ID 32290 at 0,5 %

From the comments: One person spent 13 minutes farming, another one had to kill 95 mobs.

Pattern: Fur Lining - Arcane Resist
https://wotlk.evowow.com/?item=44563
http://www.wowhead.com/item=44563/
Should drop off Cult Researcher, NPC ID 32297 and Frostbrood Spawn NPC ID 31702, in the trinity db it has no drop

From the comments: Perhaps the greatest variance of kills needed so far. 54, 100+, 150 and "well into the hundreds". One commenter claimed he had 786 kills and nothing dropped. Again, either an unlucky outlier or he was doing something wrong.

## E N C H A N T I N G

Formula: Enchant Cloak - Superior Arcane Resistance
https://wotlk.evowow.com/?item=37330
http://www.wowhead.com/item=37330
Drops off Cult Researcher, NPC ID 32297 at 0,8 % and Frostbrood Spawn NPC ID 31702 at 1,5 %

From the comments: This provides some insight about both cultists and wyrms. For wyrms it was about 100 kills from several people, or 4 hours of farming. For cultists, 37 kills. One person got 2 drops in 10 minutes. Probably an outlier.

Formula: Enchant Cloak - Superior Fire Resistance
https://wotlk.evowow.com/?item=37331
http://www.wowhead.com/item=37331
Drops off Skeletal Runesmith, NPC ID 30921 at 0,4 %

From the comments: One person farmed 15 minutes, another one for a hour, with no result.

Formula: Enchant Cloak - Superior Frost Resistance
https://wotlk.evowow.com/?item=37332
http://www.wowhead.com/item=37332
Drops off Damned Apothecary, NPC ID 32289 at 0,6 %

From the comments: No properly relevant data.

Formula: Enchant Cloak - Superior Nature Resistance
https://wotlk.evowow.com/?item=37333
http://www.wowhead.com/item=37333
Drops off Cult Alchemist, NPC ID 32290 at 0,5 %

From the comments: Time spent farming was 30 minutes for one person, 2 hours for another. Someone got 3 in 140 kills. Someone else killed 200 and nothing dropped.

Formula: Enchant Cloak - Superior Shadow Resistance
https://wotlk.evowow.com/?item=37334
http://www.wowhead.com/item=37334
Drops off Cultist Shard Watcher, NPC ID 32349 at 1 % 

From the comments: 13, 45, 90 and 98 kills.

## B L A C K S M I T H I N G 

Plans: Reinforced Cobalt Legplates
https://wotlk.evowow.com/?item=41120
http://www.wowhead.com/item=41120
Drops off Gundrak Savage, NPC ID 29235 at 1,8 %

From the comments: One person took 50 kills, another 15 minutes.

Plans: Reinforced Cobalt Chestpiece
https://wotlk.evowow.com/?item=41122
http://www.wowhead.com/item=41122
Drops off Venture Co. Excavator, NPC ID 28123 at 0,7 %

From the comments: A lot of datapoints, 5, 20, 30, 58, 60, 150 kills.

Plans: Reinforced Cobalt Helm
https://wotlk.evowow.com/?item=41123
http://www.wowhead.com/item=41123
Drops off Iron Rune-Shaper, NPC ID 26270 at 0,7 %

From the comments: 30-60 minutes, two hours and another player reports 95 kills before it dropped.

Plans: Reinforced Cobalt Shoulders
https://wotlk.evowow.com/?item=41124
http://www.wowhead.com/item=41124
Drops off Onslaught Mason, NPC ID 27333 at 0,6 %

From the comments: Someone farmed for 45 minutes before it dropped, someone else for 3 hours. Yet someone else killed 95 of the mobs.

Plans: Greater Ward of Shielding
https://wotlk.evowow.com/?item=23639
http://www.wowhead.com/item=23639
Drops off Sunfury Bloodwarder, NPC ID 18853 at 1,68 %

From the comments: It took 30m of farming for someone, other people got it after killing 50 and 97 mobs. I left out the many comments that said it dropped from 1 to 10 kills as that's a skewed statistic caused by the surprisingly early drop making the players go and comment.
Of all the parterns, this one is perhaps slightly questionable as it comes from TBC and the rates might have changed over that time.

## I propose bumping them up a bit on Dalaran, so they become farmable. Most of these drop chances are on par with world drops, pretty much.
For reference, the only other wotlk wiki I could find is twinstar, where they set the drop chances to 5-9 %. Except for the BS patterns, it seems those went unnoticed.

These are possibly not the only recipes affected, but so far it's what I found.

Lastly, I'd like to reference this:
https://github.com/dalaranwow/dalaran-wow/issues/4376

For example 
https://wotlk.evowow.com/?item=22904
and
https://wotlk.evowow.com/?item=22903
truly have very limited pool of mobs they seem to drop off whereas other TBC world drops have wide range of possible drop locations.

I did not investigate any recipes from that report past these two however.

**Comment by Chenocide** [comment]
I don't have any concrete numbers or any proof but I've farmed the enchanting and LW patterns and ohh boy, it's a struggle. The last missing LW pattern has probably taken close to 10 hours so far.

**Comment by Rushor** [comment]
dropchance increased to 10 % on PTR.
