### ISSUE TITLE
investigate the alchemist shop

### ISSUE THREAD

**Issue by griffintr** [dalaranwow/dalaran-wow#5491]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: In Undercity, I tried the quest "investigate the alchemist shop".  I AOEed the 4 void spawn down to almost no hp.  The emote: "rift spawn escapes into the void" was displayed.  The 4 void spawn become untargetable, went back to their spawn points and despawned.  I tried this 3 times with the same result.

**Expected behaviour**: At low hp, the void spawn should be come stunned so that they can be captured.

**Steps to reproduce the problem**:  

1. Be a mage.
2. Get the quest.
3.  Try the quest.

**Comment by Rushor** [comment]
duplicate linked issue https://github.com/dalaranwow/dalaran-wow/issues/5439
