### ISSUE TITLE
Envenom scaling off combo points

### ISSUE THREAD

**Issue by Srifzor** [dalaranwow/dalaran-wow#5500]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: I noticed while questing on my rogue, Srifzor (75 or so at the time), that when chaining Envenoms as an Assassination Rogue (where the strategy it to use envenom at 5 Deadly Poison stacks, get a combo point from Relentless Strikes, and then chain Envenoms without consuming the 5 stacks of Deadly Poison) my Envenoms would only be hitting for around 600, which is about a third of what mutilate was hitting for. I went to some target dummies and ran some test and it appears Envenom is scaling off combo points, not poison stacks. When using Envenom target dummy with 5 stacks of Deadly Poison AND 5 combo points, the average was 2050. When I used envenom with just 1 combo point by 5 stacks of Deadly Poison, the average went down to 409. 

**Expected behaviour**: Envenom should scale with Deadly Poison or the tooltip should reflect is scaling with CP instead.

**Steps to reproduce the problem**:

1.  Find target dummy.
2. Use envenom with 5 combo points and 5 deadly poison stacks
3. Use envenom with 1 combo point and 5 deadly poison stacks. 

**Include proofs for this behavior**

![20180606_200127](https://user-images.githubusercontent.com/40009997/41071540-52eefd24-69c6-11e8-8df2-9e24f49a90a5.jpg)
![20180606_200229](https://user-images.githubusercontent.com/40009997/41071554-6ab2aa96-69c6-11e8-956f-136d6d2a145d.jpg)

**Comment by Byssarod** [comment]
Thats because in description of Envenom is clearly written one dose of deadly poison is consumed for each combo point and it deals damage of how many doses is consumed.

**Comment by alexuktc** [comment]
![envenom](https://user-images.githubusercontent.com/24550199/41103638-4ad64bd6-6a72-11e8-8cb0-c226415705a9.png)

I fail to see how you can downvote correct information.

**Comment by Srifzor** [comment]
The description does not say anything about the damage of envenom being modified by combo points.
Further, there is a talent that makes envenom NOT consume deadly poison stacks.

**Comment by Golganeth** [comment]
As @Byssarod said, tooltip clearly says "One dose is consumed for each combo point". If you have 1 CP, only 1 dose will be consumed, regardless of how many poison stacks there is on the target.

![image](https://user-images.githubusercontent.com/5057942/41105761-ad782470-6a6e-11e8-91a3-5633b74a7875.png)

Please read your tooltips more carefully.
Closing up
