### ISSUE TITLE
Disconnect on hatching eggs in onyx

### ISSUE THREAD

**Issue by lkrocek** [dalaranwow/dalaran-wow#5509]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
All players in instance got disconnect and fight were reset when we got phase 2, and hatched the eggs. We tried it 2 times with same result, 2nd pull we were back online soon and could be able kill her, but got no achievement.

**Expected behaviour**: Tell us what should happen instead
Do not disconnect players.

**Steps to reproduce the problem**:

1. Pull onyx in 10m encounter
2. get her on 65% to get phase 2
3. run into eggs and hatch the lot of eggs (we had 2 druids which switched into cat form with dash up)
4. I think when you reach that 50 eggs hatched up then players inside of instance got that disconnect

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

We tried to do this achievement https://wowgaming.altervista.org/aowow/?achievement=4403

**Comment by TeridanDW** [comment]
Hello and thank you for the report @lkrocek 
I did few tests on PTR realm but couldn't reproduce the disconnecting issue.
Had over 50 Whelps on me.
![wowscrnshot_061318_124155](https://user-images.githubusercontent.com/6797611/41343486-6ffafc9c-6f07-11e8-85b6-6485de448682.jpg)
![wowscrnshot_061318_124020](https://user-images.githubusercontent.com/6797611/41343489-7250fbd6-6f07-11e8-9ec8-bcb35e59feb7.jpg)

**Comment by lkrocek** [comment]
I am not sure if you did the same from your comment (nothing against you, just to confirm you did it same) ... It's not about to have 50 whelps but **hatch** 50 whelps, the whelps are usually coming when 2nd phase starts, or maybe we had much more then 50, could you re-try with more or more people in raid and I can re-try it next reset if still happens or it was just a bad luck.

**Comment by galgnu** [comment]
I've heard that its also something about which spells are used. Starfall for instance will fuck it up and make people DC.

**Comment by TeridanDW** [comment]
Test it with 50+ whelps and use shockwave on all of them at the same time. DC shouldn't happen after @Lothloryen 's fix.
