### ISSUE TITLE
[Pet][Cosmetic][Warlock] Succubus emote

### ISSUE THREAD

**Issue by ashphoenix92** [dalaranwow/dalaran-wow#5515]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: No interaction with Succubus Warlock minion upon using emotes.

**Expected behaviour**: When you target the succubus with a /flirt or /kiss, a heart will appear above her head for a short time. 
**Steps to reproduce the problem**:

1. Aply emote as "flirt" or "kiss"

**Include proofs for this behaviour**

https://wow.gamepedia.com/Succubus_(warlock_minion) - section "Trivia". 

![image](https://user-images.githubusercontent.com/15208895/41496979-ce997cb6-7154-11e8-8671-39f63984b70f.png)

**Comment by Golganeth** [comment]
Don't think this was already a thing back in WotLK. All the sources indicate this was introduced in a later expansion.

Closing until WotLK proof is provided.
