### ISSUE TITLE
Ancient petrified leaf :Lvl 60 hunter epic weapon quest chain .

### ISSUE THREAD

**Issue by rubybt** [dalaranwow/dalaran-wow#5530]
Quest chain could not be completed atm due to critical issues:
1. Stave of the ancients quest: Solenor the slayer (silithus demon) does not drop the head (tryed to kill in grp and solo with/without pet)

2. A proper string quest: the quest item (mature black dragon sinew) should drop (according to wowhead) from any black dragon in burning steppes, but it doesnt, though while having a quest in quest log and hovering the cursor over black dragons in BS it shows mature black dragon sinew 0/1(this item also should drop from onyxia both lvl 60 and lvl 80 versions, but i didnt had a chance to test it).

**Comment by TeridanDW** [comment]
#974
