### ISSUE TITLE
Warlock: Player pet's abilities and out of range error

### ISSUE THREAD

**Issue by Warlockboss** [dalaranwow/dalaran-wow#554]
Right now, after commanding your pet to use certain ability on the target which is out of range, pet does nothing and you get "out of range" error.
What is expected to happen: pet will go towards the target and as soon as it is in valid range ability will be used.
Here is a thread in which retail players discuss this mechanic and felhunter's spell lock. 
http://www.arenajunkies.com/topic/179737-stupid-spell-lock-question/

**Comment by Rushor** [comment]
4b5307dc31b32f348ee8013f9270ef6bed32cd6f
- pets will now follow the target if not in los and will only start castng the spell if they are in los with the target
