### ISSUE TITLE
Quest: "Oh Noes, the Tadpoles!" Horde

### ISSUE THREAD

**Issue by Aneuk91** [dalaranwow/dalaran-wow#5540]
I am currently doing the quest "Oh Noes, the Tadpoles!" in the Borean Tundra with my troll mage. 

The quest is not working as it did in retail. Every cage you open should release the visual number of tiny murlocs. On the server it only counts the cage. So you have to open 20 cages instead of maybe 5 or 6.

**Comment by Golganeth** [comment]
#845
