### ISSUE TITLE
Warlock lvl 20 mount bug

### ISSUE THREAD

**Issue by Revnan** [dalaranwow/dalaran-wow#5547]
When I leveled to 20 I went to get warlock mount, the warlock trainer Zevrost in Ogrimmars Cleft of Shadows trained me to ride the mount (or so I thought). The ability to train the mount without any rider skill was possible. I paid, got skill learn animation and instead of mount, learned basic riding skill. Now riding skill cannot be learned from riding trainer and warlock mount is gone from list of skills to train from trainers. I have riding skill but no warlock mount.

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)

**Expected behaviour**: Mount training should be locked until riding skill is aquired or else not require it.

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Include proofs for this behaviour**

You can research this on several pages like http://wowhead.com or http://wowwiki.wikia.com or http://www.youtube.com/
Issues without proofs will be closed and tag On Hold will be added until the proof is provided.

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

You can research this on several pages like https://wowgaming.altervista.org/aowow/ or https://wowhead.com/

**Include Screenshots from the issue if necessary**

**Comment by Golganeth** [comment]
If you have learned it and you can't learn it anymore it must be there, please check the correct tab of skills, spells and mounts.

If the issue persists please attach proper screenshots so we can look further into it.

Closing
