### ISSUE TITLE
Unable to queue Random Heroic

### ISSUE THREAD

**Issue by Imbarawr** [dalaranwow/dalaran-wow#5554]
**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
When saved to every wotlk hc and attempting to join a random heroic you get a message saying "You do not meet the requirements for the chosen dungeons." and you are unable to search for a random hc.

**Expected behaviour**: Tell us what should happen instead
Once the pool of hcs is emptied you should still be able to search for random heroics.

**Steps to reproduce the problem**:

1. Get saved to all avaliable hcs
2. attempt to join random hc
3. 

**Include proofs for this behaviour**
N/A

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**
N/A

**Include Screenshots from the issue if necessary**
N/A

**Comment by lkrocek** [comment]
Yes, that was working as described from 3.0 I remember it really well.

**Comment by galgnu** [comment]
There is an old issue for this already - please search and add to that and close this one.

**Comment by Golganeth** [comment]
Duplicate #2954
