### ISSUE TITLE
Recruit a friend - email missing

### ISSUE THREAD

**Issue by Blahyn** [dalaranwow/dalaran-wow#5556]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Recruit a friend - email missing 

**Expected behaviour**: Hello we start with few friends play on this realm and some players dont have the email of recruit a friend we try use more email but still nothink happend.

**Steps to reproduce the problem**:

1. 
2. 
3. 

**Include proofs for this behaviour**

**Include Screenshots from the issue if necessary**

Thanks for advice

**Comment by Golganeth** [comment]
This is the in-game bugtracker, which lists in-game mechanic issues that can affect players.
Make sure you followed all the steps explained on the forums: [>click me<](http://www.dalaran-wow.com/forums/news-and-rules/rules-and-guidelines/topic/2565/how-to-use-the-recruit-a-friend). Also make sure to check your spam folder.

If the issue persists, please contact us at dalaran.community@gmail.com explaining your problem. Include your account name(s), e-mail(s) and any other relevant info.

Closing up
