### ISSUE TITLE
[HC] Azjol-Nerub no epic drop from last boss

### ISSUE THREAD

**Issue by BongoPachanga** [dalaranwow/dalaran-wow#5559]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**:  No epic item drop from last boss - Anub'arak

**Expected behaviour**: There sohuld be 1 epic item drop from last boss.

**Steps to reproduce the problem**:

1. Queue azjol nerub
2. Kill Anub'arak

**Comment by galgnu** [comment]
Done the instance 10+ times on heroic, even last night. Epics drop all the time. 
Are you on Kirin Tor or something?

**Comment by BongoPachanga** [comment]
Done the instance last 2 months almost every day with different characters, havent seen epic loot from this boss, also other ppl confirm it. Are u troll or blind?

https://ibb.co/egvwFe
https://ibb.co/jZ07MK

**Comment by boujii** [comment]
[img]https://i.imgur.com/ctUqYIP.png[/img]
[img]https://i.imgur.com/uj6pdfG.png[/img]

**Comment by lkrocek** [comment]
epic drop has not a 100% in azjol-nerub, it happens kinda often there are no epics from last boss, it's bug on Algalon

**Comment by Golganeth** [comment]
Confirmed.

**Comment by Lothloryen** [comment]
Hello there,

This will be corrected after the next maintenance.

Regards.
