### ISSUE TITLE
Instance / NPC: The Nexus - Crazed Mana-Surge

### ISSUE THREAD

**Issue by Golganeth** [dalaranwow/dalaran-wow#556]
**Issue:** These NPCs are not attacking the players and they are not attackable either.

**How it should work:** They should get pulled when approaching or when casting any harmful spell on them, just like the rest of the mobs. On the other hand, they should have the following abilities:

*5 man normal* - **Crazed Mana-Surge:** http://wotlk.openwow.com/npc=26737
- **Arcane Nova:** http://wotlk.openwow.com/spell=47696
- **Loose Mana:**  http://wotlk.openwow.com/spell=29882
- **Mana Burn:** http://wotlk.openwow.com/spell=48054

------------------------------------------
-------------------------------------------

*5 man heroic* - **Crazed Mana-Surge:** http://wotlk.openwow.com/npc=30519
- **Arcane Nova:** http://wotlk.openwow.com/spell=57046
- **Loose Mana:** http://wotlk.openwow.com/spell=29882
- **Mana Burn:** http://wotlk.openwow.com/spell=57047

**Comment by JunkyBulgaria** [comment]
UPDATE `creature_template` SET `unit_flags`=0 WHERE  `entry` in(26736, 26761); 
temp fix

**Comment by jonanone** [comment]
Npc flags have been updated. These fixes will be applied to the live realm soon.

**Comment by jonanone** [comment]
NPC flags have been updated. The fix will be applied to the live realm soon.
