### ISSUE TITLE
Quest not working correctly, "Investigate the Blue Recluse" (ID 1920)

### ISSUE THREAD

**Issue by gorgonical** [dalaranwow/dalaran-wow#5561]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**:

Where: Stormwind, Mage Quarter, Blue Recluse Inn
What: 
1. When using the quest item "Cantation of Manifestation", all rift spawns summon at the same time, making the quest extremely difficult to do at-level. 
2. The rift spawns are not capturable with the other quest item, "Chest of Containment Coffers"; the rift spawns never get "stunned" and are thus never capturable. I have also tried to place the coffer first before summoning the spawn, as well as placing it midway through the fight. Even if the coffer is down and in the world when I kill the spawn, it does not capture it.
3. There are no visible rifts to indicate where you should use the cantation at. I had to aimlessly walk around the inn using it before they would spawn.

**Expected behaviour**:

1. When using the cantation, only one or two rift spawns should spawn, depending on how many rifts you are in range of.
2. The rift spawns should become stunned at some point (I have read at around 10% HP), so that they can be captured by using the "Chest of Containment Coffers".
3. The mana rifts should be visible in the game world.

**Steps to reproduce the problem**:

1. Accept quest from Jennea Cannon in the Wizard's Sanctum.
2. Grab a cantation and containment coffers from the table behind her.
3. Go to the nearby Blue Recluse Inn and to the back high balcony, or into the basement with the barrels.
4. Note that no rifts are visible in either place. (issue 3)
5. Use the cantation in one of these two places. Note that all four rift spawns will summon and aggro to you. (issue 1)
6. Defeat one spawn, noting that you cannot "stun" the spawn to capture it. Note also that placing the containment coffer before or during the fight does not capture the spawn, either. (issue 2)

**Include proofs for this behaviour**

Video of issue 2: https://youtu.be/GTA9snZAnH8
Video of issues 1 and 3: https://youtu.be/dcyMPRjWEac

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

NPC -- Rift Spawn -- 6492
Quest -- Investigate the Blue Recluse -- 1920
Item -- Cantation of Manifestation -- 7308
Item -- Chest of Containement Coffers -- 7247
Zone -- Stormwind City -- 1519

**Include Screenshots from the issue if necessary**

**Comment by Golganeth** [comment]
#5417
