### ISSUE TITLE
Demonic Brutality talent is not adding the proper bonus to Felguard Demonic Frenzy

### ISSUE THREAD

**Issue by Maleficen** [dalaranwow/dalaran-wow#5565]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**:
Demonic Brutality (Warlock Tier 2) talent is not adding the proper bonus to Felguard Demonic Frenzy. Even with 3 points in the talent, the bonus is still 50%.

**Expected behaviour**:
Attack bonus from this talent should be 80% at full stacks instead of 50% with 3 points in Demonic Brutality.

**Steps to reproduce the problem**:
1. Put 3 talent points in Demonic Brutality
2. Let your Felguard attack until the stacks fill up to see bonus damage

**Include Screenshots from the issue if necessary**
![wowscrnshot_073118_182333](https://user-images.githubusercontent.com/42087862/43674571-c6482e80-97de-11e8-914b-cd4be2d8449a.jpg)

**Comment by Golganeth** [comment]
Same as #5566, this is same case as on retail, where the buff & debuff tooltips don't take into account any talents/glyphs, so they will always show the default amount.

You can check the correct amount in your action bar/spellbook tooltip. Thanks

Closing.
