### ISSUE TITLE
Glyph of Soul Link is not adding the 5% shared damage

### ISSUE THREAD

**Issue by Maleficen** [dalaranwow/dalaran-wow#5566]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**:
Soul Link (Warlock Tier 3) talent is not being affected by Glyph of Soul Link and still shows 20% of shared damage.

**Expected behaviour**:
Soul Link with glyph should give 25% shared damage instead of 20%.

**Steps to reproduce the problem**:
1. Pick Soul Link talent
2. Get Glyph of Soul Link

**Include Screenshots from the issue if necessary**
![wowscrnshot_080418_120948](https://user-images.githubusercontent.com/42087862/43674619-b5d3be06-97df-11e8-8a0d-f639f24e5b14.jpg)

**Comment by Golganeth** [comment]
This is same case as on retail, where the buff & debuff tooltips don't take into account any talents/glyphs, so they will always show the default amount.

You can check the correct amount in your action bar/spellbook tooltip. Thanks

Closing.
