### ISSUE TITLE
Book "Soothsaying for dummies" does not work

### ISSUE THREAD

**Issue by lkrocek** [dalaranwow/dalaran-wow#5569]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
In Tanaris there is book to learn or unlearn engineering specialization (goblin to gnomish) once you have one specialization done, but the book has no options. Have skill 450, gnomish spec.

**Expected behaviour**: Tell us what should happen instead
The book should offer to learn or unlearn specialization.

**Include proofs for this behaviour**
http://www.wowhead.com/forums&topic=107035.1

**Comment by lkrocek** [comment]
any alternates how to fix it asap? I want make a bullets from icc and unlearn/learn whole engi and do it again it consume a time and lot of golds, and GMs are not responding for this.

**Comment by TeridanDW** [comment]
Hello,
Already adressed in #870
