### ISSUE TITLE
Quest The Warm-Up

### ISSUE THREAD

**Issue by Crispybuilt** [dalaranwow/dalaran-wow#557]
**Quest The Warm-Up** - *12996*

- **Issue present:** When the player defeats **Kirgaraak** *(ID:29352)*, he doesn't get the credit. This is a problem because there is another NPC which is actually called **Kirgaraak Kill Credit** *(ID:30221)*, the purpose of that NPC is to give you credit.
I tested it myself , if I spawn **Kirgaraak Kill Credit** and force kill him (he is friendly), I will get the credit.

Players, when they kill **Kirgaraak** *(ID:29352)* are not getting the credit for the quest, and they should. The thing is that **Kirgaraak** *(ID:29352)* actually becomes friendly when he reaches 2-5% (but his model/mask/different ID doesn't change) unless you burst him down fast and kill him (he also doesn't give credit then either).

- **How it should work:** When you kill **Kirgaraak** *29352*, give the player credit for it.

_________________________________________

- Possible fix: Implement the same fix just like for Matis the Cruel #18 and also add characteristics of Kaw the Mammoth Destroyer #139.

- *(The most logical issue how the script should work)*
When player reaches 2% of the boss, quickly switch the npc to **Kirgaraak Kill Credit** *(ID:30221)* (even though if friendly) but still attackable and lock his HP on 2%. Next hit with the Bear on the him will give the credit because it will "damage" him but won't actually kill him. After credit is given, reset back **Kirgaraak** *(ID:29352)* and make him chained.

**Minor issue** - He also isn't chained as he is supposed to be, before and every time when he's defeated., He has to be chained all the time and have limited area to move around with chains when player is fighing him.
Also, he should reset every time if a player decides to attack him without a **Reins of the Warbear Matriarch** *(ID:42499)*. He should only trigger if attacked by a **Reins of the Warbear Matriarch** *(ID:42499)*. Simillar to issue: #139 

**Video of how it should work:** http://www.youtube.com/watch?v=bLyEsHZ-fSs

___________
http://wotlk.openwow.com/npc=30221
http://www.wowhead.com/quest=12996/the-warm-up
http://wotlk.openwow.com/quest=12996
http://wotlk.openwow.com/npc=30221

**Comment by Lothloryen** [comment]
Working since long time ago.

**Comment by Kepithor** [comment]
Kirgaraak is underground and un-attackable

**Comment by Rushor** [comment]
in the future there will be a reset script added
