### ISSUE TITLE
[HC][Northrend][Dungeon] Ley-Guardian Eregos in Oculus disappear

### ISSUE THREAD

**Issue by lkrocek** [dalaranwow/dalaran-wow#5571]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
Ley-Guardian Eregos boss disappear and don't get back in Oculus when you go out of combat.

**Expected behaviour**: Tell us what should happen instead
when you go out of combat boss shouldn't disappear.

**Steps to reproduce the problem**:

1. Pull Ley-Guardian Eregos boss in oculus HC
2. jump out of one mount-dragon
3. use shadowmeld, vanish, feign death, whatever else what you switch out of combat
4. observe boss is disappeared and will not go back (random dungeon finder failed ...)

**Comment by arestavo** [comment]
Still an issue.

**Comment by Lothloryen** [comment]
#2801
