### ISSUE TITLE
Toy Train Set doesn't have /train effect around

### ISSUE THREAD

**Issue by lkrocek** [dalaranwow/dalaran-wow#5577]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**:
usage Toy Train Set is not doing /train for players around

**Expected behaviour**:
Toy Train Set should do /train for people near to the object, when /train ends it should proc again so the spell is repeating 12sec (Radius: 5 yards)
https://www.youtube.com/watch?v=lvOTGX-RGSU

**Steps to reproduce the problem**:

1. Put Toy Train Set down on the ground
2. characters going near this should do /train emote but they doesn't

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**
https://wowgaming.altervista.org/aowow/?item=44606
https://wowgaming.altervista.org/aowow/?spell=61551

**Comment by Golganeth** [comment]
On PTR. Duplicate #1323
