### ISSUE TITLE
Random BG's quest (Call to the Arms) is not giving arena points rewards

### ISSUE THREAD

**Issue by Maleficen** [dalaranwow/dalaran-wow#5579]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**:
After winning any battleground through the random battleground queue, you get the honor bonus reward but not the arena points,

**Expected behaviour**:
You should receive also the arena points from the reward.

**Steps to reproduce the problem**:
1. Queue to Call to the Arms battleground and win
2. Arena points are not received

**Comment by Maleficen** [comment]
Seems that arena points rewards are only given at lvl 80.

**Comment by Golganeth** [comment]
All the sources from WotLK that I could find do not say otherwise about Arena Points before level 80 -> [Example](https://www.wowhead.com/item=43307/arena-points#comments:id=910651:reply=144856)
Closing until proper proof is provided.
