### ISSUE TITLE
Instance / Boss: Blackwing Lair / Razorgore the Untamed

### ISSUE THREAD

**Issue by yardieirl** [dalaranwow/dalaran-wow#558]
This boss doesn't work properly , here is the problems: 

-You can't control him (razorgore)
- You can click the eggs (After you click all the eggs still you can't kill him his HP reach 1 and unkillable.)
- Adds doesn't spawn at all.

Here's a video how it suppose to work:
http://www.youtube.com/watch?v=bXg3HFLU6q8

**Comment by Rushor** [comment]
controle works fine http://i.imgur.com/IZlDhJ5.jpg
egg despawn works fine http://i.imgur.com/H4ihmv5.jpg
attack boss after enough eggs are destroyed works fine http://i.imgur.com/4qkT5Ba.jpg
kill and loot boss after charm ends works fine http://i.imgur.com/4nND90M.jpg

closing
