### ISSUE TITLE
Mage Quest Bug - Investigate the blue Recluse.

### ISSUE THREAD

**Issue by Helvorn** [dalaranwow/dalaran-wow#5580]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Unable to kill the rift spawns and put them in containment coffers for the quest.
**Expected behaviour**: Should be able to kill them, activate the item and complete the quest. 

**Steps to reproduce the problem**:

1. Get the quest on the mage tower in Stormwind City. 
2. Go to the Blue Recluse Tavern in the same city quarter.
3. Activate the item that summons the blue recluses, try to kill them.

**Include proofs for this behaviour**

http://www.wowhead.com/quest=1920/investigate-the-blue-recluse

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

**Include Screenshots from the issue if necessary**

**Comment by Golganeth** [comment]
#5417

**Comment by boujii** [comment]
![image](https://user-images.githubusercontent.com/1514895/43919183-34102f8c-9be3-11e8-9db3-2f4116075f59.png)

Investigate the Blue Recluse

Obtain a Cantation of Manifestation and a Chest of Containment coffers from behind Jennea Cannon.  Bring 3 Filled Containment Coffers to Jennea at the Wizard's Sanctum.

A disturbance has been reported at the Blue Recluse tavern in the Mage Quarter.  Strange, invisible creatures now wander the tavern, and I fear a mana rift has formed there.$B$BI want you to investigate the tavern and capture those creatures.  Use the cantation of manifestation in the tavern to make the creatures visible, subdue them then use a containment coffer to capture them.  When you have enough, return to me with your filled coffers, your empty coffers and the cantation.

Return to Jennea Cannon in Stormwind City.

Required Item ID in bag.
![image](https://user-images.githubusercontent.com/1514895/43919295-804d5e56-9be3-11e8-8306-2cec510fed5c.png)

**Comment by boujii** [comment]
Seen your post Golfaneth as duplicate. Will follow up there.
