### ISSUE TITLE
[Naxxaramas] Polarity bonus debuff persist on logout

### ISSUE THREAD

**Issue by lkrocek** [dalaranwow/dalaran-wow#5584]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: 
Bonus damage debuff from Thadius(10 and 25m) is persist while logout.

**Expected behaviour**:
Unlimited debuff should disappear with the timed one.

**Steps to reproduce the problem**:

1. gain polarity timed debuff to deal damage around and unlimited debuff to increase player damage
2. when boss fight ends logout before timed debuff disappear
3. wait a short time to expire the timed debuff
4. log back
5. observe timed debuff disappeared but unlimited persist

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

https://wotlk.evowow.com/?spell=28085
https://wotlk.evowow.com/?spell=39093

NOTE: debuff persist even I switch spec, relog. It disappear only when I die or leaver the instance.

**Comment by Lothloryen** [comment]
Hello there,

Thank you very much for the report, this issue will be corrected after the next scheduled maintenance.

**Comment by lkrocek** [comment]
@Lothloryen fixed but still possible to keep it up ... 

1. get the polarity debuff
2. alt + f4 and login or open the second client to login but **don't enter the world yet**
3. wait till the boss is dead
4. enter the world
5. buff is up
