### ISSUE TITLE
[Ruby Sanctum] Attunement

### ISSUE THREAD

**Issue by lkrocek** [dalaranwow/dalaran-wow#5591]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**:
Was announced Ruby Sanctum will require The Frozen Throne Achievement

**Expected behaviour**: 
Ruby Sanctum should require Fall of the Lich King Achievement. Each raid instance require to have achievement for all bosses in previous instance, why should be a different here?

**Include proofs for this behaviour**
http://www.dalaran-wow.com/news/128/ruby-sanctum-s-official-release-date/

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

https://wotlk.evowow.com/?achievement=4532
https://wotlk.evowow.com/?achievement=4530

**Comment by lkrocek** [comment]
No clue if it was write down incorrectly on site or it is real, sorry ticket then if the announcement is incorrect.

small off-topic: will be ID for instance shared or separated as it is for Trial of Crusader Normal and Heroic?

**Comment by Zarjofgt** [comment]
Why the fuck are you writing this in the bug tracker

**Comment by lkrocek** [comment]
and where should I write this in-game issue?

**Comment by lkrocek** [comment]
well:

1. this is not game for dummies, you shouldn't have to be so rude on another people, this is serious bug tracker not a forum for flame wars
2. you should make a constructive answers, that mean say why I don't report it here more than wait for my question, it's making so more meaningless comments here
3. learn to read a rules early than you say something you did:

> The issuetracker is for serverside and gamemechanic issues only.

https://github.com/dalaranwow/dalaran-wow

**Comment by mrnuggets** [comment]
Why is this even a thing? It's not an issue, it's not a bug, nothing to report, just some misspelling on the Ruby Sanctum article? Dafuq.

**Comment by boujii** [comment]
A simple "This is not a bug, please post on forum" would had suffice. I don't understand why such negativity.

**Comment by Lothloryen** [comment]
Hello there,

We've corrected the text, it was our mistake. Even though this is not the place to remark such things, thanks for the heads up.
