### ISSUE TITLE
Mobs dont cast spells in Tirisfal Glades

### ISSUE THREAD

**Issue by digiwow88** [dalaranwow/dalaran-wow#560]
I've been leveling for two days in Tirisfal, and have noticed that a large percentage of the mobs I fought with weren't using any abilities at all, even if they had a mana pool
.
I have checked the problematic NPCs' pages on wowhead.com, so I am 100% sure that on retail, they have abilities.

I'd like to post a list with the names of the bugged creatures, hoping that something can be done about this annoying phenomenon. I would also like to ask you to check the large majority of mobs (especially the spellcaster types) in Tirisfal whether they can use abilities or not, because I haven't got all the names written down.

Felliant's Spirit
Wandering Spirit
Rotting Ancestor
Maggot Eye
Rot Hide Graverobber
Rot Hide Gnoll
Scarlet Initiate
Nissa Agamand
Vile Fin Minor Oracle
Vile Fin Muckdweller
Sri'skulk
Lost Soul
Scarlet Missionary
Captain Perrine
Scarlet Zealot
Hungering Dead

On the positive side, I'd like to add that Agamand Mills zone had many properly functioning mobs (Devlin Agamand, Wailing Ancestor, the majority of the Agamand family and the skeleton frost mage whose name I can't remember). 

Thank you for reading my "complaint", I hope my contribution will be useful for debugging the server.

Cheers :)

**Comment by Rushor** [comment]
2d36aafa9c5f6fb2ae4085ac5827fa958585a4c5
DB/Creature: Add abilities for creatures in Tirisfal Glades

* closes https://github.com/dalaranwow/dalaran-wow/issues/560

for more details (what will trigger the spellcast?) just look into the commit :)
