### ISSUE TITLE
Edited report.

### ISSUE THREAD

**Issue by mrfixit4210** [dalaranwow/dalaran-wow#5602]
Edited

**Comment by MalkaviaDW** [comment]
Thanks for the report, I've edited it and forwarded to the devs. Cheers!

**Comment by mrfixit4210** [comment]
Will there be a following update, if this issue is fixed? I don't want to feel like you are trying to censor or just look the other way with this issue. I mean, AT had this fixed, shouldnt be hard to fix. :-)
