### ISSUE TITLE
Character customization broken

### ISSUE THREAD

**Issue by iflashfrgold** [dalaranwow/dalaran-wow#5615]
After donation for Character Customization,  you can get to the "customize" screen,  but cannot actually complete customizing the character.     Receive message "could not customize the character".

no support on forums as well.

**Comment by Golganeth** [comment]
Invalid report. This is the in-game bugtracker, which lists in-game mechanic issues that can affect players.

Just a quick note in case you are using a custom or modified WotLK client: we do not recommend using one, they tend to cause errors very often.

Closing.

**Comment by iflashfrgold** [comment]
> 
> 
> Invalid report. This is the in-game bugtracker, which lists in-game mechanic issues that can affect players.
> 
> Just a quick note in case you are using a custom or modified WotLK client: we do not recommend using one, they tend to cause errors very often.
> 
> Closing.

I would think this IS an ingame issue...  I'm using the dala wow client...
