### ISSUE TITLE
[Quest][Northrend] Foundation for Revenge

### ISSUE THREAD

**Issue by Crispybuilt** [dalaranwow/dalaran-wow#562]
**Quest Foundation for Revenge** - *12668*

- **Issue present:** For some reason most of the time you do not get credit (around 95% of the time) when you kill **Quetz'lun Worshipper** *(ID:28713)* or **Serpent-Touched Berserk** *(ID:28748)* near the object **Soul Font** *(ID:190707)*.

This is most probably related to Credit bunny: **Quetz'lun Troll Worshipper Kill Credit Bunny** *(ID:28713)*.
I was testing it and it works if you stand 90° to the left or right from the **Soul Font** *(ID:190707)*. It doesn't work if you stand infront or on the back, it also doesn't work with all the **Soul Fonts**. The only two working I found were on these locations: 

*X:5689.839844 Y:-4294.939941 Z:373.994995 MapId:571*
*X:5742.689941 Y:-4293.649902 Z:373.994995 MapId:571* 

*It could also be related to the spell issue:* **Ghostly, rank 1 enUS** - *51671*, since sometimes you are unable to use it in some zones and buff goes down. (atleast for Game Masters)
____________________________________

http://wotlk.openwow.com/quest=12668
http://www.wowhead.com/quest=12668/foundation-for-revenge

**Comment by Taffa2** [comment]
Proximity is working ok.  But if you are in a party not everyone gets credit for the kill.  Only the person that gets the first hit gets credit.  So if you are in a party of 5 you will be killing 60 of the mobs.  With each person taking turns on hitting the mob first for their 12.

**Comment by MrAndersonX** [comment]
Confirmed - bugged - mobs reach 1 HP, then cannot be killed. Needs a fix.

**Comment by Rushor** [comment]
quest should now work better
