### ISSUE TITLE
Quest: Battle of Hillsbrad (Part 4)

### ISSUE THREAD

**Issue by smask18** [dalaranwow/dalaran-wow#5621]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**:  In mission The battle of Hillsbrad (part 4), the Hillsbrad Town Registry item can not be obtained the container does not give it.
**Expected behaviour**: the container must drop Hillsbrad Town Registry

**Steps to reproduce the problem**:

1.  open the container
2. 
3. 

**Include proofs for this behaviour**

https://wotlk-twinhead.twinstar.cz/?quest=532
https://wotlk.evowow.com/?quest=532

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

Hillsbrad Town Registry: https://wotlk.evowow.com/?item=3657

**Include Screenshots from the issue if necessary**

![wowscrnshot_102918_205218](https://user-images.githubusercontent.com/44592648/47690605-ac8c2380-dbbc-11e8-951f-a31828c7ed5d.jpg)
![wowscrnshot_102918_205232](https://user-images.githubusercontent.com/44592648/47690606-ac8c2380-dbbc-11e8-9ce5-9dee165d35dc.jpg)

**Comment by Golganeth** [comment]
General and rare issue with gameobjects. Fixed in-game. 
Quest itself works just fine.

Closing
