### ISSUE TITLE
Level 70 Boost Issue

### ISSUE THREAD

**Issue by Dralcei** [dalaranwow/dalaran-wow#5625]
I boosted my hunter and it made him into a warrior, unsure why. I picked mail gear when asked. I deleted him and reboosted another and choose leather gear and he worked out. I had to replace all the gear I got because it wasn't really hunter gear. Could I get a refund on my donation points for the toon I had to delete please?

**Comment by Golganeth** [comment]
This is the in-game bugtracker, which lists in-game mechanic issues that can affect players.

When purchasing anything from the website, please make sure you select the correct character and realm. If you made a mistake, please send an e-mail to "dalaran.community@gmail.com", add all the relevant information (such as characters and account name, date of purchase, etc.) and we will make our best to help you, I'm not sure why you deleted the first character though.

Closing.
