### ISSUE TITLE
Quest: Sarathstra, Scourge of the North

### ISSUE THREAD

**Issue by Sagrath** [dalaranwow/dalaran-wow#563]
http://www.wowhead.com/quest=12097/sarathstra-scourge-of-the-north

The NPC "Rokhan" Should summon "Sarathstra" But Rokhan dont have a gossip menu to call down Sarathstra
Rokhan: wowhead.com/npc=26859

**Comment by Golganeth** [comment]
Hotfixed. Now players won't need a flying mount to kill the NPC manually.

**Comment by cover25** [comment]
Still can't been seen/no option to summon her.

**Comment by Vandreth** [comment]
No option to summon mob and it does not seem possible for the mob to be even attacked by players without a flying mount. They fly nearly 50 yards in the air and path at approximately 280% movement speed. Sarathstra seemingly disappears for minutes at a time from Dragon's Fall and the immediate area only to show up sporadically still pathing far in the air.

**Comment by deltafoxnine** [comment]
Comfirmed, still bugged, can't get her to the ground.

**Comment by Brothus** [comment]
Confirmed x 2, still bugged.

**Comment by exiledone** [comment]
u need a flying mount to reach her. can only be done while she flyies over some of the small rock formations. stay on top and u will aggro her.
my problem is that the heart doesnt drop. is that bugged?

**Comment by Lothloryen** [comment]
This quest will be working as it should after the next realm maintenance.

Thank you.
