### ISSUE TITLE
Error with entering server 

### ISSUE THREAD

**Issue by Wintertitan** [dalaranwow/dalaran-wow#5636]
Current behaviour: Tell us what happens in detail (Where, When, What, Why, Who)
I cannot enter the server. I downloaded client 3.3.5.a (as per instruction on website), when I try to log in I get a screen with information that a Patch is downloading. After a while I restart and get the error visible on screenshot.
![wowscrnshot_112318_172852](https://user-images.githubusercontent.com/45294560/48953422-18f10d00-ef46-11e8-98fa-923bc9adbec2.jpg)

Please help

**Comment by MalkaviaDW** [comment]
Hello there, 
Try to log in with your username, and it should work.
Cheers!

**Comment by MalkaviaDW** [comment]
That happens because you are using your email, use your username instead and it will work just fine.

**Comment by Wintertitan** [comment]
Thanks!
