### ISSUE TITLE
World map not showing quests

### ISSUE THREAD

**Issue by momomanli** [dalaranwow/dalaran-wow#5639]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: World map not showing quests

**Expected behaviour**: It should show them

**Steps to reproduce the problem**:

1. open world map once: everything is normal, quests are showing.
2. close it.
3. re open it then they are gone

![behindert](https://user-images.githubusercontent.com/45316538/48978567-5e7c1a00-f0ad-11e8-81d4-273c5c13e29f.PNG)

**Comment by Golganeth** [comment]
Looks like a client issue, abandoning or completing a quest should fix the issue right away, as well as closing your game client completely and clearing your Cache folder.

Closing
