### ISSUE TITLE
Minor bug - Druid lv 70 boost

### ISSUE THREAD

**Issue by acidviews** [dalaranwow/dalaran-wow#5652]
Instant lv 70 for free :D
Thank you very much i am greatly enjoying the server!
Big thank you and great job well done tyvm.

I am just reporting a minor bug with a horde druid 70 boost
I got 2 gloves in the mail but no waist piece.
Also for some reason i cannot comment on the forums
it says i cant because i dont have a character, even though i have 2
account name is gankstar
And thats all. 

Thank you so much
happy new year :)

**Comment by Chenocide** [comment]
You need a Kirin Tor character to be able to comment on the forums.

**Comment by acidviews** [comment]
aahh 
ok ill do that thank you

**Comment by Chenocide** [comment]
Btw, this is a problem for rouges too, who receive 2 leather gloves but only 1 one-handed weapon.

**Comment by acidviews** [comment]
also i just noticed before that there was no trinkets, only 1 ring, and no stats on the legs. This did make the pvp impossible but also, questing is interesting and rewarding as you complete quests, you really look foward to the average ilv green drop as they are a bit better then what is supplied.

I did start a character on kirin tor just for forums, now its all good!
Thanks for the reply, i wished i new how to help out with the project code wise,
ill keep voting 
great job guys!

**Comment by Lothloryen** [comment]
This was fixed already, thank you for the report.
