### ISSUE TITLE
Quest: Let's Go Surfing Now

### ISSUE THREAD

**Issue by Sagrath** [dalaranwow/dalaran-wow#566]
The Quest Let's Go Surfing Now (http://old.wowhead.com/quest=11436)

How it should work :
Use the lever next to the harpoon to be launched in the air on a flamming harpoon back to Vangarde to complete your quest in style.

How it does work :
You are mounted on the flamming harpoon but you are stuck on spot and cant move.

**Comment by Tarpor** [comment]
This quest is still bugged and can not be turned in even if you have a greyed-out question mark as said above.

**Comment by Lothloryen** [comment]
Hello there,

This quest will be working after the next realm restart.

Thank you.
