### ISSUE TITLE
[Quest] [NPC] The Missing Diplomat - Dashel Stonefist

### ISSUE THREAD

**Issue by Helvorn** [dalaranwow/dalaran-wow#5664]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: During this part of The Missing Diplomat quest line you are supposed to confront Dashel Stonefist, a dwarf on an alley in Old Town, Stormwind. He calls a couple of thugs on you and after you deal some blows he calls off the attack. The problem is the quest does not advance after that. He should give me the next step of the quest. Also the thugs never turn green again. They are red and fight to death.
**Expected behaviour**: Thugs should stop attacking after Dashel tells them to. Afterwards, Stonefist should give me the next part of the quest. 

**Steps to reproduce the problem**:

1. Start the missing diplomat quest and get to the point where you are sent to talk to Deshel
2. Talk to him and his thugs show up.
3. Beat up thugs to death and fail to proceed to next part of quest. 

**Include proofs for this behaviour**
https://www.wowhead.com/quest=1246/the-missing-diplomat

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

https://www.wowhead.com/npc=4961/dashel-stonefist

**Include Screenshots from the issue if necessary**

**Comment by Golganeth** [comment]
According to [this Link](https://www.wowhead.com/quest=1246/the-missing-diplomat#comments) it's intended. You can also proceed to the next part flawlessly.

Closing
