### ISSUE TITLE
[Quest][Northrend] A Visit to the Doctor

### ISSUE THREAD

**Issue by Crispybuilt** [dalaranwow/dalaran-wow#569]
**Quest A Visit to the Doctor** - *13152*

**QUEST IS CURRENTLY WORKING BUT IT IS TOO EASY TO DO IT, HAS TO BE CORRECTED - there is no proper script made**

- **Issue**: 
**Patches** *(ID:30993)* should be friendly to players. (he is currently neutral, that is wrong and players can kill him)*
For the second part of the quest, where you have to help **Patches** to kill the **Doctor Sabnok** *(ID:30992)*, you do not even have to put effort in it. If you kill Patches, it will count towards the completion for the second quest objective. (Help Patches kill Doctor Sabnok) *(ID:30993)* - which is wrong and it shouldn't work like that.

- **How it should work**: Once you free **Patches** from his chains, **Doctor Sabnok** will spawn up there in his laboratory (behind tables) 
![image](https://f.cloud.github.com/assets/5054924/951839/54695be2-03b2-11e3-8cc1-b9d158c380fe.png)
and Patches will with you walk up to there. Then, you have to watch **Patches** how he kills the **Doctor Sabnok** and you will get the credit for it once the **Doctor Sabnok** is dead.
If you, as player, decides to do a single hit on a **Doctor Sabnok** and if you kill him before **Patches** can kill him, the quest will not count. *(even though Doctor should be completely non-interactable to players)*
**Patches** *needs to get his revenge, that is the point of the quest* - **Doctor Sabnok** should resist but with a minimum damage so **Patches can easily kill him**
**Patches** physical damage must be around 537 - 731 damage.

_____________________

- Following Dialogue most happen during the fight:

*"Patches" says: Patches get revenge on Doctor Sabnok!* - **(upon Patches aggroes him)**
*Doctor Sabnok says: Oh, bravo. Do you feel proud of yourself now that you've unleashed this terrible mistake?* **(after Patches finish his quote)**
*"Patches" says: Patches not going to be cut open or sewn up no more!* **(After Patches killes the Doctor)**

*WoWhead comment*
Do NOT attack the doctor. Although you will not be able to attack him, doing so will prevent you from getting credit after Patches kills him.
_________________________________________

http://www.wowwiki.com/Doctor_Sabnok
http://www.wowhead.com/npc=30993/patches#objective-of
http://www.wowhead.com/npc=30992/doctor-sabnok
http://wotlk.openwow.com/npc=30993#.
http://www.wowhead.com/quest=13152/a-visit-to-the-doctor
http://wotlk.openwow.com/quest=13152

**Comment by Rushor** [comment]
fixed long time ago with https://github.com/TrinityCore/TrinityCore/commit/9c61f2ce0c1972cf0f3b06cfcce6ecaef3935945

**Comment by Edzero** [comment]
The damage that Patches deals to Doctor Sabnok is not enough to trigger his death event. Instead Doctor Sabnok will kill Patches and the player will not receive credit. Patches' physical damage is currently around 280-350 rather than 537-731 as Crispybuilt said.

Current in-game workaround is for the player to deal a small amount of damage to Doctor Sabnok so that Patches can finish him off. Credit will be given in this scenario.
