### ISSUE TITLE
Quest: Fresh Remounts(bugged because you can't attack the knight)

### ISSUE THREAD

**Issue by WoWOriginProjects** [dalaranwow/dalaran-wow#5690]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)

**Expected behaviour**: Tell us what should happen instead

**Steps to reproduce the problem**:

1. Accept the quest "Fresh Remounts" from Venomspite
2. Try to attack the Knight on the horse in New Hearthglen
3. Melee attacks do not effect the Knight but ranged attacks do, making it very hard to complete for the majority of classes.
4. Can be fixed by making the knight attackable.

**Include proofs for this behaviour**

QUEST: https://www.wowhead.com/quest=12214/fresh-remounts
HORSE: https://www.wowhead.com/npc=27213/onslaught-warhorse
KNIGHT: https://www.wowhead.com/npc=27206/onslaught-knight

You can research this on several pages like https://wowgaming.altervista.org/aowow/ or https://wowhead.com/

**Include Screenshots from the issue if necessary**
https://i.postimg.cc/FFG4WKts/Wo-WScrn-Shot-021619-174809.jpg
https://i.postimg.cc/RhPxNg1n/Wo-WScrn-Shot-021619-174327.jpg

**Comment by Lothloryen** [comment]
#637
