### ISSUE TITLE
Ghostlands Errors

### ISSUE THREAD

**Issue by Soulfighter56** [dalaranwow/dalaran-wow#5695]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Areas in Ghostlands are devoid of mobs that should be present (South of Farstrider Enclave). Mining nodes are stacked (copper, tin, silver all inside of each other). Certain areas of mobs are over-populated (troll areas, ghosts in the lake, night elf encampments, lynx/bat areas in the North). Caster/ranged mobs do not always move to regain Line Of Sight (cultists in ziggurats, throwing-weapon trolls).

**Expected behaviour**: Missing mob spawns should be added back in. Mining nodes should not spawn on top of each other. Double-spawns of mobs at one spawn location should not happen. Caster/ranged mobs should move to regain Line Of Sight.

**Steps to reproduce the problem**:

1. Observed in the 10-20 Blood Elf zone, Ghostlands.
2. 
3. 

**Include proofs for this behaviour**

A quick run through the zone is sufficient proof of these behaviors as they are consistent.

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

Ghostlands, Eastern Kingdoms

**Include Screenshots from the issue if necessary**

N/A

**Comment by Golganeth** [comment]
Duplicated.
#1208 Fixed - Waiting for PTR update
#2736 Fixed - On PTR

Closing.
