### ISSUE TITLE
Quest: On Spirit's Wings

### ISSUE THREAD

**Issue by Crispybuilt** [dalaranwow/dalaran-wow#570]
**Quest On Spirit's Wings - 10714**

- **Issue present:** After using item **Rexxar's Whistle** *(ID:31128)*, on the location where **Bloodmaul Soothsayer** *(ID:22384)* & **Bloodmaul Taskmaster** *(ID:22160)* are together, nothing happens at all.

![image](https://f.cloud.github.com/assets/5054924/952794/983ce12a-03dc-11e3-9469-f82f72acbee1.png)

- **How it should work:** After using the **Rexxar's Whistle** on the location, a mob  **Spell Summon Spirit (ID: 38173)** should spawn which will spy conversation of **Bloodmaul Soothsayer** *(ID:22384)* & **Bloodmaul Taskmaster**.

They should have a conversation via whisper, and after they are done, you get the credit via **[DND]Bloodmaul Chatter Credit** *(ID:22383)*

Conversation that should happen:

*Bloodmaul Soothsayer* whispers: Have you seen those nasty creatures a day ago?
*Bloodmaul Taskmaster* whispers: Yes...we might have to send some troops to deal with them.
*Bloodmaul Soothsayer* whispers: We should warn Gruul and unleash his rage upon them!
*Bloodmaul Taskmaster* whispers: Agreed, it will be done.

And then you get quest credit and the quest is completed.

*WoWhead comment:*
**When you use the whistle, a ground target will appear. You will need to get relatively close enough to the ogres to use the whistle. You should still be outside of aggro range for those particular ones.**
____________________________________________
http://www.wowwiki.com/Quest:On_Spirit's_Wings
http://www.wowhead.com/quest=10714/on-spirits-wings
http://wotlk.openwow.com/quest=10714
http://wotlk.openwow.com/npc=22383

**Comment by Vord** [comment]
Confirmed still not working @ alagon 4/6/15

**Comment by Demlock** [comment]
So, you get teh credit now but there is still no flavor text there :S
