### ISSUE TITLE
[Item] Formula: Runed Adamantite Rod (25848)

### ISSUE THREAD

**Issue by MightyFlix** [dalaranwow/dalaran-wow#5703]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**:Vendor Rungor for the Horde doesn't restock recipe appropriately. Same as issues #3459 and #4983

**Expected behaviour**: Alliance Vendor restocks almost instantly

**Steps to reproduce the problem**:

1.  Go to Temple of Telhamat in Hellfire Peninsula, buy the formula from Vodesiin and wait some minutes to buy again
2. Try to do the same for his counterpart for the Horde
3. Never find the recipe

I really would like to understand the rationale here; if it's a question of proof for the behavior, why doesn't  the Alliance Vendor has the same restock time?

**Include proofs for this behaviour**
Easiest way is to reproduce.

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**
ID's on title

**Include Screenshots from the issue if necessary**
![Proof](https://user-images.githubusercontent.com/33992970/54387269-b00add80-4679-11e9-9922-b2ffc36645f1.jpg)

**Comment by Lothloryen** [comment]
Hello there,

Thank you for the report, it will be correct after the next maintenance.

**Comment by MightyFlix** [comment]
Wait, what? What it the correction that will be applied? Is the horde vendor getting the same restock time or is the Ally vendor getting the longer (insane) restock time?
