### ISSUE TITLE
[Quest] (13419) Preparations for War

### ISSUE THREAD

**Issue by MightyFlix** [dalaranwow/dalaran-wow#5706]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: NPC to deliver the quest is not on the gunship

**Expected behaviour**: After taking the flight to the Gunship (which btw still doesn't work 100% as mentioned on Issue  #653 ) you should be able to deliver quest, except he's not there.

**Steps to reproduce the problem**:

1. Fly to Gunship or ask Sky-Reaver Klum (31085) for a ride
2. Search for Sky-Reaver Korm Blackscar (30824)
3. Not on the ship
Quest ID: 13419
**Include Screenshots from the issue if necessary**

**Comment by alexuktc** [comment]
Phasing issue. If you are using a flying mount to get to the ship you need to dismount. NPCs on the ship should show up soon after. I have two Loremasters of Northrend who have both completed the quest chains on the Gunship.

**Comment by MightyFlix** [comment]
> Phasing issue. If you are using a flying mount to get to the ship you need to dismount. NPCs on the ship should show up soon after. I have two Loremasters of Northrend who have both completed the quest chains on the Gunship.

Got it done after a server restard, but should the flying mount make a difference? Other NPCS showed up normally except for Korm when I had the bug.

**Comment by alexuktc** [comment]
Normally the entire ship is phased for me. The difference with the flying mount is that unless it lands on the ship you are not considered on the ship.

**Comment by MightyFlix** [comment]
Is there anyway to close the issue? Still feels buggy, but I could finish the quest thanks to @alexuktc.

**Comment by MightyFlix** [comment]
Thanks @alexuktc , could hand over normally without flying mount.

**Comment by charliedaboss** [comment]
This is happening for me as well. I tried dismounting but it didn't make him appear.
