### ISSUE TITLE
Deterrence still bugged

### ISSUE THREAD

**Issue by Tritonek** [dalaranwow/dalaran-wow#5712]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: 
When hunters use deterrence while there is an auto attack or one of their abilities in mid air (before it deals dmg to the target), deterrence bugs out and every single melee ability or attack goes through it, it only deflects spells. It makes hunter really unplayable together with Entrapment bug.

**Expected behaviour**: 
No matter when you use deterrence, it always should parry melee attacks (except cheap shot, ambush, overpower and some other).

**Steps to reproduce the problem**:

1. Make deterrence parry the attacks even if there is a hunter's ability/auto attack in mid air.

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

https://wotlk-twinhead.twinstar.cz/?spell=65871

**Include Screenshots from the issue if necessary**

https://imgur.com/a/h5Zgpx2
https://imgur.com/a/2wFeMWk

**Comment by Lothloryen** [comment]
#5712
