### ISSUE TITLE
[Quest] Freedom for All Creatures

### ISSUE THREAD

**Issue by anfarwol** [dalaranwow/dalaran-wow#5719]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: The quest has a 6-minute timer in which the player is supposed to free Sprite Darters. The player is followed by the quest giver (Kindal Moonweaver) during the quest, who despawns after the objective is completed.

When the quest giver despawns after completion of the objective, it takes a few minutes for her to respawn, so she is not at her initial location before the timer runs out and the quest fails, with the player unable to turn it in in time.

**Expected behaviour**: The timer should stop after the objective is completed. 

**Steps to reproduce the problem**:

1. Accept quest.
2. Free Sprite Darters, arrive at objective location.
3. Wait for timer to end.

**Include proofs for this behaviour**

Quest page on Wowhead: https://www.wowhead.com/quest=2969/freedom-for-all-creatures
Issue discussed somewhere else: https://github.com/TrinityCore/TrinityCore/issues/17137

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

Quest: 2969
Quest giver: 7956

**Include Screenshots from the issue if necessary**

n/a

**Comment by Lothloryen** [comment]
#309
