### ISSUE TITLE
E-mail from dalaran-wow.com goes to SPAM

### ISSUE THREAD

**Issue by marceliwac** [dalaranwow/dalaran-wow#5728]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
The welcome e-mail **(Welcome to Dalaran-WoW from the address Dalaran-WoW@dalaran-wow.com** goes to SPAM.

**Expected behaviour**: Tell us what should happen instead
The e-mail should not go to SPAM

**Steps to reproduce the problem**:

1. Register on the dalaran-wow.com
2. Receive the e-mail
3. n/a

**Include proofs for this behaviour**
![Screenshot from 2019-05-21 11-30-07](https://user-images.githubusercontent.com/17514757/58089124-f91c6800-7bbb-11e9-8f5c-7c632782de06.png)
The issue persists most likely due to the lack of DKIM / SPF records, the DMARC policy or the encryption of the message itself. 

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**
n/a

**Include Screenshots from the issue if necessary**
n/a

**Comment by MalkaviaDW** [comment]
Thank you, but this bug-tracker is for in-game issues. 

Anyways, I will report it right away.

Cheers!
