### ISSUE TITLE
[Quest #12249] Ursoc, the Bear God not resetting

### ISSUE THREAD

**Issue by Cosmao** [dalaranwow/dalaran-wow#5730]
[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: 
Something is causing Tur Ragepaw to lock up, hes just standing there in tree form not resetting back to where you talk to him to start the fight. Been waiting for more than a hour and nothing has happened, roughly 8am to 9am 28/5.

**Expected behaviour**: 
Well hes supposed to reset back to where you talk to him to start the fight where you select if you want him as tank, healer or dps to help you in the fight against ursoc. 

**Steps to reproduce the problem**:
No idea how to reproduce it since hes been stuck standing there since I picked up the quest and waited for it to reset so I could start the fight myself. 

**Include proofs for this behaviour**
Guessing you could simply hop in and check yourself on algalon. Hes not budging anytime soon it seems like. 

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills** 
Quest ID is 12249
Tur Ragepaw ID is 27328

**Include Screenshots from the issue if necessary**

**Comment by Lothloryen** [comment]
Thank you,

This should be corrected already.
