### ISSUE TITLE
Gundrak final boss stuck

### ISSUE THREAD

**Issue by stubnyag** [dalaranwow/dalaran-wow#5733]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)
Gundrak Gal'Darah (final) boss stuck. Can't pull. Evades right away.

**Comment by mercred** [comment]
If u are reporting a bug please stick to the format, otherwise just make a ticket in-game.

**Comment by Lothloryen** [comment]
Hello there,

Couldn't reproduce this at all, if anyone has any feedback it would be appreciated.
