### ISSUE TITLE
Midsummer DF reward doesn't drop emblems.

### ISSUE THREAD

**Issue by nigolaj** [dalaranwow/dalaran-wow#5748]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
The [Satchel of Chilled Goods](https://wotlk-twinhead.twinstar.cz/?item=54536) rewarded for the first daily kill of Ahune doesn't drop emblems, but still makes the daily RHC reward unobtainable. Players have to choose between a chance at a pet/scythe and emblems.

**Expected behaviour**: Tell us what should happen instead
The satchel should drop 2 emblems, replacing the RHC reward.

**Steps to reproduce the problem**:

1. Kill Ahune for the first time that day
2. Get the satchel
3. Receive no emblems, RHC reward no longer obtainable

**Include proofs for this behaviour**
Emblems of Frost are listen on both the loot table above and [WoWWiki](https://wowwiki.fandom.com/wiki/Satchel_of_Chilled_Goods)

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

The ID of the satchel is **54536**.

**Comment by Lothloryen** [comment]
Thank you very much for the heads up, I thought this was fine already.

It will be corrected with the next maintenance.
