### ISSUE TITLE
Quest: Delivering the Message

### ISSUE THREAD

**Issue by Golganeth** [dalaranwow/dalaran-wow#575]
http://wotlk.openwow.com/quest=10406

**Issue:** The quest giver has to spawn the NPC you have to escort upon picking up the quest, but he doesn't. 

------

- *Protectorate Demolitionist* - http://wotlk.openwow.com/npc=20802
- *Debuff applied on the player once the NPC spawns:* http://wotlk.openwow.com/spell=35679

**Comment by MrAndersonX** [comment]
Confirmed - bugged.

**Comment by Cone182** [comment]
not bugged, the quest can be turned in at coors 70,38, there is another teleporter where an NPC spawns.

**Comment by Cone182** [comment]
yes, bugged

**Comment by Cone182** [comment]
I got it working somehow, I dont know how, but the image did appear

**Comment by jonanone** [comment]
Once the quest is accepted the demolitionist will be summoned.
Some waypoints has been fixed.
Once the escort ends and the demolitionist sabotages the conduit the quest credit is given.
The fix will be applied to the live realm soon.
