### ISSUE TITLE
Quest: Matchmaker [13147]

### ISSUE THREAD

**Issue by Sagrath** [dalaranwow/dalaran-wow#577]
http://www.wowhead.com/quest=13147 
1) After player accepts the quest, the player should be able to interact with http://www.openwow.com/?object=193424 - works
2) http://www.openwow.com/?object=193424 should have a gossip conversation to take control over a creature - works, gossip is there
3) after pressing the gossip text, a creature( http://www.openwow.com/?npc=30895 ) should spawn. - bugged, no creature is spawned
4) The player should be able to use http://www.openwow.com/?npc=30895 as a vehicle ( I tried with .npc add 30895 and it was indeed friendly however couldn't use it as a vehicle)
5) Player must go (using that creature) to http://www.openwow.com/?npc=31320 and use vehicle ability - http://www.openwow.com/?spell=58283 - on those creature. Using that ability on this creature will force creature to walk to nearest http://www.openwow.com/?npc=30921 and "kick it", each kick gives quest credit.

**Comment by AgeAgainst** [comment]
As of 5 January, 2015 - The Eye of Dominion:  http://www.openwow.com/?object=193424 is able to be accessed, but selecting <Seize control of a Lithe Stalker through the eye.> is no longer working.

Unable to do the following quests:

Quest: Generosity Abounds [13146] #578 
Quest: Stunning View [13160] #579
Quest: New Recruit questline #656

Tickets about those quests will be discarded - yet they are unable to be completed.

**Comment by Lothloryen** [comment]
Deployed time ago.
