### ISSUE TITLE
[Mechanic][Profession] Northern Cloth Scavenging remains after unlearning Tailoring

### ISSUE THREAD

**Issue by Aridam** [dalaranwow/dalaran-wow#5785]
**Current behaviour**:
My professions were BS + Tailoring, then switched to BS + Engineering. I still have NCS.

Proof: https://imgur.com/a/X4Mbrg8

It's also legit-active -- I get drops.

**Expected behaviour**:
NCS should be unlearned with Tailoring, rather than stay.

**Steps to reproduce the problem**:
1.  Get Tailoring up until you can get NCS;
2. Unlearn;
3. Still have it.

**Include proofs for this behaviour**
NCS ID: https://wowgaming.altervista.org/aowow/?spell=59390

**Comment by Golganeth** [comment]
Merge #4122
