### ISSUE TITLE
Object looting from max range.

### ISSUE THREAD

**Issue by Sagrath** [dalaranwow/dalaran-wow#58]
If one tries to loot an object that requires a cast time to be looted at their max loot range, no loot table will open, and trying to loot the object again will yield the said message, rendering it unable to be looted. 
Objects like veins, boxes and such.

**Comment by Rushor** [comment]
bc41f192bb1f2def9683a189979b85f0dcd1a87f
- interactiondistance for all objects increased from 5.0f to 5.2f

**Comment by Rushor** [comment]
note: this only improves the situation - it's not a final fix for all gos. but it will reduce the gm reports xD

**Comment by Golganeth** [comment]
Doesn't really work. 
- How to reproduce: Loot any gobject from max range.
- A clear example: http://wotlk.openwow.com/quest=12140

**Comment by chaodhib** [comment]
Hello,
@debugger123 Could you provide to us the disassembled code of wow.exe that you were talk about?
