### ISSUE TITLE
[Quest][Northrend] The Broken Front H [13228] A [13231]

### ISSUE THREAD

**Issue by Sagrath** [dalaranwow/dalaran-wow#580]
www.wowhead.com/quest=13231/the-broken-front‎
www.wowhead.com/quest=13228/the-broken-front‎
Missing 3x gossip from both Dying Berserker and Dying Soldier
wowhead Alliance npc link: http://www.wowhead.com/npc=31304
wowhead Horde npc link: http://www.wowhead.com/npc=31273

**Comment by Rushor** [comment]
http://i.imgur.com/vnxJsaR.jpg horde verrsion works fine
