### ISSUE TITLE
Unable to loot a Netherwing Egg

### ISSUE THREAD

**Issue by blacksmurf76** [dalaranwow/dalaran-wow#5807]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**:
Just started farming rep with Netherwing in Shadowmoon Valley, got first quest [The Great Netherwing Egg Hunt](https://www.wowhead.com/quest=11049/the-great-netherwing-egg-hunt) on Ledge. Found an egg (two actually), tried to loot to no success. Disabled addons, tried again, still no luck.

**Expected behaviour**:
Loot the item as long as there is enough room in player's bag(s).

**Steps to reproduce the problem**:
1. Find a [Netherwing Egg](https://www.wowhead.com/item=32506/netherwing-egg)
2. Loot/Auto loot brings the message "Looting Netherwing Egg will bind it to you"
3a. Click on Okay, nothing happens, egg is still lootable
3b. Click on Cancel, nothing happens, egg is still lootable.

**Comment by Chenocide** [comment]
![](https://i.imgur.com/FO9olp1.png)

Works fine. The eggs are quest objects, are you in a raid?

**Comment by blacksmurf76** [comment]
Was not in raid.
Am also on quest, as noted, otherwise wouldn’t be able to interact with item, no?

Sent from my iPhone

On Aug 17, 2019, at 3:58 PM, Chenocide <notifications@github.com<mailto:notifications@github.com>> wrote:


[https://camo.githubusercontent.com/98dd766b5efe78ba28740f54467bb56819d09b78/68747470733a2f2f692e696d6775722e636f6d2f464f396f6c70312e706e67]<https://camo.githubusercontent.com/98dd766b5efe78ba28740f54467bb56819d09b78/68747470733a2f2f692e696d6775722e636f6d2f464f396f6c70312e706e67>

Works fine. The eggs are quest objects, are you in a raid?

**Comment by Chenocide** [comment]
You can loot eggs all over the place since it is a repeatable quest later on. Maybe the eggs needed for the quest and the eggs needed for the repeatable are not the same. I'll try and see if I can get the quest you mentioned.

**Comment by Chenocide** [comment]
![](https://i.imgur.com/31LRb5c.jpg)

Completed it on a different character.

**Comment by blacksmurf76** [comment]
Thanks for the feedback, but this doesn’t solve my issue :)

I’ll add a video I took yesterday, knowing it would be hard to believe or reproduce.

Sent from my iPhone

On Aug 17, 2019, at 5:50 PM, Chenocide <notifications@github.com<mailto:notifications@github.com>> wrote:


[https://camo.githubusercontent.com/66765f6ebe853017cc4465d5975bc5eb08d7e905/68747470733a2f2f692e696d6775722e636f6d2f33314c526235632e6a7067]<https://camo.githubusercontent.com/66765f6ebe853017cc4465d5975bc5eb08d7e905/68747470733a2f2f692e696d6775722e636f6d2f33314c526235632e6a7067>

Completed it on a different character.

**Comment by blacksmurf76** [comment]
<https://www.icloud.com/attachment/?u=https%3A%2F%2Fcvws.icloud-content.com%2FB%2FARBHpuhXNyAzK75CbXB2-KFrDmywAbr-7M0XQMBpA9NZ_dncjhkMYnHs%2F%24%7Bf%7D%3Fo%3DAujOF12USBx71xaXA-5d3Gf3voCU61YL4Jgu84CqKOX7%26v%3D1%26x%3D3%26a%3DCAogaHKVbrsNhaV3dCJMMmrgYMfQB3eXb3KYyZCCpYrEoswSJxD33LmPyi0Y9-y049MtIgEAKggByAD_fjsneVIEaw5ssFoEDGJx7A%26e%3D1568676853%26k%3D%24%7Buk%7D%26fl%3D%26r%3D9E1D0F14-538F-48F7-B482-81AFB5926C38-1%26ckc%3Dcom.apple.largeattachment%26ckz%3D92E37A71-72CE-48AD-ADC3-C7558453029A%26p%3D58%26s%3DPMDltFsPCfHHVk5IKUurrEwNjgc&uk=AqR5cAOaFtC1718qhJal3Q&f=IMG_0917.MOV&sz=30865462>
Download Attachment
Available until Sep 16, 2019

**Comment by Chenocide** [comment]
Try abandoning the quest and take it again. If that doesn't help, then consider making a ticket. I tried to do the questline on an alt and I couldn't replicate the problem.

**Comment by blacksmurf76** [comment]
Thanks for the info.

So, in-game tickets are logged when an issue can’t be resolved/fixed otherwise?

Just asking, this is my 1st time submitting some "faulty behaviour".

Sent from my iPhone

On Aug 17, 2019, at 7:54 PM, Chenocide <notifications@github.com<mailto:notifications@github.com>> wrote:


Try abandoning the quest and take it again. If that doesn't help, then consider making a ticket. I tried to do the questline on an alt and I couldn't replicate the problem.

**Comment by Chenocide** [comment]
Well, I don't think it has to be that way but usually a bug report is only useful if you know how to replicate the problem. If you report a problem that you don't know how to replicate and the developer can't figure it out either, then it's just a dead end. Even basic pointers would be fine. In your case, it seems more helpful to have a GM help you.

**Comment by blacksmurf76** [comment]
Well, looks like I was able to interact with those eggs yesterday; could even grab two in the end.
