### ISSUE TITLE
Keg-Shaped Treasure Chest gives EoV instead of EoF

### ISSUE THREAD

**Issue by nigolaj** [dalaranwow/dalaran-wow#5818]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
The Brewfest DF reward, "Keg-Shaped Treasure Chest" drops Emblems of Valor. 
**Expected behaviour**: Tell us what should happen instead
Since it replaces the RHC reward, it should award the attune-apropriate emblems. Same problem as other seasonal RHC rewards.
**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**
The keg's ID is 54535.

**Comment by Lothloryen** [comment]
Hello there,

Thank you for the heads up, it will be corrected after the next realm restart.
