### ISSUE TITLE
Felhound Spell lock

### ISSUE THREAD

**Issue by BongoPachanga** [dalaranwow/dalaran-wow#5819]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: The warlock pet felhound autocasts Spell lock even if the auto cast on the ability is turned off. The pet just casts it whenever it wants.

**Expected behaviour**: When autocast is turned off the pet shouldnt cast Spell lock by iteslf.

**Steps to reproduce the problem**:

1. summon felhound
2. turn off autocast on spell lock
3. attack something

**Comment by ih8mondays** [comment]
I play warlock and i have never had this happen. Could you provide some proof and context.

**Comment by BongoPachanga** [comment]
https://youtu.be/O8M519FgsWY

**Comment by ih8mondays** [comment]
Try "/petautocastoff Spell Lock" just to be sure it isn't a visual bug and if that doesn't work you can try "/script PetAbandon( )" to get a fresh pet. If that still doesn't work it will be tricky to pinpoint exactly what it is that causes your problem.

**Comment by BongoPachanga** [comment]
i just asked another lock to test this for me he said he didnt have any problems. i guess it only happens to me. prob some addon causing it. who knows...

**Comment by BongoPachanga** [comment]
i used the /petautocastoff Spell Lock macro and it worked. i guess it was a visual bug.
