### ISSUE TITLE
[Quest][Northrend] The Blessing of Zim'Rhuk

### ISSUE THREAD

**Issue by babyjebas** [dalaranwow/dalaran-wow#582]
Quest cannot be turned in after gathering 10 Drakkari Offerings I went to the statue and clicked the screen opened and you the continue button doesn't do anything

**Comment by Rushor** [comment]
todo: add go attribute: huge size

**Comment by Rushor** [comment]
reward of the quest should now be much easier (interactiondistance was increased)
