### ISSUE TITLE
Glitched quests in Silithus

### ISSUE THREAD

**Issue by Sagekro2019** [dalaranwow/dalaran-wow#5826]
The quests "Abyssal Contacts" and "Dukes of the Council" in Silithus do not work properly; they require you to collect 1 and 3 Abyssal Crests, respectively (the latter also requires a Large Brilliant Shard). However, even if all necessary items have been collected, you cannot turn the quests in. While the map shows a question mark to indicate a completed quest, and the quest log shows (complete) next to the quests, when you start the dialogue with the quest-givers and choose to turn them in, the "complete" button is grayed out.

**Comment by MalkaviaDW** [comment]
Hello there, 

Thanks for the report, we are aware of this, it may happen if it took you a long while to collect all the items. Nonetheless, when this situation happens, you can safely abandon and retake the quest on the spot, and it will complete automatically after if you have all the items in your bags.

Closing this, a proper fix shall be deployed.

Cheers!
