### ISSUE TITLE
Quest: Bury Those Cockroaches!

### ISSUE THREAD

**Issue by Crispybuilt** [dalaranwow/dalaran-wow#583]
**Quest Bury Those Cockroaches** - *11608*

- **Issue present**: Only one player per every server crash/restart is able to do this quest.
The problem is that after using **Seaforium Depth Charge Bundle** *(ID:34710)* on the locations:

*99715 (Entry: 300171) - TEMP Nerub'ar Sinkhole X:2657.129883 Y:6171.350098 Z:38.954300 MapId:571] 
99714 (Entry: 300171) - TEMP Nerub'ar Sinkhole X:2716.020020 Y:6020.790039 Z:31.289900 MapId:571
99713 (Entry: 300171) - TEMP Nerub'ar Sinkhole X:2877.959961 Y:6276.009766 Z:60.944599 MapId:571
99712 (Entry: 300171) - TEMP Nerub'ar Sinkhole X:2962.159912 Y:6187.470215 Z:62.095699 MapId:571*

it will plant down a small bomb *25401* - **Seaforium Depth Charge**, which will do explosion and knock every single living NPC like 20+ yards away. The problem is that it will also knock the credit bunnies out of their original positions, which are these:

**Nerub'ar Sinkhole (South)** - *25402*
**Nerub'ar Sinkhole (West)** - *25404*
**Nerub'ar Sinkhole (North)** - *25405*
**Nerub'ar Sinkhole (East)** - *25403*

and the player will never be able to do the quest again unless there is a server crash/restart or the Game Master does .npc move on the bunnies.

**How it should work:** The explosion from spell **Seaforium Depth Charge Explosion** shouldn't knock any of those bunnies. It should just destroy them and kill them on the spot without knocking them out from their original position.. They should respawn 10 seconds after on the same spot. So more players can do this quest.

________________________

http://wotlk.openwow.com/quest=11608
http://wotlk.openwow.com/item=34710
http://wotlk.openwow.com/spell=45502

**Comment by Rushor** [comment]
* effect will no longer knock back the dummy credit creatures

**Comment by Golganeth** [comment]
Doesn't knock the triggers, but the west hole knocks Shadowstalker Luther, if placed on the edge + bomb follows the player.

Bomb should not follow the player.
Bomb shouldn't knock Shadowstalker Luther

**Comment by Rushor** [comment]
a511f387ffef07e474adccdf7041389a6f98dce9
- the bomb will now longer follow the player in combat

**Comment by Golganeth** [comment]
The bomb sometimes stays in the air floating once placed, it doesn't disappear instantly once it explodes.
