### ISSUE TITLE
No emblems of frost from ICC

### ISSUE THREAD

**Issue by Caphallorr** [dalaranwow/dalaran-wow#5837]
Current behaviour: Tell us what happens in detail (Where, When, What, Why, Who)
Friday we went ICC10 and today ICC25... I am not sure how many of the emblems did not drop, but definitely after Lady there were 0 emblem drops from bosses. Playing on horde side

Expected behaviour: Tell us what should happen instead
In ICC each boss drops emblems of frost. The quantity depends on normal/hc/10vs25
Steps to reproduce the problem:
Go to ICC.
Kill Marrowgar
(?)Possibly switch between normal and HC(?)
Don't get any emblems.

You can research this on several pages like http://wowhead.com or http://wowwiki.wikia.com or http://www.youtube.com/
Issues without proofs will be closed and tag On Hold will be added until the proof is provided.

Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills

You can research this on several pages like https://wowgaming.altervista.org/aowow/ or https://wowhead.com/

Include Screenshots from the issue if necessary

Screenshot proof: https://imgur.com/a/avROAhi (screenshot shows emblems and ID from yesterdays ICC25... killed 8/12 HC, 1/12 normal (lady)... yet got only few emblems (i believe it was 8 including quest for darnavan)

The link for the NPC:

The link at fandom (look at Lich King Patch): 

**Include Screenshots from the issue if necessary**

**Comment by Lothloryen** [comment]
Hello there,

This issue should be already resolved in Algalon, it appeared after some of the recent changes. Open a ticket and a GM will help you.

Regards.
