### ISSUE TITLE
Problem with prepaid card?

### ISSUE THREAD

**Issue by liger2312** [dalaranwow/dalaran-wow#5838]
Previously i used my paypal card to get voter points and heirloom items... now its saying there is an error? do you guys no longer accept paypal cards? whats going on?

**Comment by MalkaviaDW** [comment]
Hello, this place is for in-game issues. If you have troubles with Paymentwall you have to contact them via the help button. If you need further assistance please contact dalaran.community@gmail.com and they will try to help you out.
