### ISSUE TITLE
Item: Drakuru's Last Wish

### ISSUE THREAD

**Issue by Crispybuilt** [dalaranwow/dalaran-wow#584]
**Item Drakuru's Last Wish** - *43059*

**Issue**: The item doesn't teleport you anywhere when you use it.

**How it should work**: The item is looted from the object, Drakuru's Skull, after you finish the quest **Betrayal** and it will safely teleport you away from Voltarus, for all those who do not have flying mount. 
It should port you down to Voltarus on the road away from the building. Just add teleport bunny outside of the Voltarus and make the player to be teleported there after using the item.

___________
http://www.wowhead.com/item=43059/drakurus-last-wish#comments

**Comment by Rushor** [comment]
already fixed by tc
