### ISSUE TITLE
[Northrend - Quest] The fallen sisters in Howling Fjord

### ISSUE THREAD

**Issue by Ultrasucc** [dalaranwow/dalaran-wow#5841]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)

- Clicking on Lurielle's Pendant while targeting Chill Nymph gives "Invalid target" error

**Expected behaviour**: Tell us what should happen instead

**Steps to reproduce the problem**:

1. Target Chill Nymph
2. Use Lurielle's Pendant
3. Get error and nothing happens

My guess is that the pendant is looking for the wrong NPC ID

Quest proof:
![WoWScrnShot_122819_140240](https://user-images.githubusercontent.com/22411434/71544050-be14bb00-297a-11ea-835c-39cd4b1d1cdc.jpg)

https://www.wowhead.com/quest=11314/the-fallen-sisters
https://www.youtube.com/watch?v=Y2ZLZJwQfvU&f=

IDs:
Chill Nymph: 23678
Lurielle's Pendant: 33606

**Include Screenshots from the issue if necessary**
Put up a screenshot just in case

**Comment by MalkaviaDW** [comment]
Hello there, 

Remember you need to weaken the sisters before using the pendant, it is around 20% HP, it will show a message in the screen: Chill Nymph appears weak! then use the pendant and you will take credit for them.

Cheers!
