### ISSUE TITLE
Guild/Arena charters

### ISSUE THREAD

**Issue by Tyrandae** [dalaranwow/dalaran-wow#5858]
Steps to Reproduce:

Purchase a guild charter from a guild master NPC.

Expected Results:

Right-clicking to open a quest-styled page that contains a list of signatures needed to form a guild.

Actual Result:

Nothing. No tooltip is shown for the item, can not interact with it in any way, other than moving it around in my bags. No commands/macros work either. Same for arena charters.

Additional Information:

Available upon request.

**Comment by MalkaviaDW** [comment]
Hello, 

This may happen with certain addons or client mods, write a ticket in-game and the GMs will help you.

Cheers!

**Comment by Tyrandae** [comment]
I have already tried it with all addons disabled and im using the main client your website offers.

**Comment by Golganeth** [comment]
Confirmed. It doesn't seem to be an issue with addons or the client itself. For the time being, if you experience this issue make a ticket and we will help you.
