### ISSUE TITLE
The Champion of Anguish (Bugged Zul' Drak Quest)

### ISSUE THREAD

**Issue by Finlaypro** [dalaranwow/dalaran-wow#5860]
Hi, i wrote in game for a GM assistant but in a week nobody has answer me, sry for my english but i am spanish.
Well, this quest in Zul Drak called The Champion of Anguish can't be completed. i killed the mob Vladof the Butcher - 30022 twice with a friend in group who had the quest too and we couldn't complete it and get the credit.

**Comment by Golganeth** [comment]
Greetings @Finlaypro 
The quest works, lots of players complete it several times a day.

To make sure you get the kill credit:
- Dismiss pets, make sure you deal the first hit on the creature, as well as the killing blow.
- You (or your group) must deal the vast majority of the total damage to the creature.

Follow the instructions above and give us some feedback, it should work flawlessly.
Closing up.
