### ISSUE TITLE
Ulduar: XT-002 Deconstructor

### ISSUE THREAD

**Issue by stubnyag** [dalaranwow/dalaran-wow#5875]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)
**Current behaviour**: The Exposed Heart can not be attacked by melee! There must be a LOS bug or something!
**Expected behaviour**: The Exposed Heart should be able to be attacked by all dps! This is one of the concepts of the fight --> to nuke it when it matters the most!

**Comment by alexuktc** [comment]
Never had that issue on 2 different melee characters over 5 years on this server. You are probably too close to the boss. Move back when the heart is exposed, as the boss has a small hitbox while the heart's hitbox is huge.

**Comment by stubnyag** [comment]
It is actually very new, not 5 years old, so go check it out now. Ulduar 10

**Comment by stubnyag** [comment]
interestingly today it was working well.
