### ISSUE TITLE
Daily Quest: Thrusting Hodir's Spear

### ISSUE THREAD

**Issue by Kaara** [dalaranwow/dalaran-wow#588]
Hello,

http://www.wowhead.com/quest=13003

This quest is bugged. I used the quest item on the Wild Wyrm several times on different ones, i use the quest item but nothing happens.

**Comment by Mercular** [comment]
Still doesn't work, tried today.

**Comment by brainos1** [comment]
still bugged

**Comment by HK8919** [comment]
08/03/2015 still bugged

**Comment by Anecho** [comment]
Still.. bugged.

**Comment by Lothloryen** [comment]
Hello there,

This quest shall be working after the next update.

Thank you very much for your reports.

**Comment by Augur89** [comment]
Hi Lothloryen, the quest works now flawlessly so thank you!! I just wanted you to know that there's a little difficulty added though, as I noticed there are at most two Wild Wyrms spawned at any given time and the respawns take a very long time. When the quest was broken I remember there were easily 10+ Wild Wyrms flying around.

The quest works and is doable, there's just the minor inconvenience of having to wait a long time for a Wyrm.

Thanks again for your dedication and skills!

**Comment by jattaj7** [comment]
Haven't seen a Wyrm in 2 days their respawn seems to much longer than intended.

**Comment by Kchekrik** [comment]
I have the same problem, no wyrms.

**Comment by Taffa2** [comment]
I see the Wyrm's and can throw the spear at them.  But the quest does not as designed.  

The spear hits the worm and drags it down to the ground.  As soon as the Wyrm reaches the ground it goes back out of combat and flies back up to the sky.

Quest cannot be done at this time.

**Comment by Akkalevil** [comment]
Same as what was reported one year before : very few wyrms (to the point of simply absolutely none most of the time).
Between this quest and "hot & cold", the Sons of Hodir reputation, one of the most important due to shoulder enchants, is twice as hard to improve...
