### ISSUE TITLE
Hakkar still MCing single person in fight - Issue since 2014

### ISSUE THREAD

**Issue by postits** [dalaranwow/dalaran-wow#5884]
Current behaviour: Tell us what happens in detail (Where, When, What, Why, Who)
Hakkar mind controls even if there is only one person in the raid instance and then resets his HP to full, unlike in retail WoTLK. In retail WoTLK I never had him reset HP to full during this encounter, even having priests left unkilled (however, in this raid I killed all the priests). I've tried solo with a hunter with the pet as top threat, and I've tried solo as a ret paladin.
Expected behaviour: Tell us what should happen instead
Hakkar should not mind control and reset to 100% HP when there is only 1 person in the raid instance, or this boss never would have been soloable in retail WoTLK.
Steps to reproduce the problem:

Try to kill Hakkar solo.
Get mind controlled.
Hakkar's HP resets, smash head against wall because this is not how it worked in retail.
Include proofs for this behaviour

You can research this on several pages like http://wowhead.com or http://wowwiki.wikia.com or http://www.youtube.com/
Issues without proofs will be closed and tag On Hold will be added until the proof is provided.

Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills
https://wotlk-twinhead.twinstar.cz/?npc=14834
Raid ID 1202
You can research this on several pages like
https://wowwiki.fandom.com/wiki/Hakkar_the_Soulflayer_(tactics)

"If you are the only one fighting Hakkar he wont use his MC ability. If Bloodworms or a ghoul is active, he WILL use his MC, and you will kill it(them) before the duration of the MC is up, thus causing him to reset, and fully heal."

Include Screenshots from the issue if necessary
WoWScrnShot_081119_175816

**Comment by Lothloryen** [comment]
Thank you for the report, fixed here #5805
