### ISSUE TITLE
Achivement not recived

### ISSUE THREAD

**Issue by Leglana95** [dalaranwow/dalaran-wow#5892]
HI!

I completed Uldaur 25 with my guild but did not recive the kill on General Vezax on my Paladin Manduri.

I have a ticket open and need help asap cause I need to to continue progress in TOC 25 and ICC 25
Thanks

**Comment by Golganeth** [comment]
Greetings.

The bug tracker isn't the place to report this, if you have a ticket opened keep it up and we'll help you out as soon as possible. Keep in mind though that internet disconnects, releasing spirit or being too far away from the boss kill aren't server-side problems.

Closing
