### ISSUE TITLE
Torch Tossing Quest Bug ?

### ISSUE THREAD

**Issue by TeeGaming** [dalaranwow/dalaran-wow#5902]
Is this bug ? Torch Tossing Quest

![Annotation 2020-06-25 230604](https://user-images.githubusercontent.com/67430906/85755809-75c33380-b738-11ea-8ded-7c875dfa7fd8.png)

**Comment by MalkaviaDW** [comment]
Hello, 

Thanks for the report, the quest should have been working fine. We made few tests before the event was active. Closing this.

Cheers!
