### ISSUE TITLE
[Talent][Respec] Not spending all of talent points resets all of them upon relogging (lvl 80 respec)

### ISSUE THREAD

**Issue by maciejpk** [dalaranwow/dalaran-wow#5918]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)
If you perform a respec, for example at lvl 80 - you'll get 71 unspent talent points. If you spend <71 of talents and perform logout/force logout/alt+f4 -> log in (haven't tried crashing yet), you will have 0/0/0 spec and 71 unspent talents. The only way to save talents is to spend all of them.
While it's not a big issue, it might be annoying if you want to try respeccing.

I haven't tested it while leveling, so I don't know if when you're level 15 with 6 talent points spent, and you get to level 16 and decide to do a disconnect, you'll have 7 unspent talents and 0/0/0 tree.

Tested it on both on and off talent preview tree (along with pressing Learn and not).

**Expected behaviour**: Tell us what should happen instead
Any kind of log out should not reset already learnt talents

**Steps to reproduce the problem**:

1. Get lvl 80 to respec at trainer (tried it only with dual spec on 2nd tree)
2. You'll have 71 unspent talent points, spend <71 of them anywhere you want and learn it.
3. Relog/alt+f4 + log in/force log in
4. You'll suddenly have 71 unspent talent points

**Include proofs for this behaviour**

Not sure if this is needed, would be rather hard to find such thing in the patch notes or anything

**Include Screenshots from the issue if necessary**
![1st](https://user-images.githubusercontent.com/5055263/89160282-1ba46200-d571-11ea-8a9f-2ab21644b884.jpg)
![2nd](https://user-images.githubusercontent.com/5055263/89160292-1d6e2580-d571-11ea-928c-94488b9f763a.jpg)

You can see on the screenshot #1, that I learned almost all of the talents in mage frost spec, decided to use ice barrier. Then I relogged and suddenly all of the learned spells from talents were gone (along with talent tree).

**Comment by MalkaviaDW** [comment]
Hello there, 

We are aware of this matter, thank you for the report. A fix should be deployed as soon as possible.

Cheers!
