### ISSUE TITLE
Quest: An Apexis Relic [11058]

### ISSUE THREAD

**Issue by Sagrath** [dalaranwow/dalaran-wow#592]
www.wowhead.com/quest=11058/an-apexis-relic
You are suposed to memorize and repeat a color and sound sequence wich increases by one on each round. You win the round if you are able to repeat the whole squence, if not you lose and must try again this round or start over.
Sometimes you cant click to repeat the color, and even get hit by 7k damage is wrong color is hited

**Comment by Golganeth** [comment]
This quest works fine.
