### ISSUE TITLE
Guild Creation, charter is unclickable 

### ISSUE THREAD

**Issue by Yort23** [dalaranwow/dalaran-wow#5921]
I have been unable to create a guild. I have viewed the previous topics sbout turning off addons and if that doesn't work, open a ticket; I have opened a ticket but I have yet to hear a response, also since my ticket has been open for about 2 days. Also, I'm not sure if I need to stay on the character in order to have my ticket answered.

In addition to turning off addons i have deleted and repurchased the charter. I have even had a friend try to purchase it on their account. Neither work, essentially I am able to name the guild in the charter but it is unclickable in my backpack. Which is the only bag I have it in.

I have also tried clearing my cache folder, which offers no change

Any assistance or help on this would be much appreciated, I still have an ingame ticket open but have yet to hear a response.

P.S. I realize the server is likely shortstaffed and I don't mind waiting if thats the case but knowing approx what the waiting time is and whether or not I need to be on this toon to get the ticket answered would be helpful

**Comment by MalkaviaDW** [comment]
Hello there, 

Try downloading a new client and it should be fine, nonetheless, the waiting time with the tickets should be shorter lately, remember to edit it once you log in, so it refreshes up on the list. 

Cheers!
