### ISSUE TITLE
Druid Talents Celestial Focus, Improved Moonkin Form

### ISSUE THREAD

**Issue by thestranger064** [dalaranwow/dalaran-wow#5931]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: When you choose the talents Celestial focus and improved moonkin form, you do
not get the additonal haste applied to your character. The tooltip does not change in the character screen.

**Expected behaviour**: Celestial focus should give you an additonal total spell haste 3% of your current haste, and improved moonkin form aura should provide with additional 3% haste.

**Steps to reproduce the problem**:

1.  Be a druid and go to balance tree.
2. Click the talents and check each step if it increases haste or not.
3. Confirm that it does not.

![celestial focus](https://user-images.githubusercontent.com/25059434/96346857-53b24000-109e-11eb-822f-700ac0624bae.png)spell=16924
![celestial focus aura for haste](https://user-images.githubusercontent.com/25059434/96346863-59a82100-109e-11eb-9e97-b605a53e6d29.png)

![improved moonking form](https://user-images.githubusercontent.com/25059434/96346871-675da680-109e-11eb-80e0-fcfeff22c17f.png)spell=48396
![improved moonking form for haste](https://user-images.githubusercontent.com/25059434/96346872-69c00080-109e-11eb-8b1d-f30290203f35.png)

**Include proofs for this behaviour**

https://wotlk.evowow.com/
https://wow.gamepedia.com/Improved_Moonkin_Form
https://wowwiki.fandom.com/wiki/Improved_Moonkin_Form

https://wotlkdb.com/?spell=16924#modifies
https://wotlkdb.com/?spell=48396

**Comment by Chenocide** [comment]
Go and check if your cast speed on Wrath and Starfire changes or not, plenty of talents are not shown in your character sheet, so this is incomplete.

**Comment by thestranger064** [comment]
The hast is applied to spells if you hoover you mouse over the spell and check before , and then after the talent update.
So it should work, mostly my concern is the tooltip on the stats page.

**Comment by Chenocide** [comment]
It's almost certainly the intended function for tooltips. The 4% hit you gain isn't listed with your hit rating either but the talents should work.

**Comment by Golganeth** [comment]
This is same case as on WoW retail, where the buff, debuff and character sheet tooltips don't scale. Those tooltips don't take into account any talents/glyphs, so they will always show the default amount.

You can check the correct amount in your action bar/spellbook tooltips.

Closing.
