### ISSUE TITLE
Unable to move item that is account bounced to other character on the same account

### ISSUE THREAD

**Issue by MijoJr** [dalaranwow/dalaran-wow#5937]
Unable to move item that is account bounced to other character on the same account.

Grand Staff of Jordan <- Item

Thank you

**Comment by Chenocide** [comment]
Is the item enchanted and if so, what enchant?

**Comment by MijoJr** [comment]
Hello thank you for replying. The item was enchanted. It was flametongue
weapon from shaman. Thanks again for your help. It worked.
