### ISSUE TITLE
Instance / Game Object: Blackfathom deeps / Altar of the Deeps

### ISSUE THREAD

**Issue by Astraxa** [dalaranwow/dalaran-wow#594]
Everything works perfectly in the dungeon.
However, when the last boss is killed, there's a table behind him that can be clicked on to receive a buff - a blessing from it, and that's not the case.
I couldn't even click on it.
Please look into this.
Thank you.

**Comment by Demlock** [comment]
Confirmed.

**Comment by Tarpor** [comment]
Seems to be working.

**Comment by Rushor** [comment]
that was added long time ago https://github.com/TrinityCore/TrinityCore/blob/a56a402190c885e51038df55654875cc9e875c03/src/server/scripts/Kalimdor/BlackfathomDeeps/blackfathom_deeps.cpp#L43
