### ISSUE TITLE
Koltira Deathweaver bug, Brothers in death quest in Deathknigt starting area

### ISSUE THREAD

**Issue by Flarikje** [dalaranwow/dalaran-wow#5942]
Hi, Koltira Deathweaver is glitched under the ground beneath the scarlet hold, fighting with scarlet crusader because I keep hearing fighting sounds. She is NOT in the basement where she should be, making it impossible to complete the Brothers in death quest in the Deathknight starting area. I can target her if I click the wall next to the entrance to the scarlet hold, also sometimes being able to target the scarlet crusader. Sadly I can't pull him out because he's out of line of sight. Please help so I can finish my DK starting quests!

**Comment by MalkaviaDW** [comment]
Hello,

Closing this issue, since this should be fixed already.

Cheers.
