### ISSUE TITLE
Entry Into Karazhan (1st Key Fragment) #9831

### ISSUE THREAD

**Issue by DrFuler** [dalaranwow/dalaran-wow#5943]
[//]: # (INFORMATION ABOUT TAGS)
[//]: # (The black and yellow tag is unique. There can only be one label assigned to them - one black and one yellow)
[//]: # (Priority - ... tags are assigned by team members)
[//]: # (Your issue will be reviewed by testers and the developers will fix it in the future.)
[//]: # (Only once the issue got the label [Fixed - On Live Server] you can find the fix on your Gameserver.)
[//]: # (You can increase the relevance of your issue by adding a thumb-up emote http://i.imgur.com/RFouVVi.png)

[//]: # (***************************************************************)
[//]: # (** !!!!!!!!!!!!!DON'T DELETE THIS TEMPLATE ELSE YOUR ISSUE WILL BE CLOSED!!!!!!!!!!!! **)
[//]: # (***************************************************************)

**Current behaviour**: Tell us what happens in detail (Where, When, What, Why, Who)

- Where: **Shadow Labyrinth** (Terokkar Forest dungeon)
- When: **December 30, 2020**
- What: **Arcane Container (object #182196) can't be found**, which prevents First Fragment Guardian (npc #22890) from being summoned and consequently First Fragment Key (item #24514) from being acquired. Thus, quest Entry Into Karazhan (#9831) can't be completed.
- Why: Object #182196 seems to be missing entirely
- Who: Alyza character at **Agalon - Main Realm (PVP)**

**Expected behaviour**: **Arcane Container** (object #182196) should be present on the last chamber of Shadow Labyrinth, to the left next to the last boss (Murmur). This video showcases the expected behavior: https://www.youtube.com/watch?v=nyYcIdnw79M

**Steps to reproduce the problem**:

1. Acquire the quest (Entry Into Karazhan #9831)
2. Run through the Shadow Labyrinth dungeon
3. Try to locate Arcane Container (object #182196)

PS: I have tried this on both Heroic and Normal, and have also tried to kill last boss (Murmur) to check if the object appears afterwards. None have worked so far.

**Include proofs for this behaviour**

- All comments on https://www.wowhead.com/quest=9831/entry-into-karazhan#comments indicate that the object should be on that specific location.
- Video on https://www.youtube.com/watch?v=nyYcIdnw79M shows exactly where and how to get the object.

**Include the ID for the game objects, npcs (creatures,pets,minions), spells, items, quests, instances, zones, achievements, skills**

- Quest: #9831
- Missing object: #182196

**Include Screenshots from the issue if necessary**

Screenshot taken live from Agalon - Main Realm (PVP) server on December 30, 2020:

![WoW](https://user-images.githubusercontent.com/12341227/103357790-c8d4c500-4a92-11eb-95be-6459cc2e8895.png)

**Comment by Lothloryen** [comment]
Hello there,

Thank you for the report, it looks it got glitched with one update. It is fixed again, will be working after the next maintenance.
