### ISSUE TITLE
Quest: Forging the Keystone [13285]

### ISSUE THREAD

**Issue by Sagrath** [dalaranwow/dalaran-wow#596]
You must speak with Brann Bronzebeard ( http://old.wowhead.com/npc=31810 ) to start the event.
The NPC is not there and if you summon it with Brann's Communicator, the gossip is missing.

https://www.youtube.com/watch?v=l6ZBd9AJ7n4

**Comment by Oppie3434** [comment]
Seems to be bugged still

**Comment by jattaj7** [comment]
Can confirm, tried summoning Brann in multiple spots changed nothing.

**Comment by thestranger064** [comment]
Reopening this, if someone has done they keystone lately, the npc that is required takes a long time to respawn once someone has done it. I been waiting for more then 30m and still have not seen it after a complete event.
