### ISSUE TITLE
Cant log in help.

### ISSUE THREAD

**Issue by dropulis** [dalaranwow/dalaran-wow#5979]
"You have applied a lock to your account. You can change your locked status by calling your account lock phone nummber "
WTF is this ?

**Comment by Golganeth** [comment]
Hello @dropulis 
This is the bug tracker which only lists in-game glitches or server side issues (such as problems with quests, NPCs, mechanics...)
Send us an e-mail to 'dalaran.community@gmail.com' and we will do our best to help you out and check the reason why your account was secured and locked.

Thank you in advance for your understanding!
Closing.
