### ISSUE TITLE
NPC: Bristleback Geomancer

### ISSUE THREAD

**Issue by Astraxa** [dalaranwow/dalaran-wow#600]
These npc are located south the Barrens.

Upon bringing their hp low, they get hit by fear ( not a spell ) that makes them run away or ask help from a nearby ally to them. The problem is here: while feared, they keep casting spells even while running - in this phase, they should stop casting and then start casting again when this phase is over ( it usually takes few seconds ). They don't always cast spells while feared, but when they do, it's a bug.
Please look into this.
Thank you.

**Comment by Golganeth** [comment]
Merge with #2166
