### ISSUE TITLE
NPC: Geltharis, Xavian Betrayer/Felsworn/Hellcaller/Rogue

### ISSUE THREAD

**Issue by jillsandwich69** [dalaranwow/dalaran-wow#604]
Geltharis  id= 4619
Xavian Betrayer	id= 3754
Xavian Felsworn	id= 3755
Xavian Hellcaller	 id=3757
Xavian Rogue     id = 3752

NPC's not casting "Gift of Xavian" properly. I had pet attack, and Sperpent Sting up. When they start to cast , the bar just stagger and does not move more that a tiny bit. Notice the NPC cast bar in the picture. That is as far as it goes. I have no interrupts.  Sorry if these aren't the right IDs, I used WoWhead. I'm still learning the ropes here. 

![wowscrnshot_081513_042554](https://f.cloud.github.com/assets/5232945/967716/89a3e6d2-0584-11e3-86e0-1982e2bc91d1.jpg)

**Comment by Rushor** [comment]
this was already fixed by tc
