### ISSUE TITLE
Gyrocoptor dissapears when taking flight path from Nesingwary Base Camp to Dalaran

### ISSUE THREAD

**Issue by dv87** [dalaranwow/dalaran-wow#606]
Take the flight path from Nesingwary Base Camp, Sholazar Basin to Dalaran and you'll briefly fly on a Gyrocoptor. Soon enough, though, the gyrocoptor dissapears and you're swimming mid-air to Dalaran, instead.

**Comment by Rushor** [comment]
Cannot confirm this anymore on ptr.
