### ISSUE TITLE
Quest: Not On My Watch!

### ISSUE THREAD

**Issue by Golganeth** [dalaranwow/dalaran-wow#607]
http://wotlk.openwow.com/quest=9918

**Issue:** Once Lump reaches around 30% of his HP, he doesn't offer any gossip option to complete the quest and the NPC remains mindlessly as friendly.

-----------------

**How it should work**: Once Lump reaches around 30% of his HP, he should give up and become friendly, offering a gossip option to complete the quest, and after a while he just disappears. When he respawns, he has to be asleep and hostile to players (initial status).

- *Lump* - http://wotlk.openwow.com/npc=18351

**Comment by jonanone** [comment]
This quest is working ok at this moment.
