### ISSUE TITLE
Quest: The Big Bone Worm [10930]

### ISSUE THREAD

**Issue by Sagrath** [dalaranwow/dalaran-wow#611]
Quest: http://www.wowhead.com/quest=10930
Fumper (Drum): http://www.wowhead.com/item=31825
Sand Gnome: http://www.wowhead.com/npc=22483
Hai'shulud: http://www.wowhead.com/npc=22038
Mature Bone Sifter: http://www.wowhead.com/npc=22482
Problem:
Using Fumper is not spawning anything.

How it should work:
1. Take quest and find a Clefthoof
2. Kill the Clefthoof and use the drum near the corpse;
3. By using the drum near the corpse, you should spawn either 3 Sand Gnomes, 2 Mature Bone Sifter  or the Hai'shulud himself.
4. If any of first 2 spawn, kill them, kill more clefthoofs and try again. If "boss" spawns, kill him, loot his organs and turn in the quest.

**Comment by ashido96** [comment]
Using the drum next to a clefthoof corpse despawns the corpse but spawns nothing else. Must have become bugged during the recent update.

**Comment by muffygb** [comment]
Quest still broken. Using the fumper near a clefthoof corpse just removes corpse and nothing else. Tried this on numerous clefthoofs with no joy.

**Comment by Demlock** [comment]
Confirmed

**Comment by Finlaypro** [comment]
11/10/2015: Still not working.

You use the drump in Clefthoof corpse and nothing happens. Not appear mobs and corpse dissapear.

**Comment by Lothloryen** [comment]
Hello there,

Thank you, it has been corrected and deployed already.

**Comment by Zibathy** [comment]
Seems to be broken again on Kirin Tor. Some screenshots:
![wowscrnshot_123015_002717](https://cloud.githubusercontent.com/assets/7729864/12047146/965a254a-ae8c-11e5-898e-8b6c21a329f3.jpg)
![wowscrnshot_123015_002721](https://cloud.githubusercontent.com/assets/7729864/12047149/965dac74-ae8c-11e5-927b-319a74022386.jpg)
![wowscrnshot_123015_002724](https://cloud.githubusercontent.com/assets/7729864/12047148/965d7fd8-ae8c-11e5-806c-e78482a6fd1e.jpg)
![wowscrnshot_123015_002731](https://cloud.githubusercontent.com/assets/7729864/12047151/965f2734-ae8c-11e5-849a-ceb42ed4ee0d.jpg)
![wowscrnshot_123015_002840](https://cloud.githubusercontent.com/assets/7729864/12047147/965d530a-ae8c-11e5-82bf-9a785ad75204.jpg)
![wowscrnshot_123015_002845](https://cloud.githubusercontent.com/assets/7729864/12047150/965ec8c0-ae8c-11e5-8195-bb38bd059cc7.jpg)
![wowscrnshot_123015_002854](https://cloud.githubusercontent.com/assets/7729864/12047152/96ac6d1e-ae8c-11e5-9890-95830fcf8e11.jpg)

**Comment by Daveonx** [comment]
Borken again, nothing happens after using the drum near the corpse of a Clefthoof

**Comment by jonanone** [comment]
The quest has been fixed again and the drum will summon creatures near the dead clefthood once more. The fix will be applied to the live realm soon.
