### ISSUE TITLE
[Achievement] Flu Shot Shortage (10 / 25 player)

### ISSUE THREAD

**Issue by Golganeth** [dalaranwow/dalaran-wow#615]
**Issue:** The achievement will pop regardless if you met or have not met the conditions to obtain it. Currently it pops every time you kill the boss.

**How it should work:** You should only obtain that achievement if you meet the criteria for it which is: Defeat Festergut while none of the players in your raid group ever had 3 stacks of Inoculated.

---
- _Flu Shot Shortage (10 player)_ - http://wotlk.openwow.com/achievement=4577
- _Flu Shot Shortage (25 player)_ - http://wotlk.openwow.com/achievement=4615
- _Festergut (10 player)_ - http://wotlk.openwow.com/npc=36626
- _Festergut (25 player)_ - http://wotlk.openwow.com/npc=37505

**Comment by Rushor** [comment]
Yes that's already fixed on PTR.

* commit: d49c108509bcfe2ac706ef49348108d52eb74d8f

It can also be tested by player one another ICC PTR session is available. Thanks. (see forum for news on this.)
