### ISSUE TITLE
Quest / Item: The Only Cure is More Green Glow / Heavy Leaden Collection Phial

### ISSUE THREAD

**Issue by Crispybuilt** [dalaranwow/dalaran-wow#616]
**Quest:** The Only Cure is More Green Glow - *2962*
**Item:** Heavy Leaden Collection Phial - *9364*

**Minor issue which makes the quest way to easy to do it**

____________
________

- **Issue Present**: Item **Heavy Leaden Collection Phial** is usable anywhere in the world on any creature or non-creature or not even a target. You use the item and you get the credit regardlessly the quest objective says it has to be used on **Corrosive Lurker** 

-  **How it should work:** Players should only be awarded with the quest item, **High Potency Radioactive Fallout**  *(ID:9365)* ,upon using the **Heavy Leaden Collection Phial** on the **Corrosive Lurker** *(ID:6219)*

- **Possible Fix**: Set up a condition where the player cannot use the item unless he is targeting a dead **Corrosive Lurker** (which is located in Gnomeregan)

______________

http://www.wowhead.com/quest=2962/the-only-cure-is-more-green-glow
http://www.wowhead.com/item=9364
http://www.wowhead.com/item=9365#created-by-spell

____
___

**WoWhead comment**

*Quest chain 1 (8 Parts) : (this one of course)*
*Horde: The Hand of Gul'dan*
*Alliance: The Hand of Gul'dan*
*Enraged Spirits of Fire and Earth*
*Enraged Spirits of Water*
*Enraged Spirits of Air*
*Oronok Torn-heart*
*I Was A Lot Of Things...*
*A Lesson Learned*
*The Cipher of Damnation - Truth and History*

*Then as mentioned before there are the 3 quest in any order but MUST be completed in order to proceed to the next chain*

*These are the Fragment of Damnation Quest Series (3 Parts Totalling 16 Quest + 1 Final but not end of Chain = 17 Quest in all):*
*(Part 1)*
*Grom'tor, Son of Oronok*
*The Cipher of Damnation - Grom'tor's Charge*
*The Cipher of Damnation - The First Fragment Recovered*
*(Part 2)*
*Ar'tor, Son of Oronok*
*Demonic Crystal Prisons*
**The NPC ghost will appear - The chain continues:**
*Lohn'goron, Bow of the Torn-heart*
*The Cipher of Damnation - Ar'tor's Charge*
*The Cipher of Damnation - The Second Fragment Recovered*
*(Part 3)*
*Borak, Son of Oronok*
*Of Thistleheads and Eggs...*
*The Bundle of Bloodthistle*
*To Catch A Thistlehead*
*The Shadowmoon Shuffle*
*What Illidan Wants, Illidan Gets...*
*The Cipher of Damnation - Borak's Charge*
*The Cipher of Damnation - The Third Fragment Recovered*

*Now mind you "MUST" complete the above 3 Parts & also turn them into Oronok before carrying forward.*

*1 Quest*
*The Cipher of Damnation*

**Comment by jonanone** [comment]
Quest items for both quests have been adjusted to be used on the intended creatures. These fixes will be applied to the live realm soon.

**Comment by Rushor** [comment]
There are some more issues with that quest see https://github.com/TrinityCore/TrinityCore/issues/1723

**Comment by Rushor** [comment]
DB/Script: The Only Cure is More Green Glow - Update conditions and procchance

* updates https://github.com/dalaranwow/dalaran-wow/issues/616
* commit: 895c2a63a36d8347510a00cd917203b4d57860f1
* commit: 002527dc1e758a6b059eaaf9b835663d39daba1e

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
