### ISSUE TITLE
[Quest][Outland] The Cipher of Damnation - Ar'tor's Charge / NPC: Veneratus the Many

### ISSUE THREAD

**Issue by Revennaras** [dalaranwow/dalaran-wow#618]
**Quest:** The Cipher of Damnation - Ar'tor's Charge - _10540_
**NPC:** Veneratus the Many - _20427_
- **Issue present:** When player accepts this quest, an NPC, **Veneratus the Many**, in the Shadowmoon Valley (somewhere in the **Ilidari Point**) should force spawn after 5 minutes as a hostile mob. Here, it doesn't which makes the quest uncompletable and undoable because you have to kill that NPC since it drops a quest item to complete the quest.
- **How it should work:** If a player takes the quest, **The Cipher of Damnation - Ar'tor's Charge** from a NPC **Spirit of Ar'tor** _(ID:21318)_, the NPC Veneratus the Many - _20427_ should force spawn after 5 minutes in the Shadowmoon Valley - Ilidari Point and be hostile to players.
- However, if the player abandons the quest, cancel the event/timer and do not spawn the creature.

---

_I tried spawning creature in-game on a certain location but it appears to be friendly and unattackable_

**Short undetailed video of how it should work:** http://www.youtube.com/watch?v=w9lp9WtO7j0

---

![image](https://f.cloud.github.com/assets/5054924/978939/4f5b4d08-06ce-11e3-8403-2c9c981d010f.png)
![image](https://f.cloud.github.com/assets/5054924/978967/e4d89f56-06cf-11e3-949a-88ead624c9ab.png)

---

http://www.wowhead.com/quest=10540
http://www.wowhead.com/npc=20427#comments
http://www.wowhead.com/item=30453

**Comment by jonanone** [comment]
This quest has been fixed a while ago.

**Comment by TeridanDW** [comment]
Hm, this quest doesn't work at all on ptr. Issues that i saw:
 - creature http://www.wowhead.com/npc=20427/veneratus-the-many doesn't spawn at all
 - on quest accept player doesn't get the debuff and the "Spirit Hunter" (check video below)
 - keep in mind:

> Creatures attacked or damaged by the Spirit Hunter will not yield loot or experience.

Proof:
https://www.youtube.com/watch?v=XX_BN6eQExk

**Comment by Lothloryen** [comment]
@TeridanDW Could you please check this now on PTR?

Thank you.
