### ISSUE TITLE
Quest: Slaves to Saronite -  A / H - Daily

### ISSUE THREAD

**Issue by Crispybuilt** [dalaranwow/dalaran-wow#619]
**Quest** - Slaves to Saronite - *13300* (Alliance Version - Daily)
**Quest** - Slaves to Saronite - *13302* (Horde Version - Daily)
**NPC** - Saronite Mine Slave - *31397*

- **Issue present:** Players are not getting the credit once they free (they accept the gossip from them) **Saronite Mine Slave** *(ID:31397)*. Also, some of them have a chance to become a hostile and not give the credit to a player (10% chance)

- **How it should work:** After you talk with a **Saronite Mine Slave** *(ID:31397)* and click on a gossip option, *Go on, you're free! Get out of here!*, the slaves will either turn back on you (and yell some of their quotes) or they will run out of the cave free and you get the credit. Also, keep in mind that you have to give the credit only for those who do not turn back on you as hostile.

*On the side note, they do have currently only quotes implemented when they are about to turn back on and attack you, but the part of getting hostile does not work*

**Video of how it should work:** http://www.youtube.com/watch?v=gBnh3SQNQdw
__________________

![image](https://f.cloud.github.com/assets/5054924/978837/22cb54fc-06cb-11e3-986c-cfa6973be31a.png)

__________

http://www.wowhead.com/quest=13300/slaves-to-saronite
http://www.wowhead.com/quest=13302

**Comment by Sagrath** [comment]
It is working
