### ISSUE TITLE
Skills Death Wish/Enrage

### ISSUE THREAD

**Issue by HeadOwns** [dalaranwow/dalaran-wow#624]
hey there, seems like u guys fixed Enrage 5/5 stacking with Death Wish, but u forgot to fix Enrage 1/5 stacking with Death Wish, if i have Enrage on 1/5 on the talents, it doesnt stack with Death Wish.

**Comment by Rushor** [comment]
https://github.com/TrinityCore/TrinityCore/issues/14035

they should not stack at all - that was fixed back in 2014
