### ISSUE TITLE
Quest: The Cipher of Damnation - Last Quest in Chain

### ISSUE THREAD

**Issue by Crispybuilt** [dalaranwow/dalaran-wow#625]
**Quest** The Cipher of Damnation - *10588*
**NPC** Cyrukh the Firelord - *21181*

- **Issue present:** When using the quest item, **The Cipher of Damnation** *(ID:30657)*, on the specific location, and when the item finishes his cast, **Cyrukh the Firelord** *(ID:21181)* is spawned but he appears friendly and not attackable to anyone. He is supposed to be attackable and have the following skills: *Fel Flamestrike*, *Knock Away*, *Trample*

**Fel Flamestrike** - *39429*
**Knock Away** - *18945*
**Trample** - *39425*

- **How it should work:** There is entire roleplay event behind this before accessing the creature but as for now a temporary solution should work. 
When the creature **Cyrukh the Firelord** is spawned, he has to be and become hostile and attackable to players. 

____________

- **Reward Issue**:
Players are not getting to chose any rewards from a quest and they should be able to choose between 6 of the following items, and they are also not getting rewarded by default with an amulet:
They do also not recieve gold from a reward: You receive 24 Gold 60 Silver

**Amulet of the Torn-heart** - rewarded by default when turning in the quest

**Borak's Reminder** - *31073*-  one of the options to pick up.
**Grom'tor's Charge** - *31071* - one of the options to pick up.
**Lohn'goron, Bow of the Torn-heart** - *31072*-  one of the options to pick up.
**Oronok's Ancient Scepter** - *31036* - one of the options to pick up.
**Torn-heart Axe of Battle** - *31062* - one of the options to pick up.
**Staff of the Redeemer** -  *31038* - one of the options to pick up.

**This is how it looks before the fix:**

![image](https://f.cloud.github.com/assets/5054924/979070/3d2c7dce-06d7-11e3-91bf-362d7b70da93.png)

**And this is how it has to look after the fix (don't forget to include the 20 gold reward issue in that also)**

![image](https://f.cloud.github.com/assets/5054924/979072/4bdfe6b2-06d7-11e3-9067-097e4eed6326.png)

____________

- **Roleplay Issue**: Entire roleplay event for this quest is missing which has to be implemented. These are the comments from WoWhead how it should look like:

*When the player finishes the summoning:*
- A flaming vortex takes shape.

*Cyrukh the Firelord appears.*
- Cyrukh the Firelord: You will suffer eternally!

*Oronok Torn-heart and his two still-living sons comes flying on wyverns.*

- Oronok Torn-heart: You do not fight alone, [PLAYER NAME]! Together, we will banish this spawn of hellfire!

*Oronok and his two sons land a bit behind Gul'dan.*
- Oronok Torn-heart: We will fight when you are ready.

*When Oronok and his sons are running to face Cyrukh:*
- Oronok Torn-heart: We will set the elements free of your grasp by force!
Cyrukh the Firelord: Little creature made of flesh, your wish is granted! Death comes for you!

*When Cyrukh is defeated:*
- Oronok Torn-heart: What say the elements, Torlok? I only hear silence.
-Earthmender Torlok: I hear what you hear, brother. Look behind you...

*Four elementals, each representing an element, appears.*
- Oronok Torn-heart: They are redeemed! Then we have won?
- Redeemed Spirit of Earth: It is now as it should be, shaman. You have done well.
- Redeemed Spirit of Fire: Yes... Well enough for the elements that are here, but the cipher is known to another... The spirits of fire are in turmoil... If this force is not stopped, the world where these mortals came from will cease.
- Redeemed Spirit of Earth: Farewell, mortals... The earthmender knows what fire feels...

*The elementals disappear.*
- Oronok Torn-heart: We leave, Torlok. I have only one request...
- The Torn-heart men give their weapons to Earthmender Torlok.
- Oronok Torn-heart: Give these to the heroes that made this possible.

**A video of how it should work with event** *(couldn't find any better)*: http://www.youtube.com/watch?v=ydOLnP6kGG8

____________

http://wotlk.openwow.com/npc=21181
http://www.wowwiki.com/Quest:The_Cipher_of_Damnation
http://www.wowhead.com/npc=21181#abilities
http://www.wowhead.com/item=30657
http://www.wowhead.com/quest=10588/the-cipher-of-damnation#comments

**Comment by ashido96** [comment]
Currently the roleplay continually loops - everything seems to be said correctly, Cyrukh the Firelord just remains untargetable as he, gul'dan, and all the followers continuously repeat the same dialogue

**Comment by DrFuler** [comment]
05/01/2016: Still not working.

The fire giant is spawned, but can't be targeted.

**Comment by Rushor** [comment]
@DrFuler you need to talk to the guys in the background. click on the gossipoption and the event will start. This behaviour is blizzlike.

The reward items are still missing https://github.com/TrinityCore/TrinityCore/blob/a56a402190c885e51038df55654875cc9e875c03/sql/old/6.x/world/01_2015_03_21/2015_07_12_38_world_2015_06_13_01.sql

**Comment by Rushor** [comment]
rewarditemids and questevent are already aissigned, so no issues left here - closing
