### ISSUE TITLE
Quest:  The Captive Prospectors

### ISSUE THREAD

**Issue by Golganeth** [dalaranwow/dalaran-wow#632]
http://wotlk.openwow.com/quest=12180

**Issue:** Sometimes, players do not get credit after freeing the NPCs. On top of that, **Prospector Varana's cage** will sometimes remain opened for quite a long time.

**How it should work:** Players should always get credit after freeing the NPCs and the cages should respawn as closed after a short period of time.

-----------------------

- *Prospector Gann* - http://wotlk.openwow.com/npc=27113
- *Prospector Torgan* - http://wotlk.openwow.com/npc=27114
- *Prospector Varana* - http://wotlk.openwow.com/npc=27115

**Comment by Lothloryen** [comment]
It was corrected already.
