### ISSUE TITLE
[Quest] Free From the Hold

### ISSUE THREAD

**Issue by Astraxa** [dalaranwow/dalaran-wow#635]
This quest is in the Barrens.
We have to escort a NPC. However, while the NPC is walking, it sometimes go through a tree or the wall. Please recheck his walking course.
Please look into this quest.
Thank you.

**Comment by Rushor** [comment]
general issue with creatures. it's not related to this quest. moreover the mmaps were changed and improved in 2015. That issue should be fixed already
