### ISSUE TITLE
NPC: Winterskorn Berserker / Rune-Seer / Elder

### ISSUE THREAD

**Issue by Golganeth** [dalaranwow/dalaran-wow#638]
**Issue:** The HP bar from these NPCs are always showing them as "Dead", and even though you can kill them, you can not loot them and you are able to right click them to attack their corpse once they die (you won't deal any damage to it though).

- *Winterskorn Berserker* - http://wotlk.openwow.com/npc=23666

**Comment by jonanone** [comment]
These was fixed a while ago.
