### ISSUE TITLE
Leader of the Pack/Rampage

### ISSUE THREAD

**Issue by HeadOwns** [dalaranwow/dalaran-wow#647]
hello there,as far as I know, Leader of the Pack and Rampage shouldn't stack, we must get 5% crit only, from one of them, either from Rampage or LotP, but today I got 10%, 5% of each one.

**Comment by Golganeth** [comment]
Still broken. 
1) Have a first druid with Leader of the Pack up
2) Have a second warrior respeccing into Rampage
3) The warrior who respecs has both buffs until the druid leaves shapeshift

**Comment by robinsch** [comment]
On PTR

**Comment by Golganeth** [comment]
The talent breaks completely until next relog if:
1) Have two warriors on the same group, X = with rampage, Y = without rampage
2) Have warrior Y respec into rampage (only 1 Rampage is active, good)
3) Have warrior X respec out of rampage (Rampage is gone forever until next relog, doesn't matter if you leave group or respec back and forth).

**Comment by Golganeth** [comment]
Rampage breaks even if the warrior is alone and respecs into Rampage. Gotta relog to get the effect

**Comment by robinsch** [comment]
On PTR.

**Comment by Golganeth** [comment]
Respec into Rampage with a feral in your group -> Rampage + LotP
![image](https://cloud.githubusercontent.com/assets/5057942/16344698/1f853a34-3a3e-11e6-8284-3c7b0bfac291.png)

**Comment by plznoz** [comment]
Tested and it's fixed.
