### ISSUE TITLE
Daily Quest: Riding the Red Rocket 12432

### ISSUE THREAD

**Issue by Sagrath** [dalaranwow/dalaran-wow#655]
You need to go into goblin ship and take "Element 115" from the ship after you take it you go to "Rocket Propelled Warhead"
and right click on it it takes from you the "Element 115" and Rocket Propelled Warhead should arrive to boat and explode , after it explode you finish the quest.
The bug is that when you arrive to Rocket Propelled Warhead you cant mount it with Element 115 nor without it ofc

http://www.wowhead.com/item=37664
http://www.wowhead.com/npc=27708
http://www.wowhead.com/quest=12432
http://www.wowhead.com/npc=27593

**Comment by Cone182** [comment]
still bugged, confrmed

**Comment by KrepsyEpilepsy** [comment]
as of 9.02.2016 it is still bugged, cannot mount the rocket with or without the element.

**Comment by Crispybuilt** [comment]
It appears you can mount the rocket now, BUT it is so uncontrolable that you can fly with it anywhere you want. Also you do not get the quest credit if you hit the boat.

**Comment by jonanone** [comment]
The rocket now explodes when hitting the opposite factions boat and gives credit for it. The fix will be applied to live realm soon.

**Comment by KrepsyEpilepsy** [comment]
Awesome. Any ETA?

-----Original Message-----

**Comment by Rushor** [comment]
soon after golgy tested it :>

**Comment by KrepsyEpilepsy** [comment]
Allrightyyy can.t wait for it! :)

-----Original Message-----

**Comment by Golganeth** [comment]
Few issues for both versions of the quest:

* You can control the rocket very easily. It should turn left or right slower. You can take a zigzag course inbetween the icebergs.
* If you hit icebergs or anything in the water, the rocket doesn't explode. 
You can climb the icebergs and give the rocket extra height, in some cases making you unable to destroy the ships as you'll be too high in the air.

The rest works great.
Reference: https://www.youtube.com/watch?v=lx4RDBHBt8U&t=43s

**Comment by Zibathy** [comment]
This quest is broken and I can't complete it. It just doesn't explode on impact at all on Kirin Tor from any angle. Last screenshot is me enjoying the unlimited mobility/flying. Weehaw!

![wowscrnshot_112116_140230](https://cloud.githubusercontent.com/assets/7729864/20498692/be390a40-aff3-11e6-9ddc-a2f539b3e404.jpg)
![wowscrnshot_112116_140437](https://cloud.githubusercontent.com/assets/7729864/20498690/be35ee00-aff3-11e6-9eb5-6634c6a08226.jpg)
![wowscrnshot_112116_140440](https://cloud.githubusercontent.com/assets/7729864/20498689/be3600fc-aff3-11e6-9f02-6f26494008d1.jpg)
![wowscrnshot_112116_140450](https://cloud.githubusercontent.com/assets/7729864/20498691/be3618f8-aff3-11e6-84d1-501fe2d0e1a7.jpg)
![wowscrnshot_112116_140457](https://cloud.githubusercontent.com/assets/7729864/20498688/be3521a0-aff3-11e6-8c53-6e3143f0a1c4.jpg)
![wowscrnshot_112116_140518](https://cloud.githubusercontent.com/assets/7729864/20498693/be39ef0a-aff3-11e6-9e1e-5089348b7468.jpg)
