### ISSUE TITLE
Quest: New Recruit questline

### ISSUE THREAD

**Issue by Golganeth** [dalaranwow/dalaran-wow#656]
http://wotlk.openwow.com/quest=13143

**Issue**: Once you subjugate a Lithe Stalker, it becomes friendly but he does not follow you around, making the quest impossible to complete.

----------------------

**How it should work**: Players should only be able to subjugate a Lithe Stalker when he reaches around 30% of his HP and the following emote message appears: *"The Lithe Stalker is weakened by the assault"*. Once you use the provided item, he has to become friendly and follow you around.

The place where you need to bring him is to the east of the quest giver, where you will find a lone Lumbering Atrocity. When you get to about where the mob is, the Lithe Stalker will just run off on its own and the quest has to get completed.

-----------------------
------------------

- ***Sigil of the Ebon Blade*** - http://wotlk.openwow.com/item=43315
- ***Lithe Stalker*** - http://wotlk.openwow.com/npc=30894
- ***Lithe Stalker (once subjugated)*** - http://wotlk.openwow.com/npc=30895
- ***Geist Return Bunny (has to be added)***  - http://wotlk.openwow.com/npc=31049

**Comment by mihailovici** [comment]
Ok somebody please will ever fix this quest line?Because is easy to fix, I mean I saw you fixed other more diffcult quest mechanisms..cmon guys I really ask you kindly to fix this chain quest.Thank you very much.

**Comment by Lothloryen** [comment]
Everything mentioned here working since time ago.

**Comment by Bloodhawk92** [comment]
I don't get the emote saying the Lithe Stalker is weakened and the quest item does not work.

**Comment by tenebray** [comment]
The quest item is saying it cant be equipped im not sure if its ment to be equipped or if i cant equip it because im a druid but it make me unable to complete the quest

**Comment by humapal** [comment]
The quest item, ebon sigil,  does not work in combat

**Comment by Rushor** [comment]
i think charming those creatures should only work if you are aot-of-combat

**Comment by Rushor** [comment]
Charming the creature in Combat with the questitems works on PTR

![GitHub Logo](http://i.imgur.com/ypVvOd9.jpg)
![GitHub Logo](http://i.imgur.com/ypVvOd9.jpg)

**Comment by humapal** [comment]
![newrecruit](https://cloud.githubusercontent.com/assets/26784243/24583068/8ae2b9ca-1704-11e7-9952-7b1931a4b92b.jpg)

**Comment by humapal** [comment]
It doesn't work.   I have tried it in combat, I have let someone else attack it and it wont work.  I have done it in group and out of group and it doesn't work. I worked with someone who completed this task 3 times before and we couldn't get it to work.

**Comment by Edzero** [comment]
As it is working on PTR it will be fixed in a future merge.

**Comment by DontBeSadbro** [comment]
The quest simply does not work. I do not get the message that I should get when the mob is on 1/3 of its HP, clicking the icon from the tracked quests tells me to equip the item when actually trying to equip the item says the item cannot be equiped. I am guessing the quest gives the user the wrong item, since the icon is not of a sword. 
![image](https://user-images.githubusercontent.com/16519389/28610812-f91405da-71e9-11e7-811a-2f8c59019f18.png)
![image](https://user-images.githubusercontent.com/16519389/28610825-026f60f2-71ea-11e7-8182-56f4d6c10aef.png)

**Comment by Rushor** [comment]
> As it is working on PTR it will be fixed in a future merge.
