### ISSUE TITLE
Quest: Just Following Orders 12540

### ISSUE THREAD

**Issue by Sagrath** [dalaranwow/dalaran-wow#660]
http://www.wowhead.com/quest=12540
Event missing as Ravenous Mangal Crocolisk does not appear whit whichs dead the player should get quest credit
http://www.wowhead.com/npc=28325/ravenous-mangal-crocolisk
thoo the quest is hotfixed earlyer as the croc is spawned

**Comment by Golganeth** [comment]
Works fine.
