### ISSUE TITLE
Instance: Gnomeregan

### ISSUE THREAD

**Issue by highness** [dalaranwow/dalaran-wow#662]
Here goes more or less comprehensive report on what's going on in Gnomeregan currently.

Let's look at related quests first:

http://www.wowwiki.com/Quest:Tinkmaster_Overspark - works fine.
http://www.wowwiki.com/Quest:Save_Techbot%27s_Brain! - works fine, though:

http://www.wowwiki.com/Techbot, http://www.wowhead.com/npc=6231
It says nothing and uses none of it's abilities (which are explained in related wowwiki article).

http://www.wowwiki.com/Quest:The_Day_After - works fine.
http://www.wowwiki.com/Quest:Gnogaine and http://www.wowwiki.com/Quest:The_Only_Cure_is_More_Green_Glow - the last one was reported here (https://github.com/dalaranwow/dalaran-wow/issues/616), the bug also persists for the first quest. You can use quest items for both quests anywhere and still get credit.

http://www.wowwiki.com/Quest:Castpipe%27s_Task - not tested, but presumably works fine, since it's a simple 'go and talk' quest, also the next one in chain should be available without this prerequisite anyway (and it is available indeed).
http://www.wowwiki.com/Quest:Data_Rescue - works fine except that white punch cards continue to drop even when you have yellow and so on. Also, card swap occurs right after you interact with the respective terminals, not when the dialogue option is selected (this option currently does nothing).

http://www.wowwiki.com/Blastmaster_Emi_Shortfuse 's gauntlet event - works fine.

http://www.wowwiki.com/Quest:Klockmort%27s_Essentials - same as Castpipe's Task.
http://www.wowwiki.com/Quest:Essential_Artificials - works fine.

http://www.wowwiki.com/Quest:Gyrodrillmatic_Excavationators - works fine.

http://www.wowwiki.com/Quest:The_Sparklematic_5200! - works fine, though sometimes looting the box (http://www.wowhead.com/item=9363) which is provided as reward yields nothing (that is, box is empty). 

[img]http://i40.tinypic.com/2qavloh.png[/img]

Also, the drop chance of Grime-Encrusted Objects (http://www.wowhead.com/item=9308) and it conditions must be looked into, got only 3 in full solo run, all of them while having this quest, meanwhile wowhead states 50% chance or so.
http://www.wowwiki.com/Quest:More_Sparklematic_Action - same as previous.

http://www.wowwiki.com/Quest:A_Fine_Mess - was reported here (https://github.com/dalaranwow/dalaran-wow/issues/353), not working at all.

http://www.wowwiki.com/Quest:Grime-Encrusted_Ring - never dropped for me, but might be just my luck.
http://www.wowwiki.com/Quest:Return_of_the_Ring_%28Alliance%29 + http://www.wowwiki.com/Quest:Gnome_Improvement \ http://www.wowwiki.com/Quest:Return_of_the_Ring_%28Horde%29 + http://www.wowwiki.com/Quest:Nogg%27s_Ring_Redo - see above.

http://www.wowwiki.com/Quest:The_Grand_Betrayal - works fine, though Mekkatorque's behaviour is rather erratical, I'll explain it later.
______________________

Now, about all the issues with the NPCs in the instance, both friendly and hostile: 

Troggs: (ambushers, looters, reavers, invaders, Grubbis and his pet basilisk Chomper) working as intended.

Slimes:

Corrosive lurker (http://www.wowhead.com/npc=6219) - Corrosive Ooze buff (http://www.wowhead.com/spell=9460) which should give a chance to apply Corrosive Ooze debuff on target (http://www.wowhead.com/spell=9459) is missing.

Irradiated slime (http://www.wowhead.com/npc=6218) - both Radiation Cloud buff on it (http://www.wowhead.com/spell=10341) and Toxic Nova abilities (http://www.wowhead.com/spell=81039) are missing.

Irradiated horror (http://www.wowhead.com/npc=6220) - Poison ability (http://www.wowhead.com/spell=744) is missing.

Viscious Fallout (http://www.wowhead.com/npc=7079) - Toxic Volley ability (http://www.wowhead.com/spell=21687) is missing.

Robots:

Mechanized Guardian (http://www.wowhead.com/npc=6234) - Electrified Net ability (http://www.wowhead.com/spell=11820) is missing.

Mechanized Sentry (http://www.wowhead.com/npc=6233) - works fine.

Mechano-Flamewalker (http://www.wowhead.com/npc=6226) - missing both Fire Nova (http://www.wowhead.com/spell=11970) and Flame Spray (http://www.wowhead.com/spell=10733) abilities.

Mechano-Frostwalker (http://www.wowhead.com/npc=6227) - missing both Hail Storm (http://www.wowhead.com/spell=10734) and Ice Blast (http://www.wowhead.com/spell=11264) abilities.

Mechano-Tank (http://www.wowhead.com/npc=6225) - misses it's Machine Gun (http://www.wowhead.com/spell=10346) ability.

Peacekeeper Security Suit (http://www.wowhead.com/npc=6230) - missing both Net (http://www.wowhead.com/spell=6533) and Pacify (http://www.wowhead.com/spell=10730) abilities.

Mobile Alert System (http://www.wowhead.com/npc=7849) - script is missing completely, they are just meleeing. They should shout "Warning! Warning! Intruder alert!" 3 times, after that they should start summoning adds that have no loot. Also they should use Flare (http://www.wowhead.com/spell=94528) to reveal stealthed players.

Alarm-a-bomb 2600 (http://www.wowhead.com/npc=7897) - should be spawned only on A Fine Mess quest, multiple mobs wandering the hall instead, probably related to quest being broken.

Arcane Nullifier X-21 (http://www.wowhead.com/npc=6232) - misses it's Reflection Field ability (http://www.wowhead.com/spell=10831), Mass Nulify (http://www.wowhead.com/spell=10832) too probably, though needs further testing.

Electrocutioner 6000 (http://www.wowhead.com/npc=6235) - starts using it's abilities only on very low hp.

Crowd Pummeler 9-60 (http://www.wowhead.com/npc=6229) - probably working as intended, though it's Crowd Pummel ability (http://www.wowhead.com/spell=10887) needs further testing.

Leprous:

Leprous assistants (http://www.wowhead.com/npc=7603) - missing their lines (look at comments section @ wowhead).
Leprous defender (http://www.wowhead.com/npc=6223) - both Multi-Shot (www.wowhead.com/spell=14443) and Shoot (http://www.wowhead.com/spell=6660) abilities are missing, they are just meleeing.
Leprous Machinesmith - all abilities (Supercharge - http://www.wowhead.com/spell=10732, Throw Wrench - http://www.wowhead.com/spell=13398, Tune Up - http://www.wowhead.com/spell=10348) are missing.
Leprous Technicians (http://www.wowhead.com/npc=6222) - same as above.

Mekgineer Thermaplugg (http://www.wowhead.com/npc=7800) - script is kinda messed up. He won't use his Pound (http://www.wowhead.com/spell=74720) and Welding Beam (http://www.wowhead.com/spell=52778) abilities, also bombs that he spawns (http://www.wowhead.com/npc=7915) don't do damage when destroyed and won't seek their targets. Also, he spawns them all in one place rather than 'charging up' faces around him.

Also, he has a hard time moving from the center of the room (like some invisible walls which obstructs him is present there), but this is a general feature that occurs with NPCs at many places. Some examples, including Thermaplugg:

http://i40.tinypic.com/2cr0bch.jpg

http://i41.tinypic.com/10zu1wn.jpg

Dark Iron Dwarves:

Dark Iron Agent - was reported here already (https://github.com/dalaranwow/dalaran-wow/issues/95). Basically, they summon mines as guardians instead of stationary units. Mine should go off in 10 seconds after somebody approaches it, detonates instantly here. Also, mines have too much hps (they should have 200 and have 1900 or so instead).

Dark Iron Ambassador - needs further testing.

Alliance-Friendly NPCs:

Holdout Warrior (http://www.wowhead.com/npc=6391) - won't react at any hostile Trogg units kited to them, abilities are yet to be tested.
Here's the screen: 

http://i42.tinypic.com/any9g2.png

Holdout Technician (http://www.wowhead.com/npc=6407) - same as above.

Holdout Medic (http://www.wowhead.com/npc=6392) - same as above + they won't heal\buff you.

This concludes it all, I believe. Cheers.

**Comment by n-ghost** [comment]
Atm the creatures are scripted (which is very cool, by the way), but there is still a small matter of non-working quests, drops and friendly/hostile mob interaction.

**Comment by Rushor** [comment]
https://github.com/TrinityCore/TrinityCore/commit/51c9bc75aa20f21bbbb0ff3e7eb73d3ae455704b

**Comment by Rushor** [comment]
SAIs were already added long time agao - pls open up a new issue for the mechanic that are still missing. (each mechanic - new issue) The issue here is simply too big to get a good overview what has to be done - and what not. Thank you
