### ISSUE TITLE
Quest: No Mere Dream 10965

### ISSUE THREAD

**Issue by Sagrath** [dalaranwow/dalaran-wow#667]
http://www.wowhead.com/quest=10965
Missing Gossip from Clintar Dreamwalker which summons her spirit, which you have to protect while she gathers the relics of Aviana
Clintar Dreamwalker   http://www.wowhead.com/npc=22916
Clintar Dreamwalker's Spirit http://www.wowhead.com/npc=22834

**Comment by jonanone** [comment]
At this moment, once the quest is accepted, the escort begins. The spirit is a little cat right now. (Not sure if that's its correct form.)
