### ISSUE TITLE
NPC: Corrupted Rager

### ISSUE THREAD

**Issue by babyjebas** [dalaranwow/dalaran-wow#668]
Issue Present: Corrupted Rager in Lake Indu'le appears to be missing its loot table, I killed ~20 to farm crystallized water and nothing ever dropped.

How it should work: loot table should be added with ~19% drop rate of crystallized water among other items.

http://www.wowhead.com/npc=21223/corrupted-rager#drops

**Comment by jonanone** [comment]
The loot table has been added. This update will be applied to the live realm soon.
