### ISSUE TITLE
Quest: The Valiant's Challenge

### ISSUE THREAD

**Issue by Warlockboss** [dalaranwow/dalaran-wow#670]
The Valiant's Challenge - 13699
http://www.wowhead.com/quest=13699

How does it work currently: The player can equip his lance, mount a steed but when he goes to Squire Danny, NPC just says "Are you sure you are ready for mounted combat?"

How it should work: Player should be able to ask Squire Danny for an enemy Argent Champion, then defeat him in combat.

Squire Danny: http://www.wowhead.com/npc=33518

Argent Champion: http://www.wowhead.com/npc=33707

http://www.youtube.com/watch?v=sIv7PScmeHA

**Comment by fizzl** [comment]
Works, kinda sorta:
1. Speak to danny, he summons a champion
2. Speak to the champion, fight
3. Melee the killing blow.

I had to kill 5 champions just now, before I got it.

**Comment by Lothloryen** [comment]
It works fine since the Tournament release on Algalon.

**Comment by Vaxsysl** [comment]
I can confirm that this quest got bugged again in the manner Fizzl mentioned. I have had to kill 4 champions before getting the credit.

**Comment by Linandir** [comment]
Needs to be killed with melee-blow in order to work as fizzl said. Thanks for that btw.
