### ISSUE TITLE
Quest: Search and Rescue / Drak'tharon Keep

### ISSUE THREAD

**Issue by Golganeth** [dalaranwow/dalaran-wow#675]
http://wotlk.openwow.com/quest=12037

**Issue:** Kurzel doesn't spawn once you kill the webs.

**How it should work:** Kurzel should randomly spawn from one of the webs once they are killed. 

-----------------------

- *Darkweb Victim* - http://wotlk.openwow.com/npc=27909
- *Kurzel* - http://wotlk.openwow.com/npc=26664

**Comment by vison2** [comment]
Did the Instance on Algalon right now.

NPC was nowhere to be found

**Comment by TeridanDW** [comment]
![image](https://user-images.githubusercontent.com/6797611/32490544-2df18d26-c3bc-11e7-91ee-43af54f5d6b2.png)
