### ISSUE TITLE
Elemental Focus

### ISSUE THREAD

**Issue by Niny** [dalaranwow/dalaran-wow#683]
The Clearcasting proc isnt always working sometimes i cast a spell and im still left with 2 stacks of it, it usualy works but sometimes it dosent, i suggest u test it.

How it should work : http://wotlk.openwow.com/spell=16164

**Comment by Rushor** [comment]
> Lightning Bolt should consume a charge of Clearcasting when it's cast, not when it hits the target.

Reason for this is https://github.com/dalaranwow/dalaran-wow/issues/2186 (cosing because duplicate)

> The Clearcasting proc isnt always working sometimes

Already fixed together with https://github.com/tkrokli/TrinityCore/commit/07df574b432c641c37691b43d199daa4f69b2602 (Already working on PTR)
