### ISSUE TITLE
Profession/Instance: Skinning in Heroics

### ISSUE THREAD

**Issue by babyjebas** [dalaranwow/dalaran-wow#687]
Issue Present: All skin-able mobs in all HC dungeons are not skin-able.

How it should work: animal mobs in dungeons should be skin-able

**Comment by kazubla** [comment]
Can confirm the bug is still present after the argent tournament patch

**Comment by npmusicftw** [comment]
It's been two years since this has been found. Why on earth is it still a problem

**Comment by jonanone** [comment]
This issue has been fixed and it will be tested and deployed to the live realm soon.
