### ISSUE TITLE
Quest: Killohertz

### ISSUE THREAD

**Issue by Golganeth** [dalaranwow/dalaran-wow#688]
http://wotlk.openwow.com/quest=13383

**Issue:** Once you pick up the quest, "Infra-green Vision" is not casted on you. On top of that, the NPCs on the platform where you have to hand in the quest are not spawned, and the zone misses his protecting shield.

**How it should work:** Once you pick up the quest, "Infra-green Vision" should be casted on you, and the NPCs on the platform should become visible once you get inside the protecting shield.

--------------------------

- *Kibli Killohertz* - http://wotlk.openwow.com/npc=32444
- *Infra-green Vision* - http://wotlk.openwow.com/spell=59651
- ***Horde Version*** - #693

**Comment by Bloodhawk92** [comment]
Confirmed

**Comment by Rushor** [comment]
related script for the vehiclefight can be found here: https://github.com/Kittnz/Sunwell/blob/master/src/server/scripts/Northrend/zone_icecrown.cpp#L1063

**Comment by jonanone** [comment]
Killlohertz is now spawned and visible to everyone. This quest is now doable but not yet finished since infra-vision buff is still missing. It allows to follow with the next quests on the chain.

**Comment by Lothloryen** [comment]
#759
