### ISSUE TITLE
Quest: The Swarm Grows

### ISSUE THREAD

**Issue by Crispybuilt** [dalaranwow/dalaran-wow#69]
Quest The Swarm Grows - 1147
NPC Silithid Invade - 4131

Issue: There was only 1 Silithid Invader spawned in the entire game (checked Data Base) while there has to be multiple.

Closing this, issue resolved.

**Comment by Golganeth** [comment]
Fixed.

**Comment by Golganeth** [comment]
Reopening this.

**Comment by Rushor** [comment]
33b195f6f78d57b27698954674c4886e3f51aa4c
- added 6 Silithid Invader
