### ISSUE TITLE
Quest: Kick, What Kick?  12589

### ISSUE THREAD

**Issue by Sagrath** [dalaranwow/dalaran-wow#690]
Kick, What Kick? http://www.wowhead.com/quest=12589
RJR Rifle http://www.wowhead.com/item=38573
Lucky Wilhelm http://www.wowhead.com/npc=28054
Apple http://www.wowhead.com/npc=28053
There is no event when you shoot the Lucky Wilhelm with the apple over it's head. While Drostan should be saying a certain thing if when you miss and when you are close to hit. It should be something like X% chance to get the quest credit after shooting the NPC e.g. you have hit the apple on his head. Also the apple is missing from Wilhelms head

Lucky Wilhelm says: Ouch! That's it, I quit the target business!
Drostan says: Bah, it's an improvement.
Lucky Wilhelm says: Not the 'stache! Now I'm asymmetrical!
Drostan says: Bah, it's an improvement.
Lucky Wilhelm says: Good shot!

http://www.youtube.com/watch?v=YErfC7Gyh1o

**Comment by Lebaowski** [comment]
Temp fix is no longer functional. 

Accepted the quest, no apple. Tried shooting anyway, no reaction. 

After that Ive watched 2 others try to complete the quest over a period of 20-30 minutes or so, none of us get the apple spawned when accepting the quest.

I tried abandoning and re-accepting several times myself, better wait for another temp fix or a server restart.

**Comment by Sagrath** [comment]
working
