### ISSUE TITLE
Spell: Throw Passenger / Salvaged Demolisher / Ulduar

### ISSUE THREAD

**Issue by Sagrath** [dalaranwow/dalaran-wow#691]
Throw Passenger does not work at all, thoo passenger can be loaded into catapult
Throw Passenger http://www.wowhead.com/spell=62324
Salvaged Demolisher http://www.wowhead.com/npc=33109

**Comment by Lothloryen** [comment]
Hello there,

Corrected before the Ulduar release, I forgot to close this.

Thank you.
