### ISSUE TITLE
Quest: Recharging the Batteries 10190

### ISSUE THREAD

**Issue by Sagrath** [dalaranwow/dalaran-wow#694]
http://www.wowhead.com/quest=10190/recharging-the-batteries

Battery Recharging Blaster does nothing when used on phase hunters

**Comment by Demlock** [comment]
Not true. The quest works as intended. You need to weaken them enough to use it on them.

**Comment by Daveonx** [comment]
Tested and working fine.

**Comment by Golganeth** [comment]
I think the quest item should only be usable once NPCs are weak (35%~  The Phase Hunter is very weak" message appears)
Right now you are able to use the quest item when the NPC is at full HP but nothing will happen.
Proof needed.
