### ISSUE TITLE
Quest: Elemental Power Extraction 10226

### ISSUE THREAD

**Issue by Sagrath** [dalaranwow/dalaran-wow#695]
http://www.wowhead.com/quest=10226/elemental-power-extraction
Nothing happens upon using the quest item Elemental Power Extractor

http://www.wowhead.com/item=28547

**Comment by NomadicTurtle** [comment]
Still seems to not be working, does not auto-complete

**Comment by Daveonx** [comment]
Tested and currently working fine.

**Comment by Thimoteus** [comment]
Tried it today, all I managed to do with the item is aggro my target. Don't get any credit towards completion.
