### ISSUE TITLE
NPC: Frenzyheart / Oracles 

### ISSUE THREAD

**Issue by HeadOwns** [dalaranwow/dalaran-wow#697]
im doing quests with oracles and they told me to kill some frenzyhearts, i was killing them normally, my interface bugged so i had to relog, when i did, i couldnt attack anymore.

**Comment by taralej90** [comment]
This still doesn't work. I had to spam Thunder Clap on my Warrior in order to do the 50-kill quest...

**Comment by DrFuler** [comment]
[10/03/2016] - Still bugged. My pet (as a hunter) can still attack them though. Also, I tried as mentioned above and AoE is also an option.

**Comment by NovaHiros** [comment]
I can't attack them aswell - the only thing i can do is using "zepik" as a pet to kill them...It's irritating and frustrating. Please do something about this. P.s. - i had theyr plates visible but I couldn't attack them and any AOE effect won't affect them (no divine storm or consecration as paladin)

**Comment by Lothloryen** [comment]
You should now be able to attack them, any feedback will be welcome.

Thank you.
