### ISSUE TITLE
Quest: Dragonmaw Race: The Ballad of Oldie McOld 11064

### ISSUE THREAD

**Issue by Sagrath** [dalaranwow/dalaran-wow#701]
http://www.wowhead.com/quest=11064
You should get the quest "Dragonmaw Race: The Ballad of Oldie McOld", Follow "Murg "Oldie" Muckjaw" and defeat him in his race.  Instead, you get the quest, and he does not move, and the quest doesn't start.

Murg "Oldie" Muckjaw http://www.wowhead.com/npc=23340

**Comment by Augur89** [comment]
Still broken... and not only grants an achievement, but the whole chain also awards 3200 Netherwing reputation; that's a big chunk we'll have to grind instead.

If GM's cannot help I hope it will get fixed soon.

**Comment by Tarpor** [comment]
Still seems to be broken after the new patch.

**Comment by QjMimecha** [comment]
still broken

**Comment by Aalhazred** [comment]
still broken

**Comment by NovaHiros** [comment]
Three years later, still broken. I'll never get tired of proposing auto-complete for quests like this :)

**Comment by jonanone** [comment]
The 6 races have been implemented. They may need some polishments, but they can be completed now.

They will be applied to the live realm soon.

**Comment by sixele** [comment]
Does NOT seem to be working. The issue is the same as OP described. Does it work once per reset, or not at all, then?

**Comment by sixele** [comment]
If you do not mind the update, perhaps this does influence: for some reason (I did the Netherwing quests a year ago) I already have the quest [Earning Your Wings...](http://www.wowhead.com/quest=11063/earning-your-wings) completed, even though I have not done any races, which are needed to complete the quest. So, it means that
a) is still the case and it can break the races because you have "completed" the prerequisite quest which can only be returned after you have done the races (at least according to WoWhead) ; 
b) the races don't work at all anyways. 
I would appreciate if anyone checked out if the quests do work and it's only my (maybe others too) chain that goofed because of the one quest.

**Comment by axenon** [comment]
I don't know is it a bug again, but after accepting quest Dragonmaw Race: The Ballad of Oldie McOld proceeds to nothing. NPC is just standing at its place and nothing happens.

**Comment by 1ncredebil** [comment]
bump, NPC Oldie McOld still does nothing upon accepting the quest. It would be a shame if someone actually took his time to try fix the chain of quests, and just some minor issue is preventing them from working correctly.

**Comment by sixele** [comment]
It works now. Has been working for over a week. Not that I don't appreciate it, but as a minor note, when you fail the quest you get spammed [with this](http://i.imgur.com/ouRyq21.png). And it's not only you, anyone who is nearby, even if he does not have the relevant quest, will see the Failed messages.

**Comment by Zibathy** [comment]
Nothin'. Still broken on Kirin Tor.
![wowscrnshot_111816_184515](https://cloud.githubusercontent.com/assets/7729864/20451483/7c337486-adbf-11e6-9129-c796c39cf9c9.jpg)
![wowscrnshot_111816_184518](https://cloud.githubusercontent.com/assets/7729864/20451485/7c3797dc-adbf-11e6-8d9f-2cda2dea242d.jpg)
![wowscrnshot_111816_184523](https://cloud.githubusercontent.com/assets/7729864/20451486/7c37da76-adbf-11e6-91f1-86db9a9dedb3.jpg)
![wowscrnshot_111816_184650](https://cloud.githubusercontent.com/assets/7729864/20451484/7c36b7d6-adbf-11e6-8338-65b7b0c1b8ea.jpg)

**Comment by Rushor** [comment]
works for me http://i.imgur.com/fNOz4aL.png maybe an update this missing

commit was: cce3f272c63f95d960b9f8047a16c9cada994c6e
 maybe the update is missing on kirin Tor and it was only added on Algalon? @Lothloryen

**Comment by TeridanDW** [comment]
Works as intended on ptr, however as @jonanone said:

> They may need some polishments, but they can be completed now.

Please open a new issue for extra polishments.
