### ISSUE TITLE
Daily Group Quest: The Deadliest Trap Ever Laid 11097

### ISSUE THREAD

**Issue by Sagrath** [dalaranwow/dalaran-wow#702]
www.wowhead.com/quest=11097
In this quest the Event is missing.

Assist Commander Hobb and the Scryers in defending the Sanctum of the Stars. Once all of the Dragonmaw forces have been defeated, return to Overlord Mor'ghor at Dragonmaw Base Camp with the Scryer Medals.

http://www.youtube.com/watch?v=M_ygYydXyuk

**Comment by darkwulfv** [comment]
Still not working as of 6/10/2015. Quest can be accepted, but there is no way to start the event that allows you to complete it.

**Comment by NovaHiros** [comment]
Nothing happens - the event does not start.

**Comment by Crispybuilt** [comment]
Can confirm this is still broken.

**Comment by jonanone** [comment]
Event for both versions of the quest (Aldor and Scryer) has been added.
The fix will be added to the live realm soon.
