### ISSUE TITLE
Wintergrasp Battle Rewards

### ISSUE THREAD

**Issue by Warlockboss** [dalaranwow/dalaran-wow#707]
<b>  How it is right now:  </b>
 1) If a player is dead when battle ends he does not receive rewards.
 2) If a player is on winning side he receives 3k honor and 3 marks ignoring his rank presence in battle. Losers gets 1250 honor and 1 mark.
 
<b>  How it should be:  </b>
 1) I think player should receive his reward even if he died last second.
 2) As of patch 3.0.8:
 There are now three ranks in Wintergrasp: Recruit, Corporal, and First Lieutenant.
Players will be eligible for participation rewards after two honorable kills.
Players will receive increased honor with increased rank.
Players will receive additional Marks of Honor at Corporal or higher rank.
Players will receive corporal rank at 5 honorable kills instead of two.
 
<b>  Additional honor rewards:  </b>
As of ptach 3.1.2
Wintergrasp Victory now rewards 3000 Honor. (Down from 5000 Honor)
Wintergrasp Defeat now rewards 1250 Honor. (Down from 3000 Honor)
Tower Damaged now grants up to 750 Honor. (Down from 1250 Honor)
Tower Destroyed now grants up to 750 Honor. (Down from 1250 Honor)
Damaged Building Reward now grants up to 750 Honor. (Down from 1250 Honor)
Intact Building Defender now grants up to 1500 Honor. (Down from 2500 Honor) (Note: Currently shown as 150 Honor but most likely a typo)
 
Source: http://www.wowwiki.com/Wintergrasp

By the way, I am not sure nor I can confirm this but shouldn't workshops you control award extra honor?

**Comment by roger6** [comment]
Do those bug fixed already?
I've report the same duplicated issue, but result is this issue was closed, same bugs still exist in the game.

**Comment by Lothloryen** [comment]
Corrected.
