### ISSUE TITLE
Quest: Terokk's Downfall 11073

### ISSUE THREAD

**Issue by Sagrath** [dalaranwow/dalaran-wow#709]
http://www.wowhead.com/quest=11073

the quest should allow to summon the boss through the bones at the scene ... just that, talking to the bones, does not seem able to summon the boss

http://www.youtube.com/watch?v=71dF4s9ZCRM

**Comment by babikool** [comment]
It's working but when terokk gets shield there is no blue light on the ground for next part of quest

**Comment by Blackoutx** [comment]
Still not working 4/26

**Comment by Finlaypro** [comment]
11/10/2015: Still not working
You can summon Terokk but he takes inmunity at certain life and you can't take it out cause it doesn't appear blue light or smoke you need.

**Comment by Exorcista** [comment]
cool quest but seems like this is last of quest fixes in outland, lets hope one day will be able to do, cool trinket drop :(

**Comment by Crispybuilt** [comment]
I just did the quest and it works fine. You can call forth Terokk if you have the offering.
At 30% he becomes completely immune so you can't attack him anymore.
A way around that issue is to run away from him after he is immune, let him reset and just before he is about to regenerate health, hit him with a spell and finish the last remaining 30% hp.

**Comment by NovaHiros** [comment]
Don't say things work fine when they clearly don't. Terokk can't be killed. Once he goes "evade mode" even if you menage to engage him back before the regeneration starts, he will use divine shield again. He's got 221.000hp. They guy above says "him with a spell and finish him" - sure, 66.300 hp (its 30%) with "a spell"...please. 
Imho the divine shield part should be removed for an easy fix.

**Comment by phurios** [comment]
Lol thank you for refering this issue, not like it is going to solve itself just for doing that :v trolol.. *sigh* thank you my dear sir.

**Comment by Crispybuilt** [comment]
@NovaHiros  I have no idea what are you talking about. 
I've successfuly killed him at least 6 times now when I was farming the rep..
Like I said, you have to time it properly to hit him with something when he is about to regenerate health. His so called "bubble" does no re-apply if you do it quick enough.

**Comment by Lukas45** [comment]
Just because there's a workaround does not mean that it isn't broken

**Comment by jonanone** [comment]
Once Terokk reaches below 30% health and becomes immune, a skyward will appear to help.  Some smokey points will appear on the ground and the skyward will throw flames to that spots or summon a npc to help you with Terokk. These flames will remove Terokks immune shield.

The fix will be applied to the live realm soon.

**Comment by Golganeth** [comment]
You can summon infinite Terokks. You shouldn't be able to spawn it if one is already spawned.

**Comment by jonanone** [comment]
Terokk cannot be summoned while another Terokk is alive on the area. This update will be applied to the live realm soon.
