### ISSUE TITLE
NPC: Chill Nymph 23678

### ISSUE THREAD

**Issue by Sagrath** [dalaranwow/dalaran-wow#710]
http://www.wowhead.com/npc=23678
Chill Nymphs talking common
[00:34:17] Chill Nymph says: [Common] Garde bur O lithtos O melka bor vassild mandos an nandige tiras 
(Thank you. I thought I would die without seeing my sisters again!)
need to be set so everyone could understand

**Comment by Golganeth** [comment]
Fixed.

> Chill Nymph says: Thank you. I thought I would die without seeing my sisters again!

> Chill Nymph says: I knew Lurielle would send help! Thank you, friend, and give Lurielle my thanks as well!

> Where am I? What happened to me? You... you freed me?

Can now be read by both factions.
