### ISSUE TITLE
Daily Quest: - Troll Patrol: Done to Death (Daily)

### ISSUE THREAD

**Issue by Golganeth** [dalaranwow/dalaran-wow#712]
http://wotlk.openwow.com/quest=12568

**Issue:** Once using the provided item on the corpses, credit is not given.

----------------------

- *Incinerating Oil* - http://wotlk.openwow.com/item=38556
- *Defeated Argent Footman* - 
http://wotlk.openwow.com/npc=28156 
http://wotlk.openwow.com/npc=28260

- *Defeated Argent Footman KC Bunny* - http://wotlk.openwow.com/npc=28316

**Comment by taralej90** [comment]
Still doesn't work. Nothing happens when the quest item is used on the corpses...

**Comment by jonanone** [comment]
Using the quest item now gives credit when used on the corpses. The fix will be applied to the live realm soon.
