### ISSUE TITLE
Instance: Stratholme (vanilla) issues

### ISSUE THREAD

**Issue by riddermark** [dalaranwow/dalaran-wow#715]
First of all - rare video of 2 guys completing classic Stratholme:
http://www.youtube.com/watch?v=zTNqqNdxVzQ
(not all bosses but still nice visual)
http://www.youtube.com/watch?v=bzWMW2UXK6g
(and this one is just epic although the game is vanilla)
## 1) Malor the Zealous

http://www.wowwiki.com/Malor_the_Zealous
his chest contains [Medallion of Faith] - which u cant loot at the moment
http://www.wowhead.com/quest=5122/the-medallion-of-faith

tricky part

The reason its repeatable is because you have to hand in the medallion before you kill Baron in the same run to get http://www.wowhead.com/?quest=5125. You can hand in the medallion a million times, but if Baron is already dead when you do, the quest line wont progress. So, if you've already killed Baron when you loot the medallion, save it and hand it in first thing on your next run.

As mentioned you get - http://www.wowhead.com/quest=5125
## 2) Magistrate Barthilas

Spawned at the wrong place. (you can also see this in the video)
http://www.wowhead.com/npc=10435/magistrate-barthilas#comments
## 3) The Unforgiven

http://www.wowhead.com/npc=10516#abilities

Haven't seen him spawned or didn't manage to trigger him to appear as described in the comment section.
## 4) Hearthsinger Forresten (RARE)

http://www.wowhead.com/npc=10558#abilities

Never seen on private server mainly because he drops: http://www.wowhead.com/item=13379 which is a cool thing to buy with vote/donation points.
## 5) Timmy the Cruel

http://www.wowhead.com/npc=10808#abilities

Wasnt spawn in the runs I made and he is a 100% spawn.
## 6) Mobs

There were a few Scarlet mobs that had no weapons equipped while it felt they should have as their abilites used on me suggested.

http://www.wowwiki.com/Stratholme_(original) - scroll down to Denizens and to Crusader's Square and Scarlet Bastion.

I think a check up on abilities and equipment should be made for:
http://www.wowwiki.com/Crimson_Battle_Mage
http://www.wowwiki.com/Crimson_Gallant
http://www.wowwiki.com/Crimson_Inquisitor
http://www.wowwiki.com/Crimson_Guardsman (not so sure about this one)

As there was a lot of punching going on and even the casters joined in.

.

Well that's it from me - Apologies if something does indeed work right and I overlookedit. I included the wowhead links mainly for the abilites and spawn points. Thanks for your time.

**Comment by n-ghost** [comment]
Just got a Righteous Orb to drop, other issues still stand though.

**Comment by daxpedda** [comment]
After the update it seems that you can loot [Medallion of Faith], however the followup quest where you actually need to kill the baron is on autocomplete. At least you can finish it :)

**Comment by Demlock** [comment]
Haven't been to Stratholme since the patch but I can confirm the above issues.

**Comment by Tyrial** [comment]
Little update on how things are now
1. Malor the zelous- looted medallion with no probs (first did the "living" part of dungeon), after i proceeded to ud part i was able to deliver the q to aurius in alonsus chapel with no probs
2. Timmy the cruel- doesnt spawned, despite i cleared all mobs on the square
3. Righteous orbs- Drops perfectly fine, got like 3 from 1 run
4. Supply crates for Houses of the Holy q- i would say partially working: most of the crates cant be looted (though you can see a cursor change when hovering over them), but there are several wich actually work fine
5. Unforgiven- no spawn
6. Ud part was fine- no issues with doors or boss mechanics, the timer wich should start once you open the gate to ud part is not working though (mean the gate to ziggurat bosses, not the ones at service entrance).

**Comment by Rushor** [comment]
will move the remaining issues to https://github.com/dalaranwow/dalaran-wow/issues/1817
