### ISSUE TITLE
Quest: Vent Horizon - Chain quest for Achievement: "Operation: Gnomeregan"

### ISSUE THREAD

**Issue by Crispybuilt** [dalaranwow/dalaran-wow#72]
Quest Vent Horizon - 25212

Issue: The quest simply doesn't work when you use the device.
When you take the "roflcopter" you have to fly with assigned flypath around the mountain.  
To complete this quest, turn your camera angle 90 degrees so that you are looking to the right (toward the mountains) and zoom out. You will then clearly see the vents as you fly past them and easily be able to target them.

This is how it has to work: http://www.youtube.com/watch?v=q1oC_GdnuU8
This is a part of the chain quest "Operation: Gnomeregan"

**Comment by Dexobox** [comment]
I can confirm that the flying machine is still un-usable :thumbsdown:

**Comment by jonanone** [comment]
Selecting the gossip will start the travel with the flying machine.
On the road you will be able to drop Radiageigatrons to the vents using the quest item.

The fix will be applied to the live realm soon.
