### ISSUE TITLE
Daily Quest: Discovering Your Roots (TBC)

### ISSUE THREAD

**Issue by riddermark** [dalaranwow/dalaran-wow#722]
http://www.wowhead.com/quest=11520/discovering-your-roots
works the same way as
http://www.wowhead.com/quest=11521

In short - you go to the area kill Razorthorn Flayers who drops a Razorthorn Flayer Gland. Then you throw said gland at nearby ravager which then turns in your pet with a set of skills one of which is - Root Digging.

Then you find a dirt mound and use the pet ability near the mound so you can discover a http://www.wowhead.com/item=34254. Get 5 of those and you are done.

What's broken here? - The pet skill of digging the root does nothing when used.

**Comment by ashido96** [comment]
Just gonna bring attention to this again and say that the pet instantly becomes hostile when you go into combat with anything.
Quick fix by giving quest credit once when making it become your pet? So you still have to kill 5 flayers for 5 glands, I think it would take about the same amount of time.

**Comment by jonanone** [comment]
Once the ability is used near a mound, the pet will go to the mound and expose the roots beneath. The fix will be applied to the live realm soon.

**Comment by Golganeth** [comment]
The roots appear instantly right where the pet is when the ability is used, so it looks weird if the ability is used a few yards away of the mound.

They should appear on the mound's location once the pet reaches it

**Comment by Braniacz** [comment]
The root appears now on the location of the mound also when ability of a pet is used he will move to mound and start diging. The only problem I encountered is that when you or your pet enters combat he will break free and turn hostile. As we see in this video http://www.youtube.com/watch?v=bR-fejY0RF8 even tho player is attacked pet still remains friendly.

**Comment by Rushor** [comment]
pets should not remove auras on evade

**Comment by Zibathy** [comment]
Not working on Kirin Tor. The ravager doesn't dig to reveal to roots, and also turns hostile (removes the charmed aura) after leaving combat with anything.
