### ISSUE TITLE
Quest: Death From Below

### ISSUE THREAD

**Issue by Golganeth** [dalaranwow/dalaran-wow#731]
http://wotlk.openwow.com/quest=667

- **Issue 1:** Once you pick up the quest, waves of Nagas are not appearing.
- **Issue 2:** Upon using the lone cannon on the main deck, *World Invisible Trigger's Cannon Ball* instantly kills you.
- **Note:** Even when you don't use the cannon within the boat, you may get instantly killed by the trigger regardless.

----------------

**How it should work:** Once the quest is taken, waves of nagas should appear from behind the hill: firstly one wave of three, then one wave of two, and a final wave of three (all of them level 40).

Right-clicking the cannon should instantly one-shot them and of course, it should not kill the player.

--------

- *Cannon* - http://wotlk.openwow.com/object=113531

**Comment by Rushor** [comment]
fixed in https://github.com/TrinityCore/TrinityCore/commit/68c4ea314443699ac035e78a706d8371cc50b8ef
