### ISSUE TITLE
Dispersion & Shadowform

### ISSUE THREAD

**Issue by Astraxa** [dalaranwow/dalaran-wow#734]
When dispersion is used in Shadowform while mounted, it leaves the player after the spell is done with a transparent shadowform color but the mount is still with its correct shadowform color. Here are pics: before - while - after
![wowscrnshot_090313_032440](https://f.cloud.github.com/assets/5169063/1069788/4ea60ab0-142f-11e3-9ce4-2aea0c70688d.jpg)
![wowscrnshot_090313_032444](https://f.cloud.github.com/assets/5169063/1069789/4eabe066-142f-11e3-8aec-622c93e25080.jpg)
![wowscrnshot_090313_032454](https://f.cloud.github.com/assets/5169063/1069790/4eab469c-142f-11e3-8ee5-bfd94fb5ce0d.jpg)
Dismounting would fix this... but it would be nice to have this one fixed without glitching it.
Another bug concerning this:
starting from the last picture I submitted, when I dismount and then remount, the mount's color is also weird. Take a look at this:
![wowscrnshot_090313_033115](https://f.cloud.github.com/assets/5169063/1069813/2fd2df22-1430-11e3-9a6a-03c612265061.jpg)

**Comment by robinsch** [comment]
Can't confirm.
