### ISSUE TITLE
Quest: Volatility - Normal / Daily

### ISSUE THREAD

**Issue by Crispybuilt** [dalaranwow/dalaran-wow#736]
Quest **Volatility** - *13239 / 13261*

- **Issue present:** After collecting Pile of Bones, an Abandoned Helm, and Abandoned Armor, players will assemble a fake soldier which is picked up by a **Frosbrood Skytalon** *(ID:31137)*. **Frosbrood Skytalon** will fly up in the air and it has to be explode and get destroyed. Here, it doesn't.

- **How it should work:** **Frosbrood Skytalon** should explode and give player a credit when it dies.
It has something to do with the following NPC: *31364* - **Frostbrood Skytalon KC Bunny**. When I kill the bunny as Game Master, I get the credit.

**Video of how it should work:** *http://www.youtube.com/watch?v=2u4XA00NhfQ*

_______________________

http://wotlk.openwow.com/search=volatility#quests
http://wotlk.openwow.com/quest=13239
http://wotlk.openwow.com/quest=13261
http://www.wowwiki.com/Quest:Volatility
http://www.wowhead.com/quest=13261/volatility

**Comment by ashido96** [comment]
Since this quest became available with the recent updates and fixes to Icecrown phasing. I'll post that you can collect the 3 parts of the body and use the item to create the dummy and a frostbrood skytalon comes to pick up the dummy.

But then the frostbrood just despawns 30 seconds without blowing up or giving kill credit (with the dummy in its claws).

**Comment by AgeAgainst** [comment]
Confirming.  Does not work.

**Comment by Cone182** [comment]
confirmed, not working.

**Comment by deasease** [comment]
still not work

**Comment by MrAndersonX** [comment]
Confirmed - bugged. Needs a fix.

**Comment by Albulinek** [comment]
Still bugged

**Comment by NovaHiros** [comment]
Still bugged - doesn't give credit.

**Comment by Lothloryen** [comment]
Corrected, any feedback will be welcome.

Thank you.
