### ISSUE TITLE
Argent Officer Pureheart

### ISSUE THREAD

**Issue by Marecar96333** [dalaranwow/dalaran-wow#738]
She doesn't give the turn in quests for Argent Dawn rep to hordes,she should give them as the quests are natural and not alliance sided.
http://www.wowwiki.com/Argent_Officer_Pureheart

**Comment by Rushor** [comment]
http://wotlk.openwow.com/?npc=10840
http://wotlk.openwow.com/quest=5401

![GitHub Logo](http://i.imgur.com/WfIzy37.jpg)

works fine already on PTR
