### ISSUE TITLE
Quest: Suntara Stones

### ISSUE THREAD

**Issue by Crispybuilt** [dalaranwow/dalaran-wow#74]
Quest Suntara Stones - 3367

Issue: The entire escorting event doesn't work.

Quote from WoW Head -
If you are having trouble with this quest, simply drop it and try it again. The note was not on the ground when i first did this quest but i dropped it (the quest) and tried it again and it was there. I also play Draenei. Whether its worth the effort for you to retry is up to you.
The escort quest starts at the Grimsilt dig site. His co-ords are 63.9,61. Its advised you clear the area before start the escort quest.
The Note is at 74.4, 18.3 (this is where you will escort him to and where he will die). You will then be able to pickup the signed letter.
You then hand in the note to Curator Thorius who can be found in the Hall of Explorers in Ironforge.
Its worth about 250 rep with Ironforge and exp will depend on your level. I got about 5.8k at lvl 50.

**Comment by n-ghost** [comment]
Still an issue.

**Comment by n-ghost** [comment]
You can now take the quest from Dorius, but he still doesn't move anywhere afterwards, nor you can complete the quest at the letter.

**Comment by catta000** [comment]
Still not working.. you can take the quest, but Dorius will not move, and you cannot complete the quest.

**Comment by beregas** [comment]
Confirmed, nothing happens after accepting the quest!

**Comment by Rushor** [comment]
29c14f6f95454d642ff979d282d588b1644ae560
- added the escortevent

**Comment by Golganeth** [comment]
Quotes are missing.

**Comment by Rushor** [comment]
2da5f7abd1a2dac3e2315fe3c53593b352649cb7
- added the text, sadly i must replace the names with enemy due to $N bugs in the chat. let me know if you know a bettwe word for enemy

**Comment by Golganeth** [comment]
Dorius Stonetender says: It's on! Enemy, meet my fists. Fists, say hello to enemy.

That quote sounds very weird, but it's fine for now. Keep the tag of improvements needed.

**Comment by TeridanDW** [comment]
Works as intended on ptr, however i would like to add few small improvements:
 - The npc that spawns at the end of the escort quest (and kills npc http://wotlk.openwow.com/npc=8284), should have some extra flags like immune to npc and player attacks and reach set to deffensive on spawn so we are sure he will be able to make that shot before he is engaged in combat. After the shot unit_flag 768 can be removed.
 - npc http://wotlk.openwow.com/npc=8284 has too long respawn timer (~ 20 mins), suggestion set to 5 mins
 - set npc http://wotlk.openwow.com/npc=8284 and the one that kills him at the end of the escort to active during the quest so the event doesn't get stucked if player loses visual of any of these 2 creatures.
