### ISSUE TITLE
Missing quests and wrong quest order in Grizzly Hills

### ISSUE THREAD

**Issue by riddermark** [dalaranwow/dalaran-wow#741]
You can take The Thane of Voldrune quest which shouldn't be possible without first doing 3 other quests.The quest itself reads "Now that you've captured the flame-imbued talismans and weakened Voldrune's defenses, we can strike at its leader, Thane Torvald Eriksson."
http://www.wowhead.com/quest=12255

Said talisman is target of these quests (H) and (A) (seen on page)
http://www.wowhead.com/item=37229/flame-imbued-talisman#objective-of

Secrets of the Flamebinders (A) / The Flamebinders' Secrets (H)
http://www.wowhead.com/quest=12222#comments

This quest is usually done along with "Thinning the Ranks":
http://www.wowhead.com/quest=12223

BOTH of these quests can be taken after you complete:
http://www.wowhead.com/quest=12292

So these 3 quests must be completed before the Thane one becomes available. However I could not take Secrets of the Flamebinders and Thinning the Ranks. They just weren't available after Local Support as it should be. (I cover both quest and level requirements)

**Comment by jonanone** [comment]
Prerequisites have been fixed. This update will be applied to the live realm soon.
