### ISSUE TITLE
Jesse Masters (NPC)

### ISSUE THREAD

**Issue by riddermark** [dalaranwow/dalaran-wow#742]
http://www.wowhead.com/npc=29244/jesse-masters#comments

He is tied to the quests there - read the 2nd comment for linked quests.
"He will not sell Salted Venison until after you have completed Replenishing the Storehouse and will only sell Sizzling Grizzly Flank to you after you have completed Take Their Rear!."

Currently he sells right away without any prerequisites.

**Comment by jonanone** [comment]
This has been fixed. The update will be applied to the live realm soon.
