### ISSUE TITLE
NPC / Spell: Daggerfen Muckdweller / Paralytic Poison

### ISSUE THREAD

**Issue by Astraxa** [dalaranwow/dalaran-wow#751]
This spell is used by mobs in Zangarmash - called Daggerfen Muckdweller.
Paralytic Poison deals poison damage over time and stuns the the target for 5 seconds at the end of the spell duration ( 30 seconds ). However, the poison damage is extremely low ( 6~7 poison damage per 2 seconds ) and at the end of the duration, no stuns at all.

**Comment by Rushor** [comment]
spell=35201

**Comment by Rushor** [comment]
cd4404b4f379e4999e3cc000c2f4dbb4cdd9412c
- you will noe get stunned if the duration of the spell 35201 expires

**Comment by TeridanDW** [comment]
Works as intended on ptr.
Note: Damage from spell is still low, however i couldn't find any information that is should be higher so marking as:
