### ISSUE TITLE
[NPC] Ango'rosh Souleater

### ISSUE THREAD

**Issue by Astraxa** [dalaranwow/dalaran-wow#752]
Those mobs are bugged because they keep using their spell: Shadowform, which puts them in a "out of mana condition" all the time. They just keep spamming it every time their mana fills and is more than the mana cost of their shadowform spell. When they are attacked, they cast shadowbolt spell, but because they were already out of mana due to the shadowform spamming, they can only cast one bolt and then approach the player to melee them.

**Comment by Rushor** [comment]
![GitHub Logo](http://i.imgur.com/Cb7yjZx.jpg)

already fixed, they aren't casting their Shadowform spell all the time
