### ISSUE TITLE
Quest: Anatoly Will Talk

### ISSUE THREAD

**Issue by Crispybuilt** [dalaranwow/dalaran-wow#756]
**Quest Anatoly Will Talk** - *(ID:12330)*

- **Issue present:** The quest doesn't work properly and only one person per server restart / crash can do it. Quest needs a lot of improvements.

The issue is once someone does the quest, Tatjana and her horse doesnt' respawn properly. She should be on the horse (currently she is standing under the horse) and you are supposed to knock her down with the quest item, **Tranquilizer Dart** *(ID:37665)*. When you do that, her horse and her becomes friendly, but you are not force-mounted on the **Tatjana's Horse** *(ID:27626)*

- **Another issue**: After someone does the quest for the first time after a server restart/crash, the event will bug out. Tatjana and her horse will respawn, but once someone attempts to do the quest again, they are unable because they are simply not force-mounted on the horse for some reason (issue with NPCs).

**Tatjana** - *(ID:27626)*
**Tatjana's Horse** - *(ID:27627)*

- **How it should work:** Every time player does that quest, make sure to reset all the conditions for this quest, including all the NPCs and actions. Player should be automatically mounted on a horse and enjoy the ride until the X point to get the quest credit.
Also, make sure that Tatjana is actually mounted on the horse and not standing under it.

**Partial video of how it should work:** *http://www.youtube.com/watch?v=nV6HIvJYBA0*

____________________

http://www.wowhead.com/quest=12330/anatoly-will-talk
http://wotlk.openwow.com/quest=12330
http://www.wowwiki.com/Quest:Anatoly_Will_Talk

**Comment by Vaxsysl** [comment]
Seems to be bugged again, after this new fixes introduced. Herself and her horse are perma-friendly and nothing is happening when using the quest item, and neither are intractable.

**Comment by Vaxsysl** [comment]
So, server crashed, and I was online, so I decided to check on the quest.
Item is usable. She becomes friendly, the horse becomes friendly. We can mount...and nothing happens, and we can't do anything. She's still on the floor too.

**Comment by Lothloryen** [comment]
Hello there,

This quest should be working after the next restart, which will happen in about 20 minutes.

Thank you very much.
