### ISSUE TITLE
Quest: Digging for Prayer Beads

### ISSUE THREAD

**Issue by Crispybuilt** [dalaranwow/dalaran-wow#757]
**Quest Digging for Prayer Beads** - *(ID:10916)*

- **Issue present:** The 1st part of the quest doesn't work at all which is supposed to help you to find the **Fei Fei's Cache** to loot the item for the quest **Draenei Prayer Beads** *(ID:10916)*
The looting part works fine and you can do the quest.

- **How the first part should work**: After you give the NPC **Fei Fei** *(ID:20206)*, the item **Fei Fei Doggy Treat** *(ID:31799)*, the **Fei Fei** *(ID:20206)* should start a mini event where you have to follow him until you find game object **Fei Fei's Cache** *(ID:185302)*.

 Once you are there, **Fei Fei** will dig out a hole in the ground which will create the following animation (as shown on the video) and place a game object **Fei Fei's Stash** *(ID:185303)* near it. 

________

During the event **Fei Fei** will do the following emotions:
*Fei Fei looks for a hiding spot...* - does that when he stops
*Fei Fei digs in the dirt...* - does that when digging a dirt a placing uninteractable game object which will despawn after few minutes on a ground, **Fei Fei's Stash** *(ID:185303)*
*Fei Fei sniffs around, unsatisfied with his hiding spot* - does that when he starts looking for a new spot

**Video of how it should work:** *http://youtu.be/CgARfgAJdvI?t=2m44s*

Also, make sure to reset Fei Fei after the event is over so the other players can do it as well.

__________

http://www.wowhead.com/quest=10916/digging-for-prayer-beads
http://www.wowhead.com/item=31795
http://www.wowwiki.com/Quest:Digging_for_Prayer_Beads
http://wotlk.openwow.com/quest=10916
http://www.wowhead.com/item=31799

**Comment by Golganeth** [comment]
The waypoints are a bit glitchy on start, the dog climbs stuff and occasionally falls to textures at the start (first building).

The dog should have slightly increased speed.

(Low priority, the quest can be completed. You don't even need the doge event to complete it, since you can just directly go to the back of the inn and pick the quest item - blizzlike)
