### ISSUE TITLE
Quest: Natural Remedies

### ISSUE THREAD

**Issue by Crispybuilt** [dalaranwow/dalaran-wow#758]
**Quest Natural Remedies** - *(ID:10351)*
The quest works, but many players are spawning too much **Goliathon**'s which gives them trouble completing it.

_________

- **Issue present:** Players are able to summon infinite amount of time the following NPC while on a quest with the following item, **Seed of Revitalization** *(ID:29748)*:
**Goliathon** *(ID:19305)*

If they do it 10-15 times, they will have to face 10-15 **Goliathon**s which are all spawned on the same spot, which is then impossible to do.

- **2nd Issue present:** Entire Roleplay event from this quest is missing + the crytal is not surounded by giant roots as shown on the video. Also, a cloud of spell **Cyclone** should be active there all the time above the crystal object.

_______

**Pathaleon the Calculator's Image** *(ID:21504)* should appear non-hostile during  the summoning process and it should tell you the following quotes:

*Pathaleon the Calculator's Image: And just what do you think you are doing? You dare to interfere with the master's experiment?*

*Pathaleon the Calculator's Image: Do you like what we've done here? Perhaps we will drop these crystals from the sky all over Outland.*

*Pathaleon the Calculator's Image: I grow bored with you attempts to heal the land and quell the energies summoning and driving the colossi mad. Goliathon, King of the Colossi, Prince Kael'thas and I demand that you defend the crystal!*

*Pathaleon the Calculator's Image: We will meet again soon.*

After the channeling from an item is over, and the **Patheon the Calculator's Image** despawns, **Goliathon** will spawn where you have to fight him.

________________

- **How it should work:** They should be able to spawn **Goliathon** only once after using **Seed of Revitalization** *(ID:29748)*

**Video of how it should work:** http://www.youtube.com/watch?v=W1s4mwZXM3w

Possible fix: Simply force remove / delete the quest item from the bag once **Goliathon** is spawned behind you. That way you cannot spawn him anymore unless you re-take the quest again. If the player drops the quest, force-despawn **Goliathon** if possible.

___________

http://www.wowhead.com/quest=10351/natural-remedies
http://www.wowhead.com/item=29478
http://www.wowwiki.com/Quest:Natural_Remedies
http://www.wowhead.com/npc=19305/goliathon
http://wowpedia.org/Pathaleon_the_Calculator's_Image

**Comment by Demlock** [comment]
There is still a script missing for this. Would be awesome if you added it!

**Comment by jonanone** [comment]
Goliathon can now only be summoned while no other Goliathon is alive on the area. The animations to the red crystal and Pathaleon image talking have been added. The fix will be applied to the live realm soon.
