### ISSUE TITLE
Quest: Avenge Me!

### ISSUE THREAD

**Issue by Crispybuilt** [dalaranwow/dalaran-wow#760]
**Quest Avenge Me!** - *(ID:13230)*

- **Issue present:** Your goal is to finish off / slay the x5 of the following NPCs: **Dying Soldier** *(ID:31304)*. Currently, you are unable to kill them because they remain friendly to you. If you somehow manage to kill them, you will not get the credit for it, because they are stuck on 29,4% of their HP. Once they respawn, they'll be respawned on 100% of HP and then if you somehow manage to kill them (only GM can do it atm), you will get the credit.

- **How it should work:** **Dying Soldier** should have a gossip option, such as **Finish me!**, and once you click on it, **Dying Soldier** will appear hostile to you, but he won't attack you. Once you kill him, you should get the credit.
The quest is also related to the following bunny: **Dying Soldier KC Bunny** *(ID:31312)*

____________

http://www.wowwiki.com/Quest:Avenge_Me!
http://www.wowhead.com/quest=13230/avenge-me#comments

**Comment by DrFuler** [comment]
[21/04/2016] - Completable.

The damaged Dying Soldiers do not give credit (the ones with only 30% of their health). The ones at full health do give credit, making the quest completable.
