### ISSUE TITLE
Quest: Items of Power

### ISSUE THREAD

**Issue by Crispybuilt** [dalaranwow/dalaran-wow#761]
**Quest Items of Power** - *1948*

- **Issue present:** Players are unable to retrieve item **Bolt Charged Bramble** *(ID:7272)*, because once you use the item **Witherbark Totem Stick** *(ID:7273)* x10 near the object, **TEMP Stone of Outer Binding** *(ID:300012)*, the bramble is spawned but you are unable to interact with it.

- **How it should work:** After doing a ritual to summon a bramble, you should be able to loot the bramble and retrieve the **Bolt Charged Bramble**. The following game object has to be spawned on top of the stone and be lootable: **Bolt Charged Bramble** *(ID:103662)*

Already checked in-game and that object is lootable after spawning it manually.
![image](https://f.cloud.github.com/assets/5054924/1104005/5f286bce-18d7-11e3-9bde-3318b236e724.png)
_____________

http://www.wowhead.com/quest=1948/items-of-power
http://www.wowhead.com/item=7272#.

**Comment by Lothloryen** [comment]
Corrected after the next maintenance, thank you.

**Comment by n-ghost** [comment]
Still glitched: you can collect thingies from trolls and use them at stones, Witherbark Totem Bundle spawns on top of them, but you can't loot it whatsoever.

![wowscrnshot_062715_190231](https://cloud.githubusercontent.com/assets/8515510/8392798/63d714da-1cff-11e5-9932-35148ee2afa8.jpg)

**Comment by Lothloryen** [comment]
Thank you N-ghost, 

It will be added to the next scheduled maintenance, the patch which contained this quest fix got reverted few weeks ago.

**Comment by Lothloryen** [comment]
The realm will not be updated with this quest's correction with the ongoing maintenance. However it will be with the next one.

Thank you very much.

**Comment by n-ghost** [comment]
Works like a charm since the last update, thanks!

**Comment by Lothloryen** [comment]
Thank you, it got deployed, yes.
