### ISSUE TITLE
Quest: The Scepter of Celebras

### ISSUE THREAD

**Issue by Crispybuilt** [dalaranwow/dalaran-wow#762]
**Quest The Scepter of Celebras** - *7046*

- **Issue present:** The event doesnt' start to finish the quest. NPC **Celebras the Redeemed** *(ID:13716)* is not moving.

- **How it should work:** The event should start and you have to follow **Celebras the Redeemed** to the game object **Doodad_MaraudonStaffCreator01** *(ID:178560)* and he starts the Roleplay event to get his scepter.

_______

*Celebras the Redeemed says: You wish to learn of the stone? Follow me.*
*Celebras the Redeemed says: For so long I have drifted in my cursed form. You have freed me... Your hard work shall be repaid.*

*Celebras walks from where he is found to the stone near the further end of the tunnel.*

*Celebras the Redeemed says: Please do as I instruct you, [player's name].*
A book appears on the platform in front of the stone.

*Celebras the Redeemed says: Read this tome I have placed before you, and speak the words aloud.*
*Celebras the Redeemed begins to channel his energy, focusing on the stone.*
*Celebras the Redeemed says: Together, the two parts shall become one, once again.*

The top of the stone turns.
*Celebras the Redeemed says: Shal myrinan ishnu daldorah...*
*Celebras the Redeemed says: My scepter will once again become whole!*

**Quest objective completed** at this point.

**Video of how it should work:** *http://www.youtube.com/watch?v=QJuQ7jHeA2E*

__________

http://www.wowhead.com/quest=7046/the-scepter-of-celebras
http://www.wowwiki.com/Quest:The_Scepter_of_Celebras

**Comment by Demlock** [comment]
Confirmed, there is no event ingame. Also, the portal associated with this scepter is not working.

**Comment by n-ghost** [comment]
Still an issue.

**Comment by npmusicftw** [comment]
Two years later, still an issue.

**Comment by Zibathy** [comment]
Still an issue.

**Comment by DrFuler** [comment]
[30/04/2016] - Still an issue.

**Comment by Rushor** [comment]
still an issue kappa

**Comment by Rushor** [comment]
386221f6860f26327fb5780c3571c63544e7d288
- implemented the whole event with all texts

**Comment by Golganeth** [comment]
Quest credit is shown twice at the end of the quest.

**Comment by Rushor** [comment]
currently a general problem with all quests - not related to the script
but a fix for this was applied 5 days ago on trinitycore

**Comment by Jindra555** [comment]
Still cannot be completed - The event now works, up to the point when Celebras spawns the book. Either he doesn't or the book gets spawned inside the steps. In any case, there's nothing to click on and start the final part of the event.

**Comment by ImprezaWoW** [comment]
Tested, worked both on PTR and Live. Only issue encountered was what @Golganeth said.

**Comment by Jindra555** [comment]
Just tried it. Celebras cast the book spell himself. The last time I was there, he go stuck and the event didn't continue. Working now.

**Comment by Jindra555** [comment]
Update, tried it roughly 5 hours ago, trying it now, doesn't work. He gets stuck at the part where he should summon the book, or in our case, cast the spell. The one time it worked, I was on a different computer. Will attempt it on it again tomorrow.

**Comment by aqsdcv725xxp** [comment]
This quest is every bugged, there is no event in game
