### ISSUE TITLE
Quest: Escape From Skettis

### ISSUE THREAD

**Issue by Crispybuilt** [dalaranwow/dalaran-wow#763]
**Quest Escape From Skettis** - *(ID:11085)*

- **Issue present:** Upon picking up quest from NPC **Skyguard Prisoner** *(ID:23383)*, quest is automatically completed without starting an event. You can go back to the camp and instantly turn it in without doing any escorting effort.

- **How it should work:** You are supposed to escort **Skyguard Prisoner** away from the **Lower Veil Shil'ak** area to a safe location as show on the video, and then you get the credit. On the way, random  **Skettis Wing Guard** *(ID:21644)* should spawn and try to stop you and they have 4 main abilites.

Two **Skettis Wing Guard** will spawn as you reach the bottom of the 2nd bridge to enter ground area.
When you reach the bottom, you get the quest credit as show on the video.

	
**Demoralizing Shout** - *13730*
**Enrage** - *8599*
**Gushing Wound** - *35321*
**Retaliation** - *40546*

_____________
There are few quotes while doing this quest from **Skyguard Prisoner**:

Released from cage:
*Skyguard Prisoner says: Thanks for your help. Let's get out of here!*

Skettis Wing Guard pair killed:
*Skyguard Prisoner says: Let's keep moving. I don't like this place.*

Mobs cleared at the bottom of the ramp and quest complete:
*Skyguard Prisoner says: Thanks again. Sergeant Doryn will be glad to hear he has one less scout to replace this week.*

When **Skettis Wing Guard** spawns he has one of the random quotes he will say:
*Skettis Wing Guard says: Skettis Previals!*
*Skettis Wing Guard says: You'll go nowhere, Skyguard scum!*

**Video of how it should work:** *http://www.youtube.com/watch?v=KdUKIx2vivM*

________

http://www.wowhead.com/quest=11085/escape-from-skettis
http://www.wowhead.com/npc=23383#starts
http://www.wowwiki.com/Quest:Escape_from_Skettis

**Comment by Golganeth** [comment]
Hotfixed since the NPC Skyguard Prisoner wasn't spawned on Algalon. Now the players can obtain the quest if they meet the requirements. However above mentioned issues are still in need to be fixed (it gets autocompleted).

**Comment by jonanone** [comment]
Added the escort for the Skyguard Prisoner. The fix will be applied to the live realm soon.

**Comment by Golganeth** [comment]
The NPC for Skyguard Prisoner (ID: 23383) model seems to change randomly after restart/crash from human to dwarf etc. Sometimes it will even have the correct model. The NPC should always look like this
http://wow.zamimg.com/uploads/screenshots/normal/152362-escape-from-skettis.jpg
