### ISSUE TITLE
Racial Spell Aura / Buff: Heroic Presence from Draenei

### ISSUE THREAD

**Issue by Crispybuilt** [dalaranwow/dalaran-wow#77]
Heroic Presence - 6562 or 28878
Heroic Presence is double stacking on any character or a pet if there is more than one Draenei in the party or the raid group.

Screenshot: http://imageshack.us/scaled/landing/547/m8fc.jpg

**Comment by Thracia** [comment]
You forgot to tell that this buff doesn't seems to work. In stats there should be 1%(1) in Hit Chance Rating. I hope this will be fixed soon

**Comment by Golganeth** [comment]
This is not Cataclysm/MoP/WoD. Heroic Presence is a passive aura so the provided stats won't be reflected in your character's sheet.  Reading reliable WotLK sources helps a lot.

Thanks!

**Comment by Thracia** [comment]
Well some races have some advantages right? Take a look on a Blood elfs. They do have racial to gain mana and silence the target. Why Draenei shouldn't have fixed Heroic Presence? It skips the character stats build. Isn't that right? 1% extra hit rating in high level is great. You can raise your hit chance with 7 percent as a Draenei, while other races should build 8%. I think its great racial ability. Sorry for my english and my grammar.

**Comment by Rushor** [comment]
fixed 2 years ago 
https://github.com/TrinityCore/TrinityCore/blob/a56a402190c885e51038df55654875cc9e875c03/sql/old/3.3.5a/TDB53_to_TDB54_updates/world/2014_06_15_02_world_spell_group.sql#L603
