### ISSUE TITLE
Quest: The Ransacked Caravan 11465

### ISSUE THREAD

**Issue by Sagrath** [dalaranwow/dalaran-wow#774]
http://old.wowhead.com/quest=11465
You loot the Fjord Grub (http://old.wowhead.com/item=34102) from under the stones. You target the Fjord Turkey http://old.wowhead.com/npc=24746. You send your falcon to attack the turkey. But nothing happens. When you attack the turkey yourself, the turkey do change in the Fjord Turkey you need for the quest, but you can't pick it up.

**Comment by Daveonx** [comment]
Tested and currently working. Only minor issue I can find is that [Dragonflayer Ambusher](http://www.wowhead.com/npc=24779/dragonflayer-ambusher) spawns on every cast, when there should be a chance of it spawning.
