### ISSUE TITLE
Northrend Dungeons - Bosses Report

### ISSUE THREAD

**Issue by Muncic** [dalaranwow/dalaran-wow#778]
Nexus - 

2nd Boss (the Mage) she doesn't do the shadow ability throwing around every up and down

3rd Boss (The Rift guy) He doesn't go immune 2 times as it he is suppose to
## 4th Boss (The big Rock) - nothing wrong on the boss fight as far as I can remember, but the adds (little flowers) are suppose to give you a buff for 2% more mana/HP/w/e every 2 sec and the patrol by the boss is not patrolling at all

Utgarde Pinnale

Skada (3rd boss) - The whole encounter is bugged, from the harpoons (doable but still) to the mob spawns, the vision on him and so on and so on ... just test it and you will see ...

---

Utgarde Keep 

The Dualboss (2nd one) when one of them is killed he is spawned as an immortal dmging boss, making it an dps race

Last boss - no shockwave, no nothing from the abilitys ...

---

Gundrak

The 2nd boss (the Rock/Water element) . he doesn't not pull all the mobs inside of him on the start but we have to kill them manually 

The 3rd boss (Troll/mammoth) - he is suppose to cast faster after each interrupt or the lower the HP the faster the cast

Mobs in general ... The mobs before the last boss do not come to the central circle thingy for us to killed them normally

---

Violet Hold

A lot of texture buggs, the mobs are just dropping down and making it a waste of time. 

The last boss is bugged on role play ... she skips a lot of it 

---

Halls of Stones

1st boss (The rock dude) He doesn't display the stun nor a notification that the stun/dmg is coming ... he just bursts you like a maggot. P.S. He can be cheat pulled by hunter pats or boomkin tree mobs, which make you skip everything else

---

Halls of Lightning

Last boss mehanics not working properly, no AoE Nova

Mobs before the last boss do not patrol as they should

The Stone Mobs do not bump out after the 2nd Boss (the hallway is walkthrough)

---

Old Kingdom (my favorite)

First boss does not make his guardians on time

2nd boss is such a dps race that ICC bosses look and feel easier, 2 much healing and he makes the flame orbs OP .... not suppose to stay at one place ... they are suppose to spread around

Last boss ... The adds hit for 2 much the usually one shot the melee champs, especially the newbies that just dinged

---

Culling of Stratholme

Zombie respawn does not exist

Time run does not exist

Random mob sites - nope

The begging can bugg, not every can take the Q item and the roleplay doesn't start as it is suppose to

After killing the 2nd boss and the arthas walk through the mobs bugg on the 2nd pack ... he is suppose to be healed threw because the adds are not targetable , and the caster adds sometimes buff themselves non stop with 100% more attack speed/dmg

a lot of other thing are bugged aswell

---

Oculus
## The Mage boss is bugged, on impact he is suppose to port to another platform ... 

Pit of Saron

Ick - Does not change aggro on the "pursue" abilty

Last boss - the "if you do dmg you heal the boss" ability is not working at all

---

I know that all the instances are doable and not a priority but still wanted to report everything ...

**Comment by Rushor** [comment]
Most of the issues are already fixed. Pleae add the remaining issues to the open tickets for each instance.

you can find thos tickets with the search engine.  (f.ex.: https://github.com/dalaranwow/dalaran-wow/search?utf8=%E2%9C%93&q=Halls+of+Lightning)

For example: https://github.com/dalaranwow/dalaran-wow/issues/2050
