### ISSUE TITLE
Quest: Fire at Will! 10911

### ISSUE THREAD

**Issue by Sagrath** [dalaranwow/dalaran-wow#783]
http.wowhead.com/quest=10911
How it should work :
Use the naturalised amunition to take control over a Fel Cannon to destroy south and north warp gate.

Use the Fel Cannon ability to attack the warp gate, the warp gate will be destroyed once you shot 7 times with your fel canon ability, in the meantime imps and hounds should be summoned out of the warp-gate.

How it does work :

You can take control of a Fel Cannon but it does not attack the warp gate when the skill is used, neither summons appears from the warp gate.

**Comment by ashido96** [comment]
This quest has been removed from auto-complete status and is still bugged as described above.

**Comment by Demlock** [comment]
Yup, it apparently works only once per server restart. Can't confirm that though.

**Comment by Finlaypro** [comment]
11/10/2015: Still not working.

You can't even take control of the cannon with the item that druid gives you.

**Comment by DrFuler** [comment]
16/12/2015: Still not working.

Its getting really hard to get the On the Blade's Edge achievement ><'

**Comment by Crispybuilt** [comment]
Confirmed as not working.
21.7.2016

**Comment by Jezzybane** [comment]
Does nothing as of 03.08.2016

**Comment by jonanone** [comment]
- Using the item near the cannons will allow the player to control them.
- Using the first ability will start the event and once it has been used multiple times, the gate will be destroyed.
- Hounds and imps will be summoned during the event.

These updates will be tested and deployed to the live realm soon.

**Comment by XWingMitch0** [comment]
Quest is still bugged and unable to be completed as of 12/12/2019
