### ISSUE TITLE
[Quest][Outland] Meeting at the Blackwing Coven 10722

### ISSUE THREAD

**Issue by Sagrath** [dalaranwow/dalaran-wow#784]
http://www.wowhead.com/quest=10722
Problem: You can't speak to Kolphis Darkscale when you are in disguise. He just says "Greetings,".
How to reproduce: Take the quest,use the disguise,enter the Blackwing Coven and try to speak to Kolphis Darkscale.
How it should work: In disguise,you are able to have a conversation with him and the quest is completed.

**Comment by Zibathy** [comment]
I can't keep my costume on. I can only put it on at the entrance and it immediately gets taken off once I get through the opening tunnel. I am not casting any spells, buffing, looting, mining, nothing. I am simply walking deeper into the cave and it pops off for no reason. I can't be the only one. I can try to take video footage of it if need be. (This is on Kirin Tor btw)

**Comment by Demlock** [comment]
This works like a charm on Algalon

**Comment by Rushor** [comment]
yep work fine for me too http://i.imgur.com/7QHUY6R.jpg
