### ISSUE TITLE
[Quest][Northrend] Load'Er Up 

### ISSUE THREAD

**Issue by Sagrath** [dalaranwow/dalaran-wow#785]
www.wowhead.com/quest=11881
same issue as with https://github.com/dalaranwow/dalaran-wow/issues/355?source=cc

**Comment by Morens-D** [comment]
One more minor issue regarding this quest.

Jenny keeps follow the player even when quest is completed/rewarded.
NPC should disappear as soon as quest is completed.

**Comment by jonanone** [comment]
There is a bug with Jenny that doesn't allow us to despawn it instantly, so for now it will die as soon as the quest credit is given and it will instantly despawn after dying.

This update will be applied to the live realm soon. 

I will leave the issue open for future reference.

**Comment by Rushor** [comment]
DB/Quests/Borean Tundra: Load'er Up!

Jenny will die in order to be able to instant despawn once the quest credit is given. This way it won't stay bugged as a pet.

Closes https://github.com/dalaranwow/dalaran-wow/issues/785
* commit: d005ba3e1637682020d5d0d28f341ccac7c4b658

**Comment by TeridanDW** [comment]
This quest doesn't work on ptr at all. Issues found here:
 - Jenny doesn't follow the player at summon
 - Jenny should spawn around the player, currently it spawn over the player
 - Jenny's Z position is too high, he is spawned in the air.
