### ISSUE TITLE
Quest: Someone Else's Hard Work Pays Off

### ISSUE THREAD

**Issue by vexohm** [dalaranwow/dalaran-wow#792]
http://www.wowhead.com/quest=10218

Quest is unavailable, because the NPC to start it doesn't spawn.

The quest "Safety Is Job One" (http://www.wowhead.com/quest=10216) is completed in the "Mana Tombs" (http://www.wowhead.com/zone=3792), the quest turned in inside the instance at
>
the object "Ethereal Transporter Control Panel" (http://www.wowhead.com/object=183877). So far it worked fine. At least in normal difficulty, haven't been in HC version.

Tried clicking on the object's only clickable emote, option, nothing happened. The object should spawn
>
this NPC "Cryo-Engineer Sha'heen" (http://www.wowhead.com/npc=19671) and offer the follow up escort
>
quest "Someone Else's Hard Work Pays Off" (http://www.wowhead.com/quest=10218)

**Comment by Intensive6** [comment]
After the newest patch NPC "Cryo-Engineer Sha'heen" (http://www.wowhead.com/npc=19671) is spawned after clicking the object and offers the quest, but the escort is broken, NPC doesn't move.

**Comment by ashido96** [comment]
Will confirm that the NPC is correctly spawned and you can start the quest, but the NPC does not move.

**Comment by Demlock** [comment]
I can confirm that. He, along several other NPC's tied to escort quests are bugged to either not move at all (like in this case) or move but don't interact with objects and are not attacked by unfriendly NPC's.

**Comment by Crispybuilt** [comment]
Confirmed that the escort script for the quest is missing

**Comment by Cone182** [comment]
still broken

**Comment by jonanone** [comment]
Using the control panel summons Sha'heen and if you have the prerequisite quest completed (10216 - Safety Is Job One) he offers you the quest and starts the escort. During the escort, some creatures will spawn. At the end Xiraxis is summoned and killing him grants quest credit. The fix will be applied to the live realm soon.
