### ISSUE TITLE
Shaman/Spell: Feral Spirit/Pet ability: Spirit Walk malfunction

### ISSUE THREAD

**Issue by Brainpurge** [dalaranwow/dalaran-wow#794]
Spell: Feral Spirit (ID:52120)
Pet Ability: Spirit Walk (ID:58875)

Ability description: Removes all movement impairing effects and increases the movement speed of you and your Spirit Wolves by 60% for 15 sec.

Issue present: Using Spirit Walk (ID:58875) when the summoned wolves are not in line of sight with the shaman leads to malfunction. In that case only the wolves get affected by the slow removing effect and the speed increasing effect.

How it should work: Using Spirit Walk (ID:58875) should affect both wolves and the shaman no matter if they are in line of sight or not.

How to reproduce: Summon the Feral Spirit (ID:52120) and order them to stay in place. Than hide somewhere (like in a building or behind a pillar) and use Spirit Walk (ID:58875).

The ability and the first effect : http://wotlk.openwow.com/spell=58876
The ability and the second effect : http://wotlk.openwow.com/spell=58875

**Comment by M0dinstaller** [comment]
Still bugged.

**Comment by Rushor** [comment]
affected effects:

```sql
DELETE FROM `spell_linked_spell` WHERE `spell_trigger`=58875 AND `spell_effect`=58876;
INSERT INTO `spell_linked_spell` (`spell_trigger`,`spell_effect`,`type`,`comment`) VALUES
(58875,58876,1, 'Spirit Walk');
```

**Comment by robinsch** [comment]
Ref: d21a996794c7835c40b44272ee75c83f88a44726

On PTR.
