### ISSUE TITLE
Ally of the Netherwing - No quest reward

### ISSUE THREAD

**Issue by riddermark** [dalaranwow/dalaran-wow#796]
This is the quest
http://www.wowhead.com/quest=10870

And in addition to the rep, xp and gold it should also allow you to choose a reward. One of the following:

http://www.wowhead.com/item=31490
http://www.wowhead.com/item=31491
http://www.wowhead.com/item=31492
http://www.wowhead.com/item=31493
http://www.wowhead.com/item=31494

Same for ally and horde.

**Comment by jonanone** [comment]
Missing loot has been added. It will be updated on the live realm soon.
