### ISSUE TITLE
[Item] Dire Brew

### ISSUE THREAD

**Issue by Crispybuilt** [dalaranwow/dalaran-wow#797]
**Item: Dire Brew** - 38320
- Issue present: The item doesn't transform you into a Dark Iron Dwarf, but it applies buff on you. _51010_ - **Dire Brew, rank 1 enUS**
- How it should work: Once you drink it, it should also morph you into a Dark Iron Dwarf. 
  ---

http://www.wowhead.com/item=38320#contained-in-object

**Comment by Rushor** [comment]
works fine on PTR.

![GitHub Logo](http://i.imgur.com/Q2hhPUF.jpg)

**Comment by Torrigan** [comment]
The Dark Iron Brewer does not appear to spawn in the Grim Guzzler on the live server. I have went a few times to check and he is not where he should be, so this item is not obtainable.
