### ISSUE TITLE
Issue about Voidwalker Minions across Durotar & Tanaris

### ISSUE THREAD

**Issue by Crispybuilt** [dalaranwow/dalaran-wow#8]
The problem is that they are not the actual level they are supposed to be, but higer then usual. Minions's HP and Damage should be corrected.

**Comment by Rushor** [comment]
problem still exists for npc: 8996, 12922

**Comment by Rushor** [comment]
DB/Creature: Voidwalker Minions - Update level in order to decrease health and damage

* closes https://github.com/dalaranwow/dalaran-wow/issues/8
* affects creature: 8996, 12922
* commit: 75e606028c7b2f4bed903bdcab27311ba93b25b9
