### ISSUE TITLE
Misc: Crossing Water while being Ghost - Dead (Ghost Visual Bug)

### ISSUE THREAD

**Issue by Crispybuilt** [dalaranwow/dalaran-wow#80]
Issue: When walking across the water being dead, there is a visual bug.
It appears to be that your character will be jumping up or down, skipping & swimming above water instead of Water Walking.

You will not see a visual bug yourself, but the others will see you. 
This could be a minor issue and annoying visual bug in Battleground for example such as: Arathi Basin or Isle of Conquest.

**Comment by Rushor** [comment]
yep this issue is still there

**Comment by Rushor** [comment]
tc fix merged
