### ISSUE TITLE
Quest: Mystery of the Infinite, Redux

### ISSUE THREAD

**Issue by Crispybuilt** [dalaranwow/dalaran-wow#806]
**Quest Mystery of the Infinite, Redux** - *13343*

- **Issue present:** Once you place **Hourglass of Eternity** *(ID:44450)* on the ground , the event doesn't start.

- **How it should work:** Event is simillar to **Myster of the Infinite** *(ID:12470)*, but the only difference is that you get level 80 mobs, instead of level 72-74.
Level 72 quest was already fixed here #242, so the script is most probably simillar.

The only actual difference is that the final boss which spawns, **Infinite Timerender** *(ID:32352)* is stronger than the previous version on level 72. **(27900 Infinite Timerender)**

**Video of how it should work:** *http://www.youtube.com/watch?v=SDh93VURZfE*

_________

http://www.wowhead.com/quest=13343/mystery-of-the-infinite-redux

**Comment by Prljoman** [comment]
After the big update I checked Chromie and she offers quests again. Previous one I did without any problems but this one "Mystery of the Infinite, Redux" is not working. Hourglass is spawned but nothing is happening.

**Comment by cover25** [comment]
Can Confirm that once placing the hourglass the mob spawning script is missing. No quest credit is given either.

**Comment by ar1s7717** [comment]
yup. still bugged.First quest works just fine. the redux still doesn't work. was looking forward to completing this and was a pretty horrible bummer to discover it didn't work.

**Comment by exiledone** [comment]
still bugged

**Comment by Deedeenka** [comment]
still bugged :(

**Comment by Taffa2** [comment]
Still bugged with the Nov 2015 update

**Comment by Linandir** [comment]
Confirmed bugged.

**Comment by DrFuler** [comment]
[13/03/2016] - Still bugged.

**Comment by Lothloryen** [comment]
Hello there,

This quest should be working after this next maintenance.

Thank you.
