### ISSUE TITLE
Quest: Meeting the Warchief

### ISSUE THREAD

**Issue by Crispybuilt** [dalaranwow/dalaran-wow#807]
**Quest Meeting the Warchief** - 9626 (Blood Elf Version)
**Quest Meeting the Warchief** - 9813 (Normal Horde Version)

- **Issue present:** After completing any of the chains that leads to the quest **Meeting the Warchief**, the NPC **Lady Sylvanas Windrunner** *(ID:10181)* is not offering the players the next quest to continue the chain, which is either **Meeting the Warchief** *(ID:9626)* or **Meeting the Warchief** *(ID:9813)*.

- **How it shoud work:** He should offer the next quest to continue the chain.

________

http://www.wowhead.com/quest=9813/meeting-the-warchief
http://www.wowhead.com/quest=9626/meeting-the-warchief
http://www.wowwiki.com/Quest:Meeting_the_Warchief
http://www.wowwiki.com/Quest:Meeting_the_Warchief_(blood_elf)

**Comment by Daveonx** [comment]
Tested and was able to get the follow up quest from Lady Sylvanas Windrunner. If players still experience issues with not obtain the follow quest, comment below.
