### ISSUE TITLE
[Quest][Classic] The Lich, Ras Frostwhisper

### ISSUE THREAD

**Issue by Revennaras** [dalaranwow/dalaran-wow#808]
**Quest The Lich, Ras Frostwhisper** - _(ID:5466)_

**Quest works, but not the way it is supposed to work.**
_Players can just kill Ras and obtain the item without forcing him to transform._

---

---
- **Issue present:** After using the quest item, **Soulbound Keepsake** _(ID:13752)_, on the NPC, **Ras Frostwhisper** _(ID:10508)_, nothing happens.
- **How it should work:** After using the quest item, **Soulbound Keepsake** _(ID:13752)_, on the NPC, **Ras Frostwhisper** _(ID:10508)_, which is a 20 second cast of spell **Boon of Life** _(ID:17179)_, Ras will transform himself into a human form. 
  Only then, when you kill him you'll be able to loot **Human Head of Ras Frostwhisper** _(ID:13626)_
  If you kill him in undead form, he will not drop the quest item (currently he does which so wrong).
  If you use it before you engage him into combat, nothing will happen, since it has to be during the fight.

---

**WoWhead comments:**
_The provided item (http://www.wowhead.com/?item=13752) is a 10-second targeted channel on Ras. The range is only about 30 yards, so you have to get lucky or have some way of avoiding his fears and knockbacks. If you're healing or tanking the run, make sure you have someone who can help tank/heal while you turn him human._

_When the spell is finished, Ras becomes unattackable for a short time, then heals himself and becomes human. He still has the same spells and abilities, but you can now loot his head! (You keep the Soulbound Keepsake when you turn the quest in, but I'm not aware of anything that changes if you turn him human.)_

_[He still has the same spells and abilities.. Indeed. The change appears to be entirely cosmetic. The quest says the ritual transforms him back into a mortal, but afterward he's still considered undead. For my paladin, that came in handy._

---

http://www.wowhead.com/quest=5466/the-lich-ras-frostwhisper
http://www.wowwiki.com/Quest:The_Lich,_Ras_Frostwhisper

**Comment by n-ghost** [comment]
Still an issue.

Also, currently the book is usable anywhere, not only on Ras (although, it applies correct effect to him when used in close proximity).

**Comment by Rushor** [comment]
any idea what's the model of him in human form? http://www.wowhead.com/npc=10508/ras-frostwhisper#screenshots:id=71143

**Comment by Klala** [comment]
[Human form](http://vignette4.wikia.nocookie.net/wowwiki/images/c/c4/Ras_Human.jpg/revision/latest?cb=20070509064706)
Taken from [wowwiki](http://wowwiki.wikia.com/wiki/Ras_Frostwhisper?oldid=2348815)

**Comment by Rushor** [comment]
yes but i need a creatureid/displayid to fix that xd

**Comment by Klala** [comment]
Unfortunately I cannot seem to find anything that relates me to his human form ID.

**Comment by Rushor** [comment]
i remember some creatures in hdz- 1-3 that could look like that, but not sure :/

**Comment by Teridan-dal-wow** [comment]
hdz?

**Comment by Rushor** [comment]
hdz = höhlen der zeit (in german) = The Caverns of Time :D

**Comment by Rushor** [comment]
note: the model from creatureid: 1402 could be used for this

**Comment by GuybrushGit** [comment]
The model is 5736 given by the spell 17186 - Ras Becomes a Boy.

**Comment by Rushor** [comment]
Thank you @GuybrushGit

**Comment by Rushor** [comment]
* Scripts/Scholomance: The Lich, Ras Frostwhisper - will now only show the loot 'Human Head of Ras Frostwhisper' if he was morphed to his human form
