### ISSUE TITLE
[Quest] I Sense a Disturbance

### ISSUE THREAD

**Issue by Marecar96333** [dalaranwow/dalaran-wow#811]
The leopard doesn't get you all the way where it is should for you to get the credit for the quest,walking there does the trick
http://www.wowhead.com/quest=12665/i-sense-a-disturbance

**Comment by darkwulfv** [comment]
Worked a couple months ago, but as of right now the kitty doesn't even spawn to take you there.

**Comment by 1ncredebil** [comment]
Yep, confirmed, no kitten spawns after talking to the quest giver.

**Comment by Cone182** [comment]
Flew there with a flying mount, got the credit

**Comment by Lothloryen** [comment]
Corrected already, players shall have the raid..

**Comment by GeneralSaurfang** [comment]
Currently, the kitty spawns and gets you there and back again. But you won't get the credit and the quest won't complete.

**Comment by Crispybuilt** [comment]
Need more feedback please on this issue if possible.
We've had one complaint yesterday that it didn't work as it should and the credit wasn't given upon arrival.
