### ISSUE TITLE
[Quest][Outland] Grim(oire) Business 

### ISSUE THREAD

**Issue by vexohm** [dalaranwow/dalaran-wow#813]
http://www.wowhead.com/quest=10998

Upon entering the right spot on Blades Edge Mountains (77.5 : 31.2) the boss "Vim'gol the Vile" (22911) doesn't spawn as intended.
http://www.wowhead.com/npc=22911

**Comment by Rushor** [comment]
this was fixed in https://github.com/TrinityCore/TrinityCore/commit/770d04363c77520a901f850fb25a8723f6c88a83
