### ISSUE TITLE
Quest: "Into the Soulgrinder" (11000)

### ISSUE THREAD

**Issue by vexohm** [dalaranwow/dalaran-wow#814]
http://www.wowhead.com/quest=11000
**Quest completeable, but the event /fight is missing.**

One rough ilustration how it should be:
http://www.youtube.com/watch?v=QJPnMnQRqCU

How it currently works:
The quest object "Skulloc's Soul" (a green swirling ball) is already spawned. 
http://www.wowhead.com/object=185577

The quest item "Skulloc's Soul" can be looted from it and you are "complete".
http://www.wowhead.com/item=32383

**Comment by Daveonx** [comment]
Tested and currently working.

**Comment by Golganeth** [comment]
Some cosmetic details are lacking like Orcs disappearing too fast when killed or Soulgrinder losing beams once it enters combat and then leaves it
