### ISSUE TITLE
Brewfest: Bark for the Thunderbrews/Barleybrews

### ISSUE THREAD

**Issue by riddermark** [dalaranwow/dalaran-wow#817]
http://www.wowhead.com/quest=11294/bark-for-the-thunderbrews
http://www.wowhead.com/quest=11293

Objective:
Spread the word about Brewfest at the flags outside the bank, in the Military Ward, in the Hall of Explorers, and in the Mystic Ward.

Problem:
You will shout an advertising slogan (chosen at random) at each point (each hall). 
The player shouts out this in simple white text as he/she passes each credit point.

This doesn't work here for the moment. 

Video of a working quest:
http://www.youtube.com/watch?v=AKs_vYCnaMs (starts at 1:50)

You can find which lines you need to add from here:
http://www.wowwiki.com/Quest:Bark_for_the_Barleybrews!
http://www.wowwiki.com/Quest:Bark_for_the_Thunderbrews!

Cheers!

**Comment by Spruitje** [comment]
I guess this should be closed, this worked for me in the brewfest 2015 event

**Comment by Golganeth** [comment]
Indeed. Closing up as well
