### ISSUE TITLE
Quest: Spiritual Insight (12028)

### ISSUE THREAD

**Issue by Shaann** [dalaranwow/dalaran-wow#821]
Link: http://www.wowhead.com/quest=12028/spiritual-insight

Issue: On your journey around the area, Toalu'u the Mystic is supposed to talk to you. All that happens during this quest is that you fly around wondering what's going on.

**Comment by jonanone** [comment]
Now Toalu'u whispers you while flying around turned into a wisp. The fix will be applied to the live realm soon.
