### ISSUE TITLE
Wintergrasp Commendation 

### ISSUE THREAD

**Issue by Sagrath** [dalaranwow/dalaran-wow#825]
http://www.wowhead.com/item=44115/wintergrasp-commendation
at vendore the price (9 marks) for Wintergrasp Mark of Honor isnt visible
http://www.wowhead.com/item=43589
 Vendors
www.wowhead.com/npc=32296/stone-guard-mukar‎
www.wowhead.com/npc=32294/knight-dameron‎

**Comment by Golganeth** [comment]
Update: Wintergrasp Commendation can only be bought for 30 Stone Keeper Shards. The option to buy them for 9 Wintergrasp Mark of Honor is missing.

http://wotlk.openwow.com/item=44115
http://wotlk.openwow.com/npc=32294 (A)
http://wotlk.openwow.com/npc=32296 (H)

**Comment by robinsch** [comment]
On PTR.

**Comment by Darthblaider** [comment]
Changelogs claim this is fixed, but it's definitely not available to purchase commendations via marks yet

**Comment by ImprezaWoW** [comment]
I'm going to open this because it's not in the game yet, so either the fix did not work, or it has not been applied yet. Please close it when it is implemented, if it's the latter.

**Comment by robinsch** [comment]
@Lothloryen This should be applied on live. https://bitbucket.org/dalaran-wow/algalon/src/1571011cf14ea9232c187f08d82847a76d61b1c2/sql/fixes/npc/Northrend/wintergrasp.sql?at=dev&fileviewer=file-view-default

**Comment by kalvindeane** [comment]
Go on @Lothloryen you know you want to...
