### ISSUE TITLE
Quest: You'll Need a Gryphon

### ISSUE THREAD

**Issue by Crispybuilt** [dalaranwow/dalaran-wow#826]
**Quest You'll Need a Gryphon - 12814**

- **Issue present:** Once you obtain the quest item (it took me 120 kills on two different characters to obtain it) **Onslaught Gryphon Reins** *(ID:40970)* and once you use the item, the player is automatically mounted on a gryphon.
The problem is that the gryphon is unable to fly, only walk around.

- **How is quest doable at the moment:** Simply use the item when you get to Uzo manually and use the skill when you are next to it.

___________

http://www.wowhead.com/item=40970/onslaught-gryphon-reins#comments
http://www.wowhead.com/quest=12814/youll-need-a-gryphon
http://www.wowwiki.com/Quest:You'll_Need_a_Gryphon

**Comment by Kaporalhart** [comment]
I confirm this, although i got the reins in about 15 kills instead of 120. I think i got lucky. The griffin only jumps around instead of flying.

**Comment by Taffa2** [comment]
I used it in the water as well and was able to get it to fly.  But when I get up to the platform I cannot complete the quest.  Uzo has a gray question mark over his head and I cannot talk to him or turn in the quest.

**Comment by Rushor** [comment]
http://i.imgur.com/tshGgGt.jpg
a8b67874f69ffa820edc1abb9ef81d9616e399c2
- droppchance for item increased
- gryphon can now fly around
- questcredit already worked fine for me
