### ISSUE TITLE
Quest: Lost in Action

### ISSUE THREAD

**Issue by Crispybuilt** [dalaranwow/dalaran-wow#829]
**Quest: Lost in Action** - *(ID:9738)*

- **Issue present:** You have to discover what happened to Earthbinder Rayge, Naturalist Bite, Weeder Greenthumb, and Windcaller Claw.
3/4 NPCs successfuly work except the following NPC: **Naturalist Bite** *(ID:17893)*.

**The issue** is that nothing happens when you click on the gossip option to release **Naturalist Bite**: 
>
Alright Bite, I'll let you out.

- **How it should work:** Once you click on the gossip option, **Bite** will come out and also give you a buff called **Mark of Bite** *(ID:34906)*. Your quest credit will get completed, *Naturalist Bite Discovered*.
Also, some nagas will spawn from behind and attempt to attack you as well.

*About 4 mobs will come after you release him.*
___________

**Quotes:**
*Upon release - 
Naturalist Bite says: Uh oh! It would appear that all of the noise you've been making has attracted some unwanted attention!*

*Upon aggro (on Quagmirran) -
 Naturalist Bite says: |Naturalist Bite growls.| You took my worldly possessions, but you will NEVER take my soul!*

![image](https://f.cloud.github.com/assets/5054924/1223438/0032e30c-271d-11e3-89ac-8438621556a8.png)

___________

http://www.wowhead.com/quest=9738/lost-in-action#comments
http://www.wowwiki.com/Quest:Lost_in_Action
http://www.wowhead.com/npc=17893#comments

**Comment by Naidira** [comment]
Autocomplete appears to be disabled for this, and Bite remains unable to be released.

**Comment by Cone182** [comment]
Confirmed, still not working

**Comment by HansDAndersson** [comment]
yea, cant release him either

**Comment by jonanone** [comment]
Talking with Naturalist Bite now opens the cage and summons 3 enemy nagas. Once they are defeated talking with the Naturalist again gives quest credit and a buff. The fix will be applied to the live realm soon.

**Comment by Golganeth** [comment]
So the NPC despawns once it grants a buff so the credit can only be obtained by one member in the group, and its respawn timer is pretty long.

The NPC shouldn't despawn so that more members can get credit, or credit should be granted automatically to all members once someone gets it.

**Comment by Rushor** [comment]
4f39d2569d2105d1132a56915c859b664b7a2b71
- the whole group will get the cillcredit now

**Comment by souirkan** [comment]
Does this still work?
I just talked to Npc, killed the Nagas, talked to him again and nothing happens.
It keeps respawning Nagas.
