### ISSUE TITLE
Hunter spell: Aspect of the Viper

### ISSUE THREAD

**Issue by Tasserski** [dalaranwow/dalaran-wow#833]
Currently the mana regen triggers off just about anything.

For a good example, a hunter can simply put Viper on and do a Volley on an empty piece of land. Even when Volley hits no mob, the hunter regains mana from Volley's "hits" and he ends up gaining mana (and never needing to drink).

It also procs from various kinds of non-combat activities such as using quest items (on mob corpses for an example) etc.

**Comment by robinsch** [comment]
On PTR.
