### ISSUE TITLE
Hunter: Auto Shot getting cancelled

### ISSUE THREAD

**Issue by Tasserski** [dalaranwow/dalaran-wow#834]
Sometimes when casting **Steady Shot**, the hunter completely stops auto attacking. /Startattack or similar things do not work, and the hunter needs to de-target and then target again to start auto attacking again.

**Comment by Golganeth** [comment]
Auto shot gets cancelled if the target goes out of LoS and it doesn't resume when the enemy comes back in LoS, the player needs to manually stop and start attacking again to work. (Reference: #2859)

**Comment by Rushor** [comment]
someone knows a fix for this?

**Comment by Golganeth** [comment]
Merge with #3495

**Comment by Golganeth** [comment]
The following issues still remain:

- [ ] Autoattacks stops after CC, tested with stuns. (/cast !auto shot solves it, /startattack doesn't)
- [ ] Autoattacks stop after going out of LoS, getting interrupted, and going back within line of sight (/cast !auto shot solves it, /startattack doesn't)
- [ ] Autoattacks stop after going out of range, getting interrupted, and going back to range. (/cast !auto shot solves it, /startattack doesn't)

**Comment by Golganeth** [comment]
The following issues still remain:

- [ ] Autoattacks stops after CC, tested with stuns. (/cast !auto shot or retarget solves it, /startattack doesn't)
- [ ] Autoattacks stop after going out of LoS, getting interrupted, and going back within line of sight (/cast !auto shot or retarget solves it, /startattack doesn't)
- [ ] Autoattacks stop after going out of range, getting interrupted, and going back to range. (/cast !auto shot or retarget solves it, /startattack doesn't)

**Comment by robinsch** [comment]
All issues should be fixed. On PTR.

**Comment by carlosoharo** [comment]
Please fix it asap.

**Comment by Winstrol** [comment]
please apply this fix, really annoying to play hunter atm 👎
