### ISSUE TITLE
Quest: The Jig is Up

### ISSUE THREAD

**Issue by Tasserski** [dalaranwow/dalaran-wow#839]
Totally completable, however when engaging the NPC "Mad" Jonah Sterling, the NPC should at 30 % jump down to the bottom of the cave and be eaten by the bear. Currently he can simply be killed by the player where he is.

**Comment by jonanone** [comment]
This event is now fully scripted. The update will be applied to the live realm soon.

**Comment by Radschpud** [comment]
not working
![wowscrnshot_120717_142711](https://user-images.githubusercontent.com/14928789/33717585-bf9d8774-db5a-11e7-8583-d005af7b88f9.jpg)
