### ISSUE TITLE
Quests: To Venomspite!

### ISSUE THREAD

**Issue by riddermark** [dalaranwow/dalaran-wow#841]
http://www.wowhead.com/quest=12182/to-venomspite

Upon taking this quest you should be automatically flown to the location of the quest objective. At the moment this doesnt happen.

The same goes for this one:
http://www.wowhead.com/quest=12189

And you can only get one of these quests - you can't take both.

**Comment by jonanone** [comment]
Accepting the quest To Venomspite! will bring the player flying to Venomspite. The fix will be deployed to the live realm soon.
