### ISSUE TITLE
Blighted Last Rites

### ISSUE THREAD

**Issue by riddermark** [dalaranwow/dalaran-wow#842]
This quest:
http://www.wowhead.com/quest=12206/blighted-last-rites

Works as in completes, however most of its scripting is missing.

1) after you do this quest - http://wotlk.wowhead.com/?quest=12211 should become available. However at the moment both quests are there from the start.

2) I don't believe that the scarlet prisoner (http://www.wowhead.com/npc=27349) on whom you throw the vial should be dissolved or disappear. I can't find any info that supports him dying but when you turn in the quest the NPC says "WHAT?! That's impossible! We've perfected the blight. It has a one-hundred percent lethality." - which makes me believe he doesnt get killed and what's more - it logically connects with the mini event that happens AFTER the quest:

- AFTER COMPLETION: the following exchange takes place between the two NPCs:
http://www.wowhead.com/npc=27248 (quest giver Vicky)
http://www.wowhead.com/npc=27250 (junior apothecary)

Apothecary Vicky Levine says: Schlemiel!
Junior Apothecary Schlemiel says: Huh?
Apothecary Vicky Levine says: Apparently you flubbed this batch of blight. What do you have to say for yourself?
Junior Apothecary Schlemiel says: But... I followed your instructions precisely! Sorry?
Apothecary Vicky Levine says: Sorry? SORRY? Here's sorry for you!

- At this point, Vicky throws a vial at Schlemiel. Schlemiel promptly turns into green slime that immediately evaporates.

Junior Apothecary Schlemiel says: Eep!
Apothecary Vicky Levine says: Oops. I guess it IS working! That's odd.
Apothecary Vicky Levine says: I'm gonna need a cleanup and a new assistant over here!

**Comment by Lothloryen** [comment]
This quest and the event should be already fine.

Thank you.
