### ISSUE TITLE
Quest: Escape from the Winterfin Caverns

### ISSUE THREAD

**Issue by Tasserski** [dalaranwow/dalaran-wow#846]
Currently the murlocs in the cave are not hostile towards the escort NPC, making it possible for the player to simply use "King Mrgl-Mrgl's Spare Suit" from the quest "Surrender... Not!" and walk the NPC out of the cave with no fighting at all.

Example showing that the murlocs should still be hostile:
http://www.youtube.com/watch?v=qIPUbaWADqM

**Comment by Thillo** [comment]
Also, when arriving at the river, lurgbbrl drops through the texture, which makes it impossible to get credit. Happened to me twice, kinda gave up after that
