### ISSUE TITLE
NPC: Short John Mithril

### ISSUE THREAD

**Issue by Crispybuilt** [dalaranwow/dalaran-wow#85]
NPC Short John Mithril - 14508

The NPC doesn't do his famous quotes during the quest for Arena Master in Gurubashi arena. After you obtain or turn in or occasionally every 1 minute he should yell this quotes while you are standing in arena.

Quotes missing: Arrr, Me Hearties! I be havin' some extra Treasure that I be givin' away at the Gurubashi Arena! All ye need do to collect it is open the chest I leave on the arena floor!

Ah, hits the spot!

**Comment by n-ghost** [comment]
As of now, Short John Mithril correctly yells a zone-wide warning anytime the chest spawns.

**Comment by Rushor** [comment]
closing pls :)

**Comment by belegija** [comment]
chest spawning times are still not at fixed intervalls every 3 hours. today it spawned exactly at 10:30 realm time. it should be at 00, 03, 06, 09, 12, 15, 18 and 21 o'clock, regardless of when it was looted.

**Comment by Rushor** [comment]
the original report(missing texts) was fixed. closing :)
