### ISSUE TITLE
What Illidan Wants, Illidan Gets...

### ISSUE THREAD

**Issue by riddermark** [dalaranwow/dalaran-wow#850]
What Illidan Wants, Illidan Gets...
http://www.wowhead.com/quest=10577/what-illidan-wants-illidan-gets#comments

Problems:
1) When you put the disguise on you should be able to reach the quest target and talk to him. HOWEVER there are 2 NPC guards in front of Ruusk:
http://www.wowhead.com/npc=22102
who remain hostile - their proximity means it's impossible to just turn it in - ud rather have to kill them first then use the costume.

2) Upon losing the disguise you should be able to talk to Borak:
http://www.wowhead.com/npc=21293
and get a new one. Currently there's no such option. (although i might be reading this wrong and it could mean that u simply have to drop-and-retake the quest)

**Comment by jonanone** [comment]
Removed the two hostile guards that were in front of Ruusk when they shouldn't. Borak gives you a new costume when you lose or throw the one that you receive.
