### ISSUE TITLE
Quest: Breaking Through (Horde)

### ISSUE THREAD

**Issue by Tasserski** [dalaranwow/dalaran-wow#853]
A couple of problems with this quest, although it is completable.

Prince Valanar spawns on the wrong level for Horde. Currently he spawns on the first floor, when he should spawn on the inside (middle) floor.

Second, there is no teleport to the middle floor, which is where the top level teleport should take Horde players as seen in this video:
http://www.youtube.com/watch?v=Gk3Oc0MR9Dk

Instead the teleport takes Horde players to the roof level (where only the Alliance version of the quest should be completed), where the Alliance NPCs are hostile towards them. There appears to be some sort of problem with the Alliance side quest as well, seeing as some of the NPCs spawn double:
http://i.imgur.com/X68KYzM.jpg

**Comment by irodeyourmom** [comment]
Teleporter on middle floor, STILL broken. Still require's wasting a HS for a quest.

**Comment by jonanone** [comment]
The missing teleport has been added. This update will be applied to the live realm soon.

**Comment by Bonham01** [comment]
Teleporter is still broken as of today (11-19-16)
