### ISSUE TITLE
[Quest][Northrend] Vision of Air

### ISSUE THREAD

**Issue by Tasserski** [dalaranwow/dalaran-wow#854]
Quest is completable, but the RP event triggered by using the quest item is not scripted.

A video of the event:
http://www.youtube.com/watch?v=i1OUcBoyqwk

**Comment by jonanone** [comment]
The missing RP event has been added.

It should be applied to the live realm soon.

**Comment by Rushor** [comment]
jokey wrote:
4 lines are missing, only 1 is available, which is: "KAGANISHU!"
