### ISSUE TITLE
NPC: Rabid Grizzly & Blighted Elk

### ISSUE THREAD

**Issue by Tasserski** [dalaranwow/dalaran-wow#858]
These mobs spawn too densely and in numbers too large in Dragonblight:
http://i.cubeupload.com/gwbd34.jpg

From for example this video:
http://www.youtube.com/watch?v=9EvsCGaM7dw
it is apparent that the mobs should spawn way more scarcely.

**Comment by jonanone** [comment]
The density and quantity of Rabid Grizzly and Blighted Elk has been adjusted. This update will be applied to the live realm soon.
