### ISSUE TITLE
NPC: Dead Mage Hunter

### ISSUE THREAD

**Issue by Tasserski** [dalaranwow/dalaran-wow#866]
Currently these NPCs that stand dead in the Moonrest Gardens of Dragonblight are lootable to infinity, for they do not despawn when they're looted.

It's possible to loot infinite amounts of the item "Mage Hunter Personal Effects" from one corpse, each item being worth around half a gold.

**Comment by gotmilk0112** [comment]
Still hasn't been fixed.

**Comment by Lothloryen** [comment]
Should be fine already.
