### ISSUE TITLE
NPC: Fordragon Battle Steed

### ISSUE THREAD

**Issue by Tasserski** [dalaranwow/dalaran-wow#872]
These NPCs seem to currently inhabit Maw of Neltharion in Dragonblight for what ever reason. I am quite sure they in fact belong to Fordragon Hold instead of these cavers.

http://i.imgur.com/d2eo4SU.jpg
http://i.imgur.com/7Rv0Rlk.jpg

**Comment by jonanone** [comment]
Steeds are now mounted by Fordragon Knights so they are not rideable by players straight away.
This update will be applied to the live realm soon.
