### ISSUE TITLE
[Event] Brew of the Month Club / year-long event

### ISSUE THREAD

**Issue by riddermark** [dalaranwow/dalaran-wow#878]
Brew of the Month Club is an organization dedicated to bringing you the best and most unique brews from around the world on a monthly basis.
## Membership benefits

Each month, one sample beer is mailed to you. The beer will randomly proc a special effect for that month. The proc rate is fairly low, so you will want a stack of beers if you want to see the effect proc. You can buy additional samples of that month's beer from the Brew Vendor at the Stonefire Tavern in Ironforge for the Alliance or at Darkbriar Lodge in Orgrimmar for the Horde. (These appear to be neutral, so technically, you could use the opposing faction's vendor if you are willing to fight your way in.) 

You must have completed the quest Brew of the Month Club, which is obtained after you spend 200 [Brewfest Prize Token] on the item ["Brew of the Month" Club Membership Form]. 

Then and ONLY then you are able to access the Vendors that sell brew of the month.
- Vendors
  Horde: http://www.wowhead.com/npc=27820
  Alliance: http://www.wowhead.com/npc=27812 (not sure if this is the correct one)
  NOTE: You can only buy the current Brew of the Month not the previous ones.
- Achievement
  http://www.wowhead.com/achievement=1183
  (Just confirmed, if you miss a month or two, GM's can reimburse the brews you missed, saves you having to wait another year to complete it.)
- Brews of the month
  Binary Brew - September
  http://www.wowhead.com/?item=37496
  Autumnal Acorn Ale - October
  http://www.wowhead.com/?item=37497
  Bartlett's Bitter Brew - November
  http://www.wowhead.com/?item=37498
  Lord of Frost's Private Label - December
  http://www.wowhead.com/?item=37499
  Wild Winter Pilsner - January
  http://www.wowhead.com/?item=37488
  Izzard's Ever Flavor - February
  http://www.wowhead.com/?item=37489
  Aromatic Honey Brew - March
  http://www.wowhead.com/?item=37490
  Metok's Bubble Bock - April
  http://www.wowhead.com/?item=37491
  Springtime Stout - May
  http://www.wowhead.com/?item=37492
  Blackrock Lager - June
  http://www.wowhead.com/?item=37493
  Stranglethorn Brew - July
  http://www.wowhead.com/?item=37494
  Draenic Pale Ale - August
  http://www.wowhead.com/?item=37495
- Fun side Effects
  Every drink procs a different effect that needs to be checked if works.
  After you drink a bottle of ANY of those drinks - the followin spell is cast:
  http://www.wowhead.com/spell=51655 that creates in your bag:
  http://www.wowhead.com/item=38626/empty-brew-bottle
  Also stack up to 24. You can throw this at players and NPCs for fun times :D

"Throwing those at the position of a player makes the bottle hit the player's head, instead of falling to the ground. Hint: Target the player to have the circle below them, then place the bottle target circle in the player circle"

---

Now let's get down to business. I will outlay in detail what needs to happen each month.
- On the 1st of each month you get mail with 1 bottle of the current brew of the month.
- You can later buy more of that from the vendors.
- Vendors only usable by people with Brew of the Month achievement (membership)
- You can't buy previous month brew only current
- Each time u drink you create http://www.wowhead.com/item=38626/empty-brew-bottle which u throw at players/npcs.
## JANUARY

The month of: http://www.wowhead.com/item=37488#comments
a) When you drink this you gain a buff for 5 minutes called (The Beast Within) : 

http://www.wowhead.com/?spell=50098
b) When you right-click the buff (or wait for the 5 minutes to end) the buff will disappear and you (Unleash the Beast!) which will make you roar so hard the ground of both you and nearby players will shake. http://www.wowhead.com/?spell=50099
c) and ofc like all the other Brews, when you drink it you get an Empty Brew Bottle, which you can throw at other players

Text of the MAIL you receive on the 1st of the month with 1 sample bottle:

"From: Brew of the Month Club
Subject: A New Year, A New Brew!

Greetings <name>!

We hope that the new year is treating you well. If it isn't, stop by our vendors to pick 

up the latest brew. It is sure to bring out the animal in you.

Enjoy the samples and have a great new year!

Brew of the Month Club"
## FEBRUARY

The month of: http://www.wowhead.com/item=37489#comments
a) Has the chance to give you the buff http://www.wowhead.com/?spell=49864
b) When you right-click the buff (or wait for the 5 minutes to end) the buff you will 'burp' green smoke.

Text of the MAIL you receive on the 1st of the month with 1 sample bottle:

"From: Brew of the Month Club
Subject: Can't Keep A Good Brew Down.

<name>

Sometimes you can't keep a good brew down. This new brew is good, but can you keep it down?

Remember, if you like these samples, you can get more from visiting our vendors.

Enjoy!

Brew of the Month Club"
## MARCH

The month of: http://www.wowhead.com/item=37490#comments
a) You get this buff on drinking: http://www.wowhead.com/spell=49750#comments, you lose all control during the duration of the buff, you run around wild & swarmed/chased by bees.
b) Cannot be removed on right click

Text of the MAIL you receive on the 1st of the month with 1 sample bottle:

"Hello <name>,

Sometimes you want a fragrant brew, and what is a better aroma than honey? Creatures great and small all love the sweet smell of honey. Once you try this brew out, we think you'll agree.

Remember, if you enjoyed these samples, you can purchase more from visiting our vendors.

Enjoy!

Brew of the Month Club"
## APRIL

The month of: http://www.wowhead.com/item=37491#comments
a) Chance on drinking to get http://www.wowhead.com/spell=49822
b) When you right-click the buff (or wait for the 5 minutes to end). Then you'll let out a very large Brew Bubble that will hang around for awhile and possibly merge with other bubbles. http://www.wowhead.com/npc=27882

Text of the MAIL you receive on the 1st of the month with 1 sample bottle:

"Because You Demanded It

We've heard that some of our members wanted a brew that was a little more light and bubbly. We've tried to tell them this isn't the "Champagne of the Month Club." 

Unfortunately that didn't stop the demand. Hopefully this month's brew will satisfy those that want a lighter and more bubbly brew.

Don't forget, if you enjoyed this sample, it is available for purchase from our vendors.

Enjoy!

Brew of the Month Club"
## MAY

The month of: http://www.wowhead.com/item=37492#comments
a) Visual the same thing as http://www.wowhead.com/?spell=55503 (without the healing part)
b) Proper buff: http://www.wowhead.com/?spell=49818 - Flower Child

Text of the MAIL you receive on the 1st of the month with 1 sample bottle:

"Hello <name>

Spring is definitely in the air, and this month you may find it underfoot! Try out our new brew, Springtime Stout. It's a refreshing brew perfect for this time of year.

Enjoy the sample, and remember that you can visit our vendors to purchase more!

Brew of the Month Club"
## JUNE

The month of: http://www.wowhead.com/item=37493#comments
a) Barely visible visual of the character breathing fire
b) On buff expire or removal you burp fire!

Text of the MAIL you receive on the 1st of the month with 1 sample bottle:

"We've got a hot brew for you this month! All the way from Blackrock Mountain comes Blackrock Lager.

Remember if you enjoyed this small sample, you can purchase more from our vendors.

Enjoy!

Brew of the Month Club"
## JULY

The month of: http://www.wowhead.com/item=37904#comments
a) Drinking this will spawn mini Jungle gnomes around you, and your character will do a /scared emote. Additionally, small jungle gnomes (Yes, even smaller than regular gnomes) will run towards you, and point at you when you cower in fear. The whole effect last 16 seconds, and while maybe not neccesary to know, this effect will, during it's duration remove you from any alcoholic effect.
NPCS: http://www.wowhead.com/npc=27908
b) The buff is - http://www.wowhead.com/spell=49962

Text of the MAIL you receive on the 1st of the month with 1 sample bottle:

"Greetings <name>, 

We have an exciting brew for you this month. Brew of the Month Club members have braved the jungles of Stranglethorn and have returned with this mysterious brew. 

Don't forget that if you enjoyed this brew sample, you can purchase more from our vendors. 

Enjoy! 

Brew of the Month Club"
## AUGUST

The month of: http://www.wowhead.com/item=37905#comments
a) You get mounted on http://www.wowhead.com/spell=49908 and followed by http://www.wowhead.com/npc=27958
b) Drinking this has a chance to spawn companion sized Pink Elekks, and also Mount yourself up on a Pink Elekk for 30 seconds.

Text of the MAIL you receive on the 1st of the month with 1 sample bottle:

"From: Brew of the Month Club

Subject: Did You Remember Your Brew?

Warm wishes <Name>,

Sometimes you have to go out of your way to find the best brew. This month's brew has traveled a long way, but we feel that it is well worth it.

Remember that if you enjoyed this brew sample, you can purchase more from our vendors.

Enjoy!

Brew of the Month Club"
## SEPTEMBER

The month of: http://www.wowhead.com/item=37496
a) When you drink Binary Brew you get a buff depending on which faction you belong to, instantly teaching you a new language that lasts for the next 5 minutes.
b) http://www.wowhead.com/?spell=50246 (horde) and http://www.wowhead.com/?spell=50242 (ally)

Text of the MAIL you receive on the 1st of the month with 1 sample bottle:

"Hi <name>,

Our brew this month is a polarizing one. You either love it or like it. We'll let you decide.

If you enjoy this brew, you can purchase more from our vendors.

Enjoy!

Brew of the Month Club"
## OCTOBER

The month of: http://www.wowhead.com/item=37497
a) Drinking this might make you feel Watched for the next few seconds (time varies), aswell as create an Empty Brew Bottle which you can throw at others or at the ground. http://www.wowhead.com/?spell=49754
b) The Watched buff summons a small Woodland Squirrel with either hate aura or love aura. Those with the hate aura might toss an acorn at you, and those with the love aura will follow you around with a heart above their heads. It is fully possible to summon more than one squirrel at a time, and these may have different auras.
http://www.wowhead.com/?spell=49764
http://www.wowhead.com/?spell=49757
c) When you drink it little Squirrels run over and throw acorns at you or fall in love with you. They don't last long however and only come once for every 4 or 5 drinks.

Text of the MAIL you receive on the 1st of the month with 1 sample bottle:

"Hello <name>,

Our brew this month is a celebration of autumn. We think this brew captures just some of the essence of this season. 

But you don't have to take our word for it, give it a try.If you enjoyed this sample, you can purchase more from our vendors.

Enjoy!

Brew of the Month Club"
## NOVEMBER

The month of: http://www.wowhead.com/item=37498#comments
a) Chance on Nauseous, after that expires, you barf & Girded Gut
http://www.wowhead.com/?spell=49869 and http://www.wowhead.com/?spell=50056
b) Barf over another Player or NPC, and they get Slimed! & Nauseous, making them barf in return http://www.wowhead.com/?spell=49870 and http://www.wowhead.com/?spell=49869
NOTE: The 2nd barf won't trigger Nauseous, otherwise it would be possible to have a chain reaction

Text of the MAIL you receive on the 1st of the month with 1 sample bottle:

"From: Brew of the Month Club

Subject: A Brew Even Your Friends Can Enjoy
Greetings <Name>!

We hope that the year has been treating you well.
If it hasn't, stop by our vendors to pick up our latest: Bartlett's Bitter Brew.
The flavor is unmatched, but we warn you that it is not for the weak of stomach.

Enjoy the samples and share with your friends!

Brew of the Month Club"
## DECEMBER

The month of: http://www.wowhead.com/item=37909#comments
a)When drinking this Brew, you'll become surrounded by ice (like Ice Block). You'll be unable to move while this buff is active.
b) The ice block-like effect does NOT grant any ice block-like immunities.
c) You get: http://www.wowhead.com/?spell=46104 followed by http://www.wowhead.com/?spell=49886

Text of the MAIL you receive on the 1st of the month with 1 sample bottle:

"From: Brew of the Month Club
Subject: A Chilling Tale

<name>,

This past summer we had some of our members tackle with the mighty Lord of Frost. More importantly, they discovered a large stash of his own brew. We've manage to stockpile a large amount of this rare brew and are sending you some samples.

If you enjoyed this refreshing sample, you can purchase more from our vendors.

Enjoy!

Brew of the Month Club"

---
- That's it! And remember all drinks create http://www.wowhead.com/item=38626/empty-brew-bottle even If I didnt specify it.
- Also all letters end with "- Brew of the Month Club", I just removed the "-" so it won't screw up with the tracker's formatting.

**Comment by Tarpor** [comment]
It broke again in the last maintenance.

http://imgur.com/ziSlNnq

**Comment by Tarpor** [comment]
Fixed. Just the mail is missing currently.

**Comment by Rushor** [comment]
so the vendors are working fine now, only the mail has to be fixed @Tarpor and @all other

**Comment by Rushor** [comment]
![GitHub Logo](https://i.imgur.com/grShIeN.jpg)
![GitHub Logo](https://i.imgur.com/RECiCRf.jpg)
