### ISSUE TITLE
Quest: Troll Patrol: Whatdya Want, a Medal? (Daily)

### ISSUE THREAD

**Issue by Crispybuilt** [dalaranwow/dalaran-wow#882]
**Quest Troll Patrol: Whatdya Want, a Medal?** - *(ID:12519)*

- **Issue present:** Players are unable to see the creatures / corpses, **Drakkari Corpse** *(ID: 28162)*, to pick up the quest item, **Drakkari Medallion** *(ID:38333*) from them. - Take note it is not a phasing issue. Even if you see the corpses as a Game Master in *Debug mode* they are not lootable.

- **How it should work:** Players should be able to see the corpses and loot the quest item from them. Once they pick it up from a corpse they shouldn't be able to do it again from the same corpse.

- **Additional information:** This could work and be fixed as simillar to #349.

_________

http://www.wowhead.com/quest=12519/troll-patrol-whatdya-want-a-medal
http://www.wowhead.com/item=38333
http://www.wowwiki.com/Quest:Troll_Patrol:_Whatdya_Want,_a_Medal%3F

**Comment by Xehpo** [comment]
This is still an issue. As of today the quest cannot be completed because of the aforementioned problem that the Drakkari Corpses are not visible.

**Comment by taralej90** [comment]
Confirmed. No corpses to loot...

**Comment by mattipanduro** [comment]
I have another issue... I can pick up the quest, but the captains have no task/quests for me. 

I have tried abandoning it and retaking but it still doesn´t work.

**Comment by marsalandrei** [comment]
Still bugged, I can sometimes find corpses around but when I approach them they phase out or something, they vanish

**Comment by jonanone** [comment]
The bodies are now visible and lootable. The fix will be applied to the live realm soon.

**Comment by Zibathy** [comment]
The corpses are neither visible nor lootable on Kirin Tor.

**Comment by Rushor** [comment]
**The issue is fixed on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.**

@Zibathy pls don't push this. The fixes will be applied in the future on the realm. They are not pushed on live yet.

**Comment by Zibathy** [comment]
Ah, alright, I assumed that the fix had already gone through since this thread is so old. I'm sorry about that.

**Comment by Rushor** [comment]
np just wait a bit more :)
