### ISSUE TITLE
[Quest][Ouland] The Soul Cannon of Reth'hedron

### ISSUE THREAD

**Issue by Crispybuilt** [dalaranwow/dalaran-wow#883]
**Quest The Soul Cannon of Reth'hedron** - _(ID:11089)_
- **Issue present:** After collecting all the materials needed for the quest, one is unavailable to a player due the unscripted NPC. Players are unable to obtain **Flawless Arcane Essence** _(ID:32822)_. They have to obtain it from the NPC called **Flawless Arcane Elemental** _(ID:23100)_, but the NPC is unavailable through game and script at the moment. If you force spawn him as a Game Master, he is friendly to players and unattackable.
- **How it should work:** To collect a **Flawless Arcane Essence**, players must travel to **Lake Jorune** above Stonebreaker Hold in Terokkar Forest and complete the task **Sar'this asks.** _(ID:23093)_. This entails killing five level 70 elementals

Once you talk to him, he should have a gossip option to start the escort.

**WoWhead comment**:
_Find Sar'this in the biggest hut and talk to him. He will then lead you through a series of rituals starting with the alter and halfway around the lake. You will have to kill one of each level 70 elementals that he summons. He will then lead you back to the alter where a group summons a diamond looking elemental that he joins with. You need to kill this guy to get the flawless arcane essence._

---

Quotes from Sar'this during escort event and fights:

_Sar'this says: So my blood was not a sufficient payment, eh? Fine, let us recover your arcane essence. After this, I owe Balthas nothing._

> Sar'this places a fetish at the ritual pile.

_Sar'this says: The process is arduous. We must first summon forth acolytes of the elements. you must then destroy these acolytes so that my minions can make preparations._

> Sar'this walks around the edge of Lake Jorune to cardinal compass points. At each stop, an elemental is summoned.
> 
> At this station, an Air elemental is summoned. You slay it.

_Sar'this says: Well done! Let's continue._
*Sar'this says: Prepare yourself! The acolyte of water is soon to come...

> A water elemental is summoned. You slay it.

_Sar'this says: Well done! Let's continue._

> Sar'this continues on around the lake.

_Sar'this says: Come forth, acolyte of earth!_

> An earth elemental is summoned. You slay this as well.

_Sar'this says: Well done! Let's continue._

> Sar'this continues around the lake.

_Sar'this says: Fire, show yourself!_

> A fire elemental is summoned. Again, you slay it.

_Sar'this says: Well done! Let's continue._

> Again, Sar'this moves on.

_Sar'this says: Now we call forth the the arcane acolyte._

> Flawless Arcane Elemental is summoned.

_Flawless Arcane Elemental says: I require your life essence to maintain my existence in this realm-_
_Sar'this says: It is yours my lord!_

> You slay the elemental and retrieve the Flawless Arcane Essence.
> ---

http://www.wowwiki.com/Quest:The_Soul_Cannon_of_Reth'hedron
http://www.wowwiki.com/Sar%27this
http://www.wowhead.com/quest=11089/the-soul-cannon-of-rethhedron
http://wowpedia.org/Sar%27this

**Comment by NovaHiros** [comment]
This is still bugged - script doesn't exist and quest can't be completed. I know this is not the forum to discuss but, why can't these kind of quest be auto-complete? There's quite a bunch of missing scripts and i know it'll be a pain to script every single missing part so, autocomplete and let's go on without having to sadly abandon hopes. It's been three years for this one in particular, but it's just one of the many. Auto-complete and everything goes on, Easy game, easy life.

**Comment by jonanone** [comment]
Selecting the gossip option from Sar'this summons an Arcane Elemental that drops the Flawless Arcane Essence. Escort and the summoning of another 4 elementals not implemented yet.

**Comment by Rushor** [comment]
DB/Quests/Shadowmoon Valley: The Soul Cannon of Reth'hedron.

Selecting the gossip option from Sar'this summons an Arcane Elemental that drops the Flawless Arcane Essence. Escort and the summoning of another 4 elementals not implemented yet.
Updates https://github.com/dalaranwow/dalaran-wow/issues/883
* commit: 8590eed1f2a583d8fc129ed7701017c3b84141e2

**Comment by Rushor** [comment]
Ref: https://github.com/TrinityCore/TrinityCore/issues/4763

**Comment by TeridanDW** [comment]
Works as intended on ptr, however the event is still missing, quest is completeable.
