### ISSUE TITLE
[NPC] Gerard Abernathy and friends (mini event in Undercity)

### ISSUE THREAD

**Issue by riddermark** [dalaranwow/dalaran-wow#889]
This is a fun little mostly conversation based event in Undercity that spices up the atmosphere. It involves the following NPCs:
http://www.wowhead.com/npc=5696 (Gerard Abernathy)
http://www.wowhead.com/npc=5697 (Theresa, Gerard's mindlsave)
http://www.wowhead.com/npc=5699 (Leona Tharpe)
http://www.wowhead.com/npc=5698 (Joanna Whitehall)
and http://www.wowhead.com/npc=4607#comments (Father Lankaster - Priest Trainer)

In short: The 'owner' of Theresa, experimented with her brain and turned her into a mindslave delivering items back and forth between Gerard and Father Lankster, he will brag to the two other undead NPC's, Leona Tharpe and Joanna Whitehall about his 'pet'.

Taken from the top comment here: 6 different conversations take place
http://www.wowhead.com/npc=5696#comments

Gerard Abernathy: “Theresa, take this to Father Lankester.”
Theresa walks off with bottle in hand.
- IMPORTANT (Here at this point you get a random conversation between the 3 NPCs - listed 6 of them below)

Over at Father Lankester.

Theresa: “My lord Abernathy sends this to you.”
Father Lankester: “Ugh! What is that scoundrel doing sending his vermin to me? Get out of my sight before I what is left of your life. And take this with you!”
Theresa: “Yes my Lord.”

She Returns.

Theresa: My lord. From Father Lankester.”
Gerard:  “Why thank you, My pet.”

---

Random convos 1 to 6:

1.Gerard “Didn’t I tell you my new domination techniques would work?”
Leona Tharpe “Truly Amazing, Gerard. How did you do it?”
Gerard “It was simple once I broke her spirit.”
Joanna Whitehall “I am truly impressed Gerard. I thought you were all talk, but I see I have been proven wrong.”

2.Gerard “Didn’t I tell you my new domination techniques would work?
Leona “I’ve never seen anything like it. No concentration or loss of awareness while the subject is dominated. What did you do to her?”
Gerard “Everyone has a weakness, it’s just a matter of finding it.”
Joanna “I don’t agree with your turning to alchemy to fix some of the problems, but I do agree with the results. Very well done.”

3.Gerard “So what do you think of my new toy?
Leona “Truly amazing, Gerard. How did you do it?
Gerard “I managed to discover that certain parts of the brain when removed or stimulated will make the subject much more docile.”
Joanna “I don’t agree with your turning to alchemy to fix some of the problems, but I do agree with the results. Very well done.”

4.Gerard “How do you like my pet?”
Leona “She retains knowledge and speech, and even the self sufficiency to perform tasks for you. Precisely what did you do?
Gerard “You don’t expect me to give up all of my secrets do you?”
Joanna “Bravo, Gerard, you have exceeded yourself yet again.

5.Gerard “As good as I told you it would be, yes?”
Leona “Amazing! How did you manage a permanent dominate?”
Gerard “A little torture, a pinch of magic, and an ample helping of invasive surgery. She was conscious, of course.”
Joanna “Did you have to house train her, Gerard?”

6.Gerard “How do you like my pet?”
Leona “I don’t approve of your experiments, Gerard, but I must admit the results are impressive. What exactly did you do to her?”
Gerard “A little ritual torture can go a long way.”
Joanna “An amazing discovery you have made. I would love an opportunity to look at all of the failed experiments.”

NOTE: From another comment about the lines:
- Judging by the comments it seems to me that these conversations are not set in stone. That is - eacn NPC can throw a random line from these already listed.
- I found two more ending comments from Joanna. She said, "Very nice, Gerald. Next you will be breeding them." as well as "Impressive, very impressive. Does she do tricks?"

**Comment by Rushor** [comment]
this was fixed with

https://github.com/TrinityCore/TrinityCore/blob/a02ef421b15adf9ca850dbf35993b3475415d490/sql/updates/world/2014_07_19_02_world_misc.sql
https://github.com/TrinityCore/TrinityCore/commit/569bfc3abaeb371d3c07531e8d8674321947b6d0
https://github.com/TrinityCore/TrinityCore/commit/b7251e1c9ebf9f4151adb46cae77b1213ebd5bf8
https://github.com/TrinityCore/TrinityCore/issues/12601
