### ISSUE TITLE
Fight Club mini-event in Undercity

### ISSUE THREAD

**Issue by riddermark** [dalaranwow/dalaran-wow#891]
In the war quarter you have these 2 NPCs:
http://www.wowhead.com/npc=5653 (Tyler)
http://www.wowhead.com/npc=5654 (Edward)

Fight a 3-wave mini event of mobs as their training. From wowiki: 
- Along with Edward, Tyler fights against other NPCs summoned by Brother Malach: starting with ghouls, then humans, and at the end an abomination.

The Borther Malach guy 
http://www.wowhead.com/npc=5661/brother-malach#comments
also has lines of dialogue before and after each fight. Much like the Ring of Blood in Nagrand or any similar quest.

The actual mobs wave spawn is done by: (as evident from Malach's dialogue)
http://www.wowhead.com/npc=5679

HIS DIALOGUE:
In Gutterspeak this guy says:

1) \* Edward, Tyler. Prepare for your first challenge.
Lysta, summon in the captives. (total amount of 3 mobs)
http://www.wowhead.com/npc=5680 and/or
http://www.wowhead.com/npc=5681

2) \* Not a challenge at all it seems. Let us see how you handle your second test. Lysta, bring forth minions of the Lich King.

Lysta, summon in undead captives. (one of each total 2)
http://www.wowhead.com/npc=5685
http://www.wowhead.com/npc=5686

3) \* It is time to face your final challenge, young warriors! Prepare for your hardest fight yet.
- Lysta, summon forth... the abomination!
  http://www.wowhead.com/npc=5687
- Well done Edward and Tyler. You are progressing along in your training quite nicely. We shall test your mettle again soon.

As for the other NPCs around the fight pit:
http://www.wowhead.com/npc=5658 (Chloe Curthas)
"She does the Undead Female laugh about every 4 seconds, which gets really annoying."

http://www.wowhead.com/npc=5655
from his screenshot obviously seems like he cheers at random interval as well
I would assume the same should go for the other npcs - doing some kind of emote
http://www.wowhad.com/npc=5656
(cheer/laugh etc)

**Comment by Rushor** [comment]
![GitHub Logo](http://i.imgur.com/2WC23ob.jpg)

it's funny to know that this is a film reference xD

well the script already works and the fights will be played every 170 seconds.
