### ISSUE TITLE
[NPC] Sergeant Houser and his 3 recruits

### ISSUE THREAD

**Issue by riddermark** [dalaranwow/dalaran-wow#892]
Sergeant Houser
http://www.wowhead.com/npc=5662

He trains 3 NPCs who fight the dummies and judging by their patrol dots they should take breaks from time to time and wander around: (look at their routes)
http://www.wowhead.com/npc=5663
http://www.wowhead.com/npc=5664
http://www.wowhead.com/npc=5665

This guy is drilling the new recruits, and says different things to them:
- "Alright you sorry sack of bones. Let's see what you've got. Strike your opponent, and don't stop till I say so."
- (Pretty sure this is the starting line that makes the NPCs stop wandering around and focus on the dummies)

"Can you see yourselves? That is the most pathetic excuse for sword slinging I have ever seen!"

"These piles of wood and straw may show mercy, but the Lich King won't!"

"The sword isn't a tool, it's an extension of you. I expect better!"
- "Stop! You maggots call that fighting? That is pathetic! Now put your hearts in it, you don't need them anymore anyway!"
- (maybe at this point the NPC start patrolling for a while before starting to fight the dummies again)

"You're dead, not buried. Now show me your best!"

"You sorry sacks of maggot flesh can do better than that, now prove it!"

"You don't fight for yourselves anymore maggots! You fight for the Queen now so show me something worthy of her!"

And of particular note:

"What do you call that? If that's fighting then I'm Lothar himself!"

**Comment by Rushor** [comment]
already fixed with https://github.com/TrinityCore/TrinityCore/issues/12495 (the fix is on the live server)
