### ISSUE TITLE
[NPC] Samantha Shackleton

### ISSUE THREAD

**Issue by riddermark** [dalaranwow/dalaran-wow#893]
Samantha Shackleton
http://www.wowhead.com/npc=5700

(missing text speech is the problem here) Add these:

These are all spoken at random, but she never seems to repeat the same line twice in a row: (in gutterspeak)

If I could just find "Magic and the Ways of Power". Ahh here it is, what was it doing over here?

That wasn't very helpful. Let me check the other one.

Ahh, "Mystical Conjurings of the Archmages of Dalaran." Perfect.

But this can't be right. Where did I put that other book?

"Magic Maladies", no. "Magic Matricies", no. Ahh here we go "Magic Mysteries".

If this is correct, then I have a lot more research to do.

"Magical Flows and How They Affect the World", by Maginor Dumas. That's the one I was looking for.

That's what I wanted to know. Now I just need to find where the flux variance is discussed.

So I was right about the energies. Let's see what the other tome has to say on the subject.

Ahh there it is.

Back to the drawing board.

There's the mystical tome I was looking for.

"Khadgar's Mystical Journal, Volume 8." I think this is the one I wanted.

I really need a better system for filing these books. Ahh that's the one I wanted.

Yes, yes. Hmm, it seems to cross reference another tome. Guess I have to find that one too.

Very interesting. But if that's the case then my theory is wrong. I must reread the other sections to see what I missed.

**Comment by Rushor** [comment]
already fixed with https://github.com/TrinityCore/TrinityCore/commit/a02ef421b15adf9ca850dbf35993b3475415d490#diff-50401a75c5fa484937f0cc0cd29823e1R199

2 years ago
