### ISSUE TITLE
[NPC] Apothecary Keever

### ISSUE THREAD

**Issue by riddermark** [dalaranwow/dalaran-wow#895]
Apothecary Keever
http://www.wowhead.com/npc=5734
http://www.wowwiki.com/Apothecary_Keever

http://www.wowhead.com/npc=5736 ( Caged human male)
http://www.wowhead.com/npc=5735 (female)

He (caged man) is turned by Apothecary Keever into a: Caged Toad, Caged Squirrel, Caged Rabbit and Caged Sheep. (in that order)
http://www.wowhead.com/?npc=5742
http://www.wowhead.com/?npc=5739
http://www.wowhead.com/?npc=5741
http://www.wowhead.com/?npc=5743

Here's the full event: (you can read it transcribed on wowiki) - Note that this is what he says he just talks about himself in 3rd person.

Apothecary Keever says: Hmm, it would seem Keever needs a new subject. If that fool Abernathy keeps taking Keever's subjects, Keever may have to have a word with him.

Apothecary Keever says: Ahh, there we go. Now, Keever must try this vial and see if it works.

Apothecary Keever forces the fluid down the weary man's throat.

(The caged man turns into a toad.)

Apothecary Keever pokes the small toad.

Apothecary Keever says: Not what Keever was hoping for. Keever may have added too much earthroot. Let's see if the second serum will do what I need.

(The toad turns into a squirrel.)

Apothecary Keever pokes the small fuzzy squirrel with obvious disappointment.

Apothecary Keever says: Well, that is just not right. The creature is far too small. Let us see what Keever's third batch will do.

Apothecary Keever feeds the squirrel some of the viscous fluid.

(Squirrel turns into a rabbit.)

Apothecary Keever pokes the skittish rabbit.

Apothecary Keever says: Keever is unhappy with this. Perhaps if Keever were to try a larger dose, that may fix this dilemma.

Apothecary Keever grabs the rabbit and pours the fluid down its throat, then sets it back inside the cage.

(Rabbit turns into a sheep.)

Apothecary Keever says: What is this? Did Keever ask for a sheep? Keever wanted a weapon of great power and all he got was this sheep. Keever is very disappointed.

Apothecary Keever pokes the wooly sheep repeatedly.

(Sheep explodes into flames, Keever cackles inanely.)

Apothecary Keever says: Keever is most pleased.

EDIT: In addition the horde guards react to his speech sometimes:
The Overseers will sometimes get angry at Keever, saying stuff like "Get that rotten nut to shut his trap!" "Shut your face, you gibbering idiot!"
Horde guards are the Orc ones sent by Thrall after the wrathgate: http://www.wowhead.com/npc=36213/korkron-overseer

**Comment by Rushor** [comment]
already fixed with https://github.com/TrinityCore/TrinityCore/commit/a02ef421b15adf9ca850dbf35993b3475415d490 2 years ago
