### ISSUE TITLE
NPC: Lordaeron Citizen

### ISSUE THREAD

**Issue by riddermark** [dalaranwow/dalaran-wow#896]
Lordaeron Citizen
http://www.wowhead.com/npc=3617#drops
This NPC can be found in Undercity (38) - 38 being the total count of them?

Issue: these NPCs dont exist in-game currently. There should be around 38? i guess of them around the courtyard.
- "Yeah, and the Invisibility level is fairly high. I tried to see them with an  Elixir of Detect Lesser Invisibility, but it turns out its buff isn't enough. Begging Detect Invisibility from a passing level 45 warlock worked fine"
- Paladins can use sense undead to see them on their map.

If you read the comments it's pretty fun when low level players manage to aggro these by random aoe and get killed without them showing at all. Examples:

"Now i finally know what these are.... about a year ago when i first started the game i had a 27 warlock and used rain of fire on the broken statue in the middle, i was taking damage.... i was confused but NOW i know!"

"I accidently Ran past the broken statue where these are with my blood elf paladin and used arcane torrent, NOT a good idea. 
Even though they are invisible it's still possible to hit them with AoE, my poor level 1 paladin got 1-shot to death"

**Comment by Rushor** [comment]
already fixed 1 year ago.
