### ISSUE TITLE
Quest: "Death to the Necromagi" (12552)

### ISSUE THREAD

**Issue by vexohm** [dalaranwow/dalaran-wow#899]
The quest itself works fine.

The requirement for it to become available is off though, people could skip unknowingly.
It currently requires you to complete fully and turn in "Pa'Troll" (quest=12596), but it only should need 1/4th of it done, the respective captain's task the NPC Sergeant Moonshard is standing next to and being directly under his captains supervision: Captain Rupert (npc=28044).

In short:
For "Death to the Necromagi" (quest=12552) to become available, "Throwing Down" (quest=12598) needs to be completed, not "Pa'Troll" (quest=12596) as currently.

From wowhead:
" HolyBeans on 2009/05/29 (Patch 3.1.2)
To clarify, you don't need to complete Pa'Troll - Just Captain Rupert's criteria to unlock this quest hub. "

http://www.wowhead.com/npc=28283/sergeant-moonshard

http://www.wowhead.com/quest=12552/death-to-the-necromagi
http://www.wowhead.com/quest=12596/patroll
http://www.wowhead.com/quest=12598/throwing-down

**Comment by jonanone** [comment]
The requirement for the quest has been updated. The fix will be applied to live realm soon.

**Comment by Golganeth** [comment]
> Sergeant Moonshard still won't give the quest if the "Throwing Down" is completed and if "Pa'Troll" is completed also won't give the quest. Tested both on Horde and Alliance characters.

**Comment by Golganeth** [comment]
It seems the quest has some extra requirements. The quest showed up on PTR as soon as I completed [12553](http://wotlk.openwow.com/quest=12553) and [12583](http://wotlk.openwow.com/quest=12583) from [Specialist Cogwheel - 28284](http://wotlk.openwow.com/npc=28284)

**Comment by jonanone** [comment]
The requirement has been updated again. This time it should appear just completing Throwing Down.
