### ISSUE TITLE
Event / Encounter in Blackrock Spire with Lord Victor Nefarius

### ISSUE THREAD

**Issue by Crispybuilt** [dalaranwow/dalaran-wow#90]
Event is working and doable but not 100%, accurate and safe to, could break at any point.

ISSUE 1: All the quotes from the NPC Lord Victor Nefarius are not synced with the actual event.

Lord Victor Nefarius ID - 10162
Warchief Rend Blackhand - 10429

The fight starts with 7 to 8 waves of elite Orcs and Dragonkin, and non-elite whelps. The whelps will tend to stay in the back of the room and frostbolt people, but its not a whole lot of damage. The waves come on a set timer, so if you take too long to kill one wave, the next will come out while your still fighting. 

ISSUE 2: There was no wave of mobs , 7 or 8 and they didn't even run to arena but were simply not spawned. There was one wave of mobs before that  was already waiting inside the cage but they weren't doing anything. (that is wrong, there should be no mobs waiting for you)

Door has to open and send wave of mobs periodically then close up. After the mobs are defeated, door has to open after 20-30 seconds. Then another wave starts. After all the weaves are over, Lord Victor Nefarius will send down his Warchief Rend Blackhend to fight your group on the dragon.

Issue: The Door opened without spawning any mobs 5-6 times

==================================================

Your combat flag does drop between waves if you go fast enough, giving you a chance to drink and rez the dead.

==================================================

Eventually Nefarious will send down Rend to deal with you personally. Rend comes out on his mount, Gyth, and stays there for the first 50% or so. 

ISSUE 3 - URGENT HOT FIX - Once Gyth gets below 50%, Rend will fall off. - 
The problem is he doesn't jump down off the dragon after 50% but it jumps down between 2 - 10% which is wrong. He should force jump down on 50% so you can kill him so the next gate can be opened.

More info how the event should work:
http://www.wowhead.com/npc=10429#comments

How event should work: http://www.youtube.com/watch?v=W4DFETlnRqg

**Comment by Golganeth** [comment]
If you kill Gyth too fast, Rend will not spawn at all. Workaround: 
- DPS Gyth slowly until he reaches a really low amount of HP (4-5%). Rend Blackhand will then dismount and you can kill him so that doors open.

**Comment by Rushor** [comment]
> If you kill Gyth too fast, Rend will not spawn at all. Workaround: 

thats even a retail issue :)

**Comment by Rushor** [comment]
4192c38ae226e61d840b69cd82380083c3c01f6e

point 2 + 3 fixed
- rend will now always be summoned
- added some attackwaves after the door was activated (they will also attack the players)

**Comment by Golganeth** [comment]
It takes a while between the last wave of npcs and Gyth spawn.
If you nuke Gyth, Rend will not appear and the door to continue with the dungeon won't open. Still an issue.

**Comment by Rushor** [comment]
63ccc6bae532324927d7554441e03f953e4ab1ed
- should spawn now after nuking
- concerning the wavetimer, i think that's blizzlike because rend and gyth have to walk all the way from nef down to the area

**Comment by Golganeth** [comment]
Rend will always spawn now, doesn't matter if you oneshot Gyth.

The event itself still requires a few polishments, such as proper timing and sync between quotes / NPC waves / portcullis.

> Low priority
