### ISSUE TITLE
Asric and Jadaar

### ISSUE THREAD

**Issue by riddermark** [dalaranwow/dalaran-wow#905]
NPCs Involved:
http://www.wowhead.com/npc=31898
http://www.wowhead.com/npc=31899

Issue:
- They should have scripted conversation every 2 minutes.

Source:
http://www.wowwiki.com/Asric

Conversations:
---
Asric says: To your health, windbag. 
Jadaar says: And to yours, brat. 
(They both take a swig from their mugs.) 
/emote drink 
add mug objects on drink
.
Asric says: Now comes our chance at redemption, Jadaar. We could become heroes through this tournament! 
Jadaar says: I don't know. I am uncertain this is the proper vehicle to heroism. 
Asric says: What could be holding you back? You're hale, hearty... missing an eye perhaps, but that shouldn't keep you from competing! 
Jadaar says: I dislike elekks. Strongly. 
Asric says: Ah. That might be a problem.
-.
Jadaar says: Why aren't you competing? 
Asric says: I had a... situation some time back with one of the individuals now heading up the Sunreavers here. A falling out, if you will. 
Asric says: Needless to say, when I walked into the pavilion there was something of an altercation. 
Jadaar says: They refused to train you? 
Asric says: He suggested I do something else with the lance, instead. It's not my place to repeat vulgarities.
-.
Jadaar says: You realize, of course, that we would likely have to joust one another should we enter the tournament. 
Asric says: There is no doubt in my mind you'd lose. Speed and wit triumphs over brute strength and bullheadedness any day of the week. 
Jadaar says: Bullheadedness? It is my perseverance that has gotten us this far, dandy. You wouldn't last five seconds. 
Asric says: Typical empty boasting. Still, the stables are rather distant and the drinks here are decent enough. 
Jadaar says: I hear those lances are rough-hewn, too. I'm no fan of splinters. 
Asric says: Just as well.
-.
Jadaar says: If we do succeed here, you realize what comes next. 
Asric says: The Citadel, correct? Facing the Lich King's most powerful minions. 
Jadaar says: The two of us against the vast undead sea. 
Asric says: Indeed. 
Jadaar says: ...perhaps we should seek our fortune somewhere less likely to be fatal. 
Asric says: Discretion is the better part of valor, after all.

**Comment by jonanone** [comment]
Conversation between both characters has been added. This update will be applied to the live realm soon.
