### ISSUE TITLE
Horde Leaders Argent Event

### ISSUE THREAD

**Issue by riddermark** [dalaranwow/dalaran-wow#908]
At 10th minute of every hour:
- Thrall, Garrosh Hellscream, and 4 Kor'kron Elites arrive:
http://www.wowhead.com/npc=4949 (Thrall)
http://www.wowhead.com/npc=35372 (Garrosh)
http://www.wowhead.com/npc=35460 (Elites)

Other NPCs involved:
http://www.wowhead.com/npc=35361 (Highlord Tirion)
http://www.wowhead.com/npc=35501 (Herald Beluus)

My routes map:
http://i.imgur.com/oUcUqhK.jpg 
(also includes NPC spawn and location points)

NPCs ROUTE:
I edited this map of the tournament grounds to show you their supposed Route. Note that there is some room for improvisation before they reach the "conversation spot" as there's no data about it - they can take the longer or the shorter way - your call.
http://i.imgur.com/oUcUqhK.jpg (Please save the image I don't know how long it will be hosted)

FIRST They are announced by this NPC as they spawn:
http://www.wowhead.com/npc=35501
- yells: The Warchief of the Horde, Thrall, and Overlord Garrosh Hellscream have arrived upon the tournament grounds! Clear the way to the entrance!

THEN they start their Route (as I so masterfully drawn on the map)
- Thrall, Garrosh and their escort appear from inside the Sunreaver Pavilion and walk along the path following the Ring of Champions. Here, they stop between the Ironforge and Gnomeregan banners and observe.

The following dialogue occurs:
Thrall says: Garrosh, I expect you to control yourself here. I do not want a repeat of the Violet Citadel. 
Garrosh Hellscream says: Pah! That was a show of strength, worthy of a leader. I only regret I did not kill that human before the mage interfered. 
Thrall says: We are guests here, Garrosh, and you will conduct yourself honorably. 
Garrosh Hellscream says: What honor is there in thrashing about with blunted sticks? This is a waste of time.
.
The group proceeds to the western entrance of the Crusaders' Coliseum, where Highlord Tirion Fordring awaits.
.
http://www.wowhead.com/npc=35361 (Tirion)
.
Highlord Tirion Fordring says: Welcome, Warchief Thrall. Overlord Hellscream. 
Thrall says: Thank you for the invitation, Lord Fordring. We look forward to observing these games. 
Garrosh Hellscream says: Speak for yourself, Thrall. 
Highlord Tirion Fordring says: I hope you'll see the merit of these events in time, Garrosh. We cannot win against the Scourge if we continue to war against one another. 
Thrall says: Wise words. 
Garrosh Hellscream says: Words of a fool, you mean. The Horde will destroy the undead without your aid, human, or that of the pompous king.
.
Thrall immediately turns to face Garrosh and rebukes him directly.
(need to script him to turn)
.
Thrall says: Garrosh, enough! 
Highlord Tirion Fordring says: Under my roof, gentlemen, I trust you will behave.
.
Thrall turns back to Tirion.
.
Thrall says: Of course, Tirion. I apologize for his outburst. It will not be repeated.
Garrosh Hellscream says: Bah. 
Highlord Tirion Fordring says: If you will follow me, then.
.
The group then walks in to the coliseum proper and disappears inside.
(they despawn as they near the gates I assume)

NOTE: Please note that I have not selected random NPCs - these are all the CORRECT ones for the event with their respective IDs.

**Comment by Lothloryen** [comment]
Implemented since the Argent Tournament World event was released on Algalon.

Thank you.

**Comment by MrAndersonX** [comment]
Still bugged. The portal doesn't open.
