### ISSUE TITLE
Alliance Leaders Argent Event

### ISSUE THREAD

**Issue by riddermark** [dalaranwow/dalaran-wow#909]
On the 25th minute of every hour:
Varian Wrynn, Jaina Proudmoore, and a few (3-4) Stormwind Royal Guards arrive.
http://www.wowhead.com/npc=35321 (King)
http://www.wowhead.com/npc=35320 (Jaina)
http://www.wowhead.com/npc=35322 (Guards)

Other NPCs involved:
http://www.wowhead.com/npc=35361 (Highlord Tirion)
http://www.wowhead.com/npc=35501 (Herald Beluus)

Route Map with NPC locations:
http://i.imgur.com/oUcUqhK.jpg

FIRST they are announced by Herald Beluus.
: Herald Beluus yells: His Majesty, King Varian Wrynn, and Lady Jaina Proudmoore have touched down upon the tournament grounds! Make way!
.
Varian, Jaina and their escort appear from inside the Silver Covenant Pavilion and walk west towards the Argent Pavilion. Fordring greets them at the entrance to the Coliseum. 
(They spawn from the tent and follow the route I've given on my map)
.
When they reach Tirion the following takes place:
.
King Varian Wrynn says: Tirion. 
Highlord Tirion Fordring says: King Varian, Lady Jaina. Welcome to the tournament. Your place in the coliseum is waiting. 
Lady Jaina Proudmoore says: Thank you. It's the least I can do to support this; we need to stand together. 
King Varian Wrynn says: You ask much of me, Tirion, to sit and watch, trusting the savages to keep themselves in check. 
Highlord Tirion Fordring says: My people are here to ensure they honor the rules of  engagement. It will do your subjects well to see you in the stands. 
Lady Jaina Proudmoore says: I'm sure Thrall will have his people under control... 
King Varian Wrynn says: Perhaps. I doubt the effectiveness of this gambit. We would be better served preparing our armies for the final assault. 
King Varian Wrynn says: But if my presence is required in these games to gain your support in the battle, then I will remain. For now.
.
(emote) Highlord Tirion Fordring nods and gestures for his guests to follow.
.
The group then walks in to the coliseum proper and disappears inside.
(despawn as they enter)

NOTE: I've given the correct NPCs after researching them. Also - ALTHOUGH HOSTILE the NPCs can't attack or be attacked by anyone. Might be done by giving them the argent buff that's applied to players on the argent grounds.

**Comment by Lothloryen** [comment]
Implemented since the Argent Tournament World event was released on Algalon.

Thank you.
