### ISSUE TITLE
Highlord Tirion Fordring Argent Speech

### ISSUE THREAD

**Issue by riddermark** [dalaranwow/dalaran-wow#910]
On the purpose of the Argent Tournament itself, Highlord Tirion Fordring makes the following announcement from the stage to the east of the Ring of Champions at the top of every hour. (means at every round hour, 1 pm, 2pm etc.)

Correct NPC:
http://www.wowhead.com/npc=35361 (Highlord Tirion)
Other NPCs involved:
http://www.wowhead.com/npc=35501 (Herald Beluus)

Map:
http://i.imgur.com/oUcUqhK.jpg
I have noted the place where he holds the speech.

HERALD:
5 Minutes before the speech. That would be 55 minute of every hour, he is announced by Herald Beluus as follows:
: Herald Beluus yells: Highlord Tirion Fordring approaches the stage to address those gathered upon the tournament grounds! Make way to the stage area to attend him!

IMPORTANT: The matter of his spawning, route, despawning is unknown to me. I implore you not to get lazy and script him coming from somewhere, climbing the stage and when he's done - getting off it and then walking away as he despawns.

Speech as from: 
http://www.wowwiki.com/Argent_Tournament

Combatants of the Alliance and Horde! You are welcome under the banner of the Argent Crusade.
.
To the south lies our goal. We will march to the Citadel and cut out the heart of the Scourge where it dwells. 
.
But this is no task to be taken lightly. 
.
A massive attack with every able-bodied man would end in needless slaughter. Every soldier lost would rise as the enemy. Azeroth would be left defenseless against the undead threat. 
.
Instead, we require a small, concentrated strike force for the attack to succeed. For that reason, we have created the Argent Tournament. 
.
Within these walls, you will be tested. Your skill in combat will be matched against the fiercest dangers Northrend has to offer under the watchful eyes of your leaders. 
.
Your prowess, your might, and your cunning will be under close watch. These games will determine the best Azeroth has to offer. 
.
The victors will take their rightful place in the assault upon the Citadel. We will stand together in the face of evil, and Arthas WILL fall!

NOTE: I have put dots between the lines which seperate what I believe to be each seperate bubble. No idea if this is voiced or just /yelled. I'd bet on the latter.

**Comment by Lothloryen** [comment]
Implemented since the Argent Tournament World event was released on Algalon.

Thank you.
