### ISSUE TITLE
Quest: Electro-Shock Goodness

### ISSUE THREAD

**Issue by Jazex** [dalaranwow/dalaran-wow#913]
http://www.wowhead.com/quest=10411/electro-shock-goodness

Once you have used the potion and you attack either a Seeping Sludge or a Void Waste, they should split up into 6-10 Seeping Slugdge Globules / Void Waste Globules.

However instead of several of those spawning, the Seeping Sludge / Void Waste just turns into one of the globules itself (or it spawns only 1). 

Seeing as how the quest requires you to kill 30 of each, this makes the quest not at all worthwhile.

**Comment by Demlock** [comment]
Confirmed

**Comment by DrFuler** [comment]
18/12/2015: Still bugged.

As pointed out, it is doable but it is a pain in the ass, since it spawns only 1 of the 30 mobs you need.

**Comment by jonanone** [comment]
Void Wastes and Seeping Sludges now have a chance to split in globules when you hit them with the Electro-Shock Therapy buff on. The fix will be applied to live realm soon.
