### ISSUE TITLE
Quest: On Nethery Wings

### ISSUE THREAD

**Issue by Jazex** [dalaranwow/dalaran-wow#914]
http://www.wowhead.com/quest=10438/on-nethery-wings

You are mounted up on a dragon, and you have to drop bombs to kill a Void Conduit while flying around.

However for you to be able to drop a bomb you have to be close enough to the Void Conduit, and that is only for a couple of seconds during the flight. I've tried several times while spamming the bomb, but I never get enough bombs off to kill the Void Conduit since the bomb has a 1 second cooldown. In the end you fly back to where you got picked up by the mount, and if you didn't kill it the Void Conduit will be reset to full hp.

I think there is something wrong with the range to the Void Conduit while flying, it's close enough only for a few seconds during the reasonably long flight. You simply can't get enough bombs off to kill the NPC in time.

**Comment by ashido96** [comment]
Currently the quest item always tells you that you have to be closer to manaforge ultris even if you are standing in the exact center.

**Comment by MrAndersonX** [comment]
Confirmed - bugged.

**Comment by wwrpg** [comment]
Doesn't appear to be bugged anymore. I was able to do this quest today. I flew my own mount to the top of Ultris and there was the Void Conduit. Kept clicking the quest Phase Disrupter until it died and got quest complete.

**Comment by jonanone** [comment]
The Void Conduit should die almost on the first hit with the spell, so The Void Conduit now gives quest credit on spell hit. The fix will be applied to live realm soon.
