### ISSUE TITLE
Quest: Last Rites

### ISSUE THREAD

**Issue by Jazex** [dalaranwow/dalaran-wow#919]
http://www.wowhead.com/quest=12019/last-rites#comments

Sometimes it works, but sometimes it doesn't.

Sometimes, after you kill Valanar, the script does move on.. but then it stops when Leryssa says 'Thassarian, you're alive!'

Then Thassarian just keeps sitting there and doesn't do his follow up line, the script has ended. Because the script has to complete for you to be able to hand in the quest, even though you completed the quest you can't hand it in.

This happened for me 2 out of 3 times.

Edit: Also, once you do complete the quest (or don't, doesn't really matter) you can't use the portal on the platform to teleport you down. Since the portal is broken, the only way to get down is to.. jump down and kill yourself. (It actually has worked for me once, but after that I didn't work anymore. Seeing as to how I had to do this several times I still had to jump down several times instead)

**Comment by wwrpg** [comment]
Confirmed quest is still broken.
The portal works for me, but Thassarian just keeps sitting after Leryssa talked, so I can't turn in the quest.
I was able to kill Valanar and get the quest complete, just can't turn it in.

**Comment by Lothloryen** [comment]
It should be corrected already, after the next scheduled maintenance.

**Comment by Raulfin** [comment]
Not working on KT. 2 versions of each NPC (except Arthas, Thassarian, and Talbot) spawn, the 2 Valanars fight each other and only use auto attack, which hits for 650-750 each (7.4k armor). When the event is started the 2 Valanars kill Talbot, preventing the scene from running.

**Comment by TeridanDW** [comment]
From ptr, the quest is completeable but it has some minor issue like missing:
 - emotes
 - orientation of lk
 - position where thassarian runs to
 - wrong movement of the girl (she was running when she should be walking when she enters the scene)
 - few more

Referrence from retail legion from 28.03.2017:
https://www.youtube.com/watch?v=DxMTWt8kfoM&feature=youtu.be
