### ISSUE TITLE
[Warlock] Haunt - Crit damage - heal calc.

### ISSUE THREAD

**Issue by Jazex** [dalaranwow/dalaran-wow#920]
http://www.wowhead.com/spell=48181/haunt#comments

(This is the link for the cata version, it has changed though)

Description: 

'You send a ghostly soul into the target, dealing 465 to 544 Shadow damage and increasing all damage done by your Shadow damage-over-time effects on the target by 20% for 12 sec. When the Haunt spell ends or is dispelled, the soul returns to you, healing you for 100% of the damage it did to the target.'

Haunt doesn't heal you for the 100% damage it did to the target if the damage is a CRIT. Say my base damage is 1100 and my crit damage is 2200. Even though I do 2200 damage, the Haunt spell will still only heal me for 1100. 

If you do 2200 damage with a crit, you should be healing for 100% of that damage, that being 2200.

**Comment by Rushor** [comment]
this was fixed with 

https://github.com/TrinityCore/TrinityCore/commit/0a641bace9198f49c82ac1e0276a33d893e990ea
