### ISSUE TITLE
Quest: "Army of the Damned" (13236)

### ISSUE THREAD

**Issue by vexohm** [dalaranwow/dalaran-wow#921]
Starting with an issue with the quests before.

After turning in the completed quest "Field Repairs" (13304), you are supposed to see an immediate phase change, where you see the vehicle repaired and NPC "Matthias Lehner" (32408) apearing nearby, giving you the quest "Do Your Worst" (13305). The phase change happens only when you relog to manually "bump" it though. Otherwise, these two quests work.

The follow-up "Army of the Damned" (13236) has issues. Video of how it worked here:
http://www.youtube.com/watch?v=HqLWmIIoygE&feature=youtu.be
Video of how it should work:
http://www.youtube.com/watch?v=Rimu18yrSx8

Most critical issue (that can make it undoable) is that the "The Prodigal Leader" (npc=31268) spell "Deathstorm" (spell=58912) is able to target and damage the player, who is controling the "vehicle". As it does 25000 shadow damage, it will most likely one-shot the player. I was only able to do it as a tank, leaving the vehicle after each Deathstorm+ghouls raised to get health back up. It probably should reset the ghouls raised count then too?

Also, you are not able to use ability "Soul Cleave" (spell=58913), it tells you "No Target" as seen in video. And ghouls, the army are not fighting.

http://www.wowhead.com/quest=13304 - Field Repairs
http://www.wowhead.com/npc=31868 - Wrecked Demolisher (where you turn the quest in)

http://www.wowhead.com/npc=32408 - Matthias Lehner (at the Demolisher)
http://www.wowhead.com/quest=13305 - Do Your Worst

http://www.wowhead.com/npc=32404 - Matthias Lehner (next instance of him)
http://www.wowhead.com/quest=13236 - Army of the Damned

http://www.wowhead.com/npc=31268 - The Prodigal Leader - the vehicle
http://www.wowhead.com/spell=58912 - Deathstorm
http://www.wowhead.com/spell=58913 - Soul Cleave

**Comment by darkwulfv** [comment]
Quest is still bugged, but can be completed the way @Kolgrim notes.

**Comment by MrAndersonX** [comment]
Confirmed - bugged.

**Comment by DrFuler** [comment]
[08/04/2016] - VERY BUGGED.

I ended up re-logging during the quest, and I got stucked in the quest phase where every other NPC and character is gone from the world. My character simply got stuck in a very lonely world... really need some help.

(I have opened a ticket.)

**Comment by Rushor** [comment]
- the spell 58912 will no longer target player/your vehicle

**Comment by Golganeth** [comment]
Deathstorm deals 25k damage to the player who is controlling The Prodigal Leader. It will not target the vehicle though.

**Comment by Rushor** [comment]
tc fix applied, condition actually can be used for this now

**Comment by Golganeth** [comment]
Deathstorm no longer does damage to the caster / vehicle but I can't seem to be able to complete the quest, can't raise any ghoul nor regen any mana.

**Comment by Rushor** [comment]
loth said the conditions are working fine

**Comment by Golganeth** [comment]
Can't seem to be able to use the ability '2'. The rest seems to work fine, Deathstorm doesn't damage the vehicle/player either.

**Comment by datbunneh** [comment]
Soul Cleave cannot be casted, thus I'm not able to restore mana, thus I cannot cast abilities (as he has no mana restoration on its own). It's bugged and should be reopened.

**Comment by MrAndersonX** [comment]
Yes, Soul Cleave is still bugged. Howevery, you can use your fourth ability to sacrifice your undead minions and gain mana. But if you don't kill enough, you will not have enough to restore your mand and may have to talk to the little boy and transform into Arthas again to have a full mana bar.
So yeah, it is working and doable, but needs improvements.

**Comment by Rushor** [comment]
pls open a new issue with all details to the existing errors/needed improvements

**Comment by MrAndersonX** [comment]
Okay.
