### ISSUE TITLE
Heirloom items getting soulbound

### ISSUE THREAD

**Issue by spurdospore** [dalaranwow/dalaran-wow#922]
Putting enchants which cause items to be normally soulbound will soulbind heirloom items even though they should never get soulbound. This will cause you to be unable to mail the item to an alt on the same account. The items should be mailable and usable by the alt even if the alt does not meet the requirements of being able to benefit from the enchant. In this case the enchant would just appear red on the item tooltip and 0 stats given from the enchant.

http://www.wowhead.com/forums&topic=167524/removing-enchant#p2278386

**Comment by Excizion** [comment]
This is still bugged and you cant mail enchanted items. Says theyre Soulbound.

**Comment by robinsch** [comment]
Can't confirm on PTR.

**Comment by Rushor** [comment]
works fine on ptr
