### ISSUE TITLE
[NPC][The Arcatraz] Arcatraz Sentinel

### ISSUE THREAD

**Issue by vexohm** [dalaranwow/dalaran-wow#925]
Current issue:

1.) There are too many "Arcatraz Sentinel" mobs inside, one particular place has like 6 of them stacked. From what I roughly recal, those there should be like "statues", inactive until something trigers them, but not all at once I think.
2.) They are not casting their Energy Discharge to player in range and does not change their emotestate during they fight (once they get in combat they should act like normal creatures an start meleehits)

From wowhead:
"kazumi on 2008/03/17 (Patch 2.3.3)
There are five Arcatraz Sentinals in the run. One in the hallway at the top of the ramp after the first boss. Two in the room just before the second and third boss. Two in the hallway before the Ethereal pulls just before the last boss."
http://www.wowhead.com/npc=20869 - Arcatraz Sentinel

**Comment by Rushor** [comment]
cannot confirm first issue anymore, there are only 5 of them in the whole instance.

second issue fixed

**Comment by Rushor** [comment]
DB/Creature: Update combatscript for Arcatraz Sentinel

* closes https://github.com/dalaranwow/dalaran-wow/issues/925
* commit: 3998c1c9754019dc1018ef9b983a90fc07e16b60

**Comment by TeridanDW** [comment]
Hello, regarding the issues:
 - 1-st issue - can't confirm that also
 - 2-nd issue - the spell http://wotlk.openwow.com/spell=38831 on hc and spell http://wotlk.openwow.com/spell=36722 on normal are not been casted for some reason
