### ISSUE TITLE
missing attacks on low levels mobs.

### ISSUE THREAD

**Issue by shadow8911** [dalaranwow/dalaran-wow#926]
```
     On my warrior I have 317 hit rating and 3% hit rating talent I attack low level mobs 10-14 and I miss white attacks on them.
```

![wowscrnshot_101813_012611](https://f.cloud.github.com/assets/5713742/1356706/3b174b7c-377e-11e3-9484-82ccaca97d9a.jpg)

**Comment by Rushor** [comment]
works fine for me on ptr

**Comment by shadow8911** [comment]
thanks for report it was a 3 year old post maybe it got a fix during this time.
