### ISSUE TITLE
[Quest][Outland] The Ashtongue Corruptors

### ISSUE THREAD

**Issue by Jazex** [dalaranwow/dalaran-wow#928]
http://www.wowhead.com/quest=10574

The NPC's you have to kill should have a bubble that makes them immune to all harm (and un-aggroable) while all totems remain alive. 

At the moment they are simply attackable like regular NPC's.

Also the totem's shouldn't aggro and attack you like they do now.

**Comment by Rushor** [comment]
http://i.imgur.com/LIzQdOP.jpg
http://i.imgur.com/LIzQdOP.jpg

this was fixed with https://github.com/TrinityCore/TrinityCore/commit/d097f4d0b00610d14fc4e42edf27cfba29ef34d9
