### ISSUE TITLE
Quest: Feeding Arngrim

### ISSUE THREAD

**Issue by babyjebas** [dalaranwow/dalaran-wow#942]
Issue Present: Quest doesn't work properly. Quest item is usable on mob, but has no effect

How it should work: after the quest item is used on the mob and you dps him down to a certain amount a ghost of Arngrim should consume the mob. 

For Further Information:
http://www.wowhead.com/quest=13046

**Comment by Anecho** [comment]
Confirmed.

**Comment by Augur89** [comment]
Fixed and working perfectly, just completed it for the first time!

**Comment by npmusicftw** [comment]
No longer working, at least for me.

**Comment by Reechter** [comment]
Not working for me. Item works, and spawns the disembodied jormungar, and Arngrim appears when it's weakened, but does not consume the mob. The first kill gave credit but no subsequent kills did.

**Comment by Bloodhawk92** [comment]
Confirmed - exactly like Reechter - first kill gives credit but any subseqeunt kills do not.

**Comment by jonanone** [comment]
Now worms will stay in place once they reach 15% health. This way the giant should arrive fine to them and eat them.
The time that the giant take to eat them has been adjusted.

It was taking to long to eat them sometimes so it could glitch. Reducing the time should improve the behaviour.

These updates will be applied to the live realm soon.
