### ISSUE TITLE
[Item] Raw Summer Bas 13756

### ISSUE THREAD

**Issue by Sagrath** [dalaranwow/dalaran-wow#943]
http://www.wowhead.com/item=13756
should be only  from March 21 till September 21 available to be caught. 
what isnt the case on the live server

**Comment by Rushor** [comment]
DB/Fishing: Add timed conditions for fished items 13755/56, 13759/60

* closes https://github.com/dalaranwow/dalaran-wow/issues/943
* commit: 9dd5dc382def7ede5f835fbec19219d1b17bce07

added summerevent (id: 97). it starts 20. March (06:30) till 20 September (06:30).
during this time Summer Brass will be fishable, else  Winter Squid will be fishable.

added night and dayevent.
night (id: 98) from 00:00 till 06:00 > Nightfin Snapper is fishable
day: (id: 99) from 12:00 till 18:00 > Sunscale Salmon is fishable

Else both fishes are fishable.

Note. sometimes you get empty loot. this is a gernal problem with the looting mechanic. Do not pay attention to it while testing or open up an new issue.
