### ISSUE TITLE
Quest: Hot and Cold

### ISSUE THREAD

**Issue by Jazex** [dalaranwow/dalaran-wow#944]
http://www.wowhead.com/quest=12981

When you use the 'Essence of Ice' when you're standing near a Smoldering Scrap, it doesn't always throw the Essence of Ice to the Smoldering scrap. Sometimes it throws the Essence to a mob if one is nearby (Seething Revenant), or at your pet (I've seen several go to my pet, resulting into just losing the Essence) or even at yourself (again, nothing happens except you lose the Essence).

The Essence of Ice should only target nearby Smoldering Scrap patches, not any other targets.

The drop rate for Essence of Ice (ID:42246) from Brittle Revenant (ID:30160) is extremely low. Most when killed aren't dropping anything. Wowhead has the drop rate listed as 69%

**Comment by brainos1** [comment]
im new to this server and just wanted to say that this one quest is responsible for more than a few rage logs by me. please fix the droprate and number of mobs available to obtain the essence of ice. or atleast speed up the respawn rate. I used to do all of the hodir quests daily even after hitting exalted, sadly on this server i won't go back to that zone once get the rep i need. i know this seems like a small problem but its a big deal to people who love this game/x-pac. the whole hodir zone needs a good looking at imo.

**Comment by HK8919** [comment]
It's a huge problem, since "Thrusting Hodir's Spear" quest doesn't work either getting to exalted with Sons of Hodir, which is a necessary reputation to max if you're raiding, is a huge problem.

Today I've lost about 8 Essences of Ice just to myself and one to a revenant.

**Comment by ashido96** [comment]
Confirmed, drop rate is wrong as well as using the essence sometimes just does nothing even with a metal scrap obviously close by.

**Comment by darkwulfv** [comment]
Problem still persist; drop rate is very low, spawns are limited and are slow to respawn, and the item often does nothing, causing it to be wasted.

**Comment by deltafoxnine** [comment]
Still bugged as explained earlier

**Comment by Khronos-** [comment]
Confirmed.

I will have to disagree on drop rates though: Despite wowhead rating the drop rate at 69%, it's currently at 50% drop rate on dalaran-wow, not lower than that, which is not that bad.

What I seem to remember from WotLK days and like @Zantu said, that there was far more Revenants to kill. I'm currently taking 2-3 hours to complete this quest.

**Comment by DrFuler** [comment]
[25/03/2016] - Confirmed: doable but annoying. Specially if there is 2 or 3 other players farming it at the same time.

**Comment by Akkalevil** [comment]
Still bugged as of today, 2 years and a half later.

**Comment by Lothloryen** [comment]
Hello there,

This has been corrected already and it shall be active after the next realm restart.

Thank you.
