### ISSUE TITLE
Quest/NPC: Admiral Barean Westwind [27951]

### ISSUE THREAD

**Issue by Sagrath** [dalaranwow/dalaran-wow#947]
http://www.wowhead.com/npc=27951
- He should cast Protection Sphere on him self when entering combat
  After you kill Abbendis he walks out of the room with his protective shield, saying "I will see you weaklings in Icecrown... if you live that long!"

**Comment by NotBadGuy** [comment]
Quest can be completed if you deal enough damage and/or keep the threat on you. I am unsure if you have to deal enough damage or simply have enough threat though, but in either case I received a credit for it.

**Comment by jonanone** [comment]
I've just tried this today and it worked fine so maybe someone should test it again just in case.

**Comment by Rushor** [comment]
This was fixed with: 0594b1d838d86ad3c8fb229a33d0f34f22c9aa69

DB/SAI: New Hearthglen Fixes

Several missing texts for creatures in New Hearthglen

Also scripts Admiral Barean Westwind (Dragonblight version)
