### ISSUE TITLE
Quest: Ruthless Cunning 9927

### ISSUE THREAD

**Issue by Sagrath** [dalaranwow/dalaran-wow#952]
http://www.wowhead.com/quest=9927/
Place Warmaul Ogre Banner on top of a fallen Kil'sorrow agent. 
Players are able to place the banner anywhere no condition for area nor Kil'sorrow agent corpse
http://www.wowhead.com/item=25552

**Comment by Tarpor** [comment]
Still being trolled with daily in various places. ToC entrance, Dalaran bank, Orgrimmar AH, etc.

**Comment by Lothloryen** [comment]
Hello,

This issue will be solved after the next server restart.

Thank you.
