### ISSUE TITLE
Dispersion II

### ISSUE THREAD

**Issue by Carhar** [dalaranwow/dalaran-wow#957]
Opening this one again because i didnt explain myself as i should. I said snare instead of dazed effects.
Try to test dispersion while dazed, and check if it gets removed or if you get immune to it. I have tried many times and it did not remove a single time. 
Ps: by checking previous priest reports, i can see this was already reported once and apparently got fixed, but just test it now again.

**Comment by robinsch** [comment]
Can't confirm. Tested with Shield Bash Daze and it was correctly remove from the Priest.
