### ISSUE TITLE
Zul'Gurub: Bloodlord Mandokir

### ISSUE THREAD

**Issue by Crispybuilt** [dalaranwow/dalaran-wow#963]
**NPC: Bloodlord Mandokir** *(ID:11382)*

- **Issue present:** After a wipe, the **Bloodlord Mandokir** together with **Vilebranch Speaker** *(ID:11391)* (he is used to trigger the encounter once killed) doesn't reset properly. They both have to respawn at the original place so the player can attempt the boss again.

- **How it should work:** Both NPCs should respawn instantly after a wipe on Bloodlord Mandokir.

________

http://www.wowhead.com/npc=11382/
http://www.wowwiki.com/Bloodlord_Mandokir_(original)

**Comment by Torrigan** [comment]
Still persists

**Comment by SadhuArch** [comment]
The reported issue still persists. But I also wanted to report a very minor one.

At the moment he is yelling **"I'm keeping my eye on you, player!"**. But he is supposed to yell **"player! I'm Watching you!"**

**Comment by robinsch** [comment]
On PTR. @SadhuArch Please open a new issue with proofs.

**Comment by Rushor** [comment]
from: https://github.com/dalaranwow/dalaran-wow/issues/3734

> After a wipe, Bloodlord Mandokir (ID:11382) is supposed to position himself where the Vilebranch Speaker (ID:11391) was prior to killing him to trigger the encounter. The boss has to reset and place himself below the stairs.

going to revert this and add "position himself where the Vilebranch Speaker (ID:11391) was prior to killing him to trigger the encounter" in his script
