### ISSUE TITLE
Quest: Free Your Mind

### ISSUE THREAD

**Issue by Jazex** [dalaranwow/dalaran-wow#966]
http://www.wowhead.com/quest=12893

You have to use the Sovereign Rod on the corpses in order to 'Break them from the Lich King's will'. Now however you just get the complete after killing the creatures (Vile, The Leaper and Lady Nightswood).

You should get the complete after you turn them, so after you used the Sovereign Rod on their corpse.

**Comment by deasease** [comment]
well 1st of all i tought it wont work as i found vile and lady dead but corpse attacked me, after i died they turned abit live and i killed them and used rod, yes it works just a bit buggy

**Comment by Lothloryen** [comment]
Working as it should now, thank you.
