### ISSUE TITLE
Quest: Let Them Eat Crow

### ISSUE THREAD

**Issue by jerkyjosh** [dalaranwow/dalaran-wow#979]
When you summon the plague hound they do not show up as a pet and do not follow you. You can still complete the quest, you just have to range hit the crows and collect the meet then bring them to the hound.

Poor Cripple Plague Hound...

**Comment by jonanone** [comment]
Hungry Pleguehound now will follow its invoker. It cannot be invoked when there is another Plaguehound nearby.

These updates will be applied to the live realm soon.
