### ISSUE TITLE
Misplaced iridescent\blue pearls drop.

### ISSUE THREAD

**Issue by highness** [dalaranwow/dalaran-wow#981]
I think the drops are swapped up or something.

Normally, Iridescent Pearls (http://wotlk.openwow.com/item=5500) should drop from Thick-Shelled Clams (http://wotlk.openwow.com/item=5524), Big-mouth Clams (http://wotlk.openwow.com/item=7973) and Giant Clams (http://wotlk.openwow.com/object=19018).
Blue Pearls (http://wotlk.openwow.com/item=4611#contained-in-object) should drop from Giant Clams (http://wotlk.openwow.com/search=giant+clam#objects) only. It's a quest-only item, useless otherwise.

Now, here comes a tricky thing. Drops WERE swapped on retail at some point (since you don't have to craft any wands there anymore, so all these pearls are just for vendoring now); currently, wowhead won't show up that Iridescent Pearl dropped from Thick-Shelled Clam if you look at pearl's page.

But, on clam's page, wotlk drops are intact: http://www.wowhead.com/item=5524#contains

Here you actually can see that Thick-Shelled Clams are supposed to drop Tangy Clam Meat, Iridescent Pearls and Small Lustrous Pearls.

Now, let's have a peak in my inventory:

![1](https://f.cloud.github.com/assets/5235996/1631268/a5fd79f0-5760-11e3-80ef-5a96efd7319e.jpg)

Here, as you can see, I have 12 Thick-Shelled Clams, which came as spoils from my holy crusade against evil Southshore turtles, nagas and murlocs. Also, you can see that I already have like 12 Blue Pearls from my previous endeavours (all dropped from similar clams, and maybe even from the lower-level ones too).

Let's try to open them.

![2](https://f.cloud.github.com/assets/5235996/1631283/e6e5d9b2-5760-11e3-9418-77610f17d199.jpg)

Ta-daa! 3 more blue pearls for me, also some Tangy and regular Clam Meat.

It's kinda meh, because Iridescent Pearl is actually required to craft a Runed Golden Rod (http://wotlk.openwow.com/spell=13628). Drops from Big-mouth Clams are probably intact (ocassionaly I see some lonely Iridescent Pearl at AH for meager 80g or so), but that means that I'm stuck at 150 Enchanting till ~lvl 45, at which I can freely roam Tanaris.

Please, look into it.

Thanks.

**Comment by Rushor** [comment]
dropchance will be changed to this:

```sql
-- Thick-Shelled Clams
DELETE FROM `spell_loot_template` WHERE `Entry`=58168;
INSERT INTO `spell_loot_template` (`Entry`, `Item`, `Reference`, `Chance`, `QuestRequired`, `LootMode`, `GroupId`, `MinCount`, `MaxCount`, `Comment`) VALUES 
(58168, 5498, 0, 15, 0, 1, 1, 1, 1, 'Thick-Shelled Clams - Small Lustrous Pearl'),
(58168, 5500, 0, 26, 0, 1, 1, 1, 1, 'Thick-Shelled Clams - Iridescent Pearl'),
(58168, 5504, 0, 45, 0, 1, 1, 1, 2, 'Thick-Shelled Clams - Tangy Clam Meat');
```

**Comment by Rushor** [comment]
DB/Item: Thick-Shelled Clams - Update spellloot

* closes https://github.com/dalaranwow/dalaran-wow/issues/981
* commit: b0f59e1cd16e4baa4e5b50270e264e68d772dd9e

The issue was fixed by a developer and will now be tested on the Public Test Realm (PTR). The changes/fixes will be applied with the NEXT changelog on the liverealm.
This means that the issue exists in game at the moment i wrote this message.
Only once the issue was marked with "Fixed - On Live Server", you can find the fix on you server.
Please watch http://www.dalaran-wow.com/news/ to see when the changelog and the fix was applied.
