### ISSUE TITLE
[Quest][Classic] Screecher Spirits

### ISSUE THREAD

**Issue by Blackeight** [dalaranwow/dalaran-wow#989]
Hello, I believe this quest must be completed in Feralas but I completed it in Tanaris and I don't think it's supposed to be like that.

Just for clarification: "Screecher Spirits" quest comes with quest item provided - "Yeh'kinya's Bramble". - http://www.wowhead.com/quest=3520/screecher-spirits

I was doing "The Scrimshank Redemption" quest in the Gaping Chasm in Tanaris and was killing Hazzali Wasps to clear my way. Suddenly I decided to use the quest item "Yeh'kinya's Bramble" on their dead bodies and I got "Screecher Spirits" completed...

I didn't know that would happen.. I even did it with the idea of completing "The Scrimshank Redemption" :-)

Thank you for reading

**Comment by Rushor** [comment]
fixed long time ago https://github.com/TrinityCore/TrinityCore/commit/3de1714350f1f83ff880ee927523aabfb5731475

already fixed on PTR.
