### ISSUE TITLE
Quest: Survey Alcaz Island

### ISSUE THREAD

**Issue by Crispybuilt** [dalaranwow/dalaran-wow#99]
**Quest Survey Alcaz Island - 11142**

- **Issue:** After turning in the quest and completing it there should be a little bit of roleplay and speech from Jaina Proudmoore, there is nothing here.

This is what she should say according to WoWhead:

*"I had arranged for a secret summit between Warchief Thrall and King Wyrnn, here in Theramore.*
*The king was to travel here by ship, in secret. But the ship never arrived, and King Wrynn disappeared.*
*Your help enabled us to connect the Defias to the mastermind behind the abduction, Onyxia, who was posing as a member of the royal court.*
*Meanwhile, the king managed to escape his captors, and returned to Stormwind to deal with Onyxia.
I will send word that you have discovered the link to the Defias. I was a fool to think them broken with the defeat of Edwin Vancleef, and King Wrynn will want to make an example of all who remain."*

**Comment by Rushor** [comment]
8a914cabf389b84bbde7f0e2010f9035a5dda458
- added the textevent upon reward of 11142

**Comment by Golganeth** [comment]
Lady Jaina drops below the ground on reward, could just be related to PTR maps though. Quotes work fine regardless

**Comment by Rushor** [comment]
http://i.imgur.com/CiC9oFo.jpg yeah related to the maps probably, it's working fine with new extracted maps and vmaps

**Comment by ImprezaWoW** [comment]
Tried both in-game and PTR, even with the prerequisite[ Jaina Must Know](http://wotlk.openwow.com/quest=11141) complete, seems like [Cassa Crimsonwing](http://wowwiki.wikia.com/wiki/Cassa_Crimsonwing) does not have the dialogue function to progress the quest - you can only get her monlogue about hoping to run a Gryphon stable one day.

**Comment by Golganeth** [comment]
Players can go there manually to complete the quest.

**Comment by Rushor** [comment]
85116154750670d7b678595363164a6df1b06d6d
- you can now talk to her in order to get the flight
