### ISSUE TITLE
Quest: Gyromast's Revenge

### ISSUE THREAD

**Issue by Jazex** [dalaranwow/dalaran-wow#995]
http://www.wowhead.com/quest=2078/

You have to escort the first mate robot to Gelkak Gyromast after using the key script on him. Once you reach Gelkak Gyromast it will engage you and you'll have to kill it to get the completion credit.

Once it reaches Gelkak Gyromast by following you it WILL turn hostile, however in the next second it will 'run away' despawning almost immediately. As I was a high lvl when I did this I was still able to kill it within that one second (I had to retake the quest 2 times though, didn't expect it to disappear at first). However any low lvl will not be able to kill it in time the way it is right now.

**Comment by Rushor** [comment]
long time ago fixed with https://github.com/TrinityCore/TrinityCore/commit/3009bb48088eda7928b5be89cf6823527e601cae
